[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA Catch-all – alle Routen auf index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
