// 🔥 KÖRPER & BIOLOGIE – Erwachsene
export default [
  {q:"Wie viele Liter Speichel produziert ein Mensch pro Tag?",a:1.5,unit:"Liter",hint:"Speichel hilft bei der Verdauung und schützt Zähne vor Bakterien.",emoji:"💧"},
  {q:"Wie viele Mal schlägt das menschliche Herz pro Tag?",a:100000,unit:"Mal",hint:"Das entspricht etwa 70 Schlägen pro Minute über 24 Stunden.",emoji:"❤️"},
  {q:"Wie lang sind alle Blutgefäße eines Menschen zusammen in km?",a:100000,unit:"km",hint:"Das entspricht der 2,5-fachen Entfernung zum Mond.",emoji:"🩸"},
  {q:"Wie viele Haare verliert ein Mensch durchschnittlich pro Tag?",a:100,unit:"Haare",hint:"Ein gesunder Kopf hat ~100.000 Haare – der Verlust ist normal.",emoji:"💈"},
  {q:"Wie viele Knochen hat ein neugeborenes Baby?",a:270,unit:"Knochen",hint:"Erwachsene haben nur 206 – viele Knochen wachsen zusammen.",emoji:"🦴"},
  {q:"Wie viele m² Oberfläche hat die menschliche Lunge?",a:70,unit:"m²",hint:"Das entspricht etwa der Größe eines Tennisplatzes.",emoji:"🫁"},
  {q:"Wie viele km Nerven hat ein Mensch im Körper?",a:75,unit:"km",hint:"Nervensignale können mit bis zu 400 km/h übertragen werden.",emoji:"⚡"},
  {q:"Wie viel Prozent des Körpergewichts macht Blut aus?",a:8,unit:"%",hint:"Bei 75 kg sind das etwa 6 Liter Blut.",emoji:"🩸"},
  {q:"Wie viele Bakterien leben auf der Haut eines Menschen (Milliarden)?",a:1800,unit:"Milliarden",hint:"Die meisten davon sind harmlos oder sogar nützlich.",emoji:"🦠"},
  {q:"Wie viele Liter Blut pumpt das Herz pro Minute in Ruhe?",a:5,unit:"Liter",hint:"Bei Belastung kann es bis zu 25 Liter pro Minute sein.",emoji:"❤️"},
  {q:"Wie viele Eizellen hat eine Frau bei der Geburt?",a:1000000,unit:"Eizellen",hint:"Bis zur Pubertät sind es nur noch ca. 300.000.",emoji:"🔬"},
  {q:"Wie viele Millionen Spermien produziert ein Mann pro Tag?",a:300,unit:"Millionen",hint:"Das sind ~1500 neue Spermien pro Sekunde.",emoji:"🔬"},
  {q:"Wie lang ist der Dünndarm eines Erwachsenen in Metern?",a:6,unit:"Meter",hint:"Zusammen mit dem Dickdarm ergibt das über 8 Meter Darm.",emoji:"🌀"},
  {q:"Wie viel Gramm wiegt das menschliche Gehirn?",a:1400,unit:"Gramm",hint:"Trotz 2% Körpergewicht verbraucht es 20% unserer Energie.",emoji:"🧠"},
  {q:"Wie viele Liter Luft atmet ein Mensch pro Tag ein?",a:11000,unit:"Liter",hint:"Das entspricht 15–20 Atemzügen pro Minute.",emoji:"💨"},
  {q:"Wie viele Stunden verbringt ein Mensch pro Jahr auf der Toilette?",a:92,unit:"Stunden",hint:"Im Leben summiert sich das auf fast 3 Jahre.",emoji:"🚽"},
  {q:"Wie viele Milliliter fasst der Magen eines Erwachsenen maximal?",a:1500,unit:"ml",hint:"Im leeren Zustand hat er nur etwa 75 ml Volumen.",emoji:"🫃"},
  {q:"Wie oft blinzelt ein Mensch pro Minute?",a:15,unit:"Mal",hint:"Das macht über 10.000 Mal pro Tag.",emoji:"👁️"},
  {q:"Wie schnell wachsen Fingernägel pro Monat in mm?",a:3,unit:"mm",hint:"Fußnägel wachsen etwa halb so schnell.",emoji:"💅"},
  {q:"Wie viel Prozent des Körpers besteht aus Wasser?",a:60,unit:"%",hint:"Beim Baby sind es 75%, im Alter sinkt der Wasseranteil.",emoji:"💧"},
  {q:"Wie viele Muskeln braucht man zum Lächeln?",a:12,unit:"Muskeln",hint:"Zum Stirnrunzeln braucht man angeblich mehr – bis zu 11.",emoji:"😁"},
  {q:"Wie lang ist die DNA in einer Zelle in Metern?",a:2,unit:"Meter",hint:"Alle DNA zusammen wäre 70x die Strecke Erde-Sonne.",emoji:"🧬"},
  {q:"Wie viele Liter Magensäure produziert der Magen täglich?",a:1.5,unit:"Liter",hint:"Der pH-Wert liegt bei 1-2 – ähnlich wie Batteriesäure.",emoji:"⚗️"},
  {q:"Wie viele Kalorien verbrennt das Gehirn pro Tag?",a:300,unit:"kcal",hint:"Das sind 20% des gesamten Kalorienverbrauchs in Ruhe.",emoji:"🧠"},
  {q:"Wie viele Schweißdrüsen hat ein Mensch am ganzen Körper?",a:3000000,unit:"Drüsen",hint:"Am dichtesten sitzen sie an Fußsohlen und Handflächen.",emoji:"💦"},
  {q:"Wie lang ist der längste Muskel im Körper (Sartorius) in cm?",a:60,unit:"cm",hint:"Er verbindet Hüfte und Knie diagonal.",emoji:"🦵"},
  {q:"Wie viele Gramm wiegt eine durchschnittliche Brust?",a:500,unit:"Gramm",hint:"Der Fettanteil variiert stark je nach Körbchengröße.",emoji:"👙"},
  {q:"Wie viele Liter Blut pumpt das Herz pro Tag?",a:7200,unit:"Liter",hint:"Das Herz schlägt ~100.000 Mal täglich.",emoji:"❤️"},
  {q:"Wie viele Zellen stirbt der Körper pro Sekunde ab?",a:3800000,unit:"Zellen",hint:"Gleichzeitig werden ständig neue Zellen gebildet.",emoji:"🔬"},
  {q:"Wie viele km Sehnen und Bänder hat ein Mensch?",a:900,unit:"Meter",hint:"Bänder verbinden Knochen, Sehnen Muskeln mit Knochen.",emoji:"🦴"},
];
