// 🌍 GESCHICHTE & KURIOSITÄTEN – Erwachsene
export default [
  {q:"In welchem Jahr wurde das erste Brustimplantat einoperiert?",a:1962,unit:"Jahr",hint:"Timmie Jean Lindsey war die erste Frau weltweit.",emoji:"👙"},
  {q:"Wie viele Frauen hatte König Salomo laut Bibel?",a:700,unit:"Frauen",hint:"Dazu kamen noch 300 Konkubinen.",emoji:"👑"},
  {q:"In welchem Jahr wurde Viagra erfunden?",a:1998,unit:"Jahr",hint:"Ursprünglich als Herzmedikament entwickelt.",emoji:"💊"},
  {q:"Wie viele Millionen Menschen starben beim Schwarzen Tod?",a:50,unit:"Millionen",hint:"Ein Drittel der europäischen Bevölkerung im 14. Jh.",emoji:"💀"},
  {q:"In welchem Jahr wurde die Guillotine in Frankreich abgeschafft?",a:1981,unit:"Jahr",hint:"Letzte Hinrichtung war 1977.",emoji:"⚔️"},
  {q:"Wie viele Jahre war die Berliner Mauer in Betrieb?",a:28,unit:"Jahre",hint:"Von 1961 bis zum Fall am 9. November 1989.",emoji:"🧱"},
  {q:"In welchem Jahr wurde das erste Telefon von Bell patentiert?",a:1876,unit:"Jahr",hint:"Bell erhielt das Patent am 7. März 1876.",emoji:"📞"},
  {q:"Wie viele Arbeiter bauten schätzungsweise die Cheops-Pyramide?",a:20000,unit:"Arbeiter",hint:"Neuere Forschung: bezahlte Arbeiter, keine Sklaven.",emoji:"🏛️"},
  {q:"Wie viele Tonnen Gold sind schätzungsweise im Meer gelöst?",a:20000000,unit:"Tonnen",hint:"Genug für 9 Pfund Gold pro Person auf der Erde.",emoji:"⚱️"},
  {q:"In welchem Jahr wurde die erste Kondom-Fabrik eröffnet?",a:1844,unit:"Jahr",hint:"Nach Goodyears Vulkanisierung von Gummi.",emoji:"💊"},
  {q:"Wie viele Konkubinen hatte Kaiser Qianlong von China?",a:3000,unit:"Konkubinen",hint:"Er regierte von 1735 bis 1796.",emoji:"👑"},
  {q:"Wie viele Seiten hatte die Gutenberg-Bibel?",a:1282,unit:"Seiten",hint:"Gedruckt 1452–1454.",emoji:"📖"},
  {q:"Wie viele Jahre dauerte der Hundertjährige Krieg tatsächlich?",a:116,unit:"Jahre",hint:"Von 1337 bis 1453 – also 116 Jahre, nicht 100.",emoji:"⚔️"},
  {q:"Wie viele Personen wurden beim Hexenprozess von Salem hingerichtet?",a:19,unit:"Personen",hint:"1692 in Massachusetts.",emoji:"🔥"},
  {q:"In welchem Jahr erfand Napoleon die Konservendose?",a:1810,unit:"Jahr",hint:"Für seine Armee – als Dosenöffner gab es noch keinen.",emoji:"🥫"},
  {q:"Wie viele Minuten dauerte der kürzeste Krieg der Geschichte?",a:38,unit:"Minuten",hint:"Der Anglo-Sansibar-Krieg von 1896.",emoji:"⚔️"},
  {q:"Wie viele Jahre saß Nelson Mandela im Gefängnis?",a:27,unit:"Jahre",hint:"Von 1964 bis 1990 auf Robben Island.",emoji:"✊"},
  {q:"In welchem Jahr fand die erste Mondlandung statt?",a:1969,unit:"Jahr",hint:"Apollo 11, 20. Juli 1969.",emoji:"🌙"},
  {q:"Wie viele Millionen Juden wurden im Holocaust ermordet?",a:6,unit:"Millionen",hint:"Einer der dunkelsten Momente der Menschheitsgeschichte.",emoji:"✡️"},
  {q:"In welchem Jahr wurde die Titanic gebaut (Baubeginn)?",a:1909,unit:"Jahr",hint:"Sie sank bei ihrer Jungfernfahrt 1912.",emoji:"🚢"},
  {q:"Wie viele Millionen Menschen starben im Ersten Weltkrieg?",a:20,unit:"Millionen",hint:"Militär und Zivilbevölkerung zusammen.",emoji:"🕊️"},
  {q:"Wie viele Jahre regierte Queen Elizabeth II.?",a:70,unit:"Jahre",hint:"Von 1952 bis zu ihrem Tod 2022.",emoji:"👑"},
  {q:"In welchem Jahr erfand Karl Benz das erste Automobil?",a:1885,unit:"Jahr",hint:"Der Benz Patent-Motorwagen – drei Räder, 0,75 PS.",emoji:"🚗"},
  {q:"Wie viele Sprachen wurde die Bibel übersetzt?",a:3000,unit:"Sprachen",hint:"Mehr als jedes andere Buch der Geschichte.",emoji:"📖"},
  {q:"Wie viele Stockwerke hatte das World Trade Center?",a:110,unit:"Stockwerke",hint:"Die Zwillingstürme wurden am 11. September 2001 zerstört.",emoji:"🏙️"},
  {q:"Wie viele Jahre dauerte der Zweite Weltkrieg?",a:6,unit:"Jahre",hint:"Von 1939 bis 1945.",emoji:"🌍"},
  {q:"In welchem Jahr wurde die erste Atombombe gezündet?",a:1945,unit:"Jahr",hint:"Trinity-Test in New Mexico, 16. Juli 1945.",emoji:"💥"},
  {q:"Wie viele Menschen lebten auf der Erde im Jahr 1800?",a:1000000000,unit:"Menschen",hint:"Eine Milliarde – heute sind es 8 Milliarden.",emoji:"🌍"},
  {q:"Wie viele Mal wurde Napoleon verbannt?",a:2,unit:"Mal",hint:"Erst nach Elba, dann nach St. Helena.",emoji:"🏝️"},
  {q:"In welchem Jahr fiel die Mauer in Berlin?",a:1989,unit:"Jahr",hint:"9. November 1989 – einer der wichtigsten Tage der Geschichte.",emoji:"🧱"},
];
