// 🚀 ASTRONOMIE & PHYSIK – Erwachsene
export default [
  {q:"Wie viele Lichtjahre ist die Andromeda-Galaxie entfernt?",a:2500000,unit:"Lichtjahre",hint:"Sie ist mit bloßem Auge als kleiner Fleck sichtbar.",emoji:"🌌"},
  {q:"Wie viele Grad Celsius beträgt die Oberflächentemperatur der Sonne?",a:5500,unit:"°C",hint:"Im Kern sind es sogar 15 Millionen Grad.",emoji:"☀️"},
  {q:"Wie viele km/s ist die Lichtgeschwindigkeit?",a:300000,unit:"km/s",hint:"Licht braucht ~8 Minuten von der Sonne zur Erde.",emoji:"💡"},
  {q:"Wie viele Erdmassen hat Jupiter?",a:318,unit:"Erdmassen",hint:"Jupiter ist der größte Planet unseres Sonnensystems.",emoji:"🪐"},
  {q:"Wie viele Monde hat Saturn?",a:146,unit:"Monde",hint:"Saturn hat die meisten Monde aller Planeten.",emoji:"🪐"},
  {q:"Wie viele Grad Celsius ist es auf dem Mond nachts?",a:-170,unit:"°C",hint:"Tagsüber sind es +130°C – extreme Temperaturschwankungen.",emoji:"🌙"},
  {q:"Wie viele km beträgt der Durchmesser der Sonne?",a:1392000,unit:"km",hint:"Die Sonne hat 109x den Durchmesser der Erde.",emoji:"☀️"},
  {q:"Wie viele km ist der Mond von der Erde entfernt?",a:384400,unit:"km",hint:"Die Entfernung schwankt zwischen 356.000 und 407.000 km.",emoji:"🌙"},
  {q:"Wie viele Jahre alt ist das Universum (Milliarden)?",a:13.8,unit:"Milliarden Jahre",hint:"Seit dem Urknall vor etwa 13,8 Milliarden Jahren.",emoji:"🌌"},
  {q:"Wie viele km/h bewegt sich die Erde um die Sonne?",a:107000,unit:"km/h",hint:"Das sind etwa 30 km pro Sekunde.",emoji:"🌍"},
  {q:"Wie viele Milliarden Sterne gibt es in der Milchstraße?",a:200,unit:"Milliarden",hint:"Und es gibt Milliarden weitere Galaxien im Universum.",emoji:"⭐"},
  {q:"Wie viele Minuten braucht Licht von der Sonne zur Erde?",a:8,unit:"Minuten",hint:"Genau 8 Minuten und 20 Sekunden.",emoji:"☀️"},
  {q:"Wie heiß ist der Kern der Erde in Grad Celsius?",a:6000,unit:"°C",hint:"Ähnlich heiß wie die Oberfläche der Sonne.",emoji:"🌍"},
  {q:"Wie viele Monate dauert ein Jahr auf dem Mars?",a:24,unit:"Monate",hint:"Ein Marsjahr dauert 687 Erdtage.",emoji:"🔴"},
  {q:"Wie viele Mal größer ist die Sonne als die Erde?",a:1300000,unit:"Mal",hint:"1,3 Millionen Erden würden in die Sonne passen.",emoji:"☀️"},
  {q:"Wie viele Grad Celsius beträgt die Temperatur im Weltall?",a:-270,unit:"°C",hint:"Nahe dem absoluten Nullpunkt von -273°C.",emoji:"❄️"},
  {q:"Wie viele Stunden dauert ein Tag auf der Venus?",a:5832,unit:"Stunden",hint:"Ein Venusjahr ist kürzer als ein Venustag.",emoji:"🪐"},
  {q:"Wie viele Grad Celsius ist die Temperatur auf dem Merkur tagsüber?",a:430,unit:"°C",hint:"Nachts fällt sie auf -180°C.",emoji:"☿"},
  {q:"Wie viele km/h bewegt sich die ISS um die Erde?",a:28000,unit:"km/h",hint:"Sie umkreist die Erde alle 90 Minuten.",emoji:"🚀"},
  {q:"Wie schwer ist ein Kubikzentimeter Neutronenstern in Tonnen?",a:1000000000,unit:"Tonnen",hint:"Neutronensterne sind die dichtesten bekannten Objekte.",emoji:"⭐"},
  {q:"Wie viele km ist ein Lichtjahr lang (Billionen)?",a:9.46,unit:"Billionen km",hint:"Das Licht legt pro Jahr 9,46 Billionen km zurück.",emoji:"💡"},
  {q:"Wie viele Monde hat der Mars?",a:2,unit:"Monde",hint:"Phobos und Deimos – beide sehr klein.",emoji:"🔴"},
  {q:"Wie viele km beträgt der Durchmesser der Erde?",a:12742,unit:"km",hint:"Am Äquator ist sie etwas dicker als an den Polen.",emoji:"🌍"},
  {q:"Wie viele Sekunden braucht ein Objekt im freien Fall aus 100m?",a:4.5,unit:"Sekunden",hint:"Nach der Formel s = ½gt².",emoji:"⬇️"},
  {q:"Wie viele km/h muss eine Rakete fliegen um die Erde zu verlassen?",a:40000,unit:"km/h",hint:"Das ist die Fluchtgeschwindigkeit der Erde.",emoji:"🚀"},
  {q:"Wie viele Astronauten waren bisher auf dem Mond?",a:12,unit:"Astronauten",hint:"Alle 12 waren Amerikaner, bei den Apollo-Missionen.",emoji:"👨‍🚀"},
  {q:"Wie groß ist der Große Rote Fleck auf Jupiter in km?",a:16000,unit:"km",hint:"Ein Sturm, der seit 350 Jahren tobt.",emoji:"🪐"},
  {q:"Wie viele Kelvin ist der absolute Nullpunkt?",a:0,unit:"Kelvin",hint:"Entspricht -273,15°C – kälter geht es nicht.",emoji:"🌡️"},
  {q:"Wie weit ist Alpha Centauri von der Erde entfernt in Lichtjahren?",a:4.37,unit:"Lichtjahre",hint:"Das nächste Sternensystem nach unserem.",emoji:"⭐"},
  {q:"Wie viele Ringe hat Saturn?",a:7,unit:"Hauptringe",hint:"Die Ringe bestehen aus Eis und Gestein.",emoji:"🪐"},
];
