// 🍺 ESSEN & TRINKEN – Erwachsene
export default [
  {q:"Wie viele Kalorien hat ein Big Mac?",a:563,unit:"kcal",hint:"Davon kommen 257 kcal aus dem Fett.",emoji:"🍔"},
  {q:"Wie viele Liter Bier wurden beim Oktoberfest 2023 getrunken?",a:7300000,unit:"Liter",hint:"Das Oktoberfest ist das größte Volksfest der Welt.",emoji:"🍺"},
  {q:"Wie viele Gramm Zucker in einer Dose Cola (330ml)?",a:35,unit:"Gramm",hint:"Das sind etwa 7 Teelöffel Zucker.",emoji:"🥤"},
  {q:"Wie viele Tonnen Schokolade isst Deutschland pro Jahr?",a:900000,unit:"Tonnen",hint:"Weltmeister im Schokoladenkonsum pro Kopf.",emoji:"🍫"},
  {q:"Wie viele Liter Milch braucht man für 1 kg Käse?",a:10,unit:"Liter",hint:"Je nach Sorte 8–12 Liter Milch.",emoji:"🧀"},
  {q:"Wie viele Monate reift ein echter Parmesan mindestens?",a:24,unit:"Monate",hint:"Premium-Parmesan reift bis zu 5 Jahre.",emoji:"🧀"},
  {q:"Wie viele Körner Kaffee braucht man für einen Espresso?",a:50,unit:"Körner",hint:"Ein Kaffeebaum produziert pro Jahr ~500g Kaffee.",emoji:"☕"},
  {q:"Wie viele Liter Wein trinkt ein Franzose pro Jahr?",a:45,unit:"Liter",hint:"Frankreich führt weltweit den Pro-Kopf-Weinkonsum.",emoji:"🍷"},
  {q:"Wie viele kg Pasta isst ein Italiener durchschnittlich pro Jahr?",a:23,unit:"kg",hint:"Italien führt weltweit den Pastakonsum.",emoji:"🍝"},
  {q:"Wie hoch ist der Wasseranteil in einer Gurke in Prozent?",a:97,unit:"%",hint:"Gurken bestehen fast nur aus Wasser.",emoji:"🥒"},
  {q:"Wie viele Liter Kaffee trinken Finnen pro Kopf pro Jahr?",a:12,unit:"kg",hint:"Finnland ist Weltmeister im Kaffeeverbrauch.",emoji:"☕"},
  {q:"Wie viele Gramm Butter enthält ein original Croissant?",a:50,unit:"Gramm",hint:"Der hohe Butteranteil macht die blättrige Textur möglich.",emoji:"🥐"},
  {q:"Wie viele Prozent Fettgehalt hat Gänsestopfleber (Foie Gras)?",a:50,unit:"%",hint:"Eines der kalorienreichsten Lebensmittel.",emoji:"🍴"},
  {q:"Wie viele Liter Wasser braucht man für 1 kg Rindfleisch?",a:15000,unit:"Liter",hint:"Rindfleisch hat den größten Wasserverbrauch aller Nahrungsmittel.",emoji:"🥩"},
  {q:"Wie viele Jahre ist der älteste bekannte Wein alt (Speyer-Wein)?",a:1650,unit:"Jahre",hint:"Die Flasche wurde 1867 in einem römischen Grab gefunden.",emoji:"🍷"},
  {q:"Wie viele Gramm wiegt eine Kaviar-Perle?",a:0.05,unit:"Gramm",hint:"Beluga-Kaviar kostet bis zu 25.000€ pro kg.",emoji:"🐟"},
  {q:"Wie viele Kalorien hat ein Teelöffel Olivenöl?",a:40,unit:"kcal",hint:"Gesund – aber kalorienreich wie alle Fette.",emoji:"🫒"},
  {q:"Wie viele Gramm Salz isst ein Deutscher täglich?",a:10,unit:"Gramm",hint:"Empfohlen werden maximal 6 Gramm.",emoji:"🧂"},
  {q:"Wie scharf ist der Carolina Reaper in Millionen Scoville?",a:2.2,unit:"Mio. Scoville",hint:"Das schärfste Chili der Welt hält den Weltrekord.",emoji:"🌶️"},
  {q:"Wie viele Stunden muss Jamon Iberico mindestens reifen?",a:8760,unit:"Stunden",hint:"Das sind mindestens 3 Jahre.",emoji:"🥩"},
  {q:"Wie viele Würste werden beim Nürnberger Christkindlesmarkt gegessen?",a:2000000,unit:"Würste",hint:"Nürnberger Bratwürste sind die kleinsten deutschen Würste.",emoji:"🌭"},
  {q:"Wie alt kann ein Wein maximal werden und noch trinkbar sein in Jahren?",a:200,unit:"Jahre",hint:"Ein 1811er Château d'Yquem wurde als exzellent bewertet.",emoji:"🍷"},
  {q:"Wie viel kostet Safran pro kg in Euro?",a:10000,unit:"€/kg",hint:"Safran ist das teuerste Gewürz der Welt.",emoji:"🌺"},
  {q:"Wie viele Pizzen werden täglich weltweit gegessen in Millionen?",a:5,unit:"Millionen",hint:"Die USA essen allein 3 Milliarden Pizzen pro Jahr.",emoji:"🍕"},
  {q:"Wie viele Prozent des Wasabis im Restaurant ist echt?",a:1,unit:"%",hint:"99% ist gefälschter Wasabi aus Meerrettich und Farbe.",emoji:"🍣"},
  {q:"Wie viele Kalorien hat ein Glas Rotwein (200ml)?",a:170,unit:"kcal",hint:"Wein hat mehr Kalorien als die meisten denken.",emoji:"🍷"},
  {q:"Wie viele Stunden dauert die Herstellung von echtem Champagner mindestens?",a:12960,unit:"Stunden",hint:"Das sind mindestens 18 Monate Reifung.",emoji:"🥂"},
  {q:"Wie viele Gramm Zucker hat ein Glas Orangensaft (200ml)?",a:20,unit:"Gramm",hint:"Fast so viel wie Cola – oft unterschätzt.",emoji:"🍊"},
  {q:"Wie viele Liter Blut eines Tieres stecken in einer Blutwurst?",a:0.5,unit:"Liter",hint:"Blutwurst ist eines der ältesten Nahrungsmittel.",emoji:"🌭"},
  {q:"Wie viele Minuten pro Tag massiert man Kobe-Rind?",a:60,unit:"Minuten",hint:"Sie werden tatsächlich massiert und mit Bier gefüttert.",emoji:"🥩"},
];
