// 🐾 TIERREICH – Erwachsene
export default [
  {q:"Wie viele kg wiegen die Hoden eines Blauwals?",a:70,unit:"kg",hint:"Der Blauwal ist das größte Tier der Erde.",emoji:"🐋"},
  {q:"Wie oft pro Minute schlägt das Herz einer Maus?",a:600,unit:"Mal",hint:"Je kleiner das Tier, desto schneller das Herz.",emoji:"🐭"},
  {q:"Wie viele Tage trägt ein Elefant sein Junges?",a:645,unit:"Tage",hint:"Fast 2 Jahre – längste Schwangerschaft aller Landsäugetiere.",emoji:"🐘"},
  {q:"Wie viele Liter Milch produziert eine Kuh pro Tag?",a:25,unit:"Liter",hint:"Hochleistungskühe können bis zu 50 Liter täglich geben.",emoji:"🐄"},
  {q:"Wie schwer kann ein Riesenkalmar-Auge in Gramm werden?",a:250,unit:"Gramm",hint:"Das größte Auge im Tierreich – so groß wie ein Fußball.",emoji:"🦑"},
  {q:"Wie viele km/h läuft ein Gepard maximal?",a:112,unit:"km/h",hint:"Er kann diese Höchstgeschwindigkeit nur kurz halten.",emoji:"🐆"},
  {q:"Wie viele Magen hat eine Kuh?",a:4,unit:"Mägen",hint:"Pansen, Netzmagen, Blättermagen und Labmagen.",emoji:"🐄"},
  {q:"Wie hoch kann ein Känguru springen in Metern?",a:3,unit:"Meter",hint:"Und in der Länge sogar bis zu 9 Meter weit.",emoji:"🦘"},
  {q:"Wie schwer wird ein ausgewachsener Gorilla maximal in kg?",a:270,unit:"kg",hint:"Trotz Größe sind Gorillas überwiegend Vegetarier.",emoji:"🦍"},
  {q:"Wie viele Stunden schläft ein Koala pro Tag?",a:22,unit:"Stunden",hint:"Eukalyptus ist schwer verdaulich – daher die Müdigkeit.",emoji:"🐨"},
  {q:"Wie viele km/h kann ein Schwertschwanz-Marlin schwimmen?",a:110,unit:"km/h",hint:"Der schnellste Fisch im Meer.",emoji:"🐟"},
  {q:"Wie lange lebt eine Königin-Biene in Jahren?",a:5,unit:"Jahre",hint:"Arbeiterinnen leben im Sommer nur 6 Wochen.",emoji:"🐝"},
  {q:"Wie viele Zähne hat ein erwachsenes Krokodil?",a:66,unit:"Zähne",hint:"Krokodile erneuern ihre Zähne bis zu 50 Mal im Leben.",emoji:"🐊"},
  {q:"Wie viele Eier legt eine Königin-Termite pro Tag?",a:30000,unit:"Eier",hint:"Die produktivste Mutter im Insektenreich.",emoji:"🐜"},
  {q:"Wie viele km kann ein Polarfuchs in einer Nacht zurücklegen?",a:40,unit:"km",hint:"Polarfüchse sind unglaublich ausdauernd.",emoji:"🦊"},
  {q:"Wie viele Liter Blut hat ein ausgewachsener Elefant?",a:400,unit:"Liter",hint:"Das Elefantenherz wiegt allein bis zu 30 kg.",emoji:"🐘"},
  {q:"Wie viele Mal kann ein Specht pro Sekunde hämmern?",a:20,unit:"Mal",hint:"Sein Gehirn ist durch Spezialanpassungen geschützt.",emoji:"🐦"},
  {q:"Wie schwer ist das schwerste Vogelei (Strauß) in kg?",a:1.35,unit:"kg",hint:"Strauße legen die größten Eier aller lebenden Vögel.",emoji:"🥚"},
  {q:"Wie lange kann ein Delphin den Atem anhalten in Minuten?",a:15,unit:"Minuten",hint:"Delfine schlafen mit einer Gehirnhälfte.",emoji:"🐬"},
  {q:"Wie viele Jahre kann ein Grönlandwal leben?",a:211,unit:"Jahre",hint:"Das langlebigste Säugetier der Erde.",emoji:"🐳"},
  {q:"Wie schwer ist die Zunge eines Blauwals in kg?",a:2700,unit:"kg",hint:"Die Zunge allein wiegt so viel wie ein Elefant.",emoji:"🐋"},
  {q:"Wie viele Millionen Geruchsrezeptoren hat ein Hund?",a:300,unit:"Millionen",hint:"Menschen haben nur 6 Millionen – Hunde riechen 50x besser.",emoji:"🐕"},
  {q:"Wie viele Meter lang kann ein Bandwurm im Darm werden?",a:25,unit:"Meter",hint:"Bandwürmer können jahrelang unbemerkt leben.",emoji:"🪱"},
  {q:"Wie hoch ist der Blutdruck einer Giraffe in mmHg?",a:280,unit:"mmHg",hint:"Nötig um Blut 2 Meter nach oben ins Gehirn zu pumpen.",emoji:"🦒"},
  {q:"Wie viele kg Bambus frisst ein Pandabär täglich?",a:15,unit:"kg",hint:"Bambus ist sehr nährstoffarm – daher die riesige Menge.",emoji:"🐼"},
  {q:"Wie lange trägt ein Hai seine Jungen in Monaten?",a:24,unit:"Monate",hint:"Hammerhaie haben die längste Tragzeit.",emoji:"🦈"},
  {q:"Wie viele Augen hat eine Spinne?",a:8,unit:"Augen",hint:"Trotz 8 Augen sehen viele Spinnen sehr schlecht.",emoji:"🕷️"},
  {q:"Wie lang ist die Zunge eines Chamäleons im Verhältnis zum Körper in %?",a:150,unit:"% Körperlänge",hint:"Die Zunge schlägt mit bis zu 26 km/h aus.",emoji:"🦎"},
  {q:"Wie viele km/h erreicht ein Wanderfalke im Sturzflug?",a:320,unit:"km/h",hint:"Das schnellste Tier der Welt im Sturzflug.",emoji:"🦅"},
  {q:"Wie viele Tonnen wiegt ein ausgewachsener Blauwal?",a:150,unit:"Tonnen",hint:"Das größte Tier das je auf der Erde gelebt hat.",emoji:"🐋"},
];
