// 🐘 TIERE – Kinder
export default [
  {q:"Wie viele Beine hat eine Spinne?",a:8,unit:"Beine",hint:"Spinnen sind Spinnentiere, keine Insekten.",emoji:"🕷️"},
  {q:"Wie schwer wird ein ausgewachsener Elefant in Tonnen?",a:6,unit:"Tonnen",hint:"Elefanten sind die schwersten Landtiere.",emoji:"🐘"},
  {q:"Wie schnell kann ein Gepard laufen in km/h?",a:112,unit:"km/h",hint:"Das schnellste Landtier der Welt.",emoji:"🐆"},
  {q:"Wie viele Tage trägt ein Elefant sein Baby?",a:645,unit:"Tage",hint:"Fast 2 Jahre – die längste Schwangerschaft auf Land.",emoji:"🐘"},
  {q:"Wie hoch kann ein Känguru springen in Metern?",a:3,unit:"Meter",hint:"Und bis zu 9 Meter weit in einem Sprung!",emoji:"🦘"},
  {q:"Wie viele Stunden schläft ein Koala pro Tag?",a:22,unit:"Stunden",hint:"Eukalyptus-Blätter sind schwer verdaulich.",emoji:"🐨"},
  {q:"Wie viele Zähne hat ein erwachsenes Krokodil?",a:66,unit:"Zähne",hint:"Sie erneuern ihre Zähne bis zu 50 Mal im Leben.",emoji:"🐊"},
  {q:"Wie viele Jahre kann ein Grönlandwal leben?",a:211,unit:"Jahre",hint:"Das langlebigste Säugetier der Erde.",emoji:"🐳"},
  {q:"Wie schwer wird ein ausgewachsener Gorilla in kg?",a:270,unit:"kg",hint:"Trotz Größe sind Gorillas Vegetarier.",emoji:"🦍"},
  {q:"Wie viele Liter Milch gibt eine Kuh pro Tag?",a:25,unit:"Liter",hint:"Hochleistungskühe können bis zu 50 Liter geben.",emoji:"🐄"},
  {q:"Wie viele Magen hat eine Kuh?",a:4,unit:"Mägen",hint:"Pansen, Netzmagen, Blättermagen, Labmagen.",emoji:"🐄"},
  {q:"Wie viele Herzen hat ein Tintenfisch?",a:3,unit:"Herzen",hint:"Zwei zu den Kiemen, eines zum Körper.",emoji:"🐙"},
  {q:"Wie viele km/h schwimmt der schnellste Fisch (Marlin)?",a:110,unit:"km/h",hint:"Schneller als viele Autos auf der Autobahn.",emoji:"🐟"},
  {q:"Wie viele Geruchsrezeptoren hat ein Hund (Millionen)?",a:300,unit:"Millionen",hint:"Menschen haben nur 6 Millionen.",emoji:"🐕"},
  {q:"Wie hoch kann ein Floh springen in cm?",a:33,unit:"cm",hint:"Das ist das 200-fache seiner Körperlänge.",emoji:"🦟"},
  {q:"Wie lange schläft ein Löwe pro Tag in Stunden?",a:20,unit:"Stunden",hint:"Löwen schlafen fast den ganzen Tag!",emoji:"🦁"},
  {q:"Wie viele km/h kann ein Strauß laufen?",a:70,unit:"km/h",hint:"Der schnellste laufende Vogel der Welt.",emoji:"🦜"},
  {q:"Wie schwer ist das Ei eines Straußes in kg?",a:1.35,unit:"kg",hint:"Das größte Ei aller lebenden Vögel.",emoji:"🥚"},
  {q:"Wie viele Eier legt eine Königin-Biene täglich?",a:2000,unit:"Eier",hint:"Im Sommer legt die Königin bis zu 2000 Eier pro Tag.",emoji:"🐝"},
  {q:"Wie viele kg Bambus frisst ein Panda täglich?",a:15,unit:"kg",hint:"Bambus ist nährstoffarm – daher die riesige Menge.",emoji:"🐼"},
  {q:"Wie groß wird ein ausgewachsener Blauwal in Metern?",a:30,unit:"Meter",hint:"Das größte Tier, das je auf der Erde gelebt hat.",emoji:"🐋"},
  {q:"Wie oft schlägt das Herz eines Kolibris pro Minute?",a:1200,unit:"Mal",hint:"Das schnellste Herz aller Vögel.",emoji:"🐦"},
  {q:"Wie viele Streifen hat ein Zebra maximal?",a:80,unit:"Streifen",hint:"Jedes Zebra hat ein einzigartiges Streifenmuster.",emoji:"🦓"},
  {q:"Wie tief kann ein Wal tauchen in Metern?",a:3000,unit:"Meter",hint:"Pottwal-Rekord: fast 3 km tief.",emoji:"🐳"},
  {q:"Wie lange brütet ein Adler seine Eier in Tagen?",a:35,unit:"Tage",hint:"Beide Elternteile brüten abwechselnd.",emoji:"🦅"},
  {q:"Wie viele Beine hat ein Tausendfüßer wirklich?",a:750,unit:"Beine",hint:"Trotz des Namens haben sie nie genau 1000 Beine.",emoji:"🐛"},
  {q:"Wie lange können Schildkröten ohne Essen auskommen in Monaten?",a:12,unit:"Monate",hint:"Sie können ihren Stoffwechsel stark verlangsamen.",emoji:"🐢"},
  {q:"Wie viele Augen hat eine Biene?",a:5,unit:"Augen",hint:"2 Facettenaugen und 3 Punktaugen.",emoji:"🐝"},
  {q:"Wie schwer ist ein ausgewachsener Eisbär in kg?",a:700,unit:"kg",hint:"Das größte Landraubtier der Erde.",emoji:"🐻‍❄️"},
  {q:"Wie viele km/h läuft ein Nashorn?",a:55,unit:"km/h",hint:"Trotz ihrer Masse sind Nashörner erstaunlich schnell.",emoji:"🦏"},
];

  // ── Aufstockung auf 250 ──
  {q:"Wie viele Beine hat eine Spinne?",a:8,unit:"Beine",hint:"Spinnen sind Spinnentiere, keine Insekten – die haben nur 6.",emoji:"🕷️"},
  {q:"Wie oft schlägt das Herz eines Kolibris pro Minute?",a:1200,unit:"Mal",hint:"Der schnellste Herzschlag aller Vögel.",emoji:"🐦"},
  {q:"Wie viele Jahre kann eine Landschildkröte werden?",a:150,unit:"Jahre",hint:"Manche werden über 200 Jahre alt!",emoji:"🐢"},
  {q:"Wie schwer wird ein ausgewachsener Eisbär in kg?",a:700,unit:"kg",hint:"Das größte Landraubtier der Erde.",emoji:"🐻‍❄️"},
  {q:"Wie weit kann ein Gepard in einem Sprung?",a:8,unit:"Meter",hint:"Riesige Sprünge beim Jagen.",emoji:"🐆"},
  {q:"Wie viele Finger hat ein Koala?",a:5,unit:"Finger",hint:"Koalas haben sogar Fingerabdrücke wie Menschen.",emoji:"🐨"},
  {q:"Wie viele Stunden schläft ein Löwe am Tag?",a:20,unit:"Stunden",hint:"Fast den ganzen Tag – nachts wird gejagt.",emoji:"🦁"},
  {q:"Wie schwer wird ein Gorilla maximal in kg?",a:270,unit:"kg",hint:"Trotz Größe sind Gorillas Vegetarier.",emoji:"🦍"},
  {q:"Wie viele km/h läuft ein Strauß?",a:70,unit:"km/h",hint:"Schnellster laufender Vogel der Welt.",emoji:"🦜"},
  {q:"Wie viele Zähne hat ein Erwachsenes Krokodil?",a:66,unit:"Zähne",hint:"Sie wachsen immer wieder nach.",emoji:"🐊"},
  {q:"Wie lange schläft ein Koala pro Tag?",a:22,unit:"Stunden",hint:"Eukalyptus ist schwer verdaulich.",emoji:"🐨"},
  {q:"Wie viele Jahre lebt ein Grönlandwal?",a:211,unit:"Jahre",hint:"Das langlebigste Säugetier der Erde.",emoji:"🐳"},
  {q:"Wie viele Liter Milch gibt eine Kuh pro Tag?",a:25,unit:"Liter",hint:"Hochleistungskühe bis zu 50 Liter.",emoji:"🐄"},
  {q:"Wie schwer ist ein ausgewachsener Elefant in Tonnen?",a:6,unit:"Tonnen",hint:"Das schwerste Landtier.",emoji:"🐘"},
  {q:"Wie tief kann ein Pottwal tauchen in Metern?",a:3000,unit:"Meter",hint:"Der tieftauchende Säuger der Welt.",emoji:"🐳"},
  {q:"Wie viele Magen hat eine Kuh?",a:4,unit:"Mägen",hint:"Pansen, Netzmagen, Blättermagen, Labmagen.",emoji:"🐄"},
  {q:"Wie viele Herzen hat ein Tintenfisch?",a:3,unit:"Herzen",hint:"Zwei für die Kiemen, eines für den Körper.",emoji:"🐙"},
  {q:"Wie viele Tentakel hat ein Oktopus?",a:8,unit:"Tentakel",hint:"Jeder Arm hat eigene Nervenzellen.",emoji:"🐙"},
  {q:"Wie hoch kann ein Känguru springen in Metern?",a:3,unit:"Meter",hint:"Und bis zu 9 Meter weit!",emoji:"🦘"},
  {q:"Wie groß wird ein ausgewachsener Blauwal in Metern?",a:30,unit:"Meter",hint:"Das größte Tier das je auf der Erde lebte.",emoji:"🐋"},
  {q:"Wie viele kg Bambus frisst ein Panda täglich?",a:15,unit:"kg",hint:"Bambus ist nährstoffarm – daher viel davon.",emoji:"🐼"},
  {q:"Wie viele Gramm wiegt ein Kolibri?",a:3,unit:"Gramm",hint:"Kleiner als eine Münze.",emoji:"🐦"},
  {q:"Wie viele Flügelschläge macht ein Kolibri pro Sekunde?",a:80,unit:"Mal",hint:"So schnell dass sie unsichtbar werden.",emoji:"🐦"},
  {q:"Wie viele km/h kann ein Gepard laufen?",a:112,unit:"km/h",hint:"Das schnellste Landtier der Welt.",emoji:"🐆"},
  {q:"Wie viele Augen hat eine Biene?",a:5,unit:"Augen",hint:"2 große Facettenaugen und 3 kleine Punktaugen.",emoji:"🐝"},
  {q:"Wie viele Stacheln hat ein Igel?",a:6000,unit:"Stacheln",hint:"Modifizierte Haare.",emoji:"🦔"},
  {q:"Wie lange kann ein Kamel ohne Wasser in Tagen?",a:15,unit:"Tage",hint:"Der Höcker speichert Fett, nicht Wasser.",emoji:"🐪"},
  {q:"Wie viele Eier legt eine Königin-Biene täglich?",a:2000,unit:"Eier",hint:"Im Sommer bis zu 2000 Eier.",emoji:"🐝"},
  {q:"Wie schwer ist das Ei eines Straußes in kg?",a:1.35,unit:"kg",hint:"Das größte Ei aller lebenden Vögel.",emoji:"🥚"},
  {q:"Wie viele km/h schwimmt ein Schwertfisch?",a:110,unit:"km/h",hint:"Der schnellste Fisch im Meer.",emoji:"🐟"},
  {q:"Wie weit kann ein Springbock in einem Sprung?",a:15,unit:"Meter",hint:"Springböcke machen riesige Luftsprünge.",emoji:"🦌"},
  {q:"Wie viele Geruchsrezeptoren hat ein Hund (Millionen)?",a:300,unit:"Millionen",hint:"Hunde riechen 50x besser als wir.",emoji:"🐕"},
  {q:"Wie viele Federn hat ein Schwan?",a:25000,unit:"Federn",hint:"Wasservögel haben besonders viele Federn.",emoji:"🦢"},
  {q:"Wie lange lebt eine Arbeiterbiene im Sommer?",a:6,unit:"Wochen",hint:"Nur 6 Wochen – im Winter bis 6 Monate.",emoji:"🐝"},
  {q:"Wie viele Knochen hat eine Schlange?",a:300,unit:"Knochen",hint:"Je nach Art 200 bis 400.",emoji:"🐍"},
  {q:"Wie weit springt ein Fisch flussaufwärts (Lachs) maximal in Metern?",a:3,unit:"Meter",hint:"Lachse springen Wasserfälle hoch.",emoji:"🐟"},
  {q:"Wie viele Jahre alt wird ein Hummer?",a:100,unit:"Jahre",hint:"Hummer altern kaum – werden nur durch Jäger begrenzt.",emoji:"🦞"},
  {q:"Wie hoch fliegt ein Adler maximal in Metern?",a:3000,unit:"Meter",hint:"Steinadler kreisen sehr hoch.",emoji:"🦅"},
  {q:"Wie schwer wird ein Walross maximal in kg?",a:1700,unit:"kg",hint:"Männliche Walrosse sind riesig.",emoji:"🦭"},
  {q:"Wie viele km weit wandert ein Monarch-Schmetterling?",a:4000,unit:"km",hint:"Von Kanada bis nach Mexiko.",emoji:"🦋"},
  {q:"Wie viele Zähne hat ein Weißer Hai?",a:300,unit:"Zähne",hint:"In mehreren Reihen – nachwachsend.",emoji:"🦈"},
  {q:"Wie viele Tage brütet ein Adler seine Eier?",a:35,unit:"Tage",hint:"Beide Eltern brüten abwechselnd.",emoji:"🦅"},
  {q:"Wie lange trägt eine Elefantenmutter ihr Baby?",a:645,unit:"Tage",hint:"Fast 2 Jahre – längste Tragzeit auf Land.",emoji:"🐘"},
  {q:"Wie viele Kilometer kann ein Polarfuchs in einer Nacht laufen?",a:40,unit:"km",hint:"Unglaublich ausdauernde Tiere.",emoji:"🦊"},
  {q:"Wie schwer ist ein neugeborenes Känguru in Gramm?",a:1,unit:"Gramm",hint:"Winzig – kriecht dann in den Beutel.",emoji:"🦘"},
  {q:"Wie viele Beine hat ein Tausendfüßer wirklich?",a:750,unit:"Beine",hint:"Nie genau 1000.",emoji:"🐛"},
  {q:"Wie viele Millionen Geruchssensoren hat ein Bär?",a:2100,unit:"Millionen",hint:"Schärfster Geruchssinn aller Landtiere.",emoji:"🐻"},
  {q:"Wie weit kann ein Delfin aus dem Wasser springen in Metern?",a:6,unit:"Meter",hint:"Breaching – wichtige Kommunikation.",emoji:"🐬"},
  {q:"Wie viele Stunden täglich schläft ein Faultier?",a:20,unit:"Stunden",hint:"Fast alles außer Schlafen – schlafen.",emoji:"🦥"},
  {q:"Wie viele Streifen hat ein Zebra maximal?",a:80,unit:"Streifen",hint:"Jedes Zebra hat ein einzigartiges Muster.",emoji:"🦓"},
  {q:"Wie groß wird ein Riesenkalmar in Metern?",a:13,unit:"Meter",hint:"Größtes Tier ohne Wirbelsäule.",emoji:"🦑"},
  {q:"Wie viele Jahre lebt ein Elefant?",a:70,unit:"Jahre",hint:"In Gefangenschaft manchmal über 80.",emoji:"🐘"},
  {q:"Wie schwer ist ein Gepard-Baby bei Geburt in Gramm?",a:250,unit:"Gramm",hint:"Blind und hilflos.",emoji:"🐆"},
  {q:"Wie lange schläft ein Grizzlybär im Winterschlaf in Monaten?",a:6,unit:"Monate",hint:"Eigentlich Winterruhe – kann jederzeit aufwachen.",emoji:"🐻"},
  {q:"Wie viele km/h kann ein Nashorn laufen?",a:55,unit:"km/h",hint:"Trotz Masse erstaunlich schnell.",emoji:"🦏"},
  {q:"Wie viele Eier legt eine Meeresschildkröte pro Nest?",a:100,unit:"Eier",hint:"Nur wenige Babys überleben bis zum Meer.",emoji:"🐢"},
  {q:"Wie groß wird ein Flusspferd in kg?",a:3000,unit:"kg",hint:"Das drittschwerstste Landtier.",emoji:"🦛"},
  {q:"Wie viele km/h kann ein Gepard in 2 Sekunden erreichen?",a:75,unit:"km/h",hint:"Schnellste Beschleunigung aller Landtiere.",emoji:"🐆"},
  {q:"Wie viele Knochen hat ein Delfin?",a:200,unit:"Knochen",hint:"Delfine haben noch Knochen von Hinterbeinen.",emoji:"🐬"},
  {q:"Wie lange kann eine Qualle (bestimmte Art) theoretisch leben?",a:9999,unit:"Jahre",hint:"Turritopsis dohrnii – die unsterbliche Qualle.",emoji:"🪼"},
  {q:"Wie viele Tonnen frisst ein Blauwal täglich an Krill?",a:3.6,unit:"Tonnen",hint:"Fast 4 Tonnen täglich.",emoji:"🐋"},
  {q:"Wie viele Augen hat eine Libelle?",a:30000,unit:"Facetten",hint:"Zusammengesetzte Augen mit 30.000 Einzellinsen.",emoji:"🪲"},
  {q:"Wie schwer ist ein Polarbär-Baby bei Geburt in Gramm?",a:500,unit:"Gramm",hint:"Winzig verglichen mit der riesigen Mutter.",emoji:"🐻‍❄️"},
  {q:"Wie weit kann ein Springfrosch springen in cm?",a:530,unit:"cm",hint:"Das Vielfache der eigenen Körperlänge.",emoji:"🐸"},
  {q:"Wie viele Kilometer wandert ein Weißwal pro Jahr?",a:10000,unit:"km",hint:"Weißwale sind wanderfreudige Meeressäuger.",emoji:"🐳"},
  {q:"Wie viele Stunden täglich verbringt ein Faultier mit Schlafen?",a:20,unit:"Stunden",hint:"Champion im Schlafen.",emoji:"🦥"},
  {q:"Wie viele Gramm wiegt ein Hummel?",a:0.6,unit:"Gramm",hint:"Winzig aber kann ein Vielfaches tragen.",emoji:"🐝"},
  {q:"Wie viele Jahre lebt eine Arbeitstermiten-Königin?",a:30,unit:"Jahre",hint:"Legt täglich bis zu 30.000 Eier.",emoji:"🐜"},
  {q:"Wie viele Stunden schläft ein Delfin täglich?",a:8,unit:"Stunden",hint:"Mit einer Gehirnhälfte wach.",emoji:"🐬"},
  {q:"Wie weit kann ein Fliegendes Eichhörnchen gleiten in Metern?",a:90,unit:"Meter",hint:"Mit der Gleitfalte zwischen Beinen.",emoji:"🐿️"},
  {q:"Wie viele kg frisst ein Gorilla täglich?",a:18,unit:"kg",hint:"Reine Pflanzenfresser.",emoji:"🦍"},
  {q:"Wie hoch springt ein Lachs flussaufwärts in Metern?",a:3,unit:"Meter",hint:"Lachse überwinden Wasserfälle.",emoji:"🐟"},
  {q:"Wie viele Eier legt eine Spinne in ihrem Leben?",a:3000,unit:"Eier",hint:"Je nach Art hunderte bis tausende.",emoji:"🕷️"},
  {q:"Wie viele Millionen Arten von Insekten gibt es auf der Erde?",a:1,unit:"Million Arten",hint:"Über 1 Million bekannte Arten.",emoji:"🐛"},
  {q:"Wie weit kann eine Heuschrecke springen in Metern?",a:1,unit:"Meter",hint:"Das 20-fache der Körperlänge.",emoji:"🦗"},
  {q:"Wie viele Stunden täglich weidet ein Pferd?",a:16,unit:"Stunden",hint:"Pferde fressen fast nonstop.",emoji:"🐴"},
  {q:"Wie viele Liter Honig produziert ein Bienenvolk pro Jahr?",a:30,unit:"Liter",hint:"Für ein Glas Honig fliegen Bienen 80.000 km.",emoji:"🍯"},
  {q:"Wie schwer ist ein Schimpansen-Gehirn in Gramm?",a:400,unit:"Gramm",hint:"Das menschliche Gehirn wiegt 1400g.",emoji:"🐒"},
  {q:"Wie viele km/h kann ein Schwarzbär laufen?",a:48,unit:"km/h",hint:"Schneller als ein Mensch.",emoji:"🐻"},
  {q:"Wie lange schläft ein Hamster täglich?",a:14,unit:"Stunden",hint:"Hamster sind nachtaktiv.",emoji:"🐹"},
  {q:"Wie viele Junge hat ein Schwein pro Wurf?",a:10,unit:"Ferkel",hint:"8 bis 14 Ferkel.",emoji:"🐷"},
  {q:"Wie viele km weit fliegt eine Küstenseeschwalbe pro Jahr?",a:70000,unit:"km",hint:"Die weiteste Wanderung aller Tiere.",emoji:"🐦"},
  {q:"Wie schwer ist ein Walross in kg?",a:1700,unit:"kg",hint:"Einer der schwersten Flossenfüßer.",emoji:"🦭"},
  {q:"Wie viele Zähne hat ein Delfin?",a:100,unit:"Zähne",hint:"Zum Fangen – nicht zum Kauen.",emoji:"🐬"},
  {q:"Wie hoch kann ein Floh springen in cm?",a:33,unit:"cm",hint:"Das 200-fache der Körperlänge.",emoji:"🦟"},
  {q:"Wie viele Stunden lebt eine Eintagsfliege?",a:24,unit:"Stunden",hint:"Als Larve bis zu 3 Jahre.",emoji:"🪲"},
  {q:"Wie weit wandert ein Elch pro Jahr in km?",a:300,unit:"km",hint:"Folgt Nahrung und Wetter.",emoji:"🦌"},
  {q:"Wie viele Junge wirft eine Ratte pro Jahr?",a:70,unit:"Junge",hint:"5-10 Würfe à 5-10 Junge.",emoji:"🐀"},
  {q:"Wie viele Stunden am Tag jagt ein Tiger?",a:1,unit:"Stunde aktiv jagend",hint:"Nur 1 von 10 Jagdversuchen ist erfolgreich.",emoji:"🐯"},
  {q:"Wie viele Meter lang ist die Zunge eines Ameisenbären?",a:0.6,unit:"Meter",hint:"60 cm – schießt 150x pro Minute aus.",emoji:"🐜"},
  {q:"Wie viele Jahre lebt ein wilder Schimpanse?",a:45,unit:"Jahre",hint:"In Gefangenschaft bis 60.",emoji:"🐒"},
  {q:"Wie schwer wird ein ausgewachsener Nilpferd in Tonnen?",a:3,unit:"Tonnen",hint:"Drittschwerstestes Landtier.",emoji:"🦛"},
  {q:"Wie viele Gramm Nahrung frisst eine Raupe täglich relativ zum Körper?",a:200,unit:"% Körpergewicht",hint:"Raupen verdoppeln ihr Gewicht in Tagen.",emoji:"🐛"},
  {q:"Wie viele km kann ein Polarfuchs in einer Nacht zurücklegen?",a:40,unit:"km",hint:"Ausdauernde Jäger.",emoji:"🦊"},
  {q:"Wie viele Beine hat ein Hummer?",a:10,unit:"Beine",hint:"Krebstiere haben 10 Beine.",emoji:"🦞"},
  {q:"Wie viele Liter Wasser trinkt ein Elefant täglich?",a:190,unit:"Liter",hint:"Der Rüssel fasst 15 Liter auf einmal.",emoji:"🐘"},
  {q:"Wie viele Stunden schläft eine Katze täglich?",a:16,unit:"Stunden",hint:"Katzen schlafen mehr als die meisten Tiere.",emoji:"🐱"},
  {q:"Wie weit kann ein Springhase springen in Metern?",a:3,unit:"Meter",hint:"Afrikanischer Nager mit riesigen Sprüngen.",emoji:"🐇"},
  {q:"Wie viele kg Gras frisst ein Pferd täglich?",a:11,unit:"kg",hint:"Pferde sind reine Pflanzenfresser.",emoji:"🐴"},
  {q:"Wie viele Junge hat ein Polarfuchs pro Wurf?",a:8,unit:"Junge",hint:"Bei guter Lemmingversorgung sogar 14.",emoji:"🦊"},
  {q:"Wie viele Tentakel hat eine Qualle durchschnittlich?",a:80,unit:"Tentakel",hint:"Je nach Art 4 bis hunderte.",emoji:"🪼"},
  {q:"Wie viele Eier legt eine Hornisse pro Sommer?",a:500,unit:"Eier",hint:"Die Königin legt alle Eier.",emoji:"🐝"},
  {q:"Wie hoch fliegt ein Kondor in Metern?",a:5500,unit:"Meter",hint:"Höchst fliegender Vogel Südamerikas.",emoji:"🦅"},
  {q:"Wie viele Stunden schläft ein Grizzlybär täglich?",a:20,unit:"Stunden",hint:"Außer im Sommer wenn er Nahrung sammelt.",emoji:"🐻"},
  {q:"Wie schwer ist ein Schimpanse in kg?",a:60,unit:"kg",hint:"Trotz geringerer Größe 6x stärker als Menschen.",emoji:"🐒"},
  {q:"Wie viele Augen hat eine Fliege?",a:4000,unit:"Facetten",hint:"Facettenaugen mit tausenden Linsen.",emoji:"🪰"},
  {q:"Wie weit kann ein Albatros täglich fliegen?",a:1000,unit:"km",hint:"Albatrosse sind unglaubliche Flieger.",emoji:"🦅"},
  {q:"Wie viele Zähne wächst ein Krokodil in seinem Leben nach?",a:50,unit:"Sätze",hint:"Bis zu 50 neue Zahnsätze.",emoji:"🐊"},
  {q:"Wie viele Liter Milch trinkt ein Blauwal-Baby täglich?",a:600,unit:"Liter",hint:"Es wächst täglich um 90 kg.",emoji:"🐋"},
  {q:"Wie viele Stunden am Tag sucht ein Nashorn Nahrung?",a:12,unit:"Stunden",hint:"Die Hälfte ihres Lebens mit Fressen.",emoji:"🦏"},
  {q:"Wie schwer ist ein Gorilla-Arm in kg?",a:15,unit:"kg",hint:"Gorillas sind 6x stärker als Menschen.",emoji:"🦍"},
  {q:"Wie viele Junge hat ein Gepard pro Wurf?",a:3,unit:"Junge",hint:"1 bis 8 – meist 3 bis 5.",emoji:"🐆"},
  {q:"Wie viele Millionen Tiere leben im Amazonas-Regenwald (Arten)?",a:3,unit:"Millionen Arten",hint:"Größte Artenvielfalt der Erde.",emoji:"🌿"},
  {q:"Wie viele Stunden schläft ein Delfin täglich?",a:8,unit:"Stunden",hint:"Mit einer Gehirnhälfte immer wach.",emoji:"🐬"},
  {q:"Wie viele km/h kann eine Libelle fliegen?",a:55,unit:"km/h",hint:"Eine der schnellsten fliegenden Insekten.",emoji:"🪲"},
  {q:"Wie viele Eier legt eine Meeresschildkröte in ihrem Leben?",a:600,unit:"Eier",hint:"3-7 Gelege pro Saison.",emoji:"🐢"},
  {q:"Wie viele Zentimeter ist ein Koala-Baby bei der Geburt groß?",a:2,unit:"cm",hint:"Kriecht dann in den Beutel.",emoji:"🐨"},
  {q:"Wie viele Stunden täglich verbringt ein Orang-Utan in Bäumen?",a:24,unit:"Stunden",hint:"Größte Baumklettertiere.",emoji:"🦧"},
  {q:"Wie groß wird eine Anakonda in Metern?",a:8,unit:"Meter",hint:"Schwerste Schlange der Welt.",emoji:"🐍"},
  {q:"Wie viele Stunden am Tag spielen junge Löwenkinder?",a:6,unit:"Stunden",hint:"Spielen trainiert sie für die Jagd.",emoji:"🦁"},
  {q:"Wie viele Farben kann ein Tintenfisch anzeigen?",a:30,unit:"Farben",hint:"Obwohl farbenblind – Tarnung durch Farbwechsel.",emoji:"🦑"},
  {q:"Wie weit kann ein Krokodil aus dem Wasser herausspringen in Metern?",a:1.5,unit:"Meter",hint:"Überraschend agil.",emoji:"🐊"},
  {q:"Wie viele Knochen hat ein Vogel im Vergleich zu einem Säugetier?",a:0,unit:"weniger",hint:"Vögel haben sogar mehr Knochen als viele Säugetiere.",emoji:"🐦"},
  {q:"Wie viele km/h rennt ein Erdferkel?",a:40,unit:"km/h",hint:"Überraschend schnell.",emoji:"🐷"},
  {q:"Wie viele Junge hat ein Eisbär pro Wurf?",a:2,unit:"Junge",hint:"Fast immer Zwillinge.",emoji:"🐻‍❄️"},
  {q:"Wie viele Stacheln hat ein Stachelschwein?",a:30000,unit:"Stacheln",hint:"Jeder Stachel ist ein modifiziertes Haar.",emoji:"🦔"},
  {q:"Wie viele Gramm wiegt ein Pinguin-Ei?",a:450,unit:"Gramm",hint:"Kaiserpinguin-Eier sind riesig.",emoji:"🐧"},
  {q:"Wie lange kann ein Fisch ohne Wasser überleben (Lungenfisch)?",a:4,unit:"Jahre",hint:"Lungenfische überleben in Schlamm.",emoji:"🐟"},
  {q:"Wie viele Stunden schläft ein Braunbär im Winter?",a:20,unit:"Stunden/Tag",hint:"Winterruhe – nicht echter Tiefschlaf.",emoji:"🐻"},
  {q:"Wie weit kann ein Gepard seinen Geruch benutzen in km?",a:3,unit:"km",hint:"Geparden jagen hauptsächlich mit den Augen.",emoji:"🐆"},
  {q:"Wie viele Millionen Schäden verursachen Ratten jährlich?",a:19,unit:"Mrd. Dollar",hint:"Ratten zerstören Getreide und Kabel.",emoji:"🐀"},
  {q:"Wie viele Knochen haben beide Hände eines Affen?",a:54,unit:"Knochen",hint:"27 pro Hand – wie beim Menschen.",emoji:"🐒"},
  {q:"Wie groß wird ein Riesenkalmar-Auge in cm?",a:30,unit:"cm",hint:"Größtes Auge im Tierreich.",emoji:"🦑"},
  {q:"Wie viele km lang ist der Darm einer Kuh?",a:40,unit:"Meter",hint:"Sehr langes Verdauungssystem.",emoji:"🐄"},
  {q:"Wie viele Stunden brütet ein Kaiserpinguin sein Ei auf den Füßen?",a:1512,unit:"Stunden",hint:"63 Tage ohne Nahrung.",emoji:"🐧"},
  {q:"Wie viele Meter weit können Elefanten kommunizieren per Infraschall?",a:10,unit:"km",hint:"Tiefe Töne durch den Boden.",emoji:"🐘"},
  {q:"Wie viele Gramm frisst ein Igel täglich?",a:70,unit:"Gramm",hint:"Insekten, Würmer und kleine Wirbeltiere.",emoji:"🦔"},
  {q:"Wie viele km/h kann ein Wanderfalke im normalen Flug?",a:100,unit:"km/h",hint:"Im Sturzflug bis 320 km/h.",emoji:"🦅"},
  {q:"Wie viele Liter Speichel produziert eine Kuh täglich?",a:200,unit:"Liter",hint:"Wiederkäuen braucht viel Speichel.",emoji:"🐄"},
  {q:"Wie groß wird ein Walhai in Metern?",a:12,unit:"Meter",hint:"Größter Fisch der Welt – harmlos.",emoji:"🦈"},
  {q:"Wie viele Stunden täglich verbringt ein Faultier mit Bewegen?",a:3,unit:"Stunden",hint:"Rest des Tages hängen und schlafen.",emoji:"🦥"},
  {q:"Wie viele Zentimeter ist ein Nashorn-Horn lang?",a:150,unit:"cm",hint:"Aus Keratin – wie unsere Fingernägel.",emoji:"🦏"},
  {q:"Wie viele Junge hat ein Hase pro Jahr?",a:20,unit:"Junge",hint:"Mehrere Würfe à 3-5 Junge.",emoji:"🐇"},
  {q:"Wie schwer ist der Schädel eines T-Rex in kg?",a:500,unit:"kg",hint:"Riesiger Schädel – für riesige Beute.",emoji:"🦖"},
  {q:"Wie viele Stunden lebt eine Stubenfliege insgesamt?",a:500,unit:"Stunden",hint:"Nur 3 Wochen – legt dabei viele Eier.",emoji:"🪰"},
  {q:"Wie weit kann ein Weißkopfseeadler sehen in km?",a:3,unit:"km",hint:"8x schärfer als menschliches Sehen.",emoji:"🦅"},
  {q:"Wie viele Eier legt eine Königin-Ameise in ihrem Leben?",a:30000000,unit:"Eier",hint:"30 Millionen über ihr Leben von 30 Jahren.",emoji:"🐜"},
  {q:"Wie schwer ist ein Flusspferd-Zahn in kg?",a:3,unit:"kg",hint:"Reine Waffe gegen Rivalen.",emoji:"🦛"},
  {q:"Wie viele Stunden täglich schläft ein Tiger?",a:16,unit:"Stunden",hint:"Viel schlafen für die nächtliche Jagd.",emoji:"🐯"},
  {q:"Wie groß wird eine Kobra aufgerichtet in cm?",a:180,unit:"cm",hint:"Kobras können sich hoch aufrichten.",emoji:"🐍"},
  {q:"Wie viele km weit wandert ein Zugvogel pro Tag?",a:200,unit:"km",hint:"Je nach Wind auch mehr.",emoji:"🐦"},
  {q:"Wie viele Stacheln hat ein Kugelfisch wenn aufgeblasen?",a:1000,unit:"Stacheln",hint:"Kugelfische blähen sich bei Gefahr auf.",emoji:"🐡"},
  {q:"Wie viele Gramm Nahrung frisst ein Kolibri täglich?",a:8,unit:"Gramm",hint:"Sein eigenes Körpergewicht täglich.",emoji:"🐦"},
  {q:"Wie viele Liter Blut hat ein Nashorn?",a:20,unit:"Liter",hint:"Proportional weniger als ein Elefant.",emoji:"🦏"},
  {q:"Wie groß ist ein Kaiserpinguin in cm?",a:120,unit:"cm",hint:"Der größte Pinguin der Welt.",emoji:"🐧"},
  {q:"Wie viele Tonnen Krill frisst ein Blauwal täglich?",a:3.6,unit:"Tonnen",hint:"Alles durch Filterung.",emoji:"🐋"},
  {q:"Wie viele km/h kann ein Gepard nach 100m halten?",a:60,unit:"km/h",hint:"Er ermüdet schnell und muss pausieren.",emoji:"🐆"},
  {q:"Wie viele Jahre lebt ein Hai maximal?",a:70,unit:"Jahre",hint:"Grönlandhaie sogar 400 Jahre.",emoji:"🦈"},
  {q:"Wie viele Stunden schläft ein Gorilla täglich?",a:12,unit:"Stunden",hint:"Gorillas bauen täglich neue Schlafnester.",emoji:"🦍"},
  {q:"Wie groß ist ein Orca in Metern?",a:8,unit:"Meter",hint:"Schwertkale – die größten Delfine.",emoji:"🐋"},
  {q:"Wie viele Rippen hat eine Schlange?",a:200,unit:"Rippen",hint:"Schlangen haben für jede Wirbel ein Rippenpaar.",emoji:"🐍"},
  {q:"Wie viele Stunden dauert eine Tigerjagd?",a:1,unit:"Stunde",hint:"Meist 15-30 Minuten – selten erfolgreich.",emoji:"🐯"},
];

  {q:"Wie viele Herzen hat ein Oktopus?",a:3,unit:"Herzen",hint:"Zwei Kiemenherzen und ein Körperherz.",emoji:"🐙"},
  {q:"Wie tief kann ein Lederschildkröte tauchen?",a:1200,unit:"Meter",hint:"Die tieftauchende Schildkröte.",emoji:"🐢"},
  {q:"Wie viele km weit kann ein Elefant riechen?",a:19,unit:"km",hint:"Bester Geruchssinn aller Landtiere.",emoji:"🐘"},
  {q:"Wie lang ist die Zunge einer Giraffe in cm?",a:50,unit:"cm",hint:"Dunkelblau um Sonnenbrand zu vermeiden.",emoji:"🦒"},
  {q:"Wie viele Jahre wird eine Meeresschildkröte alt?",a:80,unit:"Jahre",hint:"Sehr langlebig – manche über 100 Jahre.",emoji:"🐢"},
  {q:"Wie viele Eier legt ein Walhai pro Trächtigkeit?",a:300,unit:"Eier",hint:"Walhaie sind lebendgebärend.",emoji:"🦈"},
  {q:"Wie lang ist ein Nashorn-Horn in cm?",a:90,unit:"cm",hint:"Das längste gemessene Horn.",emoji:"🦏"},
  {q:"Wie viele Kilogramm frisst ein Eisbär täglich?",a:10,unit:"kg",hint:"Hauptsächlich Robben und Fische.",emoji:"🐻‍❄️"},
  {q:"Wie schnell kann ein Gepard in 3 Sekunden beschleunigen?",a:96,unit:"km/h",hint:"Von 0 auf 96 km/h in 3 Sekunden.",emoji:"🐆"},
  {q:"Wie lang ist ein ausgewachsener Nilkrokodil in Metern?",a:5,unit:"Meter",hint:"Das größte Krokodil Afrikas.",emoji:"🐊"},
  {q:"Wie viele Tentakel hat eine Qualle?",a:80,unit:"Tentakel",hint:"Je nach Art von 4 bis Hunderten.",emoji:"🪼"},
  {q:"Wie viele Stunden schläft ein Pinguin täglich?",a:8,unit:"Stunden",hint:"Pinguine schlafen oft im Stehen.",emoji:"🐧"},
  {q:"Wie lang wird eine Python-Schlange maximal?",a:7,unit:"Meter",hint:"Der Netzpython ist die längste Schlange.",emoji:"🐍"},
  {q:"Wie viele Eier legt eine Schildkröte pro Nest?",a:100,unit:"Eier",hint:"Nur wenige Babys überleben.",emoji:"🥚"},
  {q:"Wie viele km/h schwimmt ein Delfin?",a:55,unit:"km/h",hint:"Im Sprint besonders schnell.",emoji:"🐬"},
  {q:"Wie lang ist das Horn eines Nashorns maximal in cm?",a:150,unit:"cm",hint:"150cm wurden gemessen.",emoji:"🦏"},
  {q:"Wie viele Zähne hat ein Weißer Hai?",a:300,unit:"Zähne",hint:"In mehreren Reihen – ständig nachwachsend.",emoji:"🦈"},
  {q:"Wie schwer wird ein Gorilla-Silberrücken in kg?",a:250,unit:"kg",hint:"Der größte lebende Affe.",emoji:"🦍"},
  {q:"Wie lang ist die Rüssellänge des größten Elefanten in cm?",a:250,unit:"cm",hint:"Der Rüssel hat über 40.000 Muskeln.",emoji:"🐘"},
  {q:"Wie viele Stunden braucht eine Schildkröte für 1 km?",a:2,unit:"Stunden",hint:"Schildkröten laufen sehr langsam.",emoji:"🐢"},
  {q:"Wie viele Meter lang ist ein ausgewachsener Blauwal?",a:30,unit:"Meter",hint:"Das größte Tier der Erde.",emoji:"🐋"},
  {q:"Wie viele km kann ein Elefant pro Tag wandern?",a:50,unit:"km",hint:"Auf der Suche nach Wasser.",emoji:"🐘"},
  {q:"Wie viele Liter Milch trinkt ein Baby-Elefant täglich?",a:10,unit:"Liter",hint:"Wird 2-3 Jahre gestillt.",emoji:"🐘"},
  {q:"Wie viele Gramm frisst ein Kolibri täglich?",a:15,unit:"Gramm",hint:"Fast sein eigenes Körpergewicht.",emoji:"🐦"},
  {q:"Wie lang ist der Stachel einer Stachelrochen in cm?",a:35,unit:"cm",hint:"Giftig und sehr schmerzhaft.",emoji:"🐟"},
  {q:"Wie viele Eier legt eine Gottesanbeterin?",a:200,unit:"Eier",hint:"In einem schaumigen Kokon.",emoji:"🦗"},
  {q:"Wie schwer ist ein neugeborener Elefant in kg?",a:120,unit:"kg",hint:"Das schwerste Neugeborene auf Land.",emoji:"🐘"},
  {q:"Wie viele Meter tief taucht ein Pinguin maximal?",a:565,unit:"Meter",hint:"Kaiserpinguin – tieftauchender Vogel.",emoji:"🐧"},
  {q:"Wie lang ist ein Krokodil-Schwanz in Metern?",a:2,unit:"Meter",hint:"Der Schwanz macht die Hälfte aus.",emoji:"🐊"},
  {q:"Wie viele Stimmen können Wölfe über km übertragen?",a:10,unit:"km",hint:"Das Heulen überträgt sich weit.",emoji:"🐺"},
  {q:"Wie viele Stacheln hat ein Stachelschwein?",a:30000,unit:"Stacheln",hint:"30.000 modifizierte Haare.",emoji:"🦔"},
  {q:"Wie lang ist ein Chamäleon-Zunge in cm?",a:30,unit:"cm",hint:"Länger als sein Körper – schlägt mit 26 km/h zu.",emoji:"🦎"},
  {q:"Wie viele Sinne haben Haifische?",a:6,unit:"Sinne",hint:"Plus Elektrorezeption – sie spüren Herzschläge.",emoji:"🦈"},
  {q:"Wie schwer ist ein Kolibri in Gramm?",a:3,unit:"Gramm",hint:"So leicht wie eine Büroklammer.",emoji:"🐦"},
  {q:"Wie viele Kilometer wandert ein Albatros pro Jahr?",a:120000,unit:"km",hint:"Fast dreimal um die Erde.",emoji:"🦅"},
  {q:"Wie lang ist ein ausgewachsener Komodo-Waran?",a:3,unit:"Meter",hint:"Größte lebende Eidechse.",emoji:"🦎"},
  {q:"Wie viele Zähne hat ein Haifisch im Leben?",a:30000,unit:"Zähne",hint:"Mehrere Sätze nachwachsender Zähne.",emoji:"🦷"},
  {q:"Wie viele Stunden schläft ein Delfin täglich?",a:8,unit:"Stunden",hint:"Mit einer Gehirnhälfte.",emoji:"🐬"},
  {q:"Wie lang ist ein Wal-Fluke (Schwanzflosse) in Metern?",a:6,unit:"Meter",hint:"Beim Blauwal bis 6 Meter breit.",emoji:"🐋"},
  {q:"Wie viele Tonnen wiegt ein Nilpferd?",a:3,unit:"Tonnen",hint:"Drittschwerste Landtier.",emoji:"🦛"},
  {q:"Wie viele Stunden am Tag schläft ein Faultier?",a:20,unit:"Stunden",hint:"Faultiere sind die Schlafweltmeister.",emoji:"🦥"},
  {q:"Wie lang ist die Jagdzunge eines Ameisenbären?",a:60,unit:"cm",hint:"150 Mal pro Minute ausgestreckt.",emoji:"🐜"},
  {q:"Wie viele Sinnesorgane hat eine Biene?",a:5,unit:"Organe",hint:"5 Augen inklusive 3 Punktaugen.",emoji:"🐝"},
  {q:"Wie schwer ist ein ausgewachsener Eisbär in kg?",a:700,unit:"kg",hint:"Das größte Landraubtier.",emoji:"🐻‍❄️"},
  {q:"Wie lang schläft ein Grizzlybär im Winter in Monaten?",a:6,unit:"Monate",hint:"November bis April in Winterruhe.",emoji:"🐻"},
  {q:"Wie viele km/h springt ein Gepard in einem Schritt?",a:7,unit:"Meter",hint:"7 Meter pro Sprung beim Jagen.",emoji:"🐆"},
  {q:"Wie lang ist ein Bienenstock in cm?",a:50,unit:"cm",hint:"Ein normaler Holzbienenstock.",emoji:"🐝"},
  {q:"Wie viele Stunden kann ein Kamel ohne Wasser?",a:360,unit:"Stunden",hint:"15 Tage in kühlerem Wetter.",emoji:"🐪"},
  {q:"Wie viele Meter weit kann ein Gepard in einem Sprung?",a:8,unit:"Meter",hint:"Riesige Sprünge beim Jagen.",emoji:"🐆"},
  {q:"Wie schwer ist ein neugeborener Blauwal in Tonnen?",a:2.7,unit:"Tonnen",hint:"Das größte Neugeborene der Welt.",emoji:"🐋"},
  {q:"Wie viele Monate brütet ein Wanderfalke?",a:1,unit:"Monat",hint:"29-32 Tage Brutzeit.",emoji:"🦅"},
  {q:"Wie viele Stunden jagt ein Löwe pro Tag?",a:4,unit:"Stunden",hint:"Nur 4 Stunden aktives Jagen.",emoji:"🦁"},
  {q:"Wie lang ist ein Python-Zahn in mm?",a:25,unit:"mm",hint:"Sehr spitze Zähne ohne Gift.",emoji:"🐍"},
  {q:"Wie viele Kilometer wandert ein Zugvogel pro Tag?",a:300,unit:"km",hint:"Manche legen 500km täglich zurück.",emoji:"🐦"},
  {q:"Wie viele Beine hat ein Tausendfüßer maximal?",a:750,unit:"Beine",hint:"Nie genau tausend trotz des Namens.",emoji:"🐛"},
  {q:"Wie schwer ist ein ausgewachsener Wal in Tonnen?",a:150,unit:"Tonnen",hint:"Der Blauwal – das schwerste Tier.",emoji:"🐋"},
  {q:"Wie lang ist ein Piranha-Zahn in mm?",a:4,unit:"mm",hint:"Klein aber extrem scharf.",emoji:"🐟"},
  {q:"Wie viele Stunden schläft eine Fledermaus täglich?",a:20,unit:"Stunden",hint:"Tagsüber hängend schlafen.",emoji:"🦇"},
  {q:"Wie viele Meter lang ist eine Giraffe von Nase bis Schwanz?",a:6,unit:"Meter",hint:"Größtes lebendes Landtier.",emoji:"🦒"},
  {q:"Wie viele Gramm frisst ein Kolibri pro Tag relativ zum Körpergewicht?",a:150,unit:"% Körpergewicht",hint:"1,5x das eigene Körpergewicht.",emoji:"🐦"},
];
