// 🚀 WELTRAUM – Kinder
export default [
  {q:"Wie viele Planeten gibt es in unserem Sonnensystem?",a:8,unit:"Planeten",hint:"Pluto ist seit 2006 kein Planet mehr.",emoji:"🪐"},
  {q:"Wie viele Minuten braucht Sonnenlicht bis zur Erde?",a:8,unit:"Minuten",hint:"Licht reist mit 300.000 km pro Sekunde.",emoji:"☀️"},
  {q:"Wie viele Monde hat der Saturn?",a:146,unit:"Monde",hint:"Saturn hat die meisten Monde aller Planeten.",emoji:"🪐"},
  {q:"Wie weit ist die Erde von der Sonne entfernt in Millionen km?",a:150,unit:"Mio. km",hint:"Diese Entfernung nennt man 1 Astronomische Einheit.",emoji:"☀️"},
  {q:"Wie viele Grad Celsius ist es auf dem Mond nachts?",a:-170,unit:"°C",hint:"Tagsüber sind es +130°C.",emoji:"🌙"},
  {q:"Wie viele Milliarden Sterne hat unsere Milchstraße?",a:200,unit:"Milliarden",hint:"200 Milliarden Sterne in der Milchstraße allein.",emoji:"⭐"},
  {q:"Wie alt ist das Universum in Milliarden Jahren?",a:13.8,unit:"Mrd. Jahre",hint:"Seit dem Urknall.",emoji:"🌌"},
  {q:"Wie viele km ist der Mond von der Erde entfernt?",a:384400,unit:"km",hint:"Apollo-Astronauten brauchten 3 Tage.",emoji:"🌙"},
  {q:"Wie hoch fliegt die ISS über der Erde in km?",a:400,unit:"km",hint:"Sie umkreist die Erde alle 90 Minuten.",emoji:"🚀"},
  {q:"Wie viele Erdmassen hat Jupiter?",a:318,unit:"Erdmassen",hint:"Jupiter ist 318 Mal so schwer wie die Erde.",emoji:"🪐"},
  {q:"Wie viele Monate dauert ein Jahr auf dem Mars?",a:24,unit:"Erdmonate",hint:"Ein Marsjahr = 687 Erdtage.",emoji:"🔴"},
  {q:"Wie viele km/h bewegt sich die Erde um die Sonne?",a:107000,unit:"km/h",hint:"Das sind 30 km pro Sekunde.",emoji:"🌍"},
  {q:"Wie viele km beträgt der Durchmesser der Erde?",a:12742,unit:"km",hint:"Am Äquator ist sie etwas dicker als an den Polen.",emoji:"🌍"},
  {q:"Wie heiß ist die Oberfläche der Sonne in °C?",a:5500,unit:"°C",hint:"Im Kern sind es 15 Millionen Grad.",emoji:"☀️"},
  {q:"Wie lange dauerte die erste Mondlandung in Stunden auf dem Mond?",a:21,unit:"Stunden",hint:"Neil Armstrong und Buzz Aldrin am 20. Juli 1969.",emoji:"🌙"},
  {q:"Wie viele km beträgt der Umfang der Erde am Äquator?",a:40075,unit:"km",hint:"Die Erde ist nicht perfekt rund.",emoji:"🌍"},
  {q:"Wie viele Astronauten waren bisher auf dem Mond?",a:12,unit:"Astronauten",hint:"Alle 12 waren Amerikaner bei den Apollo-Missionen.",emoji:"👨‍🚀"},
  {q:"Wie viele Ringe hat Saturn?",a:7,unit:"Hauptringe",hint:"Die Ringe bestehen aus Eis und Gestein.",emoji:"🪐"},
  {q:"Wie viele Monde hat der Mars?",a:2,unit:"Monde",hint:"Phobos und Deimos – beide sehr klein.",emoji:"🔴"},
  {q:"Wie viele km/h muss eine Rakete fliegen um die Erde zu verlassen?",a:40000,unit:"km/h",hint:"Das ist die Fluchtgeschwindigkeit der Erde.",emoji:"🚀"},
  {q:"Wie groß ist der Große Rote Fleck auf Jupiter in km?",a:16000,unit:"km",hint:"Ein Sturm, der seit 350 Jahren tobt.",emoji:"🪐"},
  {q:"Wie viele km beträgt der Durchmesser der Sonne?",a:1392000,unit:"km",hint:"Die Sonne ist 109 Mal so breit wie die Erde.",emoji:"☀️"},
  {q:"Wie schnell dreht sich die Erde am Äquator in km/h?",a:1670,unit:"km/h",hint:"Wir spüren die Rotation nicht, weil alles mitbewegt wird.",emoji:"🌍"},
  {q:"Wie viele Grad Celsius beträgt die Temperatur im Weltall?",a:-270,unit:"°C",hint:"Fast der absolute Nullpunkt von -273°C.",emoji:"❄️"},
  {q:"Wie weit ist Alpha Centauri von der Erde in Lichtjahren?",a:4.37,unit:"Lichtjahre",hint:"Das nächste Sternensystem nach unserem.",emoji:"⭐"},
  {q:"Wie viele Stunden dauert ein Tag auf der Venus?",a:5832,unit:"Stunden",hint:"Ein Venusjahr ist kürzer als ein Venustag!",emoji:"🪐"},
  {q:"Wie lange dauert ein Tag auf dem Merkur in Erdtagen?",a:59,unit:"Erdtage",hint:"Merkur dreht sich sehr langsam um seine Achse.",emoji:"☿"},
  {q:"Wie viele Mal größer ist die Sonne als die Erde?",a:1300000,unit:"Mal",hint:"1,3 Millionen Erden würden in die Sonne passen.",emoji:"☀️"},
  {q:"Wie heiß ist der Kern der Erde in °C?",a:6000,unit:"°C",hint:"Ähnlich heiß wie die Oberfläche der Sonne.",emoji:"🌍"},
  {q:"Wie viele km/h fährt der Sonnenwind?",a:500000,unit:"km/h",hint:"Elektrisch geladene Teilchen von der Sonne.",emoji:"💨"},
];
