// 🐾 ANIMALS & SEX – Adults – 178 questions
export default [
  {id:"tsex_001",q:"How many hours does sex last for snakes?",a:24,unit:"hours",hint:"Snakes can mate for days or even weeks.",emoji:"🐍"},
  {id:"tsex_002",q:"How many cm long is a duck's penis relative to its body length?",a:40,unit:"cm",hint:"Mallard ducks have spiral-shaped penises.",emoji:"🦆"},
  {id:"tsex_003",q:"How many testicles does a bull have?",a:2,unit:"testicles",hint:"Like most mammals.",emoji:"🐂"},
  {id:"tsex_004",q:"How many cm long is a blue whale's penis?",a:270,unit:"cm",hint:"2.7 meters – the largest sex organ in the animal kingdom.",emoji:"🐋"},
  {id:"tsex_005",q:"How many days does a female elephant carry her young?",a:645,unit:"days",hint:"Almost 2 years – the longest gestation period on land.",emoji:"🐘"},
  {id:"tsex_006",q:"How many times does a chimpanzee mate with different females?",a:100,unit:"times",hint:"Male chimps mate with many females.",emoji:"🐒"},
  {id:"tsex_007",q:"How many million eggs does a queen bee lay in her lifetime?",a:2,unit:"million eggs",hint:"2 million over her 5-year lifespan.",emoji:"🐝"},
  {id:"tsex_008",q:"How long is a cow's vagina, in cm?",a:30,unit:"cm",hint:"About as long as a child's arm.",emoji:"🐄"},
  {id:"tsex_009",q:"How many billion sperm does a bull's ejaculate contain?",a:7,unit:"billion sperm",hint:"7 billion – much more than in humans.",emoji:"🐂"},
  {id:"tsex_010",q:"How long does sex last for giraffes, in seconds?",a:2,unit:"seconds",hint:"Very fast – but frequent.",emoji:"🦒"},
  {id:"tsex_011",q:"How many times per day does a lion mate?",a:20,unit:"times",hint:"Up to 20 times daily during mating season – about every 15 minutes.",emoji:"🦁"},
  {id:"tsex_012",q:"How many cm long is a gorilla's penis?",a:4,unit:"cm",hint:"A very small sex organ despite their size.",emoji:"🦍"},
  {id:"tsex_013",q:"How long does intercourse last for bonobos?",a:15,unit:"seconds",hint:"Very short – but very frequent.",emoji:"🐒"},
  {id:"tsex_014",q:"How many testicles does a whale have?",a:2,unit:"testicles",hint:"Located internally – to protect against the cold.",emoji:"🐋"},
  {q:"How many sperm can a gorilla's ejaculate contain?",a:200000000,hint:"Significantly fewer than chimpanzees.",unit:"sperm",emoji:"🦍"},
  {id:"tsex_015",q:"How many months does a shark species carry its young?",a:24,unit:"months",hint:"Hammerhead sharks carry for 2 years.",emoji:"🦈"},
  {id:"tsex_016",q:"How many times its body length is a barnacle's penis?",a:8,unit:"x body length",hint:"Relative to body size, the longest sex organ.",emoji:"🦀"},
  {id:"tsex_017",q:"How many cm long is a hyena's clitoris?",a:18,unit:"cm",hint:"Female hyenas have a pseudo-penis-like clitoris.",emoji:"🦁"},
  {id:"tsex_018",q:"How long does mating last for rhinos, in minutes?",a:30,unit:"minutes",hint:"One of the longest among land mammals.",emoji:"🦏"},
  {id:"tsex_019",q:"How many penises do snakes have?",a:2,unit:"hemipenes",hint:"Snakes have two hemipenes.",emoji:"🐍"},
  {id:"tsex_020",q:"How many kg does a blue whale's sex organ weigh in total?",a:520,unit:"kg",hint:"Testicles ~70kg + penis ~450kg = about 520kg.",emoji:"🐋"},
  {id:"tsex_021",q:"How many days does a male emperor penguin incubate the egg?",a:63,unit:"days",hint:"63 days – without food, in the Antarctic winter.",emoji:"🐧"},
  {id:"tsex_022",q:"How many times does a drone bee mate in its lifetime?",a:1,unit:"time",hint:"After that, the drone dies.",emoji:"🐝"},
  {q:"How many sperm does a horse's ejaculate contain?",a:8000000000,hint:"8 billion sperm.",unit:"sperm",emoji:"🐴"},
  {id:"tsex_023",q:"How long does mating last for sharks, in minutes?",a:30,unit:"minutes",hint:"Minutes – with biting as a precursor.",emoji:"🦈"},
  {id:"tsex_024",q:"How many cm long is a chimpanzee's penis?",a:8,unit:"cm",hint:"Larger than a gorilla's.",emoji:"🐒"},
  {id:"tsex_025",q:"How many eggs does a giant tortoise lay per season?",a:200,unit:"eggs",hint:"Several times a year.",emoji:"🐢"},
  {id:"tsex_026",q:"How long do field grasshoppers mate in one stretch?",a:12,unit:"hours",hint:"Sometimes connected for days.",emoji:"🦗"},
  {id:"tsex_027",q:"How many centimeters long is a sperm whale's penis?",a:240,unit:"cm",hint:"The second-longest animal penis after the blue whale's.",emoji:"🐳"},
  {id:"tsex_028",q:"How many days does a dog carry her young?",a:63,unit:"days",hint:"Days of gestation.",emoji:"🐕"},
  {id:"tsex_029",q:"How many eggs does a turtle lay per clutch?",a:100,unit:"eggs",hint:"50-200, depending on the species.",emoji:"🐢"},
  {id:"tsex_030",q:"How long does mating last for spiders?",a:60,unit:"minutes",hint:"Sometimes up to several hours.",emoji:"🕷️"},
  {q:"How many sperm does a bull's semen contain in livestock breeding (per dose)?",a:10000000,hint:"10 million per insemination dose.",unit:"sperm",emoji:"🐂"},
  {id:"tsex_031",q:"How many cm long is a horse's vagina?",a:60,unit:"cm",hint:"Mares have a very long vagina.",emoji:"🐴"},
  {id:"tsex_032",q:"How long does a cat's pregnancy last, in weeks?",a:9,unit:"weeks",hint:"63-67 days.",emoji:"🐱"},
  {id:"tsex_033",q:"How many females does a bull impregnate per year in livestock breeding?",a:50000,unit:"females",hint:"Through artificial insemination.",emoji:"🐂"},
  {id:"tsex_034",q:"How long does a mouse's pregnancy last, in days?",a:21,unit:"days",hint:"Three weeks – and she can become pregnant again immediately.",emoji:"🐭"},
  {id:"tsex_035",q:"How many offspring does a mouse have per year?",a:70,unit:"offspring",hint:"5-10 litters of 5-10 young each.",emoji:"🐭"},
  {id:"tsex_036",q:"How many times per hour can rabbits mate?",a:10,unit:"times",hint:"'Breeding like rabbits' is meant literally.",emoji:"🐇"},
  {id:"tsex_037",q:"How long does sex last for dogs, in minutes?",a:20,unit:"minutes",hint:"The 'tie' – they're locked together.",emoji:"🐕"},
  {id:"tsex_038",q:"How many thousand eggs does a female octopus lay?",a:400,unit:"thousand eggs",hint:"400,000 eggs, guarded until death.",emoji:"🐙"},
  {id:"tsex_039",q:"How many cm long is an elephant's penis?",a:180,unit:"cm",hint:"1.8 meters – S-shaped and muscular.",emoji:"🐘"},
  {id:"tsex_040",q:"How long does mating last for whales, in minutes?",a:18,unit:"minutes",hint:"20 minutes – in the ocean.",emoji:"🐋"},
  {id:"tsex_041",q:"How many ovulations per year does a cat have?",a:4,unit:"times",hint:"Cats are seasonal polyestrous animals.",emoji:"🐱"},
  {id:"tsex_042",q:"How many young can an opossum carry at once?",a:20,unit:"young",hint:"In the pouch – all at the same time.",emoji:"🐀"},
  {id:"tsex_043",q:"How many months does an elephant carry its young?",a:21,unit:"months",hint:"Almost 2 years.",emoji:"🐘"},
  {id:"tsex_044",q:"How many cm long is a dolphin's penis?",a:38,unit:"cm",hint:"Dolphins have prehensile penises.",emoji:"🐬"},
  {id:"tsex_045",q:"How long does mating last for hippos, in minutes?",a:10,unit:"minutes",hint:"In the water.",emoji:"🦛"},
  {q:"How many sperm does an elephant's ejaculate contain?",a:50000000000,hint:"50 billion sperm.",unit:"sperm",emoji:"🐘"},
  {id:"tsex_046",q:"How many young does a wombat have per year?",a:1,unit:"young",hint:"Only one – very slow reproduction.",emoji:"🐨"},
  {id:"tsex_047",q:"How long do horses mate, in minutes?",a:1,unit:"minute",hint:"Short but intense.",emoji:"🐴"},
  {id:"tsex_048",q:"How many females does a gorilla silverback maintain?",a:10,unit:"females",hint:"A silverback leads a group.",emoji:"🦍"},
  {id:"tsex_049",q:"How many months does a kangaroo carry its young in the pouch?",a:9,unit:"months",hint:"Only 1cm at birth – then raised in the pouch.",emoji:"🦘"},
  {q:"How many sperm does a dog's ejaculate contain?",a:500000000,hint:"500 million.",unit:"sperm",emoji:"🐕"},
  {id:"tsex_050",q:"How many seconds does a drone bee's mating with the queen last?",a:5,unit:"seconds",hint:"Only seconds – then the drone dies.",emoji:"🐝"},
  {id:"tsex_051",q:"How many eggs does a butterfly lay in total?",a:200,unit:"eggs",hint:"Usually hundreds, spread across many plants.",emoji:"🦋"},
  {id:"tsex_052",q:"How many cm long is a manatee's penis?",a:70,unit:"cm",hint:"Manatees also have impressive organs.",emoji:"🐟"},
  {id:"tsex_053",q:"How long does a sperm whale's pregnancy last, in months?",a:16,unit:"months",hint:"Almost 1.5 years.",emoji:"🐳"},
  {id:"tsex_054",q:"How many young does a cat have per litter?",a:5,unit:"young",hint:"On average 3-7 kittens.",emoji:"🐱"},
  {id:"tsex_055",q:"How many times does a queen ant mate in her lifetime?",a:1,unit:"time",hint:"Once – then she stores sperm for years.",emoji:"🐜"},
  {id:"tsex_056",q:"How many cm long is a mouse's penis?",a:1.5,unit:"cm",hint:"Very large relative to its body.",emoji:"🐭"},
  {id:"tsex_057",q:"How long do grizzly bears mate?",a:30,unit:"minutes",hint:"The act lasts up to 30 minutes.",emoji:"🐻"},
  {id:"tsex_058",q:"How many thousand eggs does a female perch lay?",a:300,unit:"thousand eggs",hint:"Fish lay enormous quantities of eggs.",emoji:"🐟"},
  {id:"tsex_059",q:"How many cm is a female fossa's clitoris (Madagascar)?",a:7,unit:"cm",hint:"The fossa has an exceptionally long clitoris.",emoji:"🦁"},
  {id:"tsex_060",q:"How long does a queen bee's mating flight last?",a:1,unit:"hour",hint:"She mates in the air with 12-20 drones.",emoji:"🐝"},
  {q:"How many sperm from a billy goat are in one ejaculate?",a:3000000000,hint:"3 billion.",unit:"sperm",emoji:"🐐"},
  {id:"tsex_061",q:"How many days per year is a female dog in heat?",a:18,unit:"days",hint:"Twice a year, 9 days each.",emoji:"🐕"},
  {id:"tsex_062",q:"How many cm long is a hippo's penis?",a:50,unit:"cm",hint:"Hippos spray urine to mark territory.",emoji:"🦛"},
  {id:"tsex_063",q:"How long do pandas mate?",a:3,unit:"minutes",hint:"Very short – and very rare.",emoji:"🐼"},
  {id:"tsex_064",q:"How many young does a pig have per litter?",a:10,unit:"piglets",hint:"8-14 piglets per litter.",emoji:"🐷"},
  {id:"tsex_065",q:"How many eggs does a sea turtle lay per season in total?",a:600,unit:"eggs",hint:"3-7 clutches of 80-120 eggs each.",emoji:"🐢"},
  {id:"tsex_066",q:"How many cm long is a sea lion's penis?",a:40,unit:"cm",hint:"Pinnipeds have very long penises.",emoji:"🦭"},
  {id:"tsex_067",q:"How long does a chimpanzee's pregnancy last, in days?",a:243,unit:"days",hint:"Similar to humans.",emoji:"🐒"},
  {id:"tsex_068",q:"How many females does an alpha wolf impregnate per year?",a:1,unit:"female",hint:"Wolves are largely monogamous.",emoji:"🐺"},
  {q:"How many sperm does a male rabbit's ejaculate contain?",a:400000000,hint:"400 million.",unit:"sperm",emoji:"🐇"},
  {id:"tsex_069",q:"How many cm long is a walrus's penis?",a:63,unit:"cm",hint:"Walruses also have a baculum (penis bone).",emoji:"🦭"},
  {id:"tsex_070",q:"How long does mating last for crocodiles, in minutes?",a:10,unit:"minutes",hint:"In the water.",emoji:"🐊"},
  {id:"tsex_071",q:"How many young does an Arctic fox have per litter?",a:8,unit:"young",hint:"Up to 14 young.",emoji:"🦊"},
  {id:"tsex_072",q:"How many eggs does a bumblebee queen lay per summer?",a:200,unit:"eggs",hint:"Just one season.",emoji:"🐝"},
  {id:"tsex_073",q:"How many times per day does a rabbit mate?",a:10,unit:"times",hint:"'Breeding like rabbits' isn't a myth.",emoji:"🐇"},
  {id:"tsex_074",q:"How many weeks does a female dog carry her young?",a:9,unit:"weeks",hint:"63 days.",emoji:"🐕"},
  {id:"tsex_075",q:"How many eggs does a great tit lay per clutch?",a:10,unit:"eggs",hint:"Up to 15 eggs per brood.",emoji:"🐦"},
  {id:"tsex_076",q:"How many cm long is a raccoon's baculum?",a:10,unit:"cm",hint:"Raccoons have one of the largest bacula relative to body size.",emoji:"🦝"},
  {id:"tsex_077",q:"How many hours does mating last for snails?",a:6,unit:"hours",hint:"Snails are hermaphrodites.",emoji:"🐌"},
  {id:"tsex_078",q:"How many grams do both gorilla testicles weigh combined?",a:30,unit:"grams",hint:"Very small compared to a 170kg body.",emoji:"🦍"},
  {id:"tsex_079",q:"How many eggs does a silk spider lay per cocoon?",a:400,unit:"eggs",hint:"All in the same silk sac.",emoji:"🕷️"},
  {id:"tsex_080",q:"How long do houseflies mate, in minutes?",a:20,unit:"minutes",hint:"Houseflies mate for a relatively long time.",emoji:"🪰"},
  {id:"tsex_081",q:"How many cm long is an orca's penis?",a:180,unit:"cm",hint:"1.8 meters – retractable.",emoji:"🐋"},
  {id:"tsex_082",q:"How many young does a leopard have per litter?",a:2,unit:"young",hint:"1-4, usually 2-3 cubs.",emoji:"🐆"},
  {id:"tsex_083",q:"How long does a tigress's pregnancy last, in days?",a:103,unit:"days",hint:"Just under 3.5 months.",emoji:"🐯"},
  {q:"How many sperm does a goldfinch's ejaculate contain?",a:100000000,hint:"100 million – birds economize.",unit:"sperm",emoji:"🐦"},
  {id:"tsex_084",q:"How long is a hoopoe's penis relative to its body?",a:50,unit:"% of body length",hint:"Very long relative to the bird's body.",emoji:"🐦"},
  {id:"tsex_085",q:"How many cm long is a cow's fallopian tube?",a:25,unit:"cm",hint:"Connects the ovary to the uterus.",emoji:"🐄"},
  {id:"tsex_086",q:"How long does mating last for albatrosses, in hours?",a:1,unit:"hour",hint:"Albatrosses are monogamous and ceremonial.",emoji:"🦅"},
  {id:"tsex_087",q:"How many young does a bat have per year?",a:1,unit:"young",hint:"Usually just one offspring.",emoji:"🦇"},
  {q:"How many sperm does an elephant seal's ejaculate contain?",a:100000000000,hint:"100 billion.",unit:"sperm",emoji:"🦭"},
  {id:"tsex_088",q:"How long do lions mate each time, in seconds?",a:30,unit:"seconds",hint:"Short but frequent – up to 20x daily.",emoji:"🦁"},
  {id:"tsex_089",q:"How many cm is a squirrel's baculum?",a:2,unit:"cm",hint:"Small but functional.",emoji:"🐿️"},
  {id:"tsex_090",q:"How long does mating last for snakes, in hours?",a:6,unit:"hours",hint:"Sometimes for days or weeks.",emoji:"🐍"},
  {id:"tsex_091",q:"How many eggs does an ant queen lay daily?",a:800,unit:"eggs",hint:"Millions over her entire lifetime.",emoji:"🐜"},
  {id:"tsex_092",q:"How many cm long is an orangutan's penis?",a:4,unit:"cm",hint:"Similarly small to gorillas.",emoji:"🦧"},
  {id:"tsex_093",q:"How long does a hamster's pregnancy last, in days?",a:16,unit:"days",hint:"The shortest gestation period of any mammal.",emoji:"🐹"},
  {id:"tsex_094",q:"How many young does a rat have per litter?",a:8,unit:"young",hint:"5-12 – up to 8 litters per year.",emoji:"🐀"},
  {id:"tsex_095",q:"How long is a domestic pig's penis, in cm?",a:50,unit:"cm",hint:"Corkscrew-shaped.",emoji:"🐷"},
  {id:"tsex_096",q:"How many eggs does a spider lay in total over her lifetime?",a:3000,unit:"eggs",hint:"Hundreds to thousands, depending on the species.",emoji:"🕷️"},
  {id:"tsex_097",q:"How many cm long is a cat's uterus?",a:10,unit:"cm",hint:"Two-horned – can carry kittens from different fathers.",emoji:"🐱"},
  {q:"How many sperm does a pheasant's ejaculate contain?",a:2000000000,hint:"2 billion.",unit:"sperm",emoji:"🐦"},
  {id:"tsex_098",q:"How many months does a giraffe carry her young?",a:15,unit:"months",hint:"The calf falls 2m to the ground.",emoji:"🦒"},
  {id:"tsex_099",q:"How many young does a cheetah have per litter?",a:3,unit:"young",hint:"1-8 – usually 3-5.",emoji:"🐆"},
  {id:"tsex_100",q:"How long do dolphins mate?",a:12,unit:"seconds",hint:"Very short – but more frequent.",emoji:"🐬"},
  {id:"tsex_101",q:"How many eggs does a frog lay per season?",a:2000,unit:"eggs",hint:"Frogs lay thousands of tiny eggs.",emoji:"🐸"},
  {id:"tsex_102",q:"How many cm long is a polar bear's baculum?",a:22,unit:"cm",hint:"One of the longest bacula relative to body size.",emoji:"🐻‍❄️"},
  {id:"tsex_103",q:"How long does a gorilla's pregnancy last, in days?",a:257,unit:"days",hint:"Similar to humans.",emoji:"🦍"},
  {q:"How many sperm does a ram's ejaculate contain?",a:3000000000,hint:"3 billion.",unit:"sperm",emoji:"🐑"},
  {id:"tsex_104",q:"How many young does a lioness have per litter?",a:3,unit:"young",hint:"1-4, usually 2-3.",emoji:"🦁"},
  {id:"tsex_105",q:"How long do tiger frogs mate?",a:2,unit:"days",hint:"Amplexus – the embrace can last days.",emoji:"🐸"},
  {id:"tsex_106",q:"How many eggs does a wasp queen lay per summer?",a:300,unit:"eggs",hint:"Worker wasps build the nest for her.",emoji:"🐝"},
  {id:"tsex_107",q:"How many days does a rabbit carry her young?",a:31,unit:"days",hint:"A very short gestation period.",emoji:"🐇"},
  {id:"tsex_108",q:"How many young can an Arctic fox have at maximum per litter?",a:14,unit:"young",hint:"With good lemming availability.",emoji:"🦊"},
  {id:"tsex_109",q:"How many cm long is a tapir's penis?",a:60,unit:"cm",hint:"Tapirs have a prehensile penis.",emoji:"🦏"},
  {id:"tsex_110",q:"How long do martens mate?",a:2,unit:"hours",hint:"Several hours – a long mating.",emoji:"🦦"},
  {id:"tsex_111",q:"How many eggs does a silkworm lay?",a:500,unit:"eggs",hint:"Per female, in her lifetime.",emoji:"🪱"},
  {id:"tsex_112",q:"How long is a beaver's baculum?",a:5,unit:"cm",hint:"Beavers have a baculum.",emoji:"🦦"},
  {id:"tsex_113",q:"How many days does a mare carry her foal?",a:340,unit:"days",hint:"About 11 months.",emoji:"🐴"},
  {id:"tsex_114",q:"How many young does a hyena have per litter?",a:2,unit:"young",hint:"Sometimes 1-3.",emoji:"🐈"},
  {id:"tsex_115",q:"How long is a river dolphin's penis?",a:40,unit:"cm",hint:"The Amazon river dolphin.",emoji:"🐬"},
  {q:"How many sperm does a boar's ejaculate contain?",a:50000000000,hint:"50 billion – the largest ejaculate volume.",unit:"sperm",emoji:"🐷"},
  {id:"tsex_116",q:"How long do tortoises mate, in hours?",a:3,unit:"hours",hint:"Very enduring.",emoji:"🐢"},
  {id:"tsex_117",q:"How many young does a female chimpanzee have in her lifetime?",a:5,unit:"young",hint:"Chimpanzees have few offspring – one every 4-5 years.",emoji:"🐒"},
  {id:"tsex_118",q:"How long is a mare's uterus?",a:45,unit:"cm",hint:"Big enough for the foal.",emoji:"🐴"},
  {id:"tsex_119",q:"How many young does a wild boar have per litter?",a:6,unit:"piglets",hint:"4-8 – depending on food availability.",emoji:"🐗"},
  {id:"tsex_120",q:"How long is a bonobo's penis?",a:10,unit:"cm",hint:"Larger than a gorilla's, smaller than a human's.",emoji:"🐒"},
  {id:"tsex_121",q:"How many eggs does a trout lay per spawning season?",a:2000,unit:"eggs",hint:"Up to 10,000, depending on size.",emoji:"🐟"},
  {id:"tsex_122",q:"How many days does a lion carry her young?",a:110,unit:"days",hint:"Lions have single litters.",emoji:"🦁"},
  {id:"tsex_123",q:"How many young does an aardvark have per year?",a:1,unit:"young",hint:"Only one offspring per season.",emoji:"🐷"},
  {id:"tsex_124",q:"How long is a gorilla's vagina, in cm?",a:9,unit:"cm",hint:"Proportionally smaller than a human's.",emoji:"🦍"},
  {q:"How many sperm does a rabbit's ejaculate contain?",a:400000000,hint:"400 million.",unit:"sperm",emoji:"🐇"},
  {id:"tsex_125",q:"How long do Arctic foxes mate?",a:20,unit:"minutes",hint:"During the short Arctic mating season.",emoji:"🦊"},
  {id:"tsex_126",q:"How many thousand eggs does an octopus lay in total?",a:100,unit:"thousand eggs",hint:"And guards them until they hatch – then dies.",emoji:"🐙"},
  {id:"tsex_127",q:"How long is a dog's baculum?",a:10,unit:"cm",hint:"Dogs have a penis bone.",emoji:"🐕"},
  {id:"tsex_128",q:"How many young does a leopard have in her lifetime?",a:8,unit:"young",hint:"One litter every 2 years over 16 years.",emoji:"🐆"},
  {id:"tsex_129",q:"How long is a female binturong's clitoris?",a:5,unit:"cm",hint:"Binturongs are known for this trait.",emoji:"🐱"},
  {q:"How many sperm does a hamster's ejaculate contain?",a:200000000,hint:"200 million.",unit:"sperm",emoji:"🐹"},
  {id:"tsex_130",q:"How many days does a rat carry her young?",a:22,unit:"days",hint:"A very short gestation period.",emoji:"🐀"},
  {id:"tsex_131",q:"How many eggs does a butterfly species lay daily?",a:20,unit:"eggs",hint:"Usually about 200 over her entire lifetime.",emoji:"🦋"},
  {id:"tsex_132",q:"How long is an elephant's trunk – also used as a sensory organ during mating?",a:200,unit:"cm",hint:"Elephants touch each other with their trunks while mating.",emoji:"🐘"},
  {id:"tsex_133",q:"How many young does a raccoon have per litter?",a:4,unit:"young",hint:"3-5 young in spring.",emoji:"🦝"},
  {id:"tsex_134",q:"How long does mating last for shoveler ducks?",a:2,unit:"minutes",hint:"Ducks are known for forced copulation – an evolutionary arms race.",emoji:"🦆"},
  {q:"How many sperm can a single boar produce in one day?",a:50000000000,hint:"50 billion daily.",unit:"sperm",emoji:"🐷"},
  {id:"tsex_135",q:"How long is a bull's penis, in cm?",a:90,unit:"cm",hint:"A retractor muscle allows it to be stored in an S-shape.",emoji:"🐂"},
  {id:"tsex_136",q:"How many eggs does a housefly lay in her short life?",a:500,unit:"eggs",hint:"In batches of 75-150.",emoji:"🪰"},
  {id:"tsex_137",q:"How many days per year is a mare in heat?",a:15,unit:"days",hint:"Multiple times during summer.",emoji:"🐴"},
  {id:"tsex_138",q:"How long is a domestic cat's uterus, in cm?",a:8,unit:"cm",hint:"Two-horned – can have kittens from different fathers.",emoji:"🐱"},
  {id:"tsex_139",q:"How many young can an opossum carry in her pouch at once?",a:13,unit:"young",hint:"As many as there are teats – that's how many can survive.",emoji:"🐀"},
  {id:"tsex_140",q:"How long does mating last for orcas?",a:5,unit:"minutes",hint:"In the water – very rarely observed.",emoji:"🐋"},
  {q:"How many sperm does a billy goat's ejaculate contain?",a:3000000000,hint:"3 billion.",unit:"sperm",emoji:"🐐"},
  {id:"tsex_141",q:"How long is a cow's cervix?",a:10,unit:"cm",hint:"Important for artificial insemination.",emoji:"🐄"},
  {id:"tsex_142",q:"How many young does an otter have per litter?",a:3,unit:"young",hint:"1-5, usually 3.",emoji:"🦦"},
  {id:"tsex_143",q:"How long do cheetahs mate?",a:10,unit:"minutes",hint:"Multiple times daily during mating season.",emoji:"🐆"},
  {id:"tsex_144",q:"How many eggs does a praying mantis lay after mating?",a:200,unit:"eggs",hint:"In an ootheca (egg case).",emoji:"🦗"},
  {id:"tsex_145",q:"How long is a seal's baculum, in cm?",a:35,unit:"cm",hint:"Male seals have very long bacula.",emoji:"🦭"},
  {q:"How many sperm does a male cat's ejaculate contain?",a:50000000,hint:"50 million.",unit:"sperm",emoji:"🐱"},
  {id:"tsex_146",q:"How many days does a coyote carry her young?",a:63,unit:"days",hint:"Same as dogs.",emoji:"🐺"},
  {id:"tsex_147",q:"How many young does a rhino have per litter?",a:1,unit:"young",hint:"Always single births.",emoji:"🦏"},
  {id:"tsex_148",q:"How many eggs does a whale shark lay per season?",a:300,unit:"eggs",hint:"Whale sharks are viviparous – but produce eggs before birth.",emoji:"🦈"},
  {id:"tsex_149",q:"How long do domestic cats mate?",a:5,unit:"minutes",hint:"Multiple times daily – very loud.",emoji:"🐱"},
  {q:"How many sperm does a ram's ejaculate contain?",a:3000000000,hint:"3 billion.",unit:"sperm",emoji:"🐑"},
  {id:"tsex_150",q:"How many young does a stoat have per litter?",a:6,unit:"young",hint:"4-9 young.",emoji:"🦦"},
  {id:"tsex_151",q:"How many eggs does a sand lizard lay per season?",a:8,unit:"eggs",hint:"6-12 eggs.",emoji:"🦎"},
  {id:"tsex_152",q:"How long does a sheep's pregnancy last, in days?",a:147,unit:"days",hint:"About 5 months.",emoji:"🐑"},
  {id:"tsex_153",q:"How many young does a polar bear have per litter?",a:2,unit:"young",hint:"Almost always twins.",emoji:"🐻‍❄️"},
  {id:"tsex_154",q:"How long is a male domestic cat's penis?",a:1.5,unit:"cm",hint:"Very small with spiny barbs.",emoji:"🐱"},
  {q:"How many sperm does an otter's ejaculate contain?",a:300000000,hint:"300 million.",unit:"sperm",emoji:"🦦"},
  {id:"tsex_155",q:"How long do wild boars mate?",a:5,unit:"minutes",hint:"Quick but frequent.",emoji:"🐗"},
  {id:"tsex_156",q:"How many eggs does a hornet lay per summer?",a:500,unit:"eggs",hint:"The queen alone.",emoji:"🐝"},
  {id:"tsex_157",q:"How long is a female great ape's uterus?",a:8,unit:"cm",hint:"Similar to ours.",emoji:"🦍"},
  {id:"tsex_158",q:"How many young does a brown bear have per litter?",a:2,unit:"young",hint:"1-4, usually 2.",emoji:"🐻"},
  {q:"How many sperm does a boar's ejaculate contain per ml?",a:200000000,hint:"200 million/ml – total volume up to 500ml.",unit:"sperm/ml",emoji:"🐷"},
];
