// 🐾 ANIMAL KINGDOM – English
export default [
  {q:"How many kg wiegen die Hoden eines Blauwals?",a:70,unit:"kg",hint:"Der Blauwal ist das größte Tier der Erde.",emoji:"🐋"},
  {q:"How often pro Minute schlägt das Herz einer Maus?",a:600,unit:"times",hint:"Je kleiner das Tier, desto schneller das Herz.",emoji:"🐭"},
  {q:"How many Tage trägt ein Elefant sein Junges?",a:645,unit:"days",hint:"Fast 2 Jahre – längste Schwangerschaft aller Landsäugetiere.",emoji:"🐘"},
  {q:"How many Liter Milch produziert eine Kuh per day?",a:25,unit:"liters",hint:"Hochleistungskühe können bis zu 50 Liter daily geben.",emoji:"🐄"},
  {q:"How heavy kann ein Riesenkalmar-Auge in Gramm werden?",a:250,unit:"grams",hint:"Das größte Auge im Tierreich – so groß wie ein Fußball.",emoji:"🦑"},
  {q:"How many km/h läuft ein Gepard maximal?",a:112,unit:"km/h",hint:"Er kann diese Höchstgeschwindigkeit nur kurz halten.",emoji:"🐆"},
  {q:"How many Magen hat eine Kuh?",a:4,unit:"Mägen",hint:"Pansen, Netzmagen, Blättermagen und Labmagen.",emoji:"🐄"},
  {q:"How high kann ein Känguru springen in Metern?",a:3,unit:"meters",hint:"Und in der Länge sogar bis zu 9 Meter weit.",emoji:"🦘"},
  {q:"How heavy wird ein ausgewachsener Gorilla maximal in kg?",a:270,unit:"kg",hint:"Trotz Größe sind Gorillas überwiegend Vegetarier.",emoji:"🦍"},
  {q:"How many Stunden schläft ein Koala per day?",a:22,unit:"hours",hint:"Eukalyptus ist schwer verdaulich – daher die Müdigkeit.",emoji:"🐨"},
  {q:"How many km/h kann ein Schwertfisch schwimmen?",a:110,unit:"km/h",hint:"Der schnellste Fisch im Meer.",emoji:"🐟"},
  {q:"How long lebt eine Königin-Biene in Jahren?",a:5,unit:"years",hint:"Arbeiterinnen leben im Sommer nur 6 Wochen.",emoji:"🐝"},
  {q:"How many Zähne hat ein erwachsenes Krokodil?",a:66,unit:"teeth",hint:"Krokodile erneuern ihre Zähne bis zu 50 Mal im Leben.",emoji:"🐊"},
  {q:"How many Eier legt eine Königin-Termite per day?",a:30000,unit:"Eier",hint:"Die produktivste Mutter im Insektenreich.",emoji:"🐜"},
  {q:"How many Liter Blut hat ein ausgewachsener Elefant?",a:400,unit:"liters",hint:"Das Elefantenherz wiegt allein bis zu 30 kg.",emoji:"🐘"},
  {q:"How many Mal kann ein Specht pro Sekunde hämmern?",a:20,unit:"times",hint:"Sein Gehirn ist durch Spezialanpassungen geschützt.",emoji:"🐦"},
  {q:"How heavy ist das schwerste Vogelei (Strauß) in kg?",a:1.35,unit:"kg",hint:"Strauße legen die größten Eier aller lebenden Vögel.",emoji:"🥚"},
  {q:"How long kann ein Delphin den Atem anhalten in Minuten?",a:15,unit:"minutes",hint:"Delfine schlafen mit einer Gehirnhälfte.",emoji:"🐬"},
  {q:"How many Jahre kann ein Grönlandwal leben?",a:211,unit:"years",hint:"Das langlebigste Säugetier der Erde.",emoji:"🐳"},
  {q:"How heavy ist die Zunge eines Blauwals in kg?",a:2700,unit:"kg",hint:"Die Zunge allein wiegt so viel wie ein Elefant.",emoji:"🐋"},
  {q:"How many million Geruchsrezeptoren hat ein Hund?",a:300,unit:"million",hint:"Menschen haben nur 6 million – Hunde riechen 50x besser.",emoji:"🐕"},
  {q:"How many Meter lang kann ein Bandwurm im Darm werden?",a:25,unit:"meters",hint:"Bandwürmer können jahrelang unbemerkt leben.",emoji:"🪱"},
  {q:"How high ist der Blutdruck einer Giraffe in mmHg?",a:280,unit:"mmHg",hint:"Nötig um Blut 2 Meter nach oben ins Gehirn zu pumpen.",emoji:"🦒"},
  {q:"How many kg Bambus frisst ein Pandabär daily?",a:15,unit:"kg",hint:"Bambus ist sehr nährstoffarm – daher die riesige Menge.",emoji:"🐼"},
  {q:"How long trägt ein Hai seine Jungen in Monaten?",a:24,unit:"months",hint:"Hammerhaie haben die längste Tragzeit.",emoji:"🦈"},
  {q:"How many Augen hat eine Spinne?",a:8,unit:"Augen",hint:"Trotz 8 Augen sehen viele Spinnen sehr schlecht.",emoji:"🕷️"},
  {q:"How many km/h erreicht ein Wanderfalke im Sturzflug?",a:320,unit:"km/h",hint:"Das schnellste Tier der Welt im Sturzflug.",emoji:"🦅"},
  {q:"How many Tonnen wiegt ein ausgewachsener Blauwal?",a:150,unit:"tons",hint:"Das größte Tier das je auf der Erde gelebt hat.",emoji:"🐋"},
  {q:"How many Stunden kann eine Schnecke schlafen am Stück?",a:3,unit:"years",hint:"Schnecken können bis zu 3 Jahre in Kältestarre verbringen.",emoji:"🐌"},
  {q:"How many Elektronen-Volt erzeugt ein Zitteraal?",a:600,unit:"Volt",hint:"Volt – genug um einen Menschen zu betäuben.",emoji:"🐍"},
  {q:"How many km/h rennt ein Nashorn?",a:55,unit:"km/h",hint:"Trotz ihrer Masse sind Nashörner erstaunlich schnell.",emoji:"🦏"},
  {q:"How many Jahre alt kann ein Koi-Fisch werden?",a:226,unit:"years",hint:"Hanako, ein Koi in Japan, lebte 226 Jahre.",emoji:"🐟"},
  {q:"How many Knochen hat eine Schlange?",a:300,unit:"bones",hint:"Je nach Art zwischen 200 und 400 Knochen.",emoji:"🐍"},
  {q:"How many Mal pro Sekunde schlägt eine Biene ihre Flügel?",a:200,unit:"times",hint:"Das erzeugt das charakteristische Summen.",emoji:"🐝"},
  {q:"How many Liter Wasser saugt ein Elefant daily?",a:190,unit:"liters",hint:"Der Rüssel fasst bis zu 15 Liter auf einmal.",emoji:"🐘"},
  {q:"How many Jahre kann eine Schildkröte ohne Nahrung überleben?",a:1,unit:"Jahr",hint:"Schildkröten können ihren Stoffwechsel extrem verlangsamen.",emoji:"🐢"},
  {q:"How far kann ein Flugfisch aus dem Wasser gleiten in Metern?",a:400,unit:"meters",hint:"Flugfische nutzen Wind und Auftrieb zum Gleiten.",emoji:"🐟"},
  {q:"How many Gramm wiegt das Herz eines Blauwals?",a:180000,unit:"grams",hint:"Das Herz ist so groß wie ein kleines Auto.",emoji:"❤️"},
  {q:"How many Stunden schläft ein Löwe per day?",a:20,unit:"hours",hint:"Löwen schlafen mehr als Koalas.",emoji:"🦁"},
  {q:"How many Meter lang wird eine Riesenschlange (Pythons)?",a:7,unit:"meters",hint:"Der Netzpython ist die längste Schlange der Welt.",emoji:"🐍"},
  {q:"How many Eier legt ein weiblicher Oktopus?",a:400000,unit:"Eier",hint:"Sie bewacht sie bis zum Schlüpfen und stirbt danach.",emoji:"🐙"},
  {q:"How many km/h läuft ein Strauß?",a:70,unit:"km/h",hint:"Der schnellste laufende Vogel – und kann nicht fliegen.",emoji:"🦜"},
  {q:"How many Zähne hat ein Weißer Hai?",a:300,unit:"teeth",hint:"In mehreren Reihen – ständig nachwachsend.",emoji:"🦈"},
  {q:"How heavy wird ein Walross maximal in kg?",a:1700,unit:"kg",hint:"Männliche Walrosse sind deutlich schwerer als Weibchen.",emoji:"🦭"},
  {q:"How many Jahre lebt eine Arbeiterin-Biene im Sommer?",a:0.13,unit:"years",hint:"Nur 6 Wochen im Sommer – im Winter bis zu 6 Monate.",emoji:"🐝"},
  {q:"How many Arten von Insekten gibt es auf der Erde (million)?",a:1,unit:"Million Arten",hint:"Über 1 Million bekannte Arten – viele noch unentdeckt.",emoji:"🐛"},
  {q:"How many Herzen hat ein Tintenfisch?",a:3,unit:"Herzen",hint:"Zwei pumpen Blut zu den Kiemen, eines zum Körper.",emoji:"🐙"},
  {q:"How long is die Zunge eines Chamäleons im Verhältnis zum Körper?",a:150,unit:"% Körperlänge",hint:"Die Zunge schlägt mit bis zu 26 km/h aus.",emoji:"🦎"},
  {q:"How many km/h rennt ein Gepard auf kurzer Strecke?",a:112,unit:"km/h",hint:"Beschleunigt von 0 auf 100 in 3 Sekunden.",emoji:"🐆"},
  {q:"How many million Geruchssensoren hat ein Bär?",a:2100,unit:"million",hint:"Bären haben den schärfsten Geruchssinn aller Landtiere.",emoji:"🐻"},
  {q:"How heavy wird ein Polarbär maximal in kg?",a:700,unit:"kg",hint:"Das größte Landraubtier der Erde.",emoji:"🐻‍❄️"},
  {q:"How many Beine hat ein Tausendfüßer on average?",a:750,unit:"Beine",hint:"Nie genau 1000 – trotz des Namens.",emoji:"🐛"},
  {q:"How long kann eine Stubenfliege fliegen ohne zu landen?",a:2,unit:"hours",hint:"Danach braucht sie Ruhe und Nahrung.",emoji:"🪰"},
  {q:"How many Jahre alt wird eine Elefantenschildkröte maximal?",a:190,unit:"years",hint:"Harriet lebte bis 2006 und war ~175 Jahre alt.",emoji:"🐢"},
  {q:"How many km weit wandert ein Monarch-Schmetterling?",a:4000,unit:"km",hint:"Von Kanada bis Mexiko – jedes Jahr.",emoji:"🦋"},
  {q:"How many Gramm wiegt eine Hummel?",a:600,unit:"mg",hint:"Trotz winziger Masse kann sie ein Vielfaches ihres Gewichts tragen.",emoji:"🐝"},
  {q:"How many Stunden per day sucht ein Nashorn Nahrung?",a:12,unit:"hours",hint:"Die Hälfte ihres Lebens verbringen sie mit Fressen.",emoji:"🦏"},
  {q:"How high springt ein Lachs flussaufwärts maximal in Metern?",a:3,unit:"meters",hint:"Lachse springen Wasserfälle hinauf zu ihren Laichgebieten.",emoji:"🐟"},
  {q:"How many Gramm Seide produziert ein Seidenspinner für einen Kokon?",a:500,unit:"mg",hint:"Aus einem Kokon kann man bis zu 1500 Meter Seide spinnen.",emoji:"🪱"},
  {q:"How many Liter Blut verliert ein Moskito wenn er sticht?",a:0.001,unit:"ml",hint:"Ein Moskito saugt etwa 1-3 mg Blut.",emoji:"🦟"},
  {q:"How heavy wird ein ausgewachsener Nilpferd in Tonnen?",a:3,unit:"tons",hint:"Nach Elefant und Nashorn das drittschwerste Landtier.",emoji:"🦛"},
  {q:"How many Stunden schläft eine Giraffe daily?",a:2,unit:"hours",hint:"Giraffen schlafen sehr wenig – in kurzen Phasen.",emoji:"🦒"},
  {q:"How many Gramm wiegt ein Kolibri?",a:3,unit:"grams",hint:"Der kleinste Vogel der Welt wiegt weniger als eine Münze.",emoji:"🐦"},
  {q:"How often schlägt das Herz eines Kolibris pro Minute?",a:1200,unit:"times",hint:"Das schnellste Herz aller Wirbeltiere.",emoji:"🐦"},
  {q:"How far kann ein Känguru in einem einzigen Sprung?",a:9,unit:"meters",hint:"Und dabei 3 Meter hoch.",emoji:"🦘"},
  {q:"How heavy ist das Gehirn eines Elefanten in kg?",a:5,unit:"kg",hint:"Das schwerste Gehirn aller Landtiere.",emoji:"🐘"},
  {q:"How many Kilogramm frisst ein Blauwal daily an Krill?",a:3600,unit:"kg",hint:"Fast 4 Tonnen Krill daily.",emoji:"🐋"},
  {q:"How many Stunden kann ein Albatros nonstop fliegen?",a:10,unit:"hours",hint:"Albatrosse schlafen sogar im Flug.",emoji:"🦅"},
  {q:"How long is die Trächtigkeit einer Maus in Tagen?",a:21,unit:"days",hint:"Mäuse können 10 Mal per year trächtig sein.",emoji:"🐭"},
  {q:"How many Eier legt eine Königin-Ameise per year?",a:300000,unit:"Eier",hint:"Manche Königinnen leben 30 Jahre und legen daily 800 Eier.",emoji:"🐜"},
  {q:"How many km/h läuft ein Schwarzbär?",a:48,unit:"km/h",hint:"Schneller als a human – man kann vor einem Bären nicht weglaufen.",emoji:"🐻"},
  {q:"How deep kann ein Potwal tauchen in Metern?",a:3000,unit:"meters",hint:"Das tiefste Tauchgang eines Säugetiers.",emoji:"🐳"},
  {q:"How many Kilogramm Nahrung frisst ein Gorilla daily?",a:18,unit:"kg",hint:"Gorillas sind reine Vegetarier.",emoji:"🦍"},
  {q:"How long lebt eine Drohnen-Biene?",a:90,unit:"days",hint:"Drohnen leben nur bis zur Paarung – dann sterben sie.",emoji:"🐝"},
  {q:"How many Meter tief gräbt ein Maulwurf seine Tunnel?",a:1,unit:"meters",hint:"Maulwürfe bauen Tunnel-Systeme über 200 Meter Länge.",emoji:"🐀"},
  {q:"How many Jahre lebt ein wilder Schimpanse?",a:45,unit:"years",hint:"In Gefangenschaft können sie über 60 Jahre alt werden.",emoji:"🐒"},
  {q:"How heavy ist der Schädel eines Tyrannosaurus Rex in kg?",a:500,unit:"kg",hint:"Einer der größten Schädel aller fleischfressenden Dinosaurier.",emoji:"🦖"},
  {q:"How many Federn hat ein Schwan?",a:25000,unit:"Federn",hint:"Wasservögel haben besonders viele Federn für die Isolation.",emoji:"🦢"},
  {q:"How many Stunden brütet ein Kaiserpinguin sein Ei?",a:1512,unit:"hours",hint:"63 Tage – ohne Nahrung in antarktischem Winter.",emoji:"🐧"},
  {q:"How far kann ein Gepard in einem Sprung?",a:8,unit:"meters",hint:"Geparden machen enorme Sprünge beim Jagen.",emoji:"🐆"},
  {q:"How many Liter Wasser kann ein Elefant mit dem Rüssel aufnehmen?",a:15,unit:"liters",hint:"Der Rüssel ist ein multifunktionales Werkzeug.",emoji:"🐘"},
  {q:"How many km/h schlägt eine Mantis-Garnele zu?",a:80,unit:"km/h",hint:"Der schnellste Schlag im Tierreich.",emoji:"🦐"},
  {q:"How many million Leukozyten hat a human pro mm³ Blut?",a:7000,unit:"pro mm³",hint:"Immunzellen im Blut.",emoji:"🔬"},
  {q:"How many Stunden schläft ein Delfin per day?",a:8,unit:"hours",hint:"Immer mit einer Gehirnhälfte – die andere bleibt wach.",emoji:"🐬"},
  {q:"How heavy ist die Leber eines Blauwals in kg?",a:1000,unit:"kg",hint:"Alle Organe des Blauwals sind riesig.",emoji:"🐋"},
  {q:"How many Eier kann eine Meeresschildkröte pro Saison legen?",a:200,unit:"Eier",hint:"Nur etwa 1% der Jungtiere überleben bis zur Adultheit.",emoji:"🐢"},
  {q:"How many km weit fliegt ein Zugvogel im Jahr?",a:70000,unit:"km",hint:"Der Küstenseeschwalbe fliegt am weitesten.",emoji:"🐦"},
  {q:"How long kann ein Kamel ohne Wasser überleben in Tagen?",a:15,unit:"days",hint:"Der Höcker speichert Fett, nicht Wasser.",emoji:"🐪"},
  {q:"How many Stunden lebt eine Eintagsfliege als Imago?",a:24,unit:"hours",hint:"Als Larve lebt sie bis zu 3 Jahre.",emoji:"🪲"},
  {q:"How heavy ist das Gehirn eines Pottwals in kg?",a:7,unit:"kg",hint:"Das schwerste Gehirn aller bekannten Tiere.",emoji:"🐳"},
  {q:"How many Flügelschläge macht eine Kolibri pro Sekunde?",a:80,unit:"times",hint:"So schnell, dass die Flügel unsichtbar werden.",emoji:"🐦"},
  {q:"How many km/h läuft eine Gazelle?",a:90,unit:"km/h",hint:"Gazellen sind fast so schnell wie Geparden.",emoji:"🦌"},
  {q:"How deep gräbt ein Erdhörnchen seinen Bau in Metern?",a:3,unit:"meters",hint:"Mit mehreren Ein- und Ausgängen.",emoji:"🐿️"},
  {q:"How many Stacheln hat ein Igel?",a:6000,unit:"Stacheln",hint:"Stacheln sind modifizierte Haare.",emoji:"🦔"},
  {q:"How many Jahre lebt ein Hummer?",a:100,unit:"years",hint:"Hummer altern praktisch nicht – sie werden nur durch Jäger oder Hunger begrenzt.",emoji:"🦞"},
  {q:"How many Mal schlägt das Herz einer Schlange pro Minute?",a:40,unit:"times",hint:"Schlangen haben einen viel langsameren Herzschlag als Säugetiere.",emoji:"🐍"},
  {q:"How far kann eine Springspinne springen in cm?",a:50,unit:"cm",hint:"Das 50-fache ihrer Körperlänge.",emoji:"🕷️"},
  {q:"How many kg frisst ein Tiger daily?",a:8,unit:"kg",hint:"Tiger fressen seltener aber dafür viel auf einmal.",emoji:"🐯"},
  {q:"How many Liter Speichel produziert eine Kuh daily?",a:200,unit:"liters",hint:"Wiederkäuen erfordert enorm viel Speichel.",emoji:"🐄"},
  {q:"How long schläft ein Braunbär im Winterschlaf in Monaten?",a:6,unit:"months",hint:"Kein echter Tiefschlaf – sie können jederzeit aufwachen.",emoji:"🐻"},
  {q:"How many Kilometer wandert ein Weißwal per year?",a:10000,unit:"km",hint:"Weißwale sind wanderfreudige Meeressäuger.",emoji:"🐳"},
  {q:"How many Stunden lebt eine Biene nach dem Stich?",a:1,unit:"Stunde",hint:"Der Stachel verbleibt im Opfer – die Biene stirbt.",emoji:"🐝"},
  {q:"How heavy ist ein Elefantenzahn (Stoßzahn) maximal in kg?",a:100,unit:"kg",hint:"Stoßzähne wachsen ein Leben lang.",emoji:"🐘"},
  {q:"How many Gramm wiegt ein neugeborenes Känguru?",a:1,unit:"grams",hint:"Das Joeys kriecht nach der Geburt in den Beutel.",emoji:"🦘"},
  {q:"How many km/h schwimmt ein Blauwal?",a:30,unit:"km/h",hint:"Bei Gefahr können sie kurze Sprints einlegen.",emoji:"🐋"},
  {q:"How long lebt eine Taschenkrabbe in Jahren?",a:100,unit:"years",hint:"Krabben können sehr alt werden.",emoji:"🦀"},
  {q:"How many Gramm wiegt ein Kolibri-Nest?",a:2,unit:"grams",hint:"Winzige Nester aus Spinnweben und Flechten.",emoji:"🐦"},
  {q:"How many Stunden fliegt eine Hornisse daily?",a:8,unit:"hours",hint:"Hornissen sind aktive Jäger.",emoji:"🐝"},
  {q:"How far kann ein Delfin einen Ball balancieren in Stunden?",a:3,unit:"hours",hint:"Delfine sind die intelligentesten Meerestiere.",emoji:"🐬"},
  {q:"How many Jahre kann ein Krokodil ohne Nahrung überleben?",a:3,unit:"years",hint:"Krokodile haben einen extrem niedrigen Stoffwechsel.",emoji:"🐊"},
  {q:"How heavy ist der Penis eines Blauwals in kg?",a:450,unit:"kg",hint:"Das größte Geschlechtsorgan im Tierreich.",emoji:"🐋"},
  {q:"How long ist ein Blauwal-Penis in Metern?",a:2.7,unit:"meters",hint:"Proportional zum Körper aber das absolut größte.",emoji:"🐋"},
  {q:"How many Eizellen produziert eine Ozean-Sonnenblume pro Saison?",a:300000000,unit:"Eier",hint:"300 million Eier – die meisten aller Wirbeltiere.",emoji:"🐟"},
  {q:"How many Liter Blut pumpt ein Elefantenherz pro Minute?",a:300,unit:"liters",hint:"Das Elefantenherz wiegt 25 kg.",emoji:"🐘"},
  {q:"How many Stunden kann eine Nacktmull-Ratte ohne Sauerstoff überleben?",a:18,unit:"hours",hint:"Nacktmull-Ratten sind gegen Sauerstoffmangel resistent.",emoji:"🐀"},
  {q:"How heavy ist das Gehirn eines Octopus in Gramm?",a:40,unit:"grams",hint:"Sehr klein aber extrem effizient.",emoji:"🐙"},
  {q:"How many Chromatophoren hat ein Tintenfisch?",a:10000000,unit:"Chromatophoren",hint:"Diese Farbzellen ermöglichen blitzschnelle Farbwechsel.",emoji:"🦑"},
  {q:"How many Meter lang ist ein Bandwurm maximal?",a:30,unit:"meters",hint:"Fischbandwürmer können bis zu 30m lang werden.",emoji:"🪱"},
  {q:"How many Mal pro Nacht hört eine Eule?",a:360,unit:"Grad",hint:"Eulen können den Kopf 270 Grad drehen.",emoji:"🦉"},
  {q:"How heavy ist ein Ochsen-Frosch in kg?",a:3,unit:"kg",hint:"Der schwerste Frosch der Welt.",emoji:"🐸"},
  {q:"How many Liter Honig produziert ein Bienenvolk per year?",a:30,unit:"liters",hint:"Für ein Glas Honig fliegen Bienen 80.000 km.",emoji:"🍯"},
  {q:"How long is die Trächtigkeit eines Schwarzen Rhinozeros in Tagen?",a:450,unit:"days",hint:"15 Monate – eine der längsten Tragezeiten.",emoji:"🦏"},
  {q:"How many Stunden lebt eine Eintagsfliegen-Larve bevor sie schlüpft?",a:26280,unit:"hours",hint:"3 Jahre als Larve, dann 1 Tag als Erwachsener.",emoji:"🪲"},
  {q:"How deep taucht ein Kaiserpinguin maximal in Metern?",a:565,unit:"meters",hint:"Der tieftauchende Vogel der Welt.",emoji:"🐧"},
  {q:"How many Gramm wiegt das Herz eines Pferdes?",a:4500,unit:"grams",hint:"Das große Herz ist der Schlüssel zur Ausdauer.",emoji:"🐴"},
  {q:"How far kann ein Lemur springen in Metern?",a:10,unit:"meters",hint:"Lemure sind erstaunliche Springer.",emoji:"🐒"},
  {q:"How many km/h kann eine Libelle fliegen?",a:55,unit:"km/h",hint:"Eine der schnellsten fliegenden Insekten.",emoji:"🪲"},
  {q:"How long lebt eine Dragonfly in Wochen als Erwachsener?",a:4,unit:"weeks",hint:"Als Larve lebt sie bis zu 5 Jahre.",emoji:"🪲"},
  {q:"How heavy ist ein ausgewachsenes Nilpferd-Zahn in kg?",a:3,unit:"kg",hint:"Die Eckzähne sind reine Waffen.",emoji:"🦛"},
  {q:"How many Tentakel hat ein Oktopus?",a:8,unit:"Tentakel",hint:"Jeder Arm hat eigene Nervenzellen.",emoji:"🐙"},
  {q:"How far kann ein Flachlandgorilla seinen Ruf hören in km?",a:2,unit:"km",hint:"Gorillas kommunizieren über weite Distanzen.",emoji:"🦍"},
  {q:"How many Mal pro Sekunde bewegt ein Schwertfisch die Schwanzflosse?",a:3,unit:"times",hint:"Kraftvolle langsame Bewegungen für hohe Geschwindigkeit.",emoji:"🐟"},
  {q:"How long is die Nasenspitze eines Elefanten-Rüssels?",a:250,unit:"cm",hint:"Der Rüssel ist der verlängerte Nasenrücken.",emoji:"🐘"},
  {q:"How many Liter Wasser trinkt ein Kamel auf einmal nach der Wüste?",a:100,unit:"liters",hint:"In 13 Minuten kann ein Kamel 100 Liter trinken.",emoji:"🐪"},
  {q:"How heavy ist ein Blauwalhoden in kg?",a:35,unit:"kg",hint:"Jeder Hoden wiegt erstaunlich viel kg – zusammen 70 kg.",emoji:"🐋"},
  {q:"How many Stunden alt werden Libellen-Larven bevor sie schlüpfen?",a:35040,unit:"hours",hint:"4 Jahre als Larve im Wasser.",emoji:"🪲"},
  {q:"How many Farben kann ein Tintenfisch gleichzeitig anzeigen?",a:30,unit:"Farben",hint:"Obwohl farbenblind – der Farbwechsel dient der Tarnung.",emoji:"🦑"},
  {q:"How fast regeneriert ein Seestern seinen Arm in Wochen?",a:52,unit:"weeks",hint:"Ein Jahr – und aus dem abgetrennten Arm wächst ein neuer Seestern.",emoji:"⭐"},
  {q:"How many Jahre kann eine Qualle (Turritopsis dohrnii) theoretisch leben?",a:9999,unit:"years",hint:"Die biologisch unsterbliche Qualle kann sich unbegrenzt verjüngen.",emoji:"🪼"},
  {q:"How many km/h kann ein Gepard auf 100m beschleunigen?",a:75,unit:"km/h",hint:"Beschleunigung von 0 auf 75 in 2 Sekunden.",emoji:"🐆"},
  {q:"How many Kilogramm wiegt ein ausgewachsener Jaguar?",a:100,unit:"kg",hint:"Der schwerste Großkatze Amerikas.",emoji:"🐆"},
  {q:"How many Augen hat eine Libelle?",a:30000,unit:"Facetten",hint:"Zusammengesetzte Augen mit 30.000 Einzellinsen.",emoji:"🪲"},
  {q:"How far kann ein Springer-Frosch springen in cm?",a:530,unit:"cm",hint:"Vielfaches der eigenen Körperlänge.",emoji:"🐸"},
  {q:"How many Stunden daily ist eine Hauskatze aktiv?",a:5,unit:"hours",hint:"Hauskatzen schlafen 16-20 Stunden daily.",emoji:"🐱"},
  {q:"How many Gramm Honig isst ein Bär in einem Sommer?",a:40000,unit:"grams",hint:"40 kg Honig – Bären lieben Bienenstöcke.",emoji:"🐻"},
  {q:"How many km/h kann ein Tintenfisch schwimmen?",a:40,unit:"km/h",hint:"Durch rückwärtiges Ausstoßen von Wasser.",emoji:"🦑"},
  {q:"How long is die Zunge eines Ameisenbären in cm?",a:60,unit:"cm",hint:"Die klebrige Zunge fährt 150 Mal pro Minute aus.",emoji:"🐜"},
  {q:"How many Stunden am Tag weidet ein Pferd?",a:16,unit:"hours",hint:"Pferde fressen fast nonstop.",emoji:"🐴"},
  {q:"How heavy ist ein ausgewachsener Gorilla-Arm in kg?",a:15,unit:"kg",hint:"Gorillas sind 6 Mal stärker als Menschen.",emoji:"🦍"},
  {q:"How many Liter Blut pumpt ein Giraffenherz pro Minute?",a:60,unit:"liters",hint:"Das Giraffenherz wiegt 10 kg.",emoji:"🦒"},
  {q:"How many km kann eine Wüstenameise ohne Orientierungshilfe navigieren?",a:50,unit:"km",hint:"Sie nutzen Polarisationsmuster des Himmels.",emoji:"🐜"},
  {q:"How many Knochen hat ein Delfin?",a:200,unit:"bones",hint:"Delfine haben Knochen wo einst Hinterbeine waren.",emoji:"🐬"},
  {q:"How deep können Maulwürfe ihre Tunnels anlegen?",a:70,unit:"cm",hint:"Haupttunnel liegen tiefer als Jagdtunnel.",emoji:"🐀"},
  {q:"How many Stunden kann ein Flamingo auf einem Bein stehen?",a:4,unit:"hours",hint:"Das Stehen auf einem Bein kostet weniger Energie.",emoji:"🦩"},
  {q:"How many Ton frisst ein Blauwal an einem Tag?",a:3.6,unit:"tons",hint:"Fast 4 Tonnen Krill daily.",emoji:"🐋"},
  {q:"How far kann eine Heuschrecke springen in Metern?",a:1,unit:"meters",hint:"Das 20-fache ihrer eigenen Körperlänge.",emoji:"🦗"},
  {q:"How many Jahre kann ein Elefant leben?",a:70,unit:"years",hint:"In Gefangenschaft werden sie manchmal über 80.",emoji:"🐘"},
  {q:"How heavy ist ein neugeborener Blauwal in Tonnen?",a:2.7,unit:"tons",hint:"Das Größte Neugeborene der Welt.",emoji:"🐋"},
  {q:"How many Stunden schläft ein Totenkopf-Äffchen daily?",a:11,unit:"hours",hint:"Totenkopfäffchen sind echte Schläfer.",emoji:"🐒"},
  {q:"How long is ein Elefantenrüssel in Metern?",a:2,unit:"meters",hint:"Er hat über 40.000 Muskeln.",emoji:"🐘"},
  {q:"How many Eier legt eine Königin-Ameise daily?",a:800,unit:"Eier",hint:"Über ihr ganzes Leben bis zu 30 million Eier.",emoji:"🐜"},
  {q:"How long is die Trächtigkeit eines Schwertwals in Monaten?",a:17,unit:"months",hint:"Orcas haben eine der längsten Tragezeiten.",emoji:"🐋"},
  {q:"How many Stunden verbringt ein Tier im Wasser daily (Nilpferd)?",a:16,unit:"hours",hint:"Nilpferde kühlen sich und schützen ihre Haut.",emoji:"🦛"},
  {q:"How many Gramm wiegt ein Pfauenschwanz-Feder?",a:5,unit:"grams",hint:"Trotz ihrer Größe extrem leicht.",emoji:"🦚"},
  {q:"How many Stacheln hat ein Igel auf dem Rücken?",a:5000,unit:"Stacheln",hint:"Jeder Stachel ist ein modifiziertes Haar.",emoji:"🦔"},
  {q:"How far kann ein Fliegendes Eichhörnchen gleiten in Metern?",a:90,unit:"meters",hint:"Mit der Gleitfalte zwischen Vorder- und Hinterbeinen.",emoji:"🐿️"},
  {q:"How many km/h läuft ein Erdferkel?",a:40,unit:"km/h",hint:"Überraschend schnell für ein scheinbar gemächliches Tier.",emoji:"🐷"},
  {q:"How heavy ist ein ausgewachsener männlicher Elefant-Rüsseltier in kg?",a:6000,unit:"kg",hint:"Afrikanische Elefanten sind schwerer als asiatische.",emoji:"🐘"},
  {q:"How many Liter Milch trinkt ein Blauwal-Baby daily?",a:600,unit:"liters",hint:"Es wächst daily um 90 kg.",emoji:"🐋"},
  {q:"How many Stunden verbringt ein Flamingo im Wasser daily?",a:12,unit:"hours",hint:"Flamingos filtern Nahrung aus Schlamm.",emoji:"🦩"},
  {q:"How long is die Trächtigkeit eines Nashorns in Monaten?",a:16,unit:"months",hint:"Nashörner bekommen nur alle 2-5 Jahre ein Junges.",emoji:"🦏"},
  {q:"How many Gramm wiegt eine Honigbiene?",a:100,unit:"mg",hint:"Nur 100 Milligramm – aber immens wichtig.",emoji:"🐝"},
  {q:"How far kann ein Fliegender Fisch aus dem Wasser herausgleiten?",a:400,unit:"meters",hint:"Flugfische nutzen Wind und Auftrieb.",emoji:"🐟"},
  {q:"How many Jahre lebt ein Walross?",a:40,unit:"years",hint:"Walrosse werden in der Wildnis bis zu 40 Jahre alt.",emoji:"🦭"},
  {q:"How heavy ist die Schildkrötenpanzer eines Riesenschildkröte in kg?",a:30,unit:"kg",hint:"Der Panzer macht ein Drittel des Körpergewichts aus.",emoji:"🐢"},
  {q:"How many Stunden am Tag reinigt sich eine Katze?",a:5,unit:"hours",hint:"Ein Drittel ihrer Wachzeit verbringen Katzen mit Putzen.",emoji:"🐱"},
  {q:"How many Gramm wiegt ein Pinguin-Ei?",a:450,unit:"grams",hint:"Kaiserpinguin-Eier sind riesig im Verhältnis zum Körper.",emoji:"🐧"},
  {q:"How far kann ein Gepard seinen Geruchssinn nutzen in km?",a:3,unit:"km",hint:"Geparden nutzen hauptsächlich das Sehen.",emoji:"🐆"},
  {q:"How many Zähne hat ein Delfin?",a:100,unit:"teeth",hint:"Delfine benutzen Zähne zum Fangen, nicht zum Kauen.",emoji:"🐬"},
  {q:"How long is die Zunge einer Kuh in cm?",a:45,unit:"cm",hint:"Kühe lecken sich die Nase damit sauber.",emoji:"🐄"},
  {q:"How many Stacheln hat ein Stachelrochen?",a:1,unit:"Stachel",hint:"Nur ein Giftstachel – aber sehr schmerzhaft.",emoji:"🐟"},
  {q:"How heavy ist ein Gorilla-Silberrücken in kg?",a:250,unit:"kg",hint:"Silberrücken dominieren ihre Gruppe.",emoji:"🦍"},
  {q:"How far kann ein Springhase springen in Metern?",a:3,unit:"meters",hint:"Springhasen sind afrikanische Nager.",emoji:"🐇"},
  {q:"How many km/h erreicht eine Schildkröte beim Schwimmen?",a:35,unit:"km/h",hint:"Lederschildkröten sind erstaunlich schnelle Schwimmer.",emoji:"🐢"},
  {q:"How many Gramm Futter frisst eine Raupe daily im Verhältnis zum Körpergewicht?",a:200,unit:"% Körpergewicht",hint:"Raupen verdoppeln ihr Gewicht in Tagen.",emoji:"🐛"},
  {q:"How many Stunden lebt eine Hausfliegenmaggot bis zur Verpuppung?",a:240,unit:"hours",hint:"10 Tage als Made, dann Puppe.",emoji:"🪰"},
  {q:"How long is der Dünndarm einer Kuh in Metern?",a:40,unit:"meters",hint:"Kühe haben ein sehr langes Verdauungssystem.",emoji:"🐄"},
  {q:"How many Liter Speichel produziert ein Pferd daily?",a:40,unit:"liters",hint:"Pferde brauchen viel Speichel für die Verdauung.",emoji:"🐴"},
  {q:"How heavy ist ein Schimpansen-Arm im Vergleich zu einem menschlichen?",a:2,unit:"x stärker",hint:"Schimpansen sind doppelt so stark wie Menschen.",emoji:"🐒"},
  {q:"How far wandert ein Elch per year in km?",a:300,unit:"km",hint:"Elche folgen Nahrung und Wetter.",emoji:"🦌"},
  {q:"How many Stunden braucht eine Schlange für die Verdauung einer großen Mahlzeit?",a:168,unit:"hours",hint:"Eine Woche für ein großes Tier.",emoji:"🐍"},
  {q:"How many Gramm wächst ein Blauwal-Baby daily?",a:90000,unit:"grams",hint:"90 kg daily – 7 Monate lang gestillt.",emoji:"🐋"},
  {q:"How far kann ein Albatros in einem einzigen Flug zurücklegen?",a:10000,unit:"km",hint:"Albatrosse umrunden die Erde im Südpolarmeer.",emoji:"🦅"},
  {q:"How many Jahre ist ein Elefant geschlechtsreif?",a:14,unit:"years",hint:"Elefantenbullen treten erst mit 14 in die Brunst.",emoji:"🐘"},
  {q:"How many Liter Blut hat ein Nashorn?",a:20,unit:"liters",hint:"Proportional weniger als ein Elefant.",emoji:"🦏"},
  {q:"How long is die Trächtigkeit eines Orcas in Monaten?",a:17,unit:"months",hint:"Eine der längsten Tragezeiten unter Meeressäugern.",emoji:"🐋"},
  {q:"How many Gramm frisst ein Igel daily?",a:70,unit:"grams",hint:"Insekten, Würmer und kleine Wirbeltiere.",emoji:"🦔"},
  {q:"How far kann ein Springbock in einem Sprung?",a:15,unit:"meters",hint:"Springböcke machen hohe Luftsprünge als Warnsignal.",emoji:"🦌"},
  {q:"How many Federn verliert ein Vogel annually beim Mausern?",a:10000,unit:"Federn",hint:"Vögel erneuern ihr Gefieder annually komplett.",emoji:"🐦"},
  {q:"How heavy kann ein Riesenkalmars Mantel in kg werden?",a:150,unit:"kg",hint:"Riesenkalmare sind die größten wirbellosen Tiere.",emoji:"🦑"},
  {q:"How many Stunden lebt eine Stubenfliege insgesamt?",a:500,unit:"hours",hint:"Nur 3 Wochen – in dieser Zeit legen sie Eier.",emoji:"🪰"},
  {q:"How many Zellen hat ein Regenwurm?",a:1000,unit:"Segmente",hint:"Regenwürmer können in jedem Segment nachwachsen.",emoji:"🪱"},
  {q:"How far wandert ein Monarch-Schmetterling per day?",a:80,unit:"km",hint:"In 2 Monaten von Kanada nach Mexiko.",emoji:"🦋"},
  {q:"How heavy ist ein Schimpansen-Gehirn im Vergleich zum Menschen in %?",a:33,unit:"% des Menschengehirns",hint:"Schimpansen-Gehirn wiegt ~400g, menschliches ~1400g.",emoji:"🐒"},
  {q:"How many Stunden daily verbringt ein Orang-Utan in Bäumen?",a:24,unit:"hours",hint:"Orang-Utans sind die größten Baumklettertiere.",emoji:"🦧"},
  {q:"How many Eier legt eine Ozean-Qualle per year?",a:45000,unit:"Eier",hint:"Quallen können sich auch vegetativ vermehren.",emoji:"🪼"},
  {q:"How far kann eine Flossenfüßer-Robbe schwimmen daily?",a:100,unit:"km",hint:"Robben sind ausdauernde Schwimmer.",emoji:"🦭"},
  {q:"How heavy ist ein Erdwurm in Gramm?",a:5,unit:"grams",hint:"Ein normaler Regenwurm wiegt 3-10g.",emoji:"🪱"},
  {q:"How far können Elefanten eine Wasserstelle riechen in km?",a:19,unit:"km",hint:"Elefanten haben den feinsten Geruchssinn aller Landtiere.",emoji:"🐘"},
  {q:"How many Stunden braucht ein Schmetterling für die Metamorphose?",a:336,unit:"hours",hint:"2 Wochen im Kokon.",emoji:"🦋"},
  {q:"How many kg Gras frisst ein Pferd daily?",a:11,unit:"kg",hint:"Pferde sind reine Pflanzenfresser.",emoji:"🐴"},
  {q:"How far kann ein Seehund tauchen in Metern?",a:300,unit:"meters",hint:"Seehunde können bis zu 30 Minuten tauchen.",emoji:"🦭"},
  {q:"How many Zähne hat ein Hecht?",a:700,unit:"teeth",hint:"Hechte haben mehrere Reihen kleiner Zähne.",emoji:"🐟"},
  {q:"How heavy ist ein Marien-Käfer in Milligramm?",a:25,unit:"mg",hint:"Trotz winziger Größe frisst er daily 100 Blattläuse.",emoji:"🐞"},
  {q:"How far kann eine Wüstenspringmaus in einem Sprung?",a:3,unit:"meters",hint:"Relative Sprungweite: 45x die eigene Körperlänge.",emoji:"🐭"},
  {q:"How many Stunden lebt ein Schmetterlingsweibchen nach der Paarung?",a:2,unit:"weeks",hint:"Manche Schmetterlinge leben nur wenige Tage.",emoji:"🦋"},
  {q:"How heavy ist ein Pelikan-Beutel wenn voll in Liter?",a:13,unit:"liters",hint:"Der Kehlsack fasst mehr als der Magen.",emoji:"🐦"},
  {q:"How many kg Fisch frisst ein ausgewachsener Weißer Hai daily?",a:11,unit:"kg",hint:"Haie fressen selten – dafür viel auf einmal.",emoji:"🦈"},
  {q:"How far können Wale Töne unter Wasser hören in km?",a:3000,unit:"km",hint:"Finnwale kommunizieren über Tausende Kilometer.",emoji:"🐋"},
  {q:"How many Stunden daily verbringt ein Faultier mit Bewegen?",a:3,unit:"hours",hint:"Der Rest des Tages wird mit Schlafen verbracht.",emoji:"🦥"},
  {q:"How heavy ist die Leber eines Weißen Hais in kg?",a:500,unit:"kg",hint:"Die enorme Leber dient als Auftriebsorgan.",emoji:"🦈"},
  {q:"How long is die Trächtigkeit eines Gürteltiers in Monaten?",a:4,unit:"months",hint:"Gürteltiere gebären immer eineiige Vierlings.",emoji:"🐾"},
  {q:"How far springt ein Delfin aus dem Wasser in Metern?",a:6,unit:"meters",hint:"Breaching ist ein wichtiges Kommunikationsmittel.",emoji:"🐬"},
  {q:"How many Stunden lebt eine Stubenfliege als Larve?",a:120,unit:"hours",hint:"5 Tage als Maggot.",emoji:"🪰"},
  {q:"How heavy ist ein ausgewachsener Schimpansen in kg?",a:60,unit:"kg",hint:"Trotz geringerer Größe 6x stärker als a human.",emoji:"🐒"},
  {q:"How many Tentakel hat eine Qualle?",a:80,unit:"Tentakel",hint:"Je nach Art zwischen 4 und hunderten Tentakeln.",emoji:"🪼"},
  {q:"How far kann ein Krokodil aus dem Wasser herausspringen?",a:1.5,unit:"meters",hint:"Krokodile sind überraschend agil.",emoji:"🐊"},
  {q:"How many Gramm frisst eine Hausmaus daily?",a:5,unit:"grams",hint:"Ein Siebtel ihres Körpergewichts daily.",emoji:"🐭"},
  {q:"How heavy ist ein weiblicher Elefant maximal in Tonnen?",a:4,unit:"tons",hint:"Weibliche Elefanten sind kleiner als die Männchen.",emoji:"🐘"},
  {q:"How many Stunden kann ein Hamster daily im Rad laufen?",a:8,unit:"hours",hint:"Hamster legen im Rad bis zu 20 km pro Nacht zurück.",emoji:"🐹"},
  {q:"How far kann ein Kugelfisch aufblähen in cm Durchmesser?",a:90,unit:"cm",hint:"Kugelfische saugen Wasser an um sich aufzublähen.",emoji:"🐡"},
  {q:"How many Liter Milch trinkt ein Elefantenbaby daily?",a:10,unit:"liters",hint:"Elefantenbabys werden 2-3 Jahre gestillt.",emoji:"🐘"},
  {q:"How heavy ist ein Spinnwebnetz in Milligramm?",a:0.5,unit:"mg",hint:"Unglaublich leicht aber stärker als Stahl.",emoji:"🕸️"},
  {q:"How long is die Trächtigkeit eines Dachses in Wochen?",a:7,unit:"weeks",hint:"Dachse legen die Trächtigkeit auf günstige Jahreszeiten aus.",emoji:"🦡"},
  {q:"How many Stunden schläft ein Gorilla daily?",a:12,unit:"hours",hint:"Gorillas bauen daily neue Schlafnester.",emoji:"🦍"},
  {q:"How far kann ein Weißer Hai seine Kiefer vorschnellen?",a:30,unit:"cm",hint:"Der Kiefer schnellt beim Beißen weit vor.",emoji:"🦈"},
  {q:"How many Eier legt eine Riesenmeeresschildkröte in einem Nest?",a:100,unit:"Eier",hint:"Sie legen mehrere Male pro Saison.",emoji:"🐢"},
  {q:"How many Stunden daily verbringt ein Fisch mit Schlafen?",a:4,unit:"hours",hint:"Fische schlafen mit offenen Augen.",emoji:"🐟"},
  {q:"How far können Elefanten kommunizieren per Infraschall in km?",a:10,unit:"km",hint:"Tiefe Töne propagieren weit durch den Boden.",emoji:"🐘"},
  {q:"How many kg Nahrung frisst ein Nilpferd daily?",a:40,unit:"kg",hint:"Nilpferde fressen nachts an Land.",emoji:"🦛"},
  {q:"How heavy ist ein Gepard-Baby bei Geburt in Gramm?",a:250,unit:"grams",hint:"Geparden sind bei Geburt blind und hilflos.",emoji:"🐆"},
  {q:"How many Stunden dauert eine Tiger-Jagd?",a:1,unit:"Stunde",hint:"Nur 1 von 10 Jagdversuchen ist erfolgreich.",emoji:"🐯"},
  {q:"How far können Delfinpfeifen unter Wasser gehört werden in km?",a:40,unit:"km",hint:"Delfine kommunizieren über enorme Distanzen.",emoji:"🐬"},
  {q:"How many Gramm wiegt ein Stachel einer Biene?",a:3,unit:"mg",hint:"Nur 3 Milligramm aber tödliches Gift.",emoji:"🐝"},
  {q:"How deep kann eine Langschwanzkatze ihr Revier markieren in Metern?",a:50,unit:"cm Höhe",hint:"Markierungen werden auf Augenhöhe angebracht.",emoji:"🐈"},
  {q:"How many Stunden daily gehen Wölfe auf Jagd?",a:8,unit:"hours",hint:"Wölfe legen daily 30-50 km zurück.",emoji:"🐺"},
];
