// 🏛️ POLITICS & POWER – English
export default [
  {q:"How many Jahre war Angela Merkel Bundeskanzlerin?",a:16,unit:"years",hint:"Von 2005 bis 2021.",emoji:"🇩🇪"},
  {q:"How many Länder sind Mitglied der UNO?",a:193,unit:"countries",hint:"Gegründet 1945 mit 51 Mitgliedern.",emoji:"🌍"},
  {q:"How many billion Dollar gibt die USA für Wahlkampf pro Präsidentschaftswahl aus?",a:14,unit:"billion $",hint:"2020 war die teuerste Wahl der Geschichte.",emoji:"🗳️"},
  {q:"How many Personen hat der US-Senat?",a:100,unit:"Senatoren",hint:"2 pro Bundesstaat – 50 Staaten.",emoji:"🏛️"},
  {q:"How many Länder sind in der EU?",a:27,unit:"countries",hint:"Nach dem Brexit – Großbritannien trat 2020 aus.",emoji:"🇪🇺"},
  {q:"How many Jahre saß Adolf Hitler an der Macht?",a:12,unit:"years",hint:"Von 1933 bis 1945.",emoji:"☮️"},
  {q:"How many percent der Deutschen gehen zur Bundestagswahl?",a:76,unit:"%",hint:"Wahlbeteiligung 2021.",emoji:"🗳️"},
  {q:"How many Mitglieder hat der Bundestag?",a:736,unit:"Abgeordnete",hint:"Nach der Wahl 2021 – Rekordgröße.",emoji:"🏛️"},
  {q:"In what year hielt Martin Luther King seine 'I Have a Dream' Rede?",a:1963,unit:"Jahr",hint:"Am 28. August 1963 in Washington.",emoji:"✊"},
  {q:"How many Länder haben eine Atombombe?",a:9,unit:"countries",hint:"USA, Russland, UK, Frankreich, China, Indien, Pakistan, Israel, Nordkorea.",emoji:"☢️"},
  {q:"How many million Dollar verdient ein US-Präsident per year?",a:400,unit:"Tausend Dollar",hint:"000 Dollar annually.",emoji:"🏛️"},
  {q:"How many Personen hat das Europäische Parlament?",a:720,unit:"Abgeordnete",hint:"Stand nach der Wahl 2024.",emoji:"🇪🇺"},
  {q:"How many Länder sind im G20?",a:20,unit:"countries",hint:"Eigentlich 19 Länder + EU.",emoji:"🌍"},
  {q:"How many billion Euro kostet die EU-Bürokratie per year?",a:170,unit:"billion €",hint:"Das EU-Gesamtbudget.",emoji:"🇪🇺"},
  {q:"How many Jahre regierte Kim Jong-il Nordkorea?",a:17,unit:"years",hint:"Von 1994 bis zu seinem Tod 2011.",emoji:"🇰🇵"},
  {q:"How many million Dollar wert ist Donald Trumps Vermögen?",a:3000,unit:"million $",hint:"Schwankt stark – Stand 2024.",emoji:"🏙️"},
  {q:"How many Länder haben eine Monarchie?",a:43,unit:"countries",hint:"Darunter 16 mit dem britischen König als Staatsoberhaupt.",emoji:"👑"},
  {q:"How many billion Euro gibt Deutschland für Entwicklungshilfe aus?",a:32,unit:"billion €",hint:"Einer der größten Geber worldwide.",emoji:"🤝"},
  {q:"How many Sekretäre hatte die CIA insgesamt?",a:21,unit:"Direktoren",hint:"Seit Gründung 1947.",emoji:"🕵️"},
  {q:"In what year wurde die Todesstrafe in Deutschland abgeschafft?",a:1949,unit:"Jahr",hint:"Im Grundgesetz festgeschrieben.",emoji:"⚖️"},
  {q:"How many billion Dollar verdient der US-Rüstungskonzern Lockheed Martin per year?",a:67,unit:"billion $",hint:"Der größte Rüstungskonzern der Welt.",emoji:"✈️"},
  {q:"How many Jahre war Fidel Castro an der Macht in Kuba?",a:49,unit:"years",hint:"Von 1959 bis 2008.",emoji:"🇨🇺"},
  {q:"How many Länder haben Russland nach dem Ukraine-Einmarsch sanktioniert?",a:40,unit:"countries",hint:"Stand 2022.",emoji:"🇷🇺"},
  {q:"In what year wurde der Internationale Strafgerichtshof gegründet?",a:2002,unit:"Jahr",hint:"In Den Haag, Niederlande.",emoji:"⚖️"},
  {q:"How many million Stimmen erhielt Obama bei seiner ersten Wahl?",a:69,unit:"million",hint:"2008 gegen John McCain.",emoji:"🗳️"},
  {q:"In what year fand der erste G7-Gipfel statt?",a:1975,unit:"Jahr",hint:"In Rambouillet, Frankreich.",emoji:"🌍"},
  {q:"How many Personen sitzen im britischen Unterhaus?",a:650,unit:"Abgeordnete",hint:"House of Commons.",emoji:"🏴󠁧󠁢󠁥󠁮󠁧󠁿"},
  {q:"How many billion Euro kostet die deutsche Bundeswehr per year?",a:52,unit:"billion €",hint:"Nach der Zeitenwende 2022 stark erhöht.",emoji:"⚔️"},
  {q:"In what year wurde Boris Johnson britischer Premierminister?",a:2019,unit:"Jahr",hint:"Nach Theresa May.",emoji:"🇬🇧"},
  {q:"How many Länder sind in der OPEC?",a:13,unit:"countries",hint:"Organisation erdölexportierender Länder.",emoji:"🛢️"},
  {q:"How many billion Dollar wert ist Vladimir Putins geschätztes Vermögen?",a:200,unit:"billion $",hint:"Schätzungen – inoffiziell.",emoji:"🇷🇺"},
  {q:"In what year wurde der Europäische Gerichtshof gegründet?",a:1952,unit:"Jahr",hint:"In Luxemburg.",emoji:"🇪🇺"},
  {q:"How many Personen haben je den US-Präsidenten ermordet?",a:4,unit:"Präsidenten",hint:"Lincoln, Garfield, McKinley, Kennedy.",emoji:"🏛️"},
  {q:"How many million Mitglieder hat die SPD?",a:380,unit:"thousand",hint:"000 Mitglieder – stark gesunken.",emoji:"🌹"},
  {q:"In what year wurde die Todesstrafe in Frankreich abgeschafft?",a:1981,unit:"Jahr",hint:"Unter Präsident Mitterrand.",emoji:"🇫🇷"},
  {q:"How many Länder haben keine eigene Armee?",a:23,unit:"countries",hint:"Darunter Island, Costa Rica, Panama.",emoji:"🕊️"},
  {q:"How many billion Dollar gibt China annually für Spionage aus?",a:20,unit:"billion $",hint:"Schätzungen westlicher Geheimdienste.",emoji:"🕵️"},
  {q:"In what year trat das Kyoto-Protokoll in Kraft?",a:2005,unit:"Jahr",hint:"Verabschiedet 1997, in Kraft 2005.",emoji:"🌍"},
  {q:"How many million Menschen stimmten beim Brexit?",a:33,unit:"million",hint:"51,9% für Leave.",emoji:"🇬🇧"},
  {q:"How many Jahre ist Kim Jong-un an der Macht?",a:13,unit:"years",hint:"Seit dem Tod seines Vaters 2011.",emoji:"🇰🇵"},
  {q:"In what year wurde das Grundgesetz verabschiedet?",a:1949,unit:"Jahr",hint:"Am 23. Mai 1949.",emoji:"🇩🇪"},
  {q:"How many billion Dollar kostet der UN-Haushalt per year?",a:3,unit:"billion $",hint:"Reguläres Budget – ohne Friedensmissionen.",emoji:"🌍"},
  {q:"How many percent der Weltbevölkerung lebt in Demokratien?",a:46,unit:"%",hint:"Stand 2023 – sinkende Tendenz.",emoji:"🗳️"},
  {q:"In what year hielt Churchill seine 'Iron Curtain' Rede?",a:1946,unit:"Jahr",hint:"In Fulton, Missouri.",emoji:"🇬🇧"},
  {q:"How many billion Dollar wert ist Elon Musks politischer Einfluss bei X?",a:44,unit:"billion $",hint:"What er für Twitter/X bezahlt hat.",emoji:"𝕏"},
  {q:"How many Sitze hat die CDU/CSU im aktuellen Bundestag?",a:197,unit:"Sitze",hint:"Nach der Bundestagswahl 2025.",emoji:"🇩🇪"},
  {q:"In what year fand die Französische Revolution statt?",a:1789,unit:"Jahr",hint:"Sturm auf die Bastille am 14. Juli.",emoji:"🗽"},
  {q:"How many billion Dollar gibt Saudi-Arabien für Lobbying in den USA aus?",a:100,unit:"million $",hint:"Offiziell – inoffiziell viel mehr.",emoji:"🇸🇦"},
  {q:"How many Jahre war Helmut Kohl Bundeskanzler?",a:16,unit:"years",hint:"Von 1982 bis 1998.",emoji:"🇩🇪"},
  {q:"In what year wurde die Türkei Mitglied der NATO?",a:1952,unit:"Jahr",hint:"Zusammen mit Griechenland.",emoji:"🇹🇷"},
  {q:"How many million Flüchtlinge gab es worldwide 2023?",a:110,unit:"million",hint:"Rekordhohe Zahlen durch Krisen.",emoji:"🏕️"},
  {q:"How many percent der deutschen Bundestagsabgeordneten sind Frauen?",a:35,unit:"%",hint:"Stand nach der Wahl 2021.",emoji:"👩"},
  {q:"How many million Euro verdient ein EU-Kommissar per year?",a:250,unit:"Tausend Euro",hint:"Inklusive Zulagen.",emoji:"🇪🇺"},
  {q:"How many Atomsprengköpfe hat Russland?",a:5977,unit:"Sprengköpfe",hint:"Stand 2023 – größtes Arsenal worldwide.",emoji:"☢️"},
  {q:"In what year wurde der Warschauer Pakt aufgelöst?",a:1991,unit:"Jahr",hint:"Gleichzeitig mit dem Zerfall der Sowjetunion.",emoji:"☭"},
  {q:"How many billion Dollar wert ist der globale Lobbyismus-Markt?",a:3,unit:"billion $",hint:"In den USA allein.",emoji:"💼"},
  {q:"How many percent der Weltbevölkerung wählen in Diktaturen?",a:36,unit:"%",hint:"2,8 billion Menschen unter autoritären Regimen.",emoji:"🔒"},
  {q:"In what year wurde die Europäische Union offiziell gegründet?",a:1993,unit:"Jahr",hint:"Maastricht-Vertrag trat in Kraft.",emoji:"🇪🇺"},
  {q:"How many billion Dollar kostet das US-Militärbudget per year?",a:858,unit:"billion $",hint:"Mehr als die nächsten 10 Länder zusammen.",emoji:"⚔️"},
  {q:"How many Jahre saß Nelson Mandela als Präsident?",a:5,unit:"years",hint:"Von 1994 bis 1999.",emoji:"✊"},
  {q:"In what year wurde der Internationale Währungsfonds gegründet?",a:1944,unit:"Jahr",hint:"In Bretton Woods, New Hampshire.",emoji:"💰"},
  {q:"How many million Mitglieder hat die CDU?",a:370,unit:"thousand",hint:"Stand 2023 – stark gesunken.",emoji:"🇩🇪"},
  {q:"How many Länder haben den Euro als Währung?",a:20,unit:"countries",hint:"Eurozone seit 2023.",emoji:"💶"},
  {q:"In what year trat Großbritannien aus der EU aus?",a:2020,unit:"Jahr",hint:"Brexit am 31. Januar 2020.",emoji:"🇬🇧"},
  {q:"How many billion Euro zahlt Deutschland netto in die EU?",a:17,unit:"billion €",hint:"Größter Nettobeitragszahler.",emoji:"🇩🇪"},
  {q:"How many Personen saßen bei Nürnberger Prozessen auf der Anklagebank?",a:24,unit:"people",hint:"Hauptangeklagte im ersten Prozess.",emoji:"⚖️"},
  {q:"In what year wurde die Weltgesundheitsorganisation gegründet?",a:1948,unit:"Jahr",hint:"WHO – 7. April 1948.",emoji:"🏥"},
  {q:"How many million Stimmen bekam Hitler bei der letzten freien Wahl 1932?",a:13,unit:"million",hint:"37,4% der Stimmen.",emoji:"☮️"},
  {q:"How many Länder haben bisher ein UN-Veto eingelegt?",a:5,unit:"countries",hint:"USA, Russland, China, UK, Frankreich – die P5.",emoji:"🌍"},
  {q:"In what year wurde Angela Merkel zur Bundeskanzlerin gewählt?",a:2005,unit:"Jahr",hint:"Erste Frau auf diesem Amt.",emoji:"🇩🇪"},
  {q:"How many billion Euro fließen annually in die Korruption in der EU?",a:120,unit:"billion €",hint:"Schätzung der EU-Kommission.",emoji:"💸"},
  {q:"How many Personen saßen in der DDR-Stasi?",a:90000,unit:"hauptamtliche Mitarbeiter",hint:"Plus 180.000 inoffizielle Mitarbeiter.",emoji:"🧱"},
  {q:"In what year wurde Willy Brandt mit dem Friedensnobelpreis ausgezeichnet?",a:1971,unit:"Jahr",hint:"Für seine Ostpolitik.",emoji:"🕊️"},
  {q:"How many million Quadratkilometer umfasst Russland?",a:17,unit:"million km²",hint:"Das größte Land der Welt.",emoji:"🇷🇺"},
  {q:"How many percent des Bundestags sind Juristinnen und Juristen?",a:15,unit:"%",hint:"Juristen sind überrepräsentiert.",emoji:"⚖️"},
  {q:"In what year begann der Syrische Bürgerkrieg?",a:2011,unit:"Jahr",hint:"Als Teil des Arabischen Frühlings.",emoji:"🕊️"},
  {q:"How many billion Dollar gibt die USA für Geheimdienste aus?",a:90,unit:"billion $",hint:"Gesamtes Intelligence-Budget.",emoji:"🕵️"},
  {q:"How many Jahre war Robert Mugabe an der Macht in Simbabwe?",a:37,unit:"years",hint:"Von 1980 bis 2017.",emoji:"🇿🇼"},
  {q:"In what year wurde Südafrika demokratisch?",a:1994,unit:"Jahr",hint:"Erste freie Wahlen nach dem Ende der Apartheid.",emoji:"✊"},
  {q:"How many million Euro verdient ein Bundestagsabgeordneter in seiner Amtszeit?",a:500,unit:"Tausend Euro",hint:"Diäten plus Pensionsansprüche.",emoji:"💶"},
  {q:"How many Länder haben a woman als Regierungschefin (Stand 2024)?",a:26,unit:"countries",hint:"Steigende Tendenz worldwide.",emoji:"👩"},
  {q:"In what year wurde das Atomwaffensperrvertrag unterzeichnet?",a:1968,unit:"Jahr",hint:"Non-Proliferation Treaty – NPT.",emoji:"☢️"},
  {q:"How many billion Dollar hat der Irakkrieg die USA gekostet?",a:2000,unit:"billion $",hint:"Inklusive langfristiger Kosten.",emoji:"⚔️"},
  {q:"In what year wurde die Europäische Menschenrechtskonvention unterzeichnet?",a:1950,unit:"Jahr",hint:"Am 4. November 1950 in Rom.",emoji:"⚖️"},
  {q:"How many billion Euro fließen aus Deutschland in Steueroasen?",a:100,unit:"billion €",hint:"Schätzungen per year.",emoji:"💸"},
  {q:"How many Tage dauerte die längste Regierungsbildung in Deutschland?",a:171,unit:"days",hint:"2017 – Jamaika-Koalition scheiterte.",emoji:"🇩🇪"},
  {q:"In what year wurde die Allgemeine Erklärung der Menschenrechte verabschiedet?",a:1948,unit:"Jahr",hint:"Am 10. Dezember 1948 durch die UNO.",emoji:"📜"},
  {q:"How many billion Dollar wert ist Chinas Gürtel-und-Straße-Initiative?",a:1000,unit:"billion $",hint:"Chinas globales Infrastrukturprojekt.",emoji:"🌏"},
  {q:"How many percent der Deutschen vertrauen der Politik?",a:28,unit:"%",hint:"Niedriges Vertrauen laut Umfragen.",emoji:"📊"},
  {q:"In what year begann Russlands Einmarsch in die Ukraine?",a:2022,unit:"Jahr",hint:"Am 24. Februar 2022.",emoji:"🕊️"},
  {q:"How many billion Euro kostet Deutschland der Ukraine-Krieg bislang?",a:20,unit:"billion €",hint:"An Hilfe und indirekten Kosten.",emoji:"🇺🇦"},
  {q:"How many Länder haben die Russland-Sanktionen mitgemacht?",a:40,unit:"countries",hint:"Westliche Allianz.",emoji:"🌍"},
  {q:"In what year wurde Joe Biden US-Präsident?",a:2021,unit:"Jahr",hint:"Am 20. Januar 2021 vereidigt.",emoji:"🇺🇸"},
  {q:"How many million Wahlberechtigte gibt es in Deutschland?",a:61,unit:"million",hint:"Bei Bundestagswahlen.",emoji:"🗳️"},
  {q:"How many Länder sind permanent im UN-Sicherheitsrat?",a:5,unit:"countries",hint:"USA, Russland, China, UK, Frankreich.",emoji:"🌍"},
  {q:"In what year endete der Kalte Krieg?",a:1991,unit:"Jahr",hint:"Mit dem Zerfall der Sowjetunion.",emoji:"🕊️"},
  {q:"How many billion Dollar hat der Marshallplan nach dem Zweiten Weltkrieg gekostet?",a:13,unit:"billion $",hint:"Damals – heute ~160 Mrd. Dollar wert.",emoji:"🇺🇸"},
  {q:"How many percent der Deutschen sind Mitglied in einer Partei?",a:1.5,unit:"%",hint:"Historisch niedriger Wert.",emoji:"📊"},
  {q:"In what year wurde die CSU gegründet?",a:1945,unit:"Jahr",hint:"Am 8. Januar 1946 offiziell gegründet.",emoji:"🇩🇪"},
  {q:"How many Atomkraftwerke hat Deutschland abgeschaltet bis 2023?",a:17,unit:"Kraftwerke",hint:"Letztes am 15. April 2023.",emoji:"⚡"},
  {q:"How many million Euro Jahresgehalt bekommt ein EU-Kommissionspräsident?",a:320,unit:"Tausend Euro",hint:"322.000 Euro brutto.",emoji:"🇪🇺"},
  {q:"In what year erhielt die EU den Friedensnobelpreis?",a:2012,unit:"Jahr",hint:"Für sechs Jahrzehnte Frieden in Europa.",emoji:"🕊️"},
  {q:"How many million Zwangsarbeiter gab es im Dritten Reich?",a:13,unit:"million",hint:"Aus ganz Europa.",emoji:"☮️"},
  {q:"How many percent der Weltbevölkerung hat keine politischen Rechte?",a:30,unit:"%",hint:"Freedom House bewertet 30% als 'Not Free'.",emoji:"🔒"},
  {q:"In what year wurde die Grünen-Partei in Deutschland gegründet?",a:1980,unit:"Jahr",hint:"Am 13. Januar 1980 in Karlsruhe.",emoji:"🌿"},
  {q:"How many billion Euro kostet die deutsche Sozialhilfe per year?",a:40,unit:"billion €",hint:"Bürgergeld und Sozialtransfers.",emoji:"🤝"},
  {q:"How many Länder erkennen die Krim als russisch an?",a:5,unit:"countries",hint:"Nur wenige Verbündete Russlands.",emoji:"🇷🇺"},
  {q:"In what year wurde Olaf Scholz Bundeskanzler?",a:2021,unit:"Jahr",hint:"Am 8. Dezember 2021.",emoji:"🇩🇪"},
  {q:"How many million Dollar kostet ein US-Senatswahlkampf on average?",a:12,unit:"million $",hint:"Tendenz stark steigend.",emoji:"🗳️"},
  {q:"How many Länder haben die Todesstrafe noch?",a:55,unit:"countries",hint:"China, Iran, Saudi-Arabien führend.",emoji:"⚖️"},
  {q:"In what year wurde die FDP gegründet?",a:1948,unit:"Jahr",hint:"Am 11. Dezember 1948.",emoji:"🇩🇪"},
  {q:"How many billion Franken kostet die Schweizer Neutralität per year?",a:5,unit:"Mrd. Franken",hint:"Militärausgaben der neutralen Schweiz.",emoji:"🇨🇭"},
  {q:"How many percent der Weltbevölkerung lebt unter Xi Jinpings Herrschaft?",a:18,unit:"%",hint:"1,4 billion Chinesen.",emoji:"🇨🇳"},
  {q:"In what year wurde die Partei AfD gegründet?",a:2013,unit:"Jahr",hint:"Am 6. Februar 2013.",emoji:"🇩🇪"},
  {q:"How many million Tonnen CO₂ sparte Deutschland 2023?",a:44,unit:"Mio. Tonnen",hint:"Dank Energiewende.",emoji:"🌿"},
  {q:"How many billion Dollar hat die USA für Waffen an die Ukraine geliefert?",a:75,unit:"billion $",hint:"Stand Ende 2023.",emoji:"🇺🇦"},
  {q:"In what year wurde die Bundesrepublik Vollmitglied der UNO?",a:1973,unit:"Jahr",hint:"Gleichzeitig mit der DDR.",emoji:"🇩🇪"},
  {q:"How many Gesetze verabschiedet der Bundestag per year?",a:250,unit:"Gesetze",hint:"Ca. 250 neue Bundesgesetze.",emoji:"📜"},
  {q:"How many percent der Deutschen wollen die Todesstrafe einführen?",a:20,unit:"%",hint:"Trotz Grundgesetz-Verbot.",emoji:"📊"},
  {q:"In what year wurde Amnesty International gegründet?",a:1961,unit:"Jahr",hint:"Von Peter Benenson in London.",emoji:"🕯️"},
  {q:"How many billion Dollar wert ist der globale Waffenhandel?",a:600,unit:"billion $",hint:"Jährlicher legaler Waffenmarkt.",emoji:"⚔️"},
  {q:"How many Tage hat Deutschland nach der Wahl bis zur Regierungsbildung gebraucht?",a:171,unit:"days",hint:"2017 – Rekord.",emoji:"🇩🇪"},
  {q:"In what year wurde Donald Trump das erste Mal als Präsident vereidigt?",a:2017,unit:"Jahr",hint:"Am 20. Januar 2017.",emoji:"🇺🇸"},
  {q:"How many million Stimmen hatte Hillary Clinton mehr als Trump 2016?",a:2.9,unit:"million",hint:"Sie gewann die Volksabstimmung aber verlor das Electoral College.",emoji:"🗳️"},
  {q:"How many Länder haben derzeit aktive Kriege?",a:50,unit:"countries",hint:"Stand 2023 – viele Konflikte worldwide.",emoji:"☮️"},
  {q:"In what year wurde Greenpeace gegründet?",a:1971,unit:"Jahr",hint:"In Vancouver, Kanada.",emoji:"🌿"},
  {q:"How many billion Euro kostet die EU-Agrarpolitik per year?",a:58,unit:"billion €",hint:"Fast ein Drittel des EU-Budgets.",emoji:"🌾"},
  {q:"How many percent der Bundestagsabgeordneten sind ohne Migrationshintergrund?",a:95,unit:"%",hint:"Trotz 25% Migrationshintergrund in der Bevölkerung.",emoji:"📊"},
  {q:"In what year wurde die Todesstrafe in der Schweiz abgeschafft?",a:1942,unit:"Jahr",hint:"Für Zivilpersonen – Militär erst 1992.",emoji:"🇨🇭"},
  {q:"How many Stunden arbeitet ein Bundestagsabgeordneter per week?",a:60,unit:"hours",hint:"Plenarsitzungen, Ausschüsse, Wahlkreis.",emoji:"💼"},
  {q:"How many billion Dollar geben Lobbyisten in Brüssel aus?",a:1.5,unit:"billion €",hint:"Offiziell registrierte Lobbyausgaben.",emoji:"💼"},
  {q:"In what year wurde Robert Habeck Bundesminister?",a:2021,unit:"Jahr",hint:"Wirtschaftsminister in der Ampel-Koalition.",emoji:"🇩🇪"},
  {q:"How many percent der EU-Bürger vertrauen der EU?",a:45,unit:"%",hint:"Standard Eurobarometer.",emoji:"🇪🇺"},
  {q:"How many billion Franken hat die Schweiz Wirtschaftshilfe für Russland blockiert?",a:200,unit:"Mrd. Franken",hint:"Russische Gelder in der Schweiz.",emoji:"🇨🇭"},
  {q:"In what year wurde die UN-Klimarahmenkonvention gegründet?",a:1992,unit:"Jahr",hint:"Bei der Konferenz in Rio.",emoji:"🌍"},
  {q:"How many million Wähler haben 2021 die SPD gewählt?",a:11.9,unit:"million",hint:"25,7% der Stimmen.",emoji:"🗳️"},
  {q:"How many Länder haben China als größten Handelspartner?",a:120,unit:"countries",hint:"China dominiert den globalen Handel.",emoji:"🇨🇳"},
  {q:"In what year trat die DSGVO in Kraft?",a:2018,unit:"Jahr",hint:"Datenschutz-Grundverordnung, Mai 2018.",emoji:"🔒"},
  {q:"How many billion Euro wert ist Volkswagens staatlicher Anteil?",a:35,unit:"billion €",hint:"Niedersachsen hält 20% an VW.",emoji:"🚗"},
  {q:"How many Tage dauerte die längste Regierungsbildung in Belgien?",a:652,unit:"days",hint:"Weltrekord – 2010/2011.",emoji:"🇧🇪"},
  {q:"In what year wurde Wladimir Putin zum ersten Mal Präsident?",a:2000,unit:"Jahr",hint:"Am 7. Mai 2000.",emoji:"🇷🇺"},
  {q:"How many million Quadratkilometer umfasst das Territorium aller NATO-Länder?",a:25,unit:"million km²",hint:"Ein Viertel der Landfläche der Erde.",emoji:"🛡️"},
  {q:"How many billion Euro kostet Deutschlands gesetzliche Rentenversicherung per year?",a:340,unit:"billion €",hint:"Größter Sozialausgabeposten.",emoji:"👴"},
  {q:"In what year hielt Kennedy seine Berliner Rede ('Ich bin ein Berliner')?",a:1963,unit:"Jahr",hint:"Am 26. Juni 1963.",emoji:"🇺🇸"},
  {q:"How many Tage ist die längste Sitzung des UN-Sicherheitsrats gegangen?",a:5,unit:"days",hint:"Mehrere Marathonsitzungen in der Geschichte.",emoji:"🌍"},
  {q:"How many billion Dollar hat Saudi-Arabien für Sportwashing ausgegeben?",a:6,unit:"billion $",hint:"Golf, Fußball, Formel 1.",emoji:"⚽"},
  {q:"In what year wurde das Frauenwahlrecht in der Schweiz eingeführt?",a:1971,unit:"Jahr",hint:"Als eines der letzten westlichen Länder.",emoji:"🇨🇭"},
  {q:"How many million Menschen flohen 2022 aus der Ukraine?",a:8,unit:"million",hint:"Größte Flüchtlingsbewegung in Europa seit 1945.",emoji:"🇺🇦"},
  {q:"How many billion Euro kostet Deutschlands Bürgergeld per year?",a:20,unit:"billion €",hint:"Nachfolger von Hartz IV.",emoji:"🤝"},
  {q:"In what year wurde die Linke (PDS) gegründet?",a:1990,unit:"Jahr",hint:"Aus der SED der DDR.",emoji:"🇩🇪"},
  {q:"How many percent der Deutschen wollen mehr direkte Demokratie?",a:70,unit:"%",hint:"Volksentscheide sind sehr populär.",emoji:"🗳️"},
  {q:"How many billion Euro hat Deutschland während der Finanzkrise 2008 ausgegeben?",a:500,unit:"billion €",hint:"Rettungsschirm für Banken.",emoji:"💰"},
  {q:"In what year wurde der Menschenrechtsgerichtshof in Straßburg gegründet?",a:1959,unit:"Jahr",hint:"Europäischer Gerichtshof für Menschenrechte.",emoji:"⚖️"},
  {q:"How many Länder haben eine linkspopulistische Regierung (Stand 2024)?",a:15,unit:"countries",hint:"Lateinamerika, Europa und anderswo.",emoji:"🌹"},
  {q:"How many billion Dollar hat Bidens Infrastrukturpaket gekostet?",a:1200,unit:"billion $",hint:"Bipartisan Infrastructure Law 2021.",emoji:"🏗️"},
  {q:"In what year hielt Gorbatschow die Perestroika-Rede?",a:1986,unit:"Jahr",hint:"Beginn der Reformen in der Sowjetunion.",emoji:"☭"},
  {q:"How many billion Dollar kostet Nordkoreas Atomprogramm per year?",a:100,unit:"million $",hint:"Trotz Armut wird viel investiert.",emoji:"☢️"},
  {q:"How many Personen arbeiten im Weißen Haus?",a:500,unit:"Mitarbeiter",hint:"Einschließlich Küche, Sicherheit und Stab.",emoji:"🏛️"},
  {q:"In what year trat der Pariser Klimavertrag in Kraft?",a:2016,unit:"Jahr",hint:"Am 4. November 2016.",emoji:"🌍"},
  {q:"How many billion Euro wert sind die deutschen Staatsbeteiligungen?",a:100,unit:"billion €",hint:"Bahn, Post, Lufthansa und mehr.",emoji:"🇩🇪"},
  {q:"How many Jahre war Konrad Adenauer Bundeskanzler?",a:14,unit:"years",hint:"Von 1949 bis 1963.",emoji:"🇩🇪"},
  {q:"How many billion Dollar hat die globale Finanzkrise 2008 gekostet?",a:22000,unit:"billion $",hint:"22 Billionen Dollar Verlust worldwide.",emoji:"📉"},
  {q:"In what year begann der Bosnien-Krieg?",a:1992,unit:"Jahr",hint:"Nach der Unabhängigkeitserklärung von Jugoslawien.",emoji:"🕊️"},
  {q:"How many Länder haben sich der Welthandelsorganisation WTO angeschlossen?",a:164,unit:"countries",hint:"Stand 2023.",emoji:"🌍"},
  {q:"How many billion Dollar spart Apple durch Steuervermeidung per year?",a:5,unit:"billion $",hint:"Durch Irland und andere Steueroasen.",emoji:"🍎"},
  {q:"In what year wurde der Europarat gegründet?",a:1949,unit:"Jahr",hint:"Am 5. Mai 1949 in London.",emoji:"🇪🇺"},
  {q:"How many percent der Weltbevölkerung hat kein Wahlrecht?",a:40,unit:"%",hint:"Diktaturen, Minderjährige, Ausgeschlossene.",emoji:"🔒"},
  {q:"How many billion Euro hat Deutschland für Corona-Hilfen ausgegeben?",a:300,unit:"billion €",hint:"Direkte Hilfen und indirekte Kosten.",emoji:"😷"},
  {q:"In what year wurde die SPD gegründet?",a:1863,unit:"Jahr",hint:"Älteste noch aktive deutsche Partei.",emoji:"🌹"},
  {q:"How many million Dollar kostet ein moderner Kampfjet (F-35)?",a:80,unit:"million $",hint:"Der F-35 – teuerster Kampfjet der Geschichte.",emoji:"✈️"},
  {q:"How many Länder sind in der Commonwealth of Nations?",a:56,unit:"countries",hint:"Ehemalige britische Kolonien.",emoji:"👑"},
  {q:"In what year wurde die Afrikanische Union gegründet?",a:2002,unit:"Jahr",hint:"Nachfolger der Organisation für Afrikanische Einheit.",emoji:"🌍"},
  {q:"How many million Stimmen bekam Trump bei der Wahl 2020?",a:74,unit:"million",hint:"Trotz Niederlage historisch viele Stimmen.",emoji:"🗳️"},
  {q:"How many billion Dollar hat Chinas Belt and Road Infrastruktur bislang investiert?",a:1000,unit:"billion $",hint:"Die neue Seidenstraße.",emoji:"🌏"},
  {q:"In what year wurde Transparency International gegründet?",a:1993,unit:"Jahr",hint:"Korruptionsbekämpfung worldwide.",emoji:"💸"},
  {q:"How many Personen werden daily worldwide Opfer von Menschenhandel?",a:800,unit:"people",hint:"Geschätzte 800 neue Opfer daily.",emoji:"⛓️"},
  {q:"How many billion Euro kostet der deutsche öffentlich-rechtliche Rundfunk per year?",a:10,unit:"billion €",hint:"ARD, ZDF und Deutschlandradio zusammen.",emoji:"📺"},
  {q:"In what year wurde die erste Volksabstimmung in der Schweiz abgehalten?",a:1848,unit:"Jahr",hint:"Direkte Demokratie seit der Gründung.",emoji:"🇨🇭"},
];
