// 🎬 FILM, TV & POP CULTURE – Adults – 245 questions
export default [
  {id:"film_001",q:"How many Oscars did Titanic (1997) win?",a:11,unit:"Oscars",hint:"Tied with Ben-Hur and The Lord of the Rings.",emoji:"🎬"},
  {id:"film_002",q:"How many million dollars did it cost to produce Avengers: Endgame?",a:356,unit:"million dollars",hint:"One of the most expensive movies ever made.",emoji:"🦸"},
  {id:"film_003",q:"How many billion dollars did Avatar (2009) gross worldwide?",a:2.9,unit:"billion dollars",hint:"For a long time the highest-grossing film of all time.",emoji:"🎬"},
  {id:"film_004",q:"In what year did the first season of Game of Thrones premiere?",a:2011,unit:"year",hint:"Based on the books by George R.R. Martin.",emoji:"👑"},
  {id:"film_005",q:"How many episodes does the entire Breaking Bad series have?",a:62,unit:"episodes",hint:"5 seasons about the life of Walter White.",emoji:"🧪"},
  {id:"film_006",q:"How many million dollars did Jennifer Aniston earn per Friends episode at the end?",a:1,unit:"million dollars/episode",hint:"All six stars still earn millions today.",emoji:"☕"},
  {id:"film_007",q:"How many years has The Simpsons been running?",a:35,unit:"years",hint:"Since 1989 – the longest-running primetime animated series.",emoji:"🍩"},
  {id:"film_008",q:"How many million subscribers does MrBeast have on YouTube?",a:250,unit:"million",hint:"The most successful YouTube channel in the world.",emoji:"▶️"},
  {id:"film_009",q:"In what year did the first Star Wars movie come out?",a:1977,unit:"year",hint:"Episode IV – A New Hope was the beginning.",emoji:"⭐"},
  {id:"film_010",q:"How many billion dollars has the Marvel Cinematic Universe grossed in total?",a:29,unit:"billion dollars",hint:"Across more than 30 films.",emoji:"🦸"},
  {id:"film_011",q:"How many seasons does the show Friends have?",a:10,unit:"seasons",hint:"1994-2004 – one of the most beloved sitcoms ever.",emoji:"☕"},
  {id:"film_012",q:"How many million dollars does Taylor Swift earn per concert?",a:13,unit:"million dollars",hint:"The Eras Tour was the most lucrative tour ever.",emoji:"🎤"},
  {id:"film_013",q:"In what year did Michael Jackson's Thriller come out?",a:1982,unit:"year",hint:"The best-selling album of all time.",emoji:"🎵"},
  {id:"film_014",q:"How many million copies has Harry Potter and the Philosopher's Stone sold?",a:120,unit:"million",hint:"One of the best-selling books ever.",emoji:"⚡"},
  {id:"film_015",q:"How many Oscars did The Godfather win?",a:3,unit:"Oscars",hint:"Best Picture, Best Actor, Best Adapted Screenplay.",emoji:"🎬"},
  {id:"film_016",q:"How many million dollars did a 30-second Super Bowl ad cost in 2024?",a:7,unit:"million dollars",hint:"The most expensive ad slot on US TV.",emoji:"📺"},
  {id:"film_017",q:"How many seasons does the show Seinfeld have?",a:9,unit:"seasons",hint:"One of the most successful sitcoms of the '90s.",emoji:"🎤"},
  {id:"film_018",q:"In what year was Netflix founded?",a:1997,unit:"year",hint:"Originally a DVD-by-mail rental service.",emoji:"📺"},
  {id:"film_019",q:"How many million subscribers does Netflix have?",a:260,unit:"million",hint:"As of 2024 – the largest streaming service.",emoji:"📺"},
  {id:"film_020",q:"How many billion dollars did Jurassic Park (1993) gross?",a:1.1,unit:"billion dollars",hint:"The first film to cross the $1 billion mark.",emoji:"🦕"},
  {id:"film_021",q:"How many episodes does The Office (US) have?",a:201,unit:"episodes",hint:"9 seasons about the Dunder Mifflin Paper Company.",emoji:"📎"},
  {id:"film_022",q:"In what year did Nirvana's Nevermind come out?",a:1991,unit:"year",hint:"Smells Like Teen Spirit catapulted them into the mainstream.",emoji:"🎸"},
  {id:"film_023",q:"How many million dollars does Dwayne Johnson earn per film?",a:50,unit:"million dollars",hint:"One of the highest-paid actors in the world.",emoji:"💪"},
  {id:"film_024",q:"How many seasons does Grey's Anatomy have?",a:20,unit:"seasons",hint:"The longest-running primetime medical drama.",emoji:"🏥"},
  {id:"film_025",q:"How many million dollars did the first season of House of Cards cost?",a:100,unit:"million dollars",hint:"Netflix's first major original – 2 seasons greenlit upfront.",emoji:"🃏"},
  {id:"film_026",q:"In what year did Instagram launch?",a:2010,unit:"year",hint:"Over 1 million users within 2 months.",emoji:"📸"},
  {id:"film_027",q:"How many billion dollars did Frozen (2013) gross worldwide?",a:1.3,unit:"billion dollars",hint:"Let It Go became a worldwide hit.",emoji:"❄️"},
  {id:"film_028",q:"How many million followers does Cristiano Ronaldo have on Instagram?",a:620,unit:"million",hint:"The most-followed person on Instagram.",emoji:"⚽"},
  {id:"film_029",q:"In what year was the first iPhone unveiled?",a:2007,unit:"year",hint:"Steve Jobs said: 'One more thing...'",emoji:"📱"},
  {id:"film_030",q:"How many episodes does Lost have?",a:121,unit:"episodes",hint:"6 seasons on the mysterious island.",emoji:"✈️"},
  {id:"film_031",q:"How many million dollars does Robert Downey Jr. earn for returning as Iron Man?",a:200,unit:"million dollars",hint:"For Avengers: Secret Wars.",emoji:"🤖"},
  {id:"film_032",q:"In what year did the first Matrix movie come out?",a:1999,unit:"year",hint:"Keanu Reeves and the red pill.",emoji:"💊"},
  {id:"film_033",q:"How many seasons does The Walking Dead have?",a:11,unit:"seasons",hint:"2010-2022 – zombies in a post-apocalyptic world.",emoji:"🧟"},
  {id:"film_034",q:"How many million dollars did Die Hard gross?",a:140,unit:"million dollars",hint:"John McClane became Bruce Willis's iconic role.",emoji:"🔫"},
  {id:"film_035",q:"In what year was YouTube founded?",a:2005,unit:"year",hint:"Founded by three former PayPal employees.",emoji:"▶️"},
  {id:"film_036",q:"How many billion dollars did Barbie (2023) gross worldwide?",a:1.4,unit:"billion dollars",hint:"The highest-grossing film directed by a woman.",emoji:"🩷"},
  {id:"film_037",q:"How many million albums has ABBA sold in total?",a:380,unit:"million",hint:"One of the best-selling artists of all time.",emoji:"🎵"},
  {id:"film_038",q:"In what year did Stranger Things premiere?",a:2016,unit:"year",hint:"Netflix's biggest series hit.",emoji:"🔦"},
  {id:"film_039",q:"How many Oscars has Meryl Streep won?",a:3,unit:"Oscars",hint:"And 21 nominations – a record.",emoji:"🎬"},
  {id:"film_040",q:"How many million dollars does Lionel Messi earn per year?",a:135,unit:"million dollars",hint:"Including salary, sponsorships, and endorsements.",emoji:"⚽"},
  {id:"film_041",q:"In what year did Pulp Fiction come out?",a:1994,unit:"year",hint:"Quentin Tarantino's masterpiece won the Palme d'Or.",emoji:"🎬"},
  {id:"film_042",q:"How many episodes does Narcos have?",a:30,unit:"episodes",hint:"3 seasons about Pablo Escobar and the drug trade.",emoji:"🌿"},
  {id:"film_043",q:"How many million dollars did it cost to produce Cleopatra (1963)?",a:44,unit:"million dollars",hint:"The most expensive film budget in history at the time.",emoji:"👑"},
  {id:"film_044",q:"In what year did Michael Jackson's moonwalk debut?",a:1983,unit:"year",hint:"Performed at the Motown 25 anniversary special.",emoji:"🕺"},
  {id:"film_045",q:"How many seasons does Dexter have?",a:8,unit:"seasons",hint:"Plus New Blood – about the serial-killer forensic analyst.",emoji:"🔪"},
  {id:"film_046",q:"How many billion dollars did Top Gun: Maverick gross?",a:1.49,unit:"billion dollars",hint:"Tom Cruise's most successful film.",emoji:"✈️"},
  {id:"film_047",q:"In what year did TikTok launch internationally?",a:2018,unit:"year",hint:"Merged with and rebranded from Musical.ly.",emoji:"📱"},
  {id:"film_048",q:"How many million copies has The Da Vinci Code sold?",a:80,unit:"million",hint:"Dan Brown's bestseller about secret societies.",emoji:"📖"},
  {id:"film_049",q:"How many episodes does The Sopranos have?",a:86,unit:"episodes",hint:"6 seasons about Tony Soprano.",emoji:"🍕"},
  {id:"film_050",q:"In what year did Eminem's The Slim Shady LP come out?",a:1999,unit:"year",hint:"His mainstream breakthrough.",emoji:"🎤"},
  {id:"film_051",q:"How many million dollars did Harry Potter and the Philosopher's Stone gross?",a:975,unit:"million dollars",hint:"Almost a billion for the first installment.",emoji:"⚡"},
  {id:"film_052",q:"How many seasons does House of Cards have?",a:6,unit:"seasons",hint:"Frank Underwood's rise to power.",emoji:"🃏"},
  {id:"film_053",q:"In what year did Beyoncé's Lemonade come out?",a:2016,unit:"year",hint:"One of the most-discussed albums of the decade.",emoji:"🎵"},
  {id:"film_054",q:"How many billion dollars did The Dark Knight gross?",a:1,unit:"billion dollars",hint:"Heath Ledger's Joker remains unforgettable.",emoji:"🦇"},
  {id:"film_055",q:"How many episodes does The Crown have?",a:60,unit:"episodes",hint:"6 seasons about the British royal family.",emoji:"👑"},
  {id:"film_056",q:"In what year was Spotify founded?",a:2006,unit:"year",hint:"Daniel Ek launched the music revolution.",emoji:"🎵"},
  {id:"film_057",q:"How many billion dollars did Titanic (1997) gross?",a:2.2,unit:"billion dollars",hint:"Held the world record for 12 years.",emoji:"🚢"},
  {id:"film_058",q:"How many seasons does Prison Break have?",a:5,unit:"seasons",hint:"Michael Scofield and his escape plan.",emoji:"🔒"},
  {id:"film_059",q:"In what year did Facebook launch?",a:2004,unit:"year",hint:"Originally only for Harvard students.",emoji:"📱"},
  {id:"film_060",q:"How many million subscribers does PewDiePie have on YouTube?",a:111,unit:"million",hint:"The most-subscribed channel for the longest time.",emoji:"🎮"},
  {id:"film_061",q:"How many seasons does the show 24 have?",a:9,unit:"seasons",hint:"Jack Bauer saves the world in 24 hours.",emoji:"💣"},
  {id:"film_062",q:"In what year did Radiohead's OK Computer come out?",a:1997,unit:"year",hint:"Often ranked as the best album of all time.",emoji:"🎸"},
  {id:"film_063",q:"How many million dollars did The Lion King (1994) gross?",a:987,unit:"million dollars",hint:"Disney's most successful animated film.",emoji:"🦁"},
  {id:"film_064",q:"How many episodes does Homeland have?",a:96,unit:"episodes",hint:"8 seasons about CIA agent Carrie Mathison.",emoji:"🕵️"},
  {id:"film_065",q:"In what year did Daft Punk's Random Access Memories come out?",a:2013,unit:"year",hint:"Get Lucky dominated the charts.",emoji:"🎵"},
  {id:"film_066",q:"How many million dollars does Kim Kardashian earn per Instagram post?",a:1,unit:"million dollars",hint:"For paid partnerships.",emoji:"📸"},
  {id:"film_067",q:"How many seasons does Suits have?",a:9,unit:"seasons",hint:"Meghan Markle played Rachel Zane.",emoji:"⚖️"},
  {id:"film_068",q:"In what year did the first Transformers movie come out?",a:2007,unit:"year",hint:"Michael Bay and tons of CGI.",emoji:"🤖"},
  {id:"film_069",q:"How many million dollars did Shrek 2 gross?",a:920,unit:"million dollars",hint:"The most successful animated film of its time.",emoji:"🟢"},
  {id:"film_070",q:"In what year did Adele's album 21 come out?",a:2011,unit:"year",hint:"Rolling in the Deep was a global hit.",emoji:"🎵"},
  {id:"film_071",q:"How many million dollars did Inception gross?",a:836,unit:"million dollars",hint:"Christopher Nolan's dream-within-a-dream movie.",emoji:"🌀"},
  {id:"film_072",q:"How many seasons does Billions have?",a:7,unit:"seasons",hint:"About hedge funds and prosecutors.",emoji:"💰"},
  {id:"film_073",q:"In what year did Kanye West's The College Dropout come out?",a:2004,unit:"year",hint:"His critically acclaimed debut album.",emoji:"🎵"},
  {id:"film_074",q:"How many billion dollars did The Avengers (2012) gross?",a:1.52,unit:"billion dollars",hint:"The first billion-dollar superhero movie.",emoji:"🦸"},
  {id:"film_075",q:"How many episodes does Sons of Anarchy have?",a:92,unit:"episodes",hint:"7 seasons about a motorcycle club.",emoji:"🏍️"},
  {id:"film_076",q:"In what year did Cardi B's Invasion of Privacy come out?",a:2018,unit:"year",hint:"Bodak Yellow made her the first woman with a #1 solo rap hit.",emoji:"🎤"},
  {id:"film_077",q:"How many billion dollars did Aquaman (2018) gross?",a:1.15,unit:"billion dollars",hint:"The most successful DC film.",emoji:"🌊"},
  {id:"film_078",q:"How many seasons does Westworld have?",a:4,unit:"seasons",hint:"About AI and consciousness in an amusement park.",emoji:"🤖"},
  {id:"film_079",q:"In what year did Drake's Take Care come out?",a:2011,unit:"year",hint:"His second studio album – one of the most influential.",emoji:"🎵"},
  {id:"film_080",q:"How many million dollars did Iron Man (2008) gross?",a:585,unit:"million dollars",hint:"This is where the MCU began.",emoji:"🤖"},
  {id:"film_081",q:"How many seasons does Narcos: Mexico have?",a:3,unit:"seasons",hint:"About the Guadalajara Cartel.",emoji:"🌵"},
  {id:"film_082",q:"In what year did Ed Sheeran's Multiply (+) come out?",a:2014,unit:"year",hint:"Thinking Out Loud became a classic.",emoji:"🎸"},
  {id:"film_083",q:"How many billion dollars did Black Panther gross?",a:1.35,unit:"billion dollars",hint:"A groundbreaking film for representation.",emoji:"🦅"},
  {id:"film_084",q:"How many episodes does Peaky Blinders have?",a:36,unit:"episodes",hint:"6 seasons about the Shelby family.",emoji:"🎩"},
  {id:"film_085",q:"In what year did Lana Del Rey's Born to Die come out?",a:2012,unit:"year",hint:"Her breakthrough album.",emoji:"🌹"},
  {id:"film_086",q:"How many billion dollars did Jurassic World gross?",a:1.67,unit:"billion dollars",hint:"3rd place at the time – since surpassed.",emoji:"🦕"},
  {id:"film_087",q:"How many seasons does Yellowstone have?",a:5,unit:"seasons",hint:"Kevin Costner's rancher drama.",emoji:"🤠"},
  {id:"film_088",q:"In what year did the podcast Serial launch?",a:2014,unit:"year",hint:"The first major true-crime podcast.",emoji:"🎙️"},
  {id:"film_089",q:"How many million dollars did The Hunger Games (2012) gross?",a:694,unit:"million dollars",hint:"Jennifer Lawrence became a star.",emoji:"🏹"},
  {id:"film_090",q:"How many episodes does Arrested Development have?",a:84,unit:"episodes",hint:"Often called the smartest sitcom ever made.",emoji:"🍌"},
  {id:"film_091",q:"In what year did Olivia Rodrigo's SOUR come out?",a:2021,unit:"year",hint:"drivers license dominated the charts.",emoji:"🎵"},
  {id:"film_092",q:"How many million dollars did Doctor Strange in the Multiverse of Madness gross?",a:955,unit:"million dollars",hint:"Sam Raimi's horror-Marvel mashup.",emoji:"🌀"},
  {id:"film_093",q:"How many seasons does Money Heist (La Casa de Papel) have?",a:5,unit:"seasons",hint:"Spain's most successful Netflix series.",emoji:"💰"},
  {id:"film_094",q:"In what year did Billie Eilish's When We All Fall Asleep come out?",a:2019,unit:"year",hint:"She became a global star at 17.",emoji:"🖤"},
  {id:"film_095",q:"How many billion dollars did Spider-Man: No Way Home gross?",a:1.9,unit:"billion dollars",hint:"Third place of all time.",emoji:"🕷️"},
  {id:"film_096",q:"How many episodes does Fleabag have?",a:12,unit:"episodes",hint:"Phoebe Waller-Bridge's masterpiece.",emoji:"🦊"},
  {id:"film_097",q:"In what year did The Weeknd's Starboy come out?",a:2016,unit:"year",hint:"A collaboration with Daft Punk.",emoji:"⭐"},
  {id:"film_098",q:"How many million dollars did The Batman (2022) gross?",a:770,unit:"million dollars",hint:"Robert Pattinson as the dark knight.",emoji:"🦇"},
  {id:"film_099",q:"How many seasons does Better Call Saul have?",a:6,unit:"seasons",hint:"A Breaking Bad prequel about Saul Goodman.",emoji:"⚖️"},
  {id:"film_100",q:"In what year did Harry Styles' As It Was come out as a single?",a:2022,unit:"year",hint:"The most-streamed song of 2022 worldwide.",emoji:"🎵"},
  {id:"film_101",q:"How many billion dollars did Minions (2015) gross?",a:1.16,unit:"billion dollars",hint:"The little yellow guys became a cultural phenomenon.",emoji:"💛"},
  {id:"film_102",q:"How many seasons does True Detective have?",a:4,unit:"seasons",hint:"An anthology series – each season a new story.",emoji:"🔍"},
  {id:"film_103",q:"In what year did Dua Lipa's Future Nostalgia come out?",a:2020,unit:"year",hint:"Levitating became a global hit.",emoji:"💃"},
  {id:"film_104",q:"How many billion dollars did Fast and Furious 7 gross?",a:1.52,unit:"billion dollars",hint:"Paul Walker's final film.",emoji:"🚗"},
  {id:"film_105",q:"How many episodes does The Mandalorian have?",a:24,unit:"episodes",hint:"3 seasons – Baby Yoda became an internet sensation.",emoji:"⭐"},
  {id:"film_106",q:"In what year did Kendrick Lamar's DAMN. come out?",a:2017,unit:"year",hint:"The first rap album to win the Pulitzer Prize.",emoji:"🎵"},
  {id:"film_107",q:"How many billion dollars did Captain America: Civil War gross?",a:1.15,unit:"billion dollars",hint:"Marvel against itself.",emoji:"🛡️"},
  {id:"film_108",q:"How many seasons does Succession have?",a:4,unit:"seasons",hint:"The Roy family and the media mogul.",emoji:"💼"},
  {id:"film_109",q:"In what year did Lorde's Pure Heroine come out?",a:2013,unit:"year",hint:"Royals became a worldwide hit when she was just 16.",emoji:"🎵"},
  {id:"film_110",q:"How many billion dollars did Toy Story 3 gross?",a:1.07,unit:"billion dollars",hint:"Pixar's first billion-dollar film.",emoji:"🤖"},
  {id:"film_111",q:"How many episodes does The Boys have?",a:32,unit:"episodes",hint:"4 seasons – superheroes gone bad.",emoji:"⚡"},
  {id:"film_112",q:"In what year did Stormzy's Gang Signs & Prayer come out?",a:2017,unit:"year",hint:"The first grime album to hit #1 in the UK.",emoji:"🎤"},
  {id:"film_113",q:"How many million dollars did Guardians of the Galaxy Vol. 3 gross?",a:845,unit:"million dollars",hint:"James Gunn's emotional finale.",emoji:"🌌"},
  {id:"film_114",q:"How many seasons does Ozark have?",a:4,unit:"seasons",hint:"Breaking Bad of the lakes.",emoji:"💸"},
  {id:"film_115",q:"In what year did Frank Ocean's Blonde come out?",a:2016,unit:"year",hint:"One of the most important albums of the 2010s.",emoji:"🎵"},
  {id:"film_116",q:"How many million dollars did Interstellar gross?",a:701,unit:"million dollars",hint:"Christopher Nolan's space epic.",emoji:"🌌"},
  {id:"film_117",q:"How many episodes does Squid Game have?",a:9,unit:"episodes",hint:"Netflix's most-watched series ever.",emoji:"🦑"},
  {id:"film_118",q:"In what year did Ariana Grande's Thank U, Next come out?",a:2019,unit:"year",hint:"Released a week after her breakup.",emoji:"💅"},
  {id:"film_119",q:"How many million dollars did The Greatest Showman gross?",a:435,unit:"million dollars",hint:"Hugh Jackman as P.T. Barnum.",emoji:"🎪"},
  {id:"film_120",q:"How many seasons does The Witcher have?",a:3,unit:"seasons",hint:"Henry Cavill as Geralt – through season 3.",emoji:"⚔️"},
  {id:"film_121",q:"In what year did Childish Gambino's This Is America come out?",a:2018,unit:"year",hint:"The music video went viral for its symbolism.",emoji:"🎵"},
  {id:"film_122",q:"How many million dollars did Wonder Woman (2017) gross?",a:822,unit:"million dollars",hint:"The first female-led superhero blockbuster.",emoji:"⚡"},
  {id:"film_123",q:"How many episodes does the series Dark (Netflix Germany) have?",a:26,unit:"episodes",hint:"3 seasons – one of the best German series.",emoji:"🌀"},
  {id:"film_124",q:"In what year did Post Malone's Beerbongs & Bentleys come out?",a:2018,unit:"year",hint:"His second studio album with record-breaking streams.",emoji:"🎵"},
  {id:"film_125",q:"How many billion dollars did Deadpool & Wolverine gross?",a:1.34,unit:"billion dollars",hint:"The first R-rated Marvel film to cross a billion.",emoji:"🔴"},
  {id:"film_126",q:"How many seasons does Emily in Paris have?",a:4,unit:"seasons",hint:"An American in Paris – a guilty pleasure.",emoji:"🗼"},
  {id:"film_127",q:"In what year did SZA's SOS come out?",a:2022,unit:"year",hint:"The most-streamed debut album by a female artist.",emoji:"🎵"},
  {id:"film_128",q:"How many billion dollars did Joker (2019) gross?",a:1.08,unit:"billion dollars",hint:"Joaquin Phoenix won the Oscar.",emoji:"🃏"},
  {id:"film_129",q:"How many episodes does Ted Lasso have?",a:34,unit:"episodes",hint:"3 seasons – Apple's feel-good show.",emoji:"⚽"},
  {id:"film_130",q:"In what year did The Weeknd's Dawn FM come out?",a:2022,unit:"year",hint:"A complete '80s synth concept album.",emoji:"📻"},
  {id:"film_131",q:"How many million dollars did Forrest Gump gross?",a:678,unit:"million dollars",hint:"Tom Hanks won his second Oscar.",emoji:"🏃"},
  {id:"film_132",q:"How many seasons does Big Little Lies have?",a:2,unit:"seasons",hint:"Nicole Kidman and Reese Witherspoon.",emoji:"🌊"},
  {id:"film_133",q:"In what year did Twenty One Pilots' Blurryface come out?",a:2015,unit:"year",hint:"Stressed Out became an anthem for a generation.",emoji:"🎵"},
  {id:"film_134",q:"How many million dollars did The Revenant gross?",a:533,unit:"million dollars",hint:"DiCaprio finally won his Oscar.",emoji:"🐻"},
  {id:"film_135",q:"How many episodes does Euphoria have?",a:16,unit:"episodes",hint:"2 seasons – Zendaya's breakthrough as an adult actress.",emoji:"💊"},
  {id:"film_136",q:"In what year did Tyler, the Creator's Igor come out?",a:2019,unit:"year",hint:"Won the Grammy for Best Rap Album.",emoji:"🎵"},
  {id:"film_137",q:"How many million dollars did Black Widow gross?",a:379,unit:"million dollars",hint:"Disappointing due to the simultaneous Disney+ release.",emoji:"🕷️"},
  {id:"film_138",q:"How many seasons does Yellowjackets have?",a:3,unit:"seasons",hint:"About girls who survive a plane crash.",emoji:"✈️"},
  {id:"film_139",q:"In what year did Mitski's Puberty 2 come out?",a:2016,unit:"year",hint:"An indie darling and one of the best songwriters around.",emoji:"🎵"},
  {id:"film_140",q:"How many million dollars did Gladiator (2000) gross?",a:460,unit:"million dollars",hint:"Russell Crowe won the Oscar.",emoji:"⚔️"},
  {id:"film_141",q:"How many episodes does The White Lotus have?",a:14,unit:"episodes",hint:"2 seasons – satire about wealthy tourists.",emoji:"🌺"},
  {id:"film_142",q:"In what year did Childish Gambino's Awaken, My Love! come out?",a:2016,unit:"year",hint:"Redbone became a 70s-funk classic.",emoji:"🎵"},
  {id:"film_143",q:"How many million dollars did No Time to Die gross?",a:774,unit:"million dollars",hint:"Daniel Craig's final Bond film.",emoji:"🔫"},
  {id:"film_144",q:"How many seasons does The Last of Us have?",a:2,unit:"seasons",hint:"HBO's adaptation of the acclaimed video game.",emoji:"🍄"},
  {id:"film_145",q:"In what year did Normani's Motivation (single) come out?",a:2019,unit:"year",hint:"Her solo breakthrough after Fifth Harmony.",emoji:"💃"},
  {id:"film_146",q:"How many million dollars did Encanto gross?",a:256,unit:"million dollars",hint:"We Don't Talk About Bruno went viral.",emoji:"🌈"},
  {id:"film_147",q:"How many episodes does Station Eleven have?",a:10,unit:"episodes",hint:"A pandemic drama – timely right after Covid.",emoji:"☄️"},
  {id:"film_148",q:"In what year did Weyes Blood's And in the Darkness, Hearts Aglow come out?",a:2022,unit:"year",hint:"One of the year's critic-favorite albums.",emoji:"🎵"},
  {id:"film_149",q:"How many billion dollars did Avatar: The Way of Water gross?",a:2.32,unit:"billion dollars",hint:"Cameron breaks records again.",emoji:"🌊"},
  {id:"film_150",q:"How many seasons does The Bear have?",a:3,unit:"seasons",hint:"The restaurant drama won numerous Emmys.",emoji:"🍳"},
  {id:"film_151",q:"In what year did Bad Bunny's Un Verano Sin Ti come out?",a:2022,unit:"year",hint:"The most-streamed album on Spotify in 2022.",emoji:"🐇"},
  {id:"film_152",q:"How many billion dollars did The Super Mario Bros. Movie gross?",a:1.36,unit:"billion dollars",hint:"The most successful video game movie of all time.",emoji:"🍄"},
  {id:"film_153",q:"How many episodes does Only Murders in the Building have?",a:30,unit:"episodes",hint:"3 seasons – Hulu's true-crime comedy.",emoji:"🔍"},
  {id:"film_154",q:"In what year did Ice Spice's debut mixtape come out?",a:2023,unit:"year",hint:"Her rise from the Bronx to worldwide fame.",emoji:"🧡"},
  {id:"film_155",q:"How many million dollars did The Notebook (2004) gross?",a:115,unit:"million dollars",hint:"Ryan Gosling and Rachel McAdams.",emoji:"💕"},
  {id:"film_156",q:"How many seasons does Abbott Elementary have?",a:3,unit:"seasons",hint:"A mockumentary about an American elementary school.",emoji:"🏫"},
  {id:"film_157",q:"In what year did Nicki Minaj's Pink Friday come out?",a:2010,unit:"year",hint:"Her debut album – it made her the Queen of Rap.",emoji:"💕"},
  {id:"film_158",q:"How many million dollars did The Wolf of Wall Street gross?",a:392,unit:"million dollars",hint:"DiCaprio and Scorsese – 3 hours of excess.",emoji:"💰"},
  {id:"film_159",q:"How many seasons does Severance have?",a:2,unit:"seasons",hint:"Apple TV+ – work and personal life kept separate.",emoji:"🔪"},
  {id:"film_160",q:"In what year did Paramore's After Laughter come out?",a:2017,unit:"year",hint:"Their pop-oriented comeback album.",emoji:"🎵"},
  {id:"film_161",q:"How many million dollars did Glass Onion (Netflix) cost to make?",a:40,unit:"million dollars",hint:"The Knives Out sequel – exclusive to Netflix.",emoji:"🧅"},
  {id:"film_162",q:"How many episodes does Mindhunter have?",a:19,unit:"episodes",hint:"2 seasons – a Netflix series about FBI profilers.",emoji:"🔍"},
  {id:"film_163",q:"In what year did Coldplay's Music of the Spheres come out?",a:2021,unit:"year",hint:"Their most divisive – and most commercially successful – album.",emoji:"🌌"},
  {id:"film_164",q:"How many million dollars did The Truman Show gross?",a:264,unit:"million dollars",hint:"Jim Carrey in a film studies classic.",emoji:"📺"},
  {id:"film_165",q:"How many seasons does House M.D. have?",a:8,unit:"seasons",hint:"Dr. House – the cantankerous diagnostic genius.",emoji:"🏥"},
  {id:"film_166",q:"In what year did SAAB's Sorry 4 Waiting come out?",a:2021,unit:"year",hint:"A rising rap talent from Baltimore.",emoji:"🎵"},
  {id:"film_167",q:"How many seasons does Mad Men have?",a:7,unit:"seasons",hint:"About the advertising world of the 1960s.",emoji:"🥃"},
  {id:"film_168",q:"In what year did Tame Impala's Currents come out?",a:2015,unit:"year",hint:"A psychedelic-pop cornerstone.",emoji:"🌀"},
  {id:"film_169",q:"How many million dollars did Oppenheimer (2023) gross?",a:952,unit:"million dollars",hint:"Christopher Nolan's atomic bomb story.",emoji:"💥"},
  {id:"film_170",q:"How many episodes does Killing Eve have?",a:32,unit:"episodes",hint:"4 seasons – Jodie Comer as Villanelle.",emoji:"🔪"},
  {id:"film_171",q:"In what year did FKA twigs' LP1 come out?",a:2014,unit:"year",hint:"One of the most influential albums of the 2010s.",emoji:"🎵"},
  {id:"film_172",q:"How many million dollars did La La Land gross?",a:446,unit:"million dollars",hint:"Emma Stone and Ryan Gosling dance through LA.",emoji:"🌆"},
  {id:"film_173",q:"How many seasons does Chernobyl have?",a:1,unit:"season",hint:"5 episodes – an HBO miniseries about the disaster.",emoji:"☢️"},
  {id:"film_174",q:"In what year did Lizzo's Cuz I Love You come out?",a:2019,unit:"year",hint:"Truth Hurts later became her biggest hit.",emoji:"🎵"},
  {id:"film_175",q:"How many million dollars did Schindler's List gross?",a:322,unit:"million dollars",hint:"Spielberg's Holocaust drama won 7 Oscars.",emoji:"🕯️"},
  {id:"film_176",q:"How many episodes does Sharp Objects have?",a:8,unit:"episodes",hint:"Amy Adams in the HBO miniseries.",emoji:"🔪"},
  {id:"film_177",q:"In what year did Clairo's Sling come out?",a:2021,unit:"year",hint:"An indie-pop sensation.",emoji:"🎵"},
  {id:"film_178",q:"How many million dollars did Everything Everywhere All at Once gross?",a:70,unit:"million dollars",hint:"Won 7 Oscars on a tiny budget.",emoji:"🥯"},
  {id:"film_179",q:"How many seasons does Invincible (Amazon) have?",a:2,unit:"seasons",hint:"An animated series about a teenage superhero.",emoji:"💪"},
  {id:"film_180",q:"In what year did Doja Cat's Planet Her come out?",a:2021,unit:"year",hint:"Need to Know became her biggest chart hit.",emoji:"🐱"},
  {id:"film_181",q:"How many million dollars did Rocketman gross?",a:195,unit:"million dollars",hint:"Elton John's biopic starring Taron Egerton.",emoji:"🎹"},
  {id:"film_182",q:"How many episodes does Yellowstone have?",a:55,unit:"episodes",hint:"5 seasons – Paramount's mega-hit.",emoji:"🤠"},
  {id:"film_183",q:"In what year did Solange's A Seat at the Table come out?",a:2016,unit:"year",hint:"One of the most important soul albums of the 2010s.",emoji:"🎵"},
  {id:"film_184",q:"How many million dollars did Knives Out gross?",a:311,unit:"million dollars",hint:"Rian Johnson's whodunit revival.",emoji:"🔪"},
  {id:"film_185",q:"How many seasons does Atlanta have?",a:4,unit:"seasons",hint:"Donald Glover's masterpiece.",emoji:"🌙"},
  {id:"film_186",q:"In what year did Phoebe Bridgers' Punisher come out?",a:2020,unit:"year",hint:"One of the best indie-folk albums of the decade.",emoji:"🎵"},
  {id:"film_187",q:"How many million dollars did The Martian gross?",a:631,unit:"million dollars",hint:"Matt Damon grows potatoes on Mars.",emoji:"🥔"},
  {id:"film_188",q:"How many seasons does Bridgerton have?",a:3,unit:"seasons",hint:"Netflix's Regency romance.",emoji:"🌸"},
  {id:"film_189",q:"In what year did Stromae's Multitude come out?",a:2022,unit:"year",hint:"His long-awaited third album.",emoji:"🎵"},
  {id:"film_190",q:"How many million dollars did Bohemian Rhapsody gross?",a:910,unit:"million dollars",hint:"Rami Malek as Freddie Mercury.",emoji:"🎸"},
  {id:"film_191",q:"How many episodes does Succession have?",a:39,unit:"episodes",hint:"4 seasons – one of the best series ever made.",emoji:"💼"},
  {id:"film_192",q:"In what year did Weyes Blood's Titanic Rising come out?",a:2019,unit:"year",hint:"An album about climate change.",emoji:"🌊"},
  {id:"film_193",q:"How many million dollars did Top Gun (1986) originally gross?",a:356,unit:"million dollars",hint:"The film that made Tom Cruise a star.",emoji:"✈️"},
  {id:"film_194",q:"How many seasons does Banshee have?",a:4,unit:"seasons",hint:"A brutal crime series on Cinemax.",emoji:"🔫"},
  {id:"film_195",q:"In what year did Burna Boy's Love, Damini come out?",a:2022,unit:"year",hint:"An Afrobeats superstar.",emoji:"🎵"},
  {id:"film_196",q:"How many million dollars did Morbius (2022) gross?",a:167,unit:"million dollars",hint:"It became a meme: 'It's Morbin Time'.",emoji:"🦇"},
  {id:"film_197",q:"How many seasons does Twin Peaks have?",a:3,unit:"seasons",hint:"David Lynch's masterpiece.",emoji:"🌲"},
  {id:"film_198",q:"In what year did Gorillaz' Demon Days come out?",a:2005,unit:"year",hint:"Feel Good Inc. was everywhere.",emoji:"🎵"},
  {id:"film_199",q:"How many million dollars did Se7en gross?",a:327,unit:"million dollars",hint:"'What's in the box?!'",emoji:"📦"},
  {id:"film_200",q:"How many seasons does The Expanse have?",a:6,unit:"seasons",hint:"Hard science fiction set in space.",emoji:"🚀"},
  {id:"film_201",q:"In what year did Jack Johnson's In Between Dreams come out?",a:2005,unit:"year",hint:"Banana Pancakes became a summer hit.",emoji:"🎵"},
  {id:"film_202",q:"How many million dollars did Sonic the Hedgehog (2020) gross?",a:319,unit:"million dollars",hint:"A redesign after fan backlash saved the film.",emoji:"💙"},
  {id:"film_203",q:"How many seasons does Black Sails have?",a:4,unit:"seasons",hint:"A pirate prequel to Treasure Island.",emoji:"🏴‍☠️"},
  {id:"film_204",q:"In what year did Caribou's Suddenly come out?",a:2020,unit:"year",hint:"Electronic music with emotion.",emoji:"🎵"},
  {id:"film_205",q:"How many million dollars did Parasite (2019) gross?",a:258,unit:"million dollars",hint:"The first non-English-language film to win Best Picture.",emoji:"🏠"},
  {id:"film_206",q:"How many seasons does Devs have?",a:1,unit:"season",hint:"An FX miniseries about quantum computing.",emoji:"💻"},
  {id:"film_207",q:"In what year did Sufjan Stevens' Carrie & Lowell come out?",a:2015,unit:"year",hint:"One of the saddest and most beautiful albums ever.",emoji:"🎵"},
  {id:"film_208",q:"How many episodes does The Sopranos have?",a:86,unit:"episodes",hint:"6 seasons – one of the best TV dramas ever made.",emoji:"🍕"},
  {id:"film_209",q:"In what year did Nirvana's In Utero come out?",a:1993,unit:"year",hint:"Their last studio album before Cobain's death.",emoji:"🎸"},
  {id:"film_210",q:"How many million dollars did Mission Impossible – Dead Reckoning gross?",a:568,unit:"million dollars",hint:"Tom Cruise still doing his own stunts.",emoji:"🎬"},
  {id:"film_211",q:"How many seasons does The Handmaid's Tale have?",a:5,unit:"seasons",hint:"Based on Margaret Atwood's novel.",emoji:"🔴"},
  {id:"film_212",q:"In what year did Kendrick Lamar's To Pimp a Butterfly come out?",a:2015,unit:"year",hint:"Critically praised as one of the most important albums ever.",emoji:"🎵"},
  {id:"film_213",q:"How many million dollars did The Notebook gross?",a:115,unit:"million dollars",hint:"Ryan Gosling and Rachel McAdams.",emoji:"💕"},
  {id:"film_214",q:"How many seasons does Breaking Bad have?",a:5,unit:"seasons",hint:"62 episodes about Walter White's downfall.",emoji:"🧪"},
  {id:"film_215",q:"In what year did Lady Gaga's The Fame come out?",a:2008,unit:"year",hint:"Poker Face became her first global hit.",emoji:"🎤"},
  {id:"film_216",q:"How many million dollars did Crazy Rich Asians gross?",a:238,unit:"million dollars",hint:"The first Hollywood film with an all-Asian lead cast since 1993.",emoji:"💰"},
  {id:"film_217",q:"How many seasons does Westworld on HBO have?",a:4,unit:"seasons",hint:"About AI and consciousness.",emoji:"🤖"},
  {id:"film_218",q:"In what year did Jay-Z's The Blueprint come out?",a:2001,unit:"year",hint:"Released on September 11, 2001.",emoji:"🎵"},
  {id:"film_219",q:"How many million dollars did John Wick 4 gross?",a:440,unit:"million dollars",hint:"Keanu Reeves as the unkillable hitman.",emoji:"🔫"},
  {id:"film_220",q:"How many seasons does Killing Eve have?",a:4,unit:"seasons",hint:"Sandra Oh and Jodie Comer.",emoji:"🔪"},
  {id:"film_221",q:"In what year did Rihanna's ANTI come out?",a:2016,unit:"year",hint:"Work was playing everywhere.",emoji:"🎵"},
  {id:"film_222",q:"How many million dollars did Glass Onion gross?",a:311,unit:"million dollars",hint:"The Knives Out sequel, exclusive to Netflix.",emoji:"🧅"},
  {id:"film_223",q:"In what year did Pharrell Williams' Happy come out?",a:2013,unit:"year",hint:"From the Despicable Me 2 soundtrack.",emoji:"😊"},
  {id:"film_224",q:"How many million dollars did Scream (2022) gross?",a:140,unit:"million dollars",hint:"A legacy sequel – 25 years after the original.",emoji:"🔪"},
  {id:"film_225",q:"How many seasons does Ted Lasso on Apple TV+ have?",a:3,unit:"seasons",hint:"A feel-good soccer drama.",emoji:"⚽"},
  {id:"film_226",q:"In what year did Billie Eilish's Happier Than Ever come out?",a:2021,unit:"year",hint:"Her second studio album.",emoji:"🎵"},
  {id:"film_227",q:"How many seasons does Skins (UK) have?",a:7,unit:"seasons",hint:"A British teen drama with a rotating cast.",emoji:"🎭"},
  {id:"film_228",q:"In what year did The Weeknd's Beauty Behind the Madness come out?",a:2015,unit:"year",hint:"Can't Feel My Face was a global hit.",emoji:"🎵"},
  {id:"film_229",q:"How many million dollars did The Nun gross?",a:365,unit:"million dollars",hint:"Part of the Conjuring universe.",emoji:"👻"},
  {id:"film_230",q:"How many seasons does Pose (FX) have?",a:3,unit:"seasons",hint:"An LGBTQ+ drama about 1980s ballroom culture.",emoji:"🌈"},
  {id:"film_231",q:"In what year did Macklemore's The Heist come out?",a:2012,unit:"year",hint:"Thrift Shop became a viral hit.",emoji:"🛍️"},
  {id:"film_232",q:"How many million dollars did Mamma Mia! gross?",a:608,unit:"million dollars",hint:"The ABBA musical, on screen.",emoji:"🎵"},
  {id:"film_233",q:"How many seasons does True Blood have?",a:7,unit:"seasons",hint:"A vampire drama on HBO.",emoji:"🧛"},
  {id:"film_234",q:"In what year did Katy Perry's Teenage Dream come out?",a:2010,unit:"year",hint:"5 songs from one album reached #1.",emoji:"🎤"},
  {id:"film_235",q:"How many million dollars did Nope (2022) gross?",a:171,unit:"million dollars",hint:"Jordan Peele's UFO horror film.",emoji:"👽"},
  {id:"film_236",q:"How many seasons does Alias have?",a:5,unit:"seasons",hint:"Jennifer Garner as a CIA agent.",emoji:"🕵️"},
  {id:"film_237",q:"In what year did Lorde's Melodrama come out?",a:2017,unit:"year",hint:"Perfect Places – one of her best albums.",emoji:"🎵"},
  {id:"film_238",q:"How many billion dollars did The Lion King (2019) gross?",a:1.66,unit:"billion dollars",hint:"A photorealistic remake of the classic.",emoji:"🦁"},
  {id:"film_239",q:"How many seasons does Justified have?",a:6,unit:"seasons",hint:"Timothy Olyphant as a US Marshal in Kentucky.",emoji:"🤠"},
  {id:"film_240",q:"In what year did Frank Ocean's Channel Orange come out?",a:2012,unit:"year",hint:"His breakthrough album.",emoji:"🍊"},
  {id:"film_241",q:"How many million dollars did Minions: The Rise of Gru gross?",a:940,unit:"million dollars",hint:"The little yellow guys are unstoppable.",emoji:"💛"},
  {id:"film_242",q:"How many seasons does Younger have?",a:7,unit:"seasons",hint:"Hilary Duff and Sutton Foster.",emoji:"👩"},
  {id:"film_243",q:"In what year did Queens of the Stone Age's Songs for the Deaf come out?",a:2002,unit:"year",hint:"No One Knows became their best-known song.",emoji:"🎸"},
  {id:"film_244",q:"How many million dollars did The Lost City gross?",a:190,unit:"million dollars",hint:"Sandra Bullock and Channing Tatum.",emoji:"🌿"},
  {id:"film_245",q:"How many seasons does Reign (CW) have?",a:4,unit:"seasons",hint:"About Mary, Queen of Scots.",emoji:"👑"},
];
