// 🚀 ASTRONOMY & PHYSICS – English
export default [
  {q:"How many light-years is the Andromeda Galaxy from Earth?",a:2500000,unit:"light-years",hint:"Sie is mit bloßem eye as kleiner Fleck sichtbar.",emoji:"🌌"},
  {q:"How many °C is the surface temperature of the Sun?",a:5500,unit:"°C",hint:"in the core are es sogar 15 million Grad.",emoji:"☀️"},
  {q:"How many km/s is the speed of light?",a:300000,unit:"km/s",hint:"Licht takes ~8 minutes of the Sonne to the Erde.",emoji:"💡"},
  {q:"How many Earth masses does Jupiter have?",a:318,unit:"Earth masses",hint:"Jupiter is the largest Planet unseres Sonnensystems.",emoji:"🪐"},
  {q:"How many Monde does Saturn have?",a:146,unit:"Monde",hint:"Saturn has the meisten Monde aller Planeten.",emoji:"🪐"},
  {q:"How many °C is es on the Moon nachts?",a:-170,unit:"°C",hint:"Tagsüber are es +130°C.",emoji:"🌙"},
  {q:"How many times größer is the Sonnendurchmesser as the Erddurchmesser?",a:109,unit:"times",hint:"the Sonnendurchmesser is 1,39 million km.",emoji:"☀️"},
  {q:"How many km is the Mond of the Erde entfernt?",a:384400,unit:"km",hint:"the Entfernung schwankt between 356.000 and 407.000 km.",emoji:"🌙"},
  {q:"How many years alt is the universe in billion?",a:13.8,unit:"billion years",hint:"since the Urknall.",emoji:"🌌"},
  {q:"How many km/h bewegt sich the Erde um the Sonne?",a:107000,unit:"km/h",hint:"the are etwa 30 km per second.",emoji:"🌍"},
  {q:"How many billion Sterne are there in the Milky Way?",a:200,unit:"billion",hint:"and billion weitere Galaxien in the universe.",emoji:"⭐"},
  {q:"How many minutes takes Licht of the Sonne to the Erde?",a:8,unit:"minutes",hint:"Licht rast mit 300.000 km/s – trotzdem takes es a Weile.",emoji:"☀️"},
  {q:"How hot is the core the Erde in °C?",a:6000,unit:"°C",hint:"Ähnlich heiß wie the Oberfläche the Sonne.",emoji:"🌍"},
  {q:"How many months takes a Jahr on Mars?",a:24,unit:"months",hint:"a Marsjahr takes 687 Erdtage.",emoji:"🔴"},
  {q:"How many times größer is the Sonne as the Erde?",a:1300000,unit:"times",hint:"1,3 million Erden würden in the Sonne passen.",emoji:"☀️"},
  {q:"How many °C is the Temperatur in the outer space?",a:-270,unit:"°C",hint:"Nahe the absoluten Nullpunkt of -273°C.",emoji:"❄️"},
  {q:"How many hours takes a Tag auf the Venus?",a:5832,unit:"hours",hint:"a Venusjahr is kürzer as a Venustag.",emoji:"🪐"},
  {q:"How many °C is the Temperatur auf the Merkur tagsüber?",a:430,unit:"°C",hint:"Nachts falls sie auf -180°C.",emoji:"☿"},
  {q:"How many km/h bewegt sich the ISS um the Erde?",a:28000,unit:"km/h",hint:"Sie umkreist the Erde all 90 minutes.",emoji:"🚀"},
  {q:"How many billion tons weighs 1 Teelöffel Neutronensternmaterial?",a:1,unit:"billion tons",hint:"Milliarde tons in a Teelöffel – unvorstellbar dicht.",emoji:"⭐"},
  {q:"How many km is a light-year lang in Billionen?",a:9.46,unit:"Billionen km",hint:"the Licht lays per year 9,46 Billionen km zurück.",emoji:"💡"},
  {q:"How many Monde does Mars have?",a:2,unit:"Monde",hint:"Phobos and Deimos – both sehr klein.",emoji:"🔴"},
  {q:"How many km is the Durchmesser the Erde?",a:12742,unit:"km",hint:"at the Äquator is sie etwas dicker as an the Polen.",emoji:"🌍"},
  {q:"How many km/h muss a Rakete fliegen um the Erde zu verlassen?",a:40000,unit:"km/h",hint:"the is the Fluchtgeschwindigkeit the Erde.",emoji:"🚀"},
  {q:"How many Astronauten were bisher on the Moon?",a:12,unit:"Astronauten",hint:"all 12 were Amerikaner, at the Apollo-Missionen.",emoji:"👨‍🚀"},
  {q:"How many Ringe does Saturn have?",a:7,unit:"Hauptringe",hint:"the Ringe bestehen from Eis and Gestein.",emoji:"🪐"},
  {q:"How far is Alpha Centauri of the Erde entfernt in Lichtjahren?",a:4,unit:"light-years",hint:"the nächste Sternensystem after unserem.",emoji:"⭐"},
  {q:"How many Atommassen does a Wasserstoffatom have?",a:1,unit:"Atommasseneinheit",hint:"Wasserstoff is the leichteste Element.",emoji:"⚛️"},
  {q:"How many billion Galaxien are there in the beobachtbaren universe?",a:2000,unit:"billion",hint:"2 Billionen Galaxien – each mit billion Sternen.",emoji:"🌌"},
  {q:"How fast bewegt sich the Schallgeschwindigkeit in Luft in m/s?",a:343,unit:"m/s",hint:"at 20°C Lufttemperatur.",emoji:"🔊"},
  {q:"How heavy is a Proton in the Vergleich zu a Elektron?",a:1836,unit:"times schwerer",hint:"the Proton is diese Zahl-fach schwerer.",emoji:"⚛️"},
  {q:"How many km/s is the Fluchtgeschwindigkeit of the Mond?",a:2.4,unit:"km/s",hint:"Viel niedriger as on Earth.",emoji:"🌙"},
  {q:"How many Grad does a Vollkreis have?",a:360,unit:"Grad",hint:"a uralte Konvention the Babylonier – heute still Standard.",emoji:"⭕"},
  {q:"How many Planeten does the unser solar system have?",a:8,unit:"Planeten",hint:"Pluto was 2006 to the Zwergplaneten degradiert.",emoji:"🪐"},
  {q:"How many km/h is the Windgeschwindigkeit a Hurrikans (Kategorie 5)?",a:252,unit:"km/h",hint:"Ab 252 km/h is es Kategorie 5.",emoji:"🌀"},
  {q:"How many km is the Radius the Erde?",a:6371,unit:"km",hint:"the mittlere Erdradius.",emoji:"🌍"},
  {q:"How many km/s is the Umlaufgeschwindigkeit the Erde?",a:30,unit:"km/s",hint:"29,8 km/s or rund 107.000 km/h.",emoji:"🌍"},
  {q:"How many hours takes a Tag auf Jupiter?",a:10,unit:"hours",hint:"Jupiter dreht sich at the fastest aller Planeten.",emoji:"🪐"},
  {q:"How many meters lang is the Internationale Raumstation ISS?",a:109,unit:"meters",hint:"So breit wie a Fußballfeld.",emoji:"🚀"},
  {q:"How many years alt is unsere Sonne?",a:4600000000,unit:"years",hint:"4,6 billion years – Mittag ihres Lebens.",emoji:"☀️"},
  {q:"How many km/h erwortht a Meteorit at Eintritt in the atmosphere?",a:72000,unit:"km/h",hint:"20 km/s – dabei verbrennt er meist.",emoji:"☄️"},
  {q:"How many °C is the Temperatur in the Erdmittelpunkt?",a:6000,unit:"°C",hint:"Ähnlich wie the Sonnenoberfläche.",emoji:"🔥"},
  {q:"How many times größer is Jupiters Durchmesser as the Erde?",a:11,unit:"times",hint:"Jupiter has 139.820 km Durchmesser.",emoji:"🪐"},
  {q:"How many hours takes a Umdrehung the Erde um ihre Achse?",a:24,unit:"hours",hint:"Genauer: 23 hours 56 minutes.",emoji:"🌍"},
  {q:"How many Astronomische Einheiten is Neptun of the Sonne entfernt?",a:30,unit:"AE",hint:"1 AE = Erde-Sonne-Abstand. Licht takes 4 hours zu Neptun.",emoji:"🔵"},
  {q:"How many Monde does the Uranus have?",a:27,unit:"Monde",hint:"all after Shakespeare-Figuren benannt.",emoji:"🟦"},
  {q:"How many °C is the Kerntemperatur the Sonne?",a:15000000,unit:"°C",hint:"15 million Grad – da findet Kernfusion statt.",emoji:"☀️"},
  {q:"How many km/s is the Fluchtgeschwindigkeit of the Erde?",a:11.2,unit:"km/s",hint:"11,2 km/s or 40.000 km/h.",emoji:"🚀"},
  {q:"How many °C is es auf the Saturn?",a:-178,unit:"°C",hint:"the Wolkenobergrenze is sehr kalt.",emoji:"🪐"},
  {q:"How many years takes a Pluto-Jahr?",a:248,unit:"Erdenjahre",hint:"years for einen orbit um the Sonne.",emoji:"🌑"},
  {q:"How many km is the Milky Way breit?",a:100000,unit:"light-years",hint:"100.000 light-years Durchmesser.",emoji:"🌌"},
  {q:"How many hours takes a Jahr auf Merkur?",a:1408,unit:"hours",hint:"88 Erdtage – the kürzeste Planetenjahr.",emoji:"☿"},
  {q:"How many light-years is the Oortsche Wolke of the Sonne entfernt?",a:1,unit:"light-year",hint:"the äußerste Grenze unseres Sonnensystems – 50.000 AE.",emoji:"☄️"},
  {q:"How many m/s² is the Erdbeschleunigung?",a:9.81,unit:"m/s²",hint:"the freie Fall beschleunigt mit 9,81 m/s².",emoji:"⬇️"},
  {q:"How many years takes a Uranus-Jahr?",a:84,unit:"years",hint:"Erdenjahre for einen orbit.",emoji:"🟦"},
  {q:"How many km/h is the fastest menschgemachte Sonde (Parker Solar Probe)?",a:692000,unit:"km/h",hint:"the fastest of personen gebaute Maschine.",emoji:"🚀"},
  {q:"How many °C is the Temperatur auf Neptun?",a:-214,unit:"°C",hint:"the coldest Planet in the solar system.",emoji:"🔵"},
  {q:"How many Astronomische Einheiten is Pluto of the Sonne entfernt?",a:39,unit:"AE",hint:"AE – fast 40 times so weit wie the Erde.",emoji:"🌑"},
  {q:"How many hours takes a Jupiterjahr?",a:87672,unit:"hours",hint:"12 Erdenjahre for einen orbit.",emoji:"🪐"},
  {q:"How many Grad dreht sich the Erde per hour?",a:15,unit:"Grad",hint:"360° in 24h = 15° per hour.",emoji:"🌍"},
  {q:"How many km is the Abstand Erde-Sonne in Astronomischen Einheiten?",a:1,unit:"Astronomische Einheit",hint:"AU = 149,6 million km.",emoji:"☀️"},
  {q:"How many Hertz schwingen sichtbare Lichtwellen (in Billionen)?",a:600,unit:"Billionen Hz",hint:"400-700 THz – in the Beworth the sichtbaren Lichts.",emoji:"💡"},
  {q:"How many watts there are the Sonne ab?",a:386000000000000000000000000,unit:"watts",hint:"3,86 × 10²⁶ watts – unvorstellbare Leistung.",emoji:"☀️"},
  {q:"How many tons Materie wandelt the Sonne per second in Energie um?",a:4000000,unit:"tons",hint:"4 million tons per second.",emoji:"☀️"},
  {q:"How many km is the Durchmesser the Großen Roten Flecks auf Jupiter?",a:16000,unit:"km",hint:"a Sturm since 350 Jahren.",emoji:"🪐"},
  {q:"How many light-years is the Zentrum unserer Milky Way entfernt?",a:26000,unit:"light-years",hint:"a supermasseworthes Schwarzes Loch liegt dort.",emoji:"🌌"},
  {q:"How many km/h dreht sich Jupiter an seinem Äquator?",a:45000,unit:"km/h",hint:"fastest Rotation aller Planeten.",emoji:"🪐"},
  {q:"How many Nanometer are sichtbares Licht breit?",a:700,unit:"Nanometer",hint:"400-700 nm Wellenlänge.",emoji:"🌈"},
  {q:"How many °C is the Temperatur in a Blitz?",a:30000,unit:"°C",hint:"5x heißer as the Sonnenoberfläche.",emoji:"⚡"},
  {q:"How many million km is the Mars of the Erde entfernt (Durchschnitt)?",a:225,unit:"million km",hint:"Variiert stark – of 56 bis 401 Mio. km.",emoji:"🔴"},
  {q:"How many billion km is the Sonne of the Zentrum the Milky Way?",a:26000,unit:"light-years",hint:"at the Rand the Milky Way.",emoji:"🌌"},
  {q:"How many years würde a Autofahrt to the Sonne at 200 km/h dauern?",a:97,unit:"years",hint:"150 million km ÷ 200 km/h = 850.000 hours.",emoji:"🚗"},
  {q:"How many kg weighs 1 m³ water?",a:1000,unit:"kg",hint:"water has the Dichte of 1 kg/liters.",emoji:"💧"},
  {q:"How many km/h bewegt sich the Schall in the water?",a:5400,unit:"km/h",hint:"5x schneller as in Luft.",emoji:"🌊"},
  {q:"How many hours takes a Neptun-Rotation?",a:16,unit:"hours",hint:"a Neptuner Tag takes diese Zeit hours.",emoji:"🔵"},
  {q:"How many Sonnen würden in a Schwarzes Loch (Sagittarius A*) passen?",a:4000000,unit:"solar masses",hint:"the Schwarze Loch in the Zentrum the Milky Way.",emoji:"🌑"},
  {q:"How many km lang is the Durchmesser a typischen Neutronensterns?",a:20,unit:"km",hint:"Unvorstellbar dicht auf kleinstem Raum.",emoji:"⭐"},
  {q:"How many °C is the Hitze at the Kernfusion in the Sonne?",a:15000000,unit:"°C",hint:"in the core – Wasserstoff is zu Helium.",emoji:"⚛️"},
  {q:"How many km/s entfernt sich the universe at the Rande of uns?",a:300000,unit:"km/s",hint:"at the Rand expandiert es mit speed of light.",emoji:"🌌"},
  {q:"How many years takes a Saturnjahr?",a:29.5,unit:"years",hint:"29,5 Erdenjahre for einen orbit.",emoji:"🪐"},
  {q:"How many meters tief wäre the Ozean wenn the Erde kugelförmig glatt wäre?",a:2700,unit:"meters",hint:"all Berge würden in the Meer versinken.",emoji:"🌊"},
  {q:"How many Kilowattstunden Energie liefert 1 grams Uran?",a:24000,unit:"kWh",hint:"a grams Uran entspricht 3 tons Kohle.",emoji:"⚛️"},
  {q:"How many million km is the Erde of the Sonne entfernt?",a:150,unit:"million km",hint:"the is the Definition the Astronomischen Einheit (1 AE).",emoji:"☀️"},
  {q:"How many Grad kühlt sich the atmosphere pro km Höhe ab?",a:6.5,unit:"°C/km",hint:"the adiabatische Temperaturgradient.",emoji:"🌡️"},
  {q:"How many Joule does the 1 Kilowattstunde have?",a:3600000,unit:"Joule",hint:"3,6 million Joule.",emoji:"⚡"},
  {q:"How many months takes a Merkur-Jahr?",a:3,unit:"months",hint:"only 88 days – fastest orbit.",emoji:"☿"},
  {q:"Mit wie vielen km/s rasen Gammastrahlen through the All?",a:300000,unit:"km/s",hint:"speed of light – the fastest in the universe.",emoji:"💥"},
  {q:"How many Grad does Earth have Axialneigung?",a:23.5,unit:"Grad",hint:"Verursacht the Jahreszeiten.",emoji:"🌍"},
  {q:"How many km is the Umfang the Mondes?",a:10917,unit:"km",hint:"Viel kleiner as the Erde.",emoji:"🌙"},
  {q:"How many Nanometer dick is a menschliches Haar in the Vergleich zu Lichtwellen?",a:700,unit:"Nanometer",hint:"Licht and Haare are ähnlich breit.",emoji:"💇"},
  {q:"How many Atmosphären Druck herrscht in 10.000 Metern Wassertiefe?",a:1000,unit:"Atmosphären",hint:"the Druck in the Tiefsee is kaum vorstellbar.",emoji:"🌊"},
  {q:"How many °C is the average Temperatur on Mars?",a:-60,unit:"°C",hint:"between -125°C and +20°C.",emoji:"🔴"},
  {q:"How many m/s² is the Schwerkraft on the Moon?",a:1.6,unit:"m/s²",hint:"1/6 the Erdgravitation.",emoji:"🌙"},
  {q:"How many km Dicke does the Erdkruste in the Durchschnitt have?",a:35,unit:"km",hint:"under Ozeanen only 10 km, under Kontinenten 35 km.",emoji:"🌍"},
  {q:"How many billion tons weighs the Erdatmosphäre?",a:5600,unit:"Billionen kg",hint:"5,6 Quadrillionen kg.",emoji:"💨"},
  {q:"How many km/h dreht sich the Erde at the Äquator?",a:1670,unit:"km/h",hint:"Wir spüren es not – weil wir uns mit bewegen.",emoji:"🌍"},
  {q:"How many °C wärmer würde es ohne Treibhauseffekt on Earth?",a:33,unit:"°C kälter",hint:"Ohne natural Treibhauseffekt wäre es -18°C.",emoji:"🌡️"},
  {q:"How many km/h is the maximale Windgeschwindigkeit auf Neptun?",a:2100,unit:"km/h",hint:"the stärksten bekannten Winde in the solar system.",emoji:"🌀"},
  {q:"How many billion km of the Sonne is the Voyager 1 entfernt?",a:23500,unit:"million km",hint:"Stand 2023 – sie was 1977 gestartet.",emoji:"🚀"},
  {q:"How many kg Mondgestein brachten the Apollo-Missionen mit?",a:382,unit:"kg",hint:"Kg Mondgestein – still immer analysiert.",emoji:"🌙"},
  {q:"How many °C is the Temperatur in a Blitzkern?",a:27000,unit:"°C",hint:"Heißer as the Sonnenoberfläche.",emoji:"⚡"},
  {q:"How many km/h müsste man fliegen um in Erdumlaufbahn zu bleiben?",a:28000,unit:"km/h",hint:"first kosmische Geschwindigkeit.",emoji:"🚀"},
  {q:"How many hours takes a Marsianer-Tag?",a:24.6,unit:"hours",hint:"Fast wie a Erdtag.",emoji:"🔴"},
  {q:"How many °C is es auf the Sonnenkorona?",a:2000000,unit:"°C",hint:"Mysteriöserweise viel heißer as the Oberfläche.",emoji:"☀️"},
  {q:"How many million km is Merkur of the Sonne entfernt?",a:58,unit:"million km",hint:"the sonnennächste Planet.",emoji:"☿"},
  {q:"How many hours takes a Jahr auf Venus?",a:5392,unit:"hours",hint:"225 Erdtage – and a Tag is länger as a Jahr.",emoji:"🪐"},
  {q:"How many Trillionen tons weighs the Mond?",a:73,unit:"Trillionen tons",hint:"7,35 × 10²² kg.",emoji:"🌙"},
  {q:"How many °C kälter is the Weltraum as the Erde?",a:287,unit:"°C kälter",hint:"Erde is on average 15°C, outer space -273°C.",emoji:"❄️"},
  {q:"How many km hoch is the Mount Olympus on Mars?",a:22,unit:"km",hint:"the höchste Vulkan in the solar system.",emoji:"🔴"},
  {q:"How many Erden passen in the Sonne?",a:1300000,unit:"Erden",hint:"1,3 million Erden.",emoji:"☀️"},
  {q:"How many billion tons Kohlendioxid atmet the personheit per year from?",a:3,unit:"billion tons",hint:"billion tons CO₂ through Atmung.",emoji:"💨"},
  {q:"How many times per second dreht sich a Neutronenstern?",a:700,unit:"times",hint:"Pulsare rotieren bis zu 716 times per second.",emoji:"⭐"},
  {q:"How many km is the Grenze to the Weltraum (Kármán-Linie)?",a:100,unit:"km",hint:"Ab 100 km beginnt offiziell the Weltraum.",emoji:"🚀"},
  {q:"How many hours after the Urknall bildeten sich first Atome?",a:380000,unit:"years",hint:"380.000 years after the Urknall – the universe kühlte ab.",emoji:"⚛️"},
  {q:"How many kg Mondstaub are there pro m² Mondoberfläche?",a:10,unit:"tons/m²",hint:"the Regolith is mehrere meters tief.",emoji:"🌙"},
  {q:"How many billion tons water are there on Earth?",a:1400000000,unit:"billion liters",hint:"1,4 billion Kubikkilometer water.",emoji:"🌊"},
  {q:"How many km/h dreht sich a Tornado?",a:480,unit:"km/h",hint:"Stärkste Tornados erworthen over 480 km/h.",emoji:"🌪️"},
  {q:"How many times kleiner is a Proton as a Atom?",a:100000,unit:"times",hint:"the Atom is zu 99,9% leer.",emoji:"⚛️"},
  {q:"How many Grad is the maximale Sonneneinstrahlung on Mars?",a:20,unit:"°C",hint:"in the Sommer at the Äquator – nachts -60°C.",emoji:"🔴"},
  {q:"How many km/h can Sonnenwind-Teilchen erworthen?",a:900000,unit:"km/h",hint:"at koronalen Masseauswürfen still schneller.",emoji:"☀️"},
  {q:"How many Grad breit is the Sichtfeld the Hubble-Teleskops?",a:0.05,unit:"Grad",hint:"only a kleiner Ausschnitt – and trotzdem voller Galaxien.",emoji:"🔭"},
  {q:"How many billion km weit flies Licht in a Jahr?",a:9460,unit:"billion km",hint:"9,46 Billionen km – a light-year.",emoji:"💡"},
  {q:"How many Grad is the maximale Temperatur auf the Venusoberfläche?",a:465,unit:"°C",hint:"Heißer as Merkur – trotz größerer Entfernung to the Sonne.",emoji:"🌋"},
  {q:"How many Trillionen tons weighs the Erdatmosphäre?",a:5.6,unit:"Trillionen tons",hint:"5,6 Billiarden tons Luft.",emoji:"💨"},
  {q:"How many billion years does the unsere Sonne still zu leben have?",a:5,unit:"billion years",hint:"Dann is sie to the roten Riesen.",emoji:"☀️"},
  {q:"How many meters/Sekunde² is the Schwerkraft auf Jupiter?",a:24.8,unit:"m/s²",hint:"2,5x stärker as on Earth.",emoji:"🪐"},
  {q:"How many km tief is the Mariana Trench?",a:11034,unit:"meters",hint:"the tiefste Punkt the Weltmeere.",emoji:"🌊"},
  {q:"How many billion tons weighs unsere Milky Way?",a:2000000000000,unit:"solar masses",hint:"a Billion solar masses.",emoji:"🌌"},
  {q:"How many km is the Abstand zweier Elektronen in a Atom?",a:0.0000001,unit:"mm",hint:"Unvorstellbar klein – Quantenphysik.",emoji:"⚛️"},
  {q:"How many °C is es an the Polen the Mars?",a:-125,unit:"°C",hint:"CO₂-Eis bildet sich an the Polkappen.",emoji:"🔴"},
  {q:"How many km/h schnell is the fastest Jet-Flugzeug (SR-71)?",a:3530,unit:"km/h",hint:"Mach 3,3 – still nie abgeschossen.",emoji:"✈️"},
  {q:"How much times dichter is the Sonnenkern as water?",a:150,unit:"times",hint:"G/cm³ – the is um a Vielfaches dichter as water.",emoji:"☀️"},
  {q:"How many km/s bewegen sich Galaxien of uns weg?",a:67,unit:"km/s pro Megaparsec",hint:"the Hubble-Konstante beschreibt the Expansion.",emoji:"🌌"},
  {q:"How many billion light-years groß is the beobachtbare universe?",a:93,unit:"billion light-years",hint:"the sichtbare Teil – the universe könnte unendlich groß sein.",emoji:"🌌"},
  {q:"How many °C is the coldest natürlich ever measured Temperatur on Earth?",a:-89.2,unit:"°C",hint:"Gemessen in the Antarktis 1983.",emoji:"🧊"},
  {q:"How many km hoch fliegen Stratosphären-Wolken?",a:25,unit:"km",hint:"Perlmutt-Wolken in the Stratosphäre.",emoji:"☁️"},
  {q:"How many hours takes a Sonnenfinsternis maximal?",a:7.5,unit:"minutes",hint:"Maximal 7,5 minutes totale Finsternis.",emoji:"🌑"},
  {q:"How many km lang is the Canyons on Mars (Valles Marineris)?",a:4000,unit:"km",hint:"10x länger as the Grand Canyon.",emoji:"🔴"},
  {q:"How many °C is the hottest ever measured Temperatur on Earth?",a:56.7,unit:"°C",hint:"Death Valley 1913.",emoji:"🌡️"},
  {q:"How many billion tons weighs 1 m³ Neutronensternmaterie?",a:10000000,unit:"billion tons",hint:"10¹⁶ kg – a Zuckerwürfel würde the Erde zerquetschen.",emoji:"⭐"},
  {q:"How many km/h is the Schall in Stahl?",a:18000,unit:"km/h",hint:"50x schneller as in Luft.",emoji:"🔧"},
  {q:"How many hours takes es bis Pluto seinen eigenen Schatten umrundet?",a:153,unit:"hours",hint:"Pluto dreht sich sehr langsam.",emoji:"🌑"},
  {q:"How many billion km groß is the Ereignishorizont of M87*?",a:40,unit:"billion km",hint:"the first fotografierte Schwarzes Loch.",emoji:"🌑"},
  {q:"How many °C is the Unterschied between Tag and Nacht on the Moon?",a:300,unit:"°C",hint:"+130°C tagsüber, -170°C nachts.",emoji:"🌙"},
  {q:"How many km/h dreht sich a Hurrikan maximal?",a:300,unit:"km/h",hint:"Kategorie 5 Hurrikane over 250 km/h.",emoji:"🌀"},
  {q:"How many billion tons Sauerstoff contains the Erdatmosphäre?",a:1200,unit:"Billionen tons",hint:"21% the atmosphere is Sauerstoff.",emoji:"💨"},
  {q:"How many km dick is the Saturnring?",a:1,unit:"km",hint:"Bis zu 1 km – dünn wie a Blatt Papier relativ to the Breite.",emoji:"🪐"},
  {q:"How many hours liegt the ISS in the Erdschatten per day?",a:16,unit:"Sonnenaufgänge",hint:"the ISS erlebt 16 Sonnenauf- and -untergänge daily.",emoji:"🚀"},
  {q:"How many km/h is the maximale Windgeschwindigkeit a Tornados?",a:480,unit:"km/h",hint:"EF5-Tornados are the stärksten.",emoji:"🌪️"},
  {q:"How many billion years alt is the oldest bekannte Gestein on Earth?",a:4,unit:"billion years",hint:"Gefunden in Australien.",emoji:"🪨"},
  {q:"How many km is the Erdmond of the Erde in a Jahr entfernt?",a:3.8,unit:"cm weiter",hint:"the Mond entfernt sich annually 3,8 cm.",emoji:"🌙"},
  {q:"How many tons Asteroiden treffen the Erde per year?",a:40000,unit:"tons",hint:"as Meteorstaub – meist verglüht.",emoji:"☄️"},
  {q:"How many km is the Durchmesser the Großen Roten Flecks?",a:16000,unit:"km",hint:"Größer as the Erde.",emoji:"🪐"},
  {q:"How many billion light-years is the CMB of uns entfernt?",a:46,unit:"billion light-years",hint:"the oldest beobachtbare Horizont – the kosmische Hintergrundstrahlung.",emoji:"🌌"},
  {q:"How many km/s is the Geschwindigkeit the Expansion the Universums?",a:67,unit:"km/s/Mpc",hint:"the Hubble-Konstante.",emoji:"🌌"},
  {q:"How many hours takes the Sonnensturm of the Sonne bis to the Erde?",a:2,unit:"hours",hint:"Koronale Masseauswürfe kommen in 1-3 Tagen – aber Strahlung in minutes.",emoji:"☀️"},
  {q:"How many meters/Sekunde² is the Schwerkraft auf Pluto?",a:0.62,unit:"m/s²",hint:"only 6% the Erdgravitation.",emoji:"🌑"},
  {q:"How many billion Neutrinos passieren einen cm² the Erde per second?",a:65,unit:"billion",hint:"Neutrinos kommen of the Sonne and gehen through alles hindurch.",emoji:"⚛️"},
  {q:"How many °C is the Temperatur in the Innern a Tornados?",a:-10,unit:"°C",hint:"in the eye a Tornados is es kühler.",emoji:"🌪️"},
  {q:"How many km lang is the Valles Marineris on Mars?",a:4000,unit:"km",hint:"the largest Canyon-System in the solar system.",emoji:"🔴"},
  {q:"How many billion km is Neptun of the Sonne entfernt?",a:4500,unit:"billion km",hint:"Licht takes 4 hours of the Sonne zu Neptun.",emoji:"🔵"},
  {q:"How many kg Gold are there in the universe pro Kubikparsec?",a:0.000001,unit:"solar masses",hint:"Gold is selten – entsteht only at Neutronenstern-Kollisionen.",emoji:"🪙"},
  {q:"How many km/s is the Relativgeschwindigkeit the Andromeda-Galaxie to the Milky Way?",a:110,unit:"km/s",hint:"Sie bewegen sich aufeinander zu – Kollision in 4 Mrd. Jahren.",emoji:"🌌"},
  {q:"How many Quadrillionen tons Eis are there in the Antarktis?",a:26.5,unit:"million Gigatonnen",hint:"26,5 million Gigatonnen Eis.",emoji:"🧊"},
  {q:"How many hours takes a Erd-Sonnenjahr genau?",a:8766,unit:"hours",hint:"365,25 days × 24 hours.",emoji:"📅"},
  {q:"How many billion years is the Mond alt?",a:4.5,unit:"billion years",hint:"Er entstand through a Kollision mit the Proto-Erde.",emoji:"🌙"},
  {q:"How many °C is the kühlste bekannte Ort in the universe?",a:-273,unit:"°C",hint:"the Boomerang-Nebel is 1 Kelvin kühl.",emoji:"❄️"},
  {q:"How many light-years breit is the solar system (Oortsche Wolke)?",a:2,unit:"light-years",hint:"light-years Durchmesser.",emoji:"☄️"},
  {q:"How many tons Meteoritenstaub falls daily auf the Erde?",a:100,unit:"tons",hint:"Meist as Mikrometeorite.",emoji:"☄️"},
  {q:"How many Nanometer is the sichtbare Lichtspektrum breit?",a:300,unit:"Nanometer",hint:"of 400nm (violett) bis 700nm (rot).",emoji:"🌈"},
  {q:"How many years dauerte es bis to the first schwarzen Loch-Foto?",a:100,unit:"years Theoriezeit",hint:"Einstein beschrieb sie 1915, fotografiert 2019.",emoji:"🌑"},
  {q:"How many °C is the Temperatur in a Weißen Zwerg?",a:100000,unit:"°C",hint:"Weiße Zwerge kühlen over billion years ab.",emoji:"⭐"},
  {q:"How many km is the Durchmesser the Mondes?",a:3474,unit:"km",hint:"Etwa 27% the Erddurchmessers.",emoji:"🌙"},
  {q:"How many hours takes a Venustag genau?",a:5832,unit:"hours",hint:"a Venusjahr (224 days) is kürzer as a Venustag.",emoji:"🪐"},
  {q:"How many km/h dreht sich Neptun an seinem Äquator?",a:9650,unit:"km/h",hint:"Schnellere Rotation as the Erde.",emoji:"🔵"},
  {q:"How many °C kalt is es in the Schatten on the Moon?",a:-170,unit:"°C",hint:"Extreme Temperaturschwankungen ohne atmosphere.",emoji:"🌑"},
  {q:"How far is the Magellangsche Wolke of the Milky Way?",a:160000,unit:"light-years",hint:"the nächste Satellitengalaxie.",emoji:"🌌"},
  {q:"How many tons weighs a Kubikmeter Neutronensternmaterial?",a:1000,unit:"Billionen tons",hint:"10¹⁵ tons pro m³.",emoji:"⭐"},
  {q:"How many hours würde es dauern um mit the Auto to the Mond zu fahren?",a:5100,unit:"hours",hint:"at 100 km/h würde man 5100 hours brauchen.",emoji:"🌙"},
  {q:"How many °C warm is the Chromosphäre the Sonne?",a:20000,unit:"°C",hint:"the Schicht over the Photosphäre.",emoji:"☀️"},
  {q:"How many billion years is the Sonne still Energie produzieren?",a:5,unit:"billion years",hint:"Dann is sie to the Roten Riesen.",emoji:"☀️"},
  {q:"How many km is the Durchmesser of Titan (Saturnmond)?",a:5150,unit:"km",hint:"Größer as Merkur.",emoji:"🪐"},
  {q:"How many °C is the Temperatur auf Io (Jupiters Mond)?",a:-130,unit:"°C",hint:"Vulkanisch aktiv trotz extremer Kälte.",emoji:"🌋"},
  {q:"How many km/s bewegt sich unsere Sonne through the Milky Way?",a:220,unit:"km/s",hint:"a Galaktisches Jahr takes 225 million years.",emoji:"🌌"},
  {q:"How many °C kalt is the dunkelste bekannte Ort (Boomerang-Nebel)?",a:-272,unit:"°C",hint:"Kälter as the kosmische Hintergrund.",emoji:"❄️"},
  {q:"How many billion years takes Licht um the universe zu überqueren?",a:93,unit:"billion years",hint:"the Durchmesser is diese Zahl billion light-years.",emoji:"🌌"},
  {q:"How many km hoch is the atmosphere the Mars?",a:200,unit:"km",hint:"Sehr dünn – weniger as 1% Erddruck.",emoji:"🔴"},
  {q:"How many hours takes Licht of Neptun to the Erde?",a:4,unit:"hours",hint:"Neptun is diese Zahl,5 billion km entfernt.",emoji:"🔵"},
  {q:"How many °C is the Temperatur auf Titania (Uranus-Mond)?",a:-203,unit:"°C",hint:"a the coldest Monde.",emoji:"🌑"},
  {q:"How many km/h fliegen Sonnenwinde schnell?",a:500000,unit:"km/h",hint:"at Sonnenstürmen still deutlich schneller.",emoji:"☀️"},
  {q:"How many billion Sterne does the Andromeda-Galaxie have?",a:1000,unit:"billion",hint:"Fast doppelt so viele wie the Milky Way.",emoji:"🌌"},
  {q:"How many °C is the Innere the Jupiterkerns?",a:36000,unit:"°C",hint:"Extremer Druck and Hitze in the Zentrum.",emoji:"🪐"},
  {q:"How many km is the Durchmesser of Ceres (Zwergplanet)?",a:945,unit:"km",hint:"the largest Körper in the Asteroidengürtel.",emoji:"🌑"},
  {q:"How many Earth masses does the Neptun have?",a:17,unit:"Earth masses",hint:"Viel kleiner as Jupiter aber immer still gewaltig.",emoji:"🔵"},
  {q:"How many km/s rotiert a Pulsar maximal?",a:0.3,unit:"km/s Oberfläche",hint:"716 Umdrehungen per second.",emoji:"⭐"},
  {q:"How many °C is the Temperatur in the core of Uranus?",a:5000,unit:"°C",hint:"Trotz äußerer Kälte is the core sehr heiß.",emoji:"🟦"},
  {q:"How many km hoch are the Wolken auf Jupiter?",a:50,unit:"km",hint:"Mehrere Schichten from Ammoniak and anderen Verbindungen.",emoji:"🪐"},
  {q:"How many tons Materie loses the Sonne per second through Strahlung?",a:4000000,unit:"tons",hint:"4 million tons daily in Energie umgewandelt.",emoji:"☀️"},
  {q:"How many hours takes a Lichtstrahl of Pluto to the Erde?",a:5.5,unit:"hours",hint:"Pluto is ~5,9 billion km weit.",emoji:"🌑"},
  {q:"How many km/h dreht sich the Erde um the Galaxis?",a:792000,unit:"km/h",hint:"220 km/s um the galaktische Zentrum.",emoji:"🌌"},
  {q:"How many Grad is the Inklination of Uranus?",a:98,unit:"Grad",hint:"Uranus liegt fast auf the Seite.",emoji:"🟦"},
  {q:"How many billion Sonnen leuchten in the beobachtbaren universe?",a:2000000000000,unit:"Sterne",hint:"2 Billionen Galaxien mit ever ~200 billion Sternen.",emoji:"⭐"},
  {q:"How many years takes Pluto for einen orbit um the Sonne?",a:248,unit:"Erdenjahre",hint:"Seine Umlaufbahn is sehr elliptisch.",emoji:"🌑"},
  {q:"How many °C is the Oberfläche of Enceladus (Saturnmond)?",a:-201,unit:"°C",hint:"under the Eis are there flüssiges water.",emoji:"❄️"},
  {q:"How many million km are Erde and Mars auf the nächsten Punkt voneinander entfernt?",a:56,unit:"million km",hint:"million km at the besten Annäherung.",emoji:"🔴"},
  {q:"How many °C kalt is the interstellare Materie between Sternen?",a:-263,unit:"°C",hint:"Fast absoluter Nullpunkt.",emoji:"❄️"},
  {q:"How many million km lang ca Kometen-Schweif are?",a:150,unit:"million km",hint:"Kometen-Schweife can the Sonne-Erde-Distanz erworthen.",emoji:"☄️"},
  {q:"How many Trillionen tons weighs the Mond?",a:73,unit:"Trillionen tons",hint:"7,35 × 10²² kg.",emoji:"🌙"},
  {q:"How many hours was the longest Apollo-Mission (Apollo 17) on the Moon?",a:75,unit:"hours",hint:"3 days 3 hours auf the Mondoberfläche.",emoji:"🌙"},
  {q:"How many billion light-years is the oldest bekannte Licht entfernt?",a:13.8,unit:"billion light-years",hint:"the kosmische Hintergrundstrahlung.",emoji:"🌌"},
  {q:"How many °C is the Temperatur in Jupiters Sturm (Großer Roter Fleck)?",a:-160,unit:"°C",hint:"Kälter as the umgebenden Wolken.",emoji:"🪐"},
  {q:"How many billion km entfernt is the Heliopause (Grenze the Sonnensystems)?",a:18,unit:"billion km",hint:"the Heliopause – wo Sonnenwind endet.",emoji:"☄️"},
  {q:"How many Earth masses does the Uranus have?",a:14.5,unit:"Earth masses",hint:"Uranus is the kleinste Eisriese.",emoji:"🟦"},
  {q:"How many °C is the hottest bekannte Stern (WR 102)?",a:210000,unit:"°C",hint:"200x heißer as unsere Sonne.",emoji:"⭐"},
  {q:"How many °C is the Oberfläche of Io (Jupiters Mond) an Vulkanen?",a:1600,unit:"°C",hint:"Io has the aktivsten Vulkane in the solar system.",emoji:"🌋"},
  {q:"How many billion km is the Oortsche Wolke of the Sonne entfernt?",a:7500,unit:"billion km",hint:"the äußerste Beworth unseres Sonnensystems.",emoji:"☄️"},
  {q:"How many hours takes Jupiter for einen orbit um the Sonne?",a:87672,unit:"hours",hint:"12 Erdenjahre.",emoji:"🪐"},
  {q:"How many km Dicke does the eurospas Eisdecke (Jupitermond) have?",a:25,unit:"km",hint:"under the Eis: flüssiger Ozean.",emoji:"❄️"},
  {q:"How many billion Sterne entstehen per year in the Milky Way?",a:1,unit:"Sterne/Jahr",hint:"Etwa 1 neuer Stern per year.",emoji:"⭐"},
  {q:"How many °C kalt is the Mond-Polregion (dauerhafter Schatten)?",a:-248,unit:"°C",hint:"Fast absoluter Nullpunkt in the Kratern.",emoji:"🌑"},
  {q:"How many km/h is the Rotationsgeschwindigkeit of Saturns core?",a:30000,unit:"km/h",hint:"Sehr schnelle Rotation the Gasriesen.",emoji:"🪐"},
  {q:"How many billion years takes the Sonne for a Umdrehung um the Milky Way?",a:0.225,unit:"billion years",hint:"225 million years – a galaktisches Jahr.",emoji:"🌌"},
  {q:"How many °C is the Coronaregion the Sonne?",a:2000000,unit:"°C",hint:"Mysteriöserweise heißer as the Oberfläche.",emoji:"☀️"},
  {q:"How many km is the Durchmesser of Enceladus (Saturnmond)?",a:500,unit:"km",hint:"Kleiner Mond mit riesigem Wasserausbruch.",emoji:"🪐"},
  {q:"How many hours takes a Tag auf Pluto?",a:153,unit:"hours",hint:"6 Erdtage 9 hours.",emoji:"🌑"},
  {q:"How many million tons Helium produces the Sonne daily?",a:695,unit:"million tons",hint:"million tons daily.",emoji:"☀️"},
  {q:"How many km Höhe does the Mount Olympus on Mars have?",a:21,unit:"km",hint:"the höchste bekannte Vulkan in the solar system.",emoji:"🔴"},
  {q:"How many °C is the Temperatur auf the Venus-Oberfläche nachts?",a:465,unit:"°C",hint:"Tag and Nacht fast gleich heiß through Treibhauseffekt.",emoji:"🌋"},
  {q:"How many km/h bewegen sich interstellare Kometen?",a:100000,unit:"km/h",hint:"ʻOumuamua bewegte sich mit over 85.000 km/h.",emoji:"☄️"},
  {q:"How many °C is the Temperatur in the core of Neutronensternen?",a:100000000000,unit:"°C",hint:"100 billion Grad – unvorstellbar.",emoji:"⭐"},
  {q:"How many billion km is Saturns äußerster Mond Phoebe entfernt?",a:12.9,unit:"Mio. km",hint:"12,9 million km of Saturn.",emoji:"🪐"},
  {q:"How many Grad dreht sich the Sonne per day an ihrem Äquator?",a:14,unit:"Grad",hint:"the Sonne dreht sich differenziell – Äquator schneller.",emoji:"☀️"},
  {q:"How many hours after the Urknall bildeten sich the first Atomkerne?",a:3,unit:"minutes",hint:"Big Bang Nukleosynthese dauerte 3 minutes.",emoji:"⚛️"},
  {q:"How many km/h schnell rasen Sonnenwinde at Sonnenstürmen?",a:3000000,unit:"km/h",hint:"3 million km/h at starken Sonneneruptionen.",emoji:"☀️"},
  {q:"How many billion tons Eis contains the Nordpol the Mars?",a:1600,unit:"billion tons",hint:"Genug um the Mars 11m tief in water zu hüllen.",emoji:"🔴"},
  {q:"How many °C kalt is Triton (Neptunmond)?",a:-235,unit:"°C",hint:"a the coldest Körper in the solar system.",emoji:"❄️"},
  {q:"How many km is the Durchmesser of Pluto?",a:2377,unit:"km",hint:"Kleiner as Russland.",emoji:"🌑"},
  {q:"How many hours takes Licht of Alpha Centauri to the Erde?",a:38264,unit:"hours",hint:"4,37 light-years × 8760 hours/Jahr.",emoji:"⭐"},
  {q:"How many km/h rotiert the Oberfläche the Sonne at the Äquator?",a:7000,unit:"km/h",hint:"~2 km/s Rotationsgeschwindigkeit.",emoji:"☀️"},
  {q:"How many billion tons does a typischer Asteroid in the Asteroidengürtel have?",a:1,unit:"million tons",hint:"the meisten Asteroiden are sehr klein.",emoji:"☄️"},
  {q:"How many °C kalt is es in Merkurs Polkratern?",a:-180,unit:"°C",hint:"Ewiges Eis in dauerhaft beschattetem Gebiet.",emoji:"☿"}
];
