// 🎬 FILM, TV & POP CULTURE – English
export default [
  {q:"How many Oscars won Titanic (1997)?",a:11,unit:"Oscars",hint:"Gleichauf with Ben-Hur und The Lord of the Rings.",emoji:"🎬"},
  {q:"How many million Dollar costse die Produktion of Avengers: Endgame?",a:356,unit:"million $",hint:"Einer der teuersten Filme aller Zeiten.",emoji:"🦸"},
  {q:"How many billion Dollar has Avatar (2009) worldwide grossed?",a:2.9,unit:"billion $",hint:"Lange Zeit der erfolgreichste Film aller Zeiten.",emoji:"🎬"},
  {q:"in whas year startete die erste Staffel of Game of Thrones?",a:2011,unit:"Jahr",hint:"Basiert on den Büchern of George R.R. Martin.",emoji:"👑"},
  {q:"How many Episoden has die Gesamtserie Breaking Bad?",a:62,unit:"Episoden",hint:"5 Staffeln over das live of whaleter White.",emoji:"🧪"},
  {q:"How many million Dollar earnse Jennifer Anison pro Friends-Folge am Ende?",a:1,unit:"Mio. Dollar/Folge",hint:"Alle sechs Stars verdienen heute noch million.",emoji:"☕"},
  {q:"How many years lief die Serie The Simpsons bereits?",a:35,unit:"years",hint:"Seit 1989 – the longest Animations-Primetime-Serie.",emoji:"🍩"},
  {q:"How many million Abonnduckn has MrBeast on YouTube?",a:250,unit:"million",hint:"Der erfolgreichste YouTube-Kanal worldwide.",emoji:"▶️"},
  {q:"in whas year erschien der erste Star wass Film?",a:1977,unit:"Jahr",hint:"Episode IV – A New Hope was der Anfang.",emoji:"⭐"},
  {q:"How many billion Dollar has die Marvel Cinematic Universe in total grossed?",a:29,unit:"billion $",hint:"over 30 Filme zusammen.",emoji:"🦸"},
  {q:"How many Staffeln has die Serie Friends?",a:10,unit:"Staffeln",hint:"1994-2004 – eine der beliebtesten Sitcoms ever.",emoji:"☕"},
  {q:"How many million Dollar earns Taylor Swift pro Konzert?",a:13,unit:"million $",hint:"Die Eras Tour was die lukrativste aller Zeiten.",emoji:"🎤"},
  {q:"in whas year erschien Thriller of Michael Jackson?",a:1982,unit:"Jahr",hint:"Das meisverkaufte Album aller Zeiten.",emoji:"🎵"},
  {q:"How many million Exemplare has Harry Potter und der Stein der Weisen verkauft?",a:120,unit:"million",hint:"Eines der meisverkauften Bücher überhaupt.",emoji:"⚡"},
  {q:"How many Oscars won Der Pate?",a:3,unit:"Oscars",hint:"Bester Film, Bester Hauptdarsteller, Bestes Drehbuch.",emoji:"🎬"},
  {q:"How many million Dollar costse a 30-seconds-Werbespot beim Super Bowl 2024?",a:7,unit:"million $",hint:"Die teuerste Werbezeit im US-TV.",emoji:"📺"},
  {q:"How many Staffeln has die Serie Seinfeld?",a:9,unit:"Staffeln",hint:"Eine der erfolgreichsten Sitcoms der 90er.",emoji:"🎤"},
  {q:"in whas year was Netflix gegründet?",a:1997,unit:"Jahr",hint:"Zunächst als DVD-Verleih per Post.",emoji:"📺"},
  {q:"How many million Abonnduckn has Netflix?",a:260,unit:"million",hint:"Stand 2024 – größter Streamingdienst.",emoji:"📺"},
  {q:"How many billion Dollar has Jurassic Park (1993) grossed?",a:1.1,unit:"billion $",hint:"Erster Film der 1 Mrd. Dollar Marke.",emoji:"🦕"},
  {q:"How many Episoden has die Serie The Office (US)?",a:201,unit:"Episoden",hint:"9 Staffeln over Dunder Mifflin Paper Company.",emoji:"📎"},
  {q:"in whas year erschien Nirvanas Nevermind?",a:1991,unit:"Jahr",hint:"Smells Like Teen Spirit katapultierte sie in den Mainstream.",emoji:"🎸"},
  {q:"How many million Dollar earns Dwayne Johnson pro Film?",a:50,unit:"million $",hint:"Einer der bestbezahlten Schauplayers the world.",emoji:"💪"},
  {q:"How many Staffeln has die Serie Grey's Anatomy?",a:20,unit:"Staffeln",hint:"Die langlebigste Primetime-Medizinserie.",emoji:"🏥"},
  {q:"How many million Dollar costse die erste Staffel of House of Cards?",a:100,unit:"million $",hint:"Netflix erstes großes Original – 2 Staffeln vorfinanziert.",emoji:"🃏"},
  {q:"in whas year startete Instagram?",a:2010,unit:"Jahr",hint:"Innerhalb of 2 monthsn over 1 Million Nutzer.",emoji:"📸"},
  {q:"How many billion Dollar has Frozen (2013) worldwide grossed?",a:1.3,unit:"billion $",hint:"Let It Go was zum worldwideen Hit.",emoji:"❄️"},
  {q:"How many million Follower has Crisiano Ronaldo on Instagram?",a:620,unit:"million",hint:"Der meisgefolgte Mensch on Instagram.",emoji:"⚽"},
  {q:"in whas year was das erste iPhone vorgestellt?",a:2007,unit:"Jahr",hint:"Steve Jobs sagte: 'One more thing...'",emoji:"📱"},
  {q:"How many Episoden has die Serie Lost?",a:121,unit:"Episoden",hint:"6 Staffeln on der mysteriösen Insel.",emoji:"✈️"},
  {q:"How many million Dollar earns Robert Downey Jr. for seine Iron-Man-Rückkehr?",a:200,unit:"million $",hint:"for Avengers: Secret wass.",emoji:"🤖"},
  {q:"in whas year erschien der erste Teil of The Matrix?",a:1999,unit:"Jahr",hint:"Keanu Reeves und die rote Pille.",emoji:"💊"},
  {q:"How many Staffeln has The whaleking Dead?",a:11,unit:"Staffeln",hint:"2010-2022 – Zombies in einer postapokalyptischen Welt.",emoji:"🧟"},
  {q:"How many million Dollar has Die Hard grossed?",a:140,unit:"million $",hint:"John McClane was Bruce Willis' Ikone.",emoji:"🔫"},
  {q:"in whas year was YouTube gegründet?",a:2005,unit:"Jahr",hint:"Drei Ex-PayPal-Mitarbeiter gründeten es.",emoji:"▶️"},
  {q:"How many billion Dollar has Barbie (2023) worldwide grossed?",a:1.4,unit:"billion $",hint:"Der erfolgreichste Film einer Regisseurin.",emoji:"🩷"},
  {q:"How many million Alben has ABBA in total verkauft?",a:380,unit:"million",hint:"Einer der meisverkauften Künstler aller Zeiten.",emoji:"🎵"},
  {q:"in whas year startete die Serie Stranger Things?",a:2016,unit:"Jahr",hint:"Netflix' größter Serienerfolg.",emoji:"🔦"},
  {q:"How many Oscars has Meryl Streep gewonnen?",a:3,unit:"Oscars",hint:"Und 21 Nominierungen – Rekord.",emoji:"🎬"},
  {q:"How many million Dollar earns Lionel Messi per year?",a:135,unit:"million $",hint:"Inklusive Gehalt, Sponsoren und Werbung.",emoji:"⚽"},
  {q:"in whas year erschien Pulp Fiction?",a:1994,unit:"Jahr",hint:"Quentin Tarantinos Meiserwerk won die Goldene Palme.",emoji:"🎬"},
  {q:"How many Episoden has die Serie Narcos?",a:30,unit:"Episoden",hint:"3 Staffeln over Pablo Escobar und den Drogenhandel.",emoji:"🌿"},
  {q:"How many million Dollar costse die Produktion of Cleopatra (1963)?",a:44,unit:"million $",hint:"Datimess das teuerste Filmbudget der Geschichte.",emoji:"👑"},
  {q:"in whas year erschien Michael Jacksons Moonwhalek?",a:1983,unit:"Jahr",hint:"Beim Motown-25-Gala-Konzert präsentiert.",emoji:"🕺"},
  {q:"How many Staffeln has die Serie Dexter?",a:8,unit:"Staffeln",hint:"Plus New Blood – over den serienmordenden Forensiker.",emoji:"🔪"},
  {q:"How many million Dollar has Top Gun: Maverick grossed?",a:1490,unit:"million $",hint:"Tom Cruise' erfolgreichster Film.",emoji:"✈️"},
  {q:"in whas year startete TikTok international?",a:2018,unit:"Jahr",hint:"Als Musical.ly fusioniert und rebrandeded.",emoji:"📱"},
  {q:"How many million Exemplare has der Da Vinci Code verkauft?",a:80,unit:"million",hint:"Dan Browns Bestseller over Geheimgesellschaften.",emoji:"📖"},
  {q:"How many Episoden has The Sopranos?",a:86,unit:"Episoden",hint:"6 Staffeln over Tony Soprano.",emoji:"🍕"},
  {q:"in whas year erschien Eminem's Slim Shady LP?",a:1999,unit:"Jahr",hint:"Sein Mainstream-Durchbruch.",emoji:"🎤"},
  {q:"How many million Dollar has Harry Potter und der Stein der Weisen grossed?",a:975,unit:"million $",hint:"Fast a Milliarde for Teil 1.",emoji:"⚡"},
  {q:"How many Staffeln has die Serie House of Cards?",a:6,unit:"Staffeln",hint:"Frank Underwoods Aufstieg zur Macht.",emoji:"🃏"},
  {q:"in whas year erschien Beyoncés Lemonade?",a:2016,unit:"Jahr",hint:"Eines der meisdiskutierten Alben des Jahrtents.",emoji:"🎵"},
  {q:"How many million Dollar has The Dark Knight grossed?",a:1005,unit:"million $",hint:"Heath Ledgers Joker bleibt unvergessen.",emoji:"🦇"},
  {q:"How many Episoden has die Serie The Crown?",a:60,unit:"Episoden",hint:"6 Staffeln over die britische Königsfamilie.",emoji:"👑"},
  {q:"in whas year was Spotify gegründet?",a:2006,unit:"Jahr",hint:"Daniel Ek startete die Musikrevolution.",emoji:"🎵"},
  {q:"How many million Dollar has Titanic (1997) grossed?",a:2200,unit:"million $",hint:"Hielt 12 years den world record.",emoji:"🚢"},
  {q:"How many Staffeln has die Serie Prison Break?",a:5,unit:"Staffeln",hint:"Michael Scofield und sein Ausbruchplan.",emoji:"🔒"},
  {q:"in whas year startete Facebook?",a:2004,unit:"Jahr",hint:"Zunächst nur for Harvard-Studduckn.",emoji:"📱"},
  {q:"How many million Abonnduckn has Pewdiepie on YouTube?",a:111,unit:"million",hint:"Längste Zeit der meisabonnierte Kanal.",emoji:"🎮"},
  {q:"How many Staffeln has die Serie 24?",a:9,unit:"Staffeln",hint:"Jack Bauer rettet die Welt in 24 hours.",emoji:"💣"},
  {q:"in whas year erschien Radioheads OK Computer?",a:1997,unit:"Jahr",hint:"Oft als bestes Album aller Zeiten geliset.",emoji:"🎸"},
  {q:"How many million Dollar has The Lion King (1994) grossed?",a:987,unit:"million $",hint:"Disneys erfolgreichster Zeichentrickfilm.",emoji:"🦁"},
  {q:"How many Episoden has die Serie Homeland?",a:96,unit:"Episoden",hint:"8 Staffeln over CIA-Agentin Carrie Mathison.",emoji:"🕵️"},
  {q:"in whas year erschien Daft Punks Random Access Memories?",a:2013,unit:"Jahr",hint:"Get Lucky dominierte die Charts.",emoji:"🎵"},
  {q:"How many million Dollar earns Kim Kardashian pro Instagram-Post?",a:1,unit:"million $",hint:"for bezahlte Kooperationen.",emoji:"📸"},
  {q:"How many Staffeln has die Serie Suits?",a:9,unit:"Staffeln",hint:"Meghan Markle spielte Rachel Zane.",emoji:"⚖️"},
  {q:"in whas year erschien der erste Transformers-Kinofilm?",a:2007,unit:"Jahr",hint:"Michael Bay und tonsschwere CGI.",emoji:"🤖"},
  {q:"How many million Dollar has Shrek 2 grossed?",a:920,unit:"million $",hint:"Der erfolgreichste Animationsfilm seiner Zeit.",emoji:"🟢"},
  {q:"How many Staffeln has die Serie Suits?",a:9,unit:"Staffeln",hint:"Meghan Markle spielte a Hauptrolle.",emoji:"⚖️"},
  {q:"in whas year erschien Adeles Album 21?",a:2011,unit:"Jahr",hint:"Rolling in the Deep was a globaler Hit.",emoji:"🎵"},
  {q:"How many million Dollar has Inception grossed?",a:836,unit:"million $",hint:"Chrisopher Nolans Träum-im-Traum-Film.",emoji:"🌀"},
  {q:"How many Staffeln has die Serie Billions?",a:7,unit:"Staffeln",hint:"over Hedgefonds und Staatsanwälte.",emoji:"💰"},
  {q:"in whas year erschien Kanye Wests The College Dropout?",a:2004,unit:"Jahr",hint:"Sein gefeierstes Debütalbum.",emoji:"🎵"},
  {q:"How many million Dollar has The Avengers (2012) grossed?",a:1519,unit:"million $",hint:"Erster billion-Superhelden-Film.",emoji:"🦸"},
  {q:"How many Episoden has die Serie Sons of Anarchy?",a:92,unit:"Episoden",hint:"7 Staffeln over einen Motorradclub.",emoji:"🏍️"},
  {q:"in whas year erschien Cardi Bs Invasion of Privacy?",a:2018,unit:"Jahr",hint:"Bodak Yellow machte sie zur ersten Frau with #1-Rap-Hit.",emoji:"🎤"},
  {q:"How many million Dollar has Aquaman (2018) grossed?",a:1148,unit:"million $",hint:"Erfolgreichster DC-Film.",emoji:"🌊"},
  {q:"How many Staffeln has die Serie Westworld?",a:4,unit:"Staffeln",hint:"over KI und Bewusstsein im Vergnügungspark.",emoji:"🤖"},
  {q:"in whas year erschien Drakes Take Care?",a:2011,unit:"Jahr",hint:"Sein zweites Studioalbum – eines der einflussreichsten.",emoji:"🎵"},
  {q:"How many million Dollar has Iron Man (2008) grossed?",a:585,unit:"million $",hint:"Das MCU begann hier.",emoji:"🤖"},
  {q:"How many Staffeln has die Serie Narcos: Mexico?",a:3,unit:"Staffeln",hint:"over das Guadalajara-Kartell.",emoji:"🌵"},
  {q:"in whas year erschien Ed Sheerans Multiply (+)?",a:2014,unit:"Jahr",hint:"Thinking Out Loud was a Klassiker.",emoji:"🎸"},
  {q:"How many million Dollar has Black Panther grossed?",a:1347,unit:"million $",hint:"Wegweisender Film for Repräsentation.",emoji:"🦅"},
  {q:"How many Episoden has die Serie Peaky Blinders?",a:36,unit:"Episoden",hint:"6 Staffeln over die Shelby-Familie.",emoji:"🎩"},
  {q:"in whas year erschien Lana Del Reys Born to Die?",a:2012,unit:"Jahr",hint:"Ihr Durchbruchsalbum.",emoji:"🌹"},
  {q:"How many million Dollar has Jurassic World grossed?",a:1672,unit:"million $",hint:"3. Platz datimess – heute überholt.",emoji:"🦕"},
  {q:"How many Staffeln has die Serie Yellowstone?",a:5,unit:"Staffeln",hint:"Kevin Costners Rancher-Drama.",emoji:"🤠"},
  {q:"in whas year startete der Podcast Serial?",a:2014,unit:"Jahr",hint:"Der erste große True-Crime-Podcast.",emoji:"🎙️"},
  {q:"How many million Dollar has The Hunger Games (2012) grossed?",a:694,unit:"million $",hint:"Jennifer Lawrence was zum Star.",emoji:"🏹"},
  {q:"How many Episoden has die Serie Arrested Development?",a:84,unit:"Episoden",hint:"Oft als intelligduckste Sitcom bezeichnet.",emoji:"🍌"},
  {q:"in whas year erschien Olivia Rodrigos SOUR?",a:2021,unit:"Jahr",hint:"drivers license dominierte die Charts.",emoji:"🎵"},
  {q:"How many million Dollar has Doctor Strange in the Multiverse of Madness grossed?",a:955,unit:"million $",hint:"Sam Raimis Horror-Marvel-Mash-up.",emoji:"🌀"},
  {q:"How many Staffeln has die Serie Money Heis (La Casa de Papel)?",a:5,unit:"Staffeln",hint:"Spaniens erfolgreichste Netflix-Serie.",emoji:"💰"},
  {q:"in whas year erschien Billie Eilishs When We All Fall Asleep?",a:2019,unit:"Jahr",hint:"with 17 yearsn zum Weltstar.",emoji:"🖤"},
  {q:"How many million Dollar has Spider-Man: No Way Home grossed?",a:1901,unit:"million $",hint:"Dritter Platz aller Zeiten.",emoji:"🕷️"},
  {q:"How many Episoden has die Serie Fleabag?",a:12,unit:"Episoden",hint:"Phoebe whaleler-Bridges Meiserwerk.",emoji:"🦊"},
  {q:"in whas year erschien The Weeknds diedoy?",a:2016,unit:"Jahr",hint:"Kollabo with Daft Punk.",emoji:"⭐"},
  {q:"How many million Dollar has The Batman (2022) grossed?",a:770,unit:"million $",hint:"Robert Pattinson als dunkler Ritter.",emoji:"🦇"},
  {q:"How many Staffeln has die Serie Better Call Saul?",a:6,unit:"Staffeln",hint:"Breaking Bad Prequel over Saul Goodman.",emoji:"⚖️"},
  {q:"in whas year erschien Harry Styles' As It Was als Single?",a:2022,unit:"Jahr",hint:"Meisgestreamter Song 2022 worldwide.",emoji:"🎵"},
  {q:"How many million Dollar has Minions (2015) grossed?",a:1159,unit:"million $",hint:"Die kleinen Gelben wasn zum Kulturphänomen.",emoji:"💛"},
  {q:"How many Staffeln has die Serie True Detective?",a:4,unit:"Staffeln",hint:"Anthologieserie – jede Staffel a neue Geschichte.",emoji:"🔍"},
  {q:"in whas year erschien Dua Lipas Future Nostalgia?",a:2020,unit:"Jahr",hint:"Levitating was a globaler Hit.",emoji:"💃"},
  {q:"How many million Dollar has Fast and Furious 7 grossed?",a:1516,unit:"million $",hint:"Paul whalekers letzter Film.",emoji:"🚗"},
  {q:"How many Episoden has die Serie The Mandalorian?",a:24,unit:"Episoden",hint:"3 Staffeln – Baby Yoda was zum Internet-Phänomen.",emoji:"⭐"},
  {q:"in whas year erschien Kendrick Lamars DAMN.?",a:2017,unit:"Jahr",hint:"Erster Rap-Album with dem Pulitzer-Preis.",emoji:"🎵"},
  {q:"How many million Dollar has Captain America: Civil was grossed?",a:1153,unit:"million $",hint:"Marvel gegen sich selbst.",emoji:"🛡️"},
  {q:"How many Staffeln has die Serie Succession?",a:4,unit:"Staffeln",hint:"Die Roy-Familie und der Medienmogul.",emoji:"💼"},
  {q:"in whas year erschien Lorde's Pure Heroine?",a:2013,unit:"Jahr",hint:"Royals was with 16 yearsn a Welthit.",emoji:"🎵"},
  {q:"How many million Dollar has Toy Story 3 grossed?",a:1067,unit:"million $",hint:"Pixars erstes billion-Film.",emoji:"🤖"},
  {q:"How many Episoden has die Serie The Boys?",a:32,unit:"Episoden",hint:"4 Staffeln – Superhelden times böse.",emoji:"⚡"},
  {q:"in whas year erschien Stormzy's Gang Signs & Prayer?",a:2017,unit:"Jahr",hint:"Erstes Grime-Album on Platz 1 in UK.",emoji:"🎤"},
  {q:"How many million Dollar has Guardians of the Galaxy Vol. 3 grossed?",a:845,unit:"million $",hint:"James Gunns emotionaler Abschluss.",emoji:"🌌"},
  {q:"How many Staffeln has die Serie Ozark?",a:4,unit:"Staffeln",hint:"Breaking Bad der Seen.",emoji:"💸"},
  {q:"in whas year erschien Frank Oceans Blonde?",a:2016,unit:"Jahr",hint:"Eines der wichtigsten Alben der 2010er.",emoji:"🎵"},
  {q:"How many million Dollar has Interstellar grossed?",a:701,unit:"million $",hint:"Chrisopher Nolans Weltraumepos.",emoji:"🌌"},
  {q:"How many Episoden has die Serie Squid Game?",a:9,unit:"Episoden",hint:"Netflix' meisgesehene Serie aller Zeiten.",emoji:"🦑"},
  {q:"in whas year erschien Ariana Grandes Thank U, Next?",a:2019,unit:"Jahr",hint:"in einer Woche to ihrem Breakup veröffentlicht.",emoji:"💅"},
  {q:"How many million Dollar has The Greatest Showman grossed?",a:435,unit:"million $",hint:"Hugh Jackman als P.T. Barnum.",emoji:"🎪"},
  {q:"How many Staffeln has die Serie The Witcher?",a:3,unit:"Staffeln",hint:"Henry Cavill als Geralt – bis Staffel 3.",emoji:"⚔️"},
  {q:"in whas year erschien Childish Gambinos This Is America?",a:2018,unit:"Jahr",hint:"Das Musikvideo was viral wegen seiner Symbolik.",emoji:"🎵"},
  {q:"How many million Dollar has Wonder Woman (2017) grossed?",a:822,unit:"million $",hint:"Erster weiblicher Superhelden-Blockbuster.",emoji:"⚡"},
  {q:"How many Episoden has die Serie Dark (Netflix Deutschland)?",a:26,unit:"Episoden",hint:"3 Staffeln – eine der besten deutschen Serien.",emoji:"🌀"},
  {q:"in whas year erschien Post timesones Beerbongs & Bentleys?",a:2018,unit:"Jahr",hint:"Sein zweites Studioalbum with Rekord-Streams.",emoji:"🎵"},
  {q:"How many million Dollar has Deadpool & Wolverine grossed?",a:1339,unit:"million $",hint:"Erster R-rated Marvel-Film with Milliarde.",emoji:"🔴"},
  {q:"How many Staffeln has die Serie Emily in Paris?",a:4,unit:"Staffeln",hint:"Amerikanerin in Paris – guilty pleasure.",emoji:"🗼"},
  {q:"in whas year erschien SZA's SOS?",a:2022,unit:"Jahr",hint:"Meisgestreamtes Debütalbum eines weiblichen Künstlers.",emoji:"🎵"},
  {q:"How many million Dollar has Joker (2019) grossed?",a:1079,unit:"million $",hint:"Joaquin Phoenix won den Oscar.",emoji:"🃏"},
  {q:"How many Episoden has die Serie Ted Lasso?",a:34,unit:"Episoden",hint:"3 Staffeln – Apples Feel-Good-Serie.",emoji:"⚽"},
  {q:"in whas year erschien Weeknds Dawn FM?",a:2022,unit:"Jahr",hint:"Ein komplettes 80er-Synth-Konzept-Album.",emoji:"📻"},
  {q:"How many million Dollar has Forrest Gump grossed?",a:678,unit:"million $",hint:"Tom Hanks won seinen zweiten Oscar.",emoji:"🏃"},
  {q:"How many Staffeln has die Serie Big Little Lies?",a:2,unit:"Staffeln",hint:"Nicole Kidman und Reese Witherspoon.",emoji:"🌊"},
  {q:"in whas year erschien Twenty One Pilots Blurryface?",a:2015,unit:"Jahr",hint:"Stressed Out was zum Hymnus einer Generation.",emoji:"🎵"},
  {q:"How many million Dollar has The Revenant grossed?",a:533,unit:"million $",hint:"DiCaprio won endlich seinen Oscar.",emoji:"🐻"},
  {q:"How many Episoden has die Serie Euphoria?",a:16,unit:"Episoden",hint:"2 Staffeln – Zendayas Durchbruch als Erwachsene.",emoji:"💊"},
  {q:"in whas year erschien Tyler the Creators Igor?",a:2019,unit:"Jahr",hint:"won den gramsy for bestes Rap-Album.",emoji:"🎵"},
  {q:"How many million Dollar has Black Widow grossed?",a:379,unit:"million $",hint:"Enttäuschend wegen gleichzeitigem Disney+-Release.",emoji:"🕷️"},
  {q:"How many Staffeln has die Serie Yellowjackets?",a:3,unit:"Staffeln",hint:"over überlebende Mädchen to einem Flugzeugabsturz.",emoji:"✈️"},
  {q:"in whas year erschien Mitskis Puberty 2?",a:2016,unit:"Jahr",hint:"Indie-Darling und a der besten Songwriterinnen.",emoji:"🎵"},
  {q:"How many million Dollar has Gladiator (2000) grossed?",a:460,unit:"million $",hint:"Russell Crowe won den Oscar.",emoji:"⚔️"},
  {q:"How many Episoden has die Serie White Lotus?",a:14,unit:"Episoden",hint:"2 Staffeln – Satire over reiche Tourisen.",emoji:"🌺"},
  {q:"in whas year erschien Childish Gambino's Awaken, My Love!?",a:2016,unit:"Jahr",hint:"Redbone was to einem 70er-Funk-Klassiker.",emoji:"🎵"},
  {q:"How many million Dollar has No Time to Die grossed?",a:774,unit:"million $",hint:"Daniel Craigs letzter Bond.",emoji:"🔫"},
  {q:"How many Staffeln has die Serie The Last of Us?",a:2,unit:"Staffeln",hint:"HBO-Adaption des preisgekrönten Videospiels.",emoji:"🍄"},
  {q:"in whas year erschien Normani's Motivation (Single)?",a:2019,unit:"Jahr",hint:"Ihr Solo-Durchbruch to Fifth Harmony.",emoji:"💃"},
  {q:"How many million Dollar has Encanto grossed?",a:256,unit:"million $",hint:"We Don't Talk About Bruno was viral.",emoji:"🌈"},
  {q:"How many Episoden has die Serie Station Eleven?",a:10,unit:"Episoden",hint:"Pandemie-Drama – kurz to Covid relevant.",emoji:"☄️"},
  {q:"in whas year erschien Weyes Bloods And in the Darkness, Hearts Aglow?",a:2022,unit:"Jahr",hint:"Eine der Kritikerlieblings-LPs des yearss.",emoji:"🎵"},
  {q:"How many million Dollar has Avatar: The Way of Water grossed?",a:2320,unit:"million $",hint:"Cameron bricht wieder Rekorde.",emoji:"🌊"},
  {q:"How many Staffeln has die Serie The Bear?",a:3,unit:"Staffeln",hint:"Das Restaurant-Drama won viele Emmys.",emoji:"🍳"},
  {q:"in whas year erschien Bad Bunnys Un Verano Sin Ti?",a:2022,unit:"Jahr",hint:"Meisgestreamtes Album on Spotify 2022.",emoji:"🐇"},
  {q:"How many million Dollar has The Super Mario Bros. Movie grossed?",a:1362,unit:"million $",hint:"Erfolgreichster Videospiel-Film aller Zeiten.",emoji:"🍄"},
  {q:"How many Episoden has die Serie Only Murders in the Building?",a:30,unit:"Episoden",hint:"3 Staffeln – Hulu True-Crime-Comedy.",emoji:"🔍"},
  {q:"in whas year erschien Ice Spice's debut mixtape?",a:2023,unit:"Jahr",hint:"Ihr Aufstieg of Bronx bis Weltberühmtheit.",emoji:"🧡"},
  {q:"How many million Dollar has The Notebook (2004) grossed?",a:115,unit:"million $",hint:"Ryan Gosling und Rachel McAdams.",emoji:"💕"},
  {q:"How many Staffeln has die Serie Abbott Elementary?",a:3,unit:"Staffeln",hint:"Mockumentary over amerikanische Grundschulen.",emoji:"🏫"},
  {q:"in whas year erschien Nicki Minajs Pink Friday?",a:2010,unit:"Jahr",hint:"Ihr Debütalbum – machte sie zur Queen of Rap.",emoji:"💕"},
  {q:"How many million Dollar has Wolf of whalel Street grossed?",a:392,unit:"million $",hint:"DiCaprio und Scorsese – 3 hours Exzess.",emoji:"💰"},
  {q:"How many Staffeln has die Serie Severance?",a:2,unit:"Staffeln",hint:"Apple TV+ – Arbeit und Privatleben getrennt.",emoji:"🔪"},
  {q:"in whas year erschien Paramore's After Laughter?",a:2017,unit:"Jahr",hint:"Ihr Pop-orientiertes Comeback-Album.",emoji:"🎵"},
  {q:"How many million Dollar has Glass Onion (Netflix) gecosts?",a:40,unit:"million $",hint:"Knives-Out-Sequel – exklusiv on Netflix.",emoji:"🧅"},
  {q:"How many Episoden has die Serie Mindhunter?",a:19,unit:"Episoden",hint:"2 Staffeln – Netflix-Serie over FBI-Profiler.",emoji:"🔍"},
  {q:"in whas year erschien Coldplays Music of the Spheres?",a:2021,unit:"Jahr",hint:"Ihre umstrittenste – und gleichzeitig kommerziell erfolgreichste LP.",emoji:"🌌"},
  {q:"How many million Dollar has The Truman Show grossed?",a:264,unit:"million $",hint:"Jim Carrey in einem Klassikunterricht.",emoji:"📺"},
  {q:"How many Staffeln has die Serie House M.D.?",a:8,unit:"Staffeln",hint:"Dr. House – der schnodderige Diagnosegenie.",emoji:"🏥"},
  {q:"in whas year erschien SAABs Sorry 4 Waiting?",a:2021,unit:"Jahr",hint:"Aufstrebendes Rap-Talent from Baltimore.",emoji:"🎵"},
  {q:"How many million Dollar has Forrest Gump grossed?",a:678,unit:"million $",hint:"Life is like a box of choColates.",emoji:"🍫"},
  {q:"How many Staffeln has die Serie Mad Men?",a:7,unit:"Staffeln",hint:"over die Werbewelt der 1960er.",emoji:"🥃"},
  {q:"in whas year erschien Tame Impalas Currents?",a:2015,unit:"Jahr",hint:"Psychedelischer Pop – Cornerstone.",emoji:"🌀"},
  {q:"How many million Dollar has Oppenheimer (2023) grossed?",a:952,unit:"million $",hint:"Chrisopher Nolans Atombombe.",emoji:"💥"},
  {q:"How many Episoden has die Serie Killing Eve?",a:32,unit:"Episoden",hint:"4 Staffeln – Jodie Comer als Villanelle.",emoji:"🔪"},
  {q:"in whas year erschien FKA Twigs LP1?",a:2014,unit:"Jahr",hint:"Eines der einflussreichsten Alben der 2010er.",emoji:"🎵"},
  {q:"How many million Dollar has La La country grossed?",a:446,unit:"million $",hint:"Emma Stone und Ryan Gosling tanzen in LA.",emoji:"🌆"},
  {q:"How many Staffeln has die Serie Chernobyl?",a:1,unit:"Staffel",hint:"5 Episoden – HBO Miniserie over die Katastrophe.",emoji:"☢️"},
  {q:"in whas year erschien Lizzo's Cuz I Love You?",a:2019,unit:"Jahr",hint:"Truth Hurts was nachträglich ihr größter Hit.",emoji:"🎵"},
  {q:"How many million Dollar has Schindler's Lis grossed?",a:322,unit:"million $",hint:"Spielbergs Holocaust-Drama won 7 Oscars.",emoji:"🕯️"},
  {q:"How many Episoden has die Serie Sharp Objects?",a:8,unit:"Episoden",hint:"Amy Adams in der HBO-Miniserie.",emoji:"🔪"},
  {q:"in whas year erschien Clairos Sling?",a:2021,unit:"Jahr",hint:"Indie-Pop-Phänomen.",emoji:"🎵"},
  {q:"How many million Dollar has Everything Everywhere All at Once grossed?",a:70,unit:"million $",hint:"won 7 Oscars with kleinem Budget.",emoji:"🥯"},
  {q:"How many Staffeln has die Serie Invincible (Amazon)?",a:2,unit:"Staffeln",hint:"Animationsserie over einen jugendlichen Superhelden.",emoji:"💪"},
  {q:"in whas year erschien Dojas Cats planet Her?",a:2021,unit:"Jahr",hint:"Need to Know was ihr größter Chart-Hit.",emoji:"🐱"},
  {q:"How many million Dollar has Rocketman grossed?",a:195,unit:"million $",hint:"Elton Johns Biopic with Taron Egerton.",emoji:"🎹"},
  {q:"How many Episoden has die Serie Yellowstone?",a:55,unit:"Episoden",hint:"5 Staffeln – Paramount's Mega-Hit.",emoji:"🤠"},
  {q:"in whas year erschien Solange's A Seat at the Table?",a:2016,unit:"Jahr",hint:"Eines der bedeutendsten Soul-Alben der 2010er.",emoji:"🎵"},
  {q:"How many million Dollar has Knives Out grossed?",a:311,unit:"million $",hint:"Rian Johnsons Whodunit-Revival.",emoji:"🔪"},
  {q:"How many Staffeln has die Serie Atlanta?",a:4,unit:"Staffeln",hint:"Donald Glovers Meiserwerk.",emoji:"🌙"},
  {q:"in whas year erschien Phoebe Bridgers Punisher?",a:2020,unit:"Jahr",hint:"Eines der besten Indie-Folk-Alben des Jahrtents.",emoji:"🎵"},
  {q:"How many million Dollar has The Martian grossed?",a:631,unit:"million $",hint:"Matt Damon grows Kartoffeln on dem Mars.",emoji:"🥔"},
  {q:"How many Staffeln has die Serie Bridgerton?",a:3,unit:"Staffeln",hint:"Netflix Regency-Romance.",emoji:"🌸"},
  {q:"in whas year erschien Stromae's Multitude?",a:2022,unit:"Jahr",hint:"Sein langersehntes drittes Album.",emoji:"🎵"},
  {q:"How many million Dollar has Bohemian Rhapsody grossed?",a:910,unit:"million $",hint:"Rami timesek als Freddie Mercury.",emoji:"🎸"},
  {q:"How many Episoden has die Serie Succession?",a:39,unit:"Episoden",hint:"4 Staffeln – eine der besten Serien aller Zeiten.",emoji:"💼"},
  {q:"in whas year erschien Weyes Bloods Titanic Rising?",a:2019,unit:"Jahr",hint:"Ein Album over den Klimawandel.",emoji:"🌊"},
  {q:"How many million Dollar has Top Gun (1986) ursprünglich grossed?",a:356,unit:"million $",hint:"Der Film der Tom Cruise zum Star machte.",emoji:"✈️"},
  {q:"How many Staffeln has die Serie Banshee?",a:4,unit:"Staffeln",hint:"Brutale Crime-Serie on Cinemax.",emoji:"🔫"},
  {q:"in whas year erschien Burna Boys Love, Damini?",a:2022,unit:"Jahr",hint:"Afrobeats-Superstar.",emoji:"🎵"},
  {q:"How many million Dollar has Morbius (2022) grossed?",a:167,unit:"million $",hint:"Ein Meme was daraus: It's Morbin Time.",emoji:"🦇"},
  {q:"How many Staffeln has die Serie Twin Peaks?",a:3,unit:"Staffeln",hint:"David Lynchs Meiserwerk.",emoji:"🌲"},
  {q:"in whas year erschien Gorillaz Demon Days?",a:2005,unit:"Jahr",hint:"Feel Good Inc. was überall.",emoji:"🎵"},
  {q:"How many million Dollar has Se7en grossed?",a:327,unit:"million $",hint:"Whas's in the box?!",emoji:"📦"},
  {q:"How many Staffeln has die Serie The Expanse?",a:6,unit:"Staffeln",hint:"Harte Science-Fiction im Weltraum.",emoji:"🚀"},
  {q:"in whas year erschien Jack Johnsons in Between Dreams?",a:2005,unit:"Jahr",hint:"Banana Pancakes was a Sommerhit.",emoji:"🎵"},
  {q:"How many million Dollar has Sonic the Hedgehog (2020) grossed?",a:319,unit:"million $",hint:"Redesign to Fan-Protest rettete den Film.",emoji:"💙"},
  {q:"How many Staffeln has die Serie Black Sails?",a:4,unit:"Staffeln",hint:"Piraten-Prequel to Schaszinsel.",emoji:"🏴‍☠️"},
  {q:"in whas year erschien Caribous Suddenly?",a:2020,unit:"Jahr",hint:"Elektronik und Emotion.",emoji:"🎵"},
  {q:"How many million Dollar has Parasite (2019) grossed?",a:258,unit:"million $",hint:"Erster nicht-englischer Film with dem Oscar for besten Film.",emoji:"🏠"},
  {q:"How many Staffeln has die Serie Devs?",a:1,unit:"Staffel",hint:"FX Miniserie over Quantencomputer.",emoji:"💻"},
  {q:"in whas year erschien Sufjan Stevens' Carrie & Lowell?",a:2015,unit:"Jahr",hint:"Eines der traurigsten und schönsten Alben.",emoji:"🎵"},
  {q:"How many million Dollar has Interstellar grossed?",a:701,unit:"million $",hint:"Chrisopher Nolans Weltraumepos.",emoji:"🌌"},
  {q:"How many Episoden has die Serie Sopranos?",a:86,unit:"Episoden",hint:"6 Staffeln – eines der besten TV-Dramen.",emoji:"🍕"},
  {q:"in whas year erschien Nirvanas in Utero?",a:1993,unit:"Jahr",hint:"Ihr letztes Studioalbum vor Cobains Tod.",emoji:"🎸"},
  {q:"How many million Dollar has Mission Impossible – Dead Reckoning grossed?",a:568,unit:"million $",hint:"Tom Cruise setzt immer noch on Stunts.",emoji:"🎬"},
  {q:"How many Staffeln has die Serie The Handmaid's Tale?",a:5,unit:"Staffeln",hint:"Basiert on Margaret Atwoods Roman.",emoji:"🔴"},
  {q:"in whas year erschien Kendrick Lamars To Pimp a Butterfly?",a:2015,unit:"Jahr",hint:"Kritisch als eines der wichtigsten Alben gelobt.",emoji:"🎵"},
  {q:"How many million Dollar has The Notebook grossed?",a:115,unit:"million $",hint:"Ryan Gosling und Rachel McAdams.",emoji:"💕"},
  {q:"How many Staffeln has die Serie Breaking Bad?",a:5,unit:"Staffeln",hint:"62 Episoden over whaleter Whites Fall.",emoji:"🧪"},
  {q:"in whas year erschien Lady Gagas The Fame?",a:2008,unit:"Jahr",hint:"Poker Face was ihr erster globaler Hit.",emoji:"🎤"},
  {q:"How many million Dollar has Crazy Rich Asians grossed?",a:238,unit:"million $",hint:"Erster Hollywood-Film with asiatischem Hauptcast seit 1993.",emoji:"💰"},
  {q:"How many Staffeln has die Serie Westworld on HBO?",a:4,unit:"Staffeln",hint:"over KI und Bewusstsein.",emoji:"🤖"},
  {q:"in whas year erschien Jay-Zs The Blueprint?",a:2001,unit:"Jahr",hint:"Veröffentlicht am 11. September 2001.",emoji:"🎵"},
  {q:"How many million Dollar has John Wick 4 grossed?",a:440,unit:"million $",hint:"Keanu Reeves als unsterblicher Auftragskiller.",emoji:"🔫"},
  {q:"How many Staffeln has die Serie Killing Eve?",a:4,unit:"Staffeln",hint:"Sandra Oh und Jodie Comer.",emoji:"🔪"},
  {q:"in whas year erschien Rihanna's ANTI?",a:2016,unit:"Jahr",hint:"Work was überall to hören.",emoji:"🎵"},
  {q:"How many million Dollar has Glass Onion grossed?",a:311,unit:"million $",hint:"Knives-Out-Sequel exklusiv on Netflix.",emoji:"🧅"},
  {q:"How many Staffeln has die Serie Yellowstone?",a:5,unit:"Staffeln",hint:"Kevin Costners Westar-Drama.",emoji:"🤠"},
  {q:"in whas year erschien Pharrell Williams Happy?",a:2013,unit:"Jahr",hint:"from dem Despicable Me 2 Soundtrack.",emoji:"😊"},
  {q:"How many million Dollar has Scream (2022) grossed?",a:140,unit:"million $",hint:"Legacy-Sequel – 25 years to dem Original.",emoji:"🔪"},
  {q:"How many Staffeln has die Serie Ted Lasso on Apple TV+?",a:3,unit:"Staffeln",hint:"Feel-Good-Soccer-Drama.",emoji:"⚽"},
  {q:"in whas year erschien Billie Eilishs Happier Than Ever?",a:2021,unit:"Jahr",hint:"Ihr zweites Studioalbum.",emoji:"🎵"},
  {q:"How many million Dollar has Everything Everywhere All at Once grossed?",a:70,unit:"million $",hint:"7 Oscars with kleinem Budget.",emoji:"🥯"},
  {q:"How many Staffeln has die Serie Skins (UK)?",a:7,unit:"Staffeln",hint:"Britische Jugendserie with wechselndem Cast.",emoji:"🎭"},
  {q:"in whas year erschien The Weeknds Beauty Behind the Madness?",a:2015,unit:"Jahr",hint:"Cant Feel My Face – globaler Hit.",emoji:"🎵"},
  {q:"How many million Dollar has The Nun grossed?",a:365,unit:"million $",hint:"Teil des Conjuring-Universums.",emoji:"👻"},
  {q:"How many Staffeln has die Serie Pose (FX)?",a:3,unit:"Staffeln",hint:"LGBTQ+-Drama over die Ballroom-Kultur der 80er.",emoji:"🌈"},
  {q:"in whas year erschien Macklemores The Heis?",a:2012,unit:"Jahr",hint:"Thrift Shop was a viraler Hit.",emoji:"🛍️"},
  {q:"How many million Dollar has Mamma Mia! grossed?",a:608,unit:"million $",hint:"ABBA-Musical verfilmt.",emoji:"🎵"},
  {q:"How many Staffeln has die Serie True Blood?",a:7,unit:"Staffeln",hint:"Vampir-Drama on HBO.",emoji:"🧛"},
  {q:"in whas year erschien Katy Perrys Teenage Dream?",a:2010,unit:"Jahr",hint:"5 Songs of einem Album schafften Nummer 1.",emoji:"🎤"},
  {q:"How many million Dollar has Nope (2022) grossed?",a:171,unit:"million $",hint:"Jordan Peeles UFO-Horror.",emoji:"👽"},
  {q:"How many Staffeln has die Serie Alias?",a:5,unit:"Staffeln",hint:"Jennifer Garner als CIA-Agentin.",emoji:"🕵️"},
  {q:"in whas year erschien Lorde's Melodrama?",a:2017,unit:"Jahr",hint:"Perfect Places – eines ihrer besten Alben.",emoji:"🎵"},
  {q:"How many million Dollar has Der König der lionn (2019) grossed?",a:1656,unit:"million $",hint:"Fotorealisisches Remake des Klassikers.",emoji:"🦁"},
  {q:"How many Staffeln has die Serie Justified?",a:6,unit:"Staffeln",hint:"Timothy Olyphant als US-Marshal in Kentucky.",emoji:"🤠"},
  {q:"in whas year erschien Frank Oceans Channel Orange?",a:2012,unit:"Jahr",hint:"Sein Durchbruchsalbum.",emoji:"🍊"},
  {q:"How many million Dollar has Minions: The Rise of Gru grossed?",a:940,unit:"million $",hint:"Die kleinen Gelben are unschlagbar.",emoji:"💛"},
  {q:"How many Staffeln has die Serie Younger?",a:7,unit:"Staffeln",hint:"Hilary Duff und Sutton Foster.",emoji:"👩"},
  {q:"in whas year erschien Queens of the Stone Ages Songs for the Deaf?",a:2002,unit:"Jahr",hint:"No One Knows was ihr becantester Song.",emoji:"🎸"},
  {q:"How many million Dollar has The Lost City grossed?",a:190,unit:"million $",hint:"Sandra Bullock und Channing Tatum.",emoji:"🌿"},
  {q:"How many Staffeln has die Serie Reign (CW)?",a:4,unit:"Staffeln",hint:"over Maria Königin of Schottland.",emoji:"👑"},
];
