// 🎯 FREE SAMPLER – Adults – English
export default [
  {q:"How many literss of blood does the human heart pump per day?",a:7200,unit:"literss",hint:"The heart beats ~100,000 times per day.",emoji:"❤️"},
  {q:"How fast does a sneeze travel in km/h?",a:160,unit:"km/h",hint:"Particles fly up to 8 meterss.",emoji:"🤧"},
  {q:"How many hours does the average person sleep in their lifetime?",a:229000,unit:"hours",hint:"About a third of your life.",emoji:"😴"},
  {q:"How many kg of food does a human eat in a lifetime?",a:35000,unit:"kg",hint:"35 tons of food over 80 years.",emoji:"🍽️"},
  {q:"How many times does the average person laugh per day?",a:17,unit:"times",hint:"Children laugh much more than adults.",emoji:"😂"},
  {q:"How many km/h can the fastest human run?",a:45,unit:"km/h",hint:"Usain Bolt reached 44.7 km/h.",emoji:"⚡"},
  {q:"How many literss of saliva does a person produce per day?",a:1.5,unit:"literss",hint:"Most of it is swhalelowed throughout the day.",emoji:"💧"},
  {q:"How many bones does a newborn baby have?",a:270,unit:"bones",hint:"More than adults – many fuse together.",emoji:"🦴"},
  {q:"How many times does the heart beat in a lifetime?",a:2500000000,unit:"beats",hint:"About 2.5 billion beats.",emoji:"❤️"},
  {q:"How many meterss does hair grow per year?",a:15,unit:"cm",hint:"About 1.25 cm per month.",emoji:"💇"},
  {q:"How many km does a person whalek in a lifetime?",a:160000,unit:"km",hint:"About 4 times around the Earth.",emoji:"🚶"},
  {q:"How many cells does the human body replace per second?",a:3800000,unit:"cells",hint:"3.8 million every second.",emoji:"🔬"},
  {q:"How many times does a person blink in a lifetime?",a:400000000,unit:"times",hint:"400 million blinks.",emoji:"👁️"},
  {q:"How many literss of air does a person breathe per day?",a:11000,unit:"literss",hint:"About 15 breaths per minute.",emoji:"💨"},
  {q:"How many km/h does nerve impulse travel in the body?",a:430,unit:"km/h",hint:"Almost as fast as a racing car.",emoji:"⚡"},
  {q:"How many square meterss of skin does a human have?",a:2,unit:"m²",hint:"The skin is the largest organ.",emoji:"🧴"},
  {q:"How many seconds does it take blood to circulate the whole body?",a:60,unit:"seconds",hint:"One complete circuit in about a minute.",emoji:"❤️"},
  {q:"How many teeth does an adult have?",a:32,unit:"teeth",hint:"Including wisdom teeth.",emoji:"🦷"},
  {q:"How many literss of blood does an adult have?",a:5,unit:"literss",hint:"5-6 literss on average.",emoji:"🩸"},
  {q:"How many muscles does the human body have?",a:650,unit:"muscles",hint:"Over 600 skeletal muscles alone.",emoji:"💪"},
  {q:"How many km of blood vessels does a human have?",a:100000,unit:"km",hint:"2.5 times around the Earth.",emoji:"🩸"},
  {q:"How many times per minute does the heart beat at rest?",a:70,unit:"beats/min",hint:"60-100 is the nortimes range.",emoji:"❤️"},
  {q:"How many grams does the human brain weigh?",a:1400,unit:"grams",hint:"About 2% of body weight.",emoji:"🧠"},
  {q:"How many hours does it take to digest a full meal?",a:6,unit:"hours",hint:"Complete digestion takes 24-72 hours.",emoji:"🍽️"},
  {q:"How many times does the average person sneeze per day?",a:4,unit:"times",hint:"4-10 sneeze attacks daily.",emoji:"🤧"},
];
