// 💩 BODY & GROSS – English
export default [
  {q:"How many Liter Pupsgase produziert a human per day?",a:1.5,unit:"liters",hint:"14-23 Mal daily ein Pups.",emoji:"💨"},
  {q:"How many Gramm wiegt ein normaler Stuhlgang?",a:150,unit:"grams",hint:"100-200g ist der Normalbereich.",emoji:"💩"},
  {q:"How many Mal per day pupst a human on average?",a:14,unit:"times",hint:"Komplett normal – Frauen auch.",emoji:"💨"},
  {q:"How many Liter Schleim produziert die Nase daily?",a:1,unit:"liters",hint:"Ein Liter daily – fast alles schlucken wir.",emoji:"🤧"},
  {q:"How many Milliliter Schmalz scheidet ein Ohr per month aus?",a:1,unit:"ml",hint:"Erstaunlich viel für ein so kleines Organ.",emoji:"👂"},
  {q:"How many Gramm Bakterien sind im Darm eines Menschen?",a:200,unit:"grams",hint:"Das Darmmikrobiom wiegt 200g.",emoji:"🦠"},
  {q:"How many Mal im Leben wird a human kotzen (übergeben)?",a:200,unit:"times",hint:"Durchschnittlich über ein Leben.",emoji:"🤢"},
  {q:"How many Liter Magensäure werden beim Erbrechen hochgepumpt?",a:0.3,unit:"liters",hint:"300ml bei einem typischen Erbrechen.",emoji:"🤮"},
  {q:"How many Gramm Hautzellen verliert a human daily?",a:30,unit:"grams",hint:"Dein Bett sammelt das alles auf.",emoji:"🧑"},
  {q:"How many million Bakterien überträgt man beim Händeschütteln?",a:10,unit:"million",hint:"Ein Händedruck überträgt 10-100 million.",emoji:"🤝"},
  {q:"How many Liter Schweiß produziert a human bei einem Ultramarathon?",a:10,unit:"liters",hint:"Bei extremer Hitze und Belastung.",emoji:"💦"},
  {q:"How many million Bakterien sind auf einem Schreibtisch pro m²?",a:400,unit:"million",hint:"Schreibtische sind schmutziger als Toiletten.",emoji:"🦠"},
  {q:"How many Sekunden dauert ein Nieser von Einatmung bis Explosion?",a:0.5,unit:"seconds",hint:"Schleudert Partikel mit 160km/h.",emoji:"🤧"},
  {q:"How many km/h fliegen Schleimpartikel beim Niesen?",a:160,unit:"km/h",hint:"Bis zu 8 Meter weit.",emoji:"🤧"},
  {q:"How many Gramm Schweiß produziert a human per hour beim Sport?",a:1000,unit:"grams",hint:"1 Liter Schweiß per hour.",emoji:"💦"},
  {q:"How many million Mikrobenwird in der Öffentlichkeit daily ausgeatmet?",a:37,unit:"million",hint:"Nur durch normales Atmen.",emoji:"💨"},
  {q:"How many Liter Urin produziert a human per day?",a:1.5,unit:"liters",hint:"1-2 Liter bei normaler Hydration.",emoji:"💛"},
  {q:"How many Mal im Jahr bekommt ein Europäer Durchfall?",a:2,unit:"times",hint:"Gastroenteritis ist sehr häufig.",emoji:"🚽"},
  {q:"How many Tonnen Kot produziert a human in seinem Leben?",a:8,unit:"tons",hint:"Bei 150g per day über 70 Jahre.",emoji:"💩"},
  {q:"How many million Bakterien sind auf einer Zahnbürste?",a:10,unit:"million",hint:"Nach nur wenigen Tagen Benutzung.",emoji:"🦷"},
  {q:"How many Gramm Körpergeruchsbakterien produziert a human daily?",a:2,unit:"grams",hint:"Bakterien bauen Schweißproteine ab.",emoji:"💦"},
  {q:"How many Liter Speichel enthält ein Kuss?",a:3,unit:"ml",hint:"3ml Speichel – plus 80 million Bakterien.",emoji:"💋"},
  {q:"How many Gramm Fußpilzporen können in einem Zimmer sein?",a:10,unit:"mg",hint:"Winzige Mengen – reichen aber für Infektionen.",emoji:"🦶"},
  {q:"How many million Bakterien sind auf einem Küchenspülschwamm?",a:54,unit:"billion",hint:"billion – schmutzigster Haushaltsgegenstand.",emoji:"🫧"},
  {q:"How many Mal husten Menschen mit Erkältung am Tag?",a:200,unit:"times",hint:"Bis zu viele Male daily.",emoji:"😷"},
  {q:"How many Gramm Magen-Darm-Inhalt werden beim Erbrechen ausgeworfen?",a:300,unit:"grams",hint:"Je nach Mahlzeit.",emoji:"🤮"},
  {q:"How many million Hautzellen sind in einem Bett nach einem Jahr?",a:1000,unit:"million",hint:"Matratzen sammeln enormen Schmutz.",emoji:"🛏️"},
  {q:"How many Liter Urin sind in einer vollen Blase?",a:0.6,unit:"liters",hint:"500-600ml maximale Kapazität.",emoji:"💛"},
  {q:"How many million Sporen kann ein Schimmelpilz per day produzieren?",a:1000,unit:"million",hint:"1 Milliarde Sporen – winzig und überall.",emoji:"🍄"},
  {q:"How many Liter Galle produziert die Leber daily?",a:0.5,unit:"liters",hint:"500ml – essenziell für die Fettverdauung.",emoji:"💛"},
  {q:"How many Gramm Kot enthalten Sandwichbrote wenn kein Händewaschen erfolgt?",a:200,unit:"mg",hint:"Messstudie: Fäkalbakterien auf 1 von 6 Hände.",emoji:"🤢"},
  {q:"How many million Bakterien sind auf einem Handtuch nach einer Woche?",a:100,unit:"million",hint:"Badezimmerhandtücher sind voller Bakterien.",emoji:"🧺"},
  {q:"How many km/h ist die maximale Geschwindigkeit eines Huste-Ausstoßes?",a:150,unit:"km/h",hint:"Etwas langsamer als ein Niesen.",emoji:"😷"},
  {q:"How many Gramm wiegt der gesamte Inhalt des Dünndarms?",a:500,unit:"grams",hint:"Inklusive unverdauter Nahrung und Flüssigkeit.",emoji:"🌀"},
  {q:"How many million Bakterien überträgt ein Handschlag?",a:10,unit:"million",hint:"Hände sind der größte Übertragungsweg.",emoji:"🤝"},
  {q:"How many Liter Gallensäfte werden daily produziert?",a:1,unit:"liters",hint:"Aus Leber und Gallenblase.",emoji:"💛"},
  {q:"How many Gramm Ohrenschmalz produziert ein Ohr per year?",a:12,unit:"grams",hint:"12g – ein Esslöffel per year.",emoji:"👂"},
  {q:"How many million Hausmilben sind in einem Kopfkissen?",a:10,unit:"million",hint:"Ernähren sich von Hautschuppen.",emoji:"🛏️"},
  {q:"How many Gramm Kot werden nach einem Einlauf ausgeschieden?",a:2000,unit:"grams",hint:"2 Liter – mehr als ein normaler Stuhlgang.",emoji:"💩"},
  {q:"How many Liter Flüssigkeit verliert man beim Schwitzen in der Sauna?",a:1.5,unit:"liters",hint:"Pro Saunagang.",emoji:"🧖"},
  {q:"How many million Bakterien sind auf einer Türklinke?",a:10,unit:"million",hint:"Öffentliche Türklinken sind voller Keime.",emoji:"🦠"},
  {q:"How many Gramm Zahnstein bilden sich ohne Mundhygiene per year?",a:10,unit:"grams",hint:"Mineralisierter Zahnbelag.",emoji:"🦷"},
  {q:"How many million Haare verliert man durch normales Waschen per week?",a:700,unit:"hairs",hint:"100 per day × 7 Tage.",emoji:"🚿"},
  {q:"How many Gramm Augenabsonderung produzieren die Augen daily?",a:1,unit:"grams",hint:"Die Krusten am Morgen.",emoji:"👁️"},
  {q:"How many million Bakterien sind in einem Liter Trinkwasser?",a:1,unit:"million",hint:"In normalem Leitungswasser – meist harmlos.",emoji:"💧"},
  {q:"How many Gramm Stuhl kann ein Darm zurückhalten ohne Druck zu spüren?",a:500,unit:"grams",hint:"500g bevor der Harndrang kommt.",emoji:"💩"},
  {q:"How many Liter Speichel schluckt man daily?",a:1.5,unit:"liters",hint:"Den ganzen Tag produziert und geschluckt.",emoji:"💧"},
  {q:"How many million Schimmelpilzsporen sind in einem normalen Haus?",a:10,unit:"million",hint:"Überall – besonders in Badezimmern.",emoji:"🍄"},
  {q:"How many Gramm Schmegma bilden sich wöchentlich ungewaschen?",a:5,unit:"grams",hint:"Talgabsonderungen unter der Vorhaut.",emoji:"😬"},
  {q:"How many million Fäkalbakterien sind auf einem Smartphone?",a:25,unit:"thousand",hint:"Mehr als auf einer Toilette.",emoji:"📱"},
  {q:"How many Liter Blut verliert a woman während ihrer Lebens-Perioden?",a:30,unit:"liters",hint:"Ca. 50ml pro Periode × 500 Perioden.",emoji:"🩸"},
  {q:"How many Gramm Abgase atmet a human in einer Großstadt daily ein?",a:100,unit:"mg",hint:"Feinstaub und Abgase.",emoji:"🌫️"},
  {q:"How many million Bakterien sterben daily in unserem Körper?",a:1000,unit:"billion",hint:"Billionen Bakterien im Gleichgewicht.",emoji:"🦠"},
  {q:"How many Gramm Schmutz sind in Regenregenwasser pro Liter?",a:1,unit:"mg",hint:"Mikropartikel in jedem Regentropfen.",emoji:"🌧️"},
  {q:"How many million Keime sind im Mund nach dem Aufwachen?",a:20,unit:"billion",hint:"Morgenmund enthält viele Bakterien.",emoji:"😬"},
  {q:"How many Gramm Hautschuppen fallen per year aus dem Haar?",a:5,unit:"grams",hint:"Dandruff – normal bis 5g daily.",emoji:"💇"},
  {q:"How many Liter Blut werden pro Periode ausgegeben?",a:50,unit:"ml",hint:"50ml – weniger als viele denken.",emoji:"🩸"},
  {q:"How many million Staubmilben leben in einem durchschnittlichen Bett?",a:10,unit:"million",hint:"Sie fressen unsere Hautzellen.",emoji:"🛏️"},
  {q:"How many Liter Mageninhalt werden beim Erbrechen maximal ausgeleert?",a:1.5,unit:"liters",hint:"Magenkapazität beträgt maximal 1,5L.",emoji:"🤮"},
  {q:"How many million Bakterien sind auf einem frischen Küchenmesser?",a:5,unit:"million",hint:"Besonders auf dem Griff.",emoji:"🔪"},
  {q:"How many Gramm Fett schwitzt der Körper daily aus?",a:5,unit:"grams",hint:"Talg und Lipide in Schweiß.",emoji:"💦"},
  {q:"How many Liter Schleim produziert der Darm daily?",a:1.5,unit:"liters",hint:"Schleimhaut schützt den Darm.",emoji:"🌀"},
  {q:"How many million Keime überlebt eine Toilette pro Flush?",a:10,unit:"million",hint:"Toilet plume – Keime in der Luft nach dem Spülen.",emoji:"🚽"},
  {q:"How many Gramm Schmutz werden beim Händewaschen entfernt?",a:500,unit:"mg",hint:"0,5g Schmutz und Keime.",emoji:"🧼"},
  {q:"How many Gramm Haare werden monatlich geschluckt?",a:500,unit:"mg",hint:"Durch Essen, Küssen, Luftschlucken.",emoji:"💇"},
  {q:"How many Liter Körperflüssigkeiten verliert a human daily insgesamt?",a:2.5,unit:"liters",hint:"Urin, Schweiß, Atemluft zusammen.",emoji:"💧"},
  {q:"How many million Bakterien sind auf einem Geldschein?",a:26,unit:"thousand",hint:"Bargeld ist eines der dreckigsten Dinge.",emoji:"💵"},
  {q:"How many Gramm unverdaute Nahrung sind im Dickdarm?",a:1000,unit:"grams",hint:"1 kg Nahrungsreste im Dickdarm.",emoji:"🌀"},
  {q:"How many million Pilzsporen atmet a human daily ein?",a:1,unit:"Million",hint:"Überall in der Luft – meistens harmlos.",emoji:"🍄"},
  {q:"How many Gramm Körperfett verbrennt man beim Schlafen?",a:70,unit:"grams",hint:"Bei 7-8 Stunden Schlaf.",emoji:"😴"},
  {q:"How many Liter Blut enthält ein normales Steak?",a:0.1,unit:"liters",hint:"Das Rote ist Myoglobin, nicht Blut.",emoji:"🥩"},
  {q:"How many million Bakterien überlebt in einem Desinfektionsmittel?",a:1,unit:"thousand",hint:"Gute Desinfektionsmittel töten 99,999%.",emoji:"🧴"},
  {q:"How many Gramm Fingernagel-Dreck enthält eine ungewaschene Hand?",a:10,unit:"mg",hint:"Unter jedem Nagel bis zu 10.000 Bakterien.",emoji:"💅"},
  {q:"How many Liter Eiter kann ein Abszess enthalten?",a:0.5,unit:"liters",hint:"Große Abszesse können Tassen voll enthalten.",emoji:"😨"},
  {q:"How many million Zecken sind im Frühjahr in deutschen Wäldern aktiv?",a:100,unit:"million",hint:"Und jede zehnte trägt Borreliose.",emoji:"🕷️"},
  {q:"How many Gramm Fußschweiß produziert ein Fuß daily?",a:50,unit:"grams",hint:"Ein Mensch hat 250.000 Schweißdrüsen an den Füßen.",emoji:"🦶"},
  {q:"How many million Mücken-Stiche passieren in Deutschland im Sommer?",a:10,unit:"billion",hint:"Pro Nacht im Sommer.",emoji:"🦟"},
  {q:"How many Liter Lymphflüssigkeit hat der Körper?",a:2,unit:"liters",hint:"Das Lymphsystem transportiert Immunzellen.",emoji:"💛"},
  {q:"How many Gramm Schmutz enthält ein Staubsaugerbeutel nach einem Monat?",a:200,unit:"grams",hint:"Davon viel Hautschuppen und Staubmilben.",emoji:"🌀"},
  {q:"How many million Viren sind in einem Milliliter Meerwasser?",a:10,unit:"million",hint:"Das Meer ist voller Viren – meist für Algen.",emoji:"🌊"},
  {q:"How many Gramm Schmalz produziert die Haut daily?",a:10,unit:"grams",hint:"Talg als Hautschutz.",emoji:"✨"},
  {q:"How many Liter Darmgase entstehen daily?",a:2,unit:"liters",hint:"Davon werden 1,5L als Pupse abgegeben.",emoji:"💨"},
  {q:"How many million Hausmilben sind in einem Teppich pro m²?",a:1,unit:"Million",hint:"Jede isst Hautschuppen.",emoji:"🏠"},
  {q:"How many Liter Körperwärme verliert man beim Schwitzen insgesamt im Sommer?",a:5,unit:"liters",hint:"An einem heißen Tag.",emoji:"🌡️"},
  {q:"How many million Stunden verbringt die Menschheit daily auf der Toilette?",a:50,unit:"Millionen Stunden",hint:"8 billion Menschen × 6 Minuten.",emoji:"🚽"},
  {q:"How many Gramm Talg produziert eine Teenager-Haut daily?",a:15,unit:"grams",hint:"Mehr als Erwachsene – daher Akne.",emoji:"😬"},
  {q:"How many Liter Bauchspeichel produziert die Bauchspeicheldrüse daily?",a:1.5,unit:"liters",hint:"Mit wichtigen Verdauungsenzymen.",emoji:"⚗️"},
  {q:"How many million Keime sind auf einem Trinkglas nach dem Abtrocknen?",a:5,unit:"million",hint:"Feuchte Tücher übertragen Keime.",emoji:"🥃"},
  {q:"How many Gramm Zähne-Schmutz (Plaque) bilden sich daily?",a:500,unit:"mg",hint:"Ohne Zähneputzen schnell viel.",emoji:"🦷"},
  {q:"How many Liter Blut verliert man bei einem normalen Zahnarzteingriff?",a:1,unit:"ml",hint:"1ml – kaum messbar.",emoji:"🩸"},
  {q:"How many million Trichinen können in einem Stück Rohfleisch sein?",a:1,unit:"Million",hint:"Grund warum Schweinefleisch durchgegart sein muss.",emoji:"🥩"},
  {q:"How many Gramm Hornhaut wächst am Fuß per month?",a:1,unit:"grams",hint:"Besonders bei Druck.",emoji:"🦶"},
  {q:"How many Liter Flüssigkeit ist in einer normalen Blase beim Platzdruck?",a:0.7,unit:"liters",hint:"700ml – dann wird es schmerzhaft.",emoji:"💛"},
  {q:"How many million Bakterien werden beim Pinkeln in die Luft geschleudert?",a:1,unit:"Million",hint:"Toilet plume – WC-Spritzer.",emoji:"🚽"},
  {q:"How many Gramm Schweiß riechen ohne Deo nach einer Stunde?",a:100,unit:"mg",hint:"Bakterien bauen Schweißsäuren ab.",emoji:"💦"},
  {q:"How many Liter Blut fließen bei einer normalen Geburt?",a:0.5,unit:"liters",hint:"Normaler Blutverlust bei Vaginalgeburt.",emoji:"🤱"},
  {q:"How many million Parasiten kann a human beherbergen?",a:1,unit:"Million",hint:"Darmenparasiten bei Infektion.",emoji:"🪱"},
  {q:"How many Gramm Zellreste sind in einem normalen Stuhlgang?",a:50,unit:"grams",hint:"Abgestorbene Darmzellen.",emoji:"💩"},
  {q:"How many Liter Flüssigkeit produziert der Darm daily?",a:8,unit:"liters",hint:"Fast alle werden rückresorbiert.",emoji:"🌀"},
  {q:"How many million Bakterien sterben bei 60°C in Sekunden?",a:1000,unit:"million",hint:"Pasteurisierung nutzt genau das.",emoji:"🌡️"},
  {q:"How many Gramm Pupsgase sind pro Pups?",a:70,unit:"mg",hint:"70ml Gas – je nach Diät mehr.",emoji:"💨"},
  {q:"How many Liter Schleim schluckt man beim Schnupfen daily?",a:1,unit:"liters",hint:"Mehr als man denkt.",emoji:"🤧"},
  {q:"How many Gramm Körperfett werden per hour Schlaf verbrannt?",a:10,unit:"grams",hint:"Insgesamt 70g pro Nacht.",emoji:"😴"},
  {q:"How many Liter Urin kann die Blase halten ohne Schmerz?",a:0.4,unit:"liters",hint:"Harndrang beginnt schon bei 250ml.",emoji:"💛"},
  {q:"How many million Würmer können im Darm bei starker Infektion sein?",a:1,unit:"Million",hint:"Spulwürmer können zu Tausenden vorkommen.",emoji:"🪱"},
  {q:"How many Gramm Gift scheidet die Leber daily aus?",a:10,unit:"grams",hint:"Entgiftungsleistung per day.",emoji:"🟤"},
  {q:"How many Liter Blut verliert man bei einer Amputation?",a:2,unit:"liters",hint:"Ohne tourniquet – schnell lebensbedrohlich.",emoji:"🩸"},
  {q:"How many million Keime sind auf einer Computertastatur?",a:400,unit:"million",hint:"Tastaturen sind schmutziger als Toiletten.",emoji:"💻"},
  {q:"How many Gramm Nasensekret produziert man bei starker Erkältung per day?",a:50,unit:"grams",hint:"50ml Schleim – viel schnäuzen.",emoji:"🤧"},
  {q:"How many Liter Blut verliert man monatlich beim Zähneputzen?",a:1,unit:"ml",hint:"1ml – zahnfleischbluten.",emoji:"🩸"},
  {q:"How many Gramm Körperzellen sterben daily ab?",a:50,unit:"grams",hint:"50g Zellmasse wird daily ersetzt.",emoji:"🔬"},
  {q:"How many Liter Speichelfluss passiert beim Gedanken an Essen?",a:0.1,unit:"liters",hint:"100ml allein durch pavlovsche Reaktion.",emoji:"🍕"},
  {q:"How many million Keime überlebt auf einem Kissenbezug nach einer Woche?",a:3,unit:"million",hint:"Besonders Gesichtsbakterien.",emoji:"🛏️"},
  {q:"How many Gramm Fett produzieren die Kopfhautdrüsen daily?",a:1,unit:"grams",hint:"1g Talg – macht Haare fettig.",emoji:"💇"},
  {q:"How many Liter Blut produziert der Körper daily neu?",a:0.2,unit:"liters",hint:"200ml neue rote Blutkörperchen.",emoji:"🩸"},
  {q:"How many million Viren atmet man in einer Stunde im Büro ein?",a:100,unit:"million",hint:"In Innenräumen sehr viele Viren.",emoji:"🦠"},
  {q:"How many Gramm Kot enthält ein menschlicher Körper on average?",a:1000,unit:"grams",hint:"1 kg im Darm immer vorhanden.",emoji:"💩"},
  {q:"How many Liter Flüssigkeit fließt daily durch die Nieren?",a:180,unit:"liters",hint:"180L werden gefiltert – nur 1.5L Urin.",emoji:"🫘"},
  {q:"How many million Parasiteneier sind in unbewässertem Boden pro m²?",a:10,unit:"million",hint:"Hakenwürmer, Spulwürmer in Dritte-Welt-Böden.",emoji:"🌱"},
  {q:"How many Gramm Säure ist im Erbrochenen?",a:5,unit:"grams",hint:"Magensäure pH 1-2.",emoji:"⚗️"},
  {q:"How many Liter Tränen produziert a human beim Weinen?",a:10,unit:"ml",hint:"10ml bei einem weinanfall.",emoji:"😢"},
  {q:"How many million Bakterien sind auf einem Klospülknopf?",a:50,unit:"million",hint:"Mehr als auf dem Klositz.",emoji:"🚽"},
  {q:"How many Gramm Schleim sind in der Lunge?",a:150,unit:"grams",hint:"Schleimhaut schützt die Atemwege.",emoji:"🫁"},
  {q:"How many Liter Magenflüssigkeit kann man beim Spülen entleeren?",a:3,unit:"liters",hint:"Magenspülung – bei Vergiftung.",emoji:"⚗️"},
  {q:"How many million Keime überlebt ein Sponge/Schwamm nach 1 Min Mikrowelle?",a:1,unit:"million",hint:"Mikrowellen töten nicht alle Keime.",emoji:"🫧"},
  {q:"How many Gramm Talgablagerungen entstehen in verstopften Poren (Mitesser)?",a:1,unit:"mg",hint:"Winzige Mengen – aber sichtbar.",emoji:"😬"},
  {q:"How many Liter Schweiß produziert der Körper per hour in Hitze?",a:2,unit:"liters",hint:"Bei extremer Hitze bis 3L.",emoji:"☀️"},
  {q:"How many million Bakterien sind auf einem frischen Geldschein?",a:26000,unit:"Bakterien",hint:"Neues Geld hat weniger als altes.",emoji:"💵"},
  {q:"How many Gramm Körperschuppen sind im Hausstaub?",a:70,unit:"%",hint:"Des Hausstaubs sind Hautschuppen.",emoji:"🌀"},
  {q:"How many Liter Blut enthält die Leber?",a:1.5,unit:"liters",hint:"Die Leber ist ein Blutreservoir.",emoji:"🟤"},
  {q:"How many million Bakterien sind auf einem Lichtschalter?",a:220,unit:"thousand",hint:"Häufig berührt – selten gereinigt.",emoji:"💡"},
  {q:"How many Gramm Fäkalbakterien könnten auf einem Buffet-Essen sein?",a:1,unit:"mg",hint:"Schlechte Handhygiene von Köchen.",emoji:"🍽️"},
  {q:"How many Liter Schweiß produziert man in einer Sauna (Stunde)?",a:1.5,unit:"liters",hint:"Bei 80-90°C.",emoji:"🧖"},
  {q:"How many million Pilzsporen produziert ein Schimmelpilz pro Sekunde?",a:1,unit:"million",hint:"Schimmel verbreitet sich extrem schnell.",emoji:"🍄"},
  {q:"How many Gramm Schleim werden bei einer Erkältung daily produziert?",a:100,unit:"grams",hint:"100ml Schleim – viel davon geschluckt.",emoji:"🤧"},
  {q:"How many billion Liter Urin werden daily in deutschen WCs gespült?",a:20,unit:"billion liters",hint:"Enorme Wasserverschwendung.",emoji:"🚽"},
  {q:"How many million Bakterien sind in 1g frischer Erde?",a:1000,unit:"million",hint:"1 Milliarde Bakterien pro Gramm Erde.",emoji:"🌱"},
  {q:"How many Gramm Schmutz sammeln sich per year im Bauchnabel?",a:500,unit:"mg",hint:"Flusen, Öl und Bakterien.",emoji:"🔘"},
  {q:"How many Liter Blut verliert man bei einer normalen Menstruation?",a:50,unit:"ml",hint:"50ml pro Periode.",emoji:"🩸"},
  {q:"How many million Bakterien produziert a human daily durch Hautkontakt?",a:1000,unit:"million",hint:"Jede Berührung hinterlässt Spuren.",emoji:"🤲"},
  {q:"How many Gramm totes Gewebe enthält ein Nagel bei Pilzinfektion?",a:1,unit:"grams",hint:"Onychomykose – Pilz zerstört Nagelstruktur.",emoji:"💅"},
  {q:"How many Liter Lymphe wird daily durch Lymphknoten gefiltert?",a:3,unit:"liters",hint:"Das Lymphsystem als zweites Transportsystem.",emoji:"💛"},
  {q:"How many million Keime sind in einem Handtuch nach einer Woche?",a:100,unit:"million",hint:"Feuchte Handtücher sind ideal für Bakterien.",emoji:"🧺"},
  {q:"How many Gramm unverdautes Essen verlässt den Körper im Stuhl daily?",a:30,unit:"grams",hint:"Ballaststoffe und unverdauliche Reste.",emoji:"💩"},
  {q:"How many Liter Magensäure werden daily produziert?",a:2,unit:"liters",hint:"Stark genug um Stahl aufzulösen.",emoji:"⚗️"},
  {q:"How many million Viren sind in 1ml Flusswasser?",a:1,unit:"Million",hint:"Flüsse sind voller Viren – meist harmlose.",emoji:"🌊"},
  {q:"How many Gramm Körperfett werden beim Lachen verbrannt?",a:1,unit:"mg",hint:"Sehr wenig – aber Lachen ist gesund.",emoji:"😂"},
  {q:"How many Liter Speichelfluss produziert ein Hund daily?",a:2,unit:"liters",hint:"Hunde speicheln deutlich mehr als Menschen.",emoji:"🐕"},
  {q:"How many million Bakterien sind auf der Zunge nach dem Aufwachen?",a:20,unit:"billion",hint:"Morgenatemluft riecht so schlimm wegen Bakterien.",emoji:"👅"},
  {q:"How many Gramm Kot werden in einem Jahr Darmträgheit angesammelt?",a:3000,unit:"grams",hint:"Chronische Verstopfung kann zu Ablagerungen führen.",emoji:"💩"},
  {q:"How many Liter Blut filtert die Niere daily?",a:180,unit:"liters",hint:"Alle 30 Minuten das gesamte Blutvolumen.",emoji:"🫘"},
  {q:"How many million Keime überlebt ein Sponge ohne Reinigung?",a:54000,unit:"million",hint:"54 billion – der schmutzigste Küchengegenstand.",emoji:"🫧"},
  {q:"How many Gramm Eiter kann ein Furunkel enthalten?",a:5,unit:"grams",hint:"Eiterpustel kann erstaunlich viel fassen.",emoji:"😨"},
  {q:"How many Liter Flüssigkeit verliert man beim Marathon?",a:4,unit:"liters",hint:"Durch Schwitzen und Atmen.",emoji:"🏃"},
  {q:"How many million Parasiten hat die Weltbevölkerung gemeinsam?",a:1000,unit:"billion",hint:"Parasiten infizieren billion Menschen.",emoji:"🪱"},
  {q:"How many Gramm Zahnfleisch-Bakterien produziert der Mund daily?",a:1,unit:"grams",hint:"Dentalplaque-Bakterien.",emoji:"🦷"},
  {q:"How many Liter Urin enthält eine Blase kurz vor dem Platzen?",a:1,unit:"liters",hint:"Schmerzhaft – Platzen ist nur theoretisch.",emoji:"💛"},
  {q:"How many million Spulwürmer-Eier können in einem Gemüsegarten sein?",a:10,unit:"million",hint:"Hauptursache für Parasiteninfektionen.",emoji:"🥦"},
  {q:"How many Gramm Hautzellen findet man in einem Staubsauger nach Monat?",a:100,unit:"grams",hint:"Hauptanteil des Staubsaugerinhalts.",emoji:"🌀"},
  {q:"How many Liter Körperflüssigkeiten werden daily verloren und ersetzt?",a:2.5,unit:"liters",hint:"Urin, Schweiß, Atem und Verdauung.",emoji:"💧"},
  {q:"How many million Pilze können auf einem ungepflegten Fuß leben?",a:100,unit:"million",hint:"Fußpilz – oft unbemerkt.",emoji:"🦶"},
  {q:"How many Gramm Körperfett enthält ein Liter menschlicher Muttermilch?",a:40,unit:"grams",hint:"3,5-4,5% Fettgehalt.",emoji:"🤱"},
  {q:"How many Liter Gesamtblut fließt daily durch die Leber?",a:1500,unit:"liters",hint:"Die Leber ist stark durchblutet.",emoji:"🟤"},
  {q:"How many million Coli-Bakterien sind in 1ml Abwasser?",a:100,unit:"million",hint:"Roh-Abwasser enthält million E.coli.",emoji:"💧"},
  {q:"How many Gramm Gallenflüssigkeit produziert die Gallenblase daily?",a:800,unit:"ml",hint:"Galle daily.",emoji:"💛"},
  {q:"How many Liter Blut enthält eine erwachsene Leber?",a:1.5,unit:"liters",hint:"25% des Herzschlagvolumens fließt zur Leber.",emoji:"🟤"},
  {q:"How many million Viren befinden sich in 1 Liter Luft in Innenräumen?",a:100,unit:"million",hint:"Besonders in schlecht belüfteten Räumen.",emoji:"🦠"},
  {q:"How many Gramm Körpersalz verliert man beim Sport per hour?",a:2,unit:"grams",hint:"2g Natrium pro Liter Schweiß.",emoji:"🧂"},
  {q:"How many Liter Flüssigkeit verliert ein Körper beim Sterben?",a:2,unit:"liters",hint:"Körper dehydriert stark am Ende.",emoji:"☠️"},
  {q:"How many million Bakterien sind in frischer Milch (unpasteurisiert)?",a:100,unit:"million",hint:"Rohmilch enthält viele Keime.",emoji:"🥛"},
  {q:"How many Gramm Bakterienmasse ist der gesunde Stuhl?",a:30,unit:"%",hint:"Des Stuhls sind Bakterien.",emoji:"💩"},
];
