export default [
  {id:"test_001",q:"How many times does the human heart beat per day?",a:100000,unit:"times",hint:"70 beats/min × 60 × 24 ≈ 100,000 times a day.",emoji:"❤️"},
  {id:"test_002",q:"How many billion neurons does the human brain have?",a:86,unit:"billion neurons",hint:"86 billion neurons – with trillions of connections.",emoji:"🧠"},
  {id:"test_003",q:"How many liters of blood does an adult have in their body?",a:5,unit:"liters",hint:"About 5 liters – the heart pumps it through the body roughly 1,000 times a day.",emoji:"🩸"},
  {id:"test_004",q:"How many km/h can a human sneeze reach?",a:160,unit:"km/h",hint:"Up to 160 km/h – that's why you should cover your mouth!",emoji:"🤧"},
  {id:"test_005",q:"How many meters of DNA are packed into a single cell?",a:2,unit:"meters",hint:"2m × 37 trillion cells ≈ 17 times the distance from Earth to the Sun.",emoji:"🧬"},
  {id:"test_006",q:"How many billion bacteria live on a human's skin?",a:1800,unit:"billion",hint:"1,800 billion = 1.8 trillion – most of them are harmless.",emoji:"🦠"},
  {id:"test_007",q:"How many liters of sweat can you lose on a hot summer day?",a:5,unit:"liters",hint:"Up to 5 liters a day in extreme heat.",emoji:"💧"},
  {id:"test_008",q:"How many grams of skin cells does a human shed daily?",a:2,unit:"grams",hint:"1-3g per day – up to 1kg of skin flakes a year.",emoji:"🧴"},
  {id:"test_009",q:"How many liters of saliva does a human produce per year?",a:550,unit:"liters",hint:"About 1.5L/day × 365 ≈ 550 liters – enough to fill a bathtub.",emoji:"💦"},
  {id:"test_010",q:"How many times does a human blink per day?",a:15000,unit:"times",hint:"About 15-20 times per minute × 16 waking hours.",emoji:"👁️"},
  {id:"test_011",q:"What percentage of the brain does a human actually use?",a:100,unit:"%",hint:"100% – the 10% myth is scientifically false.",emoji:"🧠"},
  {id:"test_012",q:"How many years of their life does a human spend sleeping on average?",a:26,unit:"years",hint:"At 8h/night over 70 years ≈ 26 years of sleep.",emoji:"😴"},
  {id:"test_013",q:"How many million times does a human breathe in a lifetime?",a:700,unit:"million times",hint:"About 15-20 breaths per minute over 70 years.",emoji:"💨"},
  {id:"test_014",q:"How fast can a cheetah run, in km/h?",a:120,unit:"km/h",hint:"Up to 120 km/h – the fastest land animal.",emoji:"🐆"},
  {id:"test_015",q:"How many hours does a cat sleep per day?",a:16,unit:"hours",hint:"12-16 hours a day – true sleep experts.",emoji:"🐱"},
  {id:"test_016",q:"How many tons does a full-grown blue whale weigh?",a:150,unit:"tons",hint:"Up to 150-200 tons – the heaviest animal ever.",emoji:"🐋"},
  {id:"test_017",q:"How fast does a peregrine falcon fly in a dive, in km/h?",a:389,unit:"km/h",hint:"389 km/h – the fastest animal in the world.",emoji:"🦅"},
  {id:"test_018",q:"How many years can a bowhead whale live?",a:200,unit:"years",hint:"Up to 200 years – the oldest known mammal.",emoji:"🐋"},
  {id:"test_019",q:"What is the speed of light, in km/s?",a:300000,unit:"km/s",hint:"300,000 km/s – light takes about 8 minutes to travel from the Sun to Earth.",emoji:"💡"},
  {id:"test_020",q:"How many billion years old is the universe?",a:13.8,unit:"billion years",hint:"13.8 billion years since the Big Bang.",emoji:"🌌"},
  {id:"test_021",q:"How many degrees Celsius is the Sun's core temperature?",a:15,unit:"million °C",hint:"15 million degrees – that's where nuclear fusion happens.",emoji:"☀️"},
  {id:"test_022",q:"What is the atomic mass of a hydrogen atom?",a:1,unit:"atomic mass unit",hint:"Hydrogen is the lightest element.",emoji:"⚛️"},
  {id:"test_023",q:"In what year did the Berlin Wall fall?",a:1989,unit:"year",hint:"November 9, 1989 – one of the most significant events of the 20th century.",emoji:"🧱"},
  {id:"test_024",q:"How many years did World War II last?",a:6,unit:"years",hint:"1939–1945 – 6 years, the deadliest war in history.",emoji:"🕊️"},
  {id:"test_025",q:"How many million people died in World War I?",a:20,unit:"million",hint:"About 20 million dead – soldiers and civilians.",emoji:"🕊️"},
  {id:"test_026",q:"How many billion dollars is Apple worth?",a:3200,unit:"billion dollars",hint:"About 3,200 billion – the most valuable company in the world.",emoji:"🍎"},
  {id:"test_027",q:"How many billion dollars did Elon Musk pay for Twitter?",a:44,unit:"billion dollars",hint:"44 billion dollars – now called X.",emoji:"🐦"},
  {id:"test_028",q:"How many euros does 1 kg of gold cost?",a:70000,unit:"euros",hint:"About €70,000/kg (as of 2024) – highly variable.",emoji:"🥇"},
  {id:"test_029",q:"How many million sperm does 1 ml of ejaculate contain?",a:70,unit:"million sperm/ml",hint:"WHO reference value: ≥16 million/ml – 70 million/ml is considered good.",emoji:"🔬"},
  {id:"test_030",q:"How many seconds does an average orgasm last?",a:22,unit:"seconds",hint:"Men: 10-30s, women: 20-35s – on average about 22s.",emoji:"⏱️"},
  {id:"test_031",q:"How many minutes does sex last on average?",a:30,unit:"minutes",hint:"Including foreplay about 30 min., penetration alone 5-6 min.",emoji:"⏰"},
  {id:"test_032",q:"How many million people use cannabis regularly?",a:200,unit:"million people",hint:"About 200 million – the most widely used illegal drug in the world.",emoji:"🌿"},
  {id:"test_033",q:"How many grams of alcohol does the liver break down per hour?",a:10,unit:"grams/hour",hint:"0.1‰/hour ≈ 10g of alcohol for a 70kg person.",emoji:"🍺"},
  {id:"test_034",q:"How many billion dollars is the global tobacco market worth?",a:900,unit:"billion dollars",hint:"900 billion dollars a year – despite declining smoking rates.",emoji:"🚬"},
  {id:"test_035",q:"How many billion dollars did Avatar (2009) gross worldwide?",a:2.9,unit:"billion dollars",hint:"For a long time the highest-grossing film of all time.",emoji:"🎬"},
  {id:"test_036",q:"How many installments does the main Star Wars saga have?",a:9,unit:"installments",hint:"9 episodes – plus spin-offs like Rogue One and The Mandalorian.",emoji:"⭐"},
  {id:"test_037",q:"In what year did the first Harry Potter movie come out?",a:2001,unit:"year",hint:"Harry Potter and the Philosopher's Stone – November 2001.",emoji:"🧙"},
  {id:"test_038",q:"How many cups of coffee do Germans drink per year?",a:162,unit:"cups",hint:"About 162 liters per person – 3rd place worldwide.",emoji:"☕"},
  {id:"test_039",q:"How many calories does a Big Mac have?",a:563,unit:"kcal",hint:"About 563 kcal – without fries and a drink.",emoji:"🍔"},
  {id:"test_040",q:"What percentage of a tomato is water?",a:95,unit:"%",hint:"95% water – one of the most water-rich fruits.",emoji:"🍅"},
  {id:"test_041",q:"How many meters is the world record in the long jump?",a:8.95,unit:"meters",hint:"Mike Powell, 1991 – 8.95m, unbroken ever since.",emoji:"🏃"},
  {id:"test_042",q:"How fast did the fastest person on skis go, in km/h?",a:254,unit:"km/h",hint:"254 km/h – Ivan Origone, 2016.",emoji:"⛷️"},
  {id:"test_043",q:"How many hours did the longest tennis match last?",a:11,unit:"hours",hint:"Isner vs. Mahut, 2010 – 11 hours 5 minutes over 3 days.",emoji:"🎾"},
  {id:"test_044",q:"How many member states does the European Union have?",a:27,unit:"countries",hint:"27 members – without the UK since Brexit (2020).",emoji:"🇪🇺"},
  {id:"test_045",q:"How many permanent members does the UN Security Council have?",a:5,unit:"members",hint:"USA, Russia, China, France, United Kingdom.",emoji:"🌍"},
  {id:"test_046",q:"How many countries have the atomic bomb?",a:9,unit:"countries",hint:"USA, Russia, UK, France, China, Israel, India, Pakistan, North Korea.",emoji:"☢️"},
  {id:"test_047",q:"How many planets does our solar system have?",a:8,unit:"planets",hint:"Pluto was demoted to a dwarf planet in 2006.",emoji:"🪐"},
  {id:"test_048",q:"How many minutes does light take to travel from the Sun to Earth?",a:8,unit:"minutes",hint:"Light races at 300,000 km/s – yet it still takes 8 minutes.",emoji:"☀️"},
  {id:"test_049",q:"How many moons does Saturn have?",a:146,unit:"moons",hint:"Saturn has more moons than any other planet.",emoji:"🪐"},
];
