// 🧪 SCIENCE & INVENTIONS – Adults – 236 questions
export default [
  {id:"wiss_001",q:"In what year was the World Wide Web invented?",a:1989,unit:"year",hint:"Tim Berners-Lee developed it at CERN.",emoji:"🌐"},
  {id:"wiss_002",q:"How many elements does the periodic table have?",a:118,unit:"elements",hint:"The heaviest confirmed element is oganesson.",emoji:"⚗️"},
  {id:"wiss_003",q:"In what year did Fleming discover penicillin?",a:1928,unit:"year",hint:"He forgot a petri dish – and saved millions of lives.",emoji:"💊"},
  {id:"wiss_004",q:"What is the speed of light, in km/s?",a:299792,unit:"km/s",hint:"The fastest known speed in the universe.",emoji:"💡"},
  {id:"wiss_005",q:"In what year did Morse invent the telegraph?",a:1837,unit:"year",hint:"The first electrical means of communication.",emoji:"📡"},
  {id:"wiss_006",q:"How many degrees Celsius is absolute zero?",a:-273.15,unit:"°C",hint:"Zero Kelvin – no thermal motion left.",emoji:"🌡️"},
  {id:"wiss_007",q:"In what year did Darwin's 'On the Origin of Species' come out?",a:1859,unit:"year",hint:"The theory of evolution shook the world.",emoji:"🐒"},
  {id:"wiss_008",q:"How many nanometers small is an average virus?",a:100,unit:"nanometers",hint:"1000x smaller than a cell.",emoji:"🦠"},
  {id:"wiss_009",q:"In what year did Edison invent the light bulb?",a:1879,unit:"year",hint:"On October 22, 1879 – after a thousand attempts.",emoji:"💡"},
  {id:"wiss_010",q:"How many billion neurons does the human brain have?",a:86,unit:"billion",hint:"With trillions of synapses.",emoji:"🧠"},
  {id:"wiss_011",q:"In what year did Einstein discover special relativity?",a:1905,unit:"year",hint:"The Annus Mirabilis – Einstein's miracle year.",emoji:"⚛️"},
  {id:"wiss_012",q:"How many degrees does the Earth rotate daily on its axis?",a:360,unit:"degrees",hint:"Once around in 24 hours.",emoji:"🌍"},
  {id:"wiss_013",q:"In what year did Gutenberg invent the printing press?",a:1440,unit:"year",hint:"With movable type.",emoji:"📚"},
  {id:"wiss_014",q:"What is the atomic mass of carbon?",a:12,unit:"amu",hint:"Carbon-12 is the standard.",emoji:"⚗️"},
  {id:"wiss_015",q:"In what year did the first rocket reach space (V-2)?",a:1942,unit:"year",hint:"Developed by Wernher von Braun.",emoji:"🚀"},
  {id:"wiss_016",q:"How many degrees Fahrenheit is 100°C?",a:212,unit:"°F",hint:"The boiling point of water.",emoji:"🌡️"},
  {id:"wiss_017",q:"In what year did Baird invent television?",a:1926,unit:"year",hint:"John Logie Baird demonstrated it in 1926.",emoji:"📺"},
  {id:"wiss_018",q:"In what year did Curie discover radium?",a:1898,unit:"year",hint:"Marie and Pierre Curie together.",emoji:"☢️"},
  {id:"wiss_019",q:"How many km is Earth's circumference at the equator?",a:40075,unit:"km",hint:"Eratosthenes calculated it as early as 240 BCE.",emoji:"🌍"},
  {id:"wiss_020",q:"In what year did Bell invent the telephone?",a:1876,unit:"year",hint:"On March 10, 1876 – first sentence: 'Mr. Watson, come here'.",emoji:"📞"},
  {id:"wiss_021",q:"How many electrons does oxygen have?",a:8,unit:"electrons",hint:"Atomic number 8 – also 8 protons.",emoji:"⚗️"},
  {id:"wiss_022",q:"In what year was the first antibiotic (penicillin) used clinically?",a:1942,unit:"year",hint:"Saved millions during World War II.",emoji:"💊"},
  {id:"wiss_023",q:"What is Earth's gravitational acceleration, in m/s²?",a:9.81,unit:"m/s²",hint:"g = 9.81 m/s² – the foundation of physics.",emoji:"⬇️"},
  {id:"wiss_024",q:"In what year did Marconi invent the radio?",a:1895,unit:"year",hint:"The first wireless transmission.",emoji:"📻"},
  {id:"wiss_025",q:"How many degrees does a right angle have?",a:90,unit:"degrees",hint:"The definition of a right angle.",emoji:"📐"},
  {id:"wiss_026",q:"In what year did Röntgen discover X-rays?",a:1895,unit:"year",hint:"Discovered by accident on November 8, 1895.",emoji:"🩻"},
  {id:"wiss_027",q:"How many bits does a byte have?",a:8,unit:"bits",hint:"8 bits = 1 byte – the foundation of computing.",emoji:"💻"},
  {id:"wiss_028",q:"In what year did Diesel invent the diesel engine?",a:1897,unit:"year",hint:"Rudolf Diesel received the patent in 1897.",emoji:"🔧"},
  {id:"wiss_029",q:"How many protons does iron have?",a:26,unit:"protons",hint:"Fe – atomic number 26.",emoji:"⚗️"},
  {id:"wiss_030",q:"In what year was the first laser built?",a:1960,unit:"year",hint:"Theodore Maiman built it on May 16, 1960.",emoji:"💡"},
  {id:"wiss_031",q:"How many calories does 1 gram of fat have?",a:9,unit:"kcal/g",hint:"Fat has more than twice as many as carbohydrates.",emoji:"🔥"},
  {id:"wiss_032",q:"In what year did Nobel invent dynamite?",a:1867,unit:"year",hint:"Stabilized from nitroglycerin.",emoji:"💣"},
  {id:"wiss_033",q:"How many pairs of chromosomes does a human have?",a:23,unit:"pairs",hint:"46 chromosomes in total.",emoji:"🧬"},
  {id:"wiss_034",q:"In what year did the first computer model (ENIAC) appear?",a:1945,unit:"year",hint:"Electronic Numerical Integrator and Computer.",emoji:"💻"},
  {id:"wiss_035",q:"How many protons does helium have?",a:2,unit:"protons",hint:"The second-lightest element after hydrogen.",emoji:"⚗️"},
  {id:"wiss_036",q:"In what year did Watson and Crick discover the DNA double helix?",a:1953,unit:"year",hint:"With Rosalind Franklin's crucial data.",emoji:"🧬"},
  {id:"wiss_037",q:"How many degrees Celsius does alcohol (ethanol) boil at?",a:78.4,unit:"°C",hint:"Distillation uses this boiling point.",emoji:"🌡️"},
  {id:"wiss_038",q:"In what year did Watt invent the improved steam engine?",a:1769,unit:"year",hint:"Revolutionized industrialization.",emoji:"⚙️"},
  {id:"wiss_039",q:"How many sextillion atoms does a mole of matter have?",a:602,unit:"sextillion atoms",hint:"6.02 × 10²³ – Avogadro's number.",emoji:"⚗️"},
  {id:"wiss_040",q:"In what year was the first microscope invented?",a:1590,unit:"year",hint:"Zacharias Janssen in the Netherlands.",emoji:"🔬"},
  {id:"wiss_041",q:"How many protons does uranium have?",a:92,unit:"protons",hint:"The heaviest naturally occurring element.",emoji:"☢️"},
  {id:"wiss_042",q:"In what year did Archimedes discover his famous principle?",a:250,unit:"BCE",hint:"In the bath – Eureka!",emoji:"🛁"},
  {id:"wiss_043",q:"How many calories does the brain need daily?",a:300,unit:"kcal",hint:"20% of total energy consumption.",emoji:"🧠"},
  {id:"wiss_044",q:"In what year did Pasteur discover fermentation caused by microorganisms?",a:1857,unit:"year",hint:"The basis of food safety.",emoji:"🧫"},
  {id:"wiss_045",q:"How many electrons does carbon need for a stable outer orbital?",a:4,unit:"electrons",hint:"Carbon has 4 valence electrons.",emoji:"⚗️"},
  {id:"wiss_046",q:"In what year was the first vaccine developed (smallpox)?",a:1796,unit:"year",hint:"Edward Jenner vaccinated using cowpox virus.",emoji:"💉"},
  {id:"wiss_047",q:"How many Hz can a human hear at maximum?",a:20000,unit:"Hz",hint:"20 kHz – decreases with age.",emoji:"👂"},
  {id:"wiss_048",q:"In what year did Babbage invent the mechanical computer?",a:1837,unit:"year",hint:"The Analytical Engine – never completed.",emoji:"⚙️"},
  {id:"wiss_049",q:"How many degrees Celsius is the boiling point of nitrogen?",a:-196,unit:"°C",hint:"Liquid nitrogen, used for cryonics.",emoji:"🌡️"},
  {id:"wiss_050",q:"In what year did Hubble discover that the universe is expanding?",a:1929,unit:"year",hint:"Hubble's Law of cosmic expansion.",emoji:"🌌"},
  {id:"wiss_051",q:"How many kilowatt-hours of energy does 1 kg of uranium have?",a:24000,unit:"kWh",hint:"Equivalent to 3 tons of coal.",emoji:"⚡"},
  {id:"wiss_052",q:"In what year did Faraday discover the principle of electromagnetic induction?",a:1831,unit:"year",hint:"The basis of all electric motors and generators.",emoji:"⚡"},
  {id:"wiss_053",q:"How many meters long is the DNA in a human cell when stretched out?",a:2,unit:"meters",hint:"Meters of DNA in every cell nucleus.",emoji:"🧬"},
  {id:"wiss_054",q:"In what year was the first telescope built?",a:1608,unit:"year",hint:"Hans Lippershey filed the patent.",emoji:"🔭"},
  {id:"wiss_055",q:"How many nanometers small is a DNA strand in diameter?",a:2,unit:"nanometers",hint:"Nm – unimaginably small.",emoji:"🧬"},
  {id:"wiss_056",q:"In what year did Braun invent the cathode ray tube (Braun tube)?",a:1897,unit:"year",hint:"The basis of all early screens.",emoji:"📺"},
  {id:"wiss_057",q:"How many watts does the human brain consume?",a:20,unit:"watts",hint:"Like an energy-saving light bulb.",emoji:"💡"},
  {id:"wiss_058",q:"In what year did Harvey discover blood circulation?",a:1628,unit:"year",hint:"William Harvey published it in 1628.",emoji:"❤️"},
  {id:"wiss_059",q:"How many protons does copper have?",a:29,unit:"protons",hint:"Cu – atomic number 29.",emoji:"⚗️"},
  {id:"wiss_060",q:"In what year was the first telescope pointed at the sky?",a:1609,unit:"year",hint:"Galileo pointed it at the Moon.",emoji:"🌙"},
  {id:"wiss_061",q:"How many degrees Celsius does steel melt at?",a:1370,unit:"°C",hint:"Depending on the alloy, 1370-1520°C.",emoji:"🌡️"},
  {id:"wiss_062",q:"How many chromosomes does a banana cell have?",a:22,unit:"chromosomes",hint:"Bananas have 11 pairs of chromosomes.",emoji:"🍌"},
  {id:"wiss_063",q:"In what year did Newton describe the three laws of motion?",a:1687,unit:"year",hint:"In 'Principia Mathematica'.",emoji:"🍎"},
  {id:"wiss_064",q:"How many volts does a standard AA battery have?",a:1.5,unit:"volts",hint:"The small finger-sized battery has 1.5V.",emoji:"🔋"},
  {id:"wiss_065",q:"In what year did Bohr discover the atomic model?",a:1913,unit:"year",hint:"Niels Bohr's atomic model for hydrogen.",emoji:"⚛️"},
  {id:"wiss_066",q:"How many mg of caffeine does a cup of espresso have?",a:80,unit:"mg",hint:"A cup of coffee has 60-100 mg.",emoji:"☕"},
  {id:"wiss_067",q:"In what year did Turing invent the theoretical concept of the universal machine?",a:1936,unit:"year",hint:"The Turing machine – the basis of all computers.",emoji:"💻"},
  {id:"wiss_068",q:"How many grams of oxygen are needed to burn 1g of hydrogen?",a:8,unit:"grams",hint:"H₂ + O → H₂O – mass ratio 1:8.",emoji:"⚗️"},
  {id:"wiss_069",q:"In what year was the TCP/IP internet protocol developed?",a:1974,unit:"year",hint:"Vint Cerf and Bob Kahn developed it.",emoji:"🌐"},
  {id:"wiss_070",q:"How many tons of nuclear waste does a nuclear power plant produce per year?",a:30,unit:"tons",hint:"Highly radioactive waste – a problem for millennia.",emoji:"☢️"},
  {id:"wiss_071",q:"In what year did Semmelweis discover the importance of hand washing?",a:1847,unit:"year",hint:"He died without recognition – celebrated today.",emoji:"🧼"},
  {id:"wiss_072",q:"How many protons does lead have?",a:82,unit:"protons",hint:"Pb – atomic number 82.",emoji:"⚗️"},
  {id:"wiss_073",q:"In what year was the first GPS system activated?",a:1995,unit:"year",hint:"Fully operational since 1995.",emoji:"🛰️"},
  {id:"wiss_074",q:"How many atoms are in a water molecule?",a:3,unit:"atoms",hint:"H₂O – 2 hydrogen + 1 oxygen.",emoji:"💧"},
  {id:"wiss_075",q:"In what year did Pasteur invent pasteurization?",a:1864,unit:"year",hint:"For wine – then applied to milk.",emoji:"🍷"},
  {id:"wiss_076",q:"How many volts does a solar cell generate?",a:0.5,unit:"volts",hint:"A single cell – many are connected in series.",emoji:"☀️"},
  {id:"wiss_077",q:"In what year did Dalton discover the atomic model?",a:1803,unit:"year",hint:"John Dalton's first atomic theory.",emoji:"⚛️"},
  {id:"wiss_078",q:"How many centimeters is a meter?",a:100,unit:"cm",hint:"The definition of the metric system.",emoji:"📏"},
  {id:"wiss_079",q:"In what year did Otto invent the four-stroke engine?",a:1876,unit:"year",hint:"Nikolaus Otto – the basis of all modern cars.",emoji:"🚗"},
  {id:"wiss_080",q:"How many protons does silver have?",a:47,unit:"protons",hint:"Ag – atomic number 47.",emoji:"🪙"},
  {id:"wiss_081",q:"In what year did Hertz discover electromagnetic waves?",a:1887,unit:"year",hint:"Heinrich Hertz – the unit is named after him.",emoji:"📡"},
  {id:"wiss_082",q:"How many kilograms does a liter of gasoline weigh?",a:0.74,unit:"kg",hint:"Gasoline is lighter than water.",emoji:"⛽"},
  {id:"wiss_083",q:"In what year did Bayer invent aspirin?",a:1897,unit:"year",hint:"Felix Hoffmann synthesized it in 1897.",emoji:"💊"},
  {id:"wiss_084",q:"How many volts does a car battery have?",a:12,unit:"volts",hint:"Standard 12V lead-acid battery.",emoji:"🔋"},
  {id:"wiss_085",q:"How many megapixels did the first iPhone camera have?",a:2,unit:"megapixels",hint:"2007 – today's iPhones have over 48 MP.",emoji:"📱"},
  {id:"wiss_086",q:"In what year was the first smartphone (IBM Simon) invented?",a:1994,unit:"year",hint:"The IBM Simon was the first touchscreen phone.",emoji:"📱"},
  {id:"wiss_087",q:"How many degrees Celsius does butter melt at?",a:32,unit:"°C",hint:"Depending on composition, 28-36°C.",emoji:"🧈"},
  {id:"wiss_088",q:"In what year did Benz invent the first gasoline-powered car?",a:1885,unit:"year",hint:"The Benz Patent-Motorwagen – 3 wheels, 0.75 hp.",emoji:"🚗"},
  {id:"wiss_089",q:"How many grams does a mole of water weigh?",a:18,unit:"grams",hint:"H₂O: 2×1 + 16 = 18 g/mol.",emoji:"💧"},
  {id:"wiss_090",q:"In what year was CRISPR-Cas9 discovered?",a:2012,unit:"year",hint:"Charpentier and Doudna – Nobel Prize 2020.",emoji:"🧬"},
  {id:"wiss_091",q:"How many billion bits does 1 gigabyte have?",a:8.6,unit:"billion bits",hint:"1 GB = 8×1024×1024×1024 bits ≈ 8.6 billion bits.",emoji:"💻"},
  {id:"wiss_092",q:"In what year did Fleming invent the first vacuum tube (diode)?",a:1904,unit:"year",hint:"John Ambrose Fleming invented the vacuum diode – a precursor to the transistor.",emoji:"⚡"},
  {id:"wiss_093",q:"How many degrees Celsius does seawater freeze at?",a:-1.8,unit:"°C",hint:"Saltwater freezes at lower temperatures.",emoji:"🌊"},
  {id:"wiss_094",q:"In what year did Jenner discover the smallpox vaccine?",a:1796,unit:"year",hint:"The first vaccine in history.",emoji:"💉"},
  {id:"wiss_095",q:"How many protons does nitrogen have?",a:7,unit:"protons",hint:"N – atomic number 7.",emoji:"⚗️"},
  {id:"wiss_096",q:"In what year did Shockley invent the transistor?",a:1947,unit:"year",hint:"Bell Labs – the basis of all modern electronics.",emoji:"⚡"},
  {id:"wiss_097",q:"How many tesla does a strong MRI scanner have?",a:3,unit:"tesla",hint:"Tesla is the standard unit in hospitals.",emoji:"🧲"},
  {id:"wiss_098",q:"In what year did Mendeleev discover the periodic table?",a:1869,unit:"year",hint:"He predicted elements that hadn't been discovered yet.",emoji:"⚗️"},
  {id:"wiss_099",q:"How many degrees Celsius does distilled water boil at?",a:100,unit:"°C",hint:"At standard pressure, 1 atmosphere.",emoji:"🌡️"},
  {id:"wiss_100",q:"In what year did Zeppelin invent the airship?",a:1900,unit:"year",hint:"The first test flight of the LZ 1 was on July 2, 1900.",emoji:"🛸"},
  {id:"wiss_101",q:"How many grams does a mole of sodium chloride (table salt) weigh?",a:58.4,unit:"grams",hint:"Na(23) + Cl(35.5) = 58.5 g/mol.",emoji:"🧂"},
  {id:"wiss_102",q:"In what year was the first black hole photographed?",a:2019,unit:"year",hint:"The Event Horizon Telescope – M87*.",emoji:"🌑"},
  {id:"wiss_103",q:"How many nanometers is 1 micrometer?",a:1000,unit:"nanometers",hint:"1 µm = 1000 nm.",emoji:"📏"},
  {id:"wiss_104",q:"In what year did Boyle discover the gas law?",a:1662,unit:"year",hint:"Boyle's Law: pV = constant.",emoji:"⚗️"},
  {id:"wiss_105",q:"How many amps flow through a 100W light bulb (230V)?",a:0.43,unit:"amps",hint:"I = P/U = 100/230 ≈ 0.43A.",emoji:"💡"},
  {id:"wiss_106",q:"In what year did Tesla invent the AC motor?",a:1887,unit:"year",hint:"The basis of all modern electric motors.",emoji:"⚡"},
  {id:"wiss_107",q:"How many million tons of CO₂ does the world emit daily?",a:100,unit:"million tons",hint:"37 billion tons per year.",emoji:"🌍"},
  {id:"wiss_108",q:"In what year did Hooke discover the cell?",a:1665,unit:"year",hint:"Robert Hooke looked at cork under a microscope.",emoji:"🔬"},
  {id:"wiss_109",q:"How many protons does phosphorus have?",a:15,unit:"protons",hint:"P – atomic number 15.",emoji:"⚗️"},
  {id:"wiss_110",q:"In what year was the first nuclear power plant built?",a:1954,unit:"year",hint:"Obninsk in the Soviet Union.",emoji:"⚡"},
  {id:"wiss_111",q:"How many atoms does a glucose molecule have?",a:24,unit:"atoms",hint:"C₆H₁₂O₆ = 6+12+6 = 24 atoms.",emoji:"⚗️"},
  {id:"wiss_112",q:"In what year did Siemens invent the electric elevator?",a:1880,unit:"year",hint:"Werner von Siemens, in Mannheim.",emoji:"🏗️"},
  {id:"wiss_113",q:"How many degrees Celsius does glass melt at?",a:700,unit:"°C",hint:"Depending on composition, 700-1200°C.",emoji:"🌡️"},
  {id:"wiss_114",q:"In what year did Galvani discover 'animal electricity'?",a:1780,unit:"year",hint:"The basis of electrochemistry and batteries.",emoji:"⚡"},
  {id:"wiss_115",q:"How many grams does 1 liter of air weigh?",a:1.3,unit:"g",hint:"1.29 grams per liter at 20°C.",emoji:"💨"},
  {id:"wiss_116",q:"In what year did Swan invent the carbon filament lamp?",a:1878,unit:"year",hint:"Joseph Swan – shortly before Edison.",emoji:"💡"},
  {id:"wiss_117",q:"How many chromosomes does a fruit fly have?",a:8,unit:"chromosomes",hint:"Drosophila – the most important model organism.",emoji:"🪰"},
  {id:"wiss_118",q:"In what year did Kepler describe planetary motion?",a:1609,unit:"year",hint:"Kepler's first and second laws.",emoji:"🪐"},
  {id:"wiss_119",q:"How many degrees does a polarizing filter rotate light?",a:90,unit:"degrees",hint:"Two crossed polarizing filters block all light.",emoji:"💡"},
  {id:"wiss_120",q:"In what year did Halley discover the comet named after him?",a:1705,unit:"year",hint:"He predicted its return – and he was right.",emoji:"☄️"},
  {id:"wiss_121",q:"How many billion base pairs does the human genome have?",a:3,unit:"billion base pairs",hint:"3 billion base pairs in human DNA.",emoji:"🧬"},
  {id:"wiss_122",q:"In what year was the first electric car produced?",a:1884,unit:"year",hint:"Thomas Parker built it in London.",emoji:"🚗"},
  {id:"wiss_123",q:"How many volts does a fuel cell generate?",a:1.2,unit:"volts",hint:"Depending on the type, 0.5-1.2V per cell.",emoji:"⚡"},
  {id:"wiss_124",q:"In what year did Braille invent the braille writing system?",a:1824,unit:"year",hint:"Louis Braille was 15 years old.",emoji:"👆"},
  {id:"wiss_125",q:"How many protons does calcium have?",a:20,unit:"protons",hint:"Ca – atomic number 20.",emoji:"⚗️"},
  {id:"wiss_126",q:"In what year did Voyager 1 launch?",a:1977,unit:"year",hint:"On September 5, 1977 – now outside the solar system.",emoji:"🚀"},
  {id:"wiss_127",q:"How many m/s² is the gravitational acceleration on the Moon?",a:1.62,unit:"m/s²",hint:"1/6 of Earth's gravity.",emoji:"🌙"},
  {id:"wiss_128",q:"In what year did Hubble discover that Andromeda is its own galaxy?",a:1925,unit:"year",hint:"Before that, it was thought to be a nebula.",emoji:"🌌"},
  {id:"wiss_129",q:"How many neutrons does carbon-14 have?",a:8,unit:"neutrons",hint:"6 protons + 8 neutrons = mass 14.",emoji:"⚗️"},
  {id:"wiss_130",q:"In what year did Otis invent the safety elevator?",a:1852,unit:"year",hint:"Elisha Otis – a brake prevented falls.",emoji:"🏗️"},
  {id:"wiss_131",q:"How many cycles per second does European AC power have?",a:50,unit:"Hz",hint:"In Europe, 50Hz is standard.",emoji:"⚡"},
  {id:"wiss_132",q:"In what year was the first transistor radio sold?",a:1954,unit:"year",hint:"The Texas Instruments TR-1.",emoji:"📻"},
  {id:"wiss_133",q:"How many degrees Celsius does copper melt at?",a:1085,unit:"°C",hint:"A lower melting point than iron.",emoji:"🌡️"},
  {id:"wiss_134",q:"In what year did Dalton discover the law of multiple proportions?",a:1803,unit:"year",hint:"The basis of modern chemistry.",emoji:"⚗️"},
  {id:"wiss_135",q:"How many nanometers in size is a hydrogen atom?",a:0.1,unit:"nanometers",hint:"0.1 nm = 1 angstrom.",emoji:"⚛️"},
  {id:"wiss_136",q:"In what year did Volta invent the battery?",a:1800,unit:"year",hint:"The voltaic pile – the first battery.",emoji:"🔋"},
  {id:"wiss_137",q:"How many protons does sodium have?",a:11,unit:"protons",hint:"Na – atomic number 11.",emoji:"⚗️"},
  {id:"wiss_138",q:"In what year did the first Sputnik launch?",a:1957,unit:"year",hint:"On October 4, 1957.",emoji:"🛰️"},
  {id:"wiss_139",q:"How many kilowatts is 1 horsepower?",a:0.736,unit:"kW",hint:"1 hp = 0.736 kW = 736 watts.",emoji:"⚡"},
  {id:"wiss_140",q:"In what year did Bohr develop his atomic model for hydrogen?",a:1913,unit:"year",hint:"Niels Bohr's atomic model explained hydrogen's spectral lines.",emoji:"⚛️"},
  {id:"wiss_141",q:"How many atoms does a methane molecule have?",a:5,unit:"atoms",hint:"CH₄ = 1 carbon + 4 hydrogen.",emoji:"⚗️"},
  {id:"wiss_142",q:"In what year did Morse invent his famous code?",a:1838,unit:"year",hint:"Dots and dashes – a revolutionary form of communication.",emoji:"📡"},
  {id:"wiss_143",q:"How many degrees Fahrenheit is the body at fever?",a:101,unit:"°F",hint:"38°C = 100.4°F – fever begins.",emoji:"🌡️"},
  {id:"wiss_144",q:"In what year did Mendel discover the laws of inheritance?",a:1865,unit:"year",hint:"Gregor Mendel's pea plant experiments.",emoji:"🌱"},
  {id:"wiss_145",q:"How many protons does chlorine have?",a:17,unit:"protons",hint:"Cl – atomic number 17.",emoji:"⚗️"},
  {id:"wiss_146",q:"In what year was the first iPhone released?",a:2007,unit:"year",hint:"Steve Jobs: 'One more thing...'",emoji:"📱"},
  {id:"wiss_147",q:"How many megawatts does an average nuclear power plant generate?",a:1000,unit:"megawatts",hint:"1 GW – enough for a city of a million people.",emoji:"⚡"},
  {id:"wiss_148",q:"In what year did Zuckerberg invent Facebook?",a:2004,unit:"year",hint:"As a Harvard student.",emoji:"📱"},
  {id:"wiss_149",q:"How many grams of glucose does the brain need daily as a minimum?",a:120,unit:"grams",hint:"120g daily – for thinking processes.",emoji:"🧠"},
  {id:"wiss_150",q:"In what year was the first GPS satellite launched?",a:1978,unit:"year",hint:"The Block I GPS satellite.",emoji:"🛰️"},
  {id:"wiss_151",q:"How many degrees Celsius is room temperature?",a:20,unit:"°C",hint:"18-22°C is standard.",emoji:"🌡️"},
  {id:"wiss_152",q:"In what year did Koch discover the tuberculosis pathogen?",a:1882,unit:"year",hint:"Robert Koch, on March 24, 1882.",emoji:"🔬"},
  {id:"wiss_153",q:"How many protons does aluminum have?",a:13,unit:"protons",hint:"Al – atomic number 13.",emoji:"⚗️"},
  {id:"wiss_154",q:"In what year did Braun invent the television (Braun tube)?",a:1897,unit:"year",hint:"Karl Ferdinand Braun.",emoji:"📺"},
  {id:"wiss_155",q:"How many kilocalories does 1 gram of protein have?",a:4,unit:"kcal/g",hint:"The same as carbohydrates.",emoji:"💪"},
  {id:"wiss_156",q:"In what year did Planck discover quantum theory?",a:1900,unit:"year",hint:"Planck's constant, h.",emoji:"⚛️"},
  {id:"wiss_157",q:"In what year was the first electromagnet built?",a:1825,unit:"year",hint:"William Sturgeon built it.",emoji:"🧲"},
  {id:"wiss_158",q:"In what year did Becquerel discover radioactivity?",a:1896,unit:"year",hint:"Henri Becquerel – discovered by accident while developing photos.",emoji:"☢️"},
  {id:"wiss_159",q:"How many protons does magnesium have?",a:12,unit:"protons",hint:"Mg – atomic number 12.",emoji:"⚗️"},
  {id:"wiss_160",q:"In what year did the Wright Brothers build the first powered airplane?",a:1903,unit:"year",hint:"12 seconds – 37 meters – the world changed.",emoji:"✈️"},
  {id:"wiss_161",q:"How many hertz does human speech average?",a:250,unit:"Hz",hint:"The fundamental frequency of the human voice.",emoji:"🎤"},
  {id:"wiss_162",q:"In what year was chlorine identified as an element?",a:1774,unit:"year",hint:"Karl Wilhelm Scheele discovered it.",emoji:"⚗️"},
  {id:"wiss_163",q:"How many kilowatt-hours of energy does a wind turbine produce per day?",a:10000,unit:"kWh/day",hint:"A 2-MW wind turbine generates 10,000-15,000 kWh daily.",emoji:"🌬️"},
  {id:"wiss_164",q:"How many degrees Celsius is the temperature at Earth's core?",a:6000,unit:"°C",hint:"Similar to the Sun's surface.",emoji:"🌋"},
  {id:"wiss_165",q:"In what year did Ampère discover the law of electric current?",a:1820,unit:"year",hint:"André-Marie Ampère – the unit is named after him.",emoji:"⚡"},
  {id:"wiss_166",q:"How many billion transistors does a modern CPU chip have (e.g. Apple M3)?",a:25,unit:"billion",hint:"Apple M3 (2023): 25 billion – top models have even more.",emoji:"💻"},
  {id:"wiss_167",q:"In what year was the first AI program written?",a:1951,unit:"year",hint:"Logic Theorist, by Newell and Simon.",emoji:"🤖"},
  {id:"wiss_168",q:"How many grams does 1 mole of carbon dioxide weigh?",a:44,unit:"grams",hint:"C(12) + 2×O(16) = 44 g/mol.",emoji:"⚗️"},
  {id:"wiss_169",q:"How many kilojoules is 1 kilocalorie?",a:4.18,unit:"kJ",hint:"1 kcal = 4.18 kJ.",emoji:"🔥"},
  {id:"wiss_170",q:"In what year did Einstein's general theory of relativity come out?",a:1915,unit:"year",hint:"An extension of the special theory.",emoji:"⚛️"},
  {id:"wiss_171",q:"How many electrons does the first electron shell of an atom hold?",a:2,unit:"electrons",hint:"The K shell – maximum 2 electrons.",emoji:"⚛️"},
  {id:"wiss_172",q:"In what year was the first microchip invented?",a:1958,unit:"year",hint:"Jack Kilby at Texas Instruments.",emoji:"💻"},
  {id:"wiss_173",q:"How many kilopascals is air pressure at sea level?",a:101.3,unit:"kPa",hint:"1 atmosphere = 101,325 Pa.",emoji:"🌬️"},
  {id:"wiss_174",q:"In what year did Maxwell theoretically discover electromagnetic waves?",a:1864,unit:"year",hint:"James Clerk Maxwell – Hertz proved it in 1887.",emoji:"📡"},
  {id:"wiss_175",q:"In what year was the Hubble Space Telescope launched?",a:1990,unit:"year",hint:"On April 24, 1990, aboard Discovery.",emoji:"🔭"},
  {id:"wiss_176",q:"How many protons does silicon have?",a:14,unit:"protons",hint:"Si – atomic number 14 – the basis of semiconductors.",emoji:"💻"},
  {id:"wiss_177",q:"In what year did Marie Curie discover polonium?",a:1898,unit:"year",hint:"Named after her home country, Poland.",emoji:"☢️"},
  {id:"wiss_178",q:"How many joules is 1 calorie?",a:4.184,unit:"joules",hint:"1 cal = 4.184 J.",emoji:"🔥"},
  {id:"wiss_179",q:"In what year was the first barcode used?",a:1974,unit:"year",hint:"On June 26, 1974 – a pack of Wrigley's gum in Ohio.",emoji:"📊"},
  {id:"wiss_180",q:"How many protons does sulfur have?",a:16,unit:"protons",hint:"S – atomic number 16.",emoji:"⚗️"},
  {id:"wiss_181",q:"In what year was the first color photo taken?",a:1861,unit:"year",hint:"James Clerk Maxwell – a tartan ribbon.",emoji:"📷"},
  {id:"wiss_182",q:"How many amps can a household outlet carry at maximum?",a:16,unit:"amps",hint:"Standard 230V/16A in Germany.",emoji:"⚡"},
  {id:"wiss_183",q:"In what year did Ohm discover Ohm's law?",a:1827,unit:"year",hint:"Georg Simon Ohm: U = R × I.",emoji:"⚡"},
  {id:"wiss_184",q:"How many months does it take for the body to renew all its cells?",a:84,unit:"months",hint:"7 years – some cells last a lifetime.",emoji:"🔄"},
  {id:"wiss_185",q:"In what year did Zeiss invent the first apochromatic lens?",a:1886,unit:"year",hint:"The basis of modern microscopy.",emoji:"🔬"},
  {id:"wiss_186",q:"How many kilograms of oxygen does a human breathe daily?",a:0.55,unit:"kg",hint:"550 grams of oxygen daily.",emoji:"💨"},
  {id:"wiss_187",q:"In what year did Haber discover ammonia synthesis?",a:1909,unit:"year",hint:"Fritz Haber – the basis of fertilizer production.",emoji:"⚗️"},
  {id:"wiss_188",q:"How many protons does zinc have?",a:30,unit:"protons",hint:"Zn – atomic number 30.",emoji:"⚗️"},
  {id:"wiss_189",q:"How many electrons does the second shell of an atom hold?",a:8,unit:"electrons",hint:"The L shell – maximum 8 electrons.",emoji:"⚛️"},
  {id:"wiss_190",q:"In what year did Schottky invent the tube diode?",a:1914,unit:"year",hint:"The basis of radio technology.",emoji:"📡"},
  {id:"wiss_191",q:"How many kilometers per hour is the speed of sound in air?",a:1235,unit:"km/h",hint:"343 m/s = 1,235 km/h.",emoji:"🔊"},
  {id:"wiss_192",q:"In what year did Lavoisier discover the law of conservation of mass?",a:1789,unit:"year",hint:"Antoine Lavoisier – the father of modern chemistry.",emoji:"⚗️"},
  {id:"wiss_193",q:"How many protons does titanium have?",a:22,unit:"protons",hint:"Ti – atomic number 22.",emoji:"⚗️"},
  {id:"wiss_194",q:"In what year did Hawking's 'A Brief History of Time' come out?",a:1988,unit:"year",hint:"Sold millions of copies – physics made accessible to everyone.",emoji:"📚"},
  {id:"wiss_195",q:"How many degrees Celsius is the temperature in Earth's mantle?",a:3000,unit:"°C",hint:"Between the Earth's crust and core.",emoji:"🌋"},
  {id:"wiss_196",q:"How many kilobytes is 1 megabyte?",a:1024,unit:"kilobytes",hint:"Binary system – 2¹⁰ = 1024.",emoji:"💻"},
  {id:"wiss_197",q:"In what year was the first MRI machine built?",a:1977,unit:"year",hint:"The first full-body MRI, by Damadian.",emoji:"🏥"},
  {id:"wiss_198",q:"How many seconds does a day have?",a:86400,unit:"seconds",hint:"24 × 60 × 60 = 86,400.",emoji:"⏰"},
  {id:"wiss_199",q:"In what year did Banting invent insulin?",a:1921,unit:"year",hint:"Frederick Banting saved millions of diabetics.",emoji:"💉"},
  {id:"wiss_200",q:"How many protons does manganese have?",a:25,unit:"protons",hint:"Mn – atomic number 25.",emoji:"⚗️"},
  {id:"wiss_201",q:"How many million degrees Celsius is the Sun's core temperature?",a:15,unit:"million °C",hint:"15 million degrees – nuclear fusion happens there.",emoji:"☀️"},
  {id:"wiss_202",q:"In what year was the electron discovered?",a:1897,unit:"year",hint:"J.J. Thomson, during the cathode ray experiment.",emoji:"⚛️"},
  {id:"wiss_203",q:"How many electrons does the third electron shell hold?",a:18,unit:"electrons",hint:"The M shell – maximum 18 electrons.",emoji:"⚛️"},
  {id:"wiss_204",q:"In what year was the first HIV virus isolated?",a:1983,unit:"year",hint:"Françoise Barré-Sinoussi – Nobel Prize 2008.",emoji:"🔬"},
  {id:"wiss_205",q:"How many protons does gold have (atomic number)?",a:79,unit:"protons",hint:"Au – atomic number 79.",emoji:"🪙"},
  {id:"wiss_206",q:"In what year did Shannon invent information theory?",a:1948,unit:"year",hint:"Claude Shannon – the basis of digital communication.",emoji:"💻"},
  {id:"wiss_207",q:"How many kilowatt-hours does 1 kg of hydrogen contain?",a:33,unit:"kWh",hint:"Three times more than gasoline per kg.",emoji:"⚡"},
  {id:"wiss_208",q:"In what year was the first solar cell developed?",a:1954,unit:"year",hint:"Bell Labs – 6% efficiency.",emoji:"☀️"},
  {id:"wiss_209",q:"How many protons does bromine have?",a:35,unit:"protons",hint:"Br – atomic number 35.",emoji:"⚗️"},
  {id:"wiss_210",q:"In what year did Celsius discover the Celsius scale?",a:1742,unit:"year",hint:"Anders Celsius – originally inverted.",emoji:"🌡️"},
  {id:"wiss_211",q:"How many nanometers in size is an atom?",a:0.1,unit:"nanometers",hint:"0.1-0.5 nm, depending on the element.",emoji:"⚛️"},
  {id:"wiss_212",q:"In what year did Karl Ferdinand Braun receive the patent for the cathode ray tube?",a:1897,unit:"year",hint:"Braun received the Nobel Prize in Physics in 1909, together with Marconi.",emoji:"⚡"},
  {id:"wiss_213",q:"How many tons of CO₂ does a hectare of forest store per year?",a:2,unit:"tons",hint:"An average Central European mixed forest.",emoji:"🌳"},
  {id:"wiss_214",q:"In what year did Hardy discover the Hardy-Weinberg equation?",a:1908,unit:"year",hint:"The basis of population genetics.",emoji:"🧬"},
  {id:"wiss_215",q:"How many protons does nickel have?",a:28,unit:"protons",hint:"Ni – atomic number 28.",emoji:"⚗️"},
  {id:"wiss_216",q:"In what year did Daimler build the first motorcycle?",a:1885,unit:"year",hint:"Gottlieb Daimler – the Reitwagen.",emoji:"🏍️"},
  {id:"wiss_217",q:"How many atoms does a sulfuric acid molecule (H₂SO₄) have?",a:7,unit:"atoms",hint:"2H + S + 4O = 7 atoms.",emoji:"⚗️"},
  {id:"wiss_218",q:"In what year did the first chemistry textbook appear?",a:1789,unit:"year",hint:"Lavoisier's Traité élémentaire de chimie.",emoji:"📚"},
  {id:"wiss_219",q:"How many degrees Celsius does aluminum melt at?",a:660,unit:"°C",hint:"A significantly lower melting point than steel.",emoji:"🌡️"},
  {id:"wiss_220",q:"How many trillion tons of oxygen does the Earth's atmosphere contain?",a:1200,unit:"trillion tons",hint:"1.2 × 10¹⁵ kg of oxygen.",emoji:"💨"},
  {id:"wiss_221",q:"In what year did Rutherford discover the atomic nucleus?",a:1909,unit:"year",hint:"The gold foil experiment – the nucleus is small and dense.",emoji:"⚛️"},
  {id:"wiss_222",q:"How many protons does cobalt have?",a:27,unit:"protons",hint:"Co – atomic number 27.",emoji:"⚗️"},
  {id:"wiss_223",q:"In what year did Pascal invent the Pascaline calculating machine?",a:1642,unit:"year",hint:"It could add and subtract.",emoji:"🔢"},
  {id:"wiss_224",q:"How many lumens does a standard 60-watt light bulb produce?",a:800,unit:"lumens",hint:"An LED bulb only needs 8-10 watts for the same output.",emoji:"💡"},
  {id:"wiss_225",q:"In what year did Dirac theoretically discover antimatter?",a:1928,unit:"year",hint:"Paul Dirac predicted positrons.",emoji:"⚛️"},
  {id:"wiss_226",q:"How many grams does 1 mole of calcium carbonate (limestone) weigh?",a:100,unit:"grams",hint:"CaCO₃ = 40+12+(3×16) = 100 g/mol.",emoji:"⚗️"},
  {id:"wiss_227",q:"In what year did Tesla invent the wireless energy transmission principle?",a:1891,unit:"year",hint:"The Wardenclyffe Tower was his failed project.",emoji:"⚡"},
  {id:"wiss_228",q:"How many kilojoules does 1 gram of fat have?",a:37,unit:"kJ",hint:"1g of fat = 9 kcal = 37 kJ.",emoji:"🔥"},
  {id:"wiss_229",q:"In what year did Newton's Opticks come out?",a:1704,unit:"year",hint:"About light, prisms, and colors.",emoji:"🌈"},
  {id:"wiss_230",q:"How many protons does vanadium have?",a:23,unit:"protons",hint:"V – atomic number 23.",emoji:"⚗️"},
  {id:"wiss_231",q:"In what year did Geiger invent the Geiger counter?",a:1908,unit:"year",hint:"Hans Geiger – for measuring ionizing radiation.",emoji:"☢️"},
  {id:"wiss_232",q:"How many grams does 1 mole of methane weigh?",a:16,unit:"grams",hint:"CH₄ = 12+4 = 16 g/mol.",emoji:"⚗️"},
  {id:"wiss_233",q:"In what year did Heisenberg discover the uncertainty principle?",a:1927,unit:"year",hint:"Position and momentum can't be measured simultaneously.",emoji:"⚛️"},
  {id:"wiss_234",q:"How many electrons does the fourth shell hold?",a:32,unit:"electrons",hint:"The N shell – maximum 32 electrons.",emoji:"⚛️"},
  {id:"wiss_235",q:"In what year did Compton discover the Compton effect?",a:1923,unit:"year",hint:"Light behaves like a particle.",emoji:"⚛️"},
  {id:"wiss_236",q:"How many meters per hour do electrons move in a wire?",a:0.3,unit:"m/h",hint:"Only 0.3m/h – but the electromagnetic wave propagates at the speed of light.",emoji:"⚡"}
];
