// 🐾 ANIMAL KINGDOM – English
export default [
  {q:"How many kg do die testicles eines Blauwhales?",a:70,unit:"kg",hint:"Der Blauwhale is the largest animal Earth.",emoji:"🐋"},
  {q:"How often per minute schlägt das heart of a mouse?",a:600,unit:"times",hint:"Je kleiner das animal, desto schneller das heart.",emoji:"🐭"},
  {q:"How many days carries an elephant its young?",a:645,unit:"days",hint:"Fast 2 years – längste Schwangerschaft aller Landsäugetiere.",emoji:"🐘"},
  {q:"How many liters Milch produces a Kuh per day?",a:25,unit:"literss",hint:"Hochleisungskühe können bis to 50 liters daily geben.",emoji:"🐄"},
  {q:"How heavy can a Riesenkalmar-Auge in grams are?",a:250,unit:"grams",hint:"the largest Auge im Tierreich – so groß wie a Fußball.",emoji:"🦑"},
  {q:"How many km/h runs a cheetah maxitimes?",a:112,unit:"km/h",hint:"Er can diese Höchstgeschwindigkeit nur kurz halten.",emoji:"🐆"},
  {q:"How many Magen has a Kuh?",a:4,unit:"Mägen",hint:"Pansen, Netzmagen, Blättermagen und Labmagen.",emoji:"🐄"},
  {q:"How high can a kangaroo jump in meters?",a:3,unit:"meterss",hint:"Und in der Länge sogar bis to 9 meters weit.",emoji:"🦘"},
  {q:"How heavy is a fully grown Gorilla maxitimes in kg?",a:270,unit:"kg",hint:"Trotz Größe are Gorillas überwiegend Vegetarier.",emoji:"🦍"},
  {q:"How many hours sleeps a Koala per day?",a:22,unit:"hours",hint:"Eukalyptus is schwer verdaulich – daher die Müdigkeit.",emoji:"🐨"},
  {q:"How many km/h can a Schwertfisch swim?",a:110,unit:"km/h",hint:"the fastest fish im sea.",emoji:"🐟"},
  {q:"How long lives a Königin-Biene in yearsn?",a:5,unit:"years",hint:"Arbeiterinnen live im Sommer nur 6 weeks.",emoji:"🐝"},
  {q:"How many teeth has a erwachsenes Krokodil?",a:66,unit:"teeth",hint:"Krokodile erneuern ihre teeth bis to 50 times im live.",emoji:"🐊"},
  {q:"How many Eier legt a Königin-Termite per day?",a:30000,unit:"Eier",hint:"Die produktivste Mutter im Insektenreich.",emoji:"🐜"},
  {q:"How many liters blood has a fully grown elephant?",a:400,unit:"literss",hint:"Das elephantenheart weighs allein bis to 30 kg.",emoji:"🐘"},
  {q:"How many times can a Specht pro Sekunde hämmern?",a:20,unit:"times",hint:"Sein brain is through Spezialanpassungen geschützt.",emoji:"🐦"},
  {q:"How heavy is das schwerste Vogelei (Strauß) in kg?",a:1.35,unit:"kg",hint:"Strauße legen the largestn Eier aller lebenden birds.",emoji:"🥚"},
  {q:"How long can a Delphin den Atem anhalten in minutes?",a:15,unit:"minutes",hint:"dolphine schlafen with einer brainhälfte.",emoji:"🐬"},
  {q:"How many years can a Grönlandwhale live?",a:211,unit:"years",hint:"Das langlebigste Säugetier Earth.",emoji:"🐳"},
  {q:"How heavy is die Zunge eines Blauwhales in kg?",a:2700,unit:"kg",hint:"Die Zunge allein weighs so viel wie an elephant.",emoji:"🐋"},
  {q:"How many million Geruchsrezeptoren has a dog?",a:300,unit:"million",hint:"people have nur 6 million – doge riechen 50x besser.",emoji:"🐕"},
  {q:"How many meters lang can a Bandwurm im Darm are?",a:25,unit:"meterss",hint:"Bandwürmer können yearslang unbemerkt live.",emoji:"🪱"},
  {q:"How high is der Blutdruck einer Giraffe in mmHg?",a:280,unit:"mmHg",hint:"Nötig um blood 2 meters to oben ins brain to pumpen.",emoji:"🦒"},
  {q:"How many kg Bambus eats a Pandabear daily?",a:15,unit:"kg",hint:"Bambus is sehr nährstoffarm – daher die riesige Menge.",emoji:"🐼"},
  {q:"How long carries a shark seine Jungen in monthsn?",a:24,unit:"months",hint:"Hammerhaie have the longest Tragzeit.",emoji:"🦈"},
  {q:"How many Augen has a spider?",a:8,unit:"Augen",hint:"Trotz 8 Augen sehen viele spidern sehr schlecht.",emoji:"🕷️"},
  {q:"How many km/h erreicht a Wanderfalke im Sturzflug?",a:320,unit:"km/h",hint:"Das schnellste animal the world im Sturzflug.",emoji:"🦅"},
  {q:"How many tons weighs a fully grown Blauwhale?",a:150,unit:"tons",hint:"the largest animal das je on Earth gelives has.",emoji:"🐋"},
  {q:"How many hours can a Schnecke schlafen am Stück?",a:3,unit:"years",hint:"Schnecken können bis to 3 years in Kältestarre verbringen.",emoji:"🐌"},
  {q:"How many Elektronen-Volt erzeugt a Zitteraal?",a:600,unit:"Volt",hint:"Volt – genug um einen people to betäuben.",emoji:"🐍"},
  {q:"How many km/h rennt a Nashorn?",a:55,unit:"km/h",hint:"Trotz ihrer Masse are Nashörner erstaunlich schnell.",emoji:"🦏"},
  {q:"How many years alt can a Koi-fish are?",a:226,unit:"years",hint:"Hanako, ein Koi in Japan, livese 226 years.",emoji:"🐟"},
  {q:"How many bones has a Schlange?",a:300,unit:"bones",hint:"Je to Art between 200 und 400 bones.",emoji:"🐍"},
  {q:"How many times pro Sekunde schlägt a Biene ihre wings?",a:200,unit:"times",hint:"Das erzeugt das charakterisische Summen.",emoji:"🐝"},
  {q:"How many liters water saugt an elephant daily?",a:190,unit:"literss",hint:"Der Rüssel fasst bis to 15 liters on eintimes.",emoji:"🐘"},
  {q:"How many years can a Schildkröte ohne Nahrung überleben?",a:1,unit:"Jahr",hint:"Schildkröten können ihren Stoffwechsel extrem verlangsamen.",emoji:"🐢"},
  {q:"How far can a Flugfisch from dem water gleiten in meters?",a:400,unit:"meterss",hint:"Flugfische nutzen Wind und Auftrieb zum Gleiten.",emoji:"🐟"},
  {q:"How many grams weighs das heart eines Blauwhales?",a:180000,unit:"grams",hint:"Das heart is so groß wie a kleines Auto.",emoji:"❤️"},
  {q:"How many hours sleeps a lion per day?",a:20,unit:"hours",hint:"lionn schlafen mehr als Koalas.",emoji:"🦁"},
  {q:"How many meters lang is a Riesenschlange (Pythons)?",a:7,unit:"meterss",hint:"Der Netzpython is the longest Schlange the world.",emoji:"🐍"},
  {q:"How many Eier legt a weiblicher octopus?",a:400000,unit:"Eier",hint:"Sie bewacht sie bis zum Schlüpfen und dies danach.",emoji:"🐙"},
  {q:"How many km/h runs a Strauß?",a:70,unit:"km/h",hint:"the fastest laufende bird – und can nicht fly.",emoji:"🦜"},
  {q:"How many teeth has a Weißer shark?",a:300,unit:"teeth",hint:"in mehreren Reihen – ständig nachwachsend.",emoji:"🦈"},
  {q:"How heavy is a whaleross maxitimes in kg?",a:1700,unit:"kg",hint:"Männliche whalerosse are deutlich schwerer als Weibchen.",emoji:"🦭"},
  {q:"How many years lives a Arbeiterin-Biene im Sommer?",a:0.13,unit:"years",hint:"Nur 6 weeks im Sommer – im Winter bis to 6 months.",emoji:"🐝"},
  {q:"How many species of insects are there on Earth (million)?",a:1,unit:"Million species",hint:"over 1 Million becante species – viele noch unentdeckt.",emoji:"🐛"},
  {q:"How many hearten has a squid?",a:3,unit:"hearten",hint:"Zwei pumpen blood to den Kiemen, eines zum body.",emoji:"🐙"},
  {q:"How long is die Zunge eines Chamäleons im Verhältnis zum body?",a:150,unit:"% Körperlänge",hint:"Die Zunge schlägt with bis to 26 km/h from.",emoji:"🦎"},
  {q:"How many km/h rennt a cheetah on kurzer Strecke?",a:112,unit:"km/h",hint:"Beschleunigt of 0 on 100 in 3 seconds.",emoji:"🐆"},
  {q:"How many million Geruchssensoren has a bear?",a:2100,unit:"million",hint:"bearen have den schärfsten Geruchssinn aller Landtiere.",emoji:"🐻"},
  {q:"How heavy is a Polarbear maxitimes in kg?",a:700,unit:"kg",hint:"the largest Landraubtier Earth.",emoji:"🐻‍❄️"},
  {q:"How many legs has a thousandfüßer on average?",a:750,unit:"legs",hint:"Nie genau 1000 – trotz des Namens.",emoji:"🐛"},
  {q:"How long can a Stubenfliege fly ohne to landen?",a:2,unit:"hours",hint:"Danach needs sie Ruhe und Nahrung.",emoji:"🪰"},
  {q:"How many years alt is a elephantenschildkröte maxitimes?",a:190,unit:"years",hint:"Harriet livese bis 2006 und was ~175 years alt.",emoji:"🐢"},
  {q:"How many km weit wandert a Monarch-Schmetterling?",a:4000,unit:"km",hint:"of Kanada bis Mexiko – jedes Jahr.",emoji:"🦋"},
  {q:"How many grams weighs a Hummel?",a:600,unit:"mg",hint:"Trotz winziger Masse can sie a Vielfaches ihres Gewichts carry.",emoji:"🐝"},
  {q:"How many hours per day sucht a Nashorn Nahrung?",a:12,unit:"hours",hint:"Die Hälfte ihres Lebens verbringen sie with eat.",emoji:"🦏"},
  {q:"How high springt a Lachs flussaufwärts maxitimes in meters?",a:3,unit:"meterss",hint:"Lachse jump Wasserfälle hinauf to ihren Laichgebieten.",emoji:"🐟"},
  {q:"How many grams Seide produces a Seidenspiderr for einen Kokon?",a:500,unit:"mg",hint:"from einem Kokon can man bis to 1500 meters Seide spidern.",emoji:"🪱"},
  {q:"How many liters blood verliert a Moskito wenn er sticht?",a:0.001,unit:"ml",hint:"Ein Moskito saugt etwa 1-3 mg blood.",emoji:"🦟"},
  {q:"How heavy is a fully grown hippopotamus in tons?",a:3,unit:"tons",hint:"to elephant und Nashorn das drittschwerste Landtier.",emoji:"🦛"},
  {q:"How many hours sleeps a Giraffe daily?",a:2,unit:"hours",hint:"Giraffen schlafen sehr wenig – in kurzen Phasen.",emoji:"🦒"},
  {q:"How many grams weighs a Kolibri?",a:3,unit:"grams",hint:"Der kleinste bird the world weighs weniger als a Münze.",emoji:"🐦"},
  {q:"How often schlägt das heart eines Kolibris per minute?",a:1200,unit:"times",hint:"Das schnellste heart aller Wirbeltiere.",emoji:"🐦"},
  {q:"How far can a kangaroo in einem einzigen jump?",a:9,unit:"meterss",hint:"Und dabei 3 meters hoch.",emoji:"🦘"},
  {q:"How heavy is das brain eines elephanten in kg?",a:5,unit:"kg",hint:"Das schwerste brain aller Landtiere.",emoji:"🐘"},
  {q:"How many kilograms eats a Blauwhale daily an Krill?",a:3600,unit:"kg",hint:"Fast 4 tons Krill daily.",emoji:"🐋"},
  {q:"How many hours can a Albatros nonstop fly?",a:10,unit:"hours",hint:"Albatrosse schlafen sogar im Flug.",emoji:"🦅"},
  {q:"How long is die Trächtigkeit of a mouse in daysn?",a:21,unit:"days",hint:"Mäuse können 10 times per year trächtig sein.",emoji:"🐭"},
  {q:"How many Eier legt a Königin-Ameise per year?",a:300000,unit:"Eier",hint:"Manche Königinnen live 30 years und legen daily 800 Eier.",emoji:"🐜"},
  {q:"How many km/h runs a Schwaszbear?",a:48,unit:"km/h",hint:"Schneller als a human – man can vor einem bearen nicht weglaufen.",emoji:"🐻"},
  {q:"How deep can a Potwhale tauchen in meters?",a:3000,unit:"meterss",hint:"Das tiefste Tauchgang eines Säugetiers.",emoji:"🐳"},
  {q:"How many kilograms Nahrung eats a Gorilla daily?",a:18,unit:"kg",hint:"Gorillas are reine Vegetarier.",emoji:"🦍"},
  {q:"How long lives a Drohnen-Biene?",a:90,unit:"days",hint:"Drohnen live nur bis zur Paarung – dann sterben sie.",emoji:"🐝"},
  {q:"How many meters tief gräbt a Maulwurf seine Tunnel?",a:1,unit:"meterss",hint:"Maulwürfe bauen Tunnel-Systeme over 200 meters Länge.",emoji:"🐀"},
  {q:"How many years lives a wilder Schimpanse?",a:45,unit:"years",hint:"in Gefangenschaft können sie over 60 years alt are.",emoji:"🐒"},
  {q:"How heavy is der Schädel eines Tyrannosaurus Rex in kg?",a:500,unit:"kg",hint:"Einer the largestn Schädel aller fleischfressenden dinosaurs.",emoji:"🦖"},
  {q:"How many Federn has a Schwan?",a:25000,unit:"Federn",hint:"Wasservögel have besonders viele Federn for die Isolation.",emoji:"🦢"},
  {q:"How many hours brütet a Kaiserpinguin sein Ei?",a:1512,unit:"hours",hint:"63 days – ohne Nahrung in antarktischem Winter.",emoji:"🐧"},
  {q:"How far can a cheetah in einem jump?",a:8,unit:"meterss",hint:"cheetahen machen enorme Sprünge beim Jagen.",emoji:"🐆"},
  {q:"How many liters water can an elephant with dem Rüssel aufnehmen?",a:15,unit:"literss",hint:"Der Rüssel is a multifunktionales Werkzeug.",emoji:"🐘"},
  {q:"How many km/h schlägt a Mantis-Garnele to?",a:80,unit:"km/h",hint:"the fastest Schlag im Tierreich.",emoji:"🦐"},
  {q:"How many million Leukozyten has a human pro mm³ blood?",a:7000,unit:"pro mm³",hint:"Immunzellen im blood.",emoji:"🔬"},
  {q:"How many hours sleeps a dolphin per day?",a:8,unit:"hours",hint:"Immer with einer brainhälfte – die andere bleibt wach.",emoji:"🐬"},
  {q:"How heavy is die liver eines Blauwhales in kg?",a:1000,unit:"kg",hint:"Alle Organe des Blauwhales are riesig.",emoji:"🐋"},
  {q:"How many Eier can a Meeresschildkröte pro Saison legen?",a:200,unit:"Eier",hint:"Nur etwa 1% der Jungtiere überleben bis zur Adultheit.",emoji:"🐢"},
  {q:"How many km weit flies a Zugvogel in the year?",a:70000,unit:"km",hint:"Der Küstenseeschwhalebe flies am weitesten.",emoji:"🐦"},
  {q:"How long can a Kamel ohne water überleben in daysn?",a:15,unit:"days",hint:"Der Höcker speichert Fett, nicht water.",emoji:"🐪"},
  {q:"How many hours lives a Eintagsfliege als Imago?",a:24,unit:"hours",hint:"Als Larve lives sie bis to 3 years.",emoji:"🪲"},
  {q:"How heavy is das brain eines Pottwhales in kg?",a:7,unit:"kg",hint:"Das schwerste brain aller becanten animals.",emoji:"🐳"},
  {q:"How many wingsschläge macht a Kolibri pro Sekunde?",a:80,unit:"times",hint:"So schnell, dass die wings unsichtbar are.",emoji:"🐦"},
  {q:"How many km/h runs a Gazelle?",a:90,unit:"km/h",hint:"Gazellen are fast so schnell wie cheetahen.",emoji:"🦌"},
  {q:"How deep gräbt a Erdhörnchen seinen Bau in meters?",a:3,unit:"meterss",hint:"with mehreren Ein- und Ausgängen.",emoji:"🐿️"},
  {q:"How many Stacheln has a Igel?",a:6000,unit:"Stacheln",hint:"Stacheln are modifizierte hairs.",emoji:"🦔"},
  {q:"How many years lives a Hummer?",a:100,unit:"years",hint:"Hummer altern praktisch nicht – sie are nur through Jäger oder Hunger begrenzt.",emoji:"🦞"},
  {q:"How many times schlägt das heart einer Schlange per minute?",a:40,unit:"times",hint:"snakes have einen viel langsameren heartschlag als Säugetiere.",emoji:"🐍"},
  {q:"How far can a Springspider jump in cm?",a:50,unit:"cm",hint:"Das 50-fache ihrer Körperlänge.",emoji:"🕷️"},
  {q:"How many kg eats a tiger daily?",a:8,unit:"kg",hint:"tiger eat seltener aber dafür viel on eintimes.",emoji:"🐯"},
  {q:"How many liters Speichel produces a Kuh daily?",a:200,unit:"literss",hint:"Wiederkäuen erfordert enorm viel Speichel.",emoji:"🐄"},
  {q:"How long sleeps a Braunbear im Winterschlaf in monthsn?",a:6,unit:"months",hint:"Kein echter Tiefschlaf – sie können jederzeit aufwachen.",emoji:"🐻"},
  {q:"How many kilometerss wandert a Weißwhale per year?",a:10000,unit:"km",hint:"Weißwhalee are wanderfreudige Meeressäuger.",emoji:"🐳"},
  {q:"How many hours lives a Biene to dem Stich?",a:1,unit:"Stunde",hint:"Der Stachel verbleibt im Opfer – die Biene dies.",emoji:"🐝"},
  {q:"How heavy is an elephantenzahn (Stoßzahn) maxitimes in kg?",a:100,unit:"kg",hint:"Stoßteeth wachsen a live lang.",emoji:"🐘"},
  {q:"How many grams weighs a neugeborenes kangaroo?",a:1,unit:"grams",hint:"Das Joeys kriecht to der Geburt in den Beutel.",emoji:"🦘"},
  {q:"How many km/h swims a Blauwhale?",a:30,unit:"km/h",hint:"at Gefahr können sie kurze Sprints einlegen.",emoji:"🐋"},
  {q:"How long lives a Taschenkrabbe in yearsn?",a:100,unit:"years",hint:"Krabben können sehr alt are.",emoji:"🦀"},
  {q:"How many grams weighs a Kolibri-Nest?",a:2,unit:"grams",hint:"Winzige Nester from Spinnweben und Flechten.",emoji:"🐦"},
  {q:"How many hours flies a Hornisse daily?",a:8,unit:"hours",hint:"Hornissen are aktive Jäger.",emoji:"🐝"},
  {q:"How far can a dolphin einen Ball balancieren in hours?",a:3,unit:"hours",hint:"dolphine are die intelligducksten Meerebulle.",emoji:"🐬"},
  {q:"How many years can a Krokodil ohne Nahrung überleben?",a:3,unit:"years",hint:"Krokodile have einen extrem niedrigen Stoffwechsel.",emoji:"🐊"},
  {q:"How heavy is der penis eines Blauwhales in kg?",a:450,unit:"kg",hint:"the largest Geschlechtsorgan im Tierreich.",emoji:"🐋"},
  {q:"How long is a Blauwhale-penis in meters?",a:2.7,unit:"meterss",hint:"Proportional zum body aber das absolut größte.",emoji:"🐋"},
  {q:"How many Eizellen produces a ocean-sunnblume pro Saison?",a:300000000,unit:"Eier",hint:"300 million Eier – die meisen aller Wirbeltiere.",emoji:"🐟"},
  {q:"How many liters blood pumpt an elephantenheart per minute?",a:300,unit:"literss",hint:"Das elephantenheart weighs 25 kg.",emoji:"🐘"},
  {q:"How many hours can a Nacktmull-Ratte ohne Sauerstoff überleben?",a:18,unit:"hours",hint:"Nacktmull-Ratten are gegen Sauerstoffmangel resisent.",emoji:"🐀"},
  {q:"How heavy is das brain eines Octopus in grams?",a:40,unit:"grams",hint:"Sehr klein aber extrem effizient.",emoji:"🐙"},
  {q:"How many Chromatophoren has a squid?",a:10000000,unit:"Chromatophoren",hint:"Diese Farbzellen ermöglichen blitzschnelle Farbwechsel.",emoji:"🦑"},
  {q:"How many meters lang is a Bandwurm maxitimes?",a:30,unit:"meterss",hint:"Fischbandwürmer können bis to 30m lang are.",emoji:"🪱"},
  {q:"How many times pro Nacht hört a Eule?",a:360,unit:"degrees",hint:"Eulen können den Kopf 270 degrees drehen.",emoji:"🦉"},
  {q:"How heavy is a Ochsen-Frosch in kg?",a:3,unit:"kg",hint:"the heaviest Frosch the world.",emoji:"🐸"},
  {q:"How many liters Honig produces a Bienenvolk per year?",a:30,unit:"literss",hint:"for a Glas Honig fly Bienen 80.000 km.",emoji:"🍯"},
  {q:"How long is die Trächtigkeit eines Schwaszen Rhinozeros in daysn?",a:450,unit:"days",hint:"15 months – eine the longestn Tragezeiten.",emoji:"🦏"},
  {q:"How many hours lives a Eintagsfliegen-Larve bevor sie schlüpft?",a:26280,unit:"hours",hint:"3 years als Larve, dann 1 Tag als Erwachsener.",emoji:"🪲"},
  {q:"How deep taucht a Kaiserpinguin maxitimes in meters?",a:565,unit:"meterss",hint:"Der tieftauchende bird the world.",emoji:"🐧"},
  {q:"How many grams weighs das heart eines horsees?",a:4500,unit:"grams",hint:"Das große heart is der Schlüssel zur Ausdauer.",emoji:"🐴"},
  {q:"How far can a Lemur jump in meters?",a:10,unit:"meterss",hint:"Lemure are erstaunliche Springer.",emoji:"🐒"},
  {q:"How many km/h can a Libelle fly?",a:55,unit:"km/h",hint:"Eine the fastestn fliegenden insects.",emoji:"🪲"},
  {q:"How long lives a Dragonfly in weeks als Erwachsener?",a:4,unit:"weeks",hint:"Als Larve lives sie bis to 5 years.",emoji:"🪲"},
  {q:"How heavy is a fully grownes hippopotamus-Zahn in kg?",a:3,unit:"kg",hint:"Die Eckteeth are reine Waffen.",emoji:"🦛"},
  {q:"How many Tentakel has a octopus?",a:8,unit:"Tentakel",hint:"Jeder Arm has eigene Nervenzellen.",emoji:"🐙"},
  {q:"How far can a Flachlandgorilla seinen Ruf hören in km?",a:2,unit:"km",hint:"Gorillas kommunizieren over weite Disanzen.",emoji:"🦍"},
  {q:"How many times pro Sekunde bewegt a Schwertfisch die Schwanzflosse?",a:3,unit:"times",hint:"Kraftvolle langsame Bewegungen for hohe Geschwindigkeit.",emoji:"🐟"},
  {q:"How long is die Nasenspitze eines elephanten-Rüssels?",a:250,unit:"cm",hint:"Der Rüssel is der verlängerte Nasenrücken.",emoji:"🐘"},
  {q:"How many liters water drinks a Kamel on eintimes to der desert?",a:100,unit:"literss",hint:"in 13 minutes can a Kamel 100 liters drink.",emoji:"🐪"},
  {q:"How heavy is a Blauwhaletesticles in kg?",a:35,unit:"kg",hint:"Jeder testicles weighs erstaunlich viel kg – zusammen 70 kg.",emoji:"🐋"},
  {q:"How many hours alt are Libellen-Larven bevor sie schlüpfen?",a:35040,unit:"hours",hint:"4 years als Larve im water.",emoji:"🪲"},
  {q:"How many colors can a squid gleichzeitig anzeigen?",a:30,unit:"colors",hint:"Obwohl colorsblind – der Farbwechsel dient der Tarnung.",emoji:"🦑"},
  {q:"How fast regeneriert a Seestar seinen Arm in weeks?",a:52,unit:"weeks",hint:"Ein Jahr – und from dem abgetrennten Arm grows a neuer Seestar.",emoji:"⭐"},
  {q:"How many years can a Qualle (Turritopsis dohrnii) theoretisch live?",a:9999,unit:"years",hint:"Die biologisch unsterbliche Qualle can sich unbegrenzt verjüngen.",emoji:"🪼"},
  {q:"How many km/h can a cheetah on 100m beschleunigen?",a:75,unit:"km/h",hint:"Beschleunigung of 0 on 75 in 2 seconds.",emoji:"🐆"},
  {q:"How many kilograms weighs a fully grown Jaguar?",a:100,unit:"kg",hint:"the heaviest Großcat Amerikas.",emoji:"🐆"},
  {q:"How many Augen has a Libelle?",a:30000,unit:"Facetten",hint:"Zusammengesetzte Augen with 30.000 Einzellinsen.",emoji:"🪲"},
  {q:"How far can a Springer-Frosch jump in cm?",a:530,unit:"cm",hint:"Vielfaches der eigenen Körperlänge.",emoji:"🐸"},
  {q:"How many hours daily is a Hauscat aktiv?",a:5,unit:"hours",hint:"Hauscatn schlafen 16-20 hours daily.",emoji:"🐱"},
  {q:"How many grams Honig isst a bear in einem Sommer?",a:40000,unit:"grams",hint:"40 kg Honig – bearen lieben Bienenstöcke.",emoji:"🐻"},
  {q:"How many km/h can a squid swim?",a:40,unit:"km/h",hint:"through rückwärtiges Ausstoßen of water.",emoji:"🦑"},
  {q:"How long is die Zunge eines Ameisenbearen in cm?",a:60,unit:"cm",hint:"Die klebrige Zunge fährt 150 times per minute from.",emoji:"🐜"},
  {q:"How many hours am Tag weidet a horse?",a:16,unit:"hours",hint:"horsee eat fast nonstop.",emoji:"🐴"},
  {q:"How heavy is a fully grown Gorilla-Arm in kg?",a:15,unit:"kg",hint:"Gorillas are 6 times stärker als people.",emoji:"🦍"},
  {q:"How many liters blood pumpt a Giraffenheart per minute?",a:60,unit:"literss",hint:"Das Giraffenheart weighs 10 kg.",emoji:"🦒"},
  {q:"How many km can a Wüstenameise ohne Orientierungshilfe navigieren?",a:50,unit:"km",hint:"Sie nutzen Polarisationsmuster des Himmels.",emoji:"🐜"},
  {q:"How many bones has a dolphin?",a:200,unit:"bones",hint:"dolphine have bones wo einst Hinterlegs wasen.",emoji:"🐬"},
  {q:"How deep können Maulwürfe ihre Tunnels anlegen?",a:70,unit:"cm",hint:"Haupttunnel liegen tiefer als Jagdtunnel.",emoji:"🐀"},
  {q:"How many hours can a Flamingo on einem Bein stehen?",a:4,unit:"hours",hint:"Das Stehen on einem Bein costs weniger Energie.",emoji:"🦩"},
  {q:"How many Ton eats a Blauwhale an a day?",a:3.6,unit:"tons",hint:"Fast 4 tons Krill daily.",emoji:"🐋"},
  {q:"How far can a Heuschrecke jump in meters?",a:1,unit:"meterss",hint:"Das 20-fache ihrer eigenen Körperlänge.",emoji:"🦗"},
  {q:"How many years can an elephant live?",a:70,unit:"years",hint:"in Gefangenschaft are sie manchtimes over 80.",emoji:"🐘"},
  {q:"How heavy is a neugeborener Blauwhale in tons?",a:2.7,unit:"tons",hint:"the largest Neugeborene the world.",emoji:"🐋"},
  {q:"How many hours sleeps a Totenkopf-Äffchen daily?",a:11,unit:"hours",hint:"Totenkopfäffchen are echte Schläfer.",emoji:"🐒"},
  {q:"How long is an elephantenrüssel in meters?",a:2,unit:"meterss",hint:"Er has over 40.000 muscles.",emoji:"🐘"},
  {q:"How many Eier legt a Königin-Ameise daily?",a:800,unit:"Eier",hint:"over ihr ganzes live bis to 30 million Eier.",emoji:"🐜"},
  {q:"How long is die Trächtigkeit eines Schwertwhales in monthsn?",a:17,unit:"months",hint:"Orcas have a the longestn Tragezeiten.",emoji:"🐋"},
  {q:"How many hours verbringt an animal im water daily (hippopotamus)?",a:16,unit:"hours",hint:"hippopotamuse kühlen sich und schützen ihre Haut.",emoji:"🦛"},
  {q:"How many grams weighs a Pfauenschwanz-Feder?",a:5,unit:"grams",hint:"Trotz ihrer Größe extrem leicht.",emoji:"🦚"},
  {q:"How many Stacheln has a Igel on dem Rücken?",a:5000,unit:"Stacheln",hint:"Jeder Stachel is a modifiziertes Haar.",emoji:"🦔"},
  {q:"How far can a Fliegendes Eichhörnchen gleiten in meters?",a:90,unit:"meterss",hint:"with der Gleitfalte between Vorder- und Hinterlegsn.",emoji:"🐿️"},
  {q:"How many km/h runs a Erdferkel?",a:40,unit:"km/h",hint:"Überraschend schnell for a scheinbar gemächliches animal.",emoji:"🐷"},
  {q:"How heavy is a fully grown männlicher elephant-Rüsseltier in kg?",a:6000,unit:"kg",hint:"Afrikanische elephanten are schwerer als asiatische.",emoji:"🐘"},
  {q:"How many liters Milch drinks a Blauwhale-Baby daily?",a:600,unit:"literss",hint:"Es grows daily um 90 kg.",emoji:"🐋"},
  {q:"How many hours verbringt a Flamingo im water daily?",a:12,unit:"hours",hint:"Flamingos filtern Nahrung from Schlamm.",emoji:"🦩"},
  {q:"How long is die Trächtigkeit eines Nashorns in monthsn?",a:16,unit:"months",hint:"Nashörner bekommen nur alle 2-5 years a Junges.",emoji:"🦏"},
  {q:"How many grams weighs a Honigbiene?",a:100,unit:"mg",hint:"Nur 100 milligrams – aber immens wichtig.",emoji:"🐝"},
  {q:"How far can a Fliegender fish from dem water herausgleiten?",a:400,unit:"meterss",hint:"Flugfische nutzen Wind und Auftrieb.",emoji:"🐟"},
  {q:"How many years lives a whaleross?",a:40,unit:"years",hint:"whalerosse are in der Wildnis bis to 40 years alt.",emoji:"🦭"},
  {q:"How heavy is die Schildkrötenpanzer eines Riesenschildkröte in kg?",a:30,unit:"kg",hint:"Der Panzer macht a Drittel des Körpergewichts from.",emoji:"🐢"},
  {q:"How many hours am Tag reinigt sich a cat?",a:5,unit:"hours",hint:"Ein Drittel ihrer Wachzeit verbringen catn with Putzen.",emoji:"🐱"},
  {q:"How many grams weighs a penguin-Ei?",a:450,unit:"grams",hint:"Kaiserpinguin-Eier are riesig im Verhältnis zum body.",emoji:"🐧"},
  {q:"How far can a cheetah seinen Geruchssinn nutzen in km?",a:3,unit:"km",hint:"cheetahen nutzen hauptsächlich das Sehen.",emoji:"🐆"},
  {q:"How many teeth has a dolphin?",a:100,unit:"teeth",hint:"dolphine benutzen teeth zum Fangen, nicht zum Kauen.",emoji:"🐬"},
  {q:"How long is die Zunge einer Kuh in cm?",a:45,unit:"cm",hint:"Kühe lecken sich die Nase damit sauber.",emoji:"🐄"},
  {q:"How many Stacheln has a Stachelrochen?",a:1,unit:"Stachel",hint:"Nur a Giftstachel – aber sehr schmerzhaft.",emoji:"🐟"},
  {q:"How heavy is a Gorilla-Silberrücken in kg?",a:250,unit:"kg",hint:"Silberrücken domikidneyn ihre Gruppe.",emoji:"🦍"},
  {q:"How far can a Springhase jump in meters?",a:3,unit:"meterss",hint:"Springhasen are afrikanische Nager.",emoji:"🐇"},
  {q:"How many km/h erreicht a Schildkröte beim swim?",a:35,unit:"km/h",hint:"Lederschildkröten are erstaunlich schnelle Schwimmer.",emoji:"🐢"},
  {q:"How many grams Futter eats a Raupe daily im Verhältnis zum Körpergewicht?",a:200,unit:"% Körpergewicht",hint:"Raupen verdoppeln ihr Gewicht in daysn.",emoji:"🐛"},
  {q:"How many hours lives a Hausfliegenmaggot bis zur Verpuppung?",a:240,unit:"hours",hint:"10 days als Made, dann Puppe.",emoji:"🪰"},
  {q:"How long is der Dünndarm einer Kuh in meters?",a:40,unit:"meterss",hint:"Kühe have a sehr langes Verdauungssystem.",emoji:"🐄"},
  {q:"How many liters Speichel produces a horse daily?",a:40,unit:"literss",hint:"horsee brauchen viel Speichel for die Verdauung.",emoji:"🐴"},
  {q:"How heavy is a Schimpansen-Arm im Vergleich to einem menschlichen?",a:2,unit:"x stärker",hint:"Schimpansen are doppelt so stark wie people.",emoji:"🐒"},
  {q:"How far wandert a Elch per year in km?",a:300,unit:"km",hint:"Elche folgen Nahrung und Wetter.",emoji:"🦌"},
  {q:"How many hours needs a Schlange for die Verdauung einer großen Mahlzeit?",a:168,unit:"hours",hint:"Eine Woche for a großes animal.",emoji:"🐍"},
  {q:"How many grams grows a Blauwhale-Baby daily?",a:90000,unit:"grams",hint:"90 kg daily – 7 months lang gestillt.",emoji:"🐋"},
  {q:"How far can a Albatros in einem einzigen Flug zurücklegen?",a:10000,unit:"km",hint:"Albatrosse umrunden die Erde im Südpolarmeer.",emoji:"🦅"},
  {q:"How many years is an elephant geschlechtsreif?",a:14,unit:"years",hint:"elephantenbullen treten erst with 14 in die Brunst.",emoji:"🐘"},
  {q:"How many liters blood has a Nashorn?",a:20,unit:"literss",hint:"Proportional weniger als an elephant.",emoji:"🦏"},
  {q:"How long is die Trächtigkeit eines Orcas in monthsn?",a:17,unit:"months",hint:"Eine the longestn Tragezeiten under Meeressäugern.",emoji:"🐋"},
  {q:"How many grams eats a Igel daily?",a:70,unit:"grams",hint:"insects, Würmer und kleine Wirbeltiere.",emoji:"🦔"},
  {q:"How far can a Springbock in einem jump?",a:15,unit:"meterss",hint:"Springböcke machen hohe Luftsprünge als wasnsignal.",emoji:"🦌"},
  {q:"How many Federn verliert a bird annually beim Mausern?",a:10000,unit:"Federn",hint:"birds erneuern ihr Gefieder annually komplett.",emoji:"🐦"},
  {q:"How heavy can a Riesenkalmars Mantel in kg are?",a:150,unit:"kg",hint:"Riesenkalmare are the largestn wirbellosen animals.",emoji:"🦑"},
  {q:"How many hours lives a Stubenfliege in total?",a:500,unit:"hours",hint:"Nur 3 weeks – in dieser Zeit legen sie Eier.",emoji:"🪰"},
  {q:"How many Zellen has a Regenwurm?",a:1000,unit:"Segmduck",hint:"Regenwürmer können in jedem Segment nachwachsen.",emoji:"🪱"},
  {q:"How far wandert a Monarch-Schmetterling per day?",a:80,unit:"km",hint:"in 2 monthsn of Kanada to Mexiko.",emoji:"🦋"},
  {q:"How heavy is a Schimpansen-brain im Vergleich zum people in %?",a:33,unit:"% des peoplebrains",hint:"Schimpansen-brain weighs ~400g, menschliches ~1400g.",emoji:"🐒"},
  {q:"How many hours daily verbringt a Orang-Utan in Bäumen?",a:24,unit:"hours",hint:"Orang-Utans are the largestn Baumklettertiere.",emoji:"🦧"},
  {q:"How many Eier legt a ocean-Qualle per year?",a:45000,unit:"Eier",hint:"Quallen können sich auch vegetativ vermehren.",emoji:"🪼"},
  {q:"How far can a Flossenfüßer-Robbe swim daily?",a:100,unit:"km",hint:"Robben are ausdauernde Schwimmer.",emoji:"🦭"},
  {q:"How heavy is a Erdwurm in grams?",a:5,unit:"grams",hint:"Ein nortimeser Regenwurm weighs 3-10g.",emoji:"🪱"},
  {q:"How far können elephanten a Wasserstelle riechen in km?",a:19,unit:"km",hint:"elephanten have den feinsten Geruchssinn aller Landtiere.",emoji:"🐘"},
  {q:"How many hours needs a Schmetterling for die Metamorphose?",a:336,unit:"hours",hint:"2 weeks im Kokon.",emoji:"🦋"},
  {q:"How many kg Gras eats a horse daily?",a:11,unit:"kg",hint:"horsee are reine Pflanzenfresser.",emoji:"🐴"},
  {q:"How far can a Seedog tauchen in meters?",a:300,unit:"meterss",hint:"Seedoge können bis to 30 minutes tauchen.",emoji:"🦭"},
  {q:"How many teeth has a Hecht?",a:700,unit:"teeth",hint:"Hechte have mehrere Reihen kleiner teeth.",emoji:"🐟"},
  {q:"How heavy is a Marien-Käfer in milligrams?",a:25,unit:"mg",hint:"Trotz winziger Größe eats er daily 100 Blattläuse.",emoji:"🐞"},
  {q:"How far can a Wüstenspringmaus in einem jump?",a:3,unit:"meterss",hint:"Relative Sprungweite: 45x die eigene Körperlänge.",emoji:"🐭"},
  {q:"How many hours lives a Schmetterlingsweibchen to der Paarung?",a:2,unit:"weeks",hint:"Manche Schmetterlinge live nur wenige days.",emoji:"🦋"},
  {q:"How heavy is a Pelikan-Beutel wenn voll in liters?",a:13,unit:"literss",hint:"Der Kehlsack fasst mehr als der Magen.",emoji:"🐦"},
  {q:"How many kg fish eats a fully grown Weißer shark daily?",a:11,unit:"kg",hint:"Haie eat selten – dafür viel on eintimes.",emoji:"🦈"},
  {q:"How far können whalee Töne under water hören in km?",a:3000,unit:"km",hint:"Finnwhalee kommunizieren over thousande kilometerss.",emoji:"🐋"},
  {q:"How many hours daily verbringt a Faultier with Bewegen?",a:3,unit:"hours",hint:"Der Rest des dayss is with Schlafen verbracht.",emoji:"🦥"},
  {q:"How heavy is die liver eines Weißen Hais in kg?",a:500,unit:"kg",hint:"Die enorme liver dient als Auftriebsorgan.",emoji:"🦈"},
  {q:"How long is die Trächtigkeit eines Gürteltiers in monthsn?",a:4,unit:"months",hint:"Gürteltiere gebearen immer eineiige Vierlings.",emoji:"🐾"},
  {q:"How far springt a dolphin from dem water in meters?",a:6,unit:"meterss",hint:"Breaching is a wichtiges Kommunikationsmittel.",emoji:"🐬"},
  {q:"How many hours lives a Stubenfliege als Larve?",a:120,unit:"hours",hint:"5 days als Maggot.",emoji:"🪰"},
  {q:"How heavy is a fully grown Schimpansen in kg?",a:60,unit:"kg",hint:"Trotz geringerer Größe 6x stärker als a human.",emoji:"🐒"},
  {q:"How many Tentakel has a Qualle?",a:80,unit:"Tentakel",hint:"Je to Art between 4 und dogerten Tentakeln.",emoji:"🪼"},
  {q:"How far can a Krokodil from dem water herausspringen?",a:1.5,unit:"meterss",hint:"Krokodile are überraschend agil.",emoji:"🐊"},
  {q:"How many grams eats a Hausmaus daily?",a:5,unit:"grams",hint:"Ein Siebtel ihres Körpergewichts daily.",emoji:"🐭"},
  {q:"How heavy is a weiblicher elephant maxitimes in tons?",a:4,unit:"tons",hint:"Weibliche elephanten are kleiner als die Männchen.",emoji:"🐘"},
  {q:"How many hours can a Hamster daily im Rad run?",a:8,unit:"hours",hint:"Hamster legen im Rad bis to 20 km pro Nacht zurück.",emoji:"🐹"},
  {q:"How far can a Kugelfisch aufblähen in cm Durchmesser?",a:90,unit:"cm",hint:"Kugelfische saugen water an um sich aufzublähen.",emoji:"🐡"},
  {q:"How many liters Milch drinks an elephantenbaby daily?",a:10,unit:"literss",hint:"elephantenbabys are 2-3 years gestillt.",emoji:"🐘"},
  {q:"How heavy is a Spinnwebnetz in milligrams?",a:0.5,unit:"mg",hint:"Unglaublich leicht aber stärker als Stahl.",emoji:"🕸️"},
  {q:"How long is die Trächtigkeit eines Dachses in weeks?",a:7,unit:"weeks",hint:"Dachse legen die Trächtigkeit on günstige yearsszeiten from.",emoji:"🦡"},
  {q:"How many hours sleeps a Gorilla daily?",a:12,unit:"hours",hint:"Gorillas bauen daily neue Schlafnester.",emoji:"🦍"},
  {q:"How far can a Weißer shark seine Kiefer vorschnellen?",a:30,unit:"cm",hint:"Der Kiefer schnellt beim Beißen weit vor.",emoji:"🦈"},
  {q:"How many Eier legt a Riesenmeeresschildkröte in einem Nest?",a:100,unit:"Eier",hint:"Sie legen mehrere timese pro Saison.",emoji:"🐢"},
  {q:"How many hours daily verbringt a fish with Schlafen?",a:4,unit:"hours",hint:"Fische schlafen with offenen Augen.",emoji:"🐟"},
  {q:"How far können elephanten kommunizieren per Infraschall in km?",a:10,unit:"km",hint:"Tiefe Töne propagieren weit through den Boden.",emoji:"🐘"},
  {q:"How many kg Nahrung eats a hippopotamus daily?",a:40,unit:"kg",hint:"hippopotamuse eat nachts an country.",emoji:"🦛"},
  {q:"How heavy is a cheetah-Baby at Geburt in grams?",a:250,unit:"grams",hint:"cheetahen are at Geburt blind und hilflos.",emoji:"🐆"},
  {q:"How many hours takes a tiger-Jagd?",a:1,unit:"Stunde",hint:"Nur 1 of 10 Jagdversuchen is erfolgreich.",emoji:"🐯"},
  {q:"How far können dolphinpfeifen under water gehört are in km?",a:40,unit:"km",hint:"dolphine kommunizieren over enorme Disanzen.",emoji:"🐬"},
  {q:"How many grams weighs a Stachel einer Biene?",a:3,unit:"mg",hint:"Nur 3 milligrams aber tödliches Gift.",emoji:"🐝"},
  {q:"How deep can a Langschwanzcat ihr Revier markieren in meters?",a:50,unit:"cm Höhe",hint:"Markierungen are on Augenhöhe angebracht.",emoji:"🐈"},
  {q:"How many hours daily gehen Wölfe on Jagd?",a:8,unit:"hours",hint:"Wölfe legen daily 30-50 km zurück.",emoji:"🐺"},
];
