// 🐾 ANIMALS & SEX – English
export default [
  {q:"How long dauert der Sex bei Schlangen in Stunden?",a:24,unit:"hours",hint:"Schlangen können tage- und wochenlang paaren.",emoji:"🐍"},
  {q:"How many cm lang ist der Penis einer Ente relativ zur Körperlänge?",a:40,unit:"cm",hint:"Stockenten haben spiralförmige Penisse.",emoji:"🦆"},
  {q:"How many Hoden hat ein Stier?",a:2,unit:"Hoden",hint:"Wie die meisten Säugetiere.",emoji:"🐂"},
  {q:"How many cm lang ist der Penis eines Blauwals?",a:270,unit:"cm",hint:"2,7 Meter – das größte Geschlechtsorgan im Tierreich.",emoji:"🐋"},
  {q:"How long trägt eine Elefantendame ihr Junges in Tagen?",a:645,unit:"days",hint:"Fast 2 Jahre – längste Tragzeit auf Land.",emoji:"🐘"},
  {q:"How many Mal paart sich ein Schimpanse mit verschiedenen Weibchen?",a:100,unit:"times",hint:"Männliche Schimpansen paaren sich mit vielen Weibchen.",emoji:"🐒"},
  {q:"How many Eier legt eine Königin-Biene in ihrem Leben?",a:2000000,unit:"Eier",hint:"2 million über ihr Leben von 5 Jahren.",emoji:"🐝"},
  {q:"How long is die Vagina einer Kuh in cm?",a:30,unit:"cm",hint:"Ähnlich lang wie der Arm eines Kindes.",emoji:"🐄"},
  {q:"How many Spermien enthält ein Stier-Ejakulat?",a:7000000000,unit:"Spermien",hint:"7 billion – viel mehr als beim Menschen.",emoji:"🐂"},
  {q:"How long dauert der Sex bei Giraffen in Sekunden?",a:2,unit:"seconds",hint:"Sehr schnell – aber häufig.",emoji:"🦒"},
  {q:"How many Mal am Tag paart sich ein Löwe?",a:20,unit:"times",hint:"In der Ranzzeit bis zu viele Male daily.",emoji:"🦁"},
  {q:"How many cm lang ist der Penis eines Gorillas?",a:4,unit:"cm",hint:"Trotz ihrer Größe sehr kleines Geschlechtsorgan.",emoji:"🦍"},
  {q:"How long dauert der Geschlechtsakt bei Bonobos?",a:15,unit:"seconds",hint:"Sehr kurz – aber sehr häufig.",emoji:"🐒"},
  {q:"How many Hoden hat ein Wal?",a:2,unit:"Hoden",hint:"Innen liegend – zum Schutz vor Kälte.",emoji:"🐋"},
  {q:"How long trägt eine Hai-Art ihr Junges in Monaten?",a:24,unit:"months",hint:"Hammerhaie tragen 2 Jahre.",emoji:"🦈"},
  {q:"How many Meter lang ist der Penis eines Barnacle (Seepocke) relativ zur Körpergröße?",a:8,unit:"x Körperlänge",hint:"Relativ zur Körpergröße das längste Geschlechtsorgan.",emoji:"🦀"},
  {q:"How many cm ist die Klitoris einer Hyäne lang?",a:18,unit:"cm",hint:"Weibliche Hyänen haben eine pseudopenis-ähnliche Klitoris.",emoji:"🦁"},
  {q:"Wie lang dauert die Paarung bei Nashörnern in Minuten?",a:30,unit:"minutes",hint:"Eine der längsten unter Landsäugern.",emoji:"🦏"},
  {q:"How many Penisse haben Schlangen?",a:2,unit:"Hemipenis",hint:"Schlangen haben zwei Hemipenes.",emoji:"🐍"},
  {q:"How many kg wiegt das Geschlechtsorgan eines Blauwals insgesamt?",a:1000,unit:"kg",hint:"Hoden 70kg, Penis 450kg.",emoji:"🐋"},
  {q:"How many Stunden brütet ein männlicher Kaiserpinguin auf dem Ei?",a:1512,unit:"hours",hint:"63 Tage – ohne Nahrung im antarktischen Winter.",emoji:"🐧"},
  {q:"How many Mal paart sich eine Drohnen-Biene in ihrem Leben?",a:1,unit:"times",hint:"Danach stirbt die Drohne.",emoji:"🐝"},
  {q:"How long dauert der Sex bei Haien in Stunden?",a:30,unit:"minutes",hint:"Minuten – mit Bissen als Vorzeichen.",emoji:"🦈"},
  {q:"How many cm lang ist der Penis eines Schimpansen?",a:8,unit:"cm",hint:"Größer als beim Gorilla.",emoji:"🐒"},
  {q:"How many Eier legt eine Riesenschildkröte pro Saison?",a:200,unit:"Eier",hint:"Mehrmals per year.",emoji:"🐢"},
  {q:"How long paaren sich Feldheuschrecken am Stück?",a:12,unit:"hours",hint:"Manchmal tagelang verbunden.",emoji:"🦗"},
  {q:"How many Zentimeter lang ist der Penis eines Pottwal?",a:240,unit:"cm",hint:"Zweitlängster Tierpenis nach dem Blauwal.",emoji:"🐳"},
  {q:"How long trägt ein Hund sein Junges in Tagen?",a:63,unit:"days",hint:"Tage Tragezeit.",emoji:"🐕"},
  {q:"How many Mal paart sich ein Löwen-Männchen mit einer Löwin in der Ranzzeit?",a:20,unit:"Mal/Tag",hint:"Bis zu viele Male daily über mehrere Tage.",emoji:"🦁"},
  {q:"How many Eier legt eine Schildkröte pro Gelege?",a:100,unit:"Eier",hint:"Je nach Art 50-200.",emoji:"🐢"},
  {q:"How long dauert die Paarung bei Spinnen?",a:60,unit:"minutes",hint:"Manchmal bis zu mehreren Stunden.",emoji:"🕷️"},
  {q:"How many cm lang ist die Vagina einer Pferdes?",a:60,unit:"cm",hint:"Stuten haben eine sehr lange Vagina.",emoji:"🐴"},
  {q:"How long dauert die Trächtigkeit einer Katze in Wochen?",a:9,unit:"weeks",hint:"63-67 Tage.",emoji:"🐱"},
  {q:"How many Weibchen befruchtet ein Stier per year in der Tierzucht?",a:50000,unit:"Weibchen",hint:"Durch künstliche Besamung.",emoji:"🐂"},
  {q:"How long dauert die Trächtigkeit einer Maus in Tagen?",a:21,unit:"days",hint:"Drei Wochen – und kann sofort wieder trächtig werden.",emoji:"🐭"},
  {q:"How many Junge wirft eine Maus per year?",a:70,unit:"Jungtiere",hint:"5-10 Würfe à 5-10 Jungen.",emoji:"🐭"},
  {q:"How many Mal können Kaninchen in einer Stunde paaren?",a:10,unit:"times",hint:"'Schnell wie Kaninchen' – wörtlich gemeint.",emoji:"🐇"},
  {q:"How long is der Geschlechtsakt bei Hunden in Minuten?",a:20,unit:"minutes",hint:"'Tie' – sie stecken zusammen.",emoji:"🐕"},
  {q:"How many Eier legt ein Oktopus-Weibchen?",a:400000,unit:"Eier",hint:"400.000 Eier und bewacht sie bis zum Tod.",emoji:"🐙"},
  {q:"How many cm lang ist der Penis eines Elefanten?",a:180,unit:"cm",hint:"1,8 Meter – S-förmig und muskelstark.",emoji:"🐘"},
  {q:"How long paaren sich Wale in Stunden?",a:18,unit:"minutes",hint:"20 Minuten – im Meer.",emoji:"🐋"},
  {q:"How many Ovulation per year hat eine Katze?",a:4,unit:"times",hint:"Katzen sind saisonale Mehrfachläufer.",emoji:"🐱"},
  {q:"How many Junge kann ein Opossum gleichzeitig tragen?",a:20,unit:"Junge",hint:"Im Beutel – alle gleichzeitig.",emoji:"🐀"},
  {q:"How long trägt ein Elefant sein Junges in Monaten?",a:21,unit:"months",hint:"Fast 2 Jahre.",emoji:"🐘"},
  {q:"How many Eier legt eine Königin-Termite per day?",a:30000,unit:"Eier",hint:"Die produktivste Mutter im Insektenreich.",emoji:"🐜"},
  {q:"How many cm lang ist der Penis eines Delfins?",a:38,unit:"cm",hint:"Delfine haben prehensile Penisse.",emoji:"🐬"},
  {q:"How long dauert die Paarung von Flusspferden in Minuten?",a:10,unit:"minutes",hint:"Im Wasser.",emoji:"🦛"},
  {q:"How many Junge hat ein Wombat per year?",a:1,unit:"Junges",hint:"Nur ein Junges – sehr langsame Fortpflanzung.",emoji:"🐨"},
  {q:"How long paaren sich Pferde in Minuten?",a:1,unit:"Minute",hint:"Kurz aber intensiv.",emoji:"🐴"},
  {q:"How many Weibchen besucht ein Gorilla-Silberrücken?",a:10,unit:"Weibchen",hint:"Ein Silberrücken führt eine Gruppe.",emoji:"🦍"},
  {q:"How long trägt ein Känguru sein Junges im Beutel in Monaten?",a:9,unit:"months",hint:"Erst 1cm groß bei Geburt – dann im Beutel.",emoji:"🦘"},
  {q:"How many cm lang ist der Penis eines Schimpansen?",a:8,unit:"cm",hint:"Obwohl viel kleiner als Menschen denken.",emoji:"🐒"},
  {q:"How long paaren sich Bienen?",a:0.01,unit:"seconds",hint:"Nur eine Sekunde – die Drohne stirbt danach.",emoji:"🐝"},
  {q:"How many Eier legt ein Schmetterlings-Weibchen insgesamt?",a:200,unit:"Eier",hint:"Meist Hunderte verteilt auf viele Pflanzen.",emoji:"🦋"},
  {q:"How many cm lang ist der Penis einer Seekuh (Manatee)?",a:70,unit:"cm",hint:"Auch Seekühe haben beeindruckende Organe.",emoji:"🐟"},
  {q:"How long dauert die Trächtigkeit eines Pottwal in Monaten?",a:16,unit:"months",hint:"Fast 1,5 Jahre.",emoji:"🐳"},
  {q:"How many Junge wirft eine Katze pro Wurf?",a:5,unit:"Junge",hint:"Durchschnittlich 3-7 Kätzchen.",emoji:"🐱"},
  {q:"How many Male paart sich eine Königin-Ameise in ihrem Leben?",a:1,unit:"times",hint:"Einmal – dann lagert sie Spermien für Jahre.",emoji:"🐜"},
  {q:"How many cm lang ist der Penis einer Maus?",a:1.5,unit:"cm",hint:"Relativ zu ihrem Körper sehr groß.",emoji:"🐭"},
  {q:"How long paaren sich Grizzlybären?",a:30,unit:"minutes",hint:"Der Akt dauert bis zu 30 Minuten.",emoji:"🐻"},
  {q:"How many Eier legt eine Flussbarsch-Weibchen?",a:300000,unit:"Eier",hint:"Fische legen enorme Eiermengen.",emoji:"🐟"},
  {q:"How many cm ist die Klitoris einer Weibchen-Fossa (Madagaskar)?",a:7,unit:"cm",hint:"Die Fossa hat einen außergewöhnlich langen Klitoris.",emoji:"🦁"},
  {q:"How long dauert der Hochzeitsflug einer Bienenkönigin?",a:1,unit:"Stunde",hint:"Sie paart sich in der Luft mit 12-20 Drohnen.",emoji:"🐝"},
  {q:"How many Tage ist eine Hündin im Jahr läufig?",a:18,unit:"days",hint:"Zweimal im Jahr je 9 Tage.",emoji:"🐕"},
  {q:"How many cm lang ist der Penis eines Nilpferds?",a:50,unit:"cm",hint:"Nilpferde spritzen Urin zur Territorialmarkierung.",emoji:"🦛"},
  {q:"How long paaren sich Pandas?",a:3,unit:"minutes",hint:"Sehr kurz – und sehr selten.",emoji:"🐼"},
  {q:"How many Junge hat ein Schwein pro Wurf?",a:10,unit:"Ferkel",hint:"8-14 Ferkel pro Wurf.",emoji:"🐷"},
  {q:"How many Eier legt eine Meeresschildkröte pro Saison insgesamt?",a:600,unit:"Eier",hint:"3-7 Gelege à 80-120 Eier.",emoji:"🐢"},
  {q:"How many cm lang ist der Penis eines Seelöwen?",a:40,unit:"cm",hint:"Pinnipeds haben sehr lange Penisse.",emoji:"🦭"},
  {q:"How long dauert die Trächtigkeit eines Schimpansen in Tagen?",a:243,unit:"days",hint:"Ähnlich wie beim Menschen.",emoji:"🐒"},
  {q:"How many Weibchen befruchtet ein Alpha-Wolf im Jahr?",a:1,unit:"Weibchen",hint:"Wölfe sind weitgehend monogam.",emoji:"🐺"},
  {q:"How many cm lang ist der Penis eines Walrosses?",a:63,unit:"cm",hint:"Walrosse haben auch einen Baculum (Penisknochen).",emoji:"🦭"},
  {q:"How long dauert die Paarung bei Krokodilen in Minuten?",a:10,unit:"minutes",hint:"Im Wasser.",emoji:"🐊"},
  {q:"How many Junge hat ein Polarfuchs pro Wurf?",a:8,unit:"Junge",hint:"Bis zu 14 Junge.",emoji:"🦊"},
  {q:"How many Eier legt eine Hummel-Königin pro Sommer?",a:200,unit:"Eier",hint:"Nur eine Saison.",emoji:"🐝"},
  {q:"How long is der Penisknochen (Baculum) eines Eisbären in cm?",a:22,unit:"cm",hint:"Säugetiere mit Baculum haben keinen Erektions-Mechanismus.",emoji:"🐻‍❄️"},
  {q:"How many Mal per day paart sich ein Kaninchen?",a:10,unit:"times",hint:"'Sich fortpflanzen wie Kaninchen' ist kein Mythos.",emoji:"🐇"},
  {q:"How long trägt eine Hündin in Wochen?",a:9,unit:"weeks",hint:"63 Tage.",emoji:"🐕"},
  {q:"How many Eier legt eine Kohlmeise pro Gelege?",a:10,unit:"Eier",hint:"Bis zu 15 Eier pro Brut.",emoji:"🐦"},
  {q:"How many cm lang ist der Penisknochen eines Waschbären?",a:10,unit:"cm",hint:"Waschbären haben einen des größten Bacula relativ zum Körper.",emoji:"🦝"},
  {q:"How many Stunden dauert die Paarung von Schnecken?",a:6,unit:"hours",hint:"Schnecken sind Hermaphroditen.",emoji:"🐌"},
  {q:"How many Gramm wiegt ein Gorilla-Hoden?",a:30,unit:"grams",hint:"Im Vergleich zum Körper sehr klein.",emoji:"🦍"},
  {q:"How many Eier legt eine Seidenspinne pro Kokon?",a:400,unit:"Eier",hint:"Alle im selben Seidensack.",emoji:"🕷️"},
  {q:"How long paaren sich Fliegen in Minuten?",a:20,unit:"minutes",hint:"Stubenfliegen paaren sich relativ lange.",emoji:"🪰"},
  {q:"How many cm lang ist der Penis eines Schwertwals (Orca)?",a:180,unit:"cm",hint:"1,8 Meter – einfahrbarer Penis.",emoji:"🐋"},
  {q:"How many Junge hat ein Leopard pro Wurf?",a:2,unit:"Junge",hint:"1-4, meist 2-3 Jungtiere.",emoji:"🐆"},
  {q:"How long dauert die Trächtigkeit einer Tigerin in Tagen?",a:103,unit:"days",hint:"Knapp 3,5 Monate.",emoji:"🐯"},
  {q:"How long is der Penis eines Wiedehopfs relativ zum Körper?",a:50,unit:"% Körperlänge",hint:"Sehr lang relativ zum Vogelkörper.",emoji:"🐦"},
  {q:"How many cm lang ist der Eileiter einer Kuh?",a:25,unit:"cm",hint:"Verbindet Ovar mit Gebärmutter.",emoji:"🐄"},
  {q:"How long dauert die Paarung von Albatrosse in Stunden?",a:1,unit:"Stunde",hint:"Albatrosse sind monogam und zeremoniell.",emoji:"🦅"},
  {q:"How many Junge hat eine Fledermaus per year?",a:1,unit:"Junges",hint:"Meist nur ein Jungtier.",emoji:"🦇"},
  {q:"Wie lang paaren sich Löwen bei jedem Akt in Sekunden?",a:30,unit:"seconds",hint:"Kurz aber häufig – bis zu 20x daily.",emoji:"🦁"},
  {q:"How many cm hat der Penisknochen eines Eichhörnchens?",a:2,unit:"cm",hint:"Klein aber funktional.",emoji:"🐿️"},
  {q:"How long dauert die Paarung von Schlangen in Stunden?",a:6,unit:"hours",hint:"Manchmal tage- und wochenlang.",emoji:"🐍"},
  {q:"How many Eier legt eine Ameisen-Königin daily?",a:800,unit:"Eier",hint:"Über ihr gesamtes Leben million.",emoji:"🐜"},
  {q:"How many cm lang ist der Penis eines Orang-Utans?",a:4,unit:"cm",hint:"Ähnlich klein wie Gorillas.",emoji:"🦧"},
  {q:"How long dauert die Trächtigkeit eines Hamsters in Tagen?",a:16,unit:"days",hint:"Kürzeste Tragzeit der Säugetiere.",emoji:"🐹"},
  {q:"How many Junge hat eine Ratte pro Wurf?",a:8,unit:"Junge",hint:"5-12 – bis zu 8 Würfe per year.",emoji:"🐀"},
  {q:"How long is der Penis eines Hausschweins in cm?",a:50,unit:"cm",hint:"Korkenzieherförmig.",emoji:"🐷"},
  {q:"How many Eier legt eine Spinne insgesamt in ihrem Leben?",a:3000,unit:"Eier",hint:"Je nach Art hunderte bis tausende.",emoji:"🕷️"},
  {q:"How long paaren sich Hunde beim 'Tie' in Minuten?",a:20,unit:"minutes",hint:"Anschwellung hält sie zusammen.",emoji:"🐕"},
  {q:"How many cm lang ist der Uterus einer Katze?",a:10,unit:"cm",hint:"Zweizipfelig – kann verschiedene Väter tragen.",emoji:"🐱"},
  {q:"How long trägt eine Giraffe ihr Junges in Monaten?",a:15,unit:"months",hint:"Das Jungtier fällt 2m auf den Boden.",emoji:"🦒"},
  {q:"How many Junge hat ein Gepard pro Wurf?",a:3,unit:"Junge",hint:"1-8 – meist 3-5.",emoji:"🐆"},
  {q:"How long paaren sich Delfine?",a:12,unit:"seconds",hint:"Sehr kurz – dafür häufiger.",emoji:"🐬"},
  {q:"How many Eier legt ein Frosch pro Saison?",a:2000,unit:"Eier",hint:"Frösche legen Tausende kleiner Eier.",emoji:"🐸"},
  {q:"How many cm lang ist der Penisknochen eines Eisbären?",a:22,unit:"cm",hint:"Eines der längsten Bacula relativ zur Körpergröße.",emoji:"🐻‍❄️"},
  {q:"How long dauert die Trächtigkeit eines Gorillas in Tagen?",a:257,unit:"days",hint:"Ähnlich wie beim Menschen.",emoji:"🦍"},
  {q:"How long is die Vagina einer Stute in cm?",a:60,unit:"cm",hint:"Sehr lang – Geburt dauert kurz.",emoji:"🐴"},
  {q:"How many Junge hat eine Löwin pro Wurf?",a:3,unit:"Junge",hint:"1-4, meist 2-3.",emoji:"🦁"},
  {q:"How long paaren sich Tigerfrösche?",a:2,unit:"days",hint:"Amplexus – Umarmung kann Tage dauern.",emoji:"🐸"},
  {q:"How many Eier legt eine Wespenkönig pro Sommer?",a:300,unit:"Eier",hint:"Arbeiterinnen bauen das Nest für sie.",emoji:"🐝"},
  {q:"How long trägt ein Kaninchen sein Junges in Tagen?",a:31,unit:"days",hint:"Sehr kurze Tragzeit.",emoji:"🐇"},
  {q:"How many Junge hat ein Polarfuchs maximal pro Wurf?",a:14,unit:"Junge",hint:"Bei guter Lemmingversorgung.",emoji:"🦊"},
  {q:"How many cm lang ist der Penis eines Tapirs?",a:60,unit:"cm",hint:"Tapire haben einen Greif-Penis.",emoji:"🦏"},
  {q:"How long paaren sich Marder?",a:2,unit:"hours",hint:"Mehrere Stunden – lange Paarung.",emoji:"🦦"},
  {q:"How many Eier legt eine Seidenraupe?",a:500,unit:"Eier",hint:"Pro Weibchen im Leben.",emoji:"🪱"},
  {q:"How long is der Penisknochen eines Bibers?",a:5,unit:"cm",hint:"Biber haben einen Baculum.",emoji:"🦦"},
  {q:"How long trägt eine Stute ihr Junges in Tagen?",a:340,unit:"days",hint:"Ca. 11 Monate.",emoji:"🐴"},
  {q:"How many Junge hat eine Hyäne pro Wurf?",a:2,unit:"Junge",hint:"Manchmal 1-3.",emoji:"🐈"},
  {q:"How long is der Penis eines Flussdelphins?",a:40,unit:"cm",hint:"Amazonas-Delphin.",emoji:"🐬"},
  {q:"How long paaren sich Schildkröten in Stunden?",a:3,unit:"hours",hint:"Sehr ausdauernd.",emoji:"🐢"},
  {q:"How many Eier legt eine Schimpansen-Weibchen im Leben?",a:5,unit:"Junge",hint:"Schimpansen haben wenige Nachkommen.",emoji:"🐒"},
  {q:"How long is der Uterus einer Stute?",a:45,unit:"cm",hint:"Groß genug für das Fohlen.",emoji:"🐴"},
  {q:"How many Junge hat ein Wildschwein pro Wurf?",a:6,unit:"Frischlinge",hint:"4-8 – je nach Nahrungsangebot.",emoji:"🐗"},
  {q:"How long is der Penis eines Zwergschimpansen (Bonobo)?",a:10,unit:"cm",hint:"Größer als Gorilla, kleiner als Mensch.",emoji:"🐒"},
  {q:"How many Eier legt eine Forelle pro Laichsaison?",a:2000,unit:"Eier",hint:"Je nach Größe bis 10.000.",emoji:"🐟"},
  {q:"How long trägt ein Löwe sein Junges in Tagen?",a:110,unit:"days",hint:"Löwen führen Einzel-Würfe.",emoji:"🦁"},
  {q:"How many Junge hat ein Erdferkel per year?",a:1,unit:"Junges",hint:"Nur ein Jungtier pro Saison.",emoji:"🐷"},
  {q:"How long is die Vagina einer Gorilla in cm?",a:9,unit:"cm",hint:"Proportional kleiner als beim Menschen.",emoji:"🦍"},
  {q:"How long paaren sich Polarfüchse?",a:20,unit:"minutes",hint:"In der kurzen arktischen Paarungszeit.",emoji:"🦊"},
  {q:"How many Eier legt ein Oktopus insgesamt?",a:100000,unit:"Eier",hint:"Und bewacht sie bis sie schlüpfen – dann stirbt sie.",emoji:"🐙"},
  {q:"How long is der Penisknochen eines Hundes (Baculum)?",a:10,unit:"cm",hint:"Hunde haben einen Penisknochen.",emoji:"🐕"},
  {q:"How many Junge hat ein Leopard im Leben?",a:8,unit:"Junge",hint:"Alle 2 Jahre ein Wurf über 16 Jahre.",emoji:"🐆"},
  {q:"How long is die Klitoris einer Weibchen-Binturong?",a:5,unit:"cm",hint:"Binturongs sind bekannt für diese Eigenschaft.",emoji:"🐱"},
  {q:"How long trägt eine Ratte ihr Junges in Tagen?",a:22,unit:"days",hint:"Sehr kurze Tragzeit.",emoji:"🐀"},
  {q:"How many Eier legt eine Schmetterlingsgattung daily?",a:20,unit:"Eier",hint:"Über ihr ganzes Leben meist 200.",emoji:"🦋"},
  {q:"How long is der Rüssel eines Elefanten – auch als Sinnesorgan beim Paaren?",a:200,unit:"cm",hint:"Elefanten berühren sich beim Paaren mit dem Rüssel.",emoji:"🐘"},
  {q:"How many Junge hat ein Waschbär pro Wurf?",a:4,unit:"Junge",hint:"3-5 Junge im Frühling.",emoji:"🦝"},
  {q:"How long paaren sich Löffelenten?",a:2,unit:"minutes",hint:"Enten paaren sich oft mit Gewalt.",emoji:"🦆"},
  {q:"How long is der Penis eines Bullen in cm?",a:90,unit:"cm",hint:"Retraktormuskel ermöglicht S-förmige Lagerung.",emoji:"🐂"},
  {q:"How many Eier legt eine Stubenfliege in ihrem kurzen Leben?",a:500,unit:"Eier",hint:"In Gruppen von 75-150 Stück.",emoji:"🪰"},
  {q:"How many Tage ist eine Stute im Jahr rossig?",a:15,unit:"days",hint:"Mehrmals im Sommer.",emoji:"🐴"},
  {q:"How long is der Uterus einer Hauskatze in cm?",a:8,unit:"cm",hint:"Zweihörnig – kann verschiedene Väter haben.",emoji:"🐱"},
  {q:"How many Junge hat ein Opossum gleichzeitig im Beutel?",a:13,unit:"Junge",hint:"Zitzen – so viele Junge können überleben.",emoji:"🐀"},
  {q:"How long dauert die Paarung von Orcas?",a:5,unit:"minutes",hint:"Im Wasser – sehr selten beobachtet.",emoji:"🐋"},
  {q:"How long is der Gebärmutterhals einer Kuh?",a:10,unit:"cm",hint:"Wichtig für künstliche Besamung.",emoji:"🐄"},
  {q:"How many Junge hat eine Fischotter pro Wurf?",a:3,unit:"Junge",hint:"1-5, meist 3.",emoji:"🦦"},
  {q:"How long paaren sich Geparden?",a:10,unit:"minutes",hint:"Mehrmals daily in der Paarungszeit.",emoji:"🐆"},
  {q:"How many Eier legt eine Gottesanbeterin nach der Paarung?",a:200,unit:"Eier",hint:"In einem Oothek-Kokon.",emoji:"🦗"},
  {q:"How long is der Penisknochen einer Robbe (Baculum) in cm?",a:35,unit:"cm",hint:"Robbenmänner haben sehr lange Bacula.",emoji:"🦭"},
  {q:"How long trägt eine Kojote ihr Junges in Tagen?",a:63,unit:"days",hint:"Gleich wie Hunde.",emoji:"🐺"},
  {q:"How many Junge hat ein Nashorn pro Wurf?",a:1,unit:"Junges",hint:"Immer Einzelgeburten.",emoji:"🦏"},
  {q:"How long is der Baculum (Penisknochen) eines Waschbären in cm?",a:10,unit:"cm",hint:"Relativ zur Körpergröße sehr lang.",emoji:"🦝"},
  {q:"How many Eier legt ein Walhai pro Saison?",a:300,unit:"Eier",hint:"Walhaie sind lebendgebärend – aber legen Eier vor der Geburt.",emoji:"🦈"},
  {q:"How long paaren sich Hauskatzen?",a:5,unit:"minutes",hint:"Mehrmals daily – sehr laut.",emoji:"🐱"},
  {q:"How long is der Uterus einer Stute in cm?",a:50,unit:"cm",hint:"Groß genug für ein Fohlen.",emoji:"🐴"},
  {q:"How many Junge hat ein Hermelin pro Wurf?",a:6,unit:"Junge",hint:"4-9 Junge.",emoji:"🦦"},
  {q:"How many Eier legt eine Zauneidechse pro Saison?",a:8,unit:"Eier",hint:"6-12 Eier.",emoji:"🦎"},
  {q:"How long is die Vagina eines Gorilla-Weibchens?",a:9,unit:"cm",hint:"Ähnlich wie beim Menschen.",emoji:"🦍"},
  {q:"How long dauert die Trächtigkeit eines Schafes in Tagen?",a:147,unit:"days",hint:"Etwa 5 Monate.",emoji:"🐑"},
  {q:"How many Junge hat ein Eisbär pro Wurf?",a:2,unit:"Junge",hint:"Fast immer Zwillinge.",emoji:"🐻‍❄️"},
  {q:"How long is der Penis eines Hauskatze (Kater)?",a:1.5,unit:"cm",hint:"Sehr klein mit stacheligen Widerhaken.",emoji:"🐱"},
  {q:"How long paaren sich Wildschweine?",a:5,unit:"minutes",hint:"Schnell aber häufig.",emoji:"🐗"},
  {q:"How many Eier legt eine Hornisse pro Sommer?",a:500,unit:"Eier",hint:"Die Königin allein.",emoji:"🐝"},
  {q:"How long is der Uterus einer Menschenaffen-Weibchen?",a:8,unit:"cm",hint:"Ähnlich wie bei uns.",emoji:"🦍"},
  {q:"How many Junge hat ein Braunbär pro Wurf?",a:2,unit:"Junge",hint:"1-4, meist 2.",emoji:"🐻"},
  {q:"How long trägt eine Katze ihr Junges in Wochen?",a:9,unit:"weeks",hint:"63-67 Tage.",emoji:"🐱"},
];
