// 🍺 FOOD & DRINK – English
export default [
  {q:"How many Kalorien hat ein Big Mac?",a:563,unit:"kcal",hint:"Davon kommen 257 kcal aus dem Fett.",emoji:"🍔"},
  {q:"How many Liter Bier wurden beim Oktoberfest 2023 getrunken?",a:7300000,unit:"liters",hint:"Das Oktoberfest ist das größte Volksfest der Welt.",emoji:"🍺"},
  {q:"How many Gramm Zucker in einer Dose Cola (330ml)?",a:35,unit:"grams",hint:"Das sind etwa 7 Teelöffel Zucker.",emoji:"🥤"},
  {q:"How many Tonnen Schokolade isst Deutschland per year?",a:900000,unit:"tons",hint:"Weltmeister im Schokoladenkonsum pro Kopf.",emoji:"🍫"},
  {q:"How many Liter Milch braucht man für 1 kg Käse?",a:10,unit:"liters",hint:"Je nach Sorte 8–12 Liter Milch.",emoji:"🧀"},
  {q:"How many Monate reift ein echter Parmesan mindestens?",a:24,unit:"months",hint:"Premium-Parmesan reift bis zu 5 Jahre.",emoji:"🧀"},
  {q:"How many Körner Kaffee braucht man für einen Espresso?",a:50,unit:"Körner",hint:"Ein Kaffeebaum produziert per year ~500g Kaffee.",emoji:"☕"},
  {q:"How many Liter Wein trinkt ein Franzose per year?",a:45,unit:"liters",hint:"Frankreich führt worldwide den Pro-Kopf-Weinkonsum.",emoji:"🍷"},
  {q:"How many kg Pasta isst ein Italiener on average per year?",a:23,unit:"kg",hint:"Italien führt worldwide den Pastakonsum.",emoji:"🍝"},
  {q:"How high ist der Wasseranteil in einer Gurke in percent?",a:97,unit:"%",hint:"Gurken bestehen fast nur aus Wasser.",emoji:"🥒"},
  {q:"How many Liter Kaffee trinken Finnen pro Kopf per year?",a:12,unit:"kg",hint:"Finnland ist Weltmeister im Kaffeeverbrauch.",emoji:"☕"},
  {q:"How many Gramm Butter enthält ein original Croissant?",a:50,unit:"grams",hint:"Der hohe Butteranteil macht die blättrige Textur möglich.",emoji:"🥐"},
  {q:"How many percent Fettgehalt hat Gänsestopfleber (Foie Gras)?",a:50,unit:"%",hint:"Eines der kalorienreichsten Lebensmittel.",emoji:"🍴"},
  {q:"How many Liter Wasser braucht man für 1 kg Rindfleisch?",a:15000,unit:"liters",hint:"Rindfleisch hat den größten Wasserverbrauch aller Nahrungsmittel.",emoji:"🥩"},
  {q:"How many Jahre ist der älteste bekannte Wein alt (Speyer-Wein)?",a:1650,unit:"years",hint:"Die Flasche wurde 1867 in einem römischen Grab gefunden.",emoji:"🍷"},
  {q:"How many Gramm wiegt eine Kaviar-Perle?",a:50,unit:"mg",hint:"Beluga-Kaviar kostet bis zu 25.000€ pro kg.",emoji:"🐟"},
  {q:"How many Kalorien hat ein Teelöffel Olivenöl?",a:40,unit:"kcal",hint:"Gesund – aber kalorienreich wie alle Fette.",emoji:"🫒"},
  {q:"How many Gramm Salz isst ein Deutscher daily?",a:10,unit:"grams",hint:"Empfohlen werden maximal 6 Gramm.",emoji:"🧂"},
  {q:"Wie scharf ist der Carolina Reaper in million Scoville?",a:2.2,unit:"Mio. Scoville",hint:"Das schärfste Chili der Welt.",emoji:"🌶️"},
  {q:"How many Stunden muss Jamon Iberico mindestens reifen?",a:8760,unit:"hours",hint:"Das sind mindestens 3 Jahre.",emoji:"🥩"},
  {q:"How many Würste werden beim Nürnberger Christkindlesmarkt gegessen?",a:2000000,unit:"Würste",hint:"Nürnberger Bratwürste sind die kleinsten deutschen Würste.",emoji:"🌭"},
  {q:"Wie alt kann ein Wein maximal werden und noch trinkbar sein in Jahren?",a:200,unit:"years",hint:"Ein 1811er Château d'Yquem wurde als exzellent bewertet.",emoji:"🍷"},
  {q:"How much kostet Safran pro kg in Euro?",a:10000,unit:"€/kg",hint:"Safran ist das teuerste Gewürz der Welt.",emoji:"🌺"},
  {q:"How many Pizzen werden daily worldwide gegessen in million?",a:5,unit:"million",hint:"Die USA essen allein 3 billion Pizzen per year.",emoji:"🍕"},
  {q:"How many Kalorien hat ein Glas Rotwein (200ml)?",a:170,unit:"kcal",hint:"Wein hat mehr Kalorien als die meisten denken.",emoji:"🍷"},
  {q:"How many Stunden dauert die Herstellung von echtem Champagner mindestens?",a:12960,unit:"hours",hint:"Das sind mindestens 18 Monate Reifung.",emoji:"🥂"},
  {q:"How many Gramm Zucker hat ein Glas Orangensaft (200ml)?",a:20,unit:"grams",hint:"Fast so viel wie Cola – oft unterschätzt.",emoji:"🍊"},
  {q:"How many Minuten per day massiert man Kobe-Rind?",a:60,unit:"minutes",hint:"Sie werden tatsächlich massiert und mit Bier gefüttert.",emoji:"🥩"},
  {q:"How much percent des Wasabis im Restaurant ist echt?",a:1,unit:"%",hint:"99% ist gefälschter Wasabi aus Meerrettich und Farbe.",emoji:"🍣"},
  {q:"How many billion Liter Bier braut Deutschland per year?",a:8,unit:"billion liters",hint:"billion Liter – Platz 5 worldwide.",emoji:"🍺"},
  {q:"How many kcal hat eine durchschnittliche Currywurst?",a:350,unit:"kcal",hint:"Mit Pommes kommen nochmal 400 kcal dazu.",emoji:"🌭"},
  {q:"How many Milliliter Espresso enthält eine Standard-Tasse?",a:25,unit:"ml",hint:"Ein Doppio hat 50 ml.",emoji:"☕"},
  {q:"How many kg Mehl verbraucht Deutschland pro Kopf im Jahr?",a:86,unit:"kg",hint:"Wir sind eine Brotnation.",emoji:"🍞"},
  {q:"How many Liter Wasser braucht man für 1 Liter Bier?",a:300,unit:"liters",hint:"Inklusive Anbau, Verarbeitung und Kühlung.",emoji:"🍺"},
  {q:"How many Kalorien hat ein Döner Kebab?",a:850,unit:"kcal",hint:"Der Döner ist Deutschlands beliebtestes Fast Food.",emoji:"🌯"},
  {q:"How many billion Liter Wein produziert Frankreich per year?",a:4,unit:"billion liters",hint:"billion Liter – Platz 2 worldwide nach Italien.",emoji:"🍷"},
  {q:"How many Gramm Eiweiß hat ein Ei?",a:6,unit:"grams",hint:"Ein Hühnerei hat ~6g Protein.",emoji:"🥚"},
  {q:"How many Stunden fermentiert Kimchi traditionell?",a:24,unit:"hours",hint:"Manchmal auch Monate – je nach Rezept.",emoji:"🥬"},
  {q:"How many Kalorien hat 100g dunkle Schokolade?",a:550,unit:"kcal",hint:"Viel Fett und Zucker – aber auch Antioxidantien.",emoji:"🍫"},
  {q:"How many Liter Tee trinken Briten per day (pro Person)?",a:3,unit:"Tassen",hint:"Briten trinken annually 60 billion Tassen Tee.",emoji:"🫖"},
  {q:"How many Gramm Zucker hat Ketchup pro 100g?",a:22,unit:"grams",hint:"Ketchup enthält überraschend viel Zucker.",emoji:"🍅"},
  {q:"How many Liter Wasser braucht man für 1 kg Mandeln?",a:15000,unit:"liters",hint:"Mandeln sind extrem wasserintensiv.",emoji:"🌰"},
  {q:"How many billion Eier werden in Deutschland per year gegessen?",a:15,unit:"billion",hint:"Etwa 180 Eier pro Person und Jahr.",emoji:"🥚"},
  {q:"How many kcal hat eine Packung Chips (200g)?",a:1080,unit:"kcal",hint:"Über die Hälfte des Tagesbedarfs in einem Snack.",emoji:"🍟"},
  {q:"How many Monate fermentiert echter Roquefort-Käse?",a:3,unit:"months",hint:"In speziellen Höhlen bei konstanter Temperatur.",emoji:"🧀"},
  {q:"How many Gramm Salz enthält ein normales Brot (700g)?",a:10,unit:"grams",hint:"Brot ist eine der größten Salzquellen.",emoji:"🍞"},
  {q:"How many Liter Bier hat der durchschnittliche Bayer per year?",a:150,unit:"liters",hint:"Bayern führt den deutschen Bierkonsum an.",emoji:"🍺"},
  {q:"How many Kalorien hat ein Schnitzel Wiener Art (ohne Beilagen)?",a:650,unit:"kcal",hint:"Mit Kartoffelsalat kommen nochmal 300 kcal dazu.",emoji:"🥩"},
  {q:"How many Tonnen Obst isst Deutschland per year?",a:5000000,unit:"tons",hint:"Äpfel sind das beliebteste Obst.",emoji:"🍎"},
  {q:"How many percent Alkohol hat Standard-Bier?",a:5,unit:"%",hint:"Starkbiere haben bis zu 14% Alkohol.",emoji:"🍺"},
  {q:"How many Gramm Kohlenhydrate hat 100g Weißbrot?",a:50,unit:"grams",hint:"Weißbrot hat fast so viele Kohlenhydrate wie Zucker.",emoji:"🍞"},
  {q:"How many Stunden dauert die Fermentation von echtem Sourdough?",a:48,unit:"hours",hint:"Echter Sauerteig braucht Zeit für Geschmack.",emoji:"🍞"},
  {q:"How many Liter Wasser braucht man für 1 kg Avocado?",a:1000,unit:"liters",hint:"Avocados sind sehr wasserintensiv.",emoji:"🥑"},
  {q:"How many kcal hat eine Tafel Vollmilchschokolade (100g)?",a:535,unit:"kcal",hint:"Milchschokolade hat etwas weniger als dunkle.",emoji:"🍫"},
  {q:"How many Tonnen Bananen importiert Deutschland per year?",a:1000000,unit:"tons",hint:"Banane ist die meistgekaufte Frucht Deutschlands.",emoji:"🍌"},
  {q:"How many Gramm Fett hat 100g Butter?",a:83,unit:"grams",hint:"Butter ist fast pures Fett.",emoji:"🧈"},
  {q:"How many billion Würste werden in Deutschland per year produziert?",a:1500,unit:"million",hint:"Deutschland ist Weltmeister in Wurstvielfalt.",emoji:"🌭"},
  {q:"How many kcal hat ein Döner in einem normalen Fladenbrot?",a:1000,unit:"kcal",hint:"Ein Döner kann über die Hälfte des Tagesbedarfs decken.",emoji:"🌯"},
  {q:"How many Liter Wasser braucht man für 1 kg Schokolade?",a:17196,unit:"liters",hint:"Die wasserintensivste Süßigkeit.",emoji:"🍫"},
  {q:"How many Stunden reift ein Gouda-Käse mindestens?",a:720,unit:"hours",hint:"30 Tage für jungen Gouda – alter Gouda reift Monate.",emoji:"🧀"},
  {q:"How many Kalorien hat eine Maß Bier (1 Liter)?",a:430,unit:"kcal",hint:"Bier hat pro 100ml etwa 43 kcal.",emoji:"🍺"},
  {q:"How many Gramm Protein hat 100g Hühnchen (Brust)?",a:31,unit:"grams",hint:"Hühnchenbrust ist eine der eiweißreichsten Quellen.",emoji:"🍗"},
  {q:"How many Tonnen Kaffee trinkt Deutschland per year?",a:500000,unit:"tons",hint:"Kaffee ist das Lieblingsgetränk der Deutschen.",emoji:"☕"},
  {q:"How many kcal hat eine normale Portion Pommes Frites (150g)?",a:450,unit:"kcal",hint:"Mit Ketchup und Mayonnaise deutlich mehr.",emoji:"🍟"},
  {q:"How many Liter Wein trinken Deutsche pro Kopf per year?",a:20,unit:"liters",hint:"Weniger als Franzosen oder Portugiesen.",emoji:"🍷"},
  {q:"How many Gramm Zucker hat ein Glas Eistee (250ml)?",a:25,unit:"grams",hint:"Eistee ist eine versteckte Zuckerfalle.",emoji:"🍵"},
  {q:"How many kcal hat ein normales Croissant?",a:250,unit:"kcal",hint:"Kleines Gebäck mit vielen Kalorien.",emoji:"🥐"},
  {q:"How many Monate fermentiert echter Miso?",a:12,unit:"months",hint:"Traditioneller Miso reift 1-3 Jahre.",emoji:"🫙"},
  {q:"How many Gramm Mehl braucht man für eine Pizza (30cm)?",a:250,unit:"grams",hint:"Plus Tomatensauce, Käse und Belag.",emoji:"🍕"},
  {q:"How many Liter Wasser braucht man für 1 kg Schweinefleisch?",a:5988,unit:"liters",hint:"Deutlich weniger als Rind, aber immer noch viel.",emoji:"🥩"},
  {q:"How many kcal hat ein Stück Schwarzwälder Kirschtorte?",a:450,unit:"kcal",hint:"Sahne, Schokolade und Kirschwasser.",emoji:"🎂"},
  {q:"How many Gramm Capsaicin enthält ein Jalapeño?",a:100,unit:"mg",hint:"Capsaicin ist der Wirkstoff der Schärfe.",emoji:"🌶️"},
  {q:"How many Tonnen Erdbeeren produziert Deutschland per year?",a:100000,unit:"tons",hint:"Bayern ist größter Produzent.",emoji:"🍓"},
  {q:"How many Stunden braucht ein Käse um zu schimmeln (Camembert)?",a:168,unit:"hours",hint:"7 Tage für die charakteristische weiße Rinde.",emoji:"🧀"},
  {q:"How many Liter Wasser braucht man für 1 Tasse Kaffee?",a:140,unit:"liters",hint:"Inklusive Anbau und Verarbeitung.",emoji:"☕"},
  {q:"How many Kalorien hat ein Hamburger (ohne Pommes)?",a:500,unit:"kcal",hint:"Je nach Belag mehr oder weniger.",emoji:"🍔"},
  {q:"How many Gramm Omega-3 hat 100g Lachs?",a:2.5,unit:"grams",hint:"Lachs ist eine der besten Omega-3-Quellen.",emoji:"🐟"},
  {q:"How many million Hektoliter Bier trinkt die Welt per year?",a:1900,unit:"Mio. Hektoliter",hint:"China ist der größte Biermarkt worldwide.",emoji:"🍺"},
  {q:"How many kcal hat 1 Gramm Alkohol?",a:7,unit:"kcal",hint:"Mehr als Zucker (4 kcal) – aber weniger als Fett (9 kcal).",emoji:"🍺"},
  {q:"How many Tonnen Süßigkeiten isst Deutschland per year?",a:800000,unit:"tons",hint:"Haribo ist das bekannteste deutsche Süßwareunternehmen.",emoji:"🍬"},
  {q:"How many Stunden dauert das Räuchern eines Schinkens?",a:48,unit:"hours",hint:"Echtes Kalträuchern dauert Tage.",emoji:"🥩"},
  {q:"How many Gramm Zucker hat ein Päckchen Gummibärchen (200g)?",a:140,unit:"grams",hint:"70% Zucker – Gummibärchen sind fast purer Zucker.",emoji:"🐻"},
  {q:"How many kcal hat ein Bier (0,5l, Pils)?",a:215,unit:"kcal",hint:"Ein Bier hat mehr Kalorien als ein Apfel.",emoji:"🍺"},
  {q:"How many Liter Wasser braucht man für 1 kg Käse?",a:5000,unit:"liters",hint:"Inklusive der Milch die man braucht.",emoji:"🧀"},
  {q:"How many Gramm hat ein Standard-Würfel Zucker?",a:4,unit:"grams",hint:"16 kcal pro Würfel.",emoji:"🍬"},
  {q:"How many Tonnen Tomaten produziert Italien per year?",a:5000000,unit:"tons",hint:"Größter Tomatenproduzent Europas.",emoji:"🍅"},
  {q:"How many Milliliter hat ein Standard-Shot Schnaps?",a:40,unit:"ml",hint:"In Deutschland sind 2 cl der Standard.",emoji:"🥃"},
  {q:"How many kcal hat 100g Erdnussbutter?",a:589,unit:"kcal",hint:"Sehr kalorienreich – aber voller Proteine.",emoji:"🥜"},
  {q:"How many Gramm Eiweiß hat 100g Quark (Magerquark)?",a:12,unit:"grams",hint:"Magerquark ist eine günstige Proteinquelle.",emoji:"🥛"},
  {q:"How many Liter Wasser braucht man für 1 kg Tomaten?",a:183,unit:"liters",hint:"Deutlich weniger als Fleisch.",emoji:"🍅"},
  {q:"How many Kalorien hat 100g Brokkoli?",a:34,unit:"kcal",hint:"Eines der nährstoffreichsten Gemüse.",emoji:"🥦"},
  {q:"How many Tonnen Wurst produziert Deutschland per year?",a:1500000,unit:"tons",hint:"1,5 million Tonnen – über 1500 Sorten.",emoji:"🌭"},
  {q:"How many Stunden reift echter Roquefort in Höhlen?",a:2160,unit:"hours",hint:"90 Tage in Combalou-Höhlen.",emoji:"🧀"},
  {q:"How many kcal hat ein Brezn (80g)?",a:270,unit:"kcal",hint:"Mit Butter nochmal 100 kcal mehr.",emoji:"🥨"},
  {q:"How many Gramm Zucker hat 100ml Fruchtsaft?",a:10,unit:"grams",hint:"Naturtrüber Saft enthält genauso viel Zucker wie Cola.",emoji:"🍹"},
  {q:"How many billion Eier produziert Deutschland per year?",a:15,unit:"billion",hint:"Trotzdem importieren wir noch Eier.",emoji:"🥚"},
  {q:"How many kcal hat ein Weißwurst-Frühstück (2 Würste + Brezel + Bier)?",a:900,unit:"kcal",hint:"Ein bayerisches Frühstück ist keine leichte Mahlzeit.",emoji:"🍺"},
  {q:"How many Liter Wasser braucht man für 1 Liter Orangensaft?",a:1000,unit:"liters",hint:"Anbau, Transport und Verarbeitung addieren sich.",emoji:"🍊"},
  {q:"How many Gramm Fett hat ein Döner?",a:30,unit:"grams",hint:"Je nach Zubereitung 20-50g Fett.",emoji:"🌯"},
  {q:"How many Tonnen Honig produziert Deutschland per year?",a:25000,unit:"tons",hint:"Trotzdem importieren wir deutlich mehr.",emoji:"🍯"},
  {q:"How many kcal hat ein Stück Käsekuchen (100g)?",a:320,unit:"kcal",hint:"Eines der kalorienreichsten deutschen Desserts.",emoji:"🎂"},
  {q:"How many Gramm Calcium hat 100ml Milch?",a:120,unit:"grams",hint:"Milch ist die beste Calciumquelle.",emoji:"🥛"},
  {q:"How many Stunden fermentiert echter Balsamico aus Modena?",a:87600,unit:"hours",hint:"10 Jahre – manchmal sogar 25 Jahre.",emoji:"🫙"},
  {q:"How many million Liter Champagner werden worldwide per year produziert?",a:300,unit:"million liters",hint:"million Liter aus nur einer Region Frankreichs.",emoji:"🥂"},
  {q:"How many kcal hat 100g Avocado?",a:160,unit:"kcal",hint:"Reich an gesunden Fetten.",emoji:"🥑"},
  {q:"How many Tonnen Kartoffeln isst Deutschland per year?",a:4000000,unit:"tons",hint:"Über 50 kg pro Person per year.",emoji:"🥔"},
  {q:"How many Gramm Zucker hat 100g Ketchup?",a:22,unit:"grams",hint:"Ketchup ist fast ein Viertel Zucker.",emoji:"🍅"},
  {q:"How many kcal hat ein Sauerbraten mit Knödel?",a:1200,unit:"kcal",hint:"Ein echtes deutsches Festmahl.",emoji:"🥩"},
  {q:"How many Milliliter fasst ein Standard-Weinglas?",a:200,unit:"ml",hint:"Ein normales Weinglas – nicht bis zum Rand.",emoji:"🍷"},
  {q:"How many Tonnen Fleisch isst Deutschland per year?",a:7500000,unit:"tons",hint:"Etwa 90 kg Fleisch pro Person per year.",emoji:"🥩"},
  {q:"How many kcal hat ein Lebkuchen (35g)?",a:130,unit:"kcal",hint:"Weihnachtsgebäck mit versteckten Kalorien.",emoji:"🍪"},
  {q:"How many Gramm Protein hat 100g Linsen (gekocht)?",a:9,unit:"grams",hint:"Linsen sind eine gute pflanzliche Proteinquelle.",emoji:"🫘"},
  {q:"How many Liter Wasser braucht man für 1 kg Reis?",a:2500,unit:"liters",hint:"Nassreis-Anbau verbraucht enorm viel Wasser.",emoji:"🍚"},
  {q:"How many kcal hat 100g Walnüsse?",a:654,unit:"kcal",hint:"Sehr kalorienreich aber voller gesunder Fette.",emoji:"🌰"},
  {q:"How many Gramm Zucker hat eine Flasche Energydrink (250ml)?",a:27,unit:"grams",hint:"Ähnlich wie Cola – plus Koffein.",emoji:"⚡"},
  {q:"How many Tonnen Zucker konsumiert Deutschland per year?",a:3000000,unit:"tons",hint:"3 million Tonnen – über 35 kg pro Person.",emoji:"🍬"},
  {q:"How many kcal hat ein Apfelstrudel (100g)?",a:250,unit:"kcal",hint:"Wiener Spezialität mit Butter und Zucker.",emoji:"🥐"},
  {q:"How many Milliliter hat ein Standard-Espresso?",a:25,unit:"ml",hint:"Klein aber stark – 7g Kaffeemehl.",emoji:"☕"},
  {q:"How many Gramm Kohlenhydrate hat 100g Kartoffeln?",a:17,unit:"grams",hint:"Weniger als gedacht – Fett in Pommes ist das Problem.",emoji:"🥔"},
  {q:"How many Liter Wein trinkt die Welt per year (billion)?",a:26,unit:"billion liters",hint:"billion Liter – steigende Tendenz.",emoji:"🍷"},
  {q:"How many kcal hat 100g Vollmilch (3,5%)?",a:64,unit:"kcal",hint:"Milch ist kalorienärmer als die meisten denken.",emoji:"🥛"},
  {q:"How many Gramm Zucker hat 100g Joghurt (Fruchtjoghurt)?",a:13,unit:"grams",hint:"Fruchtjoghurt hat überraschend viel Zucker.",emoji:"🫙"},
  {q:"How many million Tonnen Weizen produziert Deutschland per year?",a:22,unit:"million tons",hint:"Deutschland ist einer der größten Weizenproduzenten Europas.",emoji:"🌾"},
  {q:"How many kcal hat eine Brezel mit Butter?",a:400,unit:"kcal",hint:"Eine beliebte bayrische Snack-Kombination.",emoji:"🥨"},
  {q:"How many Gramm Protein hat 100g Thunfisch (aus der Dose)?",a:26,unit:"grams",hint:"Einer der günstigsten Proteinsupplier.",emoji:"🐟"},
  {q:"How many Liter Wasser braucht man für 1 Tasse Tee?",a:30,unit:"liters",hint:"Deutlich weniger als Kaffee.",emoji:"🫖"},
  {q:"How many kcal hat 100g Hüttenkäse?",a:98,unit:"kcal",hint:"Sehr eiweißreich und kalorienarm.",emoji:"🧀"},
  {q:"How many Gramm Zucker hat ein Gummibärchen?",a:2,unit:"grams",hint:"Pro Stück – eine Packung hat 140g Zucker.",emoji:"🐻"},
  {q:"How many million Tonnen Lebensmittel verschwendet Deutschland per year?",a:12,unit:"million tons",hint:"Ein Drittel aller produzierten Lebensmittel landet im Müll.",emoji:"🗑️"},
  {q:"How many kcal hat ein Brot (Scheibe, 50g)?",a:120,unit:"kcal",hint:"Abhängig von der Brotsorte.",emoji:"🍞"},
  {q:"How many Gramm Eiweiß hat ein Hühnerei?",a:6,unit:"grams",hint:"Eier haben das hochwertigste Protein aller Lebensmittel.",emoji:"🥚"},
  {q:"How many million Liter Cognac und Armagnac destilliert Frankreich per year?",a:200,unit:"million liters",hint:"million Liter Cognac und Armagnac.",emoji:"🥃"},
  {q:"How many kcal hat 100g Olivenöl?",a:884,unit:"kcal",hint:"Das kalorienreichste gängige Lebensmittel.",emoji:"🫒"},
  {q:"How many Gramm Zucker hat 100ml Orangensaft (frisch gepresst)?",a:8,unit:"grams",hint:"Frisch gepresst hat etwas weniger Zucker als Fertigsaft.",emoji:"🍊"},
  {q:"How many Tonnen Schinken produziert Spanien per year?",a:350000,unit:"tons",hint:"Spanien ist Weltmeister im Schinkenkonsum.",emoji:"🥩"},
  {q:"How many kcal hat ein Stück Tiramisu (100g)?",a:400,unit:"kcal",hint:"Mascarpone, Eier und Zucker machen es kalorienreich.",emoji:"🎂"},
  {q:"How many Gramm Fett hat 100g Cheddar-Käse?",a:34,unit:"grams",hint:"Hartkäse sind generell sehr fettreich.",emoji:"🧀"},
  {q:"How many Liter Schnaps trinkt ein Österreicher per year?",a:5,unit:"liters",hint:"Österreich führt Europa im Schnapskonsum an.",emoji:"🥃"},
  {q:"How many kcal hat 100g Lachs (geräuchert)?",a:180,unit:"kcal",hint:"Lachs hat mehr Kalorien als mageres Fleisch.",emoji:"🐟"},
  {q:"How many Gramm Protein hat 100g Tempeh?",a:19,unit:"grams",hint:"Tempeh hat mehr Protein als Tofu.",emoji:"🫘"},
  {q:"How many million Tonnen Zucker isst die Welt per year?",a:200,unit:"million tons",hint:"million Tonnen – steigend.",emoji:"🍬"},
  {q:"How many kcal hat ein Gulasch mit Reis?",a:800,unit:"kcal",hint:"Ein sättigendes Mittagessen.",emoji:"🍲"},
  {q:"How many Gramm Kohlenhydrate hat 100g Weißbrot?",a:50,unit:"grams",hint:"Weißbrot hat einen hohen glykämischen Index.",emoji:"🍞"},
  {q:"How many million Tonnen Fisch werden worldwide per year gegessen?",a:90,unit:"million tons",hint:"million Tonnen – die Ozeane werden überfischt.",emoji:"🐟"},
  {q:"How many kcal hat 100g Leberwurst?",a:330,unit:"kcal",hint:"Sehr fett- und kalorienreich.",emoji:"🌭"},
  {q:"How many Gramm Ballaststoffe hat 100g Vollkornbrot?",a:7,unit:"grams",hint:"Deutlich mehr als Weißbrot (2g).",emoji:"🍞"},
  {q:"How many Liter Trinkwasser verbraucht ein Deutscher daily?",a:124,unit:"liters",hint:"Davon trinkt man nur 1-2 Liter direkt.",emoji:"💧"},
  {q:"How many kcal hat ein Stück Schwarzbrot (50g)?",a:108,unit:"kcal",hint:"Kalorienärmer als Weißbrot.",emoji:"🍞"},
  {q:"How many Gramm Zucker hat 100ml Cola?",a:10.6,unit:"grams",hint:"Über 10% Zucker in jedem Schluck.",emoji:"🥤"},
  {q:"How many Tonnen Käse produziert Deutschland per year?",a:2000000,unit:"tons",hint:"Deutschland ist weltführend in der Käseproduktion.",emoji:"🧀"},
  {q:"How many kcal hat 100g Baklava?",a:430,unit:"kcal",hint:"Süßes türkisches Gebäck aus Blätterteig und Honig.",emoji:"🍯"},
  {q:"How many Gramm Eiweiß hat 100g Rinderfilet?",a:22,unit:"grams",hint:"Mageres Rindfleisch ist eine hervorragende Proteinquelle.",emoji:"🥩"},
  {q:"How many million Liter Wodka trinkt Russland per year?",a:1600,unit:"million liters",hint:"Russland führt worldwide den Wodkakonsum.",emoji:"🥃"},
  {q:"How many kcal hat ein Stück Apfelkuchen (100g)?",a:290,unit:"kcal",hint:"Mit Sahne nochmal 100 kcal mehr.",emoji:"🥧"},
  {q:"How many Gramm Fett hat 100g Camembert?",a:24,unit:"grams",hint:"Der Fettgehalt variiert je nach Reifegrad.",emoji:"🧀"},
  {q:"How many Liter Wasser braucht man für 1 kg Soja?",a:1000,unit:"liters",hint:"Weniger als tierische Produkte.",emoji:"🫘"},
  {q:"How many kcal hat ein Franzbrötchen (80g)?",a:320,unit:"kcal",hint:"Hamburger Spezialität mit Butter und Zimt.",emoji:"🥐"},
  {q:"How many Gramm Kohlenhydrate hat 100g Nudeln (ungekocht)?",a:70,unit:"grams",hint:"Nudeln sind eine Kohlenhydrat-Bombe.",emoji:"🍝"},
  {q:"How many Tonnen Schokolade exportiert Deutschland per year?",a:400000,unit:"tons",hint:"Deutschland ist Europas größter Schokoladenexporteur.",emoji:"🍫"},
  {q:"How many kcal hat ein Weißwein-Schorle (200ml)?",a:80,unit:"kcal",hint:"Weniger als Rotwein durch die Verdünnung.",emoji:"🍷"},
  {q:"How many Gramm Zucker hat ein Bounty (57g)?",a:31,unit:"grams",hint:"Über die Hälfte ist Zucker.",emoji:"🍫"},
  {q:"How many million Liter Sekt trinkt Deutschland per year?",a:300,unit:"million liters",hint:"Deutschland ist Weltmeister im Sektkonsum.",emoji:"🥂"},
  {q:"How many kcal hat 100g Nüsse (gemischt)?",a:600,unit:"kcal",hint:"Nüsse sind sehr kalorienreich aber gesund.",emoji:"🥜"},
  {q:"How many Gramm Eiweiß hat 100g Shrimps?",a:24,unit:"grams",hint:"Sehr proteinreich und kalorienarm.",emoji:"🍤"},
  {q:"How many Liter Milch trinkt ein Deutscher per year?",a:52,unit:"liters",hint:"Rückgang seit Jahren – Alternativen boomen.",emoji:"🥛"},
  {q:"How many kcal hat 100g Hummus?",a:177,unit:"kcal",hint:"Gesunder Aufschnitt aus Kichererbsen.",emoji:"🫘"},
  {q:"How many Gramm Fett hat 100g Chips?",a:35,unit:"grams",hint:"Ein Drittel der Chips besteht aus Fett.",emoji:"🍟"},
  {q:"How many Tonnen Tomatenmark produziert die Welt per year?",a:9000000,unit:"tons",hint:"Die Basis fast aller Saucen.",emoji:"🍅"},
  {q:"How many kcal hat ein Stück Königsberger Klopse (2 Stück)?",a:400,unit:"kcal",hint:"Deutsche Fleischbällchen in Kapernsauce.",emoji:"🍲"},
  {q:"How many Gramm Kohlenhydrate hat 100g Honig?",a:80,unit:"grams",hint:"Honig besteht fast nur aus Zucker.",emoji:"🍯"},
  {q:"How many million Tonnen Getreide produziert die EU per year?",a:300,unit:"million tons",hint:"Getreide ist die wichtigste Nahrungsgrundlage.",emoji:"🌾"},
  {q:"How many kcal hat ein Glas Smoothie (300ml)?",a:180,unit:"kcal",hint:"Smoothies können viele versteckte Kalorien haben.",emoji:"🍹"},
  {q:"How many Gramm Protein hat 100g Kürbiskerne?",a:30,unit:"grams",hint:"Eine der proteinreichsten pflanzlichen Quellen.",emoji:"🎃"},
  {q:"How many billion Liter Bier braut die USA per year?",a:20,unit:"billion liters",hint:"Größter Biermarkt der Welt nach China.",emoji:"🍺"},
  {q:"How many kcal hat eine Tasse Cappuccino?",a:120,unit:"kcal",hint:"Milch und Schaum haben Kalorien.",emoji:"☕"},
  {q:"How many Gramm Zucker hat 100g Marmelade?",a:65,unit:"grams",hint:"Marmelade ist fast zwei Drittel Zucker.",emoji:"🍓"},
  {q:"How many Tonnen Butter produziert Deutschland per year?",a:500000,unit:"tons",hint:"Deutschland ist Europas größter Butterproduzent.",emoji:"🧈"},
  {q:"How many kcal hat 100g Mandeln?",a:576,unit:"kcal",hint:"Sehr kalorienreich – auch wenn sie gesund sind.",emoji:"🌰"},
  {q:"How many Gramm Eiweiß hat 100g Mozzarella?",a:18,unit:"grams",hint:"Mehr Protein als die meisten Weichkäse.",emoji:"🧀"},
  {q:"How many Stunden fermentiert traditionelles Sauerkraut?",a:336,unit:"hours",hint:"14 Tage oder mehr.",emoji:"🥬"},
  {q:"How many kcal hat 100g Frühstücksflocken (Cornflakes)?",a:370,unit:"kcal",hint:"Weniger als Müsli mit Nüssen.",emoji:"🥣"},
  {q:"How many Gramm Kohlenhydrate hat 100g Weintrauben?",a:17,unit:"grams",hint:"Trauben sind sehr zuckerreich.",emoji:"🍇"},
  {q:"How many million Tonnen Fleisch produziert die Welt per year?",a:340,unit:"million tons",hint:"Davon ist die Hälfte Schweinefleisch.",emoji:"🥩"},
  {q:"How many kcal hat ein Knäckebrot (10g)?",a:34,unit:"kcal",hint:"Sehr kalorienarm – gut als Diätknacker.",emoji:"🍞"},
  {q:"How many Gramm Fett hat 100g Sahne (Schlagsahne)?",a:35,unit:"grams",hint:"Schlagsahne ist fast reines Fett.",emoji:"🍦"},
  {q:"How many Liter Wasser braucht man für 1 kg Äpfel?",a:822,unit:"liters",hint:"Äpfel brauchen deutlich weniger Wasser als exotische Früchte.",emoji:"🍎"},
  {q:"How many kcal hat ein Berliner Pfannkuchen (60g)?",a:250,unit:"kcal",hint:"Frittiert und mit Marmelade gefüllt.",emoji:"🍩"},
  {q:"How many Gramm Protein hat 100g Kichererbsen (gekocht)?",a:9,unit:"grams",hint:"Eine wichtige vegane Proteinquelle.",emoji:"🫘"},
  {q:"How many Tonnen Olivenöl produziert Spanien per year?",a:1800000,unit:"tons",hint:"Größter Olivenölproduzent worldwide.",emoji:"🫒"},
  {q:"How many kcal hat 100g Speck?",a:541,unit:"kcal",hint:"Einer der kalorienreichsten Fleischprodukte.",emoji:"🥓"},
  {q:"How many Gramm Kohlenhydrate hat 100g Süßkartoffeln?",a:20,unit:"grams",hint:"Etwas mehr als normale Kartoffeln.",emoji:"🍠"},
  {q:"How many million Hektoliter Wein produziert Italien per year?",a:50,unit:"Mio. Hektoliter",hint:"Italiens größter Weinexport-Posten.",emoji:"🍷"},
  {q:"How many kcal hat 100g Räucherlachs?",a:180,unit:"kcal",hint:"Weniger kalorienreich als geräuchertes Fleisch.",emoji:"🐟"},
  {q:"How many Gramm Fett hat 100g Bratwurst?",a:25,unit:"grams",hint:"Bratwurst ist ein fettreiches Produkt.",emoji:"🌭"},
  {q:"How many Stunden dauert die Herstellung von Sojasoße traditionell?",a:4380,unit:"hours",hint:"6 Monate Fermentation.",emoji:"🫙"},
  {q:"How many kcal hat eine Pizza Margherita (30cm)?",a:900,unit:"kcal",hint:"Die klassische Pizza – noch ohne Extras.",emoji:"🍕"},
  {q:"How many Gramm Zucker hat 100g Honigmelone?",a:8,unit:"grams",hint:"Melone ist im Sommer perfekt.",emoji:"🍈"},
  {q:"How many million Tonnen Zucker stecken in der weltweiten Coca-Cola-Produktion per year?",a:10,unit:"million tons",hint:"million Tonnen Zucker in Coca-Cola annually.",emoji:"🥤"},
  {q:"How many kcal hat 100g Edamer Käse?",a:357,unit:"kcal",hint:"Ein milder Schnitt-Käse mit mittlerem Fettgehalt.",emoji:"🧀"},
  {q:"How many Gramm Eiweiß hat 100g griechischer Joghurt?",a:10,unit:"grams",hint:"Doppelt so viel wie normaler Joghurt.",emoji:"🫙"},
  {q:"How many billion Liter Scotch Whisky exportiert Schottland per year?",a:1300,unit:"million liters",hint:"1,3 billion Liter – Scotch Whisky ist ein Riesenmarkt.",emoji:"🥃"},
  {q:"How many kcal hat 100g Mayonnaise?",a:680,unit:"kcal",hint:"Fast reines Fett aus Öl und Ei.",emoji:"🫙"},
  {q:"How many Gramm Fett hat 100g Avocado?",a:15,unit:"grams",hint:"Ungesättigte Fettsäuren – die guten Fette.",emoji:"🥑"},
  {q:"How many million kg Kaffee verbraucht Deutschland daily?",a:2,unit:"Millionen kg",hint:"million Kilogramm Kaffee daily.",emoji:"☕"},
  {q:"How many kcal hat 100g Camembert (45% Fett)?",a:290,unit:"kcal",hint:"Weichkäse sind kalorienreich.",emoji:"🧀"},
  {q:"How many Gramm Kohlenhydrate hat 100g Banane?",a:23,unit:"grams",hint:"Bananen liefern schnelle Energie.",emoji:"🍌"},
  {q:"How many Gramm Eiweiß hat 100g Tofu?",a:8,unit:"grams",hint:"Tofu ist eine wichtige vegane Proteinquelle.",emoji:"🫘"},
  {q:"How many kcal hat 100g Schinken?",a:130,unit:"kcal",hint:"Weniger fett als Salami.",emoji:"🥩"},
  {q:"How many Gramm Zucker hat ein Schokoriegel (Mars, 51g)?",a:36,unit:"grams",hint:"Fast drei Viertel des Schokoriegels ist Zucker.",emoji:"🍫"},
  {q:"How many Liter Bier trinkt ein Tscheche per year?",a:189,unit:"liters",hint:"Weltmeister im Pro-Kopf-Bierverbrauch.",emoji:"🍺"},
  {q:"How many Gramm Fett hat 100g Nutella?",a:31,unit:"grams",hint:"Und 57g Zucker dazu.",emoji:"🍫"},
  {q:"How many kcal hat 100g Lachs (frisch)?",a:208,unit:"kcal",hint:"Reich an Omega-3-Fettsäuren.",emoji:"🐟"},
  {q:"How many kg Fleisch isst ein Amerikaner per year?",a:120,unit:"kg",hint:"Fast doppelt so viel wie ein Europäer.",emoji:"🥩"},
  {q:"How many Gramm Zucker hat ein Glas Milchkaffee (Latte, 300ml)?",a:14,unit:"grams",hint:"Durch die Milch.",emoji:"☕"},
  {q:"How many kcal hat ein Stück Tiramisu (150g)?",a:600,unit:"kcal",hint:"Mascarpone macht es sehr kalorienreich.",emoji:"🎂"},
  {q:"How many Gramm Protein hat 100g Seitan?",a:25,unit:"grams",hint:"Weizenglutenprodukt – sehr proteinreich.",emoji:"💪"},
  {q:"How many Liter Wasser braucht man für 1 kg Hühnchen?",a:4325,unit:"liters",hint:"Deutlich weniger als Rind.",emoji:"🐔"},
  {q:"How many kcal hat ein Donut (Glazed, 57g)?",a:269,unit:"kcal",hint:"Klein aber mächtig kalorienreich.",emoji:"🍩"},
  {q:"How many Gramm Fett hat 100g Chorizo?",a:40,unit:"grams",hint:"Eine der fettreichsten Wurstarten.",emoji:"🌭"},
  {q:"How many percent Fett enthält griechischer Joghurt (normal)?",a:10,unit:"%",hint:"Deutlich fettreicher als normaler Joghurt.",emoji:"🫙"},
  {q:"How many kcal hat 100g Roquefort-Käse?",a:369,unit:"kcal",hint:"Schimmelkäse sind kalorienreicher.",emoji:"🧀"},
  {q:"How many Gramm Zucker hat 100g Müsli?",a:15,unit:"grams",hint:"Ungesüßtes Müsli hat weniger – Fertigprodukte viel mehr.",emoji:"🥣"},
  {q:"How many Liter produziert ein Weinberg (Hektar) per year?",a:5000,unit:"liters",hint:"Wein braucht erstaunlich viel Wasser.",emoji:"🍷"},
  {q:"How many kcal hat ein Glas Apfelsaft (200ml)?",a:94,unit:"kcal",hint:"Fast wie Cola – trotz 'gesund'.",emoji:"🍎"},
  {q:"How many Gramm Protein hat 100g Haferflocken?",a:13,unit:"grams",hint:"Eine der proteinreichsten Getreidearten.",emoji:"🌾"},
  {q:"How many kcal hat ein Stück Focaccia (100g)?",a:270,unit:"kcal",hint:"Italienisches Fladenbrot mit Olivenöl.",emoji:"🍞"},
  {q:"How many Gramm Kohlenhydrate hat 100g Paprika?",a:6,unit:"grams",hint:"Paprika ist sehr kohlenhydratarm.",emoji:"🌶️"},
  {q:"How many Liter Milch trinkt ein Finne per year?",a:180,unit:"liters",hint:"Finnland ist Weltmeister im Milchkonsum.",emoji:"🥛"},
  {q:"How many kcal hat ein Vollkornbrot (Scheibe, 50g)?",a:105,unit:"kcal",hint:"Etwas weniger als Weißbrot.",emoji:"🍞"},
  {q:"How many Gramm Zucker hat 100g Balsamico-Essig?",a:17,unit:"grams",hint:"Viel Zucker für ein Sauerprodukt.",emoji:"🫙"},
  {q:"How many Tonnen Sushi wird daily in Japan gegessen?",a:2000,unit:"tons",hint:"Japan bleibt der Weltmarktführer.",emoji:"🍣"},
  {q:"How many kcal hat ein Hotdog (normal)?",a:290,unit:"kcal",hint:"Mit Senf und Ketchup etwas mehr.",emoji:"🌭"},
  {q:"How many Gramm Calcium hat 100g Parmesan?",a:1184,unit:"grams",hint:"Parmesan hat mehr Calcium als fast jedes andere Lebensmittel.",emoji:"🧀"},
  {q:"How many million Tonnen Schokolade produziert die Welt per year?",a:8,unit:"million tons",hint:"million Tonnen worldwide.",emoji:"🍫"},
  {q:"How many kcal hat 100g Macarons?",a:450,unit:"kcal",hint:"Sehr zuckerreich und kalorienreich.",emoji:"🍬"},
  {q:"How many Gramm Zucker hat ein Red Bull (250ml)?",a:27,unit:"grams",hint:"Fast so viel wie Cola.",emoji:"⚡"},
  {q:"How many Liter Wasser braucht man für 1 Tasse heißen Tee?",a:30,unit:"liters",hint:"Inklusive Anbau und Verarbeitung.",emoji:"🍵"},
  {q:"How many kcal hat ein Stück Baklava (50g)?",a:215,unit:"kcal",hint:"Süß und kalorienreich.",emoji:"🍯"},
  {q:"How many Gramm Protein hat 100g Kürbissamen?",a:30,unit:"grams",hint:"Eine der proteinreichsten pflanzlichen Quellen.",emoji:"🎃"},
  {q:"How many Tonnen Zucker isst ein Europäer per year?",a:38,unit:"kg",hint:"Kg – über 100g daily.",emoji:"🍬"},
  {q:"How many kcal hat ein Stück Käsekuchen (100g)?",a:321,unit:"kcal",hint:"Quark und Eier machen ihn kalorienreich.",emoji:"🎂"},
  {q:"How many Gramm Eiweiß hat 100g schwarze Bohnen (gekocht)?",a:9,unit:"grams",hint:"Gute pflanzliche Proteinquelle.",emoji:"🫘"},
  {q:"How many Liter Kaffee trinkt ein Norweger per year?",a:9.9,unit:"kg",hint:"Skandinavien führt den Kaffeekonsum worldwide.",emoji:"☕"},
  {q:"How many kcal hat 100g Acai-Beeren?",a:534,unit:"kcal",hint:"Überraschend kalorienreich trotz 'Superfood'.",emoji:"🫐"},
  {q:"How many Gramm Fett hat 100g Hüttenkäse?",a:4,unit:"grams",hint:"Sehr fettarm und proteinreich.",emoji:"🧀"},
  {q:"How many kcal hat ein Glas Buttermilch (200ml)?",a:66,unit:"kcal",hint:"Kalorienarm und proteinreich.",emoji:"🥛"},
  {q:"How many Gramm Zucker hat eine Flasche Gatorade (500ml)?",a:34,unit:"grams",hint:"Ähnlich wie eine Dose Limo.",emoji:"🏃"},
  {q:"How many Tonnen Avocado importiert Europa per year?",a:1000000,unit:"tons",hint:"1 Million Tonnen – der Boom hält an.",emoji:"🥑"},
  {q:"How many kcal hat 100g Joghurt mit Früchten?",a:100,unit:"kcal",hint:"Fruchtjoghurt hat mehr als Naturjoghurt.",emoji:"🫙"},
  {q:"How many Gramm Protein hat 100g Edamame?",a:11,unit:"grams",hint:"Unreife Sojabohnen – ideal als Snack.",emoji:"🫘"},
];
