// 🚀 ASTRONOMY & PHYSICS – Adults – 221 questions
export default [
  {id:"astro_001",q:"How many million light-years away is the Andromeda Galaxy?",a:2.5,unit:"million light-years",hint:"It's visible to the naked eye as a small smudge.",emoji:"🌌"},
  {id:"astro_002",q:"How many degrees Celsius is the Sun's surface temperature?",a:5500,unit:"°C",hint:"At the core it's even 15 million degrees.",emoji:"☀️"},
  {id:"astro_003",q:"What is the speed of light, in km/s?",a:300000,unit:"km/s",hint:"Light takes about 8 minutes to travel from the Sun to Earth.",emoji:"💡"},
  {id:"astro_004",q:"How many Earth masses does Jupiter have?",a:318,unit:"Earth masses",hint:"Jupiter is the largest planet in our solar system.",emoji:"🪐"},
  {id:"astro_005",q:"How many moons does Saturn have?",a:146,unit:"moons",hint:"Saturn has more moons than any other planet.",emoji:"🪐"},
  {id:"astro_006",q:"How many degrees Celsius is it on the Moon at night?",a:-170,unit:"°C",hint:"During the day it's +130°C.",emoji:"🌙"},
  {id:"astro_007",q:"How many times larger is the Sun's diameter than Earth's?",a:109,unit:"times",hint:"The Sun's diameter is 1.39 million km.",emoji:"☀️"},
  {id:"astro_008",q:"How many thousand km away is the Moon from Earth?",a:384,unit:"thousand km",hint:"Varies between 356,000 and 407,000 km.",emoji:"🌙"},
  {id:"astro_009",q:"How many billion years old is the universe?",a:13.8,unit:"billion years",hint:"Since the Big Bang.",emoji:"🌌"},
  {id:"astro_010",q:"How many km/h does the Earth travel around the Sun?",a:107000,unit:"km/h",hint:"That's about 30 km per second.",emoji:"🌍"},
  {id:"astro_011",q:"How many billion stars are there in the Milky Way?",a:200,unit:"billion",hint:"And billions more galaxies in the universe.",emoji:"⭐"},
  {id:"astro_012",q:"How many minutes does light take to travel from the Sun to Earth?",a:8,unit:"minutes",hint:"Light races at 300,000 km/s – yet it still takes a while.",emoji:"☀️"},
  {id:"astro_013",q:"How hot is Earth's core, in degrees Celsius?",a:6000,unit:"°C",hint:"About as hot as the Sun's surface.",emoji:"🌍"},
  {id:"astro_014",q:"How many months does a year on Mars last?",a:24,unit:"months",hint:"A Martian year lasts 687 Earth days.",emoji:"🔴"},
  {id:"astro_015",q:"How many million times bigger is the Sun than Earth?",a:1.3,unit:"million times",hint:"1.3 million Earths would fit inside the Sun.",emoji:"☀️"},
  {id:"astro_016",q:"How many degrees Celsius is the temperature in space?",a:-270,unit:"°C",hint:"Close to absolute zero, at -273°C.",emoji:"❄️"},
  {id:"astro_017",q:"How many hours does a day on Venus last?",a:5832,unit:"hours",hint:"A Venusian year is shorter than a Venusian day.",emoji:"🪐"},
  {id:"astro_018",q:"How many degrees Celsius is the temperature on Mercury during the day?",a:430,unit:"°C",hint:"At night it drops to -180°C.",emoji:"☿"},
  {id:"astro_019",q:"How many km/h does the ISS travel around Earth?",a:28000,unit:"km/h",hint:"It orbits Earth every 90 minutes.",emoji:"🚀"},
  {id:"astro_020",q:"How many billion tons does 1 teaspoon of neutron star material weigh?",a:1,unit:"billion tons",hint:"A billion tons in one teaspoon – unimaginably dense.",emoji:"⭐"},
  {id:"astro_021",q:"How many trillion km long is a light-year?",a:9.46,unit:"trillion km",hint:"Light travels 9.46 trillion km every year.",emoji:"💡"},
  {id:"astro_022",q:"How many moons does Mars have?",a:2,unit:"moons",hint:"Phobos and Deimos – both very small.",emoji:"🔴"},
  {id:"astro_023",q:"What is Earth's diameter, in km?",a:12742,unit:"km",hint:"Slightly thicker at the equator than at the poles.",emoji:"🌍"},
  {id:"astro_024",q:"How many km/h must a rocket fly to leave Earth?",a:40000,unit:"km/h",hint:"That's Earth's escape velocity.",emoji:"🚀"},
  {id:"astro_025",q:"How many astronauts have been on the Moon so far?",a:12,unit:"astronauts",hint:"All 12 were American, during the Apollo missions.",emoji:"👨‍🚀"},
  {id:"astro_026",q:"How many main rings does Saturn have?",a:7,unit:"main rings",hint:"The rings are made of ice and rock.",emoji:"🪐"},
  {id:"astro_027",q:"How many light-years away is Alpha Centauri from Earth?",a:4,unit:"light-years",hint:"The closest star system to our own.",emoji:"⭐"},
  {id:"astro_028",q:"What is the atomic mass of a hydrogen atom?",a:1,unit:"atomic mass unit",hint:"Hydrogen is the lightest element.",emoji:"⚛️"},
  {id:"astro_029",q:"How many trillion galaxies are there in the observable universe?",a:2,unit:"trillion",hint:"2 trillion galaxies – each with billions of stars.",emoji:"🌌"},
  {id:"astro_030",q:"How fast does sound travel in air, in m/s?",a:343,unit:"m/s",hint:"At an air temperature of 20°C.",emoji:"🔊"},
  {id:"astro_031",q:"How many times heavier is a proton compared to an electron?",a:1836,unit:"times heavier",hint:"The proton is this many times heavier.",emoji:"⚛️"},
  {id:"astro_032",q:"How many km/s is the escape velocity from the Moon?",a:2.4,unit:"km/s",hint:"Much lower than on Earth.",emoji:"🌙"},
  {id:"astro_033",q:"How many degrees does a full circle have?",a:360,unit:"degrees",hint:"An ancient Babylonian convention – still standard today.",emoji:"⭕"},
  {id:"astro_034",q:"How many planets does our solar system have?",a:8,unit:"planets",hint:"Pluto was demoted to a dwarf planet in 2006.",emoji:"🪐"},
  {id:"astro_035",q:"How many km/h is the wind speed of a Category 5 hurricane?",a:252,unit:"km/h",hint:"From 252 km/h onward, it's Category 5.",emoji:"🌀"},
  {id:"astro_036",q:"What is Earth's radius, in km?",a:6371,unit:"km",hint:"Earth's mean radius.",emoji:"🌍"},
  {id:"astro_037",q:"How many km/s is Earth's orbital speed?",a:30,unit:"km/s",hint:"29.8 km/s, or about 107,000 km/h.",emoji:"🌍"},
  {id:"astro_038",q:"How many hours does a day on Jupiter last?",a:10,unit:"hours",hint:"Jupiter rotates faster than any other planet.",emoji:"🪐"},
  {id:"astro_039",q:"How many meters long is the International Space Station?",a:109,unit:"meters",hint:"About as wide as a soccer field.",emoji:"🚀"},
  {id:"astro_040",q:"How many billion years old is our Sun?",a:4.6,unit:"billion years",hint:"4.6 billion years – right in the middle of its life.",emoji:"☀️"},
  {id:"astro_041",q:"How many km/h does a meteor reach when entering the atmosphere?",a:72000,unit:"km/h",hint:"20 km/s – it usually burns up in the process.",emoji:"☄️"},
  {id:"astro_042",q:"How many degrees Celsius is the temperature at Earth's core?",a:6000,unit:"°C",hint:"Similar to the Sun's surface.",emoji:"🔥"},
  {id:"astro_043",q:"How many times bigger is Jupiter's diameter than Earth's?",a:11,unit:"times",hint:"Jupiter has a diameter of 139,820 km.",emoji:"🪐"},
  {id:"astro_044",q:"How many hours does it take Earth to complete one rotation?",a:24,unit:"hours",hint:"More precisely: 23 hours 56 minutes.",emoji:"🌍"},
  {id:"astro_045",q:"How many astronomical units away is Neptune from the Sun?",a:30,unit:"AU",hint:"1 AU = Earth-Sun distance. Light takes 4 hours to reach Neptune.",emoji:"🔵"},
  {id:"astro_046",q:"How many moons does Uranus have?",a:27,unit:"moons",hint:"All named after Shakespeare characters.",emoji:"🟦"},
  {id:"astro_047",q:"How many km/s is Earth's escape velocity?",a:11.2,unit:"km/s",hint:"11.2 km/s, or 40,000 km/h.",emoji:"🚀"},
  {id:"astro_048",q:"How many degrees Celsius is it on Saturn?",a:-178,unit:"°C",hint:"The cloud tops are extremely cold.",emoji:"🪐"},
  {id:"astro_049",q:"How many years does a Pluto year last?",a:248,unit:"Earth years",hint:"Years for one orbit around the Sun.",emoji:"🌑"},
  {id:"astro_050",q:"How many thousand light-years wide is the Milky Way?",a:100,unit:"thousand light-years",hint:"100,000 light-years in diameter.",emoji:"🌌"},
  {id:"astro_051",q:"How many hours does a year on Mercury last?",a:1408,unit:"hours",hint:"88 Earth days – the shortest planetary year.",emoji:"☿"},
  {id:"astro_052",q:"How many light-years away is the Oort Cloud from the Sun?",a:1,unit:"light-year",hint:"The outermost edge of our solar system – 50,000 AU.",emoji:"☄️"},
  {id:"astro_053",q:"What is Earth's gravitational acceleration, in m/s²?",a:9.81,unit:"m/s²",hint:"Free fall accelerates at 9.81 m/s².",emoji:"⬇️"},
  {id:"astro_054",q:"How many years does a Uranus year last?",a:84,unit:"years",hint:"Earth years for one orbit.",emoji:"🟦"},
  {id:"astro_055",q:"How many km/h is the fastest human-made probe (Parker Solar Probe)?",a:692000,unit:"km/h",hint:"The fastest machine ever built by humans (as of ~2024).",emoji:"🚀"},
  {id:"astro_056",q:"How many degrees Celsius is the temperature on Neptune?",a:-214,unit:"°C",hint:"The coldest planet in the solar system.",emoji:"🔵"},
  {id:"astro_057",q:"How many astronomical units away is Pluto from the Sun?",a:39,unit:"AU",hint:"AU – almost 40 times farther than Earth.",emoji:"🌑"},
  {id:"astro_058",q:"How many Earth years does a Jupiter year last?",a:12,unit:"Earth years",hint:"Jupiter takes 12 Earth years for one orbit.",emoji:"🪐"},
  {id:"astro_059",q:"How many degrees does Earth rotate per hour?",a:15,unit:"degrees",hint:"360° in 24h = 15° per hour.",emoji:"🌍"},
  {id:"astro_060",q:"What is the Earth-Sun distance, in astronomical units?",a:1,unit:"astronomical unit",hint:"AU = 149.6 million km.",emoji:"☀️"},
  {id:"astro_061",q:"How many trillion Hz do visible light waves oscillate at?",a:600,unit:"trillion Hz",hint:"400-700 THz – the range of visible light.",emoji:"💡"},
  {id:"astro_062",q:"How many thousand times more energy does the Sun emit than all of Earth's power plants combined?",a:500,unit:"thousand times more",hint:"The Sun emits 3.86×10²⁶ watts – an unimaginable amount.",emoji:"☀️"},
  {id:"astro_063",q:"How many million tons of matter does the Sun convert into energy per second?",a:4,unit:"million tons",hint:"4 million tons per second.",emoji:"☀️"},
  {id:"astro_064",q:"How many light-years away is the center of our Milky Way?",a:26000,unit:"light-years",hint:"A supermassive black hole sits there.",emoji:"🌌"},
  {id:"astro_065",q:"How many km/h does Jupiter rotate at its equator?",a:45000,unit:"km/h",hint:"The fastest rotation of any planet.",emoji:"🪐"},
  {id:"astro_066",q:"How many nanometers wide is visible light?",a:700,unit:"nanometers",hint:"400-700 nm wavelength.",emoji:"🌈"},
  {id:"astro_067",q:"How many degrees Celsius is the temperature inside a lightning bolt?",a:30000,unit:"°C",hint:"5 times hotter than the Sun's surface.",emoji:"⚡"},
  {id:"astro_068",q:"How many million km is Mars from Earth on average?",a:225,unit:"million km",hint:"Varies widely – from 56 to 401 million km.",emoji:"🔴"},
  {id:"astro_069",q:"How many thousand light-years is the Sun from the center of the Milky Way?",a:26,unit:"thousand light-years",hint:"Near the edge of the Milky Way.",emoji:"🌌"},
  {id:"astro_070",q:"How many years would a car ride to the Sun take at 200 km/h?",a:97,unit:"years",hint:"150 million km ÷ 200 km/h = 850,000 hours.",emoji:"🚗"},
  {id:"astro_071",q:"How many kilograms does 1 m³ of water weigh?",a:1000,unit:"kg",hint:"Water has a density of 1 kg per liter.",emoji:"💧"},
  {id:"astro_072",q:"How many km/h does sound travel in water?",a:5400,unit:"km/h",hint:"5 times faster than in air.",emoji:"🌊"},
  {id:"astro_073",q:"How many hours does one Neptune rotation last?",a:16,unit:"hours",hint:"A day on Neptune lasts this many hours.",emoji:"🔵"},
  {id:"astro_074",q:"How many million solar masses does the black hole at the center of the Milky Way have?",a:4,unit:"million solar masses",hint:"The black hole at the center of the Milky Way.",emoji:"🌑"},
  {id:"astro_075",q:"How many km is the diameter of a typical neutron star?",a:20,unit:"km",hint:"Unimaginably dense in the smallest space.",emoji:"⭐"},
  {id:"astro_076",q:"How many million degrees Celsius is the heat of nuclear fusion in the Sun?",a:15,unit:"million °C",hint:"At the core – hydrogen is converted into helium.",emoji:"⚛️"},
  {id:"astro_077",q:"How many km/s is the universe expanding away from us at its edge?",a:300000,unit:"km/s",hint:"At the edge, it expands at the speed of light.",emoji:"🌌"},
  {id:"astro_078",q:"How many years does a Saturn year last?",a:29.5,unit:"years",hint:"29.5 Earth years for one orbit.",emoji:"🪐"},
  {id:"astro_079",q:"How many meters deep would the ocean be if Earth were a smooth sphere?",a:2700,unit:"meters",hint:"All mountains would sink into the sea.",emoji:"🌊"},
  {id:"astro_080",q:"How many kilowatt-hours of energy does 1 gram of uranium provide?",a:24000,unit:"kWh",hint:"One gram of uranium is equivalent to 3 tons of coal.",emoji:"⚛️"},
  {id:"astro_081",q:"How many million km is Earth from the Sun?",a:150,unit:"million km",hint:"This defines the astronomical unit (1 AU).",emoji:"☀️"},
  {id:"astro_082",q:"How many degrees does the atmosphere cool per km of altitude?",a:6.5,unit:"°C/km",hint:"The adiabatic temperature gradient.",emoji:"🌡️"},
  {id:"astro_083",q:"How many million joules is 1 kilowatt-hour?",a:3.6,unit:"million joules",hint:"3.6 million joules.",emoji:"⚡"},
  {id:"astro_084",q:"How many months does a Mercury year last?",a:3,unit:"months",hint:"Only 88 days – the fastest orbit.",emoji:"☿"},
  {id:"astro_085",q:"How many km/s do gamma rays race through space at?",a:300000,unit:"km/s",hint:"The speed of light – the fastest thing in the universe.",emoji:"💥"},
  {id:"astro_086",q:"How many degrees is Earth's axial tilt?",a:23.5,unit:"degrees",hint:"It's what causes the seasons.",emoji:"🌍"},
  {id:"astro_087",q:"What is the circumference of the Moon, in km?",a:10917,unit:"km",hint:"Much smaller than Earth.",emoji:"🌙"},
  {id:"astro_088",q:"How many nanometers thick is a human hair compared to light waves?",a:700,unit:"nanometers",hint:"Hair and light waves are similarly sized.",emoji:"💇"},
  {id:"astro_089",q:"How many atmospheres of pressure exist at 10,000 meters of water depth?",a:1000,unit:"atmospheres",hint:"The pressure in the deep sea is hard to imagine.",emoji:"🌊"},
  {id:"astro_090",q:"How many degrees Celsius is the average temperature on Mars?",a:-60,unit:"°C",hint:"Between -125°C and +20°C.",emoji:"🔴"},
  {id:"astro_091",q:"How many m/s² is the gravity on the Moon?",a:1.6,unit:"m/s²",hint:"1/6 of Earth's gravity.",emoji:"🌙"},
  {id:"astro_092",q:"How many km thick is Earth's crust on average?",a:35,unit:"km",hint:"Only 10 km under the oceans, 35 km under the continents.",emoji:"🌍"},
  {id:"astro_093",q:"How many million billion tons does Earth's atmosphere weigh?",a:5.6,unit:"million billion tons",hint:"5.6 quadrillion kilograms.",emoji:"💨"},
  {id:"astro_094",q:"How many km/h does Earth rotate at the equator?",a:1670,unit:"km/h",hint:"We don't feel it – because we move along with it.",emoji:"🌍"},
  {id:"astro_095",q:"How many degrees Celsius colder would Earth be without the greenhouse effect?",a:33,unit:"°C colder",hint:"Without the natural greenhouse effect, it would be -18°C.",emoji:"🌡️"},
  {id:"astro_096",q:"How many km/h is the maximum wind speed on Neptune?",a:2100,unit:"km/h",hint:"The strongest known winds in the solar system.",emoji:"🌀"},
  {id:"astro_097",q:"How many billion km away is Voyager 1 from the Sun?",a:23.5,unit:"billion km",hint:"As of 2023 – it was launched in 1977.",emoji:"🚀"},
  {id:"astro_098",q:"How many kilograms of lunar rock did the Apollo missions bring back?",a:382,unit:"kg",hint:"Kg of lunar rock – still being analyzed.",emoji:"🌙"},
  {id:"astro_099",q:"How many km/h would you need to fly to stay in Earth orbit?",a:28000,unit:"km/h",hint:"The first cosmic velocity.",emoji:"🚀"},
  {id:"astro_100",q:"How many hours does a Martian day last?",a:24.6,unit:"hours",hint:"Almost like an Earth day.",emoji:"🔴"},
  {id:"astro_101",q:"How many million km is Mercury from the Sun?",a:58,unit:"million km",hint:"The closest planet to the Sun.",emoji:"☿"},
  {id:"astro_102",q:"How many hours does a year on Venus last?",a:5392,unit:"hours",hint:"225 Earth days – and a day is longer than a year there.",emoji:"🪐"},
  {id:"astro_103",q:"How many degrees Celsius colder is space than Earth?",a:287,unit:"°C colder",hint:"Earth averages 15°C, space is -273°C.",emoji:"❄️"},
  {id:"astro_104",q:"How many km high is Olympus Mons on Mars?",a:22,unit:"km",hint:"The tallest volcano in the solar system.",emoji:"🔴"},
  {id:"astro_105",q:"How many billion tons of carbon dioxide does humanity exhale per year?",a:3,unit:"billion tons",hint:"Billions of tons of CO₂ through breathing.",emoji:"💨"},
  {id:"astro_106",q:"How many times per second does a neutron star rotate?",a:700,unit:"times",hint:"Pulsars rotate up to 716 times per second.",emoji:"⭐"},
  {id:"astro_107",q:"How many km is the boundary to space (Kármán line)?",a:100,unit:"km",hint:"Space officially begins at 100 km.",emoji:"🚀"},
  {id:"astro_108",q:"How many thousand years after the Big Bang did the first atoms form?",a:380,unit:"thousand years",hint:"380,000 years after the Big Bang – the universe had cooled down.",emoji:"⚛️"},
  {id:"astro_109",q:"How many tons of moon dust are there per m² of lunar surface?",a:10,unit:"tons/m²",hint:"The regolith is several meters deep.",emoji:"🌙"},
  {id:"astro_110",q:"How many million cubic kilometers of water are there on Earth?",a:1400,unit:"million km³",hint:"1.4 billion cubic kilometers of water.",emoji:"🌊"},
  {id:"astro_111",q:"How many km/h does a tornado rotate at?",a:480,unit:"km/h",hint:"The strongest tornadoes exceed 480 km/h.",emoji:"🌪️"},
  {id:"astro_112",q:"How many times smaller is a proton than an atom?",a:100000,unit:"times",hint:"An atom is 99.9% empty space.",emoji:"⚛️"},
  {id:"astro_113",q:"How many degrees is the maximum solar radiation temperature on Mars?",a:20,unit:"°C",hint:"In summer at the equator – at night it's -60°C.",emoji:"🔴"},
  {id:"astro_114",q:"How many km/h can solar wind particles reach?",a:900000,unit:"km/h",hint:"Even faster during coronal mass ejections.",emoji:"☀️"},
  {id:"astro_115",q:"How many degrees wide is the field of view of the Hubble Telescope?",a:0.05,unit:"degrees",hint:"Just a tiny patch – yet full of galaxies.",emoji:"🔭"},
  {id:"astro_116",q:"How many degrees is the maximum temperature on Venus's surface?",a:465,unit:"°C",hint:"Hotter than Mercury – despite being farther from the Sun.",emoji:"🌋"},
  {id:"astro_117",q:"How many quintillion tons does Earth's atmosphere weigh?",a:5.6,unit:"quintillion tons",hint:"5.6 quadrillion tons of air.",emoji:"💨"},
  {id:"astro_118",q:"How many billion years does our Sun have left to live?",a:5,unit:"billion years",hint:"Then it will become a red giant.",emoji:"☀️"},
  {id:"astro_119",q:"How many m/s² is the gravity on Jupiter?",a:24.8,unit:"m/s²",hint:"2.5 times stronger than on Earth.",emoji:"🪐"},
  {id:"astro_120",q:"How many meters deep is the Mariana Trench?",a:11034,unit:"meters",hint:"The deepest point in the world's oceans.",emoji:"🌊"},
  {id:"astro_121",q:"How many trillion solar masses does our Milky Way weigh?",a:2,unit:"trillion solar masses",hint:"A trillion solar masses.",emoji:"🌌"},
  {id:"astro_122",q:"How many femtometers in size is a proton?",a:0.85,unit:"femtometers",hint:"0.85 femtometers – a femtometer is a millionth of a nanometer.",emoji:"⚛️"},
  {id:"astro_123",q:"How many degrees Celsius is it at the poles of Mars?",a:-125,unit:"°C",hint:"CO₂ ice forms at the polar caps.",emoji:"🔴"},
  {id:"astro_124",q:"How many km/h is the fastest jet aircraft (SR-71)?",a:3530,unit:"km/h",hint:"Mach 3.3 – never shot down (as of ~2024).",emoji:"✈️"},
  {id:"astro_125",q:"How many times denser is the Sun's core than water?",a:150,unit:"times",hint:"g/cm³ – many times denser than water.",emoji:"☀️"},
  {id:"astro_126",q:"How many km/s do galaxies move away from us?",a:67,unit:"km/s per megaparsec",hint:"The Hubble constant describes the expansion.",emoji:"🌌"},
  {id:"astro_127",q:"How many billion light-years across is the observable universe?",a:93,unit:"billion light-years",hint:"The visible part – the universe itself could be infinite.",emoji:"🌌"},
  {id:"astro_128",q:"How many degrees Celsius is the coldest naturally measured temperature on Earth?",a:-89.2,unit:"°C",hint:"Measured in Antarctica in 1983.",emoji:"🧊"},
  {id:"astro_129",q:"How many km high do stratospheric clouds fly?",a:25,unit:"km",hint:"Nacreous clouds in the stratosphere.",emoji:"☁️"},
  {id:"astro_130",q:"How many minutes does a solar eclipse last at most?",a:7.5,unit:"minutes",hint:"A maximum of 7.5 minutes of total eclipse.",emoji:"🌑"},
  {id:"astro_131",q:"How many km long is the canyon on Mars (Valles Marineris)?",a:4000,unit:"km",hint:"10 times longer than the Grand Canyon.",emoji:"🔴"},
  {id:"astro_132",q:"How many degrees Celsius is the hottest temperature ever measured on Earth?",a:56.7,unit:"°C",hint:"Death Valley, 1913.",emoji:"🌡️"},
  {id:"astro_133",q:"How many km/h does sound travel through steel?",a:18000,unit:"km/h",hint:"50 times faster than in air.",emoji:"🔧"},
  {id:"astro_134",q:"How many hours does it take Pluto to rotate once on its axis?",a:153,unit:"hours",hint:"Pluto rotates very slowly.",emoji:"🌑"},
  {id:"astro_135",q:"How many billion km wide is the event horizon of M87*?",a:40,unit:"billion km",hint:"The first black hole ever photographed.",emoji:"🌑"},
  {id:"astro_136",q:"How many km/h does a hurricane rotate at maximum?",a:300,unit:"km/h",hint:"Category 5 hurricanes exceed 250 km/h.",emoji:"🌀"},
  {id:"astro_137",q:"How many million billion tons of oxygen does Earth's atmosphere contain?",a:1.2,unit:"million billion tons",hint:"21% of the atmosphere is oxygen.",emoji:"💨"},
  {id:"astro_138",q:"How many km thick is Saturn's ring?",a:1,unit:"km",hint:"Up to 1 km – thin as a sheet of paper relative to its width.",emoji:"🪐"},
  {id:"astro_139",q:"How many sunrises does the ISS see per day?",a:16,unit:"sunrises",hint:"The ISS experiences 16 sunrises and sunsets daily.",emoji:"🚀"},
  {id:"astro_140",q:"How many billion years old is the oldest known rock on Earth?",a:4,unit:"billion years",hint:"Found in Australia (as of ~2024).",emoji:"🪨"},
  {id:"astro_141",q:"How many cm farther does the Moon move from Earth each year?",a:3.8,unit:"cm farther",hint:"The Moon moves 3.8 cm farther away every year.",emoji:"🌙"},
  {id:"astro_142",q:"How many tons of asteroid material hit Earth per year?",a:40000,unit:"tons",hint:"As meteor dust – mostly burns up.",emoji:"☄️"},
  {id:"astro_143",q:"What is the diameter of the Great Red Spot, in km?",a:16000,unit:"km",hint:"Larger than Earth.",emoji:"🪐"},
  {id:"astro_144",q:"How many billion light-years away is the CMB from us?",a:46,unit:"billion light-years",hint:"The oldest observable horizon – the cosmic microwave background.",emoji:"🌌"},
  {id:"astro_145",q:"How many hours does it take for a solar storm to travel from the Sun to Earth?",a:2,unit:"hours",hint:"Coronal mass ejections arrive in 1-3 days – but radiation in minutes.",emoji:"☀️"},
  {id:"astro_146",q:"How many m/s² is the gravity on Pluto?",a:0.62,unit:"m/s²",hint:"Only 6% of Earth's gravity.",emoji:"🌑"},
  {id:"astro_147",q:"How many billion neutrinos pass through a cm² of Earth per second?",a:65,unit:"billion",hint:"Neutrinos come from the Sun and pass through everything.",emoji:"⚛️"},
  {id:"astro_148",q:"How many degrees Celsius is the temperature inside a tornado?",a:-10,unit:"°C",hint:"It's cooler in the eye of a tornado.",emoji:"🌪️"},
  {id:"astro_149",q:"How many billion km is Neptune from the Sun?",a:4500,unit:"billion km",hint:"Light takes 4 hours from the Sun to Neptune.",emoji:"🔵"},
  {id:"astro_150",q:"How many thousand tons of gold has humanity mined throughout history?",a:190,unit:"thousand tons",hint:"~190,000 tons mined – asteroids could contain many times that.",emoji:"🪙"},
  {id:"astro_151",q:"How many km/s is the relative speed of the Andromeda Galaxy toward the Milky Way?",a:110,unit:"km/s",hint:"They're moving toward each other – collision in 4 billion years.",emoji:"🌌"},
  {id:"astro_152",q:"How many quadrillion tons of ice are there in Antarctica?",a:26.5,unit:"million gigatons",hint:"26.5 million gigatons of ice.",emoji:"🧊"},
  {id:"astro_153",q:"How many hours does an Earth year last exactly?",a:8766,unit:"hours",hint:"365.25 days × 24 hours.",emoji:"📅"},
  {id:"astro_154",q:"How many billion years old is the Moon?",a:4.5,unit:"billion years",hint:"It formed from a collision with the proto-Earth.",emoji:"🌙"},
  {id:"astro_155",q:"How many degrees Celsius is the coldest known place in the universe?",a:-273,unit:"°C",hint:"The Boomerang Nebula is 1 Kelvin.",emoji:"❄️"},
  {id:"astro_156",q:"How many light-years wide is the solar system (Oort Cloud)?",a:2,unit:"light-years",hint:"Light-years in diameter.",emoji:"☄️"},
  {id:"astro_157",q:"How many tons of meteorite dust fall on Earth daily?",a:100,unit:"tons",hint:"Mostly as micrometeorites.",emoji:"☄️"},
  {id:"astro_158",q:"How many nanometers wide is the visible light spectrum?",a:300,unit:"nanometers",hint:"From 400nm (violet) to 700nm (red).",emoji:"🌈"},
  {id:"astro_159",q:"How many years passed before the first black hole photo was taken?",a:100,unit:"years of theory",hint:"Einstein described them in 1915, photographed in 2019.",emoji:"🌑"},
  {id:"astro_160",q:"How many degrees Celsius is the temperature inside a white dwarf?",a:100000,unit:"°C",hint:"White dwarfs cool down over billions of years.",emoji:"⭐"},
  {id:"astro_161",q:"What is the Moon's diameter, in km?",a:3474,unit:"km",hint:"About 27% of Earth's diameter.",emoji:"🌙"},
  {id:"astro_162",q:"How many km/h does Neptune rotate at its equator?",a:9650,unit:"km/h",hint:"Faster rotation than Earth.",emoji:"🔵"},
  {id:"astro_163",q:"How many degrees Celsius cold is it in the Moon's shadow?",a:-170,unit:"°C",hint:"Extreme temperature swings without an atmosphere.",emoji:"🌑"},
  {id:"astro_164",q:"How far is the Magellanic Cloud from the Milky Way?",a:160000,unit:"light-years",hint:"The nearest satellite galaxy.",emoji:"🌌"},
  {id:"astro_165",q:"How many trillion tons does a cubic meter of neutron star material weigh?",a:1000,unit:"trillion tons",hint:"10¹⁵ tons per m³.",emoji:"⭐"},
  {id:"astro_166",q:"How many hours would it take to drive to the Moon by car?",a:5100,unit:"hours",hint:"At 100 km/h, it would take 5,100 hours.",emoji:"🌙"},
  {id:"astro_167",q:"How many degrees Celsius hot is the Sun's chromosphere?",a:20000,unit:"°C",hint:"The layer above the photosphere.",emoji:"☀️"},
  {id:"astro_168",q:"What is the diameter of Titan (Saturn's moon), in km?",a:5150,unit:"km",hint:"Larger than Mercury.",emoji:"🪐"},
  {id:"astro_169",q:"How many degrees Celsius is the temperature on Io (Jupiter's moon)?",a:-130,unit:"°C",hint:"Volcanically active despite extreme cold.",emoji:"🌋"},
  {id:"astro_170",q:"How many km/s does our Sun move through the Milky Way?",a:220,unit:"km/s",hint:"A galactic year lasts 225 million years.",emoji:"🌌"},
  {id:"astro_171",q:"How many degrees Celsius cold is the darkest known place (Boomerang Nebula)?",a:-272,unit:"°C",hint:"Colder than the cosmic background.",emoji:"❄️"},
  {id:"astro_172",q:"How many km high is the atmosphere of Mars?",a:200,unit:"km",hint:"Very thin – less than 1% of Earth's pressure.",emoji:"🔴"},
  {id:"astro_173",q:"How many hours does light take from Neptune to Earth?",a:4,unit:"hours",hint:"Neptune is about 4.5 billion km away.",emoji:"🔵"},
  {id:"astro_174",q:"How many degrees Celsius is the temperature on Titania (Uranus's moon)?",a:-203,unit:"°C",hint:"One of the coldest moons.",emoji:"🌑"},
  {id:"astro_175",q:"How fast do solar winds travel, in km/h?",a:500000,unit:"km/h",hint:"Even faster during solar storms.",emoji:"☀️"},
  {id:"astro_176",q:"How many billion stars does the Andromeda Galaxy have?",a:1000,unit:"billion",hint:"Almost twice as many as the Milky Way.",emoji:"🌌"},
  {id:"astro_177",q:"How many degrees Celsius is the interior of Jupiter's core?",a:36000,unit:"°C",hint:"Extreme pressure and heat at the center.",emoji:"🪐"},
  {id:"astro_178",q:"What is the diameter of Ceres (dwarf planet), in km?",a:945,unit:"km",hint:"The largest body in the asteroid belt.",emoji:"🌑"},
  {id:"astro_179",q:"How many Earth masses does Neptune have?",a:17,unit:"Earth masses",hint:"Much smaller than Jupiter but still massive.",emoji:"🔵"},
  {id:"astro_180",q:"How many km/s does a pulsar's surface rotate at maximum?",a:0.3,unit:"km/s surface",hint:"716 rotations per second.",emoji:"⭐"},
  {id:"astro_181",q:"How many degrees Celsius is the temperature at Uranus's core?",a:5000,unit:"°C",hint:"Despite the cold exterior, the core is very hot.",emoji:"🟦"},
  {id:"astro_182",q:"How many km high are the clouds on Jupiter?",a:50,unit:"km",hint:"Several layers of ammonia and other compounds.",emoji:"🪐"},
  {id:"astro_183",q:"How many hours does a light beam take from Pluto to Earth?",a:5.5,unit:"hours",hint:"Pluto is about 5.9 billion km away.",emoji:"🌑"},
  {id:"astro_184",q:"How many km/h does Earth orbit the galaxy at?",a:792000,unit:"km/h",hint:"220 km/s around the galactic center.",emoji:"🌌"},
  {id:"astro_185",q:"How many degrees is Uranus's axial tilt?",a:98,unit:"degrees",hint:"Uranus lies almost on its side.",emoji:"🟦"},
  {id:"astro_186",q:"How many trillion galaxies are there in the observable universe (latest estimate)?",a:2,unit:"trillion",hint:"2 trillion galaxies – each with hundreds of billions of stars.",emoji:"⭐"},
  {id:"astro_187",q:"How many degrees Celsius is the surface of Enceladus (Saturn's moon)?",a:-201,unit:"°C",hint:"There's liquid water beneath the ice.",emoji:"❄️"},
  {id:"astro_188",q:"How many million km apart are Earth and Mars at their closest point?",a:56,unit:"million km",hint:"Million km at the closest approach.",emoji:"🔴"},
  {id:"astro_189",q:"How many degrees Celsius cold is the interstellar medium between stars?",a:-263,unit:"°C",hint:"Nearly absolute zero.",emoji:"❄️"},
  {id:"astro_190",q:"How many million km long can a comet's tail grow?",a:150,unit:"million km",hint:"Comet tails can reach the Sun-Earth distance.",emoji:"☄️"},
  {id:"astro_191",q:"How many hours was the longest Apollo mission (Apollo 17) on the Moon?",a:75,unit:"hours",hint:"3 days 3 hours on the lunar surface (as of ~2024).",emoji:"🌙"},
  {id:"astro_192",q:"How many billion light-years away is the oldest known light?",a:13.8,unit:"billion light-years",hint:"The cosmic microwave background (as of ~2024).",emoji:"🌌"},
  {id:"astro_193",q:"How many degrees Celsius is the temperature in Jupiter's storm (Great Red Spot)?",a:-160,unit:"°C",hint:"Colder than the surrounding clouds.",emoji:"🪐"},
  {id:"astro_194",q:"How many billion km away is the heliopause (the edge of the solar system)?",a:18,unit:"billion km",hint:"The heliopause – where the solar wind ends.",emoji:"☄️"},
  {id:"astro_195",q:"How many Earth masses does Uranus have?",a:14.5,unit:"Earth masses",hint:"Uranus is the smallest ice giant.",emoji:"🟦"},
  {id:"astro_196",q:"How many thousand degrees Celsius is the hottest known star (WR 102)?",a:210,unit:"thousand °C",hint:"200 times hotter than our Sun.",emoji:"⭐"},
  {id:"astro_197",q:"How many degrees Celsius is the surface of Io's (Jupiter's moon) volcanoes?",a:1600,unit:"°C",hint:"Io has the most active volcanoes in the solar system.",emoji:"🌋"},
  {id:"astro_198",q:"How many billion km is the Oort Cloud from the Sun?",a:7500,unit:"billion km",hint:"The outermost region of our solar system.",emoji:"☄️"},
  {id:"astro_199",q:"How many km thick is Europa's ice shell (Jupiter's moon)?",a:25,unit:"km",hint:"Beneath the ice: a liquid ocean.",emoji:"❄️"},
  {id:"astro_200",q:"How many new stars form per year in the Milky Way?",a:1,unit:"stars/year",hint:"About 1 new star per year.",emoji:"⭐"},
  {id:"astro_201",q:"How many degrees Celsius cold is the Moon's polar region (permanent shadow)?",a:-248,unit:"°C",hint:"Near absolute zero in the craters.",emoji:"🌑"},
  {id:"astro_202",q:"How many km/h is the rotation speed of Saturn's core?",a:30000,unit:"km/h",hint:"Very fast rotation of the gas giant.",emoji:"🪐"},
  {id:"astro_203",q:"How many million years does the Sun take for one orbit around the Milky Way?",a:225,unit:"million years",hint:"225 million years – a galactic year.",emoji:"🌌"},
  {id:"astro_204",q:"How many million degrees Celsius is the temperature of the solar corona?",a:2,unit:"million °C",hint:"Mysteriously hotter than the surface.",emoji:"☀️"},
  {id:"astro_205",q:"What is the diameter of Enceladus (Saturn's moon), in km?",a:500,unit:"km",hint:"A small moon with a massive water plume.",emoji:"🪐"},
  {id:"astro_206",q:"How many million tons of helium does the Sun produce daily?",a:695,unit:"million tons",hint:"Million tons daily.",emoji:"☀️"},
  {id:"astro_207",q:"How many km high is Olympus Mons on Mars?",a:21,unit:"km",hint:"The tallest known volcano in the solar system.",emoji:"🔴"},
  {id:"astro_208",q:"How many degrees Celsius is the temperature on Venus's surface at night?",a:465,unit:"°C",hint:"Day and night are almost equally hot due to the greenhouse effect.",emoji:"🌋"},
  {id:"astro_209",q:"How many km/h do interstellar comets travel at?",a:100000,unit:"km/h",hint:"ʻOumuamua moved at over 85,000 km/h.",emoji:"☄️"},
  {id:"astro_210",q:"How many billion degrees Celsius is the temperature inside neutron stars?",a:100,unit:"billion °C",hint:"100 billion degrees – unimaginable.",emoji:"⭐"},
  {id:"astro_211",q:"How many million km is Saturn's outermost moon Phoebe from Saturn?",a:12.9,unit:"million km",hint:"12.9 million km from Saturn.",emoji:"🪐"},
  {id:"astro_212",q:"How many degrees does the Sun rotate per day at its equator?",a:14,unit:"degrees",hint:"The Sun rotates differentially – the equator faster.",emoji:"☀️"},
  {id:"astro_213",q:"How many minutes after the Big Bang did the first atomic nuclei form?",a:3,unit:"minutes",hint:"Big Bang nucleosynthesis lasted 3 minutes.",emoji:"⚛️"},
  {id:"astro_214",q:"How many million km/h do solar winds reach during strong solar storms?",a:3,unit:"million km/h",hint:"3 million km/h during powerful solar eruptions.",emoji:"☀️"},
  {id:"astro_215",q:"How many billion tons of ice does the north pole of Mars contain?",a:1600,unit:"billion tons",hint:"Enough to cover Mars in 11m of water.",emoji:"🔴"},
  {id:"astro_216",q:"How many degrees Celsius cold is Triton (Neptune's moon)?",a:-235,unit:"°C",hint:"One of the coldest bodies in the solar system.",emoji:"❄️"},
  {id:"astro_217",q:"What is the diameter of Pluto, in km?",a:2377,unit:"km",hint:"Smaller than Russia.",emoji:"🌑"},
  {id:"astro_218",q:"How many hours does light take from Alpha Centauri to Earth?",a:38264,unit:"hours",hint:"4.37 light-years × 8,760 hours/year.",emoji:"⭐"},
  {id:"astro_219",q:"How many km/h does the Sun's surface rotate at the equator?",a:7000,unit:"km/h",hint:"About 2 km/s rotational speed.",emoji:"☀️"},
  {id:"astro_220",q:"How many meters in size is a typical asteroid in the asteroid belt?",a:500,unit:"meters",hint:"Most are smaller than 1 km – only a few are larger.",emoji:"☄️"},
  {id:"astro_221",q:"How many degrees Celsius cold is it in Mercury's polar craters?",a:-180,unit:"°C",hint:"Permanent ice in permanently shadowed regions.",emoji:"☿"},
];
