// 💀 BIZARRE RECORDS – English
export default [
  {q:"Wie lang war der längste Fingernagel einer Frau in cm?",a:909,unit:"cm",hint:"Lee Redmond ließ ihre Nägel 30 Jahre wachsen.",emoji:"💅"},
  {q:"How many Hotdogs aß Joey Chestnut als Weltrekord in 10 Minuten?",a:76,unit:"Hotdogs",hint:"Bei der berühmten Nathan's Hot Dog Contest.",emoji:"🌭"},
  {q:"How heavy war der schwerste jemals gezüchtete Kürbis in kg?",a:1190,unit:"kg",hint:"Der Riesenkürbis wurde 2021 in Italien gewogen.",emoji:"🎃"},
  {q:"How many Piercings hatte humans mit den meisten?",a:4384,unit:"Piercings",hint:"Rolf Buchholz aus Deutschland hielt diesen Rekord.",emoji:"💎"},
  {q:"Wie lang war der längste jemals gemessene Bart in cm?",a:570,unit:"cm",hint:"Hans Langseth trug ihn ein Leben lang.",emoji:"🧔"},
  {q:"How many Stunden hielt der längste Kuss der Welt?",a:58,unit:"hours",hint:"Ein thailändisches Pärchen küsste sich 2013 ununterbrochen.",emoji:"💋"},
  {q:"How many km/h fuhr das schnellste muskelkraftbetriebene Fahrrad?",a:280,unit:"km/h",hint:"Im Windschatten eines Rennwagens aufgestellt.",emoji:"🚴"},
  {q:"Wie alt war die älteste jemals lebende Katze in Jahren?",a:38,unit:"years",hint:"Creme Puff aus Texas lebte von 1967 bis 2005.",emoji:"🐱"},
  {q:"How many Sprachen spricht der Polyglott Ziad Fazah?",a:58,unit:"Sprachen",hint:"Er beherrscht Sprachen aus aller Welt.",emoji:"🗣️"},
  {q:"How many Meter tief ist die Kola-Bohrung in Russland?",a:12262,unit:"meters",hint:"Das tiefste Loch der Welt – nach 24 Jahren gestoppt.",emoji:"⛏️"},
  {q:"How heavy war das schwerste jemals gewogene Schwein in kg?",a:1157,unit:"kg",hint:"Big Bill hieß das Riesenschwein aus den USA (1933).",emoji:"🐷"},
  {q:"How many Meter lang war die längste jemals gebackene Pizza?",a:1930,unit:"meters",hint:"Gebacken 2017 in Kalifornien.",emoji:"🍕"},
  {q:"Wie alt wurde der älteste Mensch aller Zeiten in Jahren?",a:122,unit:"years",hint:"Jeanne Calment aus Frankreich, 1875–1997.",emoji:"👴"},
  {q:"How many Domino-Steine wurden beim größten Domino-Effekt verwendet?",a:4491863,unit:"Steine",hint:"2009 in den Niederlanden aufgestellt.",emoji:"🎲"},
  {q:"How many Bienen saßen gleichzeitig auf einem Menschen als Rekord?",a:637000,unit:"Bienen",hint:"Das entspricht einem Gewicht von ~63 kg Bienen.",emoji:"🐝"},
  {q:"How many Stockwerke hat der Burj Khalifa?",a:163,unit:"Stockwerke",hint:"828 Meter hoch, steht in Dubai.",emoji:"🏙️"},
  {q:"How many km lief der Weltrekordhalter Yiannis Kouros non-stop?",a:426,unit:"km",hint:"1997 in Australien aufgestellt.",emoji:"🏃"},
  {q:"How many Kugeln Eis aß der Weltrekordhalter in einer Stunde?",a:254,unit:"Kugeln",hint:"Der Wettbewerb fand in Italien statt.",emoji:"🍦"},
  {q:"How heavy war das schwerste jemals gefangene Krokodil in kg?",a:1075,unit:"kg",hint:"Ein Salzwasserkrokodil von den Philippinen.",emoji:"🐊"},
  {q:"How many m² groß war das größte jemals gemalte Gemälde?",a:17000,unit:"m²",hint:"Sacha Jafri malte es 2021 in Dubai.",emoji:"🎨"},
  {q:"How many km/h erreichte die schnellste Tennisaufschlagsgeschwindigkeit?",a:263,unit:"km/h",hint:"Samuel Groth aus Australien, 2012.",emoji:"🎾"},
  {q:"How many Meter weit wurde ein Gummistiefel beim Weitwurf geworfen?",a:63,unit:"meters",hint:"Offizieller Weltrekord im finnischen Stiefelweitwurf.",emoji:"👢"},
  {q:"How many Kerzen standen auf der größten Geburtstagstorte?",a:72585,unit:"Kerzen",hint:"Die Torte wurde 2016 in Indien aufgestellt.",emoji:"🎂"},
  {q:"Wie lang war die längste jemals gemessene Haarlänge einer Frau in cm?",a:570,unit:"cm",hint:"Xie Qiuping aus China ließ sie seit 1973 wachsen.",emoji:"💇"},
  {q:"How many Personen saßen gleichzeitig auf einem Motorrad als Rekord?",a:58,unit:"people",hint:"Aufgestellt von der indischen Armee.",emoji:"🏍️"},
  {q:"How many Meilen fuhr die längste je dokumentierte Taxifahrt?",a:21000,unit:"Meilen",hint:"Ein Brite fuhr von London nach Melbourne.",emoji:"🚕"},
  {q:"Wie lang war der längste Bart einer Frau in cm?",a:30,unit:"cm",hint:"Harnaam Kaur aus UK trägt den Rekord.",emoji:"🧔‍♀️"},
  {q:"How many Stunden badete humans mit dem längsten Bad im Toten Meer?",a:48,unit:"hours",hint:"Das extrem salzige Wasser macht langes Baden möglich.",emoji:"🛁"},
  {q:"How many Mal schlug ein Boxer in einer Minute auf einen Sandsack?",a:217,unit:"Schläge",hint:"Westley Lyons stellte diesen Rekord auf.",emoji:"🥊"},
  {q:"How many Meter lang war das längste Surfbrett?",a:12,unit:"meters",hint:"Gebaut 2015 in Australien – mit 66 Surfern drauf.",emoji:"🏄"},
  {q:"How many kg Zwiebeln schälte der Weltrekordhalter in einer Stunde?",a:11.6,unit:"kg",hint:"Unter Tränen natürlich.",emoji:"🧅"},
  {q:"How many Meter weit spuckte der Weitspuck-Weltmeister einen Kirschkern?",a:28.5,unit:"meters",hint:"Aufgestellt beim World Cherry Pit Spitting Championship.",emoji:"🍒"},
  {q:"How many Trampolin-Sprünge schaffte der Rekordhalter in einer Minute?",a:245,unit:"Sprünge",hint:"Fast 4 Sprünge pro Sekunde.",emoji:"🤸"},
  {q:"How many Stunden trug humans mit dem längsten Kopfstand auf sich?",a:3,unit:"hours",hint:"Rekord von Bryce Lane aus 2019.",emoji:"🤸"},
  {q:"How many Meter lang war der längste Zopf einer Frau?",a:2.97,unit:"meters",hint:"Rekord aus China 2021.",emoji:"💇"},
  {q:"How many Stockwerke hat das höchste Hotel der Welt (Gevora Dubai)?",a:75,unit:"Stockwerke",hint:"356 Meter hoch mit 528 Zimmern.",emoji:"🏨"},
  {q:"How many Meter weit sprang a human auf einem Pogo-Stick?",a:33,unit:"meters",hint:"Brent Sherwood hüpfte 33 Meter weit.",emoji:"🦘"},
  {q:"How many Hamburger aß der Rekordhalter in 3 Minuten?",a:12,unit:"Hamburger",hint:"Kobayashi schaffte 12 Burgern in 180 Sekunden.",emoji:"🍔"},
  {q:"How many Meter lang war der größte Weihnachtsstrumpf?",a:51,unit:"meters",hint:"Gestrickt 2018 in Großbritannien.",emoji:"🧦"},
  {q:"How many Stunden tanzte der Weltrekordhalter ununterbrochen?",a:123,unit:"hours",hint:"Über 5 Tage ohne Schlaf tanzend.",emoji:"💃"},
  {q:"How many Treppen stieg der schnellste Empire State Building Runner in Minuten?",a:9.8,unit:"minutes",hint:"1576 Stufen auf 86 Stockwerke.",emoji:"🏃"},
  {q:"How many kg wog das schwerste jemals gegrillte Steak?",a:1098,unit:"kg",hint:"Ein Riesensteak für den Weltrekord.",emoji:"🥩"},
  {q:"How many Meter tief tauchte der Rekordtaucher auf einem einzigen Atemzug?",a:214,unit:"meters",hint:"Herbert Nitsch – der tiefste Mann der Welt.",emoji:"🤿"},
  {q:"How many km lief der älteste Marathon-Finisher in Jahren?",a:100,unit:"Jahre alt",hint:"Fauja Singh aus Indien lief einen Marathon mit 100 Jahren.",emoji:"🏃"},
  {q:"How many Stunden nonstop spielte der Weltrekord-Videospieler?",a:138,unit:"hours",hint:"Fast 6 Tage nonstop zocken.",emoji:"🎮"},
  {q:"How heavy war das schwerste Kaninchen in kg?",a:22,unit:"kg",hint:"Darius – ein Kontinentaler Riese aus England.",emoji:"🐰"},
  {q:"How many Meter lang war der längste Schachspieler-Bart?",a:2.13,unit:"meters",hint:"Der Bärtler spielte gleichzeitig Schach.",emoji:"🧔"},
  {q:"How many Liegestütze machte der Rekordhalter in einer Minute?",a:138,unit:"Liegestütze",hint:"Rekord von Carlton Williams aus 2022.",emoji:"💪"},
  {q:"How many Meter lang war die längste Menschenkette unter Wasser?",a:269,unit:"meters",hint:"Über 300 Taucher bildeten 2015 diese Kette.",emoji:"🤿"},
  {q:"How many Stunden fuhr der Langstrecken-Fahrrad-Weltrekordler?",a:72,unit:"hours",hint:"Amanda Coker fuhr 72 Stunden nonstop.",emoji:"🚴"},
  {q:"How many Meter weit schoss der weiteste Elfmeter?",a:100,unit:"meters",hint:"Mit einem speziellen Kanonenschuss erzielt.",emoji:"⚽"},
  {q:"How many kg Curry aß der Rekordhalter in einer Stunde?",a:8.8,unit:"kg",hint:"Juliet Lee schaffte 8,8 kg Curry in 60 Minuten.",emoji:"🍛"},
  {q:"How many Stunden sang der Weltrekord-Karaoke-Sänger?",a:101,unit:"hours",hint:"In Indien wurde dieser Ausdauer-Rekord aufgestellt.",emoji:"🎤"},
  {q:"How heavy war der schwerste Mensch aller Zeiten in kg?",a:635,unit:"kg",hint:"Jon Brower Minnoch aus den USA wog 635 kg.",emoji:"⚖️"},
  {q:"How many m hoch war der höchste Sprung auf einem Snowboard?",a:9,unit:"meters",hint:"Travis Rice erzielte diesen Rekord in einem Halfpipe.",emoji:"🏂"},
  {q:"How many Gurken aß der Rekordhalter in einer Minute?",a:8,unit:"Gurken",hint:"Komplette Gurken, nicht Scheiben.",emoji:"🥒"},
  {q:"How many Meter lang war der längste Laufsteg bei einer Modenschau?",a:6.5,unit:"km",hint:"Unilever organisierte 2020 diesen Rekord.",emoji:"👠"},
  {q:"How many Stunden stand humans auf einem Bein als Weltrekord?",a:76,unit:"hours",hint:"Majid Khan aus Pakistan, 2016.",emoji:"🦩"},
  {q:"How many km/h fuhr der schnellste Rollstuhl bergab?",a:130,unit:"km/h",hint:"Ein speziell modifizierter Rennrollstuhl.",emoji:"♿"},
  {q:"How many Meter lang war das längste Sandwich?",a:735,unit:"meters",hint:"Hergestellt 2015 in Mexiko.",emoji:"🥪"},
  {q:"How many Stunden lief der längste Ultramarathon?",a:240,unit:"hours",hint:"10 Tage non-stop laufen.",emoji:"🏃"},
  {q:"How heavy war die schwerste in einem Stück gekochte Pasta in kg?",a:5900,unit:"kg",hint:"Fast 6 Tonnen Pasta in einem einzigen Gericht.",emoji:"🍝"},
  {q:"How many Meter lang war die längste Girlande?",a:5650,unit:"meters",hint:"In den Philippinen hergestellt für Weihnachten 2015.",emoji:"🎄"},
  {q:"How many Stunden sang ein Chor ununterbrochen als Weltrekord?",a:120,unit:"hours",hint:"Ein indischer Chor sang 5 Tage nonstop.",emoji:"🎵"},
  {q:"How many Meter lang war der längste Popcorn-Trail?",a:1768,unit:"meters",hint:"Aufgebaut 2020 in Tschechien.",emoji:"🍿"},
  {q:"How many kg wog das schwerste Weihnachtsplätzchen?",a:400,unit:"kg",hint:"Ein einziger riesiger Lebkuchen.",emoji:"🍪"},
  {q:"How many Stunden Dauerschlaf hielt der Weltrekordhalter durch?",a:11,unit:"hours",hint:"Peter Tripp blieb 201 Stunden wach – das ist der Gegenteil-Rekord.",emoji:"😴"},
  {q:"How many km/h fuhr a human auf einer Bananenschale gleitend?",a:3,unit:"km/h",hint:"Experiment zur Reibung von Bananenschalen.",emoji:"🍌"},
  {q:"How many Meter lang war der längste Volleyball-Rallye-Wechsel?",a:120,unit:"times",hint:"Pässe ohne Ballberührung des Bodens.",emoji:"🏐"},
  {q:"How many Stunden spielte ein Pianist ununterbrochen als Weltrekord?",a:120,unit:"hours",hint:"Klavierspielen 5 Tage nonstop.",emoji:"🎹"},
  {q:"How heavy war das schwerste gegessene Steak in 9 Minuten?",a:1.36,unit:"kg",hint:"Das US-Steak-Wettessen-Rekord.",emoji:"🥩"},
  {q:"How many Meter lang war die längste Nudel?",a:3776,unit:"meters",hint:"Hergestellt in China, lang wie der Fuji.",emoji:"🍜"},
  {q:"How many Sekunden lief der 100m-Sprint als absolute Bestzeit?",a:9.58,unit:"seconds",hint:"Usain Bolt, Berlin 2009.",emoji:"⚡"},
  {q:"How many m hoch ist die höchste je erklommene Welle beim Surfen?",a:24,unit:"meters",hint:"Rodrigo Koxa surfte 2017 diese Riesenwelle.",emoji:"🏄"},
  {q:"How many Marshmallows stopfte sich a man gleichzeitig in den Mund?",a:25,unit:"Marshmallows",hint:"Weltrekord im Marshmallow-Stopfen.",emoji:"🍬"},
  {q:"How many Stifte hielt der Weltrekordhalter gleichzeitig zwischen den Fingern?",a:60,unit:"Stifte",hint:"Lorenzo Resta, Italien 2019.",emoji:"✏️"},
  {q:"How many m lang war die längste Girlande aus Popcorn?",a:1200,unit:"meters",hint:"Aufgefädelt in Schoolkids in den USA.",emoji:"🍿"},
  {q:"How heavy war das schwerste Hühnerei in Gramm?",a:454,unit:"grams",hint:"Das schwerste bekannte Hühnerei der Geschichte.",emoji:"🥚"},
  {q:"How many Meter lang war das längste Fischfilet?",a:121,unit:"meters",hint:"Ein Thunfischfilet in Japan aufgeschnitten.",emoji:"🐟"},
  {q:"How many Liter Milch trank der Weltrekordhalter in einer Stunde?",a:4,unit:"liters",hint:"Liter für Liter – ein ekelhafter Rekord.",emoji:"🥛"},
  {q:"How many Stunden blieb jemand in eiskaltem Wasser am längsten?",a:24,unit:"hours",hint:"Wim Hof setzte diesen Rekord im Eisbad.",emoji:"🧊"},
  {q:"How many km/h fuhr a human auf einem Laufband als Rekord?",a:45,unit:"km/h",hint:"Sprints auf dem Laufband.",emoji:"🏃"},
  {q:"How many Wasserflaschen balancierten auf dem Kopf des Rekordhalters?",a:24,unit:"Flaschen",hint:"Dr. Ashrita Furman, Weltrekordhalter schlechthin.",emoji:"🍶"},
  {q:"How many Meter lang war das längste Currywurst?",a:96,unit:"meters",hint:"Aufgestellt beim Karneval in Deutschland.",emoji:"🌭"},
  {q:"How many Höhenmeter kletterte der schnellste Everest-Aufstieg?",a:8849,unit:"meters",hint:"Nirmal Purja schaffte den Aufstieg in weniger als 7 Stunden.",emoji:"🏔️"},
  {q:"How many Stunden joggte der älteste Marathonläufer Fauja Singh kontinuierlich?",a:8.5,unit:"hours",hint:"Mit 100 Jahren lief er einen kompletten Marathon.",emoji:"🏃"},
  {q:"How many Bälle jonglierte der Rekordhalter gleichzeitig?",a:14,unit:"Bälle",hint:"Alex Barron jonglierte 14 Bälle 2017.",emoji:"🎪"},
  {q:"How many Meter lang war die längste Schleppe eines Hochzeitskleids?",a:3000,unit:"meters",hint:"Ein 3 km langes Brautkleid aus Rumänien.",emoji:"👰"},
  {q:"How many Liter Coca-Cola trank der Rekordhalter in einer Stunde?",a:2,unit:"liters",hint:"Durch einen Strohhalm natürlich.",emoji:"🥤"},
  {q:"How many Eierkuchen übereinander schichtete der Rekordhalter?",a:76,unit:"Eierkuchen",hint:"Ein instabiler Turm aus Eierkuchen.",emoji:"🥞"},
  {q:"How many Meter lang war das größte Omelette?",a:14,unit:"Meter Durchmesser",hint:"In Frankreich, dem Land des Omeletts.",emoji:"🍳"},
  {q:"How many Stunden nonstop schaute jemand Netflix als Weltrekord?",a:94,unit:"hours",hint:"Fast 4 Tage ununterbrochen Netflix.",emoji:"📺"},
  {q:"How many kg Käse wurde beim größten Käsefondue verwendet?",a:740,unit:"kg",hint:"Ein riesiger Topf Käse in der Schweiz.",emoji:"🧀"},
  {q:"How many Meter lang war der längste Zug aus Liegestühlen?",a:2000,unit:"meters",hint:"2 km Liegestühle in einer Reihe.",emoji:"🏖️"},
  {q:"How many Tage fastete der Weltrekordhalter?",a:382,unit:"days",hint:"Angus Barbieri fastete unter medizinischer Aufsicht.",emoji:"🚫"},
  {q:"How many kg Kartoffeln schälte der Rekordhalter in einer Stunde?",a:30,unit:"kg",hint:"Ein Weltrekord aus Irland.",emoji:"🥔"},
  {q:"How many Stunden spielte eine Band nonstop als Weltrekord?",a:134,unit:"hours",hint:"Über 5 Tage Livemusik.",emoji:"🎸"},
  {q:"How many Meter lang war das längste Sushi?",a:2544,unit:"meters",hint:"In Japan hergestellt für den Weltrekord.",emoji:"🍣"},
  {q:"How many Stunden stand humans auf einem Surfbrett auf einem See?",a:40,unit:"hours",hint:"Nonstop surfen auf einem Binnensee.",emoji:"🏄"},
  {q:"How many Münzen stapelte der Rekordhalter auf einem Finger?",a:253,unit:"Münzen",hint:"Balanciert auf einem einzelnen Zeigefinger.",emoji:"🪙"},
  {q:"How many km weit schwamm der Langstreckenschwimmer nonstop?",a:225,unit:"km",hint:"Martin Strel schwamm über 225 km am Stück.",emoji:"🏊"},
  {q:"How many Meter hoch kletterte die Rekordklettererin ohne Seil?",a:600,unit:"meters",hint:"Alex Honnold kletterte den El Capitan frei (893m).",emoji:"🧗"},
  {q:"How many Stunden hielt der Rekordhalter eine Yoga-Position?",a:7,unit:"hours",hint:"Extreme Ausdauer in einer einzigen Pose.",emoji:"🧘"},
  {q:"How many kg wiegt das schwerste Schokoladenei der Welt?",a:4000,unit:"kg",hint:"Ein 4 Tonnen schweres Schokoladenei aus Italien.",emoji:"🍫"},
  {q:"How many Mal flippte der Rekordhalter ein Wasserflasche nonstop?",a:2000,unit:"times",hint:"Flipping Bottles war ein Trend – einer machte es viele Male.",emoji:"🍶"},
  {q:"How many Bücher las der Weltrekordleser in einer Woche?",a:100,unit:"Bücher",hint:"Speedreader Howard Berg las 25000 Wörter pro Minute.",emoji:"📚"},
  {q:"How many Meter lang war der größte Cheeseburger?",a:60,unit:"cm Höhe",hint:"Ein 60 cm hoher Turm-Cheeseburger.",emoji:"🍔"},
  {q:"How many Sekunden hielt a human einen lebenden Skorpion im Mund?",a:33,unit:"seconds",hint:"Ein sehr gefährlicher Weltrekord.",emoji:"🦂"},
  {q:"How many Stunden badete jemand in Bier als Weltrekord?",a:3,unit:"hours",hint:"In einem mit Bier gefüllten Whirlpool.",emoji:"🍺"},
  {q:"How many km/h fuhr das schnellste Motorrad je?",a:605,unit:"km/h",hint:"Das Streamliner-Motorrad von Ack Attack.",emoji:"🏍️"},
  {q:"How many Stunden spielte jemand Schach nonstop?",a:60,unit:"hours",hint:"Über 2,5 Tage ununterbrochen Schach.",emoji:"♟️"},
  {q:"How heavy war das schwerste verkaufte Einzel-Stück Trüffel in kg?",a:1.89,unit:"kg",hint:"2007 für 330.000€ bei Sotheby's versteigert.",emoji:"🍄"},
  {q:"How many Meter lang war die längste Schlange aus Karotten?",a:1000,unit:"meters",hint:"1 km Karotten in einer Reihe aufgestellt.",emoji:"🥕"},
  {q:"How many Stunden blieb jemand in einer Tonne Eiswürfel vergraben?",a:2.5,unit:"hours",hint:"Jin Songhao überlebte 2.5 Stunden eingefroren.",emoji:"🧊"},
  {q:"How many kg Avocados schälte der Rekordhalter in einer Minute?",a:8,unit:"Stück",hint:"Avocados in 60 Sekunden geschält.",emoji:"🥑"},
  {q:"How many Bananen schälte der Rekordhalter in einer Minute mit dem Fuß?",a:8,unit:"Bananen",hint:"Mit den Zehen – nicht mit den Händen.",emoji:"🍌"},
  {q:"How many Meter lang war die längste Bratwurst?",a:648,unit:"meters",hint:"Hergestellt in Österreich für den Weltrekord.",emoji:"🌭"},
  {q:"How many Stunden überlebte jemand ohne Schlaf als Rekord?",a:449,unit:"hours",hint:"Randy Gardner blieb 264 Stunden wach – das ist der offizielle Rekord.",emoji:"😴"},
  {q:"How many Ballonhunde formte der Rekordhalter in einer Stunde?",a:747,unit:"Ballonhunde",hint:"John Cassidy formte fast einen pro 5 Sekunden.",emoji:"🐶"},
  {q:"How many Meter lang war der längste Hot Dog?",a:203,unit:"meters",hint:"2011 in Paraguay hergestellt.",emoji:"🌭"},
  {q:"How many Stunden sitzt der Weltrekordler in einer Sauna?",a:16,unit:"hours",hint:"In Finnland natürlich.",emoji:"🧖"},
  {q:"How many kg Spaghetti aß der Rekordhalter in 30 Sekunden?",a:0.7,unit:"kg",hint:"700g Nudeln in einer halben Minute.",emoji:"🍝"},
  {q:"How many Liegestütze machte der Rekordhalter in 24 Stunden?",a:46001,unit:"Liegestütze",hint:"Charles Servizio 1993.",emoji:"💪"},
  {q:"How many km weit rollte a man auf einem Einrad nonstop?",a:1458,unit:"km",hint:"Lon Allen Hughes fuhr quer durch die USA.",emoji:"🎪"},
  {q:"How many Stunden hielt der Weltrekordhalter ein Tablett auf einem Finger?",a:2,unit:"hours",hint:"Ein Tablett balanciert auf einer Fingerspitze.",emoji:"🤸"},
  {q:"How many Tortillas aß der Rekordhalter in einer Minute?",a:13,unit:"Tortillas",hint:"Mexikanische Burrito-Wettessen-Weltrekord.",emoji:"🌮"},
  {q:"How heavy war das schwerste Sushi-Platte der Welt in kg?",a:6500,unit:"kg",hint:"6,5 Tonnen Sushi in Japan aufgetischt.",emoji:"🍣"},
  {q:"How many Meter lang war die längste Laterne aus Papier?",a:2000,unit:"meters",hint:"In China zur Feier des Laternenfests.",emoji:"🏮"},
  {q:"How many Stunden spielte jemand Basketball ununterbrochen?",a:120,unit:"hours",hint:"5 Tage Basketball ohne Schlaf.",emoji:"🏀"},
  {q:"How many Sekunden brauchte der schnellste Rubik's Cube Löser?",a:3.13,unit:"seconds",hint:"Max Park löste den Cube 2023.",emoji:"🧩"},
  {q:"How many Meter weit sprang ein Motorrad über Autos?",a:115,unit:"meters",hint:"Robbie Maddison überquerte 46 Autos.",emoji:"🏍️"},
  {q:"How many Pfannkuchen warf der Rekordhalter in einer Minute?",a:140,unit:"Pfannkuchen",hint:"Mike Cuzzacrea 1994.",emoji:"🥞"},
  {q:"How heavy war das schwerste gegrillte Würstchen in kg?",a:80,unit:"kg",hint:"Ein 80 kg schweres Riesenwürstchen.",emoji:"🌭"},
  {q:"How many Minuten hielt der längste Handstand am Stück?",a:56,unit:"minutes",hint:"Dave Brett, 1992.",emoji:"🤸"},
  {q:"How many Meter tief stieg der Taucher mit dem Taucheranzug?",a:701,unit:"meters",hint:"Nuno Gomes, 2005 im Roten Meer.",emoji:"🤿"},
  {q:"How many Stunden schlief humans mit dem längsten Mittagsschlaf?",a:5,unit:"hours",hint:"Der ausgedehnteste dokumentierte Nickerchen.",emoji:"😴"},
  {q:"How many Meter lang war der längste Knaller-Feuerwerk-Streifen?",a:5765,unit:"meters",hint:"In Mexiko 2018 aufgestellt.",emoji:"🎆"},
  {q:"How heavy war die schwerste Zwiebel der Welt in kg?",a:8.96,unit:"kg",hint:"Tony Glover aus England züchtete sie 2012.",emoji:"🧅"},
  {q:"How many Stunden trug jemand ein Brautkleid am längsten?",a:108,unit:"hours",hint:"Eine Frau trug 4,5 Tage lang ein Brautkleid.",emoji:"👰"},
  {q:"How many Sekunden brauchte der schnellste Kartenspieler für ein Deck?",a:10,unit:"seconds",hint:"Ein komplettes Kartenspiel sortieren.",emoji:"🃏"},
  {q:"How many Meter weit wurde eine Kuh bei einem Rennen geritten?",a:200,unit:"meters",hint:"Kuhrennen in Bayern – ein echter Sport.",emoji:"🐄"},
  {q:"How many Stunden blieb ein Team in einem Aufzug eingeschlossen als Weltrekord?",a:41,unit:"hours",hint:"Nicholas White war allein 41 Stunden im Aufzug gefangen.",emoji:"🛗"},
  {q:"How many Stockwerke lief der schnellste Treppenläufer beim Eiffelturm hoch?",a:9,unit:"minutes",hint:"1665 Stufen – der Rekord steht seit 2017.",emoji:"🗼"},
  {q:"How many Meter lang war der längste Bleistift?",a:323,unit:"meters",hint:"In Sri Lanka hergestellt.",emoji:"✏️"},
  {q:"How many Stunden meditierte der Weltrekord-Meditator?",a:40,unit:"days",hint:"Ein Tibetanischer Mönch meditierte 40 Tage.",emoji:"🧘"},
  {q:"How many Geburtstagstorten aß der Rekordhalter in einer Stunde?",a:14,unit:"Stück",hint:"Jeder Slice war dabei ein komplettes Kuchenstück.",emoji:"🎂"},
  {q:"How many Klimmzüge schaffte der Rekordhalter in einer Minute?",a:50,unit:"Klimmzüge",hint:"Jan Kares, 2019.",emoji:"💪"},
  {q:"How many Meter lang war das längste Spinnennetz?",a:25,unit:"meters",hint:"Eine Kolonial-Spinnenart baute es in den USA.",emoji:"🕸️"},
  {q:"How many Sekunden dauerte der längste gemessene Blitzschlag?",a:7.74,unit:"seconds",hint:"In Brasilien 2020 gemessen.",emoji:"⚡"},
  {q:"How many Stunden sang Maria Callas am längsten am Stück?",a:8,unit:"hours",hint:"Ein Endlos-Konzert-Rekord in der Oper.",emoji:"🎤"},
  {q:"How many Meter lang war die längste Wäscheleine?",a:1500,unit:"meters",hint:"Mit Wäschestücken behangen in Kroatien.",emoji:"👕"},
  {q:"How many Stunden fuhr ein Tandem-Fahrrad-Team nonstop?",a:24,unit:"hours",hint:"24h Tandemfahren ohne Pause.",emoji:"🚴"},
  {q:"How many Stunden rief a human als Weltrekord ununterbrochen?",a:21,unit:"hours",hint:"Stunden Dauerrufen ohne Pause.",emoji:"📢"},
  {q:"How many Meter lang war der längste Schuh?",a:6.4,unit:"meters",hint:"Ein Riesen-Sportschuh als Kunstwerk.",emoji:"👟"},
  {q:"How many Stunden rollte a human auf einem Skateboard nonstop?",a:36,unit:"hours",hint:"Über einen Tag und eine Nacht Skaten.",emoji:"🛹"},
  {q:"How many Stühle hob der Stärkste mit dem Mund hoch?",a:24,unit:"Stühle",hint:"Georges Christen hielt 24 Stühle mit den Zähnen.",emoji:"🦷"},
  {q:"How many Meter lang war die längste Blumenkette?",a:4000,unit:"meters",hint:"In Indien für ein Fest hergestellt.",emoji:"🌸"},
  {q:"How many Stunden hielt a child einen Hula-Hoop in der Luft?",a:74,unit:"hours",hint:"Marawa Ibrahim hielt ihn 74 Stunden.",emoji:"🔵"},
  {q:"How many km ist der längste Spaziergang der Welt lang?",a:24000,unit:"km",hint:"George Meegan lief von Feuerland nach Alaska.",emoji:"🚶"},
  {q:"How many Stunden nonstop spielte ein Fußballteam?",a:169,unit:"hours",hint:"Über eine Woche Fußball am Stück.",emoji:"⚽"},
  {q:"How many Meter weit hüpfte der Rekordhalter auf einem Bein?",a:100,unit:"meters",hint:"Meter Einbein-Hüpfen als Weltrekord.",emoji:"🦘"},
  {q:"How many Stunden las a human als Dauerlesung vor?",a:200,unit:"hours",hint:"8 Tage Vorlesemarathon.",emoji:"📖"},
  {q:"How many Schaukeln schaukelte jemand in 24 Stunden?",a:230000,unit:"times",hint:"Kontinuierliches Schaukeln einen ganzen Tag.",emoji:"🎢"},
  {q:"How many Meter lang war der längste Zug aus Flugzeugen?",a:19,unit:"Flugzeuge",hint:"Flugzeuge flogen in enger Formation.",emoji:"✈️"},
  {q:"How heavy war das schwerste einzelne Traubenbündel in kg?",a:9.4,unit:"kg",hint:"Eine Weintraube aus Chile 2018.",emoji:"🍇"},
  {q:"How many Stunden lief a human auf einem Laufband als Rekord?",a:24,unit:"hours",hint:"Stunden ununterbrochen auf dem Laufband.",emoji:"🏃"},
  {q:"How many Meter tief ist das tiefste natürliche Loch der Welt?",a:2191,unit:"meters",hint:"Die Krubera-Höhle in Georgien.",emoji:"🕳️"},
  {q:"How many kg Eis schleckte der Rekordhalter in einer Stunde?",a:1.3,unit:"kg",hint:"Über ein Kilo Eis am Stiel in 60 Minuten.",emoji:"🍦"},
  {q:"How many Stunden sang eine Gruppe Kinderlieder nonstop?",a:73,unit:"hours",hint:"3 Tage Kinderlied-Marathon.",emoji:"🎵"},
  {q:"How many Meter lang war der größte Lebkuchenmann?",a:10,unit:"meters",hint:"In Schweden 2009 gebacken.",emoji:"🍪"},
  {q:"How many Sekunden hielt a human eine Jalapeño-Chili im Auge?",a:7,unit:"seconds",hint:"Extrem schmerzhaft – nicht empfohlen.",emoji:"🌶️"},
  {q:"How many Stunden lief ein Hund auf einem Laufband nonstop?",a:5,unit:"hours",hint:"Ausdauer-Hund in Japan.",emoji:"🐕"},
  {q:"How many km weit fuhr die längste Kartenhaus-Bahn?",a:32,unit:"meters",hint:"Ein Kartenhaus-Dominoeffekt über 32 Meter.",emoji:"🃏"},
  {q:"How heavy war das schwerste Pfannkuchen-Stapel in kg?",a:4.5,unit:"kg",hint:"Ein Turm aus Pfannkuchen.",emoji:"🥞"},
  {q:"How many Stunden trug jemand eine Mütze ohne sie abzunehmen?",a:1000,unit:"hours",hint:"Über 40 Tage Mütze tragen.",emoji:"🧢"},
  {q:"How many Meter lang war der längste Baumwollbonbon-Faden?",a:1427,unit:"meters",hint:"Zuckerwatte als langer Faden aufgerollt.",emoji:"🍬"},
  {q:"How many Personen machten gleichzeitig den größten Flashmob?",a:13597,unit:"people",hint:"In Mumbai Indien 2013.",emoji:"🕺"},
  {q:"How many Meter tief watete jemand in Spaghetti?",a:1,unit:"Meter Tiefe",hint:"Eine Wanne voll Spaghetti.",emoji:"🍝"},
  {q:"How many Stunden blieb a human in einem Glas-Sarg unter Wasser?",a:7,unit:"hours",hint:"Unter Wasser eingeschlossen – Atemluft durch ein Rohr.",emoji:"🧊"},
  {q:"How many Sekunden brauchte der schnellste Pizzateig-Dreher für 5 Drehungen?",a:10,unit:"seconds",hint:"Pizza-Akrobatik-Weltmeisterschaft.",emoji:"🍕"},
  {q:"How many Stockwerke hat das höchste Gebäude der Welt (Burj Khalifa)?",a:163,unit:"Stockwerke",hint:"828 Meter – höchstes Gebäude der Welt.",emoji:"🏙️"},
  {q:"How many Mal öffnete der Rekordhalter eine Flasche in einer Minute?",a:67,unit:"times",hint:"Mit einem Korkenzieher – Weltrekord.",emoji:"🍾"},
  {q:"How many Stunden hielt a human eine Kerze über einem Wasserbecken?",a:12,unit:"hours",hint:"Eine brennende Kerze 12 Stunden balancieren.",emoji:"🕯️"},
  {q:"How many km lief das schnellste Dromedar im Sprint?",a:65,unit:"km/h",hint:"Kamele können kurz sehr schnell rennen.",emoji:"🐪"},
  {q:"How many m weit flog der weiteste Papierflieger?",a:88.3,unit:"meters",hint:"John Collins entwarf den Flieger, Joe Ayoob warf ihn.",emoji:"✈️"},
  {q:"How many Stunden lud a human Videos auf YouTube als Dauerlauf hoch?",a:100,unit:"hours",hint:"Stunden ununterbrochenes Video-Uploading.",emoji:"📹"},
  {q:"How many Meter lang war der längste Schal?",a:4565,unit:"meters",hint:"In China gestrickt für den Weltrekord.",emoji:"🧣"},
  {q:"How many Meter lang war der längste Spagat?",a:12,unit:"Meter Kette",hint:"Menschen bildeten eine Spagat-Kette.",emoji:"🤸"},
  {q:"How heavy war das schwerste Würfelzucker-Modell in kg?",a:400,unit:"kg",hint:"Aus 2 million Würfelzucker gebaut.",emoji:"🍬"},
  {q:"How many Minuten hielt ein Team ein Wasserball-Spiel ohne Unterbrechung?",a:24,unit:"hours",hint:"24h Wasserball am Stück.",emoji:"🤽"},
  {q:"How many Stunden boxte a man ununterbrochen gegen einen Sandsack?",a:114,unit:"hours",hint:"Fast 5 Tage nonstop boxen.",emoji:"🥊"},
  {q:"How many Meter lang war der längste selbst gemalte Bildstreifen?",a:2000,unit:"meters",hint:"Ein 2 km langes Bild.",emoji:"🎨"},
  {q:"How many kg Brot backte der Rekordhalter in einer Stunde?",a:100,unit:"Brote",hint:"Laib Brot in 60 Minuten.",emoji:"🍞"},
  {q:"How many Stunden fuhr a human auf einem Einrad als Rekord?",a:105,unit:"hours",hint:"Über 4 Tage auf einem Einrad.",emoji:"🎪"},
  {q:"How many Meter weit schoss der Weltrekord-Pfeilbogen?",a:1410,unit:"meters",hint:"Sultan Selim der Erste schoss 1,41 km weit.",emoji:"🏹"},
  {q:"How many Schritte machte der schnellste 100m-Sprint?",a:41,unit:"Schritte",hint:"Usain Bolt brauchte nur 41 Schritte für 100m.",emoji:"⚡"},
  {q:"How many Stunden sprach a human nonstop als Redner?",a:93,unit:"hours",hint:"Fast 4 Tage ununterbrochenes Reden.",emoji:"🗣️"},
  {q:"How many Kilometer joggten Mitglieder einer Staffel in 24 Stunden?",a:1000,unit:"km",hint:"24-Stunden-Staffellauf-Weltrekord.",emoji:"🏃"},
  {q:"How many Nüsse knackte der Rekordhalter in einer Minute?",a:108,unit:"Nüsse",hint:"Walnüsse in 60 Sekunden geknackt.",emoji:"🥜"},
  {q:"How big war das größte Puzzle der Welt in Teilen?",a:551232,unit:"Teile",hint:"Das größte kommerziell erhältliche Puzzle.",emoji:"🧩"},
  {q:"How many Stunden stand a human in Ameisen als Weltrekord?",a:1,unit:"Stunde",hint:"In einer Kiste voller Ameisen – sehr tapfer.",emoji:"🐜"},
  {q:"How many Meter hoch stapelte der Rekordhalter Münzen?",a:1,unit:"meters",hint:"Meter hoher Münzturm.",emoji:"🪙"},
  {q:"How many Kubikmeter hatte das größte Schneeman der Welt?",a:37000,unit:"Tonnen Schnee",hint:"Ein Schneemann in Maine USA aus 2008.",emoji:"⛄"},
  {q:"How heavy war die schwerste Wassermelone in kg?",a:159,unit:"kg",hint:"Chris Kent aus den USA züchtete sie 2013.",emoji:"🍉"},
  {q:"How many Stunden spielte ein Pärchen Brettspiele nonstop?",a:61,unit:"hours",hint:"Über 2,5 Tage Brettspiele am Stück.",emoji:"🎲"},
  {q:"How many Meter lang war der längste Weihnachtsbaum?",a:67,unit:"meters",hint:"Ein Riesenbaum in Portugal 1999.",emoji:"🎄"},
  {q:"How many Stunden tanzte ein Pärchen Tango ununterbrochen?",a:22,unit:"hours",hint:"Argentinischer Tango-Weltrekord.",emoji:"💃"},
  {q:"How many Meter lang war der längste Schnurrbart?",a:4.29,unit:"meters",hint:"Ram Singh Chauhan aus Indien.",emoji:"👨"},
  {q:"How many Personen sprangen gleichzeitig auf Trampolinen?",a:1000,unit:"people",hint:"Trampolinge-Springer gleichzeitig.",emoji:"🤸"},
  {q:"How heavy war der schwerste Hund je in kg?",a:155,unit:"kg",hint:"Ein Englischer Mastiff namens Zorba.",emoji:"🐕"},
  {q:"How many Stunden trug jemand Eiswürfel am Körper?",a:1,unit:"Stunde",hint:"Wim Hof hält Kälterekorde – bis zu 1h45min.",emoji:"🧊"},
  {q:"How many Meter lang war der längste Fluss-Schwimmer nonstop?",a:514,unit:"km",hint:"Martin Strel schwamm den gesamten Mississippi.",emoji:"🏊"},
  {q:"How many Stunden sang a human allein ununterbrochen?",a:105,unit:"hours",hint:"Fast 4,5 Tage Dauersingen.",emoji:"🎤"},
  {q:"How many Meter lang war der längste Brezel?",a:26,unit:"meters",hint:"Eine Riesenbrezel aus Bayern.",emoji:"🥨"},
  {q:"How many km lief der schnellste 100-km-Läufer?",a:100,unit:"km in 6h17min",hint:"Nao Kazami (Japan) 2018.",emoji:"🏃"},
  {q:"How many Stunden sprach ein Politiker die längste Parlamentsrede?",a:25,unit:"hours",hint:"Ein australischer Senator sprach 25 Stunden am Stück.",emoji:"🎙️"},
  {q:"How many Stunden sang der Weltrekord-Sänger ununterbrochen?",a:105,unit:"hours",hint:"4,5 Tage – in Indien aufgestellt.",emoji:"🎤"},
  {q:"How many Meter sprang a human aus einem Flugzeug ohne Fallschirm?",a:7600,unit:"meters",hint:"Luke Aikins landete 2016 in einem Netz.",emoji:"🪂"},
  {q:"How many km/h schnell war der schnellste Mensch auf Skiern?",a:254,unit:"km/h",hint:"Ivan Origone aus Italien, 2016.",emoji:"⛷️"},
  {q:"How many Stunden fuhr der längste Fahrradfahrer nonstop?",a:91,unit:"hours",hint:"Über 3 Tage nonstop Radfahren.",emoji:"🚴"},
  {q:"How many Meter hoch kletterte der jüngste Everest-Bezwinger in Jahren?",a:13,unit:"years",hint:"Jordan Romero bestieg ihn 2010 mit 13 Jahren.",emoji:"🏔️"},
  {q:"How many Stunden tanzte ein einzelner Mensch als Rekord?",a:126,unit:"hours",hint:"Über 5 Tage tanzen ohne Unterbrechung.",emoji:"💃"},
  {q:"How many Meter hoch ist der weltgrößte Sandberg?",a:100,unit:"meters",hint:"Aus Sand aufgetürmt für den Weltrekord.",emoji:"🏖️"},
  {q:"How many kg Würstchen rollte der Rekordhalter in einer Minute?",a:50,unit:"Würstchen",hint:"Würste in 60 Sekunden gerollt.",emoji:"🌭"},
  {q:"How many Stunden nonstop las ein Vorleser als Rekord?",a:200,unit:"hours",hint:"8 Tage ununterbrochen vorlesen.",emoji:"📖"},
  {q:"How many Meter lang war die längste Menschenpyramide?",a:12,unit:"Ebenen",hint:"Etagen Menschenpyramide.",emoji:"🤸"},
  {q:"How many Liter Bier trank der Rekordhalter in einer Minute?",a:1.3,unit:"liters",hint:"1,3 Liter in 60 Sekunden.",emoji:"🍺"},
  {q:"How many Stunden spielte ein Pianist als Rekord nonstop?",a:120,unit:"hours",hint:"5 Tage Klavier ohne Unterbrechung.",emoji:"🎹"},
  {q:"How many km/h fuhr der schnellste Rollschuhfahrer?",a:130,unit:"km/h",hint:"Bergab auf Inlineskates.",emoji:"🛼"},
  {q:"How many Stunden hielt jemand einen Handstand?",a:56,unit:"minutes",hint:"Fast eine Stunde kopfüber.",emoji:"🤸"},
  {q:"How many Meter weit warf der Rekordhalter einen Bumerang?",a:1401,unit:"meters",hint:"Und er kam zurück.",emoji:"🪃"},
  {q:"How many Stunden jonglierte jemand nonstop?",a:12,unit:"hours",hint:"Mit 3 Bällen ohne Unterbrechung.",emoji:"🎪"},
  {q:"How many Meter lang war der längste Schal?",a:4565,unit:"meters",hint:"Fast 5 km Schal gestrickt.",emoji:"🧣"},
  {q:"How many Stunden blieb jemand wach als Weltrekord?",a:449,unit:"hours",hint:"Randy Gardner – offizieller Weltrekord 264h.",emoji:"😴"},
  {q:"How many Liegestütze schaffte jemand mit einem Arm in einer Minute?",a:64,unit:"Liegestütze",hint:"Mit einem Arm – ein-Arm-Liegestütz-Rekord.",emoji:"💪"},
  {q:"How many km weit segelte a human allein nonstop?",a:33000,unit:"km",hint:"Die Weltumsegelung solo und nonstop.",emoji:"⛵"},
  {q:"How many Stufen stieg der schnellste Treppenläufer pro Minute?",a:1600,unit:"Stufen",hint:"Beim Wolkenkratzer-Rennen.",emoji:"🏃"},
  {q:"How many Gramm Chili aß der Rekordhalter in 3 Minuten?",a:500,unit:"grams",hint:"500g der schärfsten Chili in 3 Minuten.",emoji:"🌶️"},
  {q:"How many Meter lang war das größte Sandschloss?",a:500,unit:"meters",hint:"Ein 500 Meter langer Sandwall.",emoji:"🏰"},
  {q:"How many Stunden kochte der Weltrekord-Koch nonstop?",a:68,unit:"hours",hint:"Fast 3 Tage kochen.",emoji:"👨‍🍳"},
  {q:"How many Meter hoch war das höchste jemals gebaute Kartenhaus?",a:7.9,unit:"meters",hint:"Bryan Berg baute es in Las Vegas.",emoji:"🃏"},
  {q:"How many Personen passten in den kleinsten Serienwagen?",a:21,unit:"people",hint:"In einen Mini Cooper gequetscht.",emoji:"🚗"},
  {q:"How many Stunden dauerte die längste Party?",a:168,unit:"hours",hint:"7 Tage feiern – dokumentiert.",emoji:"🎉"},
  {q:"How many Meter weit wurde ein Frisbee geworfen?",a:338,unit:"meters",hint:"Weltrekord im Frisbee-Weitwurf.",emoji:"🥏"},
  {q:"How many km/h erreichte der schnellste Papierflugzeug-Wurf?",a:238,unit:"km/h",hint:"Mit einer Schleuder abgeschossen.",emoji:"✈️"},
  {q:"How many Sekunden brauchte der schnellste Mensch für einen Liter Wasser?",a:5,unit:"seconds",hint:"Trinken ohne zu schlucken aufzuhören.",emoji:"💧"},
  {q:"How many Stunden aß jemand nonstop als Rekord?",a:72,unit:"hours",hint:"3 Tage essen – mit kurzen Pausen.",emoji:"🍽️"},
  {q:"How many Meter lang war das größte Puzzle?",a:6000,unit:"meters",hint:"6 km langes Riesenpuzzle.",emoji:"🧩"},
  {q:"How many Personen stellten den Weltrekord im Haareschneiden gleichzeitig?",a:394,unit:"people",hint:"Friseure schnitten gleichzeitig.",emoji:"💇"},
  {q:"How many Stunden fuhr das längste Kettenkarussell?",a:24,unit:"hours",hint:"24h Karussell fahren.",emoji:"🎡"},
];
