// 🍆 SEX & TABOOS – Adults – 245 questions
export default [
  {id:"sex_001",q:"How many million pornographic videos are there estimated to be on the internet?",a:4,unit:"million videos",hint:"Over 4 million videos – and new ones are added daily.",emoji:"🔞"},
  {id:"sex_002",q:"How many million visitors does Pornhub get per day?",a:130,unit:"million",hint:"One of the most-visited websites in the world.",emoji:"💻"},
  {id:"sex_003",q:"How many grams does an average dildo weigh?",a:200,unit:"grams",hint:"Varies a lot depending on material and size.",emoji:"🍆"},
  {id:"sex_004",q:"In what year was the first latex condom produced?",a:1920,unit:"year",hint:"Before that, condoms were made from sheep intestine.",emoji:"💊"},
  {id:"sex_005",q:"How many calories does oral sex burn per hour?",a:100,unit:"kcal",hint:"More than you'd think – muscles are at work.",emoji:"🔥"},
  {id:"sex_006",q:"How many cm is the average erect penis worldwide?",a:13.1,unit:"cm",hint:"A 2015 meta-analysis of 15,000+ men worldwide.",emoji:"📏"},
  {id:"sex_007",q:"How many million people worldwide are infected with HIV?",a:39,unit:"million",hint:"As of 2022 – antiretroviral therapy helps.",emoji:"🎗️"},
  {id:"sex_008",q:"How long does the average act of intercourse last, according to studies, in minutes?",a:5.4,unit:"minutes",hint:"Measured from penetration to ejaculation.",emoji:"⏱️"},
  {id:"sex_009",q:"How many million sperm does an average ejaculation contain?",a:250,unit:"million",hint:"Only one of them fertilizes the egg.",emoji:"🔬"},
  {id:"sex_010",q:"In what year was Viagra approved?",a:1998,unit:"year",hint:"FDA approval on March 27, 1998.",emoji:"💊"},
  {id:"sex_011",q:"How many nerve endings does the clitoris have?",a:8000,unit:"nerve endings",hint:"Twice as many as the penis.",emoji:"⚡"},
  {id:"sex_012",q:"How many cm is the average vaginal depth at rest?",a:9,unit:"cm",hint:"When aroused, it stretches to 12-15 cm.",emoji:"📏"},
  {id:"sex_013",q:"How many billion dollars is the global sex toy industry worth?",a:33,unit:"billion dollars",hint:"$33 billion annually – growing fast.",emoji:"💰"},
  {id:"sex_014",q:"How many times per year does an average German have sex?",a:98,unit:"times",hint:"Almost twice a week, according to surveys.",emoji:"❤️"},
  {id:"sex_015",q:"How many hours in a lifetime does a person spend having sex?",a:520,unit:"hours",hint:"About 21 days – over a lifetime.",emoji:"⏰"},
  {id:"sex_016",q:"How many cm is the average flaccid penis length?",a:9,unit:"cm",hint:"On average 7-10 cm flaccid.",emoji:"📏"},
  {id:"sex_017",q:"In what year was the first vibrator invented?",a:1880,unit:"year",hint:"Originally a medical device for 'hysteria'.",emoji:"⚡"},
  {id:"sex_018",q:"How many seconds does the average female orgasm contraction last?",a:22,unit:"seconds",hint:"Female orgasms last longer than male ones.",emoji:"🌊"},
  {id:"sex_019",q:"How many million times is the term 'sex' googled daily?",a:8,unit:"million",hint:"One of the most-searched terms worldwide.",emoji:"🔍"},
  {id:"sex_020",q:"How many cm in diameter is an average nipple?",a:1.5,unit:"cm",hint:"Varies a lot – from 0.5cm to over 2.5cm.",emoji:"📏"},
  {id:"sex_021",q:"In what year was the birth control pill invented?",a:1960,unit:"year",hint:"FDA approval in 1960 – revolutionized women's rights.",emoji:"💊"},
  {id:"sex_022",q:"How many million condoms are used worldwide every day?",a:6,unit:"million",hint:"6 million daily = ~2 billion per year.",emoji:"💊"},
  {id:"sex_023",q:"How many degrees Celsius does body temperature rise during orgasm?",a:0.3,unit:"°C",hint:"A slight but measurable warming.",emoji:"🌡️"},
  {id:"sex_024",q:"How many million people worldwide have syphilis?",a:7,unit:"million",hint:"Still widespread – despite antibiotics.",emoji:"🔬"},
  {id:"sex_025",q:"How many minutes does sex last on average, from start to finish?",a:30,unit:"minutes",hint:"Including foreplay about 30 min., penetration alone 5-6 min.",emoji:"⏰"},
  {id:"sex_026",q:"How many milligrams of protein does semen contain per ejaculation?",a:300,unit:"milligrams",hint:"Less than a cup of milk.",emoji:"⚗️"},
  {id:"sex_027",q:"In what year was the first male sex toy (the Fleshlight) invented?",a:1995,unit:"year",hint:"Patented by Steve Shubin.",emoji:"📅"},
  {id:"sex_028",q:"How many cm is the average distance between the clitoris and the vaginal opening?",a:2.5,unit:"cm",hint:"Influences ease of orgasm.",emoji:"📏"},
  {id:"sex_029",q:"How many million dollars does the highest-paid porn actor earn per year?",a:1,unit:"million dollars/year",hint:"Women in the industry often earn more.",emoji:"💰"},
  {id:"sex_030",q:"How many minutes faster do you fall asleep after an orgasm?",a:10,unit:"minutes",hint:"Oxytocin and prolactin after orgasm promote sleep.",emoji:"😴"},
  {id:"sex_031",q:"How many million people worldwide work in sex work?",a:40,unit:"million",hint:"An estimate – hard to measure due to illegality.",emoji:"🌍"},
  {id:"sex_032",q:"How many cm long is the G-spot zone from the vaginal opening?",a:5,unit:"cm",hint:"On the front vaginal wall.",emoji:"📏"},
  {id:"sex_033",q:"In what year was sex work legalized in Germany?",a:2002,unit:"year",hint:"The Prostitution Act took effect on January 1, 2002.",emoji:"📜"},
  {id:"sex_034",q:"How many million visitors does OnlyFans have?",a:220,unit:"million",hint:"Registered users – with 2.5 million creators.",emoji:"📱"},
  {id:"sex_035",q:"How many grams does an average testicle weigh?",a:20,unit:"grams",hint:"Both testicles together weigh 40 grams.",emoji:"⚖️"},
  {id:"sex_036",q:"In what year was the first erotic film made?",a:1896,unit:"year",hint:"Le Coucher de la Mariée – 7 minutes long.",emoji:"🎬"},
  {id:"sex_037",q:"How many times per night does a healthy man have an erection while sleeping?",a:4,unit:"times",hint:"NPT – nocturnal penile tumescence.",emoji:"😴"},
  {id:"sex_038",q:"How many cm is the average bra band size in Germany?",a:75,unit:"cm band size",hint:"B/C cup is the most common in Germany.",emoji:"👙"},
  {id:"sex_039",q:"How many million dollars did Fifty Shades of Grey (the movie) gross worldwide?",a:569,unit:"million dollars",hint:"Budget was only $40 million – a huge success.",emoji:"📚"},
  {id:"sex_040",q:"How long does ejaculation last on average, in seconds?",a:8,unit:"seconds",hint:"The muscle contractions last 3-15 seconds.",emoji:"⏱️"},
  {id:"sex_041",q:"How many million Germans say they regularly watch porn?",a:25,unit:"million",hint:"About one in three Germans.",emoji:"📺"},
  {id:"sex_042",q:"How many cm is the average bust circumference of a woman in Germany?",a:97,unit:"cm",hint:"Bust circumference varies a lot.",emoji:"📏"},
  {id:"sex_043",q:"In what year did Fifty Shades of Grey come out (the book)?",a:2011,unit:"year",hint:"E.L. James' BDSM novel became a worldwide bestseller.",emoji:"📖"},
  {id:"sex_044",q:"How many million copies did Fifty Shades of Grey sell?",a:150,unit:"million",hint:"One of the best-selling books of all time.",emoji:"📚"},
  {id:"sex_045",q:"How many cm long is the average female nipple?",a:1,unit:"cm",hint:"About 1 cm at rest.",emoji:"📏"},
  {id:"sex_046",q:"How many million people in Germany have tried anal sex?",a:20,unit:"million",hint:"About 35-40% of the population.",emoji:"📊"},
  {id:"sex_047",q:"How many degrees Celsius warmer does the clitoris get during orgasm?",a:2,unit:"°C",hint:"Measurable with infrared thermography.",emoji:"🌡️"},
  {id:"sex_048",q:"How many hours per month does an average German watch porn?",a:4,unit:"hours",hint:"According to anonymous usage data.",emoji:"📺"},
  {id:"sex_049",q:"In what year was sex on the ISS first theoretically discussed?",a:2006,unit:"year",hint:"A NASA study on sex in space.",emoji:"🚀"},
  {id:"sex_050",q:"How many million people have a sex addiction?",a:16,unit:"million",hint:"3-6% of the population – mostly men.",emoji:"🔬"},
  {id:"sex_051",q:"How many cm long is the average erect clitoris?",a:10,unit:"cm",hint:"The internal structure – not just the visible glans.",emoji:"📏"},
  {id:"sex_052",q:"In what year was the first brothel in history documented?",a:600,unit:"BCE",hint:"In ancient Greece, under Solon.",emoji:"🏛️"},
  {id:"sex_053",q:"How many million dollars did it cost to produce Fifty Shades of Grey (the movie)?",a:40,unit:"million dollars",hint:"And it grossed $569 million.",emoji:"🎬"},
  {id:"sex_054",q:"How many grams does a prostate weigh?",a:25,unit:"grams",hint:"It can grow to 100g with age.",emoji:"⚖️"},
  {id:"sex_055",q:"In what year was the first legally produced porn film sold?",a:1972,unit:"year",hint:"Deep Throat – the first mainstream porn film.",emoji:"🎬"},
  {id:"sex_056",q:"How many cm is an average menstrual cup?",a:7,unit:"cm",hint:"An eco-friendly alternative to tampons.",emoji:"📏"},
  {id:"sex_057",q:"How many million people watch porn daily on mobile devices?",a:90,unit:"million",hint:"Over 70% of traffic comes from smartphones.",emoji:"📱"},
  {id:"sex_058",q:"How many hours of porn are uploaded to Pornhub daily?",a:115,unit:"hours",hint:"New content every day.",emoji:"📹"},
  {id:"sex_059",q:"In what year was the first plastic (polyurethane) condom introduced?",a:1994,unit:"year",hint:"An alternative for people with latex allergies.",emoji:"💊"},
  {id:"sex_060",q:"How many ml of vaginal fluid does a woman produce during sex?",a:4,unit:"ml",hint:"A natural lubrication response.",emoji:"💧"},
  {id:"sex_061",q:"How many million dollars did porn actress Lisa Ann earn per year at her peak?",a:1.5,unit:"million dollars",hint:"One of the industry's best-known stars.",emoji:"💰"},
  {id:"sex_062",q:"How many cm deep is the vagina on average during sexual arousal?",a:11,unit:"cm",hint:"7-8cm at rest, 11-12cm when aroused (Masters & Johnson, 1966).",emoji:"📏"},
  {id:"sex_063",q:"In what year was the first penis enlargement surgery documented?",a:1971,unit:"year",hint:"Surgical procedures since the 1970s.",emoji:"🏥"},
  {id:"sex_064",q:"How many million dollars is the global market for erotic video games worth?",a:100,unit:"million dollars",hint:"A niche but growing market.",emoji:"🎮"},
  {id:"sex_065",q:"How many milligrams of fructose does semen contain?",a:2.5,unit:"mg",hint:"Fructose gives sperm energy.",emoji:"⚗️"},
  {id:"sex_066",q:"In what year did the first sex clinic open in Germany?",a:1918,unit:"year",hint:"Magnus Hirschfeld opened the Institute for Sexual Science.",emoji:"🏥"},
  {id:"sex_067",q:"How many cm is the maximum vaginal depth during strong arousal?",a:15,unit:"cm",hint:"During the 'tenting' effect: the uterus lifts, the vagina lengthens to up to 15cm.",emoji:"📏"},
  {id:"sex_068",q:"How many million Pornhub searches come from Germany daily?",a:10,unit:"million",hint:"Germany is among the top consumers.",emoji:"🔍"},
  {id:"sex_069",q:"How many seconds did the longest known orgasm last?",a:43,unit:"seconds",hint:"Measured in a lab (as of ~2024).",emoji:"⏱️"},
  {id:"sex_070",q:"In what year was the first sex doll company founded?",a:1997,unit:"year",hint:"RealDoll from San Diego was the pioneer.",emoji:"🤖"},
  {id:"sex_071",q:"How many cm long is an average vibrator?",a:18,unit:"cm",hint:"The classic size.",emoji:"📏"},
  {id:"sex_072",q:"How many million dollars in revenue does the global BDSM industry generate?",a:500,unit:"million dollars",hint:"Bondage, Domination, Sadism, Masochism.",emoji:"🔗"},
  {id:"sex_073",q:"How many milligrams of zinc does an ejaculation contain?",a:5,unit:"mg",hint:"Milligrams – essential for sperm quality.",emoji:"⚗️"},
  {id:"sex_074",q:"In what year did Hugh Hefner found Playboy magazine?",a:1953,unit:"year",hint:"Marilyn Monroe was on the first cover.",emoji:"🐰"},
  {id:"sex_075",q:"How many million Pornhub searches come in daily?",a:100,unit:"million",hint:"Millions daily – a gigantic number.",emoji:"🔍"},
  {id:"sex_076",q:"How many cm long is an average anal plug?",a:10,unit:"cm",hint:"Many variations – from small to large.",emoji:"📏"},
  {q:"How many hours in a lifetime does a person spend masturbating (men)?",a:7000,hint:"Almost 300 days over a lifetime.",unit:"hours",emoji:"📊"},
  {id:"sex_077",q:"In what year was the term 'bisexuality' first used scientifically?",a:1892,unit:"year",hint:"By Charles Gilbert Chaddock.",emoji:"🔬"},
  {id:"sex_078",q:"How many million dollars is the global lubricant market worth?",a:800,unit:"million dollars",hint:"Lubricant is a massive market.",emoji:"💰"},
  {id:"sex_079",q:"How many cm long is the average human tongue?",a:9,unit:"cm",hint:"About 9cm – roughly half of it is used while kissing.",emoji:"💋"},
  {id:"sex_080",q:"In what year was the first nude photoshoot published in a magazine?",a:1896,unit:"year",hint:"In early art magazines.",emoji:"📸"},
  {id:"sex_081",q:"How many grams does the uterus weigh?",a:70,unit:"grams",hint:"When not pregnant.",emoji:"⚖️"},
  {id:"sex_082",q:"How many million people worldwide have gonorrhea?",a:82,unit:"million",hint:"One of the most common STIs.",emoji:"🔬"},
  {id:"sex_083",q:"How many cm long is the average penile foreskin?",a:5,unit:"cm",hint:"Varies a lot.",emoji:"📏"},
  {id:"sex_084",q:"In what year did the first gay club in Germany open?",a:1897,unit:"year",hint:"Hirschfeld's Scientific-Humanitarian Committee.",emoji:"🌈"},
  {id:"sex_085",q:"How many million people watch porn at work daily?",a:30,unit:"million",hint:"Surprisingly many users worldwide.",emoji:"💼"},
  {id:"sex_086",q:"How many grams do both breasts of a C-cup woman weigh combined?",a:500,unit:"grams",hint:"About 500g – depending on size.",emoji:"⚖️"},
  {id:"sex_087",q:"How many hours does an average wedding night last?",a:3,unit:"hours",hint:"More sleeping than you'd think.",emoji:"🌙"},
  {id:"sex_088",q:"In what year did the first swingers club in Germany open?",a:1971,unit:"year",hint:"In the liberal '70s.",emoji:"🕺"},
  {id:"sex_089",q:"How many cm in diameter are average Kegel balls?",a:4,unit:"cm",hint:"About 3.5-4.5 cm in diameter – suitable for beginners doing pelvic floor training.",emoji:"⭕"},
  {id:"sex_090",q:"In what year did the first strip club in the US open?",a:1969,unit:"year",hint:"In San Francisco, during the Sexual Revolution.",emoji:"💃"},
  {id:"sex_091",q:"How many grams does a strap-on dildo weigh on average?",a:300,unit:"grams",hint:"Between 200-500g depending on material.",emoji:"⚖️"},
  {id:"sex_092",q:"How many cm is the average erect penis girth?",a:12,unit:"cm circumference",hint:"Girth varies more than length.",emoji:"📏"},
  {id:"sex_093",q:"How many billion euros does sex work generate in Germany per year?",a:15,unit:"billion euros",hint:"€15 billion annually in Germany.",emoji:"💶"},
  {id:"sex_094",q:"In what year was the first female condom approved?",a:1993,unit:"year",hint:"FDA approval in 1993.",emoji:"💊"},
  {id:"sex_095",q:"How many cm long is the average clitoral hood?",a:0.5,unit:"cm",hint:"The clitoral prepuce.",emoji:"📏"},
  {id:"sex_096",q:"How many million escorts work worldwide?",a:1,unit:"million",hint:"Estimates – exact numbers aren't measurable.",emoji:"💼"},
  {id:"sex_097",q:"How many hours did the longest documented act of intercourse last (record)?",a:134,unit:"hours",hint:"134 hours – a Guinness record set by an American couple in 2004.",emoji:"⏰"},
  {id:"sex_098",q:"In what year was the phenomenon of 'female ejaculation' scientifically recognized?",a:1982,unit:"year",hint:"First scientifically described in 1982.",emoji:"🔬"},
  {id:"sex_099",q:"How many cm is the threshold for a micropenis diagnosis?",a:7,unit:"cm",hint:"Under 7cm erect is medically classified as a micropenis (about 0.6% of men).",emoji:"📏"},
  {id:"sex_100",q:"How many million people worldwide have chlamydia?",a:127,unit:"million",hint:"The most common bacterial STI.",emoji:"🔬"},
  {id:"sex_101",q:"In what year did Alfred Kinsey found his sex research institute?",a:1947,unit:"year",hint:"The Kinsey Institute in Indiana.",emoji:"🔬"},
  {id:"sex_102",q:"How many cm long is the longest penis in the world said to be, by self-report?",a:34,unit:"cm",hint:"Jonah Falcon claims 34cm – not officially medically verified.",emoji:"📏"},
  {id:"sex_103",q:"How many billion dollars is the global market for erectile dysfunction medication worth?",a:6,unit:"billion dollars",hint:"Viagra, Cialis, and generics.",emoji:"💊"},
  {id:"sex_104",q:"How many minutes does foreplay last on average, according to studies?",a:18,unit:"minutes",hint:"Too little, according to most women.",emoji:"⏱️"},
  {id:"sex_105",q:"In what year did the first sex museum in Amsterdam open?",a:1985,unit:"year",hint:"The Amsterdam Sex Museum.",emoji:"🏛️"},
  {id:"sex_106",q:"How many cm long is the average relaxed anal opening?",a:3,unit:"cm",hint:"Can become larger through training and relaxation.",emoji:"📏"},
  {id:"sex_107",q:"How many million people worldwide identify as a trans woman or trans man?",a:25,unit:"million",hint:"Estimates vary – about 0.3% of the world's population.",emoji:"🏳️‍⚧️"},
  {id:"sex_108",q:"How many milligrams does a typical birth control pill weigh?",a:150,unit:"milligrams",hint:"The tablet itself weighs about 100-200mg – the active ingredient is only 0.03mg.",emoji:"⚖️"},
  {id:"sex_109",q:"In what year did the first nudist site in Germany open?",a:1920,unit:"year",hint:"The nudist movement began in the 1920s.",emoji:"🌞"},
  {id:"sex_110",q:"How many ml does an anal plug hold on average?",a:100,unit:"ml",hint:"Varies depending on size.",emoji:"💧"},
  {id:"sex_111",q:"How many million euros does Germany's sex toy market generate?",a:400,unit:"million euros",hint:"Growing 10% annually.",emoji:"💶"},
  {id:"sex_112",q:"In what year was the Kegel pelvic floor exercise invented?",a:1948,unit:"year",hint:"Dr. Arnold Kegel developed the exercises.",emoji:"💪"},
  {id:"sex_113",q:"How many cm long is an average butt plug?",a:10,unit:"cm",hint:"Depends on size and experience.",emoji:"📏"},
  {id:"sex_114",q:"How many million condoms are sold in Germany per year?",a:200,unit:"million",hint:"Declining due to the pill and IUDs.",emoji:"💊"},
  {id:"sex_115",q:"In what year did the Kama Sutra first appear in Europe?",a:1883,unit:"year",hint:"Richard Burton translated it into English.",emoji:"📖"},
  {id:"sex_116",q:"How many positions does the Kama Sutra describe?",a:64,unit:"positions",hint:"Many of them aren't very practical for everyday use.",emoji:"📖"},
  {id:"sex_117",q:"How many cm is the maximum known vaginal depth?",a:15,unit:"cm",hint:"Well documented up to 15cm during strong arousal – extreme values are rarely documented.",emoji:"📏"},
  {id:"sex_118",q:"How many billion dollars is the global aphrodisiac market worth?",a:2,unit:"billion dollars",hint:"Rhino products, oyster extracts, and more.",emoji:"💊"},
  {id:"sex_119",q:"How many hours does the body need to recover after sex?",a:2,unit:"hours",hint:"Until heart rate and hormones return to normal.",emoji:"💓"},
  {id:"sex_120",q:"In what year did the first sex therapy practice in Germany open?",a:1975,unit:"year",hint:"After Masters & Johnson's research.",emoji:"🏥"},
  {id:"sex_121",q:"How many mm tall is an average nipple at rest?",a:5,unit:"mm",hint:"About 5mm tall, 15mm in diameter – varies a lot.",emoji:"📏"},
  {id:"sex_122",q:"How many thousand dollars did porn actress Mia Khalifa earn in total?",a:12,unit:"thousand dollars",hint:"Only $12,000 over her brief career – despite enormous fame.",emoji:"💰"},
  {id:"sex_123",q:"How many grams of glucose are burned during sex?",a:8,unit:"grams",hint:"Equivalent to a small piece of chocolate.",emoji:"🍫"},
  {id:"sex_124",q:"In what year was the first adult magazine (Playboy) founded?",a:1953,unit:"year",hint:"Hugh Hefner started a revolution.",emoji:"🐰"},
  {id:"sex_125",q:"How many million people worldwide identify as homosexual?",a:390,unit:"million",hint:"About 5% of the world's population.",emoji:"🌈"},
  {id:"sex_126",q:"How many minutes of foreplay do women need on average for an orgasm?",a:20,unit:"minutes",hint:"Studies show about 20 minutes of stimulation – more than most men assume.",emoji:"⏱️"},
  {id:"sex_127",q:"In what year was anal sex legalized in Germany?",a:1969,unit:"year",hint:"Paragraph 175 was reformed.",emoji:"📜"},
  {id:"sex_128",q:"How many grams does a typical set of Kegel balls weigh?",a:80,unit:"grams",hint:"Between 30g (beginner) and 165g (advanced) – the heavier, the more intense the workout.",emoji:"⭕"},
  {id:"sex_129",q:"How many million euros is the German erotic film market worth?",a:200,unit:"million euros",hint:"Productions made in Germany.",emoji:"🎬"},
  {id:"sex_130",q:"In what year did the first female-authored erotic novel (Lady Chatterley's Lover) come out?",a:1928,unit:"year",hint:"D.H. Lawrence wrote it – banned for decades.",emoji:"📚"},
  {id:"sex_131",q:"How many cm is the base of an average vibrator?",a:4,unit:"cm",hint:"Wider at the bottom for a secure grip.",emoji:"📏"},
  {id:"sex_132",q:"How many million people in Germany have sexual dysfunctions?",a:10,unit:"million",hint:"A broad spectrum – many don't seek help.",emoji:"🔬"},
  {id:"sex_133",q:"How many cm is the distance between the anus and the vaginal opening (perineum)?",a:3,unit:"cm",hint:"The perineum varies from person to person.",emoji:"📏"},
  {id:"sex_134",q:"How many million dollars did Hustler Magazine earn per year at its peak?",a:50,unit:"million dollars/year",hint:"Larry Flynt's adult magazine in the '80s.",emoji:"💰"},
  {id:"sex_135",q:"How many more hours per month do singles watch porn compared to couples?",a:4,unit:"hours",hint:"Singles consume significantly more.",emoji:"📊"},
  {id:"sex_136",q:"How many cm is the average bra band size in Austria?",a:80,unit:"cm band size",hint:"Similar to Germany.",emoji:"👙"},
  {id:"sex_137",q:"How many million users does Grindr have worldwide?",a:13,unit:"million",hint:"The best-known gay dating app.",emoji:"📱"},
  {id:"sex_138",q:"How many cm long is the average clitoral shaft?",a:3,unit:"cm",hint:"The internal part of the clitoral body.",emoji:"📏"},
  {id:"sex_139",q:"How many million people worldwide use swingers club apps?",a:2,unit:"million",hint:"Specialized apps for the lifestyle community.",emoji:"📱"},
  {id:"sex_140",q:"How many grams does an average ovary weigh?",a:14,unit:"grams",hint:"Both together weigh about 28 grams.",emoji:"⚖️"},
  {id:"sex_141",q:"How many ml of fluid is expelled on average during squirting?",a:50,unit:"ml",hint:"Range: 0.3ml to over 150ml – mainly urine from the bladder (Salama et al., 2015).",emoji:"💧"},
  {id:"sex_142",q:"How many hours per month do singles spend on dating apps?",a:10,unit:"hours",hint:"A lot of time spent on digital dating.",emoji:"📱"},
  {id:"sex_143",q:"How many cm away from the vaginal opening is the average hymen?",a:2,unit:"cm",hint:"The hymen is a thin layer of mucous membrane tissue.",emoji:"📏"},
  {id:"sex_144",q:"How many thousand people have a semen allergy (seminal plasma)?",a:40,unit:"thousand",hint:"About 40,000 people – a rare allergy to proteins in semen.",emoji:"🔬"},
  {id:"sex_145",q:"How many degrees Celsius warmer is the vaginal canal during orgasm?",a:0.5,unit:"°C",hint:"Measurable with precise thermometers.",emoji:"🌡️"},
  {id:"sex_146",q:"How many million people have vaginismus (involuntary vaginal muscle spasms)?",a:15,unit:"million",hint:"A common but rarely discussed condition.",emoji:"🔬"},
  {id:"sex_147",q:"How many grams does the clitoral erectile tissue network weigh?",a:20,unit:"grams",hint:"The entire clitoral system.",emoji:"⚖️"},
  {id:"sex_148",q:"How many minutes does a man need on average after orgasm before another erection?",a:30,unit:"minutes",hint:"About 30 min. for young men – in older men, it can take hours or even days.",emoji:"⏰"},
  {id:"sex_149",q:"How many million people worldwide practice bondage?",a:100,unit:"million",hint:"Studies show 15-20% of people have had BDSM experiences.",emoji:"🔗"},
  {id:"sex_150",q:"How many cm is the length of an erect clitoral body?",a:10,unit:"cm",hint:"Much larger than what's visible.",emoji:"📏"},
  {id:"sex_151",q:"How many picograms of oxytocin per ml are released during orgasm?",a:100,unit:"pg/ml",hint:"About 100 picograms/ml – a tiny amount with a big effect.",emoji:"⚗️"},
  {id:"sex_152",q:"How many hours of sleep per night are recommended for healthy sexual function?",a:8,unit:"hours",hint:"Under 5h of sleep reduces testosterone – 8h is the benchmark.",emoji:"😴"},
  {id:"sex_153",q:"How many million people use FetLife worldwide?",a:10,unit:"million",hint:"The largest BDSM social network.",emoji:"🔗"},
  {id:"sex_154",q:"How many grams of elastin does vaginal tissue contain?",a:1,unit:"grams",hint:"Elastin allows for stretching during childbirth.",emoji:"⚗️"},
  {id:"sex_155",q:"How many ml of lubrication does the Bartholin's gland produce during sex?",a:2,unit:"ml",hint:"Natural lubrication.",emoji:"💧"},
  {id:"sex_156",q:"Out of 250 million sperm, how many reach the egg at most?",a:200,unit:"sperm",hint:"Out of 250 million, only about 200 make it to the egg – one fertilizes it.",emoji:"🔬"},
  {id:"sex_157",q:"How many hours per year does a person spend on romantic activities?",a:730,unit:"hours",hint:"2 hours daily on romance and intimacy.",emoji:"❤️"},
  {id:"sex_158",q:"How many cm long is the foreskin when erect?",a:12,unit:"cm",hint:"The foreskin can cover up to half the penis.",emoji:"📏"},
  {id:"sex_159",q:"How many million people worldwide have erectile dysfunction?",a:320,unit:"million",hint:"Almost a third of all men, at some point.",emoji:"🔬"},
  {id:"sex_160",q:"How many micrometers long is an average sperm cell?",a:50,unit:"micrometers",hint:"0.05mm – about 1/20th the width of a human hair.",emoji:"🔬"},
  {id:"sex_161",q:"How many extra hours of sleep do you get after an orgasm, according to studies?",a:1,unit:"hour more",hint:"Orgasm promotes sleep through oxytocin.",emoji:"😴"},
  {id:"sex_162",q:"How many ml of vaginal fluid does a woman produce daily?",a:2,unit:"ml",hint:"Normal is 1-4 ml daily.",emoji:"💧"},
  {id:"sex_163",q:"How many cm is the maximum recorded circumference of an erect penis?",a:25,unit:"cm",hint:"Extreme cases are documented (as of ~2024).",emoji:"📏"},
  {id:"sex_164",q:"How many million people worldwide suffer from sexual anxiety disorders?",a:30,unit:"million",hint:"Sexual anxiety – not uncommon.",emoji:"🔬"},
  {id:"sex_165",q:"How many minutes per week do women masturbate on average, according to studies?",a:30,unit:"minutes/week",hint:"Studies show about 30 min./week for women – men about twice as much.",emoji:"📊"},
  {id:"sex_166",q:"How many micrograms of estradiol does a normal birth control pill contain daily?",a:30,unit:"micrograms",hint:"30µg – a very low dose; earlier pills had 50-150µg.",emoji:"💊"},
  {id:"sex_167",q:"How many million people are part of the polyamory movement?",a:21,unit:"million",hint:"An estimate for the US alone.",emoji:"💕"},
  {id:"sex_168",q:"How many times per week does an average couple have sex?",a:2,unit:"times",hint:"About 2 times a week – decreasing with age.",emoji:"❤️"},
  {id:"sex_169",q:"How many calories does sex burn (30 minutes)?",a:144,unit:"kcal",hint:"About 144 kcal – like a 25-minute walk.",emoji:"🔥"},
  {id:"sex_170",q:"What percentage of adults have had a one-night stand?",a:55,unit:"%",hint:"About 55% – more men than women, according to studies.",emoji:"🌙"},
  {id:"sex_171",q:"How many minutes does the average act of intercourse last worldwide?",a:5.4,unit:"minutes",hint:"According to a study: 5.4 minutes median – Turkey leads at 3.7.",emoji:"⏱️"},
  {id:"sex_172",q:"What percentage of women regularly achieve orgasm during sex?",a:25,unit:"%",hint:"Only ~25% through penetration alone – the rest need other stimulation.",emoji:"💫"},
  {id:"sex_173",q:"How many milligrams of testosterone does a man produce daily?",a:7,unit:"milligrams",hint:"About 7mg daily – women produce 10x less.",emoji:"💪"},
  {id:"sex_174",q:"How many cm is the average erect penis length worldwide?",a:13.1,unit:"cm",hint:"A 2015 meta-analysis of 15,000+ men – median 13.1 cm.",emoji:"📏"},
  {id:"sex_175",q:"What percentage of all websites are pornographic?",a:12,unit:"%",hint:"About 12% of all websites – generating 25% of traffic.",emoji:"🖥️"},
  {id:"sex_176",q:"How many million people worldwide have a sexually transmitted disease?",a:1000,unit:"million",hint:"About 1 billion – a WHO estimate for all STIs combined.",emoji:"🩺"},
  {id:"sex_177",q:"How many hours per week do men masturbate, according to studies?",a:1,unit:"hour",hint:"About 1 hour per week – women about half that.",emoji:"🔬"},
  {id:"sex_178",q:"How many million people identify as LGBTQ+?",a:500,unit:"million",hint:"About 5% of the world's population ≈ 500 million people.",emoji:"🏳️‍🌈"},
  {id:"sex_179",q:"What percentage of Germans have had sex in a car?",a:33,unit:"%",hint:"About 33% – cars are the third most common location after home.",emoji:"🚗"},
  {id:"sex_180",q:"How many seconds does the average male orgasm last?",a:17,unit:"seconds",hint:"3-25 seconds – median around 17 seconds.",emoji:"⏱️"},
  {id:"sex_181",q:"What percentage of all pregnancies are unplanned?",a:40,unit:"%",hint:"About 40% worldwide – over 60% in some countries.",emoji:"🤰"},
  {id:"sex_182",q:"How many million couples in Germany use the pill?",a:9,unit:"million",hint:"About 9 million women in Germany take the pill.",emoji:"💊"},
  {id:"sex_183",q:"What percentage of Germans are satisfied with their sex life?",a:65,unit:"%",hint:"About 65% – singles are less satisfied than couples.",emoji:"💑"},
  {id:"sex_184",q:"How many grams do both testicles weigh combined?",a:40,unit:"grams",hint:"About 40g together – about the weight of a small egg.",emoji:"🔬"},
  {id:"sex_185",q:"How many months does menopause last on average?",a:48,unit:"months",hint:"A 4-5-year transition period – sometimes shorter or longer.",emoji:"🌸"},
  {id:"sex_186",q:"What percentage of people have had sex at work?",a:15,unit:"%",hint:"About 15%, according to studies – usually after hours.",emoji:"💼"},
  {id:"sex_187",q:"How many minutes does it take a man on average to reach orgasm?",a:5,unit:"minutes",hint:"About 5-6 minutes – women need about 20 minutes.",emoji:"⏱️"},
  {id:"sex_188",q:"What percentage of Germans have sex at least once a week?",a:45,unit:"%",hint:"About 45% – more common among younger couples.",emoji:"❤️"},
  {id:"sex_189",q:"How many nerve endings does the clitoris have?",a:8000,unit:"nerve endings",hint:"About 8,000 nerve endings – twice as many as the penis.",emoji:"🔬"},
  {id:"sex_190",q:"How many ml of ejaculate does a normal ejaculation contain?",a:3.5,unit:"ml",hint:"2-5ml – WHO minimum for fertility: 1.5ml.",emoji:"🔬"},
  {id:"sex_191",q:"What percentage of men have experienced erectile dysfunction?",a:50,unit:"%",hint:"Over 50% of all men over 40 – the most common cause is psychological.",emoji:"🩺"},
  {id:"sex_192",q:"How many seconds does a man need after orgasm before another erection (young)?",a:1800,unit:"seconds",hint:"About 30 minutes (1,800s) – in older age, it can take hours.",emoji:"⏰"},
  {id:"sex_193",q:"What percentage of all couples cite sexual problems as a reason for separation?",a:20,unit:"%",hint:"About 20% – the most common reason after communication and trust.",emoji:"💔"},
  {id:"sex_194",q:"How many million condoms are used worldwide every day?",a:6,unit:"million",hint:"About 6 million daily – 2 billion per year.",emoji:"🎈"},
  {id:"sex_195",q:"What percentage of Germans have had sex in public?",a:25,unit:"%",hint:"About 25% – parks and public spaces are popular.",emoji:"🌿"},
  {id:"sex_196",q:"How many hormones are released during orgasm?",a:5,unit:"hormones",hint:"Oxytocin, dopamine, serotonin, endorphins, prolactin.",emoji:"🧪"},
  {id:"sex_197",q:"How many times per second is Pornhub accessed?",a:250,unit:"times",hint:"About 250 accesses per second – 81,000 videos viewed daily.",emoji:"🖥️"},
  {id:"sex_198",q:"How many million dollars is the global sex toy industry worth?",a:33000,unit:"million dollars",hint:"$33 billion annually – growing fast.",emoji:"💰"},
  {id:"sex_199",q:"What percentage of women have faked an orgasm?",a:50,unit:"%",hint:"About 50-80% say they've faked an orgasm at some point.",emoji:"🎭"},
  {id:"sex_200",q:"How many meters long can an erection be on average (foreskin)?",a:0,unit:"meters",hint:"No length – the foreskin is a ring-shaped tissue.",emoji:"🔬"},
  {id:"sex_201",q:"What percentage of Germans lose their virginity before age 16?",a:15,unit:"%",hint:"About 15% – average age the first time: 17.2 years.",emoji:"💑"},
  {id:"sex_202",q:"How many hours per month do men watch porn?",a:6,unit:"hours",hint:"About 6 hours monthly, according to Pornhub statistics.",emoji:"🖥️"},
  {id:"sex_203",q:"What percentage of all women find their nipples erogenous?",a:70,unit:"%",hint:"About 70% of women consider nipples an erogenous zone.",emoji:"🔬"},
  {id:"sex_204",q:"How many cm deep is the vagina at rest?",a:7.5,unit:"cm",hint:"About 7-8cm at rest – up to 11cm when aroused.",emoji:"📏"},
  {id:"sex_205",q:"How many hours of sleep improve sexual function?",a:8,unit:"hours",hint:"8h of sleep boosts testosterone – under 5h, it drops sharply.",emoji:"😴"},
  {id:"sex_206",q:"What percentage of Germans have experience with BDSM?",a:25,unit:"%",hint:"About 25% have BDSM experience – mild forms are very common.",emoji:"⛓️"},
  {id:"sex_207",q:"How many million people worldwide are sex addicts?",a:40,unit:"million",hint:"About 40 million – 6% of all men, 1.5% of all women.",emoji:"🩺"},
  {id:"sex_208",q:"What percentage of couples have sex at least once a month?",a:80,unit:"%",hint:"About 80% of all couples have sex at least once a month.",emoji:"💑"},
  {id:"sex_209",q:"How many minutes does foreplay last for Germans on average?",a:15,unit:"minutes",hint:"About 15 minutes – 20+ is recommended for women.",emoji:"💑"},
  {id:"sex_210",q:"What percentage of all people have a sexual fetish?",a:50,unit:"%",hint:"About 50% have a sexual preference considered a fetish.",emoji:"🔍"},
  {id:"sex_211",q:"How many million Pornhub visits are there daily?",a:130,unit:"million",hint:"About 130 million visits daily – 47 billion annually.",emoji:"🖥️"},
  {id:"sex_212",q:"How many months does a pregnancy last?",a:9,unit:"months",hint:"9 months – more precisely, 40 weeks = 280 days.",emoji:"🤰"},
  {id:"sex_213",q:"What percentage of couples are in an open relationship?",a:5,unit:"%",hint:"About 4-5% – more common among younger generations.",emoji:"💑"},
  {id:"sex_214",q:"How many picograms of oxytocin per ml are released during orgasm?",a:100,unit:"pg/ml",hint:"About 100 picograms/ml – a tiny amount with a big effect.",emoji:"💉"},
  {id:"sex_215",q:"How many seconds does an average kiss last?",a:12,unit:"seconds",hint:"About 12 seconds – the longest kiss lasted 58 hours.",emoji:"💋"},
  {id:"sex_216",q:"How many million people worldwide have HIV?",a:39,unit:"million",hint:"About 39 million people live with HIV (as of 2023).",emoji:"🩺"},
  {id:"sex_217",q:"What percentage of Germans talk about sex with their partner?",a:55,unit:"%",hint:"About 55% actively communicate about their desires.",emoji:"💬"},
  {id:"sex_218",q:"How many times in a lifetime does a person kiss on average?",a:100000,unit:"times",hint:"About 100,000 kisses – 15 minutes daily × 70 years.",emoji:"💋"},
  {id:"sex_219",q:"How many milliliters of vaginal secretion does a woman produce daily?",a:5,unit:"milliliters",hint:"About 5ml daily – increases significantly when aroused.",emoji:"🔬"},
  {id:"sex_220",q:"What percentage of Germans consider themselves monogamous?",a:85,unit:"%",hint:"About 85% – but 30-40% have cheated at some point anyway.",emoji:"💑"},
  {id:"sex_221",q:"How many million people worldwide have gonorrhea?",a:82,unit:"million",hint:"About 82 million new cases per year – WHO estimate.",emoji:"🩺"},
  {id:"sex_222",q:"How many months does male menopause (andropause) last?",a:120,unit:"months",hint:"About 10 years, gradually – testosterone declines from age 40.",emoji:"🔬"},
  {id:"sex_223",q:"What percentage of women have had more than 10 sexual partners?",a:20,unit:"%",hint:"About 20% of women and 35% of men.",emoji:"💑"},
  {id:"sex_224",q:"How many years' worth of video has been uploaded to Pornhub, if played back to back?",a:169,unit:"years",hint:"According to Pornhub: the uploaded video material adds up to about 169 years.",emoji:"🖥️"},
  {id:"sex_225",q:"What percentage of Germans have a sexual disorder?",a:30,unit:"%",hint:"About 30% – the most common disorder: low desire.",emoji:"🩺"},
  {id:"sex_226",q:"How many mg of testosterone does a 25-year-old woman have?",a:0.3,unit:"mg/dl",hint:"About 0.3mg/dl – a tenth of the male level.",emoji:"🔬"},
  {id:"sex_227",q:"How many days per month is a woman fertile?",a:6,unit:"days",hint:"About 6 days – 5 days before and on the day of ovulation.",emoji:"📅"},
  {id:"sex_228",q:"Out of 250 million sperm, how many survive until reaching the egg?",a:200,unit:"sperm",hint:"Out of 250 million, only about 200 make it to the egg – one fertilizes it.",emoji:"🔬"},
  {id:"sex_229",q:"How many minutes of stimulation do women need on average for an orgasm?",a:20,unit:"minutes",hint:"Studies show about 20 minutes – more than most men assume.",emoji:"⏱️"},
  {id:"sex_230",q:"How many days can a sperm survive in the uterus?",a:5,unit:"days",hint:"Up to 5 days – which is why you can get pregnant even before ovulation.",emoji:"🔬"},
  {id:"sex_231",q:"What percentage of Germans have had sex outdoors?",a:40,unit:"%",hint:"About 40% – numbers rise in summer.",emoji:"🌲"},
  {id:"sex_232",q:"How many million euros in revenue does the sex industry generate in Germany annually?",a:15000,unit:"million euros",hint:"About €15 billion – one of the largest markets in Europe.",emoji:"💰"},
  {id:"sex_233",q:"What percentage of men have anxiety about their penis size?",a:68,unit:"%",hint:"About 68% of all men are dissatisfied with their penis size.",emoji:"🔬"},
  {id:"sex_234",q:"How many millimeters do pupils dilate during sexual arousal?",a:3,unit:"millimeters",hint:"Up to 3mm of dilation – which is why people in love appear more attractive.",emoji:"👁️"},
  {id:"sex_235",q:"What percentage of Germans watch porn?",a:50,unit:"%",hint:"About 50% of Germans – 70% of men, 30% of women.",emoji:"🖥️"},
  {id:"sex_236",q:"How many months after infection does untreated HIV progress to AIDS?",a:120,unit:"months",hint:"Untreated, about 10 years until reaching the AIDS stage.",emoji:"🩺"},
  {id:"sex_237",q:"How many calories does a serving of semen have?",a:5,unit:"kcal",hint:"About 5 kcal per 5ml – water, proteins, fructose.",emoji:"🔬"},
  {id:"sex_238",q:"What percentage of births worldwide are C-sections?",a:21,unit:"%",hint:"About 21% – over 50% in some countries.",emoji:"🏥"},
  {id:"sex_239",q:"How many hours after sex can the morning-after pill still be used?",a:72,unit:"hours",hint:"Up to 72 hours – Ella works up to 120 hours.",emoji:"💊"},
  {id:"sex_240",q:"How many million dating app users are there worldwide?",a:366,unit:"million",hint:"About 366 million dating app users (as of 2022).",emoji:"📱"},
  {id:"sex_241",q:"What percentage of couples have sex at least once a week?",a:45,unit:"%",hint:"About 45% of couples – the younger, the more frequent.",emoji:"💑"},
  {id:"sex_242",q:"How many million dollars does the highest-paid porn actor earn per year?",a:1,unit:"million dollars",hint:"Top earners make about $1 million annually.",emoji:"💰"},
  {id:"sex_243",q:"What percentage of sexual assaults are reported?",a:15,unit:"%",hint:"Only about 10-20% of assaults are reported to police.",emoji:"⚖️"},
  {id:"sex_244",q:"How many million couples in Germany live in a long-distance relationship?",a:1,unit:"million",hint:"About 1 million couples in Germany are in a long-distance relationship.",emoji:"💑"},
];
