// 🍺 FOOD & DRINK – English
export default [
  {q:"How many calories has a Big Mac?",a:563,unit:"kcal",hint:"Davon kommen 257 kcal from dem Fett.",emoji:"🍔"},
  {q:"How many liters beer wasn at Oktoberfest 2023 getrunken?",a:7300000,unit:"literss",hint:"Das Oktoberfest is the largest Volksfest the world.",emoji:"🍺"},
  {q:"How many grams sugar in einer Dose Cola (330ml)?",a:35,unit:"grams",hint:"Das are etwa 7 Teelöffel sugar.",emoji:"🥤"},
  {q:"How many tons Schokolade isst Deutschland per year?",a:900000,unit:"tons",hint:"Weltmeiser im Schokoladenkonsum pro Kopf.",emoji:"🍫"},
  {q:"How many liters Milch needs man for 1 kg Käse?",a:10,unit:"literss",hint:"Je to Sorte 8–12 liters Milch.",emoji:"🧀"},
  {q:"How many months reift a echter Parmesan at least?",a:24,unit:"months",hint:"Premium-Parmesan reift bis to 5 years.",emoji:"🧀"},
  {q:"How many Körner coffee needs man for einen Espresso?",a:50,unit:"Körner",hint:"Ein coffeebaum produces per year ~500g coffee.",emoji:"☕"},
  {q:"How many liters wine drinks a Franzose per year?",a:45,unit:"literss",hint:"Frankreich führt worldwide den Pro-Kopf-Weinkonsum.",emoji:"🍷"},
  {q:"How many kg Pasta isst a Italiener on average per year?",a:23,unit:"kg",hint:"Italien führt worldwide den Pastakonsum.",emoji:"🍝"},
  {q:"How high is der Wasseranteil in einer Gurke in percent?",a:97,unit:"%",hint:"Gurken bestehen fast nur from water.",emoji:"🥒"},
  {q:"How many liters coffee drink Finnen pro Kopf per year?",a:12,unit:"kg",hint:"Finnland is Weltmeiser im coffeeverbrauch.",emoji:"☕"},
  {q:"How many grams Butter contains a original Croissant?",a:50,unit:"grams",hint:"Der hohe Butteranteil macht die blättrige Textur möglich.",emoji:"🥐"},
  {q:"How many percent Fettgehalt has Gänsestopfliver (Foie Gras)?",a:50,unit:"%",hint:"Eines der caloriesreichsten Lebensmittel.",emoji:"🍴"},
  {q:"How many liters water needs man for 1 kg Rindfleisch?",a:15000,unit:"literss",hint:"Rindfleisch has den größten Wasserverbrauch aller Nahrungsmittel.",emoji:"🥩"},
  {q:"How many years is der älteste becante wine alt (Speyer-wine)?",a:1650,unit:"years",hint:"Die Flasche was 1867 in einem römischen Grab gefunden.",emoji:"🍷"},
  {q:"How many grams weighs a Kaviar-Perle?",a:50,unit:"mg",hint:"Beluga-Kaviar costs bis to 25.000€ pro kg.",emoji:"🐟"},
  {q:"How many calories has a Teelöffel Olivenöl?",a:40,unit:"kcal",hint:"Gesund – aber caloriesreich wie alle Fette.",emoji:"🫒"},
  {q:"How many grams Salz isst a Deutscher daily?",a:10,unit:"grams",hint:"Empfohlen are maxitimes 6 grams.",emoji:"🧂"},
  {q:"How spicy is the Carolina Reaper in million Scoville units?",a:2.2,unit:"Mio. Scoville",hint:"Das schärfste Chili the world.",emoji:"🌶️"},
  {q:"How many hours muss Jamon Iberico at least reifen?",a:8760,unit:"hours",hint:"Das are at least 3 years.",emoji:"🥩"},
  {q:"How many Würste are beim Nürnberger Chriskindlesmarkt gegessen?",a:2000000,unit:"Würste",hint:"Nürnberger Bratwürste are die kleinsten deutschen Würste.",emoji:"🌭"},
  {q:"How old can wine get and still be drinkable in years?",a:200,unit:"years",hint:"Ein 1811er Château d'Yquem was als exzellent bewertet.",emoji:"🍷"},
  {q:"How much costs Safran pro kg in Euro?",a:10000,unit:"€/kg",hint:"Safran is das teuerste Gewürz the world.",emoji:"🌺"},
  {q:"How many Pizzen are daily worldwide gegessen in million?",a:5,unit:"million",hint:"Die USA essen allein 3 billion Pizzen per year.",emoji:"🍕"},
  {q:"How many calories has a Glas Rotwein (200ml)?",a:170,unit:"kcal",hint:"wine has mehr calories als die meisen denken.",emoji:"🍷"},
  {q:"How many hours takes die Herstellung of echtem champagne at least?",a:12960,unit:"hours",hint:"Das are at least 18 months Reifung.",emoji:"🥂"},
  {q:"How many grams sugar has a Glas Orangensaft (200ml)?",a:20,unit:"grams",hint:"Fast so viel wie Cola – oft unterschätzt.",emoji:"🍊"},
  {q:"How many minutes per day massiert man Kobe-Rind?",a:60,unit:"minutes",hint:"Sie are tatsächlich massiert und with beer gefüttert.",emoji:"🥩"},
  {q:"How much percent des Wasabis im Restaurant is echt?",a:1,unit:"%",hint:"99% is gefälschter Wasabi from Meerrettich und Farbe.",emoji:"🍣"},
  {q:"How many billion liters beer braut Deutschland per year?",a:8,unit:"billion literss",hint:"billion liters – Platz 5 worldwide.",emoji:"🍺"},
  {q:"How many kcal has a on averagee Currywurst?",a:350,unit:"kcal",hint:"with Pommes kommen nochtimes 400 kcal dazu.",emoji:"🌭"},
  {q:"How many milliliterss Espresso contains a Standard-Tasse?",a:25,unit:"ml",hint:"Ein Doppio has 50 ml.",emoji:"☕"},
  {q:"How many kg Mehl verneeds Deutschland pro Kopf in the year?",a:86,unit:"kg",hint:"Wir are a Brotnation.",emoji:"🍞"},
  {q:"How many liters water needs man for 1 liters beer?",a:300,unit:"literss",hint:"Inklusive Anbau, Verarbeitung und Kühlung.",emoji:"🍺"},
  {q:"How many calories has a Döner Kebab?",a:850,unit:"kcal",hint:"Der Döner is Deutschlands beliebtestes Fast Food.",emoji:"🌯"},
  {q:"How many billion liters wine produces Frankreich per year?",a:4,unit:"billion literss",hint:"billion liters – Platz 2 worldwide to Italien.",emoji:"🍷"},
  {q:"How many grams Eiweiß has a Ei?",a:6,unit:"grams",hint:"Ein Hühnerei has ~6g Protein.",emoji:"🥚"},
  {q:"How many hours fermentiert Kimchi traditionell?",a:24,unit:"hours",hint:"Manchtimes auch months – je to Rezept.",emoji:"🥬"},
  {q:"How many calories has 100g dunkle Schokolade?",a:550,unit:"kcal",hint:"Viel Fett und sugar – aber auch Antioxidantien.",emoji:"🍫"},
  {q:"How many liters Tee drink Briten per day (pro Person)?",a:3,unit:"Tassen",hint:"Briten drink annually 60 billion Tassen Tee.",emoji:"🫖"},
  {q:"How many grams sugar has Ketchup pro 100g?",a:22,unit:"grams",hint:"Ketchup contains überraschend viel sugar.",emoji:"🍅"},
  {q:"How many liters water needs man for 1 kg Mandeln?",a:15000,unit:"literss",hint:"Mandeln are extrem wasserintensiv.",emoji:"🌰"},
  {q:"How many billion Eier are in Germany per year gegessen?",a:15,unit:"billion",hint:"Etwa 180 Eier pro Person und Jahr.",emoji:"🥚"},
  {q:"How many kcal has a Packung Chips (200g)?",a:1080,unit:"kcal",hint:"over die Hälfte des dayssbedarfs in einem Snack.",emoji:"🍟"},
  {q:"How many months fermentiert echter Roquefort-Käse?",a:3,unit:"months",hint:"in speziellen Höhlen at konstanter Temperatur.",emoji:"🧀"},
  {q:"How many grams Salz contains a nortimeses Brot (700g)?",a:10,unit:"grams",hint:"Brot is a the largestn Salzquellen.",emoji:"🍞"},
  {q:"How many liters beer has der on averagee Bayer per year?",a:150,unit:"literss",hint:"Bayern führt den deutschen beerkonsum an.",emoji:"🍺"},
  {q:"How many calories has a Schnitzel Wiener Art (ohne Beilagen)?",a:650,unit:"kcal",hint:"with Kartoffelsalat kommen nochtimes 300 kcal dazu.",emoji:"🥩"},
  {q:"How many tons Obst isst Deutschland per year?",a:5000000,unit:"tons",hint:"Äpfel are das beliebteste Obst.",emoji:"🍎"},
  {q:"How many percent alcohol has Standard-beer?",a:5,unit:"%",hint:"Starkbeere have bis to 14% alcohol.",emoji:"🍺"},
  {q:"How many grams Kohlenhydrate has 100g Weißbrot?",a:50,unit:"grams",hint:"Weißbrot has fast so viele Kohlenhydrate wie sugar.",emoji:"🍞"},
  {q:"How many hours takes die Fermentation of echtem Sourdough?",a:48,unit:"hours",hint:"Echter Sauerteig needs Zeit for Geschmack.",emoji:"🍞"},
  {q:"How many liters water needs man for 1 kg Avocado?",a:1000,unit:"literss",hint:"Avocados are sehr wasserintensiv.",emoji:"🥑"},
  {q:"How many kcal has a Tafel Vollmilchschokolade (100g)?",a:535,unit:"kcal",hint:"Milchschokolade has etwas weniger als dunkle.",emoji:"🍫"},
  {q:"How many tons Bananen importiert Deutschland per year?",a:1000000,unit:"tons",hint:"Banane is die meisgekaufte Frucht Deutschlands.",emoji:"🍌"},
  {q:"How many grams Fett has 100g Butter?",a:83,unit:"grams",hint:"Butter is fast pures Fett.",emoji:"🧈"},
  {q:"How many billion Würste are in Germany per year produces?",a:1500,unit:"million",hint:"Deutschland is Weltmeiser in Wurstvielfalt.",emoji:"🌭"},
  {q:"How many kcal has a Döner in einem nortimesen Fladenbrot?",a:1000,unit:"kcal",hint:"Ein Döner can over die Hälfte des dayssbedarfs decken.",emoji:"🌯"},
  {q:"How many liters water needs man for 1 kg Schokolade?",a:17196,unit:"literss",hint:"Die wasserintensivste Süßigkeit.",emoji:"🍫"},
  {q:"How many hours reift a Gouda-Käse at least?",a:720,unit:"hours",hint:"30 days for jungen Gouda – alter Gouda reift months.",emoji:"🧀"},
  {q:"How many calories has a Maß beer (1 liters)?",a:430,unit:"kcal",hint:"beer has pro 100ml etwa 43 kcal.",emoji:"🍺"},
  {q:"How many grams Protein has 100g Hühnchen (Brust)?",a:31,unit:"grams",hint:"Hühnchenbrust is a der eiweißreichsten Quellen.",emoji:"🍗"},
  {q:"How many tons coffee drinks Deutschland per year?",a:500000,unit:"tons",hint:"coffee is das Lieblingsgetränk der Deutschen.",emoji:"☕"},
  {q:"How many kcal has a nortimese Portion Pommes Frites (150g)?",a:450,unit:"kcal",hint:"with Ketchup und Mayonnaise deutlich mehr.",emoji:"🍟"},
  {q:"How many liters wine drink Deutsche pro Kopf per year?",a:20,unit:"literss",hint:"Weniger als Franzosen oder Portugiesen.",emoji:"🍷"},
  {q:"How many grams sugar has a Glas Eisee (250ml)?",a:25,unit:"grams",hint:"Eisee is a versteckte sugarfalle.",emoji:"🍵"},
  {q:"How many kcal has a nortimeses Croissant?",a:250,unit:"kcal",hint:"Kleines Gebäck with vielen calories.",emoji:"🥐"},
  {q:"How many months fermentiert echter Miso?",a:12,unit:"months",hint:"Traditioneller Miso reift 1-3 years.",emoji:"🫙"},
  {q:"How many grams Mehl needs man for a Pizza (30cm)?",a:250,unit:"grams",hint:"Plus Tomatensauce, Käse und Belag.",emoji:"🍕"},
  {q:"How many liters water needs man for 1 kg Schweinefleisch?",a:5988,unit:"literss",hint:"Deutlich weniger als Rind, aber immer noch viel.",emoji:"🥩"},
  {q:"How many kcal has a Stück Schwaszwälder Kirschtorte?",a:450,unit:"kcal",hint:"Sahne, Schokolade und Kirschwasser.",emoji:"🎂"},
  {q:"How many grams Capsaicin contains a Jalapeño?",a:100,unit:"mg",hint:"Capsaicin is der Wirkstoff der Schärfe.",emoji:"🌶️"},
  {q:"How many tons Erdbeeren produces Deutschland per year?",a:100000,unit:"tons",hint:"Bayern is größter Produzent.",emoji:"🍓"},
  {q:"How many hours needs a Käse um to schimmeln (Camembert)?",a:168,unit:"hours",hint:"7 days for die charakterisische weiße Rinde.",emoji:"🧀"},
  {q:"How many liters water needs man for 1 Tasse coffee?",a:140,unit:"literss",hint:"Inklusive Anbau und Verarbeitung.",emoji:"☕"},
  {q:"How many calories has a Hamburger (ohne Pommes)?",a:500,unit:"kcal",hint:"Je to Belag mehr oder weniger.",emoji:"🍔"},
  {q:"How many grams Omega-3 has 100g Lachs?",a:2.5,unit:"grams",hint:"Lachs is a der besten Omega-3-Quellen.",emoji:"🐟"},
  {q:"How many million Hektoliters beer drinks die Welt per year?",a:1900,unit:"Mio. Hektoliters",hint:"China is the largest beermarkt worldwide.",emoji:"🍺"},
  {q:"How many kcal has 1 grams alcohol?",a:7,unit:"kcal",hint:"Mehr als sugar (4 kcal) – aber weniger als Fett (9 kcal).",emoji:"🍺"},
  {q:"How many tons Süßigkeiten isst Deutschland per year?",a:800000,unit:"tons",hint:"Haribo is das becanteste deutsche Süßwaseunternehmen.",emoji:"🍬"},
  {q:"How many hours takes das Räuchern eines Schinkens?",a:48,unit:"hours",hint:"Echtes Kalträuchern takes days.",emoji:"🥩"},
  {q:"How many grams sugar has a Päckchen Gummibearchen (200g)?",a:140,unit:"grams",hint:"70% sugar – Gummibearchen are fast purer sugar.",emoji:"🐻"},
  {q:"How many kcal has a beer (0,5l, Pils)?",a:215,unit:"kcal",hint:"Ein beer has mehr calories als a Apfel.",emoji:"🍺"},
  {q:"How many liters water needs man for 1 kg Käse?",a:5000,unit:"literss",hint:"Inklusive der Milch die man needs.",emoji:"🧀"},
  {q:"How many grams has a Standard-Würfel sugar?",a:4,unit:"grams",hint:"16 kcal pro Würfel.",emoji:"🍬"},
  {q:"How many tons Tomaten produces Italien per year?",a:5000000,unit:"tons",hint:"Größter Tomatenproduzent Europas.",emoji:"🍅"},
  {q:"How many milliliterss has a Standard-Shot Schnaps?",a:40,unit:"ml",hint:"in Germany are 2 cl der Standard.",emoji:"🥃"},
  {q:"How many kcal has 100g Erdnussbutter?",a:589,unit:"kcal",hint:"Sehr caloriesreich – aber voller Proteine.",emoji:"🥜"},
  {q:"How many grams Eiweiß has 100g Quark (Magerquark)?",a:12,unit:"grams",hint:"Magerquark is a günstige Proteinquelle.",emoji:"🥛"},
  {q:"How many liters water needs man for 1 kg Tomaten?",a:183,unit:"literss",hint:"Deutlich weniger als Fleisch.",emoji:"🍅"},
  {q:"How many calories has 100g Brokkoli?",a:34,unit:"kcal",hint:"Eines der nährstoffreichsten Gemüse.",emoji:"🥦"},
  {q:"How many tons Wurst produces Deutschland per year?",a:1500000,unit:"tons",hint:"1,5 million tons – over 1500 Sorten.",emoji:"🌭"},
  {q:"How many hours reift echter Roquefort in Höhlen?",a:2160,unit:"hours",hint:"90 days in Combalou-Höhlen.",emoji:"🧀"},
  {q:"How many kcal has a Brezn (80g)?",a:270,unit:"kcal",hint:"with Butter nochtimes 100 kcal mehr.",emoji:"🥨"},
  {q:"How many grams sugar has 100ml Fruchtsaft?",a:10,unit:"grams",hint:"Naturtrüber Saft contains genauso viel sugar wie Cola.",emoji:"🍹"},
  {q:"How many billion Eier produces Deutschland per year?",a:15,unit:"billion",hint:"Trotzdem importieren wir noch Eier.",emoji:"🥚"},
  {q:"How many kcal has a Weißwurst-Frühstück (2 Würste + Brezel + beer)?",a:900,unit:"kcal",hint:"Ein bayerisches Frühstück is keine leichte Mahlzeit.",emoji:"🍺"},
  {q:"How many liters water needs man for 1 liters Orangensaft?",a:1000,unit:"literss",hint:"Anbau, Transport und Verarbeitung addieren sich.",emoji:"🍊"},
  {q:"How many grams Fett has a Döner?",a:30,unit:"grams",hint:"Je to Zubereitung 20-50g Fett.",emoji:"🌯"},
  {q:"How many tons Honig produces Deutschland per year?",a:25000,unit:"tons",hint:"Trotzdem importieren wir deutlich mehr.",emoji:"🍯"},
  {q:"How many kcal has a Stück Käsekuchen (100g)?",a:320,unit:"kcal",hint:"Eines der caloriesreichsten deutschen Desserts.",emoji:"🎂"},
  {q:"How many grams Calcium has 100ml Milch?",a:120,unit:"grams",hint:"Milch is die beste Calciumquelle.",emoji:"🥛"},
  {q:"How many hours fermentiert echter Balsamico from Modena?",a:87600,unit:"hours",hint:"10 years – manchtimes sogar 25 years.",emoji:"🫙"},
  {q:"How many million liters champagne are worldwide per year produces?",a:300,unit:"million literss",hint:"million liters from nur einer Region Frankreichs.",emoji:"🥂"},
  {q:"How many kcal has 100g Avocado?",a:160,unit:"kcal",hint:"Reich an gesunden Fetten.",emoji:"🥑"},
  {q:"How many tons Kartoffeln isst Deutschland per year?",a:4000000,unit:"tons",hint:"over 50 kg pro Person per year.",emoji:"🥔"},
  {q:"How many grams sugar has 100g Ketchup?",a:22,unit:"grams",hint:"Ketchup is fast a Viertel sugar.",emoji:"🍅"},
  {q:"How many kcal has a Sauerbraten with Knödel?",a:1200,unit:"kcal",hint:"Ein echtes deutsches Festmahl.",emoji:"🥩"},
  {q:"How many milliliterss fasst a Standard-Weinglas?",a:200,unit:"ml",hint:"Ein nortimeses Weinglas – nicht bis zum Rand.",emoji:"🍷"},
  {q:"How many tons Fleisch isst Deutschland per year?",a:7500000,unit:"tons",hint:"Etwa 90 kg Fleisch pro Person per year.",emoji:"🥩"},
  {q:"How many kcal has a Lebkuchen (35g)?",a:130,unit:"kcal",hint:"Weihnachtsgebäck with versteckten calories.",emoji:"🍪"},
  {q:"How many grams Protein has 100g Linsen (gekocht)?",a:9,unit:"grams",hint:"Linsen are a gute pflanzliche Proteinquelle.",emoji:"🫘"},
  {q:"How many liters water needs man for 1 kg Reis?",a:2500,unit:"literss",hint:"Nassreis-Anbau verneeds enorm viel water.",emoji:"🍚"},
  {q:"How many kcal has 100g whalenüsse?",a:654,unit:"kcal",hint:"Sehr caloriesreich aber voller gesunder Fette.",emoji:"🌰"},
  {q:"How many grams sugar has a Flasche Energydrink (250ml)?",a:27,unit:"grams",hint:"Ähnlich wie Cola – plus caffeine.",emoji:"⚡"},
  {q:"How many tons sugar konsumiert Deutschland per year?",a:3000000,unit:"tons",hint:"3 million tons – over 35 kg pro Person.",emoji:"🍬"},
  {q:"How many kcal has a Apfelstrudel (100g)?",a:250,unit:"kcal",hint:"Wiener Spezialität with Butter und sugar.",emoji:"🥐"},
  {q:"How many milliliterss has a Standard-Espresso?",a:25,unit:"ml",hint:"Klein aber stark – 7g coffeemehl.",emoji:"☕"},
  {q:"How many grams Kohlenhydrate has 100g Kartoffeln?",a:17,unit:"grams",hint:"Weniger als gedacht – Fett in Pommes is das Problem.",emoji:"🥔"},
  {q:"How many liters wine drinks die Welt per year (billion)?",a:26,unit:"billion literss",hint:"billion liters – steigende Tendenz.",emoji:"🍷"},
  {q:"How many kcal has 100g Vollmilch (3,5%)?",a:64,unit:"kcal",hint:"Milch is caloriesärmer als die meisen denken.",emoji:"🥛"},
  {q:"How many grams sugar has 100g Joghurt (Fruchtjoghurt)?",a:13,unit:"grams",hint:"Fruchtjoghurt has überraschend viel sugar.",emoji:"🫙"},
  {q:"How many million tons Weizen produces Deutschland per year?",a:22,unit:"million tons",hint:"Deutschland is einer the largestn Weizenproduzduckn Europas.",emoji:"🌾"},
  {q:"How many kcal has a Brezel with Butter?",a:400,unit:"kcal",hint:"Eine beliebte bayrische Snack-Kombination.",emoji:"🥨"},
  {q:"How many grams Protein has 100g Thunfisch (from der Dose)?",a:26,unit:"grams",hint:"Einer der günstigsten Proteinsupplier.",emoji:"🐟"},
  {q:"How many liters water needs man for 1 Tasse Tee?",a:30,unit:"literss",hint:"Deutlich weniger als coffee.",emoji:"🫖"},
  {q:"How many kcal has 100g Hüttenkäse?",a:98,unit:"kcal",hint:"Sehr eiweißreich und caloriesarm.",emoji:"🧀"},
  {q:"How many grams sugar has a Gummibearchen?",a:2,unit:"grams",hint:"Pro Stück – eine Packung has 140g sugar.",emoji:"🐻"},
  {q:"How many million tons Lebensmittel verschwendet Deutschland per year?",a:12,unit:"million tons",hint:"Ein Drittel aller producesen Lebensmittel landet im Müll.",emoji:"🗑️"},
  {q:"How many kcal has a Brot (Scheibe, 50g)?",a:120,unit:"kcal",hint:"Abhängig of der Brotsorte.",emoji:"🍞"},
  {q:"How many grams Eiweiß has a Hühnerei?",a:6,unit:"grams",hint:"Eier have das hochwertigste Protein aller Lebensmittel.",emoji:"🥚"},
  {q:"How many million liters Cognac und Armagnac destilliert Frankreich per year?",a:200,unit:"million literss",hint:"million liters Cognac und Armagnac.",emoji:"🥃"},
  {q:"How many kcal has 100g Olivenöl?",a:884,unit:"kcal",hint:"Das caloriesreichste gängige Lebensmittel.",emoji:"🫒"},
  {q:"How many grams sugar has 100ml Orangensaft (frisch gepresst)?",a:8,unit:"grams",hint:"Frisch gepresst has etwas weniger sugar als Fertigsaft.",emoji:"🍊"},
  {q:"How many tons Schinken produces Spanien per year?",a:350000,unit:"tons",hint:"Spanien is Weltmeiser im Schinkenkonsum.",emoji:"🥩"},
  {q:"How many kcal has a Stück Tiramisu (100g)?",a:400,unit:"kcal",hint:"Mascarpone, Eier und sugar machen es caloriesreich.",emoji:"🎂"},
  {q:"How many grams Fett has 100g Cheddar-Käse?",a:34,unit:"grams",hint:"Hartkäse are generell sehr fettreich.",emoji:"🧀"},
  {q:"How many liters Schnaps drinks a Österreicher per year?",a:5,unit:"literss",hint:"Österreich führt Europa im Schnapskonsum an.",emoji:"🥃"},
  {q:"How many kcal has 100g Lachs (geräuchert)?",a:180,unit:"kcal",hint:"Lachs has mehr calories als mageres Fleisch.",emoji:"🐟"},
  {q:"How many grams Protein has 100g Tempeh?",a:19,unit:"grams",hint:"Tempeh has mehr Protein als Tofu.",emoji:"🫘"},
  {q:"How many million tons sugar isst die Welt per year?",a:200,unit:"million tons",hint:"million tons – steigend.",emoji:"🍬"},
  {q:"How many kcal has a Gulasch with Reis?",a:800,unit:"kcal",hint:"Ein sättigendes Mitdaysssen.",emoji:"🍲"},
  {q:"How many grams Kohlenhydrate has 100g Weißbrot?",a:50,unit:"grams",hint:"Weißbrot has an hohen glykämischen Index.",emoji:"🍞"},
  {q:"How many million tons fish are worldwide per year gegessen?",a:90,unit:"million tons",hint:"million tons – die oceans are überfischt.",emoji:"🐟"},
  {q:"How many kcal has 100g liverwurst?",a:330,unit:"kcal",hint:"Sehr fett- und caloriesreich.",emoji:"🌭"},
  {q:"How many grams Ballaststoffe has 100g Vollkornbrot?",a:7,unit:"grams",hint:"Deutlich mehr als Weißbrot (2g).",emoji:"🍞"},
  {q:"How many liters Trinkwasser verneeds a Deutscher daily?",a:124,unit:"literss",hint:"Davon drinks man nur 1-2 liters direkt.",emoji:"💧"},
  {q:"How many kcal has a Stück Schwaszbrot (50g)?",a:108,unit:"kcal",hint:"caloriesärmer als Weißbrot.",emoji:"🍞"},
  {q:"How many grams sugar has 100ml Cola?",a:10.6,unit:"grams",hint:"over 10% sugar in jedem Schluck.",emoji:"🥤"},
  {q:"How many tons Käse produces Deutschland per year?",a:2000000,unit:"tons",hint:"Deutschland is weltführend in der Käseproduktion.",emoji:"🧀"},
  {q:"How many kcal has 100g Baklava?",a:430,unit:"kcal",hint:"Süßes türkisches Gebäck from Blätterteig und Honig.",emoji:"🍯"},
  {q:"How many grams Eiweiß has 100g Rinderfilet?",a:22,unit:"grams",hint:"Mageres Rindfleisch is a hervorragende Proteinquelle.",emoji:"🥩"},
  {q:"How many million liters Wodka drinks Russland per year?",a:1600,unit:"million literss",hint:"Russland führt worldwide den Wodkakonsum.",emoji:"🥃"},
  {q:"How many kcal has a Stück Apfelkuchen (100g)?",a:290,unit:"kcal",hint:"with Sahne nochtimes 100 kcal mehr.",emoji:"🥧"},
  {q:"How many grams Fett has 100g Camembert?",a:24,unit:"grams",hint:"Der Fettgehalt variiert je to Reifedegrees.",emoji:"🧀"},
  {q:"How many liters water needs man for 1 kg Soja?",a:1000,unit:"literss",hint:"Weniger als tierische Produkte.",emoji:"🫘"},
  {q:"How many kcal has a Franzbrötchen (80g)?",a:320,unit:"kcal",hint:"Hamburger Spezialität with Butter und Zimt.",emoji:"🥐"},
  {q:"How many grams Kohlenhydrate has 100g Nudeln (ungekocht)?",a:70,unit:"grams",hint:"Nudeln are a Kohlenhydrat-Bombe.",emoji:"🍝"},
  {q:"How many tons Schokolade exportiert Deutschland per year?",a:400000,unit:"tons",hint:"Deutschland is Europas größter Schokoladenexporteur.",emoji:"🍫"},
  {q:"How many kcal has a Weißwein-Schorle (200ml)?",a:80,unit:"kcal",hint:"Weniger als Rotwein through die Verdünnung.",emoji:"🍷"},
  {q:"How many grams sugar has a Bounty (57g)?",a:31,unit:"grams",hint:"over die Hälfte is sugar.",emoji:"🍫"},
  {q:"How many million liters Sekt drinks Deutschland per year?",a:300,unit:"million literss",hint:"Deutschland is Weltmeiser im Sektkonsum.",emoji:"🥂"},
  {q:"How many kcal has 100g Nüsse (gemischt)?",a:600,unit:"kcal",hint:"Nüsse are sehr caloriesreich aber gesund.",emoji:"🥜"},
  {q:"How many grams Eiweiß has 100g Shrimps?",a:24,unit:"grams",hint:"Sehr proteinreich und caloriesarm.",emoji:"🍤"},
  {q:"How many liters Milch drinks a Deutscher per year?",a:52,unit:"literss",hint:"Rückgang seit yearsn – Alternativen boomen.",emoji:"🥛"},
  {q:"How many kcal has 100g Hummus?",a:177,unit:"kcal",hint:"Gesunder Aufschnitt from Kichererbsen.",emoji:"🫘"},
  {q:"How many grams Fett has 100g Chips?",a:35,unit:"grams",hint:"Ein Drittel der Chips besteht from Fett.",emoji:"🍟"},
  {q:"How many tons Tomatenmark produces die Welt per year?",a:9000000,unit:"tons",hint:"Die Basis fast aller Saucen.",emoji:"🍅"},
  {q:"How many kcal has a Stück Königsberger Klopse (2 Stück)?",a:400,unit:"kcal",hint:"Deutsche Fleischbällchen in Kapernsauce.",emoji:"🍲"},
  {q:"How many grams Kohlenhydrate has 100g Honig?",a:80,unit:"grams",hint:"Honig besteht fast nur from sugar.",emoji:"🍯"},
  {q:"How many million tons Getreide produces die EU per year?",a:300,unit:"million tons",hint:"Getreide is die wichtigste Nahrungsgrundlage.",emoji:"🌾"},
  {q:"How many kcal has a Glas Smoothie (300ml)?",a:180,unit:"kcal",hint:"Smoothies können viele versteckte calories have.",emoji:"🍹"},
  {q:"How many grams Protein has 100g pumpkinkerne?",a:30,unit:"grams",hint:"Eine der proteinreichsten pflanzlichen Quellen.",emoji:"🎃"},
  {q:"How many billion liters beer braut die USA per year?",a:20,unit:"billion literss",hint:"Größter beermarkt the world to China.",emoji:"🍺"},
  {q:"How many kcal has a Tasse Cappuccino?",a:120,unit:"kcal",hint:"Milch und Schaum have calories.",emoji:"☕"},
  {q:"How many grams sugar has 100g Marmelade?",a:65,unit:"grams",hint:"Marmelade is fast zwei Drittel sugar.",emoji:"🍓"},
  {q:"How many tons Butter produces Deutschland per year?",a:500000,unit:"tons",hint:"Deutschland is Europas größter Butterproduzent.",emoji:"🧈"},
  {q:"How many kcal has 100g Mandeln?",a:576,unit:"kcal",hint:"Sehr caloriesreich – auch wenn sie gesund are.",emoji:"🌰"},
  {q:"How many grams Eiweiß has 100g Mozzarella?",a:18,unit:"grams",hint:"Mehr Protein als die meisen Weichkäse.",emoji:"🧀"},
  {q:"How many hours fermentiert traditionelles Sauerkraut?",a:336,unit:"hours",hint:"14 days oder mehr.",emoji:"🥬"},
  {q:"How many kcal has 100g Frühstücksflocken (Cornflakes)?",a:370,unit:"kcal",hint:"Weniger als Müsli with Nüssen.",emoji:"🥣"},
  {q:"How many grams Kohlenhydrate has 100g Weintrauben?",a:17,unit:"grams",hint:"Trauben are sehr sugarreich.",emoji:"🍇"},
  {q:"How many million tons Fleisch produces die Welt per year?",a:340,unit:"million tons",hint:"Davon is die Hälfte Schweinefleisch.",emoji:"🥩"},
  {q:"How many kcal has a Knäckebrot (10g)?",a:34,unit:"kcal",hint:"Sehr caloriesarm – gut als Diätknacker.",emoji:"🍞"},
  {q:"How many grams Fett has 100g Sahne (Schlagsahne)?",a:35,unit:"grams",hint:"Schlagsahne is fast reines Fett.",emoji:"🍦"},
  {q:"How many liters water needs man for 1 kg Äpfel?",a:822,unit:"literss",hint:"Äpfel brauchen deutlich weniger water als exotische Früchte.",emoji:"🍎"},
  {q:"How many kcal has a Berliner Pfannkuchen (60g)?",a:250,unit:"kcal",hint:"Frittiert und with Marmelade gefüllt.",emoji:"🍩"},
  {q:"How many grams Protein has 100g Kichererbsen (gekocht)?",a:9,unit:"grams",hint:"Eine wichtige vegane Proteinquelle.",emoji:"🫘"},
  {q:"How many tons Olivenöl produces Spanien per year?",a:1800000,unit:"tons",hint:"Größter Olivenölproduzent worldwide.",emoji:"🫒"},
  {q:"How many kcal has 100g Speck?",a:541,unit:"kcal",hint:"Einer der caloriesreichsten Fleischprodukte.",emoji:"🥓"},
  {q:"How many grams Kohlenhydrate has 100g Süßkartoffeln?",a:20,unit:"grams",hint:"Etwas mehr als nortimese Kartoffeln.",emoji:"🍠"},
  {q:"How many million Hektoliters wine produces Italien per year?",a:50,unit:"Mio. Hektoliters",hint:"Italiens größter Weinexport-Posten.",emoji:"🍷"},
  {q:"How many kcal has 100g Räucherlachs?",a:180,unit:"kcal",hint:"Weniger caloriesreich als geräuchertes Fleisch.",emoji:"🐟"},
  {q:"How many grams Fett has 100g Bratwurst?",a:25,unit:"grams",hint:"Bratwurst is a fettreiches Produkt.",emoji:"🌭"},
  {q:"How many hours takes die Herstellung of Sojasoße traditionell?",a:4380,unit:"hours",hint:"6 months Fermentation.",emoji:"🫙"},
  {q:"How many kcal has a Pizza Margherita (30cm)?",a:900,unit:"kcal",hint:"Die klassische Pizza – noch ohne Extras.",emoji:"🍕"},
  {q:"How many grams sugar has 100g Honigmelone?",a:8,unit:"grams",hint:"Melone is im Sommer perfekt.",emoji:"🍈"},
  {q:"How many million tons sugar stecken in der worldwideen Coca-Cola-Produktion per year?",a:10,unit:"million tons",hint:"million tons sugar in Coca-Cola annually.",emoji:"🥤"},
  {q:"How many kcal has 100g Edamer Käse?",a:357,unit:"kcal",hint:"Ein milder Schnitt-Käse with mittlerem Fettgehalt.",emoji:"🧀"},
  {q:"How many grams Eiweiß has 100g griechischer Joghurt?",a:10,unit:"grams",hint:"Doppelt so viel wie nortimeser Joghurt.",emoji:"🫙"},
  {q:"How many billion liters Scotch Whisky exportiert Schottland per year?",a:1300,unit:"million literss",hint:"1,3 billion liters – Scotch Whisky is a Riesenmarkt.",emoji:"🥃"},
  {q:"How many kcal has 100g Mayonnaise?",a:680,unit:"kcal",hint:"Fast reines Fett from Öl und Ei.",emoji:"🫙"},
  {q:"How many grams Fett has 100g Avocado?",a:15,unit:"grams",hint:"Ungesättigte Fettsäuren – die guten Fette.",emoji:"🥑"},
  {q:"How many million kg coffee verneeds Deutschland daily?",a:2,unit:"million kg",hint:"million kilograms coffee daily.",emoji:"☕"},
  {q:"How many kcal has 100g Camembert (45% Fett)?",a:290,unit:"kcal",hint:"Weichkäse are caloriesreich.",emoji:"🧀"},
  {q:"How many grams Kohlenhydrate has 100g Banane?",a:23,unit:"grams",hint:"Bananen liefern schnelle Energie.",emoji:"🍌"},
  {q:"How many grams Eiweiß has 100g Tofu?",a:8,unit:"grams",hint:"Tofu is a wichtige vegane Proteinquelle.",emoji:"🫘"},
  {q:"How many kcal has 100g Schinken?",a:130,unit:"kcal",hint:"Weniger fett als Salami.",emoji:"🥩"},
  {q:"How many grams sugar has a Schokoriegel (Mars, 51g)?",a:36,unit:"grams",hint:"Fast drei Viertel des Schokoriegels is sugar.",emoji:"🍫"},
  {q:"How many liters beer drinks a Tscheche per year?",a:189,unit:"literss",hint:"Weltmeiser im Pro-Kopf-beerverbrauch.",emoji:"🍺"},
  {q:"How many grams Fett has 100g Nutella?",a:31,unit:"grams",hint:"Und 57g sugar dazu.",emoji:"🍫"},
  {q:"How many kcal has 100g Lachs (frisch)?",a:208,unit:"kcal",hint:"Reich an Omega-3-Fettsäuren.",emoji:"🐟"},
  {q:"How many kg Fleisch isst a Amerikaner per year?",a:120,unit:"kg",hint:"Fast doppelt so viel wie a Europäer.",emoji:"🥩"},
  {q:"How many grams sugar has a Glas Milchcoffee (Latte, 300ml)?",a:14,unit:"grams",hint:"through die Milch.",emoji:"☕"},
  {q:"How many kcal has a Stück Tiramisu (150g)?",a:600,unit:"kcal",hint:"Mascarpone macht es sehr caloriesreich.",emoji:"🎂"},
  {q:"How many grams Protein has 100g Seitan?",a:25,unit:"grams",hint:"Weizenglutenprodukt – sehr proteinreich.",emoji:"💪"},
  {q:"How many liters water needs man for 1 kg Hühnchen?",a:4325,unit:"literss",hint:"Deutlich weniger als Rind.",emoji:"🐔"},
  {q:"How many kcal has a Donut (Glazed, 57g)?",a:269,unit:"kcal",hint:"Klein aber mächtig caloriesreich.",emoji:"🍩"},
  {q:"How many grams Fett has 100g Chorizo?",a:40,unit:"grams",hint:"Eine der fettreichsten Wurstspecies.",emoji:"🌭"},
  {q:"How many percent Fett contains griechischer Joghurt (nortimes)?",a:10,unit:"%",hint:"Deutlich fettreicher als nortimeser Joghurt.",emoji:"🫙"},
  {q:"How many kcal has 100g Roquefort-Käse?",a:369,unit:"kcal",hint:"Schimmelkäse are caloriesreicher.",emoji:"🧀"},
  {q:"How many grams sugar has 100g Müsli?",a:15,unit:"grams",hint:"Ungesüßtes Müsli has weniger – Fertigprodukte viel mehr.",emoji:"🥣"},
  {q:"How many liters produces a Weinberg (Hektar) per year?",a:5000,unit:"literss",hint:"wine needs erstaunlich viel water.",emoji:"🍷"},
  {q:"How many kcal has a Glas Apfelsaft (200ml)?",a:94,unit:"kcal",hint:"Fast wie Cola – trotz 'gesund'.",emoji:"🍎"},
  {q:"How many grams Protein has 100g Haferflocken?",a:13,unit:"grams",hint:"Eine der proteinreichsten Getreidespecies.",emoji:"🌾"},
  {q:"How many kcal has a Stück Focaccia (100g)?",a:270,unit:"kcal",hint:"Italienisches Fladenbrot with Olivenöl.",emoji:"🍞"},
  {q:"How many grams Kohlenhydrate has 100g Paprika?",a:6,unit:"grams",hint:"Paprika is sehr kohlenhydratarm.",emoji:"🌶️"},
  {q:"How many liters Milch drinks a Finne per year?",a:180,unit:"literss",hint:"Finnland is Weltmeiser im Milchkonsum.",emoji:"🥛"},
  {q:"How many kcal has a Vollkornbrot (Scheibe, 50g)?",a:105,unit:"kcal",hint:"Etwas weniger als Weißbrot.",emoji:"🍞"},
  {q:"How many grams sugar has 100g Balsamico-Essig?",a:17,unit:"grams",hint:"Viel sugar for a Sauerprodukt.",emoji:"🫙"},
  {q:"How many tons Sushi is daily in Japan gegessen?",a:2000,unit:"tons",hint:"Japan bleibt the worldmarktführer.",emoji:"🍣"},
  {q:"How many kcal has a hot dog (nortimes)?",a:290,unit:"kcal",hint:"with Senf und Ketchup etwas mehr.",emoji:"🌭"},
  {q:"How many grams Calcium has 100g Parmesan?",a:1184,unit:"grams",hint:"Parmesan has mehr Calcium als fast jedes andere Lebensmittel.",emoji:"🧀"},
  {q:"How many million tons Schokolade produces die Welt per year?",a:8,unit:"million tons",hint:"million tons worldwide.",emoji:"🍫"},
  {q:"How many kcal has 100g Macarons?",a:450,unit:"kcal",hint:"Sehr sugarreich und caloriesreich.",emoji:"🍬"},
  {q:"How many grams sugar has a Red Bull (250ml)?",a:27,unit:"grams",hint:"Fast so viel wie Cola.",emoji:"⚡"},
  {q:"How many liters water needs man for 1 Tasse heißen Tee?",a:30,unit:"literss",hint:"Inklusive Anbau und Verarbeitung.",emoji:"🍵"},
  {q:"How many kcal has a Stück Baklava (50g)?",a:215,unit:"kcal",hint:"Süß und caloriesreich.",emoji:"🍯"},
  {q:"How many grams Protein has 100g pumpkinsamen?",a:30,unit:"grams",hint:"Eine der proteinreichsten pflanzlichen Quellen.",emoji:"🎃"},
  {q:"How many tons sugar isst a Europäer per year?",a:38,unit:"kg",hint:"Kg – over 100g daily.",emoji:"🍬"},
  {q:"How many kcal has a Stück Käsekuchen (100g)?",a:321,unit:"kcal",hint:"Quark und Eier machen ihn caloriesreich.",emoji:"🎂"},
  {q:"How many grams Eiweiß has 100g schwasze Bohnen (gekocht)?",a:9,unit:"grams",hint:"Gute pflanzliche Proteinquelle.",emoji:"🫘"},
  {q:"How many liters coffee drinks a Norweger per year?",a:9.9,unit:"kg",hint:"Skandinavien führt den coffeekonsum worldwide.",emoji:"☕"},
  {q:"How many kcal has 100g Acai-Beeren?",a:534,unit:"kcal",hint:"Überraschend caloriesreich trotz 'Superfood'.",emoji:"🫐"},
  {q:"How many grams Fett has 100g Hüttenkäse?",a:4,unit:"grams",hint:"Sehr fettarm und proteinreich.",emoji:"🧀"},
  {q:"How many kcal has a Glas Buttermilch (200ml)?",a:66,unit:"kcal",hint:"caloriesarm und proteinreich.",emoji:"🥛"},
  {q:"How many grams sugar has a Flasche Gatorade (500ml)?",a:34,unit:"grams",hint:"Ähnlich wie a Dose Limo.",emoji:"🏃"},
  {q:"How many tons Avocado importiert Europa per year?",a:1000000,unit:"tons",hint:"1 Million tons – der Boom hält an.",emoji:"🥑"},
  {q:"How many kcal has 100g Joghurt with Früchten?",a:100,unit:"kcal",hint:"Fruchtjoghurt has mehr als Naturjoghurt.",emoji:"🫙"},
  {q:"How many grams Protein has 100g Edamame?",a:11,unit:"grams",hint:"Unreife Sojabohnen – ideal als Snack.",emoji:"🫘"},
];
