// 💰 MONEY & PRICES – English
export default [
  {q:"How much costse das teuerste je verkaufte painting (Salvator Mundi) in million Dollar?",a:450,unit:"million $",hint:"2017 at Chrisie's versteigert.",emoji:"🖼️"},
  {q:"How many billion Dollar is Jeff Bezos reich?",a:170,unit:"billion $",hint:"Schwankt – Stand 2024 ca. 170 Mrd.",emoji:"💰"},
  {q:"How much costs a Flasche Krug Grande Cuvée champagne?",a:200,unit:"Euro",hint:"Hochwertigster champagne im Standard-Sortiment.",emoji:"🥂"},
  {q:"How much costse das teuerste Haus the world (Villa Les Cèdres) in million Euro?",a:350,unit:"million €",hint:"Villa in Cap-Ferrat, Südfrankreich.",emoji:"🏰"},
  {q:"How many billion Dollar costs a modernes Flugzeugträger?",a:13,unit:"billion $",hint:"Der Ford-Class Träger der US Navy.",emoji:"🚢"},
  {q:"How much costs 1 grams Antimaterie in Dollar?",a:62500000000000,unit:"Dollar",hint:"62,5 Billionen Dollar pro grams.",emoji:"⚛️"},
  {q:"How much costse das teuerste Parfüm (Clive Chrisian No. 1) pro Flasche?",a:2150,unit:"Dollar",hint:"in einem goldenen Flacon.",emoji:"🌸"},
  {q:"How many billion Dollar Umsatz macht Apple pro Quartal?",a:90,unit:"billion $",hint:"Apple is das wertvollste Unternehmen the world.",emoji:"🍎"},
  {q:"How much costs a moonstein-grams der NASA in Dollar?",a:50800,unit:"Dollar/grams",hint:"Der teuerste Stoff on Earth to Antimaterie.",emoji:"🌙"},
  {q:"How many billion Dollar costs die Internationale Raumstation?",a:150,unit:"billion $",hint:"Das teuerste of people gebaute Objekt.",emoji:"🚀"},
  {q:"How much costs a Schweizer Luxusquartier (Gnägi Villa) pro Nacht?",a:50000,unit:"Dollar/Nacht",hint:"Exklusivste Hotels kosten a Vermögen.",emoji:"🏨"},
  {q:"How many billion Dollar gab die US-Regierung 2023 for Militär from?",a:858,unit:"billion $",hint:"Mehr als die nächsten 10 countries zusammen.",emoji:"⚔️"},
  {q:"How much costse die teuerste Uhr (Patek Philippe Grandmaster Chime)?",a:31000000,unit:"Dollar",hint:"2019 for 31 Mio. Dollar versteigert.",emoji:"⌚"},
  {q:"How much costs 1 kilograms weißer Trüffel?",a:10000,unit:"Euro/kg",hint:"can bis to 300.000€ pro kg kosten.",emoji:"🍄"},
  {q:"How many billion Dollar costs a Space Shuttle Flug?",a:1.5,unit:"billion $",hint:"Jeder Shuttle-Flug costse ~1,5 Mrd. Dollar.",emoji:"🚀"},
  {q:"How much costse das teuerste Buch (Codex Leicester of Leonardo da Vinci)?",a:30800000,unit:"Dollar",hint:"Gekauft of Bill Gates 1994.",emoji:"📖"},
  {q:"How many Billionen Dollar schuldet die USA?",a:34,unit:"Billionen Dollar",hint:"Stand 2024 – grows daily.",emoji:"💸"},
  {q:"How much costse das teuerste Foto (Rhein II of Andreas Gursky)?",a:4338500,unit:"Dollar",hint:"2011 versteigert.",emoji:"📷"},
  {q:"How many billion Dollar yearssumsatz macht McDonald's?",a:23,unit:"billion $",hint:"Hamburger are a billiongeschäft.",emoji:"🍔"},
  {q:"How much costs a kilograms Saffron (Safran) on dem Markt?",a:10000,unit:"Euro/kg",hint:"Das teuerste Gewürz the world.",emoji:"🌺"},
  {q:"How many million Dollar costs a Top-Formel-1-Fahrer per year?",a:50,unit:"million $",hint:"Hamilton earns ~50 Mio. – plus Sponsoren.",emoji:"🏎️"},
  {q:"How much costse die teuerste Handtasche (Hermès Birkin) je?",a:300000,unit:"Dollar",hint:"from Krokodilleder with Diamanten.",emoji:"👜"},
  {q:"How many billion Dollar is der globale Markt for Pornografie wert?",a:97,unit:"billion $",hint:"Einer the largestn Märkte im Internet.",emoji:"🔞"},
  {q:"How much costs a Übernachtung im teuersten Hotel (Empathy Suite, Las Vegas)?",a:100000,unit:"Dollar/Nacht",hint:"Im Palms Casino Resort.",emoji:"🏨"},
  {q:"How many billion Dollar wert is Elon Musks SpaceX?",a:180,unit:"billion $",hint:"Stand 2024 – private Raumfahrt boomt.",emoji:"🚀"},
  {q:"How much costs 1 mg Californium-252 in Dollar?",a:27000000,unit:"Dollar/mg",hint:"27 Mio. Dollar pro milligrams.",emoji:"☢️"},
  {q:"How many billion Dollar yearssgewinn macht Saudi Aramco?",a:161,unit:"billion $",hint:"Das profitabelste Unternehmen the world 2022.",emoji:"🛢️"},
  {q:"How much costse das teuerste Auto je verkauft (Mercedes-Benz 300 SLR)?",a:142000000,unit:"Euro",hint:"2022 for 142 million Euro versteigert.",emoji:"🚗"},
  {q:"How many billion Dollar is der Bitcoin-Markt wert?",a:1000,unit:"billion $",hint:"Schwankt stark – zeitweise over 1 Billion.",emoji:"₿"},
  {q:"How much costs a Kobe-Rind pro kg?",a:500,unit:"Euro/kg",hint:"Das teuerste Fleisch the world.",emoji:"🥩"},
  {q:"How many billion Dollar yearssbudget has die NASA?",a:25,unit:"billion $",hint:"Nur 0,3% des US-Budgets.",emoji:"🚀"},
  {q:"How much costs a Glas Whisky from der Macallan Fine & Rare Collection?",a:10000,unit:"Dollar",hint:"Pro Glas in Luxus-Bars.",emoji:"🥃"},
  {q:"How many Billionen Dollar is der globale Immobilienmarkt wert?",a:326,unit:"Billionen Dollar",hint:"the largest Anlagemarkt the world.",emoji:"🏠"},
  {q:"How much costs der teuerste champagne (Goût de Diamants)?",a:1200000,unit:"Euro",hint:"with Diamanten verziert.",emoji:"🥂"},
  {q:"How many billion Dollar earns Taylor Swift pro Tour?",a:1,unit:"billion $",hint:"Die Eras Tour 2023-2024 – erste billion-Tour.",emoji:"🎤"},
  {q:"How much costs 1 grams Meissen-Porzellan (als Kunstwerk)?",a:1000,unit:"Euro",hint:"Echtes Meissen is extrem wertvoll.",emoji:"🏺"},
  {q:"How much costse das teuerste Diamant-Ehering (Pink Star)?",a:71200000,unit:"Dollar",hint:"2017 for 71,2 Mio. Dollar versteigert.",emoji:"💍"},
  {q:"How many billion Dollar Steuern hinterziehen Deutsche per year?",a:30,unit:"billion €",hint:"Schätzungen liegen at 30 billion Euro.",emoji:"💸"},
  {q:"How much costs a Flug ins All with Virgin Galactic?",a:450000,unit:"Dollar",hint:"for einen Suborbitalflug.",emoji:"🚀"},
  {q:"How many billion Dollar is der globale coffeehandel wert?",a:100,unit:"billion $",hint:"coffee is eines the largestn Handelsgüter.",emoji:"☕"},
  {q:"How much costs 1 Bitcoin on seinem Allzeithoch in Dollar?",a:73000,unit:"Dollar",hint:"Im März 2024 erreichte Bitcoin ~73.000 Dollar.",emoji:"₿"},
  {q:"How many billion Dollar has wasren Buffett gespendet?",a:50,unit:"billion $",hint:"Der meisgebende Milliardär der Geschichte.",emoji:"💝"},
  {q:"How much costs a kilograms Kaviar (Almas)?",a:34500,unit:"Euro/kg",hint:"Weißer Kaviar of Albino-Stören.",emoji:"🐟"},
  {q:"How many billion Dollar yearssumsatz macht LVMH (Luxuskonzern)?",a:86,unit:"billion €",hint:"Louis Vuitton, Moët, Hennessy und viele mehr.",emoji:"👜"},
  {q:"How much costs a Top-Anwhalet in New York per hour?",a:2000,unit:"Dollar/Stunde",hint:"Hochkarätige Anwälte verlangen enorme Honorare.",emoji:"⚖️"},
  {q:"How many billion Dollar is der globale Glücksspielmarkt wert?",a:500,unit:"billion $",hint:"Casinos, Sportwetten und Online-Gambling.",emoji:"🎰"},
  {q:"How much costs a Luxus-Penthouse in Monaco pro m²?",a:100000,unit:"Euro/m²",hint:"Teuerster Immobilienmarkt the world.",emoji:"🏠"},
  {q:"How many billion Dollar geben Amerikaner per year for Haubulle from?",a:150,unit:"billion $",hint:"billion for doge, catn und Co.",emoji:"🐕"},
  {q:"How much costs a Jahr Harvard-Studium (alles inbegriffen)?",a:80000,unit:"Dollar/Jahr",hint:"Wohnen, Essen, Studiengebühren.",emoji:"🎓"},
  {q:"How many billion Dollar costs a Kernkraftwerk?",a:12,unit:"billion $",hint:"Die neuesten Reaktoren kosten bis to 30 Mrd.",emoji:"⚡"},
  {q:"How much costs a Kilo Gold aktuell in Euro?",a:60000,unit:"Euro/kg",hint:"Gold costs ca. 60.000€/kg – Stand 2024.",emoji:"🪙"},
  {q:"How many billion Dollar yearssumsatz has Google?",a:280,unit:"billion $",hint:"Haupteinnahme: Werbung.",emoji:"🔍"},
  {q:"How much costs der teuerste Cognac (Hennessy Richard)?",a:12000,unit:"Dollar",hint:"Pro Flasche – handgefertigt.",emoji:"🥃"},
  {q:"How many billion Dollar costs es a Olympisches Spiel auszurichten?",a:15,unit:"billion $",hint:"London 2012 costse 15 Mrd. Pfund.",emoji:"🏅"},
  {q:"How much costs a kilograms Diamanten (Rohdiamant)?",a:55000,unit:"Dollar/Karat",hint:"Qualitätsdiamanten können viel mehr kosten.",emoji:"💎"},
  {q:"How many billion Dollar wert is der Tabakmarkt global?",a:900,unit:"billion $",hint:"Trotz Rückgang – immer noch riesig.",emoji:"🚬"},
  {q:"How much costs a privater Hubschrauber (Airbus H145)?",a:7000000,unit:"Dollar",hint:"Ein Standard-Luxushubschrauber.",emoji:"🚁"},
  {q:"How many billion Dollar earns FIFA pro WM?",a:5,unit:"billion $",hint:"Die WM 2022 in Katar generierte ~7,5 Mrd.",emoji:"⚽"},
  {q:"How much costs das teuerste Hotelzimmer pro Nacht in Dubai?",a:85000,unit:"Dollar",hint:"Royal Penthouse im Burj Al Arab.",emoji:"🏨"},
  {q:"How many billion Dollar wert is der globale Pharmasektor?",a:1600,unit:"billion $",hint:"Ein billionenschwerer Markt.",emoji:"💊"},
  {q:"How much costs 1 kg Heroin on dem Schwaszmarkt?",a:50000,unit:"Dollar/kg",hint:"Straßenpreise variieren stark.",emoji:"💊"},
  {q:"How many billion Dollar geben Amis per year for Fast Food from?",a:280,unit:"billion $",hint:"Fast Food is Amerikas Lieblingsessen.",emoji:"🍔"},
  {q:"How much costs a private Insel in der Karibik (Einstieg)?",a:5000000,unit:"Dollar",hint:"Kleine Inseln ab 5 Mio. Dollar.",emoji:"🏝️"},
  {q:"How many billion Dollar wert is der globale Waffenmarkt?",a:600,unit:"billion $",hint:"Legaler Waffenhandel worldwide.",emoji:"⚔️"},
  {q:"How much costs a Luxusjet (Bombardier Global 7500)?",a:75000000,unit:"Dollar",hint:"the largest Privatjet the world.",emoji:"✈️"},
  {q:"How many billion Euro has Deutschland 2023 in Rüstung invebullt?",a:52,unit:"billion €",hint:"on dem Weg zum 2%-Ziel der NATO.",emoji:"⚔️"},
  {q:"How much costs 1 Sekunde Werbung beim Super Bowl?",a:200000,unit:"Dollar",hint:"30 seconds = 6 Mio. Dollar.",emoji:"📺"},
  {q:"How many billion Dollar is TikTok (ByteDance) wert?",a:250,unit:"billion $",hint:"Stand 2024.",emoji:"📱"},
  {q:"How much costs a kilograms Seltener Erde (Scandium)?",a:15000,unit:"Dollar/kg",hint:"Seltene Erden are der Stoff der modernen Welt.",emoji:"⚗️"},
  {q:"How many billion Dollar yearssgewinne macht Apple?",a:100,unit:"billion $",hint:"Apple is unfassbar profitabel.",emoji:"🍎"},
  {q:"How much costs a Hermes Birkin Tasche (Sonderanfertigung)?",a:500000,unit:"Dollar",hint:"with exotischen Materialien.",emoji:"👜"},
  {q:"How many billion Dollar has Elon Musk for Twitter/X bezahlt?",a:44,unit:"billion $",hint:"Im Oktober 2022.",emoji:"𝕏"},
  {q:"How much costs a kilograms Plutonium?",a:6600000,unit:"Dollar",hint:"Das teuerste legale Material on Erden.",emoji:"☢️"},
  {q:"How many billion Dollar wert is Crisiano Ronaldos Marke?",a:1,unit:"billion $",hint:"CR7 is Milliardär through Marke und Investments.",emoji:"⚽"},
  {q:"How much costs a Kunstwerk of Banksy im Durchschnitt?",a:5000000,unit:"Dollar",hint:"Game Changer was for 16,8 Mio. verkauft.",emoji:"🎨"},
  {q:"How many billion Dollar costs der Mars-Kolonisierungsplan of SpaceX?",a:100,unit:"billion $",hint:"Musk schätzte ursprünglich 100 Mrd.",emoji:"🔴"},
  {q:"How much costs a Megajacht (100m+) per year an Unterhalt?",a:10000000,unit:"Dollar/Jahr",hint:"10% des Kaufpreises annually for Unterhalt.",emoji:"⛵"},
  {q:"How many billion Dollar yearssumsatz has die Pornoindustrie?",a:97,unit:"billion $",hint:"Ein gigantischer globaler Markt.",emoji:"🔞"},
  {q:"How much costs a Tasse Kopi Luwak (teuerster coffee)?",a:100,unit:"Dollar/Tasse",hint:"coffee from dem Kot der Zibetcat.",emoji:"☕"},
  {q:"How many billion Dollar wert is der globale E-Sport-Markt?",a:2,unit:"billion $",hint:"Professionelles Spielen grows rasant.",emoji:"🎮"},
  {q:"How much costs a kilograms Quecksilber on dem freien Markt?",a:50,unit:"Dollar",hint:"Relativ günstig – trotz Giftigkeit.",emoji:"🌡️"},
  {q:"How many billion Euro has Deutschland in die Flüchtlingskrise invebullt?",a:20,unit:"Mrd. Euro/Jahr",hint:"2015-2022 in total over 100 Mrd.",emoji:"🏠"},
  {q:"How much costs a Top-Fußballplayers-Transfer (Neymar)?",a:222000000,unit:"Euro",hint:"Teuerster Transfer aller Zeiten 2017.",emoji:"⚽"},
  {q:"How many billion Dollar wert is der globale Kosmetikmarkt?",a:500,unit:"billion $",hint:"Schönheit is a riesiges Geschäft.",emoji:"💄"},
  {q:"How much costs 1 watts Solarenergie zur Installation?",a:0.3,unit:"Dollar/watts",hint:"Drastisch gesunken – of 80$/W in 1970.",emoji:"☀️"},
  {q:"How many billion Dollar costs a Atomkraftwerk (Hinkley Point C)?",a:33,unit:"Mrd. Pfund",hint:"Das teuerste Bauwerk in UK.",emoji:"⚡"},
  {q:"How much costs a Luxusuhr of Richard Mille?",a:1000000,unit:"Dollar",hint:"Die teuersten Uhren the world.",emoji:"⌚"},
  {q:"How many billion Dollar yearssumsatz has Nestlé?",a:95,unit:"billion $",hint:"Größter Lebensmittelkonzern the world.",emoji:"🍫"},
  {q:"How much costs a kilograms Kokain in Europa?",a:35000,unit:"Euro/kg",hint:"Straßenpreise – stark variierend.",emoji:"💊"},
  {q:"How many billion Dollar wert is der globale alcohol-Markt?",a:1600,unit:"billion $",hint:"beer, wine und Spirituosen zusammen.",emoji:"🍷"},
  {q:"How much costs a privater Raketenstarter at SpaceX (Falcon 9)?",a:67000000,unit:"Dollar",hint:"67 Mio. pro Falcon-9-Start.",emoji:"🚀"},
  {q:"How many billion Dollar earnse Fortnite in seinem ersten Jahr?",a:2.4,unit:"billion $",hint:"Epic Games Blockbuster-Spiel.",emoji:"🎮"},
  {q:"How much costs der teuerste Sneaker je versteigert?",a:1800000,unit:"Dollar",hint:"Nike Moon Shoe of 1972.",emoji:"👟"},
  {q:"How many billion Dollar wert is die gesamte Krypto-Marktkapitalisierung?",a:2000,unit:"billion $",hint:"Stand Anfang 2024.",emoji:"₿"},
  {q:"How much costs a liters blood im Krankenhaus in den USA?",a:1000,unit:"Dollar",hint:"Gespendetes blood is teuer verkauft.",emoji:"🩸"},
  {q:"How many billion Dollar yearssumsatz has Amazon?",a:514,unit:"billion $",hint:"Größter Onlinehändler the world.",emoji:"📦"},
  {q:"How much costs a Quadratmeters in Hongkong (teuerste Gegend)?",a:100000,unit:"Dollar/m²",hint:"Hongkong is a der teuersten Städte.",emoji:"🏙️"},
  {q:"How many billion Dollar costs a neues Flugzeug (Airbus A380)?",a:445,unit:"million $",hint:"the largest Passagierflugzeug.",emoji:"✈️"},
  {q:"How much costs a Flasche Petrus (Bordeaux, 1947)?",a:75000,unit:"Euro",hint:"Einige Flaschen wasn for over 100.000€ verkauft.",emoji:"🍷"},
  {q:"How many billion Dollar wert is der globale Markt for Schusswaffen?",a:28,unit:"billion $",hint:"Legaler Waffenmarkt.",emoji:"🔫"},
  {q:"How much costs 1 km Autobahn to bauen in Germany?",a:25000000,unit:"Euro/km",hint:"25 Mio. Euro pro kilometerss.",emoji:"🛣️"},
  {q:"How many billion Euro costs der Wiederaufbau der Notre-Dame?",a:700,unit:"million €",hint:"over 700 Mio. Euro for die Renovierung.",emoji:"⛪"},
  {q:"How much costs a Quadratmeters in Paris (Innenstadt)?",a:12000,unit:"Euro/m²",hint:"Paris is a der teuersten Städte Europas.",emoji:"🗼"},
  {q:"How many billion Dollar is Tesla wert?",a:600,unit:"billion $",hint:"Schwankt stark – was times over 1 Billion.",emoji:"🚗"},
  {q:"How much costs a Jahr in der teuersten Privatschule the world?",a:120000,unit:"Schweizer Franken",hint:"Institut Le Rosey in der Schweiz.",emoji:"🎓"},
  {q:"How many billion Dollar wert is der globale Musikmarkt?",a:26,unit:"billion $",hint:"Streaming dominiert.",emoji:"🎵"},
  {q:"How much costs a kilograms Vanille?",a:600,unit:"Dollar/kg",hint:"Einer der teuersten Gewürze to Safran.",emoji:"🌿"},
  {q:"How many billion Dollar wert is Goldman Sachs?",a:120,unit:"billion $",hint:"Eine der mächtigsten Investmentbanken.",emoji:"🏦"},
  {q:"How much costs a Penthouse in New York City (on average)?",a:20000000,unit:"Dollar",hint:"Luxuspenthouses in Manhastan.",emoji:"🏙️"},
  {q:"How many billion Dollar are die Welt per year for Rüstung from?",a:2200,unit:"billion $",hint:"2,2 Billionen Dollar annually.",emoji:"⚔️"},
  {q:"How much costs 1 km neues U-Bahn-Netz in London?",a:1000000000,unit:"Dollar/km",hint:"London has die teuersten U-Bahnbauprojekte.",emoji:"🚇"},
  {q:"How many billion Dollar is der globale Markt for Videospiele wert?",a:200,unit:"billion $",hint:"Größer als Film und Musik zusammen.",emoji:"🎮"},
  {q:"How much costs a yearssgehalt eines Hedge-Fonds-Managers?",a:1000000000,unit:"Dollar",hint:"Spitzenmanager verdienen billion.",emoji:"💰"},
  {q:"How many billion Dollar is der globale Tourismus-Markt wert?",a:9500,unit:"billion $",hint:"9,5 Billionen Dollar – einer the largestn Sektoren.",emoji:"✈️"},
  {q:"How much costs das Anlegen eines stars to dir?",a:50,unit:"Dollar",hint:"Internationales starregiser – eigentlich rechtlich nicht bindend.",emoji:"⭐"},
  {q:"How many billion Dollar costs a Wolkenkratzer (Burj Khalifa)?",a:1.5,unit:"billion $",hint:"Der höchste Turm the world.",emoji:"🏙️"},
  {q:"How much costs 1 Kilo Seltener Erden-Neodym?",a:175,unit:"Dollar/kg",hint:"Essenziell for Elektromotoren.",emoji:"⚗️"},
  {q:"How many billion Dollar wert is der FC Barcelona?",a:5,unit:"billion $",hint:"Einer der wertvollsten Sportklubs.",emoji:"⚽"},
  {q:"How much costs a privater DNA-Test at 23andMe?",a:200,unit:"Dollar",hint:"Plus optionale Abonnements.",emoji:"🧬"},
  {q:"How many billion Dollar yearssumsatz has die Filmindustrie (Hollywood)?",a:50,unit:"billion $",hint:"Box Office plus Streaming.",emoji:"🎬"},
  {q:"How much costs a meters Eintrittskarte for a Taylor-Swift-Konzert (VIP)?",a:3000,unit:"Dollar",hint:"VIP-Pakete for die Eras Tour.",emoji:"🎤"},
  {q:"How many billion Dollar wert is die Marke Nike?",a:50,unit:"billion $",hint:"Just Do It – einer der stärksten Markennamen.",emoji:"👟"},
  {q:"How much costs a kilograms weißer Trüffel on Auktionen?",a:300000,unit:"Euro/kg",hint:"Rekord-Trüffel are for dogertthousande verkauft.",emoji:"🍄"},
  {q:"How many billion Dollar wert is der globale Schönheitsmarkt?",a:800,unit:"billion $",hint:"grows stark through Influencer-Kultur.",emoji:"💄"},
  {q:"How much costs a Concorde-Ticket (als sie noch flog)?",a:8000,unit:"Dollar",hint:"Ein Transatlantikflug for 8000 Dollar.",emoji:"✈️"},
  {q:"How many billion Dollar has Elon Musk in a year losten (2022)?",a:200,unit:"billion $",hint:"Größter Vermögensverlust in der Geschichte.",emoji:"📉"},
  {q:"How much costs a Quadratmeters on der teuersten Straße the world (Hong Kong)?",a:236000,unit:"Dollar/m²",hint:"Causeway Bay, Hong Kong.",emoji:"🏙️"},
  {q:"How many billion Dollar wert is der globale Sportmarkt?",a:500,unit:"billion $",hint:"Alle Sportveranstaltungen, Rechte und Merchandise.",emoji:"⚽"},
  {q:"How much costs 1 Minute Werbung on dem Super Bowl?",a:10000000,unit:"Dollar",hint:"over 10 Mio. Dollar for 30 seconds.",emoji:"📺"},
  {q:"How many billion Dollar costs das amerikanische Bildungssystem per year?",a:700,unit:"billion $",hint:"of Kindergspecies bis Uni.",emoji:"🎓"},
  {q:"How much costs a liters Parfüm Chanel No. 5?",a:3000,unit:"Euro",hint:"Eines der ikonischsten Parfüms.",emoji:"🌸"},
  {q:"How many billion Dollar has Saudi-Arabien in Soccer-Stars invebullt?",a:6,unit:"billion $",hint:"Die Saudi Pro League wirbt Weltstars ab.",emoji:"⚽"},
  {q:"How much costs a kilograms Madame Jeanette-Chili in Europa?",a:50,unit:"Euro/kg",hint:"Seltene scharfe Chili from Surinam.",emoji:"🌶️"},
  {q:"How many billion Dollar wert is der globale Markt for Streaming?",a:100,unit:"billion $",hint:"Netflix, Spotify, Amazon und alle anderen.",emoji:"📺"},
  {q:"How much costs a Mitgliedschaft im Augusta National Golf Club?",a:300000,unit:"Dollar",hint:"Der exklusivste Golfklub the world.",emoji:"⛳"},
  {q:"How many billion Dollar verliert die Weltwirtschaft through Korruption?",a:2600,unit:"billion $",hint:"2,6 Billionen Dollar per year laut UN.",emoji:"💸"},
  {q:"How much costs a kg Ambergris (whalerat) on dem Schwaszmarkt?",a:50000,unit:"Dollar",hint:"Verwendet in Luxusparfüms.",emoji:"🐋"},
  {q:"How many billion Dollar is der globale Fast-Fashion-Markt wert?",a:100,unit:"billion $",hint:"Zara, H&M und Shein domikidneyn.",emoji:"👗"},
  {q:"How much costs a Privatflug London-New York?",a:150000,unit:"Dollar",hint:"Im Luxus-Jet.",emoji:"✈️"},
  {q:"How many billion Dollar wert is der globale Lebensmittelmarkt?",a:8000,unit:"billion $",hint:"8 Billionen Dollar – täglicher Bedarf.",emoji:"🍎"},
  {q:"How much costs a meters Silizium-Chip-Produktion (TSMC 2nm)?",a:20000,unit:"Dollar/Wafer",hint:"Die teuersten Chips the world.",emoji:"💻"},
  {q:"How many billion Dollar wert is der globale Online-Shopping-Markt?",a:5000,unit:"billion $",hint:"5 Billionen Dollar – grows weiter.",emoji:"📦"},
  {q:"How much costs 1 liters menschliches Blutplasma?",a:500,unit:"Dollar",hint:"Blutplasma is a wertvolles Medizinprodukt.",emoji:"🩸"},
  {q:"How many billion Dollar wert is Spotify?",a:40,unit:"billion $",hint:"Stand 2024.",emoji:"🎵"},
  {q:"How much costs a kilograms Carbon-Fiber?",a:100,unit:"Dollar/kg",hint:"for Formel-1 und Luft-/Raumfahrt essenziell.",emoji:"🏎️"},
  {q:"How many billion Dollar has Kylie Jenner earns als jüngste Selfmade-Milliardärin?",a:1,unit:"billion $",hint:"through ihre Kosmetikmarke.",emoji:"💄"},
  {q:"How much costs a Quadratmeters in München (Maxvorstadt)?",a:15000,unit:"Euro/m²",hint:"Einer der teuersten Immobilienmärkte Deutschlands.",emoji:"🏠"},
  {q:"How many billion Dollar costs es die Klimakrise to lösen (annually)?",a:4000,unit:"billion $",hint:"Schätzungen des IPCC.",emoji:"🌍"},
  {q:"How much costs der teuerste Tee (Da Hong Pao)?",a:1000000,unit:"Dollar/kg",hint:"1 Mio. Dollar pro kg – kaum noch erhältlich.",emoji:"🍵"},
  {q:"How many billion Dollar wert is der globale cannabismarkt?",a:50,unit:"billion $",hint:"Legal und illegal zusammen.",emoji:"🌿"},
  {q:"How much costs a kilograms roher Saphir?",a:30000,unit:"Dollar/Karat",hint:"Hochwertige Saphire kosten 30.000+/Karat.",emoji:"💎"},
  {q:"How many billion Dollar annually macht die CIA with verdeckten Operationen?",a:90,unit:"billion $",hint:"Das geheime US-Geheimdienstbudget.",emoji:"🕵️"},
  {q:"How much costs a Kilo Seltenes Element Rhenium?",a:5000,unit:"Dollar/kg",hint:"Eines der seltensten stabilen elements.",emoji:"⚗️"},
  {q:"How many billion Dollar wert is der globale Markt for KI?",a:200,unit:"billion $",hint:"grows exponentiell.",emoji:"🤖"},
  {q:"How much costs a Ferrari F40 heute?",a:1500000,unit:"Euro",hint:"Legendärer Supersportwagen of 1987.",emoji:"🚗"},
  {q:"How many billion Dollar wert is der globale Cloud-Computing-Markt?",a:600,unit:"billion $",hint:"AWS, Azure und Google domikidneyn.",emoji:"☁️"},
  {q:"How much costs 1 meters Unterwasserkabel (Internet)?",a:35000,unit:"Dollar/km",hint:"Unterseekabel verbinden die Kontinduck.",emoji:"🌊"},
  {q:"How many billion Dollar geben Reiche people for Kunst from?",a:68,unit:"billion $",hint:"Der globale Kunstmarkt 2022.",emoji:"🎨"},
  {q:"How much costs der teuerste wine je (Romanée-Conti 1945)?",a:558000,unit:"Dollar",hint:"Pro Flasche – 2018 versteigert.",emoji:"🍷"},
  {q:"How many billion Dollar wert is der globale Markt for Cybersecurity?",a:200,unit:"billion $",hint:"grows with jedem Angriff.",emoji:"🔒"},
  {q:"How much costs a Penthouse in Dubai (Palm Jumeirah)?",a:30000000,unit:"Dollar",hint:"Luxuriöse Residenzen on der Palmeninsel.",emoji:"🌴"},
  {q:"How many billion Dollar wert is die Sportartikelmesse (Adidas+Nike)?",a:100,unit:"billion $",hint:"Beide zusammen.",emoji:"👟"},
  {q:"How much costs a Stunde with einem Top-Management-Consultant (McKinsey)?",a:1200,unit:"Dollar",hint:"for Senior Partner.",emoji:"💼"},
  {q:"How many billion Dollar wert is der globale Pharmamarkt?",a:1600,unit:"billion $",hint:"Medikamduck are a riesiger Markt.",emoji:"💊"},
  {q:"How much costs a yearssmitgliedschaft at Amazon Prime?",a:139,unit:"Dollar",hint:"in den USA – unterschiedlich je country.",emoji:"📦"},
  {q:"How many billion Dollar wert is der globale Markt for Elektroautos?",a:400,unit:"billion $",hint:"grows schnell – Tesla führt.",emoji:"🚗"},
  {q:"How many billion Dollar yearssumsatz has Volkswagen?",a:293,unit:"billion €",hint:"Größter Automobilkonzern Europas.",emoji:"🚗"},
  {q:"How much costs a nortimeses heart-Transplantation in den USA?",a:1000000,unit:"Dollar",hint:"Inklusive Nachsorge.",emoji:"❤️"},
  {q:"How many billion Dollar wert is TikTok-Eigentümer ByteDance?",a:250,unit:"billion $",hint:"Wertvollstes nicht-börsennotiertes Unternehmen.",emoji:"📱"},
  {q:"How much costs a kilograms Lithium on dem Weltmarkt?",a:30,unit:"Dollar/kg",hint:"Essenziell for Batterien.",emoji:"⚡"},
  {q:"How many billion Dollar wert is der globale Suchmaschinenmarkt?",a:300,unit:"billion $",hint:"Google dominiert with over 90%.",emoji:"🔍"},
  {q:"How much costs a Abonnement of Netflix per month (Standard)?",a:15,unit:"Dollar/Monat",hint:"in den USA – unterschiedlich je country.",emoji:"📺"},
  {q:"How many billion Dollar wert is der globale Markt for Elektronikmüll?",a:60,unit:"billion $",hint:"Wertvolle Metalle landen im Müll.",emoji:"♻️"},
  {q:"How much costs 1 grams Helium-3 (moonressource)?",a:14000,unit:"Dollar/grams",hint:"Potenzielle Fusionsenergiequelle.",emoji:"🌙"},
  {q:"How many billion Dollar wert is der globale Markt for Düngemittel?",a:200,unit:"billion $",hint:"Essenziell for die Nahrungsmittelproduktion.",emoji:"🌾"},
  {q:"How much costs a Stunde with einem Top-Strafrechtler in Germany?",a:600,unit:"Euro/Stunde",hint:"Top-Anwälte verlangen enorme hourssätze.",emoji:"⚖️"},
  {q:"How many billion Dollar wert is der globale Markt for Halbleiter?",a:600,unit:"billion $",hint:"Chips regieren die Welt.",emoji:"💻"},
  {q:"How much costs a Kilo Hafnium (seltenes Metall)?",a:900,unit:"Dollar/kg",hint:"Verwendet in Atomreaktoren.",emoji:"⚗️"},
  {q:"How many billion Dollar has der erste NFT (Beeple) eingebracht?",a:69,unit:"million $",hint:"'Everydays: The First 5000 Days' – 69 Mio. 2021.",emoji:"🖼️"},
  {q:"How much costs a Kilo weißes Trüffelöl?",a:5000,unit:"Euro/liters",hint:"Das beste Trüffelöl is extrem teuer.",emoji:"🍄"},
  {q:"How many billion Dollar is Airbnb wert?",a:90,unit:"billion $",hint:"Stand 2024.",emoji:"🏠"},
  {q:"How much costs a lungnatmung in einem US-Krankenhaus (Beatmung, Tag)?",a:10000,unit:"Dollar/Tag",hint:"Intensivstation in den USA.",emoji:"🏥"},
  {q:"How many billion Dollar wert is der globale Markt for Robotik?",a:100,unit:"billion $",hint:"Industrieroboter und Service-Roboter.",emoji:"🤖"},
  {q:"How much costs a kilograms Gallium?",a:250,unit:"Dollar/kg",hint:"Essenziell for Halbleiter.",emoji:"⚗️"},
  {q:"How many billion Dollar wert is Ferrari als Unternehmen?",a:60,unit:"billion $",hint:"Ferrari is mehr Luxusmarke als Autohersteller.",emoji:"🚗"},
  {q:"How much costs 1 liters Kerosin for Privatjets?",a:2,unit:"Dollar/liters",hint:"Steuerbegünstigt – weniger als Benzin.",emoji:"✈️"},
  {q:"How many billion Dollar wert is der globale Diamantmarkt?",a:80,unit:"billion $",hint:"Lab-Diamanten bedrohen den Markt.",emoji:"💎"},
  {q:"How much costs a Durchschnittskauf im Hermès Paris pro Einkauf?",a:5000,unit:"Euro",hint:"Hermès-Kunden geben viel from.",emoji:"👜"},
  {q:"How many billion Dollar wert is Airbus?",a:100,unit:"billion €",hint:"the largest Flugzeugbauer Europas.",emoji:"✈️"},
  {q:"How much costs a Tesla Model S?",a:100000,unit:"Dollar",hint:"Das Flaggschiff-Modell of Tesla.",emoji:"🚗"},
  {q:"How many billion Dollar wert is der globale Markt for nachhaltige Investments?",a:35000,unit:"billion $",hint:"ESG-Investments boomen.",emoji:"🌿"},
  {q:"How much costs a km² Agrarland in Bayern?",a:80000,unit:"Euro/Hektar",hint:"Bayern has die teuersten Agrarpreise Deutschlands.",emoji:"🌾"},
  {q:"How many billion Dollar wert is der globale Online-Gaming-Markt?",a:250,unit:"billion $",hint:"Mobile Gaming is the largest Teil.",emoji:"🎮"},
  {q:"How many billion Dollar wert is IKEA?",a:58,unit:"billion $",hint:"Privat geführt – through a Stiftung.",emoji:"🛋️"},
  {q:"How many billion Dollar yearssumsatz macht H&M?",a:22,unit:"billion $",hint:"Zweitgrößte Modekette the world.",emoji:"👗"},
  {q:"How many billion Dollar wert is WhassApp (beim Verkauf an Facebook)?",a:19,unit:"billion $",hint:"Gekauft 2014 for datimess schwindelerregende Summe.",emoji:"💬"},
  {q:"How many billion Euro wert is BMW?",a:70,unit:"billion €",hint:"Eines der wertvollsten deutschen Unternehmen.",emoji:"🚗"},
  {q:"How many billion Dollar costs a Satellitenmine?",a:300,unit:"million $",hint:"million for einen militärischen Satelliten.",emoji:"🛰️"},
  {q:"How many billion Dollar wert is Red Bull?",a:20,unit:"billion $",hint:"from Österreich zum Weltkonzern.",emoji:"🐂"},
  {q:"How many billion Dollar has die Corona-Impfkampagne die Welt gecosts?",a:15,unit:"billion $",hint:"for die Entwicklung der mRNA-Impfstoffe.",emoji:"💉"},
  {q:"How many billion Euro wert is Adidas?",a:35,unit:"billion €",hint:"Der Streifen is a der wertvollsten Marken.",emoji:"👟"},
  {q:"How many billion Dollar has Bill Gates gespendet?",a:59,unit:"billion $",hint:"Die Gates Foundation is größte private Stiftung.",emoji:"💝"},
  {q:"How many billion Dollar wert is der globale Markt for Elektrizität?",a:3000,unit:"billion $",hint:"3 Billionen Dollar – essenziell for alles.",emoji:"⚡"},
  {q:"How many billion Dollar Marktkapitalisierung has Microsoft?",a:3200,unit:"billion $",hint:"Stand 2024 – zeitweise das wertvollste Unternehmen.",emoji:"💻"},
  {q:"How many billion Euro costs Oktoberfest die Münchner Wirtschaft?",a:1.3,unit:"billion €",hint:"over a Milliarde Euro Wirtschaftsleisung.",emoji:"🍺"},
  {q:"How many billion Dollar wert is der globale Haushaltsgeräte-Markt?",a:700,unit:"billion $",hint:"Waschmaschinen, Kühlschränke und Co.",emoji:"🏠"},
  {q:"How many billion Euro Schaden entsteht through Cyberkriminalität in Germany?",a:200,unit:"billion €",hint:"Jährlich laut Bitkom.",emoji:"🔒"},
  {q:"How many billion Dollar costs 1 km Autobahn in den USA?",a:10,unit:"Mio. Dollar/km",hint:"in dicht bebauten Gebieten deutlich mehr.",emoji:"🛣️"},
  {q:"How many billion Dollar wert is der globale Markt for Haubullprodukte?",a:260,unit:"billion $",hint:"grows stark – people lieben ihre Haubulle.",emoji:"🐕"},
  {q:"How many billion Euro wert is SAP?",a:200,unit:"billion €",hint:"Deutschlands wertvollstes Tech-Unternehmen.",emoji:"💻"},
  {q:"How many billion Dollar costs die Herstellung eines Smartphones?",a:350,unit:"million $",hint:"Dollar Materialkosten for a iPhone.",emoji:"📱"},
  {q:"How many billion Dollar has Amazon for Whole Foods bezahlt?",a:13.7,unit:"billion $",hint:"2017 – Amazons Einstieg in den Lebensmittelhandel.",emoji:"🛒"},
  {q:"How many billion Dollar yearssumsatz has Coca-Cola?",a:46,unit:"billion $",hint:"Eines der becantesten Marken worldwide.",emoji:"🥤"},
  {q:"How many billion Dollar wert is der globale Sportkleidungsmarkt?",a:200,unit:"billion $",hint:"Athleisure-Trend treibt das Wachstum.",emoji:"👕"},
  {q:"How many billion Euro costs die Energiewende Deutschland bis 2035?",a:500,unit:"billion €",hint:"Schätzungen variieren erheblich.",emoji:"⚡"},
  {q:"How many billion Dollar wert is der globale Markt for Bücher?",a:138,unit:"billion $",hint:"Print und E-Books zusammen.",emoji:"📚"},
  {q:"How many billion Dollar has Google for YouTube bezahlt?",a:1.65,unit:"billion $",hint:"2006 – im Rückblick das Schnäppchen des Jahrdogerts.",emoji:"▶️"},
  {q:"How many billion Dollar wert is der globale Markt for Süßigkeiten?",a:200,unit:"billion $",hint:"Schokolade, Kaugummi und Co.",emoji:"🍫"},
  {q:"How many billion Euro has die Covid-19-Krise Deutschland gecosts?",a:300,unit:"billion €",hint:"Hilfspaket plus wirtschaftliche Einbußen.",emoji:"😷"},
  {q:"How many billion Dollar wert is Instacart?",a:10,unit:"billion $",hint:"Lebensmittellieferservice from San Francisco.",emoji:"🛒"},
  {q:"How many billion Dollar yearssgewinn macht Saudi Aramco?",a:161,unit:"billion $",hint:"Das profitabelste Unternehmen the world.",emoji:"🛢️"},
  {q:"How many billion Euro wert is Bosch?",a:93,unit:"billion €",hint:"Größter Automobilzulieferer the world.",emoji:"🔧"},
  {q:"How many billion Dollar wert is der globale Markt for Brillen?",a:150,unit:"billion $",hint:"Luxottica dominiert den Markt.",emoji:"👓"},
  {q:"How many billion Dollar has Facebook (Meta) for Instagram bezahlt?",a:1,unit:"billion $",hint:"2012 – heute is Instagram billion wert.",emoji:"📸"},
  {q:"How many billion Euro Schulden has die Deutsche Bahn?",a:30,unit:"billion €",hint:"Eines der am stärksten verschuldeten Staatsunternehmen.",emoji:"🚂"},
  {q:"How many billion Dollar wert is der globale Markt for Kreuzfahrten?",a:150,unit:"billion $",hint:"grows trotz Pandemie-Einbruch wieder.",emoji:"🚢"},
  {q:"How many billion Dollar wert is der globale Markt for Hautpflege?",a:180,unit:"billion $",hint:"Teil des riesigen Kosmetik-Markts.",emoji:"💆"},
  {q:"How many billion Dollar has Apple for Shazam bezahlt?",a:400,unit:"million $",hint:"million Dollar for die Musik-App.",emoji:"🎵"},
  {q:"How many billion Euro yearssumsatz has Deutsche Telekom?",a:114,unit:"billion €",hint:"Größter Telekomkonzern Europas.",emoji:"📱"},
  {q:"How many billion Dollar wert is der globale Markt for Dating-Apps?",a:9,unit:"billion $",hint:"Tinder, Bumble und Co.",emoji:"❤️"},
  {q:"How many billion Dollar wert is der globale Markt for Fitness?",a:100,unit:"billion $",hint:"Fitnessstudios, Apps und Equipment.",emoji:"💪"},
  {q:"How many billion Dollar has Microsoft for LinkedIn bezahlt?",a:26.2,unit:"billion $",hint:"2016 – das teuerste Social-Media-Acquisition.",emoji:"💼"},
  {q:"How many billion Dollar wert is der globale Markt for Schmerzmittel?",a:35,unit:"billion $",hint:"Ibuprofen, Aspirin und Co.",emoji:"💊"},
  {q:"How many billion Dollar costs a Flugzeugträger der USA?",a:13,unit:"billion $",hint:"Der Gerald R. Ford costs 13,3 billion.",emoji:"🚢"},
  {q:"How many billion Euro wert is BASF?",a:40,unit:"billion €",hint:"Größter Chemiekonzern the world.",emoji:"⚗️"},
  {q:"How many billion Dollar wert is der globale Markt for Legal cannabis?",a:50,unit:"billion $",hint:"grows through Legalisierungswellen.",emoji:"🌿"},
  {q:"How many billion Dollar yearssumsatz macht whalet Disney?",a:88,unit:"billion $",hint:"Film, Parks, Streaming und Merchandise.",emoji:"🏰"},
  {q:"How many billion Dollar has Microsoft for Activision Blizzard bezahlt?",a:68.7,unit:"billion $",hint:"2023 – das teuerste Gaming-Acquisition.",emoji:"🎮"},
  {q:"How many billion Euro wert is der deutsche Immobilienmarkt?",a:14000,unit:"billion €",hint:"14 Billionen Euro – größtes nationales Vermögen.",emoji:"🏠"},
  {q:"How many billion Dollar costs das James Webb Telescope?",a:10,unit:"billion $",hint:"Das teuerste Teleskop der Geschichte.",emoji:"🔭"},
  {q:"How many billion Euro yearssumsatz has Siemens?",a:77,unit:"billion €",hint:"Eines the largestn Industrieunternehmen Europas.",emoji:"⚙️"},
  {q:"How many billion Dollar wert is Zoom?",a:20,unit:"billion $",hint:"Covid has Zoom zum Must-Have gemacht.",emoji:"📹"},
  {q:"How many billion Dollar has TikTok laut Schätzungen Umsatz?",a:16,unit:"billion $",hint:"Stand 2023 – schnell wachsend.",emoji:"📱"},
  {q:"How many billion Dollar wert is der globale Sneaker-Markt?",a:70,unit:"billion $",hint:"Nike, Adidas und Resale-Markt zusammen.",emoji:"👟"},
  {q:"How many billion Euro schulden Deutsche Privathaushalte in total?",a:1900,unit:"billion €",hint:"1,9 Billionen Euro Privatschulden.",emoji:"💸"},
  {q:"How many billion Dollar wert is der globale Markt for KI-Chips?",a:100,unit:"billion $",hint:"Nvidia dominiert with seinen GPUs.",emoji:"💻"},
];
