// 🤯 WTF FACTS – Adults – English
export default [
  {q:"How many times a day does the average person burp?",a:25,unit:"times",hint:"Almost as often as they fart.",emoji:"😤"},
  {q:"How many kg of insects does a human accidentally eat per year?",a:1,unit:"kg",hint:"Hidden in food – FDA allows insect parts.",emoji:"🪲"},
  {q:"How many seconds does the average male orgasm last?",a:6,unit:"seconds",hint:"Women have the better deal at 20 seconds.",emoji:"💦"},
  {q:"How many hours per lifetime does a person spend on the toilet?",a:9000,unit:"hours",hint:"Over a year of your life on the loo.",emoji:"🚽"},
  {q:"What percentage of people have peed in the shower?",a:80,unit:"%",hint:"The rest are lying.",emoji:"🚿"},
  {q:"How many bacteria do you transfer during a handshake?",a:10000000,unit:"bacteria",hint:"10 million per second of contact.",emoji:"🤝"},
  {q:"How fast do sneezes travel in km/h?",a:160,unit:"km/h",hint:"Faster than most city cars.",emoji:"🤧"},
  {q:"How many times per hour does a person touch their face?",a:23,unit:"times/hour",hint:"552 times a day.",emoji:"✋"},
  {q:"How many kg of skin does a human shed in a lifetime?",a:48,unit:"kg",hint:"30,000 skin cells per hour.",emoji:"🧴"},
  {q:"How many meters of intestine does a human have?",a:8,unit:"meters",hint:"Small and large intestine combined.",emoji:"🌀"},
  {q:"How many millions of sperm does a man lose per ejaculation?",a:280,unit:"million",hint:"Only one gets the job.",emoji:"🏊"},
  {q:"What percentage of people have urinated in a public pool?",a:19,unit:"%",hint:"According to a US survey – probably more.",emoji:"🏊"},
  {q:"How many billion bacteria are in a single bowel movement?",a:100,unit:"billion",hint:"30% of stool is bacteria.",emoji:"💩"},
  {q:"How many degrees Celsius is a lightning bolt?",a:30000,unit:"°C",hint:"5x hotter than the sun's surface.",emoji:"⚡"},
  {q:"How many times per day does a person blink?",a:20000,unit:"times",hint:"Every 4-6 seconds.",emoji:"👁️"},
  {q:"How many grams of saliva is exchanged in a kiss?",a:3,unit:"grams",hint:"Plus 80 million bacteria.",emoji:"💋"},
  {q:"How many seconds does a decapitated chicken head survive?",a:15,unit:"seconds",hint:"The nervous system keeps running briefly.",emoji:"🐔"},
  {q:"What percentage of household dust is human skin cells?",a:70,unit:"%",hint:"You breathe in your housemates daily.",emoji:"🌫️"},
  {q:"How many liters of gas does a human produce daily through digestion?",a:2,unit:"liters",hint:"1.5L of that is released as farts.",emoji:"💨"},
  {q:"How many minutes is the longest documented female orgasm?",a:45,unit:"minutes",hint:"Medically documented case.",emoji:"😮"},
  {q:"How many grams of poop does a cow accidentally eat per day while grazing?",a:500,unit:"grams",hint:"Other cows leave traces in the grass.",emoji:"🐄"},
  {q:"What percentage of people kiss with their head tilted to the right?",a:66,unit:"%",hint:"Two out of three people tilt right.",emoji:"💏"},
  {q:"How many grams of plastic does a human eat per week?",a:5,unit:"grams",hint:"One credit card per week.",emoji:"♻️"},
  {q:"What percentage of banknotes carry cocaine traces?",a:90,unit:"%",hint:"Almost every note has traces.",emoji:"💵"},
  {q:"How many insect parts are in 100g of peanut butter according to FDA?",a:30,unit:"insect parts",hint:"FDA limit: 30 insect parts per 100g.",emoji:"🥔"},
  {q:"How many seconds is the longest documented sneeze?",a:978,unit:"seconds",hint:"16 minutes – a girl sneezed for 978 days straight.",emoji:"🤧"},
  {q:"How many liters of blood does your heart pump in a lifetime?",a:200000000,unit:"liters",hint:"200 million liters – an Olympic pool isn't enough.",emoji:"❤️"},
  {q:"What percentage of people with smartphones have fecal bacteria on their screen?",a:16,unit:"%",hint:"British study – 1 in 6 phones.",emoji:"📱"},
  {q:"How many animal species have documented sex for pleasure?",a:30,unit:"species",hint:"Bonobos, dolphins, macaques and more.",emoji:"🐬"},
  {q:"What percentage of people lie in the first 10 minutes of meeting someone?",a:60,unit:"%",hint:"Up to 3 lies in 10 minutes.",emoji:"🤥"},
  {q:"How many grams of sugar are in an adult's bloodstream?",a:5,unit:"grams",hint:"One teaspoon of sugar in your entire bloodstream.",emoji:"🍬"},
  {q:"How many hours per lifetime does a person spend kissing?",a:336,unit:"hours",hint:"2 weeks of your life is kissing.",emoji:"💋"},
  {q:"How many days does a cockroach survive without its head?",a:7,unit:"days",hint:"The body breathes through pores.",emoji:"🪳"},
  {q:"How many times a night does a person briefly wake up without noticing?",a:28,unit:"times",hint:"Normal sleep – we just don't remember it.",emoji:"😴"},
  {q:"How many calories does sex burn on average?",a:85,unit:"calories",hint:"Per session – less than a walk.",emoji:"❤️"},
  {q:"How many minutes does sex last on average according to studies?",a:5,unit:"minutes",hint:"Insertion to orgasm – worldwide average.",emoji:"⏱️"},
  {q:"How many people are on the toilet worldwide right now?",a:1,unit:"% of world population",hint:"80 million people simultaneously.",emoji:"🚽"},
  {q:"How many hours does it take for food to be fully digested?",a:53,unit:"hours",hint:"53 hours from mouth to toilet.",emoji:"💩"},
  {q:"What percentage of people sleep naked?",a:12,unit:"%",hint:"In Germany – higher in other countries.",emoji:"😴"},
  {q:"How many grams does the human brain weigh?",a:1400,unit:"grams",hint:"2% of body weight, 20% of energy use.",emoji:"🧠"},
  {q:"What percentage of DNA do humans share with bananas?",a:60,unit:"% DNA",hint:"We share DNA with almost all living things.",emoji:"🍌"},
  {q:"How many liters of stomach acid are produced daily?",a:2,unit:"liters",hint:"Strong enough to dissolve metal.",emoji:"⚗️"},
  {q:"What percentage of men have an erection upon waking?",a:90,unit:"%",hint:"Morning wood – almost daily.",emoji:"😴"},
  {q:"How many grams of snot do you swallow daily without noticing?",a:1000,unit:"grams",hint:"1 liter of mucus runs down your throat daily.",emoji:"🤧"},
  {q:"What percentage of couples both snore?",a:25,unit:"%",hint:"Every fourth couple snores in duet.",emoji:"😴"},
  {q:"How many minutes is the average toilet visit?",a:6,unit:"minutes",hint:"Men sit longer than women.",emoji:"🚽"},
  {q:"What percentage of women fake orgasms?",a:67,unit:"%",hint:"According to studies – two out of three.",emoji:"🎭"},
  {q:"How many milliliters of urine do you lose when laughing?",a:1,unit:"milliliter",hint:"Stress incontinence when laughing – very common.",emoji:"😂"},
  {q:"How many grams of earwax does an ear produce per month?",a:1,unit:"gram",hint:"Surprisingly much for such a small organ.",emoji:"👂"},
  {q:"How many times does a person masturbate on average by age 50?",a:5000,unit:"times",hint:"Men significantly more than women.",emoji:"🤫"},
  {q:"How many grams does a human tongue weigh?",a:70,unit:"grams",hint:"70g – a strong muscle.",emoji:"👅"},
  {q:"How many kilometers of blood vessels does a human have?",a:100000,unit:"km",hint:"2.5 times around the Earth.",emoji:"❤️"},
  {q:"What percentage of people have a parasite in their body without knowing?",a:50,unit:"%",hint:"Worldwide – especially in developing countries.",emoji:"🪱"},
  {q:"How many grams does a human kidney weigh?",a:150,unit:"grams",hint:"Smaller than you think.",emoji:"🫘"},
  {q:"How many bacteria does one gram of feces contain?",a:100,unit:"billion",hint:"Denser than anywhere else in the body.",emoji:"💩"},
  {q:"How many meters can human spit fly?",a:10,unit:"meters",hint:"World record is 9.44m.",emoji:"💦"},
  {q:"How many calories does a teaspoon of semen contain?",a:5,unit:"calories",hint:"Mainly fructose and proteins.",emoji:"💦"},
  {q:"How many grams of hair does a scalp produce per month?",a:15,unit:"grams",hint:"Each hair grows 1cm per month.",emoji:"💇"},
  {q:"How many decibels is the average fart?",a:50,unit:"decibels",hint:"Similar to a normal conversation.",emoji:"💨"},
  {q:"How many grams of sweat does the armpit produce per day?",a:50,unit:"grams",hint:"The smell comes from bacteria breaking it down.",emoji:"💦"},
  {q:"How many hours per lifetime does a human spend scratching?",a:5000,unit:"hours",hint:"Almost 7 months of pure scratching.",emoji:"😅"},
  {q:"How many liters of urine does a human produce in 80 years?",a:40000,unit:"liters",hint:"40,000 liters – a full tanker truck.",emoji:"💛"},
  {q:"What percentage of Germans wash their hands after using the toilet?",a:50,unit:"%",hint:"Half are lying when answering this.",emoji:"🧼"},
  {q:"How many centimeters does a fingernail grow per month?",a:3,unit:"mm",hint:"3mm per month – toenails slower.",emoji:"💅"},
  {q:"How many people die per year from coconuts falling on their heads?",a:150,unit:"people",hint:"More than from shark attacks – annually.",emoji:"🥥"},
  {q:"How many times does a person have sex in their lifetime on average?",a:5778,unit:"times",hint:"117 times a year × 49.4 active years.",emoji:"❤️"},
  {q:"How many hours of lifespan does each cigarette cost?",a:11,unit:"minutes",hint:"11 minutes shorter per cigarette.",emoji:"🚬"},
  {q:"How many decibels can the loudest human snore reach?",a:111,unit:"decibels",hint:"Louder than a jackhammer.",emoji:"😴"},
  {q:"How many grams does a human eyeball weigh?",a:7,unit:"grams",hint:"Smaller than a golf ball.",emoji:"👁️"},
  {q:"How many times does the average person breathe per day?",a:22000,unit:"times",hint:"18-20 breaths per minute.",emoji:"💨"},
  {q:"How many grams of fat does the body burn while sleeping per night?",a:70,unit:"grams",hint:"The body works during sleep.",emoji:"😴"},
  {q:"How many liter of saliva does a dog produce daily?",a:2,unit:"liters",hint:"Hence the wet nose.",emoji:"🐕"},
  {q:"What percentage of the population is currently on the toilet?",a:1,unit:"%",hint:"80 million people at any given moment.",emoji:"🚽"},
  {q:"How many grams of plaque form on teeth daily?",a:500,unit:"milligrams",hint:"0.5g daily without brushing.",emoji:"🦷"},
  {q:"How many hours does sperm survive on surfaces?",a:2,unit:"hours",hint:"On dry surfaces for 2 hours.",emoji:"💦"},
  {q:"How many grams of cat fur does a cat swallow while grooming per year?",a:100,unit:"grams",hint:"Leads to hairballs.",emoji:"🐱"},
  {q:"How many grams of insect parts are in a jar of tomato sauce per FDA?",a:30,unit:"insect parts",hint:"FDA limit: 30 fly eggs or 2 maggots.",emoji:"🍅"},
  {q:"How many people are injured by toilets in the US annually?",a:40000,unit:"people",hint:"40,000 toilet injuries per year.",emoji:"🚽"},
  {q:"How many times was the F-word said in The Wolf of Wall Street?",a:506,unit:"times",hint:"Record for most F-words in a film.",emoji:"🎬"},
  {q:"How many hours per lifetime does a human spend having orgasms?",a:1,unit:"hour",hint:"6 seconds × 5,778 times = ~1 hour.",emoji:"😮"},
  {q:"How many people are struck by lightning daily worldwide?",a:2000,unit:"people",hint:"2000 daily – 40-50 fatally.",emoji:"⚡"},
  {q:"How many days does it take for sperm to reach a supermarket shelf as food?",a:53,unit:"hours to digest",hint:"Food takes 53 hours mouth to toilet.",emoji:"💩"},
  {q:"How many nano plastic particles are in one liter of bottled water?",a:240000,unit:"particles",hint:"240,000 nanoplastic particles per liter.",emoji:"🍶"},
  {q:"How many grams does the human uterus weigh?",a:60,unit:"grams",hint:"Smaller than a fist – can grow to 1kg.",emoji:"👶"},
  {q:"How many times does the average person laugh per day?",a:17,unit:"times",hint:"Children laugh much more than adults.",emoji:"😂"},
  {q:"How many grams of dirt accumulate in the belly button per year?",a:500,unit:"milligrams",hint:"Oil, dirt, and dead skin.",emoji:"🔘"},
  {q:"How many minutes does it take sperm to reach the egg?",a:50,unit:"minutes",hint:"The fastest ones in 45-60 minutes.",emoji:"🏊"},
  {q:"What percentage of all deaths worldwide occur in the bathroom?",a:25,unit:"%",hint:"Falls, heart attacks, drowning.",emoji:"🚿"},
  {q:"How many hours per lifetime does a human spend brushing teeth?",a:122,unit:"hours",hint:"2 min × 2x daily × 75 years.",emoji:"🦷"},
  {q:"What percentage of children eat their own boogers?",a:90,unit:"%",hint:"Almost all – it even has immune benefits.",emoji:"🤧"},
];
