// 💀 BIZARRE RECORDS – English
export default [
  {q:"How long was the longest fingernail of a woman in cm?",a:909,unit:"cm",hint:"Lee Redmoon ließ ihre Nägel 30 years wachsen.",emoji:"💅"},
  {q:"How many hot dogs aß Joey Chestnut als world record in 10 minutes?",a:76,unit:"hot dogs",hint:"at der berühmten Nathan's Hot Dog Contest.",emoji:"🌭"},
  {q:"How heavy was the heaviest jetimess gezüchtete pumpkin in kg?",a:1190,unit:"kg",hint:"Der Riesenpumpkin was 2021 in Italien gewogen.",emoji:"🎃"},
  {q:"How many Piercings haste humans with den meisen?",a:4384,unit:"Piercings",hint:"Rolf Buchholz from Deutschland hielt diesen Rekord.",emoji:"💎"},
  {q:"How long was the longest jetimess gemessene Bart in cm?",a:570,unit:"cm",hint:"Hans Langseth trug ihn a live lang.",emoji:"🧔"},
  {q:"How many hours hielt the longest Kuss the world?",a:58,unit:"hours",hint:"Ein thailändisches Pärchen küsste sich 2013 ununterbrochen.",emoji:"💋"},
  {q:"How many km/h fuhr das schnellste muskelkraftbetriebene Fahrrad?",a:280,unit:"km/h",hint:"Im Windschasten eines Rennwagens aufgestellt.",emoji:"🚴"},
  {q:"How old was the oldest cat ever recorded in years?",a:38,unit:"years",hint:"Creme Puff from Texas livese of 1967 bis 2005.",emoji:"🐱"},
  {q:"How many Sprachen spricht der Polyglott Ziad Fazah?",a:58,unit:"Sprachen",hint:"Er beherrscht Sprachen from aller Welt.",emoji:"🗣️"},
  {q:"How many meters tief is die Kola-Bohrung in Russland?",a:12262,unit:"meterss",hint:"Das tiefste Loch the world – to 24 yearsn gestoppt.",emoji:"⛏️"},
  {q:"How heavy was das schwerste jetimess gewogene Schwein in kg?",a:1157,unit:"kg",hint:"Big Bill hieß das Riesenschwein from den USA (1933).",emoji:"🐷"},
  {q:"How many meters lang was the longest jetimess gebackene Pizza?",a:1930,unit:"meterss",hint:"Gebacken 2017 in Kalifornien.",emoji:"🍕"},
  {q:"How old was the oldest person ever in years?",a:122,unit:"years",hint:"Jeanne Calment from Frankreich, 1875–1997.",emoji:"👴"},
  {q:"How many Domino-Steine wasn beim größten Domino-Effekt verwendet?",a:4491863,unit:"Steine",hint:"2009 in den Niederlanden aufgestellt.",emoji:"🎲"},
  {q:"How many Bienen saßen gleichzeitig on einem people als Rekord?",a:637000,unit:"Bienen",hint:"Das equals einem Gewicht of ~63 kg Bienen.",emoji:"🐝"},
  {q:"How many Stockwerke has der Burj Khalifa?",a:163,unit:"Stockwerke",hint:"828 meters hoch, steht in Dubai.",emoji:"🏙️"},
  {q:"How many km lief the worldrekordhalter Yiannis Kouros non-stop?",a:426,unit:"km",hint:"1997 in Australien aufgestellt.",emoji:"🏃"},
  {q:"How many Kugeln Eis aß the worldrekordhalter in einer Stunde?",a:254,unit:"Kugeln",hint:"Der Wettbewerb fand in Italien statt.",emoji:"🍦"},
  {q:"How heavy was das schwerste jetimess gefangene Krokodil in kg?",a:1075,unit:"kg",hint:"Ein Salzwasserkrokodil of den Philippinen.",emoji:"🐊"},
  {q:"How many m² groß was the largest jetimess getimeste painting?",a:17000,unit:"m²",hint:"Sacha Jafri timeste es 2021 in Dubai.",emoji:"🎨"},
  {q:"How many km/h erreichte die schnellste Tennisaufschlagsgeschwindigkeit?",a:263,unit:"km/h",hint:"Samuel Groth from Australien, 2012.",emoji:"🎾"},
  {q:"How many meters weit was a Gummisiefel beim Weitwurf geworfen?",a:63,unit:"meterss",hint:"Offizieller world record im finnischen Stiefelweitwurf.",emoji:"👢"},
  {q:"How many Kerzen standen on the largestn Geburtstagstorte?",a:72585,unit:"Kerzen",hint:"Die Torte was 2016 in Indien aufgestellt.",emoji:"🎂"},
  {q:"How long was the longest jetimess gemessene Haarlänge of a woman in cm?",a:570,unit:"cm",hint:"Xie Qiuping from China ließ sie seit 1973 wachsen.",emoji:"💇"},
  {q:"How many people saßen gleichzeitig on einem Motorrad als Rekord?",a:58,unit:"people",hint:"Aufgestellt of der indischen Armee.",emoji:"🏍️"},
  {q:"How many Meilen fuhr the longest je dokumentierte Taxifahrt?",a:21000,unit:"Meilen",hint:"Ein Brite fuhr of London to Melbourne.",emoji:"🚕"},
  {q:"How long was the longest Bart of a woman in cm?",a:30,unit:"cm",hint:"Harnaam Kaur from UK carries den Rekord.",emoji:"🧔‍♀️"},
  {q:"How many hours badete humans with dem längsten Bad im Toten sea?",a:48,unit:"hours",hint:"Das extrem salzige water macht langes Baden möglich.",emoji:"🛁"},
  {q:"How many times schlug a Boxer in einer Minute on einen Sandsack?",a:217,unit:"Schläge",hint:"Westley Lyons stellte diesen Rekord on.",emoji:"🥊"},
  {q:"How many meters lang was the longest Surfbrett?",a:12,unit:"meterss",hint:"Gebaut 2015 in Australien – with 66 Surfern drauf.",emoji:"🏄"},
  {q:"How many kg Zwiebeln schälte the worldrekordhalter in einer Stunde?",a:11.6,unit:"kg",hint:"under Tränen natürlich.",emoji:"🧅"},
  {q:"How many meters weit spuckte der Weitspuck-Weltmeiser einen Kirschkern?",a:28.5,unit:"meterss",hint:"Aufgestellt beim World Cherry Pit Spitting Championship.",emoji:"🍒"},
  {q:"How many Trampolin-Sprünge schaffte der Rekordhalter in einer Minute?",a:245,unit:"Sprünge",hint:"Fast 4 Sprünge pro Sekunde.",emoji:"🤸"},
  {q:"How many hours trug humans with dem längsten Kopfstand on sich?",a:3,unit:"hours",hint:"Rekord of Bryce Lane from 2019.",emoji:"🤸"},
  {q:"How many meters lang was the longest Zopf of a woman?",a:2.97,unit:"meterss",hint:"Rekord from China 2021.",emoji:"💇"},
  {q:"How many Stockwerke has das höchste Hotel the world (Gevora Dubai)?",a:75,unit:"Stockwerke",hint:"356 meters hoch with 528 Zimmern.",emoji:"🏨"},
  {q:"How many meters weit sprang a human on einem Pogo-Stick?",a:33,unit:"meterss",hint:"Brent Sherwood hüpfte 33 meters weit.",emoji:"🦘"},
  {q:"How many Hamburger aß der Rekordhalter in 3 minutes?",a:12,unit:"Hamburger",hint:"Kobayashi schaffte 12 Burgern in 180 seconds.",emoji:"🍔"},
  {q:"How many meters lang was the largest Weihnachtsstrumpf?",a:51,unit:"meterss",hint:"Gestrickt 2018 in Großbritannien.",emoji:"🧦"},
  {q:"How many hours tanzte the worldrekordhalter ununterbrochen?",a:123,unit:"hours",hint:"over 5 days ohne Schlaf tanzend.",emoji:"💃"},
  {q:"How many Treppen stieg the fastest Empire State Building Runner in minutes?",a:9.8,unit:"minutes",hint:"1576 Stufen on 86 Stockwerke.",emoji:"🏃"},
  {q:"How many kg wog das schwerste jetimess gegrillte Steak?",a:1098,unit:"kg",hint:"Ein Riesensteak for den world record.",emoji:"🥩"},
  {q:"How many meters tief tauchte der Rekordtaucher on einem einzigen Atemzug?",a:214,unit:"meterss",hint:"Herbert Nitsch – der tiefste Mann the world.",emoji:"🤿"},
  {q:"How many km lief der älteste Marathon-Finisher in yearsn?",a:100,unit:"years alt",hint:"Fauja Singh from Indien lief einen Marathon with 100 yearsn.",emoji:"🏃"},
  {q:"How many hours nonstop spielte the worldrekord-Videoplayers?",a:138,unit:"hours",hint:"Fast 6 days nonstop zocken.",emoji:"🎮"},
  {q:"How heavy was das schwerste Kaninchen in kg?",a:22,unit:"kg",hint:"Darius – ein Kontinentaler Riese from England.",emoji:"🐰"},
  {q:"How many meters lang was the longest Schachplayers-Bart?",a:2.13,unit:"meterss",hint:"Der beartler spielte gleichzeitig Schach.",emoji:"🧔"},
  {q:"How many Liegestütze machte der Rekordhalter in einer Minute?",a:138,unit:"Liegestütze",hint:"Rekord of Carlton Williams from 2022.",emoji:"💪"},
  {q:"How many meters lang was the longest peoplekette under water?",a:269,unit:"meterss",hint:"over 300 Taucher bildeten 2015 diese Kette.",emoji:"🤿"},
  {q:"How many hours fuhr der Langstrecken-Fahrrad-world recordler?",a:72,unit:"hours",hint:"Amanda Coker fuhr 72 hours nonstop.",emoji:"🚴"},
  {q:"How many meters weit schoss der weiteste Elfmeters?",a:100,unit:"meterss",hint:"with einem speziellen Kanonenschuss erzielt.",emoji:"⚽"},
  {q:"How many kg Curry aß der Rekordhalter in einer Stunde?",a:8.8,unit:"kg",hint:"Juliet Lee schaffte 8,8 kg Curry in 60 minutes.",emoji:"🍛"},
  {q:"How many hours sang the worldrekord-Karaoke-Sänger?",a:101,unit:"hours",hint:"in Indien was dieser Ausdauer-Rekord aufgestellt.",emoji:"🎤"},
  {q:"How heavy was the heaviest Mensch aller Zeiten in kg?",a:635,unit:"kg",hint:"Jon Brower Minnoch from den USA wog 635 kg.",emoji:"⚖️"},
  {q:"How many m hoch was der höchste jump on einem Snowboard?",a:9,unit:"meterss",hint:"Travis Rice erzielte diesen Rekord in einem Halfpipe.",emoji:"🏂"},
  {q:"How many Gurken aß der Rekordhalter in einer Minute?",a:8,unit:"Gurken",hint:"Komplette Gurken, nicht Scheiben.",emoji:"🥒"},
  {q:"How many meters lang was the longest Laufsteg at einer Modenschau?",a:6.5,unit:"km",hint:"Unilever organisierte 2020 diesen Rekord.",emoji:"👠"},
  {q:"How many hours stand humans on einem Bein als world record?",a:76,unit:"hours",hint:"Majid Khan from Pakisan, 2016.",emoji:"🦩"},
  {q:"How many km/h fuhr the fastest Rollstuhl bergab?",a:130,unit:"km/h",hint:"Ein speziell modifizierter Rennrollstuhl.",emoji:"♿"},
  {q:"How many meters lang was the longest Sandwich?",a:735,unit:"meterss",hint:"Hergestellt 2015 in Mexiko.",emoji:"🥪"},
  {q:"How many hours lief the longest Ultramarathon?",a:240,unit:"hours",hint:"10 days non-stop run.",emoji:"🏃"},
  {q:"How heavy was die schwerste in einem Stück gekochte Pasta in kg?",a:5900,unit:"kg",hint:"Fast 6 tons Pasta in einem einzigen Gericht.",emoji:"🍝"},
  {q:"How many meters lang was the longest Girlande?",a:5650,unit:"meterss",hint:"in den Philippinen hergestellt for Weihnachten 2015.",emoji:"🎄"},
  {q:"How many hours sang a Chor ununterbrochen als world record?",a:120,unit:"hours",hint:"Ein indischer Chor sang 5 days nonstop.",emoji:"🎵"},
  {q:"How many meters lang was the longest Popcorn-Trail?",a:1768,unit:"meterss",hint:"Aufgebaut 2020 in Tschechien.",emoji:"🍿"},
  {q:"How many kg wog das schwerste Weihnachtsplätzchen?",a:400,unit:"kg",hint:"Ein einziger riesiger Lebkuchen.",emoji:"🍪"},
  {q:"How many hours Dauerschlaf hielt the worldrekordhalter through?",a:11,unit:"hours",hint:"Peter Tripp blieb 201 hours wach – das is der Gegduckil-Rekord.",emoji:"😴"},
  {q:"How many km/h fuhr a human on einer Bananenschale gleitend?",a:3,unit:"km/h",hint:"Experiment zur Reibung of Bananenschalen.",emoji:"🍌"},
  {q:"How many meters lang was the longest Volleyball-Rallye-Wechsel?",a:120,unit:"times",hint:"Pässe ohne Ballberührung des Bodens.",emoji:"🏐"},
  {q:"How many hours spielte a Pianis ununterbrochen als world record?",a:120,unit:"hours",hint:"Klavierspielen 5 days nonstop.",emoji:"🎹"},
  {q:"How heavy was das schwerste gegessene Steak in 9 minutes?",a:1.36,unit:"kg",hint:"Das US-Steak-Wettessen-Rekord.",emoji:"🥩"},
  {q:"How many meters lang was the longest Nudel?",a:3776,unit:"meterss",hint:"Hergestellt in China, lang wie der Fuji.",emoji:"🍜"},
  {q:"How many seconds lief der 100m-Sprint als absolute Bestzeit?",a:9.58,unit:"seconds",hint:"Usain Bolt, Berlin 2009.",emoji:"⚡"},
  {q:"How many m hoch is die höchste je erklommene Welle beim Surfen?",a:24,unit:"meterss",hint:"Rodrigo Koxa surfte 2017 diese Riesenwelle.",emoji:"🏄"},
  {q:"How many Marshtimeslows stopfte sich a man gleichzeitig in den Mund?",a:25,unit:"Marshtimeslows",hint:"world record im Marshtimeslow-Stopfen.",emoji:"🍬"},
  {q:"How many Stifte hielt the worldrekordhalter gleichzeitig between den fingern?",a:60,unit:"Stifte",hint:"Lorenzo Resta, Italien 2019.",emoji:"✏️"},
  {q:"How many m lang was the longest Girlande from Popcorn?",a:1200,unit:"meterss",hint:"Aufgefädelt in Schoolkids in den USA.",emoji:"🍿"},
  {q:"How heavy was das schwerste Hühnerei in grams?",a:454,unit:"grams",hint:"Das schwerste becante Hühnerei der Geschichte.",emoji:"🥚"},
  {q:"How many meters lang was the longest Fischfilet?",a:121,unit:"meterss",hint:"Ein Thunfischfilet in Japan aufgeschnitten.",emoji:"🐟"},
  {q:"How many liters Milch trank the worldrekordhalter in einer Stunde?",a:4,unit:"literss",hint:"liters for liters – ein ekelhafter Rekord.",emoji:"🥛"},
  {q:"How many hours blieb jemand in eiskaltem water am längsten?",a:24,unit:"hours",hint:"Wim Hof setzte diesen Rekord im Eisbad.",emoji:"🧊"},
  {q:"How many km/h fuhr a human on einem Laufband als Rekord?",a:45,unit:"km/h",hint:"Sprints on dem Laufband.",emoji:"🏃"},
  {q:"How many Wasserflaschen balancierten on dem Kopf des Rekordhalters?",a:24,unit:"Flaschen",hint:"Dr. Ashrita Furman, world recordhalter schlechthin.",emoji:"🍶"},
  {q:"How many meters lang was the longest Currywurst?",a:96,unit:"meterss",hint:"Aufgestellt beim Karneval in Germany.",emoji:"🌭"},
  {q:"How many Höhenmeters kletterte the fastest Everest-Aufstieg?",a:8849,unit:"meterss",hint:"Nirtimes Purja schaffte den Aufstieg in weniger als 7 hours.",emoji:"🏔️"},
  {q:"How many hours joggte der älteste Marathonläufer Fauja Singh kontinuierlich?",a:8.5,unit:"hours",hint:"with 100 yearsn lief er einen kompletten Marathon.",emoji:"🏃"},
  {q:"How many Bälle jonglierte der Rekordhalter gleichzeitig?",a:14,unit:"Bälle",hint:"Alex Barron jonglierte 14 Bälle 2017.",emoji:"🎪"},
  {q:"How many meters lang was the longest Schleppe eines Hochzeitskleids?",a:3000,unit:"meterss",hint:"Ein 3 km longes Brautkleid from Rumänien.",emoji:"👰"},
  {q:"How many liters Coca-Cola trank der Rekordhalter in einer Stunde?",a:2,unit:"literss",hint:"through einen Strohhalm natürlich.",emoji:"🥤"},
  {q:"How many Eierkuchen übereinander schichtete der Rekordhalter?",a:76,unit:"Eierkuchen",hint:"Ein instabiler Turm from Eierkuchen.",emoji:"🥞"},
  {q:"How many meters lang was the largest Omelette?",a:14,unit:"meters Durchmesser",hint:"in Frankreich, dem country des Omeletts.",emoji:"🍳"},
  {q:"How many hours nonstop schaute jemand Netflix als world record?",a:94,unit:"hours",hint:"Fast 4 days ununterbrochen Netflix.",emoji:"📺"},
  {q:"How many kg Käse was beim größten Käsefondue verwendet?",a:740,unit:"kg",hint:"Ein riesiger Topf Käse in der Schweiz.",emoji:"🧀"},
  {q:"How many meters lang was the longest Zug from Liegestühlen?",a:2000,unit:"meterss",hint:"2 km Liegestühle in einer Reihe.",emoji:"🏖️"},
  {q:"How many days fastete the worldrekordhalter?",a:382,unit:"days",hint:"Angus Barbeeri fastete under medizinischer Aufsicht.",emoji:"🚫"},
  {q:"How many kg Kartoffeln schälte der Rekordhalter in einer Stunde?",a:30,unit:"kg",hint:"Ein world record from Irland.",emoji:"🥔"},
  {q:"How many hours spielte a Band nonstop als world record?",a:134,unit:"hours",hint:"over 5 days Livemusik.",emoji:"🎸"},
  {q:"How many meters lang was the longest Sushi?",a:2544,unit:"meterss",hint:"in Japan hergestellt for den world record.",emoji:"🍣"},
  {q:"How many hours stand humans on einem Surfbrett on einem lake?",a:40,unit:"hours",hint:"Nonstop surfen on einem Binnensee.",emoji:"🏄"},
  {q:"How many Münzen stapelte der Rekordhalter on einem finger?",a:253,unit:"Münzen",hint:"Balanciert on einem einzelnen Zeigefinger.",emoji:"🪙"},
  {q:"How many km weit schwamm der Langstreckenschwimmer nonstop?",a:225,unit:"km",hint:"Martin Strel schwamm over 225 km am Stück.",emoji:"🏊"},
  {q:"How many meters hoch kletterte die Rekordklettererin ohne Seil?",a:600,unit:"meterss",hint:"Alex Honnold kletterte den El Capitan frei (893m).",emoji:"🧗"},
  {q:"How many hours hielt der Rekordhalter a Yoga-Position?",a:7,unit:"hours",hint:"Extreme Ausdauer in einer einzigen Pose.",emoji:"🧘"},
  {q:"How many kg weighs das schwerste Schokoladenei the world?",a:4000,unit:"kg",hint:"Ein 4 tons schweres Schokoladenei from Italien.",emoji:"🍫"},
  {q:"How many times flippte der Rekordhalter a Wasserflasche nonstop?",a:2000,unit:"times",hint:"Flipping Bottles was a Trend – einer machte es viele timese.",emoji:"🍶"},
  {q:"How many Bücher las the worldrekordleser in einer Woche?",a:100,unit:"Bücher",hint:"Speedreader Howasd mountain las 25000 Wörter per minute.",emoji:"📚"},
  {q:"How many meters lang was the largest Cheeseburger?",a:60,unit:"cm Höhe",hint:"Ein 60 cm hoher Turm-Cheeseburger.",emoji:"🍔"},
  {q:"How many seconds hielt a human einen lebenden Skorpion im Mund?",a:33,unit:"seconds",hint:"Ein sehr gefährlicher world record.",emoji:"🦂"},
  {q:"How many hours badete jemand in beer als world record?",a:3,unit:"hours",hint:"in einem with beer gefüllten Whirlpool.",emoji:"🍺"},
  {q:"How many km/h fuhr das schnellste Motorrad je?",a:605,unit:"km/h",hint:"Das Streamliner-Motorrad of Ack Attack.",emoji:"🏍️"},
  {q:"How many hours spielte jemand Schach nonstop?",a:60,unit:"hours",hint:"over 2,5 days ununterbrochen Schach.",emoji:"♟️"},
  {q:"How heavy was das schwerste verkaufte Einzel-Stück Trüffel in kg?",a:1.89,unit:"kg",hint:"2007 for 330.000€ at Sotheby's versteigert.",emoji:"🍄"},
  {q:"How many meters lang was the longest Schlange from Karotten?",a:1000,unit:"meterss",hint:"1 km Karotten in einer Reihe aufgestellt.",emoji:"🥕"},
  {q:"How many hours blieb jemand in einer Tonne Eiswürfel vergraben?",a:2.5,unit:"hours",hint:"Jin Songhao überlivese 2.5 hours eingefroren.",emoji:"🧊"},
  {q:"How many kg Avocados schälte der Rekordhalter in einer Minute?",a:8,unit:"Stück",hint:"Avocados in 60 seconds geschält.",emoji:"🥑"},
  {q:"How many Bananen schälte der Rekordhalter in einer Minute with dem Fuß?",a:8,unit:"Bananen",hint:"with den Zehen – nicht with den Händen.",emoji:"🍌"},
  {q:"How many meters lang was the longest Bratwurst?",a:648,unit:"meterss",hint:"Hergestellt in Österreich for den world record.",emoji:"🌭"},
  {q:"How many hours überlivese jemand ohne Schlaf als Rekord?",a:449,unit:"hours",hint:"Randy Gardner blieb 264 hours wach – das is der offizielle Rekord.",emoji:"😴"},
  {q:"How many Ballondoge formte der Rekordhalter in einer Stunde?",a:747,unit:"Ballondoge",hint:"John Cassidy formte fast einen pro 5 seconds.",emoji:"🐶"},
  {q:"How many meters lang was the longest Hot Dog?",a:203,unit:"meterss",hint:"2011 in Paraguay hergestellt.",emoji:"🌭"},
  {q:"How many hours sitzt the worldrekordler in einer Sauna?",a:16,unit:"hours",hint:"in Finnland natürlich.",emoji:"🧖"},
  {q:"How many kg Spaghetti aß der Rekordhalter in 30 seconds?",a:0.7,unit:"kg",hint:"700g Nudeln in einer halben Minute.",emoji:"🍝"},
  {q:"How many Liegestütze machte der Rekordhalter in 24 hours?",a:46001,unit:"Liegestütze",hint:"Charles Servizio 1993.",emoji:"💪"},
  {q:"How many km weit rollte a man on einem Einrad nonstop?",a:1458,unit:"km",hint:"Lon Allen Hughes fuhr quer through die USA.",emoji:"🎪"},
  {q:"How many hours hielt the worldrekordhalter a Tablett on einem finger?",a:2,unit:"hours",hint:"Ein Tablett balanciert on einer fingerspitze.",emoji:"🤸"},
  {q:"How many Tortillas aß der Rekordhalter in einer Minute?",a:13,unit:"Tortillas",hint:"Mexikanische Burrito-Wettessen-world record.",emoji:"🌮"},
  {q:"How heavy was das schwerste Sushi-Platte the world in kg?",a:6500,unit:"kg",hint:"6,5 tons Sushi in Japan aufgetischt.",emoji:"🍣"},
  {q:"How many meters lang was the longest Laterne from Papier?",a:2000,unit:"meterss",hint:"in China zur Feier des Laternenfests.",emoji:"🏮"},
  {q:"How many hours spielte jemand Basketball ununterbrochen?",a:120,unit:"hours",hint:"5 days Basketball ohne Schlaf.",emoji:"🏀"},
  {q:"How many seconds needse the fastest Rubik's Cube Löser?",a:3.13,unit:"seconds",hint:"Max Park löste den Cube 2023.",emoji:"🧩"},
  {q:"How many meters weit sprang a Motorrad over Autos?",a:115,unit:"meterss",hint:"Robbie Maddison überquerte 46 Autos.",emoji:"🏍️"},
  {q:"How many Pfannkuchen wasf der Rekordhalter in einer Minute?",a:140,unit:"Pfannkuchen",hint:"Mike Cuzzacrea 1994.",emoji:"🥞"},
  {q:"How heavy was das schwerste gegrillte Würstchen in kg?",a:80,unit:"kg",hint:"Ein 80 kg schweres Riesenwürstchen.",emoji:"🌭"},
  {q:"How many minutes hielt the longest Handstand am Stück?",a:56,unit:"minutes",hint:"Dave Brett, 1992.",emoji:"🤸"},
  {q:"How many meters tief stieg der Taucher with dem Taucheranzug?",a:701,unit:"meterss",hint:"Nuno Gomes, 2005 im Roten sea.",emoji:"🤿"},
  {q:"How many hours schlief humans with dem längsten Mittagsschlaf?",a:5,unit:"hours",hint:"Der ausgedehnteste dokumentierte Nickerchen.",emoji:"😴"},
  {q:"How many meters lang was the longest Knaller-Feuerwerk-Streifen?",a:5765,unit:"meterss",hint:"in Mexiko 2018 aufgestellt.",emoji:"🎆"},
  {q:"How heavy was die schwerste Zwiebel the world in kg?",a:8.96,unit:"kg",hint:"Tony Glover from England züchtete sie 2012.",emoji:"🧅"},
  {q:"How many hours trug jemand a Brautkleid am längsten?",a:108,unit:"hours",hint:"a woman trug 4,5 days lang a Brautkleid.",emoji:"👰"},
  {q:"How many seconds needse the fastest Kspeciesplayers for a Deck?",a:10,unit:"seconds",hint:"Ein komplettes Kspeciesspiel sortieren.",emoji:"🃏"},
  {q:"How many meters weit was a Kuh at einem Rennen geritten?",a:200,unit:"meterss",hint:"Kuhrennen in Bayern – ein echter Sport.",emoji:"🐄"},
  {q:"How many hours blieb a Team in einem Aufzug eingeschlossen als world record?",a:41,unit:"hours",hint:"Nicholas White was allein 41 hours im Aufzug gefangen.",emoji:"🛗"},
  {q:"How many Stockwerke lief the fastest Treppenläufer beim Eiffelturm hoch?",a:9,unit:"minutes",hint:"1665 Stufen – der Rekord steht seit 2017.",emoji:"🗼"},
  {q:"How many meters lang was the longest Bleisift?",a:323,unit:"meterss",hint:"in Sri Lanka hergestellt.",emoji:"✏️"},
  {q:"How many hours meditierte the worldrekord-Meditator?",a:40,unit:"days",hint:"Ein Tibetanischer Mönch meditierte 40 days.",emoji:"🧘"},
  {q:"How many Geburtstagstorten aß der Rekordhalter in einer Stunde?",a:14,unit:"Stück",hint:"Jeder Slice was dabei a komplettes Kuchenstück.",emoji:"🎂"},
  {q:"How many Klimmzüge schaffte der Rekordhalter in einer Minute?",a:50,unit:"Klimmzüge",hint:"Jan Kares, 2019.",emoji:"💪"},
  {q:"How many meters lang was the longest spidernnetz?",a:25,unit:"meterss",hint:"Eine Kolonial-spidernart baute es in den USA.",emoji:"🕸️"},
  {q:"How many seconds takese the longest gemessene Blitzschlag?",a:7.74,unit:"seconds",hint:"in Brasilien 2020 gemessen.",emoji:"⚡"},
  {q:"How many hours sang Maria Callas am längsten am Stück?",a:8,unit:"hours",hint:"Ein Endlos-Konzert-Rekord in der Oper.",emoji:"🎤"},
  {q:"How many meters lang was the longest Wäscheleine?",a:1500,unit:"meterss",hint:"with Wäschestücken behangen in Kroatien.",emoji:"👕"},
  {q:"How many hours fuhr a Tandem-Fahrrad-Team nonstop?",a:24,unit:"hours",hint:"24h Tandemfahren ohne Pause.",emoji:"🚴"},
  {q:"How many hours rief a human als world record ununterbrochen?",a:21,unit:"hours",hint:"hours Dauerrufen ohne Pause.",emoji:"📢"},
  {q:"How many meters lang was the longest Schuh?",a:6.4,unit:"meterss",hint:"Ein Riesen-Sportschuh als Kunstwerk.",emoji:"👟"},
  {q:"How many hours rollte a human on einem Skateboard nonstop?",a:36,unit:"hours",hint:"over einen Tag und a Nacht Skaten.",emoji:"🛹"},
  {q:"How many Stühle hob der Stärkste with dem Mund hoch?",a:24,unit:"Stühle",hint:"Georges Chrisen hielt 24 Stühle with den teethn.",emoji:"🦷"},
  {q:"How many meters lang was the longest Blumenkette?",a:4000,unit:"meterss",hint:"in Indien for a Fest hergestellt.",emoji:"🌸"},
  {q:"How many hours hielt a child einen Hula-Hoop in der Luft?",a:74,unit:"hours",hint:"Marawa Ibrahim hielt ihn 74 hours.",emoji:"🔵"},
  {q:"How many km is the longest Spaziergang the world lang?",a:24000,unit:"km",hint:"George Meegan lief of Feuerland to Alaska.",emoji:"🚶"},
  {q:"How many hours nonstop spielte a Fußballteam?",a:169,unit:"hours",hint:"over a Woche Fußball am Stück.",emoji:"⚽"},
  {q:"How many meters weit hüpfte der Rekordhalter on einem Bein?",a:100,unit:"meterss",hint:"meters Einbein-Hüpfen als world record.",emoji:"🦘"},
  {q:"How many hours las a human als Dauerlesung vor?",a:200,unit:"hours",hint:"8 days Vorlesemarathon.",emoji:"📖"},
  {q:"How many Schaukeln schaukelte jemand in 24 hours?",a:230000,unit:"times",hint:"Kontinuierliches Schaukeln einen ganzen Tag.",emoji:"🎢"},
  {q:"How many meters lang was the longest Zug from Flugzeugen?",a:19,unit:"Flugzeuge",hint:"Flugzeuge flogen in enger Formation.",emoji:"✈️"},
  {q:"How heavy was das schwerste einzelne Traubenbündel in kg?",a:9.4,unit:"kg",hint:"Eine Weintraube from Chile 2018.",emoji:"🍇"},
  {q:"How many hours lief a human on einem Laufband als Rekord?",a:24,unit:"hours",hint:"hours ununterbrochen on dem Laufband.",emoji:"🏃"},
  {q:"How many meters tief is das tiefste natürliche Loch the world?",a:2191,unit:"meterss",hint:"Die Krubera-Höhle in Georgien.",emoji:"🕳️"},
  {q:"How many kg Eis schleckte der Rekordhalter in einer Stunde?",a:1.3,unit:"kg",hint:"over a Kilo Eis am Stiel in 60 minutes.",emoji:"🍦"},
  {q:"How many hours sang a Gruppe Kinderlieder nonstop?",a:73,unit:"hours",hint:"3 days Kinderlied-Marathon.",emoji:"🎵"},
  {q:"How many meters lang was the largest Lebkuchenmann?",a:10,unit:"meterss",hint:"in Schweden 2009 gebacken.",emoji:"🍪"},
  {q:"How many seconds hielt a human a Jalapeño-Chili im Auge?",a:7,unit:"seconds",hint:"Extrem schmerzhaft – nicht empfohlen.",emoji:"🌶️"},
  {q:"How many hours lief a dog on einem Laufband nonstop?",a:5,unit:"hours",hint:"Ausdauer-dog in Japan.",emoji:"🐕"},
  {q:"How many km weit fuhr the longest Kspecieshaus-Bahn?",a:32,unit:"meterss",hint:"Ein Kspecieshaus-Dominoeffekt over 32 meters.",emoji:"🃏"},
  {q:"How heavy was das schwerste Pfannkuchen-Stapel in kg?",a:4.5,unit:"kg",hint:"Ein Turm from Pfannkuchen.",emoji:"🥞"},
  {q:"How many hours trug jemand a Mütze ohne sie abzunehmen?",a:1000,unit:"hours",hint:"over 40 days Mütze carry.",emoji:"🧢"},
  {q:"How many meters lang was the longest Baumwollbonbon-Faden?",a:1427,unit:"meterss",hint:"sugarwattse als langer Faden aufgerollt.",emoji:"🍬"},
  {q:"How many people machten gleichzeitig den größten Flashmob?",a:13597,unit:"people",hint:"in Mumbai Indien 2013.",emoji:"🕺"},
  {q:"How many meters tief watete jemand in Spaghetti?",a:1,unit:"meters Tiefe",hint:"Eine Wanne voll Spaghetti.",emoji:"🍝"},
  {q:"How many hours blieb a human in einem Glas-Sarg under water?",a:7,unit:"hours",hint:"under water eingeschlossen – Atemluft through a Rohr.",emoji:"🧊"},
  {q:"How many seconds needse the fastest Pizzateig-Dreher for 5 Drehungen?",a:10,unit:"seconds",hint:"Pizza-Akrobatik-Weltmeiserschaft.",emoji:"🍕"},
  {q:"How many Stockwerke has das höchste Gebäude the world (Burj Khalifa)?",a:163,unit:"Stockwerke",hint:"828 meters – höchstes Gebäude the world.",emoji:"🏙️"},
  {q:"How many times öffnete der Rekordhalter a Flasche in einer Minute?",a:67,unit:"times",hint:"with einem Korkenzieher – world record.",emoji:"🍾"},
  {q:"How many hours hielt a human a Kerze over einem Wasserbecken?",a:12,unit:"hours",hint:"Eine brennende Kerze 12 hours balancieren.",emoji:"🕯️"},
  {q:"How many km lief das schnellste Dromedar im Sprint?",a:65,unit:"km/h",hint:"Kamele können kurz sehr schnell rennen.",emoji:"🐪"},
  {q:"How many m weit flog der weiteste Papierflieger?",a:88.3,unit:"meterss",hint:"John Collins entwasf den Flieger, Joe Ayoob wasf ihn.",emoji:"✈️"},
  {q:"How many hours lud a human Videos on YouTube als Dauerlauf hoch?",a:100,unit:"hours",hint:"hours ununterbrochenes Video-Uploading.",emoji:"📹"},
  {q:"How many meters lang was the longest Schal?",a:4565,unit:"meterss",hint:"in China gestrickt for den world record.",emoji:"🧣"},
  {q:"How many meters lang was the longest Spagat?",a:12,unit:"meters Kette",hint:"people bildeten a Spagat-Kette.",emoji:"🤸"},
  {q:"How heavy was das schwerste Würfelsugar-Modell in kg?",a:400,unit:"kg",hint:"from 2 million Würfelsugar gebaut.",emoji:"🍬"},
  {q:"How many minutes hielt a Team a Wasserball-Spiel ohne Unterbrechung?",a:24,unit:"hours",hint:"24h Wasserball am Stück.",emoji:"🤽"},
  {q:"How many hours boxte a man ununterbrochen gegen einen Sandsack?",a:114,unit:"hours",hint:"Fast 5 days nonstop boxen.",emoji:"🥊"},
  {q:"How many meters lang was the longest selbst getimeste Bildstreifen?",a:2000,unit:"meterss",hint:"Ein 2 km longes Bild.",emoji:"🎨"},
  {q:"How many kg Brot backte der Rekordhalter in einer Stunde?",a:100,unit:"Brote",hint:"Laib Brot in 60 minutes.",emoji:"🍞"},
  {q:"How many hours fuhr a human on einem Einrad als Rekord?",a:105,unit:"hours",hint:"over 4 days on einem Einrad.",emoji:"🎪"},
  {q:"How many meters weit schoss the worldrekord-Pfeilbogen?",a:1410,unit:"meterss",hint:"Sultan Selim der Erste schoss 1,41 km weit.",emoji:"🏹"},
  {q:"How many Schritte machte the fastest 100m-Sprint?",a:41,unit:"Schritte",hint:"Usain Bolt needse nur 41 Schritte for 100m.",emoji:"⚡"},
  {q:"How many hours sprach a human nonstop als Redner?",a:93,unit:"hours",hint:"Fast 4 days ununterbrochenes Reden.",emoji:"🗣️"},
  {q:"How many kilometerss joggten Mitglieder einer Staffel in 24 hours?",a:1000,unit:"km",hint:"24-hours-Staffellauf-world record.",emoji:"🏃"},
  {q:"How many Nüsse knackte der Rekordhalter in einer Minute?",a:108,unit:"Nüsse",hint:"whalenüsse in 60 seconds geknackt.",emoji:"🥜"},
  {q:"How big was the largest Puzzle the world in Teilen?",a:551232,unit:"Teile",hint:"the largest kommerziell erhältliche Puzzle.",emoji:"🧩"},
  {q:"How many hours stand a human in Ameisen als world record?",a:1,unit:"Stunde",hint:"in einer Kise voller Ameisen – sehr tapfer.",emoji:"🐜"},
  {q:"How many meters hoch stapelte der Rekordhalter Münzen?",a:1,unit:"meterss",hint:"meters hoher Münzturm.",emoji:"🪙"},
  {q:"How many Kubikmeters haste the largest Schneeman the world?",a:37000,unit:"tons Schnee",hint:"Ein Schneemann in Maine USA from 2008.",emoji:"⛄"},
  {q:"How heavy was die schwerste Wassermelone in kg?",a:159,unit:"kg",hint:"Chris Kent from den USA züchtete sie 2013.",emoji:"🍉"},
  {q:"How many hours spielte a Pärchen Brettspiele nonstop?",a:61,unit:"hours",hint:"over 2,5 days Brettspiele am Stück.",emoji:"🎲"},
  {q:"How many meters lang was the longest Weihnachtsbaum?",a:67,unit:"meterss",hint:"Ein Riesenbaum in Portugal 1999.",emoji:"🎄"},
  {q:"How many hours tanzte a Pärchen Tango ununterbrochen?",a:22,unit:"hours",hint:"Argentinischer Tango-world record.",emoji:"💃"},
  {q:"How many meters lang was the longest Schnurrbart?",a:4.29,unit:"meterss",hint:"Ram Singh Chauhan from Indien.",emoji:"👨"},
  {q:"How many people sprangen gleichzeitig on Trampolinen?",a:1000,unit:"people",hint:"Trampolinge-Springer gleichzeitig.",emoji:"🤸"},
  {q:"How heavy was the heaviest dog je in kg?",a:155,unit:"kg",hint:"Ein Englischer Mastiff namens Zorba.",emoji:"🐕"},
  {q:"How many hours trug jemand Eiswürfel am body?",a:1,unit:"Stunde",hint:"Wim Hof hält Kälterekorde – bis to 1h45min.",emoji:"🧊"},
  {q:"How many meters lang was the longest river-Schwimmer nonstop?",a:514,unit:"km",hint:"Martin Strel schwamm den gesamten Mississippi.",emoji:"🏊"},
  {q:"How many hours sang a human allein ununterbrochen?",a:105,unit:"hours",hint:"Fast 4,5 days Dauersingen.",emoji:"🎤"},
  {q:"How many meters lang was the longest Brezel?",a:26,unit:"meterss",hint:"Eine Riesenbrezel from Bayern.",emoji:"🥨"},
  {q:"How many km lief the fastest 100-km-Läufer?",a:100,unit:"km in 6h17min",hint:"Nao Kazami (Japan) 2018.",emoji:"🏃"},
  {q:"How many hours sprach a Politiker the longest Parlamentsrede?",a:25,unit:"hours",hint:"Ein australischer Senator sprach 25 hours am Stück.",emoji:"🎙️"},
  {q:"How many hours sang the worldrekord-Sänger ununterbrochen?",a:105,unit:"hours",hint:"4,5 days – in Indien aufgestellt.",emoji:"🎤"},
  {q:"How many meters sprang a human from einem Flugzeug ohne Fallschirm?",a:7600,unit:"meterss",hint:"Luke Aikins landete 2016 in einem Netz.",emoji:"🪂"},
  {q:"How many km/h schnell was the fastest Mensch on Skiern?",a:254,unit:"km/h",hint:"Ivan Origone from Italien, 2016.",emoji:"⛷️"},
  {q:"How many hours fuhr the longest Fahrradfahrer nonstop?",a:91,unit:"hours",hint:"over 3 days nonstop Radfahren.",emoji:"🚴"},
  {q:"How many meters hoch kletterte der jüngste Everest-Bezwinger in yearsn?",a:13,unit:"years",hint:"Jordan Romero bestieg ihn 2010 with 13 yearsn.",emoji:"🏔️"},
  {q:"How many hours tanzte a einzelner Mensch als Rekord?",a:126,unit:"hours",hint:"over 5 days tanzen ohne Unterbrechung.",emoji:"💃"},
  {q:"How many meters hoch is the worldgrößte Sandberg?",a:100,unit:"meterss",hint:"from Sand aufgetürmt for den world record.",emoji:"🏖️"},
  {q:"How many kg Würstchen rollte der Rekordhalter in einer Minute?",a:50,unit:"Würstchen",hint:"Würste in 60 seconds gerollt.",emoji:"🌭"},
  {q:"How many hours nonstop las a Vorleser als Rekord?",a:200,unit:"hours",hint:"8 days ununterbrochen vorlesen.",emoji:"📖"},
  {q:"How many meters lang was the longest peoplepyramide?",a:12,unit:"Ebenen",hint:"Edaysn peoplepyramide.",emoji:"🤸"},
  {q:"How many liters beer trank der Rekordhalter in einer Minute?",a:1.3,unit:"literss",hint:"1,3 liters in 60 seconds.",emoji:"🍺"},
  {q:"How many hours spielte a Pianis als Rekord nonstop?",a:120,unit:"hours",hint:"5 days Klavier ohne Unterbrechung.",emoji:"🎹"},
  {q:"How many km/h fuhr the fastest Rollschuhfahrer?",a:130,unit:"km/h",hint:"Bergab on Inlineskates.",emoji:"🛼"},
  {q:"How many hours hielt jemand einen Handstand?",a:56,unit:"minutes",hint:"Fast a Stunde kopfüber.",emoji:"🤸"},
  {q:"How many meters weit wasf der Rekordhalter einen Bumerang?",a:1401,unit:"meterss",hint:"Und er kam zurück.",emoji:"🪃"},
  {q:"How many hours jonglierte jemand nonstop?",a:12,unit:"hours",hint:"with 3 Bällen ohne Unterbrechung.",emoji:"🎪"},
  {q:"How many meters lang was the longest Schal?",a:4565,unit:"meterss",hint:"Fast 5 km Schal gestrickt.",emoji:"🧣"},
  {q:"How many hours blieb jemand wach als world record?",a:449,unit:"hours",hint:"Randy Gardner – offizieller world record 264h.",emoji:"😴"},
  {q:"How many Liegestütze schaffte jemand with einem Arm in einer Minute?",a:64,unit:"Liegestütze",hint:"with einem Arm – ein-Arm-Liegestütz-Rekord.",emoji:"💪"},
  {q:"How many km weit segelte a human allein nonstop?",a:33000,unit:"km",hint:"Die Weltumsegelung solo und nonstop.",emoji:"⛵"},
  {q:"How many Stufen stieg the fastest Treppenläufer per minute?",a:1600,unit:"Stufen",hint:"Beim Wolkenkratzer-Rennen.",emoji:"🏃"},
  {q:"How many grams Chili aß der Rekordhalter in 3 minutes?",a:500,unit:"grams",hint:"500g der schärfsten Chili in 3 minutes.",emoji:"🌶️"},
  {q:"How many meters lang was the largest Sandschloss?",a:500,unit:"meterss",hint:"Ein 500 meters langer Sandwhalel.",emoji:"🏰"},
  {q:"How many hours kochte the worldrekord-Koch nonstop?",a:68,unit:"hours",hint:"Fast 3 days kochen.",emoji:"👨‍🍳"},
  {q:"How many meters hoch was das höchste jetimess gebaute Kspecieshaus?",a:7.9,unit:"meterss",hint:"Bryan mountain baute es in Las Vegas.",emoji:"🃏"},
  {q:"How many people passten in den kleinsten Serienwagen?",a:21,unit:"people",hint:"in einen Mini Cooper gequetscht.",emoji:"🚗"},
  {q:"How many hours takese the longest Party?",a:168,unit:"hours",hint:"7 days feiern – dokumentiert.",emoji:"🎉"},
  {q:"How many meters weit was a Frisbee geworfen?",a:338,unit:"meterss",hint:"world record im Frisbee-Weitwurf.",emoji:"🥏"},
  {q:"How many km/h erreichte the fastest Papierflugzeug-Wurf?",a:238,unit:"km/h",hint:"with einer Schleuder abgeschossen.",emoji:"✈️"},
  {q:"How many seconds needse the fastest Mensch for einen liters water?",a:5,unit:"seconds",hint:"drink ohne to schlucken aufzuhören.",emoji:"💧"},
  {q:"How many hours aß jemand nonstop als Rekord?",a:72,unit:"hours",hint:"3 days essen – with kurzen Pausen.",emoji:"🍽️"},
  {q:"How many meters lang was the largest Puzzle?",a:6000,unit:"meterss",hint:"6 km longes Riesenpuzzle.",emoji:"🧩"},
  {q:"How many people stellten den world record im hairsschneiden gleichzeitig?",a:394,unit:"people",hint:"Friseure schnitten gleichzeitig.",emoji:"💇"},
  {q:"How many hours fuhr the longest Kettenkarussell?",a:24,unit:"hours",hint:"24h Karussell fahren.",emoji:"🎡"},
];
