// 🏛️ POLITICS & POWER – Adults – 247 questions
export default [
  {id:"polit_001",q:"How many years was Angela Merkel chancellor of Germany?",a:16,unit:"years",hint:"From 2005 to 2021.",emoji:"🇩🇪"},
  {id:"polit_002",q:"How many countries are members of the UN?",a:193,unit:"countries",hint:"Founded in 1945 with 51 members.",emoji:"🌍"},
  {id:"polit_003",q:"How many billion dollars does the US spend on campaigning per presidential election?",a:14,unit:"billion dollars",hint:"2020 was the most expensive election in history.",emoji:"🗳️"},
  {id:"polit_004",q:"How many members does the US Senate have?",a:100,unit:"senators",hint:"2 per state – 50 states.",emoji:"🏛️"},
  {id:"polit_005",q:"How many countries are in the EU?",a:27,unit:"countries",hint:"After Brexit – the UK left in 2020.",emoji:"🇪🇺"},
  {id:"polit_006",q:"How many years was Adolf Hitler in power?",a:12,unit:"years",hint:"From 1933 to 1945.",emoji:"☮️"},
  {id:"polit_007",q:"How many members does the Bundestag have?",a:736,unit:"members",hint:"After the 2021 election – a record size.",emoji:"🏛️"},
  {id:"polit_008",q:"In what year did Martin Luther King deliver his 'I Have a Dream' speech?",a:1963,unit:"year",hint:"On August 28, 1963, in Washington.",emoji:"✊"},
  {id:"polit_009",q:"How many countries have an atomic bomb?",a:9,unit:"countries",hint:"USA, Russia, UK, France, China, India, Pakistan, Israel, North Korea.",emoji:"☢️"},
  {id:"polit_010",q:"How many thousand dollars does a US president earn per year?",a:400,unit:"thousand dollars",hint:"$400,000 annually.",emoji:"🏛️"},
  {id:"polit_011",q:"How many members does the European Parliament have?",a:720,unit:"members",hint:"As of the 2024 election.",emoji:"🇪🇺"},
  {id:"polit_012",q:"How many countries are in the G20?",a:20,unit:"countries",hint:"Actually 19 countries + the EU.",emoji:"🌍"},
  {id:"polit_013",q:"How many billion euros does EU bureaucracy cost per year?",a:170,unit:"billion euros",hint:"The EU's total budget.",emoji:"🇪🇺"},
  {id:"polit_014",q:"How many years did Kim Jong-il rule North Korea?",a:17,unit:"years",hint:"From 1994 until his death in 2011.",emoji:"🇰🇵"},
  {id:"polit_015",q:"How many million dollars is Donald Trump's net worth?",a:3000,unit:"million dollars",hint:"Fluctuates a lot – as of 2024.",emoji:"🏙️"},
  {id:"polit_016",q:"How many countries have a monarchy?",a:43,unit:"countries",hint:"Including 16 with the British king as head of state.",emoji:"👑"},
  {id:"polit_017",q:"How many billion euros does Germany spend on development aid?",a:32,unit:"billion euros",hint:"One of the largest donors worldwide.",emoji:"🤝"},
  {id:"polit_018",q:"How many directors has the CIA had in total?",a:21,unit:"directors",hint:"Since its founding in 1947.",emoji:"🕵️"},
  {id:"polit_019",q:"In what year was the death penalty abolished in Germany?",a:1949,unit:"year",hint:"Enshrined in the Basic Law.",emoji:"⚖️"},
  {id:"polit_020",q:"How many billion dollars does US defense contractor Lockheed Martin earn per year?",a:67,unit:"billion dollars",hint:"The largest defense contractor in the world.",emoji:"✈️"},
  {id:"polit_021",q:"How many years was Fidel Castro in power in Cuba?",a:49,unit:"years",hint:"From 1959 to 2008.",emoji:"🇨🇺"},
  {id:"polit_022",q:"How many countries sanctioned Russia after the invasion of Ukraine?",a:40,unit:"countries",hint:"As of 2022.",emoji:"🇷🇺"},
  {id:"polit_023",q:"In what year was the International Criminal Court founded?",a:2002,unit:"year",hint:"In The Hague, Netherlands.",emoji:"⚖️"},
  {id:"polit_024",q:"How many million votes did Obama receive in his first election?",a:69,unit:"million",hint:"In 2008, against John McCain.",emoji:"🗳️"},
  {id:"polit_025",q:"In what year did the first G7 summit take place?",a:1975,unit:"year",hint:"In Rambouillet, France.",emoji:"🌍"},
  {id:"polit_026",q:"How many members does the British House of Commons have?",a:650,unit:"members",hint:"House of Commons.",emoji:"🏴"},
  {id:"polit_027",q:"How many billion euros does the German military (Bundeswehr) cost per year?",a:52,unit:"billion euros",hint:"Significantly increased after the 2022 'Zeitenwende' (turning point).",emoji:"⚔️"},
  {id:"polit_028",q:"In what year did Boris Johnson become British Prime Minister?",a:2019,unit:"year",hint:"After Theresa May.",emoji:"🇬🇧"},
  {id:"polit_029",q:"How many countries are in OPEC?",a:13,unit:"countries",hint:"The Organization of the Petroleum Exporting Countries.",emoji:"🛢️"},
  {id:"polit_030",q:"How many billion dollars is Vladimir Putin's estimated net worth?",a:200,unit:"billion dollars",hint:"Estimates – unofficial.",emoji:"🇷🇺"},
  {id:"polit_031",q:"In what year was the European Court of Justice founded?",a:1952,unit:"year",hint:"In Luxembourg.",emoji:"🇪🇺"},
  {id:"polit_032",q:"How many US presidents have been assassinated?",a:4,unit:"presidents",hint:"Lincoln, Garfield, McKinley, Kennedy.",emoji:"🏛️"},
  {id:"polit_033",q:"How many thousand members does the SPD have?",a:380,unit:"thousand",hint:"Significantly declined.",emoji:"🌹"},
  {id:"polit_034",q:"In what year was the death penalty abolished in France?",a:1981,unit:"year",hint:"Under President Mitterrand.",emoji:"🇫🇷"},
  {id:"polit_035",q:"How many countries have no army of their own?",a:23,unit:"countries",hint:"Including Iceland, Costa Rica, Panama.",emoji:"🕊️"},
  {id:"polit_036",q:"How many billion dollars does China spend on espionage per year?",a:20,unit:"billion dollars",hint:"Estimates from Western intelligence agencies.",emoji:"🕵️"},
  {id:"polit_037",q:"In what year did the Kyoto Protocol take effect?",a:2005,unit:"year",hint:"Adopted in 1997, took effect in 2005.",emoji:"🌍"},
  {id:"polit_038",q:"How many million people voted in the Brexit referendum?",a:33,unit:"million",hint:"51.9% voted Leave.",emoji:"🇬🇧"},
  {id:"polit_039",q:"How many years has Kim Jong-un been in power?",a:13,unit:"years",hint:"Since his father's death in 2011.",emoji:"🇰🇵"},
  {id:"polit_040",q:"In what year was the Basic Law (Grundgesetz) adopted?",a:1949,unit:"year",hint:"On May 23, 1949.",emoji:"🇩🇪"},
  {id:"polit_041",q:"How many billion dollars does the UN budget cost per year?",a:3,unit:"billion dollars",hint:"The regular budget – excluding peacekeeping missions.",emoji:"🌍"},
  {id:"polit_042",q:"In what year did Churchill deliver his 'Iron Curtain' speech?",a:1946,unit:"year",hint:"In Fulton, Missouri.",emoji:"🇬🇧"},
  {id:"polit_043",q:"How many billion dollars did Elon Musk's political influence over X cost him?",a:44,unit:"billion dollars",hint:"What he paid for Twitter/X.",emoji:"𝕏"},
  {id:"polit_044",q:"How many seats does the CDU/CSU hold in the current Bundestag?",a:197,unit:"seats",hint:"After the 2025 federal election.",emoji:"🇩🇪"},
  {id:"polit_045",q:"In what year did the French Revolution take place?",a:1789,unit:"year",hint:"The storming of the Bastille on July 14.",emoji:"🗽"},
  {id:"polit_046",q:"How many million dollars does Saudi Arabia spend on lobbying in the US?",a:100,unit:"million dollars",hint:"Officially – unofficially much more.",emoji:"🇸🇦"},
  {id:"polit_047",q:"How many years was Helmut Kohl chancellor of Germany?",a:16,unit:"years",hint:"From 1982 to 1998.",emoji:"🇩🇪"},
  {id:"polit_048",q:"In what year did Turkey join NATO?",a:1952,unit:"year",hint:"Together with Greece.",emoji:"🇹🇷"},
  {id:"polit_049",q:"How many million refugees were there worldwide in 2023?",a:110,unit:"million",hint:"Record-high numbers due to ongoing crises.",emoji:"🏕️"},
  {id:"polit_050",q:"How many thousand euros does an EU Commissioner earn per year?",a:250,unit:"thousand euros",hint:"Including allowances.",emoji:"🇪🇺"},
  {id:"polit_051",q:"How many nuclear warheads does Russia have?",a:5977,unit:"warheads",hint:"As of 2023 – the largest arsenal in the world.",emoji:"☢️"},
  {id:"polit_052",q:"In what year was the Warsaw Pact dissolved?",a:1991,unit:"year",hint:"Simultaneously with the collapse of the Soviet Union.",emoji:"☭"},
  {id:"polit_053",q:"How many billion dollars is the global lobbying market worth?",a:3,unit:"billion dollars",hint:"In the US alone.",emoji:"💼"},
  {id:"polit_054",q:"In what year was the European Union officially founded?",a:1993,unit:"year",hint:"The Maastricht Treaty took effect.",emoji:"🇪🇺"},
  {id:"polit_055",q:"How many billion dollars does the US military budget cost per year?",a:858,unit:"billion dollars",hint:"More than the next 10 countries combined.",emoji:"⚔️"},
  {id:"polit_056",q:"How many years did Nelson Mandela serve as president?",a:5,unit:"years",hint:"From 1994 to 1999.",emoji:"✊"},
  {id:"polit_057",q:"In what year was the International Monetary Fund founded?",a:1944,unit:"year",hint:"In Bretton Woods, New Hampshire.",emoji:"💰"},
  {id:"polit_058",q:"How many thousand members does the CDU have?",a:370,unit:"thousand",hint:"As of 2023 – significantly declined.",emoji:"🇩🇪"},
  {id:"polit_059",q:"How many countries use the euro as their currency?",a:20,unit:"countries",hint:"The eurozone, as of 2023.",emoji:"💶"},
  {id:"polit_060",q:"In what year did the UK leave the EU?",a:2020,unit:"year",hint:"Brexit on January 31, 2020.",emoji:"🇬🇧"},
  {id:"polit_061",q:"How many billion euros does Germany contribute net to the EU?",a:17,unit:"billion euros",hint:"The largest net contributor.",emoji:"🇩🇪"},
  {id:"polit_062",q:"How many people sat in the defendants' dock at the Nuremberg trials?",a:24,unit:"people",hint:"Main defendants in the first trial.",emoji:"⚖️"},
  {id:"polit_063",q:"In what year was the World Health Organization founded?",a:1948,unit:"year",hint:"WHO – April 7, 1948.",emoji:"🏥"},
  {id:"polit_064",q:"How many million votes did Hitler receive in the last free election in 1932?",a:13,unit:"million",hint:"37.4% of the vote.",emoji:"☮️"},
  {id:"polit_065",q:"How many countries have ever used a UN veto?",a:5,unit:"countries",hint:"USA, Russia, China, UK, France – the P5.",emoji:"🌍"},
  {id:"polit_066",q:"In what year was Angela Merkel elected chancellor?",a:2005,unit:"year",hint:"The first woman in this office.",emoji:"🇩🇪"},
  {id:"polit_067",q:"How many billion euros flow into corruption in the EU each year?",a:120,unit:"billion euros",hint:"An estimate from the European Commission.",emoji:"💸"},
  {id:"polit_068",q:"How many people worked for the East German Stasi?",a:90000,unit:"full-time staff",hint:"Plus 180,000 unofficial informants.",emoji:"🧱"},
  {id:"polit_069",q:"In what year was Willy Brandt awarded the Nobel Peace Prize?",a:1971,unit:"year",hint:"For his Ostpolitik.",emoji:"🕊️"},
  {id:"polit_070",q:"How many million square kilometers does Russia cover?",a:17,unit:"million km²",hint:"The largest country in the world.",emoji:"🇷🇺"},
  {id:"polit_071",q:"What percentage of the Bundestag are lawyers?",a:15,unit:"%",hint:"Lawyers are overrepresented.",emoji:"⚖️"},
  {id:"polit_072",q:"In what year did the Syrian civil war begin?",a:2011,unit:"year",hint:"As part of the Arab Spring.",emoji:"🕊️"},
  {id:"polit_073",q:"How many billion dollars does the US spend on intelligence agencies?",a:90,unit:"billion dollars",hint:"The total intelligence budget.",emoji:"🕵️"},
  {id:"polit_074",q:"How many years was Robert Mugabe in power in Zimbabwe?",a:37,unit:"years",hint:"From 1980 to 2017.",emoji:"🇿🇼"},
  {id:"polit_075",q:"In what year did South Africa become a democracy?",a:1994,unit:"year",hint:"The first free elections after the end of apartheid.",emoji:"✊"},
  {id:"polit_076",q:"How many thousand euros does a member of the Bundestag earn over their term?",a:500,unit:"thousand euros",hint:"Salary plus pension entitlements.",emoji:"💶"},
  {id:"polit_077",q:"How many countries have a woman as head of government (as of 2024)?",a:26,unit:"countries",hint:"A rising trend worldwide.",emoji:"👩"},
  {id:"polit_078",q:"In what year was the Nuclear Non-Proliferation Treaty signed?",a:1968,unit:"year",hint:"The NPT.",emoji:"☢️"},
  {id:"polit_079",q:"How many trillion dollars has the Iraq War cost the US?",a:2,unit:"trillion dollars",hint:"Including long-term costs.",emoji:"⚔️"},
  {id:"polit_080",q:"In what year was the European Convention on Human Rights signed?",a:1950,unit:"year",hint:"On November 4, 1950, in Rome.",emoji:"⚖️"},
  {id:"polit_081",q:"How many billion euros flow out of Germany into tax havens?",a:100,unit:"billion euros",hint:"Estimates per year.",emoji:"💸"},
  {id:"polit_082",q:"How many days did the longest government formation in Germany take?",a:171,unit:"days",hint:"2017 – the Jamaica coalition talks failed.",emoji:"🇩🇪"},
  {id:"polit_083",q:"In what year was the Universal Declaration of Human Rights adopted?",a:1948,unit:"year",hint:"On December 10, 1948, by the UN.",emoji:"📜"},
  {id:"polit_084",q:"How many trillion dollars does China's Belt and Road Initiative cover?",a:1,unit:"trillion dollars",hint:"China's global infrastructure project.",emoji:"🌏"},
  {id:"polit_085",q:"In what year did Russia's invasion of Ukraine begin?",a:2022,unit:"year",hint:"On February 24, 2022.",emoji:"🕊️"},
  {id:"polit_086",q:"How many billion euros has the Ukraine war cost Germany so far?",a:20,unit:"billion euros",hint:"In aid and indirect costs.",emoji:"🇺🇦"},
  {id:"polit_087",q:"How many countries took part in sanctioning Russia?",a:40,unit:"countries",hint:"The Western alliance.",emoji:"🌍"},
  {id:"polit_088",q:"In what year did Joe Biden become US president?",a:2021,unit:"year",hint:"Sworn in on January 20, 2021.",emoji:"🇺🇸"},
  {id:"polit_089",q:"How many million eligible voters are there in Germany?",a:61,unit:"million",hint:"For federal elections.",emoji:"🗳️"},
  {id:"polit_090",q:"How many countries are permanent members of the UN Security Council?",a:5,unit:"countries",hint:"USA, Russia, China, UK, France.",emoji:"🌍"},
  {id:"polit_091",q:"In what year did the Cold War end?",a:1991,unit:"year",hint:"With the collapse of the Soviet Union.",emoji:"🕊️"},
  {id:"polit_092",q:"How many billion dollars did the Marshall Plan cost after World War II?",a:13,unit:"billion dollars",hint:"At the time – worth about $160 billion today.",emoji:"🇺🇸"},
  {id:"polit_093",q:"In what year was the CSU founded?",a:1945,unit:"year",hint:"Officially founded on January 8, 1946.",emoji:"🇩🇪"},
  {id:"polit_094",q:"How many nuclear power plants has Germany shut down by 2023?",a:17,unit:"plants",hint:"The last one on April 15, 2023.",emoji:"⚡"},
  {id:"polit_095",q:"How many thousand euros annually does the EU Commission president earn?",a:320,unit:"thousand euros",hint:"€322,000 gross.",emoji:"🇪🇺"},
  {id:"polit_096",q:"In what year did the EU receive the Nobel Peace Prize?",a:2012,unit:"year",hint:"For six decades of peace in Europe.",emoji:"🕊️"},
  {id:"polit_097",q:"How many million forced laborers were there in the Third Reich?",a:13,unit:"million",hint:"From all over Europe.",emoji:"☮️"},
  {id:"polit_098",q:"In what year was the German Green Party founded?",a:1980,unit:"year",hint:"On January 13, 1980, in Karlsruhe.",emoji:"🌿"},
  {id:"polit_099",q:"How many billion euros does German social welfare cost per year?",a:40,unit:"billion euros",hint:"Bürgergeld and social transfers.",emoji:"🤝"},
  {id:"polit_100",q:"How many countries recognize Crimea as Russian?",a:5,unit:"countries",hint:"Only a few of Russia's allies.",emoji:"🇷🇺"},
  {id:"polit_101",q:"In what year did Olaf Scholz become chancellor?",a:2021,unit:"year",hint:"On December 8, 2021.",emoji:"🇩🇪"},
  {id:"polit_102",q:"How many million dollars does a US Senate campaign cost on average?",a:12,unit:"million dollars",hint:"A strongly rising trend.",emoji:"🗳️"},
  {id:"polit_103",q:"How many countries still have the death penalty?",a:55,unit:"countries",hint:"China, Iran, and Saudi Arabia lead the way.",emoji:"⚖️"},
  {id:"polit_104",q:"In what year was the FDP founded?",a:1948,unit:"year",hint:"On December 11, 1948.",emoji:"🇩🇪"},
  {id:"polit_105",q:"How many billion francs does Swiss neutrality cost per year?",a:5,unit:"billion francs",hint:"Military spending by neutral Switzerland.",emoji:"🇨🇭"},
  {id:"polit_106",q:"In what year was the AfD party founded?",a:2013,unit:"year",hint:"On February 6, 2013.",emoji:"🇩🇪"},
  {id:"polit_107",q:"How many million tons of CO₂ did Germany save in 2023?",a:44,unit:"million tons",hint:"Thanks to the energy transition.",emoji:"🌿"},
  {id:"polit_108",q:"How many billion dollars in weapons has the US delivered to Ukraine?",a:75,unit:"billion dollars",hint:"As of late 2023.",emoji:"🇺🇦"},
  {id:"polit_109",q:"In what year did West Germany become a full member of the UN?",a:1973,unit:"year",hint:"At the same time as East Germany.",emoji:"🇩🇪"},
  {id:"polit_110",q:"How many laws does the Bundestag pass per year?",a:250,unit:"laws",hint:"About 250 new federal laws.",emoji:"📜"},
  {id:"polit_111",q:"In what year was Amnesty International founded?",a:1961,unit:"year",hint:"By Peter Benenson in London.",emoji:"🕯️"},
  {id:"polit_112",q:"How many billion dollars is the global arms trade worth?",a:600,unit:"billion dollars",hint:"The annual legal arms market.",emoji:"⚔️"},
  {id:"polit_113",q:"How many days did it take Germany to form a government after the election?",a:171,unit:"days",hint:"2017 – a record.",emoji:"🇩🇪"},
  {id:"polit_114",q:"In what year was Donald Trump sworn in as president for the first time?",a:2017,unit:"year",hint:"On January 20, 2017.",emoji:"🇺🇸"},
  {id:"polit_115",q:"How many million more votes did Hillary Clinton get than Trump in 2016?",a:2.9,unit:"million",hint:"She won the popular vote but lost the Electoral College.",emoji:"🗳️"},
  {id:"polit_116",q:"How many countries currently have active wars?",a:50,unit:"countries",hint:"As of 2023 – many conflicts worldwide.",emoji:"☮️"},
  {id:"polit_117",q:"In what year was Greenpeace founded?",a:1971,unit:"year",hint:"In Vancouver, Canada.",emoji:"🌿"},
  {id:"polit_118",q:"How many billion euros does EU agricultural policy cost per year?",a:58,unit:"billion euros",hint:"Almost a third of the EU budget.",emoji:"🌾"},
  {id:"polit_119",q:"What percentage of Bundestag members have no migration background?",a:95,unit:"%",hint:"Despite 25% of the population having one.",emoji:"📊"},
  {id:"polit_120",q:"In what year was the death penalty abolished in Switzerland?",a:1942,unit:"year",hint:"For civilians – the military followed only in 1992.",emoji:"🇨🇭"},
  {id:"polit_121",q:"How many hours per week does a member of the Bundestag work?",a:60,unit:"hours",hint:"Plenary sessions, committees, constituency work.",emoji:"💼"},
  {id:"polit_122",q:"How many billion euros do lobbyists spend in Brussels?",a:1.5,unit:"billion euros",hint:"Officially registered lobbying expenditures.",emoji:"💼"},
  {id:"polit_123",q:"In what year did Robert Habeck become a federal minister?",a:2021,unit:"year",hint:"Economy minister in the traffic-light coalition.",emoji:"🇩🇪"},
  {id:"polit_124",q:"What percentage of EU citizens trust the EU?",a:45,unit:"%",hint:"Standard Eurobarometer survey.",emoji:"🇪🇺"},
  {id:"polit_125",q:"How many billion francs in Russian economic assets has Switzerland frozen?",a:200,unit:"billion francs",hint:"Russian funds held in Switzerland.",emoji:"🇨🇭"},
  {id:"polit_126",q:"In what year was the UN Framework Convention on Climate Change founded?",a:1992,unit:"year",hint:"At the Rio conference.",emoji:"🌍"},
  {id:"polit_127",q:"How many million voters chose the SPD in 2021?",a:11.9,unit:"million",hint:"25.7% of the vote.",emoji:"🗳️"},
  {id:"polit_128",q:"How many countries have China as their largest trading partner?",a:120,unit:"countries",hint:"China dominates global trade (as of ~2024).",emoji:"🇨🇳"},
  {id:"polit_129",q:"In what year did the GDPR take effect?",a:2018,unit:"year",hint:"The General Data Protection Regulation, May 2018.",emoji:"🔒"},
  {id:"polit_130",q:"How many billion euros is the German state's stake in Volkswagen worth?",a:35,unit:"billion euros",hint:"The state of Lower Saxony holds 20% of VW.",emoji:"🚗"},
  {id:"polit_131",q:"How many days did the longest government formation in Belgium take?",a:652,unit:"days",hint:"A world record – 2010/2011.",emoji:"🇧🇪"},
  {id:"polit_132",q:"In what year did Vladimir Putin first become president?",a:2000,unit:"year",hint:"On May 7, 2000.",emoji:"🇷🇺"},
  {id:"polit_133",q:"How many million square kilometers does NATO territory cover in total?",a:25,unit:"million km²",hint:"A quarter of Earth's land area.",emoji:"🛡️"},
  {id:"polit_134",q:"How many billion euros does Germany's statutory pension insurance cost per year?",a:340,unit:"billion euros",hint:"The largest social spending category.",emoji:"👴"},
  {id:"polit_135",q:"In what year did Kennedy give his Berlin speech ('Ich bin ein Berliner')?",a:1963,unit:"year",hint:"On June 26, 1963.",emoji:"🇺🇸"},
  {id:"polit_136",q:"How many days did the longest session of the UN Security Council last?",a:5,unit:"days",hint:"Several marathon sessions throughout history (as of ~2024).",emoji:"🌍"},
  {id:"polit_137",q:"How many billion dollars has Saudi Arabia spent on sportswashing?",a:6,unit:"billion dollars",hint:"Golf, soccer, Formula 1.",emoji:"⚽"},
  {id:"polit_138",q:"In what year was women's suffrage introduced in Switzerland?",a:1971,unit:"year",hint:"One of the last Western countries to do so.",emoji:"🇨🇭"},
  {id:"polit_139",q:"How many million people fled Ukraine in 2022?",a:8,unit:"million",hint:"The largest refugee movement in Europe since 1945.",emoji:"🇺🇦"},
  {id:"polit_140",q:"How many billion euros does Germany's Bürgergeld cost per year?",a:20,unit:"billion euros",hint:"The successor to Hartz IV.",emoji:"🤝"},
  {id:"polit_141",q:"In what year was the Left party (PDS) founded?",a:1990,unit:"year",hint:"From the SED of East Germany.",emoji:"🇩🇪"},
  {id:"polit_142",q:"How many billion euros did Germany spend during the 2008 financial crisis?",a:500,unit:"billion euros",hint:"A bailout fund for banks.",emoji:"💰"},
  {id:"polit_143",q:"In what year was the European Court of Human Rights in Strasbourg founded?",a:1959,unit:"year",hint:"The European Court of Human Rights.",emoji:"⚖️"},
  {id:"polit_144",q:"How many countries have a left-populist government (as of 2024)?",a:15,unit:"countries",hint:"Latin America, Europe, and elsewhere.",emoji:"🌹"},
  {id:"polit_145",q:"How many billion dollars did Biden's infrastructure package cost?",a:1200,unit:"billion dollars",hint:"The Bipartisan Infrastructure Law of 2021.",emoji:"🏗️"},
  {id:"polit_146",q:"In what year did Gorbachev give his Perestroika speech?",a:1986,unit:"year",hint:"The beginning of reforms in the Soviet Union.",emoji:"☭"},
  {id:"polit_147",q:"How many million dollars does North Korea's nuclear program cost per year?",a:100,unit:"million dollars",hint:"Despite the country's poverty, heavy investment continues.",emoji:"☢️"},
  {id:"polit_148",q:"How many people work at the White House?",a:500,unit:"staff",hint:"Including kitchen, security, and staff.",emoji:"🏛️"},
  {id:"polit_149",q:"In what year did the Paris Climate Agreement take effect?",a:2016,unit:"year",hint:"On November 4, 2016.",emoji:"🌍"},
  {id:"polit_150",q:"How many billion euros are Germany's state-owned stakes worth?",a:100,unit:"billion euros",hint:"Deutsche Bahn, Deutsche Post, Lufthansa, and more.",emoji:"🇩🇪"},
  {id:"polit_151",q:"How many years was Konrad Adenauer chancellor of Germany?",a:14,unit:"years",hint:"From 1949 to 1963.",emoji:"🇩🇪"},
  {id:"polit_152",q:"How many billion dollars did the 2008 global financial crisis cost?",a:22000,unit:"billion dollars",hint:"$22 trillion in global losses.",emoji:"📉"},
  {id:"polit_153",q:"In what year did the Bosnian War begin?",a:1992,unit:"year",hint:"After Yugoslavia's declaration of independence.",emoji:"🕊️"},
  {id:"polit_154",q:"How many countries have joined the World Trade Organization?",a:164,unit:"countries",hint:"As of 2023.",emoji:"🌍"},
  {id:"polit_155",q:"How many billion dollars does Apple save per year through tax avoidance?",a:5,unit:"billion dollars",hint:"Through Ireland and other tax havens.",emoji:"🍎"},
  {id:"polit_156",q:"In what year was the Council of Europe founded?",a:1949,unit:"year",hint:"On May 5, 1949, in London.",emoji:"🇪🇺"},
  {id:"polit_157",q:"How many billion euros has Germany spent on Covid relief?",a:300,unit:"billion euros",hint:"Direct aid and indirect costs.",emoji:"😷"},
  {id:"polit_158",q:"In what year was the SPD founded?",a:1863,unit:"year",hint:"The oldest still-active German party.",emoji:"🌹"},
  {id:"polit_159",q:"How many million dollars does a modern fighter jet (F-35) cost?",a:80,unit:"million dollars",hint:"The F-35 – the most expensive fighter jet in history.",emoji:"✈️"},
  {id:"polit_160",q:"How many countries are in the Commonwealth of Nations?",a:56,unit:"countries",hint:"Former British colonies.",emoji:"👑"},
  {id:"polit_161",q:"In what year was the African Union founded?",a:2002,unit:"year",hint:"The successor to the Organisation of African Unity.",emoji:"🌍"},
  {id:"polit_162",q:"How many million votes did Trump get in the 2020 election?",a:74,unit:"million",hint:"A historically high number despite his loss.",emoji:"🗳️"},
  {id:"polit_163",q:"How many billion dollars has China invested in its Belt and Road infrastructure so far?",a:1000,unit:"billion dollars",hint:"The new Silk Road.",emoji:"🌏"},
  {id:"polit_164",q:"In what year was Transparency International founded?",a:1993,unit:"year",hint:"Fighting corruption worldwide.",emoji:"💸"},
  {id:"polit_165",q:"How many people fall victim to human trafficking worldwide each day?",a:800,unit:"people",hint:"An estimated 800 new victims daily.",emoji:"⛓️"},
  {id:"polit_166",q:"How many billion euros does German public broadcasting cost per year?",a:10,unit:"billion euros",hint:"ARD, ZDF, and Deutschlandradio combined.",emoji:"📺"},
  {id:"polit_167",q:"In what year was the first referendum held in Switzerland?",a:1848,unit:"year",hint:"Direct democracy since its founding.",emoji:"🇨🇭"},
  {id:"polit_168",q:"How many seats does the German Bundestag have?",a:736,unit:"seats",hint:"736 seats (as of 2021) – officially 598 standard seats.",emoji:"🏛️"},
  {id:"polit_169",q:"How many members does NATO have?",a:32,unit:"members",hint:"32 members – Sweden joined in 2024.",emoji:"🛡️"},
  {id:"polit_170",q:"How many countries still have the death penalty?",a:55,unit:"countries",hint:"About 55 countries – but only ~20 still carry it out.",emoji:"⚖️"},
  {id:"polit_171",q:"What percentage of Germans vote (2021 federal election)?",a:76,unit:"%",hint:"76.6% turnout – in 2017 it was 76.2%.",emoji:"🗳️"},
  {id:"polit_172",q:"How many euros of national debt does Germany have per capita?",a:29000,unit:"euros",hint:"About €29,000 per person – total debt ~€2.5 trillion.",emoji:"💰"},
  {id:"polit_173",q:"How many countries does the European Union have?",a:27,unit:"countries",hint:"27 members – without the UK since Brexit (2020).",emoji:"🇪🇺"},
  {id:"polit_174",q:"How many years does a US president's term last?",a:4,unit:"years",hint:"4 years – a maximum of 2 terms (8 years).",emoji:"🇺🇸"},
  {id:"polit_175",q:"How many people worldwide are eligible to vote?",a:4000,unit:"million",hint:"About 4 billion eligible voters worldwide.",emoji:"🗳️"},
  {id:"polit_176",q:"How many countries are permanent members of the UN Security Council?",a:5,unit:"countries",hint:"USA, Russia, China, France, United Kingdom.",emoji:"🌍"},
  {id:"polit_177",q:"How many member states does the United Nations have?",a:193,unit:"countries",hint:"193 member states – almost every country in the world.",emoji:"🌐"},
  {id:"polit_178",q:"How many official languages does the EU recognize?",a:24,unit:"languages",hint:"24 official languages – translation costs: about €1 billion/year.",emoji:"🗣️"},
  {id:"polit_179",q:"How many members does the European Parliament have?",a:720,unit:"members",hint:"720 members (from 2024) from 27 countries.",emoji:"🇪🇺"},
  {id:"polit_180",q:"How many years is the term of a Federal Constitutional Court justice in Germany?",a:12,unit:"years",hint:"12 years – no re-election possible, age limit of 68.",emoji:"⚖️"},
  {id:"polit_181",q:"What percentage of the federal budget goes to social spending?",a:30,unit:"%",hint:"About 30% of the budget – the single largest item.",emoji:"💶"},
  {id:"polit_182",q:"How many days does a US president have to form a cabinet?",a:70,unit:"days",hint:"Traditionally about 70 days from the election to the inauguration.",emoji:"🏛️"},
  {id:"polit_183",q:"How many countries have a monarchy?",a:43,unit:"countries",hint:"About 43 countries worldwide – 16 of them with the British monarch.",emoji:"👑"},
  {id:"polit_184",q:"What percentage of the world's population lives in a democracy?",a:45,unit:"%",hint:"About 45% – a declining trend, according to Freedom House.",emoji:"🗳️"},
  {id:"polit_185",q:"How many years did the Berlin Wall stand?",a:28,unit:"years",hint:"1961-1989 – exactly 28 years, 2 months, 27 days.",emoji:"🧱"},
  {id:"polit_186",q:"How many billion euros is the EU's annual budget?",a:170,unit:"billion euros",hint:"About €170 billion annually – about 1% of EU economic output.",emoji:"💶"},
  {id:"polit_187",q:"How many countries are in the G20?",a:20,unit:"countries",hint:"The G20 = 19 countries + the EU – representing 85% of the world economy.",emoji:"🌍"},
  {id:"polit_188",q:"How many years does a term in the German Bundesrat last?",a:0,unit:"fixed term",hint:"No fixed term – members are state ministers, changing with state governments.",emoji:"🏛️"},
  {id:"polit_189",q:"How many signatures does a popular initiative in Germany (Bundestag) need?",a:50000,unit:"signatures",hint:"50,000 signatures for a petition to the Bundestag.",emoji:"📝"},
  {id:"polit_190",q:"How many million members does the SPD have?",a:0.38,unit:"million",hint:"About 380,000 members (as of 2023) – significantly shrunk.",emoji:"🌹"},
  {id:"polit_191",q:"How many thousand euros does a Bundestag member earn per year?",a:125,unit:"thousand euros",hint:"About €10,500/month gross – plus an expense allowance.",emoji:"💰"},
  {id:"polit_192",q:"How many years did Angela Merkel govern as chancellor?",a:16,unit:"years",hint:"2005-2021 – four terms.",emoji:"👩‍⚖️"},
  {id:"polit_193",q:"How many chancellors has Germany had since 1949?",a:9,unit:"chancellors",hint:"Adenauer, Erhard, Kiesinger, Brandt, Schmidt, Kohl, Schröder, Merkel, Scholz.",emoji:"🇩🇪"},
  {id:"polit_194",q:"How many billion euros does Germany collect in tax revenue each year?",a:900,unit:"billion euros",hint:"About €900 billion in tax revenue (as of 2023).",emoji:"💶"},
  {id:"polit_195",q:"What percentage of the world's population lives under an authoritarian regime?",a:36,unit:"%",hint:"About 36% – over 2.7 billion people.",emoji:"🌍"},
  {id:"polit_196",q:"How many years was Nelson Mandela in prison?",a:27,unit:"years",hint:"1964-1990, on Robben Island and elsewhere.",emoji:"✊"},
  {id:"polit_197",q:"How many countries have no army?",a:22,unit:"countries",hint:"About 22 countries with no armed forces – including Iceland and Costa Rica.",emoji:"🕊️"},
  {id:"polit_198",q:"How many billion euros does Germany pay net to the EU?",a:17,unit:"billion euros",hint:"About €17 billion net contribution annually.",emoji:"🇩🇪"},
  {id:"polit_199",q:"What percentage of Germans trust the federal government?",a:25,unit:"%",hint:"According to 2023 surveys, only about 25% – a historic low.",emoji:"📊"},
  {id:"polit_200",q:"How many million members did the Nazi party (NSDAP) have at its peak?",a:8.5,unit:"million members",hint:"About 8.5 million members in 1945.",emoji:"📚"},
  {id:"polit_201",q:"How many kilometers long is the border between the US and Mexico?",a:3145,unit:"km",hint:"3,145 km – of which about 1,100 km is fortified.",emoji:"🌎"},
  {id:"polit_202",q:"How many days did the Cuban Missile Crisis last?",a:13,unit:"days",hint:"13 days in October 1962 – the world came close to World War III.",emoji:"☢️"},
  {id:"polit_203",q:"How many million votes did Hitler get in the 1932 election?",a:13.4,unit:"million votes",hint:"37.4% ≈ 13.4 million votes in the July 1932 Reichstag election.",emoji:"📚"},
  {id:"polit_204",q:"How many years did East Germany exist as a separate state?",a:41,unit:"years",hint:"1949-1990 – 41 years until reunification.",emoji:"🧱"},
  {id:"polit_205",q:"How many federal states does Germany have?",a:16,unit:"states",hint:"16 federal states – 3 of which are city-states (Berlin, Bremen, Hamburg).",emoji:"🇩🇪"},
  {id:"polit_206",q:"How many million people were deported under Stalin?",a:18,unit:"million",hint:"About 18 million in gulags – 1.5-1.8 million died there.",emoji:"📚"},
  {id:"polit_207",q:"How many euros does an F-35 fighter jet cost?",a:85,unit:"million euros",hint:"About €85 million – Germany bought 35 of them.",emoji:"✈️"},
  {id:"polit_208",q:"What percentage of GDP do NATO countries spend on defense (target)?",a:2,unit:"%",hint:"2% of GDP – Germany first hit the target in 2024.",emoji:"🛡️"},
  {id:"polit_209",q:"How many billion dollars was the Marshall Plan aid worth?",a:13,unit:"billion dollars",hint:"About $13 billion (1948-1952) – about $150 billion today.",emoji:"🇺🇸"},
  {id:"polit_210",q:"How many years was Winston Churchill British prime minister?",a:9,unit:"years",hint:"1940-1945 and 1951-1955 – about 9 years in total.",emoji:"🇬🇧"},
  {id:"polit_211",q:"How many million people live in the European Union?",a:450,unit:"million",hint:"About 450 million people across 27 EU countries.",emoji:"🇪🇺"},
  {id:"polit_212",q:"How many states does the US have?",a:50,unit:"states",hint:"50 states – Hawaii and Alaska were the last admitted, in 1959.",emoji:"🇺🇸"},
  {id:"polit_213",q:"What percentage of German electricity comes from renewable energy?",a:60,unit:"%",hint:"About 60% renewables in Germany (as of 2023).",emoji:"🌱"},
  {id:"polit_214",q:"How many billion euros does Germany's social welfare system cost per year?",a:1300,unit:"billion euros",hint:"About €1.3 trillion – the largest item in the federal budget (as of ~2024).",emoji:"🏥"},
  {id:"polit_215",q:"How many countries have diplomatically recognized China?",a:180,unit:"countries",hint:"About 180 countries – Taiwan, meanwhile, has only about 12.",emoji:"🇨🇳"},
  {id:"polit_216",q:"How many kilometers long is the Great Wall of China?",a:21000,unit:"km",hint:"21,196 km – all sections combined.",emoji:"🏯"},
  {id:"polit_217",q:"How many million people fled to Europe in 2015?",a:1,unit:"million",hint:"About 1 million refugees came to Europe in 2015.",emoji:"🌍"},
  {id:"polit_218",q:"How many days long is a Bundestag legislative term?",a:1461,unit:"days",hint:"4 years × 365.25 days ≈ 1,461 days.",emoji:"🏛️"},
  {id:"polit_219",q:"What percentage of Germans have a migration background?",a:26,unit:"%",hint:"About 26% – around 22 million people (as of 2022).",emoji:"🌍"},
  {id:"polit_220",q:"How many billion euros has Germany spent on Covid aid?",a:300,unit:"billion euros",hint:"About €300 billion in direct government spending on Covid relief.",emoji:"😷"},
  {id:"polit_221",q:"How many countries signed the Paris Climate Agreement?",a:196,unit:"countries",hint:"196 parties have signed the agreement.",emoji:"🌿"},
  {id:"polit_222",q:"How many members does the UN Human Rights Council have?",a:47,unit:"members",hint:"47 members – elected for 3-year terms.",emoji:"🌍"},
  {id:"polit_223",q:"How many thousand soldiers does the German military have?",a:181,unit:"thousand soldiers",hint:"About 181,000 active soldiers (as of 2023) – target is 203,000.",emoji:"🇩🇪"},
  {id:"polit_224",q:"How many billion euros does Germany invest in education per year?",a:160,unit:"billion euros",hint:"About €160 billion – about 4.5% of GDP.",emoji:"📚"},
  {id:"polit_225",q:"How many countries have veto power in the UN Security Council?",a:5,unit:"countries",hint:"USA, Russia, China, France, United Kingdom.",emoji:"🌍"},
  {id:"polit_226",q:"How many pages does the German Basic Law have?",a:146,unit:"pages",hint:"About 146 articles – amended over 60 times since 1949.",emoji:"📜"},
  {id:"polit_227",q:"How many years old is the German Basic Law?",a:75,unit:"years",hint:"Adopted on May 23, 1949 – 75 years old (as of 2024).",emoji:"🇩🇪"},
  {id:"polit_228",q:"How many billion dollars is the US military budget?",a:858,unit:"billion dollars",hint:"About $858 billion (2023) – the largest in the world.",emoji:"🇺🇸"},
  {id:"polit_229",q:"How many countries have nuclear power plants?",a:30,unit:"countries",hint:"About 30 countries operate nuclear power plants.",emoji:"⚛️"},
  {id:"polit_230",q:"How many million people worldwide have no right to vote?",a:2000,unit:"million",hint:"About 2 billion people live without free elections.",emoji:"🗳️"},
  {id:"polit_231",q:"How many years did the Cold War last?",a:44,unit:"years",hint:"1947-1991 – 44 years of tension between the US and USSR.",emoji:"☢️"},
  {id:"polit_232",q:"How many million square kilometers does Russia cover?",a:17,unit:"million km²",hint:"17 million km² – the largest country in the world.",emoji:"🌍"},
  {id:"polit_233",q:"How many million km² does China cover?",a:9.6,unit:"million km²",hint:"9.6 million km² – the fourth-largest country.",emoji:"🇨🇳"},
  {id:"polit_234",q:"How many euros in child benefit does a family in Germany get per month (for the first child)?",a:250,unit:"euros",hint:"€250/month (as of 2023) – raised from €219.",emoji:"👶"},
  {id:"polit_235",q:"What is Germany's VAT rate, in percent?",a:19,unit:"%",hint:"19% standard rate – reduced rate of 7% (food, books).",emoji:"🏪"},
  {id:"polit_236",q:"How many billion euros does Germany pay into pension insurance?",a:340,unit:"billion euros",hint:"About €340 billion annually – the largest social spending item.",emoji:"👴"},
  {id:"polit_237",q:"How many parties sit in the current German Bundestag?",a:6,unit:"parties",hint:"SPD, CDU/CSU, Greens, FDP, AfD, Left (as of 2023).",emoji:"🗳️"},
  {id:"polit_238",q:"How many million tons of CO₂ does Germany emit per year?",a:675,unit:"million tons",hint:"About 675 million tons of CO₂ equivalent (as of 2022).",emoji:"🌿"},
  {id:"polit_239",q:"How many countries are in the OECD?",a:38,unit:"countries",hint:"38 countries – mostly wealthy democracies.",emoji:"🌍"},
  {id:"polit_240",q:"How many billion dollars is Russia's state wealth worth?",a:1500,unit:"billion dollars",hint:"About $1.5 trillion in state assets.",emoji:"🇷🇺"},
  {id:"polit_241",q:"How many million people worldwide are displaced?",a:110,unit:"million",hint:"About 110 million displaced people (as of 2023) – a record.",emoji:"🌍"},
  {id:"polit_242",q:"How many years is the German president's term?",a:5,unit:"years",hint:"5 years – a maximum of 2 terms possible.",emoji:"🇩🇪"},
  {id:"polit_243",q:"How many billion euros did the Bundeswehr receive as a special fund?",a:100,unit:"billion euros",hint:"€100 billion special fund after the invasion of Ukraine in 2022.",emoji:"🛡️"},
  {id:"polit_244",q:"How many days does a US election campaign typically last?",a:600,unit:"days",hint:"About 600 days from the start of campaigning to election day.",emoji:"🇺🇸"},
  {id:"polit_245",q:"How many million members does the Chinese Communist Party have?",a:98,unit:"million",hint:"About 98 million members of the CCP – the largest party in the world.",emoji:"🇨🇳"},
  {id:"polit_246",q:"How many euros per hour is the German minimum wage?",a:12,unit:"euros",hint:"€12/hour (as of 2023) – raised to €12.41 in 2024.",emoji:"💶"},
  {id:"polit_247",q:"How many federal ministers does the German government have?",a:16,unit:"ministers",hint:"About 16 ministers – the number varies by coalition.",emoji:"🏛️"},
];
