// 🍆 SEX & TABOOS – English
export default [
  {q:"How many million pornographic videos are there approximately im Internet?",a:4000000,unit:"Videos",hint:"over 4 million Videos – und daily kommen neue dazu.",emoji:"🔞"},
  {q:"How many million visitors has Pornhub per day?",a:130,unit:"million",hint:"Einer der meisbesuchten Websites worldwide.",emoji:"💻"},
  {q:"How many grams weighs a on averageer dildo?",a:200,unit:"grams",hint:"Variiert stark je to Material und Größe.",emoji:"🍆"},
  {q:"in whas year was das erste Kondom from Latex hergestellt?",a:1920,unit:"Jahr",hint:"Davor wasen Kondome from Schafsdarm.",emoji:"💊"},
  {q:"How many calories verbrennt man beim Oralsex per hour?",a:100,unit:"kcal",hint:"Mehr als man denkt – muscles are im Einsatz.",emoji:"🔥"},
  {q:"How many cm is der on averagee erigierte penis in Germany?",a:14.5,unit:"cm",hint:"Deutsche Männer liegen leicht over dem globalen Schnitt.",emoji:"📏"},
  {q:"How many percent der Frauen können through Penetration allein zum Orgasmus kommen?",a:18,unit:"%",hint:"Die meisen Frauen brauchen zusätzliche Klitoris-Stimulation.",emoji:"🔬"},
  {q:"How many million people worldwide are an HIV infiziert?",a:39,unit:"million",hint:"Stand 2022 – antiretrovirale Therapie hilft.",emoji:"🎗️"},
  {q:"How long takes der on averagee Geschlechtsakt laut Studie in minutes?",a:5.4,unit:"minutes",hint:"of Penetration bis Ejakulation gemessen.",emoji:"⏱️"},
  {q:"How many million Spermien contains a on averageer Ejakulationsschuss?",a:250,unit:"million",hint:"Nur eines davon befruchtet die Eizelle.",emoji:"🔬"},
  {q:"in whas year was Viagra zugelassen?",a:1998,unit:"Jahr",hint:"FDA-Zulassung am 27. März 1998.",emoji:"💊"},
  {q:"How many Nervenendigungen has die Klitoris?",a:8000,unit:"Nervenenden",hint:"Doppelt so viele wie der penis.",emoji:"⚡"},
  {q:"How many cm is die on averagee Vaginaltiefe in Ruhe?",a:9,unit:"cm",hint:"Erregt dehnt sie sich on 12-15 cm from.",emoji:"📏"},
  {q:"How many million Dollar wert is die globale Sexspielzeug-Industrie?",a:33000,unit:"million $",hint:"33 billion Dollar – grows annually.",emoji:"💰"},
  {q:"How many times per year has a Deutscher on average Sex?",a:98,unit:"times",hint:"Fast zweitimes per week laut Umfragen.",emoji:"❤️"},
  {q:"How many hours im live verbringt a human with Sex?",a:520,unit:"hours",hint:"Etwa 21 days – over a live gerechnet.",emoji:"⏰"},
  {q:"How many cm is die on averagee penislänge schlaff?",a:9,unit:"cm",hint:"Im Durchschnitt 7-10 cm schlaff.",emoji:"📏"},
  {q:"in whas year was der erste Vibrator erfunden?",a:1880,unit:"Jahr",hint:"Ursprünglich als medizinisches Gerät for 'Hysterie'.",emoji:"⚡"},
  {q:"How many seconds takes die on averagee weibliche Orgasmus-Kontraktion?",a:22,unit:"seconds",hint:"Weibliche Orgasmen dauern länger als männliche.",emoji:"🌊"},
  {q:"How many percent der Männer have Erektionsprobleme?",a:25,unit:"%",hint:"Betrifft Männer aller Altersgruppen.",emoji:"📊"},
  {q:"How many million times is der Begriff 'sex' daily gegoogelt?",a:8,unit:"million",hint:"Einer der meisgesuchten Begriffe worldwide.",emoji:"🔍"},
  {q:"How many cm lang is die on averagee Brust-Brustwasze im Durchmesser?",a:1.5,unit:"cm",hint:"Brustwaszen variieren stark in Größe und Form.",emoji:"📏"},
  {q:"in whas year was die Pille erfunden?",a:1960,unit:"Jahr",hint:"FDA-Zulassung 1960 – revolutionierte Frauenrechte.",emoji:"💊"},
  {q:"How many million Kondome are worldwide daily verwendet?",a:6,unit:"million",hint:"billion per year.",emoji:"💊"},
  {q:"How many percent der people have schon einen One-Night-Stand gehabt?",a:66,unit:"%",hint:"Zwei Drittel aller Erwachsenen laut Umfragen.",emoji:"🌙"},
  {q:"How many degrees Celsius erhöht sich die Körpertemperatur beim Orgasmus?",a:0.3,unit:"°C",hint:"Eine leichte aber messbare Erwärmung.",emoji:"🌡️"},
  {q:"How many million people worldwide have Syphilis?",a:7,unit:"million",hint:"Immer noch verbreitet – trotz Antibiotika.",emoji:"🔬"},
  {q:"How long takes a Erektion im Schnitt an?",a:30,unit:"minutes",hint:"Inklusive aller sexuellen Aktivitäten.",emoji:"⏰"},
  {q:"How many grams Protein contains Sperma per ejaculation?",a:300,unit:"mg",hint:"Weniger als a Tasse Milch.",emoji:"⚗️"},
  {q:"How many percent der people praktizieren Oralsex?",a:80,unit:"%",hint:"Sehr weit verbreitet under Erwachsenen.",emoji:"📊"},
  {q:"in whas year was das erste Sexspielzeug for Männer (Fleshlight) erfunden?",a:1995,unit:"Jahr",hint:"Patentiert of Steve Shubin.",emoji:"📅"},
  {q:"How many cm is der Abstand between Klitoris und Vaginalöffnung on average?",a:2.5,unit:"cm",hint:"Beeinflusst die Orgasmusfähigkeit.",emoji:"📏"},
  {q:"How many million Dollar earns der meisbezahlte Pornodarsteller?",a:1,unit:"Mio. Dollar/Jahr",hint:"Frauen verdienen in der Branche oft mehr.",emoji:"💰"},
  {q:"How many percent der Deutschen have schon Sex im Freien gehabt?",a:55,unit:"%",hint:"Outdoor-Sex is überraschend populär.",emoji:"🌿"},
  {q:"How many hours schlafen people die viel Sex have länger?",a:1,unit:"Stunde mehr",hint:"Orgasmus setzt schlaffördernde Hormone frei.",emoji:"😴"},
  {q:"How many million people are worldwide in der Sexarbeit tätig?",a:40,unit:"million",hint:"Schätzung – schwer messbar through Illegalität.",emoji:"🌍"},
  {q:"How many cm lang is die G-Punkt-Zone of der Vaginalöffnung?",a:5,unit:"cm",hint:"An der vorderen Vaginalwand.",emoji:"📏"},
  {q:"in whas year was Sexarbeit in Germany legalisiert?",a:2002,unit:"Jahr",hint:"Das Prostitutionsgesetz trat am 1. Januar 2002 in Kraft.",emoji:"📜"},
  {q:"How many percent der Frauen masturbeeren regelmäßig?",a:67,unit:"%",hint:"Ähnlich wie at Männern – Mythos widerlegt.",emoji:"📊"},
  {q:"How many million visitors has OnlyFans?",a:220,unit:"million",hint:"Regisrierte Nutzer – with 2,5 Mio. Creators.",emoji:"📱"},
  {q:"How many grams weighs a Durchschnitts-testicles?",a:20,unit:"grams",hint:"Beide testicles zusammen wiegen 40 grams.",emoji:"⚖️"},
  {q:"How many percent der Paare have schon Rollenspiele ausprobeert?",a:45,unit:"%",hint:"Häufiger als die meisen denken.",emoji:"🎭"},
  {q:"in whas year was der erste Erotik-Film gedreht?",a:1896,unit:"Jahr",hint:"Le Coucher de la Mariée – 7 minutes lang.",emoji:"🎬"},
  {q:"How many times pro Nacht has a gesunder Mann a Erektion im Schlaf?",a:4,unit:"times",hint:"NPT – nächtliche penile Tumeszenz.",emoji:"😴"},
  {q:"How many percent der Deutschen have schon Cybersex gehabt?",a:30,unit:"%",hint:"Videochas, Sexting und ähnliches.",emoji:"💻"},
  {q:"How many cm is die on averagee Brust in Germany (Körbchen)?",a:75,unit:"cm Unterbrustweite",hint:"Körbchen B/C is am häufigsten in Germany.",emoji:"👙"},
  {q:"How many million Dollar wert is der globale Erotik-litersatur-Markt?",a:1500,unit:"million $",hint:"Fifty Shades of Grey allein brachte billion.",emoji:"📚"},
  {q:"How many percent der people have einen Fetisch?",a:30,unit:"%",hint:"Füße are der häufigste body-Fetisch.",emoji:"🦶"},
  {q:"How long takes der Samenerguss on average in seconds?",a:8,unit:"seconds",hint:"Die Muskelkontraktionen dauern 3-15 seconds.",emoji:"⏱️"},
  {q:"How many million Deutschen geben an, regelmäßig pornographic videos to schauen?",a:25,unit:"million",hint:"Jeder dritte Deutsche.",emoji:"📺"},
  {q:"How many cm is der on averagee Brust-Umfang of a woman in Germany?",a:97,unit:"cm",hint:"Brustumfang variiert stark.",emoji:"📏"},
  {q:"in whas year erschien Fifty Shades of Grey?",a:2011,unit:"Jahr",hint:"E.L. James' BDSM-Roman was zum Weltbestseller.",emoji:"📖"},
  {q:"How many million Exemplare verkaufte Fifty Shades of Grey?",a:150,unit:"million",hint:"Eines der meisverkauften Bücher aller Zeiten.",emoji:"📚"},
  {q:"How many percent der BDSM-Praktizierenden bezeichnen sich als 'Switch'?",a:30,unit:"%",hint:"Weder dominant noch submissiv – sondern beides.",emoji:"🔄"},
  {q:"How many cm is die on averagee weibliche Brustwasze lang?",a:1,unit:"cm",hint:"Im Ruhezustand etwa 1 cm.",emoji:"📏"},
  {q:"How many million people in Germany have schon Analverkehr praktiziert?",a:20,unit:"million",hint:"Etwa 35-40% der population.",emoji:"📊"},
  {q:"How many degrees Celsius is die Klitoris beim Orgasmus wärmer?",a:2,unit:"°C",hint:"Messbar through Infrarotthermografie.",emoji:"🌡️"},
  {q:"How many hours schaut a Durchschnittsdeutscher pornographic videos per month?",a:4,unit:"hours",hint:"Laut anonymen Nutzungsdaten.",emoji:"📺"},
  {q:"in whas year was Sex in der Raumstation ISS zum ersten times theoretisch diskutiert?",a:2006,unit:"Jahr",hint:"NASA-Studie over Sex im All.",emoji:"🚀"},
  {q:"How many percent der Frauen have vorgespielt, einen Orgasmus to have?",a:67,unit:"%",hint:"Faking it is überraschend verbreitet.",emoji:"🎭"},
  {q:"How many million people have a Sexsucht?",a:16,unit:"million",hint:"3-6% der population – hauptsächlich Männer.",emoji:"🔬"},
  {q:"How many percent der Deutschen have Sex with einem Kollegen gehabt?",a:40,unit:"%",hint:"Büroromanen are sehr häufig.",emoji:"💼"},
  {q:"How many cm lang is die on averagee erigierte Klitoris?",a:10,unit:"cm",hint:"Die innere Struktur – nicht nur die sichtbare Eichel.",emoji:"📏"},
  {q:"in whas year was das erste Bordell der Geschichte dokumentiert?",a:600,unit:"v.Chr.",hint:"Im antiken Griechenland under Solon.",emoji:"🏛️"},
  {q:"How many percent der Deutschen geben an, with ihrem Sexleben unzufrieden to sein?",a:30,unit:"%",hint:"Laut repräsentativer Umfragen.",emoji:"😔"},
  {q:"How many million Dollar costse die Produktion of Fifty Shades of Grey (Film)?",a:40,unit:"million $",hint:"Und spielte 569 Mio. Dollar ein.",emoji:"🎬"},
  {q:"How many percent der people have Sex im Auto gehabt?",a:60,unit:"%",hint:"Ein sehr verbreiteter Fantasie-Ort.",emoji:"🚗"},
  {q:"How many grams weighs a Prostata?",a:25,unit:"grams",hint:"Im Alter can sie on 100g wachsen.",emoji:"⚖️"},
  {q:"in whas year was das erste legal producese Porno-Video verkauft?",a:1972,unit:"Jahr",hint:"Deep Throat – der erste Mainstream-Pornofilm.",emoji:"🎬"},
  {q:"How many percent der Deutschen are in offenen Beziehungen?",a:8,unit:"%",hint:"Polyamorie und ENM wachsen.",emoji:"💕"},
  {q:"How many cm is der Menstrual-Cup on average groß?",a:7,unit:"cm",hint:"Umweltfreundliche Alternative to Tampons.",emoji:"📏"},
  {q:"How many million people schauen daily pornographic videos on mobilen Geräten?",a:90,unit:"million",hint:"over 70% des Traffics kommt of Smartphones.",emoji:"📱"},
  {q:"How many hours Porno are daily on Pornhub hochgeladen?",a:115,unit:"hours",hint:"Täglich neue Inhalte.",emoji:"📹"},
  {q:"How many percent der Schwangerschaften are ungeplant?",a:45,unit:"%",hint:"worldwide – in Germany etwa 30%.",emoji:"🤰"},
  {q:"in whas year was das erste Kondom from Kunststoff (Polyurethan) eingeführt?",a:1994,unit:"Jahr",hint:"Alternative for Latex-Allergiker.",emoji:"💊"},
  {q:"How many percent der Deutschen geben to, ihr Handy beim Sex to nutzen?",a:25,unit:"%",hint:"Ablenkung through Smartphones auch im Schlafzimmer.",emoji:"📱"},
  {q:"How many ml Vaginalflüssigkeit produces a woman beim Sex?",a:4,unit:"ml",hint:"Natürliche Befeuchtungsreaktion.",emoji:"💧"},
  {q:"How many million Dollar earnse die Pornodarstellerin Lisa Ann on ihrem Höhepunkt?",a:1.5,unit:"Mio. Dollar/Jahr",hint:"Einem der becantesten Stars der Branche.",emoji:"💰"},
  {q:"How many percent der Männer konsumieren daily pornographic videos?",a:18,unit:"%",hint:"Regelmäßiger Konsum under Männern.",emoji:"📊"},
  {q:"How many cm is die Vagina beim Squirting gedehnt?",a:15,unit:"cm",hint:"Dehnung through Erregung.",emoji:"📏"},
  {q:"in whas year was die erste penisvergrößerungsoperation dokumentiert?",a:1971,unit:"Jahr",hint:"Chirurgische Eingriffe seit den 1970ern.",emoji:"🏥"},
  {q:"How many percent der people have einen Fußfetisch?",a:7,unit:"%",hint:"Der häufigste körperbezogene Fetisch.",emoji:"🦶"},
  {q:"How many million Dollar wert is der globale Markt for Erotik-Videospiele?",a:100,unit:"million $",hint:"Nische aber wachsend.",emoji:"🎮"},
  {q:"How many percent der Deutschen have schon Sexting betrieben?",a:50,unit:"%",hint:"Digitale Intimität is verbreitet.",emoji:"📱"},
  {q:"How many grams Fruchtsugar contains Sperma?",a:2.5,unit:"mg",hint:"Frukose are Spermien Energie.",emoji:"⚗️"},
  {q:"in whas year was die erste Sexklinik in Germany eröffnet?",a:1918,unit:"Jahr",hint:"Magnus Hirschfeld eröffnete das Institut for Sexualwissenschaft.",emoji:"🏥"},
  {q:"How many percent der Deutschen have schon Sex on einer öffentlichen Toilette gehabt?",a:15,unit:"%",hint:"Riskanter Lustort.",emoji:"🚻"},
  {q:"How many cm is die on averagee Vaginaltiefe beim Sex (erregt)?",a:13,unit:"cm",hint:"of 9cm in Ruhe on 12-15cm erregt.",emoji:"📏"},
  {q:"How many million Pornhub-Suchanfragen kommen daily from Deutschland?",a:10,unit:"million",hint:"Deutschland gehört to den Top-Konsumduckn.",emoji:"🔍"},
  {q:"How many percent der people have schon an einem Dreier teilgenommen?",a:20,unit:"%",hint:"Häufiger praktiziert als zugegeben.",emoji:"📊"},
  {q:"How many hours takes the longest becante Orgasmus in seconds?",a:43,unit:"seconds",hint:"Gemessen im Labor.",emoji:"⏱️"},
  {q:"in whas year was das erste Sexdolls-Unternehmen gegründet?",a:1997,unit:"Jahr",hint:"RealDoll from San Diego was der Pionier.",emoji:"🤖"},
  {q:"How many percent der Deutschen kennen ihre Erogenous-Zonen?",a:55,unit:"%",hint:"Fast die Hälfte is unsicher over den eigenen body.",emoji:"📊"},
  {q:"How many cm Länge has a on averageer Vibrator?",a:18,unit:"cm",hint:"Der Klassiker.",emoji:"📏"},
  {q:"How many million Dollar Umsatz macht die BDSM-Industrie?",a:500,unit:"million $",hint:"Bondage, Dominanz, Sadismus, Masochismus.",emoji:"🔗"},
  {q:"How many percent der Deutschen have schon Stripclubs besucht?",a:35,unit:"%",hint:"Männer häufiger als Frauen.",emoji:"💃"},
  {q:"How many grams Zink contains a Ejakulation?",a:5,unit:"mg",hint:"milligrams – essenziell for Spermienqualität.",emoji:"⚗️"},
  {q:"in whas year gründete Hugh Hefner das Playboy-Magazin?",a:1953,unit:"Jahr",hint:"Marilyn Monroe was on dem ersten Cover.",emoji:"🐰"},
  {q:"How many percent der Frauen mögen Analstimulation?",a:35,unit:"%",hint:"Häufiger als offen zugegeben.",emoji:"📊"},
  {q:"How many million Pornhub-Suchanfragen gehen daily ein?",a:100,unit:"million",hint:"million daily – eine gigantische Zahl.",emoji:"🔍"},
  {q:"How many cm lang is a on averageer Anal-Plug?",a:10,unit:"cm",hint:"Viele Variationen – of klein bis groß.",emoji:"📏"},
  {q:"in whas year was der Begriff 'Bisexualität' ersttimess wissenschaftlich verwendet?",a:1892,unit:"Jahr",hint:"of Charles Gilbert Chaddock.",emoji:"🔬"},
  {q:"How many percent der people identifizieren sich als bisexuell?",a:7,unit:"%",hint:"Laut neueren Umfragen – steigend.",emoji:"🌈"},
  {q:"How many million Dollar wert is der globale Markt for Lubricants?",a:800,unit:"million $",hint:"Gleitmittel are a riesiger Markt.",emoji:"💰"},
  {q:"How many percent der people have schon an einem Swingerclub teilgenommen?",a:5,unit:"%",hint:"Häufiger under Paaren Mitte 30.",emoji:"📊"},
  {q:"How many cm is die on averagee Zungenlänge beim Küssen relevant?",a:10,unit:"cm",hint:"Franzosenkuss beinhaltet die halbe Zunge.",emoji:"💋"},
  {q:"in whas year was das erste Nackt-Fotoshooting in einer Zeitschrift veröffentlicht?",a:1896,unit:"Jahr",hint:"in frühen Kunstzeitschriften.",emoji:"📸"},
  {q:"How many percent der Deutschen have schon Sex on Drogeneinfluss gehabt?",a:40,unit:"%",hint:"alcohol is die häufigste Substanz dabei.",emoji:"🍷"},
  {q:"How many grams weighs die Gebearmutter?",a:70,unit:"grams",hint:"Im Nicht-Schwanger-Zustand.",emoji:"⚖️"},
  {q:"How many million people have Gonorrhoe worldwide?",a:82,unit:"million",hint:"Eine der häufigsten STIs.",emoji:"🔬"},
  {q:"How many percent der Männer over 70 are noch sexuell aktiv?",a:40,unit:"%",hint:"Sexualität hört nicht with dem Alter on.",emoji:"👴"},
  {q:"How many cm lang is die on averagee penisvorhaut?",a:5,unit:"cm",hint:"Variiert stark.",emoji:"📏"},
  {q:"in whas year was der erste Homosexuellen-Club in Germany eröffnet?",a:1897,unit:"Jahr",hint:"Hirschfelds Wissenschaftlich-humanitäres Komitee.",emoji:"🌈"},
  {q:"How many million people schauen daily pornographic videos on Arbeit?",a:30,unit:"million",hint:"Überraschend viele Nutzer worldwide.",emoji:"💼"},
  {q:"How many percent der Deutschen have Sex im Büro gehabt?",a:20,unit:"%",hint:"Workplace-Romances are verbreitet.",emoji:"🏢"},
  {q:"How many grams wiegen beide Brüste einer C-Körbchen-Frau zusammen?",a:500,unit:"grams",hint:"Etwa 500g – je to Größe.",emoji:"⚖️"},
  {q:"How many hours takes die on averagee Honeymoon-Nacht in hours?",a:3,unit:"hours",hint:"Mehr Schlafen als gedacht.",emoji:"🌙"},
  {q:"in whas year was der erste Swingerclub in Germany eröffnet?",a:1971,unit:"Jahr",hint:"in den liberalen 70ern.",emoji:"🕺"},
  {q:"How many percent der Frauen bezeichnen den Vibrator als ihren besten Freund?",a:25,unit:"%",hint:"Laut einer internationalen Umfrage.",emoji:"⚡"},
  {q:"How many cm is die on averagee Länge eines Liebeskugel-Sets?",a:20,unit:"cm",hint:"Liebeskugeln for Beckenboden-Training.",emoji:"📏"},
  {q:"How many million Accounts are there on OnlyFans?",a:220,unit:"million",hint:"Nutzer plus Creator-Accounts.",emoji:"📱"},
  {q:"How many percent der people können gleichzeitig mehrere Orgasmen have (Frauen)?",a:70,unit:"%",hint:"Multiples Kommen is at Frauen häufig möglich.",emoji:"🌊"},
  {q:"in whas year was der erste Striptease-Club in den USA eröffnet?",a:1969,unit:"Jahr",hint:"in San Francisco während der Sexual Revolution.",emoji:"💃"},
  {q:"How many grams weighs a Strap-on-dildo on average?",a:300,unit:"grams",hint:"Je to Material between 200-500g.",emoji:"⚖️"},
  {q:"How many percent der Deutschen have bereits Sextourismus betrieben?",a:8,unit:"%",hint:"Hauptziele: Thailand, Niederlande, Spanien.",emoji:"✈️"},
  {q:"How many cm is die on averagee penisbreite erigiert?",a:12,unit:"cm Umfang",hint:"Der Umfang variiert stärker als die Länge.",emoji:"📏"},
  {q:"How many million Euro generiert die deutsche Sexarbeit per year?",a:15000,unit:"million €",hint:"15 billion Euro annually in Germany.",emoji:"💶"},
  {q:"How many percent der people have Sex-Fantasien over Prominduck?",a:80,unit:"%",hint:"Fast jeder has schon davon geträumt.",emoji:"💭"},
  {q:"in whas year was das erste weibliche Kondom zugelassen?",a:1993,unit:"Jahr",hint:"FDA-Zulassung 1993.",emoji:"💊"},
  {q:"How many cm is die on averagee Klitoris-Vorhaut lang?",a:0.5,unit:"cm",hint:"Das Präputium Clitoridis.",emoji:"📏"},
  {q:"How many million Escorts are worldwide tätig?",a:1,unit:"Million",hint:"Schätzungen – exakte Zahlen nicht messbar.",emoji:"💼"},
  {q:"How many percent der Deutschen kennen den Begriff 'Pegging'?",a:30,unit:"%",hint:"Anale Penetration des Mannes through a woman with Strap-on.",emoji:"📊"},
  {q:"How many hours has the worldlängste gemessene Geschlechtsakt getakes?",a:15,unit:"hours",hint:"Dokumentiert in einer Studie.",emoji:"⏰"},
  {q:"in whas year was das Phänomen 'Fetimese Ejaculation' wissenschaftlich anercant?",a:1982,unit:"Jahr",hint:"Ersttimess 1982 wissenschaftlich beschrieben.",emoji:"🔬"},
  {q:"How many percent der Männer sagen, sie are zufrieden with ihrer penislänge?",a:55,unit:"%",hint:"Fast die Hälfte hadert with der Körperwahrnehmung.",emoji:"📊"},
  {q:"How many cm is der kürzeste klinisch dokumentierte erigierte penis?",a:1,unit:"cm",hint:"Mikropenis is under 7cm erigiert definiert.",emoji:"📏"},
  {q:"How many million people have Chlamydien worldwide?",a:127,unit:"million",hint:"Die häufigste bakterielle STI.",emoji:"🔬"},
  {q:"How many percent der Frauen erleben Pain beim Sex (Dyspareunie)?",a:20,unit:"%",hint:"Häufig through Austrocknugg oder andere Faktoren.",emoji:"📊"},
  {q:"in whas year gründete Alfred Kinsey sein Sexualforschungsinstitut?",a:1947,unit:"Jahr",hint:"Das Kinsey Institute in Indiana.",emoji:"🔬"},
  {q:"How many percent der Männer have Sex with anderen Männern, identifizieren sich aber als hetero?",a:5,unit:"%",hint:"Down-Low-Phänomen in Studien gemessen.",emoji:"📊"},
  {q:"How many cm is the longest dokumentierte erigierte penislänge?",a:34,unit:"cm",hint:"Jonah Falcon from New York.",emoji:"📏"},
  {q:"How many million Dollar wert is der globale Markt for Potenzpillen?",a:6000,unit:"million $",hint:"Viagra, Cialis und Generika.",emoji:"💊"},
  {q:"How many percent der Deutschen have schon an einem Orgasmus-Workshop teilgenommen?",a:3,unit:"%",hint:"Nische aber wachsend.",emoji:"📊"},
  {q:"How many hours takes Vorspiel on average laut Studien?",a:18,unit:"minutes",hint:"to wenig laut den meisen Frauen.",emoji:"⏱️"},
  {q:"in whas year was das erste Sex-Museum in Amsterdam eröffnet?",a:1985,unit:"Jahr",hint:"Das Sexmuseum Amsterdam.",emoji:"🏛️"},
  {q:"How many percent der people have schon Phone-Sex gehabt?",a:35,unit:"%",hint:"Digitale Intimität seit den 90ern.",emoji:"📞"},
  {q:"How many cm lang is die on averagee Analöffnung beim Entspanntsein?",a:3,unit:"cm",hint:"can through Training und Entspannung größer are.",emoji:"📏"},
  {q:"How many million people are in the world als Transfrau oder Transmann identifiziert?",a:25,unit:"million",hint:"Schätzungen variieren – worldwide ~0,3% der population.",emoji:"🏳️‍⚧️"},
  {q:"How many percent der Deutschen have schon virtuellen Sex (VR) ausprobeert?",a:8,unit:"%",hint:"VR-Pornografie is im Wachstum.",emoji:"🥽"},
  {q:"How many grams weighs a Geburtskontrollpille?",a:30,unit:"mg",hint:"milligrams daily – winzig aber wirkungsvoll.",emoji:"⚖️"},
  {q:"in whas year was das erste FKK-Gelände in Germany eröffnet?",a:1920,unit:"Jahr",hint:"Die Freikörperkultur begann in den 20ern.",emoji:"🌞"},
  {q:"How many percent der Paare have Sex weniger als eintimes per week?",a:50,unit:"%",hint:"Sexuelle Aktivität nimmt with der Zeit ab.",emoji:"📊"},
  {q:"How many ml fasst a Analplug on average?",a:100,unit:"ml",hint:"Variiert je to Größe.",emoji:"💧"},
  {q:"How many million Euro Umsatz macht der deutsche Sexspielzeug-Markt?",a:400,unit:"million €",hint:"grows annually um 10%.",emoji:"💶"},
  {q:"How many percent der people have a dominantes Schlafzimmer-Verhalten?",a:50,unit:"%",hint:"Etwa die Hälfte bevorzugt a dominante Rolle.",emoji:"📊"},
  {q:"in whas year was der Kegel-Beckenboden-Trainer erfunden?",a:1948,unit:"Jahr",hint:"Dr. Arnold Kegel entwickelte die Übungen.",emoji:"💪"},
  {q:"How many cm is die on averagee Länge eines Butt-Plugs?",a:10,unit:"cm",hint:"Je to Größe und Erfahrung.",emoji:"📏"},
  {q:"How many percent der Männer geben to, pornographic videos to schauen?",a:75,unit:"%",hint:"Die wahre Zahl is wahrscheinlich höher.",emoji:"📊"},
  {q:"How many million Kondome are in Germany per year verkauft?",a:200,unit:"million",hint:"Sinkende Tendenz through Pille und IUDs.",emoji:"💊"},
  {q:"How many percent der people erleben Orgasmusprobleme?",a:40,unit:"%",hint:"Häufiger at Frauen als at Männern.",emoji:"📊"},
  {q:"in whas year erschien das Kamasutra in Europa ersttimess?",a:1883,unit:"Jahr",hint:"Richard Burton übersetzte es ins Englische.",emoji:"📖"},
  {q:"How many Positionen beschreibt das Kamasutra?",a:64,unit:"Positionen",hint:"Viele davon are for den Alltag kaum praktisch.",emoji:"📖"},
  {q:"How many percent der Deutschen kennen ihre eigene G-Punkt-Region?",a:40,unit:"%",hint:"Weniger als die Hälfte laut Umfrage.",emoji:"📊"},
  {q:"How many cm is the longest dokumentierte Vaginaltiefe?",a:20,unit:"cm",hint:"Starke individuelle Variation.",emoji:"📏"},
  {q:"How many million Dollar wert is der globale Markt for Sex-Drogen (Aphrodisiaka)?",a:2000,unit:"million $",hint:"Rhino-Produkte, Oyster-Extrakte und mehr.",emoji:"💊"},
  {q:"How many percent der Deutschen have schon beim Sex gelacht?",a:85,unit:"%",hint:"Humor und Sex passen gut zusammen.",emoji:"😂"},
  {q:"How many hours needs der body um sich to dem Sex to erholen?",a:2,unit:"hours",hint:"Bis heartschlag und Hormone nortimesisiert are.",emoji:"💓"},
  {q:"in whas year was die erste Sextherapie-Praxis in Germany eröffnet?",a:1975,unit:"Jahr",hint:"to Masters & Johnson's Forschungen.",emoji:"🏥"},
  {q:"How many percent der people fantasieren beim Sex an jemand anderen?",a:75,unit:"%",hint:"Sehr verbreitet und psychologisch nortimes.",emoji:"💭"},
  {q:"How many cm groß is a on averageer Brustnippel?",a:0.5,unit:"cm Höhe",hint:"Variiert stark of Person to Person.",emoji:"📏"},
  {q:"How many million Dollar has die Pornodarstellerin Mia Khalifa in total earns?",a:12,unit:"thousand Dollar",hint:"Nur 12.000 Dollar in ihrer kurzen Karriere.",emoji:"💰"},
  {q:"How many percent der Paare geben an, ein gesundes Sexleben to have?",a:52,unit:"%",hint:"Knappe Mehrheit laut Befragungen.",emoji:"📊"},
  {q:"How many grams Glukose are beim Sex verbrannt?",a:8,unit:"grams",hint:"equals einem kleinen Stück Schokolade.",emoji:"🍫"},
  {q:"in whas year was das erste Porno-Magazin (Playboy) gegründet?",a:1953,unit:"Jahr",hint:"Hugh Hefner startete a Revolution.",emoji:"🐰"},
  {q:"How many percent der people have schon Sex im Freien gehabt?",a:55,unit:"%",hint:"Frische Luft und Abduckuer.",emoji:"🌿"},
  {q:"How many million people identifizieren sich worldwide als homosexuell?",a:390,unit:"million",hint:"Ca. 5% the worldbevölkerung.",emoji:"🌈"},
  {q:"How many hours Vorspiel brauchen Frauen on average for einen Orgasmus?",a:20,unit:"minutes",hint:"minutes Stimulation im Schnitt.",emoji:"⏱️"},
  {q:"in whas year was der Analverkehr in Germany legalisiert?",a:1969,unit:"Jahr",hint:"Paragraf 175 was reformiert.",emoji:"📜"},
  {q:"How many percent der Deutschen have schon with einem Fremden geschlafen?",a:45,unit:"%",hint:"One-Night-Stands with Fremden.",emoji:"🌙"},
  {q:"How many cm is a on averageer Liebeskugelstrang lang?",a:25,unit:"cm",hint:"Verbundene Kugeln for Beckenboden.",emoji:"📏"},
  {q:"How many million Euro wert is der deutsche Erotik-Film-Markt?",a:200,unit:"million €",hint:"Produktionen from Deutschland.",emoji:"🎬"},
  {q:"How many percent der people bezeichnen sich als asexuell?",a:1,unit:"%",hint:"Asexualität is a valide sexuelle Orientierung.",emoji:"🏳️"},
  {q:"in whas year erschien das erste weiblich geschriebene Erotik-Buch (Lady Chasterley)?",a:1928,unit:"Jahr",hint:"D.H. Lawrence schrieb es – was jahrtentelang verboten.",emoji:"📚"},
  {q:"How many percent der people finden das Gespräch over Sex to dem Sex angenehm?",a:70,unit:"%",hint:"Afterglow-Kommunikation stärkt Beziehungen.",emoji:"💕"},
  {q:"How many cm is die Basis eines on averageen Vibrators?",a:4,unit:"cm",hint:"Breiter unten for sicheres Halten.",emoji:"📏"},
  {q:"How many million people in Germany have sexuelle Dysfunktionen?",a:10,unit:"million",hint:"Breites Spektrum – viele suchen keine Hilfe.",emoji:"🔬"},
  {q:"How many percent der Deutschen have schon Erotik-Massage erhalten?",a:45,unit:"%",hint:"Sehr verbreitet under Paaren.",emoji:"💆"},
  {q:"How many cm is der Abstand between Anus und Vaginalöffnung (Perineum)?",a:3,unit:"cm",hint:"Das Perineum variiert individuell.",emoji:"📏"},
  {q:"How many million Dollar has Hustler Magazine on seinem Höhepunkt earns?",a:50,unit:"Mio. Dollar/Jahr",hint:"Larry Flynts Sexmagazin in den 80ern.",emoji:"💰"},
  {q:"How many percent der people have schon a Sexspielzeug gekauft?",a:40,unit:"%",hint:"through Online-Shopping viel zugänglicher geworden.",emoji:"📊"},
  {q:"How many percent der people have schon Sex on einem Flughafen oder Flugzeug gehabt?",a:10,unit:"%",hint:"Mile High Club – überraschend verbreitet.",emoji:"✈️"},
  {q:"How many hours im Monat schauen Singles mehr pornographic videos als Paare?",a:4,unit:"hours",hint:"Singles konsumieren deutlich mehr.",emoji:"📊"},
  {q:"How many percent der Deutschen have schon Sexfotos of sich gemacht?",a:55,unit:"%",hint:"Selfies und Sexting-Fotos sehr verbreitet.",emoji:"📸"},
  {q:"How many cm is die on averagee Brust in Österreich (Körbchengröße)?",a:80,unit:"cm Unterbrustweite",hint:"Ähnlich wie in Germany.",emoji:"👙"},
  {q:"How many percent der Männer have Sex with einer unbecanten Person gehabt?",a:50,unit:"%",hint:"One-Night-Stands with Fremden.",emoji:"🌙"},
  {q:"How many million Nutzer has Grindr worldwide?",a:13,unit:"million",hint:"Die becanteste Gay-Dating-App.",emoji:"📱"},
  {q:"How many percent der people have Probleme beim Ansprechen of Sexwishesn?",a:60,unit:"%",hint:"Kommunikation over Sex is schwierig for viele.",emoji:"💬"},
  {q:"How many cm lang is der on averagee Klitoris-Stiel?",a:3,unit:"cm",hint:"Der innere Teil des Klitoriskörpers.",emoji:"📏"},
  {q:"How many million people nutzen Swingerclub-Apps worldwide?",a:2,unit:"million",hint:"Spezialisierte Apps for Lifestyler.",emoji:"📱"},
  {q:"How many percent der Frauen sagen, Vorspiel is wichtiger als Penetration?",a:70,unit:"%",hint:"Laut Befragungen of Frauen worldwide.",emoji:"📊"},
  {q:"How many grams weighs a Durchschnitts-Ovarium (Eierstock)?",a:14,unit:"grams",hint:"Beide zusammen etwa 28 grams.",emoji:"⚖️"},
  {q:"How many percent der Deutschen finden Sex im Alter of 60+ wichtig?",a:60,unit:"%",hint:"Sexualität bleibt lebenslang wichtig.",emoji:"👴"},
  {q:"How many ml Vaginalflüssigkeit produces a woman beim Squirting?",a:200,unit:"ml",hint:"Variiert stark – of wenig bis sehr viel.",emoji:"💧"},
  {q:"How many hours im Monat verbringen Singles with Dating-Apps?",a:10,unit:"hours",hint:"Viel Zeit fürs digitale Dating.",emoji:"📱"},
  {q:"How many percent der Deutschen have schon Toys beim Partnersex benutzt?",a:40,unit:"%",hint:"Immer mehr Paare integrieren Toys.",emoji:"📊"},
  {q:"How many cm is das on averagee Hymen of der Vaginalöffnung entfernt?",a:2,unit:"cm",hint:"Das Hymen is a dünnes Schleimhautgewebe.",emoji:"📏"},
  {q:"How many million people have a Sexallergie (Seminalplasma)?",a:40,unit:"thousand",hint:"000 people – Allergie gegen Sperma-Proteine.",emoji:"🔬"},
  {q:"How many percent der people with Sexsucht are Frauen?",a:20,unit:"%",hint:"Frauen are seltener diagnostiziert.",emoji:"📊"},
  {q:"How many degrees Celsius wärmer is der Vaginalkanal während des Orgasmus?",a:0.5,unit:"°C",hint:"Messbar through präzise Thermometers.",emoji:"🌡️"},
  {q:"How many million people have vaginismus (Scheidenverkrampfen)?",a:15,unit:"million",hint:"Eine häufige aber wenig diskutierte Erkrankung.",emoji:"🔬"},
  {q:"How many percent der Deutschen kennen den Begriff 'Cuckolding'?",a:35,unit:"%",hint:"Ein verbreiteter Begriff for a Sex-Fantasie.",emoji:"📊"},
  {q:"How many grams weighs das Clitoris-Schwellkörpernetz?",a:20,unit:"grams",hint:"Das gesamte Klitorissystem.",emoji:"⚖️"},
  {q:"How many hours needs der Mann on average to dem Orgasmus bis zur nächsten Erektion?",a:30,unit:"minutes",hint:"minutes Refraktärzeit at jungen Männern.",emoji:"⏰"},
  {q:"How many percent der people würden ihren Partner betrügen wenn sie nicht erwischt würden?",a:30,unit:"%",hint:"Anonyme Befragungen zeigen hohe Zahlen.",emoji:"💔"},
  {q:"How many million people praktzieren Bondage worldwide?",a:100,unit:"million",hint:"BDSM in verschiedenen Formen.",emoji:"🔗"},
  {q:"How many cm is die Länge eines erigierten Klitoriskörpers?",a:10,unit:"cm",hint:"Viel größer als sichtbar.",emoji:"📏"},
  {q:"How many percent der Deutschen bezeichnen sich als 'kinky'?",a:20,unit:"%",hint:"Jeder Fünfte has spezielle Vorlieben.",emoji:"📊"},
  {q:"How many mg Oxytocin are beim Orgasmus ausgeschüttet?",a:0.001,unit:"mg",hint:"Winzige Menge – aber starke Bindungswirkung.",emoji:"⚗️"},
  {q:"How many hours Schlaf verbessern die Sexualfunktion?",a:8,unit:"hours",hint:"Ausreichend Schlaf is entscheidend.",emoji:"😴"},
  {q:"How many percent der Männer have schon Erektionsprobleme wegen pornographic videos?",a:30,unit:"%",hint:"PIED – Porn-Induced Erectile Dysfunction.",emoji:"📊"},
  {q:"How many million people nutzen Fetlife worldwide?",a:10,unit:"million",hint:"the largest BDSM-soziale Netzwerk.",emoji:"🔗"},
  {q:"How many grams Elastin has das Vaginalgewebe?",a:1,unit:"grams",hint:"Elastin ermöglicht die Dehnung at der Geburt.",emoji:"⚗️"},
  {q:"How many percent der people have schon während des Monats Lust on Sex gehabt?",a:99,unit:"%",hint:"Fast universell – unabhängig vom Zyklus.",emoji:"📊"},
  {q:"How many ml Schmierung produces die Bartholin-Drüse beim Sex?",a:2,unit:"ml",hint:"Natürliche Gleitfähigkeit.",emoji:"💧"},
  {q:"How many percent der Deutschen have schon Erotic litersature gelesen?",a:55,unit:"%",hint:"Erotische litersatur is sehr populär.",emoji:"📚"},
  {q:"How many million Spermatozoen überleben to der Ejakulation maxitimes?",a:1,unit:"million",hint:"of 250 million überleben nur die Stärksten.",emoji:"🔬"},
  {q:"How many hours in the year verbringt a human with romantischen Aktivitäten?",a:730,unit:"hours",hint:"2 hours daily an Romantik und Intimität.",emoji:"❤️"},
  {q:"How many percent der Swinger in Germany are Akademiker?",a:40,unit:"%",hint:"Überon average gebildet laut Studien.",emoji:"📊"},
  {q:"How many cm is die Vorhaut im erigierten Zustand lang?",a:12,unit:"cm",hint:"Die Vorhaut can bis zur Hälfte des penis bedecken.",emoji:"📏"},
  {q:"How many million people have Erektionsprobleme worldwide?",a:320,unit:"million",hint:"Fast a Drittel aller Männer irgendwann.",emoji:"🔬"},
  {q:"How many percent der Lesben berichten höhere Orgasmusraten als hetero Frauen?",a:86,unit:"%",hint:"Orgasm Gap: Lesben kommen deutlich häufiger.",emoji:"📊"},
  {q:"How many millimeterss is a on averagees Spermium lang?",a:0.05,unit:"mm",hint:"50 Mikrometers – with Schwanzanteil.",emoji:"🔬"},
  {q:"How many percent der people have Fantasien over Macht und Kontrolle?",a:65,unit:"%",hint:"Dominanz und Submission are sehr verbreitete Fantasien.",emoji:"📊"},
  {q:"How many hours schlafen people to gutem Sex besser?",a:1,unit:"Stunde mehr",hint:"Orgasmus fördert Schlaf through Oxytocin.",emoji:"😴"},
  {q:"How many ml Vaginalflüssigkeit produces a woman daily?",a:2,unit:"ml",hint:"Nortimes is 1-4 ml daily.",emoji:"💧"},
  {q:"How many percent der Deutschen wishesn sich mehr Sex als sie have?",a:55,unit:"%",hint:"Desire Discrepancy is das häufigste Problem.",emoji:"📊"},
  {q:"How many cm is der maxitimese Umfang eines erigierten penis im Rekord?",a:25,unit:"cm",hint:"Extremfälle are dokumentiert.",emoji:"📏"},
  {q:"How many million people leiden worldwide an sexuellen Angststörungen?",a:30,unit:"million",hint:"Sexangst – nicht selten.",emoji:"🔬"},
  {q:"How many hours im live verbringt a human with Masturbation (Frauen)?",a:2000,unit:"hours",hint:"Weniger als Männer – aber erheblich.",emoji:"📊"},
  {q:"How many percent der people have im öffentlichen Bereich Sex gehabt?",a:35,unit:"%",hint:"Parks, Strände und andere öffentliche Orte.",emoji:"🌿"},
  {q:"How many percent der Deutschen kennen den Begriff 'Compersion'?",a:15,unit:"%",hint:"Freude an der Lust des Partners with anderen.",emoji:"💕"},
  {q:"How many mg Östradiol contains a nortimese Verhütungspille daily?",a:0.03,unit:"mg",hint:"30 Mikrograms – sehr niedrige Dosis.",emoji:"💊"},
  {q:"How many percent der Deutschen have schon bezahlten Sex gehabt?",a:14,unit:"%",hint:"Laut anonymen Befragungen – hauptsächlich Männer.",emoji:"📊"},
  {q:"How many million people are Teil der Polyamorie-Bewegung?",a:21,unit:"million",hint:"Schätzung in den USA allein.",emoji:"💕"},
];
