// 🚀 ASTRONOMY & PHYSICS – English
export default [
  {q:"How many Lichtjahre ist die Andromeda-Galaxie entfernt?",a:2500000,unit:"light-years",hint:"Sie ist mit bloßem Auge als kleiner Fleck sichtbar.",emoji:"🌌"},
  {q:"How many Grad Celsius beträgt die Oberflächentemperatur der Sonne?",a:5500,unit:"°C",hint:"Im Kern sind es sogar 15 million Grad.",emoji:"☀️"},
  {q:"How many km/s ist die Lichtgeschwindigkeit?",a:300000,unit:"km/s",hint:"Licht braucht ~8 Minuten von der Sonne zur Erde.",emoji:"💡"},
  {q:"How many Erdmassen hat Jupiter?",a:318,unit:"Erdmassen",hint:"Jupiter ist der größte Planet unseres Sonnensystems.",emoji:"🪐"},
  {q:"How many Monde hat Saturn?",a:146,unit:"Monde",hint:"Saturn hat die meisten Monde aller Planeten.",emoji:"🪐"},
  {q:"How many Grad Celsius ist es auf dem Mond nachts?",a:-170,unit:"°C",hint:"Tagsüber sind es +130°C.",emoji:"🌙"},
  {q:"How many Mal größer ist der Sonnendurchmesser als der Erddurchmesser?",a:109,unit:"times",hint:"Der Sonnendurchmesser beträgt 1,39 million km.",emoji:"☀️"},
  {q:"How many km ist der Mond von der Erde entfernt?",a:384400,unit:"km",hint:"Die Entfernung schwankt zwischen 356.000 und 407.000 km.",emoji:"🌙"},
  {q:"How many Jahre alt ist das Universum in billion?",a:13.8,unit:"Milliarden Jahre",hint:"Seit dem Urknall.",emoji:"🌌"},
  {q:"How many km/h bewegt sich die Erde um die Sonne?",a:107000,unit:"km/h",hint:"Das sind etwa 30 km pro Sekunde.",emoji:"🌍"},
  {q:"How many billion Sterne gibt es in der Milchstraße?",a:200,unit:"billion",hint:"Und billion weitere Galaxien im Universum.",emoji:"⭐"},
  {q:"How many Minuten braucht Licht von der Sonne zur Erde?",a:8,unit:"minutes",hint:"Licht rast mit 300.000 km/s – trotzdem braucht es eine Weile.",emoji:"☀️"},
  {q:"Wie heiß ist der Kern der Erde in Grad Celsius?",a:6000,unit:"°C",hint:"Ähnlich heiß wie die Oberfläche der Sonne.",emoji:"🌍"},
  {q:"How many Monate dauert ein Jahr auf dem Mars?",a:24,unit:"months",hint:"Ein Marsjahr dauert 687 Erdtage.",emoji:"🔴"},
  {q:"How many Mal größer ist die Sonne als die Erde?",a:1300000,unit:"times",hint:"1,3 million Erden würden in die Sonne passen.",emoji:"☀️"},
  {q:"How many Grad Celsius beträgt die Temperatur im Weltall?",a:-270,unit:"°C",hint:"Nahe dem absoluten Nullpunkt von -273°C.",emoji:"❄️"},
  {q:"How many Stunden dauert ein Tag auf der Venus?",a:5832,unit:"hours",hint:"Ein Venusjahr ist kürzer als ein Venustag.",emoji:"🪐"},
  {q:"How many Grad Celsius ist die Temperatur auf dem Merkur tagsüber?",a:430,unit:"°C",hint:"Nachts fällt sie auf -180°C.",emoji:"☿"},
  {q:"How many km/h bewegt sich die ISS um die Erde?",a:28000,unit:"km/h",hint:"Sie umkreist die Erde alle 90 Minuten.",emoji:"🚀"},
  {q:"How many billion Tonnen wiegt 1 Teelöffel Neutronensternmaterial?",a:1,unit:"billion tons",hint:"Milliarde Tonnen in einem Teelöffel – unvorstellbar dicht.",emoji:"⭐"},
  {q:"How many km ist ein Lichtjahr lang in Billionen?",a:9.46,unit:"Billionen km",hint:"Das Licht legt per year 9,46 Billionen km zurück.",emoji:"💡"},
  {q:"How many Monde hat der Mars?",a:2,unit:"Monde",hint:"Phobos und Deimos – beide sehr klein.",emoji:"🔴"},
  {q:"How many km beträgt der Durchmesser der Erde?",a:12742,unit:"km",hint:"Am Äquator ist sie etwas dicker als an den Polen.",emoji:"🌍"},
  {q:"How many km/h muss eine Rakete fliegen um die Erde zu verlassen?",a:40000,unit:"km/h",hint:"Das ist die Fluchtgeschwindigkeit der Erde.",emoji:"🚀"},
  {q:"How many Astronauten waren bisher auf dem Mond?",a:12,unit:"Astronauten",hint:"Alle 12 waren Amerikaner, bei den Apollo-Missionen.",emoji:"👨‍🚀"},
  {q:"How many Ringe hat Saturn?",a:7,unit:"Hauptringe",hint:"Die Ringe bestehen aus Eis und Gestein.",emoji:"🪐"},
  {q:"How far ist Alpha Centauri von der Erde entfernt in Lichtjahren?",a:4,unit:"light-years",hint:"Das nächste Sternensystem nach unserem.",emoji:"⭐"},
  {q:"How many Atommassen hat ein Wasserstoffatom?",a:1,unit:"Atommasseneinheit",hint:"Wasserstoff ist das leichteste Element.",emoji:"⚛️"},
  {q:"How many billion Galaxien gibt es im beobachtbaren Universum?",a:2000,unit:"billion",hint:"2 Billionen Galaxien – jede mit billion Sternen.",emoji:"🌌"},
  {q:"How fast bewegt sich die Schallgeschwindigkeit in Luft in m/s?",a:343,unit:"m/s",hint:"Bei 20°C Lufttemperatur.",emoji:"🔊"},
  {q:"How heavy ist ein Proton im Vergleich zu einem Elektron?",a:1836,unit:"Mal schwerer",hint:"Das Proton ist diese Zahl-fach schwerer.",emoji:"⚛️"},
  {q:"How many km/s beträgt die Fluchtgeschwindigkeit vom Mond?",a:2.4,unit:"km/s",hint:"Viel niedriger als auf der Erde.",emoji:"🌙"},
  {q:"How many Grad hat ein Vollkreis?",a:360,unit:"Grad",hint:"Eine uralte Konvention der Babylonier – heute noch Standard.",emoji:"⭕"},
  {q:"How many Planeten hat unser Sonnensystem?",a:8,unit:"Planeten",hint:"Pluto wurde 2006 zum Zwergplaneten degradiert.",emoji:"🪐"},
  {q:"How many km/h beträgt die Windgeschwindigkeit eines Hurrikans (Kategorie 5)?",a:252,unit:"km/h",hint:"Ab 252 km/h ist es Kategorie 5.",emoji:"🌀"},
  {q:"How many km beträgt der Radius der Erde?",a:6371,unit:"km",hint:"Der mittlere Erdradius.",emoji:"🌍"},
  {q:"How many km/s beträgt die Umlaufgeschwindigkeit der Erde?",a:30,unit:"km/s",hint:"29,8 km/s oder rund 107.000 km/h.",emoji:"🌍"},
  {q:"How many Stunden dauert ein Tag auf Jupiter?",a:10,unit:"hours",hint:"Jupiter dreht sich am schnellsten aller Planeten.",emoji:"🪐"},
  {q:"How many Meter lang ist die Internationale Raumstation ISS?",a:109,unit:"meters",hint:"So breit wie ein Fußballfeld.",emoji:"🚀"},
  {q:"How many Jahre alt ist unsere Sonne?",a:4600000000,unit:"years",hint:"4,6 billion Jahre – Mittag ihres Lebens.",emoji:"☀️"},
  {q:"How many km/h erreicht ein Meteorit beim Eintritt in die Atmosphäre?",a:72000,unit:"km/h",hint:"20 km/s – dabei verbrennt er meist.",emoji:"☄️"},
  {q:"How many Grad Celsius beträgt die Temperatur im Erdmittelpunkt?",a:6000,unit:"°C",hint:"Ähnlich wie die Sonnenoberfläche.",emoji:"🔥"},
  {q:"How many Mal größer ist Jupiters Durchmesser als der der Erde?",a:11,unit:"times",hint:"Jupiter hat 139.820 km Durchmesser.",emoji:"🪐"},
  {q:"How many Stunden dauert eine Umdrehung der Erde um ihre Achse?",a:24,unit:"hours",hint:"Genauer: 23 Stunden 56 Minuten.",emoji:"🌍"},
  {q:"How many Astronomische Einheiten ist Neptun von der Sonne entfernt?",a:30,unit:"AU",hint:"1 AE = Erde-Sonne-Abstand. Licht braucht 4 Stunden zu Neptun.",emoji:"🔵"},
  {q:"How many Monde hat Uranus?",a:27,unit:"Monde",hint:"Alle nach Shakespeare-Figuren benannt.",emoji:"🟦"},
  {q:"How many Grad Celsius beträgt die Kerntemperatur der Sonne?",a:15000000,unit:"°C",hint:"15 million Grad – da findet Kernfusion statt.",emoji:"☀️"},
  {q:"How many km/s beträgt die Fluchtgeschwindigkeit von der Erde?",a:11.2,unit:"km/s",hint:"11,2 km/s oder 40.000 km/h.",emoji:"🚀"},
  {q:"How many Grad Celsius ist es auf dem Saturn?",a:-178,unit:"°C",hint:"Die Wolkenobergrenze ist sehr kalt.",emoji:"🪐"},
  {q:"How many Jahre dauert ein Pluto-Jahr?",a:248,unit:"Erdenjahre",hint:"Jahre für einen Umlauf um die Sonne.",emoji:"🌑"},
  {q:"How many km ist die Milchstraße breit?",a:100000,unit:"light-years",hint:"100.000 Lichtjahre Durchmesser.",emoji:"🌌"},
  {q:"How many Stunden dauert ein Jahr auf Merkur?",a:1408,unit:"hours",hint:"88 Erdtage – das kürzeste Planetenjahr.",emoji:"☿"},
  {q:"How many Lichtjahre ist die Oortsche Wolke von der Sonne entfernt?",a:1,unit:"light-year",hint:"Die äußerste Grenze unseres Sonnensystems – 50.000 AE.",emoji:"☄️"},
  {q:"How many m/s² beträgt die Erdbeschleunigung?",a:9.81,unit:"m/s²",hint:"Der freie Fall beschleunigt mit 9,81 m/s².",emoji:"⬇️"},
  {q:"How many Jahre dauert ein Uranus-Jahr?",a:84,unit:"years",hint:"Erdenjahre für einen Umlauf.",emoji:"🟦"},
  {q:"How many km/h ist die schnellste menschgemachte Sonde (Parker Solar Probe)?",a:692000,unit:"km/h",hint:"Die schnellste von Menschen gebaute Maschine.",emoji:"🚀"},
  {q:"How many Grad Celsius beträgt die Temperatur auf Neptun?",a:-214,unit:"°C",hint:"Der kälteste Planet im Sonnensystem.",emoji:"🔵"},
  {q:"How many Astronomische Einheiten ist Pluto von der Sonne entfernt?",a:39,unit:"AU",hint:"AE – fast 40 Mal so weit wie die Erde.",emoji:"🌑"},
  {q:"How many Stunden dauert eine Jupiterjahr?",a:87672,unit:"hours",hint:"12 Erdenjahre für einen Umlauf.",emoji:"🪐"},
  {q:"How many Grad dreht sich die Erde per hour?",a:15,unit:"Grad",hint:"360° in 24h = 15° per hour.",emoji:"🌍"},
  {q:"How many km beträgt der Abstand Erde-Sonne in Astronomischen Einheiten?",a:1,unit:"AU",hint:"AU = 149,6 million km.",emoji:"☀️"},
  {q:"How many Hertz schwingen sichtbare Lichtwellen (in Billionen)?",a:600,unit:"Billionen Hz",hint:"400-700 THz – im Bereich des sichtbaren Lichts.",emoji:"💡"},
  {q:"How many Watt gibt die Sonne ab?",a:386000000000000000000000000,unit:"watts",hint:"3,86 × 10²⁶ Watt – unvorstellbare Leistung.",emoji:"☀️"},
  {q:"How many Tonnen Materie wandelt die Sonne pro Sekunde in Energie um?",a:4000000,unit:"tons",hint:"4 million Tonnen pro Sekunde.",emoji:"☀️"},
  {q:"How many km beträgt der Durchmesser des Großen Roten Flecks auf Jupiter?",a:16000,unit:"km",hint:"Ein Sturm seit 350 Jahren.",emoji:"🪐"},
  {q:"How many Lichtjahre ist das Zentrum unserer Milchstraße entfernt?",a:26000,unit:"light-years",hint:"Ein supermassereiches Schwarzes Loch liegt dort.",emoji:"🌌"},
  {q:"How many km/h dreht sich Jupiter an seinem Äquator?",a:45000,unit:"km/h",hint:"Schnellste Rotation aller Planeten.",emoji:"🪐"},
  {q:"How many Nanometer sind sichtbares Licht breit?",a:700,unit:"nanometers",hint:"400-700 nm Wellenlänge.",emoji:"🌈"},
  {q:"How many Grad Celsius beträgt die Temperatur in einem Blitz?",a:30000,unit:"°C",hint:"5x heißer als die Sonnenoberfläche.",emoji:"⚡"},
  {q:"How many million km ist der Mars von der Erde entfernt (Durchschnitt)?",a:225,unit:"million km",hint:"Variiert stark – von 56 bis 401 Mio. km.",emoji:"🔴"},
  {q:"How many billion km ist die Sonne vom Zentrum der Milchstraße?",a:26000,unit:"light-years",hint:"Am Rand der Milchstraße.",emoji:"🌌"},
  {q:"How many Jahre würde eine Autofahrt zur Sonne bei 200 km/h dauern?",a:97,unit:"years",hint:"150 million km ÷ 200 km/h = 850.000 Stunden.",emoji:"🚗"},
  {q:"How many Kilogramm wiegt 1 m³ Wasser?",a:1000,unit:"kg",hint:"Wasser hat die Dichte von 1 kg/Liter.",emoji:"💧"},
  {q:"How many km/h bewegt sich der Schall im Wasser?",a:5400,unit:"km/h",hint:"5x schneller als in Luft.",emoji:"🌊"},
  {q:"How many Stunden dauert eine Neptun-Rotation?",a:16,unit:"hours",hint:"Ein Neptuner Tag dauert diese Zeit Stunden.",emoji:"🔵"},
  {q:"How many Sonnen würden in ein Schwarzes Loch (Sagittarius A*) passen?",a:4000000,unit:"solar masses",hint:"Das Schwarze Loch im Zentrum der Milchstraße.",emoji:"🌑"},
  {q:"How many km lang ist der Durchmesser eines typischen Neutronensterns?",a:20,unit:"km",hint:"Unvorstellbar dicht auf kleinstem Raum.",emoji:"⭐"},
  {q:"How many Grad Celsius beträgt die Hitze bei der Kernfusion in der Sonne?",a:15000000,unit:"°C",hint:"Im Kern – Wasserstoff wird zu Helium.",emoji:"⚛️"},
  {q:"How many km/s entfernt sich das Universum am Rande von uns?",a:300000,unit:"km/s",hint:"Am Rand expandiert es mit Lichtgeschwindigkeit.",emoji:"🌌"},
  {q:"How many Jahre dauert ein Saturnjahr?",a:29.5,unit:"years",hint:"29,5 Erdenjahre für einen Umlauf.",emoji:"🪐"},
  {q:"How many Meter tief wäre der Ozean wenn die Erde kugelförmig glatt wäre?",a:2700,unit:"meters",hint:"Alle Berge würden im Meer versinken.",emoji:"🌊"},
  {q:"How many Kilowattstunden Energie liefert 1 Gramm Uran?",a:24000,unit:"kWh",hint:"Ein Gramm Uran entspricht 3 Tonnen Kohle.",emoji:"⚛️"},
  {q:"How many million km ist die Erde von der Sonne entfernt?",a:150,unit:"million km",hint:"Das ist die Definition der Astronomischen Einheit (1 AE).",emoji:"☀️"},
  {q:"How many Grad kühlt sich die Atmosphäre pro km Höhe ab?",a:6.5,unit:"°C/km",hint:"Der adiabatische Temperaturgradient.",emoji:"🌡️"},
  {q:"How many Joule hat 1 Kilowattstunde?",a:3600000,unit:"Joule",hint:"3,6 million Joule.",emoji:"⚡"},
  {q:"How many Monate dauert ein Merkur-Jahr?",a:3,unit:"months",hint:"Nur 88 Tage – schnellster Umlauf.",emoji:"☿"},
  {q:"Mit wie vielen km/s rasen Gammastrahlen durch das All?",a:300000,unit:"km/s",hint:"Lichtgeschwindigkeit – das schnellste im Universum.",emoji:"💥"},
  {q:"How many Grad hat die Erde Axialneigung?",a:23.5,unit:"Grad",hint:"Verursacht die Jahreszeiten.",emoji:"🌍"},
  {q:"How many km beträgt der Umfang des Mondes?",a:10917,unit:"km",hint:"Viel kleiner als die Erde.",emoji:"🌙"},
  {q:"How many Nanometer dick ist ein menschliches Haar im Vergleich zu Lichtwellen?",a:700,unit:"nanometers",hint:"Licht und Haare sind ähnlich breit.",emoji:"💇"},
  {q:"How many Atmosphären Druck herrscht in 10.000 Metern Wassertiefe?",a:1000,unit:"atmospheres",hint:"Der Druck in der Tiefsee ist kaum vorstellbar.",emoji:"🌊"},
  {q:"How many Grad Celsius ist die durchschnittliche Temperatur auf dem Mars?",a:-60,unit:"°C",hint:"Zwischen -125°C und +20°C.",emoji:"🔴"},
  {q:"How many m/s² ist die Schwerkraft auf dem Mond?",a:1.6,unit:"m/s²",hint:"1/6 der Erdgravitation.",emoji:"🌙"},
  {q:"How many km Dicke hat die Erdkruste im Durchschnitt?",a:35,unit:"km",hint:"Unter Ozeanen nur 10 km, unter Kontinenten 35 km.",emoji:"🌍"},
  {q:"How many billion Tonnen wiegt die Erdatmosphäre?",a:5600,unit:"Billionen kg",hint:"5,6 Quadrillionen Kilogramm.",emoji:"💨"},
  {q:"How many km/h dreht sich die Erde am Äquator?",a:1670,unit:"km/h",hint:"Wir spüren es nicht – weil wir uns mit bewegen.",emoji:"🌍"},
  {q:"How many Grad Celsius wärmer würde es ohne Treibhauseffekt auf der Erde?",a:33,unit:"°C kälter",hint:"Ohne natürlichen Treibhauseffekt wäre es -18°C.",emoji:"🌡️"},
  {q:"How many km/h beträgt die maximale Windgeschwindigkeit auf Neptun?",a:2100,unit:"km/h",hint:"Die stärksten bekannten Winde im Sonnensystem.",emoji:"🌀"},
  {q:"How many billion km von der Sonne ist die Voyager 1 entfernt?",a:23500,unit:"million km",hint:"Stand 2023 – sie wurde 1977 gestartet.",emoji:"🚀"},
  {q:"How many Kilogramm Mondgestein brachten die Apollo-Missionen mit?",a:382,unit:"kg",hint:"Kg Mondgestein – noch immer analysiert.",emoji:"🌙"},
  {q:"How many Grad Celsius beträgt die Temperatur in einem Blitzkern?",a:27000,unit:"°C",hint:"Heißer als die Sonnenoberfläche.",emoji:"⚡"},
  {q:"How many km/h müsste man fliegen um in Erdumlaufbahn zu bleiben?",a:28000,unit:"km/h",hint:"Erste kosmische Geschwindigkeit.",emoji:"🚀"},
  {q:"How many Stunden dauert ein Marsianer-Tag?",a:24.6,unit:"hours",hint:"Fast wie ein Erdtag.",emoji:"🔴"},
  {q:"How many Grad Celsius ist es auf der Sonnenkorona?",a:2000000,unit:"°C",hint:"Mysteriöserweise viel heißer als die Oberfläche.",emoji:"☀️"},
  {q:"How many million km ist Merkur von der Sonne entfernt?",a:58,unit:"million km",hint:"Der sonnennächste Planet.",emoji:"☿"},
  {q:"How many Stunden dauert ein Jahr auf Venus?",a:5392,unit:"hours",hint:"225 Erdtage – und ein Tag ist länger als ein Jahr.",emoji:"🪐"},
  {q:"How many Trillionen Tonnen wiegt der Mond?",a:73,unit:"trillion tons",hint:"7,35 × 10²² kg.",emoji:"🌙"},
  {q:"How many Grad Celsius kälter ist der Weltraum als die Erde?",a:287,unit:"°C kälter",hint:"Erde ist on average 15°C, Weltall -273°C.",emoji:"❄️"},
  {q:"How many km hoch ist der Mount Olympus auf dem Mars?",a:22,unit:"km",hint:"Der höchste Vulkan im Sonnensystem.",emoji:"🔴"},
  {q:"How many Erden passen in die Sonne?",a:1300000,unit:"Erden",hint:"1,3 million Erden.",emoji:"☀️"},
  {q:"How many billion Tonnen Kohlendioxid atmet die Menschheit per year aus?",a:3,unit:"billion tons",hint:"billion Tonnen CO₂ durch Atmung.",emoji:"💨"},
  {q:"How many Mal pro Sekunde dreht sich ein Neutronenstern?",a:700,unit:"times",hint:"Pulsare rotieren bis zu 716 Mal pro Sekunde.",emoji:"⭐"},
  {q:"How many km ist die Grenze zum Weltraum (Kármán-Linie)?",a:100,unit:"km",hint:"Ab 100 km beginnt offiziell der Weltraum.",emoji:"🚀"},
  {q:"How many Stunden nach dem Urknall bildeten sich erste Atome?",a:380000,unit:"years",hint:"380.000 Jahre nach dem Urknall – das Universum kühlte ab.",emoji:"⚛️"},
  {q:"How many kg Mondstaub gibt es pro m² Mondoberfläche?",a:10,unit:"Tonnen/m²",hint:"Der Regolith ist mehrere Meter tief.",emoji:"🌙"},
  {q:"How many billion Tonnen Wasser gibt es auf der Erde?",a:1400000000,unit:"billion liters",hint:"1,4 billion Kubikkilometer Wasser.",emoji:"🌊"},
  {q:"How many km/h dreht sich ein Tornado?",a:480,unit:"km/h",hint:"Stärkste Tornados erreichen über 480 km/h.",emoji:"🌪️"},
  {q:"How many Mal kleiner ist ein Proton als ein Atom?",a:100000,unit:"times",hint:"Das Atom ist zu 99,9% leer.",emoji:"⚛️"},
  {q:"How many Grad beträgt die maximale Sonneneinstrahlung auf dem Mars?",a:20,unit:"°C",hint:"Im Sommer am Äquator – nachts -60°C.",emoji:"🔴"},
  {q:"How many km/h können Sonnenwind-Teilchen erreichen?",a:900000,unit:"km/h",hint:"Bei koronalen Masseauswürfen noch schneller.",emoji:"☀️"},
  {q:"How many Grad breit ist das Sichtfeld des Hubble-Teleskops?",a:0.05,unit:"Grad",hint:"Nur ein kleiner Ausschnitt – und trotzdem voller Galaxien.",emoji:"🔭"},
  {q:"How many billion km weit fliegt Licht in einem Jahr?",a:9460,unit:"billion km",hint:"9,46 Billionen km – ein Lichtjahr.",emoji:"💡"},
  {q:"How many Grad beträgt die maximale Temperatur auf der Venusoberfläche?",a:465,unit:"°C",hint:"Heißer als Merkur – trotz größerer Entfernung zur Sonne.",emoji:"🌋"},
  {q:"How many Trillionen Tonnen wiegt die Erdatmosphäre?",a:5.6,unit:"trillion tons",hint:"5,6 Billiarden Tonnen Luft.",emoji:"💨"},
  {q:"How many billion Jahre hat unsere Sonne noch zu leben?",a:5,unit:"Milliarden Jahre",hint:"Dann wird sie zum roten Riesen.",emoji:"☀️"},
  {q:"How many Meter/Sekunde² beträgt die Schwerkraft auf Jupiter?",a:24.8,unit:"m/s²",hint:"2,5x stärker als auf der Erde.",emoji:"🪐"},
  {q:"How many km tief ist der Marianengraben?",a:11034,unit:"meters",hint:"Der tiefste Punkt der Weltmeere.",emoji:"🌊"},
  {q:"How many billion Tonnen wiegt unsere Milchstraße?",a:2000000000000,unit:"solar masses",hint:"Eine Billion Sonnenmassen.",emoji:"🌌"},
  {q:"How many km beträgt der Abstand zweier Elektronen in einem Atom?",a:0.0000001,unit:"mm",hint:"Unvorstellbar klein – Quantenphysik.",emoji:"⚛️"},
  {q:"How many Grad Celsius ist es an den Polen des Mars?",a:-125,unit:"°C",hint:"CO₂-Eis bildet sich an den Polkappen.",emoji:"🔴"},
  {q:"How many km/h schnell ist der schnellste Jet-Flugzeug (SR-71)?",a:3530,unit:"km/h",hint:"Mach 3,3 – noch nie abgeschossen.",emoji:"✈️"},
  {q:"How much Mal dichter ist der Sonnenkern als Wasser?",a:150,unit:"times",hint:"G/cm³ – das ist um ein Vielfaches dichter als Wasser.",emoji:"☀️"},
  {q:"How many km/s bewegen sich Galaxien von uns weg?",a:67,unit:"km/s pro Megaparsec",hint:"Die Hubble-Konstante beschreibt die Expansion.",emoji:"🌌"},
  {q:"How many billion Lichtjahre groß ist das beobachtbare Universum?",a:93,unit:"Milliarden Lichtjahre",hint:"Der sichtbare Teil – das Universum könnte unendlich groß sein.",emoji:"🌌"},
  {q:"How many Grad Celsius ist die kälteste natürlich gemessene Temperatur auf der Erde?",a:-89.2,unit:"°C",hint:"Gemessen in der Antarktis 1983.",emoji:"🧊"},
  {q:"How many km hoch fliegen Stratosphären-Wolken?",a:25,unit:"km",hint:"Perlmutt-Wolken in der Stratosphäre.",emoji:"☁️"},
  {q:"How many Stunden dauert eine Sonnenfinsternis maximal?",a:7.5,unit:"minutes",hint:"Maximal 7,5 Minuten totale Finsternis.",emoji:"🌑"},
  {q:"How many km lang ist der Canyons auf dem Mars (Valles Marineris)?",a:4000,unit:"km",hint:"10x länger als der Grand Canyon.",emoji:"🔴"},
  {q:"How many Grad Celsius ist die heißeste gemessene Temperatur auf der Erde?",a:56.7,unit:"°C",hint:"Death Valley 1913.",emoji:"🌡️"},
  {q:"How many billion Tonnen wiegt 1 m³ Neutronensternmaterie?",a:10000000,unit:"billion tons",hint:"10¹⁶ kg – ein Zuckerwürfel würde die Erde zerquetschen.",emoji:"⭐"},
  {q:"How many km/h ist der Schall in Stahl?",a:18000,unit:"km/h",hint:"50x schneller als in Luft.",emoji:"🔧"},
  {q:"How many Stunden dauert es bis Pluto seinen eigenen Schatten umrundet?",a:153,unit:"hours",hint:"Pluto dreht sich sehr langsam.",emoji:"🌑"},
  {q:"How many billion km groß ist der Ereignishorizont von M87*?",a:40,unit:"billion km",hint:"Der erste fotografierte Schwarzes Loch.",emoji:"🌑"},
  {q:"How many Grad Celsius beträgt der Unterschied zwischen Tag und Nacht auf dem Mond?",a:300,unit:"°C",hint:"+130°C tagsüber, -170°C nachts.",emoji:"🌙"},
  {q:"How many km/h dreht sich ein Hurrikan maximal?",a:300,unit:"km/h",hint:"Kategorie 5 Hurrikane über 250 km/h.",emoji:"🌀"},
  {q:"How many billion Tonnen Sauerstoff enthält die Erdatmosphäre?",a:1200,unit:"trillion tons",hint:"21% der Atmosphäre ist Sauerstoff.",emoji:"💨"},
  {q:"How many km dick ist der Saturnring?",a:1,unit:"km",hint:"Bis zu 1 km – dünn wie ein Blatt Papier relativ zur Breite.",emoji:"🪐"},
  {q:"How many Stunden liegt die ISS im Erdschatten per day?",a:16,unit:"Sonnenaufgänge",hint:"Die ISS erlebt 16 Sonnenauf- und -untergänge daily.",emoji:"🚀"},
  {q:"How many km/h beträgt die maximale Windgeschwindigkeit eines Tornados?",a:480,unit:"km/h",hint:"EF5-Tornados sind die stärksten.",emoji:"🌪️"},
  {q:"How many billion Jahre alt ist das älteste bekannte Gestein auf der Erde?",a:4,unit:"Milliarden Jahre",hint:"Gefunden in Australien.",emoji:"🪨"},
  {q:"How many km ist der Erdmond von der Erde in einem Jahr entfernt?",a:3.8,unit:"cm weiter",hint:"Der Mond entfernt sich annually 3,8 cm.",emoji:"🌙"},
  {q:"How many Tonnen Asteroiden treffen die Erde per year?",a:40000,unit:"tons",hint:"Als Meteorstaub – meist verglüht.",emoji:"☄️"},
  {q:"How many km beträgt der Durchmesser des Großen Roten Flecks?",a:16000,unit:"km",hint:"Größer als die Erde.",emoji:"🪐"},
  {q:"How many billion Lichtjahre ist die CMB von uns entfernt?",a:46,unit:"Milliarden Lichtjahre",hint:"Der älteste beobachtbare Horizont – die kosmische Hintergrundstrahlung.",emoji:"🌌"},
  {q:"How many km/s beträgt die Geschwindigkeit der Expansion des Universums?",a:67,unit:"km/s/Mpc",hint:"Die Hubble-Konstante.",emoji:"🌌"},
  {q:"How many Stunden dauert der Sonnensturm von der Sonne bis zur Erde?",a:2,unit:"hours",hint:"Koronale Masseauswürfe kommen in 1-3 Tagen – aber Strahlung in Minuten.",emoji:"☀️"},
  {q:"How many Meter/Sekunde² ist die Schwerkraft auf Pluto?",a:0.62,unit:"m/s²",hint:"Nur 6% der Erdgravitation.",emoji:"🌑"},
  {q:"How many billion Neutrinos passieren einen cm² der Erde pro Sekunde?",a:65,unit:"billion",hint:"Neutrinos kommen von der Sonne und gehen durch alles hindurch.",emoji:"⚛️"},
  {q:"How many Grad Celsius ist die Temperatur im Innern eines Tornados?",a:-10,unit:"°C",hint:"Im Auge eines Tornados ist es kühler.",emoji:"🌪️"},
  {q:"How many km lang ist der Valles Marineris auf dem Mars?",a:4000,unit:"km",hint:"Das größte Canyon-System im Sonnensystem.",emoji:"🔴"},
  {q:"How many billion km ist Neptun von der Sonne entfernt?",a:4500,unit:"billion km",hint:"Licht braucht 4 Stunden von der Sonne zu Neptun.",emoji:"🔵"},
  {q:"How many Kilogramm Gold gibt es im Universum pro Kubikparsec?",a:0.000001,unit:"solar masses",hint:"Gold ist selten – entsteht nur bei Neutronenstern-Kollisionen.",emoji:"🪙"},
  {q:"How many km/s beträgt die Relativgeschwindigkeit der Andromeda-Galaxie zur Milchstraße?",a:110,unit:"km/s",hint:"Sie bewegen sich aufeinander zu – Kollision in 4 Mrd. Jahren.",emoji:"🌌"},
  {q:"How many Quadrillionen Tonnen Eis gibt es in der Antarktis?",a:26.5,unit:"Millionen Gigatonnen",hint:"26,5 million Gigatonnen Eis.",emoji:"🧊"},
  {q:"How many Stunden dauert ein Erd-Sonnenjahr genau?",a:8766,unit:"hours",hint:"365,25 Tage × 24 Stunden.",emoji:"📅"},
  {q:"How many billion Jahre ist der Mond alt?",a:4.5,unit:"Milliarden Jahre",hint:"Er entstand durch eine Kollision mit dem Proto-Erde.",emoji:"🌙"},
  {q:"How many Grad Celsius ist der kühlste bekannte Ort im Universum?",a:-273,unit:"°C",hint:"Das Boomerang-Nebel ist 1 Kelvin kühl.",emoji:"❄️"},
  {q:"How many Lichtjahre breit ist das Sonnensystem (Oortsche Wolke)?",a:2,unit:"light-years",hint:"Lichtjahre Durchmesser.",emoji:"☄️"},
  {q:"How many Tonnen Meteoritenstaub fällt daily auf die Erde?",a:100,unit:"tons",hint:"Meist als Mikrometeorite.",emoji:"☄️"},
  {q:"How many Nanometer ist das sichtbare Lichtspektrum breit?",a:300,unit:"nanometers",hint:"Von 400nm (violett) bis 700nm (rot).",emoji:"🌈"},
  {q:"How many Jahre dauerte es bis zum ersten schwarzen Loch-Foto?",a:100,unit:"Jahre Theoriezeit",hint:"Einstein beschrieb sie 1915, fotografiert 2019.",emoji:"🌑"},
  {q:"How many Grad Celsius ist die Temperatur in einem Weißen Zwerg?",a:100000,unit:"°C",hint:"Weiße Zwerge kühlen über billion Jahre ab.",emoji:"⭐"},
  {q:"How many km ist der Durchmesser des Mondes?",a:3474,unit:"km",hint:"Etwa 27% des Erddurchmessers.",emoji:"🌙"},
  {q:"How many Stunden dauert ein Venustag genau?",a:5832,unit:"hours",hint:"Ein Venusjahr (224 Tage) ist kürzer als ein Venustag.",emoji:"🪐"},
  {q:"How many km/h dreht sich Neptun an seinem Äquator?",a:9650,unit:"km/h",hint:"Schnellere Rotation als die Erde.",emoji:"🔵"},
  {q:"How many Grad Celsius kalt ist es im Schatten auf dem Mond?",a:-170,unit:"°C",hint:"Extreme Temperaturschwankungen ohne Atmosphäre.",emoji:"🌑"},
  {q:"How far ist die Magellangsche Wolke von der Milchstraße?",a:160000,unit:"light-years",hint:"Die nächste Satellitengalaxie.",emoji:"🌌"},
  {q:"How many Tonnen wiegt ein Kubikmeter Neutronensternmaterial?",a:1000,unit:"trillion tons",hint:"10¹⁵ Tonnen pro m³.",emoji:"⭐"},
  {q:"How many Stunden würde es dauern um mit dem Auto zum Mond zu fahren?",a:5100,unit:"hours",hint:"Bei 100 km/h würde man 5100 Stunden brauchen.",emoji:"🌙"},
  {q:"How many Grad Celsius warm ist die Chromosphäre der Sonne?",a:20000,unit:"°C",hint:"Die Schicht über der Photosphäre.",emoji:"☀️"},
  {q:"How many billion Jahre wird die Sonne noch Energie produzieren?",a:5,unit:"Milliarden Jahre",hint:"Dann wird sie zum Roten Riesen.",emoji:"☀️"},
  {q:"How many km beträgt der Durchmesser von Titan (Saturnmond)?",a:5150,unit:"km",hint:"Größer als Merkur.",emoji:"🪐"},
  {q:"How many Grad Celsius beträgt die Temperatur auf Io (Jupiters Mond)?",a:-130,unit:"°C",hint:"Vulkanisch aktiv trotz extremer Kälte.",emoji:"🌋"},
  {q:"How many km/s bewegt sich unsere Sonne durch die Milchstraße?",a:220,unit:"km/s",hint:"Ein Galaktisches Jahr dauert 225 million Jahre.",emoji:"🌌"},
  {q:"How many Grad Celsius kalt ist der dunkelste bekannte Ort (Boomerang-Nebel)?",a:-272,unit:"°C",hint:"Kälter als der kosmische Hintergrund.",emoji:"❄️"},
  {q:"How many billion Jahre braucht Licht um das Universum zu überqueren?",a:93,unit:"Milliarden Jahre",hint:"Der Durchmesser ist diese Zahl billion Lichtjahre.",emoji:"🌌"},
  {q:"How many km hoch ist die Atmosphäre des Mars?",a:200,unit:"km",hint:"Sehr dünn – weniger als 1% Erddruck.",emoji:"🔴"},
  {q:"How many Stunden braucht Licht von Neptun zur Erde?",a:4,unit:"hours",hint:"Neptun ist diese Zahl,5 billion km entfernt.",emoji:"🔵"},
  {q:"How many Grad Celsius ist die Temperatur auf Titania (Uranus-Mond)?",a:-203,unit:"°C",hint:"Einer der kältesten Monde.",emoji:"🌑"},
  {q:"How many km/h fliegen Sonnenwinde schnell?",a:500000,unit:"km/h",hint:"Bei Sonnenstürmen noch deutlich schneller.",emoji:"☀️"},
  {q:"How many billion Sterne hat die Andromeda-Galaxie?",a:1000,unit:"billion",hint:"Fast doppelt so viele wie die Milchstraße.",emoji:"🌌"},
  {q:"How many Grad Celsius ist das Innere des Jupiterkerns?",a:36000,unit:"°C",hint:"Extremer Druck und Hitze im Zentrum.",emoji:"🪐"},
  {q:"How many km beträgt der Durchmesser von Ceres (Zwergplanet)?",a:945,unit:"km",hint:"Der größte Körper im Asteroidengürtel.",emoji:"🌑"},
  {q:"How many Erdmassen hat Neptun?",a:17,unit:"Erdmassen",hint:"Viel kleiner als Jupiter aber immer noch gewaltig.",emoji:"🔵"},
  {q:"How many km/s rotiert ein Pulsar maximal?",a:0.3,unit:"km/s Oberfläche",hint:"716 Umdrehungen pro Sekunde.",emoji:"⭐"},
  {q:"How many Grad Celsius ist die Temperatur im Kern von Uranus?",a:5000,unit:"°C",hint:"Trotz äußerer Kälte ist der Kern sehr heiß.",emoji:"🟦"},
  {q:"How many km hoch sind die Wolken auf Jupiter?",a:50,unit:"km",hint:"Mehrere Schichten aus Ammoniak und anderen Verbindungen.",emoji:"🪐"},
  {q:"How many Tonnen Materie verliert die Sonne pro Sekunde durch Strahlung?",a:4000000,unit:"tons",hint:"4 million Tonnen daily in Energie umgewandelt.",emoji:"☀️"},
  {q:"How many Stunden braucht ein Lichtstrahl von Pluto zur Erde?",a:5.5,unit:"hours",hint:"Pluto ist ~5,9 billion km weit.",emoji:"🌑"},
  {q:"How many km/h dreht sich die Erde um die Galaxis?",a:792000,unit:"km/h",hint:"220 km/s um das galaktische Zentrum.",emoji:"🌌"},
  {q:"How many Grad beträgt die Inklination von Uranus?",a:98,unit:"Grad",hint:"Uranus liegt fast auf der Seite.",emoji:"🟦"},
  {q:"How many billion Sonnen leuchten im beobachtbaren Universum?",a:2000000000000,unit:"Sterne",hint:"2 Billionen Galaxien mit je ~200 billion Sternen.",emoji:"⭐"},
  {q:"How many Jahre braucht Pluto für einen Umlauf um die Sonne?",a:248,unit:"Erdenjahre",hint:"Seine Umlaufbahn ist sehr elliptisch.",emoji:"🌑"},
  {q:"How many Grad Celsius ist die Oberfläche von Enceladus (Saturnmond)?",a:-201,unit:"°C",hint:"Unter dem Eis gibt es flüssiges Wasser.",emoji:"❄️"},
  {q:"How many million km sind Erde und Mars auf dem nächsten Punkt voneinander entfernt?",a:56,unit:"million km",hint:"million km bei der besten Annäherung.",emoji:"🔴"},
  {q:"How many Grad Celsius kalt ist die interstellare Materie zwischen Sternen?",a:-263,unit:"°C",hint:"Fast absoluter Nullpunkt.",emoji:"❄️"},
  {q:"How many million km lang kann ein Kometen-Schweif werden?",a:150,unit:"million km",hint:"Kometen-Schweife können die Sonne-Erde-Distanz erreichen.",emoji:"☄️"},
  {q:"How many Trillionen Tonnen wiegt der Mond?",a:73,unit:"trillion tons",hint:"7,35 × 10²² kg.",emoji:"🌙"},
  {q:"How many Stunden war die längste Apollo-Mission (Apollo 17) auf dem Mond?",a:75,unit:"hours",hint:"3 Tage 3 Stunden auf der Mondoberfläche.",emoji:"🌙"},
  {q:"How many billion Lichtjahre ist das älteste bekannte Licht entfernt?",a:13.8,unit:"Milliarden Lichtjahre",hint:"Die kosmische Hintergrundstrahlung.",emoji:"🌌"},
  {q:"How many Grad Celsius beträgt die Temperatur in Jupiters Sturm (Großer Roter Fleck)?",a:-160,unit:"°C",hint:"Kälter als die umgebenden Wolken.",emoji:"🪐"},
  {q:"How many billion km entfernt ist die Heliopause (Grenze des Sonnensystems)?",a:18,unit:"billion km",hint:"Die Heliopause – wo Sonnenwind endet.",emoji:"☄️"},
  {q:"How many Erdmassen hat Uranus?",a:14.5,unit:"Erdmassen",hint:"Uranus ist der kleinste Eisriese.",emoji:"🟦"},
  {q:"How many Grad Celsius ist der heißeste bekannte Stern (WR 102)?",a:210000,unit:"°C",hint:"200x heißer als unsere Sonne.",emoji:"⭐"},
  {q:"How many Grad Celsius ist die Oberfläche von Io (Jupiters Mond) an Vulkanen?",a:1600,unit:"°C",hint:"Io hat die aktivsten Vulkane im Sonnensystem.",emoji:"🌋"},
  {q:"How many billion km ist die Oortsche Wolke von der Sonne entfernt?",a:7500,unit:"billion km",hint:"Der äußerste Bereich unseres Sonnensystems.",emoji:"☄️"},
  {q:"How many Stunden braucht Jupiter für einen Umlauf um die Sonne?",a:87672,unit:"hours",hint:"12 Erdenjahre.",emoji:"🪐"},
  {q:"How many km Dicke hat Europas Eisdecke (Jupitermond)?",a:25,unit:"km",hint:"Unter dem Eis: flüssiger Ozean.",emoji:"❄️"},
  {q:"How many billion Sterne entstehen per year in der Milchstraße?",a:1,unit:"Sterne/Jahr",hint:"Etwa 1 neuer Stern per year.",emoji:"⭐"},
  {q:"How many Grad Celsius kalt ist die Mond-Polregion (dauerhafter Schatten)?",a:-248,unit:"°C",hint:"Fast absoluter Nullpunkt in den Kratern.",emoji:"🌑"},
  {q:"How many km/h beträgt die Rotationsgeschwindigkeit von Saturns Kern?",a:30000,unit:"km/h",hint:"Sehr schnelle Rotation des Gasriesen.",emoji:"🪐"},
  {q:"How many billion Jahre braucht die Sonne für eine Umdrehung um die Milchstraße?",a:0.225,unit:"Milliarden Jahre",hint:"225 million Jahre – ein galaktisches Jahr.",emoji:"🌌"},
  {q:"How many Grad Celsius ist die Coronaregion der Sonne?",a:2000000,unit:"°C",hint:"Mysteriöserweise heißer als die Oberfläche.",emoji:"☀️"},
  {q:"How many km ist der Durchmesser von Enceladus (Saturnmond)?",a:500,unit:"km",hint:"Kleiner Mond mit riesigem Wasserausbruch.",emoji:"🪐"},
  {q:"How many Stunden dauert ein Tag auf Pluto?",a:153,unit:"hours",hint:"6 Erdtage 9 Stunden.",emoji:"🌑"},
  {q:"How many million Tonnen Helium produziert die Sonne daily?",a:695,unit:"million tons",hint:"million Tonnen daily.",emoji:"☀️"},
  {q:"How many km Höhe hat der Mount Olympus auf dem Mars?",a:21,unit:"km",hint:"Der höchste bekannte Vulkan im Sonnensystem.",emoji:"🔴"},
  {q:"How many Grad Celsius ist die Temperatur auf der Venus-Oberfläche nachts?",a:465,unit:"°C",hint:"Tag und Nacht fast gleich heiß durch Treibhauseffekt.",emoji:"🌋"},
  {q:"How many km/h bewegen sich interstellare Kometen?",a:100000,unit:"km/h",hint:"ʻOumuamua bewegte sich mit über 85.000 km/h.",emoji:"☄️"},
  {q:"How many Grad Celsius ist die Temperatur im Kern von Neutronensternen?",a:100000000000,unit:"°C",hint:"100 billion Grad – unvorstellbar.",emoji:"⭐"},
  {q:"How many billion km ist Saturns äußerster Mond Phoebe entfernt?",a:12.9,unit:"Mio. km",hint:"12,9 million km von Saturn.",emoji:"🪐"},
  {q:"How many Grad dreht sich die Sonne per day an ihrem Äquator?",a:14,unit:"Grad",hint:"Die Sonne dreht sich differenziell – Äquator schneller.",emoji:"☀️"},
  {q:"How many Stunden nach dem Urknall bildeten sich die ersten Atomkerne?",a:3,unit:"minutes",hint:"Big Bang Nukleosynthese dauerte 3 Minuten.",emoji:"⚛️"},
  {q:"How many km/h schnell rasen Sonnenwinde bei Sonnenstürmen?",a:3000000,unit:"km/h",hint:"3 million km/h bei starken Sonneneruptionen.",emoji:"☀️"},
  {q:"How many billion Tonnen Eis enthält der Nordpol des Mars?",a:1600,unit:"billion tons",hint:"Genug um den Mars 11m tief in Wasser zu hüllen.",emoji:"🔴"},
  {q:"How many Grad Celsius kalt ist Triton (Neptunmond)?",a:-235,unit:"°C",hint:"Einer der kältesten Körper im Sonnensystem.",emoji:"❄️"},
  {q:"How many km beträgt der Durchmesser von Pluto?",a:2377,unit:"km",hint:"Kleiner als Russland.",emoji:"🌑"},
  {q:"How many Stunden braucht Licht von Alpha Centauri zur Erde?",a:38264,unit:"hours",hint:"4,37 Lichtjahre × 8760 Stunden/Jahr.",emoji:"⭐"},
  {q:"How many km/h rotiert die Oberfläche der Sonne am Äquator?",a:7000,unit:"km/h",hint:"~2 km/s Rotationsgeschwindigkeit.",emoji:"☀️"},
  {q:"How many billion Tonnen hat ein typischer Asteroid im Asteroidengürtel?",a:1,unit:"million tons",hint:"Die meisten Asteroiden sind sehr klein.",emoji:"☄️"},
  {q:"How many Grad Celsius kalt ist es in Merkurs Polkratern?",a:-180,unit:"°C",hint:"Ewiges Eis in dauerhaft beschattetem Gebiet.",emoji:"☿"},
];
