// 🍆 SEX & TABOOS – English
export default [
  {q:"How many million Pornos gibt es schätzungsweise im Internet?",a:4000000,unit:"Videos",hint:"Über 4 million Videos – und daily kommen neue dazu.",emoji:"🔞"},
  {q:"How many million Besucher hat Pornhub per day?",a:130,unit:"million",hint:"Einer der meistbesuchten Websites worldwide.",emoji:"💻"},
  {q:"How many Gramm wiegt ein durchschnittlicher Dildo?",a:200,unit:"grams",hint:"Variiert stark je nach Material und Größe.",emoji:"🍆"},
  {q:"In what year wurde das erste Kondom aus Latex hergestellt?",a:1920,unit:"Jahr",hint:"Davor waren Kondome aus Schafsdarm.",emoji:"💊"},
  {q:"How many Kalorien verbrennt man beim Oralsex per hour?",a:100,unit:"kcal",hint:"Mehr als man denkt – Muskeln sind im Einsatz.",emoji:"🔥"},
  {q:"How many cm ist der durchschnittliche erigierte Penis in Deutschland?",a:14.5,unit:"cm",hint:"Deutsche Männer liegen leicht über dem globalen Schnitt.",emoji:"📏"},
  {q:"How many percent der Frauen können durch Penetration allein zum Orgasmus kommen?",a:18,unit:"%",hint:"Die meisten Frauen brauchen zusätzliche Klitoris-Stimulation.",emoji:"🔬"},
  {q:"How many million Menschen worldwide sind an HIV infiziert?",a:39,unit:"million",hint:"Stand 2022 – antiretrovirale Therapie hilft.",emoji:"🎗️"},
  {q:"How long dauert der durchschnittliche Geschlechtsakt laut Studie in Minuten?",a:5.4,unit:"minutes",hint:"Von Penetration bis Ejakulation gemessen.",emoji:"⏱️"},
  {q:"How many million Spermien enthält ein durchschnittlicher Ejakulationsschuss?",a:250,unit:"million",hint:"Nur eines davon befruchtet die Eizelle.",emoji:"🔬"},
  {q:"In what year wurde Viagra zugelassen?",a:1998,unit:"Jahr",hint:"FDA-Zulassung am 27. März 1998.",emoji:"💊"},
  {q:"How many Nervenendigungen hat die Klitoris?",a:8000,unit:"Nervenenden",hint:"Doppelt so viele wie der Penis.",emoji:"⚡"},
  {q:"How many cm ist die durchschnittliche Vaginaltiefe in Ruhe?",a:9,unit:"cm",hint:"Erregt dehnt sie sich auf 12-15 cm aus.",emoji:"📏"},
  {q:"How many million Dollar wert ist die globale Sexspielzeug-Industrie?",a:33000,unit:"million $",hint:"33 billion Dollar – wächst annually.",emoji:"💰"},
  {q:"How many Mal per year hat ein Deutscher on average Sex?",a:98,unit:"times",hint:"Fast zweimal per week laut Umfragen.",emoji:"❤️"},
  {q:"How many Stunden im Leben verbringt a human mit Sex?",a:520,unit:"hours",hint:"Etwa 21 Tage – über ein Leben gerechnet.",emoji:"⏰"},
  {q:"How many cm beträgt die durchschnittliche Penislänge schlaff?",a:9,unit:"cm",hint:"Im Durchschnitt 7-10 cm schlaff.",emoji:"📏"},
  {q:"In what year wurde der erste Vibrator erfunden?",a:1880,unit:"Jahr",hint:"Ursprünglich als medizinisches Gerät für 'Hysterie'.",emoji:"⚡"},
  {q:"How many Sekunden dauert die durchschnittliche weibliche Orgasmus-Kontraktion?",a:22,unit:"seconds",hint:"Weibliche Orgasmen dauern länger als männliche.",emoji:"🌊"},
  {q:"How many percent der Männer haben Erektionsprobleme?",a:25,unit:"%",hint:"Betrifft Männer aller Altersgruppen.",emoji:"📊"},
  {q:"How many million Mal wird der Begriff 'sex' daily gegoogelt?",a:8,unit:"million",hint:"Einer der meistgesuchten Begriffe worldwide.",emoji:"🔍"},
  {q:"How many cm lang ist die durchschnittliche Brust-Brustwarze im Durchmesser?",a:1.5,unit:"cm",hint:"Brustwarzen variieren stark in Größe und Form.",emoji:"📏"},
  {q:"In what year wurde die Pille erfunden?",a:1960,unit:"Jahr",hint:"FDA-Zulassung 1960 – revolutionierte Frauenrechte.",emoji:"💊"},
  {q:"How many million Kondome werden worldwide daily verwendet?",a:6,unit:"million",hint:"billion per year.",emoji:"💊"},
  {q:"How many percent der Menschen haben schon einen One-Night-Stand gehabt?",a:66,unit:"%",hint:"Zwei Drittel aller Erwachsenen laut Umfragen.",emoji:"🌙"},
  {q:"How many Grad Celsius erhöht sich die Körpertemperatur beim Orgasmus?",a:0.3,unit:"°C",hint:"Eine leichte aber messbare Erwärmung.",emoji:"🌡️"},
  {q:"How many million Menschen worldwide haben Syphilis?",a:7,unit:"million",hint:"Immer noch verbreitet – trotz Antibiotika.",emoji:"🔬"},
  {q:"How long dauert eine Erektion im Schnitt an?",a:30,unit:"minutes",hint:"Inklusive aller sexuellen Aktivitäten.",emoji:"⏰"},
  {q:"How many Gramm Protein enthält Sperma per ejaculation?",a:300,unit:"mg",hint:"Weniger als eine Tasse Milch.",emoji:"⚗️"},
  {q:"How many percent der Menschen praktizieren Oralsex?",a:80,unit:"%",hint:"Sehr weit verbreitet unter Erwachsenen.",emoji:"📊"},
  {q:"In what year wurde das erste Sexspielzeug für Männer (Fleshlight) erfunden?",a:1995,unit:"Jahr",hint:"Patentiert von Steve Shubin.",emoji:"📅"},
  {q:"How many cm ist der Abstand zwischen Klitoris und Vaginalöffnung on average?",a:2.5,unit:"cm",hint:"Beeinflusst die Orgasmusfähigkeit.",emoji:"📏"},
  {q:"How many million Dollar verdient der meistbezahlte Pornodarsteller?",a:1,unit:"Mio. Dollar/Jahr",hint:"Frauen verdienen in der Branche oft mehr.",emoji:"💰"},
  {q:"How many percent der Deutschen haben schon Sex im Freien gehabt?",a:55,unit:"%",hint:"Outdoor-Sex ist überraschend populär.",emoji:"🌿"},
  {q:"How many Stunden schlafen Menschen die viel Sex haben länger?",a:1,unit:"Stunde mehr",hint:"Orgasmus setzt schlaffördernde Hormone frei.",emoji:"😴"},
  {q:"How many million Menschen sind worldwide in der Sexarbeit tätig?",a:40,unit:"million",hint:"Schätzung – schwer messbar durch Illegalität.",emoji:"🌍"},
  {q:"How many cm lang ist die G-Punkt-Zone von der Vaginalöffnung?",a:5,unit:"cm",hint:"An der vorderen Vaginalwand.",emoji:"📏"},
  {q:"In what year wurde Sexarbeit in Deutschland legalisiert?",a:2002,unit:"Jahr",hint:"Das Prostitutionsgesetz trat am 1. Januar 2002 in Kraft.",emoji:"📜"},
  {q:"How many percent der Frauen masturbieren regelmäßig?",a:67,unit:"%",hint:"Ähnlich wie bei Männern – Mythos widerlegt.",emoji:"📊"},
  {q:"How many million Besucher hat OnlyFans?",a:220,unit:"million",hint:"Registrierte Nutzer – mit 2,5 Mio. Creators.",emoji:"📱"},
  {q:"How many Gramm wiegt ein Durchschnitts-Hoden?",a:20,unit:"grams",hint:"Beide Hoden zusammen wiegen 40 Gramm.",emoji:"⚖️"},
  {q:"How many percent der Paare haben schon Rollenspiele ausprobiert?",a:45,unit:"%",hint:"Häufiger als die meisten denken.",emoji:"🎭"},
  {q:"In what year wurde der erste Erotik-Film gedreht?",a:1896,unit:"Jahr",hint:"Le Coucher de la Mariée – 7 Minuten lang.",emoji:"🎬"},
  {q:"How many Mal pro Nacht hat ein gesunder Mann eine Erektion im Schlaf?",a:4,unit:"times",hint:"NPT – nächtliche penile Tumeszenz.",emoji:"😴"},
  {q:"How many percent der Deutschen haben schon Cybersex gehabt?",a:30,unit:"%",hint:"Videochat, Sexting und ähnliches.",emoji:"💻"},
  {q:"How many cm ist die durchschnittliche Brust in Deutschland (Körbchen)?",a:75,unit:"cm Unterbrustweite",hint:"Körbchen B/C ist am häufigsten in Deutschland.",emoji:"👙"},
  {q:"How many million Dollar wert ist der globale Erotik-Literatur-Markt?",a:1500,unit:"million $",hint:"Fifty Shades of Grey allein brachte billion.",emoji:"📚"},
  {q:"How many percent der Menschen haben einen Fetisch?",a:30,unit:"%",hint:"Füße sind der häufigste Körper-Fetisch.",emoji:"🦶"},
  {q:"How long dauert der Samenerguss on average in Sekunden?",a:8,unit:"seconds",hint:"Die Muskelkontraktionen dauern 3-15 Sekunden.",emoji:"⏱️"},
  {q:"How many million Deutschen geben an, regelmäßig Pornos zu schauen?",a:25,unit:"million",hint:"Jeder dritte Deutsche.",emoji:"📺"},
  {q:"How many cm beträgt der durchschnittliche Brust-Umfang einer Frau in Deutschland?",a:97,unit:"cm",hint:"Brustumfang variiert stark.",emoji:"📏"},
  {q:"In what year erschien Fifty Shades of Grey?",a:2011,unit:"Jahr",hint:"E.L. James' BDSM-Roman wurde zum Weltbestseller.",emoji:"📖"},
  {q:"How many million Exemplare verkaufte Fifty Shades of Grey?",a:150,unit:"million",hint:"Eines der meistverkauften Bücher aller Zeiten.",emoji:"📚"},
  {q:"How many percent der BDSM-Praktizierenden bezeichnen sich als 'Switch'?",a:30,unit:"%",hint:"Weder dominant noch submissiv – sondern beides.",emoji:"🔄"},
  {q:"How many cm ist die durchschnittliche weibliche Brustwarze lang?",a:1,unit:"cm",hint:"Im Ruhezustand etwa 1 cm.",emoji:"📏"},
  {q:"How many million Menschen in Deutschland haben schon Analverkehr praktiziert?",a:20,unit:"million",hint:"Etwa 35-40% der Bevölkerung.",emoji:"📊"},
  {q:"How many Grad Celsius wird die Klitoris beim Orgasmus wärmer?",a:2,unit:"°C",hint:"Messbar durch Infrarotthermografie.",emoji:"🌡️"},
  {q:"How many Stunden schaut ein Durchschnittsdeutscher Pornos per month?",a:4,unit:"hours",hint:"Laut anonymen Nutzungsdaten.",emoji:"📺"},
  {q:"In what year wurde Sex in der Raumstation ISS zum ersten Mal theoretisch diskutiert?",a:2006,unit:"Jahr",hint:"NASA-Studie über Sex im All.",emoji:"🚀"},
  {q:"How many percent der Frauen haben vorgespielt, einen Orgasmus zu haben?",a:67,unit:"%",hint:"Faking it ist überraschend verbreitet.",emoji:"🎭"},
  {q:"How many million Menschen haben eine Sexsucht?",a:16,unit:"million",hint:"3-6% der Bevölkerung – hauptsächlich Männer.",emoji:"🔬"},
  {q:"How many percent der Deutschen haben Sex mit einem Kollegen gehabt?",a:40,unit:"%",hint:"Büroromanen sind sehr häufig.",emoji:"💼"},
  {q:"How many cm lang ist die durchschnittliche erigierte Klitoris?",a:10,unit:"cm",hint:"Die innere Struktur – nicht nur die sichtbare Eichel.",emoji:"📏"},
  {q:"In what year wurde das erste Bordell der Geschichte dokumentiert?",a:600,unit:"v.Chr.",hint:"Im antiken Griechenland unter Solon.",emoji:"🏛️"},
  {q:"How many percent der Deutschen geben an, mit ihrem Sexleben unzufrieden zu sein?",a:30,unit:"%",hint:"Laut repräsentativer Umfragen.",emoji:"😔"},
  {q:"How many million Dollar kostete die Produktion von Fifty Shades of Grey (Film)?",a:40,unit:"million $",hint:"Und spielte 569 Mio. Dollar ein.",emoji:"🎬"},
  {q:"How many percent der Menschen haben Sex im Auto gehabt?",a:60,unit:"%",hint:"Ein sehr verbreiteter Fantasie-Ort.",emoji:"🚗"},
  {q:"How many Gramm wiegt eine Prostata?",a:25,unit:"grams",hint:"Im Alter kann sie auf 100g wachsen.",emoji:"⚖️"},
  {q:"In what year wurde das erste legal produzierte Porno-Video verkauft?",a:1972,unit:"Jahr",hint:"Deep Throat – der erste Mainstream-Pornofilm.",emoji:"🎬"},
  {q:"How many percent der Deutschen sind in offenen Beziehungen?",a:8,unit:"%",hint:"Polyamorie und ENM wachsen.",emoji:"💕"},
  {q:"How many cm ist der Menstrual-Cup on average groß?",a:7,unit:"cm",hint:"Umweltfreundliche Alternative zu Tampons.",emoji:"📏"},
  {q:"How many million Menschen schauen daily Pornos auf mobilen Geräten?",a:90,unit:"million",hint:"Über 70% des Traffics kommt von Smartphones.",emoji:"📱"},
  {q:"How many Stunden Porno werden daily auf Pornhub hochgeladen?",a:115,unit:"hours",hint:"Täglich neue Inhalte.",emoji:"📹"},
  {q:"How many percent der Schwangerschaften sind ungeplant?",a:45,unit:"%",hint:"Weltweit – in Deutschland etwa 30%.",emoji:"🤰"},
  {q:"In what year wurde das erste Kondom aus Kunststoff (Polyurethan) eingeführt?",a:1994,unit:"Jahr",hint:"Alternative für Latex-Allergiker.",emoji:"💊"},
  {q:"How many percent der Deutschen geben zu, ihr Handy beim Sex zu nutzen?",a:25,unit:"%",hint:"Ablenkung durch Smartphones auch im Schlafzimmer.",emoji:"📱"},
  {q:"How many ml Vaginalflüssigkeit produziert a woman beim Sex?",a:4,unit:"ml",hint:"Natürliche Befeuchtungsreaktion.",emoji:"💧"},
  {q:"How many million Dollar verdiente die Pornodarstellerin Lisa Ann auf ihrem Höhepunkt?",a:1.5,unit:"Mio. Dollar/Jahr",hint:"Einem der bekanntesten Stars der Branche.",emoji:"💰"},
  {q:"How many percent der Männer konsumieren daily Pornos?",a:18,unit:"%",hint:"Regelmäßiger Konsum unter Männern.",emoji:"📊"},
  {q:"How many cm ist die Vagina beim Squirting gedehnt?",a:15,unit:"cm",hint:"Dehnung durch Erregung.",emoji:"📏"},
  {q:"In what year wurde die erste Penisvergrößerungsoperation dokumentiert?",a:1971,unit:"Jahr",hint:"Chirurgische Eingriffe seit den 1970ern.",emoji:"🏥"},
  {q:"How many percent der Menschen haben einen Fußfetisch?",a:7,unit:"%",hint:"Der häufigste körperbezogene Fetisch.",emoji:"🦶"},
  {q:"How many million Dollar wert ist der globale Markt für Erotik-Videospiele?",a:100,unit:"million $",hint:"Nische aber wachsend.",emoji:"🎮"},
  {q:"How many percent der Deutschen haben schon Sexting betrieben?",a:50,unit:"%",hint:"Digitale Intimität ist verbreitet.",emoji:"📱"},
  {q:"How many Gramm Fruchtzucker enthält Sperma?",a:2.5,unit:"mg",hint:"Frukose gibt Spermien Energie.",emoji:"⚗️"},
  {q:"In what year wurde die erste Sexklinik in Deutschland eröffnet?",a:1918,unit:"Jahr",hint:"Magnus Hirschfeld eröffnete das Institut für Sexualwissenschaft.",emoji:"🏥"},
  {q:"How many percent der Deutschen haben schon Sex auf einer öffentlichen Toilette gehabt?",a:15,unit:"%",hint:"Riskanter Lustort.",emoji:"🚻"},
  {q:"How many cm beträgt die durchschnittliche Vaginaltiefe beim Sex (erregt)?",a:13,unit:"cm",hint:"Von 9cm in Ruhe auf 12-15cm erregt.",emoji:"📏"},
  {q:"How many million Pornhub-Suchanfragen kommen daily aus Deutschland?",a:10,unit:"million",hint:"Deutschland gehört zu den Top-Konsumenten.",emoji:"🔍"},
  {q:"How many percent der Menschen haben schon an einem Dreier teilgenommen?",a:20,unit:"%",hint:"Häufiger praktiziert als zugegeben.",emoji:"📊"},
  {q:"How many Stunden dauert der längste bekannte Orgasmus in Sekunden?",a:43,unit:"seconds",hint:"Gemessen im Labor.",emoji:"⏱️"},
  {q:"In what year wurde das erste Sexdolls-Unternehmen gegründet?",a:1997,unit:"Jahr",hint:"RealDoll aus San Diego war der Pionier.",emoji:"🤖"},
  {q:"How many percent der Deutschen kennen ihre Erogenous-Zonen?",a:55,unit:"%",hint:"Fast die Hälfte ist unsicher über den eigenen Körper.",emoji:"📊"},
  {q:"How many cm Länge hat ein durchschnittlicher Vibrator?",a:18,unit:"cm",hint:"Der Klassiker.",emoji:"📏"},
  {q:"How many million Dollar Umsatz macht die BDSM-Industrie?",a:500,unit:"million $",hint:"Bondage, Dominanz, Sadismus, Masochismus.",emoji:"🔗"},
  {q:"How many percent der Deutschen haben schon Stripclubs besucht?",a:35,unit:"%",hint:"Männer häufiger als Frauen.",emoji:"💃"},
  {q:"How many Gramm Zink enthält eine Ejakulation?",a:5,unit:"mg",hint:"Milligramm – essenziell für Spermienqualität.",emoji:"⚗️"},
  {q:"In what year gründete Hugh Hefner das Playboy-Magazin?",a:1953,unit:"Jahr",hint:"Marilyn Monroe war auf dem ersten Cover.",emoji:"🐰"},
  {q:"How many percent der Frauen mögen Analstimulation?",a:35,unit:"%",hint:"Häufiger als offen zugegeben.",emoji:"📊"},
  {q:"How many million Pornhub-Suchanfragen gehen daily ein?",a:100,unit:"million",hint:"million daily – eine gigantische Zahl.",emoji:"🔍"},
  {q:"How many cm lang ist ein durchschnittlicher Anal-Plug?",a:10,unit:"cm",hint:"Viele Variationen – von klein bis groß.",emoji:"📏"},
  {q:"In what year wurde der Begriff 'Bisexualität' erstmals wissenschaftlich verwendet?",a:1892,unit:"Jahr",hint:"Von Charles Gilbert Chaddock.",emoji:"🔬"},
  {q:"How many percent der Menschen identifizieren sich als bisexuell?",a:7,unit:"%",hint:"Laut neueren Umfragen – steigend.",emoji:"🌈"},
  {q:"How many million Dollar wert ist der globale Markt für Lubricants?",a:800,unit:"million $",hint:"Gleitmittel sind ein riesiger Markt.",emoji:"💰"},
  {q:"How many percent der Menschen haben schon an einem Swingerclub teilgenommen?",a:5,unit:"%",hint:"Häufiger unter Paaren Mitte 30.",emoji:"📊"},
  {q:"How many cm ist die durchschnittliche Zungenlänge beim Küssen relevant?",a:10,unit:"cm",hint:"Franzosenkuss beinhaltet die halbe Zunge.",emoji:"💋"},
  {q:"In what year wurde das erste Nackt-Fotoshooting in einer Zeitschrift veröffentlicht?",a:1896,unit:"Jahr",hint:"In frühen Kunstzeitschriften.",emoji:"📸"},
  {q:"How many percent der Deutschen haben schon Sex auf Drogeneinfluss gehabt?",a:40,unit:"%",hint:"Alkohol ist die häufigste Substanz dabei.",emoji:"🍷"},
  {q:"How many Gramm wiegt die Gebärmutter?",a:70,unit:"grams",hint:"Im Nicht-Schwanger-Zustand.",emoji:"⚖️"},
  {q:"How many million Menschen haben Gonorrhoe worldwide?",a:82,unit:"million",hint:"Eine der häufigsten STIs.",emoji:"🔬"},
  {q:"How many percent der Männer über 70 sind noch sexuell aktiv?",a:40,unit:"%",hint:"Sexualität hört nicht mit dem Alter auf.",emoji:"👴"},
  {q:"How many cm lang ist die durchschnittliche Penisvorhaut?",a:5,unit:"cm",hint:"Variiert stark.",emoji:"📏"},
  {q:"In what year wurde der erste Homosexuellen-Club in Deutschland eröffnet?",a:1897,unit:"Jahr",hint:"Hirschfelds Wissenschaftlich-humanitäres Komitee.",emoji:"🌈"},
  {q:"How many million Menschen schauen daily Pornos auf Arbeit?",a:30,unit:"million",hint:"Überraschend viele Nutzer worldwide.",emoji:"💼"},
  {q:"How many percent der Deutschen haben Sex im Büro gehabt?",a:20,unit:"%",hint:"Workplace-Romances sind verbreitet.",emoji:"🏢"},
  {q:"How many Gramm wiegen beide Brüste einer C-Körbchen-Frau zusammen?",a:500,unit:"grams",hint:"Etwa 500g – je nach Größe.",emoji:"⚖️"},
  {q:"How many Stunden dauert die durchschnittliche Honeymoon-Nacht in Stunden?",a:3,unit:"hours",hint:"Mehr Schlafen als gedacht.",emoji:"🌙"},
  {q:"In what year wurde der erste Swingerclub in Deutschland eröffnet?",a:1971,unit:"Jahr",hint:"In den liberalen 70ern.",emoji:"🕺"},
  {q:"How many percent der Frauen bezeichnen den Vibrator als ihren besten Freund?",a:25,unit:"%",hint:"Laut einer internationalen Umfrage.",emoji:"⚡"},
  {q:"How many cm ist die durchschnittliche Länge eines Liebeskugel-Sets?",a:20,unit:"cm",hint:"Liebeskugeln für Beckenboden-Training.",emoji:"📏"},
  {q:"How many million Accounts gibt es auf OnlyFans?",a:220,unit:"million",hint:"Nutzer plus Creator-Accounts.",emoji:"📱"},
  {q:"How many percent der Menschen können gleichzeitig mehrere Orgasmen haben (Frauen)?",a:70,unit:"%",hint:"Multiples Kommen ist bei Frauen häufig möglich.",emoji:"🌊"},
  {q:"In what year wurde der erste Striptease-Club in den USA eröffnet?",a:1969,unit:"Jahr",hint:"In San Francisco während der Sexual Revolution.",emoji:"💃"},
  {q:"How many Gramm wiegt ein Strap-on-Dildo on average?",a:300,unit:"grams",hint:"Je nach Material zwischen 200-500g.",emoji:"⚖️"},
  {q:"How many percent der Deutschen haben bereits Sextourismus betrieben?",a:8,unit:"%",hint:"Hauptziele: Thailand, Niederlande, Spanien.",emoji:"✈️"},
  {q:"How many cm ist die durchschnittliche Penisbreite erigiert?",a:12,unit:"cm Umfang",hint:"Der Umfang variiert stärker als die Länge.",emoji:"📏"},
  {q:"How many million Euro generiert die deutsche Sexarbeit per year?",a:15000,unit:"million €",hint:"15 billion Euro annually in Deutschland.",emoji:"💶"},
  {q:"How many percent der Menschen haben Sex-Fantasien über Prominente?",a:80,unit:"%",hint:"Fast jeder hat schon davon geträumt.",emoji:"💭"},
  {q:"In what year wurde das erste weibliche Kondom zugelassen?",a:1993,unit:"Jahr",hint:"FDA-Zulassung 1993.",emoji:"💊"},
  {q:"How many cm ist die durchschnittliche Klitoris-Vorhaut lang?",a:0.5,unit:"cm",hint:"Das Präputium Clitoridis.",emoji:"📏"},
  {q:"How many million Escorts sind worldwide tätig?",a:1,unit:"Million",hint:"Schätzungen – exakte Zahlen nicht messbar.",emoji:"💼"},
  {q:"How many percent der Deutschen kennen den Begriff 'Pegging'?",a:30,unit:"%",hint:"Anale Penetration des Mannes durch a woman mit Strap-on.",emoji:"📊"},
  {q:"How many Stunden hat der weltlängste gemessene Geschlechtsakt gedauert?",a:15,unit:"hours",hint:"Dokumentiert in einer Studie.",emoji:"⏰"},
  {q:"In what year wurde das Phänomen 'Female Ejaculation' wissenschaftlich anerkannt?",a:1982,unit:"Jahr",hint:"Erstmals 1982 wissenschaftlich beschrieben.",emoji:"🔬"},
  {q:"How many percent der Männer sagen, sie sind zufrieden mit ihrer Penislänge?",a:55,unit:"%",hint:"Fast die Hälfte hadert mit der Körperwahrnehmung.",emoji:"📊"},
  {q:"How many cm ist der kürzeste klinisch dokumentierte erigierte Penis?",a:1,unit:"cm",hint:"Mikropenis wird unter 7cm erigiert definiert.",emoji:"📏"},
  {q:"How many million Menschen haben Chlamydien worldwide?",a:127,unit:"million",hint:"Die häufigste bakterielle STI.",emoji:"🔬"},
  {q:"How many percent der Frauen erleben Pain beim Sex (Dyspareunie)?",a:20,unit:"%",hint:"Häufig durch Austrocknugg oder andere Faktoren.",emoji:"📊"},
  {q:"In what year gründete Alfred Kinsey sein Sexualforschungsinstitut?",a:1947,unit:"Jahr",hint:"Das Kinsey Institute in Indiana.",emoji:"🔬"},
  {q:"How many percent der Männer haben Sex mit anderen Männern, identifizieren sich aber als hetero?",a:5,unit:"%",hint:"Down-Low-Phänomen in Studien gemessen.",emoji:"📊"},
  {q:"How many cm ist die längste dokumentierte erigierte Penislänge?",a:34,unit:"cm",hint:"Jonah Falcon aus New York.",emoji:"📏"},
  {q:"How many million Dollar wert ist der globale Markt für Potenzpillen?",a:6000,unit:"million $",hint:"Viagra, Cialis und Generika.",emoji:"💊"},
  {q:"How many percent der Deutschen haben schon an einem Orgasmus-Workshop teilgenommen?",a:3,unit:"%",hint:"Nische aber wachsend.",emoji:"📊"},
  {q:"How many Stunden dauert Vorspiel on average laut Studien?",a:18,unit:"minutes",hint:"Zu wenig laut den meisten Frauen.",emoji:"⏱️"},
  {q:"In what year wurde das erste Sex-Museum in Amsterdam eröffnet?",a:1985,unit:"Jahr",hint:"Das Sexmuseum Amsterdam.",emoji:"🏛️"},
  {q:"How many percent der Menschen haben schon Phone-Sex gehabt?",a:35,unit:"%",hint:"Digitale Intimität seit den 90ern.",emoji:"📞"},
  {q:"How many cm lang ist die durchschnittliche Analöffnung beim Entspanntsein?",a:3,unit:"cm",hint:"Kann durch Training und Entspannung größer werden.",emoji:"📏"},
  {q:"How many million Menschen sind in der Welt als Transfrau oder Transmann identifiziert?",a:25,unit:"million",hint:"Schätzungen variieren – worldwide ~0,3% der Bevölkerung.",emoji:"🏳️‍⚧️"},
  {q:"How many percent der Deutschen haben schon virtuellen Sex (VR) ausprobiert?",a:8,unit:"%",hint:"VR-Pornografie ist im Wachstum.",emoji:"🥽"},
  {q:"How many Gramm wiegt eine Geburtskontrollpille?",a:30,unit:"mg",hint:"Milligramm daily – winzig aber wirkungsvoll.",emoji:"⚖️"},
  {q:"In what year wurde das erste FKK-Gelände in Deutschland eröffnet?",a:1920,unit:"Jahr",hint:"Die Freikörperkultur begann in den 20ern.",emoji:"🌞"},
  {q:"How many percent der Paare haben Sex weniger als einmal per week?",a:50,unit:"%",hint:"Sexuelle Aktivität nimmt mit der Zeit ab.",emoji:"📊"},
  {q:"How many ml fasst ein Analplug on average?",a:100,unit:"ml",hint:"Variiert je nach Größe.",emoji:"💧"},
  {q:"How many million Euro Umsatz macht der deutsche Sexspielzeug-Markt?",a:400,unit:"million €",hint:"Wächst annually um 10%.",emoji:"💶"},
  {q:"How many percent der Menschen haben ein dominantes Schlafzimmer-Verhalten?",a:50,unit:"%",hint:"Etwa die Hälfte bevorzugt eine dominante Rolle.",emoji:"📊"},
  {q:"In what year wurde der Kegel-Beckenboden-Trainer erfunden?",a:1948,unit:"Jahr",hint:"Dr. Arnold Kegel entwickelte die Übungen.",emoji:"💪"},
  {q:"How many cm ist die durchschnittliche Länge eines Butt-Plugs?",a:10,unit:"cm",hint:"Je nach Größe und Erfahrung.",emoji:"📏"},
  {q:"How many percent der Männer geben zu, Pornos zu schauen?",a:75,unit:"%",hint:"Die wahre Zahl ist wahrscheinlich höher.",emoji:"📊"},
  {q:"How many million Kondome werden in Deutschland per year verkauft?",a:200,unit:"million",hint:"Sinkende Tendenz durch Pille und IUDs.",emoji:"💊"},
  {q:"How many percent der Menschen erleben Orgasmusprobleme?",a:40,unit:"%",hint:"Häufiger bei Frauen als bei Männern.",emoji:"📊"},
  {q:"In what year erschien das Kamasutra in Europa erstmals?",a:1883,unit:"Jahr",hint:"Richard Burton übersetzte es ins Englische.",emoji:"📖"},
  {q:"How many Positionen beschreibt das Kamasutra?",a:64,unit:"Positionen",hint:"Viele davon sind für den Alltag kaum praktisch.",emoji:"📖"},
  {q:"How many percent der Deutschen kennen ihre eigene G-Punkt-Region?",a:40,unit:"%",hint:"Weniger als die Hälfte laut Umfrage.",emoji:"📊"},
  {q:"How many cm ist die längste dokumentierte Vaginaltiefe?",a:20,unit:"cm",hint:"Starke individuelle Variation.",emoji:"📏"},
  {q:"How many million Dollar wert ist der globale Markt für Sex-Drogen (Aphrodisiaka)?",a:2000,unit:"million $",hint:"Rhino-Produkte, Oyster-Extrakte und mehr.",emoji:"💊"},
  {q:"How many percent der Deutschen haben schon beim Sex gelacht?",a:85,unit:"%",hint:"Humor und Sex passen gut zusammen.",emoji:"😂"},
  {q:"How many Stunden braucht der Körper um sich nach dem Sex zu erholen?",a:2,unit:"hours",hint:"Bis Herzschlag und Hormone normalisiert sind.",emoji:"💓"},
  {q:"In what year wurde die erste Sextherapie-Praxis in Deutschland eröffnet?",a:1975,unit:"Jahr",hint:"Nach Masters & Johnson's Forschungen.",emoji:"🏥"},
  {q:"How many percent der Menschen fantasieren beim Sex an jemand anderen?",a:75,unit:"%",hint:"Sehr verbreitet und psychologisch normal.",emoji:"💭"},
  {q:"How many cm groß ist ein durchschnittlicher Brustnippel?",a:0.5,unit:"cm Höhe",hint:"Variiert stark von Person zu Person.",emoji:"📏"},
  {q:"How many million Dollar hat die Pornodarstellerin Mia Khalifa insgesamt verdient?",a:12,unit:"Tausend Dollar",hint:"Nur 12.000 Dollar in ihrer kurzen Karriere.",emoji:"💰"},
  {q:"How many percent der Paare geben an, ein gesundes Sexleben zu haben?",a:52,unit:"%",hint:"Knappe Mehrheit laut Befragungen.",emoji:"📊"},
  {q:"How many Gramm Glukose werden beim Sex verbrannt?",a:8,unit:"grams",hint:"Entspricht einem kleinen Stück Schokolade.",emoji:"🍫"},
  {q:"In what year wurde das erste Porno-Magazin (Playboy) gegründet?",a:1953,unit:"Jahr",hint:"Hugh Hefner startete eine Revolution.",emoji:"🐰"},
  {q:"How many percent der Menschen haben schon Sex im Freien gehabt?",a:55,unit:"%",hint:"Frische Luft und Abenteuer.",emoji:"🌿"},
  {q:"How many million Menschen identifizieren sich worldwide als homosexuell?",a:390,unit:"million",hint:"Ca. 5% der Weltbevölkerung.",emoji:"🌈"},
  {q:"How many Stunden Vorspiel brauchen Frauen on average für einen Orgasmus?",a:20,unit:"minutes",hint:"Minuten Stimulation im Schnitt.",emoji:"⏱️"},
  {q:"In what year wurde der Analverkehr in Deutschland legalisiert?",a:1969,unit:"Jahr",hint:"Paragraf 175 wurde reformiert.",emoji:"📜"},
  {q:"How many percent der Deutschen haben schon mit einem Fremden geschlafen?",a:45,unit:"%",hint:"One-Night-Stands mit Fremden.",emoji:"🌙"},
  {q:"How many cm ist ein durchschnittlicher Liebeskugelstrang lang?",a:25,unit:"cm",hint:"Verbundene Kugeln für Beckenboden.",emoji:"📏"},
  {q:"How many million Euro wert ist der deutsche Erotik-Film-Markt?",a:200,unit:"million €",hint:"Produktionen aus Deutschland.",emoji:"🎬"},
  {q:"How many percent der Menschen bezeichnen sich als asexuell?",a:1,unit:"%",hint:"Asexualität ist eine valide sexuelle Orientierung.",emoji:"🏳️"},
  {q:"In what year erschien das erste weiblich geschriebene Erotik-Buch (Lady Chatterley)?",a:1928,unit:"Jahr",hint:"D.H. Lawrence schrieb es – war jahrzehntelang verboten.",emoji:"📚"},
  {q:"How many percent der Menschen finden das Gespräch über Sex nach dem Sex angenehm?",a:70,unit:"%",hint:"Afterglow-Kommunikation stärkt Beziehungen.",emoji:"💕"},
  {q:"How many cm ist die Basis eines durchschnittlichen Vibrators?",a:4,unit:"cm",hint:"Breiter unten für sicheres Halten.",emoji:"📏"},
  {q:"How many million Menschen in Deutschland haben sexuelle Dysfunktionen?",a:10,unit:"million",hint:"Breites Spektrum – viele suchen keine Hilfe.",emoji:"🔬"},
  {q:"How many percent der Deutschen haben schon Erotik-Massage erhalten?",a:45,unit:"%",hint:"Sehr verbreitet unter Paaren.",emoji:"💆"},
  {q:"How many cm ist der Abstand zwischen Anus und Vaginalöffnung (Perineum)?",a:3,unit:"cm",hint:"Das Perineum variiert individuell.",emoji:"📏"},
  {q:"How many million Dollar hat Hustler Magazine auf seinem Höhepunkt verdient?",a:50,unit:"Mio. Dollar/Jahr",hint:"Larry Flynts Sexmagazin in den 80ern.",emoji:"💰"},
  {q:"How many percent der Menschen haben schon ein Sexspielzeug gekauft?",a:40,unit:"%",hint:"Durch Online-Shopping viel zugänglicher geworden.",emoji:"📊"},
  {q:"How many percent der Menschen haben schon Sex auf einem Flughafen oder Flugzeug gehabt?",a:10,unit:"%",hint:"Mile High Club – überraschend verbreitet.",emoji:"✈️"},
  {q:"How many Stunden im Monat schauen Singles mehr Pornos als Paare?",a:4,unit:"hours",hint:"Singles konsumieren deutlich mehr.",emoji:"📊"},
  {q:"How many percent der Deutschen haben schon Sexfotos von sich gemacht?",a:55,unit:"%",hint:"Selfies und Sexting-Fotos sehr verbreitet.",emoji:"📸"},
  {q:"How many cm ist die durchschnittliche Brust in Österreich (Körbchengröße)?",a:80,unit:"cm Unterbrustweite",hint:"Ähnlich wie in Deutschland.",emoji:"👙"},
  {q:"How many percent der Männer haben Sex mit einer unbekannten Person gehabt?",a:50,unit:"%",hint:"One-Night-Stands mit Fremden.",emoji:"🌙"},
  {q:"How many million Nutzer hat Grindr worldwide?",a:13,unit:"million",hint:"Die bekannteste Gay-Dating-App.",emoji:"📱"},
  {q:"How many percent der Menschen haben Probleme beim Ansprechen von Sexwünschen?",a:60,unit:"%",hint:"Kommunikation über Sex ist schwierig für viele.",emoji:"💬"},
  {q:"How many cm lang ist der durchschnittliche Klitoris-Stiel?",a:3,unit:"cm",hint:"Der innere Teil des Klitoriskörpers.",emoji:"📏"},
  {q:"How many million Menschen nutzen Swingerclub-Apps worldwide?",a:2,unit:"million",hint:"Spezialisierte Apps für Lifestyler.",emoji:"📱"},
  {q:"How many percent der Frauen sagen, Vorspiel ist wichtiger als Penetration?",a:70,unit:"%",hint:"Laut Befragungen von Frauen worldwide.",emoji:"📊"},
  {q:"How many Gramm wiegt ein Durchschnitts-Ovarium (Eierstock)?",a:14,unit:"grams",hint:"Beide zusammen etwa 28 Gramm.",emoji:"⚖️"},
  {q:"How many percent der Deutschen finden Sex im Alter von 60+ wichtig?",a:60,unit:"%",hint:"Sexualität bleibt lebenslang wichtig.",emoji:"👴"},
  {q:"How many ml Vaginalflüssigkeit produziert a woman beim Squirting?",a:200,unit:"ml",hint:"Variiert stark – von wenig bis sehr viel.",emoji:"💧"},
  {q:"How many Stunden im Monat verbringen Singles mit Dating-Apps?",a:10,unit:"hours",hint:"Viel Zeit fürs digitale Dating.",emoji:"📱"},
  {q:"How many percent der Deutschen haben schon Toys beim Partnersex benutzt?",a:40,unit:"%",hint:"Immer mehr Paare integrieren Toys.",emoji:"📊"},
  {q:"How many cm ist das durchschnittliche Hymen von der Vaginalöffnung entfernt?",a:2,unit:"cm",hint:"Das Hymen ist ein dünnes Schleimhautgewebe.",emoji:"📏"},
  {q:"How many million Menschen haben eine Sexallergie (Seminalplasma)?",a:40,unit:"thousand",hint:"000 Menschen – Allergie gegen Sperma-Proteine.",emoji:"🔬"},
  {q:"How many percent der Menschen mit Sexsucht sind Frauen?",a:20,unit:"%",hint:"Frauen werden seltener diagnostiziert.",emoji:"📊"},
  {q:"How many Grad Celsius wärmer ist der Vaginalkanal während des Orgasmus?",a:0.5,unit:"°C",hint:"Messbar durch präzise Thermometer.",emoji:"🌡️"},
  {q:"How many million Menschen haben vaginismus (Scheidenverkrampfen)?",a:15,unit:"million",hint:"Eine häufige aber wenig diskutierte Erkrankung.",emoji:"🔬"},
  {q:"How many percent der Deutschen kennen den Begriff 'Cuckolding'?",a:35,unit:"%",hint:"Ein verbreiteter Begriff für eine Sex-Fantasie.",emoji:"📊"},
  {q:"How many Gramm wiegt das Clitoris-Schwellkörpernetz?",a:20,unit:"grams",hint:"Das gesamte Klitorissystem.",emoji:"⚖️"},
  {q:"How many Stunden braucht der Mann on average nach dem Orgasmus bis zur nächsten Erektion?",a:30,unit:"minutes",hint:"Minuten Refraktärzeit bei jungen Männern.",emoji:"⏰"},
  {q:"How many percent der Menschen würden ihren Partner betrügen wenn sie nicht erwischt würden?",a:30,unit:"%",hint:"Anonyme Befragungen zeigen hohe Zahlen.",emoji:"💔"},
  {q:"How many million Menschen praktzieren Bondage worldwide?",a:100,unit:"million",hint:"BDSM in verschiedenen Formen.",emoji:"🔗"},
  {q:"How many cm ist die Länge eines erigierten Klitoriskörpers?",a:10,unit:"cm",hint:"Viel größer als sichtbar.",emoji:"📏"},
  {q:"How many percent der Deutschen bezeichnen sich als 'kinky'?",a:20,unit:"%",hint:"Jeder Fünfte hat spezielle Vorlieben.",emoji:"📊"},
  {q:"How many mg Oxytocin werden beim Orgasmus ausgeschüttet?",a:0.001,unit:"mg",hint:"Winzige Menge – aber starke Bindungswirkung.",emoji:"⚗️"},
  {q:"How many Stunden Schlaf verbessern die Sexualfunktion?",a:8,unit:"hours",hint:"Ausreichend Schlaf ist entscheidend.",emoji:"😴"},
  {q:"How many percent der Männer haben schon Erektionsprobleme wegen Pornos?",a:30,unit:"%",hint:"PIED – Porn-Induced Erectile Dysfunction.",emoji:"📊"},
  {q:"How many million Menschen nutzen Fetlife worldwide?",a:10,unit:"million",hint:"Das größte BDSM-soziale Netzwerk.",emoji:"🔗"},
  {q:"How many Gramm Elastin hat das Vaginalgewebe?",a:1,unit:"grams",hint:"Elastin ermöglicht die Dehnung bei der Geburt.",emoji:"⚗️"},
  {q:"How many percent der Menschen haben schon während des Monats Lust auf Sex gehabt?",a:99,unit:"%",hint:"Fast universell – unabhängig vom Zyklus.",emoji:"📊"},
  {q:"How many ml Schmierung produziert die Bartholin-Drüse beim Sex?",a:2,unit:"ml",hint:"Natürliche Gleitfähigkeit.",emoji:"💧"},
  {q:"How many percent der Deutschen haben schon Erotic Literature gelesen?",a:55,unit:"%",hint:"Erotische Literatur ist sehr populär.",emoji:"📚"},
  {q:"How many million Spermatozoen überleben nach der Ejakulation maximal?",a:1,unit:"million",hint:"Von 250 million überleben nur die Stärksten.",emoji:"🔬"},
  {q:"How many Stunden im Jahr verbringt a human mit romantischen Aktivitäten?",a:730,unit:"hours",hint:"2 Stunden daily an Romantik und Intimität.",emoji:"❤️"},
  {q:"How many percent der Swinger in Deutschland sind Akademiker?",a:40,unit:"%",hint:"Überdurchschnittlich gebildet laut Studien.",emoji:"📊"},
  {q:"How many cm ist die Vorhaut im erigierten Zustand lang?",a:12,unit:"cm",hint:"Die Vorhaut kann bis zur Hälfte des Penis bedecken.",emoji:"📏"},
  {q:"How many million Menschen haben Erektionsprobleme worldwide?",a:320,unit:"million",hint:"Fast ein Drittel aller Männer irgendwann.",emoji:"🔬"},
  {q:"How many percent der Lesben berichten höhere Orgasmusraten als hetero Frauen?",a:86,unit:"%",hint:"Orgasm Gap: Lesben kommen deutlich häufiger.",emoji:"📊"},
  {q:"How many Millimeter ist ein durchschnittliches Spermium lang?",a:0.05,unit:"mm",hint:"50 Mikrometer – mit Schwanzanteil.",emoji:"🔬"},
  {q:"How many percent der Menschen haben Fantasien über Macht und Kontrolle?",a:65,unit:"%",hint:"Dominanz und Submission sind sehr verbreitete Fantasien.",emoji:"📊"},
  {q:"How many Stunden schlafen Menschen nach gutem Sex besser?",a:1,unit:"Stunde mehr",hint:"Orgasmus fördert Schlaf durch Oxytocin.",emoji:"😴"},
  {q:"How many ml Vaginalflüssigkeit produziert a woman daily?",a:2,unit:"ml",hint:"Normal ist 1-4 ml daily.",emoji:"💧"},
  {q:"How many percent der Deutschen wünschen sich mehr Sex als sie haben?",a:55,unit:"%",hint:"Desire Discrepancy ist das häufigste Problem.",emoji:"📊"},
  {q:"How many cm ist der maximale Umfang eines erigierten Penis im Rekord?",a:25,unit:"cm",hint:"Extremfälle sind dokumentiert.",emoji:"📏"},
  {q:"How many million Menschen leiden worldwide an sexuellen Angststörungen?",a:30,unit:"million",hint:"Sexangst – nicht selten.",emoji:"🔬"},
  {q:"How many Stunden im Leben verbringt a human mit Masturbation (Frauen)?",a:2000,unit:"hours",hint:"Weniger als Männer – aber erheblich.",emoji:"📊"},
  {q:"How many percent der Menschen haben im öffentlichen Bereich Sex gehabt?",a:35,unit:"%",hint:"Parks, Strände und andere öffentliche Orte.",emoji:"🌿"},
  {q:"How many percent der Deutschen kennen den Begriff 'Compersion'?",a:15,unit:"%",hint:"Freude an der Lust des Partners mit anderen.",emoji:"💕"},
  {q:"How many mg Östradiol enthält eine normale Verhütungspille daily?",a:0.03,unit:"mg",hint:"30 Mikrogramm – sehr niedrige Dosis.",emoji:"💊"},
  {q:"How many percent der Deutschen haben schon bezahlten Sex gehabt?",a:14,unit:"%",hint:"Laut anonymen Befragungen – hauptsächlich Männer.",emoji:"📊"},
  {q:"How many million Menschen sind Teil der Polyamorie-Bewegung?",a:21,unit:"million",hint:"Schätzung in den USA allein.",emoji:"💕"},
];
