// 💰 MONEY & PRICES – English
export default [
  {q:"How much kostete das teuerste je verkaufte Gemälde (Salvator Mundi) in million Dollar?",a:450,unit:"million $",hint:"2017 bei Christie's versteigert.",emoji:"🖼️"},
  {q:"How many billion Dollar ist Jeff Bezos reich?",a:170,unit:"billion $",hint:"Schwankt – Stand 2024 ca. 170 Mrd.",emoji:"💰"},
  {q:"How much kostet eine Flasche Krug Grande Cuvée Champagner?",a:200,unit:"Euro",hint:"Hochwertigster Champagner im Standard-Sortiment.",emoji:"🥂"},
  {q:"How much kostete das teuerste Haus der Welt (Villa Les Cèdres) in million Euro?",a:350,unit:"million €",hint:"Villa in Cap-Ferrat, Südfrankreich.",emoji:"🏰"},
  {q:"How many billion Dollar kostet ein modernes Flugzeugträger?",a:13,unit:"billion $",hint:"Der Ford-Class Träger der US Navy.",emoji:"🚢"},
  {q:"How much kostet 1 Gramm Antimaterie in Dollar?",a:62500000000000,unit:"Dollar",hint:"62,5 Billionen Dollar pro Gramm.",emoji:"⚛️"},
  {q:"How much kostete das teuerste Parfüm (Clive Christian No. 1) pro Flasche?",a:2150,unit:"Dollar",hint:"In einem goldenen Flacon.",emoji:"🌸"},
  {q:"How many billion Dollar Umsatz macht Apple pro Quartal?",a:90,unit:"billion $",hint:"Apple ist das wertvollste Unternehmen der Welt.",emoji:"🍎"},
  {q:"How much kostet ein Mondstein-Gramm der NASA in Dollar?",a:50800,unit:"Dollar/Gramm",hint:"Der teuerste Stoff auf der Erde nach Antimaterie.",emoji:"🌙"},
  {q:"How many billion Dollar kostet die Internationale Raumstation?",a:150,unit:"billion $",hint:"Das teuerste von Menschen gebaute Objekt.",emoji:"🚀"},
  {q:"How much kostet ein Schweizer Luxusquartier (Gnägi Villa) pro Nacht?",a:50000,unit:"Dollar/Nacht",hint:"Exklusivste Hotels kosten ein Vermögen.",emoji:"🏨"},
  {q:"How many billion Dollar gab die US-Regierung 2023 für Militär aus?",a:858,unit:"billion $",hint:"Mehr als die nächsten 10 Länder zusammen.",emoji:"⚔️"},
  {q:"How much kostete die teuerste Uhr (Patek Philippe Grandmaster Chime)?",a:31000000,unit:"Dollar",hint:"2019 für 31 Mio. Dollar versteigert.",emoji:"⌚"},
  {q:"How much kostet 1 Kilogramm weißer Trüffel?",a:10000,unit:"Euro/kg",hint:"Kann bis zu 300.000€ pro kg kosten.",emoji:"🍄"},
  {q:"How many billion Dollar kostet ein Space Shuttle Flug?",a:1.5,unit:"billion $",hint:"Jeder Shuttle-Flug kostete ~1,5 Mrd. Dollar.",emoji:"🚀"},
  {q:"How much kostete das teuerste Buch (Codex Leicester von Leonardo da Vinci)?",a:30800000,unit:"Dollar",hint:"Gekauft von Bill Gates 1994.",emoji:"📖"},
  {q:"How many Billionen Dollar schuldet die USA?",a:34,unit:"Billionen Dollar",hint:"Stand 2024 – wächst daily.",emoji:"💸"},
  {q:"How much kostete das teuerste Foto (Rhein II von Andreas Gursky)?",a:4338500,unit:"Dollar",hint:"2011 versteigert.",emoji:"📷"},
  {q:"How many billion Dollar Jahresumsatz macht McDonald's?",a:23,unit:"billion $",hint:"Hamburger sind ein Milliardengeschäft.",emoji:"🍔"},
  {q:"How much kostet ein Kilogramm Saffron (Safran) auf dem Markt?",a:10000,unit:"Euro/kg",hint:"Das teuerste Gewürz der Welt.",emoji:"🌺"},
  {q:"How many million Dollar kostet ein Top-Formel-1-Fahrer per year?",a:50,unit:"million $",hint:"Hamilton verdient ~50 Mio. – plus Sponsoren.",emoji:"🏎️"},
  {q:"How much kostete die teuerste Handtasche (Hermès Birkin) je?",a:300000,unit:"Dollar",hint:"Aus Krokodilleder mit Diamanten.",emoji:"👜"},
  {q:"How many billion Dollar ist der globale Markt für Pornografie wert?",a:97,unit:"billion $",hint:"Einer der größten Märkte im Internet.",emoji:"🔞"},
  {q:"How much kostet eine Übernachtung im teuersten Hotel (Empathy Suite, Las Vegas)?",a:100000,unit:"Dollar/Nacht",hint:"Im Palms Casino Resort.",emoji:"🏨"},
  {q:"How many billion Dollar wert ist Elon Musks SpaceX?",a:180,unit:"billion $",hint:"Stand 2024 – private Raumfahrt boomt.",emoji:"🚀"},
  {q:"How much kostet 1 mg Californium-252 in Dollar?",a:27000000,unit:"Dollar/mg",hint:"27 Mio. Dollar pro Milligramm.",emoji:"☢️"},
  {q:"How many billion Dollar Jahresgewinn macht Saudi Aramco?",a:161,unit:"billion $",hint:"Das profitabelste Unternehmen der Welt 2022.",emoji:"🛢️"},
  {q:"How much kostete das teuerste Auto je verkauft (Mercedes-Benz 300 SLR)?",a:142000000,unit:"Euro",hint:"2022 für 142 million Euro versteigert.",emoji:"🚗"},
  {q:"How many billion Dollar ist der Bitcoin-Markt wert?",a:1000,unit:"billion $",hint:"Schwankt stark – zeitweise über 1 Billion.",emoji:"₿"},
  {q:"How much kostet ein Kobe-Rind pro kg?",a:500,unit:"Euro/kg",hint:"Das teuerste Fleisch der Welt.",emoji:"🥩"},
  {q:"How many billion Dollar Jahresbudget hat die NASA?",a:25,unit:"billion $",hint:"Nur 0,3% des US-Budgets.",emoji:"🚀"},
  {q:"How much kostet ein Glas Whisky aus der Macallan Fine & Rare Collection?",a:10000,unit:"Dollar",hint:"Pro Glas in Luxus-Bars.",emoji:"🥃"},
  {q:"How many Billionen Dollar ist der globale Immobilienmarkt wert?",a:326,unit:"Billionen Dollar",hint:"Der größte Anlagemarkt der Welt.",emoji:"🏠"},
  {q:"How much kostet der teuerste Champagner (Goût de Diamants)?",a:1200000,unit:"Euro",hint:"Mit Diamanten verziert.",emoji:"🥂"},
  {q:"How many billion Dollar verdient Taylor Swift pro Tour?",a:1,unit:"billion $",hint:"Die Eras Tour 2023-2024 – erste billion-Tour.",emoji:"🎤"},
  {q:"How much kostet 1 Gramm Meissen-Porzellan (als Kunstwerk)?",a:1000,unit:"Euro",hint:"Echtes Meissen ist extrem wertvoll.",emoji:"🏺"},
  {q:"How much kostete das teuerste Diamant-Ehering (Pink Star)?",a:71200000,unit:"Dollar",hint:"2017 für 71,2 Mio. Dollar versteigert.",emoji:"💍"},
  {q:"How many billion Dollar Steuern hinterziehen Deutsche per year?",a:30,unit:"billion €",hint:"Schätzungen liegen bei 30 billion Euro.",emoji:"💸"},
  {q:"How much kostet ein Flug ins All mit Virgin Galactic?",a:450000,unit:"Dollar",hint:"Für einen Suborbitalflug.",emoji:"🚀"},
  {q:"How many billion Dollar ist der globale Kaffeehandel wert?",a:100,unit:"billion $",hint:"Kaffee ist eines der größten Handelsgüter.",emoji:"☕"},
  {q:"How much kostet 1 Bitcoin auf seinem Allzeithoch in Dollar?",a:73000,unit:"Dollar",hint:"Im März 2024 erreichte Bitcoin ~73.000 Dollar.",emoji:"₿"},
  {q:"How many billion Dollar hat Warren Buffett gespendet?",a:50,unit:"billion $",hint:"Der meistgebende Milliardär der Geschichte.",emoji:"💝"},
  {q:"How much kostet ein Kilogramm Kaviar (Almas)?",a:34500,unit:"Euro/kg",hint:"Weißer Kaviar von Albino-Stören.",emoji:"🐟"},
  {q:"How many billion Dollar Jahresumsatz macht LVMH (Luxuskonzern)?",a:86,unit:"billion €",hint:"Louis Vuitton, Moët, Hennessy und viele mehr.",emoji:"👜"},
  {q:"How much kostet ein Top-Anwalt in New York per hour?",a:2000,unit:"Dollar/Stunde",hint:"Hochkarätige Anwälte verlangen enorme Honorare.",emoji:"⚖️"},
  {q:"How many billion Dollar ist der globale Glücksspielmarkt wert?",a:500,unit:"billion $",hint:"Casinos, Sportwetten und Online-Gambling.",emoji:"🎰"},
  {q:"How much kostet ein Luxus-Penthouse in Monaco pro m²?",a:100000,unit:"Euro/m²",hint:"Teuerster Immobilienmarkt der Welt.",emoji:"🏠"},
  {q:"How many billion Dollar geben Amerikaner per year für Haustiere aus?",a:150,unit:"billion $",hint:"billion für Hunde, Katzen und Co.",emoji:"🐕"},
  {q:"How much kostet ein Jahr Harvard-Studium (alles inbegriffen)?",a:80000,unit:"Dollar/Jahr",hint:"Wohnen, Essen, Studiengebühren.",emoji:"🎓"},
  {q:"How many billion Dollar kostet ein Kernkraftwerk?",a:12,unit:"billion $",hint:"Die neuesten Reaktoren kosten bis zu 30 Mrd.",emoji:"⚡"},
  {q:"How much kostet ein Kilo Gold aktuell in Euro?",a:60000,unit:"Euro/kg",hint:"Gold kostet ca. 60.000€/kg – Stand 2024.",emoji:"🪙"},
  {q:"How many billion Dollar Jahresumsatz hat Google?",a:280,unit:"billion $",hint:"Haupteinnahme: Werbung.",emoji:"🔍"},
  {q:"How much kostet der teuerste Cognac (Hennessy Richard)?",a:12000,unit:"Dollar",hint:"Pro Flasche – handgefertigt.",emoji:"🥃"},
  {q:"How many billion Dollar kostet es ein Olympisches Spiel auszurichten?",a:15,unit:"billion $",hint:"London 2012 kostete 15 Mrd. Pfund.",emoji:"🏅"},
  {q:"How much kostet ein Kilogramm Diamanten (Rohdiamant)?",a:55000,unit:"Dollar/Karat",hint:"Qualitätsdiamanten können viel mehr kosten.",emoji:"💎"},
  {q:"How many billion Dollar wert ist der Tabakmarkt global?",a:900,unit:"billion $",hint:"Trotz Rückgang – immer noch riesig.",emoji:"🚬"},
  {q:"How much kostet ein privater Hubschrauber (Airbus H145)?",a:7000000,unit:"Dollar",hint:"Ein Standard-Luxushubschrauber.",emoji:"🚁"},
  {q:"How many billion Dollar verdient FIFA pro WM?",a:5,unit:"billion $",hint:"Die WM 2022 in Katar generierte ~7,5 Mrd.",emoji:"⚽"},
  {q:"How much kostet das teuerste Hotelzimmer pro Nacht in Dubai?",a:85000,unit:"Dollar",hint:"Royal Penthouse im Burj Al Arab.",emoji:"🏨"},
  {q:"How many billion Dollar wert ist der globale Pharmasektor?",a:1600,unit:"billion $",hint:"Ein billionenschwerer Markt.",emoji:"💊"},
  {q:"How much kostet 1 kg Heroin auf dem Schwarzmarkt?",a:50000,unit:"Dollar/kg",hint:"Straßenpreise variieren stark.",emoji:"💊"},
  {q:"How many billion Dollar geben Amis per year für Fast Food aus?",a:280,unit:"billion $",hint:"Fast Food ist Amerikas Lieblingsessen.",emoji:"🍔"},
  {q:"How much kostet eine private Insel in der Karibik (Einstieg)?",a:5000000,unit:"Dollar",hint:"Kleine Inseln ab 5 Mio. Dollar.",emoji:"🏝️"},
  {q:"How many billion Dollar wert ist der globale Waffenmarkt?",a:600,unit:"billion $",hint:"Legaler Waffenhandel worldwide.",emoji:"⚔️"},
  {q:"How much kostet ein Luxusjet (Bombardier Global 7500)?",a:75000000,unit:"Dollar",hint:"Der größte Privatjet der Welt.",emoji:"✈️"},
  {q:"How many billion Euro hat Deutschland 2023 in Rüstung investiert?",a:52,unit:"billion €",hint:"Auf dem Weg zum 2%-Ziel der NATO.",emoji:"⚔️"},
  {q:"How much kostet 1 Sekunde Werbung beim Super Bowl?",a:200000,unit:"Dollar",hint:"30 Sekunden = 6 Mio. Dollar.",emoji:"📺"},
  {q:"How many billion Dollar ist TikTok (ByteDance) wert?",a:250,unit:"billion $",hint:"Stand 2024.",emoji:"📱"},
  {q:"How much kostet ein Kilogramm Seltener Erde (Scandium)?",a:15000,unit:"Dollar/kg",hint:"Seltene Erden sind der Stoff der modernen Welt.",emoji:"⚗️"},
  {q:"How many billion Dollar Jahresgewinne macht Apple?",a:100,unit:"billion $",hint:"Apple ist unfassbar profitabel.",emoji:"🍎"},
  {q:"How much kostet eine Hermes Birkin Tasche (Sonderanfertigung)?",a:500000,unit:"Dollar",hint:"Mit exotischen Materialien.",emoji:"👜"},
  {q:"How many billion Dollar hat Elon Musk für Twitter/X bezahlt?",a:44,unit:"billion $",hint:"Im Oktober 2022.",emoji:"𝕏"},
  {q:"How much kostet ein Kilogramm Plutonium?",a:6600000,unit:"Dollar",hint:"Das teuerste legale Material auf Erden.",emoji:"☢️"},
  {q:"How many billion Dollar wert ist Cristiano Ronaldos Marke?",a:1,unit:"billion $",hint:"CR7 ist Milliardär durch Marke und Investments.",emoji:"⚽"},
  {q:"How much kostet ein Kunstwerk von Banksy im Durchschnitt?",a:5000000,unit:"Dollar",hint:"Game Changer wurde für 16,8 Mio. verkauft.",emoji:"🎨"},
  {q:"How many billion Dollar kostet der Mars-Kolonisierungsplan von SpaceX?",a:100,unit:"billion $",hint:"Musk schätzte ursprünglich 100 Mrd.",emoji:"🔴"},
  {q:"How much kostet ein Megajacht (100m+) per year an Unterhalt?",a:10000000,unit:"Dollar/Jahr",hint:"10% des Kaufpreises annually für Unterhalt.",emoji:"⛵"},
  {q:"How many billion Dollar Jahresumsatz hat die Pornoindustrie?",a:97,unit:"billion $",hint:"Ein gigantischer globaler Markt.",emoji:"🔞"},
  {q:"How much kostet eine Tasse Kopi Luwak (teuerster Kaffee)?",a:100,unit:"Dollar/Tasse",hint:"Kaffee aus dem Kot der Zibetkatze.",emoji:"☕"},
  {q:"How many billion Dollar wert ist der globale E-Sport-Markt?",a:2,unit:"billion $",hint:"Professionelles Spielen wächst rasant.",emoji:"🎮"},
  {q:"How much kostet ein Kilogramm Quecksilber auf dem freien Markt?",a:50,unit:"Dollar",hint:"Relativ günstig – trotz Giftigkeit.",emoji:"🌡️"},
  {q:"How many billion Euro hat Deutschland in die Flüchtlingskrise investiert?",a:20,unit:"Mrd. Euro/Jahr",hint:"2015-2022 insgesamt über 100 Mrd.",emoji:"🏠"},
  {q:"How much kostet ein Top-Fußballspieler-Transfer (Neymar)?",a:222000000,unit:"Euro",hint:"Teuerster Transfer aller Zeiten 2017.",emoji:"⚽"},
  {q:"How many billion Dollar wert ist der globale Kosmetikmarkt?",a:500,unit:"billion $",hint:"Schönheit ist ein riesiges Geschäft.",emoji:"💄"},
  {q:"How much kostet 1 Watt Solarenergie zur Installation?",a:0.3,unit:"Dollar/Watt",hint:"Drastisch gesunken – von 80$/W in 1970.",emoji:"☀️"},
  {q:"How many billion Dollar kostet ein Atomkraftwerk (Hinkley Point C)?",a:33,unit:"Mrd. Pfund",hint:"Das teuerste Bauwerk in UK.",emoji:"⚡"},
  {q:"How much kostet eine Luxusuhr von Richard Mille?",a:1000000,unit:"Dollar",hint:"Die teuersten Uhren der Welt.",emoji:"⌚"},
  {q:"How many billion Dollar Jahresumsatz hat Nestlé?",a:95,unit:"billion $",hint:"Größter Lebensmittelkonzern der Welt.",emoji:"🍫"},
  {q:"How much kostet ein Kilogramm Kokain in Europa?",a:35000,unit:"Euro/kg",hint:"Straßenpreise – stark variierend.",emoji:"💊"},
  {q:"How many billion Dollar wert ist der globale Alkohol-Markt?",a:1600,unit:"billion $",hint:"Bier, Wein und Spirituosen zusammen.",emoji:"🍷"},
  {q:"How much kostet ein privater Raketenstarter bei SpaceX (Falcon 9)?",a:67000000,unit:"Dollar",hint:"67 Mio. pro Falcon-9-Start.",emoji:"🚀"},
  {q:"How many billion Dollar verdiente Fortnite in seinem ersten Jahr?",a:2.4,unit:"billion $",hint:"Epic Games Blockbuster-Spiel.",emoji:"🎮"},
  {q:"How much kostet der teuerste Sneaker je versteigert?",a:1800000,unit:"Dollar",hint:"Nike Moon Shoe von 1972.",emoji:"👟"},
  {q:"How many billion Dollar wert ist die gesamte Krypto-Marktkapitalisierung?",a:2000,unit:"billion $",hint:"Stand Anfang 2024.",emoji:"₿"},
  {q:"How much kostet ein Liter Blut im Krankenhaus in den USA?",a:1000,unit:"Dollar",hint:"Gespendetes Blut wird teuer verkauft.",emoji:"🩸"},
  {q:"How many billion Dollar Jahresumsatz hat Amazon?",a:514,unit:"billion $",hint:"Größter Onlinehändler der Welt.",emoji:"📦"},
  {q:"How much kostet ein Quadratmeter in Hongkong (teuerste Gegend)?",a:100000,unit:"Dollar/m²",hint:"Hongkong ist eine der teuersten Städte.",emoji:"🏙️"},
  {q:"How many billion Dollar kostet ein neues Flugzeug (Airbus A380)?",a:445,unit:"million $",hint:"Das größte Passagierflugzeug.",emoji:"✈️"},
  {q:"How much kostet eine Flasche Petrus (Bordeaux, 1947)?",a:75000,unit:"Euro",hint:"Einige Flaschen wurden für über 100.000€ verkauft.",emoji:"🍷"},
  {q:"How many billion Dollar wert ist der globale Markt für Schusswaffen?",a:28,unit:"billion $",hint:"Legaler Waffenmarkt.",emoji:"🔫"},
  {q:"How much kostet 1 km Autobahn zu bauen in Deutschland?",a:25000000,unit:"Euro/km",hint:"25 Mio. Euro pro Kilometer.",emoji:"🛣️"},
  {q:"How many billion Euro kostet der Wiederaufbau der Notre-Dame?",a:700,unit:"million €",hint:"Über 700 Mio. Euro für die Renovierung.",emoji:"⛪"},
  {q:"How much kostet ein Quadratmeter in Paris (Innenstadt)?",a:12000,unit:"Euro/m²",hint:"Paris ist eine der teuersten Städte Europas.",emoji:"🗼"},
  {q:"How many billion Dollar ist Tesla wert?",a:600,unit:"billion $",hint:"Schwankt stark – war mal über 1 Billion.",emoji:"🚗"},
  {q:"How much kostet ein Jahr in der teuersten Privatschule der Welt?",a:120000,unit:"Schweizer Franken",hint:"Institut Le Rosey in der Schweiz.",emoji:"🎓"},
  {q:"How many billion Dollar wert ist der globale Musikmarkt?",a:26,unit:"billion $",hint:"Streaming dominiert.",emoji:"🎵"},
  {q:"How much kostet ein Kilogramm Vanille?",a:600,unit:"Dollar/kg",hint:"Einer der teuersten Gewürze nach Safran.",emoji:"🌿"},
  {q:"How many billion Dollar wert ist Goldman Sachs?",a:120,unit:"billion $",hint:"Eine der mächtigsten Investmentbanken.",emoji:"🏦"},
  {q:"How much kostet ein Penthouse in New York City (on average)?",a:20000000,unit:"Dollar",hint:"Luxuspenthouses in Manhattan.",emoji:"🏙️"},
  {q:"How many billion Dollar gibt die Welt per year für Rüstung aus?",a:2200,unit:"billion $",hint:"2,2 Billionen Dollar annually.",emoji:"⚔️"},
  {q:"How much kostet 1 km neues U-Bahn-Netz in London?",a:1000000000,unit:"Dollar/km",hint:"London hat die teuersten U-Bahnbauprojekte.",emoji:"🚇"},
  {q:"How many billion Dollar ist der globale Markt für Videospiele wert?",a:200,unit:"billion $",hint:"Größer als Film und Musik zusammen.",emoji:"🎮"},
  {q:"How much kostet ein Jahresgehalt eines Hedge-Fonds-Managers?",a:1000000000,unit:"Dollar",hint:"Spitzenmanager verdienen billion.",emoji:"💰"},
  {q:"How many billion Dollar ist der globale Tourismus-Markt wert?",a:9500,unit:"billion $",hint:"9,5 Billionen Dollar – einer der größten Sektoren.",emoji:"✈️"},
  {q:"How much kostet das Anlegen eines Sterns nach dir?",a:50,unit:"Dollar",hint:"Internationales Sternregister – eigentlich rechtlich nicht bindend.",emoji:"⭐"},
  {q:"How many billion Dollar kostet ein Wolkenkratzer (Burj Khalifa)?",a:1.5,unit:"billion $",hint:"Der höchste Turm der Welt.",emoji:"🏙️"},
  {q:"How much kostet 1 Kilo Seltener Erden-Neodym?",a:175,unit:"Dollar/kg",hint:"Essenziell für Elektromotoren.",emoji:"⚗️"},
  {q:"How many billion Dollar wert ist der FC Barcelona?",a:5,unit:"billion $",hint:"Einer der wertvollsten Sportklubs.",emoji:"⚽"},
  {q:"How much kostet ein privater DNA-Test bei 23andMe?",a:200,unit:"Dollar",hint:"Plus optionale Abonnements.",emoji:"🧬"},
  {q:"How many billion Dollar Jahresumsatz hat die Filmindustrie (Hollywood)?",a:50,unit:"billion $",hint:"Box Office plus Streaming.",emoji:"🎬"},
  {q:"How much kostet ein Meter Eintrittskarte für ein Taylor-Swift-Konzert (VIP)?",a:3000,unit:"Dollar",hint:"VIP-Pakete für die Eras Tour.",emoji:"🎤"},
  {q:"How many billion Dollar wert ist die Marke Nike?",a:50,unit:"billion $",hint:"Just Do It – einer der stärksten Markennamen.",emoji:"👟"},
  {q:"How much kostet ein Kilogramm weißer Trüffel auf Auktionen?",a:300000,unit:"Euro/kg",hint:"Rekord-Trüffel werden für Hunderttausende verkauft.",emoji:"🍄"},
  {q:"How many billion Dollar wert ist der globale Schönheitsmarkt?",a:800,unit:"billion $",hint:"Wächst stark durch Influencer-Kultur.",emoji:"💄"},
  {q:"How much kostet ein Concorde-Ticket (als sie noch flog)?",a:8000,unit:"Dollar",hint:"Ein Transatlantikflug für 8000 Dollar.",emoji:"✈️"},
  {q:"How many billion Dollar hat Elon Musk in einem Jahr verloren (2022)?",a:200,unit:"billion $",hint:"Größter Vermögensverlust in der Geschichte.",emoji:"📉"},
  {q:"How much kostet ein Quadratmeter auf der teuersten Straße der Welt (Hong Kong)?",a:236000,unit:"Dollar/m²",hint:"Causeway Bay, Hong Kong.",emoji:"🏙️"},
  {q:"How many billion Dollar wert ist der globale Sportmarkt?",a:500,unit:"billion $",hint:"Alle Sportveranstaltungen, Rechte und Merchandise.",emoji:"⚽"},
  {q:"How much kostet 1 Minute Werbung auf dem Super Bowl?",a:10000000,unit:"Dollar",hint:"Über 10 Mio. Dollar für 30 Sekunden.",emoji:"📺"},
  {q:"How many billion Dollar kostet das amerikanische Bildungssystem per year?",a:700,unit:"billion $",hint:"Von Kindergarten bis Uni.",emoji:"🎓"},
  {q:"How much kostet ein Liter Parfüm Chanel No. 5?",a:3000,unit:"Euro",hint:"Eines der ikonischsten Parfüms.",emoji:"🌸"},
  {q:"How many billion Dollar hat Saudi-Arabien in Soccer-Stars investiert?",a:6,unit:"billion $",hint:"Die Saudi Pro League wirbt Weltstars ab.",emoji:"⚽"},
  {q:"How much kostet ein Kilogramm Madame Jeanette-Chili in Europa?",a:50,unit:"Euro/kg",hint:"Seltene scharfe Chili aus Surinam.",emoji:"🌶️"},
  {q:"How many billion Dollar wert ist der globale Markt für Streaming?",a:100,unit:"billion $",hint:"Netflix, Spotify, Amazon und alle anderen.",emoji:"📺"},
  {q:"How much kostet eine Mitgliedschaft im Augusta National Golf Club?",a:300000,unit:"Dollar",hint:"Der exklusivste Golfklub der Welt.",emoji:"⛳"},
  {q:"How many billion Dollar verliert die Weltwirtschaft durch Korruption?",a:2600,unit:"billion $",hint:"2,6 Billionen Dollar per year laut UN.",emoji:"💸"},
  {q:"How much kostet ein kg Ambergris (Walrat) auf dem Schwarzmarkt?",a:50000,unit:"Dollar",hint:"Verwendet in Luxusparfüms.",emoji:"🐋"},
  {q:"How many billion Dollar ist der globale Fast-Fashion-Markt wert?",a:100,unit:"billion $",hint:"Zara, H&M und Shein dominieren.",emoji:"👗"},
  {q:"How much kostet ein Privatflug London-New York?",a:150000,unit:"Dollar",hint:"Im Luxus-Jet.",emoji:"✈️"},
  {q:"How many billion Dollar wert ist der globale Lebensmittelmarkt?",a:8000,unit:"billion $",hint:"8 Billionen Dollar – täglicher Bedarf.",emoji:"🍎"},
  {q:"How much kostet ein Meter Silizium-Chip-Produktion (TSMC 2nm)?",a:20000,unit:"Dollar/Wafer",hint:"Die teuersten Chips der Welt.",emoji:"💻"},
  {q:"How many billion Dollar wert ist der globale Online-Shopping-Markt?",a:5000,unit:"billion $",hint:"5 Billionen Dollar – wächst weiter.",emoji:"📦"},
  {q:"How much kostet 1 Liter menschliches Blutplasma?",a:500,unit:"Dollar",hint:"Blutplasma ist ein wertvolles Medizinprodukt.",emoji:"🩸"},
  {q:"How many billion Dollar wert ist Spotify?",a:40,unit:"billion $",hint:"Stand 2024.",emoji:"🎵"},
  {q:"How much kostet ein Kilogramm Carbon-Fiber?",a:100,unit:"Dollar/kg",hint:"Für Formel-1 und Luft-/Raumfahrt essenziell.",emoji:"🏎️"},
  {q:"How many billion Dollar hat Kylie Jenner verdient als jüngste Selfmade-Milliardärin?",a:1,unit:"billion $",hint:"Durch ihre Kosmetikmarke.",emoji:"💄"},
  {q:"How much kostet ein Quadratmeter in München (Maxvorstadt)?",a:15000,unit:"Euro/m²",hint:"Einer der teuersten Immobilienmärkte Deutschlands.",emoji:"🏠"},
  {q:"How many billion Dollar kostet es die Klimakrise zu lösen (annually)?",a:4000,unit:"billion $",hint:"Schätzungen des IPCC.",emoji:"🌍"},
  {q:"How much kostet der teuerste Tee (Da Hong Pao)?",a:1000000,unit:"Dollar/kg",hint:"1 Mio. Dollar pro kg – kaum noch erhältlich.",emoji:"🍵"},
  {q:"How many billion Dollar wert ist der globale Cannabismarkt?",a:50,unit:"billion $",hint:"Legal und illegal zusammen.",emoji:"🌿"},
  {q:"How much kostet ein Kilogramm roher Saphir?",a:30000,unit:"Dollar/Karat",hint:"Hochwertige Saphire kosten 30.000+/Karat.",emoji:"💎"},
  {q:"How many billion Dollar annually macht die CIA mit verdeckten Operationen?",a:90,unit:"billion $",hint:"Das geheime US-Geheimdienstbudget.",emoji:"🕵️"},
  {q:"How much kostet ein Kilo Seltenes Element Rhenium?",a:5000,unit:"Dollar/kg",hint:"Eines der seltensten stabilen Elemente.",emoji:"⚗️"},
  {q:"How many billion Dollar wert ist der globale Markt für KI?",a:200,unit:"billion $",hint:"Wächst exponentiell.",emoji:"🤖"},
  {q:"How much kostet ein Ferrari F40 heute?",a:1500000,unit:"Euro",hint:"Legendärer Supersportwagen von 1987.",emoji:"🚗"},
  {q:"How many billion Dollar wert ist der globale Cloud-Computing-Markt?",a:600,unit:"billion $",hint:"AWS, Azure und Google dominieren.",emoji:"☁️"},
  {q:"How much kostet 1 Meter Unterwasserkabel (Internet)?",a:35000,unit:"Dollar/km",hint:"Unterseekabel verbinden die Kontinente.",emoji:"🌊"},
  {q:"How many billion Dollar geben Reiche Menschen für Kunst aus?",a:68,unit:"billion $",hint:"Der globale Kunstmarkt 2022.",emoji:"🎨"},
  {q:"How much kostet der teuerste Wein je (Romanée-Conti 1945)?",a:558000,unit:"Dollar",hint:"Pro Flasche – 2018 versteigert.",emoji:"🍷"},
  {q:"How many billion Dollar wert ist der globale Markt für Cybersecurity?",a:200,unit:"billion $",hint:"Wächst mit jedem Angriff.",emoji:"🔒"},
  {q:"How much kostet ein Penthouse in Dubai (Palm Jumeirah)?",a:30000000,unit:"Dollar",hint:"Luxuriöse Residenzen auf der Palmeninsel.",emoji:"🌴"},
  {q:"How many billion Dollar wert ist die Sportartikelmesse (Adidas+Nike)?",a:100,unit:"billion $",hint:"Beide zusammen.",emoji:"👟"},
  {q:"How much kostet ein Stunde mit einem Top-Management-Consultant (McKinsey)?",a:1200,unit:"Dollar",hint:"Für Senior Partner.",emoji:"💼"},
  {q:"How many billion Dollar wert ist der globale Pharmamarkt?",a:1600,unit:"billion $",hint:"Medikamente sind ein riesiger Markt.",emoji:"💊"},
  {q:"How much kostet ein Jahresmitgliedschaft bei Amazon Prime?",a:139,unit:"Dollar",hint:"In den USA – unterschiedlich je Land.",emoji:"📦"},
  {q:"How many billion Dollar wert ist der globale Markt für Elektroautos?",a:400,unit:"billion $",hint:"Wächst schnell – Tesla führt.",emoji:"🚗"},
  {q:"How many billion Dollar Jahresumsatz hat Volkswagen?",a:293,unit:"billion €",hint:"Größter Automobilkonzern Europas.",emoji:"🚗"},
  {q:"How much kostet ein normales Herz-Transplantation in den USA?",a:1000000,unit:"Dollar",hint:"Inklusive Nachsorge.",emoji:"❤️"},
  {q:"How many billion Dollar wert ist TikTok-Eigentümer ByteDance?",a:250,unit:"billion $",hint:"Wertvollstes nicht-börsennotiertes Unternehmen.",emoji:"📱"},
  {q:"How much kostet ein Kilogramm Lithium auf dem Weltmarkt?",a:30,unit:"Dollar/kg",hint:"Essenziell für Batterien.",emoji:"⚡"},
  {q:"How many billion Dollar wert ist der globale Suchmaschinenmarkt?",a:300,unit:"billion $",hint:"Google dominiert mit über 90%.",emoji:"🔍"},
  {q:"How much kostet ein Abonnement von Netflix per month (Standard)?",a:15,unit:"Dollar/Monat",hint:"In den USA – unterschiedlich je Land.",emoji:"📺"},
  {q:"How many billion Dollar wert ist der globale Markt für Elektronikmüll?",a:60,unit:"billion $",hint:"Wertvolle Metalle landen im Müll.",emoji:"♻️"},
  {q:"How much kostet 1 Gramm Helium-3 (Mondressource)?",a:14000,unit:"Dollar/Gramm",hint:"Potenzielle Fusionsenergiequelle.",emoji:"🌙"},
  {q:"How many billion Dollar wert ist der globale Markt für Düngemittel?",a:200,unit:"billion $",hint:"Essenziell für die Nahrungsmittelproduktion.",emoji:"🌾"},
  {q:"How much kostet ein Stunde mit einem Top-Strafrechtler in Deutschland?",a:600,unit:"Euro/Stunde",hint:"Top-Anwälte verlangen enorme Stundensätze.",emoji:"⚖️"},
  {q:"How many billion Dollar wert ist der globale Markt für Halbleiter?",a:600,unit:"billion $",hint:"Chips regieren die Welt.",emoji:"💻"},
  {q:"How much kostet ein Kilo Hafnium (seltenes Metall)?",a:900,unit:"Dollar/kg",hint:"Verwendet in Atomreaktoren.",emoji:"⚗️"},
  {q:"How many billion Dollar hat der erste NFT (Beeple) eingebracht?",a:69,unit:"million $",hint:"'Everydays: The First 5000 Days' – 69 Mio. 2021.",emoji:"🖼️"},
  {q:"How much kostet ein Kilo weißes Trüffelöl?",a:5000,unit:"Euro/Liter",hint:"Das beste Trüffelöl ist extrem teuer.",emoji:"🍄"},
  {q:"How many billion Dollar ist Airbnb wert?",a:90,unit:"billion $",hint:"Stand 2024.",emoji:"🏠"},
  {q:"How much kostet eine Lungenatmung in einem US-Krankenhaus (Beatmung, Tag)?",a:10000,unit:"Dollar/Tag",hint:"Intensivstation in den USA.",emoji:"🏥"},
  {q:"How many billion Dollar wert ist der globale Markt für Robotik?",a:100,unit:"billion $",hint:"Industrieroboter und Service-Roboter.",emoji:"🤖"},
  {q:"How much kostet ein Kilogramm Gallium?",a:250,unit:"Dollar/kg",hint:"Essenziell für Halbleiter.",emoji:"⚗️"},
  {q:"How many billion Dollar wert ist Ferrari als Unternehmen?",a:60,unit:"billion $",hint:"Ferrari ist mehr Luxusmarke als Autohersteller.",emoji:"🚗"},
  {q:"How much kostet 1 Liter Kerosin für Privatjets?",a:2,unit:"Dollar/Liter",hint:"Steuerbegünstigt – weniger als Benzin.",emoji:"✈️"},
  {q:"How many billion Dollar wert ist der globale Diamantmarkt?",a:80,unit:"billion $",hint:"Lab-Diamanten bedrohen den Markt.",emoji:"💎"},
  {q:"How much kostet ein Durchschnittskauf im Hermès Paris pro Einkauf?",a:5000,unit:"Euro",hint:"Hermès-Kunden geben viel aus.",emoji:"👜"},
  {q:"How many billion Dollar wert ist Airbus?",a:100,unit:"billion €",hint:"Der größte Flugzeugbauer Europas.",emoji:"✈️"},
  {q:"How much kostet ein Tesla Model S?",a:100000,unit:"Dollar",hint:"Das Flaggschiff-Modell von Tesla.",emoji:"🚗"},
  {q:"How many billion Dollar wert ist der globale Markt für nachhaltige Investments?",a:35000,unit:"billion $",hint:"ESG-Investments boomen.",emoji:"🌿"},
  {q:"How much kostet ein km² Agrarland in Bayern?",a:80000,unit:"Euro/Hektar",hint:"Bayern hat die teuersten Agrarpreise Deutschlands.",emoji:"🌾"},
  {q:"How many billion Dollar wert ist der globale Online-Gaming-Markt?",a:250,unit:"billion $",hint:"Mobile Gaming ist der größte Teil.",emoji:"🎮"},
  {q:"How many billion Dollar wert ist IKEA?",a:58,unit:"billion $",hint:"Privat geführt – durch eine Stiftung.",emoji:"🛋️"},
  {q:"How many billion Dollar Jahresumsatz macht H&M?",a:22,unit:"billion $",hint:"Zweitgrößte Modekette der Welt.",emoji:"👗"},
  {q:"How many billion Dollar wert ist WhatsApp (beim Verkauf an Facebook)?",a:19,unit:"billion $",hint:"Gekauft 2014 für damals schwindelerregende Summe.",emoji:"💬"},
  {q:"How many billion Euro wert ist BMW?",a:70,unit:"billion €",hint:"Eines der wertvollsten deutschen Unternehmen.",emoji:"🚗"},
  {q:"How many billion Dollar kostet eine Satellitenmine?",a:300,unit:"million $",hint:"million für einen militärischen Satelliten.",emoji:"🛰️"},
  {q:"How many billion Dollar wert ist Red Bull?",a:20,unit:"billion $",hint:"Aus Österreich zum Weltkonzern.",emoji:"🐂"},
  {q:"How many billion Dollar hat die Corona-Impfkampagne die Welt gekostet?",a:15,unit:"billion $",hint:"Für die Entwicklung der mRNA-Impfstoffe.",emoji:"💉"},
  {q:"How many billion Euro wert ist Adidas?",a:35,unit:"billion €",hint:"Der Streifen ist eine der wertvollsten Marken.",emoji:"👟"},
  {q:"How many billion Dollar hat Bill Gates gespendet?",a:59,unit:"billion $",hint:"Die Gates Foundation ist größte private Stiftung.",emoji:"💝"},
  {q:"How many billion Dollar wert ist der globale Markt für Elektrizität?",a:3000,unit:"billion $",hint:"3 Billionen Dollar – essenziell für alles.",emoji:"⚡"},
  {q:"How many billion Dollar Marktkapitalisierung hat Microsoft?",a:3200,unit:"billion $",hint:"Stand 2024 – zeitweise das wertvollste Unternehmen.",emoji:"💻"},
  {q:"How many billion Euro kostet Oktoberfest die Münchner Wirtschaft?",a:1.3,unit:"billion €",hint:"Über eine Milliarde Euro Wirtschaftsleistung.",emoji:"🍺"},
  {q:"How many billion Dollar wert ist der globale Haushaltsgeräte-Markt?",a:700,unit:"billion $",hint:"Waschmaschinen, Kühlschränke und Co.",emoji:"🏠"},
  {q:"How many billion Euro Schaden entsteht durch Cyberkriminalität in Deutschland?",a:200,unit:"billion €",hint:"Jährlich laut Bitkom.",emoji:"🔒"},
  {q:"How many billion Dollar kostet 1 km Autobahn in den USA?",a:10,unit:"Mio. Dollar/km",hint:"In dicht bebauten Gebieten deutlich mehr.",emoji:"🛣️"},
  {q:"How many billion Dollar wert ist der globale Markt für Haustierprodukte?",a:260,unit:"billion $",hint:"Wächst stark – Menschen lieben ihre Haustiere.",emoji:"🐕"},
  {q:"How many billion Euro wert ist SAP?",a:200,unit:"billion €",hint:"Deutschlands wertvollstes Tech-Unternehmen.",emoji:"💻"},
  {q:"How many billion Dollar kostet die Herstellung eines Smartphones?",a:350,unit:"million $",hint:"Dollar Materialkosten für ein iPhone.",emoji:"📱"},
  {q:"How many billion Dollar hat Amazon für Whole Foods bezahlt?",a:13.7,unit:"billion $",hint:"2017 – Amazons Einstieg in den Lebensmittelhandel.",emoji:"🛒"},
  {q:"How many billion Dollar Jahresumsatz hat Coca-Cola?",a:46,unit:"billion $",hint:"Eines der bekanntesten Marken worldwide.",emoji:"🥤"},
  {q:"How many billion Dollar wert ist der globale Sportkleidungsmarkt?",a:200,unit:"billion $",hint:"Athleisure-Trend treibt das Wachstum.",emoji:"👕"},
  {q:"How many billion Euro kostet die Energiewende Deutschland bis 2035?",a:500,unit:"billion €",hint:"Schätzungen variieren erheblich.",emoji:"⚡"},
  {q:"How many billion Dollar wert ist der globale Markt für Bücher?",a:138,unit:"billion $",hint:"Print und E-Books zusammen.",emoji:"📚"},
  {q:"How many billion Dollar hat Google für YouTube bezahlt?",a:1.65,unit:"billion $",hint:"2006 – im Rückblick das Schnäppchen des Jahrhunderts.",emoji:"▶️"},
  {q:"How many billion Dollar wert ist der globale Markt für Süßigkeiten?",a:200,unit:"billion $",hint:"Schokolade, Kaugummi und Co.",emoji:"🍫"},
  {q:"How many billion Euro hat die Covid-19-Krise Deutschland gekostet?",a:300,unit:"billion €",hint:"Hilfspaket plus wirtschaftliche Einbußen.",emoji:"😷"},
  {q:"How many billion Dollar wert ist Instacart?",a:10,unit:"billion $",hint:"Lebensmittellieferservice aus San Francisco.",emoji:"🛒"},
  {q:"How many billion Dollar Jahresgewinn macht Saudi Aramco?",a:161,unit:"billion $",hint:"Das profitabelste Unternehmen der Welt.",emoji:"🛢️"},
  {q:"How many billion Euro wert ist Bosch?",a:93,unit:"billion €",hint:"Größter Automobilzulieferer der Welt.",emoji:"🔧"},
  {q:"How many billion Dollar wert ist der globale Markt für Brillen?",a:150,unit:"billion $",hint:"Luxottica dominiert den Markt.",emoji:"👓"},
  {q:"How many billion Dollar hat Facebook (Meta) für Instagram bezahlt?",a:1,unit:"billion $",hint:"2012 – heute ist Instagram billion wert.",emoji:"📸"},
  {q:"How many billion Euro Schulden hat die Deutsche Bahn?",a:30,unit:"billion €",hint:"Eines der am stärksten verschuldeten Staatsunternehmen.",emoji:"🚂"},
  {q:"How many billion Dollar wert ist der globale Markt für Kreuzfahrten?",a:150,unit:"billion $",hint:"Wächst trotz Pandemie-Einbruch wieder.",emoji:"🚢"},
  {q:"How many billion Dollar wert ist der globale Markt für Hautpflege?",a:180,unit:"billion $",hint:"Teil des riesigen Kosmetik-Markts.",emoji:"💆"},
  {q:"How many billion Dollar hat Apple für Shazam bezahlt?",a:400,unit:"million $",hint:"million Dollar für die Musik-App.",emoji:"🎵"},
  {q:"How many billion Euro Jahresumsatz hat Deutsche Telekom?",a:114,unit:"billion €",hint:"Größter Telekomkonzern Europas.",emoji:"📱"},
  {q:"How many billion Dollar wert ist der globale Markt für Dating-Apps?",a:9,unit:"billion $",hint:"Tinder, Bumble und Co.",emoji:"❤️"},
  {q:"How many billion Dollar wert ist der globale Markt für Fitness?",a:100,unit:"billion $",hint:"Fitnessstudios, Apps und Equipment.",emoji:"💪"},
  {q:"How many billion Dollar hat Microsoft für LinkedIn bezahlt?",a:26.2,unit:"billion $",hint:"2016 – das teuerste Social-Media-Acquisition.",emoji:"💼"},
  {q:"How many billion Dollar wert ist der globale Markt für Schmerzmittel?",a:35,unit:"billion $",hint:"Ibuprofen, Aspirin und Co.",emoji:"💊"},
  {q:"How many billion Dollar kostet ein Flugzeugträger der USA?",a:13,unit:"billion $",hint:"Der Gerald R. Ford kostet 13,3 billion.",emoji:"🚢"},
  {q:"How many billion Euro wert ist BASF?",a:40,unit:"billion €",hint:"Größter Chemiekonzern der Welt.",emoji:"⚗️"},
  {q:"How many billion Dollar wert ist der globale Markt für Legal Cannabis?",a:50,unit:"billion $",hint:"Wächst durch Legalisierungswellen.",emoji:"🌿"},
  {q:"How many billion Dollar Jahresumsatz macht Walt Disney?",a:88,unit:"billion $",hint:"Film, Parks, Streaming und Merchandise.",emoji:"🏰"},
  {q:"How many billion Dollar hat Microsoft für Activision Blizzard bezahlt?",a:68.7,unit:"billion $",hint:"2023 – das teuerste Gaming-Acquisition.",emoji:"🎮"},
  {q:"How many billion Euro wert ist der deutsche Immobilienmarkt?",a:14000,unit:"billion €",hint:"14 Billionen Euro – größtes nationales Vermögen.",emoji:"🏠"},
  {q:"How many billion Dollar kostet das James Webb Telescope?",a:10,unit:"billion $",hint:"Das teuerste Teleskop der Geschichte.",emoji:"🔭"},
  {q:"How many billion Euro Jahresumsatz hat Siemens?",a:77,unit:"billion €",hint:"Eines der größten Industrieunternehmen Europas.",emoji:"⚙️"},
  {q:"How many billion Dollar wert ist Zoom?",a:20,unit:"billion $",hint:"Covid hat Zoom zum Must-Have gemacht.",emoji:"📹"},
  {q:"How many billion Dollar hat TikTok laut Schätzungen Umsatz?",a:16,unit:"billion $",hint:"Stand 2023 – schnell wachsend.",emoji:"📱"},
  {q:"How many billion Dollar wert ist der globale Sneaker-Markt?",a:70,unit:"billion $",hint:"Nike, Adidas und Resale-Markt zusammen.",emoji:"👟"},
  {q:"How many billion Euro schulden Deutsche Privathaushalte insgesamt?",a:1900,unit:"billion €",hint:"1,9 Billionen Euro Privatschulden.",emoji:"💸"},
  {q:"How many billion Dollar wert ist der globale Markt für KI-Chips?",a:100,unit:"billion $",hint:"Nvidia dominiert mit seinen GPUs.",emoji:"💻"},
];
