// 🏰 FAIRY TALES & FANTASY – English
export default [
  {q:"How many dwarfs has Schneewittchen?",a:7,unit:"dwarfs",hint:"Sie alle have Namen: Schlafmütze, Brummbear, hasschi...",emoji:"🏔️"},
  {q:"How many years schlief Dornröschen?",a:100,unit:"years",hint:"Bis sie a Prinz wachküsste.",emoji:"🌹"},
  {q:"How many wishes erfüllt der Geis from der Wunderlampe in Aladdin?",a:3,unit:"wishes",hint:"wishes – dann muss der Geis in die Lampe zurück.",emoji:"🪔"},
  {q:"How many Geschwiser has Aschenputtel (Stiefschwestar)?",a:2,unit:"Stiefschwestar",hint:"Zwei böse Stiefschwestar.",emoji:"👠"},
  {q:"How many Brüder has die kleine Meerjungfrau Ariel?",a:6,unit:"Brüder",hint:"Nein – sie has 6 Schwestar.",emoji:"🧜‍♀️"},
  {q:"How many Edaysn has Rapunzels Turm?",a:1,unit:"Edaysn",hint:"Ein einziger hoher Raum ganz oben.",emoji:"🏰"},
  {q:"How many dwarfs helfen den Gnomen im Märchen Snow White?",a:7,unit:"dwarfs",hint:"Die Sieben dwarfs are weltberühmt.",emoji:"⛏️"},
  {q:"How many years needs der gestiefelten Kater um seinen Herrn reich to machen?",a:1,unit:"Jahr",hint:"Im Märchen geht es sehr schnell.",emoji:"🐱"},
  {q:"How many Schwestar has Aschenputtel?",a:2,unit:"Schwestar",hint:"Beide wollen den Prinzen for sich.",emoji:"👗"},
  {q:"How many Hänsel und Gretel Kinder are there im Märchen?",a:2,unit:"Kinder",hint:"Hänsel UND Gretel – ein Bruder-Schwester-Paar.",emoji:"🏠"},
  {q:"How many meters lang is Rapunzels Haar laut Märchen?",a:20,unit:"meterss",hint:"Lang genug for den Prinzen zum Hochklettern.",emoji:"👱‍♀️"},
  {q:"How many Wölfe are there im Märchen 'Die sieben Geißlein'?",a:1,unit:"Wolf",hint:"Ein böser Wolf – der große böse Wolf.",emoji:"🐺"},
  {q:"How many Geißlein eats der Wolf?",a:6,unit:"Geißlein",hint:"Das jüngste versteckte sich in der Wanduhr.",emoji:"🐐"},
  {q:"How many Schuhe verliert Aschenputtel?",a:1,unit:"Schuh",hint:"Den gläsernen Schuh on der Treppe.",emoji:"👠"},
  {q:"How many Charaktere besuchen die Bremer Stadtmusikanten?",a:4,unit:"animals",hint:"Esel, dog, cat, Hahn.",emoji:"🎵"},
  {q:"How many Prinzessinnen tanzen die Nacht through im Märchen 'Die zertanzten Schuhe'?",a:12,unit:"Prinzessinnen",hint:"Schwestar tanzen heimlich.",emoji:"👠"},
  {q:"How many Küsse needs der Froschkönig um Mensch to are?",a:1,unit:"Kuss",hint:"Ein einziger Kuss der Prinzessin.",emoji:"🐸"},
  {q:"How many Schwestar has Cinderella in Disneys Version?",a:2,unit:"Stiefschwestar",hint:"Anastasia und Drizella.",emoji:"👑"},
  {q:"How many years sleeps die Schöne im Dornröschen?",a:100,unit:"years",hint:"Das gesamte Schloss sleeps with.",emoji:"😴"},
  {q:"How many animals helfen Schneewittchen im whaled?",a:7,unit:"whaledtiere",hint:"Die whaledtiere helfen ihr das Haus der dwarfs to finden.",emoji:"🦌"},
  {q:"How many timese versucht die Hexe Schneewittchen to töten?",a:3,unit:"timese",hint:"Haarband, Kamm und vergifteter Apfel.",emoji:"🍎"},
];
