// 🏰 FAIRY TALES & FANTASY – English
export default [
  {q:"How many Zwerge hat Schneewittchen?",a:7,unit:"Zwerge",hint:"Sie alle haben Namen: Schlafmütze, Brummbär, Hatschi...",emoji:"🏔️"},
  {q:"How many Jahre schlief Dornröschen?",a:100,unit:"years",hint:"Bis sie ein Prinz wachküsste.",emoji:"🌹"},
  {q:"How many Wünsche erfüllt der Geist aus der Wunderlampe in Aladdin?",a:3,unit:"Wünsche",hint:"Wünsche – dann muss der Geist in die Lampe zurück.",emoji:"🪔"},
  {q:"How many Geschwister hat Aschenputtel (Stiefschwestern)?",a:2,unit:"Stiefschwestern",hint:"Zwei böse Stiefschwestern.",emoji:"👠"},
  {q:"How many Brüder hat die kleine Meerjungfrau Ariel?",a:6,unit:"Brüder",hint:"Nein – sie hat 6 Schwestern.",emoji:"🧜‍♀️"},
  {q:"How many Etagen hat Rapunzels Turm?",a:1,unit:"Etagen",hint:"Ein einziger hoher Raum ganz oben.",emoji:"🏰"},
  {q:"How many Zwerge helfen den Gnomen im Märchen Snow White?",a:7,unit:"Zwerge",hint:"Die Sieben Zwerge sind weltberühmt.",emoji:"⛏️"},
  {q:"How many Jahre braucht der gestiefelten Kater um seinen Herrn reich zu machen?",a:1,unit:"Jahr",hint:"Im Märchen geht es sehr schnell.",emoji:"🐱"},
  {q:"How many Schwestern hat Aschenputtel?",a:2,unit:"Schwestern",hint:"Beide wollen den Prinzen für sich.",emoji:"👗"},
  {q:"How many Hänsel und Gretel Kinder gibt es im Märchen?",a:2,unit:"Kinder",hint:"Hänsel UND Gretel – ein Bruder-Schwester-Paar.",emoji:"🏠"},
  {q:"How many Meter lang ist Rapunzels Haar laut Märchen?",a:20,unit:"meters",hint:"Lang genug für den Prinzen zum Hochklettern.",emoji:"👱‍♀️"},
  {q:"How many Wölfe gibt es im Märchen 'Die sieben Geißlein'?",a:1,unit:"Wolf",hint:"Ein böser Wolf – der große böse Wolf.",emoji:"🐺"},
  {q:"How many Geißlein frisst der Wolf?",a:6,unit:"Geißlein",hint:"Das jüngste versteckte sich in der Wanduhr.",emoji:"🐐"},
  {q:"How many Schuhe verliert Aschenputtel?",a:1,unit:"Schuh",hint:"Den gläsernen Schuh auf der Treppe.",emoji:"👠"},
  {q:"How many Charaktere besuchen die Bremer Stadtmusikanten?",a:4,unit:"Tiere",hint:"Esel, Hund, Katze, Hahn.",emoji:"🎵"},
  {q:"How many Prinzessinnen tanzen die Nacht durch im Märchen 'Die zertanzten Schuhe'?",a:12,unit:"Prinzessinnen",hint:"Schwestern tanzen heimlich.",emoji:"👠"},
  {q:"How many Küsse braucht der Froschkönig um Mensch zu werden?",a:1,unit:"Kuss",hint:"Ein einziger Kuss der Prinzessin.",emoji:"🐸"},
  {q:"How many Schwestern hat Cinderella in Disneys Version?",a:2,unit:"Stiefschwestern",hint:"Anastasia und Drizella.",emoji:"👑"},
  {q:"How many Jahre schläft die Schöne im Dornröschen?",a:100,unit:"years",hint:"Das gesamte Schloss schläft mit.",emoji:"😴"},
  {q:"How many Tiere helfen Schneewittchen im Wald?",a:7,unit:"Waldtiere",hint:"Die Waldtiere helfen ihr das Haus der Zwerge zu finden.",emoji:"🦌"},
  {q:"How many Male versucht die Hexe Schneewittchen zu töten?",a:3,unit:"Male",hint:"Haarband, Kamm und vergifteter Apfel.",emoji:"🍎"},
];
