// 🌊 OCEANS – Kids – 53 questions
export default [
  {id:"ozean_001",q:"How many oceans are there on Earth?",a:5,unit:"oceans",hint:"Pacific, Atlantic, Indian Ocean, Arctic, Antarctic (Southern).",emoji:"🌊"},
  {id:"ozean_002",q:"How many meters deep is the Mariana Trench?",a:11034,unit:"meters",hint:"The deepest point: Challenger Deep – 11,034m.",emoji:"🌊"},
  {id:"ozean_003",q:"What percentage of Earth is covered by water?",a:71,unit:"%",hint:"71% water – Earth is a water planet.",emoji:"🌍"},
  {id:"ozean_004",q:"How many meters long does a full-grown blue whale get?",a:30,unit:"meters",hint:"Up to 33m – the largest animal of all time.",emoji:"🐋"},
  {id:"ozean_005",q:"How many arms does a squid have?",a:8,unit:"arms",hint:"8 arms – octopuses also have 8, squid have 10.",emoji:"🦑"},
  {id:"ozean_006",q:"How many teeth does a great white shark have?",a:300,unit:"teeth",hint:"Up to 300 teeth in multiple rows – constantly regrowing.",emoji:"🦈"},
  {id:"ozean_007",q:"How many fish species live in the ocean?",a:20000,unit:"species",hint:"Over 20,000 known marine fish species.",emoji:"🐠"},
  {id:"ozean_008",q:"How many tentacles does an octopus have?",a:8,unit:"tentacles",hint:"8 arms with suction cups – very intelligent.",emoji:"🐙"},
  {id:"ozean_009",q:"How many meters deep does a sperm whale dive?",a:2000,unit:"meters",hint:"Up to 2,000m – holding its breath for up to 90 minutes.",emoji:"🐋"},
  {id:"ozean_010",q:"What percentage of the ocean depths remain unexplored?",a:80,unit:"%",hint:"About 80% – we know more about the moon than our oceans.",emoji:"🔭"},
  {id:"ozean_011",q:"How many km/h does a dolphin swim?",a:55,unit:"km/h",hint:"Up to 55 km/h – one of the fastest marine mammals.",emoji:"🐬"},
  {id:"ozean_012",q:"How many arms does a starfish have?",a:5,unit:"arms",hint:"Usually 5 – but some species have up to 40 arms.",emoji:"⭐"},
  {id:"ozean_013",q:"How many meters long does a whale shark get?",a:12,unit:"meters",hint:"Up to 12m – the largest fish in the world, but harmless.",emoji:"🐋"},
  {id:"ozean_014",q:"How many meters deep does a penguin dive while hunting?",a:500,unit:"meters",hint:"Emperor penguins dive up to 500m – record is 565m.",emoji:"🐧"},
  {id:"ozean_015",q:"How many kilometers long is the Great Barrier Reef?",a:2300,unit:"km",hint:"2,300 km – the largest coral reef in the world.",emoji:"🪸"},
  {id:"ozean_016",q:"How many coral species are there?",a:800,unit:"species",hint:"Over 800 coral species – they form reefs for thousands of animals.",emoji:"🪸"},
  {id:"ozean_017",q:"How many km/h does the Gulf Stream flow?",a:9,unit:"km/h",hint:"About 9 km/h – it keeps Europe's climate warm.",emoji:"🌡️"},
  {id:"ozean_018",q:"What percentage salt does seawater have?",a:3.5,unit:"%",hint:"About 3.5% salinity – the Dead Sea has 34%.",emoji:"🧂"},
  {id:"ozean_019",q:"How many species of sea turtles are there?",a:7,unit:"species",hint:"Leatherback, loggerhead, and 5 others.",emoji:"🐢"},
  {id:"ozean_020",q:"How many hearts does a squid have?",a:3,unit:"hearts",hint:"3 hearts – one for the body, two for the gills.",emoji:"🐙"},
  {id:"ozean_021",q:"How many seconds can a flying fish stay in the air?",a:45,unit:"seconds",hint:"Up to 45 seconds – and glide up to 400m.",emoji:"🐟"},
  {id:"ozean_022",q:"How fast can a swordfish swim, in km/h?",a:130,unit:"km/h",hint:"Up to 130 km/h – one of the fastest fish.",emoji:"🐟"},
  {id:"ozean_023",q:"How many years old can a Greenland shark get?",a:400,unit:"years",hint:"Up to 400 years – the oldest known vertebrate.",emoji:"🦈"},
  {id:"ozean_024",q:"How many meters deep is the Atlantic Ocean on average?",a:3332,unit:"meters",hint:"Average 3,332m – maximum depth 8,376m.",emoji:"🌊"},
  {id:"ozean_025",q:"How many jellyfish species are there?",a:2000,unit:"species",hint:"Over 2,000 known jellyfish species.",emoji:"🪼"},
  {id:"ozean_026",q:"What percentage of Earth's water is saltwater?",a:97,unit:"%",hint:"97% saltwater – only 3% is freshwater.",emoji:"💧"},
  {id:"ozean_027",q:"How many million tons of plastic end up in the ocean each year?",a:8,unit:"million tons",hint:"About 8 million tons per year – a disaster.",emoji:"♻️"},
  {id:"ozean_028",q:"How many tons does a full-grown blue whale weigh?",a:150,unit:"tons",hint:"Up to 150-200 tons – the heaviest animal of all time.",emoji:"🐋"},
  {id:"ozean_029",q:"How fast does the fastest fish (sailfish) swim, in km/h?",a:110,unit:"km/h",hint:"The Atlantic sailfish reaches up to 110 km/h.",emoji:"🐟"},
  {id:"ozean_030",q:"How many years does it take a plastic bottle to break down in the ocean?",a:450,unit:"years",hint:"450 years – PET plastic decomposes extremely slowly.",emoji:"♻️"},
  {id:"ozean_031",q:"How many spikes does a pufferfish have when it inflates?",a:300,unit:"spikes",hint:"Up to 300 venomous spikes – a very effective defense.",emoji:"🐡"},
  {id:"ozean_032",q:"How many decibels loud is a blue whale's call?",a:188,unit:"decibels",hint:"188 dB – louder than a jet engine.",emoji:"🔊"},
  {id:"ozean_033",q:"How many meters deep can sunlight penetrate?",a:200,unit:"meters",hint:"Below 200m it gets dark – the deep sea is completely dark.",emoji:"💡"},
  {id:"ozean_034",q:"How many shark species are there?",a:500,unit:"species",hint:"Over 500 shark species – from 15cm to 12m.",emoji:"🦈"},
  {id:"ozean_035",q:"How fast can an orca swim, in km/h?",a:55,unit:"km/h",hint:"Up to 55 km/h – the fastest marine mammal.",emoji:"🐋"},
  {id:"ozean_036",q:"How many eggs does a sea turtle lay per season?",a:100,unit:"eggs",hint:"50-200 eggs per clutch – several times per season.",emoji:"🐢"},
  {id:"ozean_037",q:"What percentage of marine life remains undiscovered?",a:91,unit:"%",hint:"An estimated 91% – the ocean holds many secrets.",emoji:"🔍"},
  {id:"ozean_038",q:"How many meters wide is a manta ray (wingspan)?",a:7,unit:"meters",hint:"Up to 7m wingspan – gentle and harmless.",emoji:"🐟"},
  {id:"ozean_039",q:"How many meters deep can a sperm whale dive at maximum?",a:3000,unit:"meters",hint:"Up to 3,000m – hunting giant squid.",emoji:"🐋"},
  {id:"ozean_040",q:"How many millimeters long is the smallest fish in the world?",a:7.9,unit:"millimeters",hint:"Paedocypris progenetica – only 7.9mm small.",emoji:"🐟"},
  {id:"ozean_041",q:"How many arms does a giant squid have?",a:10,unit:"tentacles",hint:"8 arms + 2 longer feeding tentacles = 10 tentacles.",emoji:"🦑"},
  {id:"ozean_042",q:"How many km/h do tsunami waves travel?",a:720,unit:"km/h",hint:"Up to 720 km/h – like a jet plane.",emoji:"🌊"},
  {id:"ozean_043",q:"How many meters long is a giant squid?",a:13,unit:"meters",hint:"Up to 13m – including tentacles, the largest known.",emoji:"🦑"},
  {id:"ozean_044",q:"How many million km² is the Pacific Ocean?",a:165,unit:"million km²",hint:"165 million km² – bigger than all land combined.",emoji:"🌊"},
  {id:"ozean_045",q:"How many kilometers long is the Amazon?",a:6400,unit:"km",hint:"6,400 km long – the river with the most water in the world.",emoji:"🌿"},
  {id:"ozean_046",q:"How many liters of water does a blue whale drink daily?",a:3785,unit:"liters",hint:"About 3,800 liters – through filtering krill.",emoji:"🐋"},
  {id:"ozean_047",q:"How many hours does a seal sleep per day?",a:20,unit:"hours",hint:"Up to 20 hours daily – sometimes sleeping in the water.",emoji:"🦭"},
  {id:"ozean_048",q:"How many suction cups does a giant squid have per tentacle?",a:100,unit:"suction cups",hint:"Up to 100 suction cups per arm – with teeth around the edge.",emoji:"🦑"},
  {id:"ozean_049",q:"How many meters can a squid squirt its ink?",a:2,unit:"meters",hint:"Up to 2 meters – to confuse predators.",emoji:"🐙"},
  {id:"ozean_050",q:"How many grams does a seahorse weigh?",a:8,unit:"grams",hint:"The smallest seahorse weighs only 8 grams.",emoji:"🐟"},
  {id:"ozean_051",q:"What percentage of its body weight does a crab eat daily?",a:10,unit:"%",hint:"Up to 10% of its body weight daily.",emoji:"🦀"},
  {id:"ozean_052",q:"How many kilometers does a humpback whale migrate per year?",a:16000,unit:"km",hint:"Up to 16,000 km – one of the longest animal migrations.",emoji:"🐋"},
  {id:"ozean_053",q:"How many colors can an octopus change between?",a:30,unit:"colors",hint:"Over 30 color patterns – for camouflage and communication.",emoji:"🐙"},
];
