// 🎨 ART & MUSIC – Kids – 65 questions
export default [
  {id:"kunst_001",q:"How many colors does a rainbow have?",a:7,unit:"colors",hint:"Red, orange, yellow, green, blue, indigo, violet.",emoji:"🌈"},
  {id:"kunst_002",q:"How many years did Leonardo da Vinci spend painting the Mona Lisa?",a:4,unit:"years",hint:"About 1503-1507 – some say he never really stopped.",emoji:"🖼️"},
  {id:"kunst_003",q:"How many strings does a classical guitar have?",a:6,unit:"strings",hint:"6 strings – a ukulele has 4, a violin also has 4.",emoji:"🎸"},
  {id:"kunst_004",q:"How many keys does a modern piano have?",a:88,unit:"keys",hint:"52 white and 36 black keys.",emoji:"🎹"},
  {id:"kunst_005",q:"How many primary colors are there in painting?",a:3,unit:"primary colors",hint:"Red, yellow, blue – all other colors come from these.",emoji:"🎨"},
  {id:"kunst_006",q:"How many lines does a musical staff have (one system)?",a:5,unit:"lines",hint:"5 lines and 4 spaces.",emoji:"🎵"},
  {id:"kunst_007",q:"How many strings does a violin have?",a:4,unit:"strings",hint:"G, D, A, E – from low to high.",emoji:"🎻"},
  {id:"kunst_008",q:"How many notes does an octave have?",a:8,unit:"notes",hint:"Do, Re, Mi, Fa, Sol, La, Ti, Do.",emoji:"🎼"},
  {id:"kunst_009",q:"How many colors does the German flag have?",a:3,unit:"colors",hint:"Black, red, gold – since 1919.",emoji:"🇩🇪"},
  {id:"kunst_010",q:"How many strings does a classical harp have?",a:47,unit:"strings",hint:"47 strings and 7 pedals.",emoji:"🎵"},
  {id:"kunst_011",q:"How many valves does a classical trumpet have?",a:3,unit:"valves",hint:"3 valves – used to play different notes.",emoji:"🎺"},
  {id:"kunst_012",q:"How many sides does a triangle have?",a:3,unit:"sides",hint:"3 sides, 3 corners, angles add up to 180°.",emoji:"📐"},
  {id:"kunst_013",q:"How many letters does the German alphabet have?",a:26,unit:"letters",hint:"26 letters plus the umlauts ä, ö, ü and ß.",emoji:"📝"},
  {id:"kunst_014",q:"How many sides does an octagon have?",a:8,unit:"sides",hint:"Octagon = 8 sides – like a stop sign.",emoji:"🛑"},
  {id:"kunst_015",q:"How many sides does a hexagon have?",a:6,unit:"sides",hint:"Hexa = 6 – like a honeycomb.",emoji:"🐝"},
  {id:"kunst_016",q:"How many primary colors are there in light (RGB)?",a:3,unit:"colors",hint:"Red, green, blue – together they make white.",emoji:"💡"},
  {id:"kunst_017",q:"How many notes does the pentatonic scale have?",a:5,unit:"notes",hint:"5 notes – the basis of many folk songs and blues.",emoji:"🎵"},
  {id:"kunst_018",q:"How many meters tall is the Eiffel Tower?",a:330,unit:"meters",hint:"With the antenna, 330m – without it, 300m. Built in 1889.",emoji:"🗼"},
  {id:"kunst_019",q:"How many sides does a pentagon have?",a:5,unit:"sides",hint:"Penta = five.",emoji:"⬠"},
  {id:"kunst_020",q:"How many colors does a typical small box of colored pencils have?",a:12,unit:"colors",hint:"Small boxes usually have 12, big ones up to 120 colors.",emoji:"🖍️"},
  {id:"kunst_021",q:"How many works did Pablo Picasso create?",a:20000,unit:"works",hint:"Over 20,000 works – paintings, sculptures, drawings.",emoji:"🎨"},
  {id:"kunst_022",q:"How many meters long is the Sistine Chapel?",a:40,unit:"meters",hint:"40 meters long, 13 meters wide – Michelangelo painted the ceiling.",emoji:"⛪"},
  {id:"kunst_023",q:"How many years did Michelangelo work on the Sistine Chapel ceiling?",a:4,unit:"years",hint:"1508-1512 – lying on a scaffold.",emoji:"🎨"},
  {id:"kunst_024",q:"How many levels does the Eiffel Tower have?",a:3,unit:"levels",hint:"3 levels – you can enjoy the view from all of them.",emoji:"🗼"},
  {id:"kunst_025",q:"How many primary colors are used in printing (CMYK)?",a:4,unit:"colors",hint:"Cyan, Magenta, Yellow, Key (black) – for printing.",emoji:"🖨️"},
  {id:"kunst_026",q:"How many notes does the chromatic scale have?",a:12,unit:"notes",hint:"12 half-steps within one octave.",emoji:"🎹"},
  {id:"kunst_027",q:"How many colors does white light contain?",a:7,unit:"colors",hint:"White light contains all the colors of the rainbow.",emoji:"🌈"},
  {id:"kunst_028",q:"How many meters tall is the Mona Lisa?",a:0.77,unit:"meters",hint:"77 cm × 53 cm – smaller than most people think.",emoji:"🖼️"},
  {id:"kunst_029",q:"How many paintings did van Gogh sell during his lifetime?",a:1,unit:"painting",hint:"Only one – during his lifetime.",emoji:"🌻"},
  {id:"kunst_030",q:"How many stars are in van Gogh's 'Starry Night'?",a:11,unit:"stars",hint:"11 stars plus the moon in the famous painting.",emoji:"🌙"},
  {id:"kunst_031",q:"How many notes sound in a major chord?",a:3,unit:"notes",hint:"Root, third, and fifth – e.g., C-E-G.",emoji:"🎵"},
  {id:"kunst_032",q:"How many octaves does a regular piano have?",a:7,unit:"octaves",hint:"7 full octaves plus a few extra notes.",emoji:"🎹"},
  {id:"kunst_033",q:"How many colors does the rainbow (Pride) flag have?",a:6,unit:"colors",hint:"Red, orange, yellow, green, blue, violet.",emoji:"🏳️‍🌈"},
  {id:"kunst_034",q:"How many colors does the Olympic logo have?",a:5,unit:"colors",hint:"Blue, yellow, black, green, red – one for each continent.",emoji:"🏅"},
  {id:"kunst_035",q:"How many sides does a rectangle have?",a:4,unit:"sides",hint:"4 sides – two pairs of equal length.",emoji:"▭"},
  {id:"kunst_036",q:"How many sides does a heptagon have?",a:7,unit:"sides",hint:"Hepta = seven.",emoji:"⬡"},
  {id:"kunst_037",q:"How many sides does an octagon have?",a:8,unit:"sides",hint:"Octa = eight.",emoji:"🛑"},
  {id:"kunst_038",q:"How many years old is the Venus de Milo?",a:2200,unit:"years",hint:"Created around 130-100 BCE – so about 2,200 years old.",emoji:"🏛️"},
  {id:"kunst_039",q:"How many cm long is a sheet of A4 paper?",a:29.7,unit:"cm",hint:"A4: 21 × 29.7 cm – the most common paper size.",emoji:"📄"},
  {id:"kunst_040",q:"How many grams does a normal pencil weigh?",a:6,unit:"grams",hint:"About 5-7 grams – depending on length.",emoji:"✏️"},
  {id:"kunst_041",q:"How many millimeters wide is a normal pencil?",a:7,unit:"millimeters",hint:"About 7mm – the lead inside is only 2mm.",emoji:"✏️"},
  {id:"kunst_042",q:"How many paintings did Leonardo da Vinci create in his lifetime?",a:20,unit:"paintings",hint:"Only about 15-20 finished paintings – but thousands of drawings.",emoji:"🖼️"},
  {id:"kunst_043",q:"How many hours a day did Picasso paint at his peak?",a:8,unit:"hours",hint:"Up to 8 hours – he was extremely productive.",emoji:"🖌️"},
  {id:"kunst_044",q:"How many colors do you mix to get orange?",a:2,unit:"colors",hint:"Red + yellow = orange.",emoji:"🎨"},
  {id:"kunst_045",q:"How many colors do you mix to get green?",a:2,unit:"colors",hint:"Blue + yellow = green.",emoji:"🎨"},
  {id:"kunst_046",q:"How many colors do you mix to get purple?",a:2,unit:"colors",hint:"Red + blue = purple.",emoji:"🎨"},
  {id:"kunst_047",q:"How many sides does a kite (quadrilateral) have?",a:4,unit:"sides",hint:"A kite is a quadrilateral with two pairs of equal-length sides.",emoji:"🪁"},
  {id:"kunst_048",q:"How many notes does a song usually have at minimum?",a:8,unit:"notes",hint:"Most simple songs have at least 8 notes.",emoji:"🎵"},
  {id:"kunst_049",q:"How many kg does a Steinway concert grand piano weigh?",a:480,unit:"kg",hint:"About 480 kg – a very heavy instrument.",emoji:"🎹"},
  {id:"kunst_050",q:"How many colors does a normal school watercolor palette have?",a:12,unit:"colors",hint:"12 colors – enough for elementary school students.",emoji:"🎨"},
  {id:"kunst_051",q:"How many minutes does Beethoven's 5th Symphony last?",a:33,unit:"minutes",hint:"About 33 minutes – with its famous opening motif.",emoji:"🎼"},
  {id:"kunst_052",q:"How many sides does a square have?",a:4,unit:"sides",hint:"4 equal sides – all angles 90°.",emoji:"⬜"},
  {id:"kunst_053",q:"How many meters is the largest canvas in the world?",a:5000,unit:"meters",hint:"A 5,000m² canvas was painted in Dubai.",emoji:"🖼️"},
  {id:"kunst_054",q:"How many centimeters thick is the wall of the Sistine Chapel?",a:60,unit:"cm",hint:"The walls are about 60cm thick – typical for Renaissance buildings.",emoji:"🏛️"},
  {id:"kunst_055",q:"How many million colors can the human eye distinguish?",a:10,unit:"million colors",hint:"About 10 million shades – the brain processes them.",emoji:"👁️"},
  {id:"kunst_056",q:"How many characters does the Chinese alphabet have?",a:50000,unit:"characters",hint:"About 50,000 characters – everyday use needs about 3,000.",emoji:"📝"},
  {id:"kunst_057",q:"How many works did Mozart write?",a:626,unit:"works",hint:"626 works – his last piece remained unfinished.",emoji:"🎼"},
  {id:"kunst_058",q:"How old was Mozart when he died?",a:35,unit:"years",hint:"Wolfgang Amadeus Mozart died in 1791 at age 35.",emoji:"🎹"},
  {id:"kunst_059",q:"How many symphonies did Beethoven write?",a:9,unit:"symphonies",hint:"9 symphonies – his 9th is especially famous.",emoji:"🎼"},
  {id:"kunst_060",q:"How many eighth notes does a quarter note equal?",a:2,unit:"eighth notes",hint:"A quarter note = 2 eighth notes = 4 sixteenth notes.",emoji:"🎵"},
  {id:"kunst_061",q:"How many musical keys are there?",a:24,unit:"keys",hint:"12 major and 12 minor keys.",emoji:"🎹"},
  {id:"kunst_062",q:"How many hours did it take to create the Sistine Chapel ceiling?",a:20000,unit:"hours",hint:"About 4 years × 5,000 hours/year – an enormous amount of work.",emoji:"⛪"},
  {id:"kunst_063",q:"How many pieces did Rembrandt paint?",a:350,unit:"paintings",hint:"About 350 paintings – plus hundreds of etchings.",emoji:"🖼️"},
  {id:"kunst_064",q:"How many meters tall is the Brandenburg Gate?",a:26,unit:"meters",hint:"26m tall – a landmark of Berlin.",emoji:"🏛️"},
  {id:"kunst_065",q:"How many columns does the Brandenburg Gate have?",a:12,unit:"columns",hint:"12 Doric columns – 6 in front, 6 in back.",emoji:"🏛️"},
];
