// 🚀 SPACE – Kids – Part 1 of 240
export default [
  {id:"kwelt_001",q:"How many planets are there in our solar system?",a:8,unit:"planets",hint:"Pluto hasn't been a planet since 2006.",emoji:"🪐"},
  {id:"kwelt_002",q:"How many minutes does sunlight take to reach Earth?",a:8,unit:"minutes",hint:"Light travels at 300,000 km per second.",emoji:"☀️"},
  {id:"kwelt_003",q:"How many moons does Saturn have?",a:146,unit:"moons",hint:"Saturn has the most moons of any planet.",emoji:"🪐"},
  {id:"kwelt_004",q:"How far is Earth from the Sun, in million km?",a:150,unit:"million km",hint:"This distance is called 1 Astronomical Unit.",emoji:"☀️"},
  {id:"kwelt_005",q:"How many degrees Celsius is it on the Moon at night?",a:-170,unit:"°C",hint:"During the day it's +130°C.",emoji:"🌙"},
  {id:"kwelt_006",q:"How many billion stars does our Milky Way have?",a:200,unit:"billion",hint:"Billions of stars in the Milky Way alone.",emoji:"⭐"},
  {id:"kwelt_007",q:"How old is the universe, in billion years?",a:13.8,unit:"billion years",hint:"Since the Big Bang.",emoji:"🌌"},
  {id:"kwelt_008",q:"How many km is the Moon from Earth?",a:384.4,unit:"thousand km",hint:"Apollo astronauts took 3 days.",emoji:"🌙"},
  {id:"kwelt_009",q:"How high does the ISS fly above Earth, in km?",a:400,unit:"km",hint:"It orbits Earth every 90 minutes.",emoji:"🚀"},
  {id:"kwelt_010",q:"How many Earth masses does Jupiter have?",a:318,unit:"Earth masses",hint:"Jupiter is this many times heavier than Earth.",emoji:"🪐"},
  {id:"kwelt_011",q:"How many months does a year on Mars last?",a:24,unit:"Earth months",hint:"A Mars year = 687 Earth days.",emoji:"🔴"},
  {id:"kwelt_012",q:"How many km/h does Earth move around the Sun?",a:107000,unit:"km/h",hint:"That's 30 km per second.",emoji:"🌍"},
  {id:"kwelt_013",q:"How many km is Earth's diameter?",a:12742,unit:"km",hint:"It's slightly thicker at the equator than at the poles.",emoji:"🌍"},
  {id:"kwelt_014",q:"How hot is the Sun's surface, in °C?",a:5500,unit:"°C",hint:"In the core it's 15 million degrees.",emoji:"☀️"},
  {id:"kwelt_015",q:"How many hours did the first moon landing last on the Moon?",a:21,unit:"hours",hint:"Neil Armstrong and Buzz Aldrin on July 20, 1969.",emoji:"🌙"},
  {id:"kwelt_016",q:"How many km is Earth's circumference at the equator?",a:40075,unit:"km",hint:"Earth isn't perfectly round.",emoji:"🌍"},
  {id:"kwelt_017",q:"How many astronauts have been on the Moon so far?",a:12,unit:"astronauts",hint:"All 12 were Americans during the Apollo missions.",emoji:"👨‍🚀"},
  {id:"kwelt_018",q:"How many rings does Saturn have?",a:7,unit:"main rings",hint:"The rings are made of ice and rock.",emoji:"🪐"},
  {id:"kwelt_019",q:"How many moons does Mars have?",a:2,unit:"moons",hint:"Phobos and Deimos – both very small.",emoji:"🔴"},
  {id:"kwelt_020",q:"How many km/h must a rocket fly to leave Earth?",a:40000,unit:"km/h",hint:"That's Earth's escape velocity.",emoji:"🚀"},
  {id:"kwelt_021",q:"How big is the Great Red Spot on Jupiter, in km?",a:16000,unit:"km",hint:"A storm that's been raging for 350 years.",emoji:"🪐"},
  {id:"kwelt_022",q:"How many km is the Sun's diameter?",a:1.39,unit:"million km",hint:"The Sun is 109 times wider than Earth.",emoji:"☀️"},
  {id:"kwelt_023",q:"How fast does Earth rotate at the equator, in km/h?",a:1670,unit:"km/h",hint:"We don't feel the rotation because everything moves with it.",emoji:"🌍"},
  {id:"kwelt_024",q:"How many degrees Celsius is the temperature in space?",a:-270,unit:"°C",hint:"Almost absolute zero, which is -273°C.",emoji:"❄️"},
  {id:"kwelt_025",q:"How far is Alpha Centauri from Earth, in light-years?",a:4,unit:"light-years",hint:"The nearest star system to ours.",emoji:"⭐"},
  {id:"kwelt_026",q:"How many hours does a day on Venus last?",a:5832,unit:"hours",hint:"A Venus year is shorter than a Venus day!",emoji:"🪐"},
  {id:"kwelt_027",q:"How long does a day on Mercury last, in Earth days?",a:59,unit:"Earth days",hint:"Mercury rotates very slowly on its axis.",emoji:"☿"},
  {id:"kwelt_028",q:"How many million times bigger is the Sun than Earth (volume)?",a:1.3,unit:"million times",hint:"1.3 million Earths would fit inside the Sun.",emoji:"☀️"},
  {id:"kwelt_029",q:"How hot is Earth's core, in °C?",a:6000,unit:"°C",hint:"About as hot as the Sun's surface.",emoji:"🌍"},
  {id:"kwelt_030",q:"How many km/h does the solar wind travel?",a:500000,unit:"km/h",hint:"Electrically charged particles from the Sun.",emoji:"💨"},
  {id:"kwelt_031",q:"How many moons does Jupiter have?",a:95,unit:"moons",hint:"As of 2023 – the most of any planet.",emoji:"🪐"},
  {id:"kwelt_032",q:"How heavy is Earth, in kg (power of ten)?",a:24,unit:"× 10^? kg",hint:"5.97 × 10^24 kg.",emoji:"🌍"},
  {id:"kwelt_033",q:"How many years does light take from the galaxy's center to Earth?",a:26000,unit:"light-years",hint:"We live on the edge of the Milky Way.",emoji:"🌌"},
  {id:"kwelt_034",q:"How high does an airplane fly, in km?",a:10,unit:"km",hint:"Cruising altitude 9-12 km.",emoji:"✈️"},
  {id:"kwelt_035",q:"How many planets does our solar system have?",a:8,unit:"planets",hint:"Pluto hasn't been a planet since 2006.",emoji:"🪐"},
  {id:"kwelt_036",q:"How deep is the ocean on Europa (Jupiter's moon), in km?",a:100,unit:"km",hint:"Under the ice – possible life.",emoji:"❄️"},
  {id:"kwelt_037",q:"How many stars can you see at night with the naked eye?",a:5000,unit:"stars",hint:"On a clear night with no light pollution.",emoji:"⭐"},
  {id:"kwelt_038",q:"How long does it take a rocket to travel from Earth to the Moon?",a:3,unit:"days",hint:"Apollo astronauts took 3 days.",emoji:"🚀"},
  {id:"kwelt_039",q:"How big is an asteroid that could wipe out life on Earth, in km?",a:10,unit:"km",hint:"The Chicxulub asteroid was about 10 km in size.",emoji:"☄️"},
  {id:"kwelt_040",q:"How many hours does a day on the Moon last?",a:709,unit:"hours",hint:"The Moon rotates very slowly.",emoji:"🌙"},
  {id:"kwelt_041",q:"How cold is space, in °C?",a:-270,unit:"°C",hint:"Almost absolute zero.",emoji:"❄️"},
  {id:"kwelt_042",q:"How many satellites orbit the Earth?",a:9000,unit:"satellites",hint:"Active and inactive combined.",emoji:"🛰️"},
  {id:"kwelt_043",q:"How long did the first moon landing last on the Moon?",a:21,unit:"hours",hint:"Neil Armstrong and Buzz Aldrin.",emoji:"🌙"},
  {id:"kwelt_044",q:"How many km/h does a rocket need to reach the Moon?",a:40000,unit:"km/h",hint:"Earth's escape velocity.",emoji:"🚀"},
  {id:"kwelt_045",q:"How far is Neptune from the Sun, in billion km?",a:4.5,unit:"billion km",hint:"The farthest planet in the solar system.",emoji:"🔵"},
  {id:"kwelt_046",q:"How many moons does Neptune have?",a:16,unit:"moons",hint:"The biggest is called Triton.",emoji:"🔵"},
  {id:"kwelt_047",q:"How many km is Pluto's diameter?",a:2377,unit:"km",hint:"Smaller than the Moon.",emoji:"🌑"},
  {id:"kwelt_048",q:"How many years did it take to build the James Webb Telescope?",a:25,unit:"years",hint:"Years from idea to completion.",emoji:"🔭"},
  {id:"kwelt_049",q:"How high above Earth is the ISS, in km?",a:400,unit:"km",hint:"Orbits Earth every 90 minutes.",emoji:"🚀"},
  {id:"kwelt_050",q:"How big is the Kármán line (boundary to space), in km?",a:100,unit:"km",hint:"Space officially begins at 100 km.",emoji:"🚀"},
  {id:"kwelt_051",q:"How cold is it on Triton (Neptune's moon), in °C?",a:-235,unit:"°C",hint:"One of the coldest bodies in the solar system.",emoji:"❄️"},
  {id:"kwelt_052",q:"How long is a Mars month, in days?",a:59,unit:"days",hint:"2 Mars months together.",emoji:"🔴"},
  {id:"kwelt_053",q:"How many years did it take Voyager 1 to leave the solar system?",a:35,unit:"years",hint:"Launched in 1977 – reached the heliopause in 2012.",emoji:"🚀"},
  {id:"kwelt_054",q:"How fast is the speed of sound on Mars?",a:240,unit:"m/s",hint:"Slightly slower than on Earth.",emoji:"🔴"},
  {id:"kwelt_055",q:"How many km/s does Earth move around the Sun?",a:30,unit:"km/s",hint:"That's 107,000 km/h.",emoji:"🌍"},
  {id:"kwelt_056",q:"How big is a typical comet nucleus, in km?",a:5,unit:"km",hint:"Usually 1-10 km in size.",emoji:"☄️"},
  {id:"kwelt_057",q:"How far is Alpha Centauri, in light-years?",a:4,unit:"light-years",hint:"The nearest star system.",emoji:"⭐"},
  {id:"kwelt_058",q:"How many hours does light take from Neptune to Earth?",a:4,unit:"hours",hint:"Hours of light travel time.",emoji:"🔵"},
  {id:"kwelt_059",q:"How fast does Earth rotate at the equator, in km/h?",a:1670,unit:"km/h",hint:"We don't feel it – everything moves with it.",emoji:"🌍"},
  {id:"kwelt_060",q:"How big is Titan (Saturn's moon) in diameter, in km?",a:5150,unit:"km",hint:"Bigger than Mercury.",emoji:"🪐"},
  {id:"kwelt_061",q:"How many rings does Uranus have?",a:13,unit:"rings",hint:"Darker than Saturn's rings.",emoji:"🟦"},
  {id:"kwelt_062",q:"How heavy is 1 m³ of solar core material, in kg?",a:150,unit:"thousand kg",hint:"150x denser than water.",emoji:"☀️"},
  {id:"kwelt_063",q:"How many kg of moon rock did the Apollo missions bring back in total?",a:382,unit:"kg",hint:"From 6 successful landings.",emoji:"🌙"},
  {id:"kwelt_064",q:"How many km tall is Olympus Mons on Mars?",a:21,unit:"km",hint:"The tallest volcano in the solar system.",emoji:"🌋"},
  {id:"kwelt_065",q:"How big is the Andromeda Galaxy in diameter, in light-years?",a:220000,unit:"light-years",hint:"Bigger than the Milky Way.",emoji:"🌌"},
  {id:"kwelt_066",q:"How many hours does a year on Mercury last?",a:1408,unit:"hours",hint:"88 days – the shortest planetary year.",emoji:"☿"},
  {id:"kwelt_067",q:"How many km is Titan's diameter?",a:5150,unit:"km",hint:"The biggest moon of Saturn.",emoji:"🪐"},
  {id:"kwelt_068",q:"How cold is it on Mars at night at the pole, in °C?",a:-125,unit:"°C",hint:"Carbon dioxide ice forms there.",emoji:"🔴"},
  {id:"kwelt_069",q:"How many minutes does light take from the Sun to Mars?",a:13,unit:"minutes",hint:"Depending on distance, 3-22 minutes.",emoji:"🔴"},
  {id:"kwelt_070",q:"How many km long is Valles Marineris on Mars?",a:4000,unit:"km",hint:"10x longer than the Grand Canyon.",emoji:"🔴"},
  {id:"kwelt_071",q:"How big is Europa (Jupiter's moon), in km?",a:3122,unit:"km",hint:"It might have life under the ice.",emoji:"❄️"},
  {id:"kwelt_072",q:"How many hours does a day on Mercury last?",a:1408,unit:"hours",hint:"A Mercury day is longer than a Mercury year!",emoji:"☿"},
  {id:"kwelt_073",q:"How many trillion tons does the Mars atmosphere weigh?",a:25,unit:"trillion tons",hint:"2.5 × 10^16 kg – very thin.",emoji:"🔴"},
  {id:"kwelt_074",q:"How far is the Voyager probe from Earth, in billion km?",a:23,unit:"billion km",hint:"As of 2023 – still increasing.",emoji:"🚀"},
  {id:"kwelt_075",q:"How many km/h does the ISS travel around Earth?",a:28000,unit:"km/h",hint:"One full loop every 90 minutes.",emoji:"🚀"},
  {q:"How big is the diameter of the black hole M87* in km?",a:40000000000,hint:"The first photographed black hole.",unit:"km",emoji:"🌑"},
  {id:"kwelt_076",q:"How cold is it in the permanently shadowed craters on the Moon, in °C?",a:-248,unit:"°C",hint:"Almost absolute zero.",emoji:"🌑"},
  {id:"kwelt_077",q:"How many years does Pluto take to orbit the Sun?",a:248,unit:"Earth years",hint:"A very elliptical orbit.",emoji:"🌑"},
  {id:"kwelt_078",q:"How many km/h is the solar wind?",a:500000,unit:"km/h",hint:"Electrically charged particles.",emoji:"☀️"},
  {id:"kwelt_079",q:"How big is Enceladus (Saturn's moon), in km?",a:500,unit:"km",hint:"Has geysers of liquid water.",emoji:"🪐"},
  {id:"kwelt_080",q:"How many billion light-years across is the observable universe?",a:93,unit:"billion light-years",hint:"The visible part.",emoji:"🌌"},
  {id:"kwelt_081",q:"How deep is the ocean on Enceladus, in km?",a:10,unit:"km",hint:"Under 40km-thick ice.",emoji:"❄️"},
  {id:"kwelt_082",q:"How many hours does light take from Pluto to Earth?",a:5.5,unit:"hours",hint:"5.5 hours of light travel.",emoji:"🌑"},
  {id:"kwelt_083",q:"How big is the temperature difference between day and night on the Moon, in °C?",a:300,unit:"°C",hint:"+130°C during the day, -170°C at night.",emoji:"🌙"},
  {id:"kwelt_084",q:"How big is the Hubble Telescope, in meters?",a:13,unit:"meters",hint:"As big as a school bus.",emoji:"🔭"},
  {id:"kwelt_085",q:"How many astronauts have been on the ISS at the same time at maximum?",a:13,unit:"astronauts",hint:"During the STS-127 mission in 2009.",emoji:"👨‍🚀"},
  {id:"kwelt_086",q:"How long does a spaceflight from Earth to the ISS take, in hours?",a:6,unit:"hours",hint:"Modern Soyuz capsules make it in 6h.",emoji:"🚀"},
  {id:"kwelt_087",q:"How many shooting stars per hour are visible during a normal meteor shower?",a:10,unit:"per hour",hint:"During a stronger shower, up to 100.",emoji:"💫"},
  {id:"kwelt_088",q:"How many km is the diameter of Io (Jupiter's moon)?",a:3642,unit:"km",hint:"The most volcanic body in the solar system.",emoji:"🌋"},
  {id:"kwelt_089",q:"How big was the Chicxulub asteroid that wiped out the dinosaurs, in km?",a:10,unit:"km",hint:"Hit Mexico 66 million years ago.",emoji:"☄️"},
  {id:"kwelt_090",q:"How many degrees Celsius is the temperature in a white dwarf?",a:100000,unit:"°C",hint:"A dead star – cools over billions of years.",emoji:"⭐"},
  {id:"kwelt_091",q:"How long does a spaceflight to Mars take, in months?",a:9,unit:"months",hint:"At the most favorable launch window.",emoji:"🔴"},
  {id:"kwelt_092",q:"How big is the Sun compared to the Moon (diameter)?",a:400,unit:"x bigger",hint:"But the Moon is many times closer – hence they appear the same size in the sky.",emoji:"☀️"},
  {id:"kwelt_093",q:"How many planets have been discovered outside our solar system?",a:5500,unit:"exoplanets",hint:"As of 2023 – new ones found daily.",emoji:"🌍"},
  {id:"kwelt_094",q:"How heavy is the Moon compared to Earth, in %?",a:1.2,unit:"% of Earth's mass",hint:"The Moon is 1.2% as heavy as Earth.",emoji:"🌙"},
  {id:"kwelt_095",q:"How many million km long can a comet's tail be?",a:150,unit:"million km",hint:"Comet tails can be as long as the Earth-Sun distance.",emoji:"☄️"},
  {id:"kwelt_096",q:"How fast does Jupiter rotate at its equator, in km/h?",a:45000,unit:"km/h",hint:"The fastest planetary rotation.",emoji:"🪐"},
  {id:"kwelt_097",q:"How long does a day on Neptune last, in hours?",a:16,unit:"hours",hint:"A shorter day than Earth's.",emoji:"🔵"},
  {id:"kwelt_098",q:"How far is the center of the Milky Way from us, in light-years?",a:26000,unit:"light-years",hint:"Sagittarius A* – a black hole.",emoji:"🌌"},
  {id:"kwelt_099",q:"How big is Ganymede (Jupiter's moon) compared to Mercury?",a:108,unit:"% bigger",hint:"Ganymede is bigger than Mercury!",emoji:"🪐"},
  {id:"kwelt_100",q:"How many km/s is the Sun's escape velocity?",a:617,unit:"km/s",hint:"Km/s – almost 0.2% of the speed of light.",emoji:"☀️"},
  {id:"kwelt_101",q:"How cold is it on Neptune, in °C?",a:-214,unit:"°C",hint:"The coldest planet in the solar system.",emoji:"🔵"},
  {id:"kwelt_102",q:"How many moons did Galileo Galilei discover at Jupiter?",a:4,unit:"moons",hint:"Io, Europa, Ganymede, Callisto.",emoji:"🔭"},
  {id:"kwelt_103",q:"How big is the radius of Saturn's main ring, in km?",a:280,unit:"thousand km",hint:"The rings extend up to 280,000 km from the center.",emoji:"🪐"},
  {id:"kwelt_104",q:"How many degrees Celsius is Mercury during the day?",a:430,unit:"°C",hint:"At night -180°C – the most extreme temperature swing.",emoji:"☿"},
  {id:"kwelt_105",q:"How many hours does a year on Venus last?",a:5392,unit:"hours",hint:"225 Earth days – and a day is even longer!",emoji:"🌋"},
  {id:"kwelt_106",q:"How many trillion tons does the asteroid Ceres weigh?",a:9390,unit:"billion tons",hint:"9.4 × 10^20 kg – the biggest asteroid.",emoji:"☄️"},
  {id:"kwelt_107",q:"How fast does Saturn rotate at its equator, in km/h?",a:35500,unit:"km/h",hint:"The second-fastest rotation after Jupiter.",emoji:"🪐"},
  {id:"kwelt_108",q:"How long does a solar storm take to reach Earth, in hours?",a:48,unit:"hours",hint:"Coronal mass ejections: 1-3 days.",emoji:"☀️"},
  {id:"kwelt_109",q:"How big is Olympus Mons compared to Everest?",a:2.5,unit:"x taller",hint:"21km vs 8.8km – 2.5x as tall.",emoji:"🌋"},
  {id:"kwelt_110",q:"How many billion years old is the Sun?",a:4.6,unit:"billion years",hint:"And has 5 billion years left.",emoji:"☀️"},
  {id:"kwelt_111",q:"How many km from Earth does Earth's magnetism end?",a:65000,unit:"km",hint:"The magnetosphere protects us up to 65,000 km.",emoji:"🌍"},
  {id:"kwelt_112",q:"How cold is the atmosphere on Uranus, in °C?",a:-224,unit:"°C",hint:"The coldest atmospheric temperature of any planet.",emoji:"🟦"},
  {id:"kwelt_113",q:"How many seconds does light take from Earth to the Moon?",a:1.3,unit:"seconds",hint:"Only 1.3 seconds – the Moon is very close.",emoji:"🌙"},
  {id:"kwelt_114",q:"How big is a neutron star in diameter, in km?",a:20,unit:"km",hint:"As small as a city – but unimaginably heavy.",emoji:"⭐"},
  {id:"kwelt_115",q:"How many km/s does the Sun rotate at its equator?",a:2,unit:"km/s",hint:"7200 km/h – differential rotation.",emoji:"☀️"},
  {id:"kwelt_116",q:"How long did the longest space mission last?",a:437,unit:"days",hint:"Valeri Polyakov on the Mir station (as of ~2024).",emoji:"🚀"},
  {id:"kwelt_117",q:"How many hours does a year on Jupiter last?",a:87672,unit:"hours",hint:"12 Earth years.",emoji:"🪐"},
  {id:"kwelt_118",q:"How big is Pluto's biggest moon, Charon, compared to Pluto?",a:52,unit:"% of Pluto's size",hint:"Charon is huge compared to Pluto (as of ~2024).",emoji:"🌑"},
  {id:"kwelt_119",q:"How many km/h do interstellar objects like Oumuamua fly?",a:85000,unit:"km/h",hint:"The first interstellar object detected in our system.",emoji:"☄️"},
  {id:"kwelt_120",q:"How many planets does TRAPPIST-1 have?",a:7,unit:"planets",hint:"Earth-like – 3 in the habitable zone.",emoji:"🌍"},
  {id:"kwelt_121",q:"How long does a day on Titan (Saturn's moon) last?",a:382,unit:"hours",hint:"15.9 Earth days.",emoji:"🪐"},
  {id:"kwelt_122",q:"How big is Earth's magnetosphere, in Earth radii?",a:10,unit:"Earth radii",hint:"On the day side – the night side is much bigger.",emoji:"🌍"},
  {id:"kwelt_123",q:"How many billion km is Voyager 1 from Earth (2023)?",a:23,unit:"billion km",hint:"The most distant human-made object.",emoji:"🚀"},
  {id:"kwelt_124",q:"How cold is the darkest known place in the universe (Boomerang Nebula)?",a:-272,unit:"°C",hint:"Colder than the cosmic microwave background.",emoji:"❄️"},
  {id:"kwelt_125",q:"How many hours did Apollo astronauts spend on the Moon in total?",a:80,unit:"hours",hint:"Across all 6 missions.",emoji:"🌙"},
  {id:"kwelt_126",q:"How big is Callisto (Jupiter's moon), in km?",a:4820,unit:"km",hint:"Almost as big as Mercury.",emoji:"🪐"},
  {id:"kwelt_127",q:"How many hours does one ISS orbit of Earth take?",a:1.5,unit:"hours",hint:"90 minutes – 16 sunrises daily.",emoji:"🚀"},
  {id:"kwelt_128",q:"How long is a solar cycle, in years?",a:11,unit:"years",hint:"From solar minimum to solar minimum.",emoji:"☀️"},
  {id:"kwelt_129",q:"How big is the Kuiper Belt's diameter, in AU?",a:50,unit:"astronomical units",hint:"30-50 AU from the Sun.",emoji:"☄️"},
  {id:"kwelt_130",q:"How many degrees Celsius is Venus's surface?",a:465,unit:"°C",hint:"Hotter than Mercury despite being farther away.",emoji:"🌋"},
  {id:"kwelt_131",q:"How many thousand years after the Big Bang did the first atoms form?",a:380,unit:"thousand years",hint:"380,000 years after the Big Bang.",emoji:"⚛️"},
  {id:"kwelt_132",q:"How big is the solar system out to the Oort Cloud, in light-years?",a:2,unit:"light-years",hint:"Light-years in diameter.",emoji:"☄️"},
  {id:"kwelt_133",q:"How many astronauts have seen Earth from space?",a:600,unit:"astronauts",hint:"As of 2023 – from over 40 countries.",emoji:"👨‍🚀"},
  {id:"kwelt_134",q:"How long does a solar eclipse last at maximum, in minutes?",a:7.5,unit:"minutes",hint:"A total solar eclipse, maximum 7.5 minutes.",emoji:"🌑"},
  {id:"kwelt_135",q:"How big is Jupiter's moon Ganymede, in km?",a:5268,unit:"km",hint:"The biggest moon in the solar system.",emoji:"🪐"},
  {id:"kwelt_136",q:"How many km/h is the maximum wind speed on Neptune?",a:2100,unit:"km/h",hint:"The strongest known winds in the solar system.",emoji:"🌀"},
  {id:"kwelt_137",q:"How long until the Sun becomes a red giant, in billion years?",a:5,unit:"billion years",hint:"Then it will swallow Earth.",emoji:"☀️"},
  {id:"kwelt_138",q:"How far apart are stars in the Milky Way, in light-years?",a:5,unit:"light-years",hint:"On average 5 light-years between stars.",emoji:"⭐"},
  {id:"kwelt_139",q:"How many moons does Saturn have (as of 2023)?",a:146,unit:"moons",hint:"More than any other planet.",emoji:"🪐"},
  {id:"kwelt_140",q:"How big is the Sun compared to a red giant star?",a:100,unit:"x smaller",hint:"Red giants can be many times bigger.",emoji:"⭐"},
  {id:"kwelt_141",q:"How many hours does a day on Pluto last?",a:153,unit:"hours",hint:"6 Earth days.",emoji:"🌑"},
  {id:"kwelt_142",q:"How long is a solar year exactly, in days?",a:365.25,unit:"days",hint:"That's why there's a leap day every 4 years.",emoji:"📅"},
  {id:"kwelt_143",q:"How big is the Milky Way, in light-years?",a:100000,unit:"light-years",hint:"100,000 light-years in diameter.",emoji:"🌌"},
  {id:"kwelt_144",q:"How cold is space between galaxies?",a:-270,unit:"°C",hint:"Almost absolute zero.",emoji:"❄️"},
  {id:"kwelt_145",q:"How many rings does Neptune have?",a:5,unit:"rings",hint:"Darker and thinner than Saturn's.",emoji:"🔵"},
  {id:"kwelt_146",q:"How many km thick is the Moon at its equator?",a:3474,unit:"km",hint:"The Moon's diameter at the equator.",emoji:"🌙"},
  {id:"kwelt_147",q:"How big is the red supergiant Betelgeuse, in solar radii?",a:700,unit:"solar radii",hint:"Many times bigger than our Sun.",emoji:"⭐"},
  {id:"kwelt_148",q:"How many hours does a full moon cycle last?",a:709,unit:"hours",hint:"29.5 days from full moon to full moon.",emoji:"🌕"},
  {id:"kwelt_149",q:"How big is the heliosphere in diameter, in AU?",a:200,unit:"AU",hint:"Astronomical units.",emoji:"☀️"},
  {id:"kwelt_150",q:"How many months does a year on Jupiter last?",a:144,unit:"months",hint:"12 Earth years – 144 Earth months.",emoji:"🪐"},
  {id:"kwelt_151",q:"How many degrees Celsius is Neptune's surface?",a:-214,unit:"°C",hint:"The coldest planet in the solar system.",emoji:"🔵"},
  {id:"kwelt_152",q:"How far is the nearest star, Alpha Centauri?",a:4,unit:"light-years",hint:"The nearest star system.",emoji:"⭐"},
  {id:"kwelt_153",q:"How many km high is the ISS space station?",a:400,unit:"km",hint:"In Earth orbit.",emoji:"🚀"},
  {id:"kwelt_154",q:"How big is the Red Spot on Jupiter, in km?",a:16000,unit:"km",hint:"A storm raging for 350 years.",emoji:"🪐"},
  {id:"kwelt_155",q:"How many moons does Jupiter have?",a:95,unit:"moons",hint:"Jupiter has the most moons – as of 2023.",emoji:"🪐"},
  {id:"kwelt_156",q:"How long does a day on Mercury last, in Earth days?",a:59,unit:"Earth days",hint:"Very slow self-rotation.",emoji:"☿"},
  {id:"kwelt_157",q:"How far is Uranus from the Sun, in billion km?",a:2.9,unit:"billion km",hint:"7x farther than Earth.",emoji:"🟦"},
  {id:"kwelt_158",q:"How many degrees Celsius cold is it on Pluto?",a:-230,unit:"°C",hint:"One of the coldest places in the solar system.",emoji:"🌑"},
  {id:"kwelt_159",q:"How many km/h does a comet move?",a:100000,unit:"km/h",hint:"Comets race through space.",emoji:"☄️"},
  {id:"kwelt_160",q:"How many stars can you see with the naked eye?",a:5000,unit:"stars",hint:"On a clear night.",emoji:"⭐"},
  {id:"kwelt_161",q:"How many years does Uranus take to orbit?",a:84,unit:"years",hint:"Earth years per Uranus year.",emoji:"🟦"},
  {id:"kwelt_162",q:"How big is the Moon compared to Earth, in %?",a:27,unit:"% Earth's diameter",hint:"About a quarter the size.",emoji:"🌙"},
  {id:"kwelt_163",q:"How many volcanoes does Mars have?",a:43000,unit:"volcanoes",hint:"Including the biggest volcano in the solar system.",emoji:"🔴"},
  {id:"kwelt_164",q:"How many degrees Celsius is Venus at night?",a:465,unit:"°C",hint:"Day and night are almost equally hot.",emoji:"🌋"},
  {id:"kwelt_165",q:"How long is Valles Marineris on Mars, in km?",a:4000,unit:"km",hint:"10x longer than the Grand Canyon.",emoji:"🔴"},
  {id:"kwelt_166",q:"How many months does a year on Saturn last?",a:354,unit:"months",hint:"29.5 Earth years.",emoji:"🪐"},
  {id:"kwelt_167",q:"How many hours does a day on Neptune last?",a:16,unit:"hours",hint:"Fast rotation.",emoji:"🔵"},
  {id:"kwelt_168",q:"How far is Neptune from the Sun, in billion km?",a:4.5,unit:"billion km",hint:"Light takes 4 hours.",emoji:"🔵"},
  {id:"kwelt_169",q:"How many minutes does light take from Saturn to Earth?",a:75,unit:"minutes",hint:"Varies depending on position.",emoji:"🪐"},
  {id:"kwelt_170",q:"How heavy is an astronaut on the Moon compared to Earth?",a:17,unit:"% of Earth weight",hint:"60kg on Earth is only 10kg on the Moon.",emoji:"🌙"},
  {id:"kwelt_171",q:"How high is Olympus Mons on Mars?",a:22,unit:"km",hint:"3x taller than Everest.",emoji:"🔴"},
  {id:"kwelt_172",q:"How long does one moon orbit around Earth take?",a:27,unit:"days",hint:"About 27 days.",emoji:"🌙"},
  {id:"kwelt_173",q:"How many degrees does Earth rotate daily?",a:15,unit:"degrees per hour",hint:"360° in 24 hours = 15°/h.",emoji:"🌍"},
  {id:"kwelt_174",q:"How many km big is the Moon in diameter?",a:3474,unit:"km",hint:"About as wide as Australia.",emoji:"🌙"},
  {id:"kwelt_175",q:"How many hours does a flight to the ISS take?",a:6,unit:"hours",hint:"With the Soyuz capsule.",emoji:"🚀"},
  {id:"kwelt_176",q:"How many kg does the ISS weigh?",a:420,unit:"thousand kg",hint:"420 tons – as heavy as 320 cars.",emoji:"🚀"},
  {id:"kwelt_177",q:"How long does a solar flare take to reach Earth, in hours?",a:8,unit:"minutes of light",hint:"Light takes 8 minutes – particles 1-3 days.",emoji:"☀️"},
  {id:"kwelt_178",q:"How many moons does Uranus have?",a:27,unit:"moons",hint:"All named after Shakespeare characters.",emoji:"🟦"},
  {id:"kwelt_179",q:"How many kilograms of moon rock did Apollo missions bring back?",a:382,unit:"kg",hint:"Kg across all missions.",emoji:"🌙"},
  {id:"kwelt_180",q:"How long is a solar day (rotation) on Venus?",a:243,unit:"Earth days",hint:"A Venus day lasts longer than a Venus year.",emoji:"🌋"},
  {id:"kwelt_181",q:"How many km/h is the solar wind?",a:500000,unit:"km/h",hint:"Electrically charged particles from the Sun.",emoji:"☀️"},
  {id:"kwelt_182",q:"How many constellations are there in the sky?",a:88,unit:"constellations",hint:"Officially recognized by the IAU.",emoji:"⭐"},
  {id:"kwelt_183",q:"How wide is the Milky Way?",a:100000,unit:"light-years",hint:"100,000 light-years in diameter.",emoji:"🌌"},
  {id:"kwelt_184",q:"How many kilometers is the Sun's diameter?",a:1.39,unit:"million km",hint:"109x bigger than Earth.",emoji:"☀️"},
  {id:"kwelt_185",q:"How many hours of sunlight does the North Pole get daily in summer?",a:24,unit:"hours",hint:"Midnight sun – the sun never sets.",emoji:"☀️"},
  {id:"kwelt_186",q:"How many minutes does light take from Neptune to Earth?",a:240,unit:"minutes",hint:"4 hours of light travel.",emoji:"🔵"},
  {id:"kwelt_187",q:"How many months does a mission to the ISS last?",a:6,unit:"months",hint:"Astronauts typically stay 6 months.",emoji:"🚀"},
  {id:"kwelt_188",q:"How heavy is a spacesuit, in kg?",a:130,unit:"kg",hint:"An EMU spacesuit on the ISS.",emoji:"👨‍🚀"},
  {id:"kwelt_189",q:"How many km² is the Moon's surface?",a:37.9,unit:"million km²",hint:"Almost as big as Russia.",emoji:"🌙"},
  {id:"kwelt_190",q:"How many degrees Celsius is Jupiter's core?",a:36000,unit:"°C",hint:"An extremely hot core beneath the gas.",emoji:"🪐"},
  {id:"kwelt_191",q:"How long does a light signal take from Earth to Mars, in minutes?",a:12,unit:"minutes",hint:"Depending on distance, 3-22 minutes.",emoji:"🔴"},
  {id:"kwelt_192",q:"How many planets are smaller than Earth?",a:2,unit:"planets",hint:"Mercury and Mars are smaller.",emoji:"🪐"},
  {id:"kwelt_193",q:"How many km/h is the ISS's orbital speed?",a:28000,unit:"km/h",hint:"Once around Earth every 90 minutes.",emoji:"🚀"},
  {id:"kwelt_194",q:"How many billion stars does the Milky Way have approximately?",a:200,unit:"billion stars",hint:"200 billion.",emoji:"⭐"},
  {id:"kwelt_195",q:"How many billion years old is the universe?",a:13.8,unit:"billion years",hint:"13.8 billion years since the Big Bang.",emoji:"🌌"},
  {id:"kwelt_196",q:"How high is the Kármán line – the boundary to space – in km?",a:100,unit:"km",hint:"Space officially begins here.",emoji:"🚀"},
  {id:"kwelt_197",q:"How many planets in our solar system are bigger than Earth?",a:4,unit:"planets",hint:"Jupiter, Saturn, Uranus, Neptune.",emoji:"🪐"},
  {id:"kwelt_198",q:"How many km/h does the New Horizons probe fly?",a:58536,unit:"km/h",hint:"The fastest human-made probe.",emoji:"🚀"},
  {id:"kwelt_199",q:"How many days does a year on Mercury last, in Earth days?",a:88,unit:"days",hint:"Only 88 Earth days.",emoji:"☿"},
  {id:"kwelt_200",q:"How many billion km away is Voyager 1 from Earth?",a:23,unit:"billion km",hint:"The most distant human-made probe.",emoji:"🚀"},
  {id:"kwelt_201",q:"How many comets have been discovered in the solar system?",a:4000,unit:"comets",hint:"And there are still millions unknown.",emoji:"☄️"},
  {id:"kwelt_202",q:"How many asteroids have a diameter over 100km?",a:200,unit:"asteroids",hint:"In the asteroid belt.",emoji:"☄️"},
  {id:"kwelt_203",q:"How many spacewalks does an astronaut do on the ISS per mission?",a:3,unit:"spacewalks",hint:"Average 2-5 per mission.",emoji:"👨‍🚀"},
  {id:"kwelt_204",q:"How many million km away is the Sun from us?",a:150,unit:"million km",hint:"150 million km = 1 AU.",emoji:"☀️"},
  {id:"kwelt_205",q:"How big is Titan (Saturn's moon) compared to Earth, in %?",a:40,unit:"% Earth's diameter",hint:"Bigger than Mercury.",emoji:"🪐"},
  {id:"kwelt_206",q:"How many hours does it take from moonrise to moonset?",a:12,unit:"hours",hint:"Similar to the sun – but it varies.",emoji:"🌙"},
  {id:"kwelt_207",q:"How many meteorites fall on Earth daily?",a:50,unit:"tons",hint:"Tons of meteorite dust daily.",emoji:"☄️"},
  {id:"kwelt_208",q:"How many km/h does Earth rotate at the equator?",a:1670,unit:"km/h",hint:"We don't notice it.",emoji:"🌍"},
  {id:"kwelt_209",q:"How many stars can you see with a telescope?",a:50000,unit:"stars",hint:"Significantly more than with the naked eye.",emoji:"🔭"},
  {id:"kwelt_210",q:"How long is the equinox season on the planet Uranus, in years?",a:21,unit:"Earth years",hint:"Each season lasts this many years.",emoji:"🟦"},
  {id:"kwelt_211",q:"How many minutes does light take from Jupiter to Earth?",a:43,unit:"minutes",hint:"Varies with distance.",emoji:"🪐"},
  {id:"kwelt_212",q:"How many g-forces act on astronauts during a rocket launch?",a:3,unit:"g",hint:"Three times their body weight.",emoji:"🚀"},
  {id:"kwelt_213",q:"How many planets orbit other stars (exoplanets)?",a:5500,unit:"exoplanets",hint:"As of 2024 – constantly increasing.",emoji:"🌌"},
  {id:"kwelt_214",q:"How many million solar masses does the black hole at the center of the Milky Way have?",a:4,unit:"million solar masses",hint:"Sagittarius A* – 4 million solar masses.",emoji:"🌑"},
  {id:"kwelt_215",q:"How many hours does a year on Venus last?",a:5392,unit:"hours",hint:"225 Earth days – shorter than a Venus day.",emoji:"🌋"},
  {id:"kwelt_216",q:"How long did it take Voyager 1 to reach the edge of the solar system?",a:35,unit:"years",hint:"Launched 1977, reached the heliopause in 2012.",emoji:"🚀"},
  {id:"kwelt_217",q:"How many km is Earth's equator long?",a:40075,unit:"km",hint:"Earth's circumference at the equator.",emoji:"🌍"},
  {id:"kwelt_218",q:"How many shooting stars do you see on average per hour?",a:10,unit:"shooting stars",hint:"On a normal night.",emoji:"🌠"},
  {id:"kwelt_219",q:"How far is Neptune from Earth on average, in billion km?",a:4.4,unit:"billion km",hint:"The outermost planet.",emoji:"🔵"},
  {id:"kwelt_220",q:"How many degrees Celsius is the maximum daytime temperature on Mars?",a:20,unit:"°C",hint:"Only at the equator in summer.",emoji:"🔴"},
  {id:"kwelt_221",q:"How many million kilometers away is the asteroid belt from the Sun?",a:400,unit:"million km",hint:"Between Mars and Jupiter.",emoji:"☄️"},
  {id:"kwelt_222",q:"How many hours does a solar day on the Moon last?",a:708,unit:"hours",hint:"29.5 Earth days – the lunar day is long.",emoji:"🌙"},
  {id:"kwelt_223",q:"How many meters wide is the ISS's solar panel?",a:109,unit:"meters",hint:"As wide as a soccer field.",emoji:"🚀"},
  {id:"kwelt_224",q:"How many km high is Earth's atmosphere?",a:10000,unit:"km",hint:"The dense troposphere only reaches 12km.",emoji:"🌍"},
  {id:"kwelt_225",q:"How many times does the ISS orbit Earth per day?",a:16,unit:"times",hint:"One loop every 90 minutes.",emoji:"🚀"},
  {id:"kwelt_226",q:"How many minutes does light take from Mercury to Earth?",a:4,unit:"minutes",hint:"Mercury is closer than most planets.",emoji:"☿"},
  {id:"kwelt_227",q:"How many years does Neptune take to orbit?",a:165,unit:"years",hint:"Earth years.",emoji:"🔵"},
  {id:"kwelt_228",q:"How many billion km is Saturn from the Sun?",a:1.4,unit:"billion km",hint:"Almost 10x farther than Earth.",emoji:"🪐"},
  {id:"kwelt_229",q:"How many km is the diameter of the Great Red Spot on Jupiter?",a:16000,unit:"km",hint:"Bigger than Earth.",emoji:"🪐"},
  {id:"kwelt_230",q:"How long does the trip with a rocket to Mars take, in months?",a:7,unit:"months",hint:"With today's technology, about 7 months.",emoji:"🔴"},
  {id:"kwelt_231",q:"How fast does Jupiter rotate at its equator, in km/h?",a:45000,unit:"km/h",hint:"The fastest rotation of any planet.",emoji:"🪐"},
  {id:"kwelt_232",q:"How many g does an astronaut weigh on the Moon?",a:16.7,unit:"% of Earth weight",hint:"A 60kg person weighs 10kg on the Moon.",emoji:"🌙"},
  {id:"kwelt_233",q:"How many space tourists have already seen Earth from above?",a:600,unit:"people",hint:"Including astronauts – about 600 as of 2024.",emoji:"🚀"},
  {id:"kwelt_234",q:"How many km big is the crater on the Moon (Clavius)?",a:231,unit:"km",hint:"One of the biggest moon craters.",emoji:"🌙"},
  {id:"kwelt_235",q:"How many shooting stars rain down during a meteor shower per hour?",a:100,unit:"shooting stars",hint:"At peak, even more.",emoji:"🌠"},
  {id:"kwelt_236",q:"How many years has the ISS existed?",a:25,unit:"years",hint:"Under construction since 1998 – first crew in 2000.",emoji:"🚀"},
  {id:"kwelt_237",q:"How many billion solar systems could the Milky Way have?",a:100,unit:"billion",hint:"Potentially hundreds of billions.",emoji:"🌌"},
  {id:"kwelt_238",q:"How many meters is the size of the smallest known asteroids?",a:1,unit:"meter",hint:"Micro-asteroids – barely detectable.",emoji:"☄️"},
  {id:"kwelt_239",q:"How many hours of daylight does Mercury get?",a:4224,unit:"hours",hint:"176 Earth days of daylight.",emoji:"☿"},
];
