// 🌍 GEOGRAPHY – English
export default [
  {q:"How high is der Mount Everest in meters?",a:8849,unit:"meterss",hint:"Der höchste mountain Earth, im Hitimesaya.",emoji:"🏔️"},
  {q:"How long is der Nil in km?",a:6650,unit:"km",hint:"Er is the longest river the world.",emoji:"🌊"},
  {q:"How many countries are there on Earth?",a:195,unit:"countries",hint:"Davon are 193 Mitglieder der UNO.",emoji:"🌍"},
  {q:"How big is Russland in million km²?",a:17,unit:"million km²",hint:"the largest country the world.",emoji:"🗺️"},
  {q:"How deep is der Marianengraben in meters?",a:11000,unit:"meterss",hint:"Der tiefste Punkt the worldmeere.",emoji:"🌊"},
  {q:"How many km long is der Amazonas?",a:6400,unit:"km",hint:"Der wasserreichste river the world.",emoji:"🌿"},
  {q:"How high liegt die capital Boliviens (La Paz) in meters?",a:3600,unit:"meterss",hint:"Eine der höchstgelegenen Hauptstädte the world.",emoji:"🏙️"},
  {q:"How many km² has die Sahara?",a:9200000,unit:"km²",hint:"the largest desert the world.",emoji:"🏜️"},
  {q:"How deep is der Baikalsee in meters?",a:1642,unit:"meterss",hint:"Der tiefste lake the world, in Russland.",emoji:"💧"},
  {q:"How many km² has Deutschland?",a:357000,unit:"km²",hint:"Das flächengrößte country in Mitteleuropa.",emoji:"🇩🇪"},
  {q:"How high is der Kilimandscharo in meters?",a:5895,unit:"meterss",hint:"Der höchste mountain Afrikas.",emoji:"🏔️"},
  {q:"How long is die Chinesische Mauer in km?",a:21000,unit:"km",hint:"the longest Bauwerk humansheitsgeschichte.",emoji:"🧱"},
  {q:"How many Einwohner has China (billion)?",a:1400,unit:"million",hint:"Das bevölkerungsreichste country Earth.",emoji:"🇨🇳"},
  {q:"How high is der Eiffelturm in meters?",a:330,unit:"meterss",hint:"Inklusive Antenne steht er in Paris.",emoji:"🗼"},
  {q:"How many Einwohner has die Erde (billion)?",a:8,unit:"billion",hint:"2022 überschritt die Weltbevölkerung 8 billion.",emoji:"🌍"},
  {q:"How long is der Rhein in km?",a:1230,unit:"km",hint:"Er fließt through die Schweiz, Deutschland und die Niederlande.",emoji:"🌊"},
  {q:"How many km² has Australien?",a:7700000,unit:"km²",hint:"Der sechstgrößte Staat Earth.",emoji:"🦘"},
  {q:"How high fly Flugzeuge on average in meters?",a:10000,unit:"meterss",hint:"Die Reiseflughöhe liegt at 9.000–12.000 meters.",emoji:"✈️"},
  {q:"How long is die Elbe in km?",a:1091,unit:"km",hint:"Sie fließt of Tschechien through Deutschland.",emoji:"🌊"},
  {q:"How many countries grenzen an Deutschland?",a:9,unit:"countries",hint:"Dänemark, Polen, Tschechien, Österreich, Schweiz, Frankreich, Luxemburg, Belgien, Niederlande.",emoji:"🇩🇪"},
  {q:"How many Inseln has Indonesien?",a:17000,unit:"Inseln",hint:"Der viertbevölkerungsreichste Staat the world.",emoji:"🏝️"},
  {q:"How high is die Zugspitze in meters?",a:2962,unit:"meterss",hint:"Der höchste mountain Deutschlands in Bayern.",emoji:"🏔️"},
  {q:"How many km is der Äquator lang?",a:40075,unit:"km",hint:"Der Umfang Earth am Breitendegrees 0°.",emoji:"🌍"},
  {q:"How many km² is der Schwaszwhaled groß?",a:6000,unit:"km²",hint:"the largest zusammenhängende whaledgebirge Deutschlands.",emoji:"🌲"},
  {q:"How deep is der Genfer lake in meters?",a:310,unit:"meterss",hint:"the largest lake Mitteleuropas.",emoji:"💧"},
  {q:"How many km² is der Amazonas-Regenwhaled groß?",a:5500000,unit:"km²",hint:"the largest tropische Regenwhaledregion Earth.",emoji:"🌴"},
  {q:"How long is die Küstenlinie Kanadas in km?",a:202080,unit:"km",hint:"the longest Küstenlinie aller countries.",emoji:"🍁"},
  {q:"How high is der Fuji in Japan in meters?",a:3776,unit:"meterss",hint:"Der heilige mountain Japans is a Vulkan.",emoji:"🗻"},
  {q:"How many km² is Grönland groß?",a:2166086,unit:"km²",hint:"the largest Insel the world.",emoji:"🧊"},
  {q:"How long is der Mississippi in km?",a:3730,unit:"km",hint:"the longest river Nordamerikas zusammen with dem Missouri.",emoji:"🌊"},
  {q:"How long is der Amazonas in km?",a:6400,unit:"km",hint:"Der wasserreichste river the world.",emoji:"🌿"},
  {q:"How high is der Kilimandscharo in meters?",a:5895,unit:"meterss",hint:"Der höchste mountain Afrikas.",emoji:"🏔️"},
  {q:"How many countries has Afrika?",a:54,unit:"countries",hint:"Der continent with den meisen countriesn.",emoji:"🌍"},
  {q:"How long is die Chinesische Mauer in km?",a:21000,unit:"km",hint:"the longest Bauwerk humansheitsgeschichte.",emoji:"🧱"},
  {q:"How deep is der Baikalsee in meters?",a:1642,unit:"meterss",hint:"Der tiefste lake the world.",emoji:"💧"},
  {q:"How many km² has Deutschland?",a:357000,unit:"km²",hint:"Das flächengrößte country in Mitteleuropa.",emoji:"🇩🇪"},
  {q:"How high is der Eiffelturm in meters?",a:330,unit:"meterss",hint:"Inklusive Antenne in Paris.",emoji:"🗼"},
  {q:"How many Einwohner has China in billion?",a:1400,unit:"million",hint:"Das bevölkerungsreichste country.",emoji:"🇨🇳"},
  {q:"How many km is der Äquator lang?",a:40075,unit:"km",hint:"Umfang Earth am Breitendegrees 0°.",emoji:"🌍"},
  {q:"How big is Australien in km²?",a:7700000,unit:"km²",hint:"Der sechstgrößte Staat Earth.",emoji:"🦘"},
  {q:"How long is der Rhein in km?",a:1230,unit:"km",hint:"Fließt through die Schweiz, Deutschland, Niederlande.",emoji:"🌊"},
  {q:"How many countries grenzen an Deutschland?",a:9,unit:"countries",hint:"Dänemark, Polen, Tschechien, Österreich, Schweiz, Frankreich, Luxemburg, Belgien, Niederlande.",emoji:"🇩🇪"},
  {q:"How high is die Zugspitze in meters?",a:2962,unit:"meterss",hint:"Der höchste mountain Deutschlands.",emoji:"🏔️"},
  {q:"How many Inseln has Indonesien?",a:17000,unit:"Inseln",hint:"Der viertbevölkerungsreichste Staat.",emoji:"🏝️"},
  {q:"How many km² is die Sahara groß?",a:9200000,unit:"km²",hint:"the largest desert the world.",emoji:"🏜️"},
  {q:"How long is die Elbe in km?",a:1091,unit:"km",hint:"Fließt of Tschechien through Deutschland.",emoji:"🌊"},
  {q:"How many Einwohner has die Erde in billion?",a:8,unit:"billion",hint:"2022 wasn 8 billion überschritten.",emoji:"🌍"},
  {q:"How deep is der Genfer lake in meters?",a:310,unit:"meterss",hint:"the largest lake Mitteleuropas.",emoji:"💧"},
  {q:"How high is der Fuji in Japan in meters?",a:3776,unit:"meterss",hint:"Der heilige mountain Japans is a Vulkan.",emoji:"🗻"},
  {q:"How long is der Mississippi in km?",a:3730,unit:"km",hint:"the longest river Nordamerikas.",emoji:"🌊"},
  {q:"How big is Grönland in km²?",a:2166086,unit:"km²",hint:"the largest Insel the world.",emoji:"🧊"},
  {q:"How high is die Statue of Liberty in New York in meters?",a:93,unit:"meterss",hint:"Inklusive Sockel und Fackel.",emoji:"🗽"},
  {q:"How many km long is der Grand Canyon?",a:446,unit:"km",hint:"the largest Canyon-System der USA.",emoji:"🏜️"},
  {q:"How many countries are in der EU?",a:27,unit:"countries",hint:"to dem Brexit.",emoji:"🇪🇺"},
  {q:"How deep is der tiefste lake der USA (Crater Lake) in meters?",a:594,unit:"meterss",hint:"in Oregon – entstand through einen Vulkan.",emoji:"💧"},
  {q:"How big is die Antarktis in km²?",a:14000000,unit:"km²",hint:"Das fünftgrößte Territorium Earth.",emoji:"🧊"},
  {q:"How long is die Donau in km?",a:2860,unit:"km",hint:"Fließt through 10 countries.",emoji:"🌊"},
  {q:"How many km² is der Amazonas-Regenwhaled groß?",a:5500000,unit:"km²",hint:"the largest tropische Regenwhaledregion.",emoji:"🌴"},
  {q:"How high liegt Mexiko-city in meters?",a:2240,unit:"meterss",hint:"Eine der höchstgelegenen Hauptstädte.",emoji:"🏙️"},
  {q:"How many km long is die Küstenlinie Australiens?",a:25760,unit:"km",hint:"Sehr langer Küstenstreifen.",emoji:"🏖️"},
  {q:"How big is Russland in million km²?",a:17,unit:"million km²",hint:"the largest country the world.",emoji:"🗺️"},
  {q:"How high is der Olymp in Griechenland in meters?",a:2917,unit:"meterss",hint:"Der höchste mountain Griechenlands – Göttersitz.",emoji:"🏔️"},
  {q:"How many countries has Südamerika?",a:12,unit:"countries",hint:"of Kolumbien bis Argentinien.",emoji:"🌎"},
  {q:"How long is der Niger in km?",a:4180,unit:"km",hint:"Der drittlängste river Afrikas.",emoji:"🌊"},
  {q:"How deep is der Marianengraben genau in meters?",a:11034,unit:"meterss",hint:"Der Challenger Deep – tiefste Stelle der oceans.",emoji:"🌊"},
  {q:"How many km² has Bayern?",a:70550,unit:"km²",hint:"the largest deutsche Bundesland.",emoji:"🍺"},
  {q:"How high is der Mont Blanc in meters?",a:4808,unit:"meterss",hint:"Der höchste mountain der Alpen.",emoji:"🏔️"},
  {q:"How many countries liegen on dem continent Ozeanien?",a:14,unit:"countries",hint:"Australien, Neuseeland und die Pazifikinseln.",emoji:"🌊"},
  {q:"How long is der Nil with dem Weißen Nil zusammen in km?",a:6650,unit:"km",hint:"the longest river the world.",emoji:"🌊"},
  {q:"How many km² is die Gobi-desert groß?",a:1295000,unit:"km²",hint:"Die kälteste desert the world.",emoji:"🏜️"},
  {q:"How high is der Vesuvius in meters?",a:1281,unit:"meterss",hint:"Der Vulkan der Pompeji zerstörte.",emoji:"🌋"},
  {q:"How many km² has Österreich?",a:83879,unit:"km²",hint:"Kleines aber bergiges country.",emoji:"🇦🇹"},
  {q:"How long is der Kongo in km?",a:4700,unit:"km",hint:"Der tiefste river the world.",emoji:"🌊"},
  {q:"How many km² is das Mittelmeer groß?",a:2500000,unit:"km²",hint:"the largest Binnenmeer the world.",emoji:"🌊"},
  {q:"How high is der Kilimandscharo-Gipfel Kibo in meters?",a:5895,unit:"meterss",hint:"Der höchste Punkt Afrikas.",emoji:"🏔️"},
  {q:"How many countries has Asien?",a:49,unit:"countries",hint:"the largest continent with den meisen people.",emoji:"🌏"},
  {q:"How long is der Jenissei in km?",a:5539,unit:"km",hint:"Einer the longestn Flüsse the world in Russland.",emoji:"🌊"},
  {q:"How many km² is die Namib-desert groß?",a:81000,unit:"km²",hint:"Die älteste desert the world.",emoji:"🏜️"},
  {q:"How high is der Aconcagua in meters?",a:6961,unit:"meterss",hint:"Der höchste mountain Südamerikas.",emoji:"🏔️"},
  {q:"How many km long is der Panamakanal?",a:82,unit:"km",hint:"Verbindet Atlantik und Pazifik.",emoji:"⛵"},
  {q:"How many km² is Brasilien groß?",a:8515767,unit:"km²",hint:"Das fünftgrößte country the world.",emoji:"🇧🇷"},
  {q:"How long is der Rhein vom Ursprung bis zur Mündung in km?",a:1230,unit:"km",hint:"Entspringt in der Schweiz.",emoji:"🌊"},
  {q:"How many km hoch is der Hitimesaya-Gebirgszug in total?",a:2400,unit:"km Länge",hint:"the longest Hochgebirge Earth.",emoji:"🏔️"},
  {q:"How deep is der Titicacasee in meters?",a:283,unit:"meterss",hint:"Der höchstgelegene schiffbare lake.",emoji:"💧"},
  {q:"How many km² has die Schweiz?",a:41285,unit:"km²",hint:"Kleines country with großen Bergen.",emoji:"🇨🇭"},
  {q:"How long is der Ob in Russland in km?",a:3650,unit:"km",hint:"Einer the largestn sibirischen Flüsse.",emoji:"🌊"},
  {q:"How many km entfernt is New York of London?",a:5570,unit:"km",hint:"over den Atlantik.",emoji:"✈️"},
  {q:"How many km² is die Mongolei groß?",a:1564116,unit:"km²",hint:"Das country with der niedrigsten Bevölkerungsdichte.",emoji:"🐎"},
  {q:"How high is der Elbrus in Russland in meters?",a:5642,unit:"meterss",hint:"Der höchste mountain Europas.",emoji:"🏔️"},
  {q:"How many Einwohner has Tokio in million?",a:37,unit:"million",hint:"the largest Stadtregion the world.",emoji:"🗼"},
  {q:"How long is der Suezkanal in km?",a:193,unit:"km",hint:"Verbindet Mittelmeer und Rotes sea.",emoji:"⛵"},
  {q:"How many km² is die Arabische Halbinsel groß?",a:3237500,unit:"km²",hint:"the largest Halbinsel the world.",emoji:"🏜️"},
  {q:"How high is der Etna on Sizilien in meters?",a:3357,unit:"meterss",hint:"Der aktivste Vulkan Europas.",emoji:"🌋"},
  {q:"How many km² is Kanada groß?",a:9984670,unit:"km²",hint:"Das zweitgrößte country the world.",emoji:"🍁"},
  {q:"How deep is der Tiefste Punkt Deutschlands (Wilstedt)?",a:3,unit:"m under Meeresspiegel",hint:"Im Wilstermarsch in Schleswig-Holstein.",emoji:"📏"},
  {q:"How many Inseln has Griechenland?",a:6000,unit:"Inseln",hint:"Davon are etwa 200 bewohnt.",emoji:"🏝️"},
  {q:"How long is die Transsibirische Eisenbahn in km?",a:9289,unit:"km",hint:"the longest Bahnstrecke the world.",emoji:"🚂"},
  {q:"How many km² has die Türkei?",a:783562,unit:"km²",hint:"Liegt in Europa und Asien.",emoji:"🇹🇷"},
  {q:"How high is der Große Ararat in der Türkei in meters?",a:5137,unit:"meterss",hint:"Der biblische mountain der Arche Noah.",emoji:"🏔️"},
  {q:"How many km long is der Amazonas-Regenwhaled?",a:3000,unit:"km Breite",hint:"Größtes Regenwhaledgebiet Earth.",emoji:"🌿"},
  {q:"How many countries has Europa?",a:44,unit:"countries",hint:"Je to Definition 44-50.",emoji:"🇪🇺"},
  {q:"How long is die Grenze between USA und Kanada in km?",a:8891,unit:"km",hint:"the longest Landesgrenze the world.",emoji:"🗺️"},
  {q:"How many km² is Indien groß?",a:3287263,unit:"km²",hint:"Das siebtgrößte country the world.",emoji:"🇮🇳"},
  {q:"How high is die Zugspitze over München in meters (Unterschied)?",a:2932,unit:"meterss",hint:"München liegt on 520m, Zugspitze on 2962m.",emoji:"🏔️"},
  {q:"How long is die Weser in km?",a:452,unit:"km",hint:"Fließt through Hessen, Niedersachsen in die Nordsee.",emoji:"🌊"},
  {q:"How many km² is der Schwaszwhaled groß?",a:6009,unit:"km²",hint:"the largest whaledgebirge Deutschlands.",emoji:"🌲"},
  {q:"How high is der Brocken im Harz in meters?",a:1141,unit:"meterss",hint:"Der höchste Gipfel Norddeutschlands.",emoji:"🏔️"},
  {q:"How many km² is die Nordsee groß?",a:575000,unit:"km²",hint:"Ein Randmeer des Atlantiks.",emoji:"🌊"},
  {q:"How far is Berlin of München in km Luftlinie?",a:504,unit:"km",hint:"Beide Hauptstädte Deutschlands.",emoji:"🇩🇪"},
  {q:"How long is der Inn in km?",a:517,unit:"km",hint:"Entspringt in der Schweiz – mündet in die Donau.",emoji:"🌊"},
  {q:"How many km entfernt liegt Hamburg of der Nordsee?",a:100,unit:"km",hint:"Die Elbe verbindet Hamburg with der lake.",emoji:"⛵"},
  {q:"How high is der Feldberg im Schwaszwhaled in meters?",a:1493,unit:"meterss",hint:"Der höchste mountain Baden-Württembergs.",emoji:"🏔️"},
  {q:"How many Einwohner has München?",a:1500000,unit:"inhabitants",hint:"Ca. 1,5 million – größte city Bayerns.",emoji:"🏙️"},
  {q:"How many km² is Berlin groß?",a:892,unit:"km²",hint:"Etwa 3,7 million Einwohner.",emoji:"🇩🇪"},
  {q:"How long is die Oder in km?",a:866,unit:"km",hint:"Grenzfluss between Deutschland und Polen.",emoji:"🌊"},
  {q:"How many kilometerss Autobahnnetz has Deutschland?",a:13200,unit:"km",hint:"Das drittlängste the world.",emoji:"🛣️"},
  {q:"How high is der Taunus-Höchste Punkt (Großer Feldberg) in meters?",a:878,unit:"meterss",hint:"Nördlich of Frankfurt.",emoji:"🏔️"},
  {q:"How far is Hamburg of Frankfurt in km Luftlinie?",a:430,unit:"km",hint:"Beide are millionstädte.",emoji:"🇩🇪"},
  {q:"How many Bundescountries has Deutschland?",a:16,unit:"Bundescountries",hint:"3 Stadtstaaten und 13 Flächencountries.",emoji:"🇩🇪"},
  {q:"How long is die Autobahn A9 (München-Berlin) in km?",a:524,unit:"km",hint:"Eine der wichtigsten deutschen Autobahnen.",emoji:"🛣️"},
  {q:"How many km² is der Bodensee groß?",a:536,unit:"km²",hint:"Drittgrößter lake Mitteleuropas.",emoji:"💧"},
  {q:"How deep is der Bodensee maxitimes in meters?",a:254,unit:"meterss",hint:"Am tiefsten between Bregenz und Friedrichshafen.",emoji:"💧"},
  {q:"How many km² is Hamburg groß?",a:755,unit:"km²",hint:"Einer der drei deutschen Stadtstaaten.",emoji:"⚓"},
  {q:"How high is der Wendelstein in Bayern in meters?",a:1838,unit:"meterss",hint:"with Zahnradbahn zugänglich.",emoji:"🏔️"},
  {q:"How far is Köln of Düsseldorf in km?",a:45,unit:"km",hint:"Beide liegen am Rhein in NRW.",emoji:"🌊"},
  {q:"How many km² is die Lüneburger Heide groß?",a:7400,unit:"km²",hint:"Größtes Naturschutzgebiet Norddeutschlands.",emoji:"🌿"},
  {q:"How high is der Grossglockner in Österreich in meters?",a:3798,unit:"meterss",hint:"Höchster mountain Österreichs.",emoji:"🏔️"},
  {q:"How many Einwohner has Wien?",a:2000000,unit:"inhabitants",hint:"Die capital Österreichs.",emoji:"🎵"},
  {q:"How long is der Bodensee in km?",a:63,unit:"km",hint:"of Bregenz bis Konstanz.",emoji:"💧"},
  {q:"How many km² is die Nordseeküste Deutschlands lang?",a:450,unit:"km",hint:"of der dänischen Grenze bis zur Elbmündung.",emoji:"🌊"},
  {q:"How high is der Schwaszwhaled-Gipfel Belchen in meters?",a:1414,unit:"meterss",hint:"Einer der schönsten Aussichtsgipfel.",emoji:"🏔️"},
  {q:"How many Einwohner has Hamburg?",a:1800000,unit:"inhabitants",hint:"Die zweitgrößte city Deutschlands.",emoji:"⚓"},
  {q:"How long is die Küstenlinie der Ostsee (Deutschland) in km?",a:354,unit:"km",hint:"of Flensburg bis zur Oderbucht.",emoji:"🌊"},
  {q:"How far is München of Wien in km Luftlinie?",a:357,unit:"km",hint:"Zwei der schönsten deutschsprachigen Städte.",emoji:"🏙️"},
  {q:"How many km² is der Schwaszwhaled groß?",a:6009,unit:"km²",hint:"Heimat des Kuckucksuhren.",emoji:"🌲"},
  {q:"How high is der Piz Bernina in der Schweiz in meters?",a:4049,unit:"meterss",hint:"Der östlichste Vierthousander der Alpen.",emoji:"🏔️"},
  {q:"How many Einwohner has Zürich?",a:400000,unit:"inhabitants",hint:"the largest city der Schweiz.",emoji:"🇨🇭"},
  {q:"How long is die Grenze Deutschlands in total in km?",a:3757,unit:"km",hint:"9 Nachbarcountries.",emoji:"🇩🇪"},
  {q:"How high is der Dachstein in Österreich in meters?",a:2995,unit:"meterss",hint:"with Gletscher und Hängebrücke.",emoji:"🏔️"},
  {q:"How many km² is die Côte d'Azur lang?",a:180,unit:"km",hint:"of Saint-Tropez bis Menton.",emoji:"🌊"},
  {q:"How many Einwohner has Berlin?",a:3700000,unit:"inhabitants",hint:"Die capital und größte city Deutschlands.",emoji:"🇩🇪"},
  {q:"How long is die Strecke Berlin-Paris in km?",a:1050,unit:"km",hint:"with dem Zug etwa 8 hours.",emoji:"🚂"},
  {q:"How high is der Teide on Teneriffa in meters?",a:3718,unit:"meterss",hint:"Der höchste mountain Spaniens.",emoji:"🌋"},
  {q:"How many km² is die Toskana in Italien groß?",a:22987,unit:"km²",hint:"Berühmt for wine und Kunst.",emoji:"🍷"},
  {q:"How far is Deutschland of Australien entfernt in km?",a:16000,unit:"km",hint:"on der anderen Seite Earth.",emoji:"🌏"},
  {q:"How high is der Olymp in Griechenland in meters?",a:2917,unit:"meterss",hint:"Sitz der griechischen Götter.",emoji:"🏛️"},
  {q:"How many km² is Frankreich groß?",a:551695,unit:"km²",hint:"the largest country Westeuropas.",emoji:"🇫🇷"},
  {q:"How long is die Loire in Frankreich in km?",a:1013,unit:"km",hint:"the longest river Frankreichs.",emoji:"🌊"},
  {q:"How high is der Matterhorn in der Schweiz in meters?",a:4478,unit:"meterss",hint:"Das Wahrzeichen der Alpen.",emoji:"🏔️"},
  {q:"How many Einwohner has Paris?",a:2200000,unit:"inhabitants",hint:"Die city der Liebe.",emoji:"🗼"},
  {q:"How long is die Themse in Großbritannien in km?",a:346,unit:"km",hint:"Fließt through London.",emoji:"🌊"},
  {q:"How many km² is Spanien groß?",a:505990,unit:"km²",hint:"Das zweitgrößte country Westeuropas.",emoji:"🇪🇸"},
  {q:"How high is der Nanga Parbat in Pakisan in meters?",a:8126,unit:"meterss",hint:"Der neunte höchste mountain the world.",emoji:"🏔️"},
  {q:"How many km² is Italien groß?",a:301340,unit:"km²",hint:"Die Form des Stiefels.",emoji:"🇮🇹"},
  {q:"How long is der Po in Italien in km?",a:652,unit:"km",hint:"the longest river Italiens.",emoji:"🌊"},
  {q:"How high is der Vesuv at Neapel in meters?",a:1281,unit:"meterss",hint:"Er zerstörte Pompeji in the year 79 n.Chr.",emoji:"🌋"},
  {q:"How many Einwohner has Rom?",a:2800000,unit:"inhabitants",hint:"Die ewige city.",emoji:"🏛️"},
  {q:"How long is der Ebro in Spanien in km?",a:930,unit:"km",hint:"Der wasserreichste river Spaniens.",emoji:"🌊"},
  {q:"How high is der Pico de Orizaba in Mexiko in meters?",a:5636,unit:"meterss",hint:"Der höchste mountain Mexikos.",emoji:"🏔️"},
  {q:"How many km² is Mexiko groß?",a:1964375,unit:"km²",hint:"Das drittgrößte country Lateinamerikas.",emoji:"🌵"},
  {q:"How long is der Jangtse-river in China in km?",a:6300,unit:"km",hint:"the longest river Asiens.",emoji:"🌊"},
  {q:"How high is der K2 in Pakisan in meters?",a:8611,unit:"meterss",hint:"Der zweithöchste mountain the world.",emoji:"🏔️"},
  {q:"How many km² is China groß?",a:9596960,unit:"km²",hint:"Das viertgrößte country the world.",emoji:"🇨🇳"},
  {q:"How long is der Huang He (Gelber river) in China in km?",a:5464,unit:"km",hint:"Die Wiege der chinesischen Zivilisation.",emoji:"🌊"},
  {q:"How high is der Fuji-San in Japan genau in meters?",a:3776,unit:"meterss",hint:"Symbol Japans.",emoji:"🗻"},
  {q:"How many km² is Japan groß?",a:377975,unit:"km²",hint:"Ein Inselstaat im Pazifik.",emoji:"🇯🇵"},
  {q:"How many Einwohner has Tokio genau in million?",a:37,unit:"million",hint:"Größte Stadtregion the world.",emoji:"🗼"},
  {q:"How long is der Mekong in km?",a:4350,unit:"km",hint:"Fließt through 6 countries Südostasiens.",emoji:"🌊"},
  {q:"How high is der Kilimandscharos zweithöchster Gipfel Mawenzi in meters?",a:5149,unit:"meterss",hint:"Der zweite Gipfel des Kilimandscharo.",emoji:"🏔️"},
  {q:"How many km² is die USA groß?",a:9833517,unit:"km²",hint:"Das drittgrößte country the world.",emoji:"🇺🇸"},
  {q:"How long is der Missouri in km?",a:3767,unit:"km",hint:"Längster river in den USA.",emoji:"🌊"},
  {q:"How high is der Denali in Alaska in meters?",a:6190,unit:"meterss",hint:"Der höchste mountain Nordamerikas.",emoji:"🏔️"},
  {q:"How many Einwohner has New York City in million?",a:8.3,unit:"million",hint:"the largest city der USA.",emoji:"🗽"},
  {q:"How long is der Colorado River in km?",a:2334,unit:"km",hint:"Er schuf den Grand Canyon.",emoji:"🌊"},
  {q:"How many km² is Argentinien groß?",a:2780400,unit:"km²",hint:"Das achtgrößte country the world.",emoji:"🇦🇷"},
  {q:"How high are die Iguazu-Wasserfälle in meters?",a:82,unit:"meterss",hint:"Breiter als die Niagarafälle.",emoji:"🌊"},
  {q:"How many km long is der Nil vom lake Victoria bis zur Mündung?",a:5584,unit:"km",hint:"Je to Messung the longest river.",emoji:"🌊"},
  {q:"How high is der Tafelberg in Südafrika in meters?",a:1086,unit:"meterss",hint:"Wahrzeichen Kapstadts.",emoji:"🏔️"},
  {q:"How many km² is die Demokratische Republik Kongo groß?",a:2344858,unit:"km²",hint:"Das zweitgrößte country Afrikas.",emoji:"🌿"},
  {q:"How long is der Sambesi in km?",a:2574,unit:"km",hint:"An ihm liegen die Victoriafälle.",emoji:"🌊"},
  {q:"How high are die Victoriafälle in Simbabwe in meters?",a:108,unit:"meterss",hint:"Größte Wasserfälle the world to Breite.",emoji:"🌊"},
  {q:"How many km² is Ägypten groß?",a:1001449,unit:"km²",hint:"95% davon is desert.",emoji:"🏜️"},
  {q:"How long is der Sambesi of der Quelle bis zur Mündung in km?",a:2574,unit:"km",hint:"Fließt of Sambia bis Mosambik.",emoji:"🌊"},
  {q:"How long is der Amazonas-river in km?",a:6400,unit:"km",hint:"Einer the longestn Flüsse the world.",emoji:"🌿"},
  {q:"How many Einwohner has Tokio?",a:14000000,unit:"inhabitants",hint:"Eine the largestn Städte the world.",emoji:"🏙️"},
  {q:"How high is die Zugspitze in meters?",a:2962,unit:"meterss",hint:"Der höchste mountain Deutschlands.",emoji:"🏔️"},
  {q:"How many km² has Australien?",a:7700000,unit:"km²",hint:"Der sechstgrößte Staat Earth.",emoji:"🦘"},
  {q:"How long is die Chinesische Mauer in km?",a:21000,unit:"km",hint:"the longest Bauwerk humansheit.",emoji:"🧱"},
  {q:"How many countries has Afrika?",a:54,unit:"countries",hint:"Der continent with den meisen countriesn.",emoji:"🌍"},
  {q:"How deep is der Titicacasee in meters?",a:284,unit:"meterss",hint:"Der höchste schiffbare lake the world.",emoji:"🏔️"},
  {q:"How long is der Rhein in km?",a:1230,unit:"km",hint:"Fließt through Deutschland in die Nordsee.",emoji:"🌊"},
  {q:"How many Inseln has Griechenland?",a:6000,unit:"Inseln",hint:"Davon are etwa 230 bewohnt.",emoji:"🏝️"},
  {q:"How high is der Fujiyama in Japan?",a:3776,unit:"meterss",hint:"Japans heiliger Vulkan.",emoji:"🗻"},
  {q:"How big is die Sahara in km²?",a:9200000,unit:"km²",hint:"the largest desert the world.",emoji:"🏜️"},
  {q:"How many km² has Brasilien?",a:8500000,unit:"km²",hint:"Größtes country Südamerikas.",emoji:"🇧🇷"},
  {q:"How long is der Mississippif luss in km?",a:3730,unit:"km",hint:"Der große Strom Nordamerikas.",emoji:"🌊"},
  {q:"How many Einwohner has Mumbai?",a:20000000,unit:"inhabitants",hint:"the largest city Indiens.",emoji:"🏙️"},
  {q:"How high is der Aconcagua in Argentinien?",a:6961,unit:"meterss",hint:"Höchster mountain Amerikas.",emoji:"🏔️"},
  {q:"How long is der Ganges in km?",a:2525,unit:"km",hint:"Heiliger river Indiens.",emoji:"🌊"},
  {q:"How many km² has Saudi-Arabien?",a:2150000,unit:"km²",hint:"the largest country Westasiens.",emoji:"🇸🇦"},
  {q:"How deep is der Vierwhaledstättersee in meters?",a:214,unit:"meterss",hint:"in der Schweiz – heartstück der Eidgenossenschaft.",emoji:"💧"},
  {q:"How many countries grenzen an Frankreich?",a:8,unit:"countries",hint:"Spanien, Andorra, Monaco, Italien, Schweiz, Deutschland, Luxemburg, Belgien.",emoji:"🇫🇷"},
  {q:"How high is der Olymp in Griechenland?",a:2917,unit:"meterss",hint:"mountain der griechischen Götter.",emoji:"⛰️"},
  {q:"How long is der Rhein of der Quelle bis zur Mündung?",a:1230,unit:"km",hint:"of den Alpen bis zur Nordsee.",emoji:"🌊"},
  {q:"How many km² has die Türkei?",a:783000,unit:"km²",hint:"Liegt on zwei Kontinduckn.",emoji:"🇹🇷"},
  {q:"How long is die Elbe in km?",a:1091,unit:"km",hint:"Fließt of Tschechien bis zur Nordsee.",emoji:"🌊"},
  {q:"How high liegt Machu Picchu in meters?",a:2430,unit:"meterss",hint:"Die city der Inka in Peru.",emoji:"🏛️"},
  {q:"How many km² has Indien?",a:3290000,unit:"km²",hint:"Das siebtgrößte country the world.",emoji:"🇮🇳"},
  {q:"How many Einwohner has Mexiko-city?",a:22000000,unit:"inhabitants",hint:"Eine the largestn Städte Amerikas.",emoji:"🏙️"},
  {q:"How long is der Donaufluss in km?",a:2860,unit:"km",hint:"Fließt through 10 countries.",emoji:"🌊"},
  {q:"How deep is das Tote sea in meters under dem Meeresspiegel?",a:430,unit:"meterss",hint:"Der tiefste Punkt der Erdoberfläche.",emoji:"🌊"},
  {q:"How many km² has die Mongolei?",a:1564000,unit:"km²",hint:"Größtes Binnenland the world.",emoji:"🏕️"},
  {q:"How long is die Oder in km?",a:866,unit:"km",hint:"Grenzfluss between Deutschland und Polen.",emoji:"🌊"},
  {q:"How high is der Mont Blanc ohne Schneegipfel?",a:4810,unit:"meterss",hint:"Höchster mountain der Alpen.",emoji:"🏔️"},
  {q:"How many km² has Schweden?",a:450000,unit:"km²",hint:"the largest skandinavische country.",emoji:"🇸🇪"},
  {q:"How many Einwohner has Sao Paulo?",a:21000000,unit:"inhabitants",hint:"the largest city Südamerikas.",emoji:"🏙️"},
  {q:"How long is der Lena-river in Russland?",a:4400,unit:"km",hint:"Einer the longestn Flüsse Sibiriens.",emoji:"🌊"},
  {q:"How deep is der Bodensee in meters?",a:251,unit:"meterss",hint:"Dreicountriessee: Deutschland, Österreich, Schweiz.",emoji:"💧"},
  {q:"How many km² has die Ukraine?",a:603000,unit:"km²",hint:"Das flächengrößte europäische country (ohne Russland).",emoji:"🇺🇦"},
  {q:"How high is der Teide on Teneriffa in meters?",a:3718,unit:"meterss",hint:"Höchster mountain Spaniens.",emoji:"🌋"},
  {q:"How many countries has Ozeanien?",a:14,unit:"countries",hint:"Australien, Neuseeland und zwölf Inselstaaten.",emoji:"🏝️"},
  {q:"How long is die Weser in km?",a:452,unit:"km",hint:"Fließt of Hann.Münden bis Bremen.",emoji:"🌊"},
  {q:"How many km² has Spanien?",a:506000,unit:"km²",hint:"Zweitgrößtes country der EU.",emoji:"🇪🇸"},
  {q:"How deep is der Lago Maggiore in meters?",a:372,unit:"meterss",hint:"between Italien und der Schweiz.",emoji:"💧"},
  {q:"How many Einwohner has Kairo?",a:20000000,unit:"inhabitants",hint:"Größte city Afrikas.",emoji:"🏙️"},
  {q:"How long is der Tigris in km?",a:1900,unit:"km",hint:"Mesopotamien – Wiege der Zivilisation.",emoji:"🌊"},
  {q:"How high is der Vesuvius in meters?",a:1281,unit:"meterss",hint:"Berühmter Vulkan at Neapel.",emoji:"🌋"},
  {q:"How many km² has Polen?",a:313000,unit:"km²",hint:"Das neuntgrößte country Europas.",emoji:"🇵🇱"},
  {q:"How long is der Main in km?",a:525,unit:"km",hint:"Wichtigster rechter Nebenfluss des Rheins.",emoji:"🌊"},
  {q:"How deep is der Lago di Garda in meters?",a:346,unit:"meterss",hint:"Größter lake Italiens.",emoji:"💧"},
  {q:"How many Einwohner has New York City?",a:8000000,unit:"inhabitants",hint:"the largest city der USA.",emoji:"🗽"},
  {q:"How high is der Etna on Sizilien?",a:3357,unit:"meterss",hint:"Aktivster Vulkan Europas.",emoji:"🌋"},
  {q:"How long is der Euphrat in km?",a:2800,unit:"km",hint:"Zusammen with dem Tigris Wiege der Zivilisation.",emoji:"🌊"},
  {q:"How many km² has Norwegen?",a:385000,unit:"km²",hint:"country der Fjorde.",emoji:"🇳🇴"},
  {q:"How deep is der Traunsee in Österreich?",a:191,unit:"meterss",hint:"Tiefster lake Österreichs.",emoji:"💧"},
  {q:"How many Einwohner has Los Angeles?",a:4000000,unit:"inhabitants",hint:"city der Engel.",emoji:"🌴"},
  {q:"How long is der Mekong in km?",a:4350,unit:"km",hint:"Der große river Südostasiens.",emoji:"🌊"},
  {q:"How high is der Großglockner in Österreich?",a:3798,unit:"meterss",hint:"Höchster mountain Österreichs.",emoji:"🏔️"},
  {q:"How many km² has Finnland?",a:338000,unit:"km²",hint:"Das country der thousand Seen.",emoji:"🇫🇮"},
  {q:"How many Seen has Finnland?",a:188000,unit:"Seen",hint:"over 180.000 Seen – das meise water Europas.",emoji:"💧"},
  {q:"How long is der Kongof luss in km?",a:4700,unit:"km",hint:"Zweitlängster river Afrikas.",emoji:"🌊"},
  {q:"How high is der Kilimanjaro in Tansania?",a:5895,unit:"meterss",hint:"Höchster mountain Afrikas.",emoji:"🏔️"},
  {q:"How deep is der Plattensee in Ungarn?",a:12,unit:"meterss",hint:"Größter Süßwassersee Mitteleuropas.",emoji:"💧"},
  {q:"How many Inseln has Schweden?",a:220000,unit:"Inseln",hint:"over 200.000 Inseln in der Küste.",emoji:"🏝️"},
  {q:"How long is der Kongo-river in km?",a:4700,unit:"km",hint:"Tiefster river the world.",emoji:"🌊"},
  {q:"How high is der Montserrat in Spanien?",a:1236,unit:"meterss",hint:"Heiliger mountain Kataloniens.",emoji:"⛰️"},
  {q:"How many km² has Portugal?",a:92000,unit:"km²",hint:"Das westlichste country Europas.",emoji:"🇵🇹"},
  {q:"How many km long is die Küstenlinie Deutschlands?",a:2389,unit:"km",hint:"Nord- und Ostseeküste zusammen.",emoji:"🌊"},
  {q:"How high liegt Wien over dem Meeresspiegel?",a:171,unit:"meterss",hint:"capital Österreichs.",emoji:"🏙️"},
  {q:"How big is die Nordsee in km²?",a:570000,unit:"km²",hint:"between Großbritannien und dem Festland.",emoji:"🌊"},
  {q:"How long is der Inn in km?",a:517,unit:"km",hint:"Fließt through Österreich in den Rhein.",emoji:"🌊"},
];
