// 🏆 SPORT & RECORDS – English
export default [
  {q:"How many kilometerss is a Marathon lang?",a:42.195,unit:"km",hint:"Benannt to dem Lauf eines Boten from Marathon to Athen.",emoji:"🏃"},
  {q:"How fast lief Usain Bolt seinen world record over 100m in seconds?",a:9.58,unit:"seconds",hint:"Aufgestellt 2009 in Berlin.",emoji:"⚡"},
  {q:"How many Goldmedaillen won Michael Phelps at Olympia?",a:23,unit:"Goldmedaillen",hint:"Der erfolgreichste Olympiateilnehmer aller Zeiten.",emoji:"🏊"},
  {q:"How high is a Basketballkorb in meters?",a:3.05,unit:"meterss",hint:"Die offizielle Höhe in der NBA und at Olympia.",emoji:"🏀"},
  {q:"How many players stehen beim Fußball on dem Platz (beide Teams)?",a:22,unit:"players",hint:"11 pro Mannschaft.",emoji:"⚽"},
  {q:"How long is a olympisches Schwimmbecken in meters?",a:50,unit:"meterss",hint:"Die offizielle Länge for world recorde.",emoji:"🏊"},
  {q:"How many Punkte bekommt man at einem Touchdown im American Football?",a:6,unit:"Punkte",hint:"Dazu kommt noch a Extra-Punkt for den Kick.",emoji:"🏈"},
  {q:"How high is a Volleyballnetz at Männern in meters?",a:2.43,unit:"meterss",hint:"at Frauen is es 2,24 meters hoch.",emoji:"🏐"},
  {q:"How many km fährt a Tour-de-France-Fahrer in total?",a:3500,unit:"km",hint:"over 21 Etappen in 3 weeks.",emoji:"🚴"},
  {q:"How long takes a Eishockeyspiel in minutes (reine Spielzeit)?",a:60,unit:"minutes",hint:"3 Drittel à 20 minutes.",emoji:"🏒"},
  {q:"How many Runden has a Formel-1-Rennen on average?",a:57,unit:"Runden",hint:"Je to Streckenlänge variiert die Rundenzahl.",emoji:"🏎️"},
  {q:"How many meters hoch is der Hochsprung-world record?",a:2.45,unit:"meterss",hint:"Javier Sotomayor stellte 1993 diesen Rekord on.",emoji:"🏃"},
  {q:"How many Punkte needs man im Tischtennis zum Gewinnen eines Satzes?",a:11,unit:"Punkte",hint:"with 2 Punkten Vorsprung muss man gewinnen.",emoji:"🏓"},
  {q:"How long is a Fußballfeld maxitimes in meters?",a:105,unit:"meterss",hint:"Die FIFA-Vorgabe is 100–110 meters.",emoji:"⚽"},
  {q:"How many players has a Baseballmannschaft?",a:9,unit:"players",hint:"Feldplayers und a Schlagmann.",emoji:"⚾"},
  {q:"How many meters weit springt man beim Weitsprung-world record?",a:8.95,unit:"meterss",hint:"Mike Powell sprang 1991 in Tokio diesen Rekord.",emoji:"🏃"},
  {q:"How many hours takese the longest Tennisspiel aller Zeiten?",a:11,unit:"hours",hint:"Isner vs. Mahut 2010 in Wimbledon.",emoji:"🎾"},
  {q:"How many times has Bayern München die Bundesliga gewonnen?",a:32,unit:"times",hint:"Deutschlands erfolgreichster Fußballklub.",emoji:"⚽"},
  {q:"How big is a Basketballfeld in meters Länge?",a:28,unit:"meterss",hint:"Das offizielle FIBA-Spielfeld is diese Zahl x 15 meters.",emoji:"🏀"},
  {q:"How many players has a Rugbyteam?",a:15,unit:"players",hint:"Im Rugby League are es 13 players.",emoji:"🏉"},
  {q:"How many Schritte darf man im Basketball ohne Dribbeln machen?",a:2,unit:"Schritte",hint:"at 3 Schritten are there Schrittfehler.",emoji:"🏀"},
  {q:"How many km/h erreichte the fastest Tennisaufschlag?",a:263,unit:"km/h",hint:"Samuel Groth from Australien, 2012.",emoji:"🎾"},
  {q:"How many km weit wirft man beim Speerwurf-world record?",a:98.48,unit:"meterss",hint:"Jan Železný from Tschechien, 1996.",emoji:"🎯"},
  {q:"How many Tore schoss Ronaldo in seiner Karriere approximately?",a:900,unit:"Tore",hint:"Er is einer der erfolgreichsten Torschützen aller Zeiten.",emoji:"⚽"},
  {q:"How many PS has a Formel-1-Motor?",a:1000,unit:"PS",hint:"Moderne F1-Motoren leisen over 1000 PS.",emoji:"🏎️"},
  {q:"How high is a Tischtennis-Netz in cm?",a:15.25,unit:"cm",hint:"Nur 15,25 cm – das is sehr niedrig!",emoji:"🏓"},
  {q:"How many Goldmedaillen has Usain Bolt at Olympia gewonnen?",a:8,unit:"Goldmedaillen",hint:"3x Olympia, immer Gold over 100m, 200m und 4x100m.",emoji:"🏅"},
  {q:"How heavy is a Fußball in grams?",a:430,unit:"grams",hint:"Die FIFA schreibt 410–450 grams vor.",emoji:"⚽"},
  {q:"How long is a Olympia-Bahn beim swim in meters?",a:50,unit:"meterss",hint:"Kurzbahn-Wettkämpfe finden on 25 meters statt.",emoji:"🏊"},
  {q:"How many Felder has a Schachbrett?",a:64,unit:"Felder",hint:"8 x 8 Felder, abwechselnd schwasz und weiß.",emoji:"♟️"},
  {q:"How many players has a Fußballmannschaft?",a:11,unit:"players",hint:"Inklusive Torwast.",emoji:"⚽"},
  {q:"How big is a offizielles Fußballfeld in meters?",a:105,unit:"meters Länge",hint:"× 68 meters.",emoji:"⚽"},
  {q:"How high is a Basketballkorb in meters?",a:3.05,unit:"meterss",hint:"Offiziell in NBA und at Olympia.",emoji:"🏀"},
  {q:"How many Goldmedaillen has Michael Phelps?",a:23,unit:"Goldmedaillen",hint:"Erfolgreichster Olympionike aller Zeiten.",emoji:"🏊"},
  {q:"How long is a Olympisches Schwimmbecken?",a:50,unit:"meterss",hint:"for world recorde.",emoji:"🏊"},
  {q:"How fast lief Usain Bolt seine 100m in seconds?",a:9.58,unit:"seconds",hint:"Berlin 2009.",emoji:"⚡"},
  {q:"How many km is a Marathon lang?",a:42.195,unit:"km",hint:"Benannt to dem Lauf eines Boten.",emoji:"🏃"},
  {q:"How many Punkte needs man im Tischtennis?",a:11,unit:"Punkte",hint:"with 2 Punkten Vorsprung.",emoji:"🏓"},
  {q:"How many players has a Rugby-Team?",a:15,unit:"players",hint:"Im Rugby League 13.",emoji:"🏉"},
  {q:"How high is a Volleyball-Netz at Männern?",a:2.43,unit:"meterss",hint:"at Frauen 2,24 meters.",emoji:"🏐"},
  {q:"How many Runden has a Formel-1-Rennen?",a:57,unit:"Runden",hint:"Je to Streckenlänge.",emoji:"🏎️"},
  {q:"How far springt man beim Weitsprung-world record?",a:8.95,unit:"meterss",hint:"Mike Powell, Tokio 1991.",emoji:"🏃"},
  {q:"How many km fährt a Tour-de-France-Fahrer?",a:3500,unit:"km",hint:"21 Etappen in 3 weeks.",emoji:"🚴"},
  {q:"How long is a Eishockeyspiel in minutes?",a:60,unit:"minutes",hint:"3 Drittel à 20 minutes.",emoji:"🏒"},
  {q:"How many Schritte darf man im Basketball?",a:2,unit:"Schritte",hint:"at 3 Schritten: Schrittfehler.",emoji:"🏀"},
  {q:"How many km/h schlägt Serena Williams einen Aufschlag?",a:207,unit:"km/h",hint:"Rekord for Frauen.",emoji:"🎾"},
  {q:"How many players has a Baseballteam?",a:9,unit:"players",hint:"Feldplayers.",emoji:"⚾"},
  {q:"How many Punkte is a Touchdown?",a:6,unit:"Punkte",hint:"Plus Extra-Punkt for den Kick.",emoji:"🏈"},
  {q:"How many hours takese the longest Tennisspiel?",a:11,unit:"hours",hint:"Isner vs. Mahut 2010 in Wimbledon.",emoji:"🎾"},
  {q:"How many times has Bayern München die Bundesliga gewonnen?",a:32,unit:"times",hint:"Deutschlands erfolgreichster Klub.",emoji:"⚽"},
  {q:"How high is das Tischtennis-Netz in cm?",a:15.25,unit:"cm",hint:"Sehr niedrig.",emoji:"🏓"},
  {q:"How many Punkte are there beim Darts pro Pfeil maxitimes?",a:60,unit:"Punkte",hint:"Dreifach-20 = 60 Punkte.",emoji:"🎯"},
  {q:"How heavy is a Fußball in grams?",a:430,unit:"grams",hint:"410 bis 450 grams.",emoji:"⚽"},
  {q:"How many km/h flies a Badminton-Federball maxitimes?",a:493,unit:"km/h",hint:"Schnellstes Sportgerät the world.",emoji:"🏸"},
  {q:"How big is a Basketballfeld in meters?",a:28,unit:"meters Länge",hint:"× 15 meters.",emoji:"🏀"},
  {q:"How many Goldmedaillen has Usain Bolt at Olympia?",a:8,unit:"Goldmedaillen",hint:"3x Olympia, immer Gold.",emoji:"🏅"},
  {q:"How many players has a Handballteam on dem Feld?",a:7,unit:"players",hint:"Inklusive Torwast.",emoji:"🤾"},
  {q:"How high is a Turnreck in meters?",a:2.8,unit:"meterss",hint:"Das Hochreck at Männern.",emoji:"🤸"},
  {q:"How long is a Olympische Laufbahn in meters?",a:400,unit:"meterss",hint:"Alle Stadien have 400m Bahnen.",emoji:"🏃"},
  {q:"How many players has a Eishockeymannschaft on dem Eis?",a:6,unit:"players",hint:"Inklusive Torwast.",emoji:"🏒"},
  {q:"How many km/h fährt a Formel-1-Auto maxitimes?",a:370,unit:"km/h",hint:"on langen Geraden.",emoji:"🏎️"},
  {q:"How long is a Schwimmbahn at den Olympischen Spielen?",a:50,unit:"meterss",hint:"Long Course – for alle world recorde.",emoji:"🏊"},
  {q:"How many Pins stehen beim Bowling?",a:10,unit:"Pins",hint:"Im Dreieck aufgestellt.",emoji:"🎳"},
  {q:"How many players has a Wasserball-Team?",a:7,unit:"players",hint:"Inklusive Torwast.",emoji:"🤽"},
  {q:"How high is a Sprungbrett at Olympia in meters?",a:10,unit:"meterss",hint:"Turm-jump of 10m.",emoji:"🏊"},
  {q:"How many horsee zieht a Schlitten beim dogeschlittenrennen Iditarod?",a:16,unit:"doge",hint:"Keine horsee – doge!",emoji:"🐕"},
  {q:"How many km long is das Iditarod-Rennen?",a:1600,unit:"km",hint:"of Anchorage to Nome, Alaska.",emoji:"🛷"},
  {q:"How many players has a Rugby-Sevens-Team?",a:7,unit:"players",hint:"Kleiner als nortimeses Rugby.",emoji:"🏉"},
  {q:"How high is a Hochsprung-world record in meters?",a:2.45,unit:"meterss",hint:"Javier Sotomayor, 1993.",emoji:"🏃"},
  {q:"How many Runden has a Boxkampf maxitimes?",a:12,unit:"Runden",hint:"Profi-Weltmeiserschaftskampf.",emoji:"🥊"},
  {q:"How long is a Curveball-Wurfbahn beim Baseball in meters?",a:18.44,unit:"meterss",hint:"Der Pitching-Abstand.",emoji:"⚾"},
  {q:"How many players has a Cricketteam?",a:11,unit:"players",hint:"Gleich wie Fußball.",emoji:"🏏"},
  {q:"How many Hürden überquert a Läufer beim 110m-Hürdenlauf?",a:10,unit:"Hürden",hint:"Hürden á 1,067m Höhe.",emoji:"🏃"},
  {q:"How many Kegel stehen beim Kegeln?",a:9,unit:"Kegel",hint:"Im deutschen Kegeln – anders als Bowling.",emoji:"🎳"},
  {q:"How heavy is a Diskus at Frauen in kg?",a:1,unit:"kg",hint:"at Männern 2 kg.",emoji:"🥏"},
  {q:"How long is a Olympisches Ruderrennen in km?",a:2,unit:"km",hint:"2000 meters on ruhigem water.",emoji:"🚣"},
  {q:"How high is a Turnbarren vom Boden in meters?",a:2,unit:"meterss",hint:"Parallelbarren at Männern.",emoji:"🤸"},
  {q:"How many km weit wirft der Speerwurf-world record?",a:98.48,unit:"meterss",hint:"Jan Železný, 1996.",emoji:"🎯"},
  {q:"How many players has a Volleyball-Team on dem Feld?",a:6,unit:"players",hint:"Inklusive Libero.",emoji:"🏐"},
  {q:"How long is a Fußballtrikot-Kurzärmel-Ärmel maxitimes in cm?",a:30,unit:"cm",hint:"Geregelt in FIFA-Ausrüstungsregeln.",emoji:"👕"},
  {q:"How high is die Tischtennisplatte vom Boden in cm?",a:76,unit:"cm",hint:"Standardhöhe worldwide.",emoji:"🏓"},
  {q:"How long is a Badminton-Bahn in meters?",a:13.4,unit:"meterss",hint:"13,4 × 6,1 meters for Doppel.",emoji:"🏸"},
  {q:"How many players has a American-Football-Team on dem Feld?",a:11,unit:"players",hint:"Offense AND Defense je 11.",emoji:"🏈"},
  {q:"How big is a Golfball im Durchmesser in mm?",a:42.67,unit:"mm",hint:"Mindestdurchmesser to Regelwerk.",emoji:"⛳"},
  {q:"How long is a Olympisches Ruder-Skullyboot in meters?",a:8,unit:"meterss",hint:"Einer sitzt – 2 Ruder.",emoji:"🚣"},
  {q:"How many players has a Lacrosse-Team on dem Feld?",a:10,unit:"players",hint:"at Männern – at Frauen 12.",emoji:"🥍"},
  {q:"How high is a Fußballtor in meters?",a:2.44,unit:"meterss",hint:"2,44m × 7,32m breit.",emoji:"⚽"},
  {q:"How many hours takese the longest Schachpartie?",a:20,unit:"hours",hint:"Klassisches Schach ohne Zeitkontrolle.",emoji:"♟️"},
  {q:"How many km/h schießt a Tennisball beim schnellsten Aufschlag?",a:263,unit:"km/h",hint:"Samuel Groth, 2012.",emoji:"🎾"},
  {q:"How long is a Olympische Triathlon-Schwimmstrecke in km?",a:1.5,unit:"km",hint:"Dann 40km Radfahren und 10km run.",emoji:"🏊"},
  {q:"How many Punkte needs man im Squash pro Satz?",a:11,unit:"Punkte",hint:"Best of 5 Sätze.",emoji:"🎾"},
  {q:"How long is a Eishockeyfeld in meters?",a:61,unit:"meterss",hint:"× 30 meters – NHL-Standard.",emoji:"🏒"},
  {q:"How high is das Netz beim Beach-Volleyball at Männern?",a:2.43,unit:"meterss",hint:"Gleich wie Hallen-Volleyball.",emoji:"🏐"},
  {q:"How many players has a Fußball-Kader at der WM?",a:26,unit:"players",hint:"Seit der WM 2022.",emoji:"⚽"},
  {q:"How heavy is a Kugel beim Kugelstoßen at Männern in kg?",a:7.26,unit:"kg",hint:"at Frauen 4 kg.",emoji:"🏋️"},
  {q:"How long is a Bowlingbahn in meters?",a:18.29,unit:"meterss",hint:"of der Abwurflinie to den Pins.",emoji:"🎳"},
  {q:"How high is a Fußball-Tor at Frauen in meters?",a:2.44,unit:"meterss",hint:"Gleich wie at Männern.",emoji:"⚽"},
  {q:"How many Schritte macht a Marathonläufer?",a:40000,unit:"Schritte",hint:"Etwa 40.000 Schritte pro Marathon.",emoji:"🏃"},
  {q:"How long is a Biathlon-Lauf in km?",a:20,unit:"km",hint:"Plus 4 Schießeinlagen.",emoji:"🎯"},
  {q:"How many Runden dreht a Radfahrer at der Olympischen Bahn-Jagd?",a:16,unit:"Runden",hint:"4km on einer 250m-Bahn.",emoji:"🚴"},
  {q:"How many Punkte has a Golfball Grübchen?",a:336,unit:"Grübchen",hint:"Standard are 300-500 Dimples.",emoji:"⛳"},
  {q:"How long is a Olympische Kanu-Slalom-Strecke in meters?",a:250,unit:"meterss",hint:"with at least 18 Toren.",emoji:"🚣"},
  {q:"How high is a Turnhorse (Pauschenhorse) in meters?",a:1.15,unit:"meterss",hint:"Standarthöhe laut FIG.",emoji:"🤸"},
  {q:"How many km/h fährt a Ski-Abfahrtsfahrer maxitimes?",a:160,unit:"km/h",hint:"Die schnellste alpine Disziplin.",emoji:"⛷️"},
  {q:"How many players has a Curling-Team?",a:4,unit:"players",hint:"Ein Skip und drei Sweeper.",emoji:"🥌"},
  {q:"How long is a Olympische 400m-Hürdenstrecke?",a:400,unit:"meterss",hint:"10 Hürden à 91,4cm Höhe at Männern.",emoji:"🏃"},
  {q:"How heavy is a Hammerball beim Hammerwurf in kg?",a:7.26,unit:"kg",hint:"at Frauen 4 kg.",emoji:"🔨"},
  {q:"How many km/h schießt a Eishockey-Puck maxitimes?",a:175,unit:"km/h",hint:"at professionellen Slap Shots.",emoji:"🏒"},
  {q:"How many players has a Rugbyteam beim 7er-Rugby?",a:7,unit:"players",hint:"Weniger players, mehr Raum.",emoji:"🏉"},
  {q:"How high is a Sprungbrett beim Wasserspringen (Kunstspringen)?",a:3,unit:"meterss",hint:"Auch 1m-Brett und 10m-Turm.",emoji:"🏊"},
  {q:"How many Spiele has a NBA-Grunddurchgang?",a:82,unit:"Spiele",hint:"Jede Mannschaft spielt 82 Spiele.",emoji:"🏀"},
  {q:"How long is a Rhythmische Sportgymnastik-Seiltour in minutes?",a:1.5,unit:"minutes",hint:"75-90 seconds Pflichtprograms.",emoji:"🤸"},
  {q:"How many km legt a Radfahrer at der Tour de France daily zurück?",a:175,unit:"km",hint:"Durchschnitt over alle Etappen.",emoji:"🚴"},
  {q:"How high is the worldrekord im Stabhochsprung in meters?",a:6.23,unit:"meterss",hint:"Armand Duplantis 2024.",emoji:"🏃"},
  {q:"How many km/h erreicht a Profi-Tennisplayers beim Aufschlag?",a:230,unit:"km/h",hint:"Durchschnitt der Spitzenserveurs.",emoji:"🎾"},
  {q:"How many players has a Cricketteam beim Twenty20?",a:11,unit:"players",hint:"Gleich wie nortimeses Cricket.",emoji:"🏏"},
  {q:"How long takes a Judo-Partie maxitimes in minutes?",a:5,unit:"minutes",hint:"at Gleichstand: Golden Score.",emoji:"🥋"},
  {q:"How many km/h fährt a Eisschnellläufer on 500m?",a:60,unit:"km/h",hint:"Sprintdisziplin on Eis.",emoji:"⛸️"},
  {q:"How many Darts wirft man pro Aufnahme?",a:3,unit:"Darts",hint:"Drei Pfeile pro Zug.",emoji:"🎯"},
  {q:"How long is a Leichtathletik-Wurfbahn beim Speerwurf in meters?",a:4,unit:"meters Breite",hint:"Schtimese Bahn for den Anlauf.",emoji:"🎯"},
  {q:"How many minutes takes a Basketball-Halbzeit?",a:10,unit:"minutes",hint:"4 Viertel à 10 minutes (FIBA).",emoji:"🏀"},
  {q:"How heavy is a Fußball (offiziell) in grams?",a:430,unit:"grams",hint:"410-450 grams laut FIFA.",emoji:"⚽"},
  {q:"How long is die kürzeste olympische Laufdisziplin in meters?",a:100,unit:"meterss",hint:"Der Sprint over 100m.",emoji:"🏃"},
  {q:"How high is das Netz beim Badminton in meters?",a:1.55,unit:"meterss",hint:"in der Mitte 1,524m.",emoji:"🏸"},
  {q:"How many km/h schießt a Fußball beim härtesten Schuss?",a:210,unit:"km/h",hint:"of Profis at Schussrekorden.",emoji:"⚽"},
  {q:"How long is a Handball-Spielfeld in meters?",a:40,unit:"meterss",hint:"× 20 meters.",emoji:"🤾"},
  {q:"How many players has a Tug-of-was-Team?",a:8,unit:"players",hint:"Tauziehen – olympische Disziplin bis 1920.",emoji:"🏋️"},
  {q:"How long is a Bobbahn in meters?",a:1500,unit:"meterss",hint:"with vielen Kurven.",emoji:"🛷"},
  {q:"How many km/h erreicht a Luger beim Rodeln?",a:140,unit:"km/h",hint:"on dem Rücken liegend.",emoji:"🛷"},
  {q:"How many players has a Ringball-Team?",a:7,unit:"players",hint:"Südafrikanische Sportart.",emoji:"🏀"},
  {q:"How high is a Turnreck at Frauen in meters?",a:2.5,unit:"meterss",hint:"Hochreck for die Uneven Bars.",emoji:"🤸"},
  {q:"How many km long is a Biathlon-Staffel?",a:4,unit:"km pro Läufer",hint:"Läufer × 7.5km = 30km gesamt.",emoji:"🎿"},
  {q:"How many Punkte has a Snowboard-Halfpipe-Run maxitimes?",a:100,unit:"Punkte",hint:"Jurybewertung of 0-100.",emoji:"🏂"},
  {q:"How long is a Schwimm-Wettkampf beim Freisil maxitimes in meters?",a:1500,unit:"meterss",hint:"1500m Freisil is the longest Beckendisziplin.",emoji:"🏊"},
  {q:"How many km/h schleudert a Hammerwerfer den Hammer?",a:100,unit:"km/h",hint:"Der Hammer erreicht massive Geschwindigkeit.",emoji:"🔨"},
  {q:"How long is die Wettkampfstrecke beim Eisschnelllauf (kürzeste) in meters?",a:500,unit:"meterss",hint:"Die Sprintdisziplin.",emoji:"⛸️"},
  {q:"How many minutes takes a nortimeses Fußballspiel?",a:90,unit:"minutes",hint:"2 Halbzeiten à 45 minutes.",emoji:"⚽"},
  {q:"How many players has a Ultimate Frisbee-Team?",a:7,unit:"players",hint:"Vs 7 on dem Feld.",emoji:"🥏"},
  {q:"How high is a Wassersprung-Turm maxitimes in meters?",a:10,unit:"meterss",hint:"Die höchste olympische Sprunghöhe.",emoji:"🏊"},
  {q:"How many Kämpfe has a MMA-Profi per year?",a:3,unit:"Kämpfe",hint:"Etwa 2-4 Kämpfe per year.",emoji:"🥊"},
  {q:"How long is a Skisprungrampe (Nortimesschanze) in meters?",a:90,unit:"meters Sprungweite",hint:"Nortimesschanze = K90.",emoji:"🎿"},
  {q:"How many players has a Lacrosse Box-Team?",a:6,unit:"players",hint:"Indoor-Lacrosse with weniger playersn.",emoji:"🥍"},
  {q:"How long is a 110m-Hürdenlauf-Hurde in cm Höhe?",a:106.7,unit:"cm",hint:"for Männer.",emoji:"🏃"},
  {q:"How many km/h fährt a Rennradsportler beim Zeitfahren?",a:55,unit:"km/h",hint:"Tour-de-France Zeitfahrspezialisen.",emoji:"🚴"},
  {q:"How heavy is a Diskus at Männern in kg?",a:2,unit:"kg",hint:"at Frauen 1 kg.",emoji:"🥏"},
  {q:"How long is a Basketballfeld in meters?",a:28,unit:"meterss",hint:"× 15 meters FIBA-Standard.",emoji:"🏀"},
  {q:"How many Punkte needs man beim Squash for einen Satz?",a:11,unit:"Punkte",hint:"Neuere PAR-Regel.",emoji:"🎾"},
  {q:"How high is a Netz beim Tischtennis in cm?",a:15.25,unit:"cm",hint:"Sehr niedrig.",emoji:"🏓"},
  {q:"How long is a Leichtathletik-Weitsprung-Anlauf in meters?",a:40,unit:"meterss",hint:"on averageer Anlauf der Elite.",emoji:"🏃"},
  {q:"How many players has a Floorball-Team?",a:6,unit:"players",hint:"Inklusive Torwast.",emoji:"🏑"},
  {q:"How long is a Curling-Bahn in meters?",a:45,unit:"meterss",hint:"of Haus to Haus.",emoji:"🥌"},
  {q:"How many km/h erreicht a Bobteam im Eiskanal?",a:150,unit:"km/h",hint:"Viererbob on schnellen Strecken.",emoji:"🛷"},
  {q:"How many players has a Polo-Team?",a:4,unit:"players",hint:"Reiter on horseen.",emoji:"🐎"},
  {q:"How long is a Rugby-Partie in minutes?",a:80,unit:"minutes",hint:"2 Halbzeiten à 40 minutes.",emoji:"🏉"},
  {q:"How many players has a Sepak Takraw-Team?",a:3,unit:"players",hint:"Südostasiatischer Ballsport.",emoji:"🦵"},
  {q:"How long is a Biathlon-Strafschleife in meters?",a:150,unit:"meterss",hint:"for jeden verfehlten Schuss.",emoji:"🎿"},
  {q:"How high is der Weitsprung-world record at Frauen in meters?",a:7.52,unit:"meterss",hint:"Galina Chisyakova, 1988.",emoji:"🏃"},
  {q:"How many players has a Hockeyteam on dem Feld?",a:11,unit:"players",hint:"Feldhockey-Standard.",emoji:"🏑"},
  {q:"How long is a Radrenn-Mannschaftsverfolgung?",a:4,unit:"km",hint:"Km on der Bahn.",emoji:"🚴"},
  {q:"How heavy is a Schläger beim Eishockey in kg?",a:0.85,unit:"kg",hint:"Leicht for maxitimese Kontrolle.",emoji:"🏒"},
  {q:"How many players has a Gaelic-Football-Team?",a:15,unit:"players",hint:"Irischer Sport ähnlich wie Rugby.",emoji:"🏈"},
  {q:"How many km long is a Triathlon Ironman?",a:226,unit:"km",hint:"3,8km swim + 180km Rad + 42km run.",emoji:"🏊"},
  {q:"How high is a Schach-Turm on dem Brett in cm?",a:6,unit:"cm",hint:"Größte Figur to dem König.",emoji:"♟️"},
  {q:"How many players has a Handball-Team?",a:7,unit:"players",hint:"Inklusive Torwast.",emoji:"🤾"},
  {q:"How long is a Olympisches Gewichtheben-Wettkampftag?",a:10,unit:"hours",hint:"Alle Gewichtsklassen zusammen.",emoji:"🏋️"},
  {q:"How many km/h fährt a Downhill-Mountainbiker?",a:80,unit:"km/h",hint:"on extremen Strecken.",emoji:"🚵"},
  {q:"How many players has a Handball-Team on dem Feld?",a:7,unit:"players",hint:"6 Feldplayers plus Torwast.",emoji:"🤾"},
  {q:"How long is a Olympia-Laufstrecke beim 400m-Lauf?",a:400,unit:"meterss",hint:"Eine Runde um die Bahn.",emoji:"🏃"},
  {q:"How high is das Netz beim Badminton?",a:1.55,unit:"meterss",hint:"Etwas höher als beim Tennis.",emoji:"🏸"},
  {q:"How many Punkte needs man beim Dart um of 501 runterzuspielen?",a:501,unit:"Punkte",hint:"Genau on Null – nicht drunter.",emoji:"🎯"},
  {q:"How long is a Curling-Feld in meters?",a:42,unit:"meterss",hint:"Das Eis-Schach.",emoji:"🥌"},
  {q:"How many players has a American-Football-Team on dem Feld?",a:11,unit:"players",hint:"Offense gegen Defense – je 11.",emoji:"🏈"},
  {q:"How high is a Boxring in cm over dem Boden?",a:100,unit:"cm",hint:"approximately 1 meters over dem Hallenboden.",emoji:"🥊"},
  {q:"How many meters is beim Hochsprung-world record gesprungen?",a:2.45,unit:"meterss",hint:"Javier Sotomayor 1993.",emoji:"🏃"},
  {q:"How many km fährt a Tour-de-France-Sieger im Durchschnitt?",a:3500,unit:"km",hint:"over 21 Etappen.",emoji:"🚴"},
  {q:"How long takes a Eishockey-Spiel in minutes?",a:60,unit:"minutes",hint:"3 Drittel à 20 minutes.",emoji:"🏒"},
  {q:"How many Punkte is a Dreier beim Basketball wert?",a:3,unit:"Punkte",hint:"Hinter der Dreierlinie geworfen.",emoji:"🏀"},
  {q:"How long is a Olympia-Schwimmstrecke?",a:50,unit:"meterss",hint:"meters Langbahn.",emoji:"🏊"},
  {q:"How many Würfe has man beim Bowling pro Frame?",a:2,unit:"Würfe",hint:"Beim Strike nur 1 – beim 10. Frame bis to 3.",emoji:"🎳"},
  {q:"How many km/h flies a Badminton-Federball maxitimes?",a:493,unit:"km/h",hint:"Schnellstes Objekt im Sport.",emoji:"🏸"},
  {q:"How many meters tief is a Olympia-Schwimmbecken?",a:2,unit:"meterss",hint:"Mindesttiefe for internationale Wettkämpfe.",emoji:"🏊"},
  {q:"How long takes a Rugbyspiel in minutes?",a:80,unit:"minutes",hint:"2 Hälften à 40 minutes.",emoji:"🏉"},
  {q:"How many players stehen beim Volleyball on dem Feld?",a:6,unit:"players",hint:"Pro Seite.",emoji:"🏐"},
  {q:"How heavy is a Diskus at den Männern?",a:2,unit:"kg",hint:"Kg schwere Scheibe.",emoji:"🥏"},
  {q:"How many Runden has a Formel-1-Rennen in Monaco?",a:78,unit:"Runden",hint:"Kürzeste Strecke – daher mehr Runden.",emoji:"🏎️"},
  {q:"How high is a Turnhorse?",a:1.15,unit:"meterss",hint:"Olympisches Turngerät.",emoji:"🤸"},
  {q:"How many Goldmedaillen won Usain Bolt in total?",a:8,unit:"Goldmedaillen",hint:"3 Olympiaden – immer Gold over 100m und 200m.",emoji:"🥇"},
  {q:"How many meters is die Speerwurf-world recorddisanz?",a:98.48,unit:"meterss",hint:"Jan Železný 1996 in Jena.",emoji:"🎯"},
  {q:"How many km/h erreicht a Tennisball beim schärfsten Aufschlag?",a:263,unit:"km/h",hint:"Samuel Groth 2012.",emoji:"🎾"},
  {q:"How long is a Marathonlauf?",a:42.195,unit:"km",hint:"Benannt to dem Lauf of Marathon to Athen.",emoji:"🏃"},
  {q:"How many players has a Eishockey-Team on dem Eis?",a:6,unit:"players",hint:"5 Feldplayers plus Torwast.",emoji:"🏒"},
  {q:"How far springt man beim Weitsprung-world record?",a:8.95,unit:"meterss",hint:"Mike Powell 1991 in Tokio.",emoji:"🏃"},
  {q:"How many Punkte needs man beim Tennis um a Spiel to gewinnen?",a:4,unit:"Punkte",hint:"15 – 30 – 40 – Spiel.",emoji:"🎾"},
  {q:"How heavy is a Fußball in grams?",a:430,unit:"grams",hint:"410-450g to FIFA-Regeln.",emoji:"⚽"},
  {q:"How many km/h fährt a Downhill-Mountainbiker maxitimes?",a:130,unit:"km/h",hint:"on steilen Strecken.",emoji:"🚵"},
  {q:"How many Bahnen has a Olympia-Schwimmbecken?",a:8,unit:"Bahnen",hint:"Bahnen à 2,5 meters Breite.",emoji:"🏊"},
  {q:"How long is a Fußballspiel in minutes?",a:90,unit:"minutes",hint:"2 Hälften à 45 minutes.",emoji:"⚽"},
  {q:"How high is der Stabhochsprung-world record?",a:6.21,unit:"meterss",hint:"Armand Duplantis 2024.",emoji:"🏃"},
  {q:"How many players has a Baseball-Team on dem Feld?",a:9,unit:"players",hint:"Positionen on dem Feld.",emoji:"⚾"},
  {q:"How far wirft man beim Hammerwurf-world record?",a:86.74,unit:"meterss",hint:"Yuriy Sedykh 1986.",emoji:"🔨"},
  {q:"How many Runden besteht a Boxkampf maxitimes (Profis)?",a:12,unit:"Runden",hint:"Jede Runde 3 minutes.",emoji:"🥊"},
  {q:"How long is a Eisschnelllauf-Oval?",a:400,unit:"meterss",hint:"Standard-Eisschnelllaufbahn.",emoji:"⛸️"},
  {q:"How many km/h runs a Profifußballer maxitimes?",a:35,unit:"km/h",hint:"Beim Sprint.",emoji:"⚽"},
  {q:"How high is das Netz beim Tischtennis in cm?",a:15.25,unit:"cm",hint:"International standardisiert – überall gleich hoch.",emoji:"🏓"},
  {q:"How many meters has der 110m-Hürdenlauf?",a:110,unit:"meterss",hint:"10 Hürden à 1,067m Höhe.",emoji:"🏃"},
  {q:"How many Punkte is a Elfmeters-Tor im Fußball wert?",a:1,unit:"Tor",hint:"Wie jedes andere Tor auch.",emoji:"⚽"},
  {q:"How long is a Turniertennis-Platz?",a:23.77,unit:"meterss",hint:"23,77m × 8,23m (Einzel).",emoji:"🎾"},
  {q:"How heavy is a Kugel beim Kugelstoßen (Männer)?",a:7.26,unit:"kg",hint:"7,26 kg – fast a kleiner Bowlingball.",emoji:"🎱"},
  {q:"How many Torwürfe macht a Handballer per game?",a:8,unit:"Würfe",hint:"Im Durchschnitt.",emoji:"🤾"},
  {q:"How many km/h can a Profischwimmer in 50m erreichen?",a:8,unit:"km/h",hint:"Beim Sprint.",emoji:"🏊"},
  {q:"How long is der 4x100m Staffellauf in total?",a:400,unit:"meterss",hint:"4 Läufer je 100m.",emoji:"🏃"},
  {q:"How many players darf man beim Fußball einwechseln?",a:5,unit:"players",hint:"Seit 2020 – vorher nur 3.",emoji:"⚽"},
  {q:"How high is a Basketballkorb?",a:3.05,unit:"meterss",hint:"worldwide einheitlich – egal ob Profi oder Amateur.",emoji:"🏀"},
  {q:"How many km fährt a Triathlon beim langen Radabschnitt?",a:180,unit:"km",hint:"Beim Ironman: 3,8km swim – 180km Rad – 42km run.",emoji:"🚴"},
  {q:"How long is a Eiskunstlauf-Kür at den Damen?",a:4,unit:"minutes",hint:"minutes maxitimese Kürzeit.",emoji:"⛸️"},
  {q:"How many Punkte needs man beim Badminton for einen Satz?",a:21,unit:"Punkte",hint:"Best of 3 Sätze.",emoji:"🏸"},
  {q:"How many km legt a Tennisplayers pro Match zurück?",a:3,unit:"km",hint:"Je to Spiellänge.",emoji:"🎾"},
  {q:"How far springt man beim Dreisprung-world record?",a:18.29,unit:"meterss",hint:"Jonathan Edwasds 1995.",emoji:"🏃"},
  {q:"How many Tore schoss Lionel Messi at seiner Rekord-WM?",a:7,unit:"Tore",hint:"WM 2022 in Katar.",emoji:"⚽"},
  {q:"How long is a Kanuslalom-Strecke?",a:300,unit:"meterss",hint:"with Toren die durchfahren are müssen.",emoji:"🛶"},
  {q:"How many Felder has a Schachbrett?",a:64,unit:"Felder",hint:"8 times 8.",emoji:"♟️"},
  {q:"How heavy is a Boxhandschuh beim Profiboxen in Unzen?",a:10,unit:"Unzen",hint:"Profis have schwerere Handschuhe als im Training.",emoji:"🥊"},
  {q:"How many km swims man beim Ironman-Triathlon?",a:3.8,unit:"km",hint:"Start des längsten Triathlons.",emoji:"🏊"},
  {q:"How long is a Eisschnelllauf-500m-Strecke?",a:500,unit:"meterss",hint:"Schnellste Disziplin.",emoji:"⛸️"},
  {q:"How many Punkte needs man im Squash for a Spiel?",a:11,unit:"Punkte",hint:"Best of 5 Spiele.",emoji:"🎾"},
  {q:"How high is a Turnreck over dem Boden?",a:2.75,unit:"meterss",hint:"Olympisches Gerät.",emoji:"🤸"},
  {q:"How many km legt a Radprofi at der Tour de France daily zurück?",a:167,unit:"km",hint:"Durchschnitt over alle Etappen.",emoji:"🚴"},
  {q:"How many players has a Rugby-League-Team?",a:13,unit:"players",hint:"Rugby Union has 15.",emoji:"🏉"},
  {q:"How heavy is a Diskus at den Frauen?",a:1,unit:"kg",hint:"Halb so schwer wie at den Männern.",emoji:"🥏"},
  {q:"How long is a Wettkampf-Ruderboot (Achter)?",a:20,unit:"meterss",hint:"8 Ruderer plus Steuermann.",emoji:"🚣"},
  {q:"How many meters taucht a Freitaucher beim world record?",a:214,unit:"meterss",hint:"Herbert Nitsch – tiefster Mann the world.",emoji:"🤿"},
  {q:"How many km/h fährt a Profi-Radrennfahrer in der Spitze?",a:80,unit:"km/h",hint:"Im Sprint – bergab noch mehr.",emoji:"🚴"},
  {q:"How long is a Tischtennis-Tisch?",a:2.74,unit:"meterss",hint:"274cm × 152,5cm.",emoji:"🏓"},
  {q:"How many Runden besteht a Amateur-Boxkampf?",a:3,unit:"Runden",hint:"Olympisches Boxen: 3 Runden à 3 minutes.",emoji:"🥊"},
  {q:"How far schießt man beim Bogenschießen on der Olympia-Disanz?",a:70,unit:"meterss",hint:"meters at Olympia.",emoji:"🏹"},
  {q:"How high springt a Ski-Springer beim Nortimesschanzenrekord?",a:100,unit:"meterss",hint:"on der Nortimesschanze.",emoji:"⛷️"},
  {q:"How many players has a Curling-Team?",a:4,unit:"players",hint:"Einer wirft, drei kehren.",emoji:"🥌"},
  {q:"How long is a Biathlon-Lauf at den Herren?",a:20,unit:"km",hint:"Kombiniert Skilanglauf und Schießen.",emoji:"🎿"},
  {q:"How many Punkte needs man beim Volleyball for einen Satz?",a:25,unit:"Punkte",hint:"with 2 Punkten Vorsprung gewinnen.",emoji:"🏐"},
  {q:"How many km run Fußballer at einem Bundesligaspiel?",a:11,unit:"km",hint:"Durchschnitt pro players.",emoji:"⚽"},
  {q:"How heavy is a Olympia-Gewichtheber-Barbell?",a:20,unit:"kg",hint:"Die Stange selbst weighs 20kg.",emoji:"🏋️"},
  {q:"How long is a Handball-Spielfeld?",a:40,unit:"meterss",hint:"40m × 20m.",emoji:"🤾"},
  {q:"How many Runden has a Motorradrennen at der MotoGP?",a:27,unit:"Runden",hint:"Je to Strecke 20-30 Runden.",emoji:"🏍️"},
  {q:"How many players has a Wasserball-Team?",a:7,unit:"players",hint:"6 Feldplayers plus Torwast.",emoji:"🤽"},
  {q:"How long is a Hürde beim 110m-Lauf in cm Höhe?",a:106,unit:"cm",hint:"for Männer 106,7cm hoch.",emoji:"🏃"},
  {q:"How many Punkte is a Freiwurf beim Basketball wert?",a:1,unit:"Punkt",hint:"Vom Freiwurfstreifen.",emoji:"🏀"},
  {q:"How many minutes takes a Halbzeit beim Fußball?",a:45,unit:"minutes",hint:"Zwei Hälften à 45 minutes.",emoji:"⚽"},
  {q:"How many players has a Lacrosse-Team?",a:10,unit:"players",hint:"Feldplayers.",emoji:"🥍"},
  {q:"How high is das Tor beim Fußball in meters?",a:2.44,unit:"meterss",hint:"Höher als du denkst!",emoji:"⚽"},
];
