// 🌊 OCEANS & SEA – English
export default [
  {q:"How many oceans are there on Earth?",a:5,unit:"oceans",hint:"Pazifik, Atlantik, Indik, Arktis, Antarktis.",emoji:"🌊"},
  {q:"How deep is der Marianengraben in meters?",a:11034,unit:"meterss",hint:"Der tiefste Punkt the worldmeere.",emoji:"🌊"},
  {q:"How many percent Earth are of water bedeckt?",a:71,unit:"%",hint:"Deswegen heißt die Erde auch 'der blaue planet'.",emoji:"🌍"},
  {q:"How big is a fully grown Blauwhale in meters?",a:30,unit:"meterss",hint:"the largest animal on Earth.",emoji:"🐋"},
  {q:"How many Arme has a squid?",a:8,unit:"Arme",hint:"Arme plus 2 Fangarme beim octopus.",emoji:"🐙"},
  {q:"How many hearten has a squid?",a:3,unit:"hearten",hint:"Zwei Kiemenhearten und a Körperheart.",emoji:"🐙"},
  {q:"How deep can a Pottwhale tauchen in meters?",a:3000,unit:"meterss",hint:"Der tieftauchende Säuger the world.",emoji:"🐳"},
  {q:"How many species of Haien are there?",a:500,unit:"species",hint:"of winzig bis riesig.",emoji:"🦈"},
  {q:"How big is a Weißer shark in meters?",a:6,unit:"meterss",hint:"Der berühmteste Raubfisch.",emoji:"🦈"},
  {q:"How many km/h can a Schwertfisch swim?",a:110,unit:"km/h",hint:"Schnellster fish im sea.",emoji:"🐟"},
  {q:"How many million tons Müll landen annually im ocean?",a:8,unit:"million tons",hint:"Plastik is the largest Problem.",emoji:"♻️"},
  {q:"How many percent des Sauerstoffs produces der ocean?",a:50,unit:"%",hint:"Phytoplankton produces die Hälfte unseres Sauerstoffs.",emoji:"🌿"},
  {q:"How many meters lang is a Riesenkalmar?",a:13,unit:"meterss",hint:"Größtes animal ohne Wirbelsäule.",emoji:"🦑"},
  {q:"How many teeth has a Weißer shark?",a:300,unit:"teeth",hint:"in mehreren Reihen – ständig nachwachsend.",emoji:"🦷"},
  {q:"How many degrees Celsius is das Tiefseewasser?",a:2,unit:"°C",hint:"Fast eiskalt – das ganze Jahr.",emoji:"🌡️"},
  {q:"How many hours sleeps a dolphin daily?",a:8,unit:"hours",hint:"with einer brainhälfte – die andere bleibt wach.",emoji:"🐬"},
  {q:"How many species of Quallen are there?",a:3000,unit:"species",hint:"of kleinen dwarfsn bis to riesigen Mähnenquallen.",emoji:"🪼"},
  {q:"How many km/h swims a Seehorsechen?",a:1.5,unit:"km/h",hint:"Das langsamste fish im sea.",emoji:"🐠"},
  {q:"How many liters water filtert a Muschel per hour?",a:8,unit:"literss",hint:"Muscheln reinigen das Meerwasser.",emoji:"🦪"},
  {q:"How many km long is das Great Barrier Reef?",a:2300,unit:"km",hint:"the largest Lebewesen Earth.",emoji:"🪸"},
  {q:"How many percent der oceans are noch nicht erforscht?",a:80,unit:"%",hint:"Der Tiefseeboden is fremder als der moon.",emoji:"🔭"},
  {q:"How heavy is a Seestar maxitimes in grams?",a:500,unit:"grams",hint:"Je to Art.",emoji:"⭐"},
  {q:"How many kilometerss tief is der Pazifik on average?",a:4,unit:"km",hint:"4000 meters Durchschnitt.",emoji:"🌊"},
  {q:"How long can a Meeresschildkröte under water bleiben in hours?",a:7,unit:"hours",hint:"Im Schlaf noch länger.",emoji:"🐢"},
  {q:"How many Stacheln has a Igelfisch?",a:300,unit:"Stacheln",hint:"Er bläst sich on wenn er Angst has.",emoji:"🐡"},
  {q:"How many meters lang is a whalehai?",a:12,unit:"meterss",hint:"Größter fish the world – aber harmlos.",emoji:"🦈"},
  {q:"How many degrees Celsius is die Oberfläche des Meeres an einem heißen Tag?",a:30,unit:"°C",hint:"in tropischen Meeren.",emoji:"🌡️"},
  {q:"How many Eier legt a Meeresschildkröte pro Nest?",a:100,unit:"Eier",hint:"Nur wenige Babys überleben bis zum sea.",emoji:"🥚"},
  {q:"How many kilometerss tief is der Atlantik?",a:3.3,unit:"km",hint:"3300 meters Durchschnief.",emoji:"🌊"},
  {q:"How many million Tierspecies live im ocean?",a:700,unit:"thousand",hint:"000 becante species – viele noch unentdeckt.",emoji:"🐠"},
];
