// 🎯 FREE SAMPLER – English
export default [
  {q:"How many Beine hat eine Spinne?",a:8,unit:"Beine",hint:"Spinnen sind keine Insekten – Insekten haben nur 6 Beine!",emoji:"🕷️"},
  {q:"How high ist der Mount Everest in Metern?",a:8849,unit:"meters",hint:"Er ist der höchste Berg der Erde.",emoji:"🏔️"},
  {q:"How many Farben hat ein Regenbogen?",a:7,unit:"Farben",hint:"Rot, Orange, Gelb, Grün, Blau, Indigo, Violett.",emoji:"🌈"},
  {q:"How many Planeten gibt es in unserem Sonnensystem?",a:8,unit:"Planeten",hint:"Pluto zählt seit 2006 nicht mehr dazu.",emoji:"🪐"},
  {q:"How many Zähne hat ein Erwachsener?",a:32,unit:"teeth",hint:"Inklusive der Weisheitszähne.",emoji:"🦷"},
  {q:"How many Stunden hat ein Tag?",a:24,unit:"hours",hint:"Die Erde dreht sich einmal in 24 Stunden um ihre Achse.",emoji:"⏰"},
  {q:"How many Herzen hat ein Tintenfisch?",a:3,unit:"Herzen",hint:"Zwei pumpen Blut zu den Kiemen, eines zum Körper.",emoji:"🐙"},
  {q:"How fast kann ein Gepard laufen in km/h?",a:112,unit:"km/h",hint:"Er ist das schnellste Landtier der Welt.",emoji:"🐆"},
  {q:"How many km ist es von der Erde zum Mond?",a:384400,unit:"km",hint:"Die Apollo-Astronauten brauchten 3 Tage dorthin.",emoji:"🌙"},
  {q:"How many Knochen hat ein Erwachsener?",a:206,unit:"bones",hint:"Babys haben noch 270 – viele wachsen zusammen.",emoji:"🦴"},
  {q:"Wie alt kann eine Schildkröte werden in Jahren?",a:150,unit:"years",hint:"Manche Schildkröten werden über 200 Jahre alt!",emoji:"🐢"},
  {q:"How many Kontinente gibt es auf der Erde?",a:7,unit:"Kontinente",hint:"Afrika, Amerika (2), Antarktika, Asien, Australien, Europa.",emoji:"🌍"},
  {q:"How big war der größte Dinosaurier in Metern?",a:40,unit:"meters",hint:"Der Argentinosaurus war der längste bekannte Dinosaurier.",emoji:"🦕"},
  {q:"How many Augen hat eine Biene?",a:5,unit:"Augen",hint:"2 große Facettenaugen und 3 kleine Punktaugen oben.",emoji:"🐝"},
  {q:"How many Minuten braucht Sonnenlicht bis zur Erde?",a:8,unit:"minutes",hint:"Licht reist mit 300.000 km pro Sekunde.",emoji:"☀️"},
  {q:"How many Beine hat ein Insekt?",a:6,unit:"Beine",hint:"Insekten haben immer 6 Beine – Spinnen 8.",emoji:"🐛"},
  {q:"How many Zähne hat ein Kleinkind (Milchzähne)?",a:20,unit:"teeth",hint:"Erwachsene haben 32.",emoji:"🦷"},
  {q:"How many Farben hat die deutsche Flagge?",a:3,unit:"Farben",hint:"Schwarz, Rot, Gold.",emoji:"🇩🇪"},
  {q:"How many Tage hat ein Schaltjahr?",a:366,unit:"days",hint:"Alle 4 Jahre kommt ein 29. Februar dazu.",emoji:"📅"},
  {q:"How many Finger hat a human?",a:10,unit:"Finger",hint:"5 an jeder Hand.",emoji:"✋"},
  {q:"How many Jahreszeiten gibt es?",a:4,unit:"Jahreszeiten",hint:"Frühling, Sommer, Herbst, Winter.",emoji:"🌸"},
  {q:"How many Seiten hat ein Würfel?",a:6,unit:"Seiten",hint:"Alle zusammen ergeben immer 21.",emoji:"🎲"},
  {q:"How many Minuten hat eine Stunde?",a:60,unit:"minutes",hint:"Minuten × 24 Stunden = 1440 Minuten per day.",emoji:"⏰"},
  {q:"How many Buchstaben hat das Alphabet?",a:26,unit:"Buchstaben",hint:"Von A bis Z.",emoji:"🔤"},
  {q:"How many Sinne hat a human?",a:5,unit:"Sinne",hint:"Sehen, Hören, Riechen, Schmecken, Tasten.",emoji:"👁️"},
  {q:"How many Monate hat ein Jahr?",a:12,unit:"months",hint:"Von Januar bis Dezember.",emoji:"📅"},
  {q:"How many Wochen hat ein Jahr?",a:52,unit:"weeks",hint:"Wochen und 1 Tag.",emoji:"📅"},
  {q:"How many cm hat ein Meter?",a:100,unit:"cm",hint:"10 cm = 1 dm, 10 dm = 1 m.",emoji:"📏"},
  {q:"How many Seiten hat ein Dreieck?",a:3,unit:"Seiten",hint:"Tri = drei.",emoji:"🔺"},
  {q:"How many Meter hat ein Kilometer?",a:1000,unit:"meters",hint:"Kilo bedeutet tausend.",emoji:"📏"},
  {q:"How many Grad hat ein Kreis?",a:360,unit:"Grad",hint:"Alte babylonische Konvention.",emoji:"⭕"},
  {q:"How many Continente hat die Erde?",a:7,unit:"Kontinente",hint:"Afrika, Amerika (2), Antarktika, Asien, Australien, Europa.",emoji:"🌍"},
  {q:"How many Tage hat der Februar in einem normalen Jahr?",a:28,unit:"days",hint:"Außer im Schaltjahr – dann 29.",emoji:"📅"},
  {q:"How many Zähne hat ein Erwachsener ohne Weisheitszähne?",a:28,unit:"teeth",hint:"Mit Weisheitszähnen 32.",emoji:"🦷"},
  {q:"How many Sekunden hat eine Minute?",a:60,unit:"seconds",hint:"× 60 = 3600 Sekunden per hour.",emoji:"⏱️"},
  {q:"How many Seiten hat ein Quadrat?",a:4,unit:"Seiten",hint:"Alle gleich lang.",emoji:"🟦"},
  {q:"How many kg hat eine Tonne?",a:1000,unit:"kg",hint:"Kg = 1 Tonne.",emoji:"⚖️"},
  {q:"How many Spieler hat eine Fußballmannschaft?",a:11,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"⚽"},
  {q:"How many Beine hat ein Oktopus?",a:8,unit:"Arme",hint:"Oktopus = 8 Arme.",emoji:"🐙"},
  {q:"How many Kontinente berührt der Äquator?",a:3,unit:"Kontinente",hint:"Afrika, Südamerika, Asien.",emoji:"🌍"},
  {q:"How many Noten hat eine Oktave?",a:8,unit:"Noten",hint:"C, D, E, F, G, A, H, C.",emoji:"🎵"},
  {q:"How many Stunden hat eine Woche?",a:168,unit:"hours",hint:"7 Tage × 24 Stunden.",emoji:"⏰"},
  {q:"How many Gramm hat ein Kilogramm?",a:1000,unit:"grams",hint:"1 kg = 1000 g.",emoji:"⚖️"},
  {q:"How many Millimeter hat ein Zentimeter?",a:10,unit:"mm",hint:"Mm = 1 cm.",emoji:"📏"},
  {q:"How many Sekunden hat eine Stunde?",a:3600,unit:"seconds",hint:"60 × 60 = 3600.",emoji:"⏱️"},
  {q:"How many Spieler spielen gegeneinander beim Tennis (Einzel)?",a:2,unit:"Spieler",hint:"1 gegen 1.",emoji:"🎾"},
  {q:"How many Grundfarben gibt es beim Malen?",a:3,unit:"Farben",hint:"Rot, Gelb, Blau.",emoji:"🎨"},
  {q:"How many Tage hat ein Jahr?",a:365,unit:"days",hint:"Außer im Schaltjahr – dann 366.",emoji:"📅"},
  {q:"How many Planeten sind kleiner als die Erde im Sonnensystem?",a:2,unit:"Planeten",hint:"Merkur und Mars.",emoji:"🪐"},
  {q:"How many Meter tief ist ein olympisches Schwimmbecken?",a:2,unit:"meters",hint:"Mindesttiefe 2 Meter.",emoji:"🏊"},
  {q:"How many Ohren hat a human?",a:2,unit:"Ohren",hint:"Links und rechts.",emoji:"👂"},
  {q:"How many Farben hat ein Regenbogen?",a:7,unit:"Farben",hint:"ROYGBIV – Rot, Orange, Gelb, Grün, Blau, Indigo, Violett.",emoji:"🌈"},
  {q:"How many Bundesländer hat Deutschland?",a:16,unit:"Bundesländer",hint:"3 Stadtstaaten und 13 Flächenländer.",emoji:"🇩🇪"},
  {q:"How many Ecken hat ein Sechseck?",a:6,unit:"Ecken",hint:"Wie eine Bienenwabe.",emoji:"⬡"},
  {q:"How many Zehen hat a human?",a:10,unit:"Zehen",hint:"5 an jedem Fuß.",emoji:"🦶"},
  {q:"How many Seiten hat ein Pentagon?",a:5,unit:"Seiten",hint:"Penta = fünf.",emoji:"⭐"},
  {q:"How many Stunden hat ein halber Tag?",a:12,unit:"hours",hint:"Die Hälfte von 24.",emoji:"⏰"},
  {q:"How many Milimeter hat ein Meter?",a:1000,unit:"mm",hint:"10 × 10 × 10 = 1000.",emoji:"📏"},
  {q:"How many Knochen hat ein Erwachsener?",a:206,unit:"bones",hint:"Babys haben noch 270.",emoji:"🦴"},
  {q:"How many Buchstaben hat das Wort ELEFANT?",a:7,unit:"Buchstaben",hint:"E-L-E-F-A-N-T.",emoji:"🐘"},
  {q:"How many Tage hat der Monat September?",a:30,unit:"days",hint:"April, Juni, September, November haben 30 Tage.",emoji:"📅"},
  {q:"How many Seiten hat ein Oktagon?",a:8,unit:"Seiten",hint:"Octo = acht – wie ein Stop-Schild.",emoji:"🔴"},
  {q:"How many Flügel hat ein Schmetterling?",a:4,unit:"Flügel",hint:"2 Vorder- und 2 Hinterflügel.",emoji:"🦋"},
  {q:"How many Saiten hat eine Geige?",a:4,unit:"Saiten",hint:"G, D, A, E.",emoji:"🎻"},
  {q:"How many Punkte hat ein Würfel auf allen Seiten zusammen?",a:21,unit:"Punkte",hint:"1+2+3+4+5+6 = 21.",emoji:"🎲"},
  {q:"How many Knöchel hat a human pro Hand?",a:3,unit:"Knöchel",hint:"Jeder Finger hat 3 Gelenke.",emoji:"✋"},
  {q:"How many Milliliter hat ein Liter?",a:1000,unit:"ml",hint:"1 Liter = 1000 ml.",emoji:"💧"},
  {q:"How many Sekunden hat ein Tag?",a:86400,unit:"seconds",hint:"24 × 60 × 60 = 86.400.",emoji:"⏱️"},
  {q:"How many Kegelseiten hat ein Kegel?",a:1,unit:"Seitenfläche",hint:"Eine gebogene Fläche plus Kreis-Boden.",emoji:"🍦"},
  {q:"How many Tier-Beine haben Katze und Hund zusammen?",a:8,unit:"Beine",hint:"4 + 4 = 8.",emoji:"🐱"},
  {q:"How many Stunden schläft ein Baby daily?",a:16,unit:"hours",hint:"Neugeborene schlafen sehr viel.",emoji:"👶"},
  {q:"How many Tage hat eine Woche?",a:7,unit:"days",hint:"Von Montag bis Sonntag.",emoji:"📅"},
  {q:"How many km/h fährt ein Fahrrad on average?",a:15,unit:"km/h",hint:"Freizeitradler fahren 12-20 km/h.",emoji:"🚴"},
  {q:"How many Linsen hat eine Kamera?",a:1,unit:"Linse",hint:"Manche Kameras haben mehrere – die meisten eine.",emoji:"📷"},
  {q:"How many Seiten hat ein Oktaeder?",a:8,unit:"Seiten",hint:"Dreiecke.",emoji:"🔷"},
  {q:"How many Liter Wasser trinkt a human daily?",a:2,unit:"liters",hint:"Empfohlen werden 1,5-2 Liter.",emoji:"💧"},
  {q:"How many Farben hat die österreichische Flagge?",a:2,unit:"Farben",hint:"Rot und Weiß.",emoji:"🇦🇹"},
  {q:"How many Ecken hat ein Achteck?",a:8,unit:"Ecken",hint:"Octo = 8.",emoji:"🔴"},
  {q:"How many Ohren hat ein Kaninchen?",a:2,unit:"Ohren",hint:"Sehr lange Ohren.",emoji:"🐇"},
  {q:"How many Beine hat ein Stuhl meistens?",a:4,unit:"Beine",hint:"Manchmal auch 3 oder 5.",emoji:"🪑"},
  {q:"How many Knöpfe hat ein normaler Taschenrechner?",a:36,unit:"Tasten",hint:"Je nach Modell.",emoji:"🔢"},
  {q:"How many Farben hat die Schweizer Flagge?",a:2,unit:"Farben",hint:"Rot und Weiß.",emoji:"🇨🇭"},
  {q:"How many Minuten hat ein halber Tag?",a:720,unit:"minutes",hint:"12 × 60 = 720.",emoji:"⏰"},
  {q:"How many Seiten hat ein Dodekaeder?",a:12,unit:"Seiten",hint:"Dodeka = 12.",emoji:"🔷"},
  {q:"How many Tage hat der Oktober?",a:31,unit:"days",hint:"Januar, März, Mai, Juli, August, Oktober, Dezember: 31 Tage.",emoji:"📅"},
  {q:"How many Kerzen hat ein Geburtstagskuchen für ein 10-jähriges Kind?",a:10,unit:"Kerzen",hint:"Eine Kerze pro Lebensjahr.",emoji:"🎂"},
  {q:"How many Planeten sind größer als die Erde im Sonnensystem?",a:4,unit:"Planeten",hint:"Jupiter, Saturn, Uranus, Neptun.",emoji:"🪐"},
  {q:"How many Noten gibt es in einem Dur-Dreiklang?",a:3,unit:"Noten",hint:"Grundton, Terz, Quinte.",emoji:"🎵"},
  {q:"How many Räder hat ein Dreirad?",a:3,unit:"Räder",hint:"Drei = Tri.",emoji:"🚲"},
  {q:"How many Flossen hat ein typischer Fisch?",a:7,unit:"Flossen",hint:"Rücken-, Bauch-, Brust-, After- und Schwanzflosse.",emoji:"🐟"},
  {q:"How many Beine hat ein Hund?",a:4,unit:"Beine",hint:"Vierbeiner.",emoji:"🐕"},
  {q:"How many Schüsse hat ein Elfmeter?",a:1,unit:"Schuss",hint:"Ein Versuch – bei Wiederholung wieder einer.",emoji:"⚽"},
  {q:"How many Hörner hat ein Einhorn?",a:1,unit:"Horn",hint:"Ein Horn – daher Einhorn.",emoji:"🦄"},
  {q:"How many Zacken hat eine Schneeflocke?",a:6,unit:"Zacken",hint:"Alle Schneeflocken haben 6-fache Symmetrie.",emoji:"❄️"},
  {q:"How many Reifen hat ein Auto?",a:4,unit:"Reifen",hint:"Plus ein Ersatzreifen.",emoji:"🚗"},
  {q:"How many Zähne verliert a child?",a:20,unit:"Milchzähne",hint:"Alle 20 Milchzähne fallen aus.",emoji:"🦷"},
  {q:"How many Beine hat eine Ente?",a:2,unit:"Beine",hint:"Alle Vögel haben 2 Beine.",emoji:"🦆"},
  {q:"How many Sterne sind auf der EU-Flagge?",a:12,unit:"Sterne",hint:"Immer 12 – egal wie viele Mitglieder.",emoji:"🇪🇺"},
  {q:"How many Würfel braucht man für Mensch Ärger dich nicht?",a:1,unit:"Würfel",hint:"Nur ein Würfel wird geworfen.",emoji:"🎲"},
  {q:"How many Spielkarten hat ein normales Kartendeck?",a:52,unit:"Karten",hint:"4 Farben × 13 Karten.",emoji:"🃏"},
  {q:"How many Pfoten hat eine Katze?",a:4,unit:"Pfoten",hint:"Vorderläufe und Hinterläufe.",emoji:"🐱"},
  {q:"How many Augen hat ein Cyclop?",a:1,unit:"Auge",hint:"Cyclops aus der griechischen Mythologie.",emoji:"👁️"},
  {q:"How many Stunden hat ein Wochentag?",a:24,unit:"hours",hint:"Jeder Tag hat 24 Stunden.",emoji:"⏰"},
  {q:"How many Seiten hat eine Pyramide mit quadratischer Basis?",a:5,unit:"Seiten",hint:"4 Dreiecke + 1 Quadrat unten.",emoji:"🔺"},
  {q:"How many Schritte macht a human daily?",a:8000,unit:"Schritte",hint:"Durchschnitt ca. 7.000-10.000.",emoji:"🚶"},
  {q:"How many Tage hat der Monat April?",a:30,unit:"days",hint:"April, Juni, September, November: 30 Tage.",emoji:"📅"},
  {q:"How many Liter fasst ein normaler Eimer?",a:10,unit:"liters",hint:"Standard-Eimer fasst 10 Liter.",emoji:"🪣"},
  {q:"How many Buchstaben hat das deutsche Wort SCHMETTERLING?",a:13,unit:"Buchstaben",hint:"S-C-H-M-E-T-T-E-R-L-I-N-G.",emoji:"🦋"},
  {q:"How many Beine hat eine Libelle?",a:6,unit:"Beine",hint:"Alle Insekten haben genau 6 Beine.",emoji:"🪲"},
  {q:"How many Zähne hat ein erwachsener Mensch?",a:32,unit:"teeth",hint:"Inklusive der Weisheitszähne.",emoji:"🦷"},
  {q:"How deep ist der tiefste See der Welt (Baikalsee)?",a:1642,unit:"meters",hint:"In Russland – so tief wie 5 Eiffeltürme.",emoji:"💧"},
  {q:"How many Planeten gibt es in unserem Sonnensystem?",a:8,unit:"Planeten",hint:"Pluto zählt seit 2006 nicht mehr dazu.",emoji:"🪐"},
  {q:"How heavy ist ein neugeborenes Baby on average in kg?",a:3.4,unit:"kg",hint:"Zwischen 2,5 und 4,5 kg ist normal.",emoji:"👶"},
  {q:"How many Stunden hat eine Woche?",a:168,unit:"hours",hint:"7 Tage × 24 Stunden.",emoji:"📅"},
  {q:"How many Seiten hat ein Würfel?",a:6,unit:"Seiten",hint:"1, 2, 3, 4, 5, 6.",emoji:"🎲"},
  {q:"How long is ein Schuljahr in Deutschland in Wochen?",a:40,unit:"weeks",hint:"Mit ca. 12 Wochen Ferien.",emoji:"🏫"},
  {q:"How many Minuten hat ein halber Tag?",a:720,unit:"minutes",hint:"12 Stunden × 60 Minuten.",emoji:"⏰"},
  {q:"How many Knochen hat ein Neugeborenes?",a:270,unit:"bones",hint:"Mehr als Erwachsene – viele wachsen zusammen.",emoji:"🦴"},
  {q:"How many Rippen hat a human?",a:24,unit:"Rippen",hint:"12 Paare – linke und rechte Seite.",emoji:"🦴"},
  {q:"How many Liter Blut hat a child mit 10 Jahren?",a:3,unit:"liters",hint:"Erwachsene haben etwa 5-6 Liter.",emoji:"🩸"},
  {q:"How many km/h läuft der schnellste Mensch?",a:45,unit:"km/h",hint:"Usain Bolt erreichte 44,7 km/h.",emoji:"⚡"},
  {q:"How many Länder gibt es in Europa?",a:44,unit:"countries",hint:"Je nach Zählung 44-50 Länder.",emoji:"🗺️"},
  {q:"How many Monate hat ein Jahr?",a:12,unit:"months",hint:"Januar bis Dezember.",emoji:"📅"},
  {q:"How many Buchstaben hat das Alphabet?",a:26,unit:"Buchstaben",hint:"Ohne Umlaute.",emoji:"🔤"},
  {q:"How many Ecken hat ein Dreieck?",a:3,unit:"Ecken",hint:"Tri = drei.",emoji:"🔺"},
  {q:"How many Sekunden hat eine Minute?",a:60,unit:"seconds",hint:"Teilt sich perfekt durch viele Zahlen.",emoji:"⏱️"},
  {q:"How many Tage hat ein Schaltjahr?",a:366,unit:"days",hint:"Der Februar hat einen Extra-Tag.",emoji:"📅"},
  {q:"How high fliegt ein Flugzeug normalerweise in Metern?",a:10000,unit:"meters",hint:"Reiseflughöhe bei 9000-12000 Metern.",emoji:"✈️"},
  {q:"How many Finger hat a human an beiden Händen?",a:10,unit:"Finger",hint:"5 pro Hand.",emoji:"🖐️"},
  {q:"How many Zehen hat a human an beiden Füßen?",a:10,unit:"Zehen",hint:"5 pro Fuß.",emoji:"🦶"},
  {q:"How many Kalorien hat ein Apfel ungefähr?",a:80,unit:"kcal",hint:"Ein mittelgroßer Apfel.",emoji:"🍎"},
  {q:"How many Minuten dauert ein normaler Film?",a:100,unit:"minutes",hint:"Die meisten Kinofilme sind 90-120 Minuten lang.",emoji:"🎬"},
  {q:"How many Punkte hat ein Stern normalerweise?",a:5,unit:"Punkte",hint:"Der klassische Stern hat 5 Zacken.",emoji:"⭐"},
  {q:"How many Augen hat a human?",a:2,unit:"Augen",hint:"Vorderseitig – für räumliches Sehen.",emoji:"👁️"},
  {q:"How many Seiten hat ein Rechteck?",a:4,unit:"Seiten",hint:"Vier Seiten – je zwei gleich lang.",emoji:"▭"},
  {q:"How many Wochen hat ein Jahr?",a:52,unit:"weeks",hint:"Genauer: 52 Wochen und 1-2 Tage.",emoji:"📅"},
  {q:"How many Kilogramm hat eine Tonne?",a:1000,unit:"kg",hint:"Kg = 1 Tonne.",emoji:"⚖️"},
  {q:"How many Minuten dauert eine Schulstunde?",a:45,unit:"minutes",hint:"Die Standard-Schulstunde in Deutschland.",emoji:"🏫"},
  {q:"How many Beine hat ein Oktopus?",a:8,unit:"Arme",hint:"Oktopus bedeutet 'acht Füße' auf Griechisch.",emoji:"🐙"},
  {q:"How many Gramm hat ein Kilogramm?",a:1000,unit:"grams",hint:"Kilo kommt vom griechischen 'chilioi' = tausend.",emoji:"⚖️"},
  {q:"How many Meter sind ein Kilometer?",a:1000,unit:"meters",hint:"Kilo = tausend.",emoji:"📏"},
  {q:"How many Seiten hat ein Pentagon?",a:5,unit:"Seiten",hint:"Penta = fünf.",emoji:"⬠"},
  {q:"How many Tage hat der Februar in einem normalen Jahr?",a:28,unit:"days",hint:"Im Schaltjahr 29.",emoji:"📅"},
  {q:"How many Beine hat eine Krabbe?",a:10,unit:"Beine",hint:"Zehn Beine – dazu zwei Scheren.",emoji:"🦀"},
  {q:"How many Stunden hat ein halbes Jahr?",a:4380,unit:"hours",hint:"182,5 Tage × 24 Stunden.",emoji:"⏰"},
  {q:"How many Seiten hat ein Hexagon?",a:6,unit:"Seiten",hint:"Hexa = sechs – wie Bienenwaben.",emoji:"⬡"},
  {q:"How many Zähne hat ein Milchgebiss?",a:20,unit:"teeth",hint:"Kinder haben 20 Milchzähne.",emoji:"🦷"},
  {q:"How many Knochen hat ein Erwachsener?",a:206,unit:"bones",hint:"Als Baby hatte man noch 270.",emoji:"🦴"},
  {q:"How many Gramm hat eine Tafel Schokolade normalerweise?",a:100,unit:"grams",hint:"Eine Standard-Schokoladentafel.",emoji:"🍫"},
  {q:"How many Stunden dauert ein Langstreckenflug nach New York?",a:9,unit:"hours",hint:"Von Frankfurt ungefähr 8-10 Stunden.",emoji:"✈️"},
  {q:"How many Kontinente gibt es auf der Erde?",a:7,unit:"Kontinente",hint:"Afrika, Antarktika, Asien, Australien, Europa, Nordamerika, Südamerika.",emoji:"🌍"},
  {q:"How many Schritte hat eine Treppe normalerweise pro Etage?",a:16,unit:"Stufen",hint:"Durchschnittlich 15-18 Stufen.",emoji:"🏢"},
  {q:"How many Farben hat ein Regenbogen?",a:7,unit:"Farben",hint:"Rot, Orange, Gelb, Grün, Blau, Indigo, Violett.",emoji:"🌈"},
  {q:"How many Liter Wasser soll man daily trinken?",a:1.5,unit:"liters",hint:"Empfehlung für Kinder: 1-1,5 Liter.",emoji:"💧"},
  {q:"How many Stunden schläft ein Grundschulkind pro Nacht?",a:10,unit:"hours",hint:"9-11 Stunden sind empfohlen.",emoji:"😴"},
  {q:"How many Grad hat ein Vollkreis?",a:360,unit:"Grad",hint:"Eine volle Umdrehung.",emoji:"⭕"},
  {q:"How many cm hat ein Meter?",a:100,unit:"cm",hint:"Zentimeter = 1 Meter.",emoji:"📏"},
  {q:"How many Seiten hat ein Oktagon?",a:8,unit:"Seiten",hint:"Okto = acht – wie ein Stoppschild.",emoji:"🛑"},
  {q:"How many Monate hat ein Schuljahr?",a:10,unit:"months",hint:"September bis Juni mit Sommerferien.",emoji:"🏫"},
  {q:"How many Beine hat eine Ameise?",a:6,unit:"Beine",hint:"Alle Insekten haben 6 Beine.",emoji:"🐜"},
  {q:"How many Liter hat ein Wassereimer?",a:10,unit:"liters",hint:"Ein Standard-Haushaltseimer fasst 10 Liter.",emoji:"🪣"},
  {q:"How many Stockwerke hat ein typisches Einfamilienhaus?",a:2,unit:"Stockwerke",hint:"Erdgeschoss und ein Obergeschoss.",emoji:"🏠"},
  {q:"How many Minuten hat ein Viertelstunde?",a:15,unit:"minutes",hint:"Ein Viertel von 60 Minuten.",emoji:"⏰"},
  {q:"How many Beine hat eine Spinne?",a:8,unit:"Beine",hint:"Spinnen sind keine Insekten.",emoji:"🕷️"},
  {q:"How many Punkte hat ein Würfel insgesamt auf allen Seiten?",a:21,unit:"Punkte",hint:"1+2+3+4+5+6 = 21.",emoji:"🎲"},
  {q:"How many cm sind ein Dezimeter?",a:10,unit:"cm",hint:"Dezi = zehn.",emoji:"📏"},
  {q:"How many Seiten hat ein Dreieck?",a:3,unit:"Seiten",hint:"Tri = drei.",emoji:"🔺"},
  {q:"How many Monate hat ein Vierteljahr?",a:3,unit:"months",hint:"Ein Viertel von 12 Monaten.",emoji:"📅"},
  {q:"How many Liter fasst ein Badewanne?",a:150,unit:"liters",hint:"Eine typische Badewanne fasst 120-180 Liter.",emoji:"🛁"},
  {q:"How many Zähne hat ein ausgewachsener Hund?",a:42,unit:"teeth",hint:"Mehr als humans.",emoji:"🐕"},
  {q:"How many Farben hat der Regenbogen zusammen?",a:7,unit:"Farben",hint:"Alle Spektralfarben zusammen.",emoji:"🌈"},
  {q:"How many Wochentage gibt es?",a:7,unit:"days",hint:"Mo, Di, Mi, Do, Fr, Sa, So.",emoji:"📅"},
  {q:"How many Buchstaben hat das Wort SCHULE?",a:6,unit:"Buchstaben",hint:"S-C-H-U-L-E.",emoji:"🏫"},
  {q:"How many Minuten hat eine halbe Stunde?",a:30,unit:"minutes",hint:"Die Hälfte von 60 Minuten.",emoji:"⏰"},
  {q:"How many Tage hat der März?",a:31,unit:"days",hint:"Tage – dritter Monat.",emoji:"📅"},
  {q:"How many Bundesländer hat Deutschland?",a:16,unit:"Bundesländer",hint:"Länder – Bayern ist das größte.",emoji:"🇩🇪"},
  {q:"How many Meter tief ist ein Hallenbad?",a:2,unit:"meters",hint:"Meistens 1,80-2m Tiefe.",emoji:"🏊"},
  {q:"How many Zähne hat ein Hase?",a:28,unit:"teeth",hint:"Nagetiere mit ständig wachsenden Vorderzähnen.",emoji:"🐇"},
  {q:"How many Seiten hat ein Quadrat?",a:4,unit:"Seiten",hint:"Alle Seiten gleich lang.",emoji:"⬛"},
  {q:"How many Liter fasst ein Rucksack?",a:20,unit:"liters",hint:"Schulrucksäcke fassen 15-25 Liter.",emoji:"🎒"},
  {q:"How many Monate hat ein Halbjahr?",a:6,unit:"months",hint:"Die Hälfte von 12 Monaten.",emoji:"📅"},
  {q:"How many km/h fährt eine S-Bahn on average?",a:60,unit:"km/h",hint:"Mit Halten etwa 40-60 km/h Durchschnitt.",emoji:"🚊"},
  {q:"How many Stunden braucht man für 100km zu Fuß?",a:25,unit:"hours",hint:"Bei 4 km/h Gehgeschwindigkeit.",emoji:"🚶"},
  {q:"How many Stühle passen an einen normalen Esstisch?",a:6,unit:"Stühle",hint:"Runder oder ovaler 6-Personen-Tisch.",emoji:"🪑"},
  {q:"How many Gramm hat ein Schokoriegel?",a:50,unit:"grams",hint:"Typische Größe eines Schokoriegels.",emoji:"🍫"},
  {q:"How many Kilos hat ein Sack Kartoffeln?",a:10,unit:"kg",hint:"Standard-Kartoffelsack.",emoji:"🥔"},
  {q:"How many Buchstaben hat das Alphabet inklusive Umlauten?",a:29,unit:"Buchstaben",hint:"26 + ä, ö, ü = 29.",emoji:"🔤"},
  {q:"How many Beine hat eine Zecke?",a:8,unit:"Beine",hint:"Zecken sind Spinnentiere.",emoji:"🕷️"},
  {q:"How many Tage hat ein Jahr im Durchschnitt?",a:365.25,unit:"days",hint:"365 Tage plus ein Viertel – daher alle 4 Jahre Schaltjahr.",emoji:"📅"},
  {q:"How many Minuten schaut a child daily on average TV?",a:90,unit:"minutes",hint:"Laut Studien etwa 1,5 Stunden daily.",emoji:"📺"},
  {q:"How many Stunden schläft ein Baby per day?",a:16,unit:"hours",hint:"Neugeborene schlafen fast den ganzen Tag.",emoji:"👶"},
  {q:"How many Stufen hat die Leiter einer Feuerwehr?",a:14,unit:"Stufen",hint:"Eine typische Schiebleiter.",emoji:"🚒"},
  {q:"How many Liter Milch braucht man für ein Kilo Butter?",a:21,unit:"liters",hint:"Sehr viel Milch für wenig Butter.",emoji:"🧈"},
  {q:"How many Gramm Salz braucht man zum Kochen von 500g Nudeln?",a:10,unit:"grams",hint:"Pro 100g Nudeln 1-2g Salz.",emoji:"🧂"},
  {q:"How many km/h fährt eine Achterbahn maximal?",a:130,unit:"km/h",hint:"Die schnellsten Achterbahnen der Welt.",emoji:"🎢"},
  {q:"How many Stunden dauert eine Schulwoche?",a:30,unit:"hours",hint:"Bei 6 Stunden daily.",emoji:"🏫"},
  {q:"How many Minuten dauert ein Kinofilm on average?",a:100,unit:"minutes",hint:"Die meisten Filme sind 90-120 Minuten.",emoji:"🎬"},
  {q:"How many Tage hat der August?",a:31,unit:"days",hint:"Einer der Monate mit 31 Tagen.",emoji:"📅"},
  {q:"How many Augen hat ein Fliege?",a:2,unit:"Augen",hint:"Aber jedes Auge hat tausende Einzellinsen.",emoji:"🪰"},
  {q:"How many Beine hat ein Krebs?",a:10,unit:"Beine",hint:"Krebse sind Zehnfüßer.",emoji:"🦀"},
  {q:"How many Ecken hat ein Würfel?",a:8,unit:"Ecken",hint:"Ein Würfel hat 8 Ecken, 12 Kanten und 6 Flächen.",emoji:"🎲"},
  {q:"How many Monate haben 31 Tage?",a:7,unit:"months",hint:"Jan, März, Mai, Jul, Aug, Okt, Dez.",emoji:"📅"},
  {q:"How many Gramm hat ein halbes Kilogramm?",a:500,unit:"grams",hint:"Die Hälfte von 1000g.",emoji:"⚖️"},
  {q:"How many Minuten hat ein Tag?",a:1440,unit:"minutes",hint:"24 Stunden × 60 Minuten.",emoji:"⏰"},
  {q:"How many Kanten hat ein Würfel?",a:12,unit:"Kanten",hint:"Jede Fläche hat 4 Kanten – aber geteilt.",emoji:"🎲"},
  {q:"How many Seiten hat ein Oktaeder?",a:8,unit:"Seiten",hint:"Okta = acht.",emoji:"🔷"},
  {q:"How many cm ist ein halber Meter?",a:50,unit:"cm",hint:"Die Hälfte von 100cm.",emoji:"📏"},
  {q:"How many Stunden hat eine halbe Woche?",a:84,unit:"hours",hint:"3,5 Tage × 24 Stunden.",emoji:"⏰"},
  {q:"How many Achsen hat ein Auto?",a:2,unit:"Achsen",hint:"Vorder- und Hinterachse.",emoji:"🚗"},
  {q:"How many Flügel hat ein Schmetterling?",a:4,unit:"Flügel",hint:"Zwei Vorder- und zwei Hinterflügel.",emoji:"🦋"},
  {q:"How many Augen hat eine Fliege?",a:2,unit:"Augen",hint:"Zwei Facettenaugen mit je tausenden Linsen.",emoji:"🪰"},
  {q:"How many Räder hat ein Dreirad?",a:3,unit:"Räder",hint:"Tri = drei.",emoji:"🚲"},
  {q:"How many Beine hat ein Pferd?",a:4,unit:"Beine",hint:"Vier Hufe.",emoji:"🐴"},
  {q:"How many Flossen hat ein Goldfisch?",a:7,unit:"Flossen",hint:"Rücken, Brust (2), Bauch (2), After, Schwanz.",emoji:"🐠"},
  {q:"How many Knöpfe hat ein normales Hemd?",a:7,unit:"Knöpfe",hint:"Die meisten Hemden haben 6-8 Knöpfe.",emoji:"👔"},
  {q:"How many Seiten hat ein Fünfeck?",a:5,unit:"Seiten",hint:"Penta = fünf.",emoji:"⬠"},
  {q:"How many Jahreszeiten gibt es?",a:4,unit:"Jahreszeiten",hint:"Frühling, Sommer, Herbst, Winter.",emoji:"🌸"},
  {q:"How many Minuten dauert eine Schulpause?",a:10,unit:"minutes",hint:"Kurze Pause zwischen den Stunden.",emoji:"🏫"},
  {q:"How many Flügel hat eine Biene?",a:4,unit:"Flügel",hint:"Zwei Vorder- und zwei Hinterflügel.",emoji:"🐝"},
  {q:"How many Hände hat a human?",a:2,unit:"Hände",hint:"Links und rechts.",emoji:"🙌"},
  {q:"How many Tassen passen in einen Liter?",a:4,unit:"Tassen",hint:"Eine Tasse hat 250ml.",emoji:"☕"},
  {q:"How many Seiten hat ein Heptagon?",a:7,unit:"Seiten",hint:"Hepta = sieben.",emoji:"⬡"},
  {q:"How many Monate hat ein Quartal?",a:3,unit:"months",hint:"Q1: Jan-März, Q2: Apr-Jun, usw.",emoji:"📅"},
  {q:"How many Noten hat die Tonleiter?",a:7,unit:"Noten",hint:"Do, Re, Mi, Fa, Sol, La, Si.",emoji:"🎵"},
  {q:"How many Stunden hat ein langer Schulnachmittag?",a:4,unit:"hours",hint:"Von 13-17 Uhr.",emoji:"🏫"},
  {q:"How many Beine hat ein Hund?",a:4,unit:"Beine",hint:"Vier Pfoten.",emoji:"🐕"},
  {q:"How many Flügel hat ein Vogel?",a:2,unit:"Flügel",hint:"Zwei – links und rechts.",emoji:"🐦"},
  {q:"How many Augen hat ein Pferd?",a:2,unit:"Augen",hint:"Seitlich angeordnet für weites Sichtfeld.",emoji:"🐴"},
  {q:"How many Stunden braucht man um 10km zu Fuß zu gehen?",a:2.5,unit:"hours",hint:"Bei 4 km/h.",emoji:"🚶"},
  {q:"How many Liter hat eine große PET-Flasche?",a:1.5,unit:"liters",hint:"Die gängige Größe im Supermarkt.",emoji:"🍶"},
  {q:"How many Räder hat ein Fahrrad?",a:2,unit:"Räder",hint:"Bi = zwei – daher Fahrrad.",emoji:"🚲"},
  {q:"How many Federn hat ein Pfauenschwanz?",a:200,unit:"Federn",hint:"Bis zu 200 Schmuckfedern.",emoji:"🦚"},
  {q:"How many Punkte hat ein Stern mit 6 Zacken?",a:6,unit:"Zacken",hint:"Der Davidstern.",emoji:"✡️"},
  {q:"How many Minuten dauert eine Schulwoche in Unterricht?",a:1350,unit:"minutes",hint:"30 Schulstunden à 45 Minuten.",emoji:"🏫"},
  {q:"How many Beine hat eine Katze?",a:4,unit:"Beine",hint:"Vier Pfoten.",emoji:"🐱"},
  {q:"How many Seiten hat ein Nona-Eck?",a:9,unit:"Seiten",hint:"Nona = neun.",emoji:"🔷"},
  {q:"How many Ohren hat ein Hase?",a:2,unit:"Ohren",hint:"Sehr lange Ohren!",emoji:"🐇"},
  {q:"How many Taschen hat eine Jeans normalerweise?",a:5,unit:"Taschen",hint:"2 vorne, 2 hinten, 1 kleine.",emoji:"👖"},
  {q:"How many Wirbelsäulen hat a human?",a:1,unit:"Wirbelsäule",hint:"Aus 33 einzelnen Wirbeln.",emoji:"🦴"},
  {q:"How many Augen hat ein Einhorn?",a:2,unit:"Augen",hint:"Wie alle Säugetiere.",emoji:"🦄"},
  {q:"How many Zähne verliert a child insgesamt?",a:20,unit:"teeth",hint:"Das gesamte Milchgebiss.",emoji:"🦷"},
  {q:"How many Flügel hat ein Marienkäfer?",a:4,unit:"Flügel",hint:"2 Deckflügel und 2 Flugflügel.",emoji:"🐞"},
  {q:"How many Liter hat eine Badewanne?",a:150,unit:"liters",hint:"Typische Badewannen-Größe.",emoji:"🛁"},
  {q:"How many Monate hat ein Trimester?",a:3,unit:"months",hint:"In der Schwangerschaft ein Drittel.",emoji:"📅"},
  {q:"How many Noten hat eine Oktave?",a:8,unit:"Noten",hint:"Töne von C bis C.",emoji:"🎵"},
  {q:"How many Stufen hat eine normale Leiter?",a:8,unit:"Stufen",hint:"Verschiedene Größen – ca. 8.",emoji:"🪜"},
  {q:"How many Blätter hat ein vierblättriges Kleeblatt?",a:4,unit:"Blätter",hint:"Sehr selten – bringt Glück!",emoji:"🍀"},
  {q:"How many Achsen hat ein LKW?",a:3,unit:"Achsen",hint:"Vorne 1, hinten 2 Achsen.",emoji:"🚛"},
];
