// 🌍 GEOGRAPHY – Kids – Part 1 of 217
export default [
  {id:"kgeo_001",q:"How tall is Mount Everest, in meters?",a:8849,unit:"meters",hint:"The highest mountain on Earth, in the Himalayas.",emoji:"🏔️"},
  {id:"kgeo_002",q:"How long is the Nile, in km?",a:6650,unit:"km",hint:"It's the longest river in the world.",emoji:"🌊"},
  {id:"kgeo_003",q:"How many countries are there on Earth?",a:195,unit:"countries",hint:"193 of them are members of the UN.",emoji:"🌍"},
  {id:"kgeo_004",q:"How deep is the Mariana Trench, in meters?",a:11000,unit:"meters",hint:"The deepest point in the world's oceans.",emoji:"🌊"},
  {id:"kgeo_005",q:"How many km long is the Amazon?",a:6400,unit:"km",hint:"The river with the most water in the world.",emoji:"🌿"},
  {id:"kgeo_006",q:"How high up is Bolivia's capital (La Paz), in meters?",a:3600,unit:"meters",hint:"One of the highest-altitude capitals in the world.",emoji:"🏙️"},
  {id:"kgeo_007",q:"How many km² is the Sahara?",a:9.2,unit:"million km²",hint:"The largest desert in the world.",emoji:"🏜️"},
  {id:"kgeo_008",q:"How deep is Lake Baikal, in meters?",a:1642,unit:"meters",hint:"The deepest lake in the world, in Russia.",emoji:"💧"},
  {id:"kgeo_009",q:"How many people live in China (billions)?",a:1.4,unit:"billion",hint:"The most populous country on Earth.",emoji:"🇨🇳"},
  {id:"kgeo_010",q:"How tall is the Eiffel Tower, in meters?",a:330,unit:"meters",hint:"Including the antenna, it stands in Paris.",emoji:"🗼"},
  {id:"kgeo_011",q:"How many people live on Earth (billions)?",a:8,unit:"billion",hint:"In 2022, the world population passed 8 billion.",emoji:"🌍"},
  {id:"kgeo_012",q:"How long is the Rhine, in km?",a:1230,unit:"km",hint:"It flows through Switzerland, Germany, and the Netherlands.",emoji:"🌊"},
  {id:"kgeo_013",q:"How high do airplanes fly on average, in meters?",a:10000,unit:"meters",hint:"Cruising altitude is 9,000-12,000 meters.",emoji:"✈️"},
  {id:"kgeo_014",q:"How long is the Elbe, in km?",a:1091,unit:"km",hint:"It flows from the Czech Republic through Germany.",emoji:"🌊"},
  {id:"kgeo_015",q:"How many islands does Indonesia have?",a:17000,unit:"islands",hint:"The fourth most populous country in the world.",emoji:"🏝️"},
  {id:"kgeo_016",q:"How tall is the Zugspitze, in meters?",a:2962,unit:"meters",hint:"The tallest mountain in Germany, in Bavaria.",emoji:"🏔️"},
  {id:"kgeo_017",q:"How many km long is the equator?",a:40075,unit:"km",hint:"Earth's circumference at 0° latitude.",emoji:"🌍"},
  {id:"kgeo_018",q:"How many km² is the Black Forest?",a:6000,unit:"km²",hint:"The largest connected forested mountain range in Germany.",emoji:"🌲"},
  {id:"kgeo_019",q:"How many km² is the Amazon rainforest?",a:5.5,unit:"million km²",hint:"The largest tropical rainforest region on Earth.",emoji:"🌴"},
  {id:"kgeo_020",q:"How long is Canada's coastline, in km?",a:202.08,unit:"thousand km",hint:"The longest coastline of any country.",emoji:"🍁"},
  {id:"kgeo_021",q:"How many km² is Greenland?",a:2.17,unit:"million km²",hint:"The largest island in the world.",emoji:"🧊"},
  {id:"kgeo_022",q:"How long is the Mississippi, in km?",a:3730,unit:"km",hint:"The longest river in North America together with the Missouri.",emoji:"🌊"},
  {id:"kgeo_023",q:"How long is the Amazon, in km?",a:6400,unit:"km",hint:"The river with the most water in the world.",emoji:"🌿"},
  {id:"kgeo_024",q:"How tall is Mount Kilimanjaro, in meters?",a:5895,unit:"meters",hint:"The tallest mountain in Africa.",emoji:"🏔️"},
  {id:"kgeo_025",q:"How long is the Great Wall of China, in km?",a:21000,unit:"km",hint:"The longest structure in human history.",emoji:"🧱"},
  {id:"kgeo_026",q:"How many km² is Germany?",a:357,unit:"thousand km²",hint:"The largest country by area in Central Europe.",emoji:"🇩🇪"},
  {id:"kgeo_027",q:"How many people live in China, in billions?",a:1.4,unit:"billion",hint:"The most populous country.",emoji:"🇨🇳"},
  {id:"kgeo_028",q:"How big is Australia, in km²?",a:7.7,unit:"million km²",hint:"The sixth-largest country on Earth.",emoji:"🦘"},
  {id:"kgeo_029",q:"How many countries border Germany?",a:9,unit:"countries",hint:"Denmark, Poland, Czech Republic, Austria, Switzerland, France, Luxembourg, Belgium, Netherlands.",emoji:"🇩🇪"},
  {id:"kgeo_030",q:"How many km² is the Sahara?",a:9.2,unit:"million km²",hint:"The largest desert in the world.",emoji:"🏜️"},
  {id:"kgeo_031",q:"How many people live on Earth, in billions?",a:8,unit:"billion",hint:"8 billion was passed in 2022.",emoji:"🌍"},
  {id:"kgeo_032",q:"How deep is Lake Geneva, in meters?",a:310,unit:"meters",hint:"The largest lake in Central Europe.",emoji:"💧"},
  {id:"kgeo_033",q:"How tall is Mount Fuji in Japan, in meters?",a:3776,unit:"meters",hint:"Japan's sacred mountain is a volcano.",emoji:"🗻"},
  {id:"kgeo_034",q:"How big is Greenland, in km²?",a:2.17,unit:"million km²",hint:"The largest island in the world.",emoji:"🧊"},
  {id:"kgeo_035",q:"How tall is the Statue of Liberty in New York, in meters?",a:93,unit:"meters",hint:"Including the pedestal and torch.",emoji:"🗽"},
  {id:"kgeo_036",q:"How many km long is the Grand Canyon?",a:446,unit:"km",hint:"The largest canyon system in the US.",emoji:"🏜️"},
  {id:"kgeo_037",q:"How many countries are in the EU?",a:27,unit:"countries",hint:"After Brexit.",emoji:"🇪🇺"},
  {id:"kgeo_038",q:"How deep is the deepest lake in the US (Crater Lake), in meters?",a:594,unit:"meters",hint:"In Oregon – formed by a volcano.",emoji:"💧"},
  {id:"kgeo_039",q:"How big is Antarctica, in km²?",a:14,unit:"million km²",hint:"The fifth-largest territory on Earth.",emoji:"🧊"},
  {id:"kgeo_040",q:"How long is the Danube, in km?",a:2860,unit:"km",hint:"It flows through 10 countries.",emoji:"🌊"},
  {id:"kgeo_041",q:"How high up is Mexico City, in meters?",a:2240,unit:"meters",hint:"One of the highest-altitude capitals.",emoji:"🏙️"},
  {id:"kgeo_042",q:"How many km long is Australia's coastline?",a:25760,unit:"km",hint:"A very long stretch of coast.",emoji:"🏖️"},
  {id:"kgeo_043",q:"How big is Russia, in million km²?",a:17,unit:"million km²",hint:"The largest country in the world.",emoji:"🗺️"},
  {id:"kgeo_044",q:"How tall is Mount Olympus in Greece, in meters?",a:2917,unit:"meters",hint:"The tallest mountain in Greece – home of the gods.",emoji:"🏔️"},
  {id:"kgeo_045",q:"How many countries does South America have?",a:12,unit:"countries",hint:"From Colombia to Argentina.",emoji:"🌎"},
  {id:"kgeo_046",q:"How long is the Niger River, in km?",a:4180,unit:"km",hint:"The third-longest river in Africa.",emoji:"🌊"},
  {id:"kgeo_047",q:"How deep is the Mariana Trench exactly, in meters?",a:11034,unit:"meters",hint:"The Challenger Deep – the deepest point in the oceans.",emoji:"🌊"},
  {id:"kgeo_048",q:"How many km² is Bavaria?",a:70550,unit:"km²",hint:"The largest German federal state.",emoji:"🍺"},
  {id:"kgeo_049",q:"How tall is Mont Blanc, in meters?",a:4808,unit:"meters",hint:"The tallest mountain in the Alps.",emoji:"🏔️"},
  {id:"kgeo_050",q:"How many countries are on the continent of Oceania?",a:14,unit:"countries",hint:"Australia, New Zealand, and the Pacific islands.",emoji:"🌊"},
  {id:"kgeo_051",q:"How long is the Nile, including the White Nile, in km?",a:6650,unit:"km",hint:"The longest river in the world.",emoji:"🌊"},
  {id:"kgeo_052",q:"How many km² is the Gobi Desert?",a:1.29,unit:"million km²",hint:"The coldest desert in the world.",emoji:"🏜️"},
  {id:"kgeo_053",q:"How tall is Mount Vesuvius, in meters?",a:1281,unit:"meters",hint:"The volcano that destroyed Pompeii.",emoji:"🌋"},
  {id:"kgeo_054",q:"How many km² is Austria?",a:83879,unit:"km²",hint:"A small but mountainous country.",emoji:"🇦🇹"},
  {id:"kgeo_055",q:"How long is the Congo River, in km?",a:4700,unit:"km",hint:"The deepest river in the world.",emoji:"🌊"},
  {id:"kgeo_056",q:"How many km² is the Mediterranean Sea?",a:2.5,unit:"million km²",hint:"The largest inland sea in the world.",emoji:"🌊"},
  {id:"kgeo_057",q:"How tall is Kibo, the Kilimanjaro's summit, in meters?",a:5895,unit:"meters",hint:"The highest point in Africa.",emoji:"🏔️"},
  {id:"kgeo_058",q:"How many countries does Asia have?",a:49,unit:"countries",hint:"The largest continent with the most people.",emoji:"🌏"},
  {id:"kgeo_059",q:"How long is the Yenisei River, in km?",a:5539,unit:"km",hint:"One of the longest rivers in the world, in Russia.",emoji:"🌊"},
  {id:"kgeo_060",q:"How many km² is the Namib Desert?",a:81000,unit:"km²",hint:"The oldest desert in the world.",emoji:"🏜️"},
  {id:"kgeo_061",q:"How tall is Aconcagua, in meters?",a:6961,unit:"meters",hint:"The tallest mountain in South America.",emoji:"🏔️"},
  {id:"kgeo_062",q:"How many km long is the Panama Canal?",a:82,unit:"km",hint:"It connects the Atlantic and Pacific.",emoji:"⛵"},
  {id:"kgeo_063",q:"How big is Brazil, in km²?",a:8.52,unit:"million km²",hint:"The fifth-largest country in the world.",emoji:"🇧🇷"},
  {id:"kgeo_064",q:"How long is the Rhine from source to mouth, in km?",a:1230,unit:"km",hint:"It originates in Switzerland.",emoji:"🌊"},
  {id:"kgeo_065",q:"How many km long is the entire Himalayan mountain range?",a:2400,unit:"km long",hint:"The longest mountain range on Earth.",emoji:"🏔️"},
  {id:"kgeo_066",q:"How deep is Lake Titicaca, in meters?",a:283,unit:"meters",hint:"The highest-altitude navigable lake.",emoji:"💧"},
  {id:"kgeo_067",q:"How many km² is Switzerland?",a:41285,unit:"km²",hint:"A small country with big mountains.",emoji:"🇨🇭"},
  {id:"kgeo_068",q:"How long is the Ob River in Russia, in km?",a:3650,unit:"km",hint:"One of the largest Siberian rivers.",emoji:"🌊"},
  {id:"kgeo_069",q:"How many km away is New York from London?",a:5570,unit:"km",hint:"Across the Atlantic.",emoji:"✈️"},
  {id:"kgeo_070",q:"How many km² is Mongolia?",a:1.56,unit:"million km²",hint:"The country with the lowest population density.",emoji:"🐎"},
  {id:"kgeo_071",q:"How tall is Mount Elbrus in Russia, in meters?",a:5642,unit:"meters",hint:"The tallest mountain in Europe.",emoji:"🏔️"},
  {id:"kgeo_072",q:"How many people live in Tokyo, in millions?",a:37,unit:"million",hint:"The largest metropolitan area in the world.",emoji:"🗼"},
  {id:"kgeo_073",q:"How long is the Suez Canal, in km?",a:193,unit:"km",hint:"It connects the Mediterranean and the Red Sea.",emoji:"⛵"},
  {id:"kgeo_074",q:"How many km² is the Arabian Peninsula?",a:3.24,unit:"million km²",hint:"The largest peninsula in the world.",emoji:"🏜️"},
  {id:"kgeo_075",q:"How tall is Mount Etna in Sicily, in meters?",a:3357,unit:"meters",hint:"The most active volcano in Europe.",emoji:"🌋"},
  {id:"kgeo_076",q:"How many km² is Canada?",a:9.98,unit:"million km²",hint:"The second-largest country in the world.",emoji:"🍁"},
  {id:"kgeo_077",q:"How deep is Germany's lowest point (Wilstedt)?",a:3,unit:"m below sea level",hint:"In the Wilstermarsch region of Schleswig-Holstein.",emoji:"📏"},
  {id:"kgeo_078",q:"How many islands does Greece have?",a:6000,unit:"islands",hint:"About 200 of them are inhabited.",emoji:"🏝️"},
  {id:"kgeo_079",q:"How long is the Trans-Siberian Railway, in km?",a:9289,unit:"km",hint:"The longest railway line in the world.",emoji:"🚂"},
  {id:"kgeo_080",q:"How many km² is Turkey?",a:783.56,unit:"thousand km²",hint:"It lies in both Europe and Asia.",emoji:"🇹🇷"},
  {id:"kgeo_081",q:"How tall is Mount Ararat in Turkey, in meters?",a:5137,unit:"meters",hint:"The biblical mountain of Noah's Ark.",emoji:"🏔️"},
  {id:"kgeo_082",q:"How wide is the Amazon rainforest?",a:3000,unit:"km wide",hint:"The largest rainforest area on Earth.",emoji:"🌿"},
  {id:"kgeo_083",q:"How many countries does Europe have?",a:44,unit:"countries",hint:"Depending on the definition, 44-50.",emoji:"🇪🇺"},
  {id:"kgeo_084",q:"How long is the border between the US and Canada, in km?",a:8891,unit:"km",hint:"The longest land border in the world.",emoji:"🗺️"},
  {id:"kgeo_085",q:"How big is India, in km²?",a:3.29,unit:"million km²",hint:"The seventh-largest country in the world.",emoji:"🇮🇳"},
  {id:"kgeo_086",q:"How much taller is the Zugspitze than Munich, in meters (difference)?",a:2932,unit:"meters",hint:"Munich sits at 520m, the Zugspitze at 2,962m.",emoji:"🏔️"},
  {id:"kgeo_087",q:"How long is the Weser, in km?",a:452,unit:"km",hint:"It flows through Hesse and Lower Saxony into the North Sea.",emoji:"🌊"},
  {id:"kgeo_088",q:"How tall is the Brocken in the Harz Mountains, in meters?",a:1141,unit:"meters",hint:"The highest peak in northern Germany.",emoji:"🏔️"},
  {id:"kgeo_089",q:"How many km² is the North Sea?",a:575,unit:"thousand km²",hint:"A marginal sea of the Atlantic.",emoji:"🌊"},
  {id:"kgeo_090",q:"How far is Berlin from Munich, in km as the crow flies?",a:504,unit:"km",hint:"Both are major German cities.",emoji:"🇩🇪"},
  {id:"kgeo_091",q:"How long is the Inn River, in km?",a:517,unit:"km",hint:"It originates in Switzerland and flows into the Danube.",emoji:"🌊"},
  {id:"kgeo_092",q:"How many km away is Hamburg from the North Sea?",a:100,unit:"km",hint:"The Elbe connects Hamburg to the sea.",emoji:"⛵"},
  {id:"kgeo_093",q:"How tall is the Feldberg in the Black Forest, in meters?",a:1493,unit:"meters",hint:"The tallest mountain in Baden-Württemberg.",emoji:"🏔️"},
  {id:"kgeo_094",q:"How many people live in Munich?",a:1.5,unit:"million people",hint:"About 1.5 million – the largest city in Bavaria.",emoji:"🏙️"},
  {id:"kgeo_095",q:"How many km² is Berlin?",a:892,unit:"km²",hint:"About 3.7 million people live there.",emoji:"🇩🇪"},
  {id:"kgeo_096",q:"How many kilometers of highway does Germany have?",a:13200,unit:"km",hint:"The third-longest highway network in the world.",emoji:"🛣️"},
  {id:"kgeo_097",q:"How tall is the highest peak of the Taunus mountains (Großer Feldberg), in meters?",a:878,unit:"meters",hint:"North of Frankfurt.",emoji:"🏔️"},
  {id:"kgeo_098",q:"How far is Hamburg from Frankfurt, in km as the crow flies?",a:430,unit:"km",hint:"Both are cities of over a million people.",emoji:"🇩🇪"},
  {id:"kgeo_099",q:"How many federal states does Germany have?",a:16,unit:"federal states",hint:"3 city-states and 13 territorial states.",emoji:"🇩🇪"},
  {id:"kgeo_100",q:"How long is the A9 highway (Munich-Berlin), in km?",a:524,unit:"km",hint:"One of the most important German highways.",emoji:"🛣️"},
  {id:"kgeo_101",q:"How many km² is Lake Constance?",a:536,unit:"km²",hint:"The third-largest lake in Central Europe.",emoji:"💧"},
  {id:"kgeo_102",q:"How deep is Lake Constance at its deepest point, in meters?",a:254,unit:"meters",hint:"Deepest between Bregenz and Friedrichshafen.",emoji:"💧"},
  {id:"kgeo_103",q:"How many km² is Hamburg?",a:755,unit:"km²",hint:"One of the three German city-states.",emoji:"⚓"},
  {id:"kgeo_104",q:"How tall is the Wendelstein in Bavaria, in meters?",a:1838,unit:"meters",hint:"Accessible by cog railway.",emoji:"🏔️"},
  {id:"kgeo_105",q:"How far is Cologne from Düsseldorf, in km?",a:45,unit:"km",hint:"Both lie on the Rhine in North Rhine-Westphalia.",emoji:"🌊"},
  {id:"kgeo_106",q:"How many km² is the Lüneburg Heath?",a:7400,unit:"km²",hint:"The largest nature reserve in northern Germany.",emoji:"🌿"},
  {id:"kgeo_107",q:"How tall is the Grossglockner in Austria, in meters?",a:3798,unit:"meters",hint:"The tallest mountain in Austria.",emoji:"🏔️"},
  {id:"kgeo_108",q:"How many people live in Vienna?",a:2,unit:"million people",hint:"The capital of Austria.",emoji:"🎵"},
  {id:"kgeo_109",q:"How long is Lake Constance, in km?",a:63,unit:"km",hint:"From Bregenz to Konstanz.",emoji:"💧"},
  {id:"kgeo_110",q:"How long is Germany's North Sea coastline, in km?",a:450,unit:"km",hint:"From the Danish border to the mouth of the Elbe.",emoji:"🌊"},
  {id:"kgeo_111",q:"How tall is the Belchen peak in the Black Forest, in meters?",a:1414,unit:"meters",hint:"One of the most beautiful viewpoints.",emoji:"🏔️"},
  {id:"kgeo_112",q:"How many people live in Hamburg?",a:1.8,unit:"million people",hint:"The second-largest city in Germany.",emoji:"⚓"},
  {id:"kgeo_113",q:"How long is the German Baltic Sea coastline, in km?",a:354,unit:"km",hint:"From Flensburg to the Oder Bay.",emoji:"🌊"},
  {id:"kgeo_114",q:"How far is Munich from Vienna, in km as the crow flies?",a:357,unit:"km",hint:"Two of the most beautiful German-speaking cities.",emoji:"🏙️"},
  {id:"kgeo_115",q:"How tall is Piz Bernina in Switzerland, in meters?",a:4049,unit:"meters",hint:"The easternmost peak above 4,000m in the Alps.",emoji:"🏔️"},
  {id:"kgeo_116",q:"How many people live in Zurich?",a:400,unit:"thousand people",hint:"The largest city in Switzerland.",emoji:"🇨🇭"},
  {id:"kgeo_117",q:"How long is Germany's total border, in km?",a:3757,unit:"km",hint:"9 neighboring countries.",emoji:"🇩🇪"},
  {id:"kgeo_118",q:"How tall is the Dachstein in Austria, in meters?",a:2995,unit:"meters",hint:"With a glacier and a suspension bridge.",emoji:"🏔️"},
  {id:"kgeo_119",q:"How long is the French Riviera (Côte d'Azur)?",a:180,unit:"km",hint:"From Saint-Tropez to Menton.",emoji:"🌊"},
  {id:"kgeo_120",q:"How many people live in Berlin?",a:3.7,unit:"million people",hint:"The capital and largest city of Germany.",emoji:"🇩🇪"},
  {id:"kgeo_121",q:"How long is the route from Berlin to Paris, in km?",a:1050,unit:"km",hint:"About 8 hours by train.",emoji:"🚂"},
  {id:"kgeo_122",q:"How tall is Mount Teide on Tenerife, in meters?",a:3718,unit:"meters",hint:"The tallest mountain in Spain.",emoji:"🌋"},
  {id:"kgeo_123",q:"How many km² is Tuscany in Italy?",a:22987,unit:"km²",hint:"Famous for wine and art.",emoji:"🍷"},
  {id:"kgeo_124",q:"How far is Germany from Australia, in km?",a:16000,unit:"km",hint:"On the opposite side of the Earth.",emoji:"🌏"},
  {id:"kgeo_125",q:"How many km² is France?",a:551.7,unit:"thousand km²",hint:"The largest country in Western Europe.",emoji:"🇫🇷"},
  {id:"kgeo_126",q:"How long is the Loire in France, in km?",a:1013,unit:"km",hint:"The longest river in France.",emoji:"🌊"},
  {id:"kgeo_127",q:"How tall is the Matterhorn in Switzerland, in meters?",a:4478,unit:"meters",hint:"The symbol of the Alps.",emoji:"🏔️"},
  {id:"kgeo_128",q:"How many people live in Paris?",a:2.2,unit:"million people",hint:"The city of love.",emoji:"🗼"},
  {id:"kgeo_129",q:"How long is the Thames in Great Britain, in km?",a:346,unit:"km",hint:"It flows through London.",emoji:"🌊"},
  {id:"kgeo_130",q:"How many km² is Spain?",a:505.99,unit:"thousand km²",hint:"The second-largest country in Western Europe.",emoji:"🇪🇸"},
  {id:"kgeo_131",q:"How tall is Nanga Parbat in Pakistan, in meters?",a:8126,unit:"meters",hint:"The ninth-tallest mountain in the world.",emoji:"🏔️"},
  {id:"kgeo_132",q:"How many km² is Italy?",a:301.34,unit:"thousand km²",hint:"Shaped like a boot.",emoji:"🇮🇹"},
  {id:"kgeo_133",q:"How long is the Po in Italy, in km?",a:652,unit:"km",hint:"The longest river in Italy.",emoji:"🌊"},
  {id:"kgeo_134",q:"How tall is Mount Vesuvius near Naples, in meters?",a:1281,unit:"meters",hint:"It destroyed Pompeii in 79 CE.",emoji:"🌋"},
  {id:"kgeo_135",q:"How many people live in Rome?",a:2.8,unit:"million people",hint:"The Eternal City.",emoji:"🏛️"},
  {id:"kgeo_136",q:"How long is the Ebro in Spain, in km?",a:930,unit:"km",hint:"The river with the most water in Spain.",emoji:"🌊"},
  {id:"kgeo_137",q:"How tall is Pico de Orizaba in Mexico, in meters?",a:5636,unit:"meters",hint:"The tallest mountain in Mexico.",emoji:"🏔️"},
  {id:"kgeo_138",q:"How many km² is Mexico?",a:1.96,unit:"million km²",hint:"The third-largest country in Latin America.",emoji:"🌵"},
  {id:"kgeo_139",q:"How long is the Yangtze River in China, in km?",a:6300,unit:"km",hint:"The longest river in Asia.",emoji:"🌊"},
  {id:"kgeo_140",q:"How tall is K2 in Pakistan, in meters?",a:8611,unit:"meters",hint:"The second-tallest mountain in the world.",emoji:"🏔️"},
  {id:"kgeo_141",q:"How many km² is China?",a:9.6,unit:"million km²",hint:"The fourth-largest country in the world.",emoji:"🇨🇳"},
  {id:"kgeo_142",q:"How long is the Yellow River (Huang He) in China, in km?",a:5464,unit:"km",hint:"The cradle of Chinese civilization.",emoji:"🌊"},
  {id:"kgeo_143",q:"How tall is Mount Fuji in Japan exactly, in meters?",a:3776,unit:"meters",hint:"A symbol of Japan.",emoji:"🗻"},
  {id:"kgeo_144",q:"How many km² is Japan?",a:377.98,unit:"thousand km²",hint:"An island nation in the Pacific.",emoji:"🇯🇵"},
  {id:"kgeo_145",q:"How many people live in Tokyo exactly, in millions?",a:37,unit:"million",hint:"The largest metropolitan area in the world.",emoji:"🗼"},
  {id:"kgeo_146",q:"How long is the Mekong, in km?",a:4350,unit:"km",hint:"It flows through 6 Southeast Asian countries.",emoji:"🌊"},
  {id:"kgeo_147",q:"How tall is Mawenzi, Kilimanjaro's second-highest peak, in meters?",a:5149,unit:"meters",hint:"The second peak of Kilimanjaro.",emoji:"🏔️"},
  {id:"kgeo_148",q:"How many km² is the US?",a:9.83,unit:"million km²",hint:"The third-largest country in the world.",emoji:"🇺🇸"},
  {id:"kgeo_149",q:"How long is the Missouri, in km?",a:3767,unit:"km",hint:"The longest river in the US.",emoji:"🌊"},
  {id:"kgeo_150",q:"How tall is Denali in Alaska, in meters?",a:6190,unit:"meters",hint:"The tallest mountain in North America.",emoji:"🏔️"},
  {id:"kgeo_151",q:"How many people live in New York City, in millions?",a:8.3,unit:"million",hint:"The largest city in the US.",emoji:"🗽"},
  {id:"kgeo_152",q:"How long is the Colorado River, in km?",a:2334,unit:"km",hint:"It carved the Grand Canyon.",emoji:"🌊"},
  {id:"kgeo_153",q:"How many km² is Argentina?",a:2.78,unit:"million km²",hint:"The eighth-largest country in the world.",emoji:"🇦🇷"},
  {id:"kgeo_154",q:"How tall are the Iguazu Falls, in meters?",a:82,unit:"meters",hint:"Wider than Niagara Falls.",emoji:"🌊"},
  {id:"kgeo_155",q:"How long is the Nile from Lake Victoria to its mouth, in km?",a:5584,unit:"km",hint:"Depending on how it's measured, the longest river.",emoji:"🌊"},
  {id:"kgeo_156",q:"How tall is Table Mountain in South Africa, in meters?",a:1086,unit:"meters",hint:"A landmark of Cape Town.",emoji:"🏔️"},
  {id:"kgeo_157",q:"How many km² is the Democratic Republic of the Congo?",a:2.34,unit:"million km²",hint:"The second-largest country in Africa.",emoji:"🌿"},
  {id:"kgeo_158",q:"How long is the Zambezi, in km?",a:2574,unit:"km",hint:"Victoria Falls is located along it.",emoji:"🌊"},
  {id:"kgeo_159",q:"How tall are Victoria Falls in Zimbabwe, in meters?",a:108,unit:"meters",hint:"The largest waterfall in the world by width.",emoji:"🌊"},
  {id:"kgeo_160",q:"How many km² is Egypt?",a:1.0,unit:"million km²",hint:"95% of it is desert.",emoji:"🏜️"},
  {id:"kgeo_161",q:"How long is the Zambezi from source to mouth, in km?",a:2574,unit:"km",hint:"It flows from Zambia to Mozambique.",emoji:"🌊"},
  {id:"kgeo_162",q:"How long is the Amazon River, in km?",a:6400,unit:"km",hint:"One of the longest rivers in the world.",emoji:"🌿"},
  {id:"kgeo_163",q:"How many people live in Tokyo?",a:14,unit:"million people",hint:"One of the largest cities in the world.",emoji:"🏙️"},
  {id:"kgeo_164",q:"How many km² does Australia have?",a:7.7,unit:"million km²",hint:"The sixth-largest country on Earth.",emoji:"🦘"},
  {id:"kgeo_165",q:"How many countries does Africa have?",a:54,unit:"countries",hint:"The continent with the most countries.",emoji:"🌍"},
  {id:"kgeo_166",q:"How tall is Mount Fuji in Japan?",a:3776,unit:"meters",hint:"Japan's sacred volcano.",emoji:"🗻"},
  {id:"kgeo_167",q:"How big is the Sahara, in km²?",a:9.2,unit:"million km²",hint:"The largest desert in the world.",emoji:"🏜️"},
  {id:"kgeo_168",q:"How many km² does Brazil have?",a:8.5,unit:"million km²",hint:"The largest country in South America.",emoji:"🇧🇷"},
  {id:"kgeo_169",q:"How long is the Mississippi River, in km?",a:3730,unit:"km",hint:"The great river of North America.",emoji:"🌊"},
  {id:"kgeo_170",q:"How many people live in Mumbai?",a:20,unit:"million people",hint:"The largest city in India.",emoji:"🏙️"},
  {id:"kgeo_171",q:"How tall is Aconcagua in Argentina?",a:6961,unit:"meters",hint:"The tallest mountain in the Americas.",emoji:"🏔️"},
  {id:"kgeo_172",q:"How long is the Ganges, in km?",a:2525,unit:"km",hint:"India's sacred river.",emoji:"🌊"},
  {id:"kgeo_173",q:"How many km² does Saudi Arabia have?",a:2.15,unit:"million km²",hint:"The largest country in Western Asia.",emoji:"🇸🇦"},
  {id:"kgeo_174",q:"How deep is Lake Lucerne, in meters?",a:214,unit:"meters",hint:"In Switzerland – the heart of the Swiss Confederation.",emoji:"💧"},
  {id:"kgeo_175",q:"How many countries border France?",a:8,unit:"countries",hint:"Spain, Andorra, Monaco, Italy, Switzerland, Germany, Luxembourg, Belgium.",emoji:"🇫🇷"},
  {id:"kgeo_176",q:"How tall is Mount Olympus in Greece?",a:2917,unit:"meters",hint:"The mountain of the Greek gods.",emoji:"⛰️"},
  {id:"kgeo_177",q:"How long is the Rhine from source to mouth?",a:1230,unit:"km",hint:"From the Alps to the North Sea.",emoji:"🌊"},
  {id:"kgeo_178",q:"How high up is Machu Picchu, in meters?",a:2430,unit:"meters",hint:"The city of the Incas in Peru.",emoji:"🏛️"},
  {id:"kgeo_179",q:"How many km² does India have?",a:3.29,unit:"million km²",hint:"The seventh-largest country in the world.",emoji:"🇮🇳"},
  {id:"kgeo_180",q:"How many people live in Mexico City?",a:22,unit:"million people",hint:"One of the largest cities in the Americas.",emoji:"🏙️"},
  {id:"kgeo_181",q:"How long is the Danube River, in km?",a:2860,unit:"km",hint:"It flows through 10 countries.",emoji:"🌊"},
  {id:"kgeo_182",q:"How deep below sea level is the Dead Sea, in meters?",a:430,unit:"meters",hint:"The lowest point on Earth's surface.",emoji:"🌊"},
  {id:"kgeo_183",q:"How many km² does Mongolia have?",a:1.56,unit:"million km²",hint:"The largest landlocked country in the world.",emoji:"🏕️"},
  {id:"kgeo_184",q:"How long is the Oder, in km?",a:866,unit:"km",hint:"The border river between Germany and Poland.",emoji:"🌊"},
  {id:"kgeo_185",q:"How tall is Mont Blanc without the snow cap?",a:4810,unit:"meters",hint:"The tallest mountain in the Alps.",emoji:"🏔️"},
  {id:"kgeo_186",q:"How many km² does Sweden have?",a:450,unit:"thousand km²",hint:"The largest Scandinavian country.",emoji:"🇸🇪"},
  {id:"kgeo_187",q:"How many people live in São Paulo?",a:21,unit:"million people",hint:"The largest city in South America.",emoji:"🏙️"},
  {id:"kgeo_188",q:"How long is the Lena River in Russia?",a:4400,unit:"km",hint:"One of the longest rivers in Siberia.",emoji:"🌊"},
  {id:"kgeo_189",q:"How deep is Lake Constance, in meters?",a:251,unit:"meters",hint:"A three-country lake: Germany, Austria, Switzerland.",emoji:"💧"},
  {id:"kgeo_190",q:"How many km² does Ukraine have?",a:603,unit:"thousand km²",hint:"The largest European country by area (excluding Russia).",emoji:"🇺🇦"},
  {id:"kgeo_191",q:"How many countries does Oceania have?",a:14,unit:"countries",hint:"Australia, New Zealand, and twelve island nations.",emoji:"🏝️"},
  {id:"kgeo_192",q:"How many km² does Spain have?",a:506,unit:"thousand km²",hint:"The second-largest country in the EU.",emoji:"🇪🇸"},
  {id:"kgeo_193",q:"How deep is Lake Maggiore, in meters?",a:372,unit:"meters",hint:"Between Italy and Switzerland.",emoji:"💧"},
  {id:"kgeo_194",q:"How many people live in Cairo?",a:20,unit:"million people",hint:"The largest city in Africa.",emoji:"🏙️"},
  {id:"kgeo_195",q:"How long is the Tigris, in km?",a:1900,unit:"km",hint:"Mesopotamia – the cradle of civilization.",emoji:"🌊"},
  {id:"kgeo_196",q:"How many km² does Poland have?",a:313,unit:"thousand km²",hint:"The ninth-largest country in Europe.",emoji:"🇵🇱"},
  {id:"kgeo_197",q:"How long is the Main, in km?",a:525,unit:"km",hint:"The most important right-bank tributary of the Rhine.",emoji:"🌊"},
  {id:"kgeo_198",q:"How deep is Lake Garda, in meters?",a:346,unit:"meters",hint:"The largest lake in Italy.",emoji:"💧"},
  {id:"kgeo_199",q:"How many people live in New York City?",a:8,unit:"million people",hint:"The largest city in the US.",emoji:"🗽"},
  {id:"kgeo_200",q:"How tall is Mount Etna in Sicily?",a:3357,unit:"meters",hint:"The most active volcano in Europe.",emoji:"🌋"},
  {id:"kgeo_201",q:"How long is the Euphrates, in km?",a:2800,unit:"km",hint:"Together with the Tigris, the cradle of civilization.",emoji:"🌊"},
  {id:"kgeo_202",q:"How many km² does Norway have?",a:385,unit:"thousand km²",hint:"The land of fjords.",emoji:"🇳🇴"},
  {id:"kgeo_203",q:"How deep is Lake Traun in Austria?",a:191,unit:"meters",hint:"The deepest lake in Austria.",emoji:"💧"},
  {id:"kgeo_204",q:"How many people live in Los Angeles?",a:4,unit:"million people",hint:"The City of Angels.",emoji:"🌴"},
  {id:"kgeo_205",q:"How tall is the Grossglockner in Austria?",a:3798,unit:"meters",hint:"The tallest mountain in Austria.",emoji:"🏔️"},
  {id:"kgeo_206",q:"How many km² does Finland have?",a:338,unit:"thousand km²",hint:"The land of a thousand lakes.",emoji:"🇫🇮"},
  {id:"kgeo_207",q:"How many lakes does Finland have?",a:188,unit:"thousand lakes",hint:"Over 180,000 lakes – the most water in Europe.",emoji:"💧"},
  {id:"kgeo_208",q:"How long is the Congo River, in km?",a:4700,unit:"km",hint:"The second-longest river in Africa.",emoji:"🌊"},
  {id:"kgeo_209",q:"How tall is Mount Kilimanjaro in Tanzania?",a:5895,unit:"meters",hint:"The tallest mountain in Africa.",emoji:"🏔️"},
  {id:"kgeo_210",q:"How deep is Lake Balaton in Hungary?",a:12,unit:"meters",hint:"The largest freshwater lake in Central Europe.",emoji:"💧"},
  {id:"kgeo_211",q:"How many islands does Sweden have?",a:220,unit:"thousand islands",hint:"Over 200,000 islands along its coast.",emoji:"🏝️"},
  {id:"kgeo_212",q:"How long is the Congo River, in km?",a:4700,unit:"km",hint:"The deepest river in the world.",emoji:"🌊"},
  {id:"kgeo_213",q:"How tall is Montserrat in Spain?",a:1236,unit:"meters",hint:"The sacred mountain of Catalonia.",emoji:"⛰️"},
  {id:"kgeo_214",q:"How many km² does Portugal have?",a:92000,unit:"km²",hint:"The westernmost country in Europe.",emoji:"🇵🇹"},
  {id:"kgeo_215",q:"How many km long is Germany's coastline?",a:2389,unit:"km",hint:"North Sea and Baltic Sea coasts combined.",emoji:"🌊"},
  {id:"kgeo_216",q:"How high above sea level is Vienna?",a:171,unit:"meters",hint:"The capital of Austria.",emoji:"🏙️"},
  {id:"kgeo_217",q:"How big is the North Sea, in km²?",a:570,unit:"thousand km²",hint:"Between Great Britain and the mainland.",emoji:"🌊"},
];
