// 🐘 ANIMALS – Kids – Part 1 of 230
export default [
  {id:"ktier_001",q:"How many legs does a spider have?",a:8,unit:"legs",hint:"Spiders are arachnids, not insects.",emoji:"🕷️"},
  {id:"ktier_002",q:"How heavy does a full-grown elephant get, in tons?",a:6,unit:"tons",hint:"Elephants are the heaviest land animals.",emoji:"🐘"},
  {id:"ktier_003",q:"How fast can a cheetah run, in km/h?",a:112,unit:"km/h",hint:"The fastest land animal in the world.",emoji:"🐆"},
  {id:"ktier_004",q:"How many days does an elephant carry its baby?",a:645,unit:"days",hint:"Almost 2 years – the longest pregnancy on land.",emoji:"🐘"},
  {id:"ktier_005",q:"How high can a kangaroo jump, in meters?",a:3,unit:"meters",hint:"And up to 9 meters far in a single jump!",emoji:"🦘"},
  {id:"ktier_006",q:"How many hours does a koala sleep per day?",a:22,unit:"hours",hint:"Eucalyptus leaves are hard to digest.",emoji:"🐨"},
  {id:"ktier_007",q:"How many teeth does an adult crocodile have?",a:66,unit:"teeth",hint:"They regrow their teeth up to 50 times in their life.",emoji:"🐊"},
  {id:"ktier_008",q:"How many years can a bowhead whale live?",a:211,unit:"years",hint:"The longest-living mammal on Earth.",emoji:"🐳"},
  {id:"ktier_009",q:"How heavy does a full-grown gorilla get, in kg?",a:270,unit:"kg",hint:"Despite their size, gorillas are vegetarians.",emoji:"🦍"},
  {id:"ktier_010",q:"How many liters of milk does a cow give per day?",a:25,unit:"liters",hint:"High-yield cows can give up to 50 liters.",emoji:"🐄"},
  {id:"ktier_011",q:"How many hearts does an octopus have?",a:3,unit:"hearts",hint:"Two to the gills, one to the body.",emoji:"🐙"},
  {id:"ktier_012",q:"How many km/h does the fastest fish (marlin) swim?",a:110,unit:"km/h",hint:"Faster than many cars on the highway (as of ~2024).",emoji:"🐟"},
  {id:"ktier_013",q:"How many million scent receptors does a dog have?",a:300,unit:"million",hint:"Humans only have 6 million.",emoji:"🐕"},
  {id:"ktier_014",q:"How high can a flea jump, in cm?",a:33,unit:"cm",hint:"That's 200 times its body length.",emoji:"🦟"},
  {id:"ktier_015",q:"How many hours per day does a lion sleep?",a:20,unit:"hours",hint:"Lions sleep almost the whole day!",emoji:"🦁"},
  {id:"ktier_016",q:"How many km/h can an ostrich run?",a:70,unit:"km/h",hint:"The fastest running bird in the world.",emoji:"🦜"},
  {id:"ktier_017",q:"How many eggs does a queen bee lay daily?",a:2000,unit:"eggs",hint:"In summer, the queen lays up to 2000 eggs per day.",emoji:"🐝"},
  {id:"ktier_018",q:"How many kg of bamboo does a panda eat daily?",a:15,unit:"kg",hint:"Bamboo is low in nutrients – hence the huge amount.",emoji:"🐼"},
  {id:"ktier_019",q:"How big does a full-grown blue whale get, in meters?",a:30,unit:"meters",hint:"The biggest animal that has ever lived on Earth.",emoji:"🐋"},
  {id:"ktier_020",q:"How many times per minute does a hummingbird's heart beat?",a:1200,unit:"times",hint:"The fastest heart of any bird.",emoji:"🐦"},
  {id:"ktier_021",q:"How many stripes can a zebra have at maximum?",a:80,unit:"stripes",hint:"Every zebra has a unique stripe pattern.",emoji:"🦓"},
  {id:"ktier_022",q:"How deep can a whale dive, in meters?",a:3000,unit:"meters",hint:"Sperm whale record: almost 3 km deep.",emoji:"🐳"},
  {id:"ktier_023",q:"How many days does an eagle incubate its eggs?",a:35,unit:"days",hint:"Both parents take turns incubating.",emoji:"🦅"},
  {id:"ktier_024",q:"How many legs does a millipede really have?",a:750,unit:"legs",hint:"Despite the name, they never have exactly 1000 legs.",emoji:"🐛"},
  {id:"ktier_025",q:"How many months can turtles go without food?",a:12,unit:"months",hint:"They can slow their metabolism way down.",emoji:"🐢"},
  {id:"ktier_026",q:"How many eyes does a bee have?",a:5,unit:"eyes",hint:"2 compound eyes and 3 simple eyes.",emoji:"🐝"},
  {id:"ktier_027",q:"How heavy is a full-grown polar bear, in kg?",a:700,unit:"kg",hint:"The biggest land predator on Earth.",emoji:"🐻‍❄️"},
  {id:"ktier_028",q:"How many km/h can a rhino run?",a:55,unit:"km/h",hint:"Despite their mass, rhinos are surprisingly fast.",emoji:"🦏"},
  {id:"ktier_029",q:"How many years can a tortoise get?",a:150,unit:"years",hint:"Some live past 200 years!",emoji:"🐢"},
  {id:"ktier_030",q:"How heavy does a full-grown polar bear get, in kg?",a:700,unit:"kg",hint:"The biggest land predator on Earth.",emoji:"🐻‍❄️"},
  {id:"ktier_031",q:"How far can a cheetah jump in one leap?",a:8,unit:"meters",hint:"Huge leaps while hunting.",emoji:"🐆"},
  {id:"ktier_032",q:"How many fingers does a koala have?",a:5,unit:"fingers",hint:"Koalas even have fingerprints like humans.",emoji:"🐨"},
  {id:"ktier_033",q:"How many hours does a lion sleep per day?",a:20,unit:"hours",hint:"Almost all day – they hunt at night.",emoji:"🦁"},
  {id:"ktier_034",q:"How heavy can a gorilla get at maximum, in kg?",a:270,unit:"kg",hint:"Despite their size, gorillas are vegetarians.",emoji:"🦍"},
  {id:"ktier_035",q:"How many km/h can an ostrich run?",a:70,unit:"km/h",hint:"The fastest running bird in the world.",emoji:"🦜"},
  {id:"ktier_036",q:"How many hours per day does a koala sleep?",a:22,unit:"hours",hint:"Eucalyptus is hard to digest.",emoji:"🐨"},
  {id:"ktier_037",q:"How many years does a bowhead whale live?",a:211,unit:"years",hint:"The longest-living mammal on Earth.",emoji:"🐳"},
  {id:"ktier_038",q:"How heavy is a full-grown elephant, in tons?",a:6,unit:"tons",hint:"The heaviest land animal.",emoji:"🐘"},
  {id:"ktier_039",q:"How deep can a sperm whale dive, in meters?",a:3000,unit:"meters",hint:"The deepest-diving mammal in the world.",emoji:"🐳"},
  {id:"ktier_040",q:"How many stomachs does a cow have?",a:4,unit:"stomachs",hint:"Rumen, reticulum, omasum, abomasum.",emoji:"🐄"},
  {id:"ktier_041",q:"How many tentacles does an octopus have?",a:8,unit:"tentacles",hint:"Each arm has its own nerve cells.",emoji:"🐙"},
  {id:"ktier_042",q:"How many grams does a hummingbird weigh?",a:3,unit:"grams",hint:"Smaller than a coin.",emoji:"🐦"},
  {id:"ktier_043",q:"How many wing beats per second does a hummingbird make?",a:80,unit:"times",hint:"So fast that the wings become invisible.",emoji:"🐦"},
  {id:"ktier_044",q:"How many km/h can a cheetah run?",a:112,unit:"km/h",hint:"The fastest land animal in the world.",emoji:"🐆"},
  {id:"ktier_045",q:"How many spines does a hedgehog have?",a:6000,unit:"spines",hint:"Modified hairs.",emoji:"🦔"},
  {id:"ktier_046",q:"How many days can a camel go without water?",a:15,unit:"days",hint:"The hump stores fat, not water.",emoji:"🐪"},
  {id:"ktier_047",q:"How heavy is an ostrich egg, in kg?",a:1.35,unit:"kg",hint:"The biggest egg of any living bird.",emoji:"🥚"},
  {id:"ktier_048",q:"How many km/h does a swordfish swim?",a:110,unit:"km/h",hint:"The fastest fish in the ocean.",emoji:"🐟"},
  {id:"ktier_049",q:"How far can a springbok jump in one leap?",a:15,unit:"meters",hint:"Springboks make huge leaps in the air.",emoji:"🦌"},
  {id:"ktier_050",q:"How many feathers does a swan have?",a:25000,unit:"feathers",hint:"Water birds have especially many feathers.",emoji:"🦢"},
  {id:"ktier_051",q:"How long does a worker bee live in summer?",a:6,unit:"weeks",hint:"Only 6 weeks – up to 6 months in winter.",emoji:"🐝"},
  {id:"ktier_052",q:"How many bones does a snake have?",a:300,unit:"bones",hint:"Depending on the species, 200 to 400.",emoji:"🐍"},
  {id:"ktier_053",q:"How far can a fish jump upstream (salmon) at maximum, in meters?",a:3,unit:"meters",hint:"Salmon jump up waterfalls.",emoji:"🐟"},
  {id:"ktier_054",q:"How many years old can a lobster get?",a:100,unit:"years",hint:"Lobsters barely age – mostly limited by predators.",emoji:"🦞"},
  {id:"ktier_055",q:"How high can an eagle fly at maximum, in meters?",a:3000,unit:"meters",hint:"Golden eagles circle very high.",emoji:"🦅"},
  {id:"ktier_056",q:"How heavy can a walrus get at maximum, in kg?",a:1700,unit:"kg",hint:"Male walruses are huge.",emoji:"🦭"},
  {id:"ktier_057",q:"How many km does a monarch butterfly migrate?",a:4000,unit:"km",hint:"From Canada to Mexico.",emoji:"🦋"},
  {id:"ktier_058",q:"How many teeth does a great white shark have?",a:300,unit:"teeth",hint:"In multiple rows – constantly regrowing.",emoji:"🦈"},
  {id:"ktier_059",q:"How many days does an eagle incubate its eggs?",a:35,unit:"days",hint:"Both parents take turns incubating.",emoji:"🦅"},
  {id:"ktier_060",q:"How long does a mother elephant carry her baby?",a:645,unit:"days",hint:"Almost 2 years – the longest gestation on land.",emoji:"🐘"},
  {id:"ktier_061",q:"How many kilometers can an arctic fox run in one night?",a:40,unit:"km",hint:"Incredibly tireless animals.",emoji:"🦊"},
  {id:"ktier_062",q:"How heavy is a newborn kangaroo, in grams?",a:1,unit:"gram",hint:"Tiny – it then crawls into the pouch.",emoji:"🦘"},
  {id:"ktier_063",q:"How many million scent sensors does a bear have?",a:2100,unit:"million",hint:"The sharpest sense of smell of any land animal.",emoji:"🐻"},
  {id:"ktier_064",q:"How far can a dolphin jump out of the water, in meters?",a:6,unit:"meters",hint:"Breaching – important for communication.",emoji:"🐬"},
  {id:"ktier_065",q:"How many hours per day does a sloth sleep?",a:20,unit:"hours",hint:"Almost everything except sleeping – is sleeping.",emoji:"🦥"},
  {id:"ktier_066",q:"How big can a giant squid get, in meters?",a:13,unit:"meters",hint:"The biggest animal without a backbone.",emoji:"🦑"},
  {id:"ktier_067",q:"How many years does an elephant live?",a:70,unit:"years",hint:"In captivity, sometimes over 80.",emoji:"🐘"},
  {id:"ktier_068",q:"How heavy is a cheetah cub at birth, in grams?",a:250,unit:"grams",hint:"Blind and helpless.",emoji:"🐆"},
  {id:"ktier_069",q:"How many months does a grizzly bear hibernate?",a:6,unit:"months",hint:"Actually winter rest – it can wake up anytime.",emoji:"🐻"},
  {id:"ktier_070",q:"How many km/h can a rhino run?",a:55,unit:"km/h",hint:"Surprisingly fast despite their mass.",emoji:"🦏"},
  {id:"ktier_071",q:"How many eggs does a sea turtle lay per nest?",a:100,unit:"eggs",hint:"Only a few babies survive to reach the ocean.",emoji:"🐢"},
  {id:"ktier_072",q:"How heavy does a hippo get, in kg?",a:3000,unit:"kg",hint:"The third-heaviest land animal.",emoji:"🦛"},
  {id:"ktier_073",q:"How many km/h can a cheetah reach in 2 seconds?",a:75,unit:"km/h",hint:"The fastest acceleration of any land animal.",emoji:"🐆"},
  {id:"ktier_074",q:"How many bones does a dolphin have?",a:200,unit:"bones",hint:"Dolphins still have bones from hind legs.",emoji:"🐬"},
  {id:"ktier_075",q:"How long can a certain jellyfish theoretically live?",a:9999,unit:"years",hint:"Turritopsis dohrnii – the immortal jellyfish.",emoji:"🪼"},
  {id:"ktier_076",q:"How many tons of krill does a blue whale eat daily?",a:3.6,unit:"tons",hint:"Almost 4 tons daily.",emoji:"🐋"},
  {id:"ktier_077",q:"How many eyes does a dragonfly have?",a:30000,unit:"facets",hint:"Compound eyes with 30,000 individual lenses.",emoji:"🪲"},
  {id:"ktier_078",q:"How heavy is a polar bear cub at birth, in grams?",a:500,unit:"grams",hint:"Tiny compared to its huge mother.",emoji:"🐻‍❄️"},
  {id:"ktier_079",q:"How many centimeters can a leaping frog jump, in cm?",a:530,unit:"cm",hint:"Many times its own body length.",emoji:"🐸"},
  {id:"ktier_080",q:"How many kilometers does a beluga whale migrate per year?",a:10000,unit:"km",hint:"Belugas love to migrate.",emoji:"🐳"},
  {id:"ktier_081",q:"How many hours per day does a sloth spend sleeping?",a:20,unit:"hours",hint:"The sleep champion.",emoji:"🦥"},
  {id:"ktier_082",q:"How many milligrams does a bumblebee weigh?",a:600,unit:"milligrams",hint:"Tiny but can carry many times its weight.",emoji:"🐝"},
  {id:"ktier_083",q:"How many years does a termite queen live?",a:30,unit:"years",hint:"Lays up to 30,000 eggs daily.",emoji:"🐜"},
  {id:"ktier_084",q:"How many hours does a dolphin sleep daily?",a:8,unit:"hours",hint:"With one half of the brain awake.",emoji:"🐬"},
  {id:"ktier_085",q:"How far can a flying squirrel glide, in meters?",a:90,unit:"meters",hint:"Using the membrane between its legs.",emoji:"🐿️"},
  {id:"ktier_086",q:"How many kg does a gorilla eat daily?",a:18,unit:"kg",hint:"Pure plant-eaters.",emoji:"🦍"},
  {id:"ktier_087",q:"How high can a salmon jump upstream, in meters?",a:3,unit:"meters",hint:"Salmon overcome waterfalls.",emoji:"🐟"},
  {id:"ktier_088",q:"How many eggs does a spider lay in its lifetime?",a:3000,unit:"eggs",hint:"Depending on the species, hundreds to thousands.",emoji:"🕷️"},
  {id:"ktier_089",q:"How many million insect species are there on Earth?",a:1,unit:"million species",hint:"Over 1 million known species.",emoji:"🐛"},
  {id:"ktier_090",q:"How far can a grasshopper jump, in meters?",a:1,unit:"meter",hint:"20 times its own body length.",emoji:"🦗"},
  {id:"ktier_091",q:"How many hours per day does a horse graze?",a:16,unit:"hours",hint:"Horses eat almost nonstop.",emoji:"🐴"},
  {id:"ktier_092",q:"How many liters of honey does a beehive produce per year?",a:30,unit:"liters",hint:"For one jar of honey, bees fly 80,000 km.",emoji:"🍯"},
  {id:"ktier_093",q:"How heavy is a chimpanzee's brain, in grams?",a:400,unit:"grams",hint:"The human brain weighs 1400g.",emoji:"🐒"},
  {id:"ktier_094",q:"How many km/h can a black bear run?",a:48,unit:"km/h",hint:"Faster than a human.",emoji:"🐻"},
  {id:"ktier_095",q:"How many hours does a hamster sleep daily?",a:14,unit:"hours",hint:"Hamsters are active at night.",emoji:"🐹"},
  {id:"ktier_096",q:"How many piglets does a pig have per litter?",a:10,unit:"piglets",hint:"8 to 14 piglets.",emoji:"🐷"},
  {id:"ktier_097",q:"How many km does an Arctic tern fly per year?",a:70000,unit:"km",hint:"The longest migration of any animal.",emoji:"🐦"},
  {id:"ktier_098",q:"How heavy is a walrus, in kg?",a:1700,unit:"kg",hint:"One of the heaviest seals.",emoji:"🦭"},
  {id:"ktier_099",q:"How many teeth does a dolphin have?",a:100,unit:"teeth",hint:"For catching – not chewing.",emoji:"🐬"},
  {id:"ktier_100",q:"How many hours does a mayfly live?",a:24,unit:"hours",hint:"As a larva, up to 3 years.",emoji:"🪲"},
  {id:"ktier_101",q:"How far does a moose migrate per year, in km?",a:300,unit:"km",hint:"Follows food and weather.",emoji:"🦌"},
  {id:"ktier_102",q:"How many young does a rat have per year?",a:70,unit:"young",hint:"5-10 litters of 5-10 young each.",emoji:"🐀"},
  {id:"ktier_103",q:"How many hours a day does a tiger hunt?",a:1,unit:"hour actively hunting",hint:"Only 1 in 10 hunting attempts succeeds.",emoji:"🐯"},
  {id:"ktier_104",q:"How many meters long is an anteater's tongue?",a:0.6,unit:"meters",hint:"60 cm – flicks out 150 times per minute.",emoji:"🐜"},
  {id:"ktier_105",q:"How many years does a wild chimpanzee live?",a:45,unit:"years",hint:"In captivity, up to 60.",emoji:"🐒"},
  {id:"ktier_106",q:"How heavy does a full-grown hippo get, in tons?",a:3,unit:"tons",hint:"The third-heaviest land animal.",emoji:"🦛"},
  {id:"ktier_107",q:"What percentage of its body weight does a caterpillar eat daily?",a:200,unit:"% body weight",hint:"Caterpillars double their weight within days.",emoji:"🐛"},
  {id:"ktier_108",q:"How many km can an arctic fox cover in one night?",a:40,unit:"km",hint:"Tireless hunters.",emoji:"🦊"},
  {id:"ktier_109",q:"How many legs does a lobster have?",a:10,unit:"legs",hint:"Crustaceans have 10 legs.",emoji:"🦞"},
  {id:"ktier_110",q:"How many liters of water does an elephant drink daily?",a:190,unit:"liters",hint:"Its trunk holds 15 liters at once.",emoji:"🐘"},
  {id:"ktier_111",q:"How many hours does a cat sleep daily?",a:16,unit:"hours",hint:"Cats sleep more than most animals.",emoji:"🐱"},
  {id:"ktier_112",q:"How far can a springhare jump, in meters?",a:3,unit:"meters",hint:"An African rodent with huge leaps.",emoji:"🐇"},
  {id:"ktier_113",q:"How many kg of grass does a horse eat daily?",a:11,unit:"kg",hint:"Horses are strict herbivores.",emoji:"🐴"},
  {id:"ktier_114",q:"How many young does an arctic fox have per litter?",a:8,unit:"young",hint:"With good lemming availability, even 14.",emoji:"🦊"},
  {id:"ktier_115",q:"How many tentacles does a jellyfish have on average?",a:80,unit:"tentacles",hint:"Depending on the species, 4 to hundreds.",emoji:"🪼"},
  {id:"ktier_116",q:"How many eggs does a hornet lay per summer?",a:500,unit:"eggs",hint:"The queen lays all the eggs.",emoji:"🐝"},
  {id:"ktier_117",q:"How high can a condor fly, in meters?",a:5500,unit:"meters",hint:"The highest-flying bird of South America.",emoji:"🦅"},
  {id:"ktier_118",q:"How many hours does a grizzly bear sleep daily?",a:20,unit:"hours",hint:"Except in summer when gathering food.",emoji:"🐻"},
  {id:"ktier_119",q:"How heavy is a chimpanzee, in kg?",a:60,unit:"kg",hint:"Despite being smaller, 6x stronger than humans.",emoji:"🐒"},
  {id:"ktier_120",q:"How many eyes does a fly have?",a:4000,unit:"facets",hint:"Compound eyes with thousands of lenses.",emoji:"🪰"},
  {id:"ktier_121",q:"How far can an albatross fly daily?",a:1000,unit:"km",hint:"Albatrosses are incredible fliers.",emoji:"🦅"},
  {id:"ktier_122",q:"How many sets of teeth does a crocodile grow in its lifetime?",a:50,unit:"sets",hint:"Up to 50 new sets of teeth.",emoji:"🐊"},
  {id:"ktier_123",q:"How many liters of milk does a baby blue whale drink daily?",a:600,unit:"liters",hint:"It grows by 90 kg daily.",emoji:"🐋"},
  {id:"ktier_124",q:"How many hours a day does a rhino spend looking for food?",a:12,unit:"hours",hint:"Half its life is spent eating.",emoji:"🦏"},
  {id:"ktier_125",q:"How heavy is a gorilla's arm, in kg?",a:15,unit:"kg",hint:"Gorillas are 6x stronger than humans.",emoji:"🦍"},
  {id:"ktier_126",q:"How many young does a cheetah have per litter?",a:3,unit:"young",hint:"1 to 8 – usually 3 to 5.",emoji:"🐆"},
  {id:"ktier_127",q:"How many million animal species live in the Amazon rainforest?",a:3,unit:"million species",hint:"The greatest biodiversity on Earth.",emoji:"🌿"},
  {id:"ktier_128",q:"How many km/h can a dragonfly fly?",a:55,unit:"km/h",hint:"One of the fastest flying insects.",emoji:"🪲"},
  {id:"ktier_129",q:"How many eggs does a sea turtle lay in its lifetime?",a:600,unit:"eggs",hint:"3-7 clutches per season.",emoji:"🐢"},
  {id:"ktier_130",q:"How many centimeters big is a koala baby at birth?",a:2,unit:"cm",hint:"It then crawls into the pouch.",emoji:"🐨"},
  {id:"ktier_131",q:"How many hours per day does an orangutan spend in trees?",a:24,unit:"hours",hint:"The biggest tree-climbing animals.",emoji:"🦧"},
  {id:"ktier_132",q:"How big can an anaconda get, in meters?",a:8,unit:"meters",hint:"The heaviest snake in the world.",emoji:"🐍"},
  {id:"ktier_133",q:"How many hours a day do young lion cubs play?",a:6,unit:"hours",hint:"Playing trains them for hunting.",emoji:"🦁"},
  {id:"ktier_134",q:"How many colors can a squid display?",a:30,unit:"colors",hint:"Despite being colorblind – camouflage through color change.",emoji:"🦑"},
  {id:"ktier_135",q:"How far out of the water can a crocodile leap, in meters?",a:1.5,unit:"meters",hint:"Surprisingly agile.",emoji:"🐊"},
  {id:"ktier_136",q:"How fast can an aardvark run, in km/h?",a:40,unit:"km/h",hint:"Surprisingly fast.",emoji:"🐷"},
  {id:"ktier_137",q:"How many young does a polar bear have per litter?",a:2,unit:"young",hint:"Almost always twins.",emoji:"🐻‍❄️"},
  {id:"ktier_138",q:"How many spines does a porcupine have?",a:30000,unit:"spines",hint:"Each spine is a modified hair.",emoji:"🦔"},
  {id:"ktier_139",q:"How many grams does a penguin egg weigh?",a:450,unit:"grams",hint:"Emperor penguin eggs are huge.",emoji:"🐧"},
  {id:"ktier_140",q:"How many years can a fish survive without water (lungfish)?",a:4,unit:"years",hint:"Lungfish survive in mud.",emoji:"🐟"},
  {id:"ktier_141",q:"How many hours does a brown bear sleep in winter?",a:20,unit:"hours/day",hint:"Winter rest – not true deep sleep.",emoji:"🐻"},
  {id:"ktier_142",q:"How far can a cheetah use its sense of smell, in km?",a:3,unit:"km",hint:"Cheetahs hunt mainly with their eyes.",emoji:"🐆"},
  {id:"ktier_143",q:"How many billion dollars in damage do rats cause worldwide each year?",a:19,unit:"billion dollars",hint:"Rats destroy crops and cables.",emoji:"🐀"},
  {id:"ktier_144",q:"How many bones do both hands of a monkey have?",a:54,unit:"bones",hint:"27 per hand – like in humans.",emoji:"🐒"},
  {id:"ktier_145",q:"How big can a giant squid's eye get, in cm?",a:30,unit:"cm",hint:"The biggest eye in the animal kingdom.",emoji:"🦑"},
  {id:"ktier_146",q:"How many meters long is a cow's intestine?",a:40,unit:"meters",hint:"A very long digestive system.",emoji:"🐄"},
  {id:"ktier_147",q:"How many hours does an emperor penguin incubate its egg on its feet?",a:1512,unit:"hours",hint:"63 days without food.",emoji:"🐧"},
  {id:"ktier_148",q:"How many kilometers can elephants communicate via infrasound?",a:10,unit:"km",hint:"Low tones travel through the ground.",emoji:"🐘"},
  {id:"ktier_149",q:"How many grams does a hedgehog eat daily?",a:70,unit:"grams",hint:"Insects, worms, and small vertebrates.",emoji:"🦔"},
  {id:"ktier_150",q:"How many km/h can a peregrine falcon fly in normal flight?",a:100,unit:"km/h",hint:"Up to 320 km/h in a dive.",emoji:"🦅"},
  {id:"ktier_151",q:"How many liters of saliva does a cow produce daily?",a:200,unit:"liters",hint:"Chewing cud requires a lot of saliva.",emoji:"🐄"},
  {id:"ktier_152",q:"How big can a whale shark get, in meters?",a:12,unit:"meters",hint:"The biggest fish in the world – harmless.",emoji:"🦈"},
  {id:"ktier_153",q:"How many hours a day does a sloth spend moving?",a:3,unit:"hours",hint:"The rest of the day spent hanging and sleeping.",emoji:"🦥"},
  {id:"ktier_154",q:"How many centimeters long is a rhino's horn?",a:150,unit:"cm",hint:"Made of keratin – like our fingernails.",emoji:"🦏"},
  {id:"ktier_155",q:"How many young does a rabbit have per year?",a:20,unit:"young",hint:"Several litters of 3-5 young each.",emoji:"🐇"},
  {id:"ktier_156",q:"How heavy is a T-Rex skull, in kg?",a:500,unit:"kg",hint:"A huge skull for huge prey.",emoji:"🦖"},
  {id:"ktier_157",q:"How many hours does a housefly live in total?",a:500,unit:"hours",hint:"Only 3 weeks – but lays many eggs.",emoji:"🪰"},
  {id:"ktier_158",q:"How far can a bald eagle see, in km?",a:3,unit:"km",hint:"8x sharper than human vision.",emoji:"🦅"},
  {id:"ktier_159",q:"How many eggs does a queen ant lay in her lifetime?",a:30,unit:"million eggs",hint:"30 million over a 30-year lifespan.",emoji:"🐜"},
  {id:"ktier_160",q:"How heavy is a hippo's tooth, in kg?",a:3,unit:"kg",hint:"Pure weapon against rivals.",emoji:"🦛"},
  {id:"ktier_161",q:"How many hours per day does a tiger sleep?",a:16,unit:"hours",hint:"Lots of sleep for night hunting.",emoji:"🐯"},
  {id:"ktier_162",q:"How tall does a cobra get when raised up, in cm?",a:180,unit:"cm",hint:"Cobras can raise themselves up high.",emoji:"🐍"},
  {id:"ktier_163",q:"How many km does a migratory bird travel per day?",a:200,unit:"km",hint:"Depending on the wind, even more.",emoji:"🐦"},
  {id:"ktier_164",q:"How many spikes does a pufferfish have when inflated?",a:1000,unit:"spikes",hint:"Pufferfish inflate when in danger.",emoji:"🐡"},
  {id:"ktier_165",q:"How many grams of food does a hummingbird eat daily?",a:8,unit:"grams",hint:"Its own body weight daily.",emoji:"🐦"},
  {id:"ktier_166",q:"How many liters of blood does a rhino have?",a:20,unit:"liters",hint:"Proportionally less than an elephant.",emoji:"🦏"},
  {id:"ktier_167",q:"How big is an emperor penguin, in cm?",a:120,unit:"cm",hint:"The biggest penguin in the world.",emoji:"🐧"},
  {id:"ktier_168",q:"How many tons of krill does a blue whale eat daily?",a:3.6,unit:"tons",hint:"All through filtering.",emoji:"🐋"},
  {id:"ktier_169",q:"How many km/h can a cheetah sustain after 100m?",a:60,unit:"km/h",hint:"It tires quickly and must rest.",emoji:"🐆"},
  {id:"ktier_170",q:"How many years can a shark live at maximum?",a:70,unit:"years",hint:"Greenland sharks even up to 400 years.",emoji:"🦈"},
  {id:"ktier_171",q:"How many hours does a gorilla sleep daily?",a:12,unit:"hours",hint:"Gorillas build a new sleeping nest daily.",emoji:"🦍"},
  {id:"ktier_172",q:"How big is an orca, in meters?",a:8,unit:"meters",hint:"Killer whales – the biggest dolphins.",emoji:"🐋"},
  {id:"ktier_173",q:"How many ribs does a snake have?",a:200,unit:"ribs",hint:"Snakes have a pair of ribs for every vertebra.",emoji:"🐍"},
  {id:"ktier_174",q:"How many hours does a tiger hunt last?",a:1,unit:"hour",hint:"Usually 15-30 minutes – rarely successful.",emoji:"🐯"},
  {id:"ktier_175",q:"How many hearts does an octopus have?",a:3,unit:"hearts",hint:"Two gill hearts and one body heart.",emoji:"🐙"},
  {id:"ktier_176",q:"How deep can a leatherback turtle dive?",a:1200,unit:"meters",hint:"The deepest-diving turtle.",emoji:"🐢"},
  {id:"ktier_177",q:"How many km can an elephant smell, in km?",a:19,unit:"km",hint:"The best sense of smell of any land animal.",emoji:"🐘"},
  {id:"ktier_178",q:"How long is a giraffe's tongue, in cm?",a:50,unit:"cm",hint:"Dark blue to avoid sunburn.",emoji:"🦒"},
  {id:"ktier_179",q:"How many years old can a sea turtle get?",a:80,unit:"years",hint:"Very long-lived – some over 100 years.",emoji:"🐢"},
  {id:"ktier_180",q:"How many eggs does a whale shark have per pregnancy?",a:300,unit:"eggs",hint:"Whale sharks give live birth.",emoji:"🦈"},
  {id:"ktier_181",q:"How long is a rhino's horn, in cm?",a:90,unit:"cm",hint:"The longest measured horn.",emoji:"🦏"},
  {id:"ktier_182",q:"How many kilograms does a polar bear eat daily?",a:10,unit:"kg",hint:"Mainly seals and fish.",emoji:"🐻‍❄️"},
  {id:"ktier_183",q:"How fast can a cheetah accelerate in 3 seconds?",a:96,unit:"km/h",hint:"From 0 to 96 km/h in 3 seconds.",emoji:"🐆"},
  {id:"ktier_184",q:"How long is a full-grown Nile crocodile, in meters?",a:5,unit:"meters",hint:"The biggest crocodile in Africa.",emoji:"🐊"},
  {id:"ktier_185",q:"How many tentacles does a jellyfish have?",a:80,unit:"tentacles",hint:"Depending on the species, from 4 to hundreds.",emoji:"🪼"},
  {id:"ktier_186",q:"How many hours does a penguin sleep daily?",a:8,unit:"hours",hint:"Penguins often sleep standing up.",emoji:"🐧"},
  {id:"ktier_187",q:"How long can a python snake get at maximum?",a:7,unit:"meters",hint:"The reticulated python is the longest snake.",emoji:"🐍"},
  {id:"ktier_188",q:"How many eggs does a turtle lay per nest?",a:100,unit:"eggs",hint:"Only a few babies survive.",emoji:"🥚"},
  {id:"ktier_189",q:"How many km/h does a dolphin swim?",a:55,unit:"km/h",hint:"Especially fast in a sprint.",emoji:"🐬"},
  {id:"ktier_190",q:"How long can a rhino's horn get at maximum, in cm?",a:150,unit:"cm",hint:"Measured records.",emoji:"🦏"},
  {id:"ktier_191",q:"How heavy does a gorilla silverback get, in kg?",a:250,unit:"kg",hint:"The biggest living ape.",emoji:"🦍"},
  {id:"ktier_192",q:"How long is the trunk of the biggest elephant, in cm?",a:250,unit:"cm",hint:"The trunk has over 40,000 muscles (as of ~2024).",emoji:"🐘"},
  {id:"ktier_193",q:"How many hours does a turtle need for 1 km?",a:2,unit:"hours",hint:"Turtles move very slowly.",emoji:"🐢"},
  {id:"ktier_194",q:"How many meters long is a full-grown blue whale?",a:30,unit:"meters",hint:"The biggest animal on Earth.",emoji:"🐋"},
  {id:"ktier_195",q:"How many km can an elephant walk per day?",a:50,unit:"km",hint:"In search of water.",emoji:"🐘"},
  {id:"ktier_196",q:"How many liters of milk does a baby elephant drink daily?",a:10,unit:"liters",hint:"Nursed for 2-3 years.",emoji:"🐘"},
  {id:"ktier_197",q:"How many grams does a hummingbird eat daily?",a:15,unit:"grams",hint:"Almost its own body weight.",emoji:"🐦"},
  {id:"ktier_198",q:"How long is a stingray's spine, in cm?",a:35,unit:"cm",hint:"Venomous and very painful.",emoji:"🐟"},
  {id:"ktier_199",q:"How many eggs does a praying mantis lay?",a:200,unit:"eggs",hint:"In a foamy cocoon.",emoji:"🦗"},
  {id:"ktier_200",q:"How heavy is a newborn elephant, in kg?",a:120,unit:"kg",hint:"The heaviest newborn on land.",emoji:"🐘"},
  {id:"ktier_201",q:"How many meters deep can a penguin dive at maximum?",a:565,unit:"meters",hint:"Emperor penguin – a deep-diving bird.",emoji:"🐧"},
  {id:"ktier_202",q:"How long is a crocodile's tail, in meters?",a:2,unit:"meters",hint:"The tail makes up half its length.",emoji:"🐊"},
  {id:"ktier_203",q:"How many km can wolves' voices carry?",a:10,unit:"km",hint:"Howling carries far.",emoji:"🐺"},
  {id:"ktier_204",q:"How long is a chameleon's tongue, in cm?",a:30,unit:"cm",hint:"Longer than its body – strikes at 26 km/h.",emoji:"🦎"},
  {id:"ktier_205",q:"How many senses do sharks have?",a:6,unit:"senses",hint:"Plus electroreception – they sense heartbeats.",emoji:"🦈"},
  {id:"ktier_206",q:"How heavy is a hummingbird, in grams?",a:3,unit:"grams",hint:"As light as a paperclip.",emoji:"🐦"},
  {id:"ktier_207",q:"How many kilometers does an albatross migrate per year?",a:120,unit:"thousand km",hint:"Almost three times around the Earth.",emoji:"🦅"},
  {id:"ktier_208",q:"How long is a full-grown Komodo dragon?",a:3,unit:"meters",hint:"The biggest living lizard.",emoji:"🦎"},
  {id:"ktier_209",q:"How many teeth does a shark have in its lifetime?",a:30000,unit:"teeth",hint:"Multiple sets of regrowing teeth.",emoji:"🦷"},
  {id:"ktier_210",q:"How wide is a whale's fluke (tail fin), in meters?",a:6,unit:"meters",hint:"Up to 6 meters wide on a blue whale.",emoji:"🐋"},
  {id:"ktier_211",q:"How many tons does a hippo weigh?",a:3,unit:"tons",hint:"The third-heaviest land animal.",emoji:"🦛"},
  {id:"ktier_212",q:"How many hours per day does a sloth sleep?",a:20,unit:"hours",hint:"Sloths are the sleep champions.",emoji:"🦥"},
  {id:"ktier_213",q:"How long is an anteater's hunting tongue?",a:60,unit:"cm",hint:"Flicked out 150 times per minute.",emoji:"🐜"},
  {id:"ktier_214",q:"How many sense organs does a bee have?",a:5,unit:"organs",hint:"Eyes including 3 simple eyes.",emoji:"🐝"},
  {id:"ktier_215",q:"How many months does a grizzly bear sleep in winter?",a:6,unit:"months",hint:"November to April in winter rest.",emoji:"🐻"},
  {id:"ktier_216",q:"How many meters can a cheetah cover in one stride?",a:7,unit:"meters",hint:"Meters per leap while hunting.",emoji:"🐆"},
  {id:"ktier_217",q:"How long is a beehive, in cm?",a:50,unit:"cm",hint:"A normal wooden beehive.",emoji:"🐝"},
  {id:"ktier_218",q:"How many hours can a camel go without water?",a:360,unit:"hours",hint:"15 days in cooler weather.",emoji:"🐪"},
  {id:"ktier_219",q:"How many meters far can a cheetah jump in one leap?",a:8,unit:"meters",hint:"Huge leaps while hunting.",emoji:"🐆"},
  {id:"ktier_220",q:"How heavy is a newborn blue whale, in tons?",a:2.7,unit:"tons",hint:"The biggest newborn in the world.",emoji:"🐋"},
  {id:"ktier_221",q:"How many months does a peregrine falcon incubate its eggs?",a:1,unit:"month",hint:"29-32 days of incubation.",emoji:"🦅"},
  {id:"ktier_222",q:"How many hours a day does a lion hunt?",a:4,unit:"hours",hint:"Only 4 hours of active hunting.",emoji:"🦁"},
  {id:"ktier_223",q:"How long is a python's tooth, in mm?",a:25,unit:"mm",hint:"Very sharp teeth without venom.",emoji:"🐍"},
  {id:"ktier_224",q:"How many kilometers does a migratory bird travel per day?",a:300,unit:"km",hint:"Some cover 500km daily.",emoji:"🐦"},
  {id:"ktier_225",q:"How many legs does a millipede have at maximum?",a:750,unit:"legs",hint:"Never exactly a thousand despite the name.",emoji:"🐛"},
  {id:"ktier_226",q:"How heavy is a full-grown whale, in tons?",a:150,unit:"tons",hint:"The blue whale – the heaviest animal.",emoji:"🐋"},
  {id:"ktier_227",q:"How long is a piranha's tooth, in mm?",a:4,unit:"mm",hint:"Small but extremely sharp.",emoji:"🐟"},
  {id:"ktier_228",q:"How many hours does a bat sleep daily?",a:20,unit:"hours",hint:"Sleeping hanging during the day.",emoji:"🦇"},
  {id:"ktier_229",q:"How many meters long is a giraffe from nose to tail?",a:6,unit:"meters",hint:"The tallest living land animal.",emoji:"🦒"},
  {id:"ktier_230",q:"What percentage of its body weight does a hummingbird eat daily?",a:150,unit:"% body weight",hint:"1.5 times its own body weight.",emoji:"🐦"},
];
