// 🎯 FREE TEST – Kids (always free) – Part 1 of 218
export default [
  {id:"ktest_001",q:"How many legs does a spider have?",a:8,unit:"legs",hint:"Spiders aren't insects – insects only have 6 legs!",emoji:"🕷️"},
  {id:"ktest_002",q:"How tall is Mount Everest, in meters?",a:8849,unit:"meters",hint:"It's the tallest mountain on Earth.",emoji:"🏔️"},
  {id:"ktest_003",q:"How many teeth does an adult have?",a:32,unit:"teeth",hint:"Including the wisdom teeth.",emoji:"🦷"},
  {id:"ktest_004",q:"How many hours does a day have?",a:24,unit:"hours",hint:"Earth rotates once on its axis every 24 hours.",emoji:"⏰"},
  {id:"ktest_005",q:"How many hearts does an octopus have?",a:3,unit:"hearts",hint:"Two pump blood to the gills, one to the body.",emoji:"🐙"},
  {id:"ktest_006",q:"How fast can a cheetah run, in km/h?",a:112,unit:"km/h",hint:"It's the fastest land animal in the world.",emoji:"🐆"},
  {id:"ktest_007",q:"How many km is it from Earth to the Moon?",a:384.4,unit:"thousand km",hint:"The Apollo astronauts took 3 days to get there.",emoji:"🌙"},
  {id:"ktest_008",q:"How many bones does an adult have?",a:206,unit:"bones",hint:"Babies have 270 – many fuse together.",emoji:"🦴"},
  {id:"ktest_009",q:"How old can a turtle get, in years?",a:150,unit:"years",hint:"Some turtles live past 200 years!",emoji:"🐢"},
  {id:"ktest_010",q:"How many continents are there on Earth?",a:7,unit:"continents",hint:"Africa, the Americas (2), Antarctica, Asia, Australia, Europe.",emoji:"🌍"},
  {id:"ktest_011",q:"How big was the biggest dinosaur, in meters?",a:40,unit:"meters",hint:"The Argentinosaurus was the longest known dinosaur (as of ~2024).",emoji:"🦕"},
  {id:"ktest_012",q:"How many eyes does a bee have?",a:5,unit:"eyes",hint:"2 large compound eyes and 3 small simple eyes on top.",emoji:"🐝"},
  {id:"ktest_013",q:"How many minutes does sunlight take to reach Earth?",a:8,unit:"minutes",hint:"Light travels at 300,000 km per second.",emoji:"☀️"},
  {id:"ktest_014",q:"How many legs does an insect have?",a:6,unit:"legs",hint:"Insects always have 6 legs – spiders have 8.",emoji:"🐛"},
  {id:"ktest_015",q:"How many teeth does a toddler have (baby teeth)?",a:20,unit:"teeth",hint:"Adults have 32.",emoji:"🦷"},
  {id:"ktest_016",q:"How many colors does the German flag have?",a:3,unit:"colors",hint:"Black, red, gold.",emoji:"🇩🇪"},
  {id:"ktest_017",q:"How many days does a leap year have?",a:366,unit:"days",hint:"Every 4 years, an extra Feb 29 is added.",emoji:"📅"},
  {id:"ktest_018",q:"How many fingers does a person have?",a:10,unit:"fingers",hint:"5 on each hand.",emoji:"✋"},
  {id:"ktest_019",q:"How many sides does a cube have?",a:6,unit:"sides",hint:"All together, they always add up to 21.",emoji:"🎲"},
  {id:"ktest_020",q:"How many minutes does an hour have?",a:60,unit:"minutes",hint:"Minutes × 24 hours = 1440 minutes per day.",emoji:"⏰"},
  {id:"ktest_021",q:"How many letters does the alphabet have?",a:26,unit:"letters",hint:"From A to Z.",emoji:"🔤"},
  {id:"ktest_022",q:"How many senses does a person have?",a:5,unit:"senses",hint:"Sight, hearing, smell, taste, touch.",emoji:"👁️"},
  {id:"ktest_023",q:"How many months does a year have?",a:12,unit:"months",hint:"From January to December.",emoji:"📅"},
  {id:"ktest_024",q:"How many weeks does a year have?",a:52,unit:"weeks",hint:"Weeks and 1 day.",emoji:"📅"},
  {id:"ktest_025",q:"How many cm does a meter have?",a:100,unit:"cm",hint:"10 cm = 1 dm, 10 dm = 1 m.",emoji:"📏"},
  {id:"ktest_026",q:"How many meters does a kilometer have?",a:1000,unit:"meters",hint:"Kilo means thousand.",emoji:"📏"},
  {id:"ktest_027",q:"How many degrees does a circle have?",a:360,unit:"degrees",hint:"An old Babylonian convention.",emoji:"⭕"},
  {id:"ktest_028",q:"How many continents does Earth have?",a:7,unit:"continents",hint:"Africa, the Americas (2), Antarctica, Asia, Australia, Europe.",emoji:"🌍"},
  {id:"ktest_029",q:"How many days does February have in a normal year?",a:28,unit:"days",hint:"Except in a leap year – then 29.",emoji:"📅"},
  {id:"ktest_030",q:"How many teeth does an adult have without wisdom teeth?",a:28,unit:"teeth",hint:"With wisdom teeth, 32.",emoji:"🦷"},
  {id:"ktest_031",q:"How many seconds does a minute have?",a:60,unit:"seconds",hint:"× 60 = 3600 seconds per hour.",emoji:"⏱️"},
  {id:"ktest_032",q:"How many sides does a square have?",a:4,unit:"sides",hint:"All equal length.",emoji:"🟦"},
  {id:"ktest_033",q:"How many kg does a metric ton have?",a:1000,unit:"kg",hint:"Kg = 1 ton.",emoji:"⚖️"},
  {id:"ktest_034",q:"How many players does a soccer team have?",a:11,unit:"players",hint:"Including the goalkeeper.",emoji:"⚽"},
  {id:"ktest_035",q:"How many legs does an octopus have?",a:8,unit:"arms",hint:"Octopus = 8 arms.",emoji:"🐙"},
  {id:"ktest_036",q:"How many continents does the equator touch?",a:3,unit:"continents",hint:"Africa, South America, Asia.",emoji:"🌍"},
  {id:"ktest_037",q:"How many notes does an octave have?",a:8,unit:"notes",hint:"C, D, E, F, G, A, B, C.",emoji:"🎵"},
  {id:"ktest_038",q:"How many hours does a week have?",a:168,unit:"hours",hint:"7 days × 24 hours.",emoji:"⏰"},
  {id:"ktest_039",q:"How many kilograms does a kilogram have?",a:1,unit:"kilogram",hint:"1 kg = 1000 g.",emoji:"⚖️"},
  {id:"ktest_040",q:"How many millimeters does a centimeter have?",a:10,unit:"mm",hint:"Mm = 1 cm.",emoji:"📏"},
  {id:"ktest_041",q:"How many seconds does an hour have?",a:3600,unit:"seconds",hint:"60 × 60 = 3600.",emoji:"⏱️"},
  {id:"ktest_042",q:"How many players play against each other in tennis singles?",a:2,unit:"players",hint:"1 vs. 1.",emoji:"🎾"},
  {id:"ktest_043",q:"How many primary colors are there in painting?",a:3,unit:"colors",hint:"Red, yellow, blue.",emoji:"🎨"},
  {id:"ktest_044",q:"How many days does a year have?",a:365,unit:"days",hint:"Except in a leap year – then 366.",emoji:"📅"},
  {id:"ktest_045",q:"How many planets are smaller than Earth in the solar system?",a:2,unit:"planets",hint:"Mercury and Mars.",emoji:"🪐"},
  {id:"ktest_046",q:"How many meters deep is an Olympic swimming pool?",a:2,unit:"meters",hint:"Minimum depth 2 meters.",emoji:"🏊"},
  {id:"ktest_047",q:"How many ears does a person have?",a:2,unit:"ears",hint:"Left and right.",emoji:"👂"},
  {id:"ktest_048",q:"How many federal states does Germany have?",a:16,unit:"federal states",hint:"3 city-states and 13 territorial states.",emoji:"🇩🇪"},
  {id:"ktest_049",q:"How many corners does a hexagon have?",a:6,unit:"corners",hint:"Like a honeycomb.",emoji:"⬡"},
  {id:"ktest_050",q:"How many toes does a person have?",a:10,unit:"toes",hint:"5 on each foot.",emoji:"🦶"},
  {id:"ktest_051",q:"How many sides does a pentagon have?",a:5,unit:"sides",hint:"Penta = five.",emoji:"⭐"},
  {id:"ktest_052",q:"How many hours does half a day have?",a:12,unit:"hours",hint:"Half of 24.",emoji:"⏰"},
  {id:"ktest_053",q:"How many millimeters does a meter have?",a:1000,unit:"mm",hint:"10 × 10 × 10 = 1000.",emoji:"📏"},
  {id:"ktest_054",q:"How many letters does the German word for elephant, ELEFANT, have?",a:7,unit:"letters",hint:"E-L-E-F-A-N-T.",emoji:"🐘"},
  {id:"ktest_055",q:"How many days does the month of September have?",a:30,unit:"days",hint:"April, June, September, November have 30 days.",emoji:"📅"},
  {id:"ktest_056",q:"How many sides does an octagon have?",a:8,unit:"sides",hint:"Octo = eight – like a stop sign.",emoji:"🔴"},
  {id:"ktest_057",q:"How many wings does a butterfly have?",a:4,unit:"wings",hint:"2 forewings and 2 hindwings.",emoji:"🦋"},
  {id:"ktest_058",q:"How many strings does a violin have?",a:4,unit:"strings",hint:"G, D, A, E.",emoji:"🎻"},
  {id:"ktest_059",q:"How many dots does a die have on all sides combined?",a:21,unit:"dots",hint:"1+2+3+4+5+6 = 21.",emoji:"🎲"},
  {id:"ktest_060",q:"How many knuckles does a person have per hand?",a:3,unit:"knuckles",hint:"Each finger has 3 joints.",emoji:"✋"},
  {id:"ktest_061",q:"How many milliliters does a liter have?",a:1,unit:"Liter",hint:"1 liter = 1000 ml.",emoji:"💧"},
  {id:"ktest_062",q:"How many seconds does a day have?",a:86400,unit:"seconds",hint:"24 × 60 × 60 = 86,400.",emoji:"⏱️"},
  {id:"ktest_063",q:"How many side surfaces does a cone have?",a:1,unit:"side surface",hint:"One curved surface plus a circular base.",emoji:"🍦"},
  {id:"ktest_064",q:"How many animal legs do a cat and a dog have together?",a:8,unit:"legs",hint:"4 + 4 = 8.",emoji:"🐱"},
  {id:"ktest_065",q:"How many hours does a baby sleep daily?",a:16,unit:"hours",hint:"Newborns sleep a lot.",emoji:"👶"},
  {id:"ktest_066",q:"How many days does a week have?",a:7,unit:"days",hint:"From Monday to Sunday.",emoji:"📅"},
  {id:"ktest_067",q:"How many km/h does a bicycle go on average?",a:15,unit:"km/h",hint:"Casual cyclists ride 12-20 km/h.",emoji:"🚴"},
  {id:"ktest_068",q:"How many lenses does a camera have?",a:1,unit:"lens",hint:"Some cameras have several – most have one.",emoji:"📷"},
  {id:"ktest_069",q:"How many sides does an octahedron have?",a:8,unit:"sides",hint:"Triangles.",emoji:"🔷"},
  {id:"ktest_070",q:"How many liters of water does a person drink daily?",a:2,unit:"liters",hint:"1.5-2 liters is recommended.",emoji:"💧"},
  {id:"ktest_071",q:"How many colors does the Austrian flag have?",a:2,unit:"colors",hint:"Red and white.",emoji:"🇦🇹"},
  {id:"ktest_072",q:"How many corners does an octagon have?",a:8,unit:"corners",hint:"Octo = 8.",emoji:"🔴"},
  {id:"ktest_073",q:"How many ears does a rabbit have?",a:2,unit:"ears",hint:"Very long ears.",emoji:"🐇"},
  {id:"ktest_074",q:"How many legs does a chair usually have?",a:4,unit:"legs",hint:"Sometimes 3 or 5.",emoji:"🪑"},
  {id:"ktest_075",q:"How many buttons does a normal calculator have?",a:36,unit:"keys",hint:"Depending on the model.",emoji:"🔢"},
  {id:"ktest_076",q:"How many colors does the Swiss flag have?",a:2,unit:"colors",hint:"Red and white.",emoji:"🇨🇭"},
  {id:"ktest_077",q:"How many minutes does half a day have?",a:720,unit:"minutes",hint:"12 × 60 = 720.",emoji:"⏰"},
  {id:"ktest_078",q:"How many sides does a dodecahedron have?",a:12,unit:"sides",hint:"Dodeca = 12.",emoji:"🔷"},
  {id:"ktest_079",q:"How many days does October have?",a:31,unit:"days",hint:"January, March, May, July, August, October, December: 31 days.",emoji:"📅"},
  {id:"ktest_080",q:"How many candles does a birthday cake have for a 10-year-old child?",a:10,unit:"candles",hint:"One candle per year of life.",emoji:"🎂"},
  {id:"ktest_081",q:"How many planets are bigger than Earth in the solar system?",a:4,unit:"planets",hint:"Jupiter, Saturn, Uranus, Neptune.",emoji:"🪐"},
  {id:"ktest_082",q:"How many notes are in a major chord?",a:3,unit:"notes",hint:"Root, third, fifth.",emoji:"🎵"},
  {id:"ktest_083",q:"How many wheels does a tricycle have?",a:3,unit:"wheels",hint:"Tri = three.",emoji:"🚲"},
  {id:"ktest_084",q:"How many fins does a typical fish have?",a:7,unit:"fins",hint:"Dorsal, pelvic, pectoral, anal, and tail fins.",emoji:"🐟"},
  {id:"ktest_085",q:"How many legs does a dog have?",a:4,unit:"legs",hint:"Four-legged animal.",emoji:"🐕"},
  {id:"ktest_086",q:"How many shots does a penalty kick have?",a:1,unit:"shot",hint:"One attempt – if retaken, another one.",emoji:"⚽"},
  {id:"ktest_087",q:"How many horns does a unicorn have?",a:1,unit:"horn",hint:"One horn – hence the name.",emoji:"🦄"},
  {id:"ktest_088",q:"How many points does a snowflake have?",a:6,unit:"points",hint:"All snowflakes have 6-fold symmetry.",emoji:"❄️"},
  {id:"ktest_089",q:"How many tires does a car have?",a:4,unit:"tires",hint:"Plus one spare tire.",emoji:"🚗"},
  {id:"ktest_090",q:"How many teeth does a child lose?",a:20,unit:"baby teeth",hint:"All 20 baby teeth fall out.",emoji:"🦷"},
  {id:"ktest_091",q:"How many legs does a duck have?",a:2,unit:"legs",hint:"All birds have 2 legs.",emoji:"🦆"},
  {id:"ktest_092",q:"How many stars are on the EU flag?",a:12,unit:"stars",hint:"Always 12 – no matter how many members.",emoji:"🇪🇺"},
  {id:"ktest_093",q:"How many dice do you need for a typical board game like Ludo?",a:1,unit:"die",hint:"Only one die is rolled.",emoji:"🎲"},
  {id:"ktest_094",q:"How many cards does a normal deck of cards have?",a:52,unit:"cards",hint:"4 suits × 13 cards.",emoji:"🃏"},
  {id:"ktest_095",q:"How many paws does a cat have?",a:4,unit:"paws",hint:"Front legs and hind legs.",emoji:"🐱"},
  {id:"ktest_096",q:"How many eyes does a Cyclops have?",a:1,unit:"eye",hint:"Cyclops from Greek mythology.",emoji:"👁️"},
  {id:"ktest_097",q:"How many hours does a weekday have?",a:24,unit:"hours",hint:"Every day has 24 hours.",emoji:"⏰"},
  {id:"ktest_098",q:"How many sides does a pyramid with a square base have?",a:5,unit:"sides",hint:"4 triangles + 1 square at the bottom.",emoji:"🔺"},
  {id:"ktest_099",q:"How many steps does a person take daily?",a:8000,unit:"steps",hint:"Average is about 7,000-10,000.",emoji:"🚶"},
  {id:"ktest_100",q:"How many days does the month of April have?",a:30,unit:"days",hint:"April, June, September, November: 30 days.",emoji:"📅"},
  {id:"ktest_101",q:"How many liters does a normal bucket hold?",a:10,unit:"liters",hint:"A standard bucket holds 10 liters.",emoji:"🪣"},
  {id:"ktest_102",q:"How many letters does the German word for butterfly, SCHMETTERLING, have?",a:13,unit:"letters",hint:"S-C-H-M-E-T-T-E-R-L-I-N-G.",emoji:"🦋"},
  {id:"ktest_103",q:"How many legs does a dragonfly have?",a:6,unit:"legs",hint:"All insects have exactly 6 legs.",emoji:"🪲"},
  {id:"ktest_104",q:"How many teeth does an adult human have?",a:32,unit:"teeth",hint:"Including the wisdom teeth.",emoji:"🦷"},
  {id:"ktest_105",q:"How deep is the deepest lake in the world (Lake Baikal)?",a:1642,unit:"meters",hint:"In Russia – as deep as 5 Eiffel Towers.",emoji:"💧"},
  {id:"ktest_106",q:"How many planets are there in our solar system?",a:8,unit:"planets",hint:"Pluto hasn't counted since 2006.",emoji:"🪐"},
  {id:"ktest_107",q:"How heavy is a newborn baby on average, in kg?",a:3.4,unit:"kg",hint:"Between 2.5 and 4.5 kg is normal.",emoji:"👶"},
  {id:"ktest_108",q:"How long is a school year in Germany, in weeks?",a:40,unit:"weeks",hint:"With about 12 weeks of vacation.",emoji:"🏫"},
  {id:"ktest_109",q:"How many bones does a newborn have?",a:270,unit:"bones",hint:"More than adults – many fuse together.",emoji:"🦴"},
  {id:"ktest_110",q:"How many ribs does a person have?",a:24,unit:"ribs",hint:"12 pairs – left and right sides.",emoji:"🦴"},
  {id:"ktest_111",q:"How many liters of blood does a 10-year-old child have?",a:3,unit:"liters",hint:"Adults have about 5-6 liters.",emoji:"🩸"},
  {id:"ktest_112",q:"How many km/h does the fastest human run?",a:45,unit:"km/h",hint:"Usain Bolt reached 44.7 km/h (as of ~2024).",emoji:"⚡"},
  {id:"ktest_113",q:"How many countries are there in Europe?",a:44,unit:"countries",hint:"Depending on how you count, 44-50 countries.",emoji:"🗺️"},
  {id:"ktest_114",q:"How many corners does a triangle have?",a:3,unit:"corners",hint:"Tri = three.",emoji:"🔺"},
  {id:"ktest_115",q:"How high does an airplane fly normally, in meters?",a:10000,unit:"meters",hint:"Cruising altitude is 9,000-12,000 meters.",emoji:"✈️"},
  {id:"ktest_116",q:"How many fingers does a person have on both hands?",a:10,unit:"fingers",hint:"5 per hand.",emoji:"🖐️"},
  {id:"ktest_117",q:"How many toes does a person have on both feet?",a:10,unit:"toes",hint:"5 per foot.",emoji:"🦶"},
  {id:"ktest_118",q:"How many calories does an apple have approximately?",a:80,unit:"kcal",hint:"A medium-sized apple.",emoji:"🍎"},
  {id:"ktest_119",q:"How many minutes does a normal movie last?",a:100,unit:"minutes",hint:"Most movies are 90-120 minutes long.",emoji:"🎬"},
  {id:"ktest_120",q:"How many points does a star usually have?",a:5,unit:"points",hint:"The classic star has 5 points.",emoji:"⭐"},
  {id:"ktest_121",q:"How many eyes does a person have?",a:2,unit:"eyes",hint:"Facing forward – for depth perception.",emoji:"👁️"},
  {id:"ktest_122",q:"How many sides does a rectangle have?",a:4,unit:"sides",hint:"Four sides – two pairs of equal length.",emoji:"▭"},
  {id:"ktest_123",q:"How many kilograms does a ton have?",a:1000,unit:"kg",hint:"Kg = 1 ton.",emoji:"⚖️"},
  {id:"ktest_124",q:"How many minutes does a school period last?",a:45,unit:"minutes",hint:"The standard school period in Germany.",emoji:"🏫"},
  {id:"ktest_125",q:"How many meters are a kilometer?",a:1000,unit:"meters",hint:"Kilo = thousand.",emoji:"📏"},
  {id:"ktest_126",q:"How many legs does a crab have?",a:10,unit:"legs",hint:"Ten legs – plus two claws.",emoji:"🦀"},
  {id:"ktest_127",q:"How many hours does half a year have?",a:4380,unit:"hours",hint:"182.5 days × 24 hours.",emoji:"⏰"},
  {id:"ktest_128",q:"How many sides does a hexagon have?",a:6,unit:"sides",hint:"Hexa = six – like a honeycomb.",emoji:"⬡"},
  {id:"ktest_129",q:"How many teeth does a set of baby teeth have?",a:20,unit:"teeth",hint:"Children have 20 baby teeth.",emoji:"🦷"},
  {id:"ktest_130",q:"How many grams does a bar of chocolate usually have?",a:100,unit:"grams",hint:"A standard chocolate bar.",emoji:"🍫"},
  {id:"ktest_131",q:"How many hours does a long-haul flight to New York take?",a:9,unit:"hours",hint:"From Frankfurt, about 8-10 hours.",emoji:"✈️"},
  {id:"ktest_132",q:"How many steps does a staircase usually have per floor?",a:16,unit:"steps",hint:"Average 15-18 steps.",emoji:"🏢"},
  {id:"ktest_133",q:"How many colors does a rainbow have?",a:7,unit:"colors",hint:"Red, orange, yellow, green, blue, indigo, violet.",emoji:"🌈"},
  {id:"ktest_134",q:"How many liters of water should you drink daily?",a:1.5,unit:"liters",hint:"Recommendation for children: 1-1.5 liters.",emoji:"💧"},
  {id:"ktest_135",q:"How many hours does an elementary school child sleep per night?",a:10,unit:"hours",hint:"9-11 hours is recommended.",emoji:"😴"},
  {id:"ktest_136",q:"How many degrees does a full circle have?",a:360,unit:"degrees",hint:"One full rotation.",emoji:"⭕"},
  {id:"ktest_137",q:"How many months does a school year have?",a:10,unit:"months",hint:"September to June with summer vacation.",emoji:"🏫"},
  {id:"ktest_138",q:"How many legs does an ant have?",a:6,unit:"legs",hint:"All insects have 6 legs.",emoji:"🐜"},
  {id:"ktest_139",q:"How many liters does a water bucket have?",a:10,unit:"liters",hint:"A standard household bucket holds 10 liters.",emoji:"🪣"},
  {id:"ktest_140",q:"How many floors does a typical single-family home have?",a:2,unit:"floors",hint:"Ground floor and one upper floor.",emoji:"🏠"},
  {id:"ktest_141",q:"How many minutes does a quarter hour have?",a:15,unit:"minutes",hint:"A quarter of 60 minutes.",emoji:"⏰"},
  {id:"ktest_142",q:"How many dots does a die have on all sides total?",a:21,unit:"dots",hint:"1+2+3+4+5+6 = 21.",emoji:"🎲"},
  {id:"ktest_143",q:"How many cm is a decimeter?",a:10,unit:"cm",hint:"Deci = ten.",emoji:"📏"},
  {id:"ktest_144",q:"How many sides does a triangle have?",a:3,unit:"sides",hint:"Tri = three.",emoji:"🔺"},
  {id:"ktest_145",q:"How many months does a quarter year have?",a:3,unit:"months",hint:"A quarter of 12 months.",emoji:"📅"},
  {id:"ktest_146",q:"How many liters does a bathtub hold?",a:150,unit:"liters",hint:"A typical bathtub holds 120-180 liters.",emoji:"🛁"},
  {id:"ktest_147",q:"How many teeth does a full-grown dog have?",a:42,unit:"teeth",hint:"More than a human.",emoji:"🐕"},
  {id:"ktest_148",q:"How many colors does the rainbow have in total?",a:7,unit:"colors",hint:"All the spectral colors combined.",emoji:"🌈"},
  {id:"ktest_149",q:"How many weekdays are there?",a:7,unit:"days",hint:"Mon, Tue, Wed, Thu, Fri, Sat, Sun.",emoji:"📅"},
  {id:"ktest_150",q:"How many letters does the German word for school, SCHULE, have?",a:6,unit:"letters",hint:"S-C-H-U-L-E.",emoji:"🏫"},
  {id:"ktest_151",q:"How many minutes does half an hour have?",a:30,unit:"minutes",hint:"Half of 60 minutes.",emoji:"⏰"},
  {id:"ktest_152",q:"How many days does March have?",a:31,unit:"days",hint:"Days – the third month.",emoji:"📅"},
  {id:"ktest_153",q:"How many meters deep is an indoor pool?",a:2,unit:"meters",hint:"Usually 1.80-2m deep.",emoji:"🏊"},
  {id:"ktest_154",q:"How many teeth does a rabbit have?",a:28,unit:"teeth",hint:"Rodent-like animals with constantly growing front teeth.",emoji:"🐇"},
  {id:"ktest_155",q:"How many liters does a backpack hold?",a:20,unit:"liters",hint:"School backpacks hold 15-25 liters.",emoji:"🎒"},
  {id:"ktest_156",q:"How many months does half a year have?",a:6,unit:"months",hint:"Half of 12 months.",emoji:"📅"},
  {id:"ktest_157",q:"How many km/h does a commuter train go on average?",a:60,unit:"km/h",hint:"With stops, about 40-60 km/h average.",emoji:"🚊"},
  {id:"ktest_158",q:"How many hours does it take to walk 100km?",a:25,unit:"hours",hint:"At a walking speed of 4 km/h.",emoji:"🚶"},
  {id:"ktest_159",q:"How many chairs fit at a normal dining table?",a:6,unit:"chairs",hint:"A round or oval table for 6 people.",emoji:"🪑"},
  {id:"ktest_160",q:"How many grams does a chocolate bar have?",a:50,unit:"grams",hint:"A typical size for a chocolate bar.",emoji:"🍫"},
  {id:"ktest_161",q:"How many kilos does a sack of potatoes have?",a:10,unit:"kg",hint:"A standard sack of potatoes.",emoji:"🥔"},
  {id:"ktest_162",q:"How many letters does the alphabet have including umlauts?",a:29,unit:"letters",hint:"26 + ä, ö, ü = 29.",emoji:"🔤"},
  {id:"ktest_163",q:"How many legs does a tick have?",a:8,unit:"legs",hint:"Ticks are arachnids.",emoji:"🕷️"},
  {id:"ktest_164",q:"How many days does a year have on average?",a:365.25,unit:"days",hint:"365 days plus a quarter – hence a leap year every 4 years.",emoji:"📅"},
  {id:"ktest_165",q:"How many minutes does a child watch TV daily on average?",a:90,unit:"minutes",hint:"According to studies, about 1.5 hours daily.",emoji:"📺"},
  {id:"ktest_166",q:"How many hours does a baby sleep per day?",a:16,unit:"hours",hint:"Newborns sleep almost the whole day.",emoji:"👶"},
  {id:"ktest_167",q:"How many rungs does a fire truck's ladder have?",a:14,unit:"rungs",hint:"A typical extension ladder.",emoji:"🚒"},
  {id:"ktest_168",q:"How many liters of milk do you need for one kilo of butter?",a:21,unit:"liters",hint:"A lot of milk for very little butter.",emoji:"🧈"},
  {id:"ktest_169",q:"How many grams of salt do you need to cook 500g of pasta?",a:10,unit:"grams",hint:"1-2g of salt per 100g of pasta.",emoji:"🧂"},
  {id:"ktest_170",q:"How fast does a roller coaster go at maximum, in km/h?",a:130,unit:"km/h",hint:"The fastest roller coasters in the world.",emoji:"🎢"},
  {id:"ktest_171",q:"How many hours does a school week last?",a:30,unit:"hours",hint:"At 6 hours daily.",emoji:"🏫"},
  {id:"ktest_172",q:"How many minutes does a movie last on average?",a:100,unit:"minutes",hint:"Most movies are 90-120 minutes.",emoji:"🎬"},
  {id:"ktest_173",q:"How many days does August have?",a:31,unit:"days",hint:"One of the months with 31 days.",emoji:"📅"},
  {id:"ktest_174",q:"How many eyes does a fly have?",a:2,unit:"eyes",hint:"But each eye has thousands of individual lenses.",emoji:"🪰"},
  {id:"ktest_175",q:"How many legs does a crab have?",a:10,unit:"legs",hint:"Crabs are decapods (ten-footed).",emoji:"🦀"},
  {id:"ktest_176",q:"How many corners does a cube have?",a:8,unit:"corners",hint:"A cube has 8 corners, 12 edges, and 6 faces.",emoji:"🎲"},
  {id:"ktest_177",q:"How many months have 31 days?",a:7,unit:"months",hint:"Jan, Mar, May, Jul, Aug, Oct, Dec.",emoji:"📅"},
  {id:"ktest_178",q:"How many grams does half a kilogram have?",a:500,unit:"grams",hint:"Half of 1000g.",emoji:"⚖️"},
  {id:"ktest_179",q:"How many minutes does a day have?",a:1440,unit:"minutes",hint:"24 hours × 60 minutes.",emoji:"⏰"},
  {id:"ktest_180",q:"How many edges does a cube have?",a:12,unit:"edges",hint:"Each face has 4 edges – but shared.",emoji:"🎲"},
  {id:"ktest_181",q:"How many cm is half a meter?",a:50,unit:"cm",hint:"Half of 100cm.",emoji:"📏"},
  {id:"ktest_182",q:"How many hours does half a week have?",a:84,unit:"hours",hint:"3.5 days × 24 hours.",emoji:"⏰"},
  {id:"ktest_183",q:"How many axles does a car have?",a:2,unit:"axles",hint:"Front and rear axles.",emoji:"🚗"},
  {id:"ktest_184",q:"How many eyes does a fly have?",a:2,unit:"eyes",hint:"Two compound eyes with thousands of lenses each.",emoji:"🪰"},
  {id:"ktest_185",q:"How many legs does a horse have?",a:4,unit:"legs",hint:"Four hooves.",emoji:"🐴"},
  {id:"ktest_186",q:"How many fins does a goldfish have?",a:7,unit:"fins",hint:"Dorsal, pectoral (2), pelvic (2), anal, tail.",emoji:"🐠"},
  {id:"ktest_187",q:"How many buttons does a normal shirt have?",a:7,unit:"buttons",hint:"Most shirts have 6-8 buttons.",emoji:"👔"},
  {id:"ktest_188",q:"How many sides does a pentagon have?",a:5,unit:"sides",hint:"Penta = five.",emoji:"⬠"},
  {id:"ktest_189",q:"How many seasons are there?",a:4,unit:"seasons",hint:"Spring, summer, fall, winter.",emoji:"🌸"},
  {id:"ktest_190",q:"How many minutes does a school break last?",a:10,unit:"minutes",hint:"A short break between classes.",emoji:"🏫"},
  {id:"ktest_191",q:"How many wings does a bee have?",a:4,unit:"wings",hint:"Two forewings and two hindwings.",emoji:"🐝"},
  {id:"ktest_192",q:"How many hands does a person have?",a:2,unit:"hands",hint:"Left and right.",emoji:"🙌"},
  {id:"ktest_193",q:"How many cups fit in a liter?",a:4,unit:"cups",hint:"One cup is 250ml.",emoji:"☕"},
  {id:"ktest_194",q:"How many sides does a heptagon have?",a:7,unit:"sides",hint:"Hepta = seven.",emoji:"⬡"},
  {id:"ktest_195",q:"How many months does a quarter have?",a:3,unit:"months",hint:"Q1: Jan-Mar, Q2: Apr-Jun, etc.",emoji:"📅"},
  {id:"ktest_196",q:"How many notes does the musical scale have?",a:7,unit:"notes",hint:"Do, Re, Mi, Fa, Sol, La, Ti.",emoji:"🎵"},
  {id:"ktest_197",q:"How many hours does a long school afternoon have?",a:4,unit:"hours",hint:"From 1pm to 5pm.",emoji:"🏫"},
  {id:"ktest_198",q:"How many wings does a bird have?",a:2,unit:"wings",hint:"Two – left and right.",emoji:"🐦"},
  {id:"ktest_199",q:"How many eyes does a horse have?",a:2,unit:"eyes",hint:"Positioned on the sides for a wide field of view.",emoji:"🐴"},
  {id:"ktest_200",q:"How many hours does it take to walk 10km?",a:2.5,unit:"hours",hint:"At 4 km/h.",emoji:"🚶"},
  {id:"ktest_201",q:"How many liters does a large PET bottle have?",a:1.5,unit:"liters",hint:"The common size at the supermarket.",emoji:"🍶"},
  {id:"ktest_202",q:"How many wheels does a bicycle have?",a:2,unit:"wheels",hint:"Bi = two.",emoji:"🚲"},
  {id:"ktest_203",q:"How many feathers does a peacock's tail have?",a:200,unit:"feathers",hint:"Up to 200 ornamental feathers.",emoji:"🦚"},
  {id:"ktest_204",q:"How many points does a star with 6 points have?",a:6,unit:"points",hint:"The Star of David.",emoji:"✡️"},
  {id:"ktest_205",q:"How many minutes of class does a school week have?",a:1350,unit:"minutes",hint:"30 school periods of 45 minutes each.",emoji:"🏫"},
  {id:"ktest_206",q:"How many legs does a cat have?",a:4,unit:"legs",hint:"Four paws.",emoji:"🐱"},
  {id:"ktest_207",q:"How many sides does a nonagon have?",a:9,unit:"sides",hint:"Nona = nine.",emoji:"🔷"},
  {id:"ktest_208",q:"How many ears does a rabbit have?",a:2,unit:"ears",hint:"Very long ears!",emoji:"🐇"},
  {id:"ktest_209",q:"How many pockets does a pair of jeans usually have?",a:5,unit:"pockets",hint:"2 front, 2 back, 1 small one.",emoji:"👖"},
  {id:"ktest_210",q:"How many spines does a person have?",a:1,unit:"spine",hint:"Made up of 33 individual vertebrae.",emoji:"🦴"},
  {id:"ktest_211",q:"How many eyes does a unicorn have?",a:2,unit:"eyes",hint:"Like all mammals.",emoji:"🦄"},
  {id:"ktest_212",q:"How many teeth does a child lose in total?",a:20,unit:"teeth",hint:"The entire set of baby teeth.",emoji:"🦷"},
  {id:"ktest_213",q:"How many wings does a ladybug have?",a:4,unit:"wings",hint:"2 wing covers and 2 flight wings.",emoji:"🐞"},
  {id:"ktest_214",q:"How many liters does a bathtub have?",a:150,unit:"liters",hint:"A typical bathtub size.",emoji:"🛁"},
  {id:"ktest_215",q:"How many months does a trimester have?",a:3,unit:"months",hint:"A third of a pregnancy.",emoji:"📅"},
  {id:"ktest_216",q:"How many rungs does a normal ladder have?",a:8,unit:"rungs",hint:"Various sizes – about 8.",emoji:"🪜"},
  {id:"ktest_217",q:"How many leaves does a four-leaf clover have?",a:4,unit:"leaves",hint:"Very rare – brings good luck!",emoji:"🍀"},
  {id:"ktest_218",q:"How many axles does a truck have?",a:3,unit:"axles",hint:"1 in front, 2 in back.",emoji:"🚛"},
];
