// 🦕 DINOSAURS – Kids – Part 1 of 235
export default [
  {id:"kdino_001",q:"How many million years ago did the dinosaurs become extinct?",a:66,unit:"million years ago",hint:"An asteroid impact caused the mass extinction.",emoji:"☄️"},
  {id:"kdino_002",q:"How many meters long was the biggest dinosaur (Argentinosaurus)?",a:40,unit:"meters",hint:"Longer than 4 buses in a row (as of ~2024).",emoji:"🦕"},
  {id:"kdino_003",q:"How big was a T-Rex tooth, in cm?",a:30,unit:"cm",hint:"As long as a human forearm.",emoji:"🦷"},
  {id:"kdino_004",q:"How many kg did a full-grown T-Rex weigh?",a:8000,unit:"kg",hint:"Despite its size, it walked on two legs.",emoji:"🦖"},
  {id:"kdino_005",q:"How many million years did dinosaurs live on Earth?",a:165,unit:"million years",hint:"Much longer than humans have existed so far – we're only 0.3 million years old.",emoji:"🌍"},
  {id:"kdino_006",q:"How many horns did a Triceratops have?",a:3,unit:"horns",hint:"Two long ones and a short nose horn.",emoji:"🦏"},
  {id:"kdino_007",q:"How many meters long was a Velociraptor really?",a:1.8,unit:"meters",hint:"Much smaller than in the movies – about the size of a turkey.",emoji:"🦖"},
  {id:"kdino_008",q:"How many million years ago did the first dinosaurs appear?",a:231,unit:"million years ago",hint:"During the Triassic period.",emoji:"🌿"},
  {id:"kdino_009",q:"How many meters long was a Brachiosaurus's neck?",a:9,unit:"meters",hint:"That let it eat leaves from very tall trees.",emoji:"🦕"},
  {id:"kdino_010",q:"How many plates did a Stegosaurus have on its back?",a:17,unit:"plates",hint:"The plates helped regulate its temperature.",emoji:"🦖"},
  {id:"kdino_011",q:"How high could a Brachiosaurus lift its head, in meters?",a:12,unit:"meters",hint:"As high as a four-story house.",emoji:"🦕"},
  {id:"kdino_012",q:"How many teeth did a T-Rex have?",a:60,unit:"teeth",hint:"And they kept regrowing, like a shark's.",emoji:"🦷"},
  {id:"kdino_013",q:"How fast could a T-Rex run, in km/h?",a:20,unit:"km/h",hint:"Slower than a person on a bicycle.",emoji:"🦖"},
  {id:"kdino_014",q:"How many meters long was a Diplodocus?",a:27,unit:"meters",hint:"The tail alone was half as long as the whole body.",emoji:"🦕"},
  {id:"kdino_015",q:"How many million years ago did the first bird (Archaeopteryx) appear?",a:150,unit:"million years ago",hint:"Birds are the living descendants of dinosaurs.",emoji:"🐦"},
  {id:"kdino_016",q:"How many million years did the Cretaceous period last?",a:79,unit:"million years",hint:"From 145 to 66 million years ago.",emoji:"🌿"},
  {id:"kdino_017",q:"How big was a Compsognathus, in cm?",a:60,unit:"cm",hint:"One of the smallest dinosaurs – about the size of a chicken.",emoji:"🐓"},
  {id:"kdino_018",q:"How many dinosaur species have been discovered so far?",a:700,unit:"species",hint:"And new species are found every year.",emoji:"🔍"},
  {id:"kdino_019",q:"How big was a Pteranodon's wingspan, in meters?",a:7,unit:"meters",hint:"Not a dinosaur, but lived at the same time – a flying reptile.",emoji:"🦅"},
  {id:"kdino_020",q:"How many kilograms did a Brachiosaurus eat daily?",a:400,unit:"kg",hint:"Kg of plants daily – that's a lot.",emoji:"🌿"},
  {id:"kdino_021",q:"How thick was a Pachycephalosaurus's skull, in cm?",a:25,unit:"cm",hint:"For head-butting other dinosaurs of its kind.",emoji:"💀"},
  {id:"kdino_022",q:"How big were the eggs of the largest dinosaur, in cm diameter?",a:45,unit:"cm",hint:"Almost as big as a soccer ball (as of ~2024).",emoji:"🥚"},
  {id:"kdino_023",q:"How long was the spine on a Spinosaurus's back, in cm?",a:180,unit:"cm",hint:"The Spinosaurus had a big sail on its back.",emoji:"🦖"},
  {id:"kdino_024",q:"How long was a Microraptor, in cm?",a:50,unit:"cm",hint:"One of the smallest known dinosaurs.",emoji:"🐦"},
  {id:"kdino_025",q:"How many years did it take to find the first complete T-Rex skeleton?",a:100,unit:"years",hint:"Sue is the most complete T-Rex skeleton ever found.",emoji:"🦴"},
  {id:"kdino_026",q:"How heavy was an Ankylosaurus, in tons?",a:8,unit:"tons",hint:"Heavily armored – its body was like a walking fortress.",emoji:"🛡️"},
  {id:"kdino_027",q:"How long was a full-grown Allosaurus, in meters?",a:12,unit:"meters",hint:"The T-Rex of the Jurassic – lived 150 million years before us.",emoji:"🦖"},
  {id:"kdino_028",q:"How many eggs did an average dinosaur lay per clutch?",a:15,unit:"eggs",hint:"Similar to today's reptiles.",emoji:"🥚"},
  {id:"kdino_029",q:"How big was a Parasaurolophus's crest, in cm?",a:100,unit:"cm",hint:"The crest was used like an instrument to make calls.",emoji:"🦕"},
  {id:"kdino_030",q:"How far could a Pterodactylus fly per day, in km?",a:100,unit:"km",hint:"Flying reptiles were tireless fliers.",emoji:"🦅"},
  {id:"kdino_031",q:"How heavy was a full-grown Stegosaurus, in tons?",a:5,unit:"tons",hint:"Despite its size, it had a tiny brain.",emoji:"🦖"},
  {id:"kdino_032",q:"How many million years did the Triassic period last?",a:52,unit:"million years",hint:"From 252 to 201 million years ago.",emoji:"🌿"},
  {id:"kdino_033",q:"How long was a Triceratops, in meters?",a:9,unit:"meters",hint:"With three horns and a bony frill.",emoji:"🦏"},
  {id:"kdino_034",q:"How heavy was a Triceratops, in tons?",a:8,unit:"tons",hint:"About as heavy as a T-Rex.",emoji:"🦏"},
  {id:"kdino_035",q:"How many teeth did a Hadrosaur have?",a:1000,unit:"teeth",hint:"Duck-billed dinosaurs with tooth batteries.",emoji:"🦷"},
  {id:"kdino_036",q:"How long was a Spinosaurus, in meters?",a:18,unit:"meters",hint:"Probably longer than a T-Rex.",emoji:"🦖"},
  {id:"kdino_037",q:"How tall was a Brachiosaurus, in meters?",a:13,unit:"meters",hint:"As tall as a four-story house.",emoji:"🦕"},
  {id:"kdino_038",q:"How many days did dinosaurs incubate their eggs?",a:90,unit:"days",hint:"Depending on the species, 45 to 180 days.",emoji:"🥚"},
  {id:"kdino_039",q:"How heavy was a full-grown Iguanodon, in tons?",a:3.5,unit:"tons",hint:"One of the first dinosaurs ever discovered.",emoji:"🦖"},
  {id:"kdino_040",q:"How long was an Ankylosaurus, in meters?",a:10,unit:"meters",hint:"Armored like a tank.",emoji:"🛡️"},
  {id:"kdino_041",q:"How fast could a Gallimimus run, in km/h?",a:70,unit:"km/h",hint:"One of the fastest dinosaurs.",emoji:"🦖"},
  {id:"kdino_042",q:"How long was a Brontosaurus, in meters?",a:22,unit:"meters",hint:"For a long time, people thought it was the same as Apatosaurus.",emoji:"🦕"},
  {id:"kdino_043",q:"How heavy was a Carnotaurus, in tons?",a:2,unit:"tons",hint:"Had two small horns on its head.",emoji:"🦖"},
  {id:"kdino_044",q:"How many vertebrae did a Diplodocus have in its neck?",a:15,unit:"neck vertebrae",hint:"The long neck was made of 15 vertebrae.",emoji:"🦕"},
  {id:"kdino_045",q:"How long was an Archaeopteryx, in cm?",a:50,unit:"cm",hint:"The transition between dinosaur and bird.",emoji:"🐦"},
  {id:"kdino_046",q:"How big was a Pachycephalosaurus's skull, in cm?",a:60,unit:"cm",hint:"A thick skull for head-butting.",emoji:"💀"},
  {id:"kdino_047",q:"How heavy was a Maiasaura, in kg?",a:4000,unit:"kg",hint:"A dinosaur that cared for its young.",emoji:"🦖"},
  {id:"kdino_048",q:"How long was a Carnotaurus, in meters?",a:9,unit:"meters",hint:"A South American predator.",emoji:"🦖"},
  {id:"kdino_049",q:"How many fingers did an Iguanodon have?",a:4,unit:"fingers",hint:"Plus a thumb spike as a weapon.",emoji:"🦖"},
  {id:"kdino_050",q:"How heavy was a Stegosaurus, in tons?",a:5,unit:"tons",hint:"Its brain was only 80g – the smallest in the animal kingdom.",emoji:"🦖"},
  {id:"kdino_051",q:"How long was a Coelophysis, in cm?",a:300,unit:"cm",hint:"An early slender predator.",emoji:"🦖"},
  {id:"kdino_052",q:"How big was a Protoceratops egg, in cm?",a:20,unit:"cm",hint:"Many nests were found in Mongolia.",emoji:"🥚"},
  {id:"kdino_053",q:"How heavy was a Parasaurolophus, in tons?",a:2.5,unit:"tons",hint:"Could trumpet like an instrument.",emoji:"🦕"},
  {id:"kdino_054",q:"How long was a Baryonyx, in meters?",a:10,unit:"meters",hint:"A fish-eating dinosaur from England.",emoji:"🦖"},
  {id:"kdino_055",q:"How many teeth did a Diplodocus have?",a:50,unit:"teeth",hint:"Long pegs for stripping leaves.",emoji:"🦷"},
  {id:"kdino_056",q:"How heavy was an Allosaurus, in tons?",a:3,unit:"tons",hint:"The T-Rex of the Jurassic.",emoji:"🦖"},
  {id:"kdino_057",q:"How long was an Oviraptor, in cm?",a:200,unit:"cm",hint:"People thought it stole eggs – wrong!",emoji:"🦖"},
  {id:"kdino_058",q:"How tall was a Tyrannosaurus Rex standing, in meters?",a:5,unit:"meters",hint:"Meters tall – like a double-decker bus.",emoji:"🦖"},
  {id:"kdino_059",q:"How long was a Herrerasaurus, in meters?",a:4,unit:"meters",hint:"One of the oldest known dinosaurs.",emoji:"🦖"},
  {id:"kdino_060",q:"How heavy was a Euoplocephalus, in tons?",a:2,unit:"tons",hint:"Had a bony club on its tail.",emoji:"🛡️"},
  {id:"kdino_061",q:"How big was a Brachiosaurus egg, in cm?",a:30,unit:"cm",hint:"Not yet fully known.",emoji:"🥚"},
  {id:"kdino_062",q:"How many horns did a Styracosaurus have?",a:6,unit:"horns",hint:"Plus one big nose horn.",emoji:"🦏"},
  {id:"kdino_063",q:"How long was a Kentrosaurus, in meters?",a:5,unit:"meters",hint:"An African relative of Stegosaurus.",emoji:"🦖"},
  {id:"kdino_064",q:"How heavy was an Edmontosaurus, in tons?",a:4,unit:"tons",hint:"One of the most common hadrosaurs.",emoji:"🦕"},
  {id:"kdino_065",q:"How long was a Ceratosaurus, in meters?",a:7,unit:"meters",hint:"Had a horn on its nose.",emoji:"🦖"},
  {id:"kdino_066",q:"How tall was a giraffe-like ancestor (Sauroposeidon), in meters?",a:17,unit:"meters",hint:"The tallest known dinosaur.",emoji:"🦕"},
  {id:"kdino_067",q:"How heavy was a Pachycephalosaurus, in tons?",a:450,unit:"kg",hint:"Kg – relatively small.",emoji:"💀"},
  {id:"kdino_068",q:"How long was an Apatosaurus, in meters?",a:23,unit:"meters",hint:"Once called Brontosaurus.",emoji:"🦕"},
  {id:"kdino_069",q:"How many finger joints did a T-Rex have on each small arm?",a:2,unit:"joints",hint:"Tiny arms with 2 fingers.",emoji:"🦖"},
  {id:"kdino_070",q:"How many million years did the Cretaceous period last exactly?",a:79,unit:"million years",hint:"From 145 to 66 million years ago.",emoji:"🌿"},
  {id:"kdino_071",q:"How heavy was a Carcharodontosaurus, in tons?",a:7,unit:"tons",hint:"A North African rival of T-Rex.",emoji:"🦖"},
  {id:"kdino_072",q:"How many eggs did a Maiasaura lay per nest?",a:25,unit:"eggs",hint:"They cared for their young.",emoji:"🥚"},
  {id:"kdino_073",q:"How long was a Therizinosaurus claw, in cm?",a:70,unit:"cm",hint:"The longest claws of any known animal.",emoji:"🦖"},
  {id:"kdino_074",q:"How tall was a Brachiosaurus's neck, in meters?",a:9,unit:"meters",hint:"Almost as long as the whole body.",emoji:"🦕"},
  {id:"kdino_075",q:"How heavy was a Diplodocus, in tons?",a:16,unit:"tons",hint:"Despite its length, relatively light.",emoji:"🦕"},
  {id:"kdino_076",q:"How long was a Diplodocus's tail, in meters?",a:14,unit:"meters",hint:"Over half of its body length.",emoji:"🦕"},
  {id:"kdino_077",q:"How many teeth did an Allosaurus have?",a:70,unit:"teeth",hint:"Sharp serrated teeth for tearing.",emoji:"🦷"},
  {id:"kdino_078",q:"How heavy was a Psittacosaurus, in kg?",a:20,unit:"kg",hint:"A small early relative of Triceratops.",emoji:"🦖"},
  {id:"kdino_079",q:"How long was a Spinosaurus's sail, in cm?",a:170,unit:"cm",hint:"The sail on its back was 1.7m tall.",emoji:"🦖"},
  {id:"kdino_080",q:"How many million years did dinosaurs exist in total?",a:165,unit:"million years",hint:"Much longer than humans have existed.",emoji:"🌍"},
  {id:"kdino_081",q:"How big was a Velociraptor compared to a human, in %?",a:50,unit:"% of human height",hint:"Velociraptors were half the size of humans.",emoji:"🦖"},
  {id:"kdino_082",q:"How heavy was a Torvosaurus, in tons?",a:4,unit:"tons",hint:"One of the largest Jurassic predators.",emoji:"🦖"},
  {id:"kdino_083",q:"How long was a Mamenchisaurus's neck, in meters?",a:14,unit:"meters",hint:"The longest neck of any dinosaur.",emoji:"🦕"},
  {id:"kdino_084",q:"How many hours did small dinosaurs incubate their eggs?",a:2880,unit:"hours",hint:"120 days – longer than crocodiles.",emoji:"🥚"},
  {id:"kdino_085",q:"How heavy was a Giraffatitan, in tons?",a:30,unit:"tons",hint:"One of the heaviest dinosaurs.",emoji:"🦕"},
  {id:"kdino_086",q:"How long was a Compsognathus, in cm?",a:60,unit:"cm",hint:"About the size of a chicken.",emoji:"🐓"},
  {id:"kdino_087",q:"How heavy was a Huayangosaurus, in tons?",a:900,unit:"kg",hint:"An early small stegosaur.",emoji:"🦖"},
  {id:"kdino_088",q:"How long was an Ouranosaurus, in meters?",a:8,unit:"meters",hint:"Had a sail or hump on its back.",emoji:"🦕"},
  {id:"kdino_089",q:"How many toes did a Brachiosaurus have on each foot?",a:5,unit:"toes",hint:"Sauropods had 5 toes.",emoji:"🦕"},
  {id:"kdino_090",q:"How heavy was a Ceratosaurus, in tons?",a:1,unit:"ton",hint:"With a horn on its nose.",emoji:"🦖"},
  {id:"kdino_091",q:"How long was a Tenontosaurus, in meters?",a:8,unit:"meters",hint:"Prey for Velociraptors.",emoji:"🦕"},
  {id:"kdino_092",q:"How many claws did a Therizinosaurus have?",a:3,unit:"claws per hand",hint:"Giant claws – for eating plants.",emoji:"🦖"},
  {id:"kdino_093",q:"How heavy was a Sarcosuchus (super-crocodile), in tons?",a:8,unit:"tons",hint:"The biggest crocodile that ever lived.",emoji:"🐊"},
  {id:"kdino_094",q:"How long was a Sarcosuchus, in meters?",a:12,unit:"meters",hint:"Lived during the time of the dinosaurs.",emoji:"🐊"},
  {id:"kdino_095",q:"How many million years ago did the last dinosaurs die out?",a:66,unit:"million years ago",hint:"Because of the asteroid impact.",emoji:"☄️"},
  {id:"kdino_096",q:"How big was an Argentinosaurus vertebra, in meters?",a:1.8,unit:"meters long",hint:"Each vertebra was bigger than a person.",emoji:"🦕"},
  {id:"kdino_097",q:"How heavy was a Megalosaurus, in tons?",a:1,unit:"ton",hint:"The first scientifically described dinosaur.",emoji:"🦖"},
  {id:"kdino_098",q:"How long was a Camptosaurus, in meters?",a:7,unit:"meters",hint:"A two-legged plant-eater.",emoji:"🦕"},
  {id:"kdino_099",q:"How many sets of teeth did a Hadrosaur have?",a:1000,unit:"teeth at once",hint:"Always regrowing.",emoji:"🦷"},
  {id:"kdino_100",q:"How heavy was a Yangchuanosaurus, in tons?",a:3,unit:"tons",hint:"A Chinese Jurassic predator.",emoji:"🦖"},
  {id:"kdino_101",q:"How long was a Lessemsaurus, in meters?",a:9,unit:"meters",hint:"An early sauropod from Argentina.",emoji:"🦕"},
  {id:"kdino_102",q:"How many feathers did a Microraptor have?",a:500,unit:"feathers",hint:"A four-winged miniature dinosaur.",emoji:"🪶"},
  {id:"kdino_103",q:"How heavy was a Heterodontosaurus, in kg?",a:2,unit:"kg",hint:"A tiny early dinosaur.",emoji:"🦖"},
  {id:"kdino_104",q:"How long was a Plateosaurus, in meters?",a:9,unit:"meters",hint:"An early European prosauropod.",emoji:"🦕"},
  {id:"kdino_105",q:"How many million years did the Stegosaurus exist?",a:8,unit:"million years",hint:"Only 8 million years on Earth.",emoji:"🦖"},
  {id:"kdino_106",q:"How heavy was a Daspletosaurus, in tons?",a:3,unit:"tons",hint:"An ancestor of T-Rex.",emoji:"🦖"},
  {id:"kdino_107",q:"How long was a Saltasaurus, in meters?",a:12,unit:"meters",hint:"An armored sauropod from Argentina.",emoji:"🦕"},
  {id:"kdino_108",q:"How many teeth did a Parasaurolophus have?",a:800,unit:"teeth",hint:"Tooth batteries like all hadrosaurs.",emoji:"🦷"},
  {id:"kdino_109",q:"How heavy was a Megaraptor, in tons?",a:1.5,unit:"tons",hint:"A large predator from Argentina.",emoji:"🦖"},
  {id:"kdino_110",q:"How many ribs did a Diplodocus have?",a:24,unit:"pairs of ribs",hint:"Long ribs for the huge body.",emoji:"🦕"},
  {id:"kdino_111",q:"How heavy was a Styracosaurus, in tons?",a:3,unit:"tons",hint:"With an impressive bony frill.",emoji:"🦏"},
  {id:"kdino_112",q:"How long was an Albertosaurus, in meters?",a:9,unit:"meters",hint:"A smaller relative of T-Rex.",emoji:"🦖"},
  {id:"kdino_113",q:"How many meters long was a T-Rex's tail?",a:6,unit:"meters",hint:"The tail helped with balance.",emoji:"🦖"},
  {id:"kdino_114",q:"How heavy was a Dilophosaurus, in kg?",a:400,unit:"kg",hint:"Had two crests on its head.",emoji:"🦖"},
  {id:"kdino_115",q:"How long was a Scelidosaurus, in meters?",a:4,unit:"meters",hint:"An early armored dinosaur.",emoji:"🦖"},
  {id:"kdino_116",q:"How heavy was a Wannanosaurus, in kg?",a:0.5,unit:"kg",hint:"A tiny pachycephalosaur.",emoji:"🦖"},
  {id:"kdino_117",q:"How long was a Pisanosaurus, in cm?",a:100,unit:"cm",hint:"One of the oldest ornithischians.",emoji:"🦖"},
  {id:"kdino_118",q:"How many million years did the Jurassic period last?",a:56,unit:"million years",hint:"From 201 to 145 million years ago.",emoji:"🌿"},
  {id:"kdino_119",q:"How heavy was a Concavenator, in tons?",a:1,unit:"ton",hint:"Had a hump-like bump on its back.",emoji:"🦖"},
  {id:"kdino_120",q:"How long was an Irritator, in meters?",a:8,unit:"meters",hint:"A spinosaur from Brazil – hard to identify.",emoji:"🦖"},
  {id:"kdino_121",q:"How many points did the bony frill of a Triceratops have?",a:5,unit:"points",hint:"The jagged edge of the neck shield.",emoji:"🦏"},
  {id:"kdino_122",q:"How heavy was a Rapetosaurus, in tons?",a:8,unit:"tons",hint:"A titanosaur from Madagascar.",emoji:"🦕"},
  {id:"kdino_123",q:"How long was an Iguanodon's thumb spike, in cm?",a:15,unit:"cm",hint:"Used as a defensive weapon.",emoji:"🦖"},
  {id:"kdino_124",q:"How many species of dinosaurs are estimated to have existed?",a:1000,unit:"species",hint:"Only ~700 have been found so far.",emoji:"🔍"},
  {id:"kdino_125",q:"How heavy was a Pentaceratops, in tons?",a:5,unit:"tons",hint:"Had five horn-like structures.",emoji:"🦏"},
  {id:"kdino_126",q:"How long was a Muttaburrasaurus, in meters?",a:8,unit:"meters",hint:"An Australian iguanodontid.",emoji:"🦕"},
  {id:"kdino_127",q:"How many fingers did a Tyrannosaurus Rex have?",a:2,unit:"fingers",hint:"Two tiny fingers on its small arms.",emoji:"🦖"},
  {id:"kdino_128",q:"How heavy was a Giganotosaurus, in tons?",a:7,unit:"tons",hint:"A South American rival of T-Rex.",emoji:"🦖"},
  {id:"kdino_129",q:"How long was a Shunosaurus, in meters?",a:11,unit:"meters",hint:"Had a bony club on its tail.",emoji:"🦕"},
  {id:"kdino_130",q:"How many neck vertebrae did a Supersaurus have?",a:15,unit:"vertebrae",hint:"One of the longest dinosaur necks.",emoji:"🦕"},
  {id:"kdino_131",q:"How heavy was a Lambeosaurus, in tons?",a:5,unit:"tons",hint:"Had a special head crest.",emoji:"🦕"},
  {id:"kdino_132",q:"How long was a Euhelopus, in meters?",a:15,unit:"meters",hint:"A sauropod from China.",emoji:"🦕"},
  {id:"kdino_133",q:"How many billion years after Earth formed did the first dinosaurs appear?",a:4.2,unit:"billion years later",hint:"Earth is 4.5 billion years old – dinosaurs appeared 230 million years ago.",emoji:"🌍"},
  {id:"kdino_134",q:"How heavy was a Zuniceratops, in kg?",a:100,unit:"kg",hint:"A small early relative of Triceratops.",emoji:"🦏"},
  {id:"kdino_135",q:"How long was a Draconyx, in meters?",a:4,unit:"meters",hint:"An iguanodontid from Portugal.",emoji:"🦕"},
  {id:"kdino_136",q:"How many horn-teeth did a Psittacosaurus have?",a:9,unit:"teeth",hint:"A small early relative of Triceratops.",emoji:"🦖"},
  {id:"kdino_137",q:"How heavy was a Kritosaurus, in tons?",a:3,unit:"tons",hint:"A hadrosaur from North America.",emoji:"🦕"},
  {id:"kdino_138",q:"How long was an Isanosaurus, in meters?",a:15,unit:"meters",hint:"A sauropod from Thailand.",emoji:"🦕"},
  {id:"kdino_139",q:"How long was a Brachiosaurus's tongue, in cm?",a:60,unit:"cm",hint:"Perfect for plucking leaves from trees.",emoji:"🦕"},
  {id:"kdino_140",q:"How many eggs could an Oviraptor lay at once?",a:22,unit:"eggs",hint:"The name means 'egg thief' – but that wasn't true.",emoji:"🥚"},
  {id:"kdino_141",q:"How long were a Deinonychus's claws, in cm?",a:12,unit:"cm",hint:"These claws made it a dangerous hunter.",emoji:"🦖"},
  {id:"kdino_142",q:"How tall could a T-Rex stand upright, in meters?",a:6,unit:"meters",hint:"As tall as a two-story house.",emoji:"🦖"},
  {id:"kdino_143",q:"How many tons did a Brachiosaurus weigh?",a:80,unit:"tons",hint:"One of the heaviest animals ever to live.",emoji:"🦕"},
  {id:"kdino_144",q:"How many fingers did a T-Rex have on each arm?",a:2,unit:"fingers",hint:"Small arms with only two fingers.",emoji:"🦖"},
  {id:"kdino_145",q:"How fast could an Ornithomimus run, in km/h?",a:60,unit:"km/h",hint:"One of the fastest dinosaurs.",emoji:"🏃"},
  {id:"kdino_146",q:"How long did a Parasaurolophus grow, in meters?",a:10,unit:"meters",hint:"Known for its long hollow crest.",emoji:"🦕"},
  {id:"kdino_147",q:"How many kilograms did a T-Rex eat daily?",a:230,unit:"kg",hint:"A lot of meat for such a big animal.",emoji:"🦖"},
  {id:"kdino_148",q:"How many years did dinosaurs live on average?",a:80,unit:"years",hint:"Large sauropods lived especially long.",emoji:"📅"},
  {id:"kdino_149",q:"How big was a T-Rex's brain, in cm³?",a:340,unit:"cm³",hint:"Smaller than a human brain – but it was still clever.",emoji:"🧠"},
  {id:"kdino_150",q:"How long was an Iguanodon, in meters?",a:10,unit:"meters",hint:"One of the first dinosaurs ever discovered.",emoji:"🦖"},
  {id:"kdino_151",q:"How many feathers did an Archaeopteryx have?",a:12,unit:"tail feathers",hint:"A transitional animal between dinosaur and bird.",emoji:"🪶"},
  {id:"kdino_152",q:"How heavy was a Triceratops skull, in kg?",a:400,unit:"kg",hint:"One of the biggest animal heads of all time.",emoji:"💀"},
  {id:"kdino_153",q:"How far could a Pterodactylus glide, in meters?",a:100,unit:"meters",hint:"Not a dinosaur, but a flying contemporary.",emoji:"🦅"},
  {id:"kdino_154",q:"How many toes did a Velociraptor have?",a:4,unit:"toes",hint:"One toe was the famous sickle claw.",emoji:"🦶"},
  {id:"kdino_155",q:"How long was a Diplodocus's tail, in meters?",a:14,unit:"meters",hint:"It was used like a whip.",emoji:"🦕"},
  {id:"kdino_156",q:"How heavy was a Ceratosaurus, in kg?",a:980,unit:"kg",hint:"Almost a ton – a medium-sized carnivore.",emoji:"🦖"},
  {id:"kdino_157",q:"How long was an Allosaurus tooth, in cm?",a:10,unit:"cm",hint:"Serrated like a saw blade.",emoji:"🦷"},
  {id:"kdino_158",q:"How tall was the sail on a Spinosaurus's back, in cm?",a:180,unit:"cm",hint:"An almost 2-meter-tall sail on its back.",emoji:"🦖"},
  {id:"kdino_159",q:"How long was an Apatosaurus's neck, in meters?",a:6,unit:"meters",hint:"Once also called Brontosaurus.",emoji:"🦕"},
  {id:"kdino_160",q:"How many ribs did a large sauropod have?",a:24,unit:"ribs",hint:"Lots of ribs for the long body.",emoji:"🦴"},
  {id:"kdino_161",q:"How heavy was a Pachycephalosaurus, in kg?",a:450,unit:"kg",hint:"A medium-weight plant-eater.",emoji:"🦖"},
  {id:"kdino_162",q:"How long were a Quetzalcoatlus's wings?",a:11,unit:"meters",hint:"The largest known flying reptile.",emoji:"🦅"},
  {id:"kdino_163",q:"How far could a Dilophosaurus spit, according to Jurassic Park?",a:5,unit:"meters",hint:"In real life it didn't spit venom – that was just Hollywood.",emoji:"🎬"},
  {id:"kdino_164",q:"How long was a Mosasaurus, in meters?",a:17,unit:"meters",hint:"A giant ocean predator – not a real dinosaur.",emoji:"🌊"},
  {id:"kdino_165",q:"How old did turtles get during the age of dinosaurs, in years?",a:100,unit:"years",hint:"Turtles already lived alongside dinosaurs.",emoji:"🐢"},
  {id:"kdino_166",q:"How many hours a day did a plant-eating dinosaur eat?",a:16,unit:"hours",hint:"Almost nonstop eating to get enough energy.",emoji:"🌿"},
  {id:"kdino_167",q:"How long was a Corythosaurus's crest, in cm?",a:50,unit:"cm",hint:"A helmet-shaped head for communication.",emoji:"🦕"},
  {id:"kdino_168",q:"How heavy was a Tyrannosaurus leg bone, in kg?",a:20,unit:"kg",hint:"Massive bones for its weight.",emoji:"🦴"},
  {id:"kdino_169",q:"How many meters deep did dinosaurs dig their nests?",a:1,unit:"meter",hint:"Some dinosaurs built deep earthen nests.",emoji:"🥚"},
  {id:"kdino_170",q:"How long was a Gallimimus, in meters?",a:6,unit:"meters",hint:"A fast, ostrich-like dinosaur.",emoji:"🏃"},
  {id:"kdino_171",q:"How many km/h could a Gallimimus run?",a:50,unit:"km/h",hint:"One of the fastest dinosaurs.",emoji:"⚡"},
  {id:"kdino_172",q:"How tall was a full-grown Brachiosaurus, in meters?",a:13,unit:"meters",hint:"It could look into a fourth-story window.",emoji:"🦕"},
  {id:"kdino_173",q:"How long was a Stegosaurus's tail spike, in cm?",a:90,unit:"cm",hint:"The tail spikes were called a thagomizer.",emoji:"💪"},
  {id:"kdino_174",q:"How many million years ago did the first bird live?",a:150,unit:"million years",hint:"Archaeopteryx – the transition from dinosaur to bird.",emoji:"🐦"},
  {id:"kdino_175",q:"How thick was a Pachycephalosaurus's skull bone, in cm?",a:25,unit:"cm",hint:"Evolved for head-butting.",emoji:"💀"},
  {id:"kdino_176",q:"How long was a Compsognathus's body, in cm?",a:60,unit:"cm",hint:"One of the smallest known dinosaurs.",emoji:"🐓"},
  {id:"kdino_177",q:"How many million years did the Cretaceous period last?",a:79,unit:"million years",hint:"From 145 to 66 million years ago.",emoji:"📅"},
  {id:"kdino_178",q:"How tall did a tree fern grow during the age of dinosaurs, in meters?",a:15,unit:"meters",hint:"Giant plants for giant plant-eaters.",emoji:"🌿"},
  {id:"kdino_179",q:"How many bone pieces did an Ankylosaurus's armor have?",a:2000,unit:"bone pieces",hint:"A natural suit of armor.",emoji:"🛡️"},
  {id:"kdino_180",q:"How many months did a large dinosaur's pregnancy last?",a:6,unit:"months",hint:"Similar to large reptiles today.",emoji:"🥚"},
  {id:"kdino_181",q:"How far could a Pteranodon fly per day?",a:500,unit:"km",hint:"A tireless flier over oceans.",emoji:"🦅"},
  {id:"kdino_182",q:"How long was an Amargasaurus's neck spike, in cm?",a:60,unit:"cm",hint:"A double row of spikes on its neck and back.",emoji:"🦕"},
  {id:"kdino_183",q:"How many seconds did a dinosaur's heartbeat last?",a:0.3,unit:"seconds",hint:"Big heart – slow pulse.",emoji:"❤️"},
  {id:"kdino_184",q:"How heavy was a Maiasaura baby at birth, in kg?",a:0.5,unit:"kg",hint:"It cared for its young in the nest.",emoji:"👶"},
  {id:"kdino_185",q:"How many kilograms did the largest known dinosaur egg weigh?",a:3,unit:"kg",hint:"Kg – big but not huge (as of ~2024).",emoji:"🥚"},
  {id:"kdino_186",q:"How long was a Dromaeosaurus, in cm?",a:180,unit:"cm",hint:"Small but dangerous predator dino.",emoji:"🦖"},
  {id:"kdino_187",q:"How tall was an Ouranosaurus's sail, in cm?",a:60,unit:"cm",hint:"Half a meter – for temperature regulation.",emoji:"🌡️"},
  {id:"kdino_188",q:"How many eggs did a Maiasaura lay per nest?",a:30,unit:"eggs",hint:"Herd animals that cared for their young.",emoji:"🥚"},
  {id:"kdino_189",q:"How long was a Hypsilophodon, in cm?",a:150,unit:"cm",hint:"A small fast plant-eater.",emoji:"🦖"},
  {id:"kdino_190",q:"How far could a Dimorphodon fly, in km?",a:50,unit:"km",hint:"An early flying reptile from the Jurassic.",emoji:"🦅"},
  {id:"kdino_191",q:"How many tons did a Brontosaurus eat weekly?",a:3,unit:"tons",hint:"3,000 kg of plants per week.",emoji:"🌿"},
  {id:"kdino_192",q:"How many dinosaur species lived at the same time during the Cretaceous?",a:1000,unit:"species",hint:"An enormous variety.",emoji:"🦕"},
  {id:"kdino_193",q:"How long was a Microceratus, in cm?",a:60,unit:"cm",hint:"A tiny ancestor of the ceratopsians.",emoji:"🦖"},
  {id:"kdino_194",q:"How many hours did a dinosaur sleep daily?",a:8,unit:"hours",hint:"Similar to crocodiles today.",emoji:"😴"},
  {id:"kdino_195",q:"How long was a Stegosaurus's spike, in cm?",a:90,unit:"cm",hint:"Four tail spikes for defense.",emoji:"⚔️"},
  {id:"kdino_196",q:"How heavy was a newborn T-Rex, in kg?",a:10,unit:"kg",hint:"Small at first – huge as an adult.",emoji:"👶"},
  {id:"kdino_197",q:"How many days did a dinosaur egg take to hatch?",a:90,unit:"days",hint:"Three months of incubation.",emoji:"🥚"},
  {id:"kdino_198",q:"How long was a Centrosaurus, in meters?",a:6,unit:"meters",hint:"A herd animal with one nose horn.",emoji:"🦏"},
  {id:"kdino_199",q:"How many senses did a Tyrannosaurus have?",a:5,unit:"senses",hint:"Sight, hearing, smell, taste, touch.",emoji:"👁️"},
  {id:"kdino_200",q:"How long was a Protoceratops, in cm?",a:180,unit:"cm",hint:"A small ancestor of Triceratops.",emoji:"🦖"},
  {id:"kdino_201",q:"How heavy was an Iguanodon, in tons?",a:5,unit:"tons",hint:"One of the first dinosaurs ever described.",emoji:"🦴"},
  {id:"kdino_202",q:"How many back plates did a Stegosaurus have?",a:17,unit:"plates",hint:"Arranged in staggered rows.",emoji:"🦖"},
  {id:"kdino_203",q:"How long was a Suchomimus, in meters?",a:11,unit:"meters",hint:"A fish-eater similar to Spinosaurus.",emoji:"🦖"},
  {id:"kdino_204",q:"How many million years ago did the first mammals appear?",a:225,unit:"million years",hint:"At the same time as the first dinosaurs.",emoji:"🐭"},
  {id:"kdino_205",q:"How tall did a horsetail plant grow during the Triassic, in meters?",a:15,unit:"meters",hint:"Giant plants that are tiny today.",emoji:"🌿"},
  {id:"kdino_206",q:"How many tons did a Laplatasaurus weigh?",a:90,unit:"tons",hint:"One of the heaviest sauropods.",emoji:"🦕"},
  {id:"kdino_207",q:"How long was an Edmontosaurus, in meters?",a:13,unit:"meters",hint:"A large duck-billed dinosaur.",emoji:"🦕"},
  {id:"kdino_208",q:"How many hours a day did sauropods move around?",a:18,unit:"hours",hint:"Almost nonstop walking and eating.",emoji:"🚶"},
  {id:"kdino_209",q:"How far did dromaeosaurs jump, in meters?",a:4,unit:"meters",hint:"Leaping onto their prey.",emoji:"🦘"},
  {id:"kdino_210",q:"How many thousand species lived during the Jurassic period?",a:500,unit:"thousand",hint:"Enormous diversity in that era.",emoji:"🌍"},
  {id:"kdino_211",q:"How long was a Camarasaurus, in meters?",a:23,unit:"meters",hint:"The most common sauropod in North America.",emoji:"🦕"},
  {id:"kdino_212",q:"How many vertebrae did a Diplodocus have?",a:90,unit:"vertebrae",hint:"A long neck and tail mean lots of vertebrae.",emoji:"🦴"},
  {id:"kdino_213",q:"How heavy was a Torosaurus skull, in kg?",a:700,unit:"kg",hint:"The largest animal skull of all time.",emoji:"💀"},
  {id:"kdino_214",q:"How long was a Maiasaura, in meters?",a:9,unit:"meters",hint:"Its name means 'good mother lizard'.",emoji:"🦕"},
  {id:"kdino_215",q:"How fast could a Ceratosaurus run, in km/h?",a:30,unit:"km/h",hint:"A medium-speed carnivore.",emoji:"🏃"},
  {id:"kdino_216",q:"How deep were dinosaur footprints in mud, in cm?",a:30,unit:"cm",hint:"Deep imprints from large sauropods.",emoji:"👣"},
  {id:"kdino_217",q:"How many million years ago did the first crocodiles appear?",a:230,unit:"million years",hint:"They lived alongside dinosaurs.",emoji:"🐊"},
  {id:"kdino_218",q:"How long was a Zuniceratops, in cm?",a:300,unit:"cm",hint:"An early forerunner of the ceratopsians.",emoji:"🦏"},
  {id:"kdino_219",q:"How heavy was a Pachyrhinosaurus, in tons?",a:4,unit:"tons",hint:"Lived in herds in North America.",emoji:"🦕"},
  {id:"kdino_220",q:"How long was a Lesothosaurus, in cm?",a:100,unit:"cm",hint:"A small early ornithischian.",emoji:"🦖"},
  {id:"kdino_221",q:"How many eggs did a titanosaur lay per season?",a:25,unit:"eggs",hint:"Small eggs for such a huge animal.",emoji:"🥚"},
  {id:"kdino_222",q:"How far did dinosaur herds migrate per year, in km?",a:500,unit:"km",hint:"Seasonal migrations in search of food.",emoji:"🚶"},
  {id:"kdino_223",q:"How many tons did a Giraffatitan weigh?",a:60,unit:"tons",hint:"An African relative of Brachiosaurus.",emoji:"🦕"},
  {id:"kdino_224",q:"How long was a Gorgosaurus, in meters?",a:9,unit:"meters",hint:"A smaller relative of T-Rex.",emoji:"🦖"},
  {id:"kdino_225",q:"How long was a Stygimoloch's horn, in cm?",a:15,unit:"cm",hint:"Head horns used for fighting.",emoji:"🦖"},
  {id:"kdino_226",q:"How heavy was the largest dinosaur egg, in kilograms?",a:5,unit:"kilograms",hint:"5kg – the heaviest known egg (as of ~2024).",emoji:"🥚"},
  {id:"kdino_227",q:"How many kilometers did a Jobaria migrate daily?",a:20,unit:"km",hint:"An African long-necked sauropod.",emoji:"🦕"},
  {id:"kdino_228",q:"How deep was a sauropod footprint, in cm?",a:40,unit:"cm",hint:"Massive imprints in soft ground.",emoji:"👣"},
  {id:"kdino_229",q:"How long was a Sauropodomorpha, in meters?",a:10,unit:"meters",hint:"Early ancestors of the great sauropods.",emoji:"🦕"},
  {id:"kdino_230",q:"How many million years did dinosaurs exist in total?",a:165,unit:"million years",hint:"Much longer than humans so far.",emoji:"📅"},
  {id:"kdino_231",q:"How heavy was a young T-Rex at age 10, in kg?",a:2000,unit:"kg",hint:"It grew fast – up to 2kg per day.",emoji:"🦖"},
  {id:"kdino_232",q:"How long was a Dimorphodon's wingspan, in cm?",a:140,unit:"cm",hint:"An early flying reptile from the Jurassic.",emoji:"🦅"},
  {id:"kdino_233",q:"How many kilograms did a Supersaurus eat daily?",a:500,unit:"kg",hint:"Plants per day.",emoji:"🌿"},
  {id:"kdino_234",q:"How long was a Tsintaosaurus, in meters?",a:10,unit:"meters",hint:"A Chinese duck-billed dinosaur.",emoji:"🦕"},
  {id:"kdino_235",q:"How heavy was a Therizinosaurus, in tons?",a:6,unit:"tons",hint:"Giant claws – but a plant-eater.",emoji:"🦖"},
];
