// 📖 FAIRY TALES – Kids – 50 questions
export default [
  {id:"maer_001",q:"How many dwarfs does Snow White have?",a:7,unit:"dwarfs",hint:"Sneezy, Sleepy, Grumpy, Happy, Bashful, Doc, and Dopey.",emoji:"⛏️"},
  {id:"maer_002",q:"How many years did Sleeping Beauty sleep?",a:100,unit:"years",hint:"100 years – until a prince woke her.",emoji:"💤"},
  {id:"maer_003",q:"How many wishes does the genie grant in Aladdin?",a:3,unit:"wishes",hint:"3 wishes – Aladdin uses them wisely.",emoji:"🧞"},
  {id:"maer_004",q:"How many stepsisters does Cinderella have?",a:2,unit:"stepsisters",hint:"Two mean stepsisters and a mean stepmother.",emoji:"👠"},
  {id:"maer_005",q:"How many sisters does Ariel (the little mermaid) have?",a:6,unit:"sisters",hint:"6 sisters – Ariel is the seventh.",emoji:"🧜"},
  {id:"maer_006",q:"How many kids does the mother goat have in 'The Wolf and the Seven Young Goats'?",a:7,unit:"kids",hint:"7 kids – one hides in the clock case.",emoji:"🐐"},
  {id:"maer_007",q:"How many flies does the brave little tailor kill at once?",a:7,unit:"flies",hint:"Seven in one blow – that's why he writes it on his belt.",emoji:"🪰"},
  {id:"maer_008",q:"How many times does the evil queen try to kill Snow White?",a:3,unit:"attempts",hint:"A corset, a comb, and a poisoned apple.",emoji:"🍎"},
  {id:"maer_009",q:"How many horses pull Cinderella's carriage?",a:6,unit:"horses",hint:"6 white horses – transformed from 6 lizards.",emoji:"🐎"},
  {id:"maer_010",q:"How many golden eggs does the goose lay per day?",a:1,unit:"egg",hint:"One golden egg daily – until the farmer kills the goose.",emoji:"🥚"},
  {id:"maer_011",q:"How many peas does the real princess feel?",a:1,unit:"pea",hint:"A single pea under 20 mattresses.",emoji:"👸"},
  {id:"maer_012",q:"How many mattresses lie on top of the pea?",a:20,unit:"mattresses",hint:"20 mattresses and 20 featherbeds – she still felt it.",emoji:"🛏️"},
  {id:"maer_013",q:"How many brothers are turned into ravens in 'The Twelve Brothers'?",a:12,unit:"brothers",hint:"12 brothers – their sister has to stay silent for 12 years.",emoji:"🐦"},
  {id:"maer_014",q:"How many children does the Pied Piper of Hamelin lure away?",a:130,unit:"children",hint:"130 children followed the Pied Piper – never found again.",emoji:"🐀"},
  {id:"maer_015",q:"How many tasks does the brave little tailor solve?",a:3,unit:"tasks",hint:"3 impossible tasks – he passes all of them through cunning.",emoji:"✂️"},
  {id:"maer_016",q:"How many stars fall in 'The Star Money'?",a:7,unit:"stars",hint:"7 stars fell as coins – the child became rich.",emoji:"⭐"},
  {id:"maer_017",q:"How many dresses does Cinderella get from the tree?",a:3,unit:"dresses",hint:"Silver, gold, and the most beautiful dress for the ball.",emoji:"👗"},
  {id:"maer_018",q:"How many days does Rumpelstiltskin give to guess his name?",a:3,unit:"days",hint:"The miller's daughter has 3 days to guess his name.",emoji:"🧵"},
  {id:"maer_019",q:"How many nights does Rumpelstiltskin spin straw into gold?",a:3,unit:"nights",hint:"3 nights – in exchange he demands a ring, a necklace, and the child.",emoji:"🌙"},
  {id:"maer_020",q:"How many swans does the sister save in 'The Six Swans'?",a:6,unit:"brothers",hint:"6 brothers were turned into swans.",emoji:"🦢"},
  {id:"maer_021",q:"How many tasks does Cinderella get from her stepmother?",a:3,unit:"tasks",hint:"Sorting lentils, sweeping the hearth, and more.",emoji:"⭐"},
  {id:"maer_022",q:"How many voyages does Sinbad the Sailor make?",a:7,unit:"voyages",hint:"7 sea voyages – each brings new adventures.",emoji:"⛵"},
  {id:"maer_023",q:"How many Brothers Grimm collected fairy tales?",a:2,unit:"brothers",hint:"Jacob and Wilhelm Grimm – the most famous pair of brothers.",emoji:"📖"},
  {id:"maer_024",q:"How many fairy tales did the Brothers Grimm collect in total?",a:211,unit:"fairy tales",hint:"211 fairy tales in the complete edition.",emoji:"📚"},
  {id:"maer_025",q:"How many kinds of doves help Cinderella sort the lentils?",a:2,unit:"kinds of doves",hint:"White and speckled doves help her with the impossible task.",emoji:"🕊️"},
  {id:"maer_026",q:"How many children does the family in Hansel and Gretel have?",a:2,unit:"children",hint:"Two children – Hansel and Gretel.",emoji:"🌲"},
  {id:"maer_027",q:"How many meters tall is Rapunzel's tower?",a:20,unit:"meters",hint:"Tall enough that her hair can be used as a ladder.",emoji:"🏰"},
  {id:"maer_028",q:"How many tasks does Marie get in 'Mother Holle'?",a:2,unit:"tests",hint:"Hard work or laziness – the hardworking Marie passes.",emoji:"❄️"},
  {id:"maer_029",q:"How many hairs does the gold child get from the devil?",a:3,unit:"hairs",hint:"3 golden hairs – each one reveals a secret.",emoji:"✨"},
  {id:"maer_030",q:"How many golden hairs does the gold child have?",a:3,unit:"hairs",hint:"3 golden hairs from the devil.",emoji:"✨"},
  {id:"maer_031",q:"How many giants does Jack fight (Jack and the Beanstalk)?",a:1,unit:"giant",hint:"Jack fights one giant – 'Fee-fi-fo-fum!'",emoji:"⚡"},
  {id:"maer_032",q:"How many beans does Jack plant in 'Jack and the Beanstalk'?",a:5,unit:"beans",hint:"5 magic beans – they grow all the way to the sky.",emoji:"🌱"},
  {id:"maer_033",q:"How many sisters does the evil stepmother send dancing?",a:2,unit:"sisters",hint:"The two mean stepsisters – with bound feet.",emoji:"💃"},
  {id:"maer_034",q:"How many hours does the ball at Cinderella's last?",a:3,unit:"hours",hint:"The ball goes until midnight – Cinderella must leave before then.",emoji:"🕛"},
  {id:"maer_035",q:"How many teeth does the bad wolf have in Little Red Riding Hood?",a:32,unit:"teeth",hint:"What big teeth you have – 'all the better to eat you with!'",emoji:"🐺"},
  {id:"maer_036",q:"How many seasons are there in Hans Christian Andersen's fairy tales?",a:4,unit:"seasons",hint:"Spring, summer, fall, winter – the basis of many fairy tales.",emoji:"🌸"},
  {id:"maer_037",q:"How many houses do the three little pigs build?",a:3,unit:"houses",hint:"Straw, sticks, bricks – only the brick house withstands the wolf.",emoji:"🏠"},
  {id:"maer_038",q:"How many times does the wolf huff and puff in 'The Three Little Pigs'?",a:3,unit:"times",hint:"He blows down 3 houses – only the brick house stays standing.",emoji:"💨"},
  {id:"maer_039",q:"How many bears live with Goldilocks?",a:3,unit:"bears",hint:"Papa, Mama, and Baby Bear – Goldilocks tries everything.",emoji:"🐻"},
  {id:"maer_040",q:"How many bowls of porridge does Goldilocks eat?",a:1,unit:"bowl",hint:"Only the baby bear's bowl – just right.",emoji:"🥣"},
  {id:"maer_041",q:"How many dresses does Cinderella's golden nut contain?",a:1,unit:"dress",hint:"Each golden nut holds a beautiful dress.",emoji:"🌰"},
  {id:"maer_042",q:"How many days does Hansel and Gretel walk through the forest?",a:3,unit:"days",hint:"3 days of walking – deep into the dark forest.",emoji:"🌲"},
  {id:"maer_043",q:"How many days did the prince search for the castle in Sleeping Beauty?",a:1,unit:"day",hint:"He found the castle right away – the thorns parted on their own.",emoji:"🌹"},
  {id:"maer_044",q:"How many fairy tales did Hans Christian Andersen write?",a:156,unit:"fairy tales",hint:"156 fairy tales – including 'The Little Mermaid' and 'Thumbelina'.",emoji:"📖"},
  {id:"maer_045",q:"How many years did the Snow Queen live in her ice palace?",a:100,unit:"years",hint:"The Snow Queen has ruled her icy realm for ages.",emoji:"❄️"},
  {id:"maer_046",q:"How many pairs of iron shoes does the girl dance in 'The Red Shoes'?",a:1,unit:"pair",hint:"A single cursed pair of red shoes – they never stop dancing.",emoji:"👠"},
  {id:"maer_047",q:"How many months does the sleep last in 'Sleeping Beauty'?",a:1200,unit:"months",hint:"100 years = 1,200 months of sleep.",emoji:"💤"},
  {id:"maer_048",q:"How many children does the witch try to eat in Hansel and Gretel?",a:2,unit:"children",hint:"Hansel and Gretel – they're cleverly rescued.",emoji:"🏠"},
  {id:"maer_049",q:"How many boots does Puss in Boots need?",a:1,unit:"pair",hint:"Just one pair of boots – that's how his rise begins.",emoji:"😺"},
  {id:"maer_050",q:"How many times does Pinocchio lie (before his nose gets very long)?",a:3,unit:"times",hint:"Three lies before his nose gets really long.",emoji:"🪵"},
];
