// 🏆 SPORT & RECORDS – English
export default [
  {q:"How many Kilometer ist ein Marathon lang?",a:42.195,unit:"km",hint:"Benannt nach dem Lauf eines Boten aus Marathon nach Athen.",emoji:"🏃"},
  {q:"How fast lief Usain Bolt seinen Weltrekord über 100m in Sekunden?",a:9.58,unit:"seconds",hint:"Aufgestellt 2009 in Berlin.",emoji:"⚡"},
  {q:"How many Goldmedaillen gewann Michael Phelps bei Olympia?",a:23,unit:"Goldmedaillen",hint:"Der erfolgreichste Olympiateilnehmer aller Zeiten.",emoji:"🏊"},
  {q:"How high ist ein Basketballkorb in Metern?",a:3.05,unit:"meters",hint:"Die offizielle Höhe in der NBA und bei Olympia.",emoji:"🏀"},
  {q:"How many Spieler stehen beim Fußball auf dem Platz (beide Teams)?",a:22,unit:"Spieler",hint:"11 pro Mannschaft.",emoji:"⚽"},
  {q:"How long is ein olympisches Schwimmbecken in Metern?",a:50,unit:"meters",hint:"Die offizielle Länge für Weltrekorde.",emoji:"🏊"},
  {q:"How many Punkte bekommt man bei einem Touchdown im American Football?",a:6,unit:"Punkte",hint:"Dazu kommt noch ein Extra-Punkt für den Kick.",emoji:"🏈"},
  {q:"How high ist ein Volleyballnetz bei Männern in Metern?",a:2.43,unit:"meters",hint:"Bei Frauen ist es 2,24 Meter hoch.",emoji:"🏐"},
  {q:"How many km fährt ein Tour-de-France-Fahrer insgesamt?",a:3500,unit:"km",hint:"Über 21 Etappen in 3 Wochen.",emoji:"🚴"},
  {q:"How long dauert ein Eishockeyspiel in Minuten (reine Spielzeit)?",a:60,unit:"minutes",hint:"3 Drittel à 20 Minuten.",emoji:"🏒"},
  {q:"How many Runden hat ein Formel-1-Rennen on average?",a:57,unit:"Runden",hint:"Je nach Streckenlänge variiert die Rundenzahl.",emoji:"🏎️"},
  {q:"How many Meter hoch ist der Hochsprung-Weltrekord?",a:2.45,unit:"meters",hint:"Javier Sotomayor stellte 1993 diesen Rekord auf.",emoji:"🏃"},
  {q:"How many Punkte braucht man im Tischtennis zum Gewinnen eines Satzes?",a:11,unit:"Punkte",hint:"Mit 2 Punkten Vorsprung muss man gewinnen.",emoji:"🏓"},
  {q:"How long is ein Fußballfeld maximal in Metern?",a:105,unit:"meters",hint:"Die FIFA-Vorgabe ist 100–110 Meter.",emoji:"⚽"},
  {q:"How many Spieler hat eine Baseballmannschaft?",a:9,unit:"Spieler",hint:"Feldspieler und ein Schlagmann.",emoji:"⚾"},
  {q:"How many Meter weit springt man beim Weitsprung-Weltrekord?",a:8.95,unit:"meters",hint:"Mike Powell sprang 1991 in Tokio diesen Rekord.",emoji:"🏃"},
  {q:"How many Stunden dauerte das längste Tennisspiel aller Zeiten?",a:11,unit:"hours",hint:"Isner vs. Mahut 2010 in Wimbledon.",emoji:"🎾"},
  {q:"How many Mal hat Bayern München die Bundesliga gewonnen?",a:32,unit:"times",hint:"Deutschlands erfolgreichster Fußballklub.",emoji:"⚽"},
  {q:"How big ist ein Basketballfeld in Metern Länge?",a:28,unit:"meters",hint:"Das offizielle FIBA-Spielfeld ist diese Zahl x 15 Meter.",emoji:"🏀"},
  {q:"How many Spieler hat ein Rugbyteam?",a:15,unit:"Spieler",hint:"Im Rugby League sind es 13 Spieler.",emoji:"🏉"},
  {q:"How many Schritte darf man im Basketball ohne Dribbeln machen?",a:2,unit:"Schritte",hint:"Bei 3 Schritten gibt es Schrittfehler.",emoji:"🏀"},
  {q:"How many km/h erreichte der schnellste Tennisaufschlag?",a:263,unit:"km/h",hint:"Samuel Groth aus Australien, 2012.",emoji:"🎾"},
  {q:"How many km weit wirft man beim Speerwurf-Weltrekord?",a:98.48,unit:"meters",hint:"Jan Železný aus Tschechien, 1996.",emoji:"🎯"},
  {q:"How many Tore schoss Ronaldo in seiner Karriere ungefähr?",a:900,unit:"Tore",hint:"Er ist einer der erfolgreichsten Torschützen aller Zeiten.",emoji:"⚽"},
  {q:"How many PS hat ein Formel-1-Motor?",a:1000,unit:"PS",hint:"Moderne F1-Motoren leisten über 1000 PS.",emoji:"🏎️"},
  {q:"How high ist ein Tischtennis-Netz in cm?",a:15.25,unit:"cm",hint:"Nur 15,25 cm – das ist sehr niedrig!",emoji:"🏓"},
  {q:"How many Goldmedaillen hat Usain Bolt bei Olympia gewonnen?",a:8,unit:"Goldmedaillen",hint:"3x Olympia, immer Gold über 100m, 200m und 4x100m.",emoji:"🏅"},
  {q:"How heavy ist ein Fußball in Gramm?",a:430,unit:"grams",hint:"Die FIFA schreibt 410–450 Gramm vor.",emoji:"⚽"},
  {q:"How long is eine Olympia-Bahn beim Schwimmen in Metern?",a:50,unit:"meters",hint:"Kurzbahn-Wettkämpfe finden auf 25 Meter statt.",emoji:"🏊"},
  {q:"How many Felder hat ein Schachbrett?",a:64,unit:"Felder",hint:"8 x 8 Felder, abwechselnd schwarz und weiß.",emoji:"♟️"},
  {q:"How many Spieler hat eine Fußballmannschaft?",a:11,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"⚽"},
  {q:"How big ist ein offizielles Fußballfeld in Metern?",a:105,unit:"Meter Länge",hint:"× 68 Meter.",emoji:"⚽"},
  {q:"How high ist ein Basketballkorb in Metern?",a:3.05,unit:"meters",hint:"Offiziell in NBA und bei Olympia.",emoji:"🏀"},
  {q:"How many Goldmedaillen hat Michael Phelps?",a:23,unit:"Goldmedaillen",hint:"Erfolgreichster Olympionike aller Zeiten.",emoji:"🏊"},
  {q:"How long is ein Olympisches Schwimmbecken?",a:50,unit:"meters",hint:"Für Weltrekorde.",emoji:"🏊"},
  {q:"How fast lief Usain Bolt seine 100m in Sekunden?",a:9.58,unit:"seconds",hint:"Berlin 2009.",emoji:"⚡"},
  {q:"How many km ist ein Marathon lang?",a:42.195,unit:"km",hint:"Benannt nach dem Lauf eines Boten.",emoji:"🏃"},
  {q:"How many Punkte braucht man im Tischtennis?",a:11,unit:"Punkte",hint:"Mit 2 Punkten Vorsprung.",emoji:"🏓"},
  {q:"How many Spieler hat ein Rugby-Team?",a:15,unit:"Spieler",hint:"Im Rugby League 13.",emoji:"🏉"},
  {q:"How high ist ein Volleyball-Netz bei Männern?",a:2.43,unit:"meters",hint:"Bei Frauen 2,24 Meter.",emoji:"🏐"},
  {q:"How many Runden hat ein Formel-1-Rennen?",a:57,unit:"Runden",hint:"Je nach Streckenlänge.",emoji:"🏎️"},
  {q:"How far springt man beim Weitsprung-Weltrekord?",a:8.95,unit:"meters",hint:"Mike Powell, Tokio 1991.",emoji:"🏃"},
  {q:"How many km fährt ein Tour-de-France-Fahrer?",a:3500,unit:"km",hint:"21 Etappen in 3 Wochen.",emoji:"🚴"},
  {q:"How long is ein Eishockeyspiel in Minuten?",a:60,unit:"minutes",hint:"3 Drittel à 20 Minuten.",emoji:"🏒"},
  {q:"How many Schritte darf man im Basketball?",a:2,unit:"Schritte",hint:"Bei 3 Schritten: Schrittfehler.",emoji:"🏀"},
  {q:"How many km/h schlägt Serena Williams einen Aufschlag?",a:207,unit:"km/h",hint:"Rekord für Frauen.",emoji:"🎾"},
  {q:"How many Spieler hat ein Baseballteam?",a:9,unit:"Spieler",hint:"Feldspieler.",emoji:"⚾"},
  {q:"How many Punkte ist ein Touchdown?",a:6,unit:"Punkte",hint:"Plus Extra-Punkt für den Kick.",emoji:"🏈"},
  {q:"How many Stunden dauerte das längste Tennisspiel?",a:11,unit:"hours",hint:"Isner vs. Mahut 2010 in Wimbledon.",emoji:"🎾"},
  {q:"How many Mal hat Bayern München die Bundesliga gewonnen?",a:32,unit:"times",hint:"Deutschlands erfolgreichster Klub.",emoji:"⚽"},
  {q:"How high ist das Tischtennis-Netz in cm?",a:15.25,unit:"cm",hint:"Sehr niedrig.",emoji:"🏓"},
  {q:"How many Punkte gibt es beim Darts pro Pfeil maximal?",a:60,unit:"Punkte",hint:"Dreifach-20 = 60 Punkte.",emoji:"🎯"},
  {q:"How heavy ist ein Fußball in Gramm?",a:430,unit:"grams",hint:"410 bis 450 Gramm.",emoji:"⚽"},
  {q:"How many km/h fliegt ein Badminton-Federball maximal?",a:493,unit:"km/h",hint:"Schnellstes Sportgerät der Welt.",emoji:"🏸"},
  {q:"How big ist ein Basketballfeld in Metern?",a:28,unit:"Meter Länge",hint:"× 15 Meter.",emoji:"🏀"},
  {q:"How many Goldmedaillen hat Usain Bolt bei Olympia?",a:8,unit:"Goldmedaillen",hint:"3x Olympia, immer Gold.",emoji:"🏅"},
  {q:"How many Spieler hat ein Handballteam auf dem Feld?",a:7,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"🤾"},
  {q:"How high ist ein Turnreck in Metern?",a:2.8,unit:"meters",hint:"Das Hochreck bei Männern.",emoji:"🤸"},
  {q:"How long is eine Olympische Laufbahn in Metern?",a:400,unit:"meters",hint:"Alle Stadien haben 400m Bahnen.",emoji:"🏃"},
  {q:"How many Spieler hat eine Eishockeymannschaft auf dem Eis?",a:6,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"🏒"},
  {q:"How many km/h fährt ein Formel-1-Auto maximal?",a:370,unit:"km/h",hint:"Auf langen Geraden.",emoji:"🏎️"},
  {q:"How long is eine Schwimmbahn bei den Olympischen Spielen?",a:50,unit:"meters",hint:"Long Course – für alle Weltrekorde.",emoji:"🏊"},
  {q:"How many Pins stehen beim Bowling?",a:10,unit:"Pins",hint:"Im Dreieck aufgestellt.",emoji:"🎳"},
  {q:"How many Spieler hat ein Wasserball-Team?",a:7,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"🤽"},
  {q:"How high ist ein Sprungbrett bei Olympia in Metern?",a:10,unit:"meters",hint:"Turm-Springen von 10m.",emoji:"🏊"},
  {q:"How many Pferde zieht ein Schlitten beim Hundeschlittenrennen Iditarod?",a:16,unit:"Hunde",hint:"Keine Pferde – Hunde!",emoji:"🐕"},
  {q:"How many km lang ist das Iditarod-Rennen?",a:1600,unit:"km",hint:"Von Anchorage nach Nome, Alaska.",emoji:"🛷"},
  {q:"How many Spieler hat ein Rugby-Sevens-Team?",a:7,unit:"Spieler",hint:"Kleiner als normales Rugby.",emoji:"🏉"},
  {q:"How high ist ein Hochsprung-Weltrekord in Metern?",a:2.45,unit:"meters",hint:"Javier Sotomayor, 1993.",emoji:"🏃"},
  {q:"How many Runden hat ein Boxkampf maximal?",a:12,unit:"Runden",hint:"Profi-Weltmeisterschaftskampf.",emoji:"🥊"},
  {q:"How long is eine Curveball-Wurfbahn beim Baseball in Metern?",a:18.44,unit:"meters",hint:"Der Pitching-Abstand.",emoji:"⚾"},
  {q:"How many Spieler hat ein Cricketteam?",a:11,unit:"Spieler",hint:"Gleich wie Fußball.",emoji:"🏏"},
  {q:"How many Hürden überquert ein Läufer beim 110m-Hürdenlauf?",a:10,unit:"Hürden",hint:"Hürden á 1,067m Höhe.",emoji:"🏃"},
  {q:"How many Kegel stehen beim Kegeln?",a:9,unit:"Kegel",hint:"Im deutschen Kegeln – anders als Bowling.",emoji:"🎳"},
  {q:"How heavy ist ein Diskus bei Frauen in kg?",a:1,unit:"kg",hint:"Bei Männern 2 kg.",emoji:"🥏"},
  {q:"How long is ein Olympisches Ruderrennen in km?",a:2,unit:"km",hint:"2000 Meter auf ruhigem Wasser.",emoji:"🚣"},
  {q:"How high ist ein Turnbarren vom Boden in Metern?",a:2,unit:"meters",hint:"Parallelbarren bei Männern.",emoji:"🤸"},
  {q:"How many km weit wirft der Speerwurf-Weltrekord?",a:98.48,unit:"meters",hint:"Jan Železný, 1996.",emoji:"🎯"},
  {q:"How many Spieler hat ein Volleyball-Team auf dem Feld?",a:6,unit:"Spieler",hint:"Inklusive Libero.",emoji:"🏐"},
  {q:"How long is ein Fußballtrikot-Kurzärmel-Ärmel maximal in cm?",a:30,unit:"cm",hint:"Geregelt in FIFA-Ausrüstungsregeln.",emoji:"👕"},
  {q:"How high ist die Tischtennisplatte vom Boden in cm?",a:76,unit:"cm",hint:"Standardhöhe worldwide.",emoji:"🏓"},
  {q:"How long is eine Badminton-Bahn in Metern?",a:13.4,unit:"meters",hint:"13,4 × 6,1 Meter für Doppel.",emoji:"🏸"},
  {q:"How many Spieler hat ein American-Football-Team auf dem Feld?",a:11,unit:"Spieler",hint:"Offense AND Defense je 11.",emoji:"🏈"},
  {q:"How big ist ein Golfball im Durchmesser in mm?",a:42.67,unit:"mm",hint:"Mindestdurchmesser nach Regelwerk.",emoji:"⛳"},
  {q:"How long is eine Olympisches Ruder-Skullyboot in Metern?",a:8,unit:"meters",hint:"Einer sitzt – 2 Ruder.",emoji:"🚣"},
  {q:"How many Spieler hat ein Lacrosse-Team auf dem Feld?",a:10,unit:"Spieler",hint:"Bei Männern – bei Frauen 12.",emoji:"🥍"},
  {q:"How high ist ein Fußballtor in Metern?",a:2.44,unit:"meters",hint:"2,44m × 7,32m breit.",emoji:"⚽"},
  {q:"How many Stunden dauerte die längste Schachpartie?",a:20,unit:"hours",hint:"Klassisches Schach ohne Zeitkontrolle.",emoji:"♟️"},
  {q:"How many km/h schießt ein Tennisball beim schnellsten Aufschlag?",a:263,unit:"km/h",hint:"Samuel Groth, 2012.",emoji:"🎾"},
  {q:"How long is eine Olympische Triathlon-Schwimmstrecke in km?",a:1.5,unit:"km",hint:"Dann 40km Radfahren und 10km Laufen.",emoji:"🏊"},
  {q:"How many Punkte braucht man im Squash pro Satz?",a:11,unit:"Punkte",hint:"Best of 5 Sätze.",emoji:"🎾"},
  {q:"How long is ein Eishockeyfeld in Metern?",a:61,unit:"meters",hint:"× 30 Meter – NHL-Standard.",emoji:"🏒"},
  {q:"How high ist das Netz beim Beach-Volleyball bei Männern?",a:2.43,unit:"meters",hint:"Gleich wie Hallen-Volleyball.",emoji:"🏐"},
  {q:"How many Spieler hat ein Fußball-Kader bei der WM?",a:26,unit:"Spieler",hint:"Seit der WM 2022.",emoji:"⚽"},
  {q:"How heavy ist eine Kugel beim Kugelstoßen bei Männern in kg?",a:7.26,unit:"kg",hint:"Bei Frauen 4 kg.",emoji:"🏋️"},
  {q:"How long is eine Bowlingbahn in Metern?",a:18.29,unit:"meters",hint:"Von der Abwurflinie zu den Pins.",emoji:"🎳"},
  {q:"How high ist ein Fußball-Tor bei Frauen in Metern?",a:2.44,unit:"meters",hint:"Gleich wie bei Männern.",emoji:"⚽"},
  {q:"How many Schritte macht ein Marathonläufer?",a:40000,unit:"Schritte",hint:"Etwa 40.000 Schritte pro Marathon.",emoji:"🏃"},
  {q:"How long is ein Biathlon-Lauf in km?",a:20,unit:"km",hint:"Plus 4 Schießeinlagen.",emoji:"🎯"},
  {q:"How many Runden dreht ein Radfahrer bei der Olympischen Bahn-Jagd?",a:16,unit:"Runden",hint:"4km auf einer 250m-Bahn.",emoji:"🚴"},
  {q:"How many Punkte hat ein Golfball Grübchen?",a:336,unit:"Grübchen",hint:"Standard sind 300-500 Dimples.",emoji:"⛳"},
  {q:"How long is eine Olympische Kanu-Slalom-Strecke in Metern?",a:250,unit:"meters",hint:"Mit mindestens 18 Toren.",emoji:"🚣"},
  {q:"How high ist ein Turnpferd (Pauschenpferd) in Metern?",a:1.15,unit:"meters",hint:"Standarthöhe laut FIG.",emoji:"🤸"},
  {q:"How many km/h fährt ein Ski-Abfahrtsfahrer maximal?",a:160,unit:"km/h",hint:"Die schnellste alpine Disziplin.",emoji:"⛷️"},
  {q:"How many Spieler hat ein Curling-Team?",a:4,unit:"Spieler",hint:"Ein Skip und drei Sweeper.",emoji:"🥌"},
  {q:"How long is eine Olympische 400m-Hürdenstrecke?",a:400,unit:"meters",hint:"10 Hürden à 91,4cm Höhe bei Männern.",emoji:"🏃"},
  {q:"How heavy ist ein Hammerball beim Hammerwurf in kg?",a:7.26,unit:"kg",hint:"Bei Frauen 4 kg.",emoji:"🔨"},
  {q:"How many km/h schießt ein Eishockey-Puck maximal?",a:175,unit:"km/h",hint:"Bei professionellen Slap Shots.",emoji:"🏒"},
  {q:"How many Spieler hat ein Rugbyteam beim 7er-Rugby?",a:7,unit:"Spieler",hint:"Weniger Spieler, mehr Raum.",emoji:"🏉"},
  {q:"How high ist ein Sprungbrett beim Wasserspringen (Kunstspringen)?",a:3,unit:"meters",hint:"Auch 1m-Brett und 10m-Turm.",emoji:"🏊"},
  {q:"How many Spiele hat ein NBA-Grunddurchgang?",a:82,unit:"Spiele",hint:"Jede Mannschaft spielt 82 Spiele.",emoji:"🏀"},
  {q:"How long is eine Rhythmische Sportgymnastik-Seiltour in Minuten?",a:1.5,unit:"minutes",hint:"75-90 Sekunden Pflichtprogramm.",emoji:"🤸"},
  {q:"How many km legt ein Radfahrer bei der Tour de France daily zurück?",a:175,unit:"km",hint:"Durchschnitt über alle Etappen.",emoji:"🚴"},
  {q:"How high ist der Weltrekord im Stabhochsprung in Metern?",a:6.23,unit:"meters",hint:"Armand Duplantis 2024.",emoji:"🏃"},
  {q:"How many km/h erreicht ein Profi-Tennisspieler beim Aufschlag?",a:230,unit:"km/h",hint:"Durchschnitt der Spitzenserveurs.",emoji:"🎾"},
  {q:"How many Spieler hat ein Cricketteam beim Twenty20?",a:11,unit:"Spieler",hint:"Gleich wie normales Cricket.",emoji:"🏏"},
  {q:"Wie lang dauert eine Judo-Partie maximal in Minuten?",a:5,unit:"minutes",hint:"Bei Gleichstand: Golden Score.",emoji:"🥋"},
  {q:"How many km/h fährt ein Eisschnellläufer auf 500m?",a:60,unit:"km/h",hint:"Sprintdisziplin auf Eis.",emoji:"⛸️"},
  {q:"How many Darts wirft man pro Aufnahme?",a:3,unit:"Darts",hint:"Drei Pfeile pro Zug.",emoji:"🎯"},
  {q:"How long is eine Leichtathletik-Wurfbahn beim Speerwurf in Metern?",a:4,unit:"Meter Breite",hint:"Schmale Bahn für den Anlauf.",emoji:"🎯"},
  {q:"How many Minuten dauert eine Basketball-Halbzeit?",a:10,unit:"minutes",hint:"4 Viertel à 10 Minuten (FIBA).",emoji:"🏀"},
  {q:"How heavy ist ein Fußball (offiziell) in Gramm?",a:430,unit:"grams",hint:"410-450 Gramm laut FIFA.",emoji:"⚽"},
  {q:"How long is die kürzeste olympische Laufdisziplin in Metern?",a:100,unit:"meters",hint:"Der Sprint über 100m.",emoji:"🏃"},
  {q:"How high ist das Netz beim Badminton in Metern?",a:1.55,unit:"meters",hint:"In der Mitte 1,524m.",emoji:"🏸"},
  {q:"How many km/h schießt ein Fußball beim härtesten Schuss?",a:210,unit:"km/h",hint:"Von Profis bei Schussrekorden.",emoji:"⚽"},
  {q:"How long is ein Handball-Spielfeld in Metern?",a:40,unit:"meters",hint:"× 20 Meter.",emoji:"🤾"},
  {q:"How many Spieler hat ein Tug-of-War-Team?",a:8,unit:"Spieler",hint:"Tauziehen – olympische Disziplin bis 1920.",emoji:"🏋️"},
  {q:"How long is ein Bobbahn in Metern?",a:1500,unit:"meters",hint:"Mit vielen Kurven.",emoji:"🛷"},
  {q:"How many km/h erreicht ein Luger beim Rodeln?",a:140,unit:"km/h",hint:"Auf dem Rücken liegend.",emoji:"🛷"},
  {q:"How many Spieler hat ein Ringball-Team?",a:7,unit:"Spieler",hint:"Südafrikanische Sportart.",emoji:"🏀"},
  {q:"How high ist ein Turnreck bei Frauen in Metern?",a:2.5,unit:"meters",hint:"Hochreck für die Uneven Bars.",emoji:"🤸"},
  {q:"How many km lang ist eine Biathlon-Staffel?",a:4,unit:"km pro Läufer",hint:"Läufer × 7.5km = 30km gesamt.",emoji:"🎿"},
  {q:"How many Punkte hat ein Snowboard-Halfpipe-Run maximal?",a:100,unit:"Punkte",hint:"Jurybewertung von 0-100.",emoji:"🏂"},
  {q:"How long is ein Schwimm-Wettkampf beim Freistil maximal in Metern?",a:1500,unit:"meters",hint:"1500m Freistil ist die längste Beckendisziplin.",emoji:"🏊"},
  {q:"How many km/h schleudert ein Hammerwerfer den Hammer?",a:100,unit:"km/h",hint:"Der Hammer erreicht massive Geschwindigkeit.",emoji:"🔨"},
  {q:"How long is die Wettkampfstrecke beim Eisschnelllauf (kürzeste) in Metern?",a:500,unit:"meters",hint:"Die Sprintdisziplin.",emoji:"⛸️"},
  {q:"How many Minuten dauert ein normales Fußballspiel?",a:90,unit:"minutes",hint:"2 Halbzeiten à 45 Minuten.",emoji:"⚽"},
  {q:"How many Spieler hat ein Ultimate Frisbee-Team?",a:7,unit:"Spieler",hint:"Vs 7 auf dem Feld.",emoji:"🥏"},
  {q:"How high ist ein Wassersprung-Turm maximal in Metern?",a:10,unit:"meters",hint:"Die höchste olympische Sprunghöhe.",emoji:"🏊"},
  {q:"How many Kämpfe hat ein MMA-Profi per year?",a:3,unit:"Kämpfe",hint:"Etwa 2-4 Kämpfe per year.",emoji:"🥊"},
  {q:"How long is eine Skisprungrampe (Normalschanze) in Metern?",a:90,unit:"Meter Sprungweite",hint:"Normalschanze = K90.",emoji:"🎿"},
  {q:"How many Spieler hat ein Lacrosse Box-Team?",a:6,unit:"Spieler",hint:"Indoor-Lacrosse mit weniger Spielern.",emoji:"🥍"},
  {q:"How long is ein 110m-Hürdenlauf-Hurde in cm Höhe?",a:106.7,unit:"cm",hint:"Für Männer.",emoji:"🏃"},
  {q:"How many km/h fährt ein Rennradsportler beim Zeitfahren?",a:55,unit:"km/h",hint:"Tour-de-France Zeitfahrspezialisten.",emoji:"🚴"},
  {q:"How heavy ist ein Diskus bei Männern in kg?",a:2,unit:"kg",hint:"Bei Frauen 1 kg.",emoji:"🥏"},
  {q:"How long is ein Basketballfeld in Metern?",a:28,unit:"meters",hint:"× 15 Meter FIBA-Standard.",emoji:"🏀"},
  {q:"How many Punkte braucht man beim Squash für einen Satz?",a:11,unit:"Punkte",hint:"Neuere PAR-Regel.",emoji:"🎾"},
  {q:"How high ist ein Netz beim Tischtennis in cm?",a:15.25,unit:"cm",hint:"Sehr niedrig.",emoji:"🏓"},
  {q:"How long is ein Leichtathletik-Weitsprung-Anlauf in Metern?",a:40,unit:"meters",hint:"Durchschnittlicher Anlauf der Elite.",emoji:"🏃"},
  {q:"How many Spieler hat ein Floorball-Team?",a:6,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"🏑"},
  {q:"How long is eine Curling-Bahn in Metern?",a:45,unit:"meters",hint:"Von Haus zu Haus.",emoji:"🥌"},
  {q:"How many km/h erreicht ein Bobteam im Eiskanal?",a:150,unit:"km/h",hint:"Viererbob auf schnellen Strecken.",emoji:"🛷"},
  {q:"How many Spieler hat ein Polo-Team?",a:4,unit:"Spieler",hint:"Reiter auf Pferden.",emoji:"🐎"},
  {q:"How long is eine Rugby-Partie in Minuten?",a:80,unit:"minutes",hint:"2 Halbzeiten à 40 Minuten.",emoji:"🏉"},
  {q:"How many Spieler hat ein Sepak Takraw-Team?",a:3,unit:"Spieler",hint:"Südostasiatischer Ballsport.",emoji:"🦵"},
  {q:"How long is eine Biathlon-Strafschleife in Metern?",a:150,unit:"meters",hint:"Für jeden verfehlten Schuss.",emoji:"🎿"},
  {q:"How high ist der Weitsprung-Weltrekord bei Frauen in Metern?",a:7.52,unit:"meters",hint:"Galina Chistyakova, 1988.",emoji:"🏃"},
  {q:"How many Spieler hat ein Hockeyteam auf dem Feld?",a:11,unit:"Spieler",hint:"Feldhockey-Standard.",emoji:"🏑"},
  {q:"How long is eine Radrenn-Mannschaftsverfolgung?",a:4,unit:"km",hint:"Km auf der Bahn.",emoji:"🚴"},
  {q:"How heavy ist ein Schläger beim Eishockey in kg?",a:0.85,unit:"kg",hint:"Leicht für maximale Kontrolle.",emoji:"🏒"},
  {q:"How many Spieler hat ein Gaelic-Football-Team?",a:15,unit:"Spieler",hint:"Irischer Sport ähnlich wie Rugby.",emoji:"🏈"},
  {q:"How many km lang ist ein Triathlon Ironman?",a:226,unit:"km",hint:"3,8km Schwimmen + 180km Rad + 42km Laufen.",emoji:"🏊"},
  {q:"How high ist ein Schach-Turm auf dem Brett in cm?",a:6,unit:"cm",hint:"Größte Figur nach dem König.",emoji:"♟️"},
  {q:"How many Spieler hat ein Handball-Team?",a:7,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"🤾"},
  {q:"How long is ein Olympisches Gewichtheben-Wettkampftag?",a:10,unit:"hours",hint:"Alle Gewichtsklassen zusammen.",emoji:"🏋️"},
  {q:"How many km/h fährt ein Downhill-Mountainbiker?",a:80,unit:"km/h",hint:"Auf extremen Strecken.",emoji:"🚵"},
  {q:"How many Spieler hat ein Handball-Team auf dem Feld?",a:7,unit:"Spieler",hint:"6 Feldspieler plus Torwart.",emoji:"🤾"},
  {q:"How long is eine Olympia-Laufstrecke beim 400m-Lauf?",a:400,unit:"meters",hint:"Eine Runde um die Bahn.",emoji:"🏃"},
  {q:"How high ist das Netz beim Badminton?",a:1.55,unit:"meters",hint:"Etwas höher als beim Tennis.",emoji:"🏸"},
  {q:"How many Punkte braucht man beim Dart um von 501 runterzuspielen?",a:501,unit:"Punkte",hint:"Genau auf Null – nicht drunter.",emoji:"🎯"},
  {q:"How long is ein Curling-Feld in Metern?",a:42,unit:"meters",hint:"Das Eis-Schach.",emoji:"🥌"},
  {q:"How many Spieler hat ein American-Football-Team auf dem Feld?",a:11,unit:"Spieler",hint:"Offense gegen Defense – je 11.",emoji:"🏈"},
  {q:"How high ist ein Boxring in cm über dem Boden?",a:100,unit:"cm",hint:"Ungefähr 1 Meter über dem Hallenboden.",emoji:"🥊"},
  {q:"How many Meter wird beim Hochsprung-Weltrekord gesprungen?",a:2.45,unit:"meters",hint:"Javier Sotomayor 1993.",emoji:"🏃"},
  {q:"How many km fährt ein Tour-de-France-Sieger im Durchschnitt?",a:3500,unit:"km",hint:"Über 21 Etappen.",emoji:"🚴"},
  {q:"How long dauert ein Eishockey-Spiel in Minuten?",a:60,unit:"minutes",hint:"3 Drittel à 20 Minuten.",emoji:"🏒"},
  {q:"How many Punkte ist ein Dreier beim Basketball wert?",a:3,unit:"Punkte",hint:"Hinter der Dreierlinie geworfen.",emoji:"🏀"},
  {q:"How long is eine Olympia-Schwimmstrecke?",a:50,unit:"meters",hint:"Meter Langbahn.",emoji:"🏊"},
  {q:"How many Würfe hat man beim Bowling pro Frame?",a:2,unit:"Würfe",hint:"Beim Strike nur 1 – beim 10. Frame bis zu 3.",emoji:"🎳"},
  {q:"How many km/h fliegt ein Badminton-Federball maximal?",a:493,unit:"km/h",hint:"Schnellstes Objekt im Sport.",emoji:"🏸"},
  {q:"How many Meter tief ist ein Olympia-Schwimmbecken?",a:2,unit:"meters",hint:"Mindesttiefe für internationale Wettkämpfe.",emoji:"🏊"},
  {q:"How long dauert ein Rugbyspiel in Minuten?",a:80,unit:"minutes",hint:"2 Hälften à 40 Minuten.",emoji:"🏉"},
  {q:"How many Spieler stehen beim Volleyball auf dem Feld?",a:6,unit:"Spieler",hint:"Pro Seite.",emoji:"🏐"},
  {q:"How heavy ist ein Diskus bei den Männern?",a:2,unit:"kg",hint:"Kg schwere Scheibe.",emoji:"🥏"},
  {q:"How many Runden hat ein Formel-1-Rennen in Monaco?",a:78,unit:"Runden",hint:"Kürzeste Strecke – daher mehr Runden.",emoji:"🏎️"},
  {q:"How high ist ein Turnpferd?",a:1.15,unit:"meters",hint:"Olympisches Turngerät.",emoji:"🤸"},
  {q:"How many Goldmedaillen gewann Usain Bolt insgesamt?",a:8,unit:"Goldmedaillen",hint:"3 Olympiaden – immer Gold über 100m und 200m.",emoji:"🥇"},
  {q:"How many Meter beträgt die Speerwurf-Weltrekorddistanz?",a:98.48,unit:"meters",hint:"Jan Železný 1996 in Jena.",emoji:"🎯"},
  {q:"How many km/h erreicht ein Tennisball beim schärfsten Aufschlag?",a:263,unit:"km/h",hint:"Samuel Groth 2012.",emoji:"🎾"},
  {q:"How long is ein Marathonlauf?",a:42.195,unit:"km",hint:"Benannt nach dem Lauf von Marathon nach Athen.",emoji:"🏃"},
  {q:"How many Spieler hat ein Eishockey-Team auf dem Eis?",a:6,unit:"Spieler",hint:"5 Feldspieler plus Torwart.",emoji:"🏒"},
  {q:"How far springt man beim Weitsprung-Weltrekord?",a:8.95,unit:"meters",hint:"Mike Powell 1991 in Tokio.",emoji:"🏃"},
  {q:"How many Punkte braucht man beim Tennis um ein Spiel zu gewinnen?",a:4,unit:"Punkte",hint:"15 – 30 – 40 – Spiel.",emoji:"🎾"},
  {q:"How heavy ist ein Fußball in Gramm?",a:430,unit:"grams",hint:"410-450g nach FIFA-Regeln.",emoji:"⚽"},
  {q:"How many km/h fährt ein Downhill-Mountainbiker maximal?",a:130,unit:"km/h",hint:"Auf steilen Strecken.",emoji:"🚵"},
  {q:"How many Bahnen hat ein Olympia-Schwimmbecken?",a:8,unit:"Bahnen",hint:"Bahnen à 2,5 Meter Breite.",emoji:"🏊"},
  {q:"How long is ein Fußballspiel in Minuten?",a:90,unit:"minutes",hint:"2 Hälften à 45 Minuten.",emoji:"⚽"},
  {q:"How high ist der Stabhochsprung-Weltrekord?",a:6.21,unit:"meters",hint:"Armand Duplantis 2024.",emoji:"🏃"},
  {q:"How many Spieler hat ein Baseball-Team auf dem Feld?",a:9,unit:"Spieler",hint:"Positionen auf dem Feld.",emoji:"⚾"},
  {q:"How far wirft man beim Hammerwurf-Weltrekord?",a:86.74,unit:"meters",hint:"Yuriy Sedykh 1986.",emoji:"🔨"},
  {q:"How many Runden besteht ein Boxkampf maximal (Profis)?",a:12,unit:"Runden",hint:"Jede Runde 3 Minuten.",emoji:"🥊"},
  {q:"How long is ein Eisschnelllauf-Oval?",a:400,unit:"meters",hint:"Standard-Eisschnelllaufbahn.",emoji:"⛸️"},
  {q:"How many km/h läuft ein Profifußballer maximal?",a:35,unit:"km/h",hint:"Beim Sprint.",emoji:"⚽"},
  {q:"How high ist das Netz beim Tischtennis in cm?",a:15.25,unit:"cm",hint:"International standardisiert – überall gleich hoch.",emoji:"🏓"},
  {q:"How many Meter hat der 110m-Hürdenlauf?",a:110,unit:"meters",hint:"10 Hürden à 1,067m Höhe.",emoji:"🏃"},
  {q:"How many Punkte ist ein Elfmeter-Tor im Fußball wert?",a:1,unit:"Tor",hint:"Wie jedes andere Tor auch.",emoji:"⚽"},
  {q:"How long is ein Turniertennis-Platz?",a:23.77,unit:"meters",hint:"23,77m × 8,23m (Einzel).",emoji:"🎾"},
  {q:"How heavy ist eine Kugel beim Kugelstoßen (Männer)?",a:7.26,unit:"kg",hint:"7,26 kg – fast ein kleiner Bowlingball.",emoji:"🎱"},
  {q:"How many Torwürfe macht ein Handballer per game?",a:8,unit:"Würfe",hint:"Im Durchschnitt.",emoji:"🤾"},
  {q:"How many km/h kann ein Profischwimmer in 50m erreichen?",a:8,unit:"km/h",hint:"Beim Sprint.",emoji:"🏊"},
  {q:"How long is der 4x100m Staffellauf insgesamt?",a:400,unit:"meters",hint:"4 Läufer je 100m.",emoji:"🏃"},
  {q:"How many Spieler darf man beim Fußball einwechseln?",a:5,unit:"Spieler",hint:"Seit 2020 – vorher nur 3.",emoji:"⚽"},
  {q:"How high ist ein Basketballkorb?",a:3.05,unit:"meters",hint:"Weltweit einheitlich – egal ob Profi oder Amateur.",emoji:"🏀"},
  {q:"How many km fährt ein Triathlon beim langen Radabschnitt?",a:180,unit:"km",hint:"Beim Ironman: 3,8km Schwimmen – 180km Rad – 42km Laufen.",emoji:"🚴"},
  {q:"How long is eine Eiskunstlauf-Kür bei den Damen?",a:4,unit:"minutes",hint:"Minuten maximale Kürzeit.",emoji:"⛸️"},
  {q:"How many Punkte braucht man beim Badminton für einen Satz?",a:21,unit:"Punkte",hint:"Best of 3 Sätze.",emoji:"🏸"},
  {q:"How many km legt ein Tennisspieler pro Match zurück?",a:3,unit:"km",hint:"Je nach Spiellänge.",emoji:"🎾"},
  {q:"How far springt man beim Dreisprung-Weltrekord?",a:18.29,unit:"meters",hint:"Jonathan Edwards 1995.",emoji:"🏃"},
  {q:"How many Tore schoss Lionel Messi bei seiner Rekord-WM?",a:7,unit:"Tore",hint:"WM 2022 in Katar.",emoji:"⚽"},
  {q:"How long is eine Kanuslalom-Strecke?",a:300,unit:"meters",hint:"Mit Toren die durchfahren werden müssen.",emoji:"🛶"},
  {q:"How many Felder hat ein Schachbrett?",a:64,unit:"Felder",hint:"8 mal 8.",emoji:"♟️"},
  {q:"How heavy ist ein Boxhandschuh beim Profiboxen in Unzen?",a:10,unit:"Unzen",hint:"Profis haben schwerere Handschuhe als im Training.",emoji:"🥊"},
  {q:"How many km schwimmt man beim Ironman-Triathlon?",a:3.8,unit:"km",hint:"Start des längsten Triathlons.",emoji:"🏊"},
  {q:"How long is eine Eisschnelllauf-500m-Strecke?",a:500,unit:"meters",hint:"Schnellste Disziplin.",emoji:"⛸️"},
  {q:"How many Punkte braucht man im Squash für ein Spiel?",a:11,unit:"Punkte",hint:"Best of 5 Spiele.",emoji:"🎾"},
  {q:"How high ist ein Turnreck über dem Boden?",a:2.75,unit:"meters",hint:"Olympisches Gerät.",emoji:"🤸"},
  {q:"How many km legt ein Radprofi bei der Tour de France daily zurück?",a:167,unit:"km",hint:"Durchschnitt über alle Etappen.",emoji:"🚴"},
  {q:"How many Spieler hat ein Rugby-League-Team?",a:13,unit:"Spieler",hint:"Rugby Union hat 15.",emoji:"🏉"},
  {q:"How heavy ist ein Diskus bei den Frauen?",a:1,unit:"kg",hint:"Halb so schwer wie bei den Männern.",emoji:"🥏"},
  {q:"How long is ein Wettkampf-Ruderboot (Achter)?",a:20,unit:"meters",hint:"8 Ruderer plus Steuermann.",emoji:"🚣"},
  {q:"How many Meter taucht ein Freitaucher beim Weltrekord?",a:214,unit:"meters",hint:"Herbert Nitsch – tiefster Mann der Welt.",emoji:"🤿"},
  {q:"How many km/h fährt ein Profi-Radrennfahrer in der Spitze?",a:80,unit:"km/h",hint:"Im Sprint – bergab noch mehr.",emoji:"🚴"},
  {q:"How long is ein Tischtennis-Tisch?",a:2.74,unit:"meters",hint:"274cm × 152,5cm.",emoji:"🏓"},
  {q:"How many Runden besteht ein Amateur-Boxkampf?",a:3,unit:"Runden",hint:"Olympisches Boxen: 3 Runden à 3 Minuten.",emoji:"🥊"},
  {q:"How far schießt man beim Bogenschießen auf der Olympia-Distanz?",a:70,unit:"meters",hint:"Meter bei Olympia.",emoji:"🏹"},
  {q:"How high springt ein Ski-Springer beim Normalschanzenrekord?",a:100,unit:"meters",hint:"Auf der Normalschanze.",emoji:"⛷️"},
  {q:"How many Spieler hat ein Curling-Team?",a:4,unit:"Spieler",hint:"Einer wirft, drei kehren.",emoji:"🥌"},
  {q:"How long is ein Biathlon-Lauf bei den Herren?",a:20,unit:"km",hint:"Kombiniert Skilanglauf und Schießen.",emoji:"🎿"},
  {q:"How many Punkte braucht man beim Volleyball für einen Satz?",a:25,unit:"Punkte",hint:"Mit 2 Punkten Vorsprung gewinnen.",emoji:"🏐"},
  {q:"How many km laufen Fußballer bei einem Bundesligaspiel?",a:11,unit:"km",hint:"Durchschnitt pro Spieler.",emoji:"⚽"},
  {q:"How heavy ist ein Olympia-Gewichtheber-Barbell?",a:20,unit:"kg",hint:"Die Stange selbst wiegt 20kg.",emoji:"🏋️"},
  {q:"How long is ein Handball-Spielfeld?",a:40,unit:"meters",hint:"40m × 20m.",emoji:"🤾"},
  {q:"How many Runden hat ein Motorradrennen bei der MotoGP?",a:27,unit:"Runden",hint:"Je nach Strecke 20-30 Runden.",emoji:"🏍️"},
  {q:"How many Spieler hat ein Wasserball-Team?",a:7,unit:"Spieler",hint:"6 Feldspieler plus Torwart.",emoji:"🤽"},
  {q:"How long is eine Hürde beim 110m-Lauf in cm Höhe?",a:106,unit:"cm",hint:"Für Männer 106,7cm hoch.",emoji:"🏃"},
  {q:"How many Punkte ist ein Freiwurf beim Basketball wert?",a:1,unit:"Punkt",hint:"Vom Freiwurfstreifen.",emoji:"🏀"},
  {q:"How many Minuten dauert eine Halbzeit beim Fußball?",a:45,unit:"minutes",hint:"Zwei Hälften à 45 Minuten.",emoji:"⚽"},
  {q:"How many Spieler hat ein Lacrosse-Team?",a:10,unit:"Spieler",hint:"Feldspieler.",emoji:"🥍"},
  {q:"How high ist das Tor beim Fußball in Metern?",a:2.44,unit:"meters",hint:"Höher als du denkst!",emoji:"⚽"},
];
