// 🎨 ART & INVENTIONS – English
export default [
  {q:"In what year erfand Alexander Graham Bell das Telefon?",a:1876,unit:"Jahr",hint:"Am 10. März 1876 – erster Satz: 'Watson, come here!'",emoji:"📞"},
  {q:"How many Jahre arbeitete Leonardo da Vinci an der Mona Lisa?",a:4,unit:"years",hint:"Von 1503 bis ca. 1507.",emoji:"🖼️"},
  {q:"In what year wurde das erste Lego-Stein erfunden?",a:1958,unit:"Jahr",hint:"Der dänische Tischler Ole Kirk Kristiansen.",emoji:"🧱"},
  {q:"How many Farben hat ein Regenbogen?",a:7,unit:"Farben",hint:"Rot, Orange, Gelb, Grün, Blau, Indigo, Violett.",emoji:"🌈"},
  {q:"In what year erfanden die Gebrüder Wright das Flugzeug?",a:1903,unit:"Jahr",hint:"12 Sekunden Flug – und die Welt veränderte sich.",emoji:"✈️"},
  {q:"How many Meter groß ist die Mona Lisa?",a:77,unit:"cm Höhe",hint:"Nur 77cm hoch – überraschend klein.",emoji:"🖼️"},
  {q:"In what year wurde das erste Buch gedruckt?",a:1440,unit:"Jahr",hint:"Johannes Gutenberg erfand den Buchdruck.",emoji:"📚"},
  {q:"How many Farben nutzt ein Maler wenn er alle Farben mischen will?",a:3,unit:"Grundfarben",hint:"Rot, Gelb, Blau – die drei Grundfarben.",emoji:"🎨"},
  {q:"In what year erfand Thomas Edison die Glühbirne?",a:1879,unit:"Jahr",hint:"Nach 1000 Versuchen!",emoji:"💡"},
  {q:"How many Töne hat eine normale Klaviertastatur?",a:88,unit:"Töne",hint:"52 weiße und 36 schwarze Tasten.",emoji:"🎹"},
  {q:"In what year wurde das erste Smartphone (iPhone) erfunden?",a:2007,unit:"Jahr",hint:"Steve Jobs zeigte es am 9. Januar.",emoji:"📱"},
  {q:"How many Jahre malte Michelangelo die Sixtinische Kapelle?",a:4,unit:"years",hint:"Von 1508 bis 1512.",emoji:"🎨"},
  {q:"In what year wurde LEGO gegründet?",a:1932,unit:"Jahr",hint:"In Billund, Dänemark.",emoji:"🧱"},
  {q:"How many Saiten hat eine normale Gitarre?",a:6,unit:"Saiten",hint:"E, A, D, G, H, e.",emoji:"🎸"},
  {q:"In what year erfand Karl Benz das erste Auto?",a:1885,unit:"Jahr",hint:"Der Benz Patent-Motorwagen.",emoji:"🚗"},
  {q:"How many Farben hat die Mondrian-Kunst normalerweise?",a:3,unit:"Grundfarben",hint:"Rot, Gelb, Blau plus Schwarz und Weiß.",emoji:"🟥"},
  {q:"In what year erschuf Beethoven seine 9. Symphonie?",a:1824,unit:"Jahr",hint:"Beethoven war taub als er sie schrieb.",emoji:"🎵"},
  {q:"How many Seiten hat ein Oktaeder (geometrische Form)?",a:8,unit:"Seiten",hint:"Wie zwei Pyramiden aufeinandergesetzt.",emoji:"🔷"},
  {q:"In what year erfand Gutenberg die Druckmaschine?",a:1440,unit:"Jahr",hint:"Revolutionierte die Verbreitung von Wissen.",emoji:"📖"},
  {q:"How many Buchstaben hat das deutsche Alphabet?",a:26,unit:"Buchstaben",hint:"Plus ä, ö, ü und ß – aber die zählen extra.",emoji:"🔤"},
  {q:"In what year wurde der Eiffelturm gebaut?",a:1889,unit:"Jahr",hint:"Für die Weltausstellung in Paris.",emoji:"🗼"},
  {q:"How many Noten gibt es in einer Oktave?",a:8,unit:"Noten",hint:"C, D, E, F, G, A, H, C.",emoji:"🎵"},
  {q:"In what year erschuf van Gogh Sternennacht?",a:1889,unit:"Jahr",hint:"In einer Nervenheilanstalt in Arles.",emoji:"🌃"},
  {q:"How many Farben hat die brasilianische Flagge?",a:4,unit:"Farben",hint:"Grün, Gelb, Blau, Weiß.",emoji:"🇧🇷"},
  {q:"In what year erschuf Leonardo da Vinci sein Notizbuch über die Vogelflugmaschine?",a:1505,unit:"Jahr",hint:"Er träumte vom Fliegen.",emoji:"🐦"},
  {q:"How many Zinken hat eine normale Gabel?",a:4,unit:"Zinken",hint:"Die Essgabel hat 4 Zinken.",emoji:"🍴"},
  {q:"In what year erfand Alexander Fleming Penicillin?",a:1928,unit:"Jahr",hint:"Durch ein verschimmeltes Experiment.",emoji:"💊"},
  {q:"How many Seiten hat ein Hexagon?",a:6,unit:"Seiten",hint:"Hexa = sechs – wie Bienenwaben.",emoji:"⬡"},
  {q:"In what year erfand Aristoteles... seine Kategorien der Philosophie?",a:350,unit:"v.Chr.",hint:"Der Vater der Logik.",emoji:"🏛️"},
  {q:"How many Farben hat die deutsche Flagge?",a:3,unit:"Farben",hint:"Schwarz, Rot, Gold.",emoji:"🇩🇪"},
];
