// 🍺 COMIDA Y BEBIDA – Español
export default [
 {q:"¿Cuántos Kalorien hat ein grande Mac?",un:563,unit:"kcal",hint:"Davon kommen 257 kcal aus dem Fett.",emoji:"🍔"},
 {q:"¿Cuántos Liter Bier wurden beim Oktoberfest 2023 getrunken?",un:7300000,unit:"litros",hint:"Das Oktoberfest ist das größte Volksfest der Welt.",emoji:"🍺"},
 {q:"¿Cuántos Gramm Zucker en einer Dose Cola (330ml)?",un:35,unit:"gramos",hint:"Das sind etwa 7 Teelöffel Zucker.",emoji:"🥤"},
 {q:"¿Cuántos Tonnen Schokolade isst Deutschland por año?",un:900000,unit:"tons",hint:"Weltmeister im Schokoladenkonsum pro Kopf.",emoji:"🍫"},
 {q:"¿Cuántos Liter Milch braucht man für 1 kg Käse?",un:10,unit:"litros",hint:"Je nach Sorte 8–12 Liter Milch.",emoji:"🧀"},
 {q:"¿Cuántos Monate reift ein echter Parmesan mindestens?",un:24,unit:"meses",hint:"Premium-Parmesan reift bis zu 5 Jahre.",emoji:"🧀"},
 {q:"¿Cuántos Körner Kaffee braucht man für einen Espresso?",un:50,unit:"Körner",hint:"Ein Kaffeebaum produziert por año ~500g Kaffee.",emoji:"☕"},
 {q:"¿Cuántos Liter Wein trinkt ein Franzose por año?",un:45,unit:"litros",hint:"Frankreich führt en el mundo den Pro-Kopf-Weinkonsum.",emoji:"🍷"},
 {q:"¿Cuántos kg Pasta isst ein Italiener en promedio por año?",un:23,unit:"kg",hint:"Italien führt en el mundo den Pastakonsum.",emoji:"🍝"},
 {q:"¿Qué tan alto ist der Wasseranteil en einer Gurke en por ciento?",un:97,unit:"%",hint:"Gurken bestehen rápido nur aus Wasser.",emoji:"🥒"},
 {q:"¿Cuántos Liter Kaffee trinken Finnen pro Kopf por año?",un:12,unit:"kg",hint:"Finnland ist Weltmeister im Kaffeeverbrauch.",emoji:"☕"},
 {q:"¿Cuántos Gramm Butter enthält ein original Croissant?",un:50,unit:"gramos",hint:"Der hohe Butteranteil macht die blättrige Textur möglich.",emoji:"🥐"},
 {q:"¿Cuántos por ciento Fettgehalt hat Gänsestopfleber (Foie Gras)?",un:50,unit:"%",hint:"Eines der kalorienreichsten Lebensmittel.",emoji:"🍴"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 kg Rindfleisch?",un:15000,unit:"litros",hint:"Rindfleisch hat den größten Wasserverbrauch aller Nahrungsmittel.",emoji:"🥩"},
 {q:"¿Cuántos Jahre ist der älteste bekannte Wein alt (Speyer-Wein)?",un:1650,unit:"años",hint:"Die Flasche wurde 1867 en einem römischen Grab gefunden.",emoji:"🍷"},
 {q:"¿Cuántos Gramm wiegt eine Kaviar-Perle?",un:50,unit:"mg",hint:"Beluga-Kaviar kostet bis zu 25.000€ pro kg.",emoji:"🐟"},
 {q:"¿Cuántos Kalorien hat ein Teelöffel Olivenöl?",un:40,unit:"kcal",hint:"Gesund – aber kalorienreich wie alle Fette.",emoji:"🫒"},
 {q:"¿Cuántos Gramm Salz isst ein Deutscher al día?",un:10,unit:"gramos",hint:"Empfohlen werden maximal 6 Gramm.",emoji:"🧂"},
 {q:"Wie scharf ist der Carolina Reaper en millones Scoville?",un:2.2,unit:"Mio. Scoville",hint:"Das schärfste Chili der Welt.",emoji:"🌶️"},
 {q:"¿Cuántos Stunden muss Jamon Iberico mindestens reifen?",un:8760,unit:"horas",hint:"Das sind mindestens 3 Jahre.",emoji:"🥩"},
 {q:"¿Cuántos Würste werden beim Nürnberger Christkindlesmarkt gegessen?",un:2000000,unit:"Würste",hint:"Nürnberger Bratwürste sind die kleinsten deutschen Würste.",emoji:"🌭"},
 {q:"Wie alt kann ein Wein maximal werden und noch trinkbar sein en Jahren?",un:200,unit:"años",hint:"Ein 1811er Château d'Yquem wurde als exzellent bewertet.",emoji:"🍷"},
 {q:"¿Cuánto kostet Safran pro kg en Euro?",un:10000,unit:"€/kg",hint:"Safran ist das teuerste Gewürz der Welt.",emoji:"🌺"},
 {q:"¿Cuántos Pizzen werden al día en el mundo gegessen en millones?",un:5,unit:"millones",hint:"Die USA essen allein 3 mil millones Pizzen por año.",emoji:"🍕"},
 {q:"¿Cuántos Kalorien hat ein Glas Rotwein (200ml)?",un:170,unit:"kcal",hint:"Wein hat mehr Kalorien als die meisten denken.",emoji:"🍷"},
 {q:"¿Cuántos Stunden dauert die Herstellung von echtem Champagner mindestens?",un:12960,unit:"horas",hint:"Das sind mindestens 18 Monate Reifung.",emoji:"🥂"},
 {q:"¿Cuántos Gramm Zucker hat ein Glas Orangensaft (200ml)?",un:20,unit:"gramos",hint:"rápido so viel wie Cola – oft unterschätzt.",emoji:"🍊"},
 {q:"¿Cuántos Minuten por día massiert man Kobe-Rind?",un:60,unit:"minutos",hint:"Sie werden tatsächlich massiert und mit Bier gefüttert.",emoji:"🥩"},
 {q:"¿Cuánto por ciento des Wasabis im Restaurant ist echt?",un:1,unit:"%",hint:"99% ist gefälschter Wasabi aus Meerrettich und Farbe.",emoji:"🍣"},
 {q:"¿Cuántos mil millones Liter Bier braut Deutschland por año?",un:8,unit:"billion liters",hint:"mil millones Liter – Platz 5 en el mundo.",emoji:"🍺"},
 {q:"¿Cuántos kcal hat eine durchschnittliche Currywurst?",un:350,unit:"kcal",hint:"Mit Pommes kommen nochmal 400 kcal dazu.",emoji:"🌭"},
 {q:"¿Cuántos Milliliter Espresso enthält eine Standard-Tasse?",un:25,unit:"ml",hint:"Ein Doppio hat 50 ml.",emoji:"☕"},
 {q:"¿Cuántos kg Mehl verbraucht Deutschland pro Kopf im Jahr?",un:86,unit:"kg",hint:"Wir sind eine Brotnation.",emoji:"🍞"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 Liter Bier?",un:300,unit:"litros",hint:"Inklusive Anbau, Verarbeitung und Kühlung.",emoji:"🍺"},
 {q:"¿Cuántos Kalorien hat ein Döner Kebab?",un:850,unit:"kcal",hint:"Der Döner ist Deutschlands beliebtestes rápido comida.",emoji:"🌯"},
 {q:"¿Cuántos mil millones Liter Wein produziert Frankreich por año?",un:4,unit:"billion liters",hint:"mil millones Liter – Platz 2 en el mundo nach Italien.",emoji:"🍷"},
 {q:"¿Cuántos Gramm Eiweiß hat ein Ei?",un:6,unit:"gramos",hint:"Ein Hühnerei hat ~6g Protein.",emoji:"🥚"},
 {q:"¿Cuántos Stunden fermentiert Kimchi traditionell?",un:24,unit:"horas",hint:"Manchmal auch Monate – je nach Rezept.",emoji:"🥬"},
 {q:"¿Cuántos Kalorien hat 100g dunkle Schokolade?",un:550,unit:"kcal",hint:"Viel Fett und Zucker – aber auch Antioxidantien.",emoji:"🍫"},
 {q:"¿Cuántos Liter Tee trinken Briten por día (pro persona)?",un:3,unit:"Tassen",hint:"Briten trinken al año 60 mil millones Tassen Tee.",emoji:"🫖"},
 {q:"¿Cuántos Gramm Zucker hat Ketchup pro 100g?",un:22,unit:"gramos",hint:"Ketchup enthält überraschend viel Zucker.",emoji:"🍅"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 kg Mandeln?",un:15000,unit:"litros",hint:"Mandeln sind extrem wasserintensiv.",emoji:"🌰"},
 {q:"¿Cuántos mil millones Eier werden en Deutschland por año gegessen?",un:15,unit:"mil millones",hint:"Etwa 180 Eier pro persona und Jahr.",emoji:"🥚"},
 {q:"¿Cuántos kcal hat eine Packung Chips (200g)?",un:1080,unit:"kcal",hint:"Über die Hälfte des Tagesbedarfs en einem Snack.",emoji:"🍟"},
 {q:"¿Cuántos Monate fermentiert echter Roquefort-Käse?",un:3,unit:"meses",hint:"en speziellen Höhlen bei konstanter Temperatur.",emoji:"🧀"},
 {q:"¿Cuántos Gramm Salz enthält ein normales Brot (700g)?",un:10,unit:"gramos",hint:"Brot ist eine der größten Salzquellen.",emoji:"🍞"},
 {q:"¿Cuántos Liter Bier hat der durchschnittliche Bayer por año?",un:150,unit:"litros",hint:"Bayern führt den deutschen Bierkonsum un.",emoji:"🍺"},
 {q:"¿Cuántos Kalorien hat ein Schnitzel Wiener Art (ohne Beilagen)?",un:650,unit:"kcal",hint:"Mit Kartoffelsalat kommen nochmal 300 kcal dazu.",emoji:"🥩"},
 {q:"¿Cuántos Tonnen Obst isst Deutschland por año?",un:5000000,unit:"tons",hint:"Äpfel sind das beliebteste Obst.",emoji:"🍎"},
 {q:"¿Cuántos por ciento Alkohol hat Standard-Bier?",un:5,unit:"%",hint:"Starkbiere haben bis zu 14% Alkohol.",emoji:"🍺"},
 {q:"¿Cuántos Gramm Kohlenhydrate hat 100g Weißbrot?",un:50,unit:"gramos",hint:"Weißbrot hat rápido so viele Kohlenhydrate wie Zucker.",emoji:"🍞"},
 {q:"¿Cuántos Stunden dauert die Fermentation von echtem Sourdough?",un:48,unit:"horas",hint:"Echter Sauerteig braucht Zeit für Geschmack.",emoji:"🍞"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 kg Avocado?",un:1000,unit:"litros",hint:"Avocados sind sehr wasserintensiv.",emoji:"🥑"},
 {q:"¿Cuántos kcal hat eine Tafel Vollmilchschokolade (100g)?",un:535,unit:"kcal",hint:"Milchschokolade hat etwas weniger als dunkle.",emoji:"🍫"},
 {q:"¿Cuántos Tonnen Bananen importiert Deutschland por año?",un:1000000,unit:"tons",hint:"Banane ist die meistgekaufte Frucht Deutschlands.",emoji:"🍌"},
 {q:"¿Cuántos Gramm Fett hat 100g Butter?",un:83,unit:"gramos",hint:"Butter ist rápido pures Fett.",emoji:"🧈"},
 {q:"¿Cuántos mil millones Würste werden en Deutschland por año produziert?",un:1500,unit:"millones",hint:"Deutschland ist Weltmeister en Wurstvielfalt.",emoji:"🌭"},
 {q:"¿Cuántos kcal hat ein Döner en einem normalen Fladenbrot?",un:1000,unit:"kcal",hint:"Ein Döner kann über die Hälfte des Tagesbedarfs decken.",emoji:"🌯"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 kg Schokolade?",un:17196,unit:"litros",hint:"Die wasserintensivste Süßigkeit.",emoji:"🍫"},
 {q:"¿Cuántos Stunden reift ein Gouda-Käse mindestens?",un:720,unit:"horas",hint:"30 Tage für jungen Gouda – alter Gouda reift Monate.",emoji:"🧀"},
 {q:"¿Cuántos Kalorien hat eine Maß Bier (1 Liter)?",un:430,unit:"kcal",hint:"Bier hat pro 100ml etwa 43 kcal.",emoji:"🍺"},
 {q:"¿Cuántos Gramm Protein hat 100g Hühnchen (Brust)?",un:31,unit:"gramos",hint:"Hühnchenbrust ist eine der eiweißreichsten Quellen.",emoji:"🍗"},
 {q:"¿Cuántos Tonnen Kaffee trinkt Deutschland por año?",un:500000,unit:"tons",hint:"Kaffee ist das Lieblingsgetränk der Deutschen.",emoji:"☕"},
 {q:"¿Cuántos kcal hat eine normale Portion Pommes Frites (150g)?",un:450,unit:"kcal",hint:"Mit Ketchup und Mayonnaise deutlich mehr.",emoji:"🍟"},
 {q:"¿Cuántos Liter Wein trinken Deutsche pro Kopf por año?",un:20,unit:"litros",hint:"Weniger als Franzosen oder Portugiesen.",emoji:"🍷"},
 {q:"¿Cuántos Gramm Zucker hat ein Glas Eistee (250ml)?",un:25,unit:"gramos",hint:"Eistee ist eine versteckte Zuckerfalle.",emoji:"🍵"},
 {q:"¿Cuántos kcal hat ein normales Croissant?",un:250,unit:"kcal",hint:"Kleines Gebäck mit vielen Kalorien.",emoji:"🥐"},
 {q:"¿Cuántos Monate fermentiert echter Miso?",un:12,unit:"meses",hint:"Traditioneller Miso reift 1-3 Jahre.",emoji:"🫙"},
 {q:"¿Cuántos Gramm Mehl braucht man für eine Pizza (30cm)?",un:250,unit:"gramos",hint:"Plus Tomatensauce, Käse und Belag.",emoji:"🍕"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 kg Schweinefleisch?",un:5988,unit:"litros",hint:"Deutlich weniger als Rind, aber immer noch viel.",emoji:"🥩"},
 {q:"¿Cuántos kcal hat ein Stück Schwarzwälder Kirschtorte?",un:450,unit:"kcal",hint:"Sahne, Schokolade und Kirschwasser.",emoji:"🎂"},
 {q:"¿Cuántos Gramm Capsaicin enthält ein Jalapeño?",un:100,unit:"mg",hint:"Capsaicin ist der Wirkstoff der Schärfe.",emoji:"🌶️"},
 {q:"¿Cuántos Tonnen Erdbeeren produziert Deutschland por año?",un:100000,unit:"tons",hint:"Bayern ist größter Produzent.",emoji:"🍓"},
 {q:"¿Cuántos Stunden braucht ein Käse um zu schimmeln (Camembert)?",un:168,unit:"horas",hint:"7 Tage für die charakteristische weiße Rinde.",emoji:"🧀"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 Tasse Kaffee?",un:140,unit:"litros",hint:"Inklusive Anbau und Verarbeitung.",emoji:"☕"},
 {q:"¿Cuántos Kalorien hat ein Hamburger (ohne Pommes)?",un:500,unit:"kcal",hint:"Je nach Belag mehr oder weniger.",emoji:"🍔"},
 {q:"¿Cuántos Gramm Omega-3 hat 100g Lachs?",un:2.5,unit:"gramos",hint:"Lachs ist eine der besten Omega-3-Quellen.",emoji:"🐟"},
 {q:"¿Cuántos millones Hektoliter Bier trinkt die Welt por año?",un:1900,unit:"Mio. Hektoliter",hint:"China ist der größte Biermarkt en el mundo.",emoji:"🍺"},
 {q:"¿Cuántos kcal hat 1 Gramm Alkohol?",un:7,unit:"kcal",hint:"Mehr als Zucker (4 kcal) – aber weniger als Fett (9 kcal).",emoji:"🍺"},
 {q:"¿Cuántos Tonnen Süßigkeiten isst Deutschland por año?",un:800000,unit:"tons",hint:"Haribo ist das bekannteste deutsche Süßwareunternehmen.",emoji:"🍬"},
 {q:"¿Cuántos Stunden dauert das Räuchern eines Schinkens?",un:48,unit:"horas",hint:"Echtes Kalträuchern dauert Tage.",emoji:"🥩"},
 {q:"¿Cuántos Gramm Zucker hat ein Päckchen Gummibärchen (200g)?",un:140,unit:"gramos",hint:"70% Zucker – Gummibärchen sind rápido purer Zucker.",emoji:"🐻"},
 {q:"¿Cuántos kcal hat ein Bier (0,5l, Pils)?",un:215,unit:"kcal",hint:"Ein Bier hat mehr Kalorien als ein Apfel.",emoji:"🍺"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 kg Käse?",un:5000,unit:"litros",hint:"Inklusive der Milch die man braucht.",emoji:"🧀"},
 {q:"¿Cuántos Gramm hat ein Standard-Würfel Zucker?",un:4,unit:"gramos",hint:"16 kcal pro Würfel.",emoji:"🍬"},
 {q:"¿Cuántos Tonnen Tomaten produziert Italien por año?",un:5000000,unit:"tons",hint:"Größter Tomatenproduzent Europas.",emoji:"🍅"},
 {q:"¿Cuántos Milliliter hat ein Standard-Shot Schnaps?",un:40,unit:"ml",hint:"en Deutschland sind 2 cl der Standard.",emoji:"🥃"},
 {q:"¿Cuántos kcal hat 100g Erdnussbutter?",un:589,unit:"kcal",hint:"Sehr kalorienreich – aber voller Proteine.",emoji:"🥜"},
 {q:"¿Cuántos Gramm Eiweiß hat 100g Quark (Magerquark)?",un:12,unit:"gramos",hint:"Magerquark ist eine günstige Proteinquelle.",emoji:"🥛"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 kg Tomaten?",un:183,unit:"litros",hint:"Deutlich weniger als Fleisch.",emoji:"🍅"},
 {q:"¿Cuántos Kalorien hat 100g Brokkoli?",un:34,unit:"kcal",hint:"Eines der nährstoffreichsten Gemüse.",emoji:"🥦"},
 {q:"¿Cuántos Tonnen Wurst produziert Deutschland por año?",un:1500000,unit:"tons",hint:"1,5 millones Tonnen – über 1500 Sorten.",emoji:"🌭"},
 {q:"¿Cuántos Stunden reift echter Roquefort en Höhlen?",un:2160,unit:"horas",hint:"90 Tage en Combalou-Höhlen.",emoji:"🧀"},
 {q:"¿Cuántos kcal hat ein Brezn (80g)?",un:270,unit:"kcal",hint:"Mit Butter nochmal 100 kcal mehr.",emoji:"🥨"},
 {q:"¿Cuántos Gramm Zucker hat 100ml Fruchtsaft?",un:10,unit:"gramos",hint:"Naturtrüber Saft enthält genauso viel Zucker wie Cola.",emoji:"🍹"},
 {q:"¿Cuántos mil millones Eier produziert Deutschland por año?",un:15,unit:"mil millones",hint:"Trotzdem importieren wir noch Eier.",emoji:"🥚"},
 {q:"¿Cuántos kcal hat ein Weißwurst-Frühstück (2 Würste + Brezel + Bier)?",un:900,unit:"kcal",hint:"Ein bayerisches Frühstück ist keine leichte Mahlzeit.",emoji:"🍺"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 Liter Orangensaft?",un:1000,unit:"litros",hint:"Anbau, Transport und Verarbeitung addieren sich.",emoji:"🍊"},
 {q:"¿Cuántos Gramm Fett hat ein Döner?",un:30,unit:"gramos",hint:"Je nach Zubereitung 20-50g Fett.",emoji:"🌯"},
 {q:"¿Cuántos Tonnen Honig produziert Deutschland por año?",un:25000,unit:"tons",hint:"Trotzdem importieren wir deutlich mehr.",emoji:"🍯"},
 {q:"¿Cuántos kcal hat ein Stück Käsekuchen (100g)?",un:320,unit:"kcal",hint:"Eines der kalorienreichsten deutschen Desserts.",emoji:"🎂"},
 {q:"¿Cuántos Gramm Calcium hat 100ml Milch?",un:120,unit:"gramos",hint:"Milch ist die beste Calciumquelle.",emoji:"🥛"},
 {q:"¿Cuántos Stunden fermentiert echter Balsamico aus Modena?",un:87600,unit:"horas",hint:"10 Jahre – manchmal sogar 25 Jahre.",emoji:"🫙"},
 {q:"¿Cuántos millones Liter Champagner werden en el mundo por año produziert?",un:300,unit:"million liters",hint:"millones Liter aus nur einer Region Frankreichs.",emoji:"🥂"},
 {q:"¿Cuántos kcal hat 100g Avocado?",un:160,unit:"kcal",hint:"Reich un gesunden Fetten.",emoji:"🥑"},
 {q:"¿Cuántos Tonnen Kartoffeln isst Deutschland por año?",un:4000000,unit:"tons",hint:"Über 50 kg pro persona por año.",emoji:"🥔"},
 {q:"¿Cuántos Gramm Zucker hat 100g Ketchup?",un:22,unit:"gramos",hint:"Ketchup ist rápido ein Viertel Zucker.",emoji:"🍅"},
 {q:"¿Cuántos kcal hat ein Sauerbraten mit Knödel?",un:1200,unit:"kcal",hint:"Ein echtes deutsches Festmahl.",emoji:"🥩"},
 {q:"¿Cuántos Milliliter fasst ein Standard-Weinglas?",un:200,unit:"ml",hint:"Ein normales Weinglas – nicht bis zum Rand.",emoji:"🍷"},
 {q:"¿Cuántos Tonnen Fleisch isst Deutschland por año?",un:7500000,unit:"tons",hint:"Etwa 90 kg Fleisch pro persona por año.",emoji:"🥩"},
 {q:"¿Cuántos kcal hat ein Lebkuchen (35g)?",un:130,unit:"kcal",hint:"Weihnachtsgebäck mit versteckten Kalorien.",emoji:"🍪"},
 {q:"¿Cuántos Gramm Protein hat 100g Linsen (gekocht)?",un:9,unit:"gramos",hint:"Linsen sind eine gute pflanzliche Proteinquelle.",emoji:"🫘"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 kg Reis?",un:2500,unit:"litros",hint:"Nassreis-Anbau verbraucht enorm viel Wasser.",emoji:"🍚"},
 {q:"¿Cuántos kcal hat 100g Walnüsse?",un:654,unit:"kcal",hint:"Sehr kalorienreich aber voller gesunder Fette.",emoji:"🌰"},
 {q:"¿Cuántos Gramm Zucker hat eine Flasche Energydrink (250ml)?",un:27,unit:"gramos",hint:"Ähnlich wie Cola – plus Koffein.",emoji:"⚡"},
 {q:"¿Cuántos Tonnen Zucker konsumiert Deutschland por año?",un:3000000,unit:"tons",hint:"3 millones Tonnen – über 35 kg pro persona.",emoji:"🍬"},
 {q:"¿Cuántos kcal hat ein Apfelstrudel (100g)?",un:250,unit:"kcal",hint:"Wiener Spezialität mit Butter und Zucker.",emoji:"🥐"},
 {q:"¿Cuántos Milliliter hat ein Standard-Espresso?",un:25,unit:"ml",hint:"Klein aber stark – 7g Kaffeemehl.",emoji:"☕"},
 {q:"¿Cuántos Gramm Kohlenhydrate hat 100g Kartoffeln?",un:17,unit:"gramos",hint:"Weniger als gedacht – Fett en Pommes ist das Problem.",emoji:"🥔"},
 {q:"¿Cuántos Liter Wein trinkt die Welt por año (mil millones)?",un:26,unit:"billion liters",hint:"mil millones Liter – steigende Tendenz.",emoji:"🍷"},
 {q:"¿Cuántos kcal hat 100g Vollmilch (3,5%)?",un:64,unit:"kcal",hint:"Milch ist kalorienärmer als die meisten denken.",emoji:"🥛"},
 {q:"¿Cuántos Gramm Zucker hat 100g Joghurt (Fruchtjoghurt)?",un:13,unit:"gramos",hint:"Fruchtjoghurt hat überraschend viel Zucker.",emoji:"🫙"},
 {q:"¿Cuántos millones Tonnen Weizen produziert Deutschland por año?",un:22,unit:"million tons",hint:"Deutschland ist einer der größten Weizenproduzenten Europas.",emoji:"🌾"},
 {q:"¿Cuántos kcal hat eine Brezel mit Butter?",un:400,unit:"kcal",hint:"Eine beliebte bayrische Snack-Kombination.",emoji:"🥨"},
 {q:"¿Cuántos Gramm Protein hat 100g Thunfisch (aus der Dose)?",un:26,unit:"gramos",hint:"Einer der günstigsten Proteinsupplier.",emoji:"🐟"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 Tasse Tee?",un:30,unit:"litros",hint:"Deutlich weniger als Kaffee.",emoji:"🫖"},
 {q:"¿Cuántos kcal hat 100g Hüttenkäse?",un:98,unit:"kcal",hint:"Sehr eiweißreich und kalorienarm.",emoji:"🧀"},
 {q:"¿Cuántos Gramm Zucker hat ein Gummibärchen?",un:2,unit:"gramos",hint:"Pro Stück – eine Packung hat 140g Zucker.",emoji:"🐻"},
 {q:"¿Cuántos millones Tonnen Lebensmittel verschwendet Deutschland por año?",un:12,unit:"million tons",hint:"Ein Drittel aller produzierten Lebensmittel landet im Müll.",emoji:"🗑️"},
 {q:"¿Cuántos kcal hat ein Brot (Scheibe, 50g)?",un:120,unit:"kcal",hint:"Abhängig von der Brotsorte.",emoji:"🍞"},
 {q:"¿Cuántos Gramm Eiweiß hat ein Hühnerei?",un:6,unit:"gramos",hint:"Eier haben das hochwertigste Protein aller Lebensmittel.",emoji:"🥚"},
 {q:"¿Cuántos millones Liter Cognac und Armagnac destilliert Frankreich por año?",un:200,unit:"million liters",hint:"millones Liter Cognac und Armagnac.",emoji:"🥃"},
 {q:"¿Cuántos kcal hat 100g Olivenöl?",un:884,unit:"kcal",hint:"Das kalorienreichste gängige Lebensmittel.",emoji:"🫒"},
 {q:"¿Cuántos Gramm Zucker hat 100ml Orangensaft (frisch gepresst)?",un:8,unit:"gramos",hint:"Frisch gepresst hat etwas weniger Zucker als Fertigsaft.",emoji:"🍊"},
 {q:"¿Cuántos Tonnen Schinken produziert Spanien por año?",un:350000,unit:"tons",hint:"Spanien ist Weltmeister im Schinkenkonsum.",emoji:"🥩"},
 {q:"¿Cuántos kcal hat ein Stück Tiramisu (100g)?",un:400,unit:"kcal",hint:"Mascarpone, Eier und Zucker machen es kalorienreich.",emoji:"🎂"},
 {q:"¿Cuántos Gramm Fett hat 100g Cheddar-Käse?",un:34,unit:"gramos",hint:"Hartkäse sind generell sehr fettreich.",emoji:"🧀"},
 {q:"¿Cuántos Liter Schnaps trinkt ein Österreicher por año?",un:5,unit:"litros",hint:"Österreich führt Europa im Schnapskonsum un.",emoji:"🥃"},
 {q:"¿Cuántos kcal hat 100g Lachs (geräuchert)?",un:180,unit:"kcal",hint:"Lachs hat mehr Kalorien als mageres Fleisch.",emoji:"🐟"},
 {q:"¿Cuántos Gramm Protein hat 100g Tempeh?",un:19,unit:"gramos",hint:"Tempeh hat mehr Protein als Tofu.",emoji:"🫘"},
 {q:"¿Cuántos millones Tonnen Zucker isst die Welt por año?",un:200,unit:"million tons",hint:"millones Tonnen – steigend.",emoji:"🍬"},
 {q:"¿Cuántos kcal hat ein Gulasch mit Reis?",un:800,unit:"kcal",hint:"Ein sättigendes Mittagessen.",emoji:"🍲"},
 {q:"¿Cuántos Gramm Kohlenhydrate hat 100g Weißbrot?",un:50,unit:"gramos",hint:"Weißbrot hat einen hohen glykämischen Index.",emoji:"🍞"},
 {q:"¿Cuántos millones Tonnen Fisch werden en el mundo por año gegessen?",un:90,unit:"million tons",hint:"millones Tonnen – die Ozeane werden überfischt.",emoji:"🐟"},
 {q:"¿Cuántos kcal hat 100g Leberwurst?",un:330,unit:"kcal",hint:"Sehr fett- und kalorienreich.",emoji:"🌭"},
 {q:"¿Cuántos Gramm Ballaststoffe hat 100g Vollkornbrot?",un:7,unit:"gramos",hint:"Deutlich mehr als Weißbrot (2g).",emoji:"🍞"},
 {q:"¿Cuántos Liter Trinkwasser verbraucht ein Deutscher al día?",un:124,unit:"litros",hint:"Davon trinkt man nur 1-2 Liter direkt.",emoji:"💧"},
 {q:"¿Cuántos kcal hat ein Stück Schwarzbrot (50g)?",un:108,unit:"kcal",hint:"Kalorienärmer als Weißbrot.",emoji:"🍞"},
 {q:"¿Cuántos Gramm Zucker hat 100ml Cola?",un:10.6,unit:"gramos",hint:"Über 10% Zucker en jedem Schluck.",emoji:"🥤"},
 {q:"¿Cuántos Tonnen Käse produziert Deutschland por año?",un:2000000,unit:"tons",hint:"Deutschland ist weltführend en der Käseproduktion.",emoji:"🧀"},
 {q:"¿Cuántos kcal hat 100g Baklava?",un:430,unit:"kcal",hint:"Süßes türkisches Gebäck aus Blätterteig und Honig.",emoji:"🍯"},
 {q:"¿Cuántos Gramm Eiweiß hat 100g Rinderfilet?",un:22,unit:"gramos",hint:"Mageres Rindfleisch ist eine hervorragende Proteinquelle.",emoji:"🥩"},
 {q:"¿Cuántos millones Liter Wodka trinkt Russland por año?",un:1600,unit:"million liters",hint:"Russland führt en el mundo den Wodkakonsum.",emoji:"🥃"},
 {q:"¿Cuántos kcal hat ein Stück Apfelkuchen (100g)?",un:290,unit:"kcal",hint:"Mit Sahne nochmal 100 kcal mehr.",emoji:"🥧"},
 {q:"¿Cuántos Gramm Fett hat 100g Camembert?",un:24,unit:"gramos",hint:"Der Fettgehalt variiert je nach Reifegrad.",emoji:"🧀"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 kg Soja?",un:1000,unit:"litros",hint:"Weniger als tierische Produkte.",emoji:"🫘"},
 {q:"¿Cuántos kcal hat ein Franzbrötchen (80g)?",un:320,unit:"kcal",hint:"Hamburger Spezialität mit Butter und Zimt.",emoji:"🥐"},
 {q:"¿Cuántos Gramm Kohlenhydrate hat 100g Nudeln (ungekocht)?",un:70,unit:"gramos",hint:"Nudeln sind eine Kohlenhydrat-Bombe.",emoji:"🍝"},
 {q:"¿Cuántos Tonnen Schokolade exportiert Deutschland por año?",un:400000,unit:"tons",hint:"Deutschland ist Europas größter Schokoladenexporteur.",emoji:"🍫"},
 {q:"¿Cuántos kcal hat ein Weißwein-Schorle (200ml)?",un:80,unit:"kcal",hint:"Weniger als Rotwein durch die Verdünnung.",emoji:"🍷"},
 {q:"¿Cuántos Gramm Zucker hat ein Bounty (57g)?",un:31,unit:"gramos",hint:"Über die Hälfte ist Zucker.",emoji:"🍫"},
 {q:"¿Cuántos millones Liter Sekt trinkt Deutschland por año?",un:300,unit:"million liters",hint:"Deutschland ist Weltmeister im Sektkonsum.",emoji:"🥂"},
 {q:"¿Cuántos kcal hat 100g Nüsse (gemischt)?",un:600,unit:"kcal",hint:"Nüsse sind sehr kalorienreich aber gesund.",emoji:"🥜"},
 {q:"¿Cuántos Gramm Eiweiß hat 100g Shrimps?",un:24,unit:"gramos",hint:"Sehr proteinreich und kalorienarm.",emoji:"🍤"},
 {q:"¿Cuántos Liter Milch trinkt ein Deutscher por año?",un:52,unit:"litros",hint:"Rückgang seit Jahren – Alternativen boomen.",emoji:"🥛"},
 {q:"¿Cuántos kcal hat 100g Hummus?",un:177,unit:"kcal",hint:"Gesunder Aufschnitt aus Kichererbsen.",emoji:"🫘"},
 {q:"¿Cuántos Gramm Fett hat 100g Chips?",un:35,unit:"gramos",hint:"Ein Drittel der Chips besteht aus Fett.",emoji:"🍟"},
 {q:"¿Cuántos Tonnen Tomatenmark produziert die Welt por año?",un:9000000,unit:"tons",hint:"Die Basis rápido aller Saucen.",emoji:"🍅"},
 {q:"¿Cuántos kcal hat ein Stück Königsberger Klopse (2 Stück)?",un:400,unit:"kcal",hint:"Deutsche Fleischbällchen en Kapernsauce.",emoji:"🍲"},
 {q:"¿Cuántos Gramm Kohlenhydrate hat 100g Honig?",un:80,unit:"gramos",hint:"Honig besteht rápido nur aus Zucker.",emoji:"🍯"},
 {q:"¿Cuántos millones Tonnen Getreide produziert die EU por año?",un:300,unit:"million tons",hint:"Getreide ist die wichtigste Nahrungsgrundlage.",emoji:"🌾"},
 {q:"¿Cuántos kcal hat ein Glas Smoothie (300ml)?",un:180,unit:"kcal",hint:"Smoothies können viele versteckte Kalorien haben.",emoji:"🍹"},
 {q:"¿Cuántos Gramm Protein hat 100g Kürbiskerne?",un:30,unit:"gramos",hint:"Eine der proteinreichsten pflanzlichen Quellen.",emoji:"🎃"},
 {q:"¿Cuántos mil millones Liter Bier braut die USA por año?",un:20,unit:"billion liters",hint:"Größter Biermarkt der Welt nach China.",emoji:"🍺"},
 {q:"¿Cuántos kcal hat eine Tasse Cappuccino?",un:120,unit:"kcal",hint:"Milch und Schaum haben Kalorien.",emoji:"☕"},
 {q:"¿Cuántos Gramm Zucker hat 100g Marmelade?",un:65,unit:"gramos",hint:"Marmelade ist rápido zwei Drittel Zucker.",emoji:"🍓"},
 {q:"¿Cuántos Tonnen Butter produziert Deutschland por año?",un:500000,unit:"tons",hint:"Deutschland ist Europas größter Butterproduzent.",emoji:"🧈"},
 {q:"¿Cuántos kcal hat 100g Mandeln?",un:576,unit:"kcal",hint:"Sehr kalorienreich – auch wenn sie gesund sind.",emoji:"🌰"},
 {q:"¿Cuántos Gramm Eiweiß hat 100g Mozzarella?",un:18,unit:"gramos",hint:"Mehr Protein als die meisten Weichkäse.",emoji:"🧀"},
 {q:"¿Cuántos Stunden fermentiert traditionelles Sauerkraut?",un:336,unit:"horas",hint:"14 Tage oder mehr.",emoji:"🥬"},
 {q:"¿Cuántos kcal hat 100g Frühstücksflocken (Cornflakes)?",un:370,unit:"kcal",hint:"Weniger als Müsli mit Nüssen.",emoji:"🥣"},
 {q:"¿Cuántos Gramm Kohlenhydrate hat 100g Weintrauben?",un:17,unit:"gramos",hint:"Trauben sind sehr zuckerreich.",emoji:"🍇"},
 {q:"¿Cuántos millones Tonnen Fleisch produziert die Welt por año?",un:340,unit:"million tons",hint:"Davon ist die Hälfte Schweinefleisch.",emoji:"🥩"},
 {q:"¿Cuántos kcal hat ein Knäckebrot (10g)?",un:34,unit:"kcal",hint:"Sehr kalorienarm – gut als Diätknacker.",emoji:"🍞"},
 {q:"¿Cuántos Gramm Fett hat 100g Sahne (Schlagsahne)?",un:35,unit:"gramos",hint:"Schlagsahne ist rápido reines Fett.",emoji:"🍦"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 kg Äpfel?",un:822,unit:"litros",hint:"Äpfel brauchen deutlich weniger Wasser als exotische Früchte.",emoji:"🍎"},
 {q:"¿Cuántos kcal hat ein Berliner Pfannkuchen (60g)?",un:250,unit:"kcal",hint:"Frittiert und mit Marmelade gefüllt.",emoji:"🍩"},
 {q:"¿Cuántos Gramm Protein hat 100g Kichererbsen (gekocht)?",un:9,unit:"gramos",hint:"Eine wichtige vegane Proteinquelle.",emoji:"🫘"},
 {q:"¿Cuántos Tonnen Olivenöl produziert Spanien por año?",un:1800000,unit:"tons",hint:"Größter Olivenölproduzent en el mundo.",emoji:"🫒"},
 {q:"¿Cuántos kcal hat 100g Speck?",un:541,unit:"kcal",hint:"Einer der kalorienreichsten Fleischprodukte.",emoji:"🥓"},
 {q:"¿Cuántos Gramm Kohlenhydrate hat 100g Süßkartoffeln?",un:20,unit:"gramos",hint:"Etwas mehr als normale Kartoffeln.",emoji:"🍠"},
 {q:"¿Cuántos millones Hektoliter Wein produziert Italien por año?",un:50,unit:"Mio. Hektoliter",hint:"Italiens größter Weinexport-Posten.",emoji:"🍷"},
 {q:"¿Cuántos kcal hat 100g Räucherlachs?",un:180,unit:"kcal",hint:"Weniger kalorienreich als geräuchertes Fleisch.",emoji:"🐟"},
 {q:"¿Cuántos Gramm Fett hat 100g Bratwurst?",un:25,unit:"gramos",hint:"Bratwurst ist ein fettreiches Produkt.",emoji:"🌭"},
 {q:"¿Cuántos Stunden dauert die Herstellung von Sojasoße traditionell?",un:4380,unit:"horas",hint:"6 Monate Fermentation.",emoji:"🫙"},
 {q:"¿Cuántos kcal hat eine Pizza Margherita (30cm)?",un:900,unit:"kcal",hint:"Die klassische Pizza – noch ohne Extras.",emoji:"🍕"},
 {q:"¿Cuántos Gramm Zucker hat 100g Honigmelone?",un:8,unit:"gramos",hint:"Melone ist im Sommer perfekt.",emoji:"🍈"},
 {q:"¿Cuántos millones Tonnen Zucker stecken en der weltweiten Coca-Cola-Produktion por año?",un:10,unit:"million tons",hint:"millones Tonnen Zucker en Coca-Cola al año.",emoji:"🥤"},
 {q:"¿Cuántos kcal hat 100g Edamer Käse?",un:357,unit:"kcal",hint:"Ein milder Schnitt-Käse mit mittlerem Fettgehalt.",emoji:"🧀"},
 {q:"¿Cuántos Gramm Eiweiß hat 100g griechischer Joghurt?",un:10,unit:"gramos",hint:"Doppelt so viel wie normaler Joghurt.",emoji:"🫙"},
 {q:"¿Cuántos mil millones Liter Scotch Whisky exportiert Schottland por año?",un:1300,unit:"million liters",hint:"1,3 mil millones Liter – Scotch Whisky ist ein Riesenmarkt.",emoji:"🥃"},
 {q:"¿Cuántos kcal hat 100g Mayonnaise?",un:680,unit:"kcal",hint:"rápido reines Fett aus Öl und Ei.",emoji:"🫙"},
 {q:"¿Cuántos Gramm Fett hat 100g Avocado?",un:15,unit:"gramos",hint:"Ungesättigte Fettsäuren – die guten Fette.",emoji:"🥑"},
 {q:"¿Cuántos millones kg Kaffee verbraucht Deutschland al día?",un:2,unit:"Millionen kg",hint:"millones Kilogramm Kaffee al día.",emoji:"☕"},
 {q:"¿Cuántos kcal hat 100g Camembert (45% Fett)?",un:290,unit:"kcal",hint:"Weichkäse sind kalorienreich.",emoji:"🧀"},
 {q:"¿Cuántos Gramm Kohlenhydrate hat 100g Banane?",un:23,unit:"gramos",hint:"Bananen liefern schnelle Energie.",emoji:"🍌"},
 {q:"¿Cuántos Gramm Eiweiß hat 100g Tofu?",un:8,unit:"gramos",hint:"Tofu ist eine wichtige vegane Proteinquelle.",emoji:"🫘"},
 {q:"¿Cuántos kcal hat 100g Schinken?",un:130,unit:"kcal",hint:"Weniger fett als Salami.",emoji:"🥩"},
 {q:"¿Cuántos Gramm Zucker hat ein Schokoriegel (Mars, 51g)?",un:36,unit:"gramos",hint:"rápido drei Viertel des Schokoriegels ist Zucker.",emoji:"🍫"},
 {q:"¿Cuántos Liter Bier trinkt ein Tscheche por año?",un:189,unit:"litros",hint:"Weltmeister im Pro-Kopf-Bierverbrauch.",emoji:"🍺"},
 {q:"¿Cuántos Gramm Fett hat 100g Nutella?",un:31,unit:"gramos",hint:"Und 57g Zucker dazu.",emoji:"🍫"},
 {q:"¿Cuántos kcal hat 100g Lachs (frisch)?",un:208,unit:"kcal",hint:"Reich un Omega-3-Fettsäuren.",emoji:"🐟"},
 {q:"¿Cuántos kg Fleisch isst ein Amerikaner por año?",un:120,unit:"kg",hint:"rápido doppelt so viel wie ein Europäer.",emoji:"🥩"},
 {q:"¿Cuántos Gramm Zucker hat ein Glas Milchkaffee (Latte, 300ml)?",un:14,unit:"gramos",hint:"Durch die Milch.",emoji:"☕"},
 {q:"¿Cuántos kcal hat ein Stück Tiramisu (150g)?",un:600,unit:"kcal",hint:"Mascarpone macht es sehr kalorienreich.",emoji:"🎂"},
 {q:"¿Cuántos Gramm Protein hat 100g Seitan?",un:25,unit:"gramos",hint:"Weizenglutenprodukt – sehr proteinreich.",emoji:"💪"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 kg Hühnchen?",un:4325,unit:"litros",hint:"Deutlich weniger als Rind.",emoji:"🐔"},
 {q:"¿Cuántos kcal hat ein Donut (Glazed, 57g)?",un:269,unit:"kcal",hint:"Klein aber mächtig kalorienreich.",emoji:"🍩"},
 {q:"¿Cuántos Gramm Fett hat 100g Chorizo?",un:40,unit:"gramos",hint:"Eine der fettreichsten Wurstarten.",emoji:"🌭"},
 {q:"¿Cuántos por ciento Fett enthält griechischer Joghurt (normal)?",un:10,unit:"%",hint:"Deutlich fettreicher als normaler Joghurt.",emoji:"🫙"},
 {q:"¿Cuántos kcal hat 100g Roquefort-Käse?",un:369,unit:"kcal",hint:"Schimmelkäse sind kalorienreicher.",emoji:"🧀"},
 {q:"¿Cuántos Gramm Zucker hat 100g Müsli?",un:15,unit:"gramos",hint:"Ungesüßtes Müsli hat weniger – Fertigprodukte viel mehr.",emoji:"🥣"},
 {q:"¿Cuántos Liter produziert ein Weinberg (Hektar) por año?",un:5000,unit:"litros",hint:"Wein braucht erstaunlich viel Wasser.",emoji:"🍷"},
 {q:"¿Cuántos kcal hat ein Glas Apfelsaft (200ml)?",un:94,unit:"kcal",hint:"rápido wie Cola – trotz 'gesund'.",emoji:"🍎"},
 {q:"¿Cuántos Gramm Protein hat 100g Haferflocken?",un:13,unit:"gramos",hint:"Eine der proteinreichsten Getreidearten.",emoji:"🌾"},
 {q:"¿Cuántos kcal hat ein Stück Focaccia (100g)?",un:270,unit:"kcal",hint:"Italienisches Fladenbrot mit Olivenöl.",emoji:"🍞"},
 {q:"¿Cuántos Gramm Kohlenhydrate hat 100g Paprika?",un:6,unit:"gramos",hint:"Paprika ist sehr kohlenhydratarm.",emoji:"🌶️"},
 {q:"¿Cuántos Liter Milch trinkt ein Finne por año?",un:180,unit:"litros",hint:"Finnland ist Weltmeister im Milchkonsum.",emoji:"🥛"},
 {q:"¿Cuántos kcal hat ein Vollkornbrot (Scheibe, 50g)?",un:105,unit:"kcal",hint:"Etwas weniger als Weißbrot.",emoji:"🍞"},
 {q:"¿Cuántos Gramm Zucker hat 100g Balsamico-Essig?",un:17,unit:"gramos",hint:"Viel Zucker für ein Sauerprodukt.",emoji:"🫙"},
 {q:"¿Cuántos Tonnen Sushi wird al día en Japan gegessen?",un:2000,unit:"tons",hint:"Japan bleibt der Weltmarktführer.",emoji:"🍣"},
 {q:"¿Cuántos kcal hat ein Hotdog (normal)?",un:290,unit:"kcal",hint:"Mit Senf und Ketchup etwas mehr.",emoji:"🌭"},
 {q:"¿Cuántos Gramm Calcium hat 100g Parmesan?",un:1184,unit:"gramos",hint:"Parmesan hat mehr Calcium als rápido jedes andere Lebensmittel.",emoji:"🧀"},
 {q:"¿Cuántos millones Tonnen Schokolade produziert die Welt por año?",un:8,unit:"million tons",hint:"millones Tonnen en el mundo.",emoji:"🍫"},
 {q:"¿Cuántos kcal hat 100g Macarons?",un:450,unit:"kcal",hint:"Sehr zuckerreich und kalorienreich.",emoji:"🍬"},
 {q:"¿Cuántos Gramm Zucker hat ein Red Bull (250ml)?",un:27,unit:"gramos",hint:"rápido so viel wie Cola.",emoji:"⚡"},
 {q:"¿Cuántos Liter Wasser braucht man für 1 Tasse heißen Tee?",un:30,unit:"litros",hint:"Inklusive Anbau und Verarbeitung.",emoji:"🍵"},
 {q:"¿Cuántos kcal hat ein Stück Baklava (50g)?",un:215,unit:"kcal",hint:"Süß und kalorienreich.",emoji:"🍯"},
 {q:"¿Cuántos Gramm Protein hat 100g Kürbissamen?",un:30,unit:"gramos",hint:"Eine der proteinreichsten pflanzlichen Quellen.",emoji:"🎃"},
 {q:"¿Cuántos Tonnen Zucker isst ein Europäer por año?",un:38,unit:"kg",hint:"Kg – über 100g al día.",emoji:"🍬"},
 {q:"¿Cuántos kcal hat ein Stück Käsekuchen (100g)?",un:321,unit:"kcal",hint:"Quark und Eier machen ihn kalorienreich.",emoji:"🎂"},
 {q:"¿Cuántos Gramm Eiweiß hat 100g schwarze Bohnen (gekocht)?",un:9,unit:"gramos",hint:"Gute pflanzliche Proteinquelle.",emoji:"🫘"},
 {q:"¿Cuántos Liter Kaffee trinkt ein Norweger por año?",un:9.9,unit:"kg",hint:"Skandinavien führt den Kaffeekonsum en el mundo.",emoji:"☕"},
 {q:"¿Cuántos kcal hat 100g Acai-Beeren?",un:534,unit:"kcal",hint:"Überraschend kalorienreich trotz 'Superfood'.",emoji:"🫐"},
 {q:"¿Cuántos Gramm Fett hat 100g Hüttenkäse?",un:4,unit:"gramos",hint:"Sehr fettarm und proteinreich.",emoji:"🧀"},
 {q:"¿Cuántos kcal hat ein Glas Buttermilch (200ml)?",un:66,unit:"kcal",hint:"Kalorienarm und proteinreich.",emoji:"🥛"},
 {q:"¿Cuántos Gramm Zucker hat eine Flasche Gatorade (500ml)?",un:34,unit:"gramos",hint:"Ähnlich wie eine Dose Limo.",emoji:"🏃"},
 {q:"¿Cuántos Tonnen Avocado importiert Europa por año?",un:1000000,unit:"tons",hint:"1 millones Tonnen – der Boom hält un.",emoji:"🥑"},
 {q:"¿Cuántos kcal hat 100g Joghurt mit Früchten?",un:100,unit:"kcal",hint:"Fruchtjoghurt hat mehr als Naturjoghurt.",emoji:"🫙"},
 {q:"¿Cuántos Gramm Protein hat 100g Edamame?",un:11,unit:"gramos",hint:"Unreife Sojabohnen – ideal als Snack.",emoji:"🫘"},
];