// 💩 CUERPO Y ASCO – Español
export default [
 {q:"¿Cuántos Liter Pupsgase produziert un humano por día?",un:1.5,unit:"litros",hint:"14-23 Mal al día ein Pups.",emoji:"💨"},
 {q:"¿Cuántos Gramm wiegt ein normaler Stuhlgang?",un:150,unit:"gramos",hint:"100-200g ist der Normalbereich.",emoji:"💩"},
 {q:"¿Cuántos Mal por día pupst un humano en promedio?",un:14,unit:"veces",hint:"Komplett normal – Frauen auch.",emoji:"💨"},
 {q:"¿Cuántos Liter Schleim produziert die Nase al día?",un:1,unit:"litros",hint:"Ein Liter al día – rápido alles schlucken wir.",emoji:"🤧"},
 {q:"¿Cuántos Milliliter Schmalz scheidet ein Ohr por mes aus?",un:1,unit:"ml",hint:"Erstaunlich viel für ein so kleines órgano.",emoji:"👂"},
 {q:"¿Cuántos Gramm Bakterien sind im Darm eines Menschen?",un:200,unit:"gramos",hint:"Das Darmmikrobiom wiegt 200g.",emoji:"🦠"},
 {q:"¿Cuántos Mal im Leben wird un humano kotzen (übergeben)?",un:200,unit:"veces",hint:"en promedio über ein Leben.",emoji:"🤢"},
 {q:"¿Cuántos Liter Magensäure werden beim Erbrechen hochgepumpt?",un:0.3,unit:"litros",hint:"300ml bei einem typischen Erbrechen.",emoji:"🤮"},
 {q:"¿Cuántos Gramm Hautzellen verliert un humano al día?",un:30,unit:"gramos",hint:"Dein Bett sammelt das alles auf.",emoji:"🧑"},
 {q:"¿Cuántos millones Bakterien überträgt man beim Händeschütteln?",un:10,unit:"millones",hint:"Ein Händedruck überträgt 10-100 millones.",emoji:"🤝"},
 {q:"¿Cuántos Liter Schweiß produziert un humano bei einem Ultramarathon?",un:10,unit:"litros",hint:"Bei extremer Hitze und Belastung.",emoji:"💦"},
 {q:"¿Cuántos millones Bakterien sind auf einem Schreibtisch pro m²?",un:400,unit:"millones",hint:"Schreibtische sind schmutziger als Toiletten.",emoji:"🦠"},
 {q:"¿Cuántos Sekunden dauert ein Nieser von Einatmung bis Explosion?",un:0.5,unit:"segundos",hint:"Schleudert Partikel mit 160km/h.",emoji:"🤧"},
 {q:"¿Cuántos km/h fliegen Schleimpartikel beim Niesen?",un:160,unit:"km/h",hint:"Bis zu 8 Meter weit.",emoji:"🤧"},
 {q:"¿Cuántos Gramm Schweiß produziert un humano por hora beim Sport?",un:1000,unit:"gramos",hint:"1 Liter Schweiß por hora.",emoji:"💦"},
 {q:"¿Cuántos millones Mikrobenwird en der Öffentlichkeit al día ausgeatmet?",un:37,unit:"millones",hint:"Nur durch normales Atmen.",emoji:"💨"},
 {q:"¿Cuántos Liter Urin produziert un humano por día?",un:1.5,unit:"litros",hint:"1-2 Liter bei normaler Hydration.",emoji:"💛"},
 {q:"¿Cuántos Mal im Jahr bekommt ein Europäer Durchfall?",un:2,unit:"veces",hint:"Gastroenteritis ist sehr häufig.",emoji:"🚽"},
 {q:"¿Cuántos Tonnen Kot produziert un humano en seinem Leben?",un:8,unit:"tons",hint:"Bei 150g por día über 70 Jahre.",emoji:"💩"},
 {q:"¿Cuántos millones Bakterien sind auf einer Zahnbürste?",un:10,unit:"millones",hint:"Nach nur wenigen Tagen Benutzung.",emoji:"🦷"},
 {q:"¿Cuántos Gramm Körpergeruchsbakterien produziert un humano al día?",un:2,unit:"gramos",hint:"Bakterien bauen Schweißproteine ab.",emoji:"💦"},
 {q:"¿Cuántos Liter Speichel enthält ein Kuss?",un:3,unit:"ml",hint:"3ml Speichel – plus 80 millones Bakterien.",emoji:"💋"},
 {q:"¿Cuántos Gramm Fußpilzporen können en einem Zimmer sein?",un:10,unit:"mg",hint:"Winzige Mengen – reichen aber für Infektionen.",emoji:"🦶"},
 {q:"¿Cuántos millones Bakterien sind auf einem Küchenspülschwamm?",un:54,unit:"mil millones",hint:"mil millones – schmutzigster Haushaltsgegenstand.",emoji:"🫧"},
 {q:"¿Cuántos Mal husten Menschen mit Erkältung am Tag?",un:200,unit:"veces",hint:"Bis zu viele masculino al día.",emoji:"😷"},
 {q:"¿Cuántos Gramm Magen-Darm-Inhalt werden beim Erbrechen ausgeworfen?",un:300,unit:"gramos",hint:"Je nach Mahlzeit.",emoji:"🤮"},
 {q:"¿Cuántos millones Hautzellen sind en einem Bett nach einem Jahr?",un:1000,unit:"millones",hint:"Matratzen sammeln enormen Schmutz.",emoji:"🛏️"},
 {q:"¿Cuántos Liter Urin sind en einer vollen Blase?",un:0.6,unit:"litros",hint:"500-600ml maximale Kapazität.",emoji:"💛"},
 {q:"¿Cuántos millones Sporen kann ein Schimmelpilz por día produzieren?",un:1000,unit:"millones",hint:"1 Milliarde Sporen – winzig und überall.",emoji:"🍄"},
 {q:"¿Cuántos Liter Galle produziert die Leber al día?",un:0.5,unit:"litros",hint:"500ml – essenziell für die Fettverdauung.",emoji:"💛"},
 {q:"¿Cuántos Gramm Kot enthalten Sandwichbrote wenn kein Händewaschen erfolgt?",un:200,unit:"mg",hint:"Messstudie: Fäkalbakterien auf 1 von 6 Hände.",emoji:"🤢"},
 {q:"¿Cuántos millones Bakterien sind auf einem Handtuch nach einer Woche?",un:100,unit:"millones",hint:"Badezimmerhandtücher sind voller Bakterien.",emoji:"🧺"},
 {q:"¿Cuántos km/h ist die maximale Geschwindigkeit eines Huste-Ausstoßes?",un:150,unit:"km/h",hint:"Etwas langsamer als ein Niesen.",emoji:"😷"},
 {q:"¿Cuántos Gramm wiegt der gesamte Inhalt des Dünndarms?",un:500,unit:"gramos",hint:"Inklusive unverdauter Nahrung und Flüssigkeit.",emoji:"🌀"},
 {q:"¿Cuántos millones Bakterien überträgt ein Handschlag?",un:10,unit:"millones",hint:"Hände sind der größte Übertragungsweg.",emoji:"🤝"},
 {q:"¿Cuántos Liter Gallensäfte werden al día produziert?",un:1,unit:"litros",hint:"Aus Leber und Gallenblase.",emoji:"💛"},
 {q:"¿Cuántos Gramm Ohrenschmalz produziert ein Ohr por año?",un:12,unit:"gramos",hint:"12g – ein Esslöffel por año.",emoji:"👂"},
 {q:"¿Cuántos millones Hausmilben sind en einem Kopfkissen?",un:10,unit:"millones",hint:"Ernähren sich von Hautschuppen.",emoji:"🛏️"},
 {q:"¿Cuántos Gramm Kot werden nach einem Einlauf ausgeschieden?",un:2000,unit:"gramos",hint:"2 Liter – mehr als ein normaler Stuhlgang.",emoji:"💩"},
 {q:"¿Cuántos Liter Flüssigkeit verliert man beim Schwitzen en der Sauna?",un:1.5,unit:"litros",hint:"Pro Saunagang.",emoji:"🧖"},
 {q:"¿Cuántos millones Bakterien sind auf einer Türklinke?",un:10,unit:"millones",hint:"Öffentliche Türklinken sind voller Keime.",emoji:"🦠"},
 {q:"¿Cuántos Gramm Zahnstein bilden sich ohne Mundhygiene por año?",un:10,unit:"gramos",hint:"Mineralisierter Zahnbelag.",emoji:"🦷"},
 {q:"¿Cuántos millones Haare verliert man durch normales Waschen por semana?",un:700,unit:"hairs",hint:"100 por día × 7 Tage.",emoji:"🚿"},
 {q:"¿Cuántos Gramm Augenabsonderung produzieren die Augen al día?",un:1,unit:"gramos",hint:"Die Krusten am Morgen.",emoji:"👁️"},
 {q:"¿Cuántos millones Bakterien sind en einem Liter Trinkwasser?",un:1,unit:"millones",hint:"en normalem Leitungswasser – meist harmlos.",emoji:"💧"},
 {q:"¿Cuántos Gramm Stuhl kann ein Darm zurückhalten ohne Druck zu spüren?",un:500,unit:"gramos",hint:"500g bevor der Harndrang kommt.",emoji:"💩"},
 {q:"¿Cuántos Liter Speichel schluckt man al día?",un:1.5,unit:"litros",hint:"Den ganzen Tag produziert und geschluckt.",emoji:"💧"},
 {q:"¿Cuántos millones Schimmelpilzsporen sind en einem normalen Haus?",un:10,unit:"millones",hint:"Überall – besonders en Badezimmern.",emoji:"🍄"},
 {q:"¿Cuántos Gramm Schmegma bilden sich wöchentlich ungewaschen?",un:5,unit:"gramos",hint:"Talgabsonderungen unter der Vorhaut.",emoji:"😬"},
 {q:"¿Cuántos millones Fäkalbakterien sind auf einem Smartphone?",un:25,unit:"mil",hint:"Mehr als auf einer Toilette.",emoji:"📱"},
 {q:"¿Cuántos Liter Blut verliert una mujer während ihrer Lebens-Perioden?",un:30,unit:"litros",hint:"Ca. 50ml pro Periode × 500 Perioden.",emoji:"🩸"},
 {q:"¿Cuántos Gramm Abgase atmet un humano en einer Großstadt al día ein?",un:100,unit:"mg",hint:"Feinstaub und Abgase.",emoji:"🌫️"},
 {q:"¿Cuántos millones Bakterien sterben al día en unserem Körper?",un:1000,unit:"mil millones",hint:"Billionen Bakterien im Gleichgewicht.",emoji:"🦠"},
 {q:"¿Cuántos Gramm Schmutz sind en Regenregenwasser pro Liter?",un:1,unit:"mg",hint:"Mikropartikel en jedem Regentropfen.",emoji:"🌧️"},
 {q:"¿Cuántos millones Keime sind im Mund nach dem Aufwachen?",un:20,unit:"mil millones",hint:"Morgenmund enthält viele Bakterien.",emoji:"😬"},
 {q:"¿Cuántos Gramm Hautschuppen fallen por año aus dem Haar?",un:5,unit:"gramos",hint:"Dandruff – normal bis 5g al día.",emoji:"💇"},
 {q:"¿Cuántos Liter Blut werden pro Periode ausgegeben?",un:50,unit:"ml",hint:"50ml – weniger als viele denken.",emoji:"🩸"},
 {q:"¿Cuántos millones Staubmilben leben en einem durchschnittlichen Bett?",un:10,unit:"millones",hint:"Sie fressen unsere Hautzellen.",emoji:"🛏️"},
 {q:"¿Cuántos Liter Mageninhalt werden beim Erbrechen maximal ausgeleert?",un:1.5,unit:"litros",hint:"Magenkapazität beträgt maximal 1,5L.",emoji:"🤮"},
 {q:"¿Cuántos millones Bakterien sind auf einem frischen Küchenmesser?",un:5,unit:"millones",hint:"Besonders auf dem Griff.",emoji:"🔪"},
 {q:"¿Cuántos Gramm Fett schwitzt der Körper al día aus?",un:5,unit:"gramos",hint:"Talg und Lipide en Schweiß.",emoji:"💦"},
 {q:"¿Cuántos Liter Schleim produziert der Darm al día?",un:1.5,unit:"litros",hint:"Schleimhaut schützt den Darm.",emoji:"🌀"},
 {q:"¿Cuántos millones Keime überlebt eine Toilette pro Flush?",un:10,unit:"millones",hint:"el baño plume – Keime en der Luft nach dem Spülen.",emoji:"🚽"},
 {q:"¿Cuántos Gramm Schmutz werden beim Händewaschen entfernt?",un:500,unit:"mg",hint:"0,5g Schmutz und Keime.",emoji:"🧼"},
 {q:"¿Cuántos Gramm Haare werden monatlich geschluckt?",un:500,unit:"mg",hint:"Durch Essen, Küssen, Luftschlucken.",emoji:"💇"},
 {q:"¿Cuántos Liter Körperflüssigkeiten verliert un humano al día insgesamt?",un:2.5,unit:"litros",hint:"Urin, Schweiß, Atemluft zusammen.",emoji:"💧"},
 {q:"¿Cuántos millones Bakterien sind auf einem Geldschein?",un:26,unit:"mil",hint:"Bargeld ist eines der dreckigsten Dinge.",emoji:"💵"},
 {q:"¿Cuántos Gramm unverdaute Nahrung sind im Dickdarm?",un:1000,unit:"gramos",hint:"1 kg Nahrungsreste im Dickdarm.",emoji:"🌀"},
 {q:"¿Cuántos millones Pilzsporen atmet un humano al día ein?",un:1,unit:"Million",hint:"Überall en der Luft – meistens harmlos.",emoji:"🍄"},
 {q:"¿Cuántos Gramm Körperfett verbrennt man beim Schlafen?",un:70,unit:"gramos",hint:"Bei 7-8 Stunden Schlaf.",emoji:"😴"},
 {q:"¿Cuántos Liter Blut enthält ein normales Steak?",un:0.1,unit:"litros",hint:"Das Rote ist Myoglobin, nicht Blut.",emoji:"🥩"},
 {q:"¿Cuántos millones Bakterien überlebt en einem Desinfektionsmittel?",un:1,unit:"mil",hint:"Gute Desinfektionsmittel töten 99,999%.",emoji:"🧴"},
 {q:"¿Cuántos Gramm Fingernagel-Dreck enthält eine ungewaschene Hand?",un:10,unit:"mg",hint:"Unter jedem Nagel bis zu 10.000 Bakterien.",emoji:"💅"},
 {q:"¿Cuántos Liter Eiter kann ein Abszess enthalten?",un:0.5,unit:"litros",hint:"Große Abszesse können Tassen voll enthalten.",emoji:"😨"},
 {q:"¿Cuántos millones Zecken sind im Frühjahr en deutschen Wäldern aktiv?",un:100,unit:"millones",hint:"Und jede zehnte trägt Borreliose.",emoji:"🕷️"},
 {q:"¿Cuántos Gramm Fußschweiß produziert ein Fuß al día?",un:50,unit:"gramos",hint:"un humano hat 250.000 Schweißdrüsen un den Füßen.",emoji:"🦶"},
 {q:"¿Cuántos millones Mücken-Stiche passieren en Deutschland im Sommer?",un:10,unit:"mil millones",hint:"Pro Nacht im Sommer.",emoji:"🦟"},
 {q:"¿Cuántos Liter Lymphflüssigkeit hat der Körper?",un:2,unit:"litros",hint:"Das Lymphsystem transportiert Immunzellen.",emoji:"💛"},
 {q:"¿Cuántos Gramm Schmutz enthält ein Staubsaugerbeutel nach einem Monat?",un:200,unit:"gramos",hint:"Davon viel Hautschuppen und Staubmilben.",emoji:"🌀"},
 {q:"¿Cuántos millones Viren sind en einem Milliliter Meerwasser?",un:10,unit:"millones",hint:"Das Meer ist voller Viren – meist für Algen.",emoji:"🌊"},
 {q:"¿Cuántos Gramm Schmalz produziert die Haut al día?",un:10,unit:"gramos",hint:"Talg als Hautschutz.",emoji:"✨"},
 {q:"¿Cuántos Liter Darmgase entstehen al día?",un:2,unit:"litros",hint:"Davon werden 1,5L als Pupse abgegeben.",emoji:"💨"},
 {q:"¿Cuántos millones Hausmilben sind en einem Teppich pro m²?",un:1,unit:"Million",hint:"Jede isst Hautschuppen.",emoji:"🏠"},
 {q:"¿Cuántos Liter Körperwärme verliert man beim Schwitzen insgesamt im Sommer?",un:5,unit:"litros",hint:"un einem heißen Tag.",emoji:"🌡️"},
 {q:"¿Cuántos millones Stunden verbringt die Menschheit al día auf der Toilette?",un:50,unit:"Millionen Stunden",hint:"8 mil millones Menschen × 6 Minuten.",emoji:"🚽"},
 {q:"¿Cuántos Gramm Talg produziert eine Teenager-Haut al día?",un:15,unit:"gramos",hint:"Mehr als Erwachsene – daher Akne.",emoji:"😬"},
 {q:"¿Cuántos Liter Bauchspeichel produziert die Bauchspeicheldrüse al día?",un:1.5,unit:"litros",hint:"Mit wichtigen Verdauungsenzymen.",emoji:"⚗️"},
 {q:"¿Cuántos millones Keime sind auf einem Trinkglas nach dem Abtrocknen?",un:5,unit:"millones",hint:"Feuchte Tücher übertragen Keime.",emoji:"🥃"},
 {q:"¿Cuántos Gramm Zähne-Schmutz (Plaque) bilden sich al día?",un:500,unit:"mg",hint:"Ohne Zähneputzen schnell viel.",emoji:"🦷"},
 {q:"¿Cuántos Liter Blut verliert man bei einem normalen Zahnarzteingriff?",un:1,unit:"ml",hint:"1ml – kaum messbar.",emoji:"🩸"},
 {q:"¿Cuántos millones Trichinen können en einem Stück Rohfleisch sein?",un:1,unit:"Million",hint:"Grund warum Schweinefleisch durchgegart sein muss.",emoji:"🥩"},
 {q:"¿Cuántos Gramm Hornhaut wächst am Fuß por mes?",un:1,unit:"gramos",hint:"Besonders bei Druck.",emoji:"🦶"},
 {q:"¿Cuántos Liter Flüssigkeit ist en einer normalen Blase beim Platzdruck?",un:0.7,unit:"litros",hint:"700ml – dann wird es schmerzhaft.",emoji:"💛"},
 {q:"¿Cuántos millones Bakterien werden beim Pinkeln en die Luft geschleudert?",un:1,unit:"Million",hint:"el baño plume – WC-Spritzer.",emoji:"🚽"},
 {q:"¿Cuántos Gramm Schweiß riechen ohne Deo nach einer Stunde?",un:100,unit:"mg",hint:"Bakterien bauen Schweißsäuren ab.",emoji:"💦"},
 {q:"¿Cuántos Liter Blut fließen bei einer normalen Geburt?",un:0.5,unit:"litros",hint:"Normaler Blutverlust bei Vaginalgeburt.",emoji:"🤱"},
 {q:"¿Cuántos millones Parasiten kann un humano beherbergen?",un:1,unit:"Million",hint:"Darmenparasiten bei Infektion.",emoji:"🪱"},
 {q:"¿Cuántos Gramm Zellreste sind en einem normalen Stuhlgang?",un:50,unit:"gramos",hint:"Abgestorbene Darmzellen.",emoji:"💩"},
 {q:"¿Cuántos Liter Flüssigkeit produziert der Darm al día?",un:8,unit:"litros",hint:"rápido alle werden rückresorbiert.",emoji:"🌀"},
 {q:"¿Cuántos millones Bakterien sterben bei 60°C en Sekunden?",un:1000,unit:"millones",hint:"Pasteurisierung nutzt genau das.",emoji:"🌡️"},
 {q:"¿Cuántos Gramm Pupsgase sind pro Pups?",un:70,unit:"mg",hint:"70ml Gas – je nach Diät mehr.",emoji:"💨"},
 {q:"¿Cuántos Liter Schleim schluckt man beim Schnupfen al día?",un:1,unit:"litros",hint:"Mehr als man denkt.",emoji:"🤧"},
 {q:"¿Cuántos Gramm Körperfett werden por hora Schlaf verbrannt?",un:10,unit:"gramos",hint:"Insgesamt 70g pro Nacht.",emoji:"😴"},
 {q:"¿Cuántos Liter Urin kann die Blase halten ohne Schmerz?",un:0.4,unit:"litros",hint:"Harndrang beginnt schon bei 250ml.",emoji:"💛"},
 {q:"¿Cuántos millones Würmer können im Darm bei starker Infektion sein?",un:1,unit:"Million",hint:"Spulwürmer können zu Tausenden vorkommen.",emoji:"🪱"},
 {q:"¿Cuántos Gramm Gift scheidet die Leber al día aus?",un:10,unit:"gramos",hint:"Entgiftungsleistung por día.",emoji:"🟤"},
 {q:"¿Cuántos Liter Blut verliert man bei einer Amputation?",un:2,unit:"litros",hint:"Ohne tourniquet – schnell lebensbedrohlich.",emoji:"🩸"},
 {q:"¿Cuántos millones Keime sind auf einer Computertastatur?",un:400,unit:"millones",hint:"Tastaturen sind schmutziger als Toiletten.",emoji:"💻"},
 {q:"¿Cuántos Gramm Nasensekret produziert man bei starker Erkältung por día?",un:50,unit:"gramos",hint:"50ml Schleim – viel schnäuzen.",emoji:"🤧"},
 {q:"¿Cuántos Liter Blut verliert man monatlich beim Zähneputzen?",un:1,unit:"ml",hint:"1ml – zahnfleischbluten.",emoji:"🩸"},
 {q:"¿Cuántos Gramm Körperzellen sterben al día ab?",un:50,unit:"gramos",hint:"50g Zellmasse wird al día ersetzt.",emoji:"🔬"},
 {q:"¿Cuántos Liter Speichelfluss passiert beim Gedanken un Essen?",un:0.1,unit:"litros",hint:"100ml allein durch pavlovsche Reaktion.",emoji:"🍕"},
 {q:"¿Cuántos millones Keime überlebt auf einem Kissenbezug nach einer Woche?",un:3,unit:"millones",hint:"Besonders Gesichtsbakterien.",emoji:"🛏️"},
 {q:"¿Cuántos Gramm Fett produzieren die Kopfhautdrüsen al día?",un:1,unit:"gramos",hint:"1g Talg – macht Haare fettig.",emoji:"💇"},
 {q:"¿Cuántos Liter Blut produziert der Körper al día neu?",un:0.2,unit:"litros",hint:"200ml neue rote Blutkörperchen.",emoji:"🩸"},
 {q:"¿Cuántos millones Viren atmet man en einer Stunde im Büro ein?",un:100,unit:"millones",hint:"en Innenräumen sehr viele Viren.",emoji:"🦠"},
 {q:"¿Cuántos Gramm Kot enthält ein menschlicher Körper en promedio?",un:1000,unit:"gramos",hint:"1 kg im Darm immer vorhanden.",emoji:"💩"},
 {q:"¿Cuántos Liter Flüssigkeit fließt al día durch die Nieren?",un:180,unit:"litros",hint:"180L werden gefiltert – nur 1.5L Urin.",emoji:"🫘"},
 {q:"¿Cuántos millones Parasiteneier sind en unbewässertem Boden pro m²?",un:10,unit:"millones",hint:"Hakenwürmer, Spulwürmer en Dritte-Welt-Böden.",emoji:"🌱"},
 {q:"¿Cuántos Gramm Säure ist im Erbrochenen?",un:5,unit:"gramos",hint:"Magensäure pH 1-2.",emoji:"⚗️"},
 {q:"¿Cuántos Liter Tränen produziert un humano beim Weinen?",un:10,unit:"ml",hint:"10ml bei einem weinanfall.",emoji:"😢"},
 {q:"¿Cuántos millones Bakterien sind auf einem Klospülknopf?",un:50,unit:"millones",hint:"Mehr als auf dem Klositz.",emoji:"🚽"},
 {q:"¿Cuántos Gramm Schleim sind en der Lunge?",un:150,unit:"gramos",hint:"Schleimhaut schützt die Atemwege.",emoji:"🫁"},
 {q:"¿Cuántos Liter Magenflüssigkeit kann man beim Spülen entleeren?",un:3,unit:"litros",hint:"Magenspülung – bei Vergiftung.",emoji:"⚗️"},
 {q:"¿Cuántos millones Keime überlebt ein Sponge/Schwamm nach 1 Min Mikrowelle?",un:1,unit:"millones",hint:"Mikrowellen töten nicht alle Keime.",emoji:"🫧"},
 {q:"¿Cuántos Gramm Talgablagerungen entstehen en verstopften Poren (Mitesser)?",un:1,unit:"mg",hint:"Winzige Mengen – aber sichtbar.",emoji:"😬"},
 {q:"¿Cuántos Liter Schweiß produziert der Körper por hora en Hitze?",un:2,unit:"litros",hint:"Bei extremer Hitze bis 3L.",emoji:"☀️"},
 {q:"¿Cuántos millones Bakterien sind auf einem frischen Geldschein?",un:26000,unit:"Bakterien",hint:"Neues Geld hat weniger als altes.",emoji:"💵"},
 {q:"¿Cuántos Gramm Körperschuppen sind im Hausstaub?",un:70,unit:"%",hint:"Des Hausstaubs sind Hautschuppen.",emoji:"🌀"},
 {q:"¿Cuántos Liter Blut enthält die Leber?",un:1.5,unit:"litros",hint:"Die Leber ist ein Blutreservoir.",emoji:"🟤"},
 {q:"¿Cuántos millones Bakterien sind auf einem Lichtschalter?",un:220,unit:"mil",hint:"Häufig berührt – selten gereinigt.",emoji:"💡"},
 {q:"¿Cuántos Gramm Fäkalbakterien könnten auf einem Buffet-Essen sein?",un:1,unit:"mg",hint:"Schlechte Handhygiene von Köchen.",emoji:"🍽️"},
 {q:"¿Cuántos Liter Schweiß produziert man en einer Sauna (Stunde)?",un:1.5,unit:"litros",hint:"Bei 80-90°C.",emoji:"🧖"},
 {q:"¿Cuántos millones Pilzsporen produziert ein Schimmelpilz pro Sekunde?",un:1,unit:"millones",hint:"Schimmel verbreitet sich extrem schnell.",emoji:"🍄"},
 {q:"¿Cuántos Gramm Schleim werden bei einer Erkältung al día produziert?",un:100,unit:"gramos",hint:"100ml Schleim – viel davon geschluckt.",emoji:"🤧"},
 {q:"¿Cuántos mil millones Liter Urin werden al día en deutschen WCs gespült?",un:20,unit:"billion liters",hint:"Enorme Wasserverschwendung.",emoji:"🚽"},
 {q:"¿Cuántos millones Bakterien sind en 1g frischer Erde?",un:1000,unit:"millones",hint:"1 Milliarde Bakterien pro Gramm Erde.",emoji:"🌱"},
 {q:"¿Cuántos Gramm Schmutz sammeln sich por año im Bauchnabel?",un:500,unit:"mg",hint:"Flusen, Öl und Bakterien.",emoji:"🔘"},
 {q:"¿Cuántos Liter Blut verliert man bei einer normalen Menstruation?",un:50,unit:"ml",hint:"50ml pro Periode.",emoji:"🩸"},
 {q:"¿Cuántos millones Bakterien produziert un humano al día durch Hautkontakt?",un:1000,unit:"millones",hint:"Jede Berührung hinterlässt Spuren.",emoji:"🤲"},
 {q:"¿Cuántos Gramm totes Gewebe enthält ein Nagel bei Pilzinfektion?",un:1,unit:"gramos",hint:"Onychomykose – Pilz zerstört Nagelstruktur.",emoji:"💅"},
 {q:"¿Cuántos Liter Lymphe wird al día durch Lymphknoten gefiltert?",un:3,unit:"litros",hint:"Das Lymphsystem als zweites Transportsystem.",emoji:"💛"},
 {q:"¿Cuántos millones Keime sind en einem Handtuch nach einer Woche?",un:100,unit:"millones",hint:"Feuchte Handtücher sind ideal für Bakterien.",emoji:"🧺"},
 {q:"¿Cuántos Gramm unverdautes Essen verlässt den Körper im Stuhl al día?",un:30,unit:"gramos",hint:"Ballaststoffe und unverdauliche Reste.",emoji:"💩"},
 {q:"¿Cuántos Liter Magensäure werden al día produziert?",un:2,unit:"litros",hint:"Stark genug um Stahl aufzulösen.",emoji:"⚗️"},
 {q:"¿Cuántos millones Viren sind en 1ml Flusswasser?",un:1,unit:"Million",hint:"Flüsse sind voller Viren – meist harmlose.",emoji:"🌊"},
 {q:"¿Cuántos Gramm Körperfett werden beim Lachen verbrannt?",un:1,unit:"mg",hint:"Sehr wenig – aber Lachen ist gesund.",emoji:"😂"},
 {q:"¿Cuántos Liter Speichelfluss produziert ein Hund al día?",un:2,unit:"litros",hint:"Hunde speicheln deutlich mehr als Menschen.",emoji:"🐕"},
 {q:"¿Cuántos millones Bakterien sind auf der Zunge nach dem Aufwachen?",un:20,unit:"mil millones",hint:"Morgenatemluft riecht so schlimm wegen Bakterien.",emoji:"👅"},
 {q:"¿Cuántos Gramm Kot werden en einem Jahr Darmträgheit angesammelt?",un:3000,unit:"gramos",hint:"Chronische Verstopfung kann zu Ablagerungen führen.",emoji:"💩"},
 {q:"¿Cuántos Liter Blut filtert die Niere al día?",un:180,unit:"litros",hint:"Alle 30 Minuten das gesamte Blutvolumen.",emoji:"🫘"},
 {q:"¿Cuántos millones Keime überlebt ein Sponge ohne Reinigung?",un:54000,unit:"millones",hint:"54 mil millones – der schmutzigste Küchengegenstand.",emoji:"🫧"},
 {q:"¿Cuántos Gramm Eiter kann ein Furunkel enthalten?",un:5,unit:"gramos",hint:"Eiterpustel kann erstaunlich viel fassen.",emoji:"😨"},
 {q:"¿Cuántos Liter Flüssigkeit verliert man beim Marathon?",un:4,unit:"litros",hint:"Durch Schwitzen und Atmen.",emoji:"🏃"},
 {q:"¿Cuántos millones Parasiten hat die Weltbevölkerung gemeinsam?",un:1000,unit:"mil millones",hint:"Parasiten infizieren mil millones Menschen.",emoji:"🪱"},
 {q:"¿Cuántos Gramm Zahnfleisch-Bakterien produziert der Mund al día?",un:1,unit:"gramos",hint:"Dentalplaque-Bakterien.",emoji:"🦷"},
 {q:"¿Cuántos Liter Urin enthält eine Blase kurz vor dem Platzen?",un:1,unit:"litros",hint:"Schmerzhaft – Platzen ist nur theoretisch.",emoji:"💛"},
 {q:"¿Cuántos millones Spulwürmer-Eier können en einem Gemüsegarten sein?",un:10,unit:"millones",hint:"Hauptursache für Parasiteninfektionen.",emoji:"🥦"},
 {q:"¿Cuántos Gramm Hautzellen findet man en einem Staubsauger nach Monat?",un:100,unit:"gramos",hint:"Hauptanteil des Staubsaugerinhalts.",emoji:"🌀"},
 {q:"¿Cuántos Liter Körperflüssigkeiten werden al día verloren und ersetzt?",un:2.5,unit:"litros",hint:"Urin, Schweiß, Atem und Verdauung.",emoji:"💧"},
 {q:"¿Cuántos millones Pilze können auf einem ungepflegten Fuß leben?",un:100,unit:"millones",hint:"Fußpilz – oft unbemerkt.",emoji:"🦶"},
 {q:"¿Cuántos Gramm Körperfett enthält ein Liter menschlicher Muttermilch?",un:40,unit:"gramos",hint:"3,5-4,5% Fettgehalt.",emoji:"🤱"},
 {q:"¿Cuántos Liter Gesamtblut fließt al día durch die Leber?",un:1500,unit:"litros",hint:"Die Leber ist stark durchblutet.",emoji:"🟤"},
 {q:"¿Cuántos millones Coli-Bakterien sind en 1ml Abwasser?",un:100,unit:"millones",hint:"Roh-Abwasser enthält millones E.coli.",emoji:"💧"},
 {q:"¿Cuántos Gramm Gallenflüssigkeit produziert die Gallenblase al día?",un:800,unit:"ml",hint:"Galle al día.",emoji:"💛"},
 {q:"¿Cuántos Liter Blut enthält eine erwachsene Leber?",un:1.5,unit:"litros",hint:"25% des Herzschlagvolumens fließt zur Leber.",emoji:"🟤"},
 {q:"¿Cuántos millones Viren befinden sich en 1 Liter Luft en Innenräumen?",un:100,unit:"millones",hint:"Besonders en schlecht belüfteten Räumen.",emoji:"🦠"},
 {q:"¿Cuántos Gramm Körpersalz verliert man beim Sport por hora?",un:2,unit:"gramos",hint:"2g Natrium pro Liter Schweiß.",emoji:"🧂"},
 {q:"¿Cuántos Liter Flüssigkeit verliert ein Körper beim Sterben?",un:2,unit:"litros",hint:"Körper dehydriert stark am Ende.",emoji:"☠️"},
 {q:"¿Cuántos millones Bakterien sind en frischer Milch (unpasteurisiert)?",un:100,unit:"millones",hint:"Rohmilch enthält viele Keime.",emoji:"🥛"},
 {q:"¿Cuántos Gramm Bakterienmasse ist der gesunde Stuhl?",un:30,unit:"%",hint:"Des Stuhls sind Bakterien.",emoji:"💩"},
];