// 🐾 ANIMALES Y SEXO – Español
export default [
 {q:"¿Cuánto tiempo dauert der Sex bei Schlangen en Stunden?",un:24,unit:"horas",hint:"Schlangen können tage- und wochenlang paaren.",emoji:"🐍"},
 {q:"¿Cuántos cm lang ist der Penis einer Ente relativ zur Körperlänge?",un:40,unit:"cm",hint:"Stockenten haben spiralförmige Penisse.",emoji:"🦆"},
 {q:"¿Cuántos Hoden hat ein Stier?",un:2,unit:"Hoden",hint:"Wie die meisten Säugetiere.",emoji:"🐂"},
 {q:"¿Cuántos cm lang ist der Penis eines Blauwals?",un:270,unit:"cm",hint:"2,7 Meter – das größte Geschlechtsorgan im Tierreich.",emoji:"🐋"},
 {q:"¿Cuánto tiempo trägt eine Elefantendame ihr Junges en Tagen?",un:645,unit:"días",hint:"rápido 2 Jahre – längste Tragzeit auf Land.",emoji:"🐘"},
 {q:"¿Cuántos Mal paart sich ein Schimpanse mit verschiedenen Weibchen?",un:100,unit:"veces",hint:"Männliche Schimpansen paaren sich mit vielen Weibchen.",emoji:"🐒"},
 {q:"¿Cuántos Eier legt eine Königin-Biene en ihrem Leben?",un:2000000,unit:"Eier",hint:"2 millones über ihr Leben von 5 Jahren.",emoji:"🐝"},
 {q:"¿Cuánto tiempo es die Vagina einer Kuh en cm?",un:30,unit:"cm",hint:"Ähnlich lang wie der Arm eines Kindes.",emoji:"🐄"},
 {q:"¿Cuántos Spermien enthält ein Stier-Ejakulat?",un:7000000000,unit:"Spermien",hint:"7 mil millones – viel mehr als beim Menschen.",emoji:"🐂"},
 {q:"¿Cuánto tiempo dauert der Sex bei Giraffen en Sekunden?",un:2,unit:"segundos",hint:"Sehr schnell – aber häufig.",emoji:"🦒"},
 {q:"¿Cuántos Mal am Tag paart sich ein Löwe?",un:20,unit:"veces",hint:"en der Ranzzeit bis zu viele masculino al día.",emoji:"🦁"},
 {q:"¿Cuántos cm lang ist der Penis eines Gorillas?",un:4,unit:"cm",hint:"Trotz ihrer Größe sehr kleines Geschlechtsorgan.",emoji:"🦍"},
 {q:"¿Cuánto tiempo dauert der Geschlechtsakt bei Bonobos?",un:15,unit:"segundos",hint:"Sehr kurz – aber sehr häufig.",emoji:"🐒"},
 {q:"¿Cuántos Hoden hat ein Wal?",un:2,unit:"Hoden",hint:"Innen liegend – zum Schutz vor Kälte.",emoji:"🐋"},
 {q:"¿Cuánto tiempo trägt eine Hai-Art ihr Junges en Monaten?",un:24,unit:"meses",hint:"Hammerhaie tragen 2 Jahre.",emoji:"🦈"},
 {q:"¿Cuántos Meter lang ist der Penis eines Barnacle (Seepocke) relativ zur Körpergröße?",un:8,unit:"x Körperlänge",hint:"Relativ zur Körpergröße das längste Geschlechtsorgan.",emoji:"🦀"},
 {q:"¿Cuántos cm ist die Klitoris einer Hyäne lang?",un:18,unit:"cm",hint:"Weibliche Hyänen haben eine pseudopenis-ähnliche Klitoris.",emoji:"🦁"},
 {q:"Wie lang dauert die Paarung bei Nashörnern en Minuten?",un:30,unit:"minutos",hint:"Eine der längsten unter Landsäugern.",emoji:"🦏"},
 {q:"¿Cuántos Penisse haben Schlangen?",un:2,unit:"Hemipenis",hint:"Schlangen haben zwei Hemipenes.",emoji:"🐍"},
 {q:"¿Cuántos kg wiegt das Geschlechtsorgan eines Blauwals insgesamt?",un:1000,unit:"kg",hint:"Hoden 70kg, Penis 450kg.",emoji:"🐋"},
 {q:"¿Cuántos Stunden brütet ein männlicher Kaiserpinguin auf dem Ei?",un:1512,unit:"horas",hint:"63 Tage – ohne Nahrung im antarktischen Winter.",emoji:"🐧"},
 {q:"¿Cuántos Mal paart sich eine Drohnen-Biene en ihrem Leben?",un:1,unit:"veces",hint:"Danach stirbt die Drohne.",emoji:"🐝"},
 {q:"¿Cuánto tiempo dauert der Sex bei Haien en Stunden?",un:30,unit:"minutos",hint:"Minuten – mit Bissen als Vorzeichen.",emoji:"🦈"},
 {q:"¿Cuántos cm lang ist der Penis eines Schimpansen?",un:8,unit:"cm",hint:"Größer als beim Gorilla.",emoji:"🐒"},
 {q:"¿Cuántos Eier legt eine Riesenschildkröte pro Saison?",un:200,unit:"Eier",hint:"Mehrmals por año.",emoji:"🐢"},
 {q:"¿Cuánto tiempo paaren sich Feldheuschrecken am Stück?",un:12,unit:"horas",hint:"Manchmal tagelang verbunden.",emoji:"🦗"},
 {q:"¿Cuántos Zentimeter lang ist der Penis eines Pottwal?",un:240,unit:"cm",hint:"Zweitlängster Tierpenis nach dem Blauwal.",emoji:"🐳"},
 {q:"¿Cuánto tiempo trägt ein Hund sein Junges en Tagen?",un:63,unit:"días",hint:"Tage Tragezeit.",emoji:"🐕"},
 {q:"¿Cuántos Mal paart sich ein Löwen-Männchen mit einer Löwin en der Ranzzeit?",un:20,unit:"Mal/Tag",hint:"Bis zu viele masculino al día über mehrere Tage.",emoji:"🦁"},
 {q:"¿Cuántos Eier legt eine Schildkröte pro Gelege?",un:100,unit:"Eier",hint:"Je nach Art 50-200.",emoji:"🐢"},
 {q:"¿Cuánto tiempo dauert die Paarung bei Spinnen?",un:60,unit:"minutos",hint:"Manchmal bis zu mehreren Stunden.",emoji:"🕷️"},
 {q:"¿Cuántos cm lang ist die Vagina einer Pferdes?",un:60,unit:"cm",hint:"Stuten haben eine sehr lange Vagina.",emoji:"🐴"},
 {q:"¿Cuánto tiempo dauert die Trächtigkeit einer Katze en Wochen?",un:9,unit:"semanas",hint:"63-67 Tage.",emoji:"🐱"},
 {q:"¿Cuántos Weibchen befruchtet ein Stier por año en der Tierzucht?",un:50000,unit:"Weibchen",hint:"Durch künstliche Besamung.",emoji:"🐂"},
 {q:"¿Cuánto tiempo dauert die Trächtigkeit einer Maus en Tagen?",un:21,unit:"días",hint:"Drei Wochen – und kann sofort wieder trächtig werden.",emoji:"🐭"},
 {q:"¿Cuántos Junge wirft eine Maus por año?",un:70,unit:"Jungtiere",hint:"5-10 Würfe à 5-10 Jungen.",emoji:"🐭"},
 {q:"¿Cuántos Mal können Kaninchen en einer Stunde paaren?",un:10,unit:"veces",hint:"'Schnell wie Kaninchen' – wörtlich gemeint.",emoji:"🐇"},
 {q:"¿Cuánto tiempo es der Geschlechtsakt bei Hunden en Minuten?",un:20,unit:"minutos",hint:"'Tie' – sie stecken zusammen.",emoji:"🐕"},
 {q:"¿Cuántos Eier legt ein Oktopus-Weibchen?",un:400000,unit:"Eier",hint:"400.000 Eier und bewacht sie bis zum Tod.",emoji:"🐙"},
 {q:"¿Cuántos cm lang ist der Penis eines Elefanten?",un:180,unit:"cm",hint:"1,8 Meter – S-förmig und muskelstark.",emoji:"🐘"},
 {q:"¿Cuánto tiempo paaren sich Wale en Stunden?",un:18,unit:"minutos",hint:"20 Minuten – im Meer.",emoji:"🐋"},
 {q:"¿Cuántos Ovulation por año hat eine Katze?",un:4,unit:"veces",hint:"Katzen sind saisonale Mehrfachläufer.",emoji:"🐱"},
 {q:"¿Cuántos Junge kann ein Opossum gleichzeitig tragen?",un:20,unit:"Junge",hint:"Im Beutel – alle gleichzeitig.",emoji:"🐀"},
 {q:"¿Cuánto tiempo trägt ein Elefant sein Junges en Monaten?",un:21,unit:"meses",hint:"rápido 2 Jahre.",emoji:"🐘"},
 {q:"¿Cuántos Eier legt eine Königin-Termite por día?",un:30000,unit:"Eier",hint:"Die produktivste Mutter im Insektenreich.",emoji:"🐜"},
 {q:"¿Cuántos cm lang ist der Penis eines Delfins?",un:38,unit:"cm",hint:"Delfine haben prehensile Penisse.",emoji:"🐬"},
 {q:"¿Cuánto tiempo dauert die Paarung von Flusspferden en Minuten?",un:10,unit:"minutos",hint:"Im Wasser.",emoji:"🦛"},
 {q:"¿Cuántos Junge hat ein Wombat por año?",un:1,unit:"Junges",hint:"Nur ein Junges – sehr langsame Fortpflanzung.",emoji:"🐨"},
 {q:"¿Cuánto tiempo paaren sich Pferde en Minuten?",un:1,unit:"minuto",hint:"Kurz aber intensiv.",emoji:"🐴"},
 {q:"¿Cuántos Weibchen besucht ein Gorilla-Silberrücken?",un:10,unit:"Weibchen",hint:"Ein Silberrücken führt eine Gruppe.",emoji:"🦍"},
 {q:"¿Cuánto tiempo trägt ein Känguru sein Junges im Beutel en Monaten?",un:9,unit:"meses",hint:"Erst 1cm groß bei Geburt – dann im Beutel.",emoji:"🦘"},
 {q:"¿Cuántos cm lang ist der Penis eines Schimpansen?",un:8,unit:"cm",hint:"Obwohl viel kleiner als Menschen denken.",emoji:"🐒"},
 {q:"¿Cuánto tiempo paaren sich Bienen?",un:0.01,unit:"segundos",hint:"Nur eine Sekunde – die Drohne stirbt danach.",emoji:"🐝"},
 {q:"¿Cuántos Eier legt ein Schmetterlings-Weibchen insgesamt?",un:200,unit:"Eier",hint:"Meist Hunderte verteilt auf viele Pflanzen.",emoji:"🦋"},
 {q:"¿Cuántos cm lang ist der Penis einer Seekuh (Manatee)?",un:70,unit:"cm",hint:"Auch Seekühe haben beeindruckende Organe.",emoji:"🐟"},
 {q:"¿Cuánto tiempo dauert die Trächtigkeit eines Pottwal en Monaten?",un:16,unit:"meses",hint:"rápido 1,5 Jahre.",emoji:"🐳"},
 {q:"¿Cuántos Junge wirft eine Katze pro Wurf?",un:5,unit:"Junge",hint:"en promedio 3-7 Kätzchen.",emoji:"🐱"},
 {q:"¿Cuántos masculino paart sich eine Königin-Ameise en ihrem Leben?",un:1,unit:"veces",hint:"Einmal – dann lagert sie Spermien für Jahre.",emoji:"🐜"},
 {q:"¿Cuántos cm lang ist der Penis einer Maus?",un:1.5,unit:"cm",hint:"Relativ zu ihrem Körper sehr groß.",emoji:"🐭"},
 {q:"¿Cuánto tiempo paaren sich Grizzlybären?",un:30,unit:"minutos",hint:"Der Akt dauert bis zu 30 Minuten.",emoji:"🐻"},
 {q:"¿Cuántos Eier legt eine Flussbarsch-Weibchen?",un:300000,unit:"Eier",hint:"Fische legen enorme Eiermengen.",emoji:"🐟"},
 {q:"¿Cuántos cm ist die Klitoris einer Weibchen-Fossa (Madagaskar)?",un:7,unit:"cm",hint:"Die Fossa hat einen außergewöhnlich langen Klitoris.",emoji:"🦁"},
 {q:"¿Cuánto tiempo dauert der Hochzeitsflug einer Bienenkönigin?",un:1,unit:"Stunde",hint:"Sie paart sich en der Luft mit 12-20 Drohnen.",emoji:"🐝"},
 {q:"¿Cuántos Tage ist eine Hündin im Jahr läufig?",un:18,unit:"días",hint:"Zweimal im Jahr je 9 Tage.",emoji:"🐕"},
 {q:"¿Cuántos cm lang ist der Penis eines Nilpferds?",un:50,unit:"cm",hint:"Nilpferde spritzen Urin zur Territorialmarkierung.",emoji:"🦛"},
 {q:"¿Cuánto tiempo paaren sich Pandas?",un:3,unit:"minutos",hint:"Sehr kurz – und sehr selten.",emoji:"🐼"},
 {q:"¿Cuántos Junge hat ein Schwein pro Wurf?",un:10,unit:"Ferkel",hint:"8-14 Ferkel pro Wurf.",emoji:"🐷"},
 {q:"¿Cuántos Eier legt eine Meeresschildkröte pro Saison insgesamt?",un:600,unit:"Eier",hint:"3-7 Gelege à 80-120 Eier.",emoji:"🐢"},
 {q:"¿Cuántos cm lang ist der Penis eines Seelöwen?",un:40,unit:"cm",hint:"Pinnipeds haben sehr lange Penisse.",emoji:"🦭"},
 {q:"¿Cuánto tiempo dauert die Trächtigkeit eines Schimpansen en Tagen?",un:243,unit:"días",hint:"Ähnlich wie beim Menschen.",emoji:"🐒"},
 {q:"¿Cuántos Weibchen befruchtet ein Alpha-Wolf im Jahr?",un:1,unit:"Weibchen",hint:"Wölfe sind weitgehend monogam.",emoji:"🐺"},
 {q:"¿Cuántos cm lang ist der Penis eines Walrosses?",un:63,unit:"cm",hint:"Walrosse haben auch einen Baculum (Penisknochen).",emoji:"🦭"},
 {q:"¿Cuánto tiempo dauert die Paarung bei Krokodilen en Minuten?",un:10,unit:"minutos",hint:"Im Wasser.",emoji:"🐊"},
 {q:"¿Cuántos Junge hat ein Polarfuchs pro Wurf?",un:8,unit:"Junge",hint:"Bis zu 14 Junge.",emoji:"🦊"},
 {q:"¿Cuántos Eier legt eine Hummel-Königin pro Sommer?",un:200,unit:"Eier",hint:"Nur eine Saison.",emoji:"🐝"},
 {q:"¿Cuánto tiempo es der Penisknochen (Baculum) eines Eisbären en cm?",un:22,unit:"cm",hint:"Säugetiere mit Baculum haben keinen Erektions-Mechanismus.",emoji:"🐻‍❄️"},
 {q:"¿Cuántos Mal por día paart sich ein Kaninchen?",un:10,unit:"veces",hint:"'Sich fortpflanzen wie Kaninchen' ist kein Mythos.",emoji:"🐇"},
 {q:"¿Cuánto tiempo trägt eine Hündin en Wochen?",un:9,unit:"semanas",hint:"63 Tage.",emoji:"🐕"},
 {q:"¿Cuántos Eier legt eine Kohlmeise pro Gelege?",un:10,unit:"Eier",hint:"Bis zu 15 Eier pro Brut.",emoji:"🐦"},
 {q:"¿Cuántos cm lang ist der Penisknochen eines Waschbären?",un:10,unit:"cm",hint:"Waschbären haben einen des größten Bacula relativ zum Körper.",emoji:"🦝"},
 {q:"¿Cuántos Stunden dauert die Paarung von Schnecken?",un:6,unit:"horas",hint:"Schnecken sind Hermaphroditen.",emoji:"🐌"},
 {q:"¿Cuántos Gramm wiegt ein Gorilla-Hoden?",un:30,unit:"gramos",hint:"Im Vergleich zum Körper sehr klein.",emoji:"🦍"},
 {q:"¿Cuántos Eier legt eine Seidenspinne pro Kokon?",un:400,unit:"Eier",hint:"Alle im selben Seidensack.",emoji:"🕷️"},
 {q:"¿Cuánto tiempo paaren sich Fliegen en Minuten?",un:20,unit:"minutos",hint:"Stubenfliegen paaren sich relativ lange.",emoji:"🪰"},
 {q:"¿Cuántos cm lang ist der Penis eines Schwertwals (Orca)?",un:180,unit:"cm",hint:"1,8 Meter – einfahrbarer Penis.",emoji:"🐋"},
 {q:"¿Cuántos Junge hat ein Leopard pro Wurf?",un:2,unit:"Junge",hint:"1-4, meist 2-3 Jungtiere.",emoji:"🐆"},
 {q:"¿Cuánto tiempo dauert die Trächtigkeit einer Tigerin en Tagen?",un:103,unit:"días",hint:"Knapp 3,5 Monate.",emoji:"🐯"},
 {q:"¿Cuánto tiempo es der Penis eines Wiedehopfs relativ zum Körper?",un:50,unit:"% Körperlänge",hint:"Sehr lang relativ zum Vogelkörper.",emoji:"🐦"},
 {q:"¿Cuántos cm lang ist der Eileiter einer Kuh?",un:25,unit:"cm",hint:"Verbindet Ovar mit Gebärmutter.",emoji:"🐄"},
 {q:"¿Cuánto tiempo dauert die Paarung von Albatrosse en Stunden?",un:1,unit:"Stunde",hint:"Albatrosse sind monogam und zeremoniell.",emoji:"🦅"},
 {q:"¿Cuántos Junge hat eine Fledermaus por año?",un:1,unit:"Junges",hint:"Meist nur ein Jungtier.",emoji:"🦇"},
 {q:"Wie lang paaren sich Löwen bei jedem Akt en Sekunden?",un:30,unit:"segundos",hint:"Kurz aber häufig – bis zu 20x al día.",emoji:"🦁"},
 {q:"¿Cuántos cm hat der Penisknochen eines Eichhörnchens?",un:2,unit:"cm",hint:"Klein aber funktional.",emoji:"🐿️"},
 {q:"¿Cuánto tiempo dauert die Paarung von Schlangen en Stunden?",un:6,unit:"horas",hint:"Manchmal tage- und wochenlang.",emoji:"🐍"},
 {q:"¿Cuántos Eier legt eine Ameisen-Königin al día?",un:800,unit:"Eier",hint:"Über ihr gesamtes Leben millones.",emoji:"🐜"},
 {q:"¿Cuántos cm lang ist der Penis eines Orang-Utans?",un:4,unit:"cm",hint:"Ähnlich klein wie Gorillas.",emoji:"🦧"},
 {q:"¿Cuánto tiempo dauert die Trächtigkeit eines Hamsters en Tagen?",un:16,unit:"días",hint:"Kürzeste Tragzeit der Säugetiere.",emoji:"🐹"},
 {q:"¿Cuántos Junge hat eine Ratte pro Wurf?",un:8,unit:"Junge",hint:"5-12 – bis zu 8 Würfe por año.",emoji:"🐀"},
 {q:"¿Cuánto tiempo es der Penis eines Hausschweins en cm?",un:50,unit:"cm",hint:"Korkenzieherförmig.",emoji:"🐷"},
 {q:"¿Cuántos Eier legt eine Spinne insgesamt en ihrem Leben?",un:3000,unit:"Eier",hint:"Je nach Art hunderte bis tausende.",emoji:"🕷️"},
 {q:"¿Cuánto tiempo paaren sich Hunde beim 'Tie' en Minuten?",un:20,unit:"minutos",hint:"Anschwellung hält sie zusammen.",emoji:"🐕"},
 {q:"¿Cuántos cm lang ist der Uterus einer Katze?",un:10,unit:"cm",hint:"Zweizipfelig – kann verschiedene Väter tragen.",emoji:"🐱"},
 {q:"¿Cuánto tiempo trägt eine Giraffe ihr Junges en Monaten?",un:15,unit:"meses",hint:"Das Jungtier fällt 2m auf den Boden.",emoji:"🦒"},
 {q:"¿Cuántos Junge hat ein Gepard pro Wurf?",un:3,unit:"Junge",hint:"1-8 – meist 3-5.",emoji:"🐆"},
 {q:"¿Cuánto tiempo paaren sich Delfine?",un:12,unit:"segundos",hint:"Sehr kurz – dafür häufiger.",emoji:"🐬"},
 {q:"¿Cuántos Eier legt ein Frosch pro Saison?",un:2000,unit:"Eier",hint:"Frösche legen Tausende kleiner Eier.",emoji:"🐸"},
 {q:"¿Cuántos cm lang ist der Penisknochen eines Eisbären?",un:22,unit:"cm",hint:"Eines der längsten Bacula relativ zur Körpergröße.",emoji:"🐻‍❄️"},
 {q:"¿Cuánto tiempo dauert die Trächtigkeit eines Gorillas en Tagen?",un:257,unit:"días",hint:"Ähnlich wie beim Menschen.",emoji:"🦍"},
 {q:"¿Cuánto tiempo es die Vagina einer Stute en cm?",un:60,unit:"cm",hint:"Sehr lang – Geburt dauert kurz.",emoji:"🐴"},
 {q:"¿Cuántos Junge hat eine Löwin pro Wurf?",un:3,unit:"Junge",hint:"1-4, meist 2-3.",emoji:"🦁"},
 {q:"¿Cuánto tiempo paaren sich Tigerfrösche?",un:2,unit:"días",hint:"Amplexus – Umarmung kann Tage dauern.",emoji:"🐸"},
 {q:"¿Cuántos Eier legt eine Wespenkönig pro Sommer?",un:300,unit:"Eier",hint:"Arbeiterinnen bauen das Nest für sie.",emoji:"🐝"},
 {q:"¿Cuánto tiempo trägt ein Kaninchen sein Junges en Tagen?",un:31,unit:"días",hint:"Sehr kurze Tragzeit.",emoji:"🐇"},
 {q:"¿Cuántos Junge hat ein Polarfuchs maximal pro Wurf?",un:14,unit:"Junge",hint:"Bei guter Lemmingversorgung.",emoji:"🦊"},
 {q:"¿Cuántos cm lang ist der Penis eines Tapirs?",un:60,unit:"cm",hint:"Tapire haben einen Greif-Penis.",emoji:"🦏"},
 {q:"¿Cuánto tiempo paaren sich Marder?",un:2,unit:"horas",hint:"Mehrere Stunden – lange Paarung.",emoji:"🦦"},
 {q:"¿Cuántos Eier legt eine Seidenraupe?",un:500,unit:"Eier",hint:"Pro Weibchen im Leben.",emoji:"🪱"},
 {q:"¿Cuánto tiempo es der Penisknochen eines Bibers?",un:5,unit:"cm",hint:"Biber haben einen Baculum.",emoji:"🦦"},
 {q:"¿Cuánto tiempo trägt eine Stute ihr Junges en Tagen?",un:340,unit:"días",hint:"Ca. 11 Monate.",emoji:"🐴"},
 {q:"¿Cuántos Junge hat eine Hyäne pro Wurf?",un:2,unit:"Junge",hint:"Manchmal 1-3.",emoji:"🐈"},
 {q:"¿Cuánto tiempo es der Penis eines Flussdelphins?",un:40,unit:"cm",hint:"Amazonas-Delphin.",emoji:"🐬"},
 {q:"¿Cuánto tiempo paaren sich Schildkröten en Stunden?",un:3,unit:"horas",hint:"Sehr ausdauernd.",emoji:"🐢"},
 {q:"¿Cuántos Eier legt eine Schimpansen-Weibchen im Leben?",un:5,unit:"Junge",hint:"Schimpansen haben wenige Nachkommen.",emoji:"🐒"},
 {q:"¿Cuánto tiempo es der Uterus einer Stute?",un:45,unit:"cm",hint:"Groß genug für das Fohlen.",emoji:"🐴"},
 {q:"¿Cuántos Junge hat ein Wildschwein pro Wurf?",un:6,unit:"Frischlinge",hint:"4-8 – je nach Nahrungsangebot.",emoji:"🐗"},
 {q:"¿Cuánto tiempo es der Penis eines Zwergschimpansen (Bonobo)?",un:10,unit:"cm",hint:"Größer als Gorilla, kleiner als Mensch.",emoji:"🐒"},
 {q:"¿Cuántos Eier legt eine Forelle pro Laichsaison?",un:2000,unit:"Eier",hint:"Je nach Größe bis 10.000.",emoji:"🐟"},
 {q:"¿Cuánto tiempo trägt ein Löwe sein Junges en Tagen?",un:110,unit:"días",hint:"Löwen führen Einzel-Würfe.",emoji:"🦁"},
 {q:"¿Cuántos Junge hat ein Erdferkel por año?",un:1,unit:"Junges",hint:"Nur ein Jungtier pro Saison.",emoji:"🐷"},
 {q:"¿Cuánto tiempo es die Vagina einer Gorilla en cm?",un:9,unit:"cm",hint:"Proportional kleiner als beim Menschen.",emoji:"🦍"},
 {q:"¿Cuánto tiempo paaren sich Polarfüchse?",un:20,unit:"minutos",hint:"en der kurzen arktischen Paarungszeit.",emoji:"🦊"},
 {q:"¿Cuántos Eier legt ein Oktopus insgesamt?",un:100000,unit:"Eier",hint:"Und bewacht sie bis sie schlüpfen – dann stirbt sie.",emoji:"🐙"},
 {q:"¿Cuánto tiempo es der Penisknochen eines Hundes (Baculum)?",un:10,unit:"cm",hint:"Hunde haben einen Penisknochen.",emoji:"🐕"},
 {q:"¿Cuántos Junge hat ein Leopard im Leben?",un:8,unit:"Junge",hint:"Alle 2 Jahre ein Wurf über 16 Jahre.",emoji:"🐆"},
 {q:"¿Cuánto tiempo es die Klitoris einer Weibchen-Binturong?",un:5,unit:"cm",hint:"Binturongs sind bekannt für diese Eigenschaft.",emoji:"🐱"},
 {q:"¿Cuánto tiempo trägt eine Ratte ihr Junges en Tagen?",un:22,unit:"días",hint:"Sehr kurze Tragzeit.",emoji:"🐀"},
 {q:"¿Cuántos Eier legt eine Schmetterlingsgattung al día?",un:20,unit:"Eier",hint:"Über ihr ganzes Leben meist 200.",emoji:"🦋"},
 {q:"¿Cuánto tiempo es der Rüssel eines Elefanten – auch als Sinnesorgan beim Paaren?",un:200,unit:"cm",hint:"Elefanten berühren sich beim Paaren mit dem Rüssel.",emoji:"🐘"},
 {q:"¿Cuántos Junge hat ein Waschbär pro Wurf?",un:4,unit:"Junge",hint:"3-5 Junge im Frühling.",emoji:"🦝"},
 {q:"¿Cuánto tiempo paaren sich Löffelenten?",un:2,unit:"minutos",hint:"Enten paaren sich oft mit Gewalt.",emoji:"🦆"},
 {q:"¿Cuánto tiempo es der Penis eines Bullen en cm?",un:90,unit:"cm",hint:"Retraktormuskel ermöglicht S-förmige Lagerung.",emoji:"🐂"},
 {q:"¿Cuántos Eier legt eine Stubenfliege en ihrem kurzen Leben?",un:500,unit:"Eier",hint:"en Gruppen von 75-150 Stück.",emoji:"🪰"},
 {q:"¿Cuántos Tage ist eine Stute im Jahr rossig?",un:15,unit:"días",hint:"Mehrmals im Sommer.",emoji:"🐴"},
 {q:"¿Cuánto tiempo es der Uterus einer Hauskatze en cm?",un:8,unit:"cm",hint:"Zweihörnig – kann verschiedene Väter haben.",emoji:"🐱"},
 {q:"¿Cuántos Junge hat ein Opossum gleichzeitig im Beutel?",un:13,unit:"Junge",hint:"Zitzen – so viele Junge können überleben.",emoji:"🐀"},
 {q:"¿Cuánto tiempo dauert die Paarung von Orcas?",un:5,unit:"minutos",hint:"Im Wasser – sehr selten beobachtet.",emoji:"🐋"},
 {q:"¿Cuánto tiempo es der Gebärmutterhals einer Kuh?",un:10,unit:"cm",hint:"Wichtig für künstliche Besamung.",emoji:"🐄"},
 {q:"¿Cuántos Junge hat eine Fischotter pro Wurf?",un:3,unit:"Junge",hint:"1-5, meist 3.",emoji:"🦦"},
 {q:"¿Cuánto tiempo paaren sich Geparden?",un:10,unit:"minutos",hint:"Mehrmals al día en der Paarungszeit.",emoji:"🐆"},
 {q:"¿Cuántos Eier legt eine Gottesanbeterin nach der Paarung?",un:200,unit:"Eier",hint:"en einem Oothek-Kokon.",emoji:"🦗"},
 {q:"¿Cuánto tiempo es der Penisknochen einer Robbe (Baculum) en cm?",un:35,unit:"cm",hint:"Robbenmänner haben sehr lange Bacula.",emoji:"🦭"},
 {q:"¿Cuánto tiempo trägt eine Kojote ihr Junges en Tagen?",un:63,unit:"días",hint:"Gleich wie Hunde.",emoji:"🐺"},
 {q:"¿Cuántos Junge hat ein Nashorn pro Wurf?",un:1,unit:"Junges",hint:"Immer Einzelgeburten.",emoji:"🦏"},
 {q:"¿Cuánto tiempo es der Baculum (Penisknochen) eines Waschbären en cm?",un:10,unit:"cm",hint:"Relativ zur Körpergröße sehr lang.",emoji:"🦝"},
 {q:"¿Cuántos Eier legt ein Walhai pro Saison?",un:300,unit:"Eier",hint:"Walhaie sind lebendgebärend – aber legen Eier vor der Geburt.",emoji:"🦈"},
 {q:"¿Cuánto tiempo paaren sich Hauskatzen?",un:5,unit:"minutos",hint:"Mehrmals al día – sehr laut.",emoji:"🐱"},
 {q:"¿Cuánto tiempo es der Uterus einer Stute en cm?",un:50,unit:"cm",hint:"Groß genug für ein Fohlen.",emoji:"🐴"},
 {q:"¿Cuántos Junge hat ein Hermelin pro Wurf?",un:6,unit:"Junge",hint:"4-9 Junge.",emoji:"🦦"},
 {q:"¿Cuántos Eier legt eine Zauneidechse pro Saison?",un:8,unit:"Eier",hint:"6-12 Eier.",emoji:"🦎"},
 {q:"¿Cuánto tiempo es die Vagina eines Gorilla-Weibchens?",un:9,unit:"cm",hint:"Ähnlich wie beim Menschen.",emoji:"🦍"},
 {q:"¿Cuánto tiempo dauert die Trächtigkeit eines Schafes en Tagen?",un:147,unit:"días",hint:"Etwa 5 Monate.",emoji:"🐑"},
 {q:"¿Cuántos Junge hat ein Eisbär pro Wurf?",un:2,unit:"Junge",hint:"rápido immer Zwillinge.",emoji:"🐻‍❄️"},
 {q:"¿Cuánto tiempo es der Penis eines Hauskatze (Kater)?",un:1.5,unit:"cm",hint:"Sehr klein mit stacheligen Widerhaken.",emoji:"🐱"},
 {q:"¿Cuánto tiempo paaren sich Wildschweine?",un:5,unit:"minutos",hint:"Schnell aber häufig.",emoji:"🐗"},
 {q:"¿Cuántos Eier legt eine Hornisse pro Sommer?",un:500,unit:"Eier",hint:"Die Königin allein.",emoji:"🐝"},
 {q:"¿Cuánto tiempo es der Uterus einer Menschenaffen-Weibchen?",un:8,unit:"cm",hint:"Ähnlich wie bei uns.",emoji:"🦍"},
 {q:"¿Cuántos Junge hat ein Braunbär pro Wurf?",un:2,unit:"Junge",hint:"1-4, meist 2.",emoji:"🐻"},
 {q:"¿Cuánto tiempo trägt eine Katze ihr Junges en Wochen?",un:9,unit:"semanas",hint:"63-67 Tage.",emoji:"🐱"},
];