// 🧪 CIENCIA – Español
export default [
 {q:"¿En qué año wurde das mundo Wide Web erfunden?",un:1989,unit:"Jahr",hint:"Tim Berners-Lee entwickelte es am CERN.",emoji:"🌐"},
 {q:"¿Cuántos Elemente hat das Periodensystem?",un:118,unit:"Elemente",hint:"Das schwerste bestätigte Element ist Oganesson.",emoji:"⚗️"},
 {q:"¿En qué año entdeckte Fleming Penicillin?",un:1928,unit:"Jahr",hint:"Er vergaß eine Petrischale – und rettete millones Leben.",emoji:"💊"},
 {q:"¿Cuántos km/s ist die Lichtgeschwindigkeit?",un:299792,unit:"km/s",hint:"Die schnellste bekannte Geschwindigkeit im Universum.",emoji:"💡"},
 {q:"¿En qué año erfand Morse den Telegraf?",un:1837,unit:"Jahr",hint:"Das erste elektrische Kommunikationsmittel.",emoji:"📡"},
 {q:"¿Cuántos Grad Celsius ist der absolute Nullpunkt?",un:-273.15,unit:"°C",hint:"Null Kelvin – keine thermische Bewegung mehr.",emoji:"🌡️"},
 {q:"¿En qué año erschien Darwins 'On el Origin de Species'?",un:1859,unit:"Jahr",hint:"Die Evolutionstheorie erschütterte die Welt.",emoji:"🐒"},
 {q:"¿Cuántos Nanometer klein ist ein durchschnittliches Virus?",un:100,unit:"nanometers",hint:"1000x kleiner als eine Zelle.",emoji:"🦠"},
 {q:"¿En qué año erfand Edison die Glühbirne?",un:1879,unit:"Jahr",hint:"Am 22. Oktober 1879 – nach tausend Versuchen.",emoji:"💡"},
 {q:"¿Cuántos mil millones Neuronen hat das menschliche Gehirn?",un:86,unit:"mil millones",hint:"Mit Billionen von Synapsen.",emoji:"🧠"},
 {q:"¿En qué año entdeckte Einstein die Spezielle Relativitätstheorie?",un:1905,unit:"Jahr",hint:"Das Annus Mirabilis – Einsteins Wunderjahr.",emoji:"⚛️"},
 {q:"¿Cuántos Grad dreht sich die Erde al día um ihre Achse?",un:360,unit:"Grad",hint:"Einmal herum en 24 Stunden.",emoji:"🌍"},
 {q:"¿En qué año erfand Gutenberg den Buchdruck?",un:1440,unit:"Jahr",hint:"Mit beweglichen Lettern.",emoji:"📚"},
 {q:"¿Cuántos Atommassen hat Kohlenstoff?",un:12,unit:"amu",hint:"Kohlenstoff-12 ist der Standard.",emoji:"⚗️"},
 {q:"¿En qué año startete die erste Rakete ins All (V2)?",un:1942,unit:"Jahr",hint:"Von Wernher von Braun entwickelt.",emoji:"🚀"},
 {q:"¿Cuántos Grad Fahrenheit entsprechen 100°C?",un:212,unit:"°F",hint:"Siedepunkt des Wassers.",emoji:"🌡️"},
 {q:"¿En qué año erfand Baird das Fernsehen?",un:1926,unit:"Jahr",hint:"John Logie Baird demonstrierte es 1926.",emoji:"📺"},
 {q:"¿Cuántos Protonen hat Gold (Ordnungszahl)?",un:79,unit:"Protonen",hint:"Au mit Ordnungszahl 79.",emoji:"🪙"},
 {q:"¿En qué año entdeckte Curie das Radium?",un:1898,unit:"Jahr",hint:"Marie und Pierre Curie zusammen.",emoji:"☢️"},
 {q:"¿Cuántos km beträgt der Erdumfang am Äquator?",un:40075,unit:"km",hint:"Eratosthenes berechnete es bereits 240 v.Chr.",emoji:"🌍"},
 {q:"¿En qué año erfand Bell das Telefon?",un:1876,unit:"Jahr",hint:"Am 10. März 1876 – erster Satz: 'Mr. Watson, come here'.",emoji:"📞"},
 {q:"¿Cuántos Elektronen hat Sauerstoff?",un:8,unit:"Elektronen",hint:"Ordnungszahl 8 – auch 8 Protonen.",emoji:"⚗️"},
 {q:"¿En qué año wurde das erste Antibiotikum (Penicillin) klinisch eingesetzt?",un:1942,unit:"Jahr",hint:"Im Zweiten Weltkrieg gerettet millones.",emoji:"💊"},
 {q:"¿Cuántos m/s² ist die Erdbeschleunigung?",un:9.81,unit:"m/s²",hint:"g = 9,81 m/s² – Grundlage der Physik.",emoji:"⬇️"},
 {q:"¿En qué año erfand Marconi das Radio?",un:1895,unit:"Jahr",hint:"Erste drahtlose Übertragung.",emoji:"📻"},
 {q:"¿Cuántos Grad hat ein rechter Winkel?",un:90,unit:"Grad",hint:"Definition des rechten Winkels.",emoji:"📐"},
 {q:"¿En qué año entdeckte Röntgen die Röntgenstrahlen?",un:1895,unit:"Jahr",hint:"Am 8. November 1895 zufällig entdeckt.",emoji:"🩻"},
 {q:"¿Cuántos Bit hat ein Byte?",un:8,unit:"Bit",hint:"Bit = 1 Byte – Basis der Informatik.",emoji:"💻"},
 {q:"¿En qué año erfand Diesel den Dieselmotor?",un:1897,unit:"Jahr",hint:"Rudolf Diesel erhielt 1897 das Patent.",emoji:"🔧"},
 {q:"¿Cuántos Protonen hat Eisen?",un:26,unit:"Protonen",hint:"Fe – Ordnungszahl 26.",emoji:"⚗️"},
 {q:"¿En qué año wurde der erste Laser gebaut?",un:1960,unit:"Jahr",hint:"Theodore Maiman baute ihn am 16. Mai 1960.",emoji:"💡"},
 {q:"¿Cuántos Kalorie hat 1 Gramm Fett?",un:9,unit:"kcal/g",hint:"Fett hat mehr als doppelt so viel wie Kohlenhydrate.",emoji:"🔥"},
 {q:"¿En qué año erfand Nobel das Dynamit?",un:1867,unit:"Jahr",hint:"Aus Nitroglycerin stabilisiert.",emoji:"💣"},
 {q:"¿Cuántos Chromosomenpaare hat un humano?",un:23,unit:"Paare",hint:"46 Chromosomen insgesamt.",emoji:"🧬"},
 {q:"¿En qué año erschien das erste Computermodell (ENIAC)?",un:1945,unit:"Jahr",hint:"Electronic Numerical Integrator y Computer.",emoji:"💻"},
 {q:"¿Cuántos Protonen hat Helium?",un:2,unit:"Protonen",hint:"Das zweitlichteste Element nach Wasserstoff.",emoji:"⚗️"},
 {q:"¿En qué año entdeckte Watson und Crick die DNA-Doppelhelix?",un:1953,unit:"Jahr",hint:"Mit Rosalind Franklins entscheidenden Daten.",emoji:"🧬"},
 {q:"¿Cuántos Grad Celsius siedet Alkohol (Ethanol)?",un:78.4,unit:"°C",hint:"Destillation nutzt diesen Siedepunkt.",emoji:"🌡️"},
 {q:"¿En qué año erfand Watt die verbesserte Dampfmaschine?",un:1769,unit:"Jahr",hint:"Revolutionierte die Industrialisierung.",emoji:"⚙️"},
 {q:"¿Cuántos Atome hat ein Mol Materie?",un:602000000000000000000000,unit:"Atome",hint:"6,02 × 10²³ – die Avogadro-Zahl.",emoji:"⚗️"},
 {q:"¿En qué año wurde das erste Mikroskop erfunden?",un:1590,unit:"Jahr",hint:"Zacharias Janssen en den Niederlanden.",emoji:"🔬"},
 {q:"¿Cuántos Protonen hat Uran?",un:92,unit:"Protonen",hint:"Das schwerste natürlich vorkommende Element.",emoji:"☢️"},
 {q:"¿En qué año erfand Archimedes sein berühmtes Prinzip?",un:250,unit:"v.Chr.",hint:"Im Bad – Heureka!",emoji:"🛁"},
 {q:"¿Cuántos Kalorien braucht das Gehirn al día?",un:300,unit:"kcal",hint:"20% des gesamten Energieverbrauchs.",emoji:"🧠"},
 {q:"¿En qué año entdeckte Pasteur die Gärung durch Mikroorganismen?",un:1857,unit:"Jahr",hint:"Grundlage für Lebensmittelsicherheit.",emoji:"🧫"},
 {q:"¿Cuántos Elektronen braucht Kohlenstoff für ein stabiles Außenorbital?",un:4,unit:"Elektronen",hint:"Kohlenstoff hat 4 Valenzelektronen.",emoji:"⚗️"},
 {q:"¿En qué año wurde das erste Impfmittel entwickelt (Pocken)?",un:1796,unit:"Jahr",hint:"Edward Jenner impfte mit Kuhpockenvirus.",emoji:"💉"},
 {q:"¿Cuántos Hz hört un humano maximal?",un:20000,unit:"Hz",hint:"20 kHz – abnimmt mit dem Alter.",emoji:"👂"},
 {q:"¿En qué año erfand Babbage den mechanischen Computer?",un:1837,unit:"Jahr",hint:"Die Analytical Engine – nicht fertiggestellt.",emoji:"⚙️"},
 {q:"¿Cuántos Grad Celsius beträgt der Siedepunkt von Stickstoff?",un:-196,unit:"°C",hint:"Flüssiger Stickstoff für Kryonik.",emoji:"🌡️"},
 {q:"¿En qué año entdeckte Hubble, dass das Universum expandiert?",un:1929,unit:"Jahr",hint:"Das Hubble-Gesetz der kosmischen Expansion.",emoji:"🌌"},
 {q:"¿Cuántos Kilowattstunden Energie hat 1 kg Uran?",un:24000,unit:"kWh",hint:"Entspricht 3 Tonnen Kohle.",emoji:"⚡"},
 {q:"¿En qué año erfand Faraday das Prinzip der elektromagnetischen Induktion?",un:1831,unit:"Jahr",hint:"Grundlage für alle Elektromotoren und Generatoren.",emoji:"⚡"},
 {q:"¿Cuántos Seiten hat die DNA der menschlichen Zelle wenn ausgerollt?",un:2,unit:"metros",hint:"Meter DNA en jedem Zellkern.",emoji:"🧬"},
 {q:"¿En qué año wurde das erste Teleskop gebaut?",un:1608,unit:"Jahr",hint:"Hans Lippershey beantragte das Patent.",emoji:"🔭"},
 {q:"¿Cuántos Nanometer klein ist ein DNA-Strang im Durchmesser?",un:2,unit:"nanometers",hint:"Nm – unvorstellbar klein.",emoji:"🧬"},
 {q:"¿En qué año erfand Braun die Elektronenröhre (Braunsche Röhre)?",un:1897,unit:"Jahr",hint:"Grundlage für alle frühen Bildschirme.",emoji:"📺"},
 {q:"¿Cuántos Watt verbraucht das menschliche Gehirn?",un:20,unit:"vatios",hint:"Wie eine Energiesparbirne.",emoji:"💡"},
 {q:"¿En qué año entdeckte Harvey den Blutkreislauf?",un:1628,unit:"Jahr",hint:"William Harvey veröffentlichte es 1628.",emoji:"❤️"},
 {q:"¿Cuántos Protonen hat Kupfer?",un:29,unit:"Protonen",hint:"Cu – Ordnungszahl 29.",emoji:"⚗️"},
 {q:"¿En qué año wurde das erste Fernrohr auf den Himmel gerichtet?",un:1609,unit:"Jahr",hint:"Galilei richtete es auf den Mond.",emoji:"🌙"},
 {q:"¿Cuántos Grad Celsius schmilzt Stahl?",un:1370,unit:"°C",hint:"Je nach Legierung 1370-1520°C.",emoji:"🌡️"},
 {q:"¿En qué año erfand Diesel die Kompression-Zündmaschine?",un:1893,unit:"Jahr",hint:"Patent 1893 – erste Maschine 1897.",emoji:"⚙️"},
 {q:"¿Cuántos Chromosomen hat eine Bananenzelle?",un:22,unit:"Chromosomen",hint:"Bananen haben 11 Chromosomenpaare.",emoji:"🍌"},
 {q:"¿En qué año beschrieb Newton die drei Gesetze der Bewegung?",un:1687,unit:"Jahr",hint:"en 'Principia Mathematica'.",emoji:"🍎"},
 {q:"¿Cuántos Volt hat eine standard AA-Batterie?",un:1.5,unit:"Volt",hint:"Kleinfinger-Batterie 1,5V.",emoji:"🔋"},
 {q:"¿En qué año entdeckte Bohr das Atommodell?",un:1913,unit:"Jahr",hint:"Niels Bohrs Atommodell für Wasserstoff.",emoji:"⚛️"},
 {q:"¿Cuántos mg Koffein hat eine Tasse Espresso?",un:80,unit:"mg",hint:"Eine Tasse Kaffee hat 60-100 mg.",emoji:"☕"},
 {q:"¿En qué año erfand Turing das theoretische Konzept der universellen Maschine?",un:1936,unit:"Jahr",hint:"Die Turing-Maschine – Grundlage aller Computer.",emoji:"💻"},
 {q:"¿Cuántos Gram Sauerstoff braucht man für 1g Wasserstoff zur Verbrennung?",un:8,unit:"gramos",hint:"H₂ + O → H₂O – Massenverhältnis 1:8.",emoji:"⚗️"},
 {q:"¿En qué año wurde das Internet-Protokoll TCP/IP entwickelt?",un:1974,unit:"Jahr",hint:"Vint Cerf und Bob Kahn entwickelten es.",emoji:"🌐"},
 {q:"¿Cuántos Tonnen Atommüll produziert ein Kernkraftwerk por año?",un:30,unit:"tons",hint:"Hochradioaktiver Abfall – Problem für Jahrtausende.",emoji:"☢️"},
 {q:"¿En qué año entdeckte Semmelweis die Bedeutung des Händewaschens?",un:1847,unit:"Jahr",hint:"Er starb ohne Anerkennung – heute gefeiert.",emoji:"🧼"},
 {q:"¿Cuántos Protonen hat Blei?",un:82,unit:"Protonen",hint:"Pb – Ordnungszahl 82.",emoji:"⚗️"},
 {q:"¿En qué año wurde das erste GPS-System aktiviert?",un:1995,unit:"Jahr",hint:"Vollständige Nutzung seit 1995.",emoji:"🛰️"},
 {q:"¿Cuántos Atome sind en einem Wassermolekül?",un:3,unit:"Atome",hint:"H₂O – 2 Wasserstoff + 1 Sauerstoff.",emoji:"💧"},
 {q:"¿En qué año erfand Pasteur die Pasteurisierung?",un:1864,unit:"Jahr",hint:"Für Wein – dann auf Milch angewendet.",emoji:"🍷"},
 {q:"¿Cuántos Volt erzeugt eine Solarzelle?",un:0.5,unit:"Volt",hint:"Einzelne Zelle – viele werden en Serie geschaltet.",emoji:"☀️"},
 {q:"¿En qué año entdeckte Dalton das Atommodell?",un:1803,unit:"Jahr",hint:"John Daltons erste Atomtheorie.",emoji:"⚛️"},
 {q:"¿Cuántos Zentimeter ist ein Meter?",un:100,unit:"cm",hint:"Definition des metrischen Systems.",emoji:"📏"},
 {q:"¿En qué año erfand Otto den Viertaktmotor?",un:1876,unit:"Jahr",hint:"Nikolaus Otto – Grundlage aller heutigen Autos.",emoji:"🚗"},
 {q:"¿Cuántos Protonen hat Silber?",un:47,unit:"Protonen",hint:"Ag – Ordnungszahl 47.",emoji:"🪙"},
 {q:"¿En qué año entdeckte Hertz die elektromagnetischen Wellen?",un:1887,unit:"Jahr",hint:"Heinrich Hertz – die Einheit trägt seinen Namen.",emoji:"📡"},
 {q:"¿Cuántos Kilogramm wiegt ein Liter Benzin?",un:0.74,unit:"kg",hint:"Benzin ist leichter als Wasser.",emoji:"⛽"},
 {q:"¿En qué año erfand Aspirin Bayer?",un:1897,unit:"Jahr",hint:"Felix Hoffmann synthetisierte es 1897.",emoji:"💊"},
 {q:"¿Cuántos Volt hat eine Autobatterie?",un:12,unit:"Volt",hint:"Standard 12V Bleiakkumulator.",emoji:"🔋"},
 {q:"¿En qué año entdeckte Crick und Watson die Doppelhelix?",un:1953,unit:"Jahr",hint:"Veröffentlicht en Nature – Rosalind Franklin unvergessen.",emoji:"🧬"},
 {q:"¿Cuántos Megapixel hatte die erste iPhone-Kamera?",un:2,unit:"Megapixel",hint:"2007 – heute haben iPhones über 48 MP.",emoji:"📱"},
 {q:"¿En qué año wurde das erste Smartphone (IBM Simon) erfunden?",un:1994,unit:"Jahr",hint:"IBM Simon war der erste Touchscreen-Phone.",emoji:"📱"},
 {q:"¿Cuántos Grad Celsius schmilzt Butter?",un:32,unit:"°C",hint:"Je nach Zusammensetzung 28-36°C.",emoji:"🧈"},
 {q:"¿En qué año erfand Benz das erste benzinbetriebene Auto?",un:1885,unit:"Jahr",hint:"Benz Patent-Motorwagen – 3 Räder, 0,75 PS.",emoji:"🚗"},
 {q:"¿Cuántos Gramm wiegt ein Mol Wasser?",un:18,unit:"gramos",hint:"H₂O: 2×1 + 16 = 18 g/mol.",emoji:"💧"},
 {q:"¿En qué año wurde CRISPR-Cas9 entdeckt?",un:2012,unit:"Jahr",hint:"Charpentier und Doudna – Nobelpreis 2020.",emoji:"🧬"},
 {q:"¿Cuántos Bit hat 1 Gigabyte?",un:8589934592,unit:"Bit",hint:"8 mil millones Bit.",emoji:"💻"},
 {q:"¿En qué año erfand Fleming den Transistor (Diode)?",un:1904,unit:"Jahr",hint:"John Ambrose Fleming erfand die Diode.",emoji:"⚡"},
 {q:"¿Cuántos Grad Celsius friert Meerwasser?",un:-1.8,unit:"°C",hint:"Salzwasser friert bei niedrigeren Temperaturen.",emoji:"🌊"},
 {q:"¿En qué año entdeckte Jenner den Impfstoff gegen Pocken?",un:1796,unit:"Jahr",hint:"Der erste Impfstoff en der Geschichte.",emoji:"💉"},
 {q:"¿Cuántos Protonen hat Stickstoff?",un:7,unit:"Protonen",hint:"N – Ordnungszahl 7.",emoji:"⚗️"},
 {q:"¿En qué año erfand Shockley den Transistor?",un:1947,unit:"Jahr",hint:"Bell Labs – Grundlage aller modernen Elektronik.",emoji:"⚡"},
 {q:"¿Cuántos Tesla hat ein starker MRI-Scanner?",un:3,unit:"Tesla",hint:"Tesla ist Standard en Krankenhäusern.",emoji:"🧲"},
 {q:"¿En qué año entdeckte Mendeleev das Periodensystem?",un:1869,unit:"Jahr",hint:"Er sagte Elemente vorher die noch nicht entdeckt waren.",emoji:"⚗️"},
 {q:"¿Cuántos Grad Celsius kocht destilliertes Wasser?",un:100,unit:"°C",hint:"Bei Normaldruck 1 Atmosphäre.",emoji:"🌡️"},
 {q:"¿En qué año erfand Zeppelin das Luftschiff?",un:1900,unit:"Jahr",hint:"Erster Testflug des LZ 1 am 2. Juli 1900.",emoji:"🛸"},
 {q:"¿Cuántos Gramm wiegt ein Mol Natriumchlorid (Kochsalz)?",un:58.4,unit:"gramos",hint:"Na(23) + Cl(35,5) = 58,5 g/mol.",emoji:"🧂"},
 {q:"¿En qué año wurde das erste schwarze Loch fotografiert?",un:2019,unit:"Jahr",hint:"Event Horizon Telescope – M87*.",emoji:"🌑"},
 {q:"¿Cuántos Nanometer sind 1 Mikrometer?",un:1000,unit:"nanometers",hint:"1 µm = 1000 nm.",emoji:"📏"},
 {q:"¿En qué año entdeckte Boyle das Gasgesetz?",un:1662,unit:"Jahr",hint:"Boyle's Law: pV = konstant.",emoji:"⚗️"},
 {q:"¿Cuántos Ampere fließen durch eine 100W Glühbirne (230V)?",un:0.43,unit:"Ampere",hint:"I = P/U = 100/230 ≈ 0,43A.",emoji:"💡"},
 {q:"¿En qué año erfand Tesla den Wechselstrommotor?",un:1887,unit:"Jahr",hint:"Grundlage aller modernen Elektromotoren.",emoji:"⚡"},
 {q:"¿Cuántos millones Tonnen CO₂ emittiert die Welt al día?",un:100,unit:"million tons",hint:"37 mil millones Tonnen por año.",emoji:"🌍"},
 {q:"¿En qué año entdeckte Hooke die Zelle?",un:1665,unit:"Jahr",hint:"Robert Hooke betrachtete Kork unterm Mikroskop.",emoji:"🔬"},
 {q:"¿Cuántos Protonen hat Phosphor?",un:15,unit:"Protonen",hint:"P – Ordnungszahl 15.",emoji:"⚗️"},
 {q:"¿En qué año wurde das erste Kernkraftwerk gebaut?",un:1954,unit:"Jahr",hint:"Obninsk en der Sowjetunion.",emoji:"⚡"},
 {q:"¿Cuántos Atome hat ein Glukose-Molekül?",un:24,unit:"Atome",hint:"C₆H₁₂O₆ = 6+12+6 = 24 Atome.",emoji:"⚗️"},
 {q:"¿En qué año erfand Siemens den elektrischen Aufzug?",un:1880,unit:"Jahr",hint:"Werner von Siemens en Mannheim.",emoji:"🏗️"},
 {q:"¿Cuántos Grad Celsius schmilzt Glas?",un:700,unit:"°C",hint:"Je nach Zusammensetzung 700-1200°C.",emoji:"🌡️"},
 {q:"¿En qué año entdeckte Galvani den 'Tierstrom'?",un:1780,unit:"Jahr",hint:"Grundlage für Elektrochemie und Batterien.",emoji:"⚡"},
 {q:"¿Cuántos Kilogramm wiegt 1 Liter Luft?",un:0.0013,unit:"kg",hint:"1,29 Gramm pro Liter bei 20°C.",emoji:"💨"},
 {q:"¿En qué año erfand Swan die Kohlenfadenlampe?",un:1878,unit:"Jahr",hint:"Joseph Swan – kurz vor Edison.",emoji:"💡"},
 {q:"¿Cuántos Chromosomen hat eine Fruchtfliege?",un:8,unit:"Chromosomen",hint:"Drosophila – wichtigstes Modellorganismus.",emoji:"🪰"},
 {q:"¿En qué año beschrieb Kepler die Planetenbewegungen?",un:1609,unit:"Jahr",hint:"Keplers erste und zweite Gesetze.",emoji:"🪐"},
 {q:"¿Cuántos Grad dreht ein Polarisationsfilter das Licht?",un:90,unit:"Grad",hint:"Zwei gekreuzte Polarisationsfilter blocken alles.",emoji:"💡"},
 {q:"¿En qué año entdeckte Halley den Kometen (der nach ihm benannt ist)?",un:1705,unit:"Jahr",hint:"Er sagte die Wiederkehr vorher – Recht hatte er.",emoji:"☄️"},
 {q:"¿Cuántos Basispaare hat das menschliche Genom?",un:3000000000,unit:"Basenpaare",hint:"3 mil millones Basenpaare en der menschlichen DNA.",emoji:"🧬"},
 {q:"¿En qué año wurde das erste Elektroauto produziert?",un:1884,unit:"Jahr",hint:"Thomas Parker baute es en London.",emoji:"🚗"},
 {q:"¿Cuántos Volt erzeugt eine Brennstoffzelle?",un:1.2,unit:"Volt",hint:"Je nach Typ 0,5-1,2V pro Zelle.",emoji:"⚡"},
 {q:"¿En qué año erfand Braille das Blindenschriftsystem?",un:1824,unit:"Jahr",hint:"Louis Braille war 15 Jahre alt.",emoji:"👆"},
 {q:"¿Cuántos Protonen hat Calcium?",un:20,unit:"Protonen",hint:"Ca – Ordnungszahl 20.",emoji:"⚗️"},
 {q:"¿En qué año startete Voyager 1?",un:1977,unit:"Jahr",hint:"Am 5. September 1977 – jetzt außerhalb des Sonnensystems.",emoji:"🚀"},
 {q:"¿Cuántos m/s² beträgt die Schwerebeschleunigung auf dem Mond?",un:1.62,unit:"m/s²",hint:"1/6 der Erdgravitation.",emoji:"🌙"},
 {q:"¿En qué año entdeckte Hubble die Andromeda-Galaxie als eigene Galaxie?",un:1925,unit:"Jahr",hint:"Davor dachte man es sei ein Nebel.",emoji:"🌌"},
 {q:"¿Cuántos Neutronen hat Carbon-14?",un:8,unit:"Neutronen",hint:"6 Protonen + 8 Neutronen = Masse 14.",emoji:"⚗️"},
 {q:"¿En qué año erfand Otis den Sicherheitsaufzug?",un:1852,unit:"Jahr",hint:"Elisha Otis - Bremse verhinderte Absturz.",emoji:"🏗️"},
 {q:"¿Cuántos Hz hat 50Hz Wechselstrom pro Sekunde?",un:50,unit:"Zyklen/s",hint:"en Europa ist 50Hz Standard.",emoji:"⚡"},
 {q:"¿En qué año wurde der erste Transistorradio verkauft?",un:1954,unit:"Jahr",hint:"Texas Instruments TR-1.",emoji:"📻"},
 {q:"¿Cuántos Grad Celsius schmilzt Kupfer?",un:1085,unit:"°C",hint:"Niedrigerer Schmelzpunkt als Eisen.",emoji:"🌡️"},
 {q:"¿En qué año entdeckte Dalton das Gesetz der multiplen Proportionen?",un:1803,unit:"Jahr",hint:"Grundlage der modernen Chemie.",emoji:"⚗️"},
 {q:"¿Cuántos Nanometer groß ist ein Wasserstoffatom?",un:0.1,unit:"nanometers",hint:"0,1 nm = 1 Ångström.",emoji:"⚛️"},
 {q:"¿En qué año erfand Volta die Batterie?",un:1800,unit:"Jahr",hint:"Voltasche Säule – erste Batterie.",emoji:"🔋"},
 {q:"¿Cuántos Protonen hat Natrium?",un:11,unit:"Protonen",hint:"Na – Ordnungszahl 11.",emoji:"⚗️"},
 {q:"¿En qué año startete der erste Sputnik?",un:1957,unit:"Jahr",hint:"Am 4. Oktober 1957.",emoji:"🛰️"},
 {q:"¿Cuántos Kilowatt hat 1 PS?",un:0.736,unit:"kW",hint:"1 PS = 0,736 kW = 736 Watt.",emoji:"⚡"},
 {q:"¿En qué año entdeckte Bohr das Quantum der Wirkung?",un:1913,unit:"Jahr",hint:"Zusammen mit Plancks Quantentheorie.",emoji:"⚛️"},
 {q:"¿Cuántos Atome hat ein Methanmolekül?",un:5,unit:"Atome",hint:"CH₄ = 1 Kohlenstoff + 4 Wasserstoff.",emoji:"⚗️"},
 {q:"¿En qué año erfand Morse seinen berühmten Code?",un:1838,unit:"Jahr",hint:"Punkte und Striche – revolutionäre Kommunikation.",emoji:"📡"},
 {q:"¿Cuántos Grad Fahrenheit ist der Körper bei Fieber?",un:101,unit:"°F",hint:"38°C = 100,4°F – Fieber beginnt.",emoji:"🌡️"},
 {q:"¿En qué año entdeckte Mendel die Vererbungsgesetze?",un:1865,unit:"Jahr",hint:"Gregor Mendels Erbsenexperimente.",emoji:"🌱"},
 {q:"¿Cuántos Protonen hat Chlor?",un:17,unit:"Protonen",hint:"Cl – Ordnungszahl 17.",emoji:"⚗️"},
 {q:"¿En qué año wurde das erste iPhone veröffentlicht?",un:2007,unit:"Jahr",hint:"Steve Jobs: 'uno más thing...'",emoji:"📱"},
 {q:"¿Cuántos Megawatt erzeugt ein durchschnittliches Kernkraftwerk?",un:1000,unit:"Megawatt",hint:"1 GW – genug für eine Millionenstadt.",emoji:"⚡"},
 {q:"¿En qué año erfand Zuckerberg Facebook?",un:2004,unit:"Jahr",hint:"Als Harvard-Student.",emoji:"📱"},
 {q:"¿Cuántos Gramm Glukose hat das Gehirn al día als Mindestbedarf?",un:120,unit:"gramos",hint:"120g al día – für Denkprozesse.",emoji:"🧠"},
 {q:"¿En qué año wurde das erste GPS-Satellit gestartet?",un:1978,unit:"Jahr",hint:"Block I GPS-Satellit.",emoji:"🛰️"},
 {q:"¿Cuántos Grad Celsius beträgt die Raumtemperatur?",un:20,unit:"°C",hint:"18-22°C ist Standard.",emoji:"🌡️"},
 {q:"¿En qué año entdeckte Koch den Tuberkulose-Erreger?",un:1882,unit:"Jahr",hint:"Robert Koch am 24. März 1882.",emoji:"🔬"},
 {q:"¿Cuántos Protonen hat Aluminium?",un:13,unit:"Protonen",hint:"Al – Ordnungszahl 13.",emoji:"⚗️"},
 {q:"¿En qué año erfand Braun das Fernsehen (Braunsche Röhre)?",un:1897,unit:"Jahr",hint:"Karl Ferdinand Braun.",emoji:"📺"},
 {q:"¿Cuántos Kilokalorien hat 1 Gramm Protein?",un:4,unit:"kcal/g",hint:"Gleich wie Kohlenhydrate.",emoji:"💪"},
 {q:"¿En qué año entdeckte Planck die Quantentheorie?",un:1900,unit:"Jahr",hint:"Das Plancksche Wirkungsquantum h.",emoji:"⚛️"},
 {q:"¿En qué año entdeckte Hubble die Rotverschiebung?",un:1929,unit:"Jahr",hint:"Beweis für die Expansion des Universums.",emoji:"🌌"},
 {q:"¿Cuántos Elektronen hat Sauerstoff?",un:8,unit:"Elektronen",hint:"Gleich wie Protonen bei neutralem Atom.",emoji:"⚗️"},
 {q:"¿En qué año wurde der erste Elektromagnet gebaut?",un:1825,unit:"Jahr",hint:"William Sturgeon baute ihn.",emoji:"🧲"},
 {q:"¿Cuántos Grad Celsius beträgt der Siedepunkt von Flüssigstickstoff?",un:-196,unit:"°C",hint:"Wird für Kryonik und Kühlung verwendet.",emoji:"🌡️"},
 {q:"¿En qué año entdeckte Becquerel die Radioaktivität?",un:1896,unit:"Jahr",hint:"Henri Becquerel – zufällig beim Fotografieren.",emoji:"☢️"},
 {q:"¿Cuántos Protonen hat Magnesium?",un:12,unit:"Protonen",hint:"Mg – Ordnungszahl 12.",emoji:"⚗️"},
 {q:"¿En qué año baute Wright Brothers das erste Motorflugzeug?",un:1903,unit:"Jahr",hint:"12 Sekunden – 37 Meter – die Welt veränderte sich.",emoji:"✈️"},
 {q:"¿Cuántos Hertz hat menschliche Sprache en promedio?",un:250,unit:"Hz",hint:"Grundfrequenz der menschlichen Stimme.",emoji:"🎤"},
 {q:"¿En qué año wurde Chlor als Element identifiziert?",un:1774,unit:"Jahr",hint:"Karl Wilhelm Scheele entdeckte es.",emoji:"⚗️"},
 {q:"¿Cuántos Kilowattstunden Energie produziert ein Windrad por día?",un:10000,unit:"kWh/Tag",hint:"Ein 2-MW-Windrad erzeugt 10.000-15.000 kWh al día.",emoji:"🌬️"},
 {q:"¿En qué año wurde das erste Antibiotikum klinisch angewendet?",un:1942,unit:"Jahr",hint:"Anne Miller – erste Patientin geheilt mit Penicillin.",emoji:"💊"},
 {q:"¿Cuántos Grad Celsius beträgt die Temperatur im Erdkern?",un:6000,unit:"°C",hint:"Ähnlich wie die Sonnenoberfläche.",emoji:"🌋"},
 {q:"¿En qué año entdeckte Ampère das Gesetz des elektrischen Stroms?",un:1820,unit:"Jahr",hint:"André-Marie Ampère – die Einheit trägt seinen Namen.",emoji:"⚡"},
 {q:"¿Cuántos millones Transistoren hat ein moderner CPU-Chip?",un:50000,unit:"millones",hint:"50 mil millones – Apple M3 hat 25 Mrd.",emoji:"💻"},
 {q:"¿En qué año wurde das erste KI-Programm geschrieben?",un:1951,unit:"Jahr",hint:"Logic Theorist von Newell und Simon.",emoji:"🤖"},
 {q:"¿Cuántos Gramm wiegt 1 Mol Kohlendioxid?",un:44,unit:"gramos",hint:"C(12) + 2×O(16) = 44 g/mol.",emoji:"⚗️"},
 {q:"¿En qué año entdeckte Faraday die elektromagnetische Induktion?",un:1831,unit:"Jahr",hint:"Grundlage für Generator und Motor.",emoji:"⚡"},
 {q:"¿Cuántos Kilojoule hat 1 Kilokalorien?",un:4.18,unit:"kJ",hint:"1 kcal = 4,18 kJ.",emoji:"🔥"},
 {q:"¿En qué año erschien Einsteins allgemeine Relativitätstheorie?",un:1915,unit:"Jahr",hint:"Erweiterung der speziellen Theorie.",emoji:"⚛️"},
 {q:"¿Cuántos Elektronen fasst die erste Elektronenschale eines Atoms?",un:2,unit:"Elektronen",hint:"K-Schale – maximal 2 Elektronen.",emoji:"⚛️"},
 {q:"¿En qué año wurde der erste Microchip erfunden?",un:1958,unit:"Jahr",hint:"Jack Kilby bei Texas Instruments.",emoji:"💻"},
 {q:"¿Cuántos Kilopascal beträgt der Luftdruck auf Meereshöhe?",un:101.3,unit:"kPa",hint:"1 Atmosphäre = 101.325 Pa.",emoji:"🌬️"},
 {q:"¿En qué año entdeckte Maxwell die elektromagnetischen Wellen theoretisch?",un:1864,unit:"Jahr",hint:"James Clerk Maxwell – Hertz bewies es 1887.",emoji:"📡"},
 {q:"¿Cuántos Grad Celsius siedet Ethanol?",un:78.4,unit:"°C",hint:"Unter dem Siedepunkt des Wassers.",emoji:"🌡️"},
 {q:"¿En qué año wurde das Hubble espacio Telescope gestartet?",un:1990,unit:"Jahr",hint:"Am 24. April 1990 mit Discovery.",emoji:"🔭"},
 {q:"¿Cuántos Protonen hat Silizium?",un:14,unit:"Protonen",hint:"Si – Ordnungszahl 14 – Basis der Halbleiter.",emoji:"💻"},
 {q:"¿En qué año entdeckte Marie Curie Polonium?",un:1898,unit:"Jahr",hint:"Benannt nach ihrer Heimat Polen.",emoji:"☢️"},
 {q:"¿Cuántos Joule hat 1 Kalorie?",un:4.184,unit:"Joule",hint:"1 cal = 4,184 J.",emoji:"🔥"},
 {q:"¿En qué año wurde der erste Barcode verwendet?",un:1974,unit:"Jahr",hint:"Am 26. Juni 1974 – Wrigley's Kaugummi en Ohio.",emoji:"📊"},
 {q:"¿Cuántos Protonen hat Schwefel?",un:16,unit:"Protonen",hint:"S – Ordnungszahl 16.",emoji:"⚗️"},
 {q:"¿En qué año wurde das erste Farbfoto aufgenommen?",un:1861,unit:"Jahr",hint:"James Clerk Maxwell – ein Schottenkaro.",emoji:"📷"},
 {q:"¿Cuántos Ampere darf eine Haushaltssteckdose maximal führen?",un:16,unit:"Ampere",hint:"Standard 230V/16A en Deutschland.",emoji:"⚡"},
 {q:"¿En qué año entdeckte Ohm das Ohmsche Gesetz?",un:1827,unit:"Jahr",hint:"Georg Simon Ohm: U = R × I.",emoji:"⚡"},
 {q:"¿Cuántos Monate dauert es bis der Körper alle Zellen erneuert hat?",un:84,unit:"meses",hint:"7 Jahre – manche Zellen halten ein Leben lang.",emoji:"🔄"},
 {q:"¿En qué año erfand Zeiss die erste apochromatische Linse?",un:1886,unit:"Jahr",hint:"Grundlage moderner Mikroskopie.",emoji:"🔬"},
 {q:"¿Cuántos Kilogramm Sauerstoff atmet un humano al día?",un:0.55,unit:"kg",hint:"550 Gramm Sauerstoff al día.",emoji:"💨"},
 {q:"¿En qué año entdeckte Haber die Ammoniaksynthese?",un:1909,unit:"Jahr",hint:"Fritz Haber – Grundlage der Düngemittelproduktion.",emoji:"⚗️"},
 {q:"¿Cuántos Protonen hat Zink?",un:30,unit:"Protonen",hint:"Zn – Ordnungszahl 30.",emoji:"⚗️"},
 {q:"¿En qué año wurde das erste Halbleiter-Transistorradio gebaut?",un:1954,unit:"Jahr",hint:"Texas Instruments TR-1.",emoji:"📻"},
 {q:"¿Cuántos Elektronen fasst die zweite Schale eines Atoms?",un:8,unit:"Elektronen",hint:"L-Schale – maximal 8 Elektronen.",emoji:"⚛️"},
 {q:"¿En qué año erfand Schottky die Röhrendiode?",un:1914,unit:"Jahr",hint:"Grundlage der Radiotechnik.",emoji:"📡"},
 {q:"¿Cuántos Kilometer por hora ist die Schallgeschwindigkeit en Luft?",un:1235,unit:"km/h",hint:"343 m/s = 1235 km/h.",emoji:"🔊"},
 {q:"¿En qué año entdeckte Lavoisier das Gesetz der Massenerhaltung?",un:1789,unit:"Jahr",hint:"Antoine Lavoisier – Vater der modernen Chemie.",emoji:"⚗️"},
 {q:"¿Cuántos Protonen hat Titan?",un:22,unit:"Protonen",hint:"Ti – Ordnungszahl 22.",emoji:"⚗️"},
 {q:"¿En qué año erschien Hawkings 'un Brief History de tiempo'?",un:1988,unit:"Jahr",hint:"Millionenfach verkauft – allgemein verständliche Physik.",emoji:"📚"},
 {q:"¿Cuántos Grad Celsius beträgt die Temperatur im Erdmantel?",un:3000,unit:"°C",hint:"Zwischen Erdkruste und Kern.",emoji:"🌋"},
 {q:"¿En qué año entdeckte Fleming die Röntgenstrahlen?",un:1895,unit:"Jahr",hint:"Nicht Fleming – sondern Wilhelm Conrad Röntgen.",emoji:"🩻"},
 {q:"¿Cuántos Kilobyte hat 1 Megabyte?",un:1024,unit:"Kilobyte",hint:"Binärsystem – 2¹⁰ = 1024.",emoji:"💻"},
 {q:"¿En qué año wurde die erste MRT-Maschine gebaut?",un:1977,unit:"Jahr",hint:"Erste Ganzkörper-MRT von Damadian.",emoji:"🏥"},
 {q:"¿Cuántos Sekunden hat ein Tag?",un:86400,unit:"segundos",hint:"24 × 60 × 60 = 86.400.",emoji:"⏰"},
 {q:"¿En qué año erfand Banting Insulin?",un:1921,unit:"Jahr",hint:"Frederick Banting rettete millones Diabetiker.",emoji:"💉"},
 {q:"¿Cuántos Protonen hat Mangan?",un:25,unit:"Protonen",hint:"Mn – Ordnungszahl 25.",emoji:"⚗️"},
 {q:"¿En qué año wurde das erste elektromagnetische Induktions-Experiment gemacht?",un:1831,unit:"Jahr",hint:"Michael Faraday – Grundlage für Generatoren.",emoji:"⚡"},
 {q:"¿Cuántos Grad Celsius beträgt die Kerntemperatur der Sonne?",un:15000000,unit:"°C",hint:"15 millones Grad – Kernfusion findet dort statt.",emoji:"☀️"},
 {q:"¿En qué año wurde das Elektron entdeckt?",un:1897,unit:"Jahr",hint:"J.J. Thomson beim Kathodenstrahlexperiment.",emoji:"⚛️"},
 {q:"¿Cuántos Elektronen fasst die dritte Elektronenschale?",un:18,unit:"Elektronen",hint:"M-Schale – maximal 18 Elektronen.",emoji:"⚛️"},
 {q:"¿En qué año wurde das erste HIV-Virus isoliert?",un:1983,unit:"Jahr",hint:"Françoise Barré-Sinoussi – Nobelpreis 2008.",emoji:"🔬"},
 {q:"¿Cuántos Protonen hat Gold (Ordnungszahl)?",un:79,unit:"Protonen",hint:"Au – Ordnungszahl 79.",emoji:"🪙"},
 {q:"¿En qué año erfand Shannon die Informationstheorie?",un:1948,unit:"Jahr",hint:"Claude Shannon – Grundlage der digitalen Kommunikation.",emoji:"💻"},
 {q:"¿Cuántos Kilowattstunden enthält 1 kg Wasserstoff?",un:33,unit:"kWh",hint:"Drei Mal mehr als Benzin pro kg.",emoji:"⚡"},
 {q:"¿En qué año wurde die erste Solarzelle entwickelt?",un:1954,unit:"Jahr",hint:"Bell Labs – 6% Wirkungsgrad.",emoji:"☀️"},
 {q:"¿Cuántos Protonen hat Brom?",un:35,unit:"Protonen",hint:"Br – Ordnungszahl 35.",emoji:"⚗️"},
 {q:"¿En qué año entdeckte Celsius die Celsiusskala?",un:1742,unit:"Jahr",hint:"Anders Celsius – ursprünglich umgekehrt.",emoji:"🌡️"},
 {q:"¿Cuántos Nanometer ist ein Atom groß?",un:0.1,unit:"nanometers",hint:"0,1-0,5 nm je nach Element.",emoji:"⚛️"},
 {q:"¿En qué año erfand Braun den Wechselrichter?",un:1897,unit:"Jahr",hint:"Karl Ferdinand Braun – auch Nobelpreis 1909.",emoji:"⚡"},
 {q:"¿Cuántos Tonnen CO₂ speichert ein Hektar Wald por año?",un:2,unit:"tons",hint:"Durchschnittlicher mitteleuropäischer Mischwald.",emoji:"🌳"},
 {q:"¿En qué año entdeckte Hardy die Hardy-Weinberg-Gleichung?",un:1908,unit:"Jahr",hint:"Grundlage der Populationsgenetik.",emoji:"🧬"},
 {q:"¿Cuántos Protonen hat Nickel?",un:28,unit:"Protonen",hint:"Ni – Ordnungszahl 28.",emoji:"⚗️"},
 {q:"¿En qué año baute Daimler das erste Motorrad?",un:1885,unit:"Jahr",hint:"Gottlieb Daimler – der Reitwagen.",emoji:"🏍️"},
 {q:"¿Cuántos Atome hat ein Schwefelsäuremolekül (H₂SO₄)?",un:7,unit:"Atome",hint:"2H + S + 4O = 7 Atome.",emoji:"⚗️"},
 {q:"¿En qué año erschien das erste Lehrbuch der Chemie?",un:1789,unit:"Jahr",hint:"Lavoisiers Traité élémentaire de chimie.",emoji:"📚"},
 {q:"¿Cuántos Grad Celsius schmilzt Aluminium?",un:660,unit:"°C",hint:"Deutlich niedrigerer Schmelzpunkt als Stahl.",emoji:"🌡️"},
 {q:"¿En qué año entdeckte Banting und Best Insulin?",un:1921,unit:"Jahr",hint:"Lebensrettend für millones Diabetiker.",emoji:"💉"},
 {q:"¿Cuántos Billionen Tonnen Sauerstoff enthält die Erdatmosphäre?",un:1200,unit:"trillion tons",hint:"1,2 × 10¹⁵ kg Sauerstoff.",emoji:"💨"},
 {q:"¿En qué año entdeckte Rutherford den Atomkern?",un:1909,unit:"Jahr",hint:"Goldfolienexperiment – der Kern ist klein und dicht.",emoji:"⚛️"},
 {q:"¿Cuántos Protonen hat Kobalt?",un:27,unit:"Protonen",hint:"Co – Ordnungszahl 27.",emoji:"⚗️"},
 {q:"¿En qué año erfand Pascal die Rechenmaschine Pascaline?",un:1642,unit:"Jahr",hint:"Konnte addieren und subtrahieren.",emoji:"🔢"},
 {q:"¿Cuántos Lumen erzeugt eine standard 60-Watt-Glühbirne?",un:800,unit:"Lumen",hint:"Eine LED-Birne braucht nur 8-10 Watt dafür.",emoji:"💡"},
 {q:"¿En qué año entdeckte Dirac die Antimaterie theoretisch?",un:1928,unit:"Jahr",hint:"Paul Dirac sagte Positronen vorher.",emoji:"⚛️"},
 {q:"¿Cuántos Gramm wiegt 1 Mol Calciumcarbonat (Kalk)?",un:100,unit:"gramos",hint:"CaCO₃ = 40+12+(3×16) = 100 g/mol.",emoji:"⚗️"},
 {q:"¿En qué año erfand Tesla das drahtlose Energieübertragungsprinzip?",un:1891,unit:"Jahr",hint:"Wardenclyffe Tower war sein gescheitertes Projekt.",emoji:"⚡"},
 {q:"¿Cuántos Kilojoule hat 1 Gramm Fett?",un:37,unit:"kJ",hint:"1g Fett = 9 kcal = 37 kJ.",emoji:"🔥"},
 {q:"¿En qué año erschien Newtons Opticks?",un:1704,unit:"Jahr",hint:"Über Licht, Prismen und Farben.",emoji:"🌈"},
 {q:"¿Cuántos Protonen hat Vanadium?",un:23,unit:"Protonen",hint:"V – Ordnungszahl 23.",emoji:"⚗️"},
 {q:"¿En qué año erfand Geiger den Geigerzähler?",un:1908,unit:"Jahr",hint:"Hans Geiger – zur Messung ionisierender Strahlung.",emoji:"☢️"},
 {q:"¿Cuántos Gramm wiegt 1 Mol Methan?",un:16,unit:"gramos",hint:"CH₄ = 12+4 = 16 g/mol.",emoji:"⚗️"},
 {q:"¿En qué año entdeckte Heisenberg das Unschärfeprinzip?",un:1927,unit:"Jahr",hint:"Ort und Impuls nicht gleichzeitig messbar.",emoji:"⚛️"},
 {q:"¿Cuántos Elektronen fasst die vierte Schale?",un:32,unit:"Elektronen",hint:"N-Schale – maximal 32 Elektronen.",emoji:"⚛️"},
 {q:"¿En qué año entdeckte Compton den Compton-Effekt?",un:1923,unit:"Jahr",hint:"Licht verhält sich wie Teilchen.",emoji:"⚛️"},
 {q:"¿Cuántos km/h schnell bewegen sich Elektronen en einem Kabel?",un:0.0003,unit:"km/h",hint:"Sehr langsam – aber die Welle geht mit Lichtgeschwindigkeit.",emoji:"⚡"},
];