// 🎯 MUESTRA GRATUITA – Adultos – Español
export default [
  {q:"¿Cuántos litros de sangre bombea el corazón humano al día?",a:7200,unit:"litros",hint:"El corazón late ~100.000 veces al día.",emoji:"❤️"},
  {q:"¿A qué velocidad viaja un estornudo?",a:160,unit:"km/h",hint:"Las partículas vuelan hasta 8 metros.",emoji:"🤧"},
  {q:"¿Cuántas horas duerme una persona a lo largo de su vida?",a:229000,unit:"horas",hint:"Aproximadamente un tercio de tu vida.",emoji:"😴"},
  {q:"¿Cuántos kg de comida consume un humano a lo largo de su vida?",a:35000,unit:"kg",hint:"35 toneladas de comida en 80 años.",emoji:"🍽️"},
  {q:"¿Cuántas veces se ríe una persona al día en promedio?",a:17,unit:"veces",hint:"Los niños se ríen mucho más que los adultos.",emoji:"😂"},
  {q:"¿A cuántos km/h puede correr el humano más rápido?",a:45,unit:"km/h",hint:"Usain Bolt alcanzó los 44,7 km/h.",emoji:"⚡"},
  {q:"¿Cuántos litros de saliva produce una persona al día?",a:1.5,unit:"litros",hint:"La mayor parte se traga durante el día.",emoji:"💧"},
  {q:"¿Cuántos huesos tiene un bebé recién nacido?",a:270,unit:"huesos",hint:"Más que los adultos – muchos se fusionan.",emoji:"🦴"},
  {q:"¿Cuántas veces late el corazón a lo largo de una vida?",a:2500000000,unit:"latidos",hint:"Unos 2.500 millones de latidos.",emoji:"❤️"},
  {q:"¿Cuántos metros crece el cabello al año?",a:15,unit:"cm",hint:"Unos 1,25 cm por mes.",emoji:"💇"},
  {q:"¿Cuántos km camina una persona a lo largo de su vida?",a:160000,unit:"km",hint:"Unas 4 veces alrededor de la Tierra.",emoji:"🚶"},
  {q:"¿Cuántas células reemplaza el cuerpo humano por segundo?",a:3800000,unit:"células",hint:"3,8 millones cada segundo.",emoji:"🔬"},
  {q:"¿Cuántas veces parpadea una persona a lo largo de su vida?",a:400000000,unit:"veces",hint:"400 millones de parpadeos.",emoji:"👁️"},
  {q:"¿Cuántos litros de aire respira una persona al día?",a:11000,unit:"litros",hint:"Unas 15 respiraciones por minuto.",emoji:"💨"},
  {q:"¿A qué velocidad viajan los impulsos nerviosos en el cuerpo?",a:430,unit:"km/h",hint:"Casi tan rápido como un coche de carreras.",emoji:"⚡"},
  {q:"¿Cuántos metros cuadrados de piel tiene un humano?",a:2,unit:"m²",hint:"La piel es el órgano más grande.",emoji:"🧴"},
  {q:"¿Cuántos segundos tarda la sangre en circular por todo el cuerpo?",a:60,unit:"segundos",hint:"Un circuito completo en aproximadamente un minuto.",emoji:"❤️"},
  {q:"¿Cuántos dientes tiene un adulto?",a:32,unit:"dientes",hint:"Incluyendo las muelas del juicio.",emoji:"🦷"},
  {q:"¿Cuántos litros de sangre tiene un adulto?",a:5,unit:"litros",hint:"Entre 5 y 6 litros en promedio.",emoji:"🩸"},
  {q:"¿Cuántos músculos tiene el cuerpo humano?",a:650,unit:"músculos",hint:"Más de 600 músculos esqueléticos.",emoji:"💪"},
  {q:"¿Cuántos km de vasos sanguíneos tiene el cuerpo?",a:100000,unit:"km",hint:"2,5 veces alrededor de la Tierra.",emoji:"🩸"},
  {q:"¿Cuántas veces late el corazón por minuto en reposo?",a:70,unit:"latidos",hint:"Entre 60 y 100 es lo normal.",emoji:"❤️"},
  {q:"¿Cuántos gramos pesa el cerebro humano?",a:1400,unit:"gramos",hint:"El 2% del peso corporal.",emoji:"🧠"},
  {q:"¿Cuántas horas tarda el cuerpo en digerir una comida completa?",a:6,unit:"horas",hint:"La digestión completa toma entre 24 y 72 horas.",emoji:"🍽️"},
  {q:"¿Cuántas veces estornuda una persona al día en promedio?",a:4,unit:"veces",hint:"Entre 4 y 10 ataques de estornudo al día.",emoji:"🤧"},
];
