// 🔥 CUERPO Y BIOLOGÍA – Español
export default [
 {q:"¿Cuántos liters de sangre el corazón pump por día?",un:7200,unit:"litros",hint:"el corazón beats ~100,000 veces un día.",emoji:"❤️"},
 {q:"¿Cuántos bones un adulto humano tiene?",un:206,unit:"huesos",hint:"Newborns tiene 270 – many fuse.",emoji:"🦴"},
 {q:"¿Cuántos km/h un nervio signal viaja?",un:430,unit:"km/h",hint:"uno de el fastest things en your cuerpo.",emoji:"⚡"},
 {q:"¿Cuántos square meters de piel covers el humano cuerpo?",un:2,unit:"m²",hint:"el largest órgano.",emoji:"🧴"},
 {q:"¿Cuántos liters de air un persona breathe por día?",un:11000,unit:"litros",hint:"sobre 15 breaths por minuto.",emoji:"💨"},
 {q:"¿Cuántos muscles el humano cuerpo tiene?",un:650,unit:"músculos",hint:"Over 600 skeletal muscles.",emoji:"💪"},
 {q:"¿Cuántos km de sangre vessels el cuerpo contiene?",un:100000,unit:"km",hint:"2.5 veces around el tierra.",emoji:"🩸"},
 {q:"¿Cuántas veces el corazón beat por minuto a rest?",un:70,unit:"latidos",hint:"60-100 es normal.",emoji:"❤️"},
 {q:"¿Cuántos liters de saliva el cuerpo produce al día?",un:1.5,unit:"litros",hint:"Most es swallowed.",emoji:"💧"},
 {q:"¿Cuántos cells el cuerpo replace por segundo?",un:3800000,unit:"cells",hint:"3.8 millones every segundo.",emoji:"🔬"},
 {q:"¿Cuántas veces un persona blink por día?",un:20000,unit:"veces",hint:"Every 4-6 segundos.",emoji:"👁️"},
 {q:"¿Cuántos grams el humano cerebro pesa?",un:1400,unit:"gramos",hint:"2% de cuerpo peso but 20% de energía.",emoji:"🧠"},
 {q:"¿Cuántos liters de sangre un adulto tiene?",un:5,unit:"litros",hint:"5-6 liters en promedio.",emoji:"🩸"},
 {q:"¿Cuántas horas de dormir un humano pasa en su vida?",un:229000,unit:"horas",hint:"sobre un third de your vida.",emoji:"😴"},
 {q:"¿Cuántos km camina una persona de media a lo largo de su vida?",un:160000,unit:"km",hint:"Four veces around el tierra.",emoji:"🚶"},
 {q:"¿Cuántos teeth un adulto humano tiene?",un:32,unit:"dientes",hint:"Including wisdom teeth.",emoji:"🦷"},
 {q:"¿Cuántas veces late el corazón a lo largo de una vida?",un:2500000000,unit:"latidos",hint:"sobre 2.5 mil millones beats.",emoji:"❤️"},
 {q:"¿Cuánto tiempo it take para sangre to circulate el cuerpo?",un:60,unit:"segundos",hint:"uno full circuit por minuto.",emoji:"❤️"},
 {q:"¿Cuántos grams de piel el cuerpo shed por día?",un:30,unit:"gramos",hint:"Your la cama collects all de it.",emoji:"🧴"},
 {q:"¿Cuántos taste buds el humano lengua tiene?",un:10000,unit:"taste buds",hint:"They regenerate every 10-14 días.",emoji:"👅"},
 {q:"¿Cuántos hairs el promedio humano head tiene?",un:100000,unit:"hairs",hint:"100,000 en promedio – varies by cabello color.",emoji:"💇"},
 {q:"¿Cuántos hairs un persona lose por día?",un:100,unit:"hairs",hint:"normal cabello loss.",emoji:"💇"},
 {q:"¿Cuántos beats por minuto puede el corazón reach durante extreme exercise?",un:220,unit:"latidos/min",hint:"Maximum corazón rate formula: 220 minus age.",emoji:"❤️"},
 {q:"¿Cuántos liters de orina el cuerpo produce al día?",un:1.5,unit:"litros",hint:"1-2 liters con normal hydration.",emoji:"💛"},
 {q:"¿Cuántos cm de fingernail grows por mes?",un:3,unit:"mm",hint:"3mm por mes en promedio.",emoji:"💅"},
 {q:"¿Cuántos grams de fat puede el cuerpo store?",un:15,unit:"kg",hint:"promedio adulto stores 10-20 kg de fat.",emoji:"🍔"},
 {q:"¿Cuántas horas puede un humano survive without agua?",un:72,unit:"horas",hint:"3 días maximum en normal conditions.",emoji:"💧"},
 {q:"¿Cuántos días puede un humano survive without comida?",un:30,unit:"días",hint:"Depends on cuerpo fat y health.",emoji:"🍽️"},
 {q:"¿Cuántos watts de power el cerebro consume?",un:20,unit:"vatios",hint:"Less que un lightbulb.",emoji:"🧠"},
 {q:"¿Cuántas veces puede el humano ojo distinguish colors?",un:10000000,unit:"colores",hint:"10 millones shades.",emoji:"👁️"},
 {q:"¿Cuántos grams el humano corazón pesa?",un:300,unit:"gramos",hint:"sobre el size de un fist.",emoji:"❤️"},
 {q:"¿Cuántos liters de sangre el liver process al día?",un:1500,unit:"litros",hint:"el liver processes massive volumes.",emoji:"🟤"},
 {q:"¿Cuántos degrees Celsius es normal cuerpo temperatura?",un:37,unit:"°C",hint:"98.6°F en Fahrenheit.",emoji:"🌡️"},
 {q:"¿Cuántos cm puede pupils dilate en el dark?",un:8,unit:"mm",hint:"de 2mm en luz to 8mm en dark.",emoji:"👁️"},
 {q:"¿Cuántos km/h puede un humano sneeze viaja?",un:160,unit:"km/h",hint:"Particles fly up to 8 meters.",emoji:"🤧"},
 {q:"¿Cuántos bones son en el humano hand?",un:27,unit:"huesos",hint:"27 bones en uno hand alone.",emoji:"✋"},
 {q:"¿Cuántos segundos puede un humano hold their aliento en promedio?",un:60,unit:"segundos",hint:"Trained free divers puede exceed 20 minutos.",emoji:"🫁"},
 {q:"¿Cuántos grams el humano liver pesa?",un:1500,unit:"gramos",hint:"el largest internal órgano.",emoji:"🟤"},
 {q:"¿Cuántos liters de gastric acid son produced por día?",un:2,unit:"litros",hint:"Strong enough to dissolve metal.",emoji:"⚗️"},
 {q:"¿Cuántas horas de vida cada cigarette cost?",un:11,unit:"minutos",hint:"11 minutos shorter por cigarette.",emoji:"🚬"},
 {q:"¿Cuántos km/h es el fastest recorded humano punch?",un:45,unit:"km/h",hint:"Boxing punches puede exceed 40 km/h.",emoji:"🥊"},
 {q:"¿Cuántos grams de oxygen un humano inhale por día?",un:550,unit:"gramos",hint:"sobre 550g de oxygen por día.",emoji:"💨"},
 {q:"¿Cuántos square cm es el surface area de el pulmones?",un:70,unit:"m²",hint:"70 square meters – like un tennis court.",emoji:"🫁"},
 {q:"¿Cuántos minutos puede el cerebro survive without oxygen?",un:6,unit:"minutos",hint:"cerebro damage begins after 4-6 minutos.",emoji:"🧠"},
 {q:"¿Cuántos grams de cabello un persona tiene on their entire cuerpo?",un:30,unit:"gramos",hint:"Excluding head cabello.",emoji:"💇"},
 {q:"¿Cuántos días it take para el estómago lining to completely renew?",un:5,unit:"días",hint:"New estómago lining every few días.",emoji:"🫀"},
 {q:"¿Cuántos cm puede el estómago expand when full?",un:4,unit:"litros",hint:"de 75ml empty to 1-4 liters full.",emoji:"🍽️"},
 {q:"¿Cuántos teeth did prehistoric los humanos tiene?",un:32,unit:"dientes",hint:"Same as modern los humanos.",emoji:"🦷"},
 {q:"¿Cuántos grams el spleen pesa?",un:150,unit:"gramos",hint:"sobre el same as un riñón.",emoji:"🫀"},
 {q:"¿Cuántos liters de bile el liver produce al día?",un:0.8,unit:"litros",hint:"800ml de bile al día.",emoji:"💛"},
];