// 🤯 WTF FACTS – Adultos – Español
export default [
  {q:"¿Cuántas veces al día eructa una persona en promedio?",a:25,unit:"veces",hint:"Casi igual que los pedos.",emoji:"😤"},
  {q:"¿Cuántos kg de insectos come un humano accidentalmente al año?",a:1,unit:"kg",hint:"Escondidos en alimentos – la FDA permite partes de insectos.",emoji:"🪲"},
  {q:"¿Cuántos segundos dura el orgasmo masculino promedio?",a:6,unit:"segundos",hint:"Las mujeres tienen más suerte con 20 segundos.",emoji:"💦"},
  {q:"¿Cuántas horas pasa una persona en el baño a lo largo de su vida?",a:9000,unit:"horas",hint:"Más de un año de tu vida en el inodoro.",emoji:"🚽"},
  {q:"¿Qué porcentaje de personas ha orinado en la ducha?",a:80,unit:"%",hint:"El resto miente.",emoji:"🚿"},
  {q:"¿Cuántas bacterias se transfieren al dar la mano?",a:10000000,unit:"bacterias",hint:"10 millones por segundo de contacto.",emoji:"🤝"},
  {q:"¿A qué velocidad viaja un estornudo en km/h?",a:160,unit:"km/h",hint:"Las partículas vuelan hasta 8 metros.",emoji:"🤧"},
  {q:"¿Cuántas veces por hora toca una persona su cara?",a:23,unit:"veces/hora",hint:"552 veces al día.",emoji:"✋"},
  {q:"¿Cuántos kg de piel pierde un humano a lo largo de su vida?",a:48,unit:"kg",hint:"30.000 células de piel por hora.",emoji:"🧴"},
  {q:"¿Cuántos metros de intestino tiene un humano?",a:8,unit:"metros",hint:"Intestino delgado y grueso juntos.",emoji:"🌀"},
  {q:"¿Cuántos millones de espermatozoides pierde un hombre por eyaculación?",a:280,unit:"millones",hint:"Solo uno consigue el trabajo.",emoji:"🏊"},
  {q:"¿Qué porcentaje de personas ha orinado en una piscina pública?",a:19,unit:"%",hint:"Según encuesta estadounidense – probablemente más.",emoji:"🏊"},
  {q:"¿Cuántos mil millones de bacterias hay en una sola deposición?",a:100,unit:"mil millones",hint:"El 30% de las heces son bacterias.",emoji:"💩"},
  {q:"¿A cuántos grados Celsius llega un rayo?",a:30000,unit:"°C",hint:"5 veces más caliente que la superficie del sol.",emoji:"⚡"},
  {q:"¿Cuántas veces parpadea una persona al día?",a:20000,unit:"veces",hint:"Cada 4-6 segundos.",emoji:"👁️"},
  {q:"¿Cuántos gramos de saliva se intercambian en un beso?",a:3,unit:"gramos",hint:"Más 80 millones de bacterias.",emoji:"💋"},
  {q:"¿Cuántos segundos sobrevive la cabeza cortada de un pollo?",a:15,unit:"segundos",hint:"El sistema nervioso sigue funcionando brevemente.",emoji:"🐔"},
  {q:"¿Qué porcentaje del polvo doméstico son células de piel humana?",a:70,unit:"%",hint:"Respiras a tus compañeros de casa cada día.",emoji:"🌫️"},
  {q:"¿Cuántos litros de gas produce un humano al día por digestión?",a:2,unit:"litros",hint:"1,5 litros se liberan como pedos.",emoji:"💨"},
  {q:"¿Cuántos minutos dura el orgasmo femenino más largo documentado?",a:45,unit:"minutos",hint:"Caso médicamente documentado.",emoji:"😮"},
  {q:"¿Cuántos gramos de excrementos come una vaca al día al pastar?",a:500,unit:"gramos",hint:"Otras vacas dejan rastros en la hierba.",emoji:"🐄"},
  {q:"¿Qué porcentaje de personas besa inclinando la cabeza hacia la derecha?",a:66,unit:"%",hint:"Dos de cada tres personas se inclinan a la derecha.",emoji:"💏"},
  {q:"¿Cuántos gramos de plástico come un humano por semana?",a:5,unit:"gramos",hint:"Una tarjeta de crédito por semana.",emoji:"♻️"},
  {q:"¿Qué porcentaje de billetes llevan rastros de cocaína?",a:90,unit:"%",hint:"Casi todos los billetes tienen rastros.",emoji:"💵"},
  {q:"¿Cuántas partes de insecto hay en 100g de mantequilla de cacahuete según la FDA?",a:30,unit:"partes de insecto",hint:"Límite FDA: 30 partes de insecto por 100g.",emoji:"🥜"},
  {q:"¿Cuántos segundos dura el estornudo más largo documentado?",a:978,unit:"segundos",hint:"16 minutos – una niña estuvo estornudando 978 días seguidos.",emoji:"🤧"},
  {q:"¿Cuántos litros de sangre bombea tu corazón a lo largo de tu vida?",a:200000000,unit:"litros",hint:"200 millones de litros – ni una piscina olímpica es suficiente.",emoji:"❤️"},
  {q:"¿Qué porcentaje de pantallas de smartphones tienen rastros de materia fecal?",a:16,unit:"%",hint:"Estudio británico – 1 de cada 6 teléfonos.",emoji:"📱"},
  {q:"¿Cuántas especies animales tienen sexo documentado por placer?",a:30,unit:"especies",hint:"Bonobos, delfines, macacos y más.",emoji:"🐬"},
  {q:"¿Qué porcentaje de personas miente en los primeros 10 minutos de conocer a alguien?",a:60,unit:"%",hint:"Hasta 3 mentiras en 10 minutos.",emoji:"🤥"},
  {q:"¿Cuántos gramos de azúcar hay en el torrente sanguíneo de un adulto?",a:5,unit:"gramos",hint:"Una cucharadita de azúcar en todo el torrente sanguíneo.",emoji:"🍬"},
  {q:"¿Cuántas horas pasa una persona besando a lo largo de su vida?",a:336,unit:"horas",hint:"2 semanas de tu vida besando.",emoji:"💋"},
  {q:"¿Cuántos días sobrevive una cucaracha sin cabeza?",a:7,unit:"días",hint:"El cuerpo respira por los poros.",emoji:"🪳"},
  {q:"¿Cuántas veces por noche se despierta brevemente una persona sin notarlo?",a:28,unit:"veces",hint:"Sueño normal – simplemente no lo recordamos.",emoji:"😴"},
  {q:"¿Cuántas calorías quema el sexo en promedio?",a:85,unit:"calorías",hint:"Por sesión – menos que un paseo.",emoji:"❤️"},
  {q:"¿Cuántos minutos dura el sexo en promedio según estudios?",a:5,unit:"minutos",hint:"Desde la penetración hasta el orgasmo – promedio mundial.",emoji:"⏱️"},
  {q:"¿Qué porcentaje de la población mundial está ahora mismo en el baño?",a:1,unit:"% de la población",hint:"80 millones de personas simultáneamente.",emoji:"🚽"},
  {q:"¿Cuántas horas tarda la comida en ser completamente digerida?",a:53,unit:"horas",hint:"53 horas desde la boca hasta el inodoro.",emoji:"💩"},
  {q:"¿Qué porcentaje de personas duerme desnudo?",a:12,unit:"%",hint:"En Alemania – mayor en otros países.",emoji:"😴"},
  {q:"¿Cuántos gramos pesa el cerebro humano?",a:1400,unit:"gramos",hint:"El 2% del peso corporal pero el 20% del consumo energético.",emoji:"🧠"},
  {q:"¿Qué porcentaje de ADN comparten los humanos con los plátanos?",a:60,unit:"% ADN",hint:"Compartimos ADN con casi todos los seres vivos.",emoji:"🍌"},
  {q:"¿Cuántos litros de ácido gástrico se producen al día?",a:2,unit:"litros",hint:"Suficientemente fuerte para disolver metal.",emoji:"⚗️"},
  {q:"¿Qué porcentaje de hombres tiene erección al despertar?",a:90,unit:"%",hint:"Erección matutina – casi a diario.",emoji:"😴"},
  {q:"¿Cuántos gramos de moco tragas al día sin notarlo?",a:1000,unit:"gramos",hint:"1 litro de moco baja por la garganta al día.",emoji:"🤧"},
  {q:"¿Qué porcentaje de parejas roncan los dos?",a:25,unit:"%",hint:"Una de cada cuatro parejas ronca a dúo.",emoji:"😴"},
  {q:"¿Cuántos minutos dura la visita media al baño?",a:6,unit:"minutos",hint:"Los hombres se sientan más tiempo que las mujeres.",emoji:"🚽"},
  {q:"¿Qué porcentaje de mujeres finge el orgasmo?",a:67,unit:"%",hint:"Según estudios – dos de cada tres.",emoji:"🎭"},
  {q:"¿Cuántos mililitros de orina se pierden al reír?",a:1,unit:"mililitro",hint:"Incontinencia por estrés al reír – muy común.",emoji:"😂"},
  {q:"¿Cuántos gramos de cerumen produce un oído al mes?",a:1,unit:"gramo",hint:"Sorprendentemente mucho para un órgano tan pequeño.",emoji:"👂"},
  {q:"¿Cuántas veces se masturba una persona en promedio hasta los 50 años?",a:5000,unit:"veces",hint:"Los hombres significativamente más que las mujeres.",emoji:"🤫"},
  {q:"¿Cuántos gramos pesa la lengua humana?",a:70,unit:"gramos",hint:"70g – un músculo fuerte.",emoji:"👅"},
  {q:"¿Cuántos kilómetros de vasos sanguíneos tiene un humano?",a:100000,unit:"km",hint:"2,5 veces alrededor de la Tierra.",emoji:"❤️"},
  {q:"¿Qué porcentaje de personas tiene un parásito en el cuerpo sin saberlo?",a:50,unit:"%",hint:"En todo el mundo – especialmente en países en desarrollo.",emoji:"🪱"},
  {q:"¿Cuántos gramos pesa un riñón humano?",a:150,unit:"gramos",hint:"Más pequeño de lo que crees.",emoji:"🫘"},
  {q:"¿Cuántos miles de millones de bacterias contiene un gramo de heces?",a:100,unit:"mil millones",hint:"Más densas que en ningún otro lugar del cuerpo.",emoji:"💩"},
  {q:"¿Cuántos metros puede volar la saliva humana al escupir?",a:10,unit:"metros",hint:"El récord mundial es 9,44m.",emoji:"💦"},
  {q:"¿Cuántas calorías tiene una cucharadita de esperma?",a:5,unit:"calorías",hint:"Principalmente fructosa y proteínas.",emoji:"💦"},
  {q:"¿Cuántos gramos de cabello produce el cuero cabelludo al mes?",a:15,unit:"gramos",hint:"Cada cabello crece 1cm al mes.",emoji:"💇"},
  {q:"¿Cuántos decibelios tiene un pedo promedio?",a:50,unit:"decibelios",hint:"Similar a una conversación normal.",emoji:"💨"},
  {q:"¿Cuántos gramos de sudor produce la axila al día?",a:50,unit:"gramos",hint:"El olor viene de las bacterias que lo descomponen.",emoji:"💦"},
  {q:"¿Cuántas horas pasa una persona rascándose a lo largo de su vida?",a:5000,unit:"horas",hint:"Casi 7 meses de rascado puro.",emoji:"😅"},
  {q:"¿Cuántos litros de orina produce un humano en 80 años?",a:40000,unit:"litros",hint:"40.000 litros – un camión cisterna lleno.",emoji:"💛"},
  {q:"¿Qué porcentaje de alemanes se lava las manos después del baño?",a:50,unit:"%",hint:"La mitad miente al responder esto.",emoji:"🧼"},
  {q:"¿Cuántos centímetros crece una uña al mes?",a:3,unit:"mm",hint:"3mm al mes – las uñas de los pies crecen más lento.",emoji:"💅"},
  {q:"¿Cuántas personas mueren al año por cocos que caen sobre su cabeza?",a:150,unit:"personas",hint:"Más que por ataques de tiburones – anualmente.",emoji:"🥥"},
  {q:"¿Cuántas veces tiene sexo una persona de media a lo largo de su vida?",a:5778,unit:"veces",hint:"117 veces al año × 49,4 años activos.",emoji:"❤️"},
  {q:"¿Cuántos minutos de esperanza de vida cuesta cada cigarrillo?",a:11,unit:"minutos",hint:"11 minutos menos por cigarrillo.",emoji:"🚬"},
  {q:"¿Cuántos decibelios puede alcanzar el ronquido humano más fuerte?",a:111,unit:"decibelios",hint:"Más fuerte que una perforadora.",emoji:"😴"},
  {q:"¿Cuántos gramos pesa el globo ocular humano?",a:7,unit:"gramos",hint:"Más pequeño que una pelota de golf.",emoji:"👁️"},
  {q:"¿Cuántas veces respira una persona al día?",a:22000,unit:"veces",hint:"18-20 respiraciones por minuto.",emoji:"💨"},
  {q:"¿Cuántos gramos de grasa quema el cuerpo durmiendo por noche?",a:70,unit:"gramos",hint:"El cuerpo trabaja mientras duermes.",emoji:"😴"},
  {q:"¿Cuántos litros de saliva produce un perro al día?",a:2,unit:"litros",hint:"De ahí la nariz húmeda.",emoji:"🐕"},
  {q:"¿Qué porcentaje de la población está en el baño en este momento?",a:1,unit:"%",hint:"80 millones de personas en cualquier momento.",emoji:"🚽"},
  {q:"¿Cuántos miligramos de sarro se forman en los dientes al día?",a:500,unit:"miligramos",hint:"0,5g al día sin cepillarse.",emoji:"🦷"},
  {q:"¿Cuántas horas sobrevive el esperma sobre superficies?",a:2,unit:"horas",hint:"En superficies secas 2 horas.",emoji:"💦"},
  {q:"¿Cuántos gramos de pelo traga un gato al acicalarse al año?",a:100,unit:"gramos",hint:"Lleva a las bolas de pelo.",emoji:"🐱"},
  {q:"¿Cuántas partes de insecto hay en un tarro de salsa de tomate según la FDA?",a:30,unit:"partes de insecto",hint:"Límite FDA: 30 huevos de mosca o 2 larvas.",emoji:"🍅"},
  {q:"¿Cuántas personas se lesionan en baños en EE.UU. anualmente?",a:40000,unit:"personas",hint:"40.000 lesiones de baño al año.",emoji:"🚽"},
  {q:"¿Cuántas veces se dijo la palabra con F en El Lobo de Wall Street?",a:506,unit:"veces",hint:"Récord de más palabrotas en una película.",emoji:"🎬"},
  {q:"¿Cuántas horas pasa una persona teniendo orgasmos a lo largo de su vida?",a:1,unit:"hora",hint:"6 segundos × 5.778 veces = ~1 hora.",emoji:"😮"},
  {q:"¿Cuántas personas son alcanzadas por un rayo al día en todo el mundo?",a:2000,unit:"personas",hint:"2000 al día – 40-50 de forma mortal.",emoji:"⚡"},
  {q:"¿Cuántas nanopartículas de plástico hay en un litro de agua embotellada?",a:240000,unit:"partículas",hint:"240.000 partículas de nanoplástico por litro.",emoji:"🍶"},
  {q:"¿Cuántos gramos pesa el útero humano?",a:60,unit:"gramos",hint:"Más pequeño que un puño – puede crecer hasta 1kg.",emoji:"👶"},
  {q:"¿Cuántas veces se ríe una persona al día en promedio?",a:17,unit:"veces",hint:"Los niños se ríen mucho más que los adultos.",emoji:"😂"},
  {q:"¿Cuántos miligramos de suciedad se acumulan en el ombligo al año?",a:500,unit:"miligramos",hint:"Aceite, suciedad y piel muerta.",emoji:"🔘"},
  {q:"¿Cuántos minutos tarda el espermatozoide en llegar al óvulo?",a:50,unit:"minutos",hint:"Los más rápidos en 45-60 minutos.",emoji:"🏊"},
  {q:"¿Qué porcentaje de las muertes mundiales ocurren en el baño?",a:25,unit:"%",hint:"Caídas, infartos, ahogamiento.",emoji:"🚿"},
  {q:"¿Cuántas horas pasa una persona a lo largo de su vida cepillándose los dientes?",a:122,unit:"horas",hint:"2 min × 2 veces al día × 75 años.",emoji:"🦷"},
  {q:"¿Qué porcentaje de niños se come los mocos?",a:90,unit:"%",hint:"Casi todos – incluso tiene beneficios inmunológicos.",emoji:"🤧"},
];
