// 🐾 REINO animal – Español
export default [
 {q:"¿Cuántos kg wiegen die Hoden eines Blauwals?",un:70,unit:"kg",hint:"Der Blauwal ist das größte Tier der Erde.",emoji:"🐋"},
 {q:"¿Con qué frecuencia pro minuto schlägt das Herz einer Maus?",un:600,unit:"veces",hint:"Je kleiner das Tier, desto schneller das Herz.",emoji:"🐭"},
 {q:"¿Cuántos Tage trägt ein Elefant sein Junges?",un:645,unit:"días",hint:"rápido 2 Jahre – längste Schwangerschaft aller Landsäugetiere.",emoji:"🐘"},
 {q:"¿Cuántos Liter Milch produziert eine Kuh por día?",un:25,unit:"litros",hint:"Hochleistungskühe können bis zu 50 Liter al día geben.",emoji:"🐄"},
 {q:"¿Cuánto pesa kann ein Riesenkalmar-Auge en Gramm werden?",un:250,unit:"gramos",hint:"Das größte Auge im Tierreich – so groß wie ein Fußball.",emoji:"🦑"},
 {q:"¿Cuántos km/h läuft ein Gepard maximal?",un:112,unit:"km/h",hint:"Er kann diese Höchstgeschwindigkeit nur kurz halten.",emoji:"🐆"},
 {q:"¿Cuántos Magen hat eine Kuh?",un:4,unit:"Mägen",hint:"Pansen, Netzmagen, Blättermagen und Labmagen.",emoji:"🐄"},
 {q:"¿Qué tan alto kann ein Känguru springen en Metern?",un:3,unit:"metros",hint:"Und en der Länge sogar bis zu 9 Meter weit.",emoji:"🦘"},
 {q:"¿Cuánto pesa wird ein ausgewachsener Gorilla maximal en kg?",un:270,unit:"kg",hint:"Trotz Größe sind Gorillas überwiegend Vegetarier.",emoji:"🦍"},
 {q:"¿Cuántos Stunden schläft ein Koala por día?",un:22,unit:"horas",hint:"Eukalyptus ist schwer verdaulich – daher die Müdigkeit.",emoji:"🐨"},
 {q:"¿Cuántos km/h kann ein Schwertfisch schwimmen?",un:110,unit:"km/h",hint:"Der schnellste Fisch im Meer.",emoji:"🐟"},
 {q:"¿Cuánto tiempo lebt eine Königin-Biene en Jahren?",un:5,unit:"años",hint:"Arbeiterinnen leben im Sommer nur 6 Wochen.",emoji:"🐝"},
 {q:"¿Cuántos Zähne hat ein erwachsenes Krokodil?",un:66,unit:"dientes",hint:"Krokodile erneuern ihre Zähne bis zu 50 Mal im Leben.",emoji:"🐊"},
 {q:"¿Cuántos Eier legt eine Königin-Termite por día?",un:30000,unit:"Eier",hint:"Die produktivste Mutter im Insektenreich.",emoji:"🐜"},
 {q:"¿Cuántos Liter Blut hat ein ausgewachsener Elefant?",un:400,unit:"litros",hint:"Das Elefantenherz wiegt allein bis zu 30 kg.",emoji:"🐘"},
 {q:"¿Cuántos Mal kann ein Specht pro Sekunde hämmern?",un:20,unit:"veces",hint:"Sein Gehirn ist durch Spezialanpassungen geschützt.",emoji:"🐦"},
 {q:"¿Cuánto pesa ist das schwerste Vogelei (Strauß) en kg?",un:1.35,unit:"kg",hint:"Strauße legen die größten Eier aller lebenden Vögel.",emoji:"🥚"},
 {q:"¿Cuánto tiempo kann ein Delphin den Atem anhalten en Minuten?",un:15,unit:"minutos",hint:"Delfine schlafen mit einer Gehirnhälfte.",emoji:"🐬"},
 {q:"¿Cuántos Jahre kann ein Grönlandwal leben?",un:211,unit:"años",hint:"Das langlebigste Säugetier der Erde.",emoji:"🐳"},
 {q:"¿Cuánto pesa ist die Zunge eines Blauwals en kg?",un:2700,unit:"kg",hint:"Die Zunge allein wiegt so viel wie ein Elefant.",emoji:"🐋"},
 {q:"¿Cuántos millones Geruchsrezeptoren hat ein Hund?",un:300,unit:"millones",hint:"Menschen haben nur 6 millones – Hunde riechen 50x besser.",emoji:"🐕"},
 {q:"¿Cuántos Meter lang kann ein Bandwurm im Darm werden?",un:25,unit:"metros",hint:"Bandwürmer können jahrelang unbemerkt leben.",emoji:"🪱"},
 {q:"¿Qué tan alto ist der Blutdruck einer Giraffe en mmHg?",un:280,unit:"mmHg",hint:"Nötig um Blut 2 Meter nach oben ins Gehirn zu pumpen.",emoji:"🦒"},
 {q:"¿Cuántos kg Bambus frisst ein Pandabär al día?",un:15,unit:"kg",hint:"Bambus ist sehr nährstoffarm – daher die riesige Menge.",emoji:"🐼"},
 {q:"¿Cuánto tiempo trägt ein Hai seine Jungen en Monaten?",un:24,unit:"meses",hint:"Hammerhaie haben die längste Tragzeit.",emoji:"🦈"},
 {q:"¿Cuántos Augen hat eine Spinne?",un:8,unit:"Augen",hint:"Trotz 8 Augen sehen viele Spinnen sehr schlecht.",emoji:"🕷️"},
 {q:"¿Cuántos km/h erreicht ein Wanderfalke im Sturzflug?",un:320,unit:"km/h",hint:"Das schnellste Tier der Welt im Sturzflug.",emoji:"🦅"},
 {q:"¿Cuántos Tonnen wiegt ein ausgewachsener Blauwal?",un:150,unit:"tons",hint:"Das größte Tier das je auf der Erde gelebt hat.",emoji:"🐋"},
 {q:"¿Cuántos Stunden kann eine Schnecke schlafen am Stück?",un:3,unit:"años",hint:"Schnecken können bis zu 3 Jahre en Kältestarre verbringen.",emoji:"🐌"},
 {q:"¿Cuántos Elektronen-Volt erzeugt ein Zitteraal?",un:600,unit:"Volt",hint:"Volt – genug um einen Menschen zu betäuben.",emoji:"🐍"},
 {q:"¿Cuántos km/h rennt ein Nashorn?",un:55,unit:"km/h",hint:"Trotz ihrer Masse sind Nashörner erstaunlich schnell.",emoji:"🦏"},
 {q:"¿Cuántos Jahre alt kann ein Koi-Fisch werden?",un:226,unit:"años",hint:"Hanako, ein Koi en Japan, lebte 226 Jahre.",emoji:"🐟"},
 {q:"¿Cuántos Knochen hat eine Schlange?",un:300,unit:"huesos",hint:"Je nach Art zwischen 200 und 400 Knochen.",emoji:"🐍"},
 {q:"¿Cuántos Mal pro Sekunde schlägt eine Biene ihre Flügel?",un:200,unit:"veces",hint:"Das erzeugt das charakteristische Summen.",emoji:"🐝"},
 {q:"¿Cuántos Liter Wasser saugt ein Elefant al día?",un:190,unit:"litros",hint:"Der Rüssel fasst bis zu 15 Liter auf einmal.",emoji:"🐘"},
 {q:"¿Cuántos Jahre kann eine Schildkröte ohne Nahrung sobreviven?",un:1,unit:"Jahr",hint:"Schildkröten können ihren Stoffwechsel extrem verlangsamen.",emoji:"🐢"},
 {q:"¿un qué distancia kann ein Flugfisch aus dem Wasser gleiten en Metern?",un:400,unit:"metros",hint:"Flugfische nutzen Wind und Auftrieb zum Gleiten.",emoji:"🐟"},
 {q:"¿Cuántos Gramm wiegt das Herz eines Blauwals?",un:180000,unit:"gramos",hint:"Das Herz ist so groß wie ein kleines Auto.",emoji:"❤️"},
 {q:"¿Cuántos Stunden schläft ein Löwe por día?",un:20,unit:"horas",hint:"Löwen schlafen mehr als Koalas.",emoji:"🦁"},
 {q:"¿Cuántos Meter lang wird eine Riesenschlange (Pythons)?",un:7,unit:"metros",hint:"Der Netzpython ist die längste Schlange der Welt.",emoji:"🐍"},
 {q:"¿Cuántos Eier legt ein weiblicher Oktopus?",un:400000,unit:"Eier",hint:"Sie bewacht sie bis zum Schlüpfen und stirbt danach.",emoji:"🐙"},
 {q:"¿Cuántos km/h läuft ein Strauß?",un:70,unit:"km/h",hint:"Der schnellste laufende Vogel – und kann nicht fliegen.",emoji:"🦜"},
 {q:"¿Cuántos Zähne hat ein Weißer Hai?",un:300,unit:"dientes",hint:"en mehreren Reihen – ständig nachwachsend.",emoji:"🦈"},
 {q:"¿Cuánto pesa wird ein Walross maximal en kg?",un:1700,unit:"kg",hint:"Männliche Walrosse sind deutlich schwerer als Weibchen.",emoji:"🦭"},
 {q:"¿Cuántos Jahre lebt eine Arbeiterin-Biene im Sommer?",un:0.13,unit:"años",hint:"Nur 6 Wochen im Sommer – im Winter bis zu 6 Monate.",emoji:"🐝"},
 {q:"¿Cuántos Arten von Insekten gibt es auf der Erde (millones)?",un:1,unit:"Million Arten",hint:"Über 1 millones bekannte Arten – viele noch unentdeckt.",emoji:"🐛"},
 {q:"¿Cuántos Herzen hat ein Tintenfisch?",un:3,unit:"Herzen",hint:"Zwei pumpen Blut zu den Kiemen, eines zum Körper.",emoji:"🐙"},
 {q:"¿Cuánto tiempo es die Zunge eines Chamäleons im Verhältnis zum Körper?",un:150,unit:"% Körperlänge",hint:"Die Zunge schlägt mit bis zu 26 km/h aus.",emoji:"🦎"},
 {q:"¿Cuántos km/h rennt ein Gepard auf kurzer Strecke?",un:112,unit:"km/h",hint:"Beschleunigt von 0 auf 100 en 3 Sekunden.",emoji:"🐆"},
 {q:"¿Cuántos millones Geruchssensoren hat ein Bär?",un:2100,unit:"millones",hint:"Bären haben den schärfsten Geruchssinn aller Landtiere.",emoji:"🐻"},
 {q:"¿Cuánto pesa wird ein Polarbär maximal en kg?",un:700,unit:"kg",hint:"Das größte Landraubtier der Erde.",emoji:"🐻‍❄️"},
 {q:"¿Cuántos Beine hat ein Tausendfüßer en promedio?",un:750,unit:"Beine",hint:"Nie genau 1000 – trotz des Namens.",emoji:"🐛"},
 {q:"¿Cuánto tiempo kann eine Stubenfliege fliegen ohne zu landen?",un:2,unit:"horas",hint:"Danach braucht sie Ruhe und Nahrung.",emoji:"🪰"},
 {q:"¿Cuántos Jahre alt wird eine Elefantenschildkröte maximal?",un:190,unit:"años",hint:"Harriet lebte bis 2006 und war ~175 Jahre alt.",emoji:"🐢"},
 {q:"¿Cuántos km weit wandert ein Monarch-Schmetterling?",un:4000,unit:"km",hint:"Von Kanada bis Mexiko – jedes Jahr.",emoji:"🦋"},
 {q:"¿Cuántos Gramm wiegt eine Hummel?",un:600,unit:"mg",hint:"Trotz winziger Masse kann sie ein Vielfaches ihres Gewichts tragen.",emoji:"🐝"},
 {q:"¿Cuántos Stunden por día sucht ein Nashorn Nahrung?",un:12,unit:"horas",hint:"Die Hälfte ihres Lebens verbringen sie mit Fressen.",emoji:"🦏"},
 {q:"¿Qué tan alto springt ein Lachs flussaufwärts maximal en Metern?",un:3,unit:"metros",hint:"Lachse springen Wasserfälle hinauf zu ihren Laichgebieten.",emoji:"🐟"},
 {q:"¿Cuántos Gramm Seide produziert ein Seidenspinner für einen Kokon?",un:500,unit:"mg",hint:"Aus einem Kokon kann man bis zu 1500 Meter Seide spinnen.",emoji:"🪱"},
 {q:"¿Cuántos Liter Blut verliert ein Moskito wenn er sticht?",un:0.001,unit:"ml",hint:"Ein Moskito saugt etwa 1-3 mg Blut.",emoji:"🦟"},
 {q:"¿Cuánto pesa wird ein ausgewachsener Nilpferd en Tonnen?",un:3,unit:"tons",hint:"Nach Elefant und Nashorn das drittschwerste Landtier.",emoji:"🦛"},
 {q:"¿Cuántos Stunden schläft eine Giraffe al día?",un:2,unit:"horas",hint:"Giraffen schlafen sehr wenig – en kurzen Phasen.",emoji:"🦒"},
 {q:"¿Cuántos Gramm wiegt ein Kolibri?",un:3,unit:"gramos",hint:"Der kleinste Vogel der Welt wiegt weniger als eine Münze.",emoji:"🐦"},
 {q:"¿Con qué frecuencia schlägt das Herz eines Kolibris pro minuto?",un:1200,unit:"veces",hint:"Das schnellste Herz aller Wirbeltiere.",emoji:"🐦"},
 {q:"¿un qué distancia kann ein Känguru en einem einzigen Sprung?",un:9,unit:"metros",hint:"Und dabei 3 Meter hoch.",emoji:"🦘"},
 {q:"¿Cuánto pesa ist das Gehirn eines Elefanten en kg?",un:5,unit:"kg",hint:"Das schwerste Gehirn aller Landtiere.",emoji:"🐘"},
 {q:"¿Cuántos Kilogramm frisst ein Blauwal al día un Krill?",un:3600,unit:"kg",hint:"rápido 4 Tonnen Krill al día.",emoji:"🐋"},
 {q:"¿Cuántos Stunden kann ein Albatros nonstop fliegen?",un:10,unit:"horas",hint:"Albatrosse schlafen sogar im Flug.",emoji:"🦅"},
 {q:"¿Cuánto tiempo es die Trächtigkeit einer Maus en Tagen?",un:21,unit:"días",hint:"Mäuse können 10 Mal por año trächtig sein.",emoji:"🐭"},
 {q:"¿Cuántos Eier legt eine Königin-Ameise por año?",un:300000,unit:"Eier",hint:"Manche Königinnen leben 30 Jahre und legen al día 800 Eier.",emoji:"🐜"},
 {q:"¿Cuántos km/h läuft ein Schwarzbär?",un:48,unit:"km/h",hint:"Schneller als un humano – man kann vor einem Bären nicht weglaufen.",emoji:"🐻"},
 {q:"¿Qué tan profundo kann ein Potwal tauchen en Metern?",un:3000,unit:"metros",hint:"Das tiefste Tauchgang eines Säugetiers.",emoji:"🐳"},
 {q:"¿Cuántos Kilogramm Nahrung frisst ein Gorilla al día?",un:18,unit:"kg",hint:"Gorillas sind reine Vegetarier.",emoji:"🦍"},
 {q:"¿Cuánto tiempo lebt eine Drohnen-Biene?",un:90,unit:"días",hint:"Drohnen leben nur bis zur Paarung – dann sterben sie.",emoji:"🐝"},
 {q:"¿Cuántos Meter tief gräbt ein Maulwurf seine Tunnel?",un:1,unit:"metros",hint:"Maulwürfe bauen Tunnel-Systeme über 200 Meter Länge.",emoji:"🐀"},
 {q:"¿Cuántos Jahre lebt ein wilder Schimpanse?",un:45,unit:"años",hint:"en Gefangenschaft können sie über 60 Jahre alt werden.",emoji:"🐒"},
 {q:"¿Cuánto pesa ist der Schädel eines Tyrannosaurus Rex en kg?",un:500,unit:"kg",hint:"Einer der größten Schädel aller fleischfressenden Dinosaurier.",emoji:"🦖"},
 {q:"¿Cuántos Federn hat ein Schwan?",un:25000,unit:"Federn",hint:"Wasservögel haben besonders viele Federn für die Isolation.",emoji:"🦢"},
 {q:"¿Cuántos Stunden brütet ein Kaiserpinguin sein Ei?",un:1512,unit:"horas",hint:"63 Tage – ohne Nahrung en antarktischem Winter.",emoji:"🐧"},
 {q:"¿un qué distancia kann ein Gepard en einem Sprung?",un:8,unit:"metros",hint:"Geparden machen enorme Sprünge beim Jagen.",emoji:"🐆"},
 {q:"¿Cuántos Liter Wasser kann ein Elefant mit dem Rüssel aufnehmen?",un:15,unit:"litros",hint:"Der Rüssel ist ein multifunktionales Werkzeug.",emoji:"🐘"},
 {q:"¿Cuántos km/h schlägt eine Mantis-Garnele zu?",un:80,unit:"km/h",hint:"Der schnellste Schlag im Tierreich.",emoji:"🦐"},
 {q:"¿Cuántos millones Leukozyten hat un humano pro mm³ Blut?",un:7000,unit:"pro mm³",hint:"Immunzellen im Blut.",emoji:"🔬"},
 {q:"¿Cuántos Stunden schläft ein Delfin por día?",un:8,unit:"horas",hint:"Immer mit einer Gehirnhälfte – die andere bleibt wach.",emoji:"🐬"},
 {q:"¿Cuánto pesa ist die Leber eines Blauwals en kg?",un:1000,unit:"kg",hint:"Alle Organe des Blauwals sind riesig.",emoji:"🐋"},
 {q:"¿Cuántos Eier kann eine Meeresschildkröte pro Saison legen?",un:200,unit:"Eier",hint:"Nur etwa 1% der Jungtiere sobreviven bis zur Adultheit.",emoji:"🐢"},
 {q:"¿Cuántos km weit fliegt ein Zugvogel im Jahr?",un:70000,unit:"km",hint:"Der Küstenseeschwalbe fliegt am weitesten.",emoji:"🐦"},
 {q:"¿Cuánto tiempo kann ein Kamel ohne Wasser sobreviven en Tagen?",un:15,unit:"días",hint:"Der Höcker speichert Fett, nicht Wasser.",emoji:"🐪"},
 {q:"¿Cuántos Stunden lebt eine Eintagsfliege als Imago?",un:24,unit:"horas",hint:"Als Larve lebt sie bis zu 3 Jahre.",emoji:"🪲"},
 {q:"¿Cuánto pesa ist das Gehirn eines Pottwals en kg?",un:7,unit:"kg",hint:"Das schwerste Gehirn aller bekannten Tiere.",emoji:"🐳"},
 {q:"¿Cuántos Flügelschläge macht eine Kolibri pro Sekunde?",un:80,unit:"veces",hint:"So schnell, dass die Flügel unsichtbar werden.",emoji:"🐦"},
 {q:"¿Cuántos km/h läuft eine Gazelle?",un:90,unit:"km/h",hint:"Gazellen sind rápido so schnell wie Geparden.",emoji:"🦌"},
 {q:"¿Qué tan profundo gräbt ein Erdhörnchen seinen Bau en Metern?",un:3,unit:"metros",hint:"Mit mehreren Ein- und Ausgängen.",emoji:"🐿️"},
 {q:"¿Cuántos Stacheln hat ein Igel?",un:6000,unit:"Stacheln",hint:"Stacheln sind modifizierte Haare.",emoji:"🦔"},
 {q:"¿Cuántos Jahre lebt ein Hummer?",un:100,unit:"años",hint:"Hummer altern praktisch nicht – sie werden nur durch Jäger oder Hunger begrenzt.",emoji:"🦞"},
 {q:"¿Cuántos Mal schlägt das Herz einer Schlange pro minuto?",un:40,unit:"veces",hint:"Schlangen haben einen viel langsameren Herzschlag als Säugetiere.",emoji:"🐍"},
 {q:"¿un qué distancia kann eine Springspinne springen en cm?",un:50,unit:"cm",hint:"Das 50-fache ihrer Körperlänge.",emoji:"🕷️"},
 {q:"¿Cuántos kg frisst ein Tiger al día?",un:8,unit:"kg",hint:"Tiger fressen seltener aber dafür viel auf einmal.",emoji:"🐯"},
 {q:"¿Cuántos Liter Speichel produziert eine Kuh al día?",un:200,unit:"litros",hint:"Wiederkäuen erfordert enorm viel Speichel.",emoji:"🐄"},
 {q:"¿Cuánto tiempo schläft ein Braunbär im Winterschlaf en Monaten?",un:6,unit:"meses",hint:"Kein echter Tiefschlaf – sie können jederzeit aufwachen.",emoji:"🐻"},
 {q:"¿Cuántos Kilometer wandert ein Weißwal por año?",un:10000,unit:"km",hint:"Weißwale sind wanderfreudige Meeressäuger.",emoji:"🐳"},
 {q:"¿Cuántos Stunden lebt eine Biene nach dem Stich?",un:1,unit:"Stunde",hint:"Der Stachel verbleibt im Opfer – die Biene stirbt.",emoji:"🐝"},
 {q:"¿Cuánto pesa ist ein Elefantenzahn (Stoßzahn) maximal en kg?",un:100,unit:"kg",hint:"Stoßzähne wachsen ein Leben lang.",emoji:"🐘"},
 {q:"¿Cuántos Gramm wiegt ein neugeborenes Känguru?",un:1,unit:"gramos",hint:"Das Joeys kriecht nach der Geburt en den Beutel.",emoji:"🦘"},
 {q:"¿Cuántos km/h schwimmt ein Blauwal?",un:30,unit:"km/h",hint:"Bei Gefahr können sie kurze Sprints einlegen.",emoji:"🐋"},
 {q:"¿Cuánto tiempo lebt eine Taschenkrabbe en Jahren?",un:100,unit:"años",hint:"Krabben können sehr alt werden.",emoji:"🦀"},
 {q:"¿Cuántos Gramm wiegt ein Kolibri-Nest?",un:2,unit:"gramos",hint:"Winzige Nester aus Spinnweben und Flechten.",emoji:"🐦"},
 {q:"¿Cuántos Stunden fliegt eine Hornisse al día?",un:8,unit:"horas",hint:"Hornissen sind aktive Jäger.",emoji:"🐝"},
 {q:"¿un qué distancia kann ein Delfin einen Ball balancieren en Stunden?",un:3,unit:"horas",hint:"Delfine sind die intelligentesten Meerestiere.",emoji:"🐬"},
 {q:"¿Cuántos Jahre kann ein Krokodil ohne Nahrung sobreviven?",un:3,unit:"años",hint:"Krokodile haben einen extrem niedrigen Stoffwechsel.",emoji:"🐊"},
 {q:"¿Cuánto pesa ist der Penis eines Blauwals en kg?",un:450,unit:"kg",hint:"Das größte Geschlechtsorgan im Tierreich.",emoji:"🐋"},
 {q:"¿Cuánto tiempo ist ein Blauwal-Penis en Metern?",un:2.7,unit:"metros",hint:"Proportional zum Körper aber das absolut größte.",emoji:"🐋"},
 {q:"¿Cuántos Eizellen produziert eine Ozean-Sonnenblume pro Saison?",un:300000000,unit:"Eier",hint:"300 millones Eier – die meisten aller Wirbeltiere.",emoji:"🐟"},
 {q:"¿Cuántos Liter Blut pumpt ein Elefantenherz pro minuto?",un:300,unit:"litros",hint:"Das Elefantenherz wiegt 25 kg.",emoji:"🐘"},
 {q:"¿Cuántos Stunden kann eine Nacktmull-Ratte ohne Sauerstoff sobreviven?",un:18,unit:"horas",hint:"Nacktmull-Ratten sind gegen Sauerstoffmangel resistent.",emoji:"🐀"},
 {q:"¿Cuánto pesa ist das Gehirn eines Octopus en Gramm?",un:40,unit:"gramos",hint:"Sehr klein aber extrem effizient.",emoji:"🐙"},
 {q:"¿Cuántos Chromatophoren hat ein Tintenfisch?",un:10000000,unit:"Chromatophoren",hint:"Diese Farbzellen ermöglichen blitzschnelle Farbwechsel.",emoji:"🦑"},
 {q:"¿Cuántos Meter lang ist ein Bandwurm maximal?",un:30,unit:"metros",hint:"Fischbandwürmer können bis zu 30m lang werden.",emoji:"🪱"},
 {q:"¿Cuántos Mal pro Nacht hört eine Eule?",un:360,unit:"Grad",hint:"Eulen können den Kopf 270 Grad drehen.",emoji:"🦉"},
 {q:"¿Cuánto pesa ist ein Ochsen-Frosch en kg?",un:3,unit:"kg",hint:"Der schwerste Frosch der Welt.",emoji:"🐸"},
 {q:"¿Cuántos Liter Honig produziert ein Bienenvolk por año?",un:30,unit:"litros",hint:"Für ein Glas Honig fliegen Bienen 80.000 km.",emoji:"🍯"},
 {q:"¿Cuánto tiempo es die Trächtigkeit eines Schwarzen Rhinozeros en Tagen?",un:450,unit:"días",hint:"15 Monate – eine der längsten Tragezeiten.",emoji:"🦏"},
 {q:"¿Cuántos Stunden lebt eine Eintagsfliegen-Larve bevor sie schlüpft?",un:26280,unit:"horas",hint:"3 Jahre als Larve, dann 1 Tag als Erwachsener.",emoji:"🪲"},
 {q:"¿Qué tan profundo taucht ein Kaiserpinguin maximal en Metern?",un:565,unit:"metros",hint:"Der tieftauchende Vogel der Welt.",emoji:"🐧"},
 {q:"¿Cuántos Gramm wiegt das Herz eines Pferdes?",un:4500,unit:"gramos",hint:"Das große Herz ist der Schlüssel zur Ausdauer.",emoji:"🐴"},
 {q:"¿un qué distancia kann ein Lemur springen en Metern?",un:10,unit:"metros",hint:"Lemure sind erstaunliche Springer.",emoji:"🐒"},
 {q:"¿Cuántos km/h kann eine Libelle fliegen?",un:55,unit:"km/h",hint:"Eine der schnellsten fliegenden Insekten.",emoji:"🪲"},
 {q:"¿Cuánto tiempo lebt eine Dragonfly en Wochen als Erwachsener?",un:4,unit:"semanas",hint:"Als Larve lebt sie bis zu 5 Jahre.",emoji:"🪲"},
 {q:"¿Cuánto pesa ist ein ausgewachsenes Nilpferd-Zahn en kg?",un:3,unit:"kg",hint:"Die Eckzähne sind reine Waffen.",emoji:"🦛"},
 {q:"¿Cuántos Tentakel hat ein Oktopus?",un:8,unit:"Tentakel",hint:"Jeder Arm hat eigene Nervenzellen.",emoji:"🐙"},
 {q:"¿un qué distancia kann ein Flachlandgorilla seinen Ruf hören en km?",un:2,unit:"km",hint:"Gorillas kommunizieren über weite Distanzen.",emoji:"🦍"},
 {q:"¿Cuántos Mal pro Sekunde bewegt ein Schwertfisch die Schwanzflosse?",un:3,unit:"veces",hint:"Kraftvolle langsame Bewegungen für hohe Geschwindigkeit.",emoji:"🐟"},
 {q:"¿Cuánto tiempo es die Nasenspitze eines Elefanten-Rüssels?",un:250,unit:"cm",hint:"Der Rüssel ist der verlängerte Nasenrücken.",emoji:"🐘"},
 {q:"¿Cuántos Liter Wasser trinkt ein Kamel auf einmal nach der Wüste?",un:100,unit:"litros",hint:"en 13 Minuten kann ein Kamel 100 Liter trinken.",emoji:"🐪"},
 {q:"¿Cuánto pesa ist ein Blauwalhoden en kg?",un:35,unit:"kg",hint:"Jeder Hoden wiegt erstaunlich viel kg – zusammen 70 kg.",emoji:"🐋"},
 {q:"¿Cuántos Stunden alt werden Libellen-Larven bevor sie schlüpfen?",un:35040,unit:"horas",hint:"4 Jahre als Larve im Wasser.",emoji:"🪲"},
 {q:"¿Cuántos Farben kann ein Tintenfisch gleichzeitig anzeigen?",un:30,unit:"Farben",hint:"Obwohl farbenblind – der Farbwechsel dient der Tarnung.",emoji:"🦑"},
 {q:"¿un qué velocidad regeneriert ein Seestern seinen Arm en Wochen?",un:52,unit:"semanas",hint:"Ein Jahr – und aus dem abgetrennten Arm wächst ein neuer Seestern.",emoji:"⭐"},
 {q:"¿Cuántos Jahre kann eine Qualle (Turritopsis dohrnii) theoretisch leben?",un:9999,unit:"años",hint:"Die biologisch unsterbliche Qualle kann sich unbegrenzt verjüngen.",emoji:"🪼"},
 {q:"¿Cuántos km/h kann ein Gepard auf 100m beschleunigen?",un:75,unit:"km/h",hint:"Beschleunigung von 0 auf 75 en 2 Sekunden.",emoji:"🐆"},
 {q:"¿Cuántos Kilogramm wiegt ein ausgewachsener Jaguar?",un:100,unit:"kg",hint:"Der schwerste Großkatze Amerikas.",emoji:"🐆"},
 {q:"¿Cuántos Augen hat eine Libelle?",un:30000,unit:"Facetten",hint:"Zusammengesetzte Augen mit 30.000 Einzellinsen.",emoji:"🪲"},
 {q:"¿un qué distancia kann ein Springer-Frosch springen en cm?",un:530,unit:"cm",hint:"Vielfaches der eigenen Körperlänge.",emoji:"🐸"},
 {q:"¿Cuántos Stunden al día ist eine Hauskatze aktiv?",un:5,unit:"horas",hint:"Hauskatzen schlafen 16-20 Stunden al día.",emoji:"🐱"},
 {q:"¿Cuántos Gramm Honig isst ein Bär en einem Sommer?",un:40000,unit:"gramos",hint:"40 kg Honig – Bären lieben Bienenstöcke.",emoji:"🐻"},
 {q:"¿Cuántos km/h kann ein Tintenfisch schwimmen?",un:40,unit:"km/h",hint:"Durch rückwärtiges Ausstoßen von Wasser.",emoji:"🦑"},
 {q:"¿Cuánto tiempo es die Zunge eines Ameisenbären en cm?",un:60,unit:"cm",hint:"Die klebrige Zunge fährt 150 Mal pro minuto aus.",emoji:"🐜"},
 {q:"¿Cuántos Stunden am Tag weidet ein Pferd?",un:16,unit:"horas",hint:"Pferde fressen rápido nonstop.",emoji:"🐴"},
 {q:"¿Cuánto pesa ist ein ausgewachsener Gorilla-Arm en kg?",un:15,unit:"kg",hint:"Gorillas sind 6 Mal stärker als Menschen.",emoji:"🦍"},
 {q:"¿Cuántos Liter Blut pumpt ein Giraffenherz pro minuto?",un:60,unit:"litros",hint:"Das Giraffenherz wiegt 10 kg.",emoji:"🦒"},
 {q:"¿Cuántos km kann eine Wüstenameise ohne Orientierungshilfe navigieren?",un:50,unit:"km",hint:"Sie nutzen Polarisationsmuster des Himmels.",emoji:"🐜"},
 {q:"¿Cuántos Knochen hat ein Delfin?",un:200,unit:"huesos",hint:"Delfine haben Knochen wo einst Hinterbeine waren.",emoji:"🐬"},
 {q:"¿Qué tan profundo können Maulwürfe ihre Tunnels anlegen?",un:70,unit:"cm",hint:"Haupttunnel liegen tiefer als Jagdtunnel.",emoji:"🐀"},
 {q:"¿Cuántos Stunden kann ein Flamingo auf einem Bein stehen?",un:4,unit:"horas",hint:"Das Stehen auf einem Bein kostet weniger Energie.",emoji:"🦩"},
 {q:"¿Cuántos Ton frisst ein Blauwal un einem Tag?",un:3.6,unit:"tons",hint:"rápido 4 Tonnen Krill al día.",emoji:"🐋"},
 {q:"¿un qué distancia kann eine Heuschrecke springen en Metern?",un:1,unit:"metros",hint:"Das 20-fache ihrer eigenen Körperlänge.",emoji:"🦗"},
 {q:"¿Cuántos Jahre kann ein Elefant leben?",un:70,unit:"años",hint:"en Gefangenschaft werden sie manchmal über 80.",emoji:"🐘"},
 {q:"¿Cuánto pesa ist ein neugeborener Blauwal en Tonnen?",un:2.7,unit:"tons",hint:"Das Größte Neugeborene der Welt.",emoji:"🐋"},
 {q:"¿Cuántos Stunden schläft ein Totenkopf-Äffchen al día?",un:11,unit:"horas",hint:"Totenkopfäffchen sind echte Schläfer.",emoji:"🐒"},
 {q:"¿Cuánto tiempo es ein Elefantenrüssel en Metern?",un:2,unit:"metros",hint:"Er hat über 40.000 Muskeln.",emoji:"🐘"},
 {q:"¿Cuántos Eier legt eine Königin-Ameise al día?",un:800,unit:"Eier",hint:"Über ihr ganzes Leben bis zu 30 millones Eier.",emoji:"🐜"},
 {q:"¿Cuánto tiempo es die Trächtigkeit eines Schwertwals en Monaten?",un:17,unit:"meses",hint:"Orcas haben eine der längsten Tragezeiten.",emoji:"🐋"},
 {q:"¿Cuántos Stunden pasa ein Tier im Wasser al día (Nilpferd)?",un:16,unit:"horas",hint:"Nilpferde kühlen sich und schützen ihre Haut.",emoji:"🦛"},
 {q:"¿Cuántos Gramm wiegt ein Pfauenschwanz-Feder?",un:5,unit:"gramos",hint:"Trotz ihrer Größe extrem leicht.",emoji:"🦚"},
 {q:"¿Cuántos Stacheln hat ein Igel auf dem Rücken?",un:5000,unit:"Stacheln",hint:"Jeder Stachel ist ein modifiziertes Haar.",emoji:"🦔"},
 {q:"¿un qué distancia kann ein Fliegendes Eichhörnchen gleiten en Metern?",un:90,unit:"metros",hint:"Mit der Gleitfalte zwischen Vorder- und Hinterbeinen.",emoji:"🐿️"},
 {q:"¿Cuántos km/h läuft ein Erdferkel?",un:40,unit:"km/h",hint:"Überraschend schnell für ein scheinbar gemächliches Tier.",emoji:"🐷"},
 {q:"¿Cuánto pesa ist ein ausgewachsener männlicher Elefant-Rüsseltier en kg?",un:6000,unit:"kg",hint:"Afrikanische Elefanten sind schwerer als asiatische.",emoji:"🐘"},
 {q:"¿Cuántos Liter Milch trinkt ein Blauwal-Baby al día?",un:600,unit:"litros",hint:"Es wächst al día um 90 kg.",emoji:"🐋"},
 {q:"¿Cuántos Stunden pasa ein Flamingo im Wasser al día?",un:12,unit:"horas",hint:"Flamingos filtern Nahrung aus Schlamm.",emoji:"🦩"},
 {q:"¿Cuánto tiempo es die Trächtigkeit eines Nashorns en Monaten?",un:16,unit:"meses",hint:"Nashörner bekommen nur alle 2-5 Jahre ein Junges.",emoji:"🦏"},
 {q:"¿Cuántos Gramm wiegt eine Honigbiene?",un:100,unit:"mg",hint:"Nur 100 Milligramm – aber immens wichtig.",emoji:"🐝"},
 {q:"¿un qué distancia kann ein Fliegender Fisch aus dem Wasser herausgleiten?",un:400,unit:"metros",hint:"Flugfische nutzen Wind und Auftrieb.",emoji:"🐟"},
 {q:"¿Cuántos Jahre lebt ein Walross?",un:40,unit:"años",hint:"Walrosse werden en der Wildnis bis zu 40 Jahre alt.",emoji:"🦭"},
 {q:"¿Cuánto pesa ist die Schildkrötenpanzer eines Riesenschildkröte en kg?",un:30,unit:"kg",hint:"Der Panzer macht ein Drittel des Körpergewichts aus.",emoji:"🐢"},
 {q:"¿Cuántos Stunden am Tag reinigt sich eine Katze?",un:5,unit:"horas",hint:"Ein Drittel ihrer Wachzeit verbringen Katzen mit Putzen.",emoji:"🐱"},
 {q:"¿Cuántos Gramm wiegt ein Pinguin-Ei?",un:450,unit:"gramos",hint:"Kaiserpinguin-Eier sind riesig im Verhältnis zum Körper.",emoji:"🐧"},
 {q:"¿un qué distancia kann ein Gepard seinen Geruchssinn nutzen en km?",un:3,unit:"km",hint:"Geparden nutzen hauptsächlich das Sehen.",emoji:"🐆"},
 {q:"¿Cuántos Zähne hat ein Delfin?",un:100,unit:"dientes",hint:"Delfine benutzen Zähne zum Fangen, nicht zum Kauen.",emoji:"🐬"},
 {q:"¿Cuánto tiempo es die Zunge einer Kuh en cm?",un:45,unit:"cm",hint:"Kühe lecken sich die Nase damit sauber.",emoji:"🐄"},
 {q:"¿Cuántos Stacheln hat ein Stachelrochen?",un:1,unit:"Stachel",hint:"Nur ein Giftstachel – aber sehr schmerzhaft.",emoji:"🐟"},
 {q:"¿Cuánto pesa ist ein Gorilla-Silberrücken en kg?",un:250,unit:"kg",hint:"Silberrücken dominieren ihre Gruppe.",emoji:"🦍"},
 {q:"¿un qué distancia kann ein Springhase springen en Metern?",un:3,unit:"metros",hint:"Springhasen sind afrikanische Nager.",emoji:"🐇"},
 {q:"¿Cuántos km/h erreicht eine Schildkröte beim Schwimmen?",un:35,unit:"km/h",hint:"Lederschildkröten sind erstaunlich schnelle Schwimmer.",emoji:"🐢"},
 {q:"¿Cuántos Gramm Futter frisst eine Raupe al día im Verhältnis zum peso corporal?",un:200,unit:"% peso corporal",hint:"Raupen verdoppeln ihr Gewicht en Tagen.",emoji:"🐛"},
 {q:"¿Cuántos Stunden lebt eine Hausfliegenmaggot bis zur Verpuppung?",un:240,unit:"horas",hint:"10 Tage als Made, dann Puppe.",emoji:"🪰"},
 {q:"¿Cuánto tiempo es der Dünndarm einer Kuh en Metern?",un:40,unit:"metros",hint:"Kühe haben ein sehr langes Verdauungssystem.",emoji:"🐄"},
 {q:"¿Cuántos Liter Speichel produziert ein Pferd al día?",un:40,unit:"litros",hint:"Pferde brauchen viel Speichel für die Verdauung.",emoji:"🐴"},
 {q:"¿Cuánto pesa ist ein Schimpansen-Arm im Vergleich zu einem menschlichen?",un:2,unit:"x stärker",hint:"Schimpansen sind doppelt so stark wie Menschen.",emoji:"🐒"},
 {q:"¿un qué distancia wandert ein Elch por año en km?",un:300,unit:"km",hint:"Elche folgen Nahrung und Wetter.",emoji:"🦌"},
 {q:"¿Cuántos Stunden braucht eine Schlange für die Verdauung einer großen Mahlzeit?",un:168,unit:"horas",hint:"Eine Woche für ein großes Tier.",emoji:"🐍"},
 {q:"¿Cuántos Gramm wächst ein Blauwal-Baby al día?",un:90000,unit:"gramos",hint:"90 kg al día – 7 Monate lang gestillt.",emoji:"🐋"},
 {q:"¿un qué distancia kann ein Albatros en einem einzigen Flug zurücklegen?",un:10000,unit:"km",hint:"Albatrosse umrunden die Erde im Südpolarmeer.",emoji:"🦅"},
 {q:"¿Cuántos Jahre ist ein Elefant geschlechtsreif?",un:14,unit:"años",hint:"Elefantenbullen treten erst mit 14 en die Brunst.",emoji:"🐘"},
 {q:"¿Cuántos Liter Blut hat ein Nashorn?",un:20,unit:"litros",hint:"Proportional weniger als ein Elefant.",emoji:"🦏"},
 {q:"¿Cuánto tiempo es die Trächtigkeit eines Orcas en Monaten?",un:17,unit:"meses",hint:"Eine der längsten Tragezeiten unter Meeressäugern.",emoji:"🐋"},
 {q:"¿Cuántos Gramm frisst ein Igel al día?",un:70,unit:"gramos",hint:"Insekten, Würmer und kleine Wirbeltiere.",emoji:"🦔"},
 {q:"¿un qué distancia kann ein Springbock en einem Sprung?",un:15,unit:"metros",hint:"Springböcke machen hohe Luftsprünge als Warnsignal.",emoji:"🦌"},
 {q:"¿Cuántos Federn verliert ein Vogel al año beim Mausern?",un:10000,unit:"Federn",hint:"Vögel erneuern ihr Gefieder al año komplett.",emoji:"🐦"},
 {q:"¿Cuánto pesa kann ein Riesenkalmars Mantel en kg werden?",un:150,unit:"kg",hint:"Riesenkalmare sind die größten wirbellosen Tiere.",emoji:"🦑"},
 {q:"¿Cuántos Stunden lebt eine Stubenfliege insgesamt?",un:500,unit:"horas",hint:"Nur 3 Wochen – en dieser Zeit legen sie Eier.",emoji:"🪰"},
 {q:"¿Cuántos Zellen hat ein Regenwurm?",un:1000,unit:"Segmente",hint:"Regenwürmer können en jedem Segment nachwachsen.",emoji:"🪱"},
 {q:"¿un qué distancia wandert ein Monarch-Schmetterling por día?",un:80,unit:"km",hint:"en 2 Monaten von Kanada nach Mexiko.",emoji:"🦋"},
 {q:"¿Cuánto pesa ist ein Schimpansen-Gehirn im Vergleich zum Menschen en %?",un:33,unit:"% des Menschengehirns",hint:"Schimpansen-Gehirn wiegt ~400g, menschliches ~1400g.",emoji:"🐒"},
 {q:"¿Cuántos Stunden al día pasa ein Orang-Utan en Bäumen?",un:24,unit:"horas",hint:"Orang-Utans sind die größten Baumklettertiere.",emoji:"🦧"},
 {q:"¿Cuántos Eier legt eine Ozean-Qualle por año?",un:45000,unit:"Eier",hint:"Quallen können sich auch vegetativ vermehren.",emoji:"🪼"},
 {q:"¿un qué distancia kann eine Flossenfüßer-Robbe schwimmen al día?",un:100,unit:"km",hint:"Robben sind ausdauernde Schwimmer.",emoji:"🦭"},
 {q:"¿Cuánto pesa ist ein Erdwurm en Gramm?",un:5,unit:"gramos",hint:"Ein normaler Regenwurm wiegt 3-10g.",emoji:"🪱"},
 {q:"¿un qué distancia können Elefanten eine Wasserstelle riechen en km?",un:19,unit:"km",hint:"Elefanten haben den feinsten Geruchssinn aller Landtiere.",emoji:"🐘"},
 {q:"¿Cuántos Stunden braucht ein Schmetterling für die Metamorphose?",un:336,unit:"horas",hint:"2 Wochen im Kokon.",emoji:"🦋"},
 {q:"¿Cuántos kg Gras frisst ein Pferd al día?",un:11,unit:"kg",hint:"Pferde sind reine Pflanzenfresser.",emoji:"🐴"},
 {q:"¿un qué distancia kann ein Seehund tauchen en Metern?",un:300,unit:"metros",hint:"Seehunde können bis zu 30 Minuten tauchen.",emoji:"🦭"},
 {q:"¿Cuántos Zähne hat ein Hecht?",un:700,unit:"dientes",hint:"Hechte haben mehrere Reihen kleiner Zähne.",emoji:"🐟"},
 {q:"¿Cuánto pesa ist ein Marien-Käfer en Milligramm?",un:25,unit:"mg",hint:"Trotz winziger Größe frisst er al día 100 Blattläuse.",emoji:"🐞"},
 {q:"¿un qué distancia kann eine Wüstenspringmaus en einem Sprung?",un:3,unit:"metros",hint:"Relative Sprungweite: 45x die eigene Körperlänge.",emoji:"🐭"},
 {q:"¿Cuántos Stunden lebt ein Schmetterlingsweibchen nach der Paarung?",un:2,unit:"semanas",hint:"Manche Schmetterlinge leben nur wenige Tage.",emoji:"🦋"},
 {q:"¿Cuánto pesa ist ein Pelikan-Beutel wenn voll en Liter?",un:13,unit:"litros",hint:"Der Kehlsack fasst mehr als der Magen.",emoji:"🐦"},
 {q:"¿Cuántos kg Fisch frisst ein ausgewachsener Weißer Hai al día?",un:11,unit:"kg",hint:"Haie fressen selten – dafür viel auf einmal.",emoji:"🦈"},
 {q:"¿un qué distancia können Wale Töne unter Wasser hören en km?",un:3000,unit:"km",hint:"Finnwale kommunizieren über Tausende Kilometer.",emoji:"🐋"},
 {q:"¿Cuántos Stunden al día pasa ein Faultier mit Bewegen?",un:3,unit:"horas",hint:"Der Rest des Tages wird mit Schlafen verbracht.",emoji:"🦥"},
 {q:"¿Cuánto pesa ist die Leber eines Weißen Hais en kg?",un:500,unit:"kg",hint:"Die enorme Leber dient als Auftriebsorgan.",emoji:"🦈"},
 {q:"¿Cuánto tiempo es die Trächtigkeit eines Gürteltiers en Monaten?",un:4,unit:"meses",hint:"Gürteltiere gebären immer eineiige Vierlings.",emoji:"🐾"},
 {q:"¿un qué distancia springt ein Delfin aus dem Wasser en Metern?",un:6,unit:"metros",hint:"Es un importante medio de comunicación.",emoji:"🐬"},
 {q:"¿Cuántos Stunden lebt eine Stubenfliege als Larve?",un:120,unit:"horas",hint:"5 Tage als Maggot.",emoji:"🪰"},
 {q:"¿Cuánto pesa ist ein ausgewachsener Schimpansen en kg?",un:60,unit:"kg",hint:"Trotz geringerer Größe 6x stärker als un humano.",emoji:"🐒"},
 {q:"¿Cuántos Tentakel hat eine Qualle?",un:80,unit:"Tentakel",hint:"Je nach Art zwischen 4 und hunderten Tentakeln.",emoji:"🪼"},
 {q:"¿un qué distancia kann ein Krokodil aus dem Wasser herausspringen?",un:1.5,unit:"metros",hint:"Krokodile sind überraschend agil.",emoji:"🐊"},
 {q:"¿Cuántos Gramm frisst eine Hausmaus al día?",un:5,unit:"gramos",hint:"Ein Siebtel ihres Körpergewichts al día.",emoji:"🐭"},
 {q:"¿Cuánto pesa ist ein weiblicher Elefant maximal en Tonnen?",un:4,unit:"tons",hint:"Weibliche Elefanten sind kleiner als die Männchen.",emoji:"🐘"},
 {q:"¿Cuántos Stunden kann ein Hamster al día im Rad laufen?",un:8,unit:"horas",hint:"Hamster legen im Rad bis zu 20 km pro Nacht zurück.",emoji:"🐹"},
 {q:"¿un qué distancia kann ein Kugelfisch aufblähen en cm Durchmesser?",un:90,unit:"cm",hint:"Kugelfische saugen Wasser un um sich aufzublähen.",emoji:"🐡"},
 {q:"¿Cuántos Liter Milch trinkt ein Elefantenbaby al día?",un:10,unit:"litros",hint:"Elefantenbabys werden 2-3 Jahre gestillt.",emoji:"🐘"},
 {q:"¿Cuánto pesa ist ein Spinnwebnetz en Milligramm?",un:0.5,unit:"mg",hint:"Unglaublich leicht aber stärker als Stahl.",emoji:"🕸️"},
 {q:"¿Cuánto tiempo es die Trächtigkeit eines Dachses en Wochen?",un:7,unit:"semanas",hint:"Dachse legen die Trächtigkeit auf günstige Jahreszeiten aus.",emoji:"🦡"},
 {q:"¿Cuántos Stunden schläft ein Gorilla al día?",un:12,unit:"horas",hint:"Gorillas bauen al día neue Schlafnester.",emoji:"🦍"},
 {q:"¿un qué distancia kann ein Weißer Hai seine Kiefer vorschnellen?",un:30,unit:"cm",hint:"Der Kiefer schnellt beim Beißen weit vor.",emoji:"🦈"},
 {q:"¿Cuántos Eier legt eine Riesenmeeresschildkröte en einem Nest?",un:100,unit:"Eier",hint:"Sie legen mehrere masculino pro Saison.",emoji:"🐢"},
 {q:"¿Cuántos Stunden al día pasa ein Fisch mit Schlafen?",un:4,unit:"horas",hint:"Fische schlafen mit offenen Augen.",emoji:"🐟"},
 {q:"¿un qué distancia können Elefanten kommunizieren por Infraschall en km?",un:10,unit:"km",hint:"Tiefe Töne propagieren weit durch den Boden.",emoji:"🐘"},
 {q:"¿Cuántos kg Nahrung frisst ein Nilpferd al día?",un:40,unit:"kg",hint:"Nilpferde fressen nachts un Land.",emoji:"🦛"},
 {q:"¿Cuánto pesa ist ein Gepard-Baby bei Geburt en Gramm?",un:250,unit:"gramos",hint:"Geparden sind bei Geburt blind und hilflos.",emoji:"🐆"},
 {q:"¿Cuántos Stunden dauert eine Tiger-Jagd?",un:1,unit:"Stunde",hint:"Nur 1 von 10 Jagdversuchen ist erfolgreich.",emoji:"🐯"},
 {q:"¿un qué distancia können Delfinpfeifen unter Wasser gehört werden en km?",un:40,unit:"km",hint:"Delfine kommunizieren über enorme Distanzen.",emoji:"🐬"},
 {q:"¿Cuántos Gramm wiegt ein Stachel einer Biene?",un:3,unit:"mg",hint:"Nur 3 Milligramm aber tödliches Gift.",emoji:"🐝"},
 {q:"¿Qué tan profundo kann eine Langschwanzkatze ihr Revier markieren en Metern?",un:50,unit:"cm Höhe",hint:"Markierungen werden auf Augenhöhe angebracht.",emoji:"🐈"},
 {q:"¿Cuántos Stunden al día gehen Wölfe auf Jagd?",un:8,unit:"horas",hint:"Wölfe legen al día 30-50 km zurück.",emoji:"🐺"},
];