// 💰 DINERO Y PRECIOS – Español
export default [
 {q:"¿Cuánto kostete das teuerste je verkaufte Gemälde (Salvator Mundi) en millones Dollar?",un:450,unit:"millones de $",hint:"2017 bei Christie's versteigert.",emoji:"🖼️"},
 {q:"¿Cuántos mil millones Dollar ist Jeff Bezos reich?",un:170,unit:"mil millones de $",hint:"Schwankt – Stand 2024 ca. 170 Mrd.",emoji:"💰"},
 {q:"¿Cuánto kostet eine Flasche Krug Grande Cuvée Champagner?",un:200,unit:"Euro",hint:"Hochwertigster Champagner im Standard-Sortiment.",emoji:"🥂"},
 {q:"¿Cuánto kostete das teuerste Haus der Welt (Villa Les Cèdres) en millones Euro?",un:350,unit:"millones de €",hint:"Villa en Cap-Ferrat, Südfrankreich.",emoji:"🏰"},
 {q:"¿Cuántos mil millones Dollar kostet ein modernes Flugzeugträger?",un:13,unit:"mil millones de $",hint:"Der Ford-Class Träger der US Navy.",emoji:"🚢"},
 {q:"¿Cuánto kostet 1 Gramm Antimaterie en Dollar?",un:62500000000000,unit:"Dollar",hint:"62,5 Billionen Dollar pro Gramm.",emoji:"⚛️"},
 {q:"¿Cuánto kostete das teuerste Parfüm (Clive Christian No. 1) pro Flasche?",un:2150,unit:"Dollar",hint:"en einem goldenen Flacon.",emoji:"🌸"},
 {q:"¿Cuántos mil millones Dollar Umsatz macht Apple pro Quartal?",un:90,unit:"mil millones de $",hint:"Apple ist das wertvollste Unternehmen der Welt.",emoji:"🍎"},
 {q:"¿Cuánto kostet ein Mondstein-Gramm der NASA en Dollar?",un:50800,unit:"Dollar/Gramm",hint:"Der teuerste Stoff auf der Erde nach Antimaterie.",emoji:"🌙"},
 {q:"¿Cuántos mil millones Dollar kostet die Internationale Raumstation?",un:150,unit:"mil millones de $",hint:"Das teuerste von Menschen gebaute Objekt.",emoji:"🚀"},
 {q:"¿Cuánto kostet ein Schweizer Luxusquartier (Gnägi Villa) pro Nacht?",un:50000,unit:"Dollar/Nacht",hint:"Exklusivste Hotels kosten ein Vermögen.",emoji:"🏨"},
 {q:"¿Cuántos mil millones Dollar gab die US-Regierung 2023 für Militär aus?",un:858,unit:"mil millones de $",hint:"Mehr als die nächsten 10 Länder zusammen.",emoji:"⚔️"},
 {q:"¿Cuánto kostete die teuerste Uhr (Patek Philippe Grandmaster Chime)?",un:31000000,unit:"Dollar",hint:"2019 für 31 Mio. Dollar versteigert.",emoji:"⌚"},
 {q:"¿Cuánto kostet 1 Kilogramm weißer Trüffel?",un:10000,unit:"Euro/kg",hint:"Kann bis zu 300.000€ pro kg kosten.",emoji:"🍄"},
 {q:"¿Cuántos mil millones Dollar kostet ein espacio Shuttle Flug?",un:1.5,unit:"mil millones de $",hint:"Jeder Shuttle-Flug kostete ~1,5 Mrd. Dollar.",emoji:"🚀"},
 {q:"¿Cuánto kostete das teuerste Buch (Codex Leicester von Leonardo da Vinci)?",un:30800000,unit:"Dollar",hint:"Gekauft von Bill Gates 1994.",emoji:"📖"},
 {q:"¿Cuántos Billionen Dollar schuldet die USA?",un:34,unit:"Billionen Dollar",hint:"Stand 2024 – wächst al día.",emoji:"💸"},
 {q:"¿Cuánto kostete das teuerste Foto (Rhein II von Andreas Gursky)?",un:4338500,unit:"Dollar",hint:"2011 versteigert.",emoji:"📷"},
 {q:"¿Cuántos mil millones Dollar Jahresumsatz macht McDonald's?",un:23,unit:"mil millones de $",hint:"Hamburger sind ein Milliardengeschäft.",emoji:"🍔"},
 {q:"¿Cuánto kostet ein Kilogramm Saffron (Safran) auf dem Markt?",un:10000,unit:"Euro/kg",hint:"Das teuerste Gewürz der Welt.",emoji:"🌺"},
 {q:"¿Cuántos millones Dollar kostet ein Top-Formel-1-Fahrer por año?",un:50,unit:"millones de $",hint:"Hamilton verdient ~50 Mio. – plus Sponsoren.",emoji:"🏎️"},
 {q:"¿Cuánto kostete die teuerste Handtasche (Hermès Birkin) je?",un:300000,unit:"Dollar",hint:"Aus Krokodilleder mit Diamanten.",emoji:"👜"},
 {q:"¿Cuántos mil millones Dollar ist der globale Markt für Pornografie wert?",un:97,unit:"mil millones de $",hint:"Einer der größten Märkte im Internet.",emoji:"🔞"},
 {q:"¿Cuánto kostet eine Übernachtung im teuersten Hotel (Empathy Suite, Las Vegas)?",un:100000,unit:"Dollar/Nacht",hint:"Im Palms Casino Resort.",emoji:"🏨"},
 {q:"¿Cuántos mil millones Dollar wert ist Elon Musks SpaceX?",un:180,unit:"mil millones de $",hint:"Stand 2024 – private Raumfahrt boomt.",emoji:"🚀"},
 {q:"¿Cuánto kostet 1 mg Californium-252 en Dollar?",un:27000000,unit:"Dollar/mg",hint:"27 Mio. Dollar pro Milligramm.",emoji:"☢️"},
 {q:"¿Cuántos mil millones Dollar Jahresgewinn macht Saudi Aramco?",un:161,unit:"mil millones de $",hint:"Das profitabelste Unternehmen der Welt 2022.",emoji:"🛢️"},
 {q:"¿Cuánto kostete das teuerste Auto je verkauft (Mercedes-Benz 300 SLR)?",un:142000000,unit:"Euro",hint:"2022 für 142 millones Euro versteigert.",emoji:"🚗"},
 {q:"¿Cuántos mil millones Dollar ist der Bitcoin-Markt wert?",un:1000,unit:"mil millones de $",hint:"Schwankt stark – zeitweise über 1 mil millones.",emoji:"₿"},
 {q:"¿Cuánto kostet ein Kobe-Rind pro kg?",un:500,unit:"Euro/kg",hint:"Das teuerste Fleisch der Welt.",emoji:"🥩"},
 {q:"¿Cuántos mil millones Dollar Jahresbudget hat die NASA?",un:25,unit:"mil millones de $",hint:"Nur 0,3% des US-Budgets.",emoji:"🚀"},
 {q:"¿Cuánto kostet ein Glas Whisky aus der Macallan Fine & Rare Collection?",un:10000,unit:"Dollar",hint:"Pro Glas en Luxus-Bars.",emoji:"🥃"},
 {q:"¿Cuántos Billionen Dollar ist der globale Immobilienmarkt wert?",un:326,unit:"Billionen Dollar",hint:"Der größte Anlagemarkt der Welt.",emoji:"🏠"},
 {q:"¿Cuánto kostet der teuerste Champagner (Goût de Diamants)?",un:1200000,unit:"Euro",hint:"Mit Diamanten verziert.",emoji:"🥂"},
 {q:"¿Cuántos mil millones Dollar verdient Taylor Swift pro Tour?",un:1,unit:"mil millones de $",hint:"Die Eras Tour 2023-2024 – erste mil millones-Tour.",emoji:"🎤"},
 {q:"¿Cuánto kostet 1 Gramm Meissen-Porzellan (als Kunstwerk)?",un:1000,unit:"Euro",hint:"Echtes Meissen ist extrem wertvoll.",emoji:"🏺"},
 {q:"¿Cuánto kostete das teuerste Diamant-Ehering (Pink Star)?",un:71200000,unit:"Dollar",hint:"2017 für 71,2 Mio. Dollar versteigert.",emoji:"💍"},
 {q:"¿Cuántos mil millones Dollar Steuern hinterziehen Deutsche por año?",un:30,unit:"mil millones de €",hint:"Schätzungen liegen bei 30 mil millones Euro.",emoji:"💸"},
 {q:"¿Cuánto kostet ein Flug ins All mit Virgin Galactic?",un:450000,unit:"Dollar",hint:"Für einen Suborbitalflug.",emoji:"🚀"},
 {q:"¿Cuántos mil millones Dollar ist der globale Kaffeehandel wert?",un:100,unit:"mil millones de $",hint:"Kaffee ist eines der größten Handelsgüter.",emoji:"☕"},
 {q:"¿Cuánto kostet 1 Bitcoin auf seinem Allzeithoch en Dollar?",un:73000,unit:"Dollar",hint:"Im März 2024 erreichte Bitcoin ~73.000 Dollar.",emoji:"₿"},
 {q:"¿Cuántos mil millones Dollar hat Warren Buffett gespendet?",un:50,unit:"mil millones de $",hint:"Der meistgebende Milliardär der Geschichte.",emoji:"💝"},
 {q:"¿Cuánto kostet ein Kilogramm Kaviar (Almas)?",un:34500,unit:"Euro/kg",hint:"Weißer Kaviar von Albino-Stören.",emoji:"🐟"},
 {q:"¿Cuántos mil millones Dollar Jahresumsatz macht LVMH (Luxuskonzern)?",un:86,unit:"mil millones de €",hint:"Louis Vuitton, Moët, Hennessy und viele mehr.",emoji:"👜"},
 {q:"¿Cuánto kostet ein Top-Anwalt en New York por hora?",un:2000,unit:"Dollar/Stunde",hint:"Hochkarätige Anwälte verlangen enorme Honorare.",emoji:"⚖️"},
 {q:"¿Cuántos mil millones Dollar ist der globale Glücksspielmarkt wert?",un:500,unit:"mil millones de $",hint:"Casinos, Sportwetten und Online-Gambling.",emoji:"🎰"},
 {q:"¿Cuánto kostet ein Luxus-Penthouse en Monaco pro m²?",un:100000,unit:"Euro/m²",hint:"Teuerster Immobilienmarkt der Welt.",emoji:"🏠"},
 {q:"¿Cuántos mil millones Dollar geben Amerikaner por año für Haustiere aus?",un:150,unit:"mil millones de $",hint:"mil millones für Hunde, Katzen und Co.",emoji:"🐕"},
 {q:"¿Cuánto kostet ein Jahr Harvard-Studium (alles inbegriffen)?",un:80000,unit:"Dollar/Jahr",hint:"Wohnen, Essen, Studiengebühren.",emoji:"🎓"},
 {q:"¿Cuántos mil millones Dollar kostet ein Kernkraftwerk?",un:12,unit:"mil millones de $",hint:"Die neuesten Reaktoren kosten bis zu 30 Mrd.",emoji:"⚡"},
 {q:"¿Cuánto kostet ein Kilo Gold aktuell en Euro?",un:60000,unit:"Euro/kg",hint:"Gold kostet ca. 60.000€/kg – Stand 2024.",emoji:"🪙"},
 {q:"¿Cuántos mil millones Dollar Jahresumsatz hat Google?",un:280,unit:"mil millones de $",hint:"Haupteinnahme: Werbung.",emoji:"🔍"},
 {q:"¿Cuánto kostet der teuerste Cognac (Hennessy Richard)?",un:12000,unit:"Dollar",hint:"Pro Flasche – handgefertigt.",emoji:"🥃"},
 {q:"¿Cuántos mil millones Dollar kostet es ein Olympisches Spiel auszurichten?",un:15,unit:"mil millones de $",hint:"London 2012 kostete 15 Mrd. Pfund.",emoji:"🏅"},
 {q:"¿Cuánto kostet ein Kilogramm Diamanten (Rohdiamant)?",un:55000,unit:"Dollar/Karat",hint:"Qualitätsdiamanten können viel mehr kosten.",emoji:"💎"},
 {q:"¿Cuántos mil millones Dollar wert ist der Tabakmarkt global?",un:900,unit:"mil millones de $",hint:"Trotz Rückgang – immer noch riesig.",emoji:"🚬"},
 {q:"¿Cuánto kostet ein privater Hubschrauber (Airbus H145)?",un:7000000,unit:"Dollar",hint:"Ein Standard-Luxushubschrauber.",emoji:"🚁"},
 {q:"¿Cuántos mil millones Dollar verdient FIFA pro WM?",un:5,unit:"mil millones de $",hint:"Die WM 2022 en Katar generierte ~7,5 Mrd.",emoji:"⚽"},
 {q:"¿Cuánto kostet das teuerste Hotelzimmer pro Nacht en Dubai?",un:85000,unit:"Dollar",hint:"Royal Penthouse im Burj Al Arab.",emoji:"🏨"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Pharmasektor?",un:1600,unit:"mil millones de $",hint:"Ein billionenschwerer Markt.",emoji:"💊"},
 {q:"¿Cuánto kostet 1 kg Heroin auf dem Schwarzmarkt?",un:50000,unit:"Dollar/kg",hint:"Straßenpreise variieren stark.",emoji:"💊"},
 {q:"¿Cuántos mil millones Dollar geben Amis por año für rápido comida aus?",un:280,unit:"mil millones de $",hint:"rápido comida ist Amerikas Lieblingsessen.",emoji:"🍔"},
 {q:"¿Cuánto kostet eine private Insel en der Karibik (Einstieg)?",un:5000000,unit:"Dollar",hint:"Kleine Inseln ab 5 Mio. Dollar.",emoji:"🏝️"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Waffenmarkt?",un:600,unit:"mil millones de $",hint:"Legaler Waffenhandel en el mundo.",emoji:"⚔️"},
 {q:"¿Cuánto kostet ein Luxusjet (Bombardier Global 7500)?",un:75000000,unit:"Dollar",hint:"Der größte Privatjet der Welt.",emoji:"✈️"},
 {q:"¿Cuántos mil millones Euro hat Deutschland 2023 en Rüstung investiert?",un:52,unit:"mil millones de €",hint:"Auf dem Weg zum 2%-Ziel der NATO.",emoji:"⚔️"},
 {q:"¿Cuánto kostet 1 Sekunde Werbung beim Super Bowl?",un:200000,unit:"Dollar",hint:"30 Sekunden = 6 Mio. Dollar.",emoji:"📺"},
 {q:"¿Cuántos mil millones Dollar ist TikTok (ByteDance) wert?",un:250,unit:"mil millones de $",hint:"Stand 2024.",emoji:"📱"},
 {q:"¿Cuánto kostet ein Kilogramm Seltener Erde (Scandium)?",un:15000,unit:"Dollar/kg",hint:"Seltene Erden sind der Stoff der modernen Welt.",emoji:"⚗️"},
 {q:"¿Cuántos mil millones Dollar Jahresgewinne macht Apple?",un:100,unit:"mil millones de $",hint:"Apple ist unfassbar profitabel.",emoji:"🍎"},
 {q:"¿Cuánto kostet eine Hermes Birkin Tasche (Sonderanfertigung)?",un:500000,unit:"Dollar",hint:"Mit exotischen Materialien.",emoji:"👜"},
 {q:"¿Cuántos mil millones Dollar hat Elon Musk für Twitter/X bezahlt?",un:44,unit:"mil millones de $",hint:"Im Oktober 2022.",emoji:"𝕏"},
 {q:"¿Cuánto kostet ein Kilogramm Plutonium?",un:6600000,unit:"Dollar",hint:"Das teuerste legale Material auf Erden.",emoji:"☢️"},
 {q:"¿Cuántos mil millones Dollar wert ist Cristiano Ronaldos Marke?",un:1,unit:"mil millones de $",hint:"CR7 ist Milliardär durch Marke und Investments.",emoji:"⚽"},
 {q:"¿Cuánto kostet ein Kunstwerk von Banksy im Durchschnitt?",un:5000000,unit:"Dollar",hint:"Game Changer wurde für 16,8 Mio. verkauft.",emoji:"🎨"},
 {q:"¿Cuántos mil millones Dollar kostet der Mars-Kolonisierungsplan von SpaceX?",un:100,unit:"mil millones de $",hint:"Musk schätzte ursprünglich 100 Mrd.",emoji:"🔴"},
 {q:"¿Cuánto kostet ein Megajacht (100m+) por año un Unterhalt?",un:10000000,unit:"Dollar/Jahr",hint:"10% des Kaufpreises al año für Unterhalt.",emoji:"⛵"},
 {q:"¿Cuántos mil millones Dollar Jahresumsatz hat die Pornoindustrie?",un:97,unit:"mil millones de $",hint:"Ein gigantischer globaler Markt.",emoji:"🔞"},
 {q:"¿Cuánto kostet eine Tasse Kopi Luwak (teuerster Kaffee)?",un:100,unit:"Dollar/Tasse",hint:"Kaffee aus dem Kot der Zibetkatze.",emoji:"☕"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale E-Sport-Markt?",un:2,unit:"mil millones de $",hint:"Professionelles Spielen wächst rasant.",emoji:"🎮"},
 {q:"¿Cuánto kostet ein Kilogramm Quecksilber auf dem freien Markt?",un:50,unit:"Dollar",hint:"Relativ günstig – trotz Giftigkeit.",emoji:"🌡️"},
 {q:"¿Cuántos mil millones Euro hat Deutschland en die Flüchtlingskrise investiert?",un:20,unit:"Mrd. Euro/Jahr",hint:"2015-2022 insgesamt über 100 Mrd.",emoji:"🏠"},
 {q:"¿Cuánto kostet ein Top-Fußballspieler-se transfieren (Neymar)?",un:222000000,unit:"Euro",hint:"Teuerster se transfieren aller Zeiten 2017.",emoji:"⚽"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Kosmetikmarkt?",un:500,unit:"mil millones de $",hint:"Schönheit ist ein riesiges Geschäft.",emoji:"💄"},
 {q:"¿Cuánto kostet 1 Watt Solarenergie zur Installation?",un:0.3,unit:"Dollar/Watt",hint:"Drastisch gesunken – von 80$/W en 1970.",emoji:"☀️"},
 {q:"¿Cuántos mil millones Dollar kostet ein Atomkraftwerk (Hinkley Point C)?",un:33,unit:"Mrd. Pfund",hint:"Das teuerste Bauwerk en UK.",emoji:"⚡"},
 {q:"¿Cuánto kostet eine Luxusuhr von Richard Mille?",un:1000000,unit:"Dollar",hint:"Die teuersten Uhren der Welt.",emoji:"⌚"},
 {q:"¿Cuántos mil millones Dollar Jahresumsatz hat Nestlé?",un:95,unit:"mil millones de $",hint:"Größter Lebensmittelkonzern der Welt.",emoji:"🍫"},
 {q:"¿Cuánto kostet ein Kilogramm Kokain en Europa?",un:35000,unit:"Euro/kg",hint:"Straßenpreise – stark variierend.",emoji:"💊"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Alkohol-Markt?",un:1600,unit:"mil millones de $",hint:"Bier, Wein und Spirituosen zusammen.",emoji:"🍷"},
 {q:"¿Cuánto kostet ein privater Raketenstarter bei SpaceX (Falcon 9)?",un:67000000,unit:"Dollar",hint:"67 Mio. pro Falcon-9-Start.",emoji:"🚀"},
 {q:"¿Cuántos mil millones Dollar verdiente Fortnite en seinem ersten Jahr?",un:2.4,unit:"mil millones de $",hint:"Epic Games Blockbuster-Spiel.",emoji:"🎮"},
 {q:"¿Cuánto kostet der teuerste Sneaker je versteigert?",un:1800000,unit:"Dollar",hint:"Nike luna Shoe von 1972.",emoji:"👟"},
 {q:"¿Cuántos mil millones Dollar wert ist die gesamte Krypto-Marktkapitalisierung?",un:2000,unit:"mil millones de $",hint:"Stand Anfang 2024.",emoji:"₿"},
 {q:"¿Cuánto kostet ein Liter Blut im Krankenhaus en den USA?",un:1000,unit:"Dollar",hint:"Gespendetes Blut wird teuer verkauft.",emoji:"🩸"},
 {q:"¿Cuántos mil millones Dollar Jahresumsatz hat Amazon?",un:514,unit:"mil millones de $",hint:"Größter Onlinehändler der Welt.",emoji:"📦"},
 {q:"¿Cuánto kostet ein Quadratmeter en Hongkong (teuerste Gegend)?",un:100000,unit:"Dollar/m²",hint:"Hongkong ist eine der teuersten Städte.",emoji:"🏙️"},
 {q:"¿Cuántos mil millones Dollar kostet ein neues Flugzeug (Airbus A380)?",un:445,unit:"millones de $",hint:"Das größte Passagierflugzeug.",emoji:"✈️"},
 {q:"¿Cuánto kostet eine Flasche Petrus (Bordeaux, 1947)?",un:75000,unit:"Euro",hint:"Einige Flaschen wurden für über 100.000€ verkauft.",emoji:"🍷"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Schusswaffen?",un:28,unit:"mil millones de $",hint:"Legaler Waffenmarkt.",emoji:"🔫"},
 {q:"¿Cuánto kostet 1 km Autobahn zu bauen en Deutschland?",un:25000000,unit:"Euro/km",hint:"25 Mio. Euro pro Kilometer.",emoji:"🛣️"},
 {q:"¿Cuántos mil millones Euro kostet der Wiederaufbau der Notre-Dame?",un:700,unit:"millones de €",hint:"Über 700 Mio. Euro für die Renovierung.",emoji:"⛪"},
 {q:"¿Cuánto kostet ein Quadratmeter en Paris (Innenstadt)?",un:12000,unit:"Euro/m²",hint:"Paris ist eine der teuersten Städte Europas.",emoji:"🗼"},
 {q:"¿Cuántos mil millones Dollar ist Tesla wert?",un:600,unit:"mil millones de $",hint:"Schwankt stark – war mal über 1 mil millones.",emoji:"🚗"},
 {q:"¿Cuánto kostet ein Jahr en der teuersten Privatschule der Welt?",un:120000,unit:"Schweizer Franken",hint:"Institut Le Rosey en der Schweiz.",emoji:"🎓"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Musikmarkt?",un:26,unit:"mil millones de $",hint:"Streaming dominiert.",emoji:"🎵"},
 {q:"¿Cuánto kostet ein Kilogramm Vanille?",un:600,unit:"Dollar/kg",hint:"Einer der teuersten Gewürze nach Safran.",emoji:"🌿"},
 {q:"¿Cuántos mil millones Dollar wert ist Goldman Sachs?",un:120,unit:"mil millones de $",hint:"Eine der mächtigsten Investmentbanken.",emoji:"🏦"},
 {q:"¿Cuánto kostet ein Penthouse en New York ciudad (en promedio)?",un:20000000,unit:"Dollar",hint:"Luxuspenthouses en Manhattan.",emoji:"🏙️"},
 {q:"¿Cuántos mil millones Dollar gibt die Welt por año für Rüstung aus?",un:2200,unit:"mil millones de $",hint:"2,2 Billionen Dollar al año.",emoji:"⚔️"},
 {q:"¿Cuánto kostet 1 km neues U-Bahn-Netz en London?",un:1000000000,unit:"Dollar/km",hint:"London hat die teuersten U-Bahnbauprojekte.",emoji:"🚇"},
 {q:"¿Cuántos mil millones Dollar ist der globale Markt für Videospiele wert?",un:200,unit:"mil millones de $",hint:"Größer als película und Musik zusammen.",emoji:"🎮"},
 {q:"¿Cuánto kostet ein Jahresgehalt eines Hedge-Fonds-Managers?",un:1000000000,unit:"Dollar",hint:"Spitzenmanager verdienen mil millones.",emoji:"💰"},
 {q:"¿Cuántos mil millones Dollar ist der globale Tourismus-Markt wert?",un:9500,unit:"mil millones de $",hint:"9,5 Billionen Dollar – einer der größten Sektoren.",emoji:"✈️"},
 {q:"¿Cuánto kostet das Anlegen eines Sterns nach dir?",un:50,unit:"Dollar",hint:"Internationales Sternregister – eigentlich rechtlich nicht bindend.",emoji:"⭐"},
 {q:"¿Cuántos mil millones Dollar kostet ein Wolkenkratzer (Burj Khalifa)?",un:1.5,unit:"mil millones de $",hint:"Der höchste Turm der Welt.",emoji:"🏙️"},
 {q:"¿Cuánto kostet 1 Kilo Seltener Erden-Neodym?",un:175,unit:"Dollar/kg",hint:"Essenziell für Elektromotoren.",emoji:"⚗️"},
 {q:"¿Cuántos mil millones Dollar wert ist der FC Barcelona?",un:5,unit:"mil millones de $",hint:"Einer der wertvollsten Sportklubs.",emoji:"⚽"},
 {q:"¿Cuánto kostet ein privater DNA-Test bei 23andMe?",un:200,unit:"Dollar",hint:"Plus optionale Abonnements.",emoji:"🧬"},
 {q:"¿Cuántos mil millones Dollar Jahresumsatz hat die Filmindustrie (Hollywood)?",un:50,unit:"mil millones de $",hint:"Box Office plus Streaming.",emoji:"🎬"},
 {q:"¿Cuánto kostet ein Meter Eintrittskarte für ein Taylor-Swift-Konzert (VIP)?",un:3000,unit:"Dollar",hint:"VIP-Pakete für die Eras Tour.",emoji:"🎤"},
 {q:"¿Cuántos mil millones Dollar wert ist die Marke Nike?",un:50,unit:"mil millones de $",hint:"Just Do It – einer der stärksten Markennamen.",emoji:"👟"},
 {q:"¿Cuánto kostet ein Kilogramm weißer Trüffel auf Auktionen?",un:300000,unit:"Euro/kg",hint:"Rekord-Trüffel werden für Hunderttausende verkauft.",emoji:"🍄"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Schönheitsmarkt?",un:800,unit:"mil millones de $",hint:"Wächst stark durch Influencer-Kultur.",emoji:"💄"},
 {q:"¿Cuánto kostet ein Concorde-Ticket (als sie noch flog)?",un:8000,unit:"Dollar",hint:"Ein Transatlantikflug für 8000 Dollar.",emoji:"✈️"},
 {q:"¿Cuántos mil millones Dollar hat Elon Musk en einem Jahr verloren (2022)?",un:200,unit:"mil millones de $",hint:"Größter Vermögensverlust en der Geschichte.",emoji:"📉"},
 {q:"¿Cuánto kostet ein Quadratmeter auf der teuersten Straße der Welt (Hong Kong)?",un:236000,unit:"Dollar/m²",hint:"Causeway Bay, Hong Kong.",emoji:"🏙️"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Sportmarkt?",un:500,unit:"mil millones de $",hint:"Alle Sportveranstaltungen, Rechte und Merchandise.",emoji:"⚽"},
 {q:"¿Cuánto kostet 1 minuto Werbung auf dem Super Bowl?",un:10000000,unit:"Dollar",hint:"Über 10 Mio. Dollar für 30 Sekunden.",emoji:"📺"},
 {q:"¿Cuántos mil millones Dollar kostet das amerikanische Bildungssystem por año?",un:700,unit:"mil millones de $",hint:"Von Kindergarten bis Uni.",emoji:"🎓"},
 {q:"¿Cuánto kostet ein Liter Parfüm Chanel No. 5?",un:3000,unit:"Euro",hint:"Eines der ikonischsten Parfüms.",emoji:"🌸"},
 {q:"¿Cuántos mil millones Dollar hat Saudi-Arabien en Soccer-Stars investiert?",un:6,unit:"mil millones de $",hint:"Die Saudi Pro League wirbt Weltstars ab.",emoji:"⚽"},
 {q:"¿Cuánto kostet ein Kilogramm Madame Jeanette-Chili en Europa?",un:50,unit:"Euro/kg",hint:"Seltene scharfe Chili aus Surinam.",emoji:"🌶️"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Streaming?",un:100,unit:"mil millones de $",hint:"Netflix, Spotify, Amazon und alle anderen.",emoji:"📺"},
 {q:"¿Cuánto kostet eine Mitgliedschaft im Augusta National Golf Club?",un:300000,unit:"Dollar",hint:"Der exklusivste Golfklub der Welt.",emoji:"⛳"},
 {q:"¿Cuántos mil millones Dollar verliert die Weltwirtschaft durch Korruption?",un:2600,unit:"mil millones de $",hint:"2,6 Billionen Dollar por año laut UN.",emoji:"💸"},
 {q:"¿Cuánto kostet ein kg Ambergris (Walrat) auf dem Schwarzmarkt?",un:50000,unit:"Dollar",hint:"Verwendet en Luxusparfüms.",emoji:"🐋"},
 {q:"¿Cuántos mil millones Dollar ist der globale rápido-Fashion-Markt wert?",un:100,unit:"mil millones de $",hint:"Zara, H&M und Shein dominieren.",emoji:"👗"},
 {q:"¿Cuánto kostet ein Privatflug London-New York?",un:150000,unit:"Dollar",hint:"Im Luxus-Jet.",emoji:"✈️"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Lebensmittelmarkt?",un:8000,unit:"mil millones de $",hint:"8 Billionen Dollar – täglicher Bedarf.",emoji:"🍎"},
 {q:"¿Cuánto kostet ein Meter Silizium-Chip-Produktion (TSMC 2nm)?",un:20000,unit:"Dollar/Wafer",hint:"Die teuersten Chips der Welt.",emoji:"💻"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Online-Shopping-Markt?",un:5000,unit:"mil millones de $",hint:"5 Billionen Dollar – wächst weiter.",emoji:"📦"},
 {q:"¿Cuánto kostet 1 Liter menschliches Blutplasma?",un:500,unit:"Dollar",hint:"Blutplasma ist ein wertvolles Medizinprodukt.",emoji:"🩸"},
 {q:"¿Cuántos mil millones Dollar wert ist Spotify?",un:40,unit:"mil millones de $",hint:"Stand 2024.",emoji:"🎵"},
 {q:"¿Cuánto kostet ein Kilogramm Carbon-Fiber?",un:100,unit:"Dollar/kg",hint:"Für Formel-1 und Luft-/Raumfahrt essenziell.",emoji:"🏎️"},
 {q:"¿Cuántos mil millones Dollar hat Kylie Jenner verdient als jüngste Selfmade-Milliardärin?",un:1,unit:"mil millones de $",hint:"Durch ihre Kosmetikmarke.",emoji:"💄"},
 {q:"¿Cuánto kostet ein Quadratmeter en München (Maxvorstadt)?",un:15000,unit:"Euro/m²",hint:"Einer der teuersten Immobilienmärkte Deutschlands.",emoji:"🏠"},
 {q:"¿Cuántos mil millones Dollar kostet es die Klimakrise zu lösen (al año)?",un:4000,unit:"mil millones de $",hint:"Schätzungen des IPCC.",emoji:"🌍"},
 {q:"¿Cuánto kostet der teuerste Tee (Da Hong Pao)?",un:1000000,unit:"Dollar/kg",hint:"1 Mio. Dollar pro kg – kaum noch erhältlich.",emoji:"🍵"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Cannabismarkt?",un:50,unit:"mil millones de $",hint:"Legal und illegal zusammen.",emoji:"🌿"},
 {q:"¿Cuánto kostet ein Kilogramm roher Saphir?",un:30000,unit:"Dollar/Karat",hint:"Hochwertige Saphire kosten 30.000+/Karat.",emoji:"💎"},
 {q:"¿Cuántos mil millones Dollar al año macht die CIA mit verdeckten Operationen?",un:90,unit:"mil millones de $",hint:"Das geheime US-Geheimdienstbudget.",emoji:"🕵️"},
 {q:"¿Cuánto kostet ein Kilo Seltenes Element Rhenium?",un:5000,unit:"Dollar/kg",hint:"Eines der seltensten stabilen Elemente.",emoji:"⚗️"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für KI?",un:200,unit:"mil millones de $",hint:"Wächst exponentiell.",emoji:"🤖"},
 {q:"¿Cuánto kostet ein Ferrari F40 heute?",un:1500000,unit:"Euro",hint:"Legendärer Supersportwagen von 1987.",emoji:"🚗"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Cloud-Computing-Markt?",un:600,unit:"mil millones de $",hint:"AWS, Azure und Google dominieren.",emoji:"☁️"},
 {q:"¿Cuánto kostet 1 Meter Unterwasserkabel (Internet)?",un:35000,unit:"Dollar/km",hint:"Unterseekabel verbinden die Kontinente.",emoji:"🌊"},
 {q:"¿Cuántos mil millones Dollar geben Reiche Menschen für Kunst aus?",un:68,unit:"mil millones de $",hint:"Der globale Kunstmarkt 2022.",emoji:"🎨"},
 {q:"¿Cuánto kostet der teuerste Wein je (Romanée-Conti 1945)?",un:558000,unit:"Dollar",hint:"Pro Flasche – 2018 versteigert.",emoji:"🍷"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Cybersecurity?",un:200,unit:"mil millones de $",hint:"Wächst mit jedem Angriff.",emoji:"🔒"},
 {q:"¿Cuánto kostet ein Penthouse en Dubai (Palm Jumeirah)?",un:30000000,unit:"Dollar",hint:"Luxuriöse Residenzen auf der Palmeninsel.",emoji:"🌴"},
 {q:"¿Cuántos mil millones Dollar wert ist die Sportartikelmesse (Adidas+Nike)?",un:100,unit:"mil millones de $",hint:"Beide zusammen.",emoji:"👟"},
 {q:"¿Cuánto kostet ein Stunde mit einem Top-Management-Consultant (McKinsey)?",un:1200,unit:"Dollar",hint:"Für Senior Partner.",emoji:"💼"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Pharmamarkt?",un:1600,unit:"mil millones de $",hint:"Medikamente sind ein riesiger Markt.",emoji:"💊"},
 {q:"¿Cuánto kostet ein Jahresmitgliedschaft bei Amazon Prime?",un:139,unit:"Dollar",hint:"en den USA – unterschiedlich je Land.",emoji:"📦"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Elektroautos?",un:400,unit:"mil millones de $",hint:"Wächst schnell – Tesla führt.",emoji:"🚗"},
 {q:"¿Cuántos mil millones Dollar Jahresumsatz hat Volkswagen?",un:293,unit:"mil millones de €",hint:"Größter Automobilkonzern Europas.",emoji:"🚗"},
 {q:"¿Cuánto kostet ein normales Herz-Transplantation en den USA?",un:1000000,unit:"Dollar",hint:"Inklusive Nachsorge.",emoji:"❤️"},
 {q:"¿Cuántos mil millones Dollar wert ist TikTok-Eigentümer ByteDance?",un:250,unit:"mil millones de $",hint:"Wertvollstes nicht-börsennotiertes Unternehmen.",emoji:"📱"},
 {q:"¿Cuánto kostet ein Kilogramm Lithium auf dem Weltmarkt?",un:30,unit:"Dollar/kg",hint:"Essenziell für Batterien.",emoji:"⚡"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Suchmaschinenmarkt?",un:300,unit:"mil millones de $",hint:"Google dominiert mit über 90%.",emoji:"🔍"},
 {q:"¿Cuánto kostet ein Abonnement von Netflix por mes (Standard)?",un:15,unit:"Dollar/Monat",hint:"en den USA – unterschiedlich je Land.",emoji:"📺"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Elektronikmüll?",un:60,unit:"mil millones de $",hint:"Wertvolle Metalle landen im Müll.",emoji:"♻️"},
 {q:"¿Cuánto kostet 1 Gramm Helium-3 (Mondressource)?",un:14000,unit:"Dollar/Gramm",hint:"Potenzielle Fusionsenergiequelle.",emoji:"🌙"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Düngemittel?",un:200,unit:"mil millones de $",hint:"Essenziell für die Nahrungsmittelproduktion.",emoji:"🌾"},
 {q:"¿Cuánto kostet ein Stunde mit einem Top-Strafrechtler en Deutschland?",un:600,unit:"Euro/Stunde",hint:"Top-Anwälte verlangen enorme Stundensätze.",emoji:"⚖️"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Halbleiter?",un:600,unit:"mil millones de $",hint:"Chips regieren die Welt.",emoji:"💻"},
 {q:"¿Cuánto kostet ein Kilo Hafnium (seltenes Metall)?",un:900,unit:"Dollar/kg",hint:"Verwendet en Atomreaktoren.",emoji:"⚗️"},
 {q:"¿Cuántos mil millones Dollar hat der erste NFT (Beeple) eingebracht?",un:69,unit:"millones de $",hint:"'Everydays: el First 5000 días' – 69 Mio. 2021.",emoji:"🖼️"},
 {q:"¿Cuánto kostet ein Kilo weißes Trüffelöl?",un:5000,unit:"Euro/Liter",hint:"Das beste Trüffelöl ist extrem teuer.",emoji:"🍄"},
 {q:"¿Cuántos mil millones Dollar ist Airbnb wert?",un:90,unit:"mil millones de $",hint:"Stand 2024.",emoji:"🏠"},
 {q:"¿Cuánto kostet eine Lungenatmung en einem US-Krankenhaus (Beatmung, Tag)?",un:10000,unit:"Dollar/Tag",hint:"Intensivstation en den USA.",emoji:"🏥"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Robotik?",un:100,unit:"mil millones de $",hint:"Industrieroboter und Service-Roboter.",emoji:"🤖"},
 {q:"¿Cuánto kostet ein Kilogramm Gallium?",un:250,unit:"Dollar/kg",hint:"Essenziell für Halbleiter.",emoji:"⚗️"},
 {q:"¿Cuántos mil millones Dollar wert ist Ferrari als Unternehmen?",un:60,unit:"mil millones de $",hint:"Ferrari ist mehr Luxusmarke als Autohersteller.",emoji:"🚗"},
 {q:"¿Cuánto kostet 1 Liter Kerosin für Privatjets?",un:2,unit:"Dollar/Liter",hint:"Steuerbegünstigt – weniger als Benzin.",emoji:"✈️"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Diamantmarkt?",un:80,unit:"mil millones de $",hint:"Lab-Diamanten bedrohen den Markt.",emoji:"💎"},
 {q:"¿Cuánto kostet ein Durchschnittskauf im Hermès Paris pro Einkauf?",un:5000,unit:"Euro",hint:"Hermès-Kunden geben viel aus.",emoji:"👜"},
 {q:"¿Cuántos mil millones Dollar wert ist Airbus?",un:100,unit:"mil millones de €",hint:"Der größte Flugzeugbauer Europas.",emoji:"✈️"},
 {q:"¿Cuánto kostet ein Tesla Model S?",un:100000,unit:"Dollar",hint:"Das Flaggschiff-Modell von Tesla.",emoji:"🚗"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für nachhaltige Investments?",un:35000,unit:"mil millones de $",hint:"ESG-Investments boomen.",emoji:"🌿"},
 {q:"¿Cuánto kostet ein km² Agrarland en Bayern?",un:80000,unit:"Euro/Hektar",hint:"Bayern hat die teuersten Agrarpreise Deutschlands.",emoji:"🌾"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Online-Gaming-Markt?",un:250,unit:"mil millones de $",hint:"Mobile Gaming ist der größte Teil.",emoji:"🎮"},
 {q:"¿Cuántos mil millones Dollar wert ist IKEA?",un:58,unit:"mil millones de $",hint:"Privat geführt – durch eine Stiftung.",emoji:"🛋️"},
 {q:"¿Cuántos mil millones Dollar Jahresumsatz macht H&M?",un:22,unit:"mil millones de $",hint:"Zweitgrößte Modekette der Welt.",emoji:"👗"},
 {q:"¿Cuántos mil millones Dollar wert ist WhatsApp (beim Verkauf un Facebook)?",un:19,unit:"mil millones de $",hint:"Gekauft 2014 für damals schwindelerregende Summe.",emoji:"💬"},
 {q:"¿Cuántos mil millones Euro wert ist BMW?",un:70,unit:"mil millones de €",hint:"Eines der wertvollsten deutschen Unternehmen.",emoji:"🚗"},
 {q:"¿Cuántos mil millones Dollar kostet eine Satellitenmine?",un:300,unit:"millones de $",hint:"millones für einen militärischen Satelliten.",emoji:"🛰️"},
 {q:"¿Cuántos mil millones Dollar wert ist Red Bull?",un:20,unit:"mil millones de $",hint:"Aus Österreich zum Weltkonzern.",emoji:"🐂"},
 {q:"¿Cuántos mil millones Dollar hat die Corona-Impfkampagne die Welt gekostet?",un:15,unit:"mil millones de $",hint:"Für die Entwicklung der mRNA-Impfstoffe.",emoji:"💉"},
 {q:"¿Cuántos mil millones Euro wert ist Adidas?",un:35,unit:"mil millones de €",hint:"Der Streifen ist eine der wertvollsten Marken.",emoji:"👟"},
 {q:"¿Cuántos mil millones Dollar hat Bill Gates gespendet?",un:59,unit:"mil millones de $",hint:"Die Gates Foundation ist größte private Stiftung.",emoji:"💝"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Elektrizität?",un:3000,unit:"mil millones de $",hint:"3 Billionen Dollar – essenziell für alles.",emoji:"⚡"},
 {q:"¿Cuántos mil millones Dollar Marktkapitalisierung hat Microsoft?",un:3200,unit:"mil millones de $",hint:"Stand 2024 – zeitweise das wertvollste Unternehmen.",emoji:"💻"},
 {q:"¿Cuántos mil millones Euro kostet Oktoberfest die Münchner Wirtschaft?",un:1.3,unit:"mil millones de €",hint:"Über eine Milliarde Euro Wirtschaftsleistung.",emoji:"🍺"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Haushaltsgeräte-Markt?",un:700,unit:"mil millones de $",hint:"Waschmaschinen, Kühlschränke und Co.",emoji:"🏠"},
 {q:"¿Cuántos mil millones Euro Schaden entsteht durch Cyberkriminalität en Deutschland?",un:200,unit:"mil millones de €",hint:"al año laut Bitkom.",emoji:"🔒"},
 {q:"¿Cuántos mil millones Dollar kostet 1 km Autobahn en den USA?",un:10,unit:"Mio. Dollar/km",hint:"en dicht bebauten Gebieten deutlich mehr.",emoji:"🛣️"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Haustierprodukte?",un:260,unit:"mil millones de $",hint:"Wächst stark – Menschen lieben ihre Haustiere.",emoji:"🐕"},
 {q:"¿Cuántos mil millones Euro wert ist SAP?",un:200,unit:"mil millones de €",hint:"Deutschlands wertvollstes Tech-Unternehmen.",emoji:"💻"},
 {q:"¿Cuántos mil millones Dollar kostet die Herstellung eines Smartphones?",un:350,unit:"millones de $",hint:"Dollar Materialkosten für ein iPhone.",emoji:"📱"},
 {q:"¿Cuántos mil millones Dollar hat Amazon für Whole Foods bezahlt?",un:13.7,unit:"mil millones de $",hint:"2017 – Amazons Einstieg en den Lebensmittelhandel.",emoji:"🛒"},
 {q:"¿Cuántos mil millones Dollar Jahresumsatz hat Coca-Cola?",un:46,unit:"mil millones de $",hint:"Eines der bekanntesten Marken en el mundo.",emoji:"🥤"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Sportkleidungsmarkt?",un:200,unit:"mil millones de $",hint:"Athleisure-Trend treibt das Wachstum.",emoji:"👕"},
 {q:"¿Cuántos mil millones Euro kostet die Energiewende Deutschland bis 2035?",un:500,unit:"mil millones de €",hint:"Schätzungen variieren erheblich.",emoji:"⚡"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Bücher?",un:138,unit:"mil millones de $",hint:"Print und E-Books zusammen.",emoji:"📚"},
 {q:"¿Cuántos mil millones Dollar hat Google für YouTube bezahlt?",un:1.65,unit:"mil millones de $",hint:"2006 – im Rückblick das Schnäppchen des Jahrhunderts.",emoji:"▶️"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Süßigkeiten?",un:200,unit:"mil millones de $",hint:"Schokolade, Kaugummi und Co.",emoji:"🍫"},
 {q:"¿Cuántos mil millones Euro hat die Covid-19-Krise Deutschland gekostet?",un:300,unit:"mil millones de €",hint:"Hilfspaket plus wirtschaftliche Einbußen.",emoji:"😷"},
 {q:"¿Cuántos mil millones Dollar wert ist Instacart?",un:10,unit:"mil millones de $",hint:"Lebensmittellieferservice aus San Francisco.",emoji:"🛒"},
 {q:"¿Cuántos mil millones Dollar Jahresgewinn macht Saudi Aramco?",un:161,unit:"mil millones de $",hint:"Das profitabelste Unternehmen der Welt.",emoji:"🛢️"},
 {q:"¿Cuántos mil millones Euro wert ist Bosch?",un:93,unit:"mil millones de €",hint:"Größter Automobilzulieferer der Welt.",emoji:"🔧"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Brillen?",un:150,unit:"mil millones de $",hint:"Luxottica dominiert den Markt.",emoji:"👓"},
 {q:"¿Cuántos mil millones Dollar hat Facebook (Meta) für Instagram bezahlt?",un:1,unit:"mil millones de $",hint:"2012 – heute ist Instagram mil millones wert.",emoji:"📸"},
 {q:"¿Cuántos mil millones Euro Schulden hat die Deutsche Bahn?",un:30,unit:"mil millones de €",hint:"Eines der am stärksten verschuldeten Staatsunternehmen.",emoji:"🚂"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Kreuzfahrten?",un:150,unit:"mil millones de $",hint:"Wächst trotz Pandemie-Einbruch wieder.",emoji:"🚢"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Hautpflege?",un:180,unit:"mil millones de $",hint:"Teil des riesigen Kosmetik-Markts.",emoji:"💆"},
 {q:"¿Cuántos mil millones Dollar hat Apple für Shazam bezahlt?",un:400,unit:"millones de $",hint:"millones Dollar für die Musik-App.",emoji:"🎵"},
 {q:"¿Cuántos mil millones Euro Jahresumsatz hat Deutsche Telekom?",un:114,unit:"mil millones de €",hint:"Größter Telekomkonzern Europas.",emoji:"📱"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Dating-Apps?",un:9,unit:"mil millones de $",hint:"Tinder, Bumble und Co.",emoji:"❤️"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Fitness?",un:100,unit:"mil millones de $",hint:"Fitnessstudios, Apps und Equipment.",emoji:"💪"},
 {q:"¿Cuántos mil millones Dollar hat Microsoft für LinkedIn bezahlt?",un:26.2,unit:"mil millones de $",hint:"2016 – das teuerste Social-Media-Acquisition.",emoji:"💼"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Schmerzmittel?",un:35,unit:"mil millones de $",hint:"Ibuprofen, Aspirin und Co.",emoji:"💊"},
 {q:"¿Cuántos mil millones Dollar kostet ein Flugzeugträger der USA?",un:13,unit:"mil millones de $",hint:"Der Gerald R. Ford kostet 13,3 mil millones.",emoji:"🚢"},
 {q:"¿Cuántos mil millones Euro wert ist BASF?",un:40,unit:"mil millones de €",hint:"Größter Chemiekonzern der Welt.",emoji:"⚗️"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für Legal Cannabis?",un:50,unit:"mil millones de $",hint:"Wächst durch Legalisierungswellen.",emoji:"🌿"},
 {q:"¿Cuántos mil millones Dollar Jahresumsatz macht Walt Disney?",un:88,unit:"mil millones de $",hint:"película, Parks, Streaming und Merchandise.",emoji:"🏰"},
 {q:"¿Cuántos mil millones Dollar hat Microsoft für Activision Blizzard bezahlt?",un:68.7,unit:"mil millones de $",hint:"2023 – das teuerste Gaming-Acquisition.",emoji:"🎮"},
 {q:"¿Cuántos mil millones Euro wert ist der deutsche Immobilienmarkt?",un:14000,unit:"mil millones de €",hint:"14 Billionen Euro – größtes nationales Vermögen.",emoji:"🏠"},
 {q:"¿Cuántos mil millones Dollar kostet das James Webb Telescope?",un:10,unit:"mil millones de $",hint:"Das teuerste Teleskop der Geschichte.",emoji:"🔭"},
 {q:"¿Cuántos mil millones Euro Jahresumsatz hat Siemens?",un:77,unit:"mil millones de €",hint:"Eines der größten Industrieunternehmen Europas.",emoji:"⚙️"},
 {q:"¿Cuántos mil millones Dollar wert ist Zoom?",un:20,unit:"mil millones de $",hint:"Covid hat Zoom zum Must-tiene gemacht.",emoji:"📹"},
 {q:"¿Cuántos mil millones Dollar hat TikTok laut Schätzungen Umsatz?",un:16,unit:"mil millones de $",hint:"Stand 2023 – schnell wachsend.",emoji:"📱"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Sneaker-Markt?",un:70,unit:"mil millones de $",hint:"Nike, Adidas und Resale-Markt zusammen.",emoji:"👟"},
 {q:"¿Cuántos mil millones Euro schulden Deutsche Privathaushalte insgesamt?",un:1900,unit:"mil millones de €",hint:"1,9 Billionen Euro Privatschulden.",emoji:"💸"},
 {q:"¿Cuántos mil millones Dollar wert ist der globale Markt für KI-Chips?",un:100,unit:"mil millones de $",hint:"Nvidia dominiert mit seinen GPUs.",emoji:"💻"},
];