// 🌍 HISTORIA – Español
export default [
 {q:"¿En qué año wurde das erste Brustimplantat einoperiert?",un:1962,unit:"Jahr",hint:"Timmie Jean Lindsey war die erste Frau en el mundo.",emoji:"👙"},
 {q:"¿Cuántos Frauen hatte König Salomo laut Bibel?",un:700,unit:"Frauen",hint:"Dazu kamen noch 300 Konkubinen.",emoji:"👑"},
 {q:"¿En qué año wurde Viagra erfunden?",un:1998,unit:"Jahr",hint:"Ursprünglich als Herzmedikament entwickelt.",emoji:"💊"},
 {q:"¿Cuántos millones Menschen starben beim Schwarzen Tod?",un:50,unit:"millones",hint:"Ein Drittel der europäischen Bevölkerung im 14. Jh.",emoji:"💀"},
 {q:"¿En qué año wurde die Guillotine en Frankreich abgeschafft?",un:1981,unit:"Jahr",hint:"Letzte Hinrichtung war 1977.",emoji:"⚔️"},
 {q:"¿Cuántos Jahre war die Berliner Mauer en Betrieb?",un:28,unit:"años",hint:"Von 1961 bis zum Fall am 9. November 1989.",emoji:"🧱"},
 {q:"¿En qué año wurde das erste Telefon von Bell patentiert?",un:1876,unit:"Jahr",hint:"Bell erhielt das Patent am 7. März 1876.",emoji:"📞"},
 {q:"¿Cuántos Arbeiter bauten schätzungsweise die Cheops-Pyramide?",un:20000,unit:"Arbeiter",hint:"Neuere Forschung: bezahlte Arbeiter, keine Sklaven.",emoji:"🏛️"},
 {q:"¿Cuántos millones Tonnen Gold sind schätzungsweise im Meer gelöst?",un:20,unit:"million tons",hint:"Genug für 9 Pfund Gold pro persona auf der Erde.",emoji:"⚱️"},
 {q:"¿En qué año wurde die erste Kondom-Fabrik eröffnet?",un:1844,unit:"Jahr",hint:"Nach Goodyears Vulkanisierung von Gummi.",emoji:"💊"},
 {q:"¿Cuántos Konkubinen hatte Kaiser Qianlong von China?",un:3000,unit:"Konkubinen",hint:"Er regierte von 1735 bis 1796.",emoji:"👑"},
 {q:"¿Cuántos Jahre dauerte der Hundertjährige Krieg tatsächlich?",un:116,unit:"años",hint:"Von 1337 bis 1453 – also 116 Jahre, nicht 100.",emoji:"⚔️"},
 {q:"¿Cuántos Personen wurden beim Hexenprozess von Salem hingerichtet?",un:19,unit:"personas",hint:"1692 en Massachusetts.",emoji:"🔥"},
 {q:"¿En qué año erfand Napoleon die Konservendose?",un:1810,unit:"Jahr",hint:"Für seine Armee – als Dosenöffner gab es noch keinen.",emoji:"🥫"},
 {q:"¿Cuántos Minuten dauerte der kürzeste Krieg der Geschichte?",un:38,unit:"minutos",hint:"Der Anglo-Sansibar-Krieg von 1896.",emoji:"⚔️"},
 {q:"¿Cuántos Jahre saß Nelson Mandela im Gefängnis?",un:27,unit:"años",hint:"Von 1964 bis 1990 auf Robben Island.",emoji:"✊"},
 {q:"¿En qué año fand die erste Mondlandung statt?",un:1969,unit:"Jahr",hint:"Apollo 11, 20. Juli 1969.",emoji:"🌙"},
 {q:"¿En qué año wurde die Titanic gebaut (Baubeginn)?",un:1909,unit:"Jahr",hint:"Sie sank bei ihrer Jungfernfahrt 1912.",emoji:"🚢"},
 {q:"¿Cuántos millones Menschen starben im Ersten Weltkrieg?",un:20,unit:"millones",hint:"Militär und Zivilbevölkerung zusammen.",emoji:"🕊️"},
 {q:"¿Cuántos Jahre regierte Queen Elizabeth II.?",un:70,unit:"años",hint:"Von 1952 bis zu ihrem Tod 2022.",emoji:"👑"},
 {q:"¿En qué año erfand Karl Benz das erste Automobil?",un:1885,unit:"Jahr",hint:"Der Benz Patent-Motorwagen – drei Räder, 0,75 PS.",emoji:"🚗"},
 {q:"¿Cuántos Stockwerke hatte das mundo Trade Center?",un:110,unit:"Stockwerke",hint:"Die Zwillingstürme wurden am 11. September 2001 zerstört.",emoji:"🏙️"},
 {q:"¿Cuántos Jahre dauerte der Zweite Weltkrieg?",un:6,unit:"años",hint:"Von 1939 bis 1945.",emoji:"🌍"},
 {q:"¿En qué año wurde die erste Atombombe gezündet?",un:1945,unit:"Jahr",hint:"Trinity-Test en New Mexico, 16. Juli 1945.",emoji:"💥"},
 {q:"¿Cuántos Menschen lebten auf der Erde im Jahr 1800?",un:1000000000,unit:"personas",hint:"Eine Milliarde – heute sind es 8 mil millones.",emoji:"🌍"},
 {q:"¿Cuántos Mal wurde Napoleon verbannt?",un:2,unit:"veces",hint:"Erst nach Elba, dann nach St. Helena.",emoji:"🏝️"},
 {q:"¿En qué año fiel die Mauer en Berlin?",un:1989,unit:"Jahr",hint:"9. November 1989 – einer der wichtigsten Tage der Geschichte.",emoji:"🧱"},
 {q:"¿Cuántos millones Juden wurden im Holocaust ermordet?",un:6,unit:"millones",hint:"Einer der dunkelsten Momente der Menschheitsgeschichte.",emoji:"✡️"},
 {q:"¿En qué año wurde das Internet erfunden (ARPANET)?",un:1969,unit:"Jahr",hint:"Das erste Netzwerk übertrug 1969 Daten.",emoji:"🌐"},
 {q:"¿Cuántos Sklaven wurden im transatlantischen Sklavenhandel verschleppt?",un:12000000,unit:"personas",hint:"12 millones Afrikaner wurden zwischen 1500 und 1900 verschleppt.",emoji:"⛓️"},
 {q:"¿En qué año landete Kolumbus en Amerika?",un:1492,unit:"Jahr",hint:"Am 12. Oktober 1492 betrat er San Salvador.",emoji:"⛵"},
 {q:"¿Cuántos Bücher der Bibel gibt es?",un:66,unit:"Bücher",hint:"39 im Alten, 27 im Neuen Testament.",emoji:"📖"},
 {q:"¿Cuántos millones Menschen starben en der Spanischen Grippe?",un:50,unit:"millones",hint:"1918-1920 – schlimmer als der Erste Weltkrieg.",emoji:"😷"},
 {q:"¿En qué año wurde die Magna Carta unterzeichnet?",un:1215,unit:"Jahr",hint:"König Johann ohne Land unterschrieb die erste Verfassung.",emoji:"📜"},
 {q:"¿Cuántos Götter hatte das alte Ägypten?",un:2000,unit:"Götter",hint:"Das ägyptische Pantheon war riesig.",emoji:"🏛️"},
 {q:"¿En qué año erfand Gutenberg den Buchdruck?",un:1450,unit:"Jahr",hint:"Die Druckpresse veränderte die Welt.",emoji:"📚"},
 {q:"¿Cuántos Jahre regierte das Römische Reich insgesamt?",un:503,unit:"años",hint:"Vom Stadtgründungsdatum 27 v.Chr. bis 476 n.Chr.",emoji:"🏛️"},
 {q:"¿Cuántos Tonnen Gold enthielt der Schatz von Tutanchamun?",un:110,unit:"kg Gold",hint:"Kg pures Gold im Sarkophag.",emoji:"🪙"},
 {q:"¿En qué año gab es die erste Zeitung?",un:1605,unit:"Jahr",hint:"'Relation' wurde 1605 en Straßburg gedruckt.",emoji:"📰"},
 {q:"¿Cuántos Menschen lebten zur Zeit Jesu auf der Erde?",un:300000000,unit:"personas",hint:"300 millones um das Jahr 0.",emoji:"🌍"},
 {q:"¿Cuántos Seiten umfasst die längste erhaltene Rechtskodex (Hammurabi)?",un:282,unit:"Paragraphen",hint:"Hammurabi regierte Babylon 1792-1750 v.Chr.",emoji:"📜"},
 {q:"¿En qué año wurde Stonehenge gebaut?",un:3100,unit:"v.Chr.",hint:"Die ältesten Steine wurden um 3100 v.Chr. aufgestellt.",emoji:"🗿"},
 {q:"¿Cuántos Sklaven besaß George Washington?",un:317,unit:"Sklaven",hint:"Bei seinem Tod besaß er 317 Sklaven.",emoji:"⛓️"},
 {q:"¿En qué año wurde das erste Kondom patentiert?",un:1844,unit:"Jahr",hint:"Aus vulkanisiertem Gummi – dank Goodyear.",emoji:"💊"},
 {q:"¿Cuántos Personen wurden beim Massaker von Nanjing getötet?",un:300000,unit:"personas",hint:"1937 töteten japanische Truppen bis zu 300.000 Chinesen.",emoji:"☮️"},
 {q:"¿En qué año fand das letzte öffentliche Hinrichtung en Frankreich statt?",un:1939,unit:"Jahr",hint:"Eugen Weidmann war der letzte öffentlich Hingerichtete.",emoji:"⚔️"},
 {q:"¿Cuántos Jahre dauerte die Inquisition der Katholischen Kirche?",un:600,unit:"años",hint:"Von 1184 bis 1820.",emoji:"🔥"},
 {q:"¿Cuántos Nationen nahmen am Zweiten Weltkrieg teil?",un:30,unit:"Nationen",hint:"Auf beiden Seiten zusammen über 30 Länder.",emoji:"🌍"},
 {q:"¿En qué año begann die Französische Revolution?",un:1789,unit:"Jahr",hint:"Mit dem Sturm auf die Bastille am 14. Juli.",emoji:"🗽"},
 {q:"¿Cuántos Personen wurden während der Französischen Revolution guillotiniert?",un:16594,unit:"personas",hint:"Während der Terrorherrschaft 1793-1794.",emoji:"⚔️"},
 {q:"¿Cuántos millones Menschen lebten im Römischen Reich?",un:65,unit:"millones",hint:"Im 2. Jahrhundert n.Chr. auf dem Höhepunkt.",emoji:"🏛️"},
 {q:"¿En qué año erfand Edison die Glühbirne?",un:1879,unit:"Jahr",hint:"Am 22. Oktober 1879 leuchtete sie 13,5 Stunden.",emoji:"💡"},
 {q:"¿Cuántos Frauen haben je eine vollständige Legislaturperiode als Staatschef abgeschlossen?",un:60,unit:"Frauen",hint:"Über 60 Frauen haben ein Land regiert.",emoji:"👩"},
 {q:"¿Cuántos Jahre dauerte die Sklaverei en den USA legal?",un:246,unit:"años",hint:"Von 1619 bis zur Abschaffung 1865.",emoji:"⛓️"},
 {q:"¿En qué año begann der Erste Kreuzzug?",un:1096,unit:"Jahr",hint:"Papst Urban II. rief dazu auf.",emoji:"⚔️"},
 {q:"¿Cuántos Personen überlebten den Untergang der Titanic?",un:710,unit:"personas",hint:"Von 2224 Bordpersonen.",emoji:"🚢"},
 {q:"¿Cuántos Jahre dauerte die Berliner Luftbrücke?",un:1,unit:"Jahr",hint:"Juni 1948 bis Mai 1949.",emoji:"✈️"},
 {q:"¿Cuántos millones Menschen starben en der Hungersnot en Irland?",un:1,unit:"Million",hint:"1845-1852 starben über 1 millones Iren.",emoji:"🥔"},
 {q:"¿En qué año erfand Fleming Penicillin?",un:1928,unit:"Jahr",hint:"Alexander Fleming entdeckte es zufällig.",emoji:"💊"},
 {q:"¿Cuántos Generäle hatte Napoleon en seinem Heer?",un:300,unit:"Generäle",hint:"Napoleon hatte das modernste Offizierskorps seiner Zeit.",emoji:"⚔️"},
 {q:"¿Cuántos Kilometer lang war die Große Chinesische Mauer?",un:21000,unit:"km",hint:"Das längste Bauwerk der Menschheitsgeschichte.",emoji:"🧱"},
 {q:"¿En qué año wurde die erste Dampfmaschine gebaut?",un:1712,unit:"Jahr",hint:"Thomas Newcomen baute die erste praktische Dampfmaschine.",emoji:"🔧"},
 {q:"¿Cuántos Männer haben auf dem Mond gestanden?",un:12,unit:"Männer",hint:"Alle 12 waren Amerikaner – alle Apollo-Missionen.",emoji:"🌙"},
 {q:"¿Cuántos Jahre regierte Cleopatra Ägypten?",un:21,unit:"años",hint:"Von 51 v.Chr. bis zu ihrem Tod 30 v.Chr.",emoji:"👑"},
 {q:"¿En qué año wurde das erste Foto aufgenommen?",un:1826,unit:"Jahr",hint:"Joseph Nicéphore Niépce machte die älteste erhaltene Aufnahme.",emoji:"📷"},
 {q:"¿Cuántos millones Menschen tötete Stalin?",un:20,unit:"millones",hint:"Schätzungen variieren zwischen 6 und 20 millones.",emoji:"☭"},
 {q:"¿En qué año erfand Wright Brothers das Flugzeug?",un:1903,unit:"Jahr",hint:"Am 17. Dezember 1903 flog Orville 12 Sekunden.",emoji:"✈️"},
 {q:"¿Cuántos Personen starben beim Bau des Panamakanals?",un:27500,unit:"personas",hint:"Durch Malaria, Gelbfieber und Unfälle.",emoji:"⚒️"},
 {q:"¿Cuántos Jahre baute man am Kölner Dom?",un:632,unit:"años",hint:"Von 1248 bis zur Vollendung 1880.",emoji:"⛪"},
 {q:"¿En qué año erfand Bell das Telefon?",un:1876,unit:"Jahr",hint:"Am 10. März 1876 telefonierte Bell mit seinem Assistenten.",emoji:"📞"},
 {q:"¿Cuántos millones Menschen starben bei der Atombombe en Hiroshima?",un:140,unit:"mil",hint:"000 starben bis Ende 1945.",emoji:"💥"},
 {q:"¿En qué año fand die Oktoberrevolution statt?",un:1917,unit:"Jahr",hint:"Am 7. November 1917 stürmten Bolschewiken den Winterpalast.",emoji:"☭"},
 {q:"¿Cuántos Nationen unterzeichneten die UN-Charta?",un:51,unit:"Nationen",hint:"Bei Gründung 1945 – heute 193.",emoji:"🌍"},
 {q:"¿En qué año verlor Deutschland den Ersten Weltkrieg?",un:1918,unit:"Jahr",hint:"Waffenstillstand am 11. November 1918.",emoji:"🕊️"},
 {q:"¿Cuántos Stockwerke hat der Eiffelturm?",un:3,unit:"Etagen",hint:"Mit drei Aussichtsplattformen.",emoji:"🗼"},
 {q:"¿En qué año wurde die Unabhängigkeitserklärung der USA unterzeichnet?",un:1776,unit:"Jahr",hint:"Am 4. Juli 1776.",emoji:"🗽"},
 {q:"¿Cuántos Jahre lebte Leonardo da Vinci?",un:67,unit:"años",hint:"1452-1519 – Universalgenie der Renaissance.",emoji:"🎨"},
 {q:"¿En qué año erfand Tesla die Wechselstrom-Übertragung?",un:1888,unit:"Jahr",hint:"Der Kampf gegen Edison begann.",emoji:"⚡"},
 {q:"¿Cuántos Nationen nahmen un der Unterzeichnung des Versailler Vertrags teil?",un:27,unit:"Nationen",hint:"1919 nach dem Ersten Weltkrieg.",emoji:"📜"},
 {q:"¿En qué año erfand Marconi das Radio?",un:1896,unit:"Jahr",hint:"Guglielmo Marconi meldete 1896 sein Patent un.",emoji:"📻"},
 {q:"¿Cuántos Personen wurden en der Bartholomäusnacht getötet?",un:30000,unit:"personas",hint:"1572 – Massaker un Hugenotten en Frankreich.",emoji:"🔥"},
 {q:"¿En qué año erschoss ein Serbe den österreichischen Kronprinzen?",un:1914,unit:"Jahr",hint:"Gavrilo Princip erschoss Franz Ferdinand.",emoji:"💣"},
 {q:"¿Cuántos km lang ist der Suezkanal?",un:193,unit:"km",hint:"Verbindet das Mittelmeer mit dem Roten Meer.",emoji:"⛵"},
 {q:"¿En qué año wurde die Berliner Mauer gebaut?",un:1961,unit:"Jahr",hint:"Am 13. August 1961 begann der Bau.",emoji:"🧱"},
 {q:"¿Cuántos Jahre existierte das Dritte Reich?",un:12,unit:"años",hint:"Von 1933 bis 1945.",emoji:"☮️"},
 {q:"¿En qué año wurde die NATO gegründet?",un:1949,unit:"Jahr",hint:"Am 4. April 1949 en Washington.",emoji:"🌍"},
 {q:"¿Cuántos millones Soldaten starben im Zweiten Weltkrieg?",un:25,unit:"millones",hint:"Zivile Opfer waren mit ~50 Mio. noch mehr.",emoji:"🕊️"},
 {q:"¿En qué año wurde das erste Konzentrationslager eröffnet?",un:1933,unit:"Jahr",hint:"Dachau wurde am 22. März 1933 eröffnet.",emoji:"☮️"},
 {q:"¿Cuántos Tage dauerte die Belagerung von Stalingrad?",un:160,unit:"días",hint:"Von August 1942 bis Februar 1943.",emoji:"⚔️"},
 {q:"¿En qué año wurde die EU gegründet?",un:1993,unit:"Jahr",hint:"Der Maastricht-Vertrag trat am 1. November 1993 en Kraft.",emoji:"🇪🇺"},
 {q:"¿Cuántos Länder gehörten zur Sowjetunion?",un:15,unit:"countries",hint:"Die UdSSR löste sich 1991 auf.",emoji:"☭"},
 {q:"¿En qué año entdeckte Newton die Schwerkraft?",un:1666,unit:"Jahr",hint:"Der Apfel fiel – die Legende begann.",emoji:"🍎"},
 {q:"¿Cuántos Personen wurden en der Nacht der langen Messer ermordet?",un:85,unit:"personas",hint:"1934 – Hitler ließ SA-Führer und politische Gegner töten.",emoji:"🔪"},
 {q:"¿En qué año erfand Pasteur die Pasteurisierung?",un:1864,unit:"Jahr",hint:"Louis Pasteur entwickelte sie für Wein.",emoji:"🧪"},
 {q:"¿Cuántos km lang war der Westwall im Zweiten Weltkrieg?",un:630,unit:"km",hint:"Deutschlands Befestigungslinie un der Westgrenze.",emoji:"⚔️"},
 {q:"¿En qué año wurde der Euro eingeführt?",un:1999,unit:"Jahr",hint:"Als Buchgeld – als Bargeld ab 2002.",emoji:"💶"},
 {q:"¿Cuántos Personen starben beim Erdbeben von Lissabon?",un:60000,unit:"personas",hint:"1755 – eines der schlimmsten Erdbeben Europas.",emoji:"🌋"},
 {q:"¿En qué año gründete Hitler die NSDAP?",un:1919,unit:"Jahr",hint:"Als DAP – en NSDAP umbenannt 1920.",emoji:"☮️"},
 {q:"¿Cuántos Jahre dauerte die Reformation?",un:50,unit:"años",hint:"Von Luthers Thesenanschlag 1517 bis etwa 1570.",emoji:"⛪"},
 {q:"¿En qué año wurde der Eiffelturm fertiggestellt?",un:1889,unit:"Jahr",hint:"Für die Weltausstellung en Paris.",emoji:"🗼"},
 {q:"¿Cuántos millones Menschen starben en der Ukrainischen Hungersnot (Holodomor)?",un:4,unit:"millones",hint:"1932-1933 – vom Sowjet-Regime verursacht.",emoji:"🌾"},
 {q:"¿En qué año begann der Koreakrieg?",un:1950,unit:"Jahr",hint:"Am 25. Juni 1950.",emoji:"⚔️"},
 {q:"¿Cuántos km lang war die Ostfront im Zweiten Weltkrieg?",un:4000,unit:"km",hint:"Die längste Front der Kriegsgeschichte.",emoji:"⚔️"},
 {q:"¿En qué año erfand Tesla die Neonröhre?",un:1891,unit:"Jahr",hint:"Tesla demonstrierte seine drahtlosen Lampen.",emoji:"💡"},
 {q:"¿Cuántos Seiten umfasst Hitlers Mein Kampf?",un:782,unit:"Seiten",hint:"Geschrieben während seiner Haftzeit 1924-1925.",emoji:"📖"},
 {q:"¿En qué año wurde Deutschland geteilt?",un:1949,unit:"Jahr",hint:"BRD und DDR entstanden 1949.",emoji:"🧱"},
 {q:"¿Cuántos Länder invadierte das Britische Empire?",un:171,unit:"countries",hint:"rápido die ganze Welt – nur 22 Länder nie.",emoji:"🗺️"},
 {q:"¿En qué año erfand Nobel das Dynamit?",un:1867,unit:"Jahr",hint:"Alfred Nobel patentierte es 1867.",emoji:"💣"},
 {q:"¿Cuántos millones Menschen wurden von den Mongolen getötet?",un:40,unit:"millones",hint:"Dschingis Khan und seine Nachfolger töteten millones.",emoji:"⚔️"},
 {q:"¿En qué año wurde die UNO gegründet?",un:1945,unit:"Jahr",hint:"Am 24. Oktober 1945 – der UN-Tag.",emoji:"🌍"},
 {q:"¿Cuántos km lang war die Chinesische Mauer als sie vollständig war?",un:21196,unit:"km",hint:"Inklusive aller Seiten und Verzweigungen.",emoji:"🧱"},
 {q:"¿En qué año verbrannte Joan de Arc?",un:1431,unit:"Jahr",hint:"Am 30. Mai 1431 en Rouen.",emoji:"🔥"},
 {q:"¿Cuántos millones Menschen starben un der Pest im 14. Jahrhundert?",un:75,unit:"millones",hint:"Ein Drittel der Weltbevölkerung.",emoji:"💀"},
 {q:"¿En qué año erfand Daimler den Verbrennungsmotor?",un:1885,unit:"Jahr",hint:"Benz und Daimler erfanden unabhängig voneinander.",emoji:"🚗"},
 {q:"¿Cuántos Personen haben auf dem Mond gestanden?",un:12,unit:"personas",hint:"Alle bei Apollo-Missionen zwischen 1969-1972.",emoji:"🌙"},
 {q:"¿En qué año begann der Vietnamkrieg (US-Beteiligung)?",un:1965,unit:"Jahr",hint:"Die USA griffen direkt 1965 ein.",emoji:"✈️"},
 {q:"¿Cuántos millones Menschen starben im Mongolenreich?",un:40,unit:"millones",hint:"Dschingis Khans Feldzüge töteten millones.",emoji:"⚔️"},
 {q:"¿En qué año wurde das erste Konzentrationslager en Ausschwitz gebaut?",un:1940,unit:"Jahr",hint:"Auschwitz I wurde 1940 eröffnet.",emoji:"☮️"},
 {q:"¿Cuántos Personen starben auf der Titanic?",un:1514,unit:"personas",hint:"Von 2224 Personen un Bord.",emoji:"🚢"},
 {q:"¿En qué año wurde die Atombombe auf Hiroshima abgeworfen?",un:1945,unit:"Jahr",hint:"Am 6. August 1945.",emoji:"💥"},
 {q:"¿Cuántos Stockwerke hatte der Turm von Babel laut Bibel?",un:7,unit:"Etagen",hint:"Eine Zikkurat mit 7 Stufen.",emoji:"🏛️"},
 {q:"¿En qué año begann die Reformation durch Martin Luther?",un:1517,unit:"Jahr",hint:"Mit dem Thesenanschlag am 31. Oktober.",emoji:"⛪"},
 {q:"¿Cuántos millones Menschen starben im Dreißigjährigen Krieg?",un:8,unit:"millones",hint:"Ein Drittel der deutschen Bevölkerung.",emoji:"⚔️"},
 {q:"¿En qué año wurde der Panamakanal eröffnet?",un:1914,unit:"Jahr",hint:"Am 15. August 1914.",emoji:"⛵"},
 {q:"¿Cuántos km lang ist die Transsibirische Eisenbahn?",un:9289,unit:"km",hint:"Die längste Eisenbahnstrecke der Welt.",emoji:"🚂"},
 {q:"¿En qué año begann der Kalte Krieg?",un:1947,unit:"Jahr",hint:"Mit der Truman-Doktrin im März 1947.",emoji:"☭"},
 {q:"¿Cuántos millones Sklaven wurden en die USA importiert?",un:400,unit:"mil",hint:"000 – die Nachkommen sind über 40 millones.",emoji:"⛓️"},
 {q:"¿En qué año fiel der Eiserne Vorhang?",un:1989,unit:"Jahr",hint:"Öffneten sich die Grenzen.",emoji:"🧱"},
 {q:"¿Cuántos Jahre dauerte der Dreißigjährige Krieg?",un:30,unit:"años",hint:"Von 1618 bis 1648.",emoji:"⚔️"},
 {q:"¿En qué año wurde das erste Automobile öffentlich vorgestellt?",un:1886,unit:"Jahr",hint:"Bertha Benz fuhr die erste Langstrecke.",emoji:"🚗"},
 {q:"¿En qué año erfand Morse den Morsecode?",un:1838,unit:"Jahr",hint:"Samuel Morse demonstrierte ihn 1838.",emoji:"📡"},
 {q:"¿Cuántos Sprachen spricht die UNO offiziell?",un:6,unit:"Sprachen",hint:"Arabisch, Chinesisch, Englisch, Französisch, Russisch, Spanisch.",emoji:"🌍"},
 {q:"¿En qué año begann die Entdeckung Amerikas durch Vikinger?",un:1000,unit:"Jahr",hint:"Leif Eriksson erreichte Nordamerika um 1000 n.Chr.",emoji:"⛵"},
 {q:"¿Cuántos km lang ist der Amazonas en Südamerika?",un:6400,unit:"km",hint:"Einer der längsten Flüsse der Welt.",emoji:"🌿"},
 {q:"¿En qué año wurde das erste Parlament gegründet (Island)?",un:930,unit:"Jahr",hint:"Das Althing en Island – ältestes Parlament der Welt.",emoji:"📜"},
 {q:"¿Cuántos millones Menschen starben bei der Spanischen Grippe 1918?",un:50,unit:"millones",hint:"Mehr als im Ersten Weltkrieg.",emoji:"😷"},
 {q:"¿En qué año wurde die Berliner Mauer offiziell abgerissen?",un:1990,unit:"Jahr",hint:"Der offizielle Abriss begann 1990.",emoji:"🧱"},
 {q:"¿Cuántos Seiten hat das Alte Testament?",un:929,unit:"Kapitel",hint:"Kapitel im Alten Testament.",emoji:"📖"},
 {q:"¿En qué año erfand Semmelweis das Händewaschen?",un:1847,unit:"Jahr",hint:"Er rettete Menschenleben – wurde dafür aber verlacht.",emoji:"🧼"},
 {q:"¿Cuántos millones Menschen starben en Chinas Großem Sprung nach vorn?",un:45,unit:"millones",hint:"Maos Hungersnot 1959-1961.",emoji:"🌾"},
 {q:"¿En qué año wurde das erste Frauenwahlrecht eingeführt (Neuseeland)?",un:1893,unit:"Jahr",hint:"Neuseeland war das erste Land en el mundo.",emoji:"🗳️"},
 {q:"¿Cuántos Jahre dauerte der Peloponnesische Krieg?",un:27,unit:"años",hint:"Athen gegen Sparta, 431-404 v.Chr.",emoji:"⚔️"},
 {q:"¿En qué año wurde Saddam Hussein hingerichtet?",un:2006,unit:"Jahr",hint:"Am 30. Dezember 2006.",emoji:"☮️"},
 {q:"¿Cuántos millones Menschen tötete Pol Pot en Kambodscha?",un:2,unit:"millones",hint:"Ein Viertel der Bevölkerung Kambodschas.",emoji:"☮️"},
 {q:"¿En qué año begann der Irakkrieg?",un:2003,unit:"Jahr",hint:"Am 20. März 2003 begann die US-Invasion.",emoji:"⚔️"},
 {q:"¿Cuántos millones Menschen waren bei D-día beteiligt?",un:3,unit:"millones",hint:"millones Alliierte planten die Invasion.",emoji:"⚔️"},
 {q:"¿En qué año wurde der Erste Computer (ENIAC) gebaut?",un:1945,unit:"Jahr",hint:"ENIAC füllte einen ganzen Raum.",emoji:"💻"},
 {q:"¿Cuántos Nationen unterzeichneten den Kyoto-Protokoll?",un:192,unit:"Nationen",hint:"rápido alle Länder der Welt.",emoji:"🌍"},
 {q:"¿En qué año erfand Levi Strauss die Jeans?",un:1873,unit:"Jahr",hint:"Für Goldgräber en Kalifornien.",emoji:"👖"},
 {q:"¿Cuántos Personen starben beim Attentat auf Abraham Lincoln?",un:1,unit:"persona",hint:"Lincoln selbst – der Attentäter floh zunächst.",emoji:"🎩"},
 {q:"¿En qué año endete der Koreakrieg?",un:1953,unit:"Jahr",hint:"Mit einem Waffenstillstand – kein Friedensvertrag.",emoji:"🕊️"},
 {q:"¿Cuántos millones Flüchtlinge gab es nach dem Zweiten Weltkrieg?",un:50,unit:"millones",hint:"Die größte Flüchtlingsbewegung der Geschichte.",emoji:"🚶"},
 {q:"¿En qué año wurde das Frauenwahlrecht en Deutschland eingeführt?",un:1918,unit:"Jahr",hint:"Nach dem Ersten Weltkrieg.",emoji:"🗳️"},
 {q:"¿Cuántos Jahre saß Mandela im Gefängnis auf Robben Island?",un:18,unit:"años",hint:"Von 27 Jahren Gesamtstrafe.",emoji:"✊"},
 {q:"¿En qué año landete der erste Mensch auf dem Mars?",un:9999,unit:"(noch nicht)",hint:"Stand 2025 ist es noch kein Mensch auf dem Mars gelandet.",emoji:"🔴"},
 {q:"¿Cuántos Personen haben die ISS besucht?",un:250,unit:"personas",hint:"Über 250 Menschen aus 20 Ländern.",emoji:"🚀"},
 {q:"¿En qué año wurde das erste iPhone vorgestellt?",un:2007,unit:"Jahr",hint:"Steve Jobs präsentierte es am 9. Januar 2007.",emoji:"📱"},
 {q:"¿Cuántos mil millones Menschen nutzen das Internet?",un:5,unit:"mil millones",hint:"Über 60% der Weltbevölkerung.",emoji:"🌐"},
 {q:"¿En qué año wurde Facebook gegründet?",un:2004,unit:"Jahr",hint:"Mark Zuckerberg gründete es als Harvard-Student.",emoji:"📱"},
 {q:"¿Cuántos Jahre hat los humanos das Feuer genutzt?",un:1000000,unit:"años",hint:"Erste Belege für Feuer vor 1 millones Jahren.",emoji:"🔥"},
 {q:"¿En qué año erfand Archimedes sein Prinzip?",un:250,unit:"v.Chr.",hint:"Archimedes rief 'Heureka!' en seiner Badewanne.",emoji:"🛁"},
 {q:"¿Cuántos millones Tonnen Gold wurden en der Geschichte abgebaut?",un:190,unit:"Tausend Tonnen",hint:"000 Tonnen – aller abgebaute Gold der Geschichte.",emoji:"🪙"},
 {q:"¿En qué año erfand Pasteur den Impfstoff gegen Tollwut?",un:1885,unit:"Jahr",hint:"Die erste erfolgreiche Tollwutimpfung.",emoji:"💉"},
 {q:"¿Cuántos Personen haben je den Nobelpreis erhalten?",un:950,unit:"personas",hint:"Manche Preisträger haben ihn zweimal bekommen.",emoji:"🏆"},
 {q:"¿En qué año erfand Röntgen die Röntgenstrahlen?",un:1895,unit:"Jahr",hint:"Am 8. November 1895 entdeckte er sie zufällig.",emoji:"🩻"},
 {q:"¿Cuántos Länder beteiligten sich am Ersten Weltkrieg?",un:30,unit:"countries",hint:"Auf beiden Seiten zusammen.",emoji:"⚔️"},
 {q:"¿En qué año gründete Hitler die SS?",un:1925,unit:"Jahr",hint:"Als persönliche Leibwache, später Terrorapparat.",emoji:"☮️"},
 {q:"¿Cuántos millones Tonnen Sprengstoff wurden im Zweiten Weltkrieg verwendet?",un:5,unit:"million tons",hint:"Der Zweite Weltkrieg übertraf den Ersten bei weitem.",emoji:"💣"},
 {q:"¿En qué año erfand Curie das Radium?",un:1898,unit:"Jahr",hint:"Marie und Pierre Curie entdeckten Polonium und Radium.",emoji:"☢️"},
 {q:"¿Cuántos Jahre alt ist das älteste bekannte Schriftsystem?",un:5500,unit:"años",hint:"Sumerische Keilschrift aus Mesopotamien.",emoji:"📜"},
 {q:"¿En qué año begann der Amerikanische Bürgerkrieg?",un:1861,unit:"Jahr",hint:"Am 12. April 1861 mit der Beschießung Fort Sumters.",emoji:"⚔️"},
 {q:"¿Cuántos millones Menschen starben im Amerikanischen Bürgerkrieg?",un:750,unit:"mil",hint:"000 – der verlustreichste amerikanische Krieg.",emoji:"⚔️"},
 {q:"¿En qué año wurde das erste Kernkraftwerk gebaut?",un:1954,unit:"Jahr",hint:"Obninsk en der Sowjetunion, 1954.",emoji:"⚡"},
 {q:"¿Cuántos Atommächte gibt es offiziell?",un:9,unit:"countries",hint:"USA, Russland, UK, Frankreich, China, Indien, Pakistan, Israel, Nordkorea.",emoji:"☢️"},
 {q:"¿En qué año wurde das Konzentrationslager Auschwitz befreit?",un:1945,unit:"Jahr",hint:"Am 27. Januar 1945 durch sowjetische Truppen.",emoji:"☮️"},
 {q:"¿Cuántos Jahre war die UdSSR ein Staat?",un:69,unit:"años",hint:"Von 1922 bis zur Auflösung 1991.",emoji:"☭"},
 {q:"¿En qué año gründete Roosevelt die CIA?",un:1947,unit:"Jahr",hint:"Truman unterzeichnete den National Security Act.",emoji:"🕵️"},
 {q:"¿Cuántos millones Tonnen werden al año en Atomkraftwerken verarbeitet?",un:0.07,unit:"Millionen Tonnen Uran",hint:"70.000 Tonnen Uran al año en el mundo.",emoji:"⚡"},
 {q:"¿En qué año erfand Archimedes den Hebel?",un:250,unit:"v.Chr.",hint:"'Gebt mir einen festen Punkt und ich hebe die Welt aus den Angeln.'",emoji:"⚙️"},
 {q:"¿Cuántos Sprachen sprach Kleopatra?",un:9,unit:"Sprachen",hint:"Sie war die erste Ptolemäerin die Ägyptisch sprach.",emoji:"👑"},
 {q:"¿En qué año fand der erste Olympische Wettkampf statt?",un:776,unit:"v.Chr.",hint:"en Olympia, Griechenland.",emoji:"🏅"},
 {q:"¿Cuántos Meter hoch war das Kolosseum en Rom?",un:48,unit:"metros",hint:"Das größte Amphitheater der Antike.",emoji:"🏛️"},
 {q:"¿En qué año wurde das erste U-Boot eingesetzt?",un:1776,unit:"Jahr",hint:"Die Turtle wurde im Amerikanischen Unabhängigkeitskrieg eingesetzt.",emoji:"🌊"},
 {q:"¿Cuántos km entfernt ist Karthago von Rom?",un:1500,unit:"km",hint:"Trotzdem kämpften sie drei Kriege lang.",emoji:"⚔️"},
 {q:"¿En qué año erfand Lister die Antisepsis?",un:1867,unit:"Jahr",hint:"Joseph Lister revolutionierte die Chirurgie.",emoji:"🏥"},
 {q:"¿Cuántos Personen wurden im Tower de London hingerichtet?",un:3000,unit:"personas",hint:"Über 3000 Jahre Exekutionen.",emoji:"🏰"},
 {q:"¿En qué año baute Henry Ford das erste Fließband?",un:1913,unit:"Jahr",hint:"Die Massenproduktion begann en Detroit.",emoji:"🚗"},
 {q:"¿Cuántos Jahre regierte das Osmanische Reich?",un:623,unit:"años",hint:"Von 1299 bis 1922.",emoji:"🌙"},
 {q:"¿En qué año erfand Morse den ersten Telegrafen?",un:1837,unit:"Jahr",hint:"Das erste elektrische Nachrichtensystem.",emoji:"📡"},
 {q:"¿Cuántos Personen starben bei der Bombardierung von Dresden?",un:25000,unit:"personas",hint:"Im Februar 1945.",emoji:"💥"},
 {q:"¿En qué año begann der Spanische Bürgerkrieg?",un:1936,unit:"Jahr",hint:"Franco gegen die Republik.",emoji:"⚔️"},
 {q:"¿Cuántos Jahre lang herrschte die Apartheid en Südafrika?",un:46,unit:"años",hint:"Von 1948 bis zur Aufhebung 1994.",emoji:"✊"},
 {q:"¿En qué año erfand Freud die Psychoanalyse?",un:1899,unit:"Jahr",hint:"Mit der Veröffentlichung der Traumdeutung.",emoji:"🧠"},
 {q:"¿Cuántos mil millones Dollar kostete das Manhattan-Projekt?",un:2,unit:"mil millones de $",hint:"en heutiger Kaufkraft über 25 mil millones.",emoji:"💣"},
 {q:"¿En qué año fand die Befreiung der KZs statt?",un:1945,unit:"Jahr",hint:"Mit dem Vormarsch der Alliierten.",emoji:"🕊️"},
 {q:"¿Cuántos km weit schoss die Pariser Kanone im Ersten Weltkrieg?",un:130,unit:"km",hint:"Konnte Paris vom deutschen Hinterland aus bombardieren.",emoji:"💣"},
 {q:"¿En qué año wurde die erste Weltkarte gezeichnet?",un:600,unit:"v.Chr.",hint:"Von Anaximander aus Milet.",emoji:"🗺️"},
 {q:"¿Cuántos Sprachen hat das Alte Testament ursprünglich?",un:3,unit:"Sprachen",hint:"Hebräisch, Aramäisch und Griechisch.",emoji:"📖"},
 {q:"¿En qué año erfand Pascal den Taschenrechner?",un:1642,unit:"Jahr",hint:"Die Pascaline konnte addieren und subtrahieren.",emoji:"🔢"},
 {q:"¿Cuántos millones Menschen lebten en Pompeji beim Ausbruch des Vesuvs?",un:11,unit:"mil",hint:"000 Einwohner – viele entkamen.",emoji:"🌋"},
 {q:"¿En qué año erfand Watt die Dampfmaschine (verbesserte Version)?",un:1769,unit:"Jahr",hint:"James Watt verbesserte Newcomens Version erheblich.",emoji:"⚙️"},
 {q:"¿Cuántos Tonnen wog das schwerste Schlachtschiff aller Zeiten (Yamato)?",un:72000,unit:"tons",hint:"Das japanische Schlachtschiff Yamato.",emoji:"⛵"},
 {q:"¿En qué año wurde der erste Weltrat des Sports gegründet?",un:1896,unit:"Jahr",hint:"Die ersten modernen Olympischen Spiele 1896.",emoji:"🏅"},
 {q:"¿Cuántos Völker lebten im Römischen Reich?",un:50,unit:"Völker",hint:"Das Reich vereinte Dutzende Kulturen.",emoji:"🏛️"},
 {q:"¿En qué año erfand Galilei das Teleskop?",un:1609,unit:"Jahr",hint:"Er verbesserte ein niederländisches Modell.",emoji:"🔭"},
 {q:"¿Cuántos km lang war die Frontlinie bei Verdun?",un:30,unit:"km",hint:"Über 300 Tage dauerte die Schlacht.",emoji:"⚔️"},
 {q:"¿En qué año erfand Darwin die Evolutionstheorie?",un:1859,unit:"Jahr",hint:"Mit der Veröffentlichung von 'On el Origin de Species'.",emoji:"🔬"},
 {q:"¿Cuántos millones Sklaven starben auf der Überfahrt (Middle Passage)?",un:2,unit:"millones",hint:"15-20% aller Verschleppten starben auf See.",emoji:"⛓️"},
 {q:"¿En qué año begann der Peloponnesische Krieg?",un:431,unit:"v.Chr.",hint:"Athen gegen Sparta.",emoji:"⚔️"},
 {q:"¿Cuántos Jahre regierte Alexander der Große?",un:13,unit:"años",hint:"Von 336 bis zu seinem Tod 323 v.Chr.",emoji:"⚔️"},
 {q:"¿En qué año erfand Einstein die Relativitätstheorie?",un:1905,unit:"Jahr",hint:"Das 'Annus Mirabilis' – Einstein veröffentlichte 4 Revolutionen.",emoji:"⚛️"},
 {q:"¿Cuántos Meter hoch war das Kolosseum?",un:48,unit:"metros",hint:"4 Stockwerke – fasste 50.000-80.000 Zuschauer.",emoji:"🏛️"},
 {q:"¿En qué año wurde der erste Satellit (Sputnik) gestartet?",un:1957,unit:"Jahr",hint:"Am 4. Oktober 1957.",emoji:"🛰️"},
 {q:"¿Cuántos millones Menschen besuchten die Weltausstellung 1889 en Paris?",un:32,unit:"millones",hint:"Mit dem Eiffelturm als Hauptattraktion.",emoji:"🗼"},
 {q:"¿En qué año erfand Röntgen seine Strahlen?",un:1895,unit:"Jahr",hint:"Wilhelm Röntgen entdeckte sie am 8. November.",emoji:"🩻"},
 {q:"¿Cuántos Personen saßen beim letzten Abendmahl?",un:13,unit:"personas",hint:"Jesus und 12 Jünger.",emoji:"✝️"},
 {q:"¿En qué año wurde Deutschland (BRD) Mitglied der NATO?",un:1955,unit:"Jahr",hint:"Am 9. Mai 1955.",emoji:"🇩🇪"},
 {q:"¿Cuántos millones Tonnen CO₂ stieß die Welt 1900 aus?",un:2000,unit:"million tons",hint:"Heute sind es 37 mil millones Tonnen.",emoji:"🌿"},
 {q:"¿En qué año wurde Karthago zerstört?",un:146,unit:"v.Chr.",hint:"Das dritte Punische Krieg endete mit der Vernichtung.",emoji:"🏛️"},
 {q:"¿Cuántos millones Menschen lebten zur Zeit Alexanders des Großen auf der Erde?",un:150,unit:"millones",hint:"Um 300 v.Chr. – Weltbevölkerung sehr viel kleiner.",emoji:"🌍"},
 {q:"¿En qué año wurde der Turm von London gebaut?",un:1078,unit:"Jahr",hint:"Wilhelm der Eroberer ließ ihn bauen.",emoji:"🏰"},
 {q:"¿Cuántos Jahre dauerte die mongolische Herrschaft über Russland?",un:240,unit:"años",hint:"Das Mongolische Joch von 1240 bis 1480.",emoji:"⚔️"},
 {q:"¿En qué año fand die Uraufführung von Beethovens 9. Symphonie statt?",un:1824,unit:"Jahr",hint:"en Wien – Beethoven war damals taub.",emoji:"🎵"},
 {q:"¿Cuántos km lang war das Netz der Römerstraßen?",un:400000,unit:"km",hint:"400.000 km Straßen verbanden das Imperium.",emoji:"🏛️"},
 {q:"¿En qué año erfand Franklin Blitzableiter?",un:1752,unit:"Jahr",hint:"Benjamin Franklin und sein berühmter Drachen.",emoji:"⚡"},
 {q:"¿Cuántos Gladiatorenkämpfe fanden im Kolosseum al año statt?",un:100,unit:"días",hint:"Bis zu 100 Spieltage im Jahr.",emoji:"⚔️"},
 {q:"¿En qué año wurde Österreich-Ungarn aufgelöst?",un:1918,unit:"Jahr",hint:"Ende des Ersten Weltkriegs.",emoji:"🗺️"},
 {q:"¿Cuántos millones Menschen waren en der Sklaverei en den USA 1860?",un:4,unit:"millones",hint:"Kurz vor dem Bürgerkrieg.",emoji:"⛓️"},
 {q:"¿En qué año begann der Vietnamkrieg für Vietnam?",un:1955,unit:"Jahr",hint:"US-Beteiligung ab 1965.",emoji:"🌿"},
 {q:"¿Cuántos Personen unterzeichneten die US-Unabhängigkeitserklärung?",un:56,unit:"personas",hint:"Delegierte am 4. Juli 1776.",emoji:"📜"},
 {q:"¿En qué año wurde der Suezkanal eröffnet?",un:1869,unit:"Jahr",hint:"Am 17. November 1869.",emoji:"⛵"},
 {q:"¿Cuántos millones Menschen starben en Maos Kulturrevolution?",un:2,unit:"millones",hint:"Von 1966 bis 1976.",emoji:"☭"},
 {q:"¿En qué año entdeckte Marco Polo China?",un:1271,unit:"Jahr",hint:"Er reiste 17 Jahre durch Asien.",emoji:"🗺️"},
 {q:"¿Cuántos Jahre dauerte die Belagerung von Troja laut Homer?",un:10,unit:"años",hint:"Der Trojanische Krieg.",emoji:"⚔️"},
 {q:"¿En qué año begann die Kreuzzugs-Ära?",un:1096,unit:"Jahr",hint:"Erster Kreuzzug ausgerufen von Papst Urban II.",emoji:"✝️"},
 {q:"¿Cuántos millones Tote forderte der Dreißigjährige Krieg?",un:8,unit:"millones",hint:"Ein Drittel der deutschen Bevölkerung.",emoji:"💀"},
 {q:"¿En qué año wurde die erste Zeitung en Deutschland gedruckt?",un:1605,unit:"Jahr",hint:"Relation en Straßburg.",emoji:"📰"},
 {q:"¿Cuántos Jahre regierte Kaiser Augustus?",un:44,unit:"años",hint:"Von 27 v.Chr. bis 14 n.Chr.",emoji:"🏛️"},
 {q:"¿En qué año wurde Konstantinopel von den Osmanen eingenommen?",un:1453,unit:"Jahr",hint:"Ende des Byzantinischen Reiches.",emoji:"🌙"},
 {q:"¿Cuántos Tage dauerte das Massaker von My Lai im Vietnamkrieg?",un:1,unit:"Tag",hint:"Am 16. März 1968 – 504 Zivilisten getötet.",emoji:"☮️"},
 {q:"¿En qué año wurde der erste Motor-Flug versucht (Langley)?",un:1903,unit:"Jahr",hint:"Langley scheiterte kurz vor den Wrights.",emoji:"✈️"},
 {q:"¿Cuántos millones Iren emigrierten nach der Hungersnot?",un:1,unit:"Million",hint:"1845-1852 – neben 1 Mio. Toten.",emoji:"🌿"},
 {q:"¿En qué año wurde Argentinien unabhängig?",un:1816,unit:"Jahr",hint:"9. Juli 1816 – Unabhängigkeitstag.",emoji:"🇦🇷"},
 {q:"¿Cuántos Jahre regierte Dschingis Khan?",un:21,unit:"años",hint:"Von 1206 bis zu seinem Tod 1227.",emoji:"⚔️"},
 {q:"¿En qué año wurde die Atombombe erstmals eingesetzt?",un:1945,unit:"Jahr",hint:"Hiroshima, 6. August 1945.",emoji:"💥"},
 {q:"¿Cuántos millones Tonnen Gold schürfte das Römische Reich?",un:1,unit:"Tausend Tonnen",hint:"Wenig – aber das meiste der Antike.",emoji:"🪙"},
 {q:"¿En qué año wurde Japan demokratisch?",un:1945,unit:"Jahr",hint:"Nach der Kapitulation im Zweiten Weltkrieg.",emoji:"🗳️"},
 {q:"¿Cuántos Schlachten verlor Napoleon insgesamt?",un:10,unit:"Schlachten",hint:"Er gewann 60 von 70 Schlachten.",emoji:"⚔️"},
 {q:"¿En qué año gründete William Penn Pennsylvania?",un:1681,unit:"Jahr",hint:"Als Zuflucht für Quäker.",emoji:"📜"},
];