// 💀 RÉCORDS BIZARROS – Español
export default [
 {q:"Wie lang war der längste Fingernagel einer Frau en cm?",un:909,unit:"cm",hint:"Lee Redmond ließ ihre Nägel 30 Jahre wachsen.",emoji:"💅"},
 {q:"¿Cuántos Hotdogs aß Joey Chestnut als Weltrekord en 10 Minuten?",un:76,unit:"Hotdogs",hint:"Bei der berühmten Nathan's caliente perro Contest.",emoji:"🌭"},
 {q:"¿Cuánto pesa war der schwerste jemals gezüchtete Kürbis en kg?",un:1190,unit:"kg",hint:"Der Riesenkürbis wurde 2021 en Italien gewogen.",emoji:"🎃"},
 {q:"¿Cuántos Piercings hatte los humanos mit den meisten?",un:4384,unit:"Piercings",hint:"Rolf Buchholz aus Deutschland hielt diesen Rekord.",emoji:"💎"},
 {q:"Wie lang war der längste jemals gemessene Bart en cm?",un:570,unit:"cm",hint:"Hans Langseth trug ihn ein Leben lang.",emoji:"🧔"},
 {q:"¿Cuántos Stunden hielt der längste Kuss der Welt?",un:58,unit:"horas",hint:"Ein thailändisches Pärchen küsste sich 2013 ununterbrochen.",emoji:"💋"},
 {q:"¿Cuántos km/h fuhr das schnellste muskelkraftbetriebene Fahrrad?",un:280,unit:"km/h",hint:"Im Windschatten eines Rennwagens aufgestellt.",emoji:"🚴"},
 {q:"Wie alt war die älteste jemals lebende Katze en Jahren?",un:38,unit:"años",hint:"Creme Puff aus Texas lebte von 1967 bis 2005.",emoji:"🐱"},
 {q:"¿Cuántos Sprachen spricht der Polyglott Ziad Fazah?",un:58,unit:"Sprachen",hint:"Er beherrscht Sprachen aus aller Welt.",emoji:"🗣️"},
 {q:"¿Cuántos Meter tief ist die Kola-Bohrung en Russland?",un:12262,unit:"metros",hint:"Das tiefste Loch der Welt – nach 24 Jahren gestoppt.",emoji:"⛏️"},
 {q:"¿Cuánto pesa war das schwerste jemals gewogene Schwein en kg?",un:1157,unit:"kg",hint:"grande Bill hieß das Riesenschwein aus den USA (1933).",emoji:"🐷"},
 {q:"¿Cuántos Meter lang war die längste jemals gebackene Pizza?",un:1930,unit:"metros",hint:"Gebacken 2017 en Kalifornien.",emoji:"🍕"},
 {q:"Wie alt wurde der älteste Mensch aller Zeiten en Jahren?",un:122,unit:"años",hint:"Jeanne Calment aus Frankreich, 1875–1997.",emoji:"👴"},
 {q:"¿Cuántos Domino-Steine wurden beim größten Domino-Effekt verwendet?",un:4491863,unit:"Steine",hint:"2009 en den Niederlanden aufgestellt.",emoji:"🎲"},
 {q:"¿Cuántos Bienen saßen gleichzeitig auf einem Menschen als Rekord?",un:637000,unit:"Bienen",hint:"Das entspricht einem Gewicht von ~63 kg Bienen.",emoji:"🐝"},
 {q:"¿Cuántos Stockwerke hat der Burj Khalifa?",un:163,unit:"Stockwerke",hint:"828 Meter hoch, steht en Dubai.",emoji:"🏙️"},
 {q:"¿Cuántos km lief der Weltrekordhalter Yiannis Kouros non-stop?",un:426,unit:"km",hint:"1997 en Australien aufgestellt.",emoji:"🏃"},
 {q:"¿Cuántos Kugeln Eis aß der Weltrekordhalter en einer Stunde?",un:254,unit:"Kugeln",hint:"Der Wettbewerb fand en Italien statt.",emoji:"🍦"},
 {q:"¿Cuánto pesa war das schwerste jemals gefangene Krokodil en kg?",un:1075,unit:"kg",hint:"Ein Salzwasserkrokodil von den Philippinen.",emoji:"🐊"},
 {q:"¿Cuántos m² groß war das größte jemals gemalte Gemälde?",un:17000,unit:"m²",hint:"Sacha Jafri malte es 2021 en Dubai.",emoji:"🎨"},
 {q:"¿Cuántos km/h erreichte die schnellste Tennisaufschlagsgeschwindigkeit?",un:263,unit:"km/h",hint:"Samuel Groth aus Australien, 2012.",emoji:"🎾"},
 {q:"¿Cuántos Meter weit wurde ein Gummistiefel beim Weitwurf geworfen?",un:63,unit:"metros",hint:"Offizieller Weltrekord im finnischen Stiefelweitwurf.",emoji:"👢"},
 {q:"¿Cuántos Kerzen standen auf der größten Geburtstagstorte?",un:72585,unit:"Kerzen",hint:"Die Torte wurde 2016 en Indien aufgestellt.",emoji:"🎂"},
 {q:"Wie lang war die längste jemals gemessene Haarlänge einer Frau en cm?",un:570,unit:"cm",hint:"Xie Qiuping aus China ließ sie seit 1973 wachsen.",emoji:"💇"},
 {q:"¿Cuántos Personen saßen gleichzeitig auf einem Motorrad als Rekord?",un:58,unit:"personas",hint:"Aufgestellt von der indischen Armee.",emoji:"🏍️"},
 {q:"¿Cuántos Meilen fuhr die längste je dokumentierte Taxifahrt?",un:21000,unit:"Meilen",hint:"Ein Brite fuhr von London nach Melbourne.",emoji:"🚕"},
 {q:"Wie lang war der längste Bart einer Frau en cm?",un:30,unit:"cm",hint:"Harnaam Kaur aus UK trägt den Rekord.",emoji:"🧔‍♀️"},
 {q:"¿Cuántos Stunden badete los humanos mit dem längsten Bad im Toten Meer?",un:48,unit:"horas",hint:"Das extrem salzige Wasser macht langes Baden möglich.",emoji:"🛁"},
 {q:"¿Cuántos Mal schlug ein Boxer en einer minuto auf einen Sandsack?",un:217,unit:"Schläge",hint:"Westley Lyons stellte diesen Rekord auf.",emoji:"🥊"},
 {q:"¿Cuántos Meter lang war das längste Surfbrett?",un:12,unit:"metros",hint:"Gebaut 2015 en Australien – mit 66 Surfern drauf.",emoji:"🏄"},
 {q:"¿Cuántos kg Zwiebeln schälte der Weltrekordhalter en einer Stunde?",un:11.6,unit:"kg",hint:"Unter Tränen natürlich.",emoji:"🧅"},
 {q:"¿Cuántos Meter weit spuckte der Weitspuck-Weltmeister einen Kirschkern?",un:28.5,unit:"metros",hint:"Aufgestellt beim mundo Cherry Pit Spitting Championship.",emoji:"🍒"},
 {q:"¿Cuántos Trampolin-Sprünge schaffte der Rekordhalter en einer minuto?",un:245,unit:"Sprünge",hint:"rápido 4 Sprünge pro Sekunde.",emoji:"🤸"},
 {q:"¿Cuántos Stunden trug los humanos mit dem längsten Kopfstand auf sich?",un:3,unit:"horas",hint:"Rekord von Bryce Lane aus 2019.",emoji:"🤸"},
 {q:"¿Cuántos Meter lang war der längste Zopf einer Frau?",un:2.97,unit:"metros",hint:"Rekord aus China 2021.",emoji:"💇"},
 {q:"¿Cuántos Stockwerke hat das höchste Hotel der Welt (Gevora Dubai)?",un:75,unit:"Stockwerke",hint:"356 Meter hoch mit 528 Zimmern.",emoji:"🏨"},
 {q:"¿Cuántos Meter weit sprang un humano auf einem Pogo-Stick?",un:33,unit:"metros",hint:"Brent Sherwood hüpfte 33 Meter weit.",emoji:"🦘"},
 {q:"¿Cuántos Hamburger aß der Rekordhalter en 3 Minuten?",un:12,unit:"Hamburger",hint:"Kobayashi schaffte 12 Burgern en 180 Sekunden.",emoji:"🍔"},
 {q:"¿Cuántos Meter lang war der größte Weihnachtsstrumpf?",un:51,unit:"metros",hint:"Gestrickt 2018 en Großbritannien.",emoji:"🧦"},
 {q:"¿Cuántos Stunden tanzte der Weltrekordhalter ununterbrochen?",un:123,unit:"horas",hint:"Über 5 Tage ohne Schlaf tanzend.",emoji:"💃"},
 {q:"¿Cuántos Treppen stieg der schnellste Empire State Building Runner en Minuten?",un:9.8,unit:"minutos",hint:"1576 Stufen auf 86 Stockwerke.",emoji:"🏃"},
 {q:"¿Cuántos kg wog das schwerste jemals gegrillte Steak?",un:1098,unit:"kg",hint:"Ein Riesensteak für den Weltrekord.",emoji:"🥩"},
 {q:"¿Cuántos Meter tief tauchte der Rekordtaucher auf einem einzigen Atemzug?",un:214,unit:"metros",hint:"Herbert Nitsch – der tiefste Mann der Welt.",emoji:"🤿"},
 {q:"¿Cuántos km lief der älteste Marathon-Finisher en Jahren?",un:100,unit:"Jahre alt",hint:"Fauja Singh aus Indien lief einen Marathon mit 100 Jahren.",emoji:"🏃"},
 {q:"¿Cuántos Stunden nonstop spielte der Weltrekord-Videospieler?",un:138,unit:"horas",hint:"rápido 6 Tage nonstop zocken.",emoji:"🎮"},
 {q:"¿Cuánto pesa war das schwerste Kaninchen en kg?",un:22,unit:"kg",hint:"Darius – ein Kontinentaler Riese aus England.",emoji:"🐰"},
 {q:"¿Cuántos Meter lang war der längste Schachspieler-Bart?",un:2.13,unit:"metros",hint:"Der Bärtler spielte gleichzeitig Schach.",emoji:"🧔"},
 {q:"¿Cuántos Liegestütze machte der Rekordhalter en einer minuto?",un:138,unit:"Liegestütze",hint:"Rekord von Carlton Williams aus 2022.",emoji:"💪"},
 {q:"¿Cuántos Meter lang war die längste Menschenkette unter Wasser?",un:269,unit:"metros",hint:"Über 300 Taucher bildeten 2015 diese Kette.",emoji:"🤿"},
 {q:"¿Cuántos Stunden fuhr der Langstrecken-Fahrrad-Weltrekordler?",un:72,unit:"horas",hint:"Amanda Coker fuhr 72 Stunden nonstop.",emoji:"🚴"},
 {q:"¿Cuántos Meter weit schoss der weiteste Elfmeter?",un:100,unit:"metros",hint:"Mit einem speziellen Kanonenschuss erzielt.",emoji:"⚽"},
 {q:"¿Cuántos kg Curry aß der Rekordhalter en einer Stunde?",un:8.8,unit:"kg",hint:"Juliet Lee schaffte 8,8 kg Curry en 60 Minuten.",emoji:"🍛"},
 {q:"¿Cuántos Stunden sang der Weltrekord-Karaoke-Sänger?",un:101,unit:"horas",hint:"en Indien wurde dieser Ausdauer-Rekord aufgestellt.",emoji:"🎤"},
 {q:"¿Cuánto pesa war der schwerste Mensch aller Zeiten en kg?",un:635,unit:"kg",hint:"Jon Brower Minnoch aus den USA wog 635 kg.",emoji:"⚖️"},
 {q:"¿Cuántos m hoch war der höchste Sprung auf einem Snowboard?",un:9,unit:"metros",hint:"Travis Rice erzielte diesen Rekord en einem Halfpipe.",emoji:"🏂"},
 {q:"¿Cuántos Gurken aß der Rekordhalter en einer minuto?",un:8,unit:"Gurken",hint:"Komplette Gurken, nicht Scheiben.",emoji:"🥒"},
 {q:"¿Cuántos Meter lang war der längste Laufsteg bei einer Modenschau?",un:6.5,unit:"km",hint:"Unilever organisierte 2020 diesen Rekord.",emoji:"👠"},
 {q:"¿Cuántos Stunden stand los humanos auf einem Bein als Weltrekord?",un:76,unit:"horas",hint:"Majid Khan aus Pakistan, 2016.",emoji:"🦩"},
 {q:"¿Cuántos km/h fuhr der schnellste Rollstuhl bergab?",un:130,unit:"km/h",hint:"Ein speziell modifizierter Rennrollstuhl.",emoji:"♿"},
 {q:"¿Cuántos Meter lang war das längste Sandwich?",un:735,unit:"metros",hint:"Hergestellt 2015 en Mexiko.",emoji:"🥪"},
 {q:"¿Cuántos Stunden lief der längste Ultramarathon?",un:240,unit:"horas",hint:"10 Tage non-stop laufen.",emoji:"🏃"},
 {q:"¿Cuánto pesa war die schwerste en einem Stück gekochte Pasta en kg?",un:5900,unit:"kg",hint:"rápido 6 Tonnen Pasta en einem einzigen Gericht.",emoji:"🍝"},
 {q:"¿Cuántos Meter lang war die längste Girlande?",un:5650,unit:"metros",hint:"en den Philippinen hergestellt für Weihnachten 2015.",emoji:"🎄"},
 {q:"¿Cuántos Stunden sang ein Chor ununterbrochen als Weltrekord?",un:120,unit:"horas",hint:"Ein indischer Chor sang 5 Tage nonstop.",emoji:"🎵"},
 {q:"¿Cuántos Meter lang war der längste Popcorn-Trail?",un:1768,unit:"metros",hint:"Aufgebaut 2020 en Tschechien.",emoji:"🍿"},
 {q:"¿Cuántos kg wog das schwerste Weihnachtsplätzchen?",un:400,unit:"kg",hint:"Ein einziger riesiger Lebkuchen.",emoji:"🍪"},
 {q:"¿Cuántos Stunden Dauerschlaf hielt der Weltrekordhalter durch?",un:11,unit:"horas",hint:"Peter Tripp blieb 201 Stunden wach – das ist der Gegenteil-Rekord.",emoji:"😴"},
 {q:"¿Cuántos km/h fuhr un humano auf einer Bananenschale gleitend?",un:3,unit:"km/h",hint:"Experiment zur Reibung von Bananenschalen.",emoji:"🍌"},
 {q:"¿Cuántos Meter lang war der längste Volleyball-Rallye-Wechsel?",un:120,unit:"veces",hint:"Pässe ohne Ballberührung des Bodens.",emoji:"🏐"},
 {q:"¿Cuántos Stunden spielte ein Pianist ununterbrochen als Weltrekord?",un:120,unit:"horas",hint:"Klavierspielen 5 Tage nonstop.",emoji:"🎹"},
 {q:"¿Cuánto pesa war das schwerste gegessene Steak en 9 Minuten?",un:1.36,unit:"kg",hint:"Das US-Steak-Wettessen-Rekord.",emoji:"🥩"},
 {q:"¿Cuántos Meter lang war die längste Nudel?",un:3776,unit:"metros",hint:"Hergestellt en China, lang wie der Fuji.",emoji:"🍜"},
 {q:"¿Cuántos Sekunden lief der 100m-Sprint als absolute Bestzeit?",un:9.58,unit:"segundos",hint:"Usain Bolt, Berlin 2009.",emoji:"⚡"},
 {q:"¿Cuántos m hoch ist die höchste je erklommene Welle beim Surfen?",un:24,unit:"metros",hint:"Rodrigo Koxa surfte 2017 diese Riesenwelle.",emoji:"🏄"},
 {q:"¿Cuántos Marshmallows stopfte sich un hombre gleichzeitig en den Mund?",un:25,unit:"Marshmallows",hint:"Weltrekord im Marshmallow-Stopfen.",emoji:"🍬"},
 {q:"¿Cuántos Stifte hielt der Weltrekordhalter gleichzeitig zwischen den Fingern?",un:60,unit:"Stifte",hint:"Lorenzo Resta, Italien 2019.",emoji:"✏️"},
 {q:"¿Cuántos m lang war die längste Girlande aus Popcorn?",un:1200,unit:"metros",hint:"Aufgefädelt en Schoolkids en den USA.",emoji:"🍿"},
 {q:"¿Cuánto pesa war das schwerste Hühnerei en Gramm?",un:454,unit:"gramos",hint:"Das schwerste bekannte Hühnerei der Geschichte.",emoji:"🥚"},
 {q:"¿Cuántos Meter lang war das längste Fischfilet?",un:121,unit:"metros",hint:"Ein Thunfischfilet en Japan aufgeschnitten.",emoji:"🐟"},
 {q:"¿Cuántos Liter Milch trank der Weltrekordhalter en einer Stunde?",un:4,unit:"litros",hint:"Liter für Liter – ein ekelhafter Rekord.",emoji:"🥛"},
 {q:"¿Cuántos Stunden blieb jemand en eiskaltem Wasser am längsten?",un:24,unit:"horas",hint:"Wim Hof setzte diesen Rekord im Eisbad.",emoji:"🧊"},
 {q:"¿Cuántos km/h fuhr un humano auf einem Laufband als Rekord?",un:45,unit:"km/h",hint:"Sprints auf dem Laufband.",emoji:"🏃"},
 {q:"¿Cuántos Wasserflaschen balancierten auf dem Kopf des Rekordhalters?",un:24,unit:"Flaschen",hint:"Dr. Ashrita Furman, Weltrekordhalter schlechthin.",emoji:"🍶"},
 {q:"¿Cuántos Meter lang war das längste Currywurst?",un:96,unit:"metros",hint:"Aufgestellt beim Karneval en Deutschland.",emoji:"🌭"},
 {q:"¿Cuántos Höhenmeter kletterte der schnellste Everest-Aufstieg?",un:8849,unit:"metros",hint:"Nirmal Purja schaffte den Aufstieg en weniger als 7 Stunden.",emoji:"🏔️"},
 {q:"¿Cuántos Stunden joggte der älteste Marathonläufer Fauja Singh kontinuierlich?",un:8.5,unit:"horas",hint:"Mit 100 Jahren lief er einen kompletten Marathon.",emoji:"🏃"},
 {q:"¿Cuántos Bälle jonglierte der Rekordhalter gleichzeitig?",un:14,unit:"Bälle",hint:"Alex Barron jonglierte 14 Bälle 2017.",emoji:"🎪"},
 {q:"¿Cuántos Meter lang war die längste Schleppe eines Hochzeitskleids?",un:3000,unit:"metros",hint:"Ein 3 km langes Brautkleid aus Rumänien.",emoji:"👰"},
 {q:"¿Cuántos Liter Coca-Cola trank der Rekordhalter en einer Stunde?",un:2,unit:"litros",hint:"Durch einen Strohhalm natürlich.",emoji:"🥤"},
 {q:"¿Cuántos Eierkuchen übereinander schichtete der Rekordhalter?",un:76,unit:"Eierkuchen",hint:"Ein instabiler Turm aus Eierkuchen.",emoji:"🥞"},
 {q:"¿Cuántos Meter lang war das größte Omelette?",un:14,unit:"Meter Durchmesser",hint:"en Frankreich, dem Land des Omeletts.",emoji:"🍳"},
 {q:"¿Cuántos Stunden nonstop schaute jemand Netflix als Weltrekord?",un:94,unit:"horas",hint:"rápido 4 Tage ununterbrochen Netflix.",emoji:"📺"},
 {q:"¿Cuántos kg Käse wurde beim größten Käsefondue verwendet?",un:740,unit:"kg",hint:"Ein riesiger Topf Käse en der Schweiz.",emoji:"🧀"},
 {q:"¿Cuántos Meter lang war der längste Zug aus Liegestühlen?",un:2000,unit:"metros",hint:"2 km Liegestühle en einer Reihe.",emoji:"🏖️"},
 {q:"¿Cuántos Tage fastete der Weltrekordhalter?",un:382,unit:"días",hint:"Angus Barbieri fastete unter medizinischer Aufsicht.",emoji:"🚫"},
 {q:"¿Cuántos kg Kartoffeln schälte der Rekordhalter en einer Stunde?",un:30,unit:"kg",hint:"Ein Weltrekord aus Irland.",emoji:"🥔"},
 {q:"¿Cuántos Stunden spielte eine Band nonstop als Weltrekord?",un:134,unit:"horas",hint:"Über 5 Tage Livemusik.",emoji:"🎸"},
 {q:"¿Cuántos Meter lang war das längste Sushi?",un:2544,unit:"metros",hint:"en Japan hergestellt für den Weltrekord.",emoji:"🍣"},
 {q:"¿Cuántos Stunden stand los humanos auf einem Surfbrett auf einem See?",un:40,unit:"horas",hint:"Nonstop surfen auf einem Binnensee.",emoji:"🏄"},
 {q:"¿Cuántos Münzen stapelte der Rekordhalter auf einem Finger?",un:253,unit:"Münzen",hint:"Balanciert auf einem einzelnen Zeigefinger.",emoji:"🪙"},
 {q:"¿Cuántos km weit schwamm der Langstreckenschwimmer nonstop?",un:225,unit:"km",hint:"Martin Strel schwamm über 225 km am Stück.",emoji:"🏊"},
 {q:"¿Cuántos Meter hoch kletterte die Rekordklettererin ohne Seil?",un:600,unit:"metros",hint:"Alex Honnold kletterte den El Capitan frei (893m).",emoji:"🧗"},
 {q:"¿Cuántos Stunden hielt der Rekordhalter eine Yoga-Position?",un:7,unit:"horas",hint:"Extreme Ausdauer en einer einzigen Pose.",emoji:"🧘"},
 {q:"¿Cuántos kg wiegt das schwerste Schokoladenei der Welt?",un:4000,unit:"kg",hint:"Ein 4 Tonnen schweres Schokoladenei aus Italien.",emoji:"🍫"},
 {q:"¿Cuántos Mal flippte der Rekordhalter ein Wasserflasche nonstop?",un:2000,unit:"veces",hint:"Flipping Bottles war ein Trend – einer machte es viele masculino.",emoji:"🍶"},
 {q:"¿Cuántos Bücher las der Weltrekordleser en einer Woche?",un:100,unit:"Bücher",hint:"Speedreader Howard Berg las 25000 Wörter pro minuto.",emoji:"📚"},
 {q:"¿Cuántos Meter lang war der größte Cheeseburger?",un:60,unit:"cm Höhe",hint:"Ein 60 cm hoher Turm-Cheeseburger.",emoji:"🍔"},
 {q:"¿Cuántos Sekunden hielt un humano einen lebenden Skorpion im Mund?",un:33,unit:"segundos",hint:"Ein sehr gefährlicher Weltrekord.",emoji:"🦂"},
 {q:"¿Cuántos Stunden badete jemand en Bier als Weltrekord?",un:3,unit:"horas",hint:"en einem mit Bier gefüllten Whirlpool.",emoji:"🍺"},
 {q:"¿Cuántos km/h fuhr das schnellste Motorrad je?",un:605,unit:"km/h",hint:"Das Streamliner-Motorrad von Ack Attack.",emoji:"🏍️"},
 {q:"¿Cuántos Stunden spielte jemand Schach nonstop?",un:60,unit:"horas",hint:"Über 2,5 Tage ununterbrochen Schach.",emoji:"♟️"},
 {q:"¿Cuánto pesa war das schwerste verkaufte Einzel-Stück Trüffel en kg?",un:1.89,unit:"kg",hint:"2007 für 330.000€ bei Sotheby's versteigert.",emoji:"🍄"},
 {q:"¿Cuántos Meter lang war die längste Schlange aus Karotten?",un:1000,unit:"metros",hint:"1 km Karotten en einer Reihe aufgestellt.",emoji:"🥕"},
 {q:"¿Cuántos Stunden blieb jemand en einer Tonne Eiswürfel vergraben?",un:2.5,unit:"horas",hint:"Jin Songhao überlebte 2.5 Stunden eingefroren.",emoji:"🧊"},
 {q:"¿Cuántos kg Avocados schälte der Rekordhalter en einer minuto?",un:8,unit:"Stück",hint:"Avocados en 60 Sekunden geschält.",emoji:"🥑"},
 {q:"¿Cuántos Bananen schälte der Rekordhalter en einer minuto mit dem Fuß?",un:8,unit:"Bananen",hint:"Mit den Zehen – nicht mit den Händen.",emoji:"🍌"},
 {q:"¿Cuántos Meter lang war die längste Bratwurst?",un:648,unit:"metros",hint:"Hergestellt en Österreich für den Weltrekord.",emoji:"🌭"},
 {q:"¿Cuántos Stunden überlebte jemand ohne Schlaf als Rekord?",un:449,unit:"horas",hint:"Randy Gardner blieb 264 Stunden wach – das ist der offizielle Rekord.",emoji:"😴"},
 {q:"¿Cuántos Ballonhunde formte der Rekordhalter en einer Stunde?",un:747,unit:"Ballonhunde",hint:"John Cassidy formte rápido einen pro 5 Sekunden.",emoji:"🐶"},
 {q:"¿Cuántos Meter lang war der längste caliente perro?",un:203,unit:"metros",hint:"2011 en Paraguay hergestellt.",emoji:"🌭"},
 {q:"¿Cuántos Stunden sitzt der Weltrekordler en einer Sauna?",un:16,unit:"horas",hint:"en Finnland natürlich.",emoji:"🧖"},
 {q:"¿Cuántos kg Spaghetti aß der Rekordhalter en 30 Sekunden?",un:0.7,unit:"kg",hint:"700g Nudeln en einer halben minuto.",emoji:"🍝"},
 {q:"¿Cuántos Liegestütze machte der Rekordhalter en 24 Stunden?",un:46001,unit:"Liegestütze",hint:"Charles Servizio 1993.",emoji:"💪"},
 {q:"¿Cuántos km weit rollte un hombre auf einem Einrad nonstop?",un:1458,unit:"km",hint:"Lon Allen Hughes fuhr quer durch die USA.",emoji:"🎪"},
 {q:"¿Cuántos Stunden hielt der Weltrekordhalter ein Tablett auf einem Finger?",un:2,unit:"horas",hint:"Ein Tablett balanciert auf einer Fingerspitze.",emoji:"🤸"},
 {q:"¿Cuántos Tortillas aß der Rekordhalter en einer minuto?",un:13,unit:"Tortillas",hint:"Mexikanische Burrito-Wettessen-Weltrekord.",emoji:"🌮"},
 {q:"¿Cuánto pesa war das schwerste Sushi-Platte der Welt en kg?",un:6500,unit:"kg",hint:"6,5 Tonnen Sushi en Japan aufgetischt.",emoji:"🍣"},
 {q:"¿Cuántos Meter lang war die längste Laterne aus Papier?",un:2000,unit:"metros",hint:"en China zur Feier des Laternenfests.",emoji:"🏮"},
 {q:"¿Cuántos Stunden spielte jemand Basketball ununterbrochen?",un:120,unit:"horas",hint:"5 Tage Basketball ohne Schlaf.",emoji:"🏀"},
 {q:"¿Cuántos Sekunden brauchte der schnellste Rubik's Cube Löser?",un:3.13,unit:"segundos",hint:"Max Park löste den Cube 2023.",emoji:"🧩"},
 {q:"¿Cuántos Meter weit sprang ein Motorrad über Autos?",un:115,unit:"metros",hint:"Robbie Maddison überquerte 46 Autos.",emoji:"🏍️"},
 {q:"¿Cuántos Pfannkuchen warf der Rekordhalter en einer minuto?",un:140,unit:"Pfannkuchen",hint:"Mike Cuzzacrea 1994.",emoji:"🥞"},
 {q:"¿Cuánto pesa war das schwerste gegrillte Würstchen en kg?",un:80,unit:"kg",hint:"Ein 80 kg schweres Riesenwürstchen.",emoji:"🌭"},
 {q:"¿Cuántos Minuten hielt der längste Handstand am Stück?",un:56,unit:"minutos",hint:"Dave Brett, 1992.",emoji:"🤸"},
 {q:"¿Cuántos Meter tief stieg der Taucher mit dem Taucheranzug?",un:701,unit:"metros",hint:"Nuno Gomes, 2005 im Roten Meer.",emoji:"🤿"},
 {q:"¿Cuántos Stunden schlief los humanos mit dem längsten Mittagsschlaf?",un:5,unit:"horas",hint:"Der ausgedehnteste dokumentierte Nickerchen.",emoji:"😴"},
 {q:"¿Cuántos Meter lang war der längste Knaller-Feuerwerk-Streifen?",un:5765,unit:"metros",hint:"en Mexiko 2018 aufgestellt.",emoji:"🎆"},
 {q:"¿Cuánto pesa war die schwerste Zwiebel der Welt en kg?",un:8.96,unit:"kg",hint:"Tony Glover aus England züchtete sie 2012.",emoji:"🧅"},
 {q:"¿Cuántos Stunden trug jemand ein Brautkleid am längsten?",un:108,unit:"horas",hint:"una mujer trug 4,5 Tage lang ein Brautkleid.",emoji:"👰"},
 {q:"¿Cuántos Sekunden brauchte der schnellste Kartenspieler für ein Deck?",un:10,unit:"segundos",hint:"Ein komplettes Kartenspiel sortieren.",emoji:"🃏"},
 {q:"¿Cuántos Meter weit wurde eine Kuh bei einem Rennen geritten?",un:200,unit:"metros",hint:"Kuhrennen en Bayern – ein echter Sport.",emoji:"🐄"},
 {q:"¿Cuántos Stunden blieb ein Team en einem Aufzug eingeschlossen als Weltrekord?",un:41,unit:"horas",hint:"Nicholas White war allein 41 Stunden im Aufzug gefangen.",emoji:"🛗"},
 {q:"¿Cuántos Stockwerke lief der schnellste Treppenläufer beim Eiffelturm hoch?",un:9,unit:"minutos",hint:"1665 Stufen – der Rekord steht seit 2017.",emoji:"🗼"},
 {q:"¿Cuántos Meter lang war der längste Bleistift?",un:323,unit:"metros",hint:"en Sri Lanka hergestellt.",emoji:"✏️"},
 {q:"¿Cuántos Stunden meditierte der Weltrekord-Meditator?",un:40,unit:"días",hint:"Ein Tibetanischer Mönch meditierte 40 Tage.",emoji:"🧘"},
 {q:"¿Cuántos Geburtstagstorten aß der Rekordhalter en einer Stunde?",un:14,unit:"Stück",hint:"Jeder Slice war dabei ein komplettes Kuchenstück.",emoji:"🎂"},
 {q:"¿Cuántos Klimmzüge schaffte der Rekordhalter en einer minuto?",un:50,unit:"Klimmzüge",hint:"Jan Kares, 2019.",emoji:"💪"},
 {q:"¿Cuántos Meter lang war das längste Spinnennetz?",un:25,unit:"metros",hint:"Eine Kolonial-Spinnenart baute es en den USA.",emoji:"🕸️"},
 {q:"¿Cuántos Sekunden dauerte der längste gemessene Blitzschlag?",un:7.74,unit:"segundos",hint:"en Brasilien 2020 gemessen.",emoji:"⚡"},
 {q:"¿Cuántos Stunden sang Maria Callas am längsten am Stück?",un:8,unit:"horas",hint:"Ein Endlos-Konzert-Rekord en der Oper.",emoji:"🎤"},
 {q:"¿Cuántos Meter lang war die längste Wäscheleine?",un:1500,unit:"metros",hint:"Mit Wäschestücken behangen en Kroatien.",emoji:"👕"},
 {q:"¿Cuántos Stunden fuhr ein Tandem-Fahrrad-Team nonstop?",un:24,unit:"horas",hint:"24h Tandemfahren ohne Pause.",emoji:"🚴"},
 {q:"¿Cuántos Stunden rief un humano als Weltrekord ununterbrochen?",un:21,unit:"horas",hint:"Stunden Dauerrufen ohne Pause.",emoji:"📢"},
 {q:"¿Cuántos Meter lang war der längste Schuh?",un:6.4,unit:"metros",hint:"Ein Riesen-Sportschuh als Kunstwerk.",emoji:"👟"},
 {q:"¿Cuántos Stunden rollte un humano auf einem Skateboard nonstop?",un:36,unit:"horas",hint:"Über einen Tag und eine Nacht Skaten.",emoji:"🛹"},
 {q:"¿Cuántos Stühle hob der Stärkste mit dem Mund hoch?",un:24,unit:"Stühle",hint:"Georges Christen hielt 24 Stühle mit den Zähnen.",emoji:"🦷"},
 {q:"¿Cuántos Meter lang war die längste Blumenkette?",un:4000,unit:"metros",hint:"en Indien für ein Fest hergestellt.",emoji:"🌸"},
 {q:"¿Cuántos Stunden hielt un niño einen Hula-Hoop en der Luft?",un:74,unit:"horas",hint:"Marawa Ibrahim hielt ihn 74 Stunden.",emoji:"🔵"},
 {q:"¿Cuántos km ist der längste Spaziergang der Welt lang?",un:24000,unit:"km",hint:"George Meegan lief von Feuerland nach Alaska.",emoji:"🚶"},
 {q:"¿Cuántos Stunden nonstop spielte ein Fußballteam?",un:169,unit:"horas",hint:"Über eine Woche Fußball am Stück.",emoji:"⚽"},
 {q:"¿Cuántos Meter weit hüpfte der Rekordhalter auf einem Bein?",un:100,unit:"metros",hint:"Meter Einbein-Hüpfen als Weltrekord.",emoji:"🦘"},
 {q:"¿Cuántos Stunden las un humano als Dauerlesung vor?",un:200,unit:"horas",hint:"8 Tage Vorlesemarathon.",emoji:"📖"},
 {q:"¿Cuántos Schaukeln schaukelte jemand en 24 Stunden?",un:230000,unit:"veces",hint:"Kontinuierliches Schaukeln einen ganzen Tag.",emoji:"🎢"},
 {q:"¿Cuántos Meter lang war der längste Zug aus Flugzeugen?",un:19,unit:"Flugzeuge",hint:"Flugzeuge flogen en enger Formation.",emoji:"✈️"},
 {q:"¿Cuánto pesa war das schwerste einzelne Traubenbündel en kg?",un:9.4,unit:"kg",hint:"Eine Weintraube aus Chile 2018.",emoji:"🍇"},
 {q:"¿Cuántos Stunden lief un humano auf einem Laufband als Rekord?",un:24,unit:"horas",hint:"Stunden ununterbrochen auf dem Laufband.",emoji:"🏃"},
 {q:"¿Cuántos Meter tief ist das tiefste natürliche Loch der Welt?",un:2191,unit:"metros",hint:"Die Krubera-Höhle en Georgien.",emoji:"🕳️"},
 {q:"¿Cuántos kg Eis schleckte der Rekordhalter en einer Stunde?",un:1.3,unit:"kg",hint:"Über ein Kilo Eis am Stiel en 60 Minuten.",emoji:"🍦"},
 {q:"¿Cuántos Stunden sang eine Gruppe Kinderlieder nonstop?",un:73,unit:"horas",hint:"3 Tage Kinderlied-Marathon.",emoji:"🎵"},
 {q:"¿Cuántos Meter lang war der größte Lebkuchenmann?",un:10,unit:"metros",hint:"en Schweden 2009 gebacken.",emoji:"🍪"},
 {q:"¿Cuántos Sekunden hielt un humano eine Jalapeño-Chili im Auge?",un:7,unit:"segundos",hint:"Extrem schmerzhaft – nicht empfohlen.",emoji:"🌶️"},
 {q:"¿Cuántos Stunden lief ein Hund auf einem Laufband nonstop?",un:5,unit:"horas",hint:"Ausdauer-Hund en Japan.",emoji:"🐕"},
 {q:"¿Cuántos km weit fuhr die längste Kartenhaus-Bahn?",un:32,unit:"metros",hint:"Ein Kartenhaus-Dominoeffekt über 32 Meter.",emoji:"🃏"},
 {q:"¿Cuánto pesa war das schwerste Pfannkuchen-Stapel en kg?",un:4.5,unit:"kg",hint:"Ein Turm aus Pfannkuchen.",emoji:"🥞"},
 {q:"¿Cuántos Stunden trug jemand eine Mütze ohne sie abzunehmen?",un:1000,unit:"horas",hint:"Über 40 Tage Mütze tragen.",emoji:"🧢"},
 {q:"¿Cuántos Meter lang war der längste Baumwollbonbon-Faden?",un:1427,unit:"metros",hint:"Zuckerwatte als langer Faden aufgerollt.",emoji:"🍬"},
 {q:"¿Cuántos Personen machten gleichzeitig den größten Flashmob?",un:13597,unit:"personas",hint:"en Mumbai Indien 2013.",emoji:"🕺"},
 {q:"¿Cuántos Meter tief watete jemand en Spaghetti?",un:1,unit:"Meter Tiefe",hint:"Eine Wanne voll Spaghetti.",emoji:"🍝"},
 {q:"¿Cuántos Stunden blieb un humano en einem Glas-Sarg unter Wasser?",un:7,unit:"horas",hint:"Unter Wasser eingeschlossen – Atemluft durch ein Rohr.",emoji:"🧊"},
 {q:"¿Cuántos Sekunden brauchte der schnellste Pizzateig-Dreher für 5 Drehungen?",un:10,unit:"segundos",hint:"Pizza-Akrobatik-Weltmeisterschaft.",emoji:"🍕"},
 {q:"¿Cuántos Stockwerke hat das höchste Gebäude der Welt (Burj Khalifa)?",un:163,unit:"Stockwerke",hint:"828 Meter – höchstes Gebäude der Welt.",emoji:"🏙️"},
 {q:"¿Cuántos Mal öffnete der Rekordhalter eine Flasche en einer minuto?",un:67,unit:"veces",hint:"Mit einem Korkenzieher – Weltrekord.",emoji:"🍾"},
 {q:"¿Cuántos Stunden hielt un humano eine Kerze über einem Wasserbecken?",un:12,unit:"horas",hint:"Eine brennende Kerze 12 Stunden balancieren.",emoji:"🕯️"},
 {q:"¿Cuántos km lief das schnellste Dromedar im Sprint?",un:65,unit:"km/h",hint:"Kamele können kurz sehr schnell rennen.",emoji:"🐪"},
 {q:"¿Cuántos m weit flog der weiteste Papierflieger?",un:88.3,unit:"metros",hint:"John Collins entwarf den Flieger, Joe Ayoob warf ihn.",emoji:"✈️"},
 {q:"¿Cuántos Stunden lud un humano Videos auf YouTube als Dauerlauf hoch?",un:100,unit:"horas",hint:"Stunden ununterbrochenes Video-Uploading.",emoji:"📹"},
 {q:"¿Cuántos Meter lang war der längste Schal?",un:4565,unit:"metros",hint:"en China gestrickt für den Weltrekord.",emoji:"🧣"},
 {q:"¿Cuántos Meter lang war der längste Spagat?",un:12,unit:"Meter Kette",hint:"Menschen bildeten eine Spagat-Kette.",emoji:"🤸"},
 {q:"¿Cuánto pesa war das schwerste Würfelzucker-Modell en kg?",un:400,unit:"kg",hint:"Aus 2 millones Würfelzucker gebaut.",emoji:"🍬"},
 {q:"¿Cuántos Minuten hielt ein Team ein Wasserball-Spiel ohne Unterbrechung?",un:24,unit:"horas",hint:"24h Wasserball am Stück.",emoji:"🤽"},
 {q:"¿Cuántos Stunden boxte un hombre ununterbrochen gegen einen Sandsack?",un:114,unit:"horas",hint:"rápido 5 Tage nonstop boxen.",emoji:"🥊"},
 {q:"¿Cuántos Meter lang war der längste selbst gemalte Bildstreifen?",un:2000,unit:"metros",hint:"Ein 2 km langes Bild.",emoji:"🎨"},
 {q:"¿Cuántos kg Brot backte der Rekordhalter en einer Stunde?",un:100,unit:"Brote",hint:"Laib Brot en 60 Minuten.",emoji:"🍞"},
 {q:"¿Cuántos Stunden fuhr un humano auf einem Einrad als Rekord?",un:105,unit:"horas",hint:"Über 4 Tage auf einem Einrad.",emoji:"🎪"},
 {q:"¿Cuántos Meter weit schoss der Weltrekord-Pfeilbogen?",un:1410,unit:"metros",hint:"Sultan Selim der Erste schoss 1,41 km weit.",emoji:"🏹"},
 {q:"¿Cuántos Schritte machte der schnellste 100m-Sprint?",un:41,unit:"Schritte",hint:"Usain Bolt brauchte nur 41 Schritte für 100m.",emoji:"⚡"},
 {q:"¿Cuántos Stunden sprach un humano nonstop als Redner?",un:93,unit:"horas",hint:"rápido 4 Tage ununterbrochenes Reden.",emoji:"🗣️"},
 {q:"¿Cuántos Kilometer joggten Mitglieder einer Staffel en 24 Stunden?",un:1000,unit:"km",hint:"24-Stunden-Staffellauf-Weltrekord.",emoji:"🏃"},
 {q:"¿Cuántos Nüsse knackte der Rekordhalter en einer minuto?",un:108,unit:"Nüsse",hint:"Walnüsse en 60 Sekunden geknackt.",emoji:"🥜"},
 {q:"¿Qué tan grande war das größte Puzzle der Welt en Teilen?",un:551232,unit:"Teile",hint:"Das größte kommerziell erhältliche Puzzle.",emoji:"🧩"},
 {q:"¿Cuántos Stunden stand un humano en Ameisen als Weltrekord?",un:1,unit:"Stunde",hint:"en einer Kiste voller Ameisen – sehr tapfer.",emoji:"🐜"},
 {q:"¿Cuántos Meter hoch stapelte der Rekordhalter Münzen?",un:1,unit:"metros",hint:"Meter hoher Münzturm.",emoji:"🪙"},
 {q:"¿Cuántos Kubikmeter hatte das größte Schneeman der Welt?",un:37000,unit:"Tonnen Schnee",hint:"Ein Schneemann en Maine USA aus 2008.",emoji:"⛄"},
 {q:"¿Cuánto pesa war die schwerste Wassermelone en kg?",un:159,unit:"kg",hint:"Chris Kent aus den USA züchtete sie 2013.",emoji:"🍉"},
 {q:"¿Cuántos Stunden spielte ein Pärchen Brettspiele nonstop?",un:61,unit:"horas",hint:"Über 2,5 Tage Brettspiele am Stück.",emoji:"🎲"},
 {q:"¿Cuántos Meter lang war der längste Weihnachtsbaum?",un:67,unit:"metros",hint:"Ein Riesenbaum en Portugal 1999.",emoji:"🎄"},
 {q:"¿Cuántos Stunden tanzte ein Pärchen Tango ununterbrochen?",un:22,unit:"horas",hint:"Argentinischer Tango-Weltrekord.",emoji:"💃"},
 {q:"¿Cuántos Meter lang war der längste Schnurrbart?",un:4.29,unit:"metros",hint:"Ram Singh Chauhan aus Indien.",emoji:"👨"},
 {q:"¿Cuántos Personen sprangen gleichzeitig auf Trampolinen?",un:1000,unit:"personas",hint:"Trampolinge-Springer gleichzeitig.",emoji:"🤸"},
 {q:"¿Cuánto pesa war der schwerste Hund je en kg?",un:155,unit:"kg",hint:"Ein Englischer Mastiff namens Zorba.",emoji:"🐕"},
 {q:"¿Cuántos Stunden trug jemand Eiswürfel am Körper?",un:1,unit:"Stunde",hint:"Wim Hof hält Kälterekorde – bis zu 1h45min.",emoji:"🧊"},
 {q:"¿Cuántos Meter lang war der längste Fluss-Schwimmer nonstop?",un:514,unit:"km",hint:"Martin Strel schwamm den gesamten Mississippi.",emoji:"🏊"},
 {q:"¿Cuántos Stunden sang un humano allein ununterbrochen?",un:105,unit:"horas",hint:"rápido 4,5 Tage Dauersingen.",emoji:"🎤"},
 {q:"¿Cuántos Meter lang war der längste Brezel?",un:26,unit:"metros",hint:"Eine Riesenbrezel aus Bayern.",emoji:"🥨"},
 {q:"¿Cuántos km lief der schnellste 100-km-Läufer?",un:100,unit:"km en 6h17min",hint:"Nao Kazami (Japan) 2018.",emoji:"🏃"},
 {q:"¿Cuántos Stunden sprach ein Politiker die längste Parlamentsrede?",un:25,unit:"horas",hint:"Ein australischer Senator sprach 25 Stunden am Stück.",emoji:"🎙️"},
 {q:"¿Cuántos Stunden sang der Weltrekord-Sänger ununterbrochen?",un:105,unit:"horas",hint:"4,5 Tage – en Indien aufgestellt.",emoji:"🎤"},
 {q:"¿Cuántos Meter sprang un humano aus einem Flugzeug ohne Fallschirm?",un:7600,unit:"metros",hint:"Luke Aikins landete 2016 en einem Netz.",emoji:"🪂"},
 {q:"¿Cuántos km/h schnell war der schnellste Mensch auf Skiern?",un:254,unit:"km/h",hint:"Ivan Origone aus Italien, 2016.",emoji:"⛷️"},
 {q:"¿Cuántos Stunden fuhr der längste Fahrradfahrer nonstop?",un:91,unit:"horas",hint:"Über 3 Tage nonstop Radfahren.",emoji:"🚴"},
 {q:"¿Cuántos Meter hoch kletterte der jüngste Everest-Bezwinger en Jahren?",un:13,unit:"años",hint:"Jordan Romero bestieg ihn 2010 mit 13 Jahren.",emoji:"🏔️"},
 {q:"¿Cuántos Stunden tanzte ein einzelner Mensch als Rekord?",un:126,unit:"horas",hint:"Über 5 Tage tanzen ohne Unterbrechung.",emoji:"💃"},
 {q:"¿Cuántos Meter hoch ist der weltgrößte Sandberg?",un:100,unit:"metros",hint:"Aus Sand aufgetürmt für den Weltrekord.",emoji:"🏖️"},
 {q:"¿Cuántos kg Würstchen rollte der Rekordhalter en einer minuto?",un:50,unit:"Würstchen",hint:"Würste en 60 Sekunden gerollt.",emoji:"🌭"},
 {q:"¿Cuántos Stunden nonstop las ein Vorleser als Rekord?",un:200,unit:"horas",hint:"8 Tage ununterbrochen vorlesen.",emoji:"📖"},
 {q:"¿Cuántos Meter lang war die längste Menschenpyramide?",un:12,unit:"Ebenen",hint:"Etagen Menschenpyramide.",emoji:"🤸"},
 {q:"¿Cuántos Liter Bier trank der Rekordhalter en einer minuto?",un:1.3,unit:"litros",hint:"1,3 Liter en 60 Sekunden.",emoji:"🍺"},
 {q:"¿Cuántos Stunden spielte ein Pianist als Rekord nonstop?",un:120,unit:"horas",hint:"5 Tage Klavier ohne Unterbrechung.",emoji:"🎹"},
 {q:"¿Cuántos km/h fuhr der schnellste Rollschuhfahrer?",un:130,unit:"km/h",hint:"Bergab auf Inlineskates.",emoji:"🛼"},
 {q:"¿Cuántos Stunden hielt jemand einen Handstand?",un:56,unit:"minutos",hint:"rápido eine Stunde kopfüber.",emoji:"🤸"},
 {q:"¿Cuántos Meter weit warf der Rekordhalter einen Bumerang?",un:1401,unit:"metros",hint:"Und er kam zurück.",emoji:"🪃"},
 {q:"¿Cuántos Stunden jonglierte jemand nonstop?",un:12,unit:"horas",hint:"Mit 3 Bällen ohne Unterbrechung.",emoji:"🎪"},
 {q:"¿Cuántos Meter lang war der längste Schal?",un:4565,unit:"metros",hint:"rápido 5 km Schal gestrickt.",emoji:"🧣"},
 {q:"¿Cuántos Stunden blieb jemand wach als Weltrekord?",un:449,unit:"horas",hint:"Randy Gardner – offizieller Weltrekord 264h.",emoji:"😴"},
 {q:"¿Cuántos Liegestütze schaffte jemand mit einem Arm en einer minuto?",un:64,unit:"Liegestütze",hint:"Mit einem Arm – ein-Arm-Liegestütz-Rekord.",emoji:"💪"},
 {q:"¿Cuántos km weit segelte un humano allein nonstop?",un:33000,unit:"km",hint:"Die Weltumsegelung solo und nonstop.",emoji:"⛵"},
 {q:"¿Cuántos Stufen stieg der schnellste Treppenläufer pro minuto?",un:1600,unit:"Stufen",hint:"Beim Wolkenkratzer-Rennen.",emoji:"🏃"},
 {q:"¿Cuántos Gramm Chili aß der Rekordhalter en 3 Minuten?",un:500,unit:"gramos",hint:"500g der schärfsten Chili en 3 Minuten.",emoji:"🌶️"},
 {q:"¿Cuántos Meter lang war das größte Sandschloss?",un:500,unit:"metros",hint:"Ein 500 Meter langer Sandwall.",emoji:"🏰"},
 {q:"¿Cuántos Stunden kochte der Weltrekord-Koch nonstop?",un:68,unit:"horas",hint:"rápido 3 Tage kochen.",emoji:"👨‍🍳"},
 {q:"¿Cuántos Meter hoch war das höchste jemals gebaute Kartenhaus?",un:7.9,unit:"metros",hint:"Bryan Berg baute es en Las Vegas.",emoji:"🃏"},
 {q:"¿Cuántos Personen passten en den kleinsten Serienwagen?",un:21,unit:"personas",hint:"en einen Mini Cooper gequetscht.",emoji:"🚗"},
 {q:"¿Cuántos Stunden dauerte die längste Party?",un:168,unit:"horas",hint:"7 Tage feiern – dokumentiert.",emoji:"🎉"},
 {q:"¿Cuántos Meter weit wurde ein Frisbee geworfen?",un:338,unit:"metros",hint:"Weltrekord im Frisbee-Weitwurf.",emoji:"🥏"},
 {q:"¿Cuántos km/h erreichte der schnellste Papierflugzeug-Wurf?",un:238,unit:"km/h",hint:"Mit einer Schleuder abgeschossen.",emoji:"✈️"},
 {q:"¿Cuántos Sekunden brauchte der schnellste Mensch für einen Liter Wasser?",un:5,unit:"segundos",hint:"Trinken ohne zu schlucken aufzuhören.",emoji:"💧"},
 {q:"¿Cuántos Stunden aß jemand nonstop als Rekord?",un:72,unit:"horas",hint:"3 Tage essen – mit kurzen Pausen.",emoji:"🍽️"},
 {q:"¿Cuántos Meter lang war das größte Puzzle?",un:6000,unit:"metros",hint:"6 km langes Riesenpuzzle.",emoji:"🧩"},
 {q:"¿Cuántos Personen stellten den Weltrekord im Haareschneiden gleichzeitig?",un:394,unit:"personas",hint:"Friseure schnitten gleichzeitig.",emoji:"💇"},
 {q:"¿Cuántos Stunden fuhr das längste Kettenkarussell?",un:24,unit:"horas",hint:"24h Karussell fahren.",emoji:"🎡"},
];