// 🌊 OCÉANOS Y MAR – Español
export default [
 {q:"¿Cuántos Ozeane gibt es auf der Erde?",un:5,unit:"Ozeane",hint:"Pazifik, Atlantik, Indik, Arktis, Antarktis.",emoji:"🌊"},
 {q:"¿Qué tan profundo ist der Marianengraben en Metern?",un:11034,unit:"metros",hint:"Der tiefste Punkt der Weltmeere.",emoji:"🌊"},
 {q:"¿Cuántos por ciento der Erde sind von Wasser bedeckt?",un:71,unit:"%",hint:"Deswegen heißt die Erde auch 'der blaue Planet'.",emoji:"🌍"},
 {q:"¿Qué tan grande wird ein ausgewachsener Blauwal en Metern?",un:30,unit:"metros",hint:"Das größte Tier auf der Erde.",emoji:"🐋"},
 {q:"¿Cuántos Arme hat ein Tintenfisch?",un:8,unit:"Arme",hint:"Arme plus 2 Fangarme beim Oktopus.",emoji:"🐙"},
 {q:"¿Cuántos Herzen hat ein Tintenfisch?",un:3,unit:"Herzen",hint:"Zwei Kiemenherzen und ein Körperherz.",emoji:"🐙"},
 {q:"¿Qué tan profundo kann ein Pottwal tauchen en Metern?",un:3000,unit:"metros",hint:"Der tieftauchende Säuger der Welt.",emoji:"🐳"},
 {q:"¿Cuántos Arten von Haien gibt es?",un:500,unit:"especies",hint:"Von winzig bis riesig.",emoji:"🦈"},
 {q:"¿Qué tan grande wird ein Weißer Hai en Metern?",un:6,unit:"metros",hint:"Der berühmteste Raubfisch.",emoji:"🦈"},
 {q:"¿Cuántos km/h kann ein Schwertfisch schwimmen?",un:110,unit:"km/h",hint:"Schnellster Fisch im Meer.",emoji:"🐟"},
 {q:"¿Cuántos millones Tonnen Müll landen al año im Ozean?",un:8,unit:"million tons",hint:"Plastik ist das größte Problem.",emoji:"♻️"},
 {q:"¿Cuántos por ciento des Sauerstoffs produziert der Ozean?",un:50,unit:"%",hint:"Phytoplankton produziert die Hälfte unseres Sauerstoffs.",emoji:"🌿"},
 {q:"¿Cuántos Meter lang wird ein Riesenkalmar?",un:13,unit:"metros",hint:"Größtes Tier ohne Wirbelsäule.",emoji:"🦑"},
 {q:"¿Cuántos Zähne hat ein Weißer Hai?",un:300,unit:"dientes",hint:"en mehreren Reihen – ständig nachwachsend.",emoji:"🦷"},
 {q:"¿Cuántos Grad Celsius ist das Tiefseewasser?",un:2,unit:"°C",hint:"rápido eiskalt – das ganze Jahr.",emoji:"🌡️"},
 {q:"¿Cuántos Stunden schläft ein Delfin al día?",un:8,unit:"horas",hint:"Mit einer Gehirnhälfte – die andere bleibt wach.",emoji:"🐬"},
 {q:"¿Cuántos Arten von Quallen gibt es?",un:3000,unit:"especies",hint:"Von kleinen Zwergen bis zu riesigen Mähnenquallen.",emoji:"🪼"},
 {q:"¿Cuántos km/h schwimmt ein Seepferdchen?",un:1.5,unit:"km/h",hint:"Das langsamste Fisch im Meer.",emoji:"🐠"},
 {q:"¿Cuántos Liter Wasser filtert eine Muschel por hora?",un:8,unit:"litros",hint:"Muscheln reinigen das Meerwasser.",emoji:"🦪"},
 {q:"¿Cuántos km lang ist das Great Barrier Reef?",un:2300,unit:"km",hint:"Das größte Lebewesen der Erde.",emoji:"🪸"},
 {q:"¿Cuántos por ciento der Ozeane sind noch nicht erforscht?",un:80,unit:"%",hint:"Der Tiefseeboden ist fremder als der Mond.",emoji:"🔭"},
 {q:"¿Cuánto pesa wird ein Seestern maximal en Gramm?",un:500,unit:"gramos",hint:"Je nach Art.",emoji:"⭐"},
 {q:"¿Cuántos Kilometer tief ist der Pazifik en promedio?",un:4,unit:"km",hint:"4000 Meter Durchschnitt.",emoji:"🌊"},
 {q:"¿Cuánto tiempo kann eine Meeresschildkröte unter Wasser bleiben en Stunden?",un:7,unit:"horas",hint:"Im Schlaf noch länger.",emoji:"🐢"},
 {q:"¿Cuántos Stacheln hat ein Igelfisch?",un:300,unit:"Stacheln",hint:"Er bläst sich auf wenn er Angst hat.",emoji:"🐡"},
 {q:"¿Cuántos Meter lang wird ein Walhai?",un:12,unit:"metros",hint:"Größter Fisch der Welt – aber harmlos.",emoji:"🦈"},
 {q:"¿Cuántos Grad Celsius ist die Oberfläche des Meeres un einem heißen Tag?",un:30,unit:"°C",hint:"en tropischen Meeren.",emoji:"🌡️"},
 {q:"¿Cuántos Eier legt eine Meeresschildkröte pro Nest?",un:100,unit:"Eier",hint:"Nur wenige Babys überleben bis zum Meer.",emoji:"🥚"},
 {q:"¿Cuántos Kilometer tief ist der Atlantik?",un:3.3,unit:"km",hint:"3300 Meter Durchschnief.",emoji:"🌊"},
 {q:"¿Cuántos millones Tierarten leben im Ozean?",un:700,unit:"mil",hint:"000 bekannte Arten – viele noch unentdeckt.",emoji:"🐠"},
];