// 🏰 CUENTOS Y FANTASÍA – Español
export default [
 {q:"¿Cuántos Zwerge hat Schneewittchen?",un:7,unit:"Zwerge",hint:"Sie alle haben Namen: Schlafmütze, Brummbär, Hatschi...",emoji:"🏔️"},
 {q:"¿Cuántos Jahre schlief Dornröschen?",un:100,unit:"años",hint:"Bis sie ein Prinz wachküsste.",emoji:"🌹"},
 {q:"¿Cuántos Wünsche erfüllt der Geist aus der Wunderlampe en Aladdin?",un:3,unit:"Wünsche",hint:"Wünsche – dann muss der Geist en die Lampe zurück.",emoji:"🪔"},
 {q:"¿Cuántos Geschwister hat Aschenputtel (Stiefschwestern)?",un:2,unit:"Stiefschwestern",hint:"Zwei böse Stiefschwestern.",emoji:"👠"},
 {q:"¿Cuántos Brüder hat die kleine Meerjungfrau Ariel?",un:6,unit:"Brüder",hint:"Nein – sie hat 6 Schwestern.",emoji:"🧜‍♀️"},
 {q:"¿Cuántos Etagen hat Rapunzels Turm?",un:1,unit:"Etagen",hint:"Ein einziger hoher Raum ganz oben.",emoji:"🏰"},
 {q:"¿Cuántos Zwerge helfen den Gnomen im Märchen Snow White?",un:7,unit:"Zwerge",hint:"Die Sieben Zwerge sind weltberühmt.",emoji:"⛏️"},
 {q:"¿Cuántos Jahre braucht der gestiefelten Kater um seinen Herrn reich zu machen?",un:1,unit:"Jahr",hint:"Im Märchen geht es sehr schnell.",emoji:"🐱"},
 {q:"¿Cuántos Schwestern hat Aschenputtel?",un:2,unit:"Schwestern",hint:"Beide wollen den Prinzen für sich.",emoji:"👗"},
 {q:"¿Cuántos Hänsel und Gretel Kinder gibt es im Märchen?",un:2,unit:"Kinder",hint:"Hänsel UND Gretel – ein Bruder-Schwester-Paar.",emoji:"🏠"},
 {q:"¿Cuántos Meter lang ist Rapunzels Haar laut Märchen?",un:20,unit:"metros",hint:"Lang genug für den Prinzen zum Hochklettern.",emoji:"👱‍♀️"},
 {q:"¿Cuántos Wölfe gibt es im Märchen 'Die sieben Geißlein'?",un:1,unit:"Wolf",hint:"Ein böser Wolf – der große böse Wolf.",emoji:"🐺"},
 {q:"¿Cuántos Geißlein frisst der Wolf?",un:6,unit:"Geißlein",hint:"Das jüngste versteckte sich en der Wanduhr.",emoji:"🐐"},
 {q:"¿Cuántos Schuhe verliert Aschenputtel?",un:1,unit:"Schuh",hint:"Den gläsernen Schuh auf der Treppe.",emoji:"👠"},
 {q:"¿Cuántos Charaktere besuchen die Bremer Stadtmusikanten?",un:4,unit:"Tiere",hint:"Esel, Hund, Katze, Hahn.",emoji:"🎵"},
 {q:"¿Cuántos Prinzessinnen tanzen die Nacht durch im Märchen 'Die zertanzten Schuhe'?",un:12,unit:"Prinzessinnen",hint:"Schwestern tanzen heimlich.",emoji:"👠"},
 {q:"¿Cuántos Küsse braucht der Froschkönig um Mensch zu werden?",un:1,unit:"Kuss",hint:"Ein einziger Kuss der Prinzessin.",emoji:"🐸"},
 {q:"¿Cuántos Schwestern hat Cinderella en Disneys Version?",un:2,unit:"Stiefschwestern",hint:"Anastasia und Drizella.",emoji:"👑"},
 {q:"¿Cuántos Jahre schläft die Schöne im Dornröschen?",un:100,unit:"años",hint:"Das gesamte Schloss schläft mit.",emoji:"😴"},
 {q:"¿Cuántos Tiere helfen Schneewittchen im Wald?",un:7,unit:"Waldtiere",hint:"Die Waldtiere helfen ihr das Haus der Zwerge zu finden.",emoji:"🦌"},
 {q:"¿Cuántos masculino versucht die Hexe Schneewittchen zu töten?",un:3,unit:"masculino",hint:"Haarband, Kamm und vergifteter Apfel.",emoji:"🍎"},
];