// 🎨 ARTE E INVENTOS – Español
export default [
 {q:"¿En qué año erfand Alexander Graham Bell das Telefon?",un:1876,unit:"Jahr",hint:"Am 10. März 1876 – erster Satz: 'Watson, come here!'",emoji:"📞"},
 {q:"¿Cuántos Jahre arbeitete Leonardo da Vinci un der Mona Lisa?",un:4,unit:"años",hint:"Von 1503 bis ca. 1507.",emoji:"🖼️"},
 {q:"¿En qué año wurde das erste Lego-Stein erfunden?",un:1958,unit:"Jahr",hint:"Der dänische Tischler Ole Kirk Kristiansen.",emoji:"🧱"},
 {q:"¿Cuántos Farben hat ein Regenbogen?",un:7,unit:"Farben",hint:"Rot, Orange, Gelb, Grün, Blau, Indigo, Violett.",emoji:"🌈"},
 {q:"¿En qué año erfanden die Gebrüder Wright das Flugzeug?",un:1903,unit:"Jahr",hint:"12 Sekunden Flug – und die Welt veränderte sich.",emoji:"✈️"},
 {q:"¿Cuántos Meter groß ist die Mona Lisa?",un:77,unit:"cm Höhe",hint:"Nur 77cm hoch – überraschend klein.",emoji:"🖼️"},
 {q:"¿En qué año wurde das erste Buch gedruckt?",un:1440,unit:"Jahr",hint:"Johannes Gutenberg erfand den Buchdruck.",emoji:"📚"},
 {q:"¿Cuántos Farben nutzt ein Maler wenn er alle Farben mischen va a?",un:3,unit:"Grundfarben",hint:"Rot, Gelb, Blau – die drei Grundfarben.",emoji:"🎨"},
 {q:"¿En qué año erfand Thomas Edison die Glühbirne?",un:1879,unit:"Jahr",hint:"Nach 1000 Versuchen!",emoji:"💡"},
 {q:"¿Cuántos Töne hat eine normale Klaviertastatur?",un:88,unit:"Töne",hint:"52 weiße und 36 schwarze Tasten.",emoji:"🎹"},
 {q:"¿En qué año wurde das erste Smartphone (iPhone) erfunden?",un:2007,unit:"Jahr",hint:"Steve Jobs zeigte es am 9. Januar.",emoji:"📱"},
 {q:"¿Cuántos Jahre malte Michelangelo die Sixtinische Kapelle?",un:4,unit:"años",hint:"Von 1508 bis 1512.",emoji:"🎨"},
 {q:"¿En qué año wurde LEGO gegründet?",un:1932,unit:"Jahr",hint:"en Billund, Dänemark.",emoji:"🧱"},
 {q:"¿Cuántos Saiten hat eine normale Gitarre?",un:6,unit:"Saiten",hint:"E, un, D, G, H, e.",emoji:"🎸"},
 {q:"¿En qué año erfand Karl Benz das erste Auto?",un:1885,unit:"Jahr",hint:"Der Benz Patent-Motorwagen.",emoji:"🚗"},
 {q:"¿Cuántos Farben hat die Mondrian-Kunst normalerweise?",un:3,unit:"Grundfarben",hint:"Rot, Gelb, Blau plus Schwarz und Weiß.",emoji:"🟥"},
 {q:"¿En qué año erschuf Beethoven seine 9. Symphonie?",un:1824,unit:"Jahr",hint:"Beethoven war taub als er sie schrieb.",emoji:"🎵"},
 {q:"¿Cuántos Seiten hat ein Oktaeder (geometrische Form)?",un:8,unit:"Seiten",hint:"Wie zwei Pyramiden aufeinandergesetzt.",emoji:"🔷"},
 {q:"¿En qué año erfand Gutenberg die Druckmaschine?",un:1440,unit:"Jahr",hint:"Revolutionierte die Verbreitung von Wissen.",emoji:"📖"},
 {q:"¿Cuántos Buchstaben hat das deutsche Alphabet?",un:26,unit:"Buchstaben",hint:"Plus ä, ö, ü und ß – aber die zählen extra.",emoji:"🔤"},
 {q:"¿En qué año wurde der Eiffelturm gebaut?",un:1889,unit:"Jahr",hint:"Für die Weltausstellung en Paris.",emoji:"🗼"},
 {q:"¿Cuántos Noten gibt es en einer Oktave?",un:8,unit:"Noten",hint:"C, D, E, F, G, un, H, C.",emoji:"🎵"},
 {q:"¿En qué año erschuf van Gogh Sternennacht?",un:1889,unit:"Jahr",hint:"en einer Nervenheilanstalt en Arles.",emoji:"🌃"},
 {q:"¿Cuántos Farben hat die brasilianische Flagge?",un:4,unit:"Farben",hint:"Grün, Gelb, Blau, Weiß.",emoji:"🇧🇷"},
 {q:"¿En qué año erschuf Leonardo da Vinci sein Notizbuch über die Vogelflugmaschine?",un:1505,unit:"Jahr",hint:"Er träumte vom Fliegen.",emoji:"🐦"},
 {q:"¿Cuántos Zinken hat eine normale Gabel?",un:4,unit:"Zinken",hint:"Die Essgabel hat 4 Zinken.",emoji:"🍴"},
 {q:"¿En qué año erfand Alexander Fleming Penicillin?",un:1928,unit:"Jahr",hint:"Durch ein verschimmeltes Experiment.",emoji:"💊"},
 {q:"¿Cuántos Seiten hat ein Hexagon?",un:6,unit:"Seiten",hint:"Hexa = sechs – wie Bienenwaben.",emoji:"⬡"},
 {q:"¿En qué año erfand Aristoteles... seine Kategorien der Philosophie?",un:350,unit:"v.Chr.",hint:"Der Vater der Logik.",emoji:"🏛️"},
 {q:"¿Cuántos Farben hat die deutsche Flagge?",un:3,unit:"Farben",hint:"Schwarz, Rot, Gold.",emoji:"🇩🇪"},
];