// 💊 DROGEN & RAUSCH – Erwachsene – 250 Fragen
export default [
  {q:"Wie viele Milliarden Dollar wert ist der globale Drogenmarkt?",a:650,unit:"Mrd. Dollar",hint:"Illegal und legal zusammen.",emoji:"💊"},
  {q:"Wie viele Gramm Cannabis sind in Deutschland seit 2024 legal zu besitzen?",a:25,unit:"Gramm",hint:"Ab 18 Jahren – Teillegalisierung.",emoji:"🌿"},
  {q:"Wie viele Milligramm Koffein enthält eine Tasse Kaffee?",a:80,unit:"mg",hint:"Espresso hat etwas mehr – ca. 80-100mg.",emoji:"☕"},
  {q:"In welchem Jahr wurde Heroin von Bayer als Hustenmittel verkauft?",a:1898,unit:"Jahr",hint:"Bayer nannte es 'heroisch' wirksam.",emoji:"💊"},
  {q:"Wie viele Milliarden Dollar verdient das Medellin-Kartell auf seinem Höhepunkt pro Jahr?",a:4,unit:"Mrd. Dollar",hint:"Pablo Escobar – zeitweise reichster Verbrecher.",emoji:"🇨🇴"},
  {q:"Wie viele Kilogramm Kokain wurden 2022 in Europa beschlagnahmt?",a:300000,unit:"kg",hint:"300 Tonnen – Rekordmenge.",emoji:"❄️"},
  {q:"In welchem Jahr erfand LSD Albert Hofmann?",a:1938,unit:"Jahr",hint:"Entdeckt 1938, Wirkung bemerkt 1943.",emoji:"🔬"},
  {q:"Wie viele Milligramm Alkohol baut die Leber pro Stunde ab?",a:0.1,unit:"Promille/Stunde",hint:"0,1 Promille – unabhängig von der Menge.",emoji:"🍺"},
  {q:"Wie viele Milliarden Dollar wert ist der legale Cannabis-Markt in den USA?",a:30,unit:"Mrd. Dollar",hint:"Wächst durch Legalisierung stetig.",emoji:"🌿"},
  {q:"In welchem Jahr wurde die erste Anti-Drogen-Kampagne gestartet?",a:1971,unit:"Jahr",hint:"Nixons 'War on Drugs'.",emoji:"🇺🇸"},
  {q:"Wie viele Milligramm Ecstasy (MDMA) gelten als Einzeldosis?",a:100,unit:"Milligramm",hint:"100mg – typische Partydosis.",emoji:"💊"},
  {q:"Wie viele Milliarden Dollar Umsatz macht die Tabakindustrie weltweit?",a:900,unit:"Mrd. Dollar",hint:"Trotz Rückgang riesiger Markt.",emoji:"🚬"},
  {q:"Wie viele Milligramm Nikotin hat eine Zigarette?",a:10,unit:"mg",hint:"Davon werden 1-2mg absorbiert.",emoji:"🚬"},
  {q:"In welchem Jahr wurde Alkohol in den USA verboten (Prohibition)?",a:1920,unit:"Jahr",hint:"Von 1920 bis 1933.",emoji:"🍺"},
  {q:"Wie viele Millionen Raucher sterben jährlich weltweit?",a:8,unit:"Millionen",hint:"Rauchen ist die führende vermeidbare Todesursache.",emoji:"🚬"},
  {q:"Wie viele Milligramm Heroin gelten als tödliche Dosis?",a:200,unit:"Milligramm",hint:"200mg können bei Nicht-Abhängigen tödlich sein.",emoji:"💉"},
  {q:"Wie viele Milliarden Dollar verliert die Gesellschaft durch Alkoholmissbrauch jährlich?",a:250,unit:"Mrd. Dollar",hint:"In den USA allein.",emoji:"🍷"},
  {q:"In welchem Jahr begann das globale Opium-Problem in China?",a:1800,unit:"Jahr",hint:"Britische Händler führten Opium massenhaft ein.",emoji:"🇨🇳"},
  {q:"Wie viele Prozent der Drogendeaths weltweit sind durch Opioide?",a:70,unit:"%",hint:"Opioidkrise besonders in den USA.",emoji:"💊"},
  {q:"Wie viele Milligramm Koffein sind in einem Red Bull (250ml)?",a:80,unit:"mg",hint:"Gleich wie eine Tasse Kaffee.",emoji:"⚡"},
  {q:"Wie viele Millionen Menschen sind weltweit drogenabhängig?",a:40,unit:"Millionen",hint:"Über 40 Millionen mit ernsthafter Abhängigkeit.",emoji:"🔬"},
  {q:"In welchem Jahr wurde Kokain in Coca-Cola verboten?",a:1903,unit:"Jahr",hint:"Bis 1903 enthielt Coca-Cola echtes Kokain.",emoji:"🥤"},
  {q:"Wie viele Milliliter Wein entsprechen einer Standardportion Alkohol?",a:200,unit:"ml",hint:"0,2 Liter = ca. 20g reiner Alkohol.",emoji:"🍷"},
  {q:"Wie viele Milligramm MDMA braucht man für erste Wirkung?",a:75,unit:"mg",hint:"Eine typische Party-Pille wiegt sehr wenig.",emoji:"💊"},
  {q:"In welchem Jahr wurde Marihuana in Colorado legal?",a:2012,unit:"Jahr",hint:"Erster US-Bundesstaat der es legalisierte.",emoji:"🌿"},
  {q:"Wie viele Stunden hält der Cannabis-Rausch typischerweise an?",a:4,unit:"Stunden",hint:"Beim Rauchen – beim Essen länger.",emoji:"🌿"},
  {q:"Wie viele Milliarden Dollar verdient Walter White (Heisenberg) in Breaking Bad?",a:80,unit:"Mio. Dollar",hint:"Im Keller – tatsächlich im Drehbuch erwähnt.",emoji:"🧪"},
  {q:"Wie viele Gramm Alkohol stecken in einem 0,5l Bier (5%)?",a:20,unit:"Gramm",hint:"5% × 500ml × 0,8g/ml = 20g Alkohol.",emoji:"🍺"},
  {q:"In welchem Jahr wurde Crystal Meth erstmals synthetisiert?",a:1919,unit:"Jahr",hint:"In Japan von Akira Ogata.",emoji:"💎"},
  {q:"Wie viele Stunden dauert ein LSD-Trip?",a:12,unit:"Stunden",hint:"Von 8 bis 16 Stunden möglich.",emoji:"🌈"},
  {q:"Wie viele Milliarden Dollar kostet die US-Opioidkrise jährlich?",a:80,unit:"Mrd. Dollar",hint:"An verlorener Produktivität und Gesundheitskosten.",emoji:"💊"},
  {q:"Wie viele Millionen Menschen weltweit konsumieren Cannabis?",a:209,unit:"Millionen",hint:"Die am weitesten verbreitete illegale Droge.",emoji:"🌿"},
  {q:"In welchem Jahr endete die Prohibition in den USA?",a:1933,unit:"Jahr",hint:"21. Zusatzartikel zur Verfassung.",emoji:"🍺"},
  {q:"Wie viele Kilogramm Kokain konsumiert Großbritannien pro Tag?",a:700,unit:"kg/Woche",hint:"Das meistkonsumierte Land in Europa.",emoji:"❄️"},
  {q:"Wie viele Milligramm Psilocybin gelten als starke Dosis?",a:25,unit:"mg",hint:"Reines Psilocybin – starke Erfahrung.",emoji:"🍄"},
  {q:"In welchem Jahr wurde Cannabis in den Niederlanden toleriert?",a:1976,unit:"Jahr",hint:"Gedoogbeleid – keine Strafverfolgung.",emoji:"🌷"},
  {q:"Wie viele Stunden dauert ein MDMA-Trip?",a:6,unit:"Stunden",hint:"Wirkung hält 3-6 Stunden an.",emoji:"💊"},
  {q:"Wie viele Gramm Cannabis raucht ein Durchschnittskonsument pro Woche?",a:3.5,unit:"Gramm",hint:"Ein halbes Eighth pro Woche.",emoji:"🌿"},
  {q:"Wie viele Milliarden Dollar macht Pablo Escobars Vermögen auf Höhepunkt?",a:30,unit:"Mrd. Dollar",hint:"Forbes listete ihn 1989.",emoji:"🇨🇴"},
  {q:"In welchem Jahr kam OxyContin auf den Markt?",a:1995,unit:"Jahr",hint:"Startschuss der amerikanischen Opioidkrise.",emoji:"💊"},
  {q:"Wie viele Prozent des Kokains kommen aus Kolumbien?",a:70,unit:"%",hint:"Kolumbien ist weltgrößter Kokaproduzent.",emoji:"🇨🇴"},
  {q:"Wie viele Milligramm Koffein sind in einem Espresso?",a:80,unit:"mg",hint:"In einem single shot.",emoji:"☕"},
  {q:"Wie viele Stunden bleibt Alkohol im Blut nachweisbar?",a:12,unit:"Stunden",hint:"Je nach Menge bis zu 24 Stunden.",emoji:"🍺"},
  {q:"In welchem Jahr synthetisierte Hofmann erstmals Psilocybin?",a:1958,unit:"Jahr",hint:"Albert Hofmann auch hier der Pionier.",emoji:"🍄"},
  {q:"Wie viele Tonnen Opium produziert Afghanistan pro Jahr?",a:6000,unit:"Tonnen",hint:"90% des weltweiten Opiums.",emoji:"🌸"},
  {q:"Wie viele Milligramm Kokain gelten als durchschnittliche Linie?",a:50,unit:"mg",hint:"Eine Linie ist viel kleiner als die meisten denken.",emoji:"❄️"},
  {q:"Wie viele Prozent aller Verbrechen in Deutschland stehen unter Drogeneinfluss?",a:30,unit:"%",hint:"Alkohol und andere Substanzen.",emoji:"📊"},
  {q:"In welchem Jahr wurde Fentanyl synthetisiert?",a:1960,unit:"Jahr",hint:"Von Paul Janssen – 100x stärker als Morphin.",emoji:"💊"},
  {q:"Wie viele Milligramm Tabak enthält eine Zigarette?",a:700,unit:"Milligramm",hint:"700mg Tabak pro Filterzigarette.",emoji:"🚬"},
  {q:"Wie viele Stunden dauert der körperliche Alkohol-Entzug?",a:72,unit:"Stunden",hint:"3-7 Tage – kann lebensgefährlich sein.",emoji:"🏥"},
  {q:"Wie viele Millionen Bundesbürger gelten als alkoholabhängig?",a:3.1,unit:"Millionen",hint:"Schätzung der Deutschen Hauptstelle für Suchtfragen.",emoji:"🍺"},
  {q:"In welchem Jahr begann Mexikos Drogenkrieg offiziell?",a:2006,unit:"Jahr",hint:"Calderon erklärte den Krieg gegen die Kartelle.",emoji:"🇲🇽"},
  {q:"Wie viele Milligramm Wirkstoff hat ein typischer Haschisch-Joint?",a:10,unit:"mg THC",hint:"Bei 10% THC-Gehalt in 100mg Hasch.",emoji:"🌿"},
  {q:"Wie viele Tonnen Kokain werden jährlich weltweit produziert?",a:1000,unit:"Tonnen",hint:"Mehrere Tonnen pro Jahr – ein riesiger Markt.",emoji:"❄️"},
  {q:"In welchem Jahr begann die Opioidkrise in den USA offiziell?",a:1999,unit:"Jahr",hint:"Erste Welle durch verschreibungspflichtige Opioide.",emoji:"💊"},
  {q:"Wie viele Prozent aller Drogentoten sterben durch Alkohol?",a:55,unit:"%",hint:"Alkohol ist die tödlichste Droge.",emoji:"🍷"},
  {q:"Wie viele Milligramm Heroin sind in einer typischen Straßendosis?",a:50,unit:"mg",hint:"Stark variierend je nach Reinheit.",emoji:"💉"},
  {q:"Wie viele Stunden bleibt THC im Blut nachweisbar?",a:24,unit:"Stunden",hint:"Im Urin bis zu 30 Tage.",emoji:"🌿"},
  {q:"In welchem Jahr wurde Ecstasy (MDMA) erstmals synthetisiert?",a:1912,unit:"Jahr",hint:"Von Merck – ursprünglich als Appetitzügler.",emoji:"💊"},
  {q:"Wie viele Milliarden Dollar wert ist die Pharmaindustrie die Opioide verkauft?",a:50,unit:"Mrd. Dollar",hint:"Nur der Opioid-Markt allein.",emoji:"💊"},
  {q:"Wie viele Prozent der Kokainkonsumenten werden abhängig?",a:15,unit:"%",hint:"Geringer als bei Nikotin oder Heroin.",emoji:"📊"},
  {q:"In welchem Jahr legalisierte Uruguay als erstes Land Cannabis?",a:2013,unit:"Jahr",hint:"Erstes Land weltweit.",emoji:"🌿"},
  {q:"Wie viele Gramm Cannabis darf man in Deutschland zu Hause lagern?",a:50,unit:"Gramm",hint:"Seit der Teillegalisierung 2024.",emoji:"🌿"},
  {q:"Wie viele Milligramm Nikotin braucht ein Nikotinpflaster?",a:14,unit:"mg",hint:"Je nach Stärke des Pflasters variiert die Dosis.",emoji:"🩹"},
  {q:"Wie viele Stunden braucht man um bei 2 Promille fahrtüchtig zu sein?",a:20,unit:"Stunden",hint:"0,1 Promille pro Stunde abbau.",emoji:"🚗"},
  {q:"In welchem Jahr wurde Morphin aus Opium isoliert?",a:1804,unit:"Jahr",hint:"Friedrich Sertürner in Deutschland.",emoji:"🌸"},
  {q:"Wie viele Tonnen Kokain werden jährlich in die EU geschmuggelt?",a:200,unit:"Tonnen",hint:"Schätzungen der Europol.",emoji:"🚢"},
  {q:"Wie viele Milligramm Koffein sind in einem Matcha (200ml)?",a:70,unit:"mg",hint:"Ähnlich wie Kaffee aber gleichmäßigere Wirkung.",emoji:"🍵"},
  {q:"Wie viele Prozent der Nikotinabhängigen schaffen es mit Willenskraft aufzuhören?",a:5,unit:"%",hint:"Nur 5% schaffen es dauerhaft ohne Hilfe.",emoji:"📊"},
  {q:"In welchem Jahr wurde Methamphetamin in der NS-Zeit eingesetzt?",a:1940,unit:"Jahr",hint:"Pervitin – Soldaten-Droge im Zweiten Weltkrieg.",emoji:"⚔️"},
  {q:"Wie viele Milligramm Koffein sind zu viel für einen Erwachsenen?",a:400,unit:"mg",hint:"Täglich gilt als sichere Obergrenze.",emoji:"☕"},
  {q:"Wie viele Jahre braucht man durchschnittlich um Nikotinsucht vollständig zu überwinden?",a:5,unit:"Jahre",hint:"Das Verlangen kann Jahre anhalten.",emoji:"🚬"},
  {q:"In welchem Jahr kaufte El Chapo die erste Tonne Kokain?",a:1980,unit:"Jahr",hint:"Beginn seiner kriminellen Karriere.",emoji:"🇲🇽"},
  {q:"Wie viele Milligramm THC reichen für eine starke Wirkung bei Neukonsumienten?",a:5,unit:"mg",hint:"THC ist für Unerfahrene viel.",emoji:"🌿"},
  {q:"In welchem Jahr wurde das Opiumgesetz in Deutschland verabschiedet?",a:1929,unit:"Jahr",hint:"Erste deutsche Drogengesetzgebung.",emoji:"📜"},
  {q:"Wie viele Stunden kann ein Koffeinentzugskopfschmerz dauern?",a:72,unit:"Stunden",hint:"Koffeinabhängigkeit ist eine anerkannte Störung.",emoji:"☕"},
  {q:"Wie viele Milliarden Dollar verdient Mexikos Sinaloa-Kartell pro Jahr?",a:3,unit:"Mrd. Dollar",hint:"Eines der mächtigsten Kartelle der Welt.",emoji:"🇲🇽"},
  {q:"Wie viele Stunden liegt die Halbwertszeit von LSD im Körper?",a:3.5,unit:"Stunden",hint:"Wirkung hält viel länger an als die Halbwertszeit.",emoji:"🌈"},
  {q:"In welchem Jahr wurde das erste Methadon-Programm gestartet?",a:1964,unit:"Jahr",hint:"In New York City von Dole und Nyswander.",emoji:"💉"},
  {q:"Wie viele Milligramm Psilocybin hat ein magic mushroom (durchschnittlich)?",a:10,unit:"mg",hint:"Je nach Art 5-15mg.",emoji:"🍄"},
  {q:"Wie viele Tonnen Heroin werden jährlich aus Afghanistan exportiert?",a:400,unit:"Tonnen",hint:"Trotz US-Besatzung stieg Produktion.",emoji:"🌸"},
  {q:"In welchem Jahr begann Deutschland mit Cannabis-Legalisierung?",a:2024,unit:"Jahr",hint:"Am 1. April 2024 trat das Cannabisgesetz in Kraft.",emoji:"🌿"},
  {q:"Wie viele Stunden nach Drogenkonsum kann eine Urinprobe positiv sein (Kokain)?",a:72,unit:"Stunden",hint:"3 Tage für Kokain.",emoji:"🔬"},
  {q:"Wie viele Milliarden Dollar kostet Drogenprävention und Behandlung weltweit?",a:35,unit:"Mrd. Dollar",hint:"Vastly insufficient vs. the problem.",emoji:"💊"},
  {q:"In welchem Jahr erfand man das Bier (erste Aufzeichnung)?",a:5000,unit:"v.Chr.",hint:"In Mesopotamien gebraut.",emoji:"🍺"},
  {q:"Wie viele Milligramm Alkohol hat ein Promille im Blut?",a:1,unit:"g/L",hint:"Promille = 1g Alkohol pro Liter Blut.",emoji:"🍷"},
  {q:"In welchem Jahr wurde das erste Konzentrationslager-Drogenexperiment dokumentiert?",a:1942,unit:"Jahr",hint:"Dachau – erzwungene Drogenversuche.",emoji:"☮️"},
  {q:"Wie viele Milligramm Kokain am Tag hat Sigmund Freud konsumiert?",a:200,unit:"mg",hint:"Er pries es anfangs als Wundermittel.",emoji:"🧠"},
  {q:"Wie viele Tonnen MDMA werden jährlich produziert?",a:200,unit:"Tonnen",hint:"Hauptsächlich in den Niederlanden.",emoji:"🌷"},
  {q:"In welchem Jahr wurde Heroin verboten in Deutschland?",a:1971,unit:"Jahr",hint:"Mit dem Betäubungsmittelgesetz.",emoji:"💉"},
  {q:"Wie viele Stunden ist man nach einem MDMA-Konsum nicht fahrtüchtig?",a:24,unit:"Stunden",hint:"Mindestens 24 Stunden.",emoji:"🚗"},
  {q:"Wie viele Milliarden Dollar wert ist der CBD-Markt weltweit?",a:6,unit:"Mrd. Dollar",hint:"CBD ohne THC – boom in den 2010ern.",emoji:"🌿"},
  {q:"In welchem Jahr wurde Kokain in den USA verboten?",a:1914,unit:"Jahr",hint:"Harrison Narcotics Tax Act.",emoji:"🇺🇸"},
  {q:"Wie viele Millionen Kapseln Tramadol wurden in Nigeria beschlagnahmt?",a:4,unit:"Millionen Kapseln",hint:"Massenhafter Schmuggel in Westafrika (Stand 2018).",emoji:"💊"},
  {q:"In welchem Jahr begann die psychedelische Revolution in der Psychiatrie?",a:2018,unit:"Jahr",hint:"Psilocybin-Therapie wurde ernsthaft untersucht.",emoji:"🍄"},
  {q:"Wie viele Milliarden Zigaretten werden jährlich weltweit geraucht?",a:5500,unit:"Milliarden",hint:"5,5 Billionen Zigaretten.",emoji:"🚬"},
  {q:"Wie viele Gramm Alkohol pro Tag gelten als schädlich für Männer?",a:20,unit:"Gramm",hint:"2 Standardgläser – DGE-Empfehlung.",emoji:"🍷"},
  {q:"In welchem Jahr entdeckte Hoffman Mescalin zu synthetisieren?",a:1919,unit:"Jahr",hint:"Ernst Späth synthetisierte Mescalin.",emoji:"🌵"},
  {q:"Wie viele Millionen Dollar hat El Chapo insgesamt verdient?",a:14000,unit:"Mio. Dollar",hint:"14 Milliarden Dollar geschätztes Vermögen.",emoji:"🇲🇽"},
  {q:"Wie viele Stunden braucht der Körper um Ecstasy abzubauen?",a:40,unit:"Stunden",hint:"Halbwertszeit 8-9 Stunden – vollständig 40h.",emoji:"💊"},
  {q:"Wie viele Prozent der Heroinkonsumenten werden abhängig?",a:23,unit:"%",hint:"Höchste Abhängigkeitsrate aller Drogen.",emoji:"💉"},
  {q:"In welchem Jahr trat das deutsche Cannabisgesetz in Kraft?",a:2024,unit:"Jahr",hint:"1. April 2024.",emoji:"🌿"},
  {q:"Wie viele Milligramm Psilocybin gelten als mikrodosing?",a:0.1,unit:"mg",hint:"0,1-0,3g getrocknete Pilze.",emoji:"🍄"},
  {q:"Wie viele Länder haben Cannabis vollständig legalisiert?",a:5,unit:"Länder",hint:"Uruguay, Kanada, Deutschland, Malta, Luxemburg (Stand 2024).",emoji:"🌿"},
  {q:"In welchem Jahr synthetisierte Merck erstmals MDMA?",a:1912,unit:"Jahr",hint:"Ursprünglich zur Blutgerinnung gedacht.",emoji:"💊"},
  {q:"Wie viele Stunden hält die Wirkung von Mescalin an?",a:12,unit:"Stunden",hint:"8-12 Stunden – ähnlich wie LSD.",emoji:"🌵"},
  {q:"Wie viele Milliarden Dollar verliert Mexiko durch den Drogenkrieg wirtschaftlich?",a:10,unit:"Mrd. Dollar",hint:"Indirekte Kosten durch Unsicherheit.",emoji:"🇲🇽"},
  {q:"Wie viele Tonnen Tabak produziert China jährlich?",a:2400,unit:"Tonnen",hint:"China ist weltgrößter Tabakproduzent.",emoji:"🚬"},
  {q:"In welchem Jahr wurde Krokodil (Desomorphin) populär in Russland?",a:2003,unit:"Jahr",hint:"Günstige und verheerende Droge.",emoji:"🇷🇺"},
  {q:"Wie viele Prozent der Gefängnisinsassen in Deutschland sitzen wegen Drogendelikten?",a:15,unit:"%",hint:"Vor allem Handel und Besitz.",emoji:"🔒"},
  {q:"Wie viele Milligramm Koffein hat eine Tasse grüner Tee?",a:25,unit:"mg",hint:"Deutlich weniger als Kaffee.",emoji:"🍵"},
  {q:"In welchem Jahr begann die niederländische Drogenpolitik (Toleranz)?",a:1976,unit:"Jahr",hint:"Opiumgesetz-Reform.",emoji:"🌷"},
  {q:"Wie viele Milliarden Dollar Schaden entsteht durch Drogenkonsum am Arbeitsplatz?",a:120,unit:"Mrd. Dollar",hint:"Allein in den USA.",emoji:"💼"},
  {q:"Wie viele Stunden Schlaf fördert CBD?",a:1,unit:"Stunde mehr",hint:"Studien zeigen leichte Schlafverbesserung.",emoji:"😴"},
  {q:"Wie viele Prozent des Heroins kommen über die Balkanroute nach Europa?",a:70,unit:"%",hint:"Türkei – Balkan – Westeuropa.",emoji:"🚢"},
  {q:"In welchem Jahr wurde das Haager Opiumabkommen unterzeichnet?",a:1912,unit:"Jahr",hint:"Erste internationale Drogenkonvention.",emoji:"🌍"},
  {q:"Wie viele Gramm Ethanol sind in einem Glas Sekt (0,1l)?",a:8,unit:"Gramm",hint:"Bei 11% Alkohol.",emoji:"🥂"},
  {q:"Wie viele Millionen Deutsche konsumieren regelmäßig Schlaftabletten?",a:2,unit:"Millionen",hint:"Davon viele mit Abhängigkeit.",emoji:"💊"},
  {q:"In welchem Jahr kam Ritalin auf den Markt?",a:1954,unit:"Jahr",hint:"Methylphenidat – für ADHS.",emoji:"💊"},
  {q:"Wie viele Milligramm Koffein stecken in einer Dose Monster Energy?",a:160,unit:"mg",hint:"Doppelt so viel wie Red Bull.",emoji:"⚡"},
  {q:"Wie viele Tonnen illegale Drogen werden jährlich in Deutschland beschlagnahmt?",a:20,unit:"Tonnen",hint:"Cannabis, Kokain, Heroin und mehr.",emoji:"🔍"},
  {q:"In welchem Jahr wurde Kodein als Hustenemittel eingesetzt?",a:1832,unit:"Jahr",hint:"Aus Opium isoliert.",emoji:"💊"},
  {q:"Wie viele Milligramm Psilocybin enthält ein typischer Zauberpilz?",a:10,unit:"mg",hint:"Pro Gramm getrockneter Pilze ~10mg.",emoji:"🍄"},
  {q:"Wie viele Prozent der Drogenabhängigen erhalten Behandlung?",a:15,unit:"%",hint:"85% bleiben unbehandelt.",emoji:"📊"},
  {q:"In welchem Jahr begann der globale Krieg gegen Kokain?",a:1989,unit:"Jahr",hint:"Bush erklärte den War on Drugs.",emoji:"🇺🇸"},
  {q:"Wie viele Gramm Alkohol hat ein Schnapsglas (4cl, 40%)?",a:12,unit:"Gramm",hint:"Ein Standarddrink enthält ~10-12g Alkohol.",emoji:"🥃"},
  {q:"Wie viele Stunden bleibt Kokain im Urin nachweisbar?",a:72,unit:"Stunden",hint:"3-4 Tage für Gelegenheitskonsumenten.",emoji:"🔬"},
  {q:"In welchem Jahr wurde Tabak in Europa eingeführt?",a:1492,unit:"Jahr",hint:"Kolumbus brachte es mit.",emoji:"⛵"},
  {q:"Wie viele Millionen Menschen konsumieren täglich Alkohol weltweit?",a:500,unit:"Millionen",hint:"Über 2 Milliarden trinken gelegentlich.",emoji:"🍷"},
  {q:"Wie viele Gramm Alkohol am Tag erhöhen das Krebsrisiko messbar?",a:10,unit:"Gramm",hint:"Schon ein Glas täglich erhöht das Risiko.",emoji:"⚠️"},
  {q:"In welchem Jahr wurde GHB zur Partydrogen-Substanz bekannt?",a:1990,unit:"Jahr",hint:"Ghb – auch 'Liquid Ecstasy' genannt.",emoji:"💊"},
  {q:"Wie viele Milliarden Dollar wert ist das Bitcoin-Geldwäsche-Geschäft für Kartelle?",a:2,unit:"Mrd. Dollar",hint:"Krypto als Geldwäsche-Tool.",emoji:"₿"},
  {q:"In welchem Jahr wurde Fentanyl in den USA zur Epidemie erklärt?",a:2016,unit:"Jahr",hint:"Dritte Welle der Opioidkrise.",emoji:"💊"},
  {q:"Wie viele Stunden Schlafen verbessern die Drogenresistenz?",a:8,unit:"Stunden",hint:"Schlafmangel erhöht Suchtrisiko.",emoji:"😴"},
  {q:"Wie viele Milliarden Dollar wert ist der weltweite Alkoholmarkt?",a:1600,unit:"Mrd. Dollar",hint:"Beer, Wine, Spirits zusammen.",emoji:"🍷"},
  {q:"Wie viele Gramm Alkohol pro Woche empfiehlt die WHO maximal?",a:100,unit:"Gramm",hint:"Neuere Richtlinien – weniger ist besser.",emoji:"🏥"},
  {q:"In welchem Jahr wurde das erste Entzugszentrum in Deutschland gegründet?",a:1850,unit:"Jahr",hint:"In Hamburg – für Alkohol.",emoji:"🏥"},
  {q:"Wie viele Milligramm Methamphetamin gelten als 'Tweaker'-Dosis?",a:200,unit:"mg",hint:"Missbrauchsdosis – extrem gefährlich.",emoji:"💎"},
  {q:"Wie viele Tonnen Cannabis werden jährlich in Deutschland konsumiert?",a:400,unit:"Tonnen",hint:"Nach der Legalisierung deutlicher Anstieg.",emoji:"🌿"},
  {q:"In welchem Jahr begann die psychedelische Forschung der CIA (MK Ultra)?",a:1953,unit:"Jahr",hint:"LSD-Experimente an Unwissenden.",emoji:"🕵️"},
  {q:"Wie viele Milliarden Dollar wert ist der globale Markt für Schlaf-Supplements?",a:85,unit:"Mrd. Dollar",hint:"Melatonin, Baldrian und Co.",emoji:"😴"},
  {q:"Wie viele Prozent der Schweizer konsumieren regelmäßig Cannabis?",a:5,unit:"%",hint:"Trotz Verbot – relativ hohe Rate.",emoji:"🇨🇭"},
  {q:"In welchem Jahr erschien das Buch 'Go Ask Alice' über Drogensucht?",a:1971,unit:"Jahr",hint:"Umstrittenes Jugendbuch.",emoji:"📚"},
  {q:"Wie viele Milligramm Ketamin werden bei Anästhesie eingesetzt?",a:1,unit:"mg/kg",hint:"Die Dosierung hängt vom Körpergewicht ab.",emoji:"💊"},
  {q:"Wie viele Stunden liegt die Wirkung von Speed (Amphetamin) an?",a:8,unit:"Stunden",hint:"4-8 Stunden.",emoji:"⚡"},
  {q:"In welchem Jahr entdeckte man die Wirkung von Cannabis als Medizin?",a:2700,unit:"v.Chr.",hint:"Chinesische Medizin nutzte es 2700 v.Chr.",emoji:"🌿"},
  {q:"Wie viele Milliarden Dollar wert ist Purdue Pharma beim Bankrott?",a:10,unit:"Mrd. Dollar",hint:"Opioid-Hersteller – pleite durch Klagen.",emoji:"💊"},
  {q:"Wie viele Prozent der 18-25-Jährigen in Deutschland haben Cannabis probiert?",a:48,unit:"%",hint:"Fast jeder Zweite in dieser Altersgruppe.",emoji:"🌿"},
  {q:"In welchem Jahr begann Japan Methamphetamin nach dem Krieg zu verbieten?",a:1951,unit:"Jahr",hint:"Nach einer massiven Nachkriegssucht.",emoji:"🇯🇵"},
  {q:"Wie viele Tonnen Opium produziert der sogenannte Goldene Halbmond?",a:3000,unit:"Tonnen",hint:"Iran, Afghanistan, Pakistan.",emoji:"🌸"},
  {q:"In welchem Jahr wurde Cannabis in Marokko entkriminalisiert?",a:2021,unit:"Jahr",hint:"Medizianlisch erlaubt.",emoji:"🌿"},
  {q:"Wie viele Milliarden Dollar investiert die Pharmaindustrie in Drogenbehandlung?",a:3,unit:"Mrd. Dollar",hint:"Viel weniger als in neue Drogen.",emoji:"💊"},
  {q:"Wie viele Kilogramm THC braucht man für eine tödliche Dosis?",a:9999,unit:"kg",hint:"Praktisch unmöglich zu überdosieren.",emoji:"🌿"},
  {q:"In welchem Jahr wurde Crack-Kokain populär in US-Innenstädten?",a:1985,unit:"Jahr",hint:"Crack-Epidemic in den 80ern.",emoji:"🇺🇸"},
  {q:"Wie viele Stunden dauert der Kater nach starkem Alkoholkonsum?",a:24,unit:"Stunden",hint:"Hangover bis zu 24 Stunden.",emoji:"🤢"},
  {q:"Wie viele Milliarden Dollar Jahresumsatz macht Altria (Marlboro-Hersteller)?",a:25,unit:"Mrd. Dollar",hint:"Philip Morris International.",emoji:"🚬"},
  {q:"In welchem Jahr wurden Opiate aus der türkischen Medizin verbannt?",a:1933,unit:"Jahr",hint:"Atatürks Modernisierungsreformen.",emoji:"🇹🇷"},
  {q:"Wie viele Millionen Menschen starben in der Geschichte an Opiumsucht?",a:100,unit:"Millionen",hint:"Schätzung über alle Jahrhunderte.",emoji:"🌸"},
  {q:"In welchem Jahr wurde das Rauchen in deutschen Gaststätten verboten?",a:2007,unit:"Jahr",hint:"Varies by Bundesland.",emoji:"🚭"},
  {q:"Wie viele Gramm Alkohol stecken in einem Glas Sekt (0,1L, 11%)?",a:8.8,unit:"Gramm",hint:"0,1L × 0,11 × 0,8g/ml = 8,8g.",emoji:"🥂"},
  {q:"Wie viele Millionen Menschen sind weltweit spielsüchtig?",a:400,unit:"Millionen",hint:"Eine behavioral addiction wie Drogensucht.",emoji:"🎰"},
  {q:"In welchem Jahr erschien Breaking Bad?",a:2008,unit:"Jahr",hint:"Die Serie über Crystal Meth.",emoji:"🧪"},
  {q:"Wie viele Milligramm Morphin sind äquivalent zu 10mg Heroin?",a:30,unit:"mg Morphin",hint:"Heroin ist 3x so stark wie Morphin.",emoji:"💉"},
  {q:"In welchem Jahr begann die erste Welle der Opioidkrise in den USA?",a:1999,unit:"Jahr",hint:"Durch Verschreibungen.",emoji:"💊"},
  {q:"Wie viele Milliarden Dollar verdienen Pharmaunternehmen an Antidepressiva?",a:15,unit:"Mrd. Dollar",hint:"Prozac, Zoloft und Generika.",emoji:"💊"},
  {q:"Wie viele Tonnen Kokain werden jährlich in den USA konsumiert?",a:200,unit:"Tonnen",hint:"Größter Kokainmarkt der Welt.",emoji:"❄️"},
  {q:"In welchem Jahr gründete George Soros die Drug Policy Alliance?",a:2000,unit:"Jahr",hint:"Für eine liberalere Drogenpolitik.",emoji:"💊"},
  {q:"Wie viele Milligramm Koffein machen abhängig?",a:200,unit:"mg/Tag",hint:"Regelmäßige Zufuhr von 200-300mg.",emoji:"☕"},
  {q:"Wie viele Gramm Cannabis darf man in Colorado kaufen auf einmal?",a:28,unit:"Gramm",hint:"1 Ounce – für Einwohner und Touristen.",emoji:"🌿"},
  {q:"In welchem Jahr beschlagnahmte die DEA mehr als 10.000 kg Meth?",a:2019,unit:"Jahr",hint:"Rekordmenge in einem Jahr.",emoji:"💎"},
  {q:"Wie viele Milliarden Dollar wert ist der Cannabis-Markt in Deutschland nach Legalisierung?",a:5,unit:"Mrd. Euro",hint:"Schätzung für den deutschen Markt.",emoji:"🌿"},
  {q:"Wie viele Stunden bleibt Heroin im Blut nachweisbar?",a:12,unit:"Stunden",hint:"Kurze Halbwertszeit – Metabolite länger.",emoji:"🔬"},
  {q:"In welchem Jahr wurde das erste Strafgesetzbuch zu Drogen in China verabschiedet?",a:1840,unit:"Jahr",hint:"Nach den Opiumkriegen.",emoji:"🇨🇳"},
  {q:"In welchem Jahr begann Portugal seinen progressiven Drogenansatz?",a:2001,unit:"Jahr",hint:"Entkriminalisierung aller Drogen.",emoji:"🇵🇹"},
  {q:"Wie viele Milligramm Fentanyl sind tödlich?",a:2,unit:"mg",hint:"– ein winziger Fleck auf der Haut.",emoji:"💊"},
  {q:"Wie viele Tonnen Cannabis produziert Marokko jährlich (Haschisch)?",a:800,unit:"Tonnen",hint:"Größter Haschisch-Exporteur Europas.",emoji:"🌍"},
  {q:"In welchem Jahr wurde Naloxon (Narcan) zur Rettung bei Überdosis entwickelt?",a:1961,unit:"Jahr",hint:"Opioid-Gegenmittel.",emoji:"💉"},
  {q:"Wie viele Milliarden Dollar Verlust macht der globale Südostasien-Drogenmarkt durch Konfiszierungen?",a:1,unit:"Mrd. Dollar",hint:"Goldenes Dreieck – Myanmar, Laos, Thailand.",emoji:"🌏"},
  {q:"Wie viele Gramm Wein müsste man trinken um an Alkohol zu sterben?",a:500,unit:"Gramm Alkohol",hint:"500g reiner Alkohol = tödliche Dosis.",emoji:"🍷"},
  {q:"In welchem Jahr wurde GHB als Dopingmittel verboten?",a:2000,unit:"Jahr",hint:"WADA fügte es auf die Liste.",emoji:"🏃"},
];
