// 🐾 TIERE & SEX – Erwachsene – 250 Fragen
export default [
  {id:"tsex_001",q:"Wie lange dauert der Sex bei Schlangen in Stunden?",a:24,unit:"Stunden",hint:"Schlangen können tage- und wochenlang paaren.",emoji:"🐍"},
  {id:"tsex_002",q:"Wie viele cm lang ist der Penis einer Ente relativ zur Körperlänge?",a:40,unit:"cm",hint:"Stockenten haben spiralförmige Penisse.",emoji:"🦆"},
  {id:"tsex_003",q:"Wie viele Hoden hat ein Stier?",a:2,unit:"Hoden",hint:"Wie die meisten Säugetiere.",emoji:"🐂"},
  {id:"tsex_004",q:"Wie viele cm lang ist der Penis eines Blauwals?",a:270,unit:"cm",hint:"2,7 Meter – das größte Geschlechtsorgan im Tierreich.",emoji:"🐋"},
  {id:"tsex_005",q:"Wie lange trägt eine Elefantendame ihr Junges in Tagen?",a:645,unit:"Tage",hint:"Fast 2 Jahre – längste Tragzeit auf Land.",emoji:"🐘"},
  {id:"tsex_006",q:"Wie viele Mal paart sich ein Schimpanse mit verschiedenen Weibchen?",a:100,unit:"Mal",hint:"Männliche Schimpansen paaren sich mit vielen Weibchen.",emoji:"🐒"},
  {id:"tsex_007",q:"Wie viele Millionen Eier legt eine Königin-Biene in ihrem Leben?",a:2,unit:"Millionen Eier",hint:"2 Millionen über ihr Leben von 5 Jahren.",emoji:"🐝"},
  {id:"tsex_008",q:"Wie lang ist die Vagina einer Kuh in cm?",a:30,unit:"cm",hint:"Ähnlich lang wie der Arm eines Kindes.",emoji:"🐄"},
  {id:"tsex_009",q:"Wie viele Milliarden Spermien enthält ein Stier-Ejakulat?",a:7,unit:"Milliarden Spermien",hint:"7 Milliarden – viel mehr als beim Menschen.",emoji:"🐂"},
  {id:"tsex_010",q:"Wie lange dauert der Sex bei Giraffen in Sekunden?",a:2,unit:"Sekunden",hint:"Sehr schnell – aber häufig.",emoji:"🦒"},
  {id:"tsex_011",q:"Wie viele Mal am Tag paart sich ein Löwe?",a:20,unit:"Mal",hint:"In der Ranzzeit bis zu 20 Mal täglich – je alle 15 Minuten.",emoji:"🦁"},
  {id:"tsex_012",q:"Wie viele cm lang ist der Penis eines Gorillas?",a:4,unit:"cm",hint:"Trotz ihrer Größe sehr kleines Geschlechtsorgan.",emoji:"🦍"},
  {id:"tsex_013",q:"Wie lange dauert der Geschlechtsakt bei Bonobos?",a:15,unit:"Sekunden",hint:"Sehr kurz – aber sehr häufig.",emoji:"🐒"},
  {id:"tsex_014",q:"Wie viele Hoden hat ein Wal?",a:2,unit:"Hoden",hint:"Innen liegend – zum Schutz vor Kälte.",emoji:"🐋"},
  {q:"Wie viele Spermien kann ein Gorilla-Ejakulat enthalten?",a:200000000,hint:"Deutlich weniger als Schimpansen.",unit:"Spermien",emoji:"🦍"},
  {id:"tsex_015",q:"Wie lange trägt eine Hai-Art ihr Junges in Monaten?",a:24,unit:"Monate",hint:"Hammerhaie tragen 2 Jahre.",emoji:"🦈"},
  {id:"tsex_016",q:"Wie viele Male seiner Körpergröße ist der Penis einer Seepocke lang?",a:8,unit:"x Körperlänge",hint:"Relativ zur Körpergröße das längste Geschlechtsorgan.",emoji:"🦀"},
  {id:"tsex_017",q:"Wie viele cm ist die Klitoris einer Hyäne lang?",a:18,unit:"cm",hint:"Weibliche Hyänen haben eine pseudopenis-ähnliche Klitoris.",emoji:"🦁"},
  {id:"tsex_018",q:"Wie lang dauert die Paarung bei Nashörnern in Minuten?",a:30,unit:"Minuten",hint:"Eine der längsten unter Landsäugern.",emoji:"🦏"},
  {id:"tsex_019",q:"Wie viele Penisse haben Schlangen?",a:2,unit:"Hemipenis",hint:"Schlangen haben zwei Hemipenes.",emoji:"🐍"},
  {id:"tsex_020",q:"Wie viele kg wiegt das Geschlechtsorgan eines Blauwals insgesamt?",a:520,unit:"kg",hint:"Hoden ~70kg + Penis ~450kg = ca. 520kg.",emoji:"🐋"},
  {id:"tsex_021",q:"Wie viele Tage brütet ein männlicher Kaiserpinguin auf dem Ei?",a:63,unit:"Tage",hint:"63 Tage – ohne Nahrung im antarktischen Winter.",emoji:"🐧"},
  {id:"tsex_022",q:"Wie viele Mal paart sich eine Drohnen-Biene in ihrem Leben?",a:1,unit:"Mal",hint:"Danach stirbt die Drohne.",emoji:"🐝"},
  {q:"Wie viele Spermien enthält ein Pferde-Ejakulat?",a:8000000000,hint:"8 Milliarden Spermien.",unit:"Spermien",emoji:"🐴"},
  {id:"tsex_023",q:"Wie lange dauert die Paarung bei Haien in Minuten?",a:30,unit:"Minuten",hint:"Minuten – mit Bissen als Vorzeichen.",emoji:"🦈"},
  {id:"tsex_024",q:"Wie viele cm lang ist der Penis eines Schimpansen?",a:8,unit:"cm",hint:"Größer als beim Gorilla.",emoji:"🐒"},
  {id:"tsex_025",q:"Wie viele Eier legt eine Riesenschildkröte pro Saison?",a:200,unit:"Eier",hint:"Mehrmals pro Jahr.",emoji:"🐢"},
  {id:"tsex_026",q:"Wie lange paaren sich Feldheuschrecken am Stück?",a:12,unit:"Stunden",hint:"Manchmal tagelang verbunden.",emoji:"🦗"},
  {id:"tsex_027",q:"Wie viele Zentimeter lang ist der Penis eines Pottwal?",a:240,unit:"cm",hint:"Zweitlängster Tierpenis nach dem Blauwal.",emoji:"🐳"},
  {id:"tsex_028",q:"Wie lange trägt ein Hund sein Junges in Tagen?",a:63,unit:"Tage",hint:"Tage Tragezeit.",emoji:"🐕"},
  {id:"tsex_029",q:"Wie viele Eier legt eine Schildkröte pro Gelege?",a:100,unit:"Eier",hint:"Je nach Art 50-200.",emoji:"🐢"},
  {id:"tsex_030",q:"Wie lange dauert die Paarung bei Spinnen?",a:60,unit:"Minuten",hint:"Manchmal bis zu mehreren Stunden.",emoji:"🕷️"},
  {q:"Wie viele Spermien enthält ein Bullensamen in der Tierzucht (pro Portion)?",a:10000000,hint:"10 Millionen pro Besamungsdosis.",unit:"Spermien",emoji:"🐂"},
  {id:"tsex_031",q:"Wie viele cm lang ist die Vagina einer Pferdes?",a:60,unit:"cm",hint:"Stuten haben eine sehr lange Vagina.",emoji:"🐴"},
  {id:"tsex_032",q:"Wie lange dauert die Trächtigkeit einer Katze in Wochen?",a:9,unit:"Wochen",hint:"63-67 Tage.",emoji:"🐱"},
  {id:"tsex_033",q:"Wie viele Weibchen befruchtet ein Stier pro Jahr in der Tierzucht?",a:50000,unit:"Weibchen",hint:"Durch künstliche Besamung.",emoji:"🐂"},
  {id:"tsex_034",q:"Wie lange dauert die Trächtigkeit einer Maus in Tagen?",a:21,unit:"Tage",hint:"Drei Wochen – und kann sofort wieder trächtig werden.",emoji:"🐭"},
  {id:"tsex_035",q:"Wie viele Junge wirft eine Maus pro Jahr?",a:70,unit:"Jungtiere",hint:"5-10 Würfe à 5-10 Jungen.",emoji:"🐭"},
  {id:"tsex_036",q:"Wie viele Mal können Kaninchen in einer Stunde paaren?",a:10,unit:"Mal",hint:"'Schnell wie Kaninchen' – wörtlich gemeint.",emoji:"🐇"},
  {id:"tsex_037",q:"Wie lang ist der Geschlechtsakt bei Hunden in Minuten?",a:20,unit:"Minuten",hint:"'Tie' – sie stecken zusammen.",emoji:"🐕"},
  {id:"tsex_038",q:"Wie viele Tausend Eier legt ein Oktopus-Weibchen?",a:400,unit:"Tausend Eier",hint:"400.000 Eier und bewacht sie bis zum Tod.",emoji:"🐙"},
  {id:"tsex_039",q:"Wie viele cm lang ist der Penis eines Elefanten?",a:180,unit:"cm",hint:"1,8 Meter – S-förmig und muskelstark.",emoji:"🐘"},
  {id:"tsex_040",q:"Wie lange dauert die Paarung bei Walen in Minuten?",a:18,unit:"Minuten",hint:"20 Minuten – im Meer.",emoji:"🐋"},
  {id:"tsex_041",q:"Wie viele Ovulation pro Jahr hat eine Katze?",a:4,unit:"Mal",hint:"Katzen sind saisonale Mehrfachläufer.",emoji:"🐱"},
  {id:"tsex_042",q:"Wie viele Junge kann ein Opossum gleichzeitig tragen?",a:20,unit:"Junge",hint:"Im Beutel – alle gleichzeitig.",emoji:"🐀"},
  {id:"tsex_043",q:"Wie lange trägt ein Elefant sein Junges in Monaten?",a:21,unit:"Monate",hint:"Fast 2 Jahre.",emoji:"🐘"},
  {id:"tsex_044",q:"Wie viele cm lang ist der Penis eines Delfins?",a:38,unit:"cm",hint:"Delfine haben prehensile Penisse.",emoji:"🐬"},
  {id:"tsex_045",q:"Wie lange dauert die Paarung von Flusspferden in Minuten?",a:10,unit:"Minuten",hint:"Im Wasser.",emoji:"🦛"},
  {q:"Wie viele Spermien hat ein Elefanten-Ejakulat?",a:50000000000,hint:"50 Milliarden Spermien.",unit:"Spermien",emoji:"🐘"},
  {id:"tsex_046",q:"Wie viele Junge hat ein Wombat pro Jahr?",a:1,unit:"Junges",hint:"Nur ein Junges – sehr langsame Fortpflanzung.",emoji:"🐨"},
  {id:"tsex_047",q:"Wie lange paaren sich Pferde in Minuten?",a:1,unit:"Minute",hint:"Kurz aber intensiv.",emoji:"🐴"},
  {id:"tsex_048",q:"Wie viele Weibchen besucht ein Gorilla-Silberrücken?",a:10,unit:"Weibchen",hint:"Ein Silberrücken führt eine Gruppe.",emoji:"🦍"},
  {id:"tsex_049",q:"Wie lange trägt ein Känguru sein Junges im Beutel in Monaten?",a:9,unit:"Monate",hint:"Erst 1cm groß bei Geburt – dann im Beutel.",emoji:"🦘"},
  {q:"Wie viele Spermien enthält ein Hunde-Ejakulat?",a:500000000,hint:"500 Millionen.",unit:"Spermien",emoji:"🐕"},
  {id:"tsex_050",q:"Wie viele Sekunden dauert die Paarung einer Drohnen-Biene mit der Königin?",a:5,unit:"Sekunden",hint:"Nur Sekunden – dann stirbt die Drohne.",emoji:"🐝"},
  {id:"tsex_051",q:"Wie viele Eier legt ein Schmetterlings-Weibchen insgesamt?",a:200,unit:"Eier",hint:"Meist Hunderte verteilt auf viele Pflanzen.",emoji:"🦋"},
  {id:"tsex_052",q:"Wie viele cm lang ist der Penis einer Seekuh (Manatee)?",a:70,unit:"cm",hint:"Auch Seekühe haben beeindruckende Organe.",emoji:"🐟"},
  {id:"tsex_053",q:"Wie lange dauert die Trächtigkeit eines Pottwal in Monaten?",a:16,unit:"Monate",hint:"Fast 1,5 Jahre.",emoji:"🐳"},
  {id:"tsex_054",q:"Wie viele Junge wirft eine Katze pro Wurf?",a:5,unit:"Junge",hint:"Durchschnittlich 3-7 Kätzchen.",emoji:"🐱"},
  {id:"tsex_055",q:"Wie viele Male paart sich eine Königin-Ameise in ihrem Leben?",a:1,unit:"Mal",hint:"Einmal – dann lagert sie Spermien für Jahre.",emoji:"🐜"},
  {id:"tsex_056",q:"Wie viele cm lang ist der Penis einer Maus?",a:1.5,unit:"cm",hint:"Relativ zu ihrem Körper sehr groß.",emoji:"🐭"},
  {id:"tsex_057",q:"Wie lange paaren sich Grizzlybären?",a:30,unit:"Minuten",hint:"Der Akt dauert bis zu 30 Minuten.",emoji:"🐻"},
  {id:"tsex_058",q:"Wie viele Tausend Eier legt ein Flussbarsch-Weibchen?",a:300,unit:"Tausend Eier",hint:"Fische legen enorme Eiermengen.",emoji:"🐟"},
  {id:"tsex_059",q:"Wie viele cm ist die Klitoris einer Weibchen-Fossa (Madagaskar)?",a:7,unit:"cm",hint:"Die Fossa hat einen außergewöhnlich langen Klitoris.",emoji:"🦁"},
  {id:"tsex_060",q:"Wie lange dauert der Hochzeitsflug einer Bienenkönigin?",a:1,unit:"Stunde",hint:"Sie paart sich in der Luft mit 12-20 Drohnen.",emoji:"🐝"},
  {q:"Wie viele Spermien eines Bocks (Ziege) sind in einem Ejakulat?",a:3000000000,hint:"3 Milliarden.",unit:"Spermien",emoji:"🐐"},
  {id:"tsex_061",q:"Wie viele Tage ist eine Hündin im Jahr läufig?",a:18,unit:"Tage",hint:"Zweimal im Jahr je 9 Tage.",emoji:"🐕"},
  {id:"tsex_062",q:"Wie viele cm lang ist der Penis eines Nilpferds?",a:50,unit:"cm",hint:"Nilpferde spritzen Urin zur Territorialmarkierung.",emoji:"🦛"},
  {id:"tsex_063",q:"Wie lange paaren sich Pandas?",a:3,unit:"Minuten",hint:"Sehr kurz – und sehr selten.",emoji:"🐼"},
  {id:"tsex_064",q:"Wie viele Junge hat ein Schwein pro Wurf?",a:10,unit:"Ferkel",hint:"8-14 Ferkel pro Wurf.",emoji:"🐷"},
  {id:"tsex_065",q:"Wie viele Eier legt eine Meeresschildkröte pro Saison insgesamt?",a:600,unit:"Eier",hint:"3-7 Gelege à 80-120 Eier.",emoji:"🐢"},
  {id:"tsex_066",q:"Wie viele cm lang ist der Penis eines Seelöwen?",a:40,unit:"cm",hint:"Pinnipeds haben sehr lange Penisse.",emoji:"🦭"},
  {id:"tsex_067",q:"Wie lange dauert die Trächtigkeit eines Schimpansen in Tagen?",a:243,unit:"Tage",hint:"Ähnlich wie beim Menschen.",emoji:"🐒"},
  {id:"tsex_068",q:"Wie viele Weibchen befruchtet ein Alpha-Wolf im Jahr?",a:1,unit:"Weibchen",hint:"Wölfe sind weitgehend monogam.",emoji:"🐺"},
  {q:"Wie viele Spermien enthält ein Rammler-Ejakulat?",a:400000000,hint:"400 Millionen.",unit:"Spermien",emoji:"🐇"},
  {id:"tsex_069",q:"Wie viele cm lang ist der Penis eines Walrosses?",a:63,unit:"cm",hint:"Walrosse haben auch einen Baculum (Penisknochen).",emoji:"🦭"},
  {id:"tsex_070",q:"Wie lange dauert die Paarung bei Krokodilen in Minuten?",a:10,unit:"Minuten",hint:"Im Wasser.",emoji:"🐊"},
  {id:"tsex_071",q:"Wie viele Junge hat ein Polarfuchs pro Wurf?",a:8,unit:"Junge",hint:"Bis zu 14 Junge.",emoji:"🦊"},
  {id:"tsex_072",q:"Wie viele Eier legt eine Hummel-Königin pro Sommer?",a:200,unit:"Eier",hint:"Nur eine Saison.",emoji:"🐝"},
  {id:"tsex_073",q:"Wie viele Mal pro Tag paart sich ein Kaninchen?",a:10,unit:"Mal",hint:"'Sich fortpflanzen wie Kaninchen' ist kein Mythos.",emoji:"🐇"},
  {id:"tsex_074",q:"Wie lange trägt eine Hündin in Wochen?",a:9,unit:"Wochen",hint:"63 Tage.",emoji:"🐕"},
  {id:"tsex_075",q:"Wie viele Eier legt eine Kohlmeise pro Gelege?",a:10,unit:"Eier",hint:"Bis zu 15 Eier pro Brut.",emoji:"🐦"},
  {id:"tsex_076",q:"Wie viele cm lang ist der Penisknochen eines Waschbären?",a:10,unit:"cm",hint:"Waschbären haben einen des größten Bacula relativ zum Körper.",emoji:"🦝"},
  {id:"tsex_077",q:"Wie viele Stunden dauert die Paarung von Schnecken?",a:6,unit:"Stunden",hint:"Schnecken sind Hermaphroditen.",emoji:"🐌"},
  {id:"tsex_078",q:"Wie viele Gramm wiegen beide Gorilla-Hoden zusammen?",a:30,unit:"Gramm",hint:"Im Vergleich zum 170kg-Körper sehr klein.",emoji:"🦍"},
  {id:"tsex_079",q:"Wie viele Eier legt eine Seidenspinne pro Kokon?",a:400,unit:"Eier",hint:"Alle im selben Seidensack.",emoji:"🕷️"},
  {id:"tsex_080",q:"Wie lange paaren sich Fliegen in Minuten?",a:20,unit:"Minuten",hint:"Stubenfliegen paaren sich relativ lange.",emoji:"🪰"},
  {id:"tsex_081",q:"Wie viele cm lang ist der Penis eines Schwertwals (Orca)?",a:180,unit:"cm",hint:"1,8 Meter – einfahrbarer Penis.",emoji:"🐋"},
  {id:"tsex_082",q:"Wie viele Junge hat ein Leopard pro Wurf?",a:2,unit:"Junge",hint:"1-4, meist 2-3 Jungtiere.",emoji:"🐆"},
  {id:"tsex_083",q:"Wie lange dauert die Trächtigkeit einer Tigerin in Tagen?",a:103,unit:"Tage",hint:"Knapp 3,5 Monate.",emoji:"🐯"},
  {q:"Wie viele Spermien enthält ein Stieglitz-Ejakulat?",a:100000000,hint:"100 Millionen – Vögel sparen.",unit:"Spermien",emoji:"🐦"},
  {id:"tsex_084",q:"Wie lang ist der Penis eines Wiedehopfs relativ zum Körper?",a:50,unit:"% Körperlänge",hint:"Sehr lang relativ zum Vogelkörper.",emoji:"🐦"},
  {id:"tsex_085",q:"Wie viele cm lang ist der Eileiter einer Kuh?",a:25,unit:"cm",hint:"Verbindet Ovar mit Gebärmutter.",emoji:"🐄"},
  {id:"tsex_086",q:"Wie lange dauert die Paarung von Albatrosse in Stunden?",a:1,unit:"Stunde",hint:"Albatrosse sind monogam und zeremoniell.",emoji:"🦅"},
  {id:"tsex_087",q:"Wie viele Junge hat eine Fledermaus pro Jahr?",a:1,unit:"Junges",hint:"Meist nur ein Jungtier.",emoji:"🦇"},
  {q:"Wie viele Spermien enthält das Ejakulat eines Elefantenseeohrs?",a:100000000000,hint:"100 Milliarden.",unit:"Spermien",emoji:"🦭"},
  {id:"tsex_088",q:"Wie lang paaren sich Löwen bei jedem Akt in Sekunden?",a:30,unit:"Sekunden",hint:"Kurz aber häufig – bis zu 20x täglich.",emoji:"🦁"},
  {id:"tsex_089",q:"Wie viele cm hat der Penisknochen eines Eichhörnchens?",a:2,unit:"cm",hint:"Klein aber funktional.",emoji:"🐿️"},
  {id:"tsex_090",q:"Wie lange dauert die Paarung von Schlangen in Stunden?",a:6,unit:"Stunden",hint:"Manchmal tage- und wochenlang.",emoji:"🐍"},
  {id:"tsex_091",q:"Wie viele Eier legt eine Ameisen-Königin täglich?",a:800,unit:"Eier",hint:"Über ihr gesamtes Leben Millionen.",emoji:"🐜"},
  {id:"tsex_092",q:"Wie viele cm lang ist der Penis eines Orang-Utans?",a:4,unit:"cm",hint:"Ähnlich klein wie Gorillas.",emoji:"🦧"},
  {id:"tsex_093",q:"Wie lange dauert die Trächtigkeit eines Hamsters in Tagen?",a:16,unit:"Tage",hint:"Kürzeste Tragzeit der Säugetiere.",emoji:"🐹"},
  {id:"tsex_094",q:"Wie viele Junge hat eine Ratte pro Wurf?",a:8,unit:"Junge",hint:"5-12 – bis zu 8 Würfe pro Jahr.",emoji:"🐀"},
  {id:"tsex_095",q:"Wie lang ist der Penis eines Hausschweins in cm?",a:50,unit:"cm",hint:"Korkenzieherförmig.",emoji:"🐷"},
  {id:"tsex_096",q:"Wie viele Eier legt eine Spinne insgesamt in ihrem Leben?",a:3000,unit:"Eier",hint:"Je nach Art hunderte bis tausende.",emoji:"🕷️"},
  {id:"tsex_097",q:"Wie viele cm lang ist der Uterus einer Katze?",a:10,unit:"cm",hint:"Zweizipfelig – kann verschiedene Väter tragen.",emoji:"🐱"},
  {q:"Wie viele Spermien enthält ein Fasan-Ejakulat?",a:2000000000,hint:"2 Milliarden.",unit:"Spermien",emoji:"🐦"},
  {id:"tsex_098",q:"Wie lange trägt eine Giraffe ihr Junges in Monaten?",a:15,unit:"Monate",hint:"Das Jungtier fällt 2m auf den Boden.",emoji:"🦒"},
  {id:"tsex_099",q:"Wie viele Junge hat ein Gepard pro Wurf?",a:3,unit:"Junge",hint:"1-8 – meist 3-5.",emoji:"🐆"},
  {id:"tsex_100",q:"Wie lange paaren sich Delfine?",a:12,unit:"Sekunden",hint:"Sehr kurz – dafür häufiger.",emoji:"🐬"},
  {id:"tsex_101",q:"Wie viele Eier legt ein Frosch pro Saison?",a:2000,unit:"Eier",hint:"Frösche legen Tausende kleiner Eier.",emoji:"🐸"},
  {id:"tsex_102",q:"Wie viele cm lang ist der Penisknochen eines Eisbären?",a:22,unit:"cm",hint:"Eines der längsten Bacula relativ zur Körpergröße.",emoji:"🐻‍❄️"},
  {id:"tsex_103",q:"Wie lange dauert die Trächtigkeit eines Gorillas in Tagen?",a:257,unit:"Tage",hint:"Ähnlich wie beim Menschen.",emoji:"🦍"},
  {q:"Wie viele Spermien hat ein Schaf-Ejakulat?",a:3000000000,hint:"3 Milliarden.",unit:"Spermien",emoji:"🐑"},
  {id:"tsex_104",q:"Wie viele Junge hat eine Löwin pro Wurf?",a:3,unit:"Junge",hint:"1-4, meist 2-3.",emoji:"🦁"},
  {id:"tsex_105",q:"Wie lange paaren sich Tigerfrösche?",a:2,unit:"Tage",hint:"Amplexus – Umarmung kann Tage dauern.",emoji:"🐸"},
  {id:"tsex_106",q:"Wie viele Eier legt eine Wespenkönig pro Sommer?",a:300,unit:"Eier",hint:"Arbeiterinnen bauen das Nest für sie.",emoji:"🐝"},
  {id:"tsex_107",q:"Wie lange trägt ein Kaninchen sein Junges in Tagen?",a:31,unit:"Tage",hint:"Sehr kurze Tragzeit.",emoji:"🐇"},
  {id:"tsex_108",q:"Wie viele Junge hat ein Polarfuchs maximal pro Wurf?",a:14,unit:"Junge",hint:"Bei guter Lemmingversorgung.",emoji:"🦊"},
  {id:"tsex_109",q:"Wie viele cm lang ist der Penis eines Tapirs?",a:60,unit:"cm",hint:"Tapire haben einen Greif-Penis.",emoji:"🦏"},
  {id:"tsex_110",q:"Wie lange paaren sich Marder?",a:2,unit:"Stunden",hint:"Mehrere Stunden – lange Paarung.",emoji:"🦦"},
  {id:"tsex_111",q:"Wie viele Eier legt eine Seidenraupe?",a:500,unit:"Eier",hint:"Pro Weibchen im Leben.",emoji:"🪱"},
  {id:"tsex_112",q:"Wie lang ist der Penisknochen eines Bibers?",a:5,unit:"cm",hint:"Biber haben einen Baculum.",emoji:"🦦"},
  {id:"tsex_113",q:"Wie lange trägt eine Stute ihr Junges in Tagen?",a:340,unit:"Tage",hint:"Ca. 11 Monate.",emoji:"🐴"},
  {id:"tsex_114",q:"Wie viele Junge hat eine Hyäne pro Wurf?",a:2,unit:"Junge",hint:"Manchmal 1-3.",emoji:"🐈"},
  {id:"tsex_115",q:"Wie lang ist der Penis eines Flussdelphins?",a:40,unit:"cm",hint:"Amazonas-Delphin.",emoji:"🐬"},
  {q:"Wie viele Spermien enthält ein Eber-Ejakulat?",a:50000000000,hint:"50 Milliarden – größtes Ejakulatvolumen.",unit:"Spermien",emoji:"🐷"},
  {id:"tsex_116",q:"Wie lange paaren sich Schildkröten in Stunden?",a:3,unit:"Stunden",hint:"Sehr ausdauernd.",emoji:"🐢"},
  {id:"tsex_117",q:"Wie viele Junge bekommt ein Schimpansen-Weibchen in ihrem Leben?",a:5,unit:"Junge",hint:"Schimpansen haben wenige Nachkommen – alle 4-5 Jahre ein Junges.",emoji:"🐒"},
  {id:"tsex_118",q:"Wie lang ist der Uterus einer Stute?",a:45,unit:"cm",hint:"Groß genug für das Fohlen.",emoji:"🐴"},
  {id:"tsex_119",q:"Wie viele Junge hat ein Wildschwein pro Wurf?",a:6,unit:"Frischlinge",hint:"4-8 – je nach Nahrungsangebot.",emoji:"🐗"},
  {id:"tsex_120",q:"Wie lang ist der Penis eines Zwergschimpansen (Bonobo)?",a:10,unit:"cm",hint:"Größer als Gorilla, kleiner als Mensch.",emoji:"🐒"},
  {id:"tsex_121",q:"Wie viele Eier legt eine Forelle pro Laichsaison?",a:2000,unit:"Eier",hint:"Je nach Größe bis 10.000.",emoji:"🐟"},
  {id:"tsex_122",q:"Wie lange trägt ein Löwe sein Junges in Tagen?",a:110,unit:"Tage",hint:"Löwen führen Einzel-Würfe.",emoji:"🦁"},
  {id:"tsex_123",q:"Wie viele Junge hat ein Erdferkel pro Jahr?",a:1,unit:"Junges",hint:"Nur ein Jungtier pro Saison.",emoji:"🐷"},
  {id:"tsex_124",q:"Wie lang ist die Vagina einer Gorilla in cm?",a:9,unit:"cm",hint:"Proportional kleiner als beim Menschen.",emoji:"🦍"},
  {q:"Wie viele Spermien enthält ein Kaninchen-Ejakulat?",a:400000000,hint:"400 Millionen.",unit:"Spermien",emoji:"🐇"},
  {id:"tsex_125",q:"Wie lange paaren sich Polarfüchse?",a:20,unit:"Minuten",hint:"In der kurzen arktischen Paarungszeit.",emoji:"🦊"},
  {id:"tsex_126",q:"Wie viele Tausend Eier legt ein Oktopus insgesamt?",a:100,unit:"Tausend Eier",hint:"Und bewacht sie bis sie schlüpfen – dann stirbt sie.",emoji:"🐙"},
  {id:"tsex_127",q:"Wie lang ist der Penisknochen eines Hundes (Baculum)?",a:10,unit:"cm",hint:"Hunde haben einen Penisknochen.",emoji:"🐕"},
  {id:"tsex_128",q:"Wie viele Junge hat ein Leopard im Leben?",a:8,unit:"Junge",hint:"Alle 2 Jahre ein Wurf über 16 Jahre.",emoji:"🐆"},
  {id:"tsex_129",q:"Wie lang ist die Klitoris einer Weibchen-Binturong?",a:5,unit:"cm",hint:"Binturongs sind bekannt für diese Eigenschaft.",emoji:"🐱"},
  {q:"Wie viele Spermien enthält ein Hamster-Ejakulat?",a:200000000,hint:"200 Millionen.",unit:"Spermien",emoji:"🐹"},
  {id:"tsex_130",q:"Wie lange trägt eine Ratte ihr Junges in Tagen?",a:22,unit:"Tage",hint:"Sehr kurze Tragzeit.",emoji:"🐀"},
  {id:"tsex_131",q:"Wie viele Eier legt eine Schmetterlingsgattung täglich?",a:20,unit:"Eier",hint:"Über ihr ganzes Leben meist 200.",emoji:"🦋"},
  {id:"tsex_132",q:"Wie lang ist der Rüssel eines Elefanten – auch als Sinnesorgan beim Paaren?",a:200,unit:"cm",hint:"Elefanten berühren sich beim Paaren mit dem Rüssel.",emoji:"🐘"},
  {id:"tsex_133",q:"Wie viele Junge hat ein Waschbär pro Wurf?",a:4,unit:"Junge",hint:"3-5 Junge im Frühling.",emoji:"🦝"},
  {id:"tsex_134",q:"Wie lange dauert die Paarung bei Löffelenten?",a:2,unit:"Minuten",hint:"Enten sind bekannt für erzwungene Kopulationen – evolutionäres Rüstungswettrennen.",emoji:"🦆"},
  {q:"Wie viele Spermien kann ein einziger Eber in einem Tag produzieren?",a:50000000000,hint:"50 Milliarden täglich.",unit:"Spermien",emoji:"🐷"},
  {id:"tsex_135",q:"Wie lang ist der Penis eines Bullen in cm?",a:90,unit:"cm",hint:"Retraktormuskel ermöglicht S-förmige Lagerung.",emoji:"🐂"},
  {id:"tsex_136",q:"Wie viele Eier legt eine Stubenfliege in ihrem kurzen Leben?",a:500,unit:"Eier",hint:"In Gruppen von 75-150 Stück.",emoji:"🪰"},
  {id:"tsex_137",q:"Wie viele Tage ist eine Stute im Jahr rossig?",a:15,unit:"Tage",hint:"Mehrmals im Sommer.",emoji:"🐴"},
  {id:"tsex_138",q:"Wie lang ist der Uterus einer Hauskatze in cm?",a:8,unit:"cm",hint:"Zweihörnig – kann verschiedene Väter haben.",emoji:"🐱"},
  {id:"tsex_139",q:"Wie viele Junge hat ein Opossum gleichzeitig im Beutel?",a:13,unit:"Junge",hint:"Zitzen – so viele Junge können überleben.",emoji:"🐀"},
  {id:"tsex_140",q:"Wie lange dauert die Paarung von Orcas?",a:5,unit:"Minuten",hint:"Im Wasser – sehr selten beobachtet.",emoji:"🐋"},
  {q:"Wie viele Spermien enthält ein Ziegenbock-Ejakulat?",a:3000000000,hint:"3 Milliarden.",unit:"Spermien",emoji:"🐐"},
  {id:"tsex_141",q:"Wie lang ist der Gebärmutterhals einer Kuh?",a:10,unit:"cm",hint:"Wichtig für künstliche Besamung.",emoji:"🐄"},
  {id:"tsex_142",q:"Wie viele Junge hat eine Fischotter pro Wurf?",a:3,unit:"Junge",hint:"1-5, meist 3.",emoji:"🦦"},
  {id:"tsex_143",q:"Wie lange paaren sich Geparden?",a:10,unit:"Minuten",hint:"Mehrmals täglich in der Paarungszeit.",emoji:"🐆"},
  {id:"tsex_144",q:"Wie viele Eier legt eine Gottesanbeterin nach der Paarung?",a:200,unit:"Eier",hint:"In einem Oothek-Kokon.",emoji:"🦗"},
  {id:"tsex_145",q:"Wie lang ist der Penisknochen einer Robbe (Baculum) in cm?",a:35,unit:"cm",hint:"Robbenmänner haben sehr lange Bacula.",emoji:"🦭"},
  {q:"Wie viele Spermien hat ein Kater-Ejakulat?",a:50000000,hint:"50 Millionen.",unit:"Spermien",emoji:"🐱"},
  {id:"tsex_146",q:"Wie lange trägt eine Kojote ihr Junges in Tagen?",a:63,unit:"Tage",hint:"Gleich wie Hunde.",emoji:"🐺"},
  {id:"tsex_147",q:"Wie viele Junge hat ein Nashorn pro Wurf?",a:1,unit:"Junges",hint:"Immer Einzelgeburten.",emoji:"🦏"},
  {id:"tsex_148",q:"Wie viele Eier legt ein Walhai pro Saison?",a:300,unit:"Eier",hint:"Walhaie sind lebendgebärend – aber legen Eier vor der Geburt.",emoji:"🦈"},
  {id:"tsex_149",q:"Wie lange paaren sich Hauskatzen?",a:5,unit:"Minuten",hint:"Mehrmals täglich – sehr laut.",emoji:"🐱"},
  {q:"Wie viele Spermien enthält ein Schafbock-Ejakulat?",a:3000000000,hint:"3 Milliarden.",unit:"Spermien",emoji:"🐑"},
  {id:"tsex_150",q:"Wie viele Junge hat ein Hermelin pro Wurf?",a:6,unit:"Junge",hint:"4-9 Junge.",emoji:"🦦"},
  {id:"tsex_151",q:"Wie viele Eier legt eine Zauneidechse pro Saison?",a:8,unit:"Eier",hint:"6-12 Eier.",emoji:"🦎"},
  {id:"tsex_152",q:"Wie lange dauert die Trächtigkeit eines Schafes in Tagen?",a:147,unit:"Tage",hint:"Etwa 5 Monate.",emoji:"🐑"},
  {id:"tsex_153",q:"Wie viele Junge hat ein Eisbär pro Wurf?",a:2,unit:"Junge",hint:"Fast immer Zwillinge.",emoji:"🐻‍❄️"},
  {id:"tsex_154",q:"Wie lang ist der Penis eines Hauskatze (Kater)?",a:1.5,unit:"cm",hint:"Sehr klein mit stacheligen Widerhaken.",emoji:"🐱"},
  {q:"Wie viele Spermien enthält ein Fischotter-Ejakulat?",a:300000000,hint:"300 Millionen.",unit:"Spermien",emoji:"🦦"},
  {id:"tsex_155",q:"Wie lange paaren sich Wildschweine?",a:5,unit:"Minuten",hint:"Schnell aber häufig.",emoji:"🐗"},
  {id:"tsex_156",q:"Wie viele Eier legt eine Hornisse pro Sommer?",a:500,unit:"Eier",hint:"Die Königin allein.",emoji:"🐝"},
  {id:"tsex_157",q:"Wie lang ist der Uterus einer Menschenaffen-Weibchen?",a:8,unit:"cm",hint:"Ähnlich wie bei uns.",emoji:"🦍"},
  {id:"tsex_158",q:"Wie viele Junge hat ein Braunbär pro Wurf?",a:2,unit:"Junge",hint:"1-4, meist 2.",emoji:"🐻"},
  {q:"Wie viele Spermien enthält ein Eberejakulat pro ml?",a:200000000,hint:"200 Millionen/ml – Gesamtvolumen bis 500ml.",unit:"Spermien/ml",emoji:"🐷"},
];
