// 🔥 KÖRPER & BIOLOGIE – Erwachsene – 250 Fragen
export default [
  {id:"koerp_001",q:"Wie viele Liter Speichel produziert ein Mensch pro Tag?",a:1.5,unit:"Liter",hint:"Speichel hilft bei der Verdauung und schützt Zähne vor Bakterien.",emoji:"💧"},
  {id:"koerp_002",q:"Wie viele Mal schlägt das menschliche Herz pro Tag?",a:100000,unit:"Mal",hint:"70 Schläge/min × 60 × 24 = ca. 100.000 Mal täglich.",emoji:"❤️"},
  {id:"koerp_003",q:"Wie lang sind alle Blutgefäße eines Menschen zusammen in km?",a:100000,unit:"km",hint:"100.000 km – das entspricht 2,5× dem Erdumfang.",emoji:"🩸"},
  {id:"koerp_004",q:"Wie viele Haare verliert ein Mensch durchschnittlich pro Tag?",a:100,unit:"Haare",hint:"Ein gesunder Kopf hat ~100.000 Haare – der Verlust ist normal.",emoji:"💈"},
  {id:"koerp_005",q:"Wie viele Knochen hat ein neugeborenes Baby?",a:270,unit:"Knochen",hint:"Erwachsene haben nur 206 – viele Knochen wachsen zusammen.",emoji:"🦴"},
  {id:"koerp_006",q:"Wie viele m² Oberfläche hat die menschliche Lunge?",a:70,unit:"m²",hint:"Das entspricht etwa der Größe eines Tennisplatzes.",emoji:"🫁"},
  {id:"koerp_007",q:"Wie viele km Nerven hat ein Mensch im Körper?",a:75,unit:"km",hint:"Nervensignale können mit bis zu 400 km/h übertragen werden.",emoji:"⚡"},
  {id:"koerp_008",q:"Wie viel Prozent des Körpergewichts macht Blut aus?",a:8,unit:"%",hint:"Bei 75 kg sind das etwa 6 Liter Blut.",emoji:"🩸"},
  {id:"koerp_009",q:"Wie viele Milliarden Bakterien leben auf der Haut eines Menschen?",a:1800,unit:"Milliarden",hint:"1.800 Milliarden = 1,8 Billionen – die meisten sind harmlos.",emoji:"🦠"},
  {id:"koerp_010",q:"Wie viele Liter Blut pumpt das Herz pro Minute in Ruhe?",a:5,unit:"Liter",hint:"Bei Belastung kann es bis zu 25 Liter pro Minute sein.",emoji:"❤️"},
  {id:"koerp_011",q:"Wie viele Millionen Eizellen hat eine Frau bei der Geburt?",a:1,unit:"Millionen Eizellen",hint:"Bis zur Pubertät sind es nur noch ca. 300.000.",emoji:"🔬"},
  {id:"koerp_012",q:"Wie viele Millionen Spermien produziert ein Mann pro Tag?",a:300,unit:"Millionen",hint:"Das sind ~1500 neue Spermien pro Sekunde.",emoji:"🔬"},
  {id:"koerp_013",q:"Wie lang ist der Dünndarm eines Erwachsenen in Metern?",a:6,unit:"Meter",hint:"Zusammen mit dem Dickdarm ergibt das über 8 Meter Darm.",emoji:"🌀"},
  {id:"koerp_014",q:"Wie viel Kilogramm wiegt das menschliche Gehirn?",a:1.4,unit:"Kilogramm",hint:"Trotz 2% Körpergewicht verbraucht es 20% unserer Energie.",emoji:"🧠"},
  {id:"koerp_015",q:"Wie viele Liter Luft atmet ein Mensch pro Tag ein?",a:11000,unit:"Liter",hint:"15 Atemzüge/min × 0,5L × 60 × 24 = ~10.800L täglich.",emoji:"💨"},
  {id:"koerp_016",q:"Wie viele Stunden verbringt ein Mensch pro Jahr auf der Toilette?",a:92,unit:"Stunden",hint:"Im Leben summiert sich das auf fast 3 Jahre.",emoji:"🚽"},
  {id:"koerp_017",q:"Wie viele Liter fasst der Magen eines Erwachsenen maximal?",a:1.5,unit:"Liter",hint:"Im leeren Zustand hat er nur etwa 75 ml Volumen.",emoji:"🫃"},
  {id:"koerp_018",q:"Wie oft blinzelt ein Mensch pro Minute?",a:15,unit:"Mal",hint:"Das macht über 10.000 Mal pro Tag.",emoji:"👁️"},
  {id:"koerp_019",q:"Wie schnell wachsen Fingernägel pro Monat in mm?",a:3,unit:"mm",hint:"Fußnägel wachsen etwa halb so schnell.",emoji:"💅"},
  {id:"koerp_020",q:"Wie viel Prozent des Körpers besteht aus Wasser?",a:60,unit:"%",hint:"Beim Baby sind es 75%, im Alter sinkt der Wasseranteil.",emoji:"💧"},
  {id:"koerp_021",q:"Wie viele Muskeln braucht man zum Lächeln?",a:12,unit:"Muskeln",hint:"Zum Stirnrunzeln braucht man angeblich mehr.",emoji:"😁"},
  {id:"koerp_022",q:"Wie lang ist die DNA in einer einzigen Zelle in Metern?",a:2,unit:"Meter",hint:"2m × 37 Billionen Zellen = ~17× die Strecke Erde-Sonne.",emoji:"🧬"},
  {id:"koerp_023",q:"Wie viele Liter Magensäure produziert der Magen täglich?",a:1.5,unit:"Liter",hint:"Der pH-Wert liegt bei 1-2 – ähnlich wie Batteriesäure.",emoji:"⚗️"},
  {id:"koerp_024",q:"Wie viele Kalorien verbrennt das Gehirn pro Tag?",a:300,unit:"kcal",hint:"Das sind 20% des gesamten Kalorienverbrauchs in Ruhe.",emoji:"🧠"},
  {id:"koerp_025",q:"Wie viele Millionen Schweißdrüsen hat ein Mensch am ganzen Körper?",a:3,unit:"Millionen Drüsen",hint:"Am dichtesten sitzen sie an Fußsohlen und Handflächen.",emoji:"💦"},
  {id:"koerp_026",q:"Wie lang ist der längste Muskel im Körper (Sartorius) in cm?",a:60,unit:"cm",hint:"Er verbindet Hüfte und Knie diagonal (Stand ~2024).",emoji:"🦵"},
  {id:"koerp_027",q:"Wie viele Gramm wiegt eine durchschnittliche weibliche Brust?",a:500,unit:"Gramm",hint:"Der Fettanteil variiert stark je nach Körbchengröße.",emoji:"👙"},
  {id:"koerp_028",q:"Wie viele Liter Blut pumpt das Herz pro Tag?",a:7200,unit:"Liter",hint:"Das Herz schlägt ~100.000 Mal täglich.",emoji:"❤️"},
  {id:"koerp_029",q:"Wie viele Millionen Zellen sterben im Körper pro Sekunde ab?",a:3.8,unit:"Millionen Zellen/s",hint:"Gleichzeitig werden ständig neue Zellen gebildet.",emoji:"🔬"},
  {id:"koerp_030",q:"Wie viele km Sehnen und Bänder hat ein Mensch im Körper?",a:9,unit:"km",hint:"Etwa 9km – Sehnen verbinden Muskeln mit Knochen, Bänder Knochen mit Knochen.",emoji:"🦴"},
  {id:"koerp_031",q:"Wie viele Milliliter Sperma enthält eine durchschnittliche Ejakulation?",a:3.5,unit:"ml",hint:"Darin befinden sich 15-200 Millionen Spermien pro ml.",emoji:"💦"},
  {id:"koerp_032",q:"Wie viele Zentimeter ist die durchschnittliche erigierte Penisgröße?",a:13.1,unit:"cm",hint:"Laut einer Metastudie mit über 15.000 Männern weltweit.",emoji:"📏"},
  {id:"koerp_033",q:"Wie viele Orgasmen kann eine Frau theoretisch in einer Stunde haben?",a:10,unit:"Orgasmen",hint:"Frauen sind multorgasmusfähig – Studien berichten bis zu 10+ in einer Stunde.",emoji:"🌊"},
  {id:"koerp_034",q:"Wie viele Stunden im Leben verbringt ein Mensch durchschnittlich mit Sex?",a:520,unit:"Stunden",hint:"Das sind etwa 21 ganze Tage im Leben.",emoji:"❤️"},
  {id:"koerp_035",q:"Wie lange dauert der durchschnittliche Geschlechtsakt in Minuten?",a:5.4,unit:"Minuten",hint:"Laut einer internationalen Studie aus 2005.",emoji:"⏱️"},
  {id:"koerp_036",q:"Wie viele Kalorien verbrennt man beim Sex pro Stunde?",a:200,unit:"kcal",hint:"Etwa so viel wie ein leichtes Jogging.",emoji:"🔥"},
  {id:"koerp_037",q:"Wie lang ist der Klitoris tatsächlich in cm (gesamte innere Struktur)?",a:10,unit:"cm",hint:"Nur die Eichel ist sichtbar – der Rest liegt innen.",emoji:"🔬"},
  {id:"koerp_038",q:"Wie viele Nervenendigungen hat die Klitoris?",a:8000,unit:"Nervenenden",hint:"Doppelt so viele wie der Penis – konzentriert auf kleinstem Raum.",emoji:"⚡"},
  {id:"koerp_039",q:"Wie viele Liter Blut fließen während einer Erektion in den Penis?",a:0.13,unit:"Liter",hint:"Das entspricht etwa 130 ml – das Blut füllt die Schwellkörper.",emoji:"🩸"},
  {id:"koerp_040",q:"Wie viele Mal ejakuliert ein Mann durchschnittlich in seinem Leben?",a:7200,unit:"Mal",hint:"Das entspricht etwa einmal täglich von 20-40 Jahren.",emoji:"📊"},
  {id:"koerp_041",q:"Wie viele Gramm wiegen beide Hoden zusammen?",a:40,unit:"Gramm",hint:"Jeder Hoden wiegt etwa 20 Gramm.",emoji:"⚖️"},
  {id:"koerp_042",q:"Wie lange kann ein Spermium im weiblichen Körper überleben in Tagen?",a:5,unit:"Tage",hint:"Manche Spermien überleben sogar bis zu einer Woche.",emoji:"🔬"},
  {id:"koerp_043",q:"Wie viele Liter Blut hat ein durchschnittlicher Erwachsener?",a:5.5,unit:"Liter",hint:"Frauen haben etwas weniger als Männer.",emoji:"🩸"},
  {id:"koerp_044",q:"Wie viele Milliarden Mal schlägt das Herz in 70 Jahren?",a:2.5,unit:"Milliarden",hint:"2,5 Milliarden Schläge – ohne Pause ein Leben lang.",emoji:"❤️"},
  {id:"koerp_045",q:"Wie viele cm muss ein Spermium vom Ejakulationsort bis zur Eizelle zurücklegen?",a:17,unit:"cm",hint:"Für das Spermium entspricht das Tausenden von Kilometern in menschlicher Größe.",emoji:"🏊"},
  {id:"koerp_046",q:"Wie viel Prozent des Körperfetts befindet sich unter der Haut?",a:80,unit:"%",hint:"Der Rest sitzt um die Organe (viszerales Fett).",emoji:"📊"},
  {id:"koerp_047",q:"Wie viele Milliliter Urin kann die Blase maximal fassen?",a:600,unit:"ml",hint:"Harndrang spürt man ab etwa 150-250 ml.",emoji:"💛"},
  {id:"koerp_048",q:"Wie viele Gramm Protein braucht ein 80-kg-Mensch täglich laut DGE?",a:64,unit:"Gramm",hint:"Die Empfehlung liegt bei 0,8g pro kg Körpergewicht.",emoji:"💪"},
  {id:"koerp_049",q:"Wie viele Jahre seines Lebens schläft ein Mensch durchschnittlich?",a:26,unit:"Jahre",hint:"Bei 8h/Nacht × 70 Jahre = ca. 26 Jahre Schlaf.",emoji:"😴"},
  {id:"koerp_050",q:"Wie viele Meter legen die Augen pro Tag durch Augenbewegungen zurück?",a:800,unit:"Meter",hint:"Sakkaden und Folgebewegungen zusammen: ca. 800m pro Tag.",emoji:"👀"},
  {id:"koerp_051",q:"Wie viele Liter Tränenflüssigkeit produzieren die Augen pro Jahr?",a:5.5,unit:"Liter",hint:"Auch wenn man nicht weint – die Augen werden ständig befeuchtet.",emoji:"😢"},
  {id:"koerp_052",q:"Wie groß ist die Oberfläche der Haut eines Erwachsenen in m²?",a:1.8,unit:"m²",hint:"Die Haut ist das größte Organ des menschlichen Körpers.",emoji:"🧑"},
  {id:"koerp_053",q:"Wie viele Millionen Haare hat ein Mensch auf dem gesamten Körper?",a:5,unit:"Millionen Haare",hint:"Nur auf dem Kopf sind es ca. 100.000.",emoji:"💇"},
  {id:"koerp_054",q:"Wie viele Liter Blut fließen täglich durch die Nieren?",a:1800,unit:"Liter",hint:"Die Nieren filtern das gesamte Blut ca. 300 Mal täglich.",emoji:"🫘"},
  {id:"koerp_055",q:"Wie lange dauert die Verdauung vom Essen bis zur Ausscheidung in Stunden?",a:24,unit:"Stunden",hint:"Je nach Mahlzeit kann es 12-72 Stunden dauern.",emoji:"⏰"},
  {id:"koerp_056",q:"Wie viele Gramm wiegt das menschliche Herz?",a:300,unit:"Gramm",hint:"Etwa so schwer wie eine große Orange.",emoji:"❤️"},
  {id:"koerp_057",q:"Wie viele mm dicke ist die menschliche Haut durchschnittlich?",a:2,unit:"mm",hint:"An den Fußsohlen ist sie mit 4mm am dicksten.",emoji:"🧑"},
  {id:"koerp_058",q:"Wie viele km/h fließt das Blut in der Aorta?",a:4,unit:"km/h",hint:"Ca. 4-5 km/h in der Aorta – in Kapillaren nur 0,5 mm/s.",emoji:"🩸"},
  {id:"koerp_059",q:"Wie viele Zähne hat ein Erwachsener (mit Weisheitszähnen)?",a:32,unit:"Zähne",hint:"Ohne Weisheitszähne sind es nur 28.",emoji:"🦷"},
  {id:"koerp_060",q:"Wie viele Milliliter Luft atmet man pro Atemzug in Ruhe ein?",a:500,unit:"ml",hint:"Das ist das sogenannte Atemzugvolumen.",emoji:"💨"},
  {id:"koerp_061",q:"Wie viel Prozent der Körperwärme verliert man über den Kopf?",a:10,unit:"%",hint:"Der Mythos sagt 50% – stimmt aber nicht.",emoji:"🌡️"},
  {id:"koerp_062",q:"Wie viele Gramm Fett verbrennt man im Schlaf pro Nacht?",a:70,unit:"Gramm",hint:"Der Körper verbrennt auch im Schlaf ca. 300-400 kcal.",emoji:"😴"},
  {id:"koerp_063",q:"Wie viele Millionen Rezeptoren hat die menschliche Nase?",a:10,unit:"Millionen",hint:"Wir können bis zu 1 Billion verschiedene Gerüche unterscheiden.",emoji:"👃"},
  {id:"koerp_064",q:"Wie viele Tonnen Nahrung verarbeitet der Magen in einem Leben?",a:30,unit:"Tonnen",hint:"Das entspricht dem Gewicht von etwa 5 Elefanten.",emoji:"🍽️"},
  {id:"koerp_065",q:"Wie lang ist der Dickdarm in cm?",a:150,unit:"cm",hint:"Trotz kürzerer Länge hat er einen größeren Durchmesser als der Dünndarm.",emoji:"🌀"},
  {id:"koerp_066",q:"Wie viele Knochen hat ein Erwachsener im Fuß?",a:26,unit:"Knochen",hint:"Ein Viertel aller Knochen im Körper befinden sich in den Füßen.",emoji:"🦶"},
  {id:"koerp_067",q:"Wie viele Mal pro Sekunde können Muskelfasern zucken?",a:100,unit:"Mal",hint:"Schnelle Muskelfasern (Fast-Twitch) für explosive Bewegungen.",emoji:"💪"},
  {id:"koerp_068",q:"Wie viele ml Blut pumpt das Herz pro Schlag?",a:70,unit:"ml",hint:"Das nennt man Schlagvolumen – in Ruhe etwa 70 ml.",emoji:"❤️"},
  {id:"koerp_069",q:"Wie schwer ist die menschliche Leber in Kilogramm?",a:1.5,unit:"Kilogramm",hint:"Die Leber ist das schwerste innere Organ.",emoji:"🟤"},
  {id:"koerp_070",q:"Wie viele Liter Lymphe produziert der Körper täglich?",a:2,unit:"Liter",hint:"Die Lymphe transportiert Abwehrzellen im Körper.",emoji:"💛"},
  {id:"koerp_071",q:"Wie viele Wochen dauert es bis sich die äußere Hautschicht erneuert hat?",a:3,unit:"Wochen",hint:"Alle 2-4 Wochen – neue Zellen schieben die alten nach oben.",emoji:"✨"},
  {id:"koerp_072",q:"Wie viele Grad Celsius beträgt die normale Körpertemperatur?",a:37,unit:"°C",hint:"Ab 38°C spricht man von Fieber.",emoji:"🌡️"},
  {id:"koerp_073",q:"Wie viele Minuten überlebt das Gehirn ohne Sauerstoff?",a:5,unit:"Minuten",hint:"Nach 5 Minuten beginnen irreversible Schäden.",emoji:"🧠"},
  {id:"koerp_074",q:"Wie viele Milliliter Blut verliert eine Frau durchschnittlich pro Periode?",a:50,unit:"ml",hint:"Obwohl es mehr wirkt – im Schnitt sind es 30-80 ml.",emoji:"🩸"},
  {id:"koerp_075",q:"Wie lang ist die durchschnittliche Schlafdauer eines Erwachsenen in Stunden?",a:7,unit:"Stunden",hint:"Schlafmangel erhöht das Risiko für Herzerkrankungen.",emoji:"😴"},
  {id:"koerp_076",q:"Wie viele Gramm Zucker hat das Gehirn täglich als Mindestbedarf?",a:120,unit:"Gramm",hint:"Das Gehirn ist der größte Glukoseverbraucher im Körper.",emoji:"🧠"},
  {id:"koerp_077",q:"Wie viele km/h kann ein Nervensignal im Körper übertragen werden?",a:400,unit:"km/h",hint:"Schnelle motorische Nervenfasern leiten besonders schnell.",emoji:"⚡"},
  {id:"koerp_078",q:"Wie viele Mal im Leben wechselt ein Mensch seine Hautzellen komplett?",a:1000,unit:"Mal",hint:"Die Haut erneuert sich alle 2-4 Wochen.",emoji:"✨"},
  {id:"koerp_079",q:"Wie viele Liter beträgt das Gesamtvolumen beider Lungen zusammen?",a:6,unit:"Liter",hint:"Die Totalkapazität beider Lungen zusammen.",emoji:"🫁"},
  {id:"koerp_080",q:"Wie lang ist der Dünndarm eines Erwachsenen wirklich (entfaltet) in Metern?",a:6,unit:"Meter",hint:"Zusammengefaltet passt er in den Bauchraum.",emoji:"🌀"},
  {id:"koerp_081",q:"Wie viele Milliarden Neuronen hat das menschliche Gehirn?",a:86,unit:"Milliarden Neuronen",hint:"86 Milliarden Neuronen – mit Billionen von Verbindungen.",emoji:"🧠"},
  {id:"koerp_082",q:"Wie viele Gramm wiegt die Milz?",a:150,unit:"Gramm",hint:"Die Milz filtert das Blut und speichert Blutzellen.",emoji:"🔴"},
  {id:"koerp_083",q:"Wie viele Liter Blut filtert die Niere pro Tag?",a:180,unit:"Liter",hint:"Daraus entstehen nur etwa 1,5 Liter Urin.",emoji:"🫘"},
  {id:"koerp_084",q:"Wie viele cm wächst ein Mensch im Schlaf durch Bandscheibenerholung?",a:1,unit:"cm",hint:"Morgens ist man bis zu 1 cm größer als abends.",emoji:"📏"},
  {id:"koerp_085",q:"Wie viele Liter Salzsäure produziert der Magen täglich?",a:1.5,unit:"Liter",hint:"Genug um Metall aufzulösen – die Magenschleimhaut schützt uns.",emoji:"⚗️"},
  {id:"koerp_086",q:"Wie viele Minuten braucht das Blut für einen kompletten Kreislauf?",a:1,unit:"Minute",hint:"In einer Minute fließt das Blut einmal durch den ganzen Körper.",emoji:"🔄"},
  {id:"koerp_087",q:"Wie viele m² Oberfläche hat der Dünndarm durch Zotten und Falten?",a:200,unit:"m²",hint:"Mehr als ein Tennisplatz – für maximale Nährstoffaufnahme.",emoji:"🌀"},
  {id:"koerp_088",q:"Wie viele Gramm Gehirnmasse verliert man pro Jahr nach dem 30. Lebensjahr?",a:1.9,unit:"Gramm",hint:"Das Gehirn schrumpft im Alter leicht.",emoji:"🧠"},
  {id:"koerp_089",q:"Wie viele Tausend Liter Speichel produziert ein Mensch in seinem Leben?",a:37,unit:"Tausend Liter",hint:"37.000 Liter – genug um zwei Swimmingpools zu füllen.",emoji:"💧"},
  {id:"koerp_090",q:"Wie viele Knochen haben beide Hände zusammen?",a:54,unit:"Knochen",hint:"27 Knochen pro Hand – ein Viertel aller Körperknochen.",emoji:"🖐️"},
  {id:"koerp_091",q:"Wie viele Mal schlägt das Herz während eines 90-minütigen Films?",a:6300,unit:"Mal",hint:"90 Minuten × 70 Schläge/min = 6.300 Schläge.",emoji:"🎬"},
  {id:"koerp_092",q:"Wie lang ist die Speiseröhre in cm?",a:25,unit:"cm",hint:"Sie verbindet Mund und Magen durch die Brust.",emoji:"🫁"},
  {id:"koerp_093",q:"Wie viele Gramm wiegt eine menschliche Niere?",a:150,unit:"Gramm",hint:"Beide Nieren wiegen zusammen etwa 300g.",emoji:"🫘"},
  {id:"koerp_094",q:"Wie viele Dezibel kann das menschliche Ohr maximal wahrnehmen?",a:140,unit:"Dezibel",hint:"Ab 85 dB dauerhaft beginnen Hörschäden.",emoji:"👂"},
  {id:"koerp_095",q:"Wie viele Bilder pro Sekunde verarbeitet das menschliche Auge?",a:60,unit:"Bilder/s",hint:"Manche Menschen sehen sogar bis zu 200 fps.",emoji:"👁️"},
  {id:"koerp_096",q:"Wie viele Gramm Zucker enthält der menschliche Körper?",a:70,unit:"Gramm",hint:"Davon befinden sich ~5g als Glukose im Blut.",emoji:"🍭"},
  {id:"koerp_097",q:"Wie viele Millionen Mal atmet ein Mensch in seinem Leben?",a:700,unit:"Millionen Mal",hint:"Ca. 15-20 Atemzüge/Minute × 60 × 24 × 365 × 70 Jahre.",emoji:"💨"},
  {id:"koerp_098",q:"Wie viele Stunden pro Tag ist der Mund-Rachen-Raum mit Schleim bedeckt?",a:24,unit:"Stunden",hint:"Der Körper produziert ständig Schleim zur Selbstreinigung.",emoji:"😷"},
  {id:"koerp_099",q:"Wie viele Gramm Wasser verliert man durch Atmen pro Tag?",a:400,unit:"Gramm",hint:"Deshalb kondensiert Atem bei Kälte.",emoji:"💨"},
  {id:"koerp_100",q:"Wie lang ist der Penis im Durchschnitt nicht erigiert in cm?",a:9,unit:"cm",hint:"Die durchschnittliche Penislänge schlaff liegt bei 7-10 cm.",emoji:"📏"},
  {id:"koerp_101",q:"Wie viele Mikrometer breit ist der Spermium-Kopf?",a:5,unit:"Mikrometer",hint:"Kopf: 5μm breit, 55μm lang gesamt – extrem klein.",emoji:"🔬"},
  {id:"koerp_102",q:"Wie viele Milliliter Sekret produzieren Bartholin-Drüsen beim Sex?",a:2,unit:"ml",hint:"Diese Drüsen produzieren natürliche Gleitmittel.",emoji:"💧"},
  {id:"koerp_103",q:"Wie lange kann eine Eizelle nach dem Eisprung befruchtet werden in Stunden?",a:24,unit:"Stunden",hint:"Im Gegensatz zu Spermien die 5 Tage überleben.",emoji:"⏰"},
  {id:"koerp_104",q:"Wie viele Mal pro Jahr hat ein Deutscher durchschnittlich Sex?",a:98,unit:"Mal",hint:"Laut einer repräsentativen Umfrage aus 2019.",emoji:"❤️"},
  {id:"koerp_105",q:"Wie hoch ist der Testosteronspiegel eines Mannes morgens im Vergleich zum Abend in %?",a:25,unit:"% höher",hint:"Der Testosteronspiegel folgt einem Tagesrhythmus.",emoji:"📈"},
  {id:"koerp_106",q:"Wie viele Kilogramm wiegt ein neugeborenes Baby durchschnittlich?",a:3.4,unit:"Kilogramm",hint:"Normal sind 2500-4000g.",emoji:"👶"},
  {id:"koerp_107",q:"Wie lang ist die Nabelschnur bei einem Neugeborenen durchschnittlich in cm?",a:55,unit:"cm",hint:"Sie kann zwischen 20 und 100 cm lang sein.",emoji:"🍼"},
  {id:"koerp_108",q:"Wie viele Tausend Eizellen hat ein Mädchen bei der Pubertät noch?",a:300,unit:"Tausend",hint:"Von 1 Million bei der Geburt bleiben ~300.000 übrig.",emoji:"🔬"},
  {id:"koerp_109",q:"Wie viele Organe hat der menschliche Körper insgesamt?",a:78,unit:"Organe",hint:"Je nach Definition werden 78 Organe gezählt.",emoji:"🫀"},
  {id:"koerp_110",q:"Wie lang dauert die durchschnittliche menschliche Schwangerschaft in Tagen?",a:280,unit:"Tage",hint:"Das entspricht 40 Wochen oder 9 Monaten.",emoji:"🤰"},
  {id:"koerp_111",q:"Wie viele Kalorien verbrennt das Gehirn pro Stunde?",a:12,unit:"kcal",hint:"Das Gehirn läuft wie eine 20-Watt-Glühbirne.",emoji:"🧠"},
  {id:"koerp_112",q:"Wie viele Gramm wiegt die menschliche Zunge?",a:70,unit:"Gramm",hint:"Die Zunge besteht aus 8 ineinandergreifenden Muskeln.",emoji:"👅"},
  {id:"koerp_113",q:"Wie viele Rezeptoren hat die Zunge für Geschmack?",a:10000,unit:"Geschmacksknospen",hint:"Jede Geschmacksknospe hat 50-100 Sinneszellen.",emoji:"👅"},
  {id:"koerp_114",q:"Wie viel Prozent des täglichen Energiebedarfs verbraucht das Gehirn?",a:20,unit:"%",hint:"Obwohl es nur 2% des Körpergewichts ausmacht.",emoji:"🧠"},
  {id:"koerp_115",q:"Wie viele Milligramm Keratin produziert der Körper täglich?",a:500,unit:"Milligramm",hint:"Keratin ist der Hauptbestandteil von Haaren und Nägeln.",emoji:"💅"},
  {id:"koerp_116",q:"Wie viele Liter Blut verliert eine Frau durchschnittlich während der Geburt?",a:0.5,unit:"Liter",hint:"Bei Kaiserschnitt kann es mehr sein.",emoji:"🩸"},
  {id:"koerp_117",q:"Wie viele Millionen Schmerzrezeptoren hat die menschliche Haut?",a:3.5,unit:"Millionen",hint:"Schmerz ist ein wichtiges Warnsignal des Körpers.",emoji:"😣"},
  {id:"koerp_118",q:"Wie lang wächst ein Fingernagel in einem Jahr in cm?",a:3.6,unit:"cm",hint:"Circa 3mm pro Monat.",emoji:"💅"},
  {id:"koerp_119",q:"Wie viele Stunden Musik hört man im Durchschnitt pro Jahr?",a:730,unit:"Stunden",hint:"Das entspricht 2 Stunden täglich.",emoji:"🎵"},
  {id:"koerp_120",q:"Wie viele ml Sperma enthält eine Ejakulation durchschnittlich?",a:3.5,unit:"ml",hint:"Davon sind 90% Wasser, Proteine und Fruchtzucker.",emoji:"💧"},
  {id:"koerp_121",q:"Wie viel Prozent des Körpers macht Fettgewebe bei einem normalgewichtigen Mann aus?",a:18,unit:"%",hint:"Bei Frauen sind es gesunde 25%.",emoji:"📊"},
  {id:"koerp_122",q:"Wie viele Stunden verbringt ein Mensch durchschnittlich mit Küssen im Leben?",a:336,unit:"Stunden",hint:"Ca. 2 Wochen – etwa 30 Sekunden pro Tag über 70 Jahre.",emoji:"💋"},
  {id:"koerp_123",q:"Wie viele Gramm Eisen hat ein erwachsener Körper?",a:4,unit:"Gramm",hint:"Genug um einen kleinen Nagel herzustellen.",emoji:"⚙️"},
  {id:"koerp_124",q:"Wie viele Kilogramm Calcium enthält der menschliche Körper?",a:1,unit:"Kilogramm",hint:"99% davon befinden sich in Knochen und Zähnen.",emoji:"🦷"},
  {id:"koerp_125",q:"Wie lange dauert die Pubertät bei Mädchen durchschnittlich in Jahren?",a:5,unit:"Jahre",hint:"Bei Jungen dauert sie etwas länger.",emoji:"👧"},
  {id:"koerp_126",q:"Wie viele Milliliter Ohrenschmalz produziert das Ohr pro Monat?",a:1,unit:"ml",hint:"Ohrenschmalz schützt den Gehörgang.",emoji:"👂"},
  {id:"koerp_127",q:"Wie viele Liter Schweiß kann ein Mensch bei Hitze pro Stunde verlieren?",a:2,unit:"Liter",hint:"Bei extremer Hitze und körperlicher Anstrengung.",emoji:"💦"},
  {id:"koerp_128",q:"Wie viele Mal schlägt das Herz beim Orgasmus pro Minute?",a:150,unit:"Schläge/min",hint:"Das Herz pumpt beim Höhepunkt deutlich schneller.",emoji:"❤️"},
  {id:"koerp_129",q:"Wie viele Dezibel ist ein typischer menschlicher Schrei?",a:85,unit:"Dezibel",hint:"Laute Schreie können 100 dB oder mehr erreichen.",emoji:"😱"},
  {id:"koerp_130",q:"Wie viele Gramm wiegen die Augen eines Erwachsenen zusammen?",a:14,unit:"Gramm",hint:"Jedes Auge wiegt ca. 7 Gramm.",emoji:"👁️"},
  {id:"koerp_131",q:"Wie viele Milligramm Testosteron produziert ein Mann täglich?",a:7,unit:"Milligramm",hint:"Milligramm – eine winzige Menge mit großer Wirkung.",emoji:"⚗️"},
  {id:"koerp_132",q:"Wie viele Mal hat ein Mann durchschnittlich pro Nacht eine Erektion im Schlaf?",a:4,unit:"Mal",hint:"3-5 nächtliche Erektionen, je 20-30 Min – normaler REM-Schlaf.",emoji:"📊"},
  {id:"koerp_133",q:"Wie viele Millionen Liter Blut pumpt das Herz in einem 70-jährigen Leben?",a:184,unit:"Millionen Liter",hint:"Ca. 184 Mio. Liter – genug für 73 olympische Schwimmbecken.",emoji:"❤️"},
  {id:"koerp_134",q:"Wie viele Kilogramm Haut wirft ein Mensch in seinem Leben ab?",a:48,unit:"kg",hint:"Die Haut erneuert sich alle 2-4 Wochen komplett.",emoji:"✨"},
  {id:"koerp_135",q:"Wie hoch ist die durchschnittliche Körpertemperatur im Rektum in °C?",a:37.5,unit:"°C",hint:"Die rektale Temperatur ist etwas höher als die Mundtemperatur.",emoji:"🌡️"},
  {id:"koerp_136",q:"Wie viele Gramm wiegt die Bauchspeicheldrüse?",a:85,unit:"Gramm",hint:"Sie produziert Insulin und Verdauungsenzyme.",emoji:"🟡"},
  {id:"koerp_137",q:"Wie viele cm² hat die Oberfläche der Cornea (Hornhaut) des Auges?",a:1,unit:"cm²",hint:"Die Hornhaut ist das einzige Körpergewebe ohne Blutgefäße.",emoji:"👁️"},
  {id:"koerp_138",q:"Wie viele Mikrometer dick ist ein menschliches Haar?",a:70,unit:"Mikrometer",hint:"Blondes Haar ist oft dünner als dunkles.",emoji:"💇"},
  {id:"koerp_139",q:"Wie viele Mal pro Nacht hat ein gesunder Mann eine Erektion im Schlaf?",a:4,unit:"Mal",hint:"Diese nächtlichen Erektionen dauern je 20-30 Minuten.",emoji:"😴"},
  {id:"koerp_140",q:"Wie viele Hz beträgt die obere Hörgrenze des menschlichen Ohres?",a:20000,unit:"Hz",hint:"Das ist die obere Grenze des menschlichen Hörvermögens.",emoji:"👂"},
  {id:"koerp_141",q:"Wie lange dauert es, bis Alkohol vollständig aus dem Blut abgebaut ist (0,5 Promille)?",a:5,unit:"Stunden",hint:"Der Körper baut ca. 0,1 Promille pro Stunde ab.",emoji:"🍺"},
  {id:"koerp_142",q:"Wie viele Liter Sperma produziert ein Mann in seinem Leben?",a:25,unit:"Liter",hint:"3,5ml × ~7.200 Ejakulationen = ca. 25 Liter im Leben.",emoji:"📊"},
  {id:"koerp_143",q:"Wie lang ist die Vagina in cm (nicht erregt)?",a:9,unit:"cm",hint:"Erregt dehnt sie sich auf bis zu 12-15 cm aus.",emoji:"📏"},
  {id:"koerp_144",q:"Wie viele ml Vaginalflüssigkeit produziert eine Frau pro Tag?",a:2,unit:"ml",hint:"Natürliche Selbstreinigung des Körpers.",emoji:"💧"},
  {id:"koerp_145",q:"Wie viele Minuten braucht ein Spermium von der Ejakulation bis zur Eizelle?",a:45,unit:"Minuten",hint:"Die schnellsten schaffen es in unter 30 Minuten.",emoji:"🏊"},
  {id:"koerp_146",q:"Wie viele cm ist der G-Punkt von der Vaginalöffnung entfernt?",a:5,unit:"cm",hint:"An der vorderen Vaginalwand gelegen.",emoji:"📏"},
  {q:"Wie viele Stunden im Leben verbringt ein Mensch mit dem Ausscheiden?",a:19000,hint:"Das sind über 2 Jahre auf der Toilette.",unit:"Stunden",emoji:"🚽"},
  {id:"koerp_147",q:"Wie viele Liter fasst ein Kondom maximal?",a:18,unit:"Liter",hint:"Kondoms können bis zu 18 Liter Wasser fassen – vor dem Platzen.",emoji:"💧"},
  {id:"koerp_148",q:"Wie viele kg Nahrung isst ein Mensch in seinem Leben?",a:35000,unit:"kg",hint:"Das entspricht dem Gewicht von 7 Elefanten.",emoji:"🍽️"},
  {id:"koerp_149",q:"Wie viele Millionen Mal blinzelt ein Mensch in seinem Leben?",a:450,unit:"Millionen Mal",hint:"15 Mal pro Minute × 16 Wachstunden × 365 Tage × 70 Jahre.",emoji:"👁️"},
  {id:"koerp_150",q:"Wie viele Grad Celsius kann die Körpertemperatur beim Sport maximal steigen?",a:40,unit:"°C",hint:"Ab 42°C wird es lebensgefährlich.",emoji:"🌡️"},
  {id:"koerp_151",q:"Wie viele Milligramm Haare verliert ein Mensch täglich?",a:10,unit:"Milligramm",hint:"100 Haare × ca. 0,1mg = ~10mg täglich.",emoji:"💇"},
  {id:"koerp_152",q:"Wie viele ml Flüssigkeit enthält ein frisch gesetzter Knochenbruch?",a:500,unit:"ml",hint:"Der Körper reagiert mit Entzündung und Flüssigkeitseinlagerung.",emoji:"🦴"},
  {id:"koerp_153",q:"Wie viele Kilometer legt das Blut in einem Jahr in Gefäßen zurück?",a:96000,unit:"km",hint:"96.000 km – entspricht 2,4× dem Erdumfang (40.000 km).",emoji:"🩸"},
  {id:"koerp_154",q:"Wie lang ist die Harnröhre beim Mann in cm?",a:20,unit:"cm",hint:"Bei der Frau ist sie nur 4 cm lang.",emoji:"📏"},
  {q:"Wie viele Stunden im Leben verbringt ein Mensch beim Schminken (Frauen)?",a:3276,hint:"Etwa 45 Minuten täglich über 20 Jahre.",unit:"Stunden",emoji:"💄"},
  {id:"koerp_155",q:"Wie viele Gramm wiegt der Blinddarm?",a:7,unit:"Gramm",hint:"Der Blinddarm hat noch keine vollständig geklärte Funktion.",emoji:"🔴"},
  {id:"koerp_156",q:"Wie viele Tonnen Nahrung verarbeitet der Magen in einem 70-jährigen Leben?",a:30,unit:"Tonnen",hint:"Das sind ~430 kg pro Jahr.",emoji:"🍽️"},
  {id:"koerp_157",q:"Wie viele Kilometer lang sind alle Kapillaren im Körper zusammen?",a:100000,unit:"km",hint:"Kapillaren sind die kleinsten Blutgefäße.",emoji:"🩸"},
  {id:"koerp_158",q:"Wie viele Minuten hält ein trainierter Freitaucher die Luft an?",a:10,unit:"Minuten",hint:"Geübte schaffen 8-15 Min – Weltrekord mit O₂-Vorbereitung: 24 Min (2016).",emoji:"💨"},
  {id:"koerp_159",q:"Wie viele Gramm Glykogen speichert die Leber?",a:100,unit:"Gramm",hint:"Zusätzlich speichern die Muskeln weitere 400g.",emoji:"🟤"},
  {id:"koerp_160",q:"Wie viele Mal schlägt das Herz eines Embryos pro Minute?",a:160,unit:"Schläge/min",hint:"Im Mutterleib schlägt das Herz deutlich schneller.",emoji:"❤️"},
  {id:"koerp_161",q:"Wie viele mg Melatonin produziert die Zirbeldrüse pro Nacht?",a:0.3,unit:"mg",hint:"Winzige Mengen steuern den Schlaf-Wach-Rhythmus.",emoji:"😴"},
  {id:"koerp_162",q:"Wie viele Liter Blut befinden sich in den Muskeln bei körperlicher Arbeit?",a:4,unit:"Liter",hint:"In Ruhe befinden sich nur 1 Liter in den Muskeln.",emoji:"💪"},
  {id:"koerp_163",q:"Wie viele cm ist der Gebärmutterhals vom äußeren Muttermund entfernt?",a:3,unit:"cm",hint:"Die Gebärmutter ist etwa 7 cm lang.",emoji:"🔬"},
  {id:"koerp_164",q:"Wie viele Neuronen stirbt man pro Tag ab dem 30. Lebensjahr?",a:100000,unit:"Neuronen",hint:"Das klingt viel – aber bei 86 Milliarden kaum spürbar.",emoji:"🧠"},
  {id:"koerp_165",q:"Wie viele Stunden im Leben verbringt man mit Lachen?",a:6400,unit:"Stunden",hint:"Ca. 15 Minuten täglich × 70 Jahre = ~6.400 Stunden.",emoji:"😂"},
  {id:"koerp_166",q:"Wie viele Milligramm Serotonin befinden sich im menschlichen Körper?",a:10,unit:"mg",hint:"90% des Serotonins befinden sich im Darm.",emoji:"😊"},
  {id:"koerp_167",q:"Wie lang dauert die durchschnittliche Refraktärzeit eines Mannes nach dem Orgasmus in Minuten?",a:30,unit:"Minuten",hint:"Bei jungen Männern kürzer, bei älteren länger.",emoji:"⏰"},
  {id:"koerp_168",q:"Wie viele Stunden täglich verbringt ein Durchschnittsmensch mit Essen?",a:1.5,unit:"Stunden",hint:"Im Jahr sind das über 500 Stunden.",emoji:"🍽️"},
  {id:"koerp_169",q:"Wie viele Kilogramm Sauerstoff atmet ein Mensch pro Jahr ein?",a:550,unit:"kg",hint:"Das entspricht ca. 1,5 kg täglich.",emoji:"💨"},
  {id:"koerp_170",q:"Wie viele Liter Fruchtwasser umgibt das Baby im Mutterleib?",a:1,unit:"Liter",hint:"Das Fruchtwasser wird ständig erneuert.",emoji:"💧"},
  {id:"koerp_171",q:"Wie viele Millionen Nervenzellen hat der menschliche Darm?",a:100,unit:"Millionen Neuronen",hint:"Das Darm-Nervensystem wird oft als 'zweites Gehirn' bezeichnet.",emoji:"🧠"},
  {id:"koerp_172",q:"Wie viele Kilometer legt ein Mensch in seinem Leben zu Fuß zurück?",a:160,unit:"Tausend km",hint:"Das entspricht 4 Mal um den Erdumfang.",emoji:"🚶"},
  {id:"koerp_173",q:"Wie viele Liter Schleim produzieren die Atemwege täglich?",a:1,unit:"Liter",hint:"1–1,5 Liter – fast alles wird unbemerkt geschluckt.",emoji:"🤧"},
  {id:"koerp_174",q:"Wie viele Mal pro Jahr träumt ein Mensch durchschnittlich?",a:1460,unit:"Träume",hint:"4 Träume pro Nacht × 365 Nächte.",emoji:"💭"},
  {id:"koerp_175",q:"Wie hoch ist die durchschnittliche Körperfettmenge einer normalgewichtigen Frau in kg?",a:18,unit:"kg",hint:"Bei Männern sind es gesunde 10-15 kg.",emoji:"📊"},
  {id:"koerp_176",q:"Wie viele Nanometer ist ein Spermium lang?",a:55000,unit:"Nanometer",hint:"Das entspricht 55 Mikrometern oder 0,055 mm.",emoji:"🔬"},
  {id:"koerp_177",q:"Wie viele cm ist die durchschnittliche Klitoris-Eichel groß?",a:1,unit:"cm",hint:"Obwohl klein, hat sie 8000 Nervenendigungen.",emoji:"📏"},
  {id:"koerp_178",q:"Wie viele Millionen Spermien enthält 1 Milliliter Ejakulat?",a:70,unit:"Millionen Spermien/ml",hint:"70 Millionen Spermien in einem einzigen Milliliter.",emoji:"🔬"},
  {id:"koerp_179",q:"Wie viele Jahre dauert es bis alle Zellen im Körper ausgetauscht wurden?",a:7,unit:"Jahre",hint:"Manche Zellen wie Nervenzellen halten ein Leben lang.",emoji:"🔄"},
  {id:"koerp_180",q:"Wie viele Gramm Phosphor enthält der menschliche Körper?",a:700,unit:"Gramm",hint:"Phosphor steckt vor allem in Knochen und DNA.",emoji:"⚗️"},
  {id:"koerp_181",q:"Wie viele Milliliter Mageninhalt würde ein leerer Magen beim Erbrechen entleeren?",a:75,unit:"ml",hint:"Ein leerer Magen hat nur 75 ml Volumen.",emoji:"🤢"},
  {id:"koerp_182",q:"Wie viele Kilometer laufen wir in einem Jahr bei normaler Alltagsaktivität?",a:2000,unit:"km",hint:"Bei 10.000 Schritten täglich à 0,75m.",emoji:"🚶"},
  {id:"koerp_183",q:"Wie viele Gramm Alkohol baut die Leber pro Stunde ab?",a:10,unit:"Gramm",hint:"Ca. 10g entspricht 0,1 Promille – unabhängig von der Trinkmenge.",emoji:"🍺"},
  {id:"koerp_184",q:"Wie viele Zellen hat der menschliche Körper insgesamt (Billionen)?",a:37,unit:"Billionen",hint:"Billionen menschliche Zellen – plus Milliarden Bakterien.",emoji:"🔬"},
  {id:"koerp_185",q:"Wie viele Gramm Fett produziert die Haut täglich als Schutzfilm?",a:10,unit:"Gramm",hint:"Talg hält die Haut geschmeidig und schützt vor Bakterien.",emoji:"✨"},
  {id:"koerp_186",q:"Wie viele Stunden pro Tag ist die Darmperistaltik aktiv?",a:24,unit:"Stunden",hint:"Der Darm arbeitet unaufhörlich auch im Schlaf.",emoji:"🌀"},
  {id:"koerp_187",q:"Wie viel Prozent der menschlichen DNA ist mit Schimpansen identisch?",a:98.7,unit:"%",hint:"Nur 1,3% machen den Unterschied zwischen Mensch und Schimpanse.",emoji:"🧬"},
  {id:"koerp_188",q:"Wie viele Gramm wiegt das Kleinhirn?",a:150,unit:"Gramm",hint:"Obwohl klein – es koordiniert alle Bewegungen.",emoji:"🧠"},
  {id:"koerp_189",q:"Wie viele Millionen Bakterien befinden sich in einem ml Speichel?",a:100,unit:"Millionen",hint:"Der Mund beherbergt über 700 verschiedene Bakterienarten.",emoji:"🦠"},
  {id:"koerp_190",q:"Wie lang ist der weibliche Menstruationszyklus durchschnittlich in Tagen?",a:28,unit:"Tage",hint:"Normale Zyklen dauern 21-35 Tage.",emoji:"🗓️"},
  {id:"koerp_191",q:"Wie viele Kilogramm Bindegewebe hat der menschliche Körper ungefähr?",a:15,unit:"Kilogramm",hint:"Bindegewebe macht etwa 20% der Körpermasse aus.",emoji:"💪"},
  {id:"koerp_192",q:"Wie viele Mal pro Minute atmet ein Neugeborenes?",a:40,unit:"Mal",hint:"Neugeborene atmen doppelt so schnell wie Erwachsene.",emoji:"👶"},
  {id:"koerp_193",q:"Wie viele Kalorien verbrennt ein Kuss pro Minute?",a:3,unit:"kcal",hint:"Leidenschaftliches Küssen kann bis zu 6 kcal/min verbrennen.",emoji:"💋"},
  {id:"koerp_194",q:"Wie viele Kilogramm Wasser enthält das menschliche Gehirn?",a:1.12,unit:"Kilogramm",hint:"Das Gehirn besteht zu 80% aus Wasser.",emoji:"🧠"},
  {id:"koerp_195",q:"Wie viele Dezibel ist ein Orgasmus laut gemessen?",a:70,unit:"Dezibel",hint:"Das entspricht dem Lärmpegel einer Hauptstraße.",emoji:"😱"},
  {id:"koerp_196",q:"Wie viele Millionen Bakterien überträgt man beim Küssen?",a:80,unit:"Millionen",hint:"Ein Kuss dauert 10 Sekunden und tauscht 80 Mio. Bakterien aus.",emoji:"💋"},
  {id:"koerp_197",q:"Wie viele Milligramm Protein enthält der durchschnittliche Ejakulationsschuss?",a:300,unit:"Milligramm",hint:"Sperma enthält Proteine, Fruchtzucker und Zink.",emoji:"💧"},
  {id:"koerp_198",q:"Wie lang dauert ein typischer REM-Schlafzyklus in Minuten?",a:90,unit:"Minuten",hint:"Wir durchlaufen 4-6 Schlafzyklen pro Nacht.",emoji:"😴"},
  {id:"koerp_199",q:"Wie viele Milligramm Zink enthält eine normale Ejakulation?",a:5,unit:"mg",hint:"Zink ist wichtig für die Spermienqualität.",emoji:"⚗️"},
  {id:"koerp_200",q:"Wie viele Grad Celsius hat das Innere des Hodens?",a:35,unit:"°C",hint:"Hoden brauchen 2°C weniger als Körpertemperatur für Spermienproduktion.",emoji:"🌡️"},
  {id:"koerp_201",q:"Wie viele Gramm wiegt die Plazenta nach der Geburt?",a:500,unit:"Gramm",hint:"Die Plazenta wird nach der Geburt als 'Nachgeburt' ausgestoßen.",emoji:"🤱"},
  {id:"koerp_202",q:"Wie viele ml Flüssigkeit verliert ein Mensch täglich über die Haut (ohne Schwitzen)?",a:600,unit:"ml",hint:"Transepidermaler Wasserverlust – unmerklich aber konstant.",emoji:"💧"},
  {id:"koerp_203",q:"Wie viele Milligramm Serotonin produziert der Darm täglich?",a:10,unit:"Milligramm",hint:"Mg täglich – der Darm ist die Hauptproduktionsstätte.",emoji:"😊"},
  {id:"koerp_204",q:"Wie viele Minuten pro Tag denkt ein Mensch an Sex (Männer)?",a:19,unit:"Minuten",hint:"Entgegen dem Mythos nicht alle 7 Sekunden.",emoji:"💭"},
  {id:"koerp_205",q:"Wie viele Gramm Kollagen produziert die Haut pro Jahr?",a:3,unit:"Gramm",hint:"Ab 25 nimmt die Kollagenproduktion jährlich ab.",emoji:"✨"},
  {id:"koerp_206",q:"Wie lange dauert ein Wimpernhaar bis es ausfällt in Monaten?",a:3,unit:"Monate",hint:"Wimpern haben einen kurzen Lebenszyklus.",emoji:"👁️"},
  {id:"koerp_207",q:"Wie viele Kilokalorien verbrennt man beim Orgasmus?",a:3,unit:"kcal",hint:"Weniger als ein Keks – aber deutlich mehr Spaß.",emoji:"🔥"},
  {id:"koerp_208",q:"Wie viele Liter Blut pumpt das Herz pro Minute bei sexueller Erregung?",a:10,unit:"Liter/min",hint:"In Ruhe 5L/min – bei Erregung verdoppelt es sich auf ~10L/min.",emoji:"❤️"},
  {id:"koerp_209",q:"Wie viele Zentimeter verlängert sich der Penis durchschnittlich bei der Erektion?",a:4,unit:"cm",hint:"Von ~9cm schlaff auf ~13cm erigiert.",emoji:"📏"},
  {id:"koerp_210",q:"Wie viele Millionen Menschen weltweit haben Gonorrhoe?",a:82,unit:"Millionen",hint:"Eine der häufigsten sexuell übertragbaren Erkrankungen.",emoji:"🔬"},
  {id:"koerp_211",q:"Wie viele Gramm wiegt ein Hoden durchschnittlich?",a:20,unit:"Gramm",hint:"Beide Hoden wiegen zusammen etwa 40 Gramm.",emoji:"⚖️"},
  {id:"koerp_212",q:"Wie viele Stunden pro Woche sind Jugendliche in der Pubertät beschäftigt mit sexuellen Gedanken?",a:2,unit:"Stunden",hint:"Weniger als viele denken – trotz Hormonflut.",emoji:"💭"},
  {id:"koerp_213",q:"Wie viele Milliliter Schleim produziert die Gebärmutter täglich?",a:4,unit:"ml",hint:"Zervixschleim ändert sich im Zyklus.",emoji:"💧"},
  {id:"koerp_214",q:"Wie lang ist der menschliche Gebärmutterhals in cm?",a:3,unit:"cm",hint:"Während der Geburt öffnet er sich auf 10cm.",emoji:"📏"},
  {id:"koerp_215",q:"Wie viele Kilogramm Fett hat ein durchschnittlicher Mensch im Körper?",a:15,unit:"kg",hint:"Bei Normalgewicht sind etwa 15-25% Körperfett normal.",emoji:"📊"},
  {id:"koerp_216",q:"Wie viele Sekunden dauert ein durchschnittlicher Niesanfall?",a:0.5,unit:"Sekunden",hint:"Niesen ist ein Reflex zum Reinigen der Atemwege.",emoji:"🤧"},
  {id:"koerp_217",q:"Wie viele km/h erreicht ein Nieser?",a:160,unit:"km/h",hint:"Schleim wird dabei bis zu 8 Meter weit geschleudert.",emoji:"🤧"},
  {id:"koerp_218",q:"Wie viele Stunden im Durchschnitt schläft ein Teenager täglich?",a:9,unit:"Stunden",hint:"Teenager brauchen mehr Schlaf als Erwachsene.",emoji:"😴"},
  {id:"koerp_219",q:"Wie viele Mal pro Jahr erkälten sich Kinder durchschnittlich?",a:8,unit:"Mal",hint:"Erwachsene nur 2-4 Mal.",emoji:"🤧"},
  {id:"koerp_220",q:"Wie viele Kilo wiegt das Skelett eines Erwachsenen?",a:10,unit:"kg",hint:"Das Skelett macht ca. 15% des Körpergewichts aus.",emoji:"🦴"},
  {id:"koerp_221",q:"Wie viele Millionen Zellen produziert der Körper pro Sekunde?",a:3.8,unit:"Millionen/Sekunde",hint:"3,8 Millionen neue Zellen pro Sekunde = 330 Milliarden täglich.",emoji:"🔬"},
  {id:"koerp_222",q:"Wie viele cm wächst Kopfhaar pro Monat?",a:1.25,unit:"cm",hint:"Etwa 15 cm pro Jahr.",emoji:"💇"},
  {id:"koerp_223",q:"Wie viele Gramm Salz scheidet die Niere täglich aus?",a:7,unit:"Gramm",hint:"Die tägliche Aufnahme sollte maximal 6g betragen.",emoji:"🧂"},
  {id:"koerp_224",q:"Wie viele Milliarden weiße Blutzellen hat ein gesunder Mensch?",a:37,unit:"Milliarden",hint:"Ca. 7.500/µl × 5L Blut = ~37 Milliarden gesamt.",emoji:"🩸"},
  {id:"koerp_225",q:"Wie viele Mikrometer Durchmesser hat eine rote Blutzelle?",a:8,unit:"Mikrometer",hint:"8 Mikrometer – 1000 nebeneinander wären 8mm.",emoji:"🔬"},
  {id:"koerp_226",q:"Wie viele Millisekunden dauert ein Wimpernschlag?",a:150,unit:"Millisekunden",hint:"0,15 Sekunden für einen kompletten Schlag.",emoji:"👁️"},
  {id:"koerp_227",q:"Wie viele Schritte gehen Forscher als optimale Tageszahl an?",a:7500,unit:"Schritte",hint:"Neuste Studien: 7.500 bringen optimalen Gesundheitseffekt.",emoji:"🚶"},
  {id:"koerp_228",q:"Wie viele Gramm Glycogen speichern die Muskeln insgesamt?",a:400,unit:"Gramm",hint:"Plus 100g in der Leber.",emoji:"💪"},
  {id:"koerp_229",q:"Wie viele Milligramm Melatonin nimmt man typischerweise als Schlafmittel?",a:0.5,unit:"mg",hint:"Niedrige Dosis ist oft effektiver als 10mg.",emoji:"😴"},
  {id:"koerp_230",q:"Wie viele Prozent der Gene teilt der Mensch mit einer Banane?",a:60,unit:"%",hint:"Gemeinsame Gene – überraschend viel.",emoji:"🍌"},
  {id:"koerp_231",q:"Wie viele ml Blut verliert eine Frau bei der Geburt?",a:500,unit:"ml",hint:"Normal 300-500ml – Kaiserschnitt mehr.",emoji:"🤱"},
  {id:"koerp_232",q:"Wie viele Gramm Kreatin speichert ein Muskel?",a:120,unit:"Gramm",hint:"Etwa 4g/kg Muskelgewebe.",emoji:"💪"},
  {id:"koerp_233",q:"Wie viele Zentimeter wächst ein Kind im ersten Lebensjahr?",a:25,unit:"cm",hint:"Von ca. 50cm auf 75cm.",emoji:"👶"},
  {id:"koerp_234",q:"Wie viele Tage braucht der Darm um seine Schleimhaut komplett zu erneuern?",a:3,unit:"Tage",hint:"Alle 3-5 Tage erneuert sich die Darmschleimhaut komplett.",emoji:"🌀"},
  {id:"koerp_235",q:"Wie viele Gramm Eisen hat das Blut eines Erwachsenen?",a:3,unit:"Gramm",hint:"Etwa 3,5g Eisen im Körper – davon 70% im Hämoglobin.",emoji:"⚙️"},
  {id:"koerp_236",q:"Wie viele Millimeter beträgt der Durchmesser einer Pupille maximal?",a:8,unit:"mm",hint:"Im Dunkeln öffnet sie sich auf bis zu 8mm.",emoji:"👁️"}
];
