// 🐾 TIERREICH – Erwachsene – 250 Fragen
export default [
  {q:"Wie viele kg wiegen die Hoden eines Blauwals?",a:70,unit:"kg",hint:"Der Blauwal ist das größte Tier der Erde.",emoji:"🐋"},
  {q:"Wie oft pro Minute schlägt das Herz einer Maus?",a:600,unit:"Mal",hint:"Je kleiner das Tier, desto schneller das Herz.",emoji:"🐭"},
  {q:"Wie viele Tage trägt ein Elefant sein Junges?",a:645,unit:"Tage",hint:"Fast 2 Jahre – längste Schwangerschaft aller Landsäugetiere.",emoji:"🐘"},
  {q:"Wie viele Liter Milch produziert eine Kuh pro Tag?",a:25,unit:"Liter",hint:"Hochleistungskühe können bis zu 50 Liter täglich geben.",emoji:"🐄"},
  {q:"Wie schwer kann ein Riesenkalmar-Auge in Gramm werden?",a:250,unit:"Gramm",hint:"Das größte Auge im Tierreich – so groß wie ein Fußball.",emoji:"🦑"},
  {q:"Wie viele km/h läuft ein Gepard maximal?",a:112,unit:"km/h",hint:"Er kann diese Höchstgeschwindigkeit nur kurz halten.",emoji:"🐆"},
  {q:"Wie viele Magen hat eine Kuh?",a:4,unit:"Mägen",hint:"Pansen, Netzmagen, Blättermagen und Labmagen.",emoji:"🐄"},
  {q:"Wie hoch kann ein Känguru springen in Metern?",a:3,unit:"Meter",hint:"Und in der Länge sogar bis zu 9 Meter weit.",emoji:"🦘"},
  {q:"Wie schwer wird ein ausgewachsener Gorilla maximal in kg?",a:270,unit:"kg",hint:"Trotz Größe sind Gorillas überwiegend Vegetarier.",emoji:"🦍"},
  {q:"Wie viele Stunden schläft ein Koala pro Tag?",a:22,unit:"Stunden",hint:"Eukalyptus ist schwer verdaulich – daher die Müdigkeit.",emoji:"🐨"},
  {q:"Wie viele km/h kann ein Schwertfisch schwimmen?",a:110,unit:"km/h",hint:"Der schnellste Fisch im Meer.",emoji:"🐟"},
  {q:"Wie lange lebt eine Königin-Biene in Jahren?",a:5,unit:"Jahre",hint:"Arbeiterinnen leben im Sommer nur 6 Wochen.",emoji:"🐝"},
  {q:"Wie viele Zähne hat ein erwachsenes Krokodil?",a:66,unit:"Zähne",hint:"Krokodile erneuern ihre Zähne bis zu 50 Mal im Leben.",emoji:"🐊"},
  {q:"Wie viele Eier legt eine Königin-Termite pro Tag?",a:30000,unit:"Eier",hint:"Die produktivste Mutter im Insektenreich.",emoji:"🐜"},
  {q:"Wie viele Liter Blut hat ein ausgewachsener Elefant?",a:400,unit:"Liter",hint:"Das Elefantenherz wiegt allein bis zu 30 kg.",emoji:"🐘"},
  {q:"Wie viele Mal kann ein Specht pro Sekunde hämmern?",a:20,unit:"Mal",hint:"Sein Gehirn ist durch Spezialanpassungen geschützt.",emoji:"🐦"},
  {q:"Wie schwer ist das schwerste Vogelei (Strauß) in kg?",a:1.35,unit:"kg",hint:"Strauße legen die größten Eier aller lebenden Vögel.",emoji:"🥚"},
  {q:"Wie lange kann ein Delphin den Atem anhalten in Minuten?",a:15,unit:"Minuten",hint:"Delfine schlafen mit einer Gehirnhälfte.",emoji:"🐬"},
  {q:"Wie viele Jahre kann ein Grönlandwal leben?",a:211,unit:"Jahre",hint:"Das langlebigste Säugetier der Erde.",emoji:"🐳"},
  {q:"Wie schwer ist die Zunge eines Blauwals in kg?",a:2700,unit:"kg",hint:"Die Zunge allein wiegt so viel wie ein Elefant.",emoji:"🐋"},
  {q:"Wie viele Millionen Geruchsrezeptoren hat ein Hund?",a:300,unit:"Millionen",hint:"Menschen haben nur 6 Millionen – Hunde riechen 50x besser.",emoji:"🐕"},
  {q:"Wie viele Meter lang kann ein Bandwurm im Darm werden?",a:25,unit:"Meter",hint:"Bandwürmer können jahrelang unbemerkt leben.",emoji:"🪱"},
  {q:"Wie hoch ist der Blutdruck einer Giraffe in mmHg?",a:280,unit:"mmHg",hint:"Nötig um Blut 2 Meter nach oben ins Gehirn zu pumpen.",emoji:"🦒"},
  {q:"Wie viele kg Bambus frisst ein Pandabär täglich?",a:15,unit:"kg",hint:"Bambus ist sehr nährstoffarm – daher die riesige Menge.",emoji:"🐼"},
  {q:"Wie lange trägt ein Hai seine Jungen in Monaten?",a:24,unit:"Monate",hint:"Hammerhaie haben die längste Tragzeit.",emoji:"🦈"},
  {q:"Wie viele Augen hat eine Spinne?",a:8,unit:"Augen",hint:"Trotz 8 Augen sehen viele Spinnen sehr schlecht.",emoji:"🕷️"},
  {q:"Wie viele km/h erreicht ein Wanderfalke im Sturzflug?",a:320,unit:"km/h",hint:"Das schnellste Tier der Welt im Sturzflug.",emoji:"🦅"},
  {q:"Wie viele Tonnen wiegt ein ausgewachsener Blauwal?",a:150,unit:"Tonnen",hint:"Das größte Tier das je auf der Erde gelebt hat.",emoji:"🐋"},
  {q:"Wie viele Stunden kann eine Schnecke schlafen am Stück?",a:3,unit:"Jahre",hint:"Schnecken können bis zu 3 Jahre in Kältestarre verbringen.",emoji:"🐌"},
  {q:"Wie viele Elektronen-Volt erzeugt ein Zitteraal?",a:600,unit:"Volt",hint:"600 Volt – genug um einen Menschen zu betäuben.",emoji:"🐍"},
  {q:"Wie viele km/h rennt ein Nashorn?",a:55,unit:"km/h",hint:"Trotz ihrer Masse sind Nashörner erstaunlich schnell.",emoji:"🦏"},
  {q:"Wie viele Jahre alt kann ein Koi-Fisch werden?",a:226,unit:"Jahre",hint:"Hanako, ein Koi in Japan, lebte 226 Jahre.",emoji:"🐟"},
  {q:"Wie viele Knochen hat eine Schlange?",a:300,unit:"Knochen",hint:"Je nach Art zwischen 200 und 400 Knochen.",emoji:"🐍"},
  {q:"Wie viele Mal pro Sekunde schlägt eine Biene ihre Flügel?",a:200,unit:"Mal",hint:"Das erzeugt das charakteristische Summen.",emoji:"🐝"},
  {q:"Wie viele Liter Wasser saugt ein Elefant täglich?",a:190,unit:"Liter",hint:"Der Rüssel fasst bis zu 15 Liter auf einmal.",emoji:"🐘"},
  {q:"Wie viele Jahre kann eine Schildkröte ohne Nahrung überleben?",a:1,unit:"Jahr",hint:"Schildkröten können ihren Stoffwechsel extrem verlangsamen.",emoji:"🐢"},
  {q:"Wie weit kann ein Flugfisch aus dem Wasser gleiten in Metern?",a:400,unit:"Meter",hint:"Flugfische nutzen Wind und Auftrieb zum Gleiten.",emoji:"🐟"},
  {q:"Wie viele Gramm wiegt das Herz eines Blauwals?",a:180000,unit:"Gramm",hint:"Das Herz ist so groß wie ein kleines Auto.",emoji:"❤️"},
  {q:"Wie viele Stunden schläft ein Löwe pro Tag?",a:20,unit:"Stunden",hint:"Löwen schlafen mehr als Koalas.",emoji:"🦁"},
  {q:"Wie viele Meter lang wird eine Riesenschlange (Pythons)?",a:7,unit:"Meter",hint:"Der Netzpython ist die längste Schlange der Welt.",emoji:"🐍"},
  {q:"Wie viele Eier legt ein weiblicher Oktopus?",a:400000,unit:"Eier",hint:"Sie bewacht sie bis zum Schlüpfen und stirbt danach.",emoji:"🐙"},
  {q:"Wie viele km/h läuft ein Strauß?",a:70,unit:"km/h",hint:"Der schnellste laufende Vogel – und kann nicht fliegen.",emoji:"🦜"},
  {q:"Wie viele Zähne hat ein Weißer Hai?",a:300,unit:"Zähne",hint:"In mehreren Reihen – ständig nachwachsend.",emoji:"🦈"},
  {q:"Wie schwer wird ein Walross maximal in kg?",a:1700,unit:"kg",hint:"Männliche Walrosse sind deutlich schwerer als Weibchen.",emoji:"🦭"},
  {q:"Wie viele Jahre lebt eine Arbeiterin-Biene im Sommer?",a:0.13,unit:"Jahre",hint:"Nur 6 Wochen im Sommer – im Winter bis zu 6 Monate.",emoji:"🐝"},
  {q:"Wie viele Arten von Insekten gibt es auf der Erde (Millionen)?",a:1,unit:"Million Arten",hint:"Über 1 Million bekannte Arten – viele noch unentdeckt.",emoji:"🐛"},
  {q:"Wie viele Herzen hat ein Tintenfisch?",a:3,unit:"Herzen",hint:"Zwei pumpen Blut zu den Kiemen, eines zum Körper.",emoji:"🐙"},
  {q:"Wie lang ist die Zunge eines Chamäleons im Verhältnis zum Körper?",a:150,unit:"% Körperlänge",hint:"Die Zunge schlägt mit bis zu 26 km/h aus.",emoji:"🦎"},
  {q:"Wie viele km/h rennt ein Gepard auf kurzer Strecke?",a:112,unit:"km/h",hint:"Beschleunigt von 0 auf 100 in 3 Sekunden.",emoji:"🐆"},
  {q:"Wie viele Millionen Geruchssensoren hat ein Bär?",a:2100,unit:"Millionen",hint:"Bären haben den schärfsten Geruchssinn aller Landtiere.",emoji:"🐻"},
  {q:"Wie schwer wird ein Polarbär maximal in kg?",a:700,unit:"kg",hint:"Das größte Landraubtier der Erde.",emoji:"🐻‍❄️"},
  {q:"Wie viele Beine hat ein Tausendfüßer durchschnittlich?",a:750,unit:"Beine",hint:"Nie genau 1000 – trotz des Namens.",emoji:"🐛"},
  {q:"Wie lange kann eine Stubenfliege fliegen ohne zu landen?",a:2,unit:"Stunden",hint:"Danach braucht sie Ruhe und Nahrung.",emoji:"🪰"},
  {q:"Wie viele Jahre alt wird eine Elefantenschildkröte maximal?",a:190,unit:"Jahre",hint:"Harriet lebte bis 2006 und war ~175 Jahre alt.",emoji:"🐢"},
  {q:"Wie viele km weit wandert ein Monarch-Schmetterling?",a:4000,unit:"km",hint:"Von Kanada bis Mexiko – jedes Jahr.",emoji:"🦋"},
  {q:"Wie viele Gramm wiegt eine Hummel?",a:0.6,unit:"Gramm",hint:"Trotz winziger Masse kann sie ein Vielfaches ihres Gewichts tragen.",emoji:"🐝"},
  {q:"Wie viele Stunden pro Tag sucht ein Nashorn Nahrung?",a:12,unit:"Stunden",hint:"Die Hälfte ihres Lebens verbringen sie mit Fressen.",emoji:"🦏"},
  {q:"Wie hoch springt ein Lachs flussaufwärts maximal in Metern?",a:3,unit:"Meter",hint:"Lachse springen Wasserfälle hinauf zu ihren Laichgebieten.",emoji:"🐟"},
  {q:"Wie viele Gramm Seide produziert ein Seidenspinner für einen Kokon?",a:0.5,unit:"Gramm",hint:"Aus einem Kokon kann man bis zu 1500 Meter Seide spinnen.",emoji:"🪱"},
  {q:"Wie viele Liter Blut verliert ein Moskito wenn er sticht?",a:0.001,unit:"ml",hint:"Ein Moskito saugt etwa 1-3 mg Blut.",emoji:"🦟"},
  {q:"Wie schwer wird ein ausgewachsener Nilpferd in Tonnen?",a:3,unit:"Tonnen",hint:"Nach Elefant und Nashorn das drittschwerste Landtier.",emoji:"🦛"},
  {q:"Wie viele Stunden schläft eine Giraffe täglich?",a:2,unit:"Stunden",hint:"Giraffen schlafen sehr wenig – in kurzen Phasen.",emoji:"🦒"},
  {q:"Wie viele Gramm wiegt ein Kolibri?",a:3,unit:"Gramm",hint:"Der kleinste Vogel der Welt wiegt weniger als eine Münze.",emoji:"🐦"},
  {q:"Wie oft schlägt das Herz eines Kolibris pro Minute?",a:1200,unit:"Mal",hint:"Das schnellste Herz aller Wirbeltiere.",emoji:"🐦"},
  {q:"Wie weit kann ein Känguru in einem einzigen Sprung?",a:9,unit:"Meter",hint:"Und dabei 3 Meter hoch.",emoji:"🦘"},
  {q:"Wie schwer ist das Gehirn eines Elefanten in kg?",a:5,unit:"kg",hint:"Das schwerste Gehirn aller Landtiere.",emoji:"🐘"},
  {q:"Wie viele Kilogramm frisst ein Blauwal täglich an Krill?",a:3600,unit:"kg",hint:"Fast 4 Tonnen Krill täglich.",emoji:"🐋"},
  {q:"Wie viele Stunden kann ein Albatros nonstop fliegen?",a:10,unit:"Stunden",hint:"Albatrosse schlafen sogar im Flug.",emoji:"🦅"},
  {q:"Wie lang ist die Trächtigkeit einer Maus in Tagen?",a:21,unit:"Tage",hint:"Mäuse können 10 Mal pro Jahr trächtig sein.",emoji:"🐭"},
  {q:"Wie viele Eier legt eine Königin-Ameise pro Jahr?",a:300000,unit:"Eier",hint:"Manche Königinnen leben 30 Jahre und legen täglich 800 Eier.",emoji:"🐜"},
  {q:"Wie viele km/h läuft ein Schwarzbär?",a:48,unit:"km/h",hint:"Schneller als ein Mensch – man kann vor einem Bären nicht weglaufen.",emoji:"🐻"},
  {q:"Wie tief kann ein Potwal tauchen in Metern?",a:3000,unit:"Meter",hint:"Das tiefste Tauchgang eines Säugetiers.",emoji:"🐳"},
  {q:"Wie viele Kilogramm Nahrung frisst ein Gorilla täglich?",a:18,unit:"kg",hint:"Gorillas sind reine Vegetarier.",emoji:"🦍"},
  {q:"Wie lange lebt eine Drohnen-Biene?",a:90,unit:"Tage",hint:"Drohnen leben nur bis zur Paarung – dann sterben sie.",emoji:"🐝"},
  {q:"Wie viele Meter tief gräbt ein Maulwurf seine Tunnel?",a:1,unit:"Meter",hint:"Maulwürfe bauen Tunnel-Systeme über 200 Meter Länge.",emoji:"🐀"},
  {q:"Wie viele Jahre lebt ein wilder Schimpanse?",a:45,unit:"Jahre",hint:"In Gefangenschaft können sie über 60 Jahre alt werden.",emoji:"🐒"},
  {q:"Wie schwer ist der Schädel eines Tyrannosaurus Rex in kg?",a:500,unit:"kg",hint:"Einer der größten Schädel aller fleischfressenden Dinosaurier.",emoji:"🦖"},
  {q:"Wie viele Federn hat ein Schwan?",a:25000,unit:"Federn",hint:"Wasservögel haben besonders viele Federn für die Isolation.",emoji:"🦢"},
  {q:"Wie viele Stunden brütet ein Kaiserpinguin sein Ei?",a:1512,unit:"Stunden",hint:"63 Tage – ohne Nahrung in antarktischem Winter.",emoji:"🐧"},
  {q:"Wie weit kann ein Gepard in einem Sprung?",a:8,unit:"Meter",hint:"Geparden machen enorme Sprünge beim Jagen.",emoji:"🐆"},
  {q:"Wie viele Liter Wasser kann ein Elefant mit dem Rüssel aufnehmen?",a:15,unit:"Liter",hint:"Der Rüssel ist ein multifunktionales Werkzeug.",emoji:"🐘"},
  {q:"Wie viele km/h schlägt eine Mantis-Garnele zu?",a:80,unit:"km/h",hint:"Der schnellste Schlag im Tierreich.",emoji:"🦐"},
  {q:"Wie viele Millionen Leukozyten hat ein Mensch pro mm³ Blut?",a:7000,unit:"pro mm³",hint:"Immunzellen im Blut.",emoji:"🔬"},
  {q:"Wie viele Stunden schläft ein Delfin pro Tag?",a:8,unit:"Stunden",hint:"Immer mit einer Gehirnhälfte – die andere bleibt wach.",emoji:"🐬"},
  {q:"Wie schwer ist die Leber eines Blauwals in kg?",a:1000,unit:"kg",hint:"Alle Organe des Blauwals sind riesig.",emoji:"🐋"},
  {q:"Wie viele Eier kann eine Meeresschildkröte pro Saison legen?",a:200,unit:"Eier",hint:"Nur etwa 1% der Jungtiere überleben bis zur Adultheit.",emoji:"🐢"},
  {q:"Wie viele km weit fliegt ein Zugvogel im Jahr?",a:70000,unit:"km",hint:"Der Küstenseeschwalbe fliegt am weitesten.",emoji:"🐦"},
  {q:"Wie lange kann ein Kamel ohne Wasser überleben in Tagen?",a:15,unit:"Tage",hint:"Der Höcker speichert Fett, nicht Wasser.",emoji:"🐪"},
  {q:"Wie viele Stunden lebt eine Eintagsfliege als Imago?",a:24,unit:"Stunden",hint:"Als Larve lebt sie bis zu 3 Jahre.",emoji:"🪲"},
  {q:"Wie schwer ist das Gehirn eines Pottwals in kg?",a:7,unit:"kg",hint:"Das schwerste Gehirn aller bekannten Tiere.",emoji:"🐳"},
  {q:"Wie viele Flügelschläge macht eine Kolibri pro Sekunde?",a:80,unit:"Mal",hint:"So schnell, dass die Flügel unsichtbar werden.",emoji:"🐦"},
  {q:"Wie viele km/h läuft eine Gazelle?",a:90,unit:"km/h",hint:"Gazellen sind fast so schnell wie Geparden.",emoji:"🦌"},
  {q:"Wie tief gräbt ein Erdhörnchen seinen Bau in Metern?",a:3,unit:"Meter",hint:"Mit mehreren Ein- und Ausgängen.",emoji:"🐿️"},
  {q:"Wie viele Stacheln hat ein Igel?",a:6000,unit:"Stacheln",hint:"Stacheln sind modifizierte Haare.",emoji:"🦔"},
  {q:"Wie viele Jahre lebt ein Hummer?",a:100,unit:"Jahre",hint:"Hummer altern praktisch nicht – sie werden nur durch Jäger oder Hunger begrenzt.",emoji:"🦞"},
  {q:"Wie viele Mal schlägt das Herz einer Schlange pro Minute?",a:40,unit:"Mal",hint:"Schlangen haben einen viel langsameren Herzschlag als Säugetiere.",emoji:"🐍"},
  {q:"Wie weit kann eine Springspinne springen in cm?",a:50,unit:"cm",hint:"Das 50-fache ihrer Körperlänge.",emoji:"🕷️"},
  {q:"Wie viele kg frisst ein Tiger täglich?",a:8,unit:"kg",hint:"Tiger fressen seltener aber dafür viel auf einmal.",emoji:"🐯"},
  {q:"Wie viele Liter Speichel produziert eine Kuh täglich?",a:200,unit:"Liter",hint:"Wiederkäuen erfordert enorm viel Speichel.",emoji:"🐄"},
  {q:"Wie lange schläft ein Braunbär im Winterschlaf in Monaten?",a:6,unit:"Monate",hint:"Kein echter Tiefschlaf – sie können jederzeit aufwachen.",emoji:"🐻"},
  {q:"Wie viele Kilometer wandert ein Weißwal pro Jahr?",a:10000,unit:"km",hint:"Weißwale sind wanderfreudige Meeressäuger.",emoji:"🐳"},
  {q:"Wie viele Stunden lebt eine Biene nach dem Stich?",a:1,unit:"Stunde",hint:"Der Stachel verbleibt im Opfer – die Biene stirbt.",emoji:"🐝"},
  {q:"Wie schwer ist ein Elefantenzahn (Stoßzahn) maximal in kg?",a:100,unit:"kg",hint:"Stoßzähne wachsen ein Leben lang.",emoji:"🐘"},
  {q:"Wie viele Gramm wiegt ein neugeborenes Känguru?",a:1,unit:"Gramm",hint:"Das Joeys kriecht nach der Geburt in den Beutel.",emoji:"🦘"},
  {q:"Wie viele km/h schwimmt ein Blauwal?",a:30,unit:"km/h",hint:"Bei Gefahr können sie kurze Sprints einlegen.",emoji:"🐋"},
  {q:"Wie lange lebt eine Taschenkrabbe in Jahren?",a:100,unit:"Jahre",hint:"Krabben können sehr alt werden.",emoji:"🦀"},
  {q:"Wie viele Gramm wiegt ein Kolibri-Nest?",a:2,unit:"Gramm",hint:"Winzige Nester aus Spinnweben und Flechten.",emoji:"🐦"},
  {q:"Wie viele Stunden fliegt eine Hornisse täglich?",a:8,unit:"Stunden",hint:"Hornissen sind aktive Jäger.",emoji:"🐝"},
  {q:"Wie weit kann ein Delfin einen Ball balancieren in Stunden?",a:3,unit:"Stunden",hint:"Delfine sind die intelligentesten Meerestiere.",emoji:"🐬"},
  {q:"Wie viele Jahre kann ein Krokodil ohne Nahrung überleben?",a:3,unit:"Jahre",hint:"Krokodile haben einen extrem niedrigen Stoffwechsel.",emoji:"🐊"},
  {q:"Wie schwer ist der Penis eines Blauwals in kg?",a:450,unit:"kg",hint:"Das größte Geschlechtsorgan im Tierreich.",emoji:"🐋"},
  {q:"Wie lange ist ein Blauwal-Penis in Metern?",a:2.7,unit:"Meter",hint:"Proportional zum Körper aber das absolut größte.",emoji:"🐋"},
  {q:"Wie viele Eizellen produziert eine Ozean-Sonnenblume pro Saison?",a:300000000,unit:"Eier",hint:"300 Millionen Eier – die meisten aller Wirbeltiere.",emoji:"🐟"},
  {q:"Wie viele Liter Blut pumpt ein Elefantenherz pro Minute?",a:300,unit:"Liter",hint:"Das Elefantenherz wiegt 25 kg.",emoji:"🐘"},
  {q:"Wie viele Stunden kann eine Nacktmull-Ratte ohne Sauerstoff überleben?",a:18,unit:"Stunden",hint:"Nacktmull-Ratten sind gegen Sauerstoffmangel resistent.",emoji:"🐀"},
  {q:"Wie schwer ist das Gehirn eines Octopus in Gramm?",a:40,unit:"Gramm",hint:"Sehr klein aber extrem effizient.",emoji:"🐙"},
  {q:"Wie viele Chromatophoren hat ein Tintenfisch?",a:10000000,unit:"Chromatophoren",hint:"Diese Farbzellen ermöglichen blitzschnelle Farbwechsel.",emoji:"🦑"},
  {q:"Wie viele Meter lang ist ein Bandwurm maximal?",a:30,unit:"Meter",hint:"Fischbandwürmer können bis zu 30m lang werden.",emoji:"🪱"},
  {q:"Wie viele Mal pro Nacht hört eine Eule?",a:360,unit:"Grad",hint:"Eulen können den Kopf 270 Grad drehen.",emoji:"🦉"},
  {q:"Wie schwer ist ein Ochsen-Frosch in kg?",a:3,unit:"kg",hint:"Der schwerste Frosch der Welt.",emoji:"🐸"},
  {q:"Wie viele Liter Honig produziert ein Bienenvolk pro Jahr?",a:30,unit:"Liter",hint:"Für ein Glas Honig fliegen Bienen 80.000 km.",emoji:"🍯"},
  {q:"Wie lang ist die Trächtigkeit eines Schwarzen Rhinozeros in Tagen?",a:450,unit:"Tage",hint:"15 Monate – eine der längsten Tragezeiten.",emoji:"🦏"},
  {q:"Wie viele Stunden lebt eine Eintagsfliegen-Larve bevor sie schlüpft?",a:26280,unit:"Stunden",hint:"3 Jahre als Larve, dann 1 Tag als Erwachsener.",emoji:"🪲"},
  {q:"Wie tief taucht ein Kaiserpinguin maximal in Metern?",a:565,unit:"Meter",hint:"Der tieftauchende Vogel der Welt.",emoji:"🐧"},
  {q:"Wie viele Gramm wiegt das Herz eines Pferdes?",a:4500,unit:"Gramm",hint:"Das große Herz ist der Schlüssel zur Ausdauer.",emoji:"🐴"},
  {q:"Wie weit kann ein Lemur springen in Metern?",a:10,unit:"Meter",hint:"Lemure sind erstaunliche Springer.",emoji:"🐒"},
  {q:"Wie viele km/h kann eine Libelle fliegen?",a:55,unit:"km/h",hint:"Eine der schnellsten fliegenden Insekten.",emoji:"🪲"},
  {q:"Wie lange lebt eine Dragonfly in Wochen als Erwachsener?",a:4,unit:"Wochen",hint:"Als Larve lebt sie bis zu 5 Jahre.",emoji:"🪲"},
  {q:"Wie schwer ist ein ausgewachsenes Nilpferd-Zahn in kg?",a:3,unit:"kg",hint:"Die Eckzähne sind reine Waffen.",emoji:"🦛"},
  {q:"Wie viele Tentakel hat ein Oktopus?",a:8,unit:"Tentakel",hint:"Jeder Arm hat eigene Nervenzellen.",emoji:"🐙"},
  {q:"Wie weit kann ein Flachlandgorilla seinen Ruf hören in km?",a:2,unit:"km",hint:"Gorillas kommunizieren über weite Distanzen.",emoji:"🦍"},
  {q:"Wie viele Mal pro Sekunde bewegt ein Schwertfisch die Schwanzflosse?",a:3,unit:"Mal",hint:"Kraftvolle langsame Bewegungen für hohe Geschwindigkeit.",emoji:"🐟"},
  {q:"Wie lang ist die Nasenspitze eines Elefanten-Rüssels?",a:250,unit:"cm",hint:"Der Rüssel ist der verlängerte Nasenrücken.",emoji:"🐘"},
  {q:"Wie viele Liter Wasser trinkt ein Kamel auf einmal nach der Wüste?",a:100,unit:"Liter",hint:"In 13 Minuten kann ein Kamel 100 Liter trinken.",emoji:"🐪"},
  {q:"Wie schwer ist ein Blauwalhoden in kg?",a:35,unit:"kg",hint:"Jeder Hoden wiegt 35 kg – zusammen 70 kg.",emoji:"🐋"},
  {q:"Wie viele Stunden alt werden Libellen-Larven bevor sie schlüpfen?",a:35040,unit:"Stunden",hint:"4 Jahre als Larve im Wasser.",emoji:"🪲"},
  {q:"Wie viele Farben kann ein Tintenfisch gleichzeitig anzeigen?",a:30,unit:"Farben",hint:"Obwohl farbenblind – der Farbwechsel dient der Tarnung.",emoji:"🦑"},
  {q:"Wie schnell regeneriert ein Seestern seinen Arm in Wochen?",a:52,unit:"Wochen",hint:"Ein Jahr – und aus dem abgetrennten Arm wächst ein neuer Seestern.",emoji:"⭐"},
  {q:"Wie viele Jahre kann eine Qualle (Turritopsis dohrnii) theoretisch leben?",a:9999,unit:"Jahre",hint:"Die biologisch unsterbliche Qualle kann sich unbegrenzt verjüngen.",emoji:"🪼"},
  {q:"Wie viele km/h kann ein Gepard auf 100m beschleunigen?",a:75,unit:"km/h",hint:"Beschleunigung von 0 auf 75 in 2 Sekunden.",emoji:"🐆"},
  {q:"Wie viele Kilogramm wiegt ein ausgewachsener Jaguar?",a:100,unit:"kg",hint:"Der schwerste Großkatze Amerikas.",emoji:"🐆"},
  {q:"Wie viele Augen hat eine Libelle?",a:30000,unit:"Facetten",hint:"Zusammengesetzte Augen mit 30.000 Einzellinsen.",emoji:"🪲"},
  {q:"Wie weit kann ein Springer-Frosch springen in cm?",a:530,unit:"cm",hint:"Vielfaches der eigenen Körperlänge.",emoji:"🐸"},
  {q:"Wie viele Stunden täglich ist eine Hauskatze aktiv?",a:5,unit:"Stunden",hint:"Hauskatzen schlafen 16-20 Stunden täglich.",emoji:"🐱"},
  {q:"Wie viele Gramm Honig isst ein Bär in einem Sommer?",a:40000,unit:"Gramm",hint:"40 kg Honig – Bären lieben Bienenstöcke.",emoji:"🐻"},
  {q:"Wie viele km/h kann ein Tintenfisch schwimmen?",a:40,unit:"km/h",hint:"Durch rückwärtiges Ausstoßen von Wasser.",emoji:"🦑"},
  {q:"Wie lang ist die Zunge eines Ameisenbären in cm?",a:60,unit:"cm",hint:"Die klebrige Zunge fährt 150 Mal pro Minute aus.",emoji:"🐜"},
  {q:"Wie viele Stunden am Tag weidet ein Pferd?",a:16,unit:"Stunden",hint:"Pferde fressen fast nonstop.",emoji:"🐴"},
  {q:"Wie schwer ist ein ausgewachsener Gorilla-Arm in kg?",a:15,unit:"kg",hint:"Gorillas sind 6 Mal stärker als Menschen.",emoji:"🦍"},
  {q:"Wie viele Liter Blut pumpt ein Giraffenherz pro Minute?",a:60,unit:"Liter",hint:"Das Giraffenherz wiegt 10 kg.",emoji:"🦒"},
  {q:"Wie viele km kann eine Wüstenameise ohne Orientierungshilfe navigieren?",a:50,unit:"km",hint:"Sie nutzen Polarisationsmuster des Himmels.",emoji:"🐜"},
  {q:"Wie viele Knochen hat ein Delfin?",a:200,unit:"Knochen",hint:"Delfine haben Knochen wo einst Hinterbeine waren.",emoji:"🐬"},
  {q:"Wie tief können Maulwürfe ihre Tunnels anlegen?",a:70,unit:"cm",hint:"Haupttunnel liegen tiefer als Jagdtunnel.",emoji:"🐀"},
  {q:"Wie viele Stunden kann ein Flamingo auf einem Bein stehen?",a:4,unit:"Stunden",hint:"Das Stehen auf einem Bein kostet weniger Energie.",emoji:"🦩"},
  {q:"Wie viele Ton frisst ein Blauwal an einem Tag?",a:3.6,unit:"Tonnen",hint:"Fast 4 Tonnen Krill täglich.",emoji:"🐋"},
  {q:"Wie weit kann eine Heuschrecke springen in Metern?",a:1,unit:"Meter",hint:"Das 20-fache ihrer eigenen Körperlänge.",emoji:"🦗"},
  {q:"Wie viele Jahre kann ein Elefant leben?",a:70,unit:"Jahre",hint:"In Gefangenschaft werden sie manchmal über 80.",emoji:"🐘"},
  {q:"Wie schwer ist ein neugeborener Blauwal in Tonnen?",a:2.7,unit:"Tonnen",hint:"Das Größte Neugeborene der Welt.",emoji:"🐋"},
  {q:"Wie viele Stunden schläft ein Totenkopf-Äffchen täglich?",a:11,unit:"Stunden",hint:"Totenkopfäffchen sind echte Schläfer.",emoji:"🐒"},
  {q:"Wie lang ist ein Elefantenrüssel in Metern?",a:2,unit:"Meter",hint:"Er hat über 40.000 Muskeln.",emoji:"🐘"},
  {q:"Wie viele Eier legt eine Königin-Ameise täglich?",a:800,unit:"Eier",hint:"Über ihr ganzes Leben bis zu 30 Millionen Eier.",emoji:"🐜"},
  {q:"Wie lang ist die Trächtigkeit eines Schwertwals in Monaten?",a:17,unit:"Monate",hint:"Orcas haben eine der längsten Tragezeiten.",emoji:"🐋"},
  {q:"Wie viele Stunden verbringt ein Tier im Wasser täglich (Nilpferd)?",a:16,unit:"Stunden",hint:"Nilpferde kühlen sich und schützen ihre Haut.",emoji:"🦛"},
  {q:"Wie viele Gramm wiegt ein Pfauenschwanz-Feder?",a:5,unit:"Gramm",hint:"Trotz ihrer Größe extrem leicht.",emoji:"🦚"},
  {q:"Wie viele Stacheln hat ein Igel auf dem Rücken?",a:5000,unit:"Stacheln",hint:"Jeder Stachel ist ein modifiziertes Haar.",emoji:"🦔"},
  {q:"Wie weit kann ein Fliegendes Eichhörnchen gleiten in Metern?",a:90,unit:"Meter",hint:"Mit der Gleitfalte zwischen Vorder- und Hinterbeinen.",emoji:"🐿️"},
  {q:"Wie viele km/h läuft ein Erdferkel?",a:40,unit:"km/h",hint:"Überraschend schnell für ein scheinbar gemächliches Tier.",emoji:"🐷"},
  {q:"Wie schwer ist ein ausgewachsener männlicher Elefant-Rüsseltier in kg?",a:6000,unit:"kg",hint:"Afrikanische Elefanten sind schwerer als asiatische.",emoji:"🐘"},
  {q:"Wie viele Liter Milch trinkt ein Blauwal-Baby täglich?",a:600,unit:"Liter",hint:"Es wächst täglich um 90 kg.",emoji:"🐋"},
  {q:"Wie viele Stunden verbringt ein Flamingo im Wasser täglich?",a:12,unit:"Stunden",hint:"Flamingos filtern Nahrung aus Schlamm.",emoji:"🦩"},
  {q:"Wie lang ist die Trächtigkeit eines Nashorns in Monaten?",a:16,unit:"Monate",hint:"Nashörner bekommen nur alle 2-5 Jahre ein Junges.",emoji:"🦏"},
  {q:"Wie viele Gramm wiegt eine Honigbiene?",a:0.1,unit:"Gramm",hint:"Nur 100 Milligramm – aber immens wichtig.",emoji:"🐝"},
  {q:"Wie weit kann ein Fliegender Fisch aus dem Wasser herausgleiten?",a:400,unit:"Meter",hint:"Flugfische nutzen Wind und Auftrieb.",emoji:"🐟"},
  {q:"Wie viele Jahre lebt ein Walross?",a:40,unit:"Jahre",hint:"Walrosse werden in der Wildnis bis zu 40 Jahre alt.",emoji:"🦭"},
  {q:"Wie schwer ist die Schildkrötenpanzer eines Riesenschildkröte in kg?",a:30,unit:"kg",hint:"Der Panzer macht ein Drittel des Körpergewichts aus.",emoji:"🐢"},
  {q:"Wie viele Stunden am Tag reinigt sich eine Katze?",a:5,unit:"Stunden",hint:"Ein Drittel ihrer Wachzeit verbringen Katzen mit Putzen.",emoji:"🐱"},
  {q:"Wie viele Gramm wiegt ein Pinguin-Ei?",a:450,unit:"Gramm",hint:"Kaiserpinguin-Eier sind riesig im Verhältnis zum Körper.",emoji:"🐧"},
  {q:"Wie weit kann ein Gepard seinen Geruchssinn nutzen in km?",a:3,unit:"km",hint:"Geparden nutzen hauptsächlich das Sehen.",emoji:"🐆"},
  {q:"Wie viele Zähne hat ein Delfin?",a:100,unit:"Zähne",hint:"Delfine benutzen Zähne zum Fangen, nicht zum Kauen.",emoji:"🐬"},
  {q:"Wie lang ist die Zunge einer Kuh in cm?",a:45,unit:"cm",hint:"Kühe lecken sich die Nase damit sauber.",emoji:"🐄"},
  {q:"Wie viele Stacheln hat ein Stachelrochen?",a:1,unit:"Stachel",hint:"Nur ein Giftstachel – aber sehr schmerzhaft.",emoji:"🐟"},
  {q:"Wie schwer ist ein Gorilla-Silberrücken in kg?",a:250,unit:"kg",hint:"Silberrücken dominieren ihre Gruppe.",emoji:"🦍"},
  {q:"Wie weit kann ein Springhase springen in Metern?",a:3,unit:"Meter",hint:"Springhasen sind afrikanische Nager.",emoji:"🐇"},
  {q:"Wie viele km/h erreicht eine Schildkröte beim Schwimmen?",a:35,unit:"km/h",hint:"Lederschildkröten sind erstaunlich schnelle Schwimmer.",emoji:"🐢"},
  {q:"Wie viele Gramm Futter frisst eine Raupe täglich im Verhältnis zum Körpergewicht?",a:200,unit:"% Körpergewicht",hint:"Raupen verdoppeln ihr Gewicht in Tagen.",emoji:"🐛"},
  {q:"Wie viele Stunden lebt eine Hausfliegenmaggot bis zur Verpuppung?",a:240,unit:"Stunden",hint:"10 Tage als Made, dann Puppe.",emoji:"🪰"},
  {q:"Wie lang ist der Dünndarm einer Kuh in Metern?",a:40,unit:"Meter",hint:"Kühe haben ein sehr langes Verdauungssystem.",emoji:"🐄"},
  {q:"Wie viele Liter Speichel produziert ein Pferd täglich?",a:40,unit:"Liter",hint:"Pferde brauchen viel Speichel für die Verdauung.",emoji:"🐴"},
  {q:"Wie schwer ist ein Schimpansen-Arm im Vergleich zu einem menschlichen?",a:2,unit:"x stärker",hint:"Schimpansen sind doppelt so stark wie Menschen.",emoji:"🐒"},
  {q:"Wie weit wandert ein Elch pro Jahr in km?",a:300,unit:"km",hint:"Elche folgen Nahrung und Wetter.",emoji:"🦌"},
  {q:"Wie viele Stunden braucht eine Schlange für die Verdauung einer großen Mahlzeit?",a:168,unit:"Stunden",hint:"Eine Woche für ein großes Tier.",emoji:"🐍"},
  {q:"Wie viele Gramm wächst ein Blauwal-Baby täglich?",a:90000,unit:"Gramm",hint:"90 kg täglich – 7 Monate lang gestillt.",emoji:"🐋"},
  {q:"Wie weit kann ein Albatros in einem einzigen Flug zurücklegen?",a:10000,unit:"km",hint:"Albatrosse umrunden die Erde im Südpolarmeer.",emoji:"🦅"},
  {q:"Wie viele Jahre ist ein Elefant geschlechtsreif?",a:14,unit:"Jahre",hint:"Elefantenbullen treten erst mit 14 in die Brunst.",emoji:"🐘"},
  {q:"Wie viele Liter Blut hat ein Nashorn?",a:20,unit:"Liter",hint:"Proportional weniger als ein Elefant.",emoji:"🦏"},
  {q:"Wie lang ist die Trächtigkeit eines Orcas in Monaten?",a:17,unit:"Monate",hint:"Eine der längsten Tragezeiten unter Meeressäugern.",emoji:"🐋"},
  {q:"Wie viele Gramm frisst ein Igel täglich?",a:70,unit:"Gramm",hint:"Insekten, Würmer und kleine Wirbeltiere.",emoji:"🦔"},
  {q:"Wie weit kann ein Springbock in einem Sprung?",a:15,unit:"Meter",hint:"Springböcke machen hohe Luftsprünge als Warnsignal.",emoji:"🦌"},
  {q:"Wie viele Federn verliert ein Vogel jährlich beim Mausern?",a:10000,unit:"Federn",hint:"Vögel erneuern ihr Gefieder jährlich komplett.",emoji:"🐦"},
  {q:"Wie schwer kann ein Riesenkalmars Mantel in kg werden?",a:150,unit:"kg",hint:"Riesenkalmare sind die größten wirbellosen Tiere.",emoji:"🦑"},
  {q:"Wie viele Stunden lebt eine Stubenfliege insgesamt?",a:500,unit:"Stunden",hint:"Nur 3 Wochen – in dieser Zeit legen sie Eier.",emoji:"🪰"},
  {q:"Wie viele Zellen hat ein Regenwurm?",a:1000,unit:"Segmente",hint:"Regenwürmer können in jedem Segment nachwachsen.",emoji:"🪱"},
  {q:"Wie weit wandert ein Monarch-Schmetterling pro Tag?",a:80,unit:"km",hint:"In 2 Monaten von Kanada nach Mexiko.",emoji:"🦋"},
  {q:"Wie schwer ist ein Schimpansen-Gehirn im Vergleich zum Menschen in %?",a:33,unit:"% des Menschengehirns",hint:"Schimpansen-Gehirn wiegt ~400g, menschliches ~1400g.",emoji:"🐒"},
  {q:"Wie viele Stunden täglich verbringt ein Orang-Utan in Bäumen?",a:24,unit:"Stunden",hint:"Orang-Utans sind die größten Baumklettertiere.",emoji:"🦧"},
  {q:"Wie viele Eier legt eine Ozean-Qualle pro Jahr?",a:45000,unit:"Eier",hint:"Quallen können sich auch vegetativ vermehren.",emoji:"🪼"},
  {q:"Wie weit kann eine Flossenfüßer-Robbe schwimmen täglich?",a:100,unit:"km",hint:"Robben sind ausdauernde Schwimmer.",emoji:"🦭"},
  {q:"Wie viele Jahre schläft ein Bär nicht im Winterschlaf?",a:0,unit:"Jahre (er schläft immer)",hint:"Bären halten keinen echten Winterschlaf sondern Winterruhe.",emoji:"🐻"},
  {q:"Wie schwer ist ein Erdwurm in Gramm?",a:5,unit:"Gramm",hint:"Ein normaler Regenwurm wiegt 3-10g.",emoji:"🪱"},
  {q:"Wie weit können Elefanten eine Wasserstelle riechen in km?",a:19,unit:"km",hint:"Elefanten haben den feinsten Geruchssinn aller Landtiere.",emoji:"🐘"},
  {q:"Wie viele Stunden braucht ein Schmetterling für die Metamorphose?",a:336,unit:"Stunden",hint:"2 Wochen im Kokon.",emoji:"🦋"},
  {q:"Wie viele kg Gras frisst ein Pferd täglich?",a:11,unit:"kg",hint:"Pferde sind reine Pflanzenfresser.",emoji:"🐴"},
  {q:"Wie weit kann ein Seehund tauchen in Metern?",a:300,unit:"Meter",hint:"Seehunde können bis zu 30 Minuten tauchen.",emoji:"🦭"},
  {q:"Wie viele Zähne hat ein Hecht?",a:700,unit:"Zähne",hint:"Hechte haben mehrere Reihen kleiner Zähne.",emoji:"🐟"},
  {q:"Wie schwer ist ein Marien-Käfer in Milligramm?",a:25,unit:"mg",hint:"Trotz winziger Größe frisst er täglich 100 Blattläuse.",emoji:"🐞"},
  {q:"Wie weit kann eine Wüstenspringmaus in einem Sprung?",a:3,unit:"Meter",hint:"Relative Sprungweite: 45x die eigene Körperlänge.",emoji:"🐭"},
  {q:"Wie viele Stunden lebt ein Schmetterlingsweibchen nach der Paarung?",a:2,unit:"Wochen",hint:"Manche Schmetterlinge leben nur wenige Tage.",emoji:"🦋"},
  {q:"Wie schwer ist ein Pelikan-Beutel wenn voll in Liter?",a:13,unit:"Liter",hint:"Der Kehlsack fasst mehr als der Magen.",emoji:"🐦"},
  {q:"Wie viele kg Fisch frisst ein ausgewachsener Weißer Hai täglich?",a:11,unit:"kg",hint:"Haie fressen selten – dafür viel auf einmal.",emoji:"🦈"},
  {q:"Wie weit können Wale Töne unter Wasser hören in km?",a:3000,unit:"km",hint:"Finnwale kommunizieren über Tausende Kilometer.",emoji:"🐋"},
  {q:"Wie viele Stunden täglich verbringt ein Faultier mit Bewegen?",a:3,unit:"Stunden",hint:"Der Rest des Tages wird mit Schlafen verbracht.",emoji:"🦥"},
  {q:"Wie schwer ist die Leber eines Weißen Hais in kg?",a:500,unit:"kg",hint:"Die enorme Leber dient als Auftriebsorgan.",emoji:"🦈"},
  {q:"Wie lang ist die Trächtigkeit eines Gürteltiers in Monaten?",a:4,unit:"Monate",hint:"Gürteltiere gebären immer eineiige Vierlings.",emoji:"🐾"},
  {q:"Wie weit springt ein Delfin aus dem Wasser in Metern?",a:6,unit:"Meter",hint:"Breaching ist ein wichtiges Kommunikationsmittel.",emoji:"🐬"},
  {q:"Wie viele Stunden lebt eine Stubenfliege als Larve?",a:120,unit:"Stunden",hint:"5 Tage als Maggot.",emoji:"🪰"},
  {q:"Wie schwer ist ein ausgewachsener Schimpansen in kg?",a:60,unit:"kg",hint:"Trotz geringerer Größe 6x stärker als ein Mensch.",emoji:"🐒"},
  {q:"Wie viele Tentakel hat eine Qualle?",a:80,unit:"Tentakel",hint:"Je nach Art zwischen 4 und hunderten Tentakeln.",emoji:"🪼"},
  {q:"Wie weit kann ein Krokodil aus dem Wasser herausspringen?",a:1.5,unit:"Meter",hint:"Krokodile sind überraschend agil.",emoji:"🐊"},
  {q:"Wie viele Gramm frisst eine Hausmaus täglich?",a:5,unit:"Gramm",hint:"Ein Siebtel ihres Körpergewichts täglich.",emoji:"🐭"},
  {q:"Wie schwer ist ein weiblicher Elefant maximal in Tonnen?",a:4,unit:"Tonnen",hint:"Weibliche Elefanten sind kleiner als die Männchen.",emoji:"🐘"},
  {q:"Wie viele Stunden kann ein Hamster täglich im Rad laufen?",a:8,unit:"Stunden",hint:"Hamster legen im Rad bis zu 20 km pro Nacht zurück.",emoji:"🐹"},
  {q:"Wie weit kann ein Kugelfisch aufblähen in cm Durchmesser?",a:90,unit:"cm",hint:"Kugelfische saugen Wasser an um sich aufzublähen.",emoji:"🐡"},
  {q:"Wie viele Liter Milch trinkt ein Elefantenbaby täglich?",a:10,unit:"Liter",hint:"Elefantenbabys werden 2-3 Jahre gestillt.",emoji:"🐘"},
  {q:"Wie schwer ist ein Spinnwebnetz in Milligramm?",a:0.5,unit:"Milligramm",hint:"Unglaublich leicht aber stärker als Stahl.",emoji:"🕸️"},
  {q:"Wie lang ist die Trächtigkeit eines Dachses in Wochen?",a:7,unit:"Wochen",hint:"Dachse legen die Trächtigkeit auf günstige Jahreszeiten aus.",emoji:"🦡"},
  {q:"Wie viele Stunden schläft ein Gorilla täglich?",a:12,unit:"Stunden",hint:"Gorillas bauen täglich neue Schlafnester.",emoji:"🦍"},
  {q:"Wie weit kann ein Weißer Hai seine Kiefer vorschnellen?",a:30,unit:"cm",hint:"Der Kiefer schnellt beim Beißen weit vor.",emoji:"🦈"},
  {q:"Wie viele Eier legt eine Riesenmeeresschildkröte in einem Nest?",a:100,unit:"Eier",hint:"Sie legen mehrere Male pro Saison.",emoji:"🐢"},
  {q:"Wie schwer ist ein Elefanten-Stoßzahn bei Geburt in Gramm?",a:0,unit:"Gramm",hint:"Stoßzähne wachsen erst nach der Geburt.",emoji:"🐘"},
  {q:"Wie viele Stunden täglich verbringt ein Fisch mit Schlafen?",a:4,unit:"Stunden",hint:"Fische schlafen mit offenen Augen.",emoji:"🐟"},
  {q:"Wie weit können Elefanten kommunizieren per Infraschall in km?",a:10,unit:"km",hint:"Tiefe Töne propagieren weit durch den Boden.",emoji:"🐘"},
  {q:"Wie viele kg Nahrung frisst ein Nilpferd täglich?",a:40,unit:"kg",hint:"Nilpferde fressen nachts an Land.",emoji:"🦛"},
  {q:"Wie schwer ist ein Gepard-Baby bei Geburt in Gramm?",a:250,unit:"Gramm",hint:"Geparden sind bei Geburt blind und hilflos.",emoji:"🐆"},
  {q:"Wie viele Stunden dauert eine Tiger-Jagd?",a:1,unit:"Stunde",hint:"Nur 1 von 10 Jagdversuchen ist erfolgreich.",emoji:"🐯"},
  {q:"Wie weit können Delfinpfeifen unter Wasser gehört werden in km?",a:40,unit:"km",hint:"Delfine kommunizieren über enorme Distanzen.",emoji:"🐬"},
  {q:"Wie viele Gramm wiegt ein Stachel einer Biene?",a:0.003,unit:"Gramm",hint:"Nur 3 Milligramm aber tödliches Gift.",emoji:"🐝"},
  {q:"Wie tief kann eine Langschwanzkatze ihr Revier markieren in Metern?",a:0.5,unit:"Meter Höhe",hint:"Markierungen werden auf Augenhöhe angebracht.",emoji:"🐈"},
  {q:"Wie viele Stunden täglich gehen Wölfe auf Jagd?",a:8,unit:"Stunden",hint:"Wölfe legen täglich 30-50 km zurück.",emoji:"🐺"},
];
