// 🐾 TIERREICH – Erwachsene – 250 Fragen
export default [
  {id:"tier_001",q:"Wie viele kg wiegen die Hoden eines Blauwals?",a:70,unit:"kg",hint:"Der Blauwal ist das größte Tier der Erde.",emoji:"🐋"},
  {id:"tier_002",q:"Wie oft pro Minute schlägt das Herz einer Maus?",a:600,unit:"Mal",hint:"Je kleiner das Tier, desto schneller das Herz.",emoji:"🐭"},
  {id:"tier_003",q:"Wie viele Tage trägt ein Elefant sein Junges?",a:660,unit:"Tage",hint:"~22 Monate – die längste Schwangerschaft aller Landsäugetiere.",emoji:"🐘"},
  {id:"tier_004",q:"Wie viele Liter Milch produziert eine Kuh pro Tag?",a:25,unit:"Liter",hint:"Hochleistungskühe können bis zu 50 Liter täglich geben.",emoji:"🐄"},
  {id:"tier_005",q:"Wie schwer kann ein Riesenkalmar-Auge in Gramm werden?",a:250,unit:"Gramm",hint:"Das größte Auge im Tierreich – so groß wie ein Fußball.",emoji:"🦑"},
  {id:"tier_006",q:"Wie viele km/h läuft ein Gepard maximal?",a:112,unit:"km/h",hint:"Er kann diese Höchstgeschwindigkeit nur kurz halten.",emoji:"🐆"},
  {id:"tier_007",q:"Wie viele Magen hat eine Kuh?",a:4,unit:"Mägen",hint:"Pansen, Netzmagen, Blättermagen und Labmagen.",emoji:"🐄"},
  {id:"tier_008",q:"Wie hoch kann ein Känguru springen in Metern?",a:3,unit:"Meter",hint:"Und in der Länge sogar bis zu 9 Meter weit.",emoji:"🦘"},
  {id:"tier_009",q:"Wie schwer wird ein ausgewachsener Gorilla maximal in kg?",a:270,unit:"kg",hint:"Trotz Größe sind Gorillas überwiegend Vegetarier.",emoji:"🦍"},
  {id:"tier_010",q:"Wie viele Stunden schläft ein Koala pro Tag?",a:22,unit:"Stunden",hint:"Eukalyptus ist schwer verdaulich – daher die Müdigkeit.",emoji:"🐨"},
  {id:"tier_011",q:"Wie viele km/h kann ein Schwertfisch schwimmen?",a:110,unit:"km/h",hint:"Der schnellste Fisch im Meer.",emoji:"🐟"},
  {id:"tier_012",q:"Wie lange lebt eine Königin-Biene in Jahren?",a:5,unit:"Jahre",hint:"Arbeiterinnen leben im Sommer nur 6 Wochen.",emoji:"🐝"},
  {id:"tier_013",q:"Wie viele Zähne hat ein erwachsenes Krokodil?",a:66,unit:"Zähne",hint:"Krokodile erneuern ihre Zähne bis zu 50 Mal im Leben.",emoji:"🐊"},
  {id:"tier_014",q:"Wie viele Eier legt eine Königin-Termite pro Tag?",a:30000,unit:"Eier",hint:"Die produktivste Mutter im Insektenreich.",emoji:"🐜"},
  {id:"tier_015",q:"Wie viele Liter Blut hat ein ausgewachsener Elefant?",a:400,unit:"Liter",hint:"Das Elefantenherz wiegt allein bis zu 30 kg.",emoji:"🐘"},
  {id:"tier_016",q:"Wie viele Mal kann ein Specht pro Sekunde hämmern?",a:20,unit:"Mal",hint:"Sein Gehirn ist durch Spezialanpassungen geschützt.",emoji:"🐦"},
  {id:"tier_017",q:"Wie schwer ist das schwerste Vogelei (Strauß) in kg?",a:1.35,unit:"kg",hint:"Strauße legen die größten Eier aller lebenden Vögel (Stand ~2024).",emoji:"🥚"},
  {id:"tier_018",q:"Wie lange kann ein Delphin den Atem anhalten in Minuten?",a:15,unit:"Minuten",hint:"Delfine schlafen mit einer Gehirnhälfte.",emoji:"🐬"},
  {id:"tier_019",q:"Wie viele Jahre kann ein Grönlandwal leben?",a:211,unit:"Jahre",hint:"Das langlebigste Säugetier der Erde.",emoji:"🐳"},
  {id:"tier_020",q:"Wie schwer ist die Zunge eines Blauwals in kg?",a:2700,unit:"kg",hint:"2,7 Tonnen – so schwer wie ein kleiner Elefant.",emoji:"🐋"},
  {id:"tier_021",q:"Wie viele Millionen Geruchsrezeptoren hat ein Hund?",a:300,unit:"Millionen",hint:"Menschen haben nur 6 Millionen – Hunde riechen 50x besser.",emoji:"🐕"},
  {id:"tier_022",q:"Wie viele Meter lang kann ein Bandwurm im Darm werden?",a:25,unit:"Meter",hint:"Bandwürmer können jahrelang unbemerkt leben.",emoji:"🪱"},
  {id:"tier_023",q:"Wie hoch ist der Blutdruck einer Giraffe in mmHg?",a:280,unit:"mmHg",hint:"Nötig um Blut 2 Meter nach oben ins Gehirn zu pumpen.",emoji:"🦒"},
  {id:"tier_024",q:"Wie viele kg Bambus frisst ein Pandabär täglich?",a:15,unit:"kg",hint:"Bambus ist sehr nährstoffarm – daher die riesige Menge.",emoji:"🐼"},
  {id:"tier_025",q:"Wie lange trägt ein Hai seine Jungen in Monaten?",a:24,unit:"Monate",hint:"Hammerhaie haben die längste Tragzeit.",emoji:"🦈"},
  {id:"tier_026",q:"Wie viele Augen hat eine Spinne?",a:8,unit:"Augen",hint:"Trotz 8 Augen sehen viele Spinnen sehr schlecht.",emoji:"🕷️"},
  {id:"tier_027",q:"Wie viele km/h erreicht ein Wanderfalke im Sturzflug?",a:320,unit:"km/h",hint:"Das schnellste Tier der Welt im Sturzflug.",emoji:"🦅"},
  {id:"tier_028",q:"Wie viele Tonnen wiegt ein ausgewachsener Blauwal?",a:150,unit:"Tonnen",hint:"Das größte Tier das je auf der Erde gelebt hat.",emoji:"🐋"},
  {id:"tier_029",q:"Wie viele Jahre kann eine Schnecke schlafen am Stück?",a:3,unit:"Jahre",hint:"Schnecken können bis zu 3 Jahre in Kältestarre verbringen.",emoji:"🐌"},
  {id:"tier_030",q:"Wie viele Volt Elektrizität erzeugt ein Zitteraal?",a:600,unit:"Volt",hint:"Volt – genug um einen Menschen zu betäuben.",emoji:"🐍"},
  {id:"tier_031",q:"Wie viele km/h rennt ein Nashorn?",a:55,unit:"km/h",hint:"Trotz ihrer Masse sind Nashörner erstaunlich schnell.",emoji:"🦏"},
  {id:"tier_032",q:"Wie viele Jahre alt kann ein Koi-Fisch werden?",a:226,unit:"Jahre",hint:"Hanako, ein Koi in Japan, lebte 226 Jahre.",emoji:"🐟"},
  {id:"tier_033",q:"Wie viele Knochen hat eine Schlange?",a:300,unit:"Knochen",hint:"Je nach Art zwischen 200 und 400 Knochen.",emoji:"🐍"},
  {id:"tier_034",q:"Wie viele Mal pro Sekunde schlägt eine Biene ihre Flügel?",a:200,unit:"Mal",hint:"Das erzeugt das charakteristische Summen.",emoji:"🐝"},
  {id:"tier_035",q:"Wie viele Liter Wasser saugt ein Elefant täglich?",a:190,unit:"Liter",hint:"Der Rüssel fasst bis zu 15 Liter auf einmal.",emoji:"🐘"},
  {id:"tier_036",q:"Wie viele Jahre kann eine Schildkröte ohne Nahrung überleben?",a:1,unit:"Jahr",hint:"Schildkröten können ihren Stoffwechsel extrem verlangsamen.",emoji:"🐢"},
  {id:"tier_037",q:"Wie weit kann ein Flugfisch aus dem Wasser gleiten in Metern?",a:400,unit:"Meter",hint:"Flugfische nutzen Wind und Auftrieb zum Gleiten.",emoji:"🐟"},
  {id:"tier_038",q:"Wie viele Kilogramm wiegt das Herz eines Blauwals?",a:180,unit:"Kilogramm",hint:"Das Herz ist so groß wie ein kleines Auto.",emoji:"❤️"},
  {id:"tier_039",q:"Wie viele Stunden schläft ein Löwe pro Tag?",a:20,unit:"Stunden",hint:"20 Stunden – fast so viel wie ein Koala (22h).",emoji:"🦁"},
  {id:"tier_040",q:"Wie viele Meter lang wird eine Riesenschlange (Pythons)?",a:7,unit:"Meter",hint:"Der Netzpython ist die längste Schlange der Welt.",emoji:"🐍"},
  {id:"tier_041",q:"Wie viele Tausend Eier legt ein weiblicher Oktopus?",a:400,unit:"Tausend Eier",hint:"Sie bewacht sie bis zum Schlüpfen und stirbt danach.",emoji:"🐙"},
  {id:"tier_042",q:"Wie viele km/h läuft ein Strauß?",a:70,unit:"km/h",hint:"Der schnellste laufende Vogel – und kann nicht fliegen.",emoji:"🦜"},
  {id:"tier_043",q:"Wie viele Zähne hat ein Weißer Hai?",a:300,unit:"Zähne",hint:"In mehreren Reihen – ständig nachwachsend.",emoji:"🦈"},
  {id:"tier_044",q:"Wie schwer wird ein Walross maximal in kg?",a:1700,unit:"kg",hint:"Männliche Walrosse sind deutlich schwerer als Weibchen.",emoji:"🦭"},
  {id:"tier_045",q:"Wie viele Wochen lebt eine Arbeiterin-Biene im Sommer?",a:6,unit:"Wochen",hint:"Nur 6 Wochen im Sommer – im Winter bis zu 6 Monate.",emoji:"🐝"},
  {id:"tier_046",q:"Wie viele Arten von Insekten gibt es auf der Erde (Millionen)?",a:1,unit:"Million Arten",hint:"Über 1 Million bekannte Arten – viele noch unentdeckt.",emoji:"🐛"},
  {id:"tier_047",q:"Wie viele Herzen hat ein Tintenfisch?",a:3,unit:"Herzen",hint:"Zwei pumpen Blut zu den Kiemen, eines zum Körper.",emoji:"🐙"},
  {id:"tier_048",q:"Wie lang ist die Zunge eines Chamäleons im Verhältnis zum Körper?",a:150,unit:"% Körperlänge",hint:"Die Zunge schlägt mit bis zu 26 km/h aus.",emoji:"🦎"},
  {id:"tier_049",q:"Wie viele Milliarden Geruchssensoren hat ein Bär?",a:2.1,unit:"Milliarden",hint:"Bären haben den schärfsten Geruchssinn aller Landtiere.",emoji:"🐻"},
  {id:"tier_050",q:"Wie schwer wird ein Polarbär maximal in kg?",a:700,unit:"kg",hint:"Das größte Landraubtier der Erde.",emoji:"🐻‍❄️"},
  {id:"tier_051",q:"Wie viele Beine hat ein Tausendfüßer durchschnittlich?",a:750,unit:"Beine",hint:"Nie genau 1000 – trotz des Namens.",emoji:"🐛"},
  {id:"tier_052",q:"Wie lange kann eine Stubenfliege fliegen ohne zu landen?",a:2,unit:"Stunden",hint:"Danach braucht sie Ruhe und Nahrung.",emoji:"🪰"},
  {id:"tier_053",q:"Wie viele Jahre alt wird eine Elefantenschildkröte maximal?",a:190,unit:"Jahre",hint:"Harriet lebte bis 2006 und war ~175 Jahre alt.",emoji:"🐢"},
  {id:"tier_054",q:"Wie viele km weit wandert ein Monarch-Schmetterling?",a:4000,unit:"km",hint:"Von Kanada bis Mexiko – jedes Jahr.",emoji:"🦋"},
  {id:"tier_055",q:"Wie viele Milligramm wiegt eine Hummel?",a:600,unit:"Milligramm",hint:"Trotz winziger Masse kann sie ein Vielfaches ihres Gewichts tragen.",emoji:"🐝"},
  {id:"tier_056",q:"Wie viele Stunden pro Tag sucht ein Nashorn Nahrung?",a:12,unit:"Stunden",hint:"Die Hälfte ihres Lebens verbringen sie mit Fressen.",emoji:"🦏"},
  {id:"tier_057",q:"Wie hoch springt ein Lachs flussaufwärts maximal in Metern?",a:3,unit:"Meter",hint:"Lachse springen Wasserfälle hinauf zu ihren Laichgebieten.",emoji:"🐟"},
  {id:"tier_058",q:"Wie viele Milligramm Seide produziert ein Seidenspinner für einen Kokon?",a:500,unit:"Milligramm",hint:"Aus einem Kokon kann man bis zu 1500 Meter Seide spinnen.",emoji:"🪱"},
  {id:"tier_059",q:"Wie viele Mikroliter Blut saugt ein Moskito beim Stechen?",a:3,unit:"Mikroliter",hint:"1-3 Mikroliter – das Gewicht einer Ameise.",emoji:"🦟"},
  {id:"tier_060",q:"Wie schwer wird ein ausgewachsener Nilpferd in Tonnen?",a:3,unit:"Tonnen",hint:"Nach Elefant und Nashorn das drittschwerste Landtier.",emoji:"🦛"},
  {id:"tier_061",q:"Wie viele Stunden schläft eine Giraffe täglich?",a:2,unit:"Stunden",hint:"Giraffen schlafen sehr wenig – in kurzen Phasen.",emoji:"🦒"},
  {id:"tier_062",q:"Wie viele Gramm wiegt ein Kolibri?",a:3,unit:"Gramm",hint:"Der kleinste Vogel der Welt wiegt weniger als eine Münze.",emoji:"🐦"},
  {id:"tier_063",q:"Wie oft schlägt das Herz eines Kolibris pro Minute?",a:1200,unit:"Mal",hint:"Das schnellste Herz aller Wirbeltiere.",emoji:"🐦"},
  {id:"tier_064",q:"Wie weit kann ein Känguru in einem einzigen Sprung?",a:9,unit:"Meter",hint:"Und dabei 3 Meter hoch.",emoji:"🦘"},
  {id:"tier_065",q:"Wie schwer ist das Gehirn eines Elefanten in kg?",a:5,unit:"kg",hint:"Das schwerste Gehirn aller Landtiere.",emoji:"🐘"},
  {id:"tier_066",q:"Wie viele Tage kann ein Albatros nonstop fliegen?",a:5,unit:"Tage",hint:"Albatrosse schlafen sogar im Flug und können Wochen in der Luft bleiben.",emoji:"🦅"},
  {id:"tier_067",q:"Wie lang ist die Trächtigkeit einer Maus in Tagen?",a:21,unit:"Tage",hint:"Mäuse können 10 Mal pro Jahr trächtig sein.",emoji:"🐭"},
  {id:"tier_068",q:"Wie viele Tausend Eier legt eine Königin-Ameise pro Jahr?",a:300,unit:"Tausend Eier",hint:"Manche Königinnen leben 30 Jahre und legen täglich 800 Eier.",emoji:"🐜"},
  {id:"tier_069",q:"Wie viele km/h läuft ein Schwarzbär?",a:48,unit:"km/h",hint:"Schneller als ein Mensch – man kann vor einem Bären nicht weglaufen.",emoji:"🐻"},
  {id:"tier_070",q:"Wie tief kann ein Potwal tauchen in Metern?",a:3000,unit:"Meter",hint:"Das tiefste Tauchgang eines Säugetiers.",emoji:"🐳"},
  {id:"tier_071",q:"Wie viele Kilogramm Nahrung frisst ein Gorilla täglich?",a:18,unit:"kg",hint:"Gorillas sind reine Vegetarier.",emoji:"🦍"},
  {id:"tier_072",q:"Wie lange lebt eine Drohnen-Biene?",a:90,unit:"Tage",hint:"Bis zur Herbsttracht – dann werden sie aus dem Volk vertrieben.",emoji:"🐝"},
  {id:"tier_073",q:"Wie viele Meter tief gräbt ein Maulwurf seine Tunnel?",a:1,unit:"Meter",hint:"Maulwürfe bauen Tunnel-Systeme über 200 Meter Länge.",emoji:"🐀"},
  {id:"tier_074",q:"Wie viele Jahre lebt ein wilder Schimpanse?",a:45,unit:"Jahre",hint:"In Gefangenschaft können sie über 60 Jahre alt werden.",emoji:"🐒"},
  {id:"tier_075",q:"Wie schwer ist der Schädel eines Tyrannosaurus Rex in kg?",a:600,unit:"kg",hint:"Einer der größten Schädel – ca. 600 kg bei einem 12m langen Tier.",emoji:"🦖"},
  {id:"tier_076",q:"Wie viele Federn hat ein Schwan?",a:25000,unit:"Federn",hint:"Wasservögel haben besonders viele Federn für die Isolation.",emoji:"🦢"},
  {id:"tier_077",q:"Wie viele Tage brütet ein Kaiserpinguin sein Ei?",a:63,unit:"Tage",hint:"63 Tage – ohne Nahrung im antarktischen Winter.",emoji:"🐧"},
  {id:"tier_078",q:"Wie weit kann ein Gepard in einem Sprung?",a:8,unit:"Meter",hint:"Geparden machen enorme Sprünge beim Jagen.",emoji:"🐆"},
  {id:"tier_079",q:"Wie viele Liter Wasser kann ein Elefant mit dem Rüssel aufnehmen?",a:15,unit:"Liter",hint:"Der Rüssel ist ein multifunktionales Werkzeug.",emoji:"🐘"},
  {id:"tier_080",q:"Wie viele km/h schlägt eine Mantis-Garnele zu?",a:80,unit:"km/h",hint:"Der schnellste Schlag im Tierreich.",emoji:"🦐"},
  {id:"tier_081",q:"Wie viele Leukozyten hat ein Hund pro Mikroliter Blut?",a:7000,unit:"pro µl",hint:"Ähnlich wie beim Menschen – 5.000–15.000 pro µl.",emoji:"🔬"},
  {id:"tier_082",q:"Wie viele Stunden schläft ein Delfin pro Tag?",a:8,unit:"Stunden",hint:"Immer mit einer Gehirnhälfte – die andere bleibt wach.",emoji:"🐬"},
  {id:"tier_083",q:"Wie schwer ist die Leber eines Blauwals in kg?",a:1000,unit:"kg",hint:"Alle Organe des Blauwals sind riesig.",emoji:"🐋"},
  {id:"tier_084",q:"Wie viele Eier kann eine Meeresschildkröte pro Saison legen?",a:200,unit:"Eier",hint:"Nur etwa 1% der Jungtiere überleben bis zur Adultheit.",emoji:"🐢"},
  {id:"tier_085",q:"Wie viele km weit fliegt ein Zugvogel im Jahr?",a:70000,unit:"km",hint:"Der Küstenseeschwalbe fliegt am weitesten.",emoji:"🐦"},
  {id:"tier_086",q:"Wie lange kann ein Kamel ohne Wasser überleben in Tagen?",a:15,unit:"Tage",hint:"Der Höcker speichert Fett, nicht Wasser.",emoji:"🐪"},
  {id:"tier_087",q:"Wie viele Stunden lebt eine Eintagsfliege als Imago?",a:24,unit:"Stunden",hint:"Als Larve lebt sie bis zu 3 Jahre.",emoji:"🪲"},
  {id:"tier_088",q:"Wie schwer ist das Gehirn eines Pottwals in kg?",a:7,unit:"kg",hint:"Das schwerste Gehirn aller bekannten Tiere.",emoji:"🐳"},
  {id:"tier_089",q:"Wie viele Flügelschläge macht eine Kolibri pro Sekunde?",a:80,unit:"Mal",hint:"So schnell, dass die Flügel unsichtbar werden.",emoji:"🐦"},
  {id:"tier_090",q:"Wie viele km/h läuft eine Gazelle?",a:90,unit:"km/h",hint:"Gazellen sind fast so schnell wie Geparden.",emoji:"🦌"},
  {id:"tier_091",q:"Wie tief gräbt ein Erdhörnchen seinen Bau in Metern?",a:3,unit:"Meter",hint:"Mit mehreren Ein- und Ausgängen.",emoji:"🐿️"},
  {id:"tier_092",q:"Wie viele Stacheln hat ein Igel?",a:6000,unit:"Stacheln",hint:"Stacheln sind modifizierte Haare.",emoji:"🦔"},
  {id:"tier_093",q:"Wie viele Jahre lebt ein Hummer?",a:100,unit:"Jahre",hint:"Hummer altern praktisch nicht – sie werden nur durch Jäger oder Hunger begrenzt.",emoji:"🦞"},
  {id:"tier_094",q:"Wie viele Mal schlägt das Herz einer Schlange pro Minute?",a:40,unit:"Mal",hint:"Schlangen haben einen viel langsameren Herzschlag als Säugetiere.",emoji:"🐍"},
  {id:"tier_095",q:"Wie viele Zentimeter weit kann eine Springspinne springen in cm?",a:50,unit:"cm",hint:"Das 50-fache ihrer Körperlänge.",emoji:"🕷️"},
  {id:"tier_096",q:"Wie viele kg frisst ein Tiger täglich?",a:8,unit:"kg",hint:"Tiger fressen seltener aber dafür viel auf einmal.",emoji:"🐯"},
  {id:"tier_097",q:"Wie viele Liter Speichel produziert eine Kuh täglich?",a:200,unit:"Liter",hint:"Wiederkäuen erfordert enorm viel Speichel.",emoji:"🐄"},
  {id:"tier_098",q:"Wie lange schläft ein Braunbär im Winterschlaf in Monaten?",a:6,unit:"Monate",hint:"Kein echter Tiefschlaf – sie können jederzeit aufwachen.",emoji:"🐻"},
  {id:"tier_099",q:"Wie viele Kilometer wandert ein Weißwal pro Jahr?",a:10000,unit:"km",hint:"Weißwale sind wanderfreudige Meeressäuger.",emoji:"🐳"},
  {id:"tier_100",q:"Wie viele Stunden lebt eine Biene nach dem Stich?",a:1,unit:"Stunde",hint:"Der Stachel verbleibt im Opfer – die Biene stirbt.",emoji:"🐝"},
  {id:"tier_101",q:"Wie schwer ist ein Elefantenzahn (Stoßzahn) maximal in kg?",a:100,unit:"kg",hint:"Stoßzähne wachsen ein Leben lang.",emoji:"🐘"},
  {id:"tier_102",q:"Wie viele Gramm wiegt ein neugeborenes Känguru?",a:1,unit:"Gramm",hint:"Das Joeys kriecht nach der Geburt in den Beutel.",emoji:"🦘"},
  {id:"tier_103",q:"Wie viele km/h schwimmt ein Blauwal?",a:30,unit:"km/h",hint:"Bei Gefahr können sie kurze Sprints einlegen.",emoji:"🐋"},
  {id:"tier_104",q:"Wie lange lebt eine Taschenkrabbe in Jahren?",a:100,unit:"Jahre",hint:"Krabben können sehr alt werden.",emoji:"🦀"},
  {id:"tier_105",q:"Wie viele Gramm wiegt ein Kolibri-Nest?",a:2,unit:"Gramm",hint:"Winzige Nester aus Spinnweben und Flechten.",emoji:"🐦"},
  {id:"tier_106",q:"Wie viele Stunden fliegt eine Hornisse täglich?",a:8,unit:"Stunden",hint:"Hornissen sind aktive Jäger.",emoji:"🐝"},
  {id:"tier_107",q:"Wie viele Stunden kann ein trainierter Delfin einen Ball auf der Nase balancieren?",a:3,unit:"Stunden",hint:"Delfine sind die intelligentesten Meerestiere.",emoji:"🐬"},
  {id:"tier_108",q:"Wie viele Jahre kann ein Krokodil ohne Nahrung überleben?",a:3,unit:"Jahre",hint:"Krokodile haben einen extrem niedrigen Stoffwechsel.",emoji:"🐊"},
  {id:"tier_109",q:"Wie schwer ist der Penis eines Blauwals in kg?",a:150,unit:"kg",hint:"Das größte Geschlechtsorgan im Tierreich.",emoji:"🐋"},
  {id:"tier_110",q:"Wie lange ist ein Blauwal-Penis in Metern?",a:2.7,unit:"Meter",hint:"Proportional zum Körper aber das absolut größte.",emoji:"🐋"},
  {id:"tier_111",q:"Wie viele Millionen Eizellen produziert eine Ozean-Sonnenblume pro Saison?",a:300,unit:"Millionen Eier",hint:"300 Millionen Eier – die meisten aller Wirbeltiere.",emoji:"🐟"},
  {id:"tier_112",q:"Wie viele Liter Blut pumpt ein Elefantenherz pro Minute?",a:300,unit:"Liter",hint:"Das Elefantenherz wiegt etwa 12 kg – das Blauwal-Herz 180 kg.",emoji:"🐘"},
  {id:"tier_113",q:"Wie viele Stunden kann eine Nacktmull-Ratte ohne Sauerstoff überleben?",a:18,unit:"Stunden",hint:"Nacktmull-Ratten sind gegen Sauerstoffmangel resistent.",emoji:"🐀"},
  {id:"tier_114",q:"Wie schwer ist das Gehirn eines Octopus in Gramm?",a:40,unit:"Gramm",hint:"Sehr klein aber extrem effizient.",emoji:"🐙"},
  {id:"tier_115",q:"Wie viele Millionen Chromatophoren hat ein Tintenfisch?",a:10,unit:"Millionen Chromatophoren",hint:"Diese Farbzellen ermöglichen blitzschnelle Farbwechsel.",emoji:"🦑"},
  {id:"tier_116",q:"Wie viele Meter lang ist ein Bandwurm maximal?",a:30,unit:"Meter",hint:"Fischbandwürmer können bis zu 30m lang werden.",emoji:"🪱"},
  {id:"tier_117",q:"Wie viele Grad kann eine Eule den Kopf drehen?",a:270,unit:"Grad",hint:"270 Grad – so können sie ohne Körperdrehung nach hinten schauen.",emoji:"🦉"},
  {id:"tier_118",q:"Wie schwer ist ein Ochsen-Frosch in kg?",a:3,unit:"kg",hint:"Der schwerste Frosch der Welt.",emoji:"🐸"},
  {id:"tier_119",q:"Wie viele Liter Honig produziert ein Bienenvolk pro Jahr?",a:30,unit:"Liter",hint:"Für ein Glas Honig fliegen Bienen 80.000 km.",emoji:"🍯"},
  {id:"tier_120",q:"Wie lang ist die Trächtigkeit eines Schwarzen Rhinozeros in Tagen?",a:450,unit:"Tage",hint:"15 Monate – eine der längsten Tragezeiten.",emoji:"🦏"},
  {id:"tier_121",q:"Wie viele Jahre lebt eine Eintagsfliegen-Larve bevor sie schlüpft?",a:3,unit:"Jahre",hint:"3 Jahre als Larve – dann nur 1 Tag als Erwachsener.",emoji:"🪲"},
  {id:"tier_122",q:"Wie tief taucht ein Kaiserpinguin maximal in Metern?",a:565,unit:"Meter",hint:"Der tieftauchende Vogel der Welt.",emoji:"🐧"},
  {id:"tier_123",q:"Wie viele Kilogramm wiegt das Herz eines Pferdes?",a:4.5,unit:"Kilogramm",hint:"Das große Herz ist der Schlüssel zur Ausdauer.",emoji:"🐴"},
  {id:"tier_124",q:"Wie weit kann ein Lemur springen in Metern?",a:10,unit:"Meter",hint:"Lemure sind erstaunliche Springer.",emoji:"🐒"},
  {id:"tier_125",q:"Wie viele km/h kann eine Libelle fliegen?",a:55,unit:"km/h",hint:"Eine der schnellsten fliegenden Insekten.",emoji:"🪲"},
  {id:"tier_126",q:"Wie lange lebt eine Dragonfly in Wochen als Erwachsener?",a:4,unit:"Wochen",hint:"Als Larve lebt sie bis zu 5 Jahre.",emoji:"🪲"},
  {id:"tier_127",q:"Wie schwer ist ein ausgewachsenes Nilpferd-Zahn in kg?",a:3,unit:"kg",hint:"Die Eckzähne sind reine Waffen.",emoji:"🦛"},
  {id:"tier_128",q:"Wie viele Tentakel hat ein Oktopus?",a:8,unit:"Tentakel",hint:"Jeder Arm hat eigene Nervenzellen.",emoji:"🐙"},
  {id:"tier_129",q:"Wie weit kann ein Flachlandgorilla seinen Ruf hören in km?",a:2,unit:"km",hint:"Gorillas kommunizieren über weite Distanzen.",emoji:"🦍"},
  {id:"tier_130",q:"Wie viele Mal pro Sekunde bewegt ein Schwertfisch die Schwanzflosse?",a:3,unit:"Mal",hint:"Kraftvolle langsame Bewegungen für hohe Geschwindigkeit.",emoji:"🐟"},
  {id:"tier_131",q:"Wie lang ist ein Elefantenrüssel durchschnittlich in cm?",a:250,unit:"cm",hint:"Der Rüssel ist die verlängerte Nase und Oberlippe – über 40.000 Muskeln.",emoji:"🐘"},
  {id:"tier_132",q:"Wie viele Liter Wasser trinkt ein Kamel auf einmal nach der Wüste?",a:100,unit:"Liter",hint:"In 13 Minuten kann ein Kamel 100 Liter trinken.",emoji:"🐪"},
  {id:"tier_133",q:"Wie schwer ist ein einzelner Blauwalhoden in kg?",a:35,unit:"kg",hint:"Zwei Hoden zusammen ~70 kg – das schwerste Geschlechtsorgan der Welt.",emoji:"🐋"},
  {id:"tier_134",q:"Wie viele Jahre leben Libellen-Larven im Wasser bevor sie schlüpfen?",a:4,unit:"Jahre",hint:"4 Jahre als Larve – dann ca. 4 Wochen als Erwachsene.",emoji:"🪲"},
  {id:"tier_135",q:"Wie viele Farben kann ein Tintenfisch gleichzeitig anzeigen?",a:30,unit:"Farben",hint:"Obwohl farbenblind – der Farbwechsel dient der Tarnung.",emoji:"🦑"},
  {id:"tier_136",q:"Wie schnell regeneriert ein Seestern seinen Arm in Wochen?",a:52,unit:"Wochen",hint:"Ein Jahr – und aus dem abgetrennten Arm wächst ein neuer Seestern.",emoji:"⭐"},
  {id:"tier_137",q:"Wie viele Mal kann sich die unsterbliche Qualle (Turritopsis dohrnii) theoretisch verjüngen?",a:1000,unit:"Mal (theoretisch unbegrenzt)",hint:"Sie kann biologisch unbegrenzt verjüngen – theoretisch unsterblich.",emoji:"🪼"},
  {id:"tier_138",q:"Wie viele km/h kann ein Gepard auf 100m beschleunigen?",a:75,unit:"km/h",hint:"Beschleunigung von 0 auf 75 in 2 Sekunden.",emoji:"🐆"},
  {id:"tier_139",q:"Wie viele Kilogramm wiegt ein ausgewachsener Jaguar?",a:100,unit:"kg",hint:"Der schwerste Großkatze Amerikas.",emoji:"🐆"},
  {id:"tier_140",q:"Wie viele Augen hat eine Libelle?",a:30000,unit:"Facetten",hint:"Zusammengesetzte Augen mit 30.000 Einzellinsen.",emoji:"🪲"},
  {id:"tier_141",q:"Wie viele Zentimeter weit kann ein Springer-Frosch springen in cm?",a:530,unit:"cm",hint:"Vielfaches der eigenen Körperlänge.",emoji:"🐸"},
  {id:"tier_142",q:"Wie viele Stunden täglich ist eine Hauskatze aktiv?",a:5,unit:"Stunden",hint:"Hauskatzen schlafen 16-20 Stunden täglich.",emoji:"🐱"},
  {id:"tier_143",q:"Wie viele Kilogramm Honig isst ein Bär in einem Sommer?",a:40,unit:"Kilogramm",hint:"40 kg Honig – Bären lieben Bienenstöcke.",emoji:"🐻"},
  {id:"tier_144",q:"Wie viele km/h kann ein Tintenfisch schwimmen?",a:40,unit:"km/h",hint:"Durch rückwärtiges Ausstoßen von Wasser.",emoji:"🦑"},
  {id:"tier_145",q:"Wie lang ist die Zunge eines Ameisenbären in cm?",a:60,unit:"cm",hint:"Die klebrige Zunge fährt 150 Mal pro Minute aus.",emoji:"🐜"},
  {id:"tier_146",q:"Wie viele Stunden am Tag weidet ein Pferd?",a:16,unit:"Stunden",hint:"Pferde fressen fast nonstop.",emoji:"🐴"},
  {id:"tier_147",q:"Wie schwer ist ein ausgewachsener Gorilla-Arm in kg?",a:15,unit:"kg",hint:"Gorillas sind 6 Mal stärker als Menschen.",emoji:"🦍"},
  {id:"tier_148",q:"Wie viele Liter Blut pumpt ein Giraffenherz pro Minute?",a:60,unit:"Liter",hint:"Das Giraffenherz wiegt 10 kg.",emoji:"🦒"},
  {id:"tier_149",q:"Wie viele km kann eine Wüstenameise ohne Orientierungshilfe navigieren?",a:50,unit:"km",hint:"Sie nutzen Polarisationsmuster des Himmels.",emoji:"🐜"},
  {id:"tier_150",q:"Wie viele Knochen hat ein Delfin?",a:200,unit:"Knochen",hint:"Delfine haben Knochen wo einst Hinterbeine waren.",emoji:"🐬"},
  {id:"tier_151",q:"Wie tief liegen die Jagdtunnel eines Maulwurfs typischerweise in cm?",a:20,unit:"cm",hint:"Jagdtunnel: 20cm tief – Haupttunnel bis 1m.",emoji:"🐀"},
  {id:"tier_152",q:"Wie viele Stunden kann ein Flamingo auf einem Bein stehen?",a:4,unit:"Stunden",hint:"Das Stehen auf einem Bein kostet weniger Energie.",emoji:"🦩"},
  {id:"tier_153",q:"Wie viele Ton frisst ein Blauwal an einem Tag?",a:3.6,unit:"Tonnen",hint:"Fast 4 Tonnen Krill täglich.",emoji:"🐋"},
  {id:"tier_154",q:"Wie weit kann eine Heuschrecke springen in Metern?",a:1,unit:"Meter",hint:"Das 20-fache ihrer eigenen Körperlänge.",emoji:"🦗"},
  {id:"tier_155",q:"Wie viele Jahre kann ein Elefant leben?",a:70,unit:"Jahre",hint:"In Gefangenschaft werden sie manchmal über 80.",emoji:"🐘"},
  {id:"tier_156",q:"Wie schwer ist ein neugeborener Blauwal in Tonnen?",a:2.7,unit:"Tonnen",hint:"Das Größte Neugeborene der Welt.",emoji:"🐋"},
  {id:"tier_157",q:"Wie viele Stunden schläft ein Totenkopf-Äffchen täglich?",a:11,unit:"Stunden",hint:"Totenkopfäffchen sind echte Schläfer.",emoji:"🐒"},
  {id:"tier_158",q:"Wie lang ist ein Elefantenrüssel in Metern?",a:2,unit:"Meter",hint:"Er hat über 40.000 Muskeln.",emoji:"🐘"},
  {id:"tier_159",q:"Wie viele Eier legt eine Königin-Ameise täglich?",a:800,unit:"Eier",hint:"Über ihr ganzes Leben bis zu 30 Millionen Eier.",emoji:"🐜"},
  {id:"tier_160",q:"Wie lang ist die Trächtigkeit eines Schwertwals in Monaten?",a:17,unit:"Monate",hint:"Orcas haben eine der längsten Tragezeiten.",emoji:"🐋"},
  {id:"tier_161",q:"Wie viele Stunden verbringt ein Tier im Wasser täglich (Nilpferd)?",a:16,unit:"Stunden",hint:"Nilpferde kühlen sich und schützen ihre Haut.",emoji:"🦛"},
  {id:"tier_162",q:"Wie viele Gramm wiegt ein Pfauenschwanz-Feder?",a:5,unit:"Gramm",hint:"Trotz ihrer Größe extrem leicht.",emoji:"🦚"},
  {id:"tier_163",q:"Wie weit kann ein Fliegendes Eichhörnchen gleiten in Metern?",a:90,unit:"Meter",hint:"Mit der Gleitfalte zwischen Vorder- und Hinterbeinen.",emoji:"🐿️"},
  {id:"tier_164",q:"Wie viele km/h läuft ein Erdferkel?",a:40,unit:"km/h",hint:"Überraschend schnell für ein scheinbar gemächliches Tier.",emoji:"🐷"},
  {id:"tier_165",q:"Wie schwer ist ein ausgewachsener männlicher Elefant-Rüsseltier in kg?",a:6000,unit:"kg",hint:"Afrikanische Elefanten sind schwerer als asiatische.",emoji:"🐘"},
  {id:"tier_166",q:"Wie viele Liter Milch trinkt ein Blauwal-Baby täglich?",a:600,unit:"Liter",hint:"Es wächst täglich um 90 kg.",emoji:"🐋"},
  {id:"tier_167",q:"Wie viele Stunden verbringt ein Flamingo im Wasser täglich?",a:12,unit:"Stunden",hint:"Flamingos filtern Nahrung aus Schlamm.",emoji:"🦩"},
  {id:"tier_168",q:"Wie lang ist die Trächtigkeit eines Nashorns in Monaten?",a:16,unit:"Monate",hint:"Nashörner bekommen nur alle 2-5 Jahre ein Junges.",emoji:"🦏"},
  {id:"tier_169",q:"Wie viele Milligramm wiegt eine Honigbiene?",a:100,unit:"Milligramm",hint:"Nur 100 Milligramm – aber immens wichtig.",emoji:"🐝"},
  {id:"tier_170",q:"Wie viele Jahre lebt ein Walross?",a:40,unit:"Jahre",hint:"Walrosse werden in der Wildnis bis zu 40 Jahre alt.",emoji:"🦭"},
  {id:"tier_171",q:"Wie schwer ist der Panzer einer Riesenschildkröte in kg?",a:30,unit:"kg",hint:"Der Panzer macht ein Drittel des Körpergewichts aus.",emoji:"🐢"},
  {id:"tier_172",q:"Wie viele Stunden am Tag reinigt sich eine Katze?",a:5,unit:"Stunden",hint:"Ein Drittel ihrer Wachzeit verbringen Katzen mit Putzen.",emoji:"🐱"},
  {id:"tier_173",q:"Wie viele Gramm wiegt ein Pinguin-Ei?",a:450,unit:"Gramm",hint:"Kaiserpinguin-Eier sind riesig im Verhältnis zum Körper.",emoji:"🐧"},
  {id:"tier_174",q:"Wie weit kann ein Gepard seinen Geruchssinn nutzen in km?",a:3,unit:"km",hint:"Geparden nutzen hauptsächlich das Sehen.",emoji:"🐆"},
  {id:"tier_175",q:"Wie viele Zähne hat ein Delfin?",a:100,unit:"Zähne",hint:"Delfine benutzen Zähne zum Fangen, nicht zum Kauen.",emoji:"🐬"},
  {id:"tier_176",q:"Wie lang ist die Zunge einer Kuh in cm?",a:45,unit:"cm",hint:"Kühe lecken sich die Nase damit sauber.",emoji:"🐄"},
  {id:"tier_177",q:"Wie viele Stacheln hat ein Stachelrochen?",a:1,unit:"Stachel",hint:"Nur ein Giftstachel – aber sehr schmerzhaft.",emoji:"🐟"},
  {id:"tier_178",q:"Wie schwer ist ein Gorilla-Silberrücken in kg?",a:250,unit:"kg",hint:"Silberrücken dominieren ihre Gruppe.",emoji:"🦍"},
  {id:"tier_179",q:"Wie weit kann ein Springhase springen in Metern?",a:3,unit:"Meter",hint:"Springhasen sind afrikanische Nager.",emoji:"🐇"},
  {id:"tier_180",q:"Wie viele km/h erreicht eine Schildkröte beim Schwimmen?",a:35,unit:"km/h",hint:"Lederschildkröten sind erstaunlich schnelle Schwimmer.",emoji:"🐢"},
  {id:"tier_181",q:"Wie viel Prozent ihres Körpergewichts frisst eine Raupe täglich?",a:200,unit:"% Körpergewicht",hint:"Raupen verdoppeln ihr Gewicht in Tagen.",emoji:"🐛"},
  {id:"tier_182",q:"Wie viele Tage lebt eine Hausfliegenlarve bis zur Verpuppung?",a:10,unit:"Tage",hint:"10 Tage als Made – dann 4-5 Tage als Puppe.",emoji:"🪰"},
  {id:"tier_183",q:"Wie lang ist der Dünndarm einer Kuh in Metern?",a:40,unit:"Meter",hint:"Kühe haben ein sehr langes Verdauungssystem.",emoji:"🐄"},
  {id:"tier_184",q:"Wie viele Liter Speichel produziert ein Pferd täglich?",a:40,unit:"Liter",hint:"Pferde brauchen viel Speichel für die Verdauung.",emoji:"🐴"},
  {id:"tier_185",q:"Wie viel Mal stärker als ein Mensch ist ein Schimpanse?",a:2,unit:"Mal stärker",hint:"Schimpansen sind doppelt so stark wie Menschen.",emoji:"🐒"},
  {id:"tier_186",q:"Wie weit wandert ein Elch pro Jahr in km?",a:300,unit:"km",hint:"Elche folgen Nahrung und Wetter.",emoji:"🦌"},
  {id:"tier_187",q:"Wie viele Tage braucht eine Schlange für die Verdauung einer großen Mahlzeit?",a:7,unit:"Tage",hint:"Eine Woche für ein großes Tier – Stoffwechsel läuft auf Hochtouren.",emoji:"🐍"},
  {id:"tier_188",q:"Wie viele Kilogramm wächst ein Blauwal-Baby täglich?",a:90,unit:"Kilogramm",hint:"90 kg täglich – 7 Monate lang gestillt.",emoji:"🐋"},
  {id:"tier_189",q:"Wie weit kann ein Albatros in einem einzigen Flug zurücklegen?",a:10000,unit:"km",hint:"Albatrosse umrunden die Erde im Südpolarmeer.",emoji:"🦅"},
  {id:"tier_190",q:"Wie viele Jahre ist ein Elefant geschlechtsreif?",a:14,unit:"Jahre",hint:"Elefantenbullen treten erst mit 14 in die Brunst.",emoji:"🐘"},
  {id:"tier_191",q:"Wie viele Liter Blut hat ein Nashorn?",a:20,unit:"Liter",hint:"Proportional weniger als ein Elefant.",emoji:"🦏"},
  {id:"tier_192",q:"Wie viele Gramm frisst ein Igel täglich?",a:70,unit:"Gramm",hint:"Insekten, Würmer und kleine Wirbeltiere.",emoji:"🦔"},
  {id:"tier_193",q:"Wie weit kann ein Springbock in einem Sprung?",a:15,unit:"Meter",hint:"Springböcke machen hohe Luftsprünge als Warnsignal.",emoji:"🦌"},
  {id:"tier_194",q:"Wie viele Federn verliert ein Vogel jährlich beim Mausern?",a:10000,unit:"Federn",hint:"Vögel erneuern ihr Gefieder jährlich komplett.",emoji:"🐦"},
  {id:"tier_195",q:"Wie schwer kann ein Riesenkalmars Mantel in kg werden?",a:150,unit:"kg",hint:"Riesenkalmare sind die größten wirbellosen Tiere.",emoji:"🦑"},
  {id:"tier_196",q:"Wie viele Wochen lebt eine Stubenfliege insgesamt?",a:3,unit:"Wochen",hint:"~3 Wochen – in dieser Zeit legen sie bis zu 500 Eier.",emoji:"🪰"},
  {id:"tier_197",q:"Wie viele Segmente hat ein Regenwurm?",a:120,unit:"Segmente",hint:"100-150 Segmente – bei Teilung kann der vordere Teil überleben.",emoji:"🪱"},
  {id:"tier_198",q:"Wie weit wandert ein Monarch-Schmetterling pro Tag?",a:80,unit:"km",hint:"In 2 Monaten von Kanada nach Mexiko.",emoji:"🦋"},
  {id:"tier_199",q:"Wie schwer ist ein Schimpansen-Gehirn im Vergleich zum Menschen in %?",a:33,unit:"% des Menschengehirns",hint:"Schimpansen-Gehirn wiegt ~400g, menschliches ~1400g.",emoji:"🐒"},
  {id:"tier_200",q:"Wie viele Stunden täglich verbringt ein Orang-Utan in Bäumen?",a:24,unit:"Stunden",hint:"Orang-Utans sind die größten Baumklettertiere.",emoji:"🦧"},
  {id:"tier_201",q:"Wie viele Eier legt eine Ozean-Qualle pro Jahr?",a:45000,unit:"Eier",hint:"Quallen können sich auch vegetativ vermehren.",emoji:"🪼"},
  {id:"tier_202",q:"Wie weit kann eine Flossenfüßer-Robbe schwimmen täglich?",a:100,unit:"km",hint:"Robben sind ausdauernde Schwimmer.",emoji:"🦭"},
  {id:"tier_203",q:"Wie schwer ist ein Erdwurm in Gramm?",a:5,unit:"Gramm",hint:"Ein normaler Regenwurm wiegt 3-10g.",emoji:"🪱"},
  {id:"tier_204",q:"Wie weit können Elefanten eine Wasserstelle riechen in km?",a:19,unit:"km",hint:"Elefanten haben den feinsten Geruchssinn aller Landtiere.",emoji:"🐘"},
  {id:"tier_205",q:"Wie viele Wochen verbringt ein Schmetterling im Kokon?",a:2,unit:"Wochen",hint:"Je nach Art 1-4 Wochen – dann schlüpft der Schmetterling.",emoji:"🦋"},
  {id:"tier_206",q:"Wie viele kg Gras frisst ein Pferd täglich?",a:11,unit:"kg",hint:"Pferde sind reine Pflanzenfresser.",emoji:"🐴"},
  {id:"tier_207",q:"Wie weit kann ein Seehund tauchen in Metern?",a:300,unit:"Meter",hint:"Seehunde können bis zu 30 Minuten tauchen.",emoji:"🦭"},
  {id:"tier_208",q:"Wie viele Zähne hat ein Hecht?",a:700,unit:"Zähne",hint:"Hechte haben mehrere Reihen kleiner Zähne.",emoji:"🐟"},
  {id:"tier_209",q:"Wie schwer ist ein Marien-Käfer in Milligramm?",a:25,unit:"mg",hint:"Trotz winziger Größe frisst er täglich 100 Blattläuse.",emoji:"🐞"},
  {id:"tier_210",q:"Wie weit kann eine Wüstenspringmaus in einem Sprung?",a:3,unit:"Meter",hint:"Relative Sprungweite: 45x die eigene Körperlänge.",emoji:"🐭"},
  {id:"tier_211",q:"Wie viele Wochen lebt ein Schmetterlingsweibchen nach der Paarung?",a:2,unit:"Wochen",hint:"Manche Schmetterlinge leben nur wenige Tage.",emoji:"🦋"},
  {id:"tier_212",q:"Wie viele Liter fasst der Kehlsack eines Pelikans wenn voll?",a:13,unit:"Liter",hint:"Der Kehlsack fasst mehr als der Magen.",emoji:"🐦"},
  {id:"tier_213",q:"Wie viele kg Fisch frisst ein ausgewachsener Weißer Hai täglich?",a:11,unit:"kg",hint:"Haie fressen selten – dafür viel auf einmal.",emoji:"🦈"},
  {id:"tier_214",q:"Wie weit können Wale Töne unter Wasser hören in km?",a:3000,unit:"km",hint:"Finnwale kommunizieren über Tausende Kilometer.",emoji:"🐋"},
  {id:"tier_215",q:"Wie viele Stunden täglich verbringt ein Faultier mit Bewegen?",a:3,unit:"Stunden",hint:"Der Rest des Tages wird mit Schlafen verbracht.",emoji:"🦥"},
  {id:"tier_216",q:"Wie schwer ist die Leber eines Weißen Hais in kg?",a:500,unit:"kg",hint:"Die enorme Leber dient als Auftriebsorgan.",emoji:"🦈"},
  {id:"tier_217",q:"Wie lang ist die Trächtigkeit eines Gürteltiers in Monaten?",a:4,unit:"Monate",hint:"Gürteltiere gebären immer eineiige Vierlings.",emoji:"🐾"},
  {id:"tier_218",q:"Wie weit springt ein Delfin aus dem Wasser in Metern?",a:6,unit:"Meter",hint:"Breaching ist ein wichtiges Kommunikationsmittel.",emoji:"🐬"},
  {id:"tier_219",q:"Wie viele Tage lebt eine Stubenfliegen-Made (Larve) bis zur Verpuppung?",a:8,unit:"Tage",hint:"Bei 25°C ca. 8 Tage – dann 4-5 Tage als Puppe.",emoji:"🪰"},
  {id:"tier_220",q:"Wie schwer ist ein ausgewachsener Schimpansen in kg?",a:60,unit:"kg",hint:"Trotz geringerer Größe 6x stärker als ein Mensch.",emoji:"🐒"},
  {id:"tier_221",q:"Wie viele Tentakel hat eine Qualle?",a:80,unit:"Tentakel",hint:"Je nach Art zwischen 4 und hunderten Tentakeln.",emoji:"🪼"},
  {id:"tier_222",q:"Wie weit kann ein Krokodil aus dem Wasser herausspringen?",a:1.5,unit:"Meter",hint:"Krokodile sind überraschend agil.",emoji:"🐊"},
  {id:"tier_223",q:"Wie viele Gramm frisst eine Hausmaus täglich?",a:5,unit:"Gramm",hint:"Ein Siebtel ihres Körpergewichts täglich.",emoji:"🐭"},
  {id:"tier_224",q:"Wie schwer ist ein weiblicher Elefant maximal in Tonnen?",a:4,unit:"Tonnen",hint:"Weibliche Elefanten sind kleiner als die Männchen.",emoji:"🐘"},
  {id:"tier_225",q:"Wie viele Stunden kann ein Hamster täglich im Rad laufen?",a:8,unit:"Stunden",hint:"Hamster legen im Rad bis zu 20 km pro Nacht zurück.",emoji:"🐹"},
  {id:"tier_226",q:"Wie viele Zentimeter weit kann ein Kugelfisch aufblähen in cm Durchmesser?",a:90,unit:"cm",hint:"Kugelfische saugen Wasser an um sich aufzublähen.",emoji:"🐡"},
  {id:"tier_227",q:"Wie viele Liter Milch trinkt ein Elefantenbaby täglich?",a:10,unit:"Liter",hint:"Elefantenbabys werden 2-3 Jahre gestillt.",emoji:"🐘"},
  {id:"tier_228",q:"Wie viele Milligramm wiegt ein kleines Spinnennetz?",a:1,unit:"Milligramm",hint:"0,5-2mg – leichter als eine Ameise aber stärker als Stahl.",emoji:"🕸️"},
  {id:"tier_229",q:"Wie lang ist die Trächtigkeit eines Dachses in Wochen?",a:7,unit:"Wochen",hint:"Dachse legen die Trächtigkeit auf günstige Jahreszeiten aus.",emoji:"🦡"},
  {id:"tier_230",q:"Wie viele Stunden schläft ein Gorilla täglich?",a:12,unit:"Stunden",hint:"Gorillas bauen täglich neue Schlafnester.",emoji:"🦍"},
  {id:"tier_231",q:"Wie viele Zentimeter weit kann ein Weißer Hai seine Kiefer vorschnellen?",a:30,unit:"cm",hint:"Der Kiefer schnellt beim Beißen weit vor.",emoji:"🦈"},
  {id:"tier_232",q:"Wie viele Eier legt eine Riesenmeeresschildkröte in einem Nest?",a:100,unit:"Eier",hint:"Sie legen mehrere Male pro Saison.",emoji:"🐢"},
  {id:"tier_233",q:"Wie viele Stunden täglich verbringt ein Fisch mit Schlafen?",a:4,unit:"Stunden",hint:"Fische schlafen mit offenen Augen.",emoji:"🐟"},
  {id:"tier_234",q:"Wie weit können Elefanten kommunizieren per Infraschall in km?",a:10,unit:"km",hint:"Tiefe Töne propagieren weit durch den Boden.",emoji:"🐘"},
  {id:"tier_235",q:"Wie viele kg Nahrung frisst ein Nilpferd täglich?",a:40,unit:"kg",hint:"Nilpferde fressen nachts an Land.",emoji:"🦛"},
  {id:"tier_236",q:"Wie schwer ist ein Gepard-Baby bei Geburt in Gramm?",a:250,unit:"Gramm",hint:"Geparden sind bei Geburt blind und hilflos.",emoji:"🐆"},
  {id:"tier_237",q:"Wie viele Stunden dauert eine Tiger-Jagd?",a:1,unit:"Stunde",hint:"Nur 1 von 10 Jagdversuchen ist erfolgreich.",emoji:"🐯"},
  {id:"tier_238",q:"Wie weit können Delfinpfeifen unter Wasser gehört werden in km?",a:40,unit:"km",hint:"Delfine kommunizieren über enorme Distanzen.",emoji:"🐬"},
  {id:"tier_239",q:"Wie viele Milligramm wiegt ein Stachel einer Biene?",a:3,unit:"Milligramm",hint:"Nur 3 Milligramm aber tödliches Gift.",emoji:"🐝"},
  {id:"tier_240",q:"Wie viele cm hoch markiert eine Langschwanzkatze ihr Revier?",a:50,unit:"cm",hint:"Auf Augenhöhe – damit andere Katzen es wahrnehmen.",emoji:"🐈"},
  {id:"tier_241",q:"Wie viele Stunden täglich gehen Wölfe auf Jagd?",a:8,unit:"Stunden",hint:"Wölfe legen täglich 30-50 km zurück.",emoji:"🐺"},
];
