// 🧪 WISSENSCHAFT & ERFINDUNGEN – Erwachsene – 250 Fragen
export default [
  {id:"wiss_001",q:"In welchem Jahr wurde das World Wide Web erfunden?",a:1989,unit:"Jahr",hint:"Tim Berners-Lee entwickelte es am CERN.",emoji:"🌐"},
  {id:"wiss_002",q:"Wie viele Elemente hat das Periodensystem?",a:118,unit:"Elemente",hint:"Das schwerste bestätigte Element ist Oganesson.",emoji:"⚗️"},
  {id:"wiss_003",q:"In welchem Jahr entdeckte Fleming Penicillin?",a:1928,unit:"Jahr",hint:"Er vergaß eine Petrischale – und rettete Millionen Leben.",emoji:"💊"},
  {id:"wiss_004",q:"Wie viele km/s ist die Lichtgeschwindigkeit?",a:299792,unit:"km/s",hint:"Die schnellste bekannte Geschwindigkeit im Universum.",emoji:"💡"},
  {id:"wiss_005",q:"In welchem Jahr erfand Morse den Telegraf?",a:1837,unit:"Jahr",hint:"Das erste elektrische Kommunikationsmittel.",emoji:"📡"},
  {id:"wiss_006",q:"Wie viele Grad Celsius ist der absolute Nullpunkt?",a:-273.15,unit:"°C",hint:"Null Kelvin – keine thermische Bewegung mehr.",emoji:"🌡️"},
  {id:"wiss_007",q:"In welchem Jahr erschien Darwins 'On the Origin of Species'?",a:1859,unit:"Jahr",hint:"Die Evolutionstheorie erschütterte die Welt.",emoji:"🐒"},
  {id:"wiss_008",q:"Wie viele Nanometer klein ist ein durchschnittliches Virus?",a:100,unit:"Nanometer",hint:"1000x kleiner als eine Zelle.",emoji:"🦠"},
  {id:"wiss_009",q:"In welchem Jahr erfand Edison die Glühbirne?",a:1879,unit:"Jahr",hint:"Am 22. Oktober 1879 – nach tausend Versuchen.",emoji:"💡"},
  {id:"wiss_010",q:"Wie viele Milliarden Neuronen hat das menschliche Gehirn?",a:86,unit:"Milliarden",hint:"Mit Billionen von Synapsen.",emoji:"🧠"},
  {id:"wiss_011",q:"In welchem Jahr entdeckte Einstein die Spezielle Relativitätstheorie?",a:1905,unit:"Jahr",hint:"Das Annus Mirabilis – Einsteins Wunderjahr.",emoji:"⚛️"},
  {id:"wiss_012",q:"Wie viele Grad dreht sich die Erde täglich um ihre Achse?",a:360,unit:"Grad",hint:"Einmal herum in 24 Stunden.",emoji:"🌍"},
  {id:"wiss_013",q:"In welchem Jahr erfand Gutenberg den Buchdruck?",a:1440,unit:"Jahr",hint:"Mit beweglichen Lettern.",emoji:"📚"},
  {id:"wiss_014",q:"Wie viele Atommassen hat Kohlenstoff?",a:12,unit:"amu",hint:"Kohlenstoff-12 ist der Standard.",emoji:"⚗️"},
  {id:"wiss_015",q:"In welchem Jahr startete die erste Rakete ins All (V2)?",a:1942,unit:"Jahr",hint:"Von Wernher von Braun entwickelt.",emoji:"🚀"},
  {id:"wiss_016",q:"Wie viele Grad Fahrenheit entsprechen 100°C?",a:212,unit:"°F",hint:"Siedepunkt des Wassers.",emoji:"🌡️"},
  {id:"wiss_017",q:"In welchem Jahr erfand Baird das Fernsehen?",a:1926,unit:"Jahr",hint:"John Logie Baird demonstrierte es 1926.",emoji:"📺"},
  {id:"wiss_018",q:"In welchem Jahr entdeckte Curie das Radium?",a:1898,unit:"Jahr",hint:"Marie und Pierre Curie zusammen.",emoji:"☢️"},
  {id:"wiss_019",q:"Wie viele km beträgt der Erdumfang am Äquator?",a:40075,unit:"km",hint:"Eratosthenes berechnete es bereits 240 v.Chr.",emoji:"🌍"},
  {id:"wiss_020",q:"In welchem Jahr erfand Bell das Telefon?",a:1876,unit:"Jahr",hint:"Am 10. März 1876 – erster Satz: 'Mr. Watson, come here'.",emoji:"📞"},
  {id:"wiss_021",q:"Wie viele Elektronen hat Sauerstoff?",a:8,unit:"Elektronen",hint:"Ordnungszahl 8 – auch 8 Protonen.",emoji:"⚗️"},
  {id:"wiss_022",q:"In welchem Jahr wurde das erste Antibiotikum (Penicillin) klinisch eingesetzt?",a:1942,unit:"Jahr",hint:"Im Zweiten Weltkrieg gerettet Millionen.",emoji:"💊"},
  {id:"wiss_023",q:"Wie viele m/s² ist die Erdbeschleunigung?",a:9.81,unit:"m/s²",hint:"g = 9,81 m/s² – Grundlage der Physik.",emoji:"⬇️"},
  {id:"wiss_024",q:"In welchem Jahr erfand Marconi das Radio?",a:1895,unit:"Jahr",hint:"Erste drahtlose Übertragung.",emoji:"📻"},
  {id:"wiss_025",q:"Wie viele Grad hat ein rechter Winkel?",a:90,unit:"Grad",hint:"Definition des rechten Winkels.",emoji:"📐"},
  {id:"wiss_026",q:"In welchem Jahr entdeckte Röntgen die Röntgenstrahlen?",a:1895,unit:"Jahr",hint:"Am 8. November 1895 zufällig entdeckt.",emoji:"🩻"},
  {id:"wiss_027",q:"Wie viele Bit hat ein Byte?",a:8,unit:"Bit",hint:"Bit = 1 Byte – Basis der Informatik.",emoji:"💻"},
  {id:"wiss_028",q:"In welchem Jahr erfand Diesel den Dieselmotor?",a:1897,unit:"Jahr",hint:"Rudolf Diesel erhielt 1897 das Patent.",emoji:"🔧"},
  {id:"wiss_029",q:"Wie viele Protonen hat Eisen?",a:26,unit:"Protonen",hint:"Fe – Ordnungszahl 26.",emoji:"⚗️"},
  {id:"wiss_030",q:"In welchem Jahr wurde der erste Laser gebaut?",a:1960,unit:"Jahr",hint:"Theodore Maiman baute ihn am 16. Mai 1960.",emoji:"💡"},
  {id:"wiss_031",q:"Wie viele Kalorie hat 1 Gramm Fett?",a:9,unit:"kcal/g",hint:"Fett hat mehr als doppelt so viel wie Kohlenhydrate.",emoji:"🔥"},
  {id:"wiss_032",q:"In welchem Jahr erfand Nobel das Dynamit?",a:1867,unit:"Jahr",hint:"Aus Nitroglycerin stabilisiert.",emoji:"💣"},
  {id:"wiss_033",q:"Wie viele Chromosomenpaare hat ein Mensch?",a:23,unit:"Paare",hint:"46 Chromosomen insgesamt.",emoji:"🧬"},
  {id:"wiss_034",q:"In welchem Jahr erschien das erste Computermodell (ENIAC)?",a:1945,unit:"Jahr",hint:"Electronic Numerical Integrator and Computer.",emoji:"💻"},
  {id:"wiss_035",q:"Wie viele Protonen hat Helium?",a:2,unit:"Protonen",hint:"Das zweitlichteste Element nach Wasserstoff.",emoji:"⚗️"},
  {id:"wiss_036",q:"In welchem Jahr entdeckte Watson und Crick die DNA-Doppelhelix?",a:1953,unit:"Jahr",hint:"Mit Rosalind Franklins entscheidenden Daten.",emoji:"🧬"},
  {id:"wiss_037",q:"Wie viele Grad Celsius siedet Alkohol (Ethanol)?",a:78.4,unit:"°C",hint:"Destillation nutzt diesen Siedepunkt.",emoji:"🌡️"},
  {id:"wiss_038",q:"In welchem Jahr erfand Watt die verbesserte Dampfmaschine?",a:1769,unit:"Jahr",hint:"Revolutionierte die Industrialisierung.",emoji:"⚙️"},
  {id:"wiss_039",q:"Wie viele Sextillionen Atome hat ein Mol Materie?",a:602,unit:"Sextillionen Atome",hint:"6,02 × 10²³ – die Avogadro-Zahl.",emoji:"⚗️"},
  {id:"wiss_040",q:"In welchem Jahr wurde das erste Mikroskop erfunden?",a:1590,unit:"Jahr",hint:"Zacharias Janssen in den Niederlanden.",emoji:"🔬"},
  {id:"wiss_041",q:"Wie viele Protonen hat Uran?",a:92,unit:"Protonen",hint:"Das schwerste natürlich vorkommende Element.",emoji:"☢️"},
  {id:"wiss_042",q:"In welchem Jahr erfand Archimedes sein berühmtes Prinzip?",a:250,unit:"v.Chr.",hint:"Im Bad – Heureka!",emoji:"🛁"},
  {id:"wiss_043",q:"Wie viele Kalorien braucht das Gehirn täglich?",a:300,unit:"kcal",hint:"20% des gesamten Energieverbrauchs.",emoji:"🧠"},
  {id:"wiss_044",q:"In welchem Jahr entdeckte Pasteur die Gärung durch Mikroorganismen?",a:1857,unit:"Jahr",hint:"Grundlage für Lebensmittelsicherheit.",emoji:"🧫"},
  {id:"wiss_045",q:"Wie viele Elektronen braucht Kohlenstoff für ein stabiles Außenorbital?",a:4,unit:"Elektronen",hint:"Kohlenstoff hat 4 Valenzelektronen.",emoji:"⚗️"},
  {id:"wiss_046",q:"In welchem Jahr wurde das erste Impfmittel entwickelt (Pocken)?",a:1796,unit:"Jahr",hint:"Edward Jenner impfte mit Kuhpockenvirus.",emoji:"💉"},
  {id:"wiss_047",q:"Wie viele Hz hört ein Mensch maximal?",a:20000,unit:"Hz",hint:"20 kHz – abnimmt mit dem Alter.",emoji:"👂"},
  {id:"wiss_048",q:"In welchem Jahr erfand Babbage den mechanischen Computer?",a:1837,unit:"Jahr",hint:"Die Analytical Engine – nicht fertiggestellt.",emoji:"⚙️"},
  {id:"wiss_049",q:"Wie viele Grad Celsius beträgt der Siedepunkt von Stickstoff?",a:-196,unit:"°C",hint:"Flüssiger Stickstoff für Kryonik.",emoji:"🌡️"},
  {id:"wiss_050",q:"In welchem Jahr entdeckte Hubble, dass das Universum expandiert?",a:1929,unit:"Jahr",hint:"Das Hubble-Gesetz der kosmischen Expansion.",emoji:"🌌"},
  {id:"wiss_051",q:"Wie viele Kilowattstunden Energie hat 1 kg Uran?",a:24000,unit:"kWh",hint:"Entspricht 3 Tonnen Kohle.",emoji:"⚡"},
  {id:"wiss_052",q:"In welchem Jahr erfand Faraday das Prinzip der elektromagnetischen Induktion?",a:1831,unit:"Jahr",hint:"Grundlage für alle Elektromotoren und Generatoren.",emoji:"⚡"},
  {id:"wiss_053",q:"Wie viele Meter lang ist die DNA in einer menschlichen Zelle wenn gestreckt?",a:2,unit:"Meter",hint:"Meter DNA in jedem Zellkern.",emoji:"🧬"},
  {id:"wiss_054",q:"In welchem Jahr wurde das erste Teleskop gebaut?",a:1608,unit:"Jahr",hint:"Hans Lippershey beantragte das Patent.",emoji:"🔭"},
  {id:"wiss_055",q:"Wie viele Nanometer klein ist ein DNA-Strang im Durchmesser?",a:2,unit:"Nanometer",hint:"Nm – unvorstellbar klein.",emoji:"🧬"},
  {id:"wiss_056",q:"In welchem Jahr erfand Braun die Elektronenröhre (Braunsche Röhre)?",a:1897,unit:"Jahr",hint:"Grundlage für alle frühen Bildschirme.",emoji:"📺"},
  {id:"wiss_057",q:"Wie viele Watt verbraucht das menschliche Gehirn?",a:20,unit:"Watt",hint:"Wie eine Energiesparbirne.",emoji:"💡"},
  {id:"wiss_058",q:"In welchem Jahr entdeckte Harvey den Blutkreislauf?",a:1628,unit:"Jahr",hint:"William Harvey veröffentlichte es 1628.",emoji:"❤️"},
  {id:"wiss_059",q:"Wie viele Protonen hat Kupfer?",a:29,unit:"Protonen",hint:"Cu – Ordnungszahl 29.",emoji:"⚗️"},
  {id:"wiss_060",q:"In welchem Jahr wurde das erste Fernrohr auf den Himmel gerichtet?",a:1609,unit:"Jahr",hint:"Galilei richtete es auf den Mond.",emoji:"🌙"},
  {id:"wiss_061",q:"Wie viele Grad Celsius schmilzt Stahl?",a:1370,unit:"°C",hint:"Je nach Legierung 1370-1520°C.",emoji:"🌡️"},
  {id:"wiss_062",q:"Wie viele Chromosomen hat eine Bananenzelle?",a:22,unit:"Chromosomen",hint:"Bananen haben 11 Chromosomenpaare.",emoji:"🍌"},
  {id:"wiss_063",q:"In welchem Jahr beschrieb Newton die drei Gesetze der Bewegung?",a:1687,unit:"Jahr",hint:"In 'Principia Mathematica'.",emoji:"🍎"},
  {id:"wiss_064",q:"Wie viele Volt hat eine standard AA-Batterie?",a:1.5,unit:"Volt",hint:"Kleinfinger-Batterie 1,5V.",emoji:"🔋"},
  {id:"wiss_065",q:"In welchem Jahr entdeckte Bohr das Atommodell?",a:1913,unit:"Jahr",hint:"Niels Bohrs Atommodell für Wasserstoff.",emoji:"⚛️"},
  {id:"wiss_066",q:"Wie viele mg Koffein hat eine Tasse Espresso?",a:80,unit:"mg",hint:"Eine Tasse Kaffee hat 60-100 mg.",emoji:"☕"},
  {id:"wiss_067",q:"In welchem Jahr erfand Turing das theoretische Konzept der universellen Maschine?",a:1936,unit:"Jahr",hint:"Die Turing-Maschine – Grundlage aller Computer.",emoji:"💻"},
  {id:"wiss_068",q:"Wie viele Gram Sauerstoff braucht man für 1g Wasserstoff zur Verbrennung?",a:8,unit:"Gramm",hint:"H₂ + O → H₂O – Massenverhältnis 1:8.",emoji:"⚗️"},
  {id:"wiss_069",q:"In welchem Jahr wurde das Internet-Protokoll TCP/IP entwickelt?",a:1974,unit:"Jahr",hint:"Vint Cerf und Bob Kahn entwickelten es.",emoji:"🌐"},
  {id:"wiss_070",q:"Wie viele Tonnen Atommüll produziert ein Kernkraftwerk pro Jahr?",a:30,unit:"Tonnen",hint:"Hochradioaktiver Abfall – Problem für Jahrtausende.",emoji:"☢️"},
  {id:"wiss_071",q:"In welchem Jahr entdeckte Semmelweis die Bedeutung des Händewaschens?",a:1847,unit:"Jahr",hint:"Er starb ohne Anerkennung – heute gefeiert.",emoji:"🧼"},
  {id:"wiss_072",q:"Wie viele Protonen hat Blei?",a:82,unit:"Protonen",hint:"Pb – Ordnungszahl 82.",emoji:"⚗️"},
  {id:"wiss_073",q:"In welchem Jahr wurde das erste GPS-System aktiviert?",a:1995,unit:"Jahr",hint:"Vollständige Nutzung seit 1995.",emoji:"🛰️"},
  {id:"wiss_074",q:"Wie viele Atome sind in einem Wassermolekül?",a:3,unit:"Atome",hint:"H₂O – 2 Wasserstoff + 1 Sauerstoff.",emoji:"💧"},
  {id:"wiss_075",q:"In welchem Jahr erfand Pasteur die Pasteurisierung?",a:1864,unit:"Jahr",hint:"Für Wein – dann auf Milch angewendet.",emoji:"🍷"},
  {id:"wiss_076",q:"Wie viele Volt erzeugt eine Solarzelle?",a:0.5,unit:"Volt",hint:"Einzelne Zelle – viele werden in Serie geschaltet.",emoji:"☀️"},
  {id:"wiss_077",q:"In welchem Jahr entdeckte Dalton das Atommodell?",a:1803,unit:"Jahr",hint:"John Daltons erste Atomtheorie.",emoji:"⚛️"},
  {id:"wiss_078",q:"Wie viele Zentimeter ist ein Meter?",a:100,unit:"cm",hint:"Definition des metrischen Systems.",emoji:"📏"},
  {id:"wiss_079",q:"In welchem Jahr erfand Otto den Viertaktmotor?",a:1876,unit:"Jahr",hint:"Nikolaus Otto – Grundlage aller heutigen Autos.",emoji:"🚗"},
  {id:"wiss_080",q:"Wie viele Protonen hat Silber?",a:47,unit:"Protonen",hint:"Ag – Ordnungszahl 47.",emoji:"🪙"},
  {id:"wiss_081",q:"In welchem Jahr entdeckte Hertz die elektromagnetischen Wellen?",a:1887,unit:"Jahr",hint:"Heinrich Hertz – die Einheit trägt seinen Namen.",emoji:"📡"},
  {id:"wiss_082",q:"Wie viele Kilogramm wiegt ein Liter Benzin?",a:0.74,unit:"kg",hint:"Benzin ist leichter als Wasser.",emoji:"⛽"},
  {id:"wiss_083",q:"In welchem Jahr erfand Aspirin Bayer?",a:1897,unit:"Jahr",hint:"Felix Hoffmann synthetisierte es 1897.",emoji:"💊"},
  {id:"wiss_084",q:"Wie viele Volt hat eine Autobatterie?",a:12,unit:"Volt",hint:"Standard 12V Bleiakkumulator.",emoji:"🔋"},
  {id:"wiss_085",q:"Wie viele Megapixel hatte die erste iPhone-Kamera?",a:2,unit:"Megapixel",hint:"2007 – heute haben iPhones über 48 MP.",emoji:"📱"},
  {id:"wiss_086",q:"In welchem Jahr wurde das erste Smartphone (IBM Simon) erfunden?",a:1994,unit:"Jahr",hint:"IBM Simon war der erste Touchscreen-Phone.",emoji:"📱"},
  {id:"wiss_087",q:"Wie viele Grad Celsius schmilzt Butter?",a:32,unit:"°C",hint:"Je nach Zusammensetzung 28-36°C.",emoji:"🧈"},
  {id:"wiss_088",q:"In welchem Jahr erfand Benz das erste benzinbetriebene Auto?",a:1885,unit:"Jahr",hint:"Benz Patent-Motorwagen – 3 Räder, 0,75 PS.",emoji:"🚗"},
  {id:"wiss_089",q:"Wie viele Gramm wiegt ein Mol Wasser?",a:18,unit:"Gramm",hint:"H₂O: 2×1 + 16 = 18 g/mol.",emoji:"💧"},
  {id:"wiss_090",q:"In welchem Jahr wurde CRISPR-Cas9 entdeckt?",a:2012,unit:"Jahr",hint:"Charpentier und Doudna – Nobelpreis 2020.",emoji:"🧬"},
  {id:"wiss_091",q:"Wie viele Milliarden Bit hat 1 Gigabyte?",a:8.6,unit:"Milliarden Bit",hint:"1 GB = 8×1024×1024×1024 Bit = ~8,6 Milliarden Bit.",emoji:"💻"},
  {id:"wiss_092",q:"In welchem Jahr erfand Fleming die erste Elektronenröhre (Diode)?",a:1904,unit:"Jahr",hint:"John Ambrose Fleming erfand die Vakuumdiode – Vorläufer des Transistors.",emoji:"⚡"},
  {id:"wiss_093",q:"Wie viele Grad Celsius friert Meerwasser?",a:-1.8,unit:"°C",hint:"Salzwasser friert bei niedrigeren Temperaturen.",emoji:"🌊"},
  {id:"wiss_094",q:"In welchem Jahr entdeckte Jenner den Impfstoff gegen Pocken?",a:1796,unit:"Jahr",hint:"Der erste Impfstoff in der Geschichte.",emoji:"💉"},
  {id:"wiss_095",q:"Wie viele Protonen hat Stickstoff?",a:7,unit:"Protonen",hint:"N – Ordnungszahl 7.",emoji:"⚗️"},
  {id:"wiss_096",q:"In welchem Jahr erfand Shockley den Transistor?",a:1947,unit:"Jahr",hint:"Bell Labs – Grundlage aller modernen Elektronik.",emoji:"⚡"},
  {id:"wiss_097",q:"Wie viele Tesla hat ein starker MRI-Scanner?",a:3,unit:"Tesla",hint:"Tesla ist Standard in Krankenhäusern.",emoji:"🧲"},
  {id:"wiss_098",q:"In welchem Jahr entdeckte Mendeleev das Periodensystem?",a:1869,unit:"Jahr",hint:"Er sagte Elemente vorher die noch nicht entdeckt waren.",emoji:"⚗️"},
  {id:"wiss_099",q:"Wie viele Grad Celsius kocht destilliertes Wasser?",a:100,unit:"°C",hint:"Bei Normaldruck 1 Atmosphäre.",emoji:"🌡️"},
  {id:"wiss_100",q:"In welchem Jahr erfand Zeppelin das Luftschiff?",a:1900,unit:"Jahr",hint:"Erster Testflug des LZ 1 am 2. Juli 1900.",emoji:"🛸"},
  {id:"wiss_101",q:"Wie viele Gramm wiegt ein Mol Natriumchlorid (Kochsalz)?",a:58.4,unit:"Gramm",hint:"Na(23) + Cl(35,5) = 58,5 g/mol.",emoji:"🧂"},
  {id:"wiss_102",q:"In welchem Jahr wurde das erste schwarze Loch fotografiert?",a:2019,unit:"Jahr",hint:"Event Horizon Telescope – M87*.",emoji:"🌑"},
  {id:"wiss_103",q:"Wie viele Nanometer sind 1 Mikrometer?",a:1000,unit:"Nanometer",hint:"1 µm = 1000 nm.",emoji:"📏"},
  {id:"wiss_104",q:"In welchem Jahr entdeckte Boyle das Gasgesetz?",a:1662,unit:"Jahr",hint:"Boyle's Law: pV = konstant.",emoji:"⚗️"},
  {id:"wiss_105",q:"Wie viele Ampere fließen durch eine 100W Glühbirne (230V)?",a:0.43,unit:"Ampere",hint:"I = P/U = 100/230 ≈ 0,43A.",emoji:"💡"},
  {id:"wiss_106",q:"In welchem Jahr erfand Tesla den Wechselstrommotor?",a:1887,unit:"Jahr",hint:"Grundlage aller modernen Elektromotoren.",emoji:"⚡"},
  {id:"wiss_107",q:"Wie viele Millionen Tonnen CO₂ emittiert die Welt täglich?",a:100,unit:"Millionen Tonnen",hint:"37 Milliarden Tonnen pro Jahr.",emoji:"🌍"},
  {id:"wiss_108",q:"In welchem Jahr entdeckte Hooke die Zelle?",a:1665,unit:"Jahr",hint:"Robert Hooke betrachtete Kork unterm Mikroskop.",emoji:"🔬"},
  {id:"wiss_109",q:"Wie viele Protonen hat Phosphor?",a:15,unit:"Protonen",hint:"P – Ordnungszahl 15.",emoji:"⚗️"},
  {id:"wiss_110",q:"In welchem Jahr wurde das erste Kernkraftwerk gebaut?",a:1954,unit:"Jahr",hint:"Obninsk in der Sowjetunion.",emoji:"⚡"},
  {id:"wiss_111",q:"Wie viele Atome hat ein Glukose-Molekül?",a:24,unit:"Atome",hint:"C₆H₁₂O₆ = 6+12+6 = 24 Atome.",emoji:"⚗️"},
  {id:"wiss_112",q:"In welchem Jahr erfand Siemens den elektrischen Aufzug?",a:1880,unit:"Jahr",hint:"Werner von Siemens in Mannheim.",emoji:"🏗️"},
  {id:"wiss_113",q:"Wie viele Grad Celsius schmilzt Glas?",a:700,unit:"°C",hint:"Je nach Zusammensetzung 700-1200°C.",emoji:"🌡️"},
  {id:"wiss_114",q:"In welchem Jahr entdeckte Galvani den 'Tierstrom'?",a:1780,unit:"Jahr",hint:"Grundlage für Elektrochemie und Batterien.",emoji:"⚡"},
  {id:"wiss_115",q:"Wie viele Gramm wiegt 1 Liter Luft?",a:1.3,unit:"g",hint:"1,29 Gramm pro Liter bei 20°C.",emoji:"💨"},
  {id:"wiss_116",q:"In welchem Jahr erfand Swan die Kohlenfadenlampe?",a:1878,unit:"Jahr",hint:"Joseph Swan – kurz vor Edison.",emoji:"💡"},
  {id:"wiss_117",q:"Wie viele Chromosomen hat eine Fruchtfliege?",a:8,unit:"Chromosomen",hint:"Drosophila – wichtigstes Modellorganismus.",emoji:"🪰"},
  {id:"wiss_118",q:"In welchem Jahr beschrieb Kepler die Planetenbewegungen?",a:1609,unit:"Jahr",hint:"Keplers erste und zweite Gesetze.",emoji:"🪐"},
  {id:"wiss_119",q:"Wie viele Grad dreht ein Polarisationsfilter das Licht?",a:90,unit:"Grad",hint:"Zwei gekreuzte Polarisationsfilter blocken alles.",emoji:"💡"},
  {id:"wiss_120",q:"In welchem Jahr entdeckte Halley den Kometen (der nach ihm benannt ist)?",a:1705,unit:"Jahr",hint:"Er sagte die Wiederkehr vorher – Recht hatte er.",emoji:"☄️"},
  {id:"wiss_121",q:"Wie viele Milliarden Basenpaare hat das menschliche Genom?",a:3,unit:"Milliarden Basenpaare",hint:"3 Milliarden Basenpaare in der menschlichen DNA.",emoji:"🧬"},
  {id:"wiss_122",q:"In welchem Jahr wurde das erste Elektroauto produziert?",a:1884,unit:"Jahr",hint:"Thomas Parker baute es in London.",emoji:"🚗"},
  {id:"wiss_123",q:"Wie viele Volt erzeugt eine Brennstoffzelle?",a:1.2,unit:"Volt",hint:"Je nach Typ 0,5-1,2V pro Zelle.",emoji:"⚡"},
  {id:"wiss_124",q:"In welchem Jahr erfand Braille das Blindenschriftsystem?",a:1824,unit:"Jahr",hint:"Louis Braille war 15 Jahre alt.",emoji:"👆"},
  {id:"wiss_125",q:"Wie viele Protonen hat Calcium?",a:20,unit:"Protonen",hint:"Ca – Ordnungszahl 20.",emoji:"⚗️"},
  {id:"wiss_126",q:"In welchem Jahr startete Voyager 1?",a:1977,unit:"Jahr",hint:"Am 5. September 1977 – jetzt außerhalb des Sonnensystems.",emoji:"🚀"},
  {id:"wiss_127",q:"Wie viele m/s² beträgt die Schwerebeschleunigung auf dem Mond?",a:1.62,unit:"m/s²",hint:"1/6 der Erdgravitation.",emoji:"🌙"},
  {id:"wiss_128",q:"In welchem Jahr entdeckte Hubble die Andromeda-Galaxie als eigene Galaxie?",a:1925,unit:"Jahr",hint:"Davor dachte man es sei ein Nebel.",emoji:"🌌"},
  {id:"wiss_129",q:"Wie viele Neutronen hat Carbon-14?",a:8,unit:"Neutronen",hint:"6 Protonen + 8 Neutronen = Masse 14.",emoji:"⚗️"},
  {id:"wiss_130",q:"In welchem Jahr erfand Otis den Sicherheitsaufzug?",a:1852,unit:"Jahr",hint:"Elisha Otis - Bremse verhinderte Absturz.",emoji:"🏗️"},
  {id:"wiss_131",q:"Wie viele Zyklen pro Sekunde hat europäischer Wechselstrom?",a:50,unit:"Hz",hint:"In Europa ist 50Hz Standard.",emoji:"⚡"},
  {id:"wiss_132",q:"In welchem Jahr wurde der erste Transistorradio verkauft?",a:1954,unit:"Jahr",hint:"Texas Instruments TR-1.",emoji:"📻"},
  {id:"wiss_133",q:"Wie viele Grad Celsius schmilzt Kupfer?",a:1085,unit:"°C",hint:"Niedrigerer Schmelzpunkt als Eisen.",emoji:"🌡️"},
  {id:"wiss_134",q:"In welchem Jahr entdeckte Dalton das Gesetz der multiplen Proportionen?",a:1803,unit:"Jahr",hint:"Grundlage der modernen Chemie.",emoji:"⚗️"},
  {id:"wiss_135",q:"Wie viele Nanometer groß ist ein Wasserstoffatom?",a:0.1,unit:"Nanometer",hint:"0,1 nm = 1 Ångström.",emoji:"⚛️"},
  {id:"wiss_136",q:"In welchem Jahr erfand Volta die Batterie?",a:1800,unit:"Jahr",hint:"Voltasche Säule – erste Batterie.",emoji:"🔋"},
  {id:"wiss_137",q:"Wie viele Protonen hat Natrium?",a:11,unit:"Protonen",hint:"Na – Ordnungszahl 11.",emoji:"⚗️"},
  {id:"wiss_138",q:"In welchem Jahr startete der erste Sputnik?",a:1957,unit:"Jahr",hint:"Am 4. Oktober 1957.",emoji:"🛰️"},
  {id:"wiss_139",q:"Wie viele Kilowatt hat 1 PS?",a:0.736,unit:"kW",hint:"1 PS = 0,736 kW = 736 Watt.",emoji:"⚡"},
  {id:"wiss_140",q:"In welchem Jahr entwickelte Bohr sein Atommodell für Wasserstoff?",a:1913,unit:"Jahr",hint:"Niels Bohrs Atommodell erklärte die Wasserstoff-Spektrallinien.",emoji:"⚛️"},
  {id:"wiss_141",q:"Wie viele Atome hat ein Methanmolekül?",a:5,unit:"Atome",hint:"CH₄ = 1 Kohlenstoff + 4 Wasserstoff.",emoji:"⚗️"},
  {id:"wiss_142",q:"In welchem Jahr erfand Morse seinen berühmten Code?",a:1838,unit:"Jahr",hint:"Punkte und Striche – revolutionäre Kommunikation.",emoji:"📡"},
  {id:"wiss_143",q:"Wie viele Grad Fahrenheit ist der Körper bei Fieber?",a:101,unit:"°F",hint:"38°C = 100,4°F – Fieber beginnt.",emoji:"🌡️"},
  {id:"wiss_144",q:"In welchem Jahr entdeckte Mendel die Vererbungsgesetze?",a:1865,unit:"Jahr",hint:"Gregor Mendels Erbsenexperimente.",emoji:"🌱"},
  {id:"wiss_145",q:"Wie viele Protonen hat Chlor?",a:17,unit:"Protonen",hint:"Cl – Ordnungszahl 17.",emoji:"⚗️"},
  {id:"wiss_146",q:"In welchem Jahr wurde das erste iPhone veröffentlicht?",a:2007,unit:"Jahr",hint:"Steve Jobs: 'One more thing...'",emoji:"📱"},
  {id:"wiss_147",q:"Wie viele Megawatt erzeugt ein durchschnittliches Kernkraftwerk?",a:1000,unit:"Megawatt",hint:"1 GW – genug für eine Millionenstadt.",emoji:"⚡"},
  {id:"wiss_148",q:"In welchem Jahr erfand Zuckerberg Facebook?",a:2004,unit:"Jahr",hint:"Als Harvard-Student.",emoji:"📱"},
  {id:"wiss_149",q:"Wie viele Gramm Glukose hat das Gehirn täglich als Mindestbedarf?",a:120,unit:"Gramm",hint:"120g täglich – für Denkprozesse.",emoji:"🧠"},
  {id:"wiss_150",q:"In welchem Jahr wurde das erste GPS-Satellit gestartet?",a:1978,unit:"Jahr",hint:"Block I GPS-Satellit.",emoji:"🛰️"},
  {id:"wiss_151",q:"Wie viele Grad Celsius beträgt die Raumtemperatur?",a:20,unit:"°C",hint:"18-22°C ist Standard.",emoji:"🌡️"},
  {id:"wiss_152",q:"In welchem Jahr entdeckte Koch den Tuberkulose-Erreger?",a:1882,unit:"Jahr",hint:"Robert Koch am 24. März 1882.",emoji:"🔬"},
  {id:"wiss_153",q:"Wie viele Protonen hat Aluminium?",a:13,unit:"Protonen",hint:"Al – Ordnungszahl 13.",emoji:"⚗️"},
  {id:"wiss_154",q:"In welchem Jahr erfand Braun das Fernsehen (Braunsche Röhre)?",a:1897,unit:"Jahr",hint:"Karl Ferdinand Braun.",emoji:"📺"},
  {id:"wiss_155",q:"Wie viele Kilokalorien hat 1 Gramm Protein?",a:4,unit:"kcal/g",hint:"Gleich wie Kohlenhydrate.",emoji:"💪"},
  {id:"wiss_156",q:"In welchem Jahr entdeckte Planck die Quantentheorie?",a:1900,unit:"Jahr",hint:"Das Plancksche Wirkungsquantum h.",emoji:"⚛️"},
  {id:"wiss_157",q:"In welchem Jahr wurde der erste Elektromagnet gebaut?",a:1825,unit:"Jahr",hint:"William Sturgeon baute ihn.",emoji:"🧲"},
  {id:"wiss_158",q:"In welchem Jahr entdeckte Becquerel die Radioaktivität?",a:1896,unit:"Jahr",hint:"Henri Becquerel – zufällig beim Fotografieren.",emoji:"☢️"},
  {id:"wiss_159",q:"Wie viele Protonen hat Magnesium?",a:12,unit:"Protonen",hint:"Mg – Ordnungszahl 12.",emoji:"⚗️"},
  {id:"wiss_160",q:"In welchem Jahr baute Wright Brothers das erste Motorflugzeug?",a:1903,unit:"Jahr",hint:"12 Sekunden – 37 Meter – die Welt veränderte sich.",emoji:"✈️"},
  {id:"wiss_161",q:"Wie viele Hertz hat menschliche Sprache durchschnittlich?",a:250,unit:"Hz",hint:"Grundfrequenz der menschlichen Stimme.",emoji:"🎤"},
  {id:"wiss_162",q:"In welchem Jahr wurde Chlor als Element identifiziert?",a:1774,unit:"Jahr",hint:"Karl Wilhelm Scheele entdeckte es.",emoji:"⚗️"},
  {id:"wiss_163",q:"Wie viele Kilowattstunden Energie produziert ein Windrad pro Tag?",a:10000,unit:"kWh/Tag",hint:"Ein 2-MW-Windrad erzeugt 10.000-15.000 kWh täglich.",emoji:"🌬️"},
  {id:"wiss_164",q:"Wie viele Grad Celsius beträgt die Temperatur im Erdkern?",a:6000,unit:"°C",hint:"Ähnlich wie die Sonnenoberfläche.",emoji:"🌋"},
  {id:"wiss_165",q:"In welchem Jahr entdeckte Ampère das Gesetz des elektrischen Stroms?",a:1820,unit:"Jahr",hint:"André-Marie Ampère – die Einheit trägt seinen Namen.",emoji:"⚡"},
  {id:"wiss_166",q:"Wie viele Milliarden Transistoren hat ein moderner CPU-Chip (z.B. Apple M3)?",a:25,unit:"Milliarden",hint:"Apple M3 (2023): 25 Milliarden – Spitzenmodelle noch mehr.",emoji:"💻"},
  {id:"wiss_167",q:"In welchem Jahr wurde das erste KI-Programm geschrieben?",a:1951,unit:"Jahr",hint:"Logic Theorist von Newell und Simon.",emoji:"🤖"},
  {id:"wiss_168",q:"Wie viele Gramm wiegt 1 Mol Kohlendioxid?",a:44,unit:"Gramm",hint:"C(12) + 2×O(16) = 44 g/mol.",emoji:"⚗️"},
  {id:"wiss_169",q:"Wie viele Kilojoule hat 1 Kilokalorien?",a:4.18,unit:"kJ",hint:"1 kcal = 4,18 kJ.",emoji:"🔥"},
  {id:"wiss_170",q:"In welchem Jahr erschien Einsteins allgemeine Relativitätstheorie?",a:1915,unit:"Jahr",hint:"Erweiterung der speziellen Theorie.",emoji:"⚛️"},
  {id:"wiss_171",q:"Wie viele Elektronen fasst die erste Elektronenschale eines Atoms?",a:2,unit:"Elektronen",hint:"K-Schale – maximal 2 Elektronen.",emoji:"⚛️"},
  {id:"wiss_172",q:"In welchem Jahr wurde der erste Microchip erfunden?",a:1958,unit:"Jahr",hint:"Jack Kilby bei Texas Instruments.",emoji:"💻"},
  {id:"wiss_173",q:"Wie viele Kilopascal beträgt der Luftdruck auf Meereshöhe?",a:101.3,unit:"kPa",hint:"1 Atmosphäre = 101.325 Pa.",emoji:"🌬️"},
  {id:"wiss_174",q:"In welchem Jahr entdeckte Maxwell die elektromagnetischen Wellen theoretisch?",a:1864,unit:"Jahr",hint:"James Clerk Maxwell – Hertz bewies es 1887.",emoji:"📡"},
  {id:"wiss_175",q:"In welchem Jahr wurde das Hubble Space Telescope gestartet?",a:1990,unit:"Jahr",hint:"Am 24. April 1990 mit Discovery.",emoji:"🔭"},
  {id:"wiss_176",q:"Wie viele Protonen hat Silizium?",a:14,unit:"Protonen",hint:"Si – Ordnungszahl 14 – Basis der Halbleiter.",emoji:"💻"},
  {id:"wiss_177",q:"In welchem Jahr entdeckte Marie Curie Polonium?",a:1898,unit:"Jahr",hint:"Benannt nach ihrer Heimat Polen.",emoji:"☢️"},
  {id:"wiss_178",q:"Wie viele Joule hat 1 Kalorie?",a:4.184,unit:"Joule",hint:"1 cal = 4,184 J.",emoji:"🔥"},
  {id:"wiss_179",q:"In welchem Jahr wurde der erste Barcode verwendet?",a:1974,unit:"Jahr",hint:"Am 26. Juni 1974 – Wrigley's Kaugummi in Ohio.",emoji:"📊"},
  {id:"wiss_180",q:"Wie viele Protonen hat Schwefel?",a:16,unit:"Protonen",hint:"S – Ordnungszahl 16.",emoji:"⚗️"},
  {id:"wiss_181",q:"In welchem Jahr wurde das erste Farbfoto aufgenommen?",a:1861,unit:"Jahr",hint:"James Clerk Maxwell – ein Schottenkaro.",emoji:"📷"},
  {id:"wiss_182",q:"Wie viele Ampere darf eine Haushaltssteckdose maximal führen?",a:16,unit:"Ampere",hint:"Standard 230V/16A in Deutschland.",emoji:"⚡"},
  {id:"wiss_183",q:"In welchem Jahr entdeckte Ohm das Ohmsche Gesetz?",a:1827,unit:"Jahr",hint:"Georg Simon Ohm: U = R × I.",emoji:"⚡"},
  {id:"wiss_184",q:"Wie viele Monate dauert es bis der Körper alle Zellen erneuert hat?",a:84,unit:"Monate",hint:"7 Jahre – manche Zellen halten ein Leben lang.",emoji:"🔄"},
  {id:"wiss_185",q:"In welchem Jahr erfand Zeiss die erste apochromatische Linse?",a:1886,unit:"Jahr",hint:"Grundlage moderner Mikroskopie.",emoji:"🔬"},
  {id:"wiss_186",q:"Wie viele Kilogramm Sauerstoff atmet ein Mensch täglich?",a:0.55,unit:"kg",hint:"550 Gramm Sauerstoff täglich.",emoji:"💨"},
  {id:"wiss_187",q:"In welchem Jahr entdeckte Haber die Ammoniaksynthese?",a:1909,unit:"Jahr",hint:"Fritz Haber – Grundlage der Düngemittelproduktion.",emoji:"⚗️"},
  {id:"wiss_188",q:"Wie viele Protonen hat Zink?",a:30,unit:"Protonen",hint:"Zn – Ordnungszahl 30.",emoji:"⚗️"},
  {id:"wiss_189",q:"Wie viele Elektronen fasst die zweite Schale eines Atoms?",a:8,unit:"Elektronen",hint:"L-Schale – maximal 8 Elektronen.",emoji:"⚛️"},
  {id:"wiss_190",q:"In welchem Jahr erfand Schottky die Röhrendiode?",a:1914,unit:"Jahr",hint:"Grundlage der Radiotechnik.",emoji:"📡"},
  {id:"wiss_191",q:"Wie viele Kilometer pro Stunde ist die Schallgeschwindigkeit in Luft?",a:1235,unit:"km/h",hint:"343 m/s = 1235 km/h.",emoji:"🔊"},
  {id:"wiss_192",q:"In welchem Jahr entdeckte Lavoisier das Gesetz der Massenerhaltung?",a:1789,unit:"Jahr",hint:"Antoine Lavoisier – Vater der modernen Chemie.",emoji:"⚗️"},
  {id:"wiss_193",q:"Wie viele Protonen hat Titan?",a:22,unit:"Protonen",hint:"Ti – Ordnungszahl 22.",emoji:"⚗️"},
  {id:"wiss_194",q:"In welchem Jahr erschien Hawkings 'A Brief History of Time'?",a:1988,unit:"Jahr",hint:"Millionenfach verkauft – allgemein verständliche Physik.",emoji:"📚"},
  {id:"wiss_195",q:"Wie viele Grad Celsius beträgt die Temperatur im Erdmantel?",a:3000,unit:"°C",hint:"Zwischen Erdkruste und Kern.",emoji:"🌋"},
  {id:"wiss_196",q:"Wie viele Kilobyte hat 1 Megabyte?",a:1024,unit:"Kilobyte",hint:"Binärsystem – 2¹⁰ = 1024.",emoji:"💻"},
  {id:"wiss_197",q:"In welchem Jahr wurde die erste MRT-Maschine gebaut?",a:1977,unit:"Jahr",hint:"Erste Ganzkörper-MRT von Damadian.",emoji:"🏥"},
  {id:"wiss_198",q:"Wie viele Sekunden hat ein Tag?",a:86400,unit:"Sekunden",hint:"24 × 60 × 60 = 86.400.",emoji:"⏰"},
  {id:"wiss_199",q:"In welchem Jahr erfand Banting Insulin?",a:1921,unit:"Jahr",hint:"Frederick Banting rettete Millionen Diabetiker.",emoji:"💉"},
  {id:"wiss_200",q:"Wie viele Protonen hat Mangan?",a:25,unit:"Protonen",hint:"Mn – Ordnungszahl 25.",emoji:"⚗️"},
  {id:"wiss_201",q:"Wie viele Millionen Grad Celsius beträgt die Kerntemperatur der Sonne?",a:15,unit:"Millionen °C",hint:"15 Millionen Grad – Kernfusion findet dort statt.",emoji:"☀️"},
  {id:"wiss_202",q:"In welchem Jahr wurde das Elektron entdeckt?",a:1897,unit:"Jahr",hint:"J.J. Thomson beim Kathodenstrahlexperiment.",emoji:"⚛️"},
  {id:"wiss_203",q:"Wie viele Elektronen fasst die dritte Elektronenschale?",a:18,unit:"Elektronen",hint:"M-Schale – maximal 18 Elektronen.",emoji:"⚛️"},
  {id:"wiss_204",q:"In welchem Jahr wurde das erste HIV-Virus isoliert?",a:1983,unit:"Jahr",hint:"Françoise Barré-Sinoussi – Nobelpreis 2008.",emoji:"🔬"},
  {id:"wiss_205",q:"Wie viele Protonen hat Gold (Ordnungszahl)?",a:79,unit:"Protonen",hint:"Au – Ordnungszahl 79.",emoji:"🪙"},
  {id:"wiss_206",q:"In welchem Jahr erfand Shannon die Informationstheorie?",a:1948,unit:"Jahr",hint:"Claude Shannon – Grundlage der digitalen Kommunikation.",emoji:"💻"},
  {id:"wiss_207",q:"Wie viele Kilowattstunden enthält 1 kg Wasserstoff?",a:33,unit:"kWh",hint:"Drei Mal mehr als Benzin pro kg.",emoji:"⚡"},
  {id:"wiss_208",q:"In welchem Jahr wurde die erste Solarzelle entwickelt?",a:1954,unit:"Jahr",hint:"Bell Labs – 6% Wirkungsgrad.",emoji:"☀️"},
  {id:"wiss_209",q:"Wie viele Protonen hat Brom?",a:35,unit:"Protonen",hint:"Br – Ordnungszahl 35.",emoji:"⚗️"},
  {id:"wiss_210",q:"In welchem Jahr entdeckte Celsius die Celsiusskala?",a:1742,unit:"Jahr",hint:"Anders Celsius – ursprünglich umgekehrt.",emoji:"🌡️"},
  {id:"wiss_211",q:"Wie viele Nanometer ist ein Atom groß?",a:0.1,unit:"Nanometer",hint:"0,1-0,5 nm je nach Element.",emoji:"⚛️"},
  {id:"wiss_212",q:"In welchem Jahr erhielt Karl Ferdinand Braun das Patent für die Braunsche Röhre?",a:1897,unit:"Jahr",hint:"Braun erhielt 1909 den Nobelpreis für Physik gemeinsam mit Marconi.",emoji:"⚡"},
  {id:"wiss_213",q:"Wie viele Tonnen CO₂ speichert ein Hektar Wald pro Jahr?",a:2,unit:"Tonnen",hint:"Durchschnittlicher mitteleuropäischer Mischwald.",emoji:"🌳"},
  {id:"wiss_214",q:"In welchem Jahr entdeckte Hardy die Hardy-Weinberg-Gleichung?",a:1908,unit:"Jahr",hint:"Grundlage der Populationsgenetik.",emoji:"🧬"},
  {id:"wiss_215",q:"Wie viele Protonen hat Nickel?",a:28,unit:"Protonen",hint:"Ni – Ordnungszahl 28.",emoji:"⚗️"},
  {id:"wiss_216",q:"In welchem Jahr baute Daimler das erste Motorrad?",a:1885,unit:"Jahr",hint:"Gottlieb Daimler – der Reitwagen.",emoji:"🏍️"},
  {id:"wiss_217",q:"Wie viele Atome hat ein Schwefelsäuremolekül (H₂SO₄)?",a:7,unit:"Atome",hint:"2H + S + 4O = 7 Atome.",emoji:"⚗️"},
  {id:"wiss_218",q:"In welchem Jahr erschien das erste Lehrbuch der Chemie?",a:1789,unit:"Jahr",hint:"Lavoisiers Traité élémentaire de chimie.",emoji:"📚"},
  {id:"wiss_219",q:"Wie viele Grad Celsius schmilzt Aluminium?",a:660,unit:"°C",hint:"Deutlich niedrigerer Schmelzpunkt als Stahl.",emoji:"🌡️"},
  {id:"wiss_220",q:"Wie viele Billionen Tonnen Sauerstoff enthält die Erdatmosphäre?",a:1200,unit:"Billionen Tonnen",hint:"1,2 × 10¹⁵ kg Sauerstoff.",emoji:"💨"},
  {id:"wiss_221",q:"In welchem Jahr entdeckte Rutherford den Atomkern?",a:1909,unit:"Jahr",hint:"Goldfolienexperiment – der Kern ist klein und dicht.",emoji:"⚛️"},
  {id:"wiss_222",q:"Wie viele Protonen hat Kobalt?",a:27,unit:"Protonen",hint:"Co – Ordnungszahl 27.",emoji:"⚗️"},
  {id:"wiss_223",q:"In welchem Jahr erfand Pascal die Rechenmaschine Pascaline?",a:1642,unit:"Jahr",hint:"Konnte addieren und subtrahieren.",emoji:"🔢"},
  {id:"wiss_224",q:"Wie viele Lumen erzeugt eine standard 60-Watt-Glühbirne?",a:800,unit:"Lumen",hint:"Eine LED-Birne braucht nur 8-10 Watt dafür.",emoji:"💡"},
  {id:"wiss_225",q:"In welchem Jahr entdeckte Dirac die Antimaterie theoretisch?",a:1928,unit:"Jahr",hint:"Paul Dirac sagte Positronen vorher.",emoji:"⚛️"},
  {id:"wiss_226",q:"Wie viele Gramm wiegt 1 Mol Calciumcarbonat (Kalk)?",a:100,unit:"Gramm",hint:"CaCO₃ = 40+12+(3×16) = 100 g/mol.",emoji:"⚗️"},
  {id:"wiss_227",q:"In welchem Jahr erfand Tesla das drahtlose Energieübertragungsprinzip?",a:1891,unit:"Jahr",hint:"Wardenclyffe Tower war sein gescheitertes Projekt.",emoji:"⚡"},
  {id:"wiss_228",q:"Wie viele Kilojoule hat 1 Gramm Fett?",a:37,unit:"kJ",hint:"1g Fett = 9 kcal = 37 kJ.",emoji:"🔥"},
  {id:"wiss_229",q:"In welchem Jahr erschien Newtons Opticks?",a:1704,unit:"Jahr",hint:"Über Licht, Prismen und Farben.",emoji:"🌈"},
  {id:"wiss_230",q:"Wie viele Protonen hat Vanadium?",a:23,unit:"Protonen",hint:"V – Ordnungszahl 23.",emoji:"⚗️"},
  {id:"wiss_231",q:"In welchem Jahr erfand Geiger den Geigerzähler?",a:1908,unit:"Jahr",hint:"Hans Geiger – zur Messung ionisierender Strahlung.",emoji:"☢️"},
  {id:"wiss_232",q:"Wie viele Gramm wiegt 1 Mol Methan?",a:16,unit:"Gramm",hint:"CH₄ = 12+4 = 16 g/mol.",emoji:"⚗️"},
  {id:"wiss_233",q:"In welchem Jahr entdeckte Heisenberg das Unschärfeprinzip?",a:1927,unit:"Jahr",hint:"Ort und Impuls nicht gleichzeitig messbar.",emoji:"⚛️"},
  {id:"wiss_234",q:"Wie viele Elektronen fasst die vierte Schale?",a:32,unit:"Elektronen",hint:"N-Schale – maximal 32 Elektronen.",emoji:"⚛️"},
  {id:"wiss_235",q:"In welchem Jahr entdeckte Compton den Compton-Effekt?",a:1923,unit:"Jahr",hint:"Licht verhält sich wie Teilchen.",emoji:"⚛️"},
  {id:"wiss_236",q:"Wie viele Meter pro Stunde bewegen sich Elektronen in einem Kabel?",a:0.3,unit:"m/h",hint:"Nur 0,3m/h – aber die elektromagn. Welle pflanzt sich mit Lichtgeschwindigkeit fort.",emoji:"⚡"}
];
