// 💩 KÖRPER & EKEL – Erwachsene – 250 Fragen
export default [
  {q:"Wie viele Liter Pupsgase produziert ein Mensch pro Tag?",a:1.5,unit:"Liter",hint:"14-23 Mal täglich ein Pups.",emoji:"💨"},
  {q:"Wie viele Gramm wiegt ein normaler Stuhlgang?",a:150,unit:"Gramm",hint:"100-200g ist der Normalbereich.",emoji:"💩"},
  {q:"Wie viele Mal pro Tag pupst ein Mensch durchschnittlich?",a:14,unit:"Mal",hint:"Komplett normal – Frauen auch.",emoji:"💨"},
  {q:"Wie viele Liter Schleim produziert die Nase täglich?",a:1,unit:"Liter",hint:"Ein Liter täglich – fast alles schlucken wir.",emoji:"🤧"},
  {q:"Wie viele Milliliter Schmalz scheidet ein Ohr pro Monat aus?",a:1,unit:"ml",hint:"1-2 ml Ohrenschmalz monatlich.",emoji:"👂"},
  {q:"Wie viele Gramm Bakterien sind im Darm eines Menschen?",a:200,unit:"Gramm",hint:"Das Darmmikrobiom wiegt 200g.",emoji:"🦠"},
  {q:"Wie viele Mal im Leben wird ein Mensch kotzen (übergeben)?",a:200,unit:"Mal",hint:"Durchschnittlich über ein Leben.",emoji:"🤢"},
  {q:"Wie viele Liter Magensäure werden beim Erbrechen hochgepumpt?",a:0.3,unit:"Liter",hint:"300ml bei einem typischen Erbrechen.",emoji:"🤮"},
  {q:"Wie viele Gramm Hautzellen verliert ein Mensch täglich?",a:30,unit:"Gramm",hint:"30-40g Hautschuppen täglich.",emoji:"🧑"},
  {q:"Wie viele Millionen Bakterien überträgt man beim Händeschütteln?",a:10,unit:"Millionen",hint:"Ein Händedruck überträgt 10-100 Millionen.",emoji:"🤝"},
  {q:"Wie viele Liter Schweiß produziert ein Mensch bei einem Ultramarathon?",a:10,unit:"Liter",hint:"Bei extremer Hitze und Belastung.",emoji:"💦"},
  {q:"Wie viele Gramm Kot sind in einem Appendix (Blinddarm)?",a:0,unit:"Gramm",hint:"Der Blinddarm ist normalerweise leer.",emoji:"💩"},
  {q:"Wie viele Millionen Bakterien sind auf einem Schreibtisch pro m²?",a:400,unit:"Millionen",hint:"Schreibtische sind schmutziger als Toiletten.",emoji:"🦠"},
  {q:"Wie viele Sekunden dauert ein Nieser von Einatmung bis Explosion?",a:0.5,unit:"Sekunden",hint:"Schleudert Partikel mit 160km/h.",emoji:"🤧"},
  {q:"Wie viele km/h fliegen Schleimpartikel beim Niesen?",a:160,unit:"km/h",hint:"Bis zu 8 Meter weit.",emoji:"🤧"},
  {q:"Wie viele Gramm Schweiß produziert ein Mensch pro Stunde beim Sport?",a:1000,unit:"Gramm",hint:"1 Liter Schweiß pro Stunde.",emoji:"💦"},
  {q:"Wie viele Millionen Mikroben werden in der Öffentlichkeit täglich ausgeatmet?",a:37,unit:"Millionen",hint:"Nur durch normales Atmen.",emoji:"💨"},
  {q:"Wie viele Liter Urin produziert ein Mensch pro Tag?",a:1.5,unit:"Liter",hint:"1-2 Liter bei normaler Hydration.",emoji:"💛"},
  {q:"Wie viele Mal im Jahr bekommt ein Europäer Durchfall?",a:2,unit:"Mal",hint:"Gastroenteritis ist sehr häufig.",emoji:"🚽"},
  {q:"Wie viele Tonnen Kot produziert ein Mensch in seinem Leben?",a:8,unit:"Tonnen",hint:"Bei 150g pro Tag über 70 Jahre.",emoji:"💩"},
  {q:"Wie viele Millionen Bakterien sind auf einer Zahnbürste?",a:10,unit:"Millionen",hint:"Nach nur wenigen Tagen Benutzung.",emoji:"🦷"},
  {q:"Wie viele Gramm Körpergeruchsbakterien produziert ein Mensch täglich?",a:2,unit:"Gramm",hint:"Bakterien bauen Schweißproteine ab.",emoji:"💦"},
  {q:"Wie viele Liter Speichel enthält ein Kuss?",a:0.003,unit:"Liter",hint:"3ml Speichel – plus 80 Millionen Bakterien.",emoji:"💋"},
  {q:"Wie viele Gramm Fußpilzporen können in einem Zimmer sein?",a:0.01,unit:"Gramm",hint:"Winzige Mengen – reichen aber für Infektionen.",emoji:"🦶"},
  {q:"Wie viele Millionen Bakterien sind auf einem Küchenspülschwamm?",a:54,unit:"Milliarden",hint:"54 Milliarden – schmutzigster Haushaltsgegenstand.",emoji:"🫧"},
  {q:"Wie viele Mal husten Menschen mit Erkältung am Tag?",a:200,unit:"Mal",hint:"Bis zu 200 Mal täglich.",emoji:"😷"},
  {q:"Wie viele Gramm Magen-Darm-Inhalt werden beim Erbrechen ausgeworfen?",a:300,unit:"Gramm",hint:"Je nach Mahlzeit.",emoji:"🤮"},
  {q:"Wie viele Millionen Hautzellen sind in einem Bett nach einem Jahr?",a:1000,unit:"Millionen",hint:"Matratzen sammeln enormen Schmutz.",emoji:"🛏️"},
  {q:"Wie viele Liter Urin sind in einer vollen Blase?",a:0.6,unit:"Liter",hint:"500-600ml maximale Kapazität.",emoji:"💛"},
  {q:"Wie viele Gramm Haare verliert man durch Schweiß pro Tag?",a:0,unit:"Gramm",hint:"Haare verliert man durch Schuppen, nicht Schweiß.",emoji:"💇"},
  {q:"Wie viele Millionen Sporen kann ein Schimmelpilz pro Tag produzieren?",a:1000,unit:"Millionen",hint:"1 Milliarde Sporen – winzig und überall.",emoji:"🍄"},
  {q:"Wie viele Liter Galle produziert die Leber täglich?",a:0.5,unit:"Liter",hint:"500ml – essenziell für die Fettverdauung.",emoji:"💛"},
  {q:"Wie viele Gramm Kot enthalten Sandwichbrote wenn kein Händewaschen erfolgt?",a:0.2,unit:"Gramm",hint:"Messstudie: Fäkalbakterien auf 1 von 6 Hände.",emoji:"🤢"},
  {q:"Wie viele Millionen Bakterien sind auf einem Handtuch nach einer Woche?",a:100,unit:"Millionen",hint:"Badezimmerhandtücher sind voller Bakterien.",emoji:"🧺"},
  {q:"Wie viele km/h ist die maximale Geschwindigkeit eines Huste-Ausstoßes?",a:150,unit:"km/h",hint:"Etwas langsamer als ein Niesen.",emoji:"😷"},
  {q:"Wie viele Gramm wiegt der gesamte Inhalt des Dünndarms?",a:500,unit:"Gramm",hint:"Inklusive unverdauter Nahrung und Flüssigkeit.",emoji:"🌀"},
  {q:"Wie viele Millionen Bakterien überträgt ein Handschlag?",a:10,unit:"Millionen",hint:"Hände sind der größte Übertragungsweg.",emoji:"🤝"},
  {q:"Wie viele Liter Gallensäfte werden täglich produziert?",a:1,unit:"Liter",hint:"Aus Leber und Gallenblase.",emoji:"💛"},
  {q:"Wie viele Gramm Ohrenschmalz produziert ein Ohr pro Jahr?",a:12,unit:"Gramm",hint:"12g – ein Esslöffel pro Jahr.",emoji:"👂"},
  {q:"Wie viele Millionen Hausmilben sind in einem Kopfkissen?",a:10,unit:"Millionen",hint:"Ernähren sich von Hautschuppen.",emoji:"🛏️"},
  {q:"Wie viele Gramm Kot werden nach einem Einlauf ausgeschieden?",a:2000,unit:"Gramm",hint:"2 Liter – mehr als ein normaler Stuhlgang.",emoji:"💩"},
  {q:"Wie viele Liter Flüssigkeit verliert man beim Schwitzen in der Sauna?",a:1.5,unit:"Liter",hint:"Pro Saunagang.",emoji:"🧖"},
  {q:"Wie viele Millionen Bakterien sind auf einer Türklinke?",a:10,unit:"Millionen",hint:"Öffentliche Türklinken sind voller Keime.",emoji:"🦠"},
  {q:"Wie viele Gramm Zahnstein bilden sich ohne Mundhygiene pro Jahr?",a:10,unit:"Gramm",hint:"Mineralisierter Zahnbelag.",emoji:"🦷"},
  {q:"Wie viele Millionen Haare verliert man durch normales Waschen pro Woche?",a:700,unit:"Haare",hint:"100 pro Tag × 7 Tage.",emoji:"🚿"},
  {q:"Wie viele Gramm Augenabsonderung produzieren die Augen täglich?",a:1,unit:"Gramm",hint:"Die Krusten am Morgen.",emoji:"👁️"},
  {q:"Wie viele Millionen Bakterien sind in einem Liter Trinkwasser?",a:1,unit:"Millionen",hint:"In normalem Leitungswasser – meist harmlos.",emoji:"💧"},
  {q:"Wie viele Gramm Stuhl kann ein Darm zurückhalten ohne Druck zu spüren?",a:500,unit:"Gramm",hint:"500g bevor der Harndrang kommt.",emoji:"💩"},
  {q:"Wie viele Liter Speichel schluckt man täglich?",a:1.5,unit:"Liter",hint:"Den ganzen Tag produziert und geschluckt.",emoji:"💧"},
  {q:"Wie viele Millionen Schimmelpilzsporen sind in einem normalen Haus?",a:10,unit:"Millionen",hint:"Überall – besonders in Badezimmern.",emoji:"🍄"},
  {q:"Wie viele Gramm Schmegma bilden sich wöchentlich ungewaschen?",a:5,unit:"Gramm",hint:"Talgabsonderungen unter der Vorhaut.",emoji:"😬"},
  {q:"Wie viele Millionen Fäkalbakterien sind auf einem Smartphone?",a:25,unit:"Tausend",hint:"Mehr als auf einer Toilette.",emoji:"📱"},
  {q:"Wie viele Liter Blut verliert eine Frau während ihrer Lebens-Perioden?",a:30,unit:"Liter",hint:"Ca. 50ml pro Periode × 500 Perioden.",emoji:"🩸"},
  {q:"Wie viele Gramm Abgase atmet ein Mensch in einer Großstadt täglich ein?",a:0.1,unit:"Gramm",hint:"Feinstaub und Abgase.",emoji:"🌫️"},
  {q:"Wie viele Millionen Bakterien sterben täglich in unserem Körper?",a:1000,unit:"Milliarden",hint:"Billionen Bakterien im Gleichgewicht.",emoji:"🦠"},
  {q:"Wie viele Gramm Schmutz sind in Regenregenwasser pro Liter?",a:0.001,unit:"Gramm",hint:"Mikropartikel in jedem Regentropfen.",emoji:"🌧️"},
  {q:"Wie viele Millionen Keime sind im Mund nach dem Aufwachen?",a:20,unit:"Milliarden",hint:"Morgenmund enthält viele Bakterien.",emoji:"😬"},
  {q:"Wie viele Gramm Hautschuppen fallen pro Jahr aus dem Haar?",a:5,unit:"Gramm",hint:"Dandruff – normal bis 5g täglich.",emoji:"💇"},
  {q:"Wie viele Liter Blut werden pro Periode ausgegeben?",a:0.05,unit:"Liter",hint:"50ml – weniger als viele denken.",emoji:"🩸"},
  {q:"Wie viele Millionen Staubmilben leben in einem durchschnittlichen Bett?",a:10,unit:"Millionen",hint:"Sie fressen unsere Hautzellen.",emoji:"🛏️"},
  {q:"Wie viele Gramm Fäkalien-Partikel sind auf einem öffentlichen WC-Sitz?",a:0.0001,unit:"Gramm",hint:"Messbar aber sehr wenig.",emoji:"🚽"},
  {q:"Wie viele Liter Mageninhalt werden beim Erbrechen maximal ausgeleert?",a:1.5,unit:"Liter",hint:"Magenkapazität beträgt maximal 1,5L.",emoji:"🤮"},
  {q:"Wie viele Millionen Bakterien sind auf einem frischen Küchenmesser?",a:5,unit:"Millionen",hint:"Besonders auf dem Griff.",emoji:"🔪"},
  {q:"Wie viele Gramm Fett schwitzt der Körper täglich aus?",a:5,unit:"Gramm",hint:"Talg und Lipide in Schweiß.",emoji:"💦"},
  {q:"Wie viele Liter Schleim produziert der Darm täglich?",a:1.5,unit:"Liter",hint:"Schleimhaut schützt den Darm.",emoji:"🌀"},
  {q:"Wie viele Millionen Keime überlebt eine Toilette pro Flush?",a:10,unit:"Millionen",hint:"Toilet plume – Keime in der Luft nach dem Spülen.",emoji:"🚽"},
  {q:"Wie viele Gramm Schmutz werden beim Händewaschen entfernt?",a:0.5,unit:"Gramm",hint:"0,5g Schmutz und Keime.",emoji:"🧼"},
  {q:"Wie viele Millionen Spermien sind in einem Liter Schwimmbadwasser?",a:0,unit:"Millionen",hint:"Chlor zerstört alle Spermien sofort.",emoji:"🏊"},
  {q:"Wie viele Gramm Haare werden monatlich geschluckt?",a:0.5,unit:"Gramm",hint:"Durch Essen, Küssen, Luftschlucken.",emoji:"💇"},
  {q:"Wie viele Liter Körperflüssigkeiten verliert ein Mensch täglich insgesamt?",a:2.5,unit:"Liter",hint:"Urin, Schweiß, Atemluft zusammen.",emoji:"💧"},
  {q:"Wie viele Millionen Bakterien sind auf einem Geldschein?",a:26,unit:"Tausend",hint:"Bargeld ist eines der dreckigsten Dinge.",emoji:"💵"},
  {q:"Wie viele Gramm unverdaute Nahrung sind im Dickdarm?",a:1000,unit:"Gramm",hint:"1 kg Nahrungsreste im Dickdarm.",emoji:"🌀"},
  {q:"Wie viele Millionen Pilzsporen atmet ein Mensch täglich ein?",a:1,unit:"Million",hint:"Überall in der Luft – meistens harmlos.",emoji:"🍄"},
  {q:"Wie viele Gramm Körperfett verbrennt man beim Schlafen?",a:70,unit:"Gramm",hint:"Bei 7-8 Stunden Schlaf.",emoji:"😴"},
  {q:"Wie viele Liter Blut enthält ein normales Steak?",a:0.1,unit:"Liter",hint:"Das Rote ist Myoglobin, nicht Blut.",emoji:"🥩"},
  {q:"Wie viele Millionen Bakterien überlebt in einem Desinfektionsmittel?",a:0.001,unit:"Millionen",hint:"Gute Desinfektionsmittel töten 99,999%.",emoji:"🧴"},
  {q:"Wie viele Gramm Fingernagel-Dreck enthält eine ungewaschene Hand?",a:0.01,unit:"Gramm",hint:"Unter jedem Nagel bis zu 10.000 Bakterien.",emoji:"💅"},
  {q:"Wie viele Liter Eiter kann ein Abszess enthalten?",a:0.5,unit:"Liter",hint:"Große Abszesse können Tassen voll enthalten.",emoji:"😨"},
  {q:"Wie viele Millionen Zecken sind im Frühjahr in deutschen Wäldern aktiv?",a:100,unit:"Millionen",hint:"Und jede zehnte trägt Borreliose.",emoji:"🕷️"},
  {q:"Wie viele Gramm Fußschweiß produziert ein Fuß täglich?",a:50,unit:"Gramm",hint:"Ein Mensch hat 250.000 Schweißdrüsen an den Füßen.",emoji:"🦶"},
  {q:"Wie viele Millionen Mücken-Stiche passieren in Deutschland im Sommer?",a:10,unit:"Milliarden",hint:"Pro Nacht im Sommer.",emoji:"🦟"},
  {q:"Wie viele Liter Lymphflüssigkeit hat der Körper?",a:2,unit:"Liter",hint:"Das Lymphsystem transportiert Immunzellen.",emoji:"💛"},
  {q:"Wie viele Gramm Schmutz enthält ein Staubsaugerbeutel nach einem Monat?",a:200,unit:"Gramm",hint:"Davon viel Hautschuppen und Staubmilben.",emoji:"🌀"},
  {q:"Wie viele Millionen Viren sind in einem Milliliter Meerwasser?",a:10,unit:"Millionen",hint:"Das Meer ist voller Viren – meist für Algen.",emoji:"🌊"},
  {q:"Wie viele Gramm Schmalz produziert die Haut täglich?",a:10,unit:"Gramm",hint:"Talg als Hautschutz.",emoji:"✨"},
  {q:"Wie viele Liter Darmgase entstehen täglich?",a:2,unit:"Liter",hint:"Davon werden 1,5L als Pupse abgegeben.",emoji:"💨"},
  {q:"Wie viele Millionen Hausmilben sind in einem Teppich pro m²?",a:1,unit:"Million",hint:"Jede isst Hautschuppen.",emoji:"🏠"},
  {q:"Wie viele Gramm Parasiten-Eier sind in einem ungewaschenem Salat?",a:0.00001,unit:"Gramm",hint:"Mikroskopisch klein – reichen aber.",emoji:"🥗"},
  {q:"Wie viele Liter Körperwärme verliert man beim Schwitzen insgesamt im Sommer?",a:5,unit:"Liter",hint:"An einem heißen Tag.",emoji:"🌡️"},
  {q:"Wie viele Millionen Stunden verbringt die Menschheit täglich auf der Toilette?",a:50,unit:"Millionen Stunden",hint:"8 Milliarden Menschen × 6 Minuten.",emoji:"🚽"},
  {q:"Wie viele Gramm Talg produziert eine Teenager-Haut täglich?",a:15,unit:"Gramm",hint:"Mehr als Erwachsene – daher Akne.",emoji:"😬"},
  {q:"Wie viele Liter Bauchspeichel produziert die Bauchspeicheldrüse täglich?",a:1.5,unit:"Liter",hint:"Mit wichtigen Verdauungsenzymen.",emoji:"⚗️"},
  {q:"Wie viele Millionen Keime sind auf einem Trinkglas nach dem Abtrocknen?",a:5,unit:"Millionen",hint:"Feuchte Tücher übertragen Keime.",emoji:"🥃"},
  {q:"Wie viele Gramm Zähne-Schmutz (Plaque) bilden sich täglich?",a:0.5,unit:"Gramm",hint:"Ohne Zähneputzen schnell viel.",emoji:"🦷"},
  {q:"Wie viele Liter Blut verliert man bei einem normalen Zahnarzteingriff?",a:0.001,unit:"Liter",hint:"1ml – kaum messbar.",emoji:"🩸"},
  {q:"Wie viele Millionen Trichinen können in einem Stück Rohfleisch sein?",a:1,unit:"Million",hint:"Grund warum Schweinefleisch durchgegart sein muss.",emoji:"🥩"},
  {q:"Wie viele Gramm Hornhaut wächst am Fuß pro Monat?",a:1,unit:"Gramm",hint:"Besonders bei Druck.",emoji:"🦶"},
  {q:"Wie viele Liter Flüssigkeit ist in einer normalen Blase beim Platzdruck?",a:0.7,unit:"Liter",hint:"700ml – dann wird es schmerzhaft.",emoji:"💛"},
  {q:"Wie viele Millionen Bakterien werden beim Pinkeln in die Luft geschleudert?",a:1,unit:"Million",hint:"Toilet plume – WC-Spritzer.",emoji:"🚽"},
  {q:"Wie viele Gramm Schweiß riechen ohne Deo nach einer Stunde?",a:0.1,unit:"Gramm",hint:"Bakterien bauen Schweißsäuren ab.",emoji:"💦"},
  {q:"Wie viele Liter Blut fließen bei einer normalen Geburt?",a:0.5,unit:"Liter",hint:"Normaler Blutverlust bei Vaginalgeburt.",emoji:"🤱"},
  {q:"Wie viele Millionen Parasiten kann ein Mensch beherbergen?",a:1,unit:"Million",hint:"Darmenparasiten bei Infektion.",emoji:"🪱"},
  {q:"Wie viele Gramm Zellreste sind in einem normalen Stuhlgang?",a:50,unit:"Gramm",hint:"Abgestorbene Darmzellen.",emoji:"💩"},
  {q:"Wie viele Liter Flüssigkeit produziert der Darm täglich?",a:8,unit:"Liter",hint:"Fast alle werden rückresorbiert.",emoji:"🌀"},
  {q:"Wie viele Millionen Bakterien sterben bei 60°C in Sekunden?",a:1000,unit:"Millionen",hint:"Pasteurisierung nutzt genau das.",emoji:"🌡️"},
  {q:"Wie viele Gramm Pupsgase sind pro Pups?",a:0.07,unit:"Gramm",hint:"70ml Gas – je nach Diät mehr.",emoji:"💨"},
  {q:"Wie viele Liter Schleim schluckt man beim Schnupfen täglich?",a:1,unit:"Liter",hint:"Mehr als man denkt.",emoji:"🤧"},
  {q:"Wie viele Millionen Schimmelpilze sind in einem normalen Joghurt?",a:0,unit:"Millionen",hint:"Joghurt-Bakterien verdrängen Schimmel.",emoji:"🫙"},
  {q:"Wie viele Gramm Körperfett werden pro Stunde Schlaf verbrannt?",a:10,unit:"Gramm",hint:"Insgesamt 70g pro Nacht.",emoji:"😴"},
  {q:"Wie viele Liter Urin kann die Blase halten ohne Schmerz?",a:0.4,unit:"Liter",hint:"Harndrang beginnt schon bei 250ml.",emoji:"💛"},
  {q:"Wie viele Millionen Würmer können im Darm bei starker Infektion sein?",a:1,unit:"Million",hint:"Spulwürmer können zu Tausenden vorkommen.",emoji:"🪱"},
  {q:"Wie viele Gramm Gift scheidet die Leber täglich aus?",a:10,unit:"Gramm",hint:"Entgiftungsleistung pro Tag.",emoji:"🟤"},
  {q:"Wie viele Liter Blut verliert man bei einer Amputation?",a:2,unit:"Liter",hint:"Ohne tourniquet – schnell lebensbedrohlich.",emoji:"🩸"},
  {q:"Wie viele Millionen Keime sind auf einer Computertastatur?",a:400,unit:"Millionen",hint:"Tastaturen sind schmutziger als Toiletten.",emoji:"💻"},
  {q:"Wie viele Gramm Nasensekret produziert man bei starker Erkältung pro Tag?",a:50,unit:"Gramm",hint:"50ml Schleim – viel schnäuzen.",emoji:"🤧"},
  {q:"Wie viele Liter Blut verliert man monatlich beim Zähneputzen?",a:0.001,unit:"Liter",hint:"1ml – zahnfleischbluten.",emoji:"🩸"},
  {q:"Wie viele Millionen Bakterien fressen Staubmilben täglich?",a:0,unit:"Millionen",hint:"Staubmilben fressen Hautschuppen, nicht Bakterien.",emoji:"🛏️"},
  {q:"Wie viele Gramm Körperzellen sterben täglich ab?",a:50,unit:"Gramm",hint:"50g Zellmasse wird täglich ersetzt.",emoji:"🔬"},
  {q:"Wie viele Liter Speichelfluss passiert beim Gedanken an Essen?",a:0.1,unit:"Liter",hint:"100ml allein durch pavlovsche Reaktion.",emoji:"🍕"},
  {q:"Wie viele Millionen Keime überlebt auf einem Kissenbezug nach einer Woche?",a:3,unit:"Millionen",hint:"Besonders Gesichtsbakterien.",emoji:"🛏️"},
  {q:"Wie viele Gramm Fett produzieren die Kopfhautdrüsen täglich?",a:1,unit:"Gramm",hint:"1g Talg – macht Haare fettig.",emoji:"💇"},
  {q:"Wie viele Liter Blut produziert der Körper täglich neu?",a:0.2,unit:"Liter",hint:"200ml neue rote Blutkörperchen.",emoji:"🩸"},
  {q:"Wie viele Millionen Viren atmet man in einer Stunde im Büro ein?",a:100,unit:"Millionen",hint:"In Innenräumen sehr viele Viren.",emoji:"🦠"},
  {q:"Wie viele Gramm Kot enthält ein menschlicher Körper durchschnittlich?",a:1000,unit:"Gramm",hint:"1 kg im Darm immer vorhanden.",emoji:"💩"},
  {q:"Wie viele Liter Flüssigkeit fließt täglich durch die Nieren?",a:180,unit:"Liter",hint:"180L werden gefiltert – nur 1.5L Urin.",emoji:"🫘"},
  {q:"Wie viele Millionen Parasiteneier sind in unbewässertem Boden pro m²?",a:10,unit:"Millionen",hint:"Hakenwürmer, Spulwürmer in Dritte-Welt-Böden.",emoji:"🌱"},
  {q:"Wie viele Gramm Säure ist im Erbrochenen?",a:5,unit:"Gramm",hint:"Magensäure pH 1-2.",emoji:"⚗️"},
  {q:"Wie viele Liter Tränen produziert ein Mensch beim Weinen?",a:0.01,unit:"Liter",hint:"10ml bei einem weinanfall.",emoji:"😢"},
  {q:"Wie viele Millionen Bakterien sind auf einem Klospülknopf?",a:50,unit:"Millionen",hint:"Mehr als auf dem Klositz.",emoji:"🚽"},
  {q:"Wie viele Gramm Schleim sind in der Lunge?",a:150,unit:"Gramm",hint:"Schleimhaut schützt die Atemwege.",emoji:"🫁"},
  {q:"Wie viele Liter Magenflüssigkeit kann man beim Spülen entleeren?",a:3,unit:"Liter",hint:"Magenspülung – bei Vergiftung.",emoji:"⚗️"},
  {q:"Wie viele Millionen Keime überlebt ein Sponge/Schwamm nach 1 Min Mikrowelle?",a:1,unit:"Millionen",hint:"Mikrowellen töten nicht alle Keime.",emoji:"🫧"},
  {q:"Wie viele Gramm Talgablagerungen entstehen in verstopften Poren (Mitesser)?",a:0.001,unit:"Gramm",hint:"Winzige Mengen – aber sichtbar.",emoji:"😬"},
  {q:"Wie viele Liter Schweiß produziert der Körper pro Stunde in Hitze?",a:2,unit:"Liter",hint:"Bei extremer Hitze bis 3L.",emoji:"☀️"},
  {q:"Wie viele Millionen Bakterien sind auf einem frischen Geldschein?",a:26000,unit:"Bakterien",hint:"Neues Geld hat weniger als altes.",emoji:"💵"},
  {q:"Wie viele Gramm Körperschuppen sind im Hausstaub?",a:70,unit:"%",hint:"70% des Hausstaubs sind Hautschuppen.",emoji:"🌀"},
  {q:"Wie viele Liter Blut enthält die Leber?",a:1.5,unit:"Liter",hint:"Die Leber ist ein Blutreservoir.",emoji:"🟤"},
  {q:"Wie viele Millionen Bakterien sind auf einem Lichtschalter?",a:220,unit:"Tausend",hint:"Häufig berührt – selten gereinigt.",emoji:"💡"},
  {q:"Wie viele Gramm Fäkalbakterien könnten auf einem Buffet-Essen sein?",a:0.001,unit:"Gramm",hint:"Schlechte Handhygiene von Köchen.",emoji:"🍽️"},
  {q:"Wie viele Liter Schweiß produziert man in einer Sauna (Stunde)?",a:1.5,unit:"Liter",hint:"Bei 80-90°C.",emoji:"🧖"},
  {q:"Wie viele Millionen Pilzsporen produziert ein Schimmelpilz pro Sekunde?",a:1,unit:"Millionen",hint:"Schimmel verbreitet sich extrem schnell.",emoji:"🍄"},
  {q:"Wie viele Gramm Schleim werden bei einer Erkältung täglich produziert?",a:100,unit:"Gramm",hint:"100ml Schleim – viel davon geschluckt.",emoji:"🤧"},
  {q:"Wie viele Milliarden Liter Urin werden täglich in deutschen WCs gespült?",a:20,unit:"Milliarden Liter",hint:"Enorme Wasserverschwendung.",emoji:"🚽"},
  {q:"Wie viele Millionen Bakterien sind in 1g frischer Erde?",a:1000,unit:"Millionen",hint:"1 Milliarde Bakterien pro Gramm Erde.",emoji:"🌱"},
  {q:"Wie viele Gramm Schmutz sammeln sich pro Jahr im Bauchnabel?",a:0.5,unit:"Gramm",hint:"Flusen, Öl und Bakterien.",emoji:"🔘"},
  {q:"Wie viele Liter Blut verliert man bei einer normalen Menstruation?",a:0.05,unit:"Liter",hint:"50ml pro Periode.",emoji:"🩸"},
  {q:"Wie viele Millionen Bakterien produziert ein Mensch täglich durch Hautkontakt?",a:1000,unit:"Millionen",hint:"Jede Berührung hinterlässt Spuren.",emoji:"🤲"},
  {q:"Wie viele Gramm totes Gewebe enthält ein Nagel bei Pilzinfektion?",a:1,unit:"Gramm",hint:"Onychomykose – Pilz zerstört Nagelstruktur.",emoji:"💅"},
  {q:"Wie viele Liter Lymphe wird täglich durch Lymphknoten gefiltert?",a:3,unit:"Liter",hint:"Das Lymphsystem als zweites Transportsystem.",emoji:"💛"},
  {q:"Wie viele Millionen Keime sind in einem Handtuch nach einer Woche?",a:100,unit:"Millionen",hint:"Feuchte Handtücher sind ideal für Bakterien.",emoji:"🧺"},
  {q:"Wie viele Gramm unverdautes Essen verlässt den Körper im Stuhl täglich?",a:30,unit:"Gramm",hint:"Ballaststoffe und unverdauliche Reste.",emoji:"💩"},
  {q:"Wie viele Liter Magensäure werden täglich produziert?",a:2,unit:"Liter",hint:"Stark genug um Stahl aufzulösen.",emoji:"⚗️"},
  {q:"Wie viele Millionen Viren sind in 1ml Flusswasser?",a:1,unit:"Million",hint:"Flüsse sind voller Viren – meist harmlose.",emoji:"🌊"},
  {q:"Wie viele Gramm Körperfett werden beim Lachen verbrannt?",a:0.001,unit:"Gramm",hint:"Sehr wenig – aber Lachen ist gesund.",emoji:"😂"},
  {q:"Wie viele Liter Speichelfluss produziert ein Hund täglich?",a:2,unit:"Liter",hint:"Hunde speicheln deutlich mehr als Menschen.",emoji:"🐕"},
  {q:"Wie viele Millionen Bakterien sind auf der Zunge nach dem Aufwachen?",a:20,unit:"Milliarden",hint:"Morgenatemluft riecht so schlimm wegen Bakterien.",emoji:"👅"},
  {q:"Wie viele Gramm Kot werden in einem Jahr Darmträgheit angesammelt?",a:3000,unit:"Gramm",hint:"Chronische Verstopfung kann zu Ablagerungen führen.",emoji:"💩"},
  {q:"Wie viele Liter Blut filtert die Niere täglich?",a:180,unit:"Liter",hint:"Alle 30 Minuten das gesamte Blutvolumen.",emoji:"🫘"},
  {q:"Wie viele Millionen Keime überlebt ein Sponge ohne Reinigung?",a:54000,unit:"Millionen",hint:"54 Milliarden – der schmutzigste Küchengegenstand.",emoji:"🫧"},
  {q:"Wie viele Gramm Eiter kann ein Furunkel enthalten?",a:5,unit:"Gramm",hint:"Eiterpustel kann erstaunlich viel fassen.",emoji:"😨"},
  {q:"Wie viele Liter Flüssigkeit verliert man beim Marathon?",a:4,unit:"Liter",hint:"Durch Schwitzen und Atmen.",emoji:"🏃"},
  {q:"Wie viele Millionen Parasiten hat die Weltbevölkerung gemeinsam?",a:1000,unit:"Milliarden",hint:"Parasiten infizieren Milliarden Menschen.",emoji:"🪱"},
  {q:"Wie viele Gramm Zahnfleisch-Bakterien produziert der Mund täglich?",a:1,unit:"Gramm",hint:"Dentalplaque-Bakterien.",emoji:"🦷"},
  {q:"Wie viele Liter Urin enthält eine Blase kurz vor dem Platzen?",a:1,unit:"Liter",hint:"Schmerzhaft – Platzen ist nur theoretisch.",emoji:"💛"},
  {q:"Wie viele Millionen Spulwürmer-Eier können in einem Gemüsegarten sein?",a:10,unit:"Millionen",hint:"Hauptursache für Parasiteninfektionen.",emoji:"🥦"},
  {q:"Wie viele Gramm Hautzellen findet man in einem Staubsauger nach Monat?",a:100,unit:"Gramm",hint:"Hauptanteil des Staubsaugerinhalts.",emoji:"🌀"},
  {q:"Wie viele Liter Körperflüssigkeiten werden täglich verloren und ersetzt?",a:2.5,unit:"Liter",hint:"Urin, Schweiß, Atem und Verdauung.",emoji:"💧"},
  {q:"Wie viele Millionen Pilze können auf einem ungepflegten Fuß leben?",a:100,unit:"Millionen",hint:"Fußpilz – oft unbemerkt.",emoji:"🦶"},
  {q:"Wie viele Gramm Körperfett enthält ein Liter menschlicher Muttermilch?",a:40,unit:"Gramm",hint:"3,5-4,5% Fettgehalt.",emoji:"🤱"},
  {q:"Wie viele Liter Gesamtblut fließt täglich durch die Leber?",a:1500,unit:"Liter",hint:"Die Leber ist stark durchblutet.",emoji:"🟤"},
  {q:"Wie viele Millionen Coli-Bakterien sind in 1ml Abwasser?",a:100,unit:"Millionen",hint:"Roh-Abwasser enthält Millionen E.coli.",emoji:"💧"},
  {q:"Wie viele Gramm Gallenflüssigkeit produziert die Gallenblase täglich?",a:800,unit:"ml",hint:"800ml Galle täglich.",emoji:"💛"},
  {q:"Wie viele Liter Blut enthält eine erwachsene Leber?",a:1.5,unit:"Liter",hint:"25% des Herzschlagvolumens fließt zur Leber.",emoji:"🟤"},
  {q:"Wie viele Millionen Viren befinden sich in 1 Liter Luft in Innenräumen?",a:100,unit:"Millionen",hint:"Besonders in schlecht belüfteten Räumen.",emoji:"🦠"},
  {q:"Wie viele Gramm Körpersalz verliert man beim Sport pro Stunde?",a:2,unit:"Gramm",hint:"2g Natrium pro Liter Schweiß.",emoji:"🧂"},
  {q:"Wie viele Liter Flüssigkeit verliert ein Körper beim Sterben?",a:2,unit:"Liter",hint:"Körper dehydriert stark am Ende.",emoji:"☠️"},
  {q:"Wie viele Millionen Bakterien sind in frischer Milch (unpasteurisiert)?",a:100,unit:"Millionen",hint:"Rohmilch enthält viele Keime.",emoji:"🥛"},
  {q:"Wie viele Gramm Bakterienmasse ist der gesunde Stuhl?",a:30,unit:"%",hint:"30% des Stuhls sind Bakterien.",emoji:"💩"},
];
