export const ADULT_TEST_DE = [
  {q:"Wie viele Mal schlägt das menschliche Herz pro Tag?",a:100000,unit:"Mal",hint:"70 Schläge/min × 60 × 24 = ca. 100.000 Mal täglich.",emoji:"❤️"},
  {q:"Wie viele Milliarden Neuronen hat das menschliche Gehirn?",a:86,unit:"Milliarden Neuronen",hint:"86 Milliarden Neuronen – mit Billionen von Verbindungen.",emoji:"🧠"},
  {q:"Wie viele Liter Blut hat ein Erwachsener im Körper?",a:5,unit:"Liter",hint:"Ca. 5 Liter – das Herz pumpt sie 1.000 Mal täglich durch.",emoji:"🩸"},
  {q:"Wie viele km/h niest ein Mensch?",a:160,unit:"km/h",hint:"Bis zu 160 km/h – deshalb Mund zuhalten!",emoji:"🤧"},
  {q:"Wie viele Meter DNA steckt in einer einzigen Zelle?",a:2,unit:"Meter",hint:"2m × 37 Billionen Zellen = ~17× die Strecke Erde-Sonne.",emoji:"🧬"},
  {q:"Wie viele Milliarden Bakterien leben auf der Haut eines Menschen?",a:1800,unit:"Milliarden",hint:"1.800 Milliarden = 1,8 Billionen – die meisten sind harmlos.",emoji:"🦠"},
  {q:"Wie viele Liter Schweiß verliert man an einem heißen Sommertag?",a:5,unit:"Liter",hint:"Bis zu 5 Liter täglich bei großer Hitze.",emoji:"💧"},
  {q:"Wie viele Gramm Hautzellen verliert ein Mensch täglich?",a:2,unit:"Gramm",hint:"1-3g täglich – im Jahr bis zu 1kg Hautschuppen.",emoji:"🧴"},
  {q:"Wie viele Liter Speichel produziert ein Mensch pro Jahr?",a:550,unit:"Liter",hint:"Ca. 1,5L/Tag × 365 = ~550 Liter – genug für eine Badewanne.",emoji:"💦"},
  {q:"Wie viele Mal blinzelt ein Mensch pro Tag?",a:15000,unit:"Mal",hint:"Ca. 15-20 Mal pro Minute × 16 Stunden wach.",emoji:"👁️"},
  {q:"Wie viele Prozent des Gehirns nutzt ein Mensch?",a:100,unit:"%",hint:"100% – der Mythos der 10% ist wissenschaftlich falsch.",emoji:"🧠"},
  {q:"Wie viele Jahre seines Lebens schläft ein Mensch durchschnittlich?",a:26,unit:"Jahre",hint:"Bei 8h/Nacht × 70 Jahre = ca. 26 Jahre Schlaf.",emoji:"😴"},
  {q:"Wie viele Millionen Mal atmet ein Mensch im Leben?",a:700,unit:"Millionen Mal",hint:"Ca. 15-20 Atemzüge/Minute über 70 Jahre.",emoji:"💨"},
  {q:"Wie viele km/h kann ein Gepard laufen?",a:120,unit:"km/h",hint:"Bis 120 km/h – schnellstes Landtier.",emoji:"🐆"},
  {q:"Wie viele Stunden schläft eine Katze pro Tag?",a:16,unit:"Stunden",hint:"12-16 Stunden täglich – echte Schlafprofis.",emoji:"🐱"},
  {q:"Wie viele Tonnen wiegt ein ausgewachsener Blauwal?",a:150,unit:"Tonnen",hint:"Bis 150-200 Tonnen – das schwerste Tier aller Zeiten.",emoji:"🐋"},
  {q:"Wie viele km/h fliegt eine Wanderfalke im Sturzflug?",a:389,unit:"km/h",hint:"389 km/h – schnellstes Tier der Welt.",emoji:"🦅"},
  {q:"Wie viele Jahre wird eine Grönlandwal alt?",a:200,unit:"Jahre",hint:"Bis 200 Jahre – ältestes bekanntes Säugetier.",emoji:"🐋"},
  {q:"Wie viele km/s ist die Lichtgeschwindigkeit?",a:300000,unit:"km/s",hint:"300.000 km/s – Licht braucht ~8 Minuten von der Sonne zur Erde.",emoji:"💡"},
  {q:"Wie viele Milliarden Jahre alt ist das Universum?",a:13.8,unit:"Milliarden Jahre",hint:"13,8 Milliarden Jahre seit dem Urknall.",emoji:"🌌"},
  {q:"Wie viele Grad Celsius beträgt die Kerntemperatur der Sonne?",a:15,unit:"Millionen °C",hint:"15 Millionen Grad – dort findet Kernfusion statt.",emoji:"☀️"},
  {q:"Wie viele Atommassen hat ein Wasserstoffatom?",a:1,unit:"Atommasseneinheit",hint:"Wasserstoff ist das leichteste Element.",emoji:"⚛️"},
  {q:"In welchem Jahr fiel die Berliner Mauer?",a:1989,unit:"Jahr",hint:"9. November 1989 – eines der bedeutendsten Ereignisse des 20. Jh.",emoji:"🧱"},
  {q:"Wie viele Jahre dauerte der Zweite Weltkrieg?",a:6,unit:"Jahre",hint:"1939–1945 – 6 Jahre, der verlustreichste Krieg der Geschichte.",emoji:"🕊️"},
  {q:"Wie viele Millionen Menschen starben im Ersten Weltkrieg?",a:20,unit:"Millionen",hint:"Ca. 20 Millionen Tote – Soldaten und Zivilisten.",emoji:"🕊️"},
  {q:"Wie viele Milliarden Dollar ist Apple wert?",a:3200,unit:"Milliarden Dollar",hint:"Ca. 3.200 Milliarden – das wertvollste Unternehmen der Welt.",emoji:"🍎"},
  {q:"Wie viele Milliarden Dollar hat Elon Musk für Twitter bezahlt?",a:44,unit:"Milliarden Dollar",hint:"44 Milliarden Dollar – jetzt heißt es X.",emoji:"🐦"},
  {q:"Wie viele Euro kostet 1 kg Gold?",a:70000,unit:"Euro",hint:"Ca. 70.000€/kg (Stand 2024) – stark schwankend.",emoji:"🥇"},
  {q:"Wie viele Millionen Spermien enthält 1 ml Ejakulat?",a:70,unit:"Millionen Spermien/ml",hint:"WHO-Referenzwert: ≥16 Mio./ml – guter Wert sind 70 Mio./ml.",emoji:"🔬"},
  {q:"Wie viele Sekunden dauert ein durchschnittlicher Orgasmus?",a:22,unit:"Sekunden",hint:"Männer: 10-30s, Frauen: 20-35s – im Durchschnitt ca. 22s.",emoji:"⏱️"},
  {q:"Wie viele Minuten dauert ein Geschlechtsakt durchschnittlich?",a:30,unit:"Minuten",hint:"Inklusive Vorspiel ca. 30 Min., nur Penetration 5-6 Min.",emoji:"⏰"},
  {q:"Wie viele Millionen Menschen konsumieren regelmäßig Cannabis?",a:200,unit:"Millionen Menschen",hint:"Ca. 200 Millionen – die meistgenutzte illegale Droge weltweit.",emoji:"🌿"},
  {q:"Wie viele Gramm Alkohol baut die Leber pro Stunde ab?",a:10,unit:"Gramm/Stunde",hint:"0,1 Promille/Stunde = ca. 10g Alkohol bei 70kg.",emoji:"🍺"},
  {q:"Wie viele Milliarden Dollar wert ist der globale Tabakmarkt?",a:900,unit:"Milliarden Dollar",hint:"900 Milliarden Dollar jährlich – trotz sinkender Raucherquoten.",emoji:"🚬"},
  {q:"Wie viele Milliarden Dollar hat Avatar (2009) weltweit eingespielt?",a:2.9,unit:"Milliarden Dollar",hint:"Lange Zeit der erfolgreichste Film aller Zeiten.",emoji:"🎬"},
  {q:"Wie viele Teile hat die Star Wars Hauptsaga?",a:9,unit:"Teile",hint:"9 Episoden – plus Spin-offs wie Rogue One und The Mandalorian.",emoji:"⭐"},
  {q:"In welchem Jahr erschien der erste Harry Potter Film?",a:2001,unit:"Jahr",hint:"Harry Potter und der Stein der Weisen – November 2001.",emoji:"🧙"},
  {q:"Wie viele Tassen Kaffee trinken Deutsche pro Jahr?",a:162,unit:"Tassen",hint:"Ca. 162 Liter pro Person – Platz 3 weltweit.",emoji:"☕"},
  {q:"Wie viele Kalorien hat ein Big Mac?",a:563,unit:"kcal",hint:"Ca. 563 kcal – ohne Pommes und Getränk.",emoji:"🍔"},
  {q:"Wie viele Prozent Wasser enthält eine Tomate?",a:95,unit:"%",hint:"95% Wasser – eine der wasserreichsten Früchte.",emoji:"🍅"},
  {q:"Wie viele Meter ist der Weltrekord im Weitsprung?",a:8.95,unit:"Meter",hint:"Mike Powell 1991 – 8,95m, seitdem ungebrochen.",emoji:"🏃"},
  {q:"Wie viele km/h fuhr der schnellste Mensch auf Skiern?",a:254,unit:"km/h",hint:"254 km/h – Ivan Origone 2016.",emoji:"⛷️"},
  {q:"Wie viele Stunden dauerte das längste Tennismatch?",a:11,unit:"Stunden",hint:"Isner vs. Mahut 2010 – 11 Stunden 5 Minuten über 3 Tage.",emoji:"🎾"},
  {q:"Wie viele Mitgliedsstaaten hat die Europäische Union?",a:27,unit:"Länder",hint:"27 Mitglieder – seit dem Brexit (2020) ohne Großbritannien.",emoji:"🇪🇺"},
  {q:"Wie viele ständige Mitglieder hat der UN-Sicherheitsrat?",a:5,unit:"Mitglieder",hint:"USA, Russland, China, Frankreich, Großbritannien.",emoji:"🌍"},
  {q:"Wie viele Länder haben die Atombombe?",a:9,unit:"Länder",hint:"USA, Russland, UK, Frankreich, China, Israel, Indien, Pakistan, Nordkorea.",emoji:"☢️"},
  {q:"Wie viele Planeten hat unser Sonnensystem?",a:8,unit:"Planeten",hint:"Pluto wurde 2006 zum Zwergplaneten degradiert.",emoji:"🪐"},
  {q:"Wie viele Minuten braucht Licht von der Sonne zur Erde?",a:8,unit:"Minuten",hint:"Licht rast mit 300.000 km/s – trotzdem braucht es 8 Minuten.",emoji:"☀️"},
  {q:"Wie viele Monde hat der Saturn?",a:146,unit:"Monde",hint:"Saturn hat die meisten Monde aller Planeten.",emoji:"🪐"},
];
