// 🎬 FILM, TV & POPKULTUR – Erwachsene – 250 Fragen
export default [
  {id:"film_001",q:"Wie viele Oscars gewann Titanic (1997)?",a:11,unit:"Oscars",hint:"Gleichauf mit Ben-Hur und The Lord of the Rings.",emoji:"🎬"},
  {id:"film_002",q:"Wie viele Millionen Dollar kostete die Produktion von Avengers: Endgame?",a:356,unit:"Millionen Dollar",hint:"Einer der teuersten Filme aller Zeiten.",emoji:"🦸"},
  {id:"film_003",q:"Wie viele Milliarden Dollar hat Avatar (2009) weltweit eingespielt?",a:2.9,unit:"Milliarden Dollar",hint:"Lange Zeit der erfolgreichste Film aller Zeiten.",emoji:"🎬"},
  {id:"film_004",q:"In welchem Jahr startete die erste Staffel von Game of Thrones?",a:2011,unit:"Jahr",hint:"Basiert auf den Büchern von George R.R. Martin.",emoji:"👑"},
  {id:"film_005",q:"Wie viele Episoden hat die Gesamtserie Breaking Bad?",a:62,unit:"Episoden",hint:"5 Staffeln über das Leben von Walter White.",emoji:"🧪"},
  {id:"film_006",q:"Wie viele Millionen Dollar verdiente Jennifer Aniston pro Friends-Folge am Ende?",a:1,unit:"Millionen Dollar /Folge",hint:"Alle sechs Stars verdienen heute noch Millionen.",emoji:"☕"},
  {id:"film_007",q:"Wie viele Jahre lief die Serie The Simpsons bereits?",a:35,unit:"Jahre",hint:"Seit 1989 – die längste Animations-Primetime-Serie.",emoji:"🍩"},
  {id:"film_008",q:"Wie viele Millionen Abonnenten hat MrBeast auf YouTube?",a:250,unit:"Millionen",hint:"Der erfolgreichste YouTube-Kanal weltweit.",emoji:"▶️"},
  {id:"film_009",q:"In welchem Jahr erschien der erste Star Wars Film?",a:1977,unit:"Jahr",hint:"Episode IV – A New Hope war der Anfang.",emoji:"⭐"},
  {id:"film_010",q:"Wie viele Milliarden Dollar hat die Marvel Cinematic Universe insgesamt eingespielt?",a:29,unit:"Milliarden Dollar",hint:"Über 30 Filme zusammen.",emoji:"🦸"},
  {id:"film_011",q:"Wie viele Staffeln hat die Serie Friends?",a:10,unit:"Staffeln",hint:"1994-2004 – eine der beliebtesten Sitcoms ever.",emoji:"☕"},
  {id:"film_012",q:"Wie viele Millionen Dollar verdient Taylor Swift pro Konzert?",a:13,unit:"Millionen Dollar",hint:"Die Eras Tour war die lukrativste aller Zeiten.",emoji:"🎤"},
  {id:"film_013",q:"In welchem Jahr erschien Thriller von Michael Jackson?",a:1982,unit:"Jahr",hint:"Das meistverkaufte Album aller Zeiten.",emoji:"🎵"},
  {id:"film_014",q:"Wie viele Millionen Exemplare hat Harry Potter und der Stein der Weisen verkauft?",a:120,unit:"Millionen",hint:"Eines der meistverkauften Bücher überhaupt.",emoji:"⚡"},
  {id:"film_015",q:"Wie viele Oscars gewann Der Pate?",a:3,unit:"Oscars",hint:"Bester Film, Bester Hauptdarsteller, Bestes Drehbuch.",emoji:"🎬"},
  {id:"film_016",q:"Wie viele Millionen Dollar kostete ein 30-Sekunden-Werbespot beim Super Bowl 2024?",a:7,unit:"Millionen Dollar",hint:"Die teuerste Werbezeit im US-TV.",emoji:"📺"},
  {id:"film_017",q:"Wie viele Staffeln hat die Serie Seinfeld?",a:9,unit:"Staffeln",hint:"Eine der erfolgreichsten Sitcoms der 90er.",emoji:"🎤"},
  {id:"film_018",q:"In welchem Jahr wurde Netflix gegründet?",a:1997,unit:"Jahr",hint:"Zunächst als DVD-Verleih per Post.",emoji:"📺"},
  {id:"film_019",q:"Wie viele Millionen Abonnenten hat Netflix?",a:260,unit:"Millionen",hint:"Stand 2024 – größter Streamingdienst.",emoji:"📺"},
  {id:"film_020",q:"Wie viele Milliarden Dollar hat Jurassic Park (1993) eingespielt?",a:1.1,unit:"Milliarden Dollar",hint:"Erster Film der 1 Mrd. Dollar Marke.",emoji:"🦕"},
  {id:"film_021",q:"Wie viele Episoden hat die Serie The Office (US)?",a:201,unit:"Episoden",hint:"9 Staffeln über Dunder Mifflin Paper Company.",emoji:"📎"},
  {id:"film_022",q:"In welchem Jahr erschien Nirvanas Nevermind?",a:1991,unit:"Jahr",hint:"Smells Like Teen Spirit katapultierte sie in den Mainstream.",emoji:"🎸"},
  {id:"film_023",q:"Wie viele Millionen Dollar verdient Dwayne Johnson pro Film?",a:50,unit:"Millionen Dollar",hint:"Einer der bestbezahlten Schauspieler der Welt.",emoji:"💪"},
  {id:"film_024",q:"Wie viele Staffeln hat die Serie Grey's Anatomy?",a:20,unit:"Staffeln",hint:"Die langlebigste Primetime-Medizinserie.",emoji:"🏥"},
  {id:"film_025",q:"Wie viele Millionen Dollar kostete die erste Staffel von House of Cards?",a:100,unit:"Millionen Dollar",hint:"Netflix erstes großes Original – 2 Staffeln vorfinanziert.",emoji:"🃏"},
  {id:"film_026",q:"In welchem Jahr startete Instagram?",a:2010,unit:"Jahr",hint:"Innerhalb von 2 Monaten über 1 Million Nutzer.",emoji:"📸"},
  {id:"film_027",q:"Wie viele Milliarden Dollar hat Frozen (2013) weltweit eingespielt?",a:1.3,unit:"Milliarden Dollar",hint:"Let It Go wurde zum weltweiten Hit.",emoji:"❄️"},
  {id:"film_028",q:"Wie viele Millionen Follower hat Cristiano Ronaldo auf Instagram?",a:620,unit:"Millionen",hint:"Der meistgefolgte Mensch auf Instagram.",emoji:"⚽"},
  {id:"film_029",q:"In welchem Jahr wurde das erste iPhone vorgestellt?",a:2007,unit:"Jahr",hint:"Steve Jobs sagte: 'One more thing...'",emoji:"📱"},
  {id:"film_030",q:"Wie viele Episoden hat die Serie Lost?",a:121,unit:"Episoden",hint:"6 Staffeln auf der mysteriösen Insel.",emoji:"✈️"},
  {id:"film_031",q:"Wie viele Millionen Dollar verdient Robert Downey Jr. für seine Iron-Man-Rückkehr?",a:200,unit:"Millionen Dollar",hint:"Für Avengers: Secret Wars.",emoji:"🤖"},
  {id:"film_032",q:"In welchem Jahr erschien der erste Teil von The Matrix?",a:1999,unit:"Jahr",hint:"Keanu Reeves und die rote Pille.",emoji:"💊"},
  {id:"film_033",q:"Wie viele Staffeln hat The Walking Dead?",a:11,unit:"Staffeln",hint:"2010-2022 – Zombies in einer postapokalyptischen Welt.",emoji:"🧟"},
  {id:"film_034",q:"Wie viele Millionen Dollar hat Die Hard eingespielt?",a:140,unit:"Millionen Dollar",hint:"John McClane wurde Bruce Willis' Ikone.",emoji:"🔫"},
  {id:"film_035",q:"In welchem Jahr wurde YouTube gegründet?",a:2005,unit:"Jahr",hint:"Drei Ex-PayPal-Mitarbeiter gründeten es.",emoji:"▶️"},
  {id:"film_036",q:"Wie viele Milliarden Dollar hat Barbie (2023) weltweit eingespielt?",a:1.4,unit:"Milliarden Dollar",hint:"Der erfolgreichste Film einer Regisseurin.",emoji:"🩷"},
  {id:"film_037",q:"Wie viele Millionen Alben hat ABBA insgesamt verkauft?",a:380,unit:"Millionen",hint:"Einer der meistverkauften Künstler aller Zeiten.",emoji:"🎵"},
  {id:"film_038",q:"In welchem Jahr startete die Serie Stranger Things?",a:2016,unit:"Jahr",hint:"Netflix' größter Serienerfolg.",emoji:"🔦"},
  {id:"film_039",q:"Wie viele Oscars hat Meryl Streep gewonnen?",a:3,unit:"Oscars",hint:"Und 21 Nominierungen – Rekord.",emoji:"🎬"},
  {id:"film_040",q:"Wie viele Millionen Dollar verdient Lionel Messi pro Jahr?",a:135,unit:"Millionen Dollar",hint:"Inklusive Gehalt, Sponsoren und Werbung.",emoji:"⚽"},
  {id:"film_041",q:"In welchem Jahr erschien Pulp Fiction?",a:1994,unit:"Jahr",hint:"Quentin Tarantinos Meisterwerk gewann die Goldene Palme.",emoji:"🎬"},
  {id:"film_042",q:"Wie viele Episoden hat die Serie Narcos?",a:30,unit:"Episoden",hint:"3 Staffeln über Pablo Escobar und den Drogenhandel.",emoji:"🌿"},
  {id:"film_043",q:"Wie viele Millionen Dollar kostete die Produktion von Cleopatra (1963)?",a:44,unit:"Millionen Dollar",hint:"Damals das teuerste Filmbudget der Geschichte.",emoji:"👑"},
  {id:"film_044",q:"In welchem Jahr erschien Michael Jacksons Moonwalk?",a:1983,unit:"Jahr",hint:"Beim Motown-25-Gala-Konzert präsentiert.",emoji:"🕺"},
  {id:"film_045",q:"Wie viele Staffeln hat die Serie Dexter?",a:8,unit:"Staffeln",hint:"Plus New Blood – über den serienmordenden Forensiker.",emoji:"🔪"},
  {id:"film_046",q:"Wie viele Milliarden Dollar hat Top Gun: Maverick eingespielt?",a:1.49,unit:"Milliarden Dollar",hint:"Tom Cruise' erfolgreichster Film.",emoji:"✈️"},
  {id:"film_047",q:"In welchem Jahr startete TikTok international?",a:2018,unit:"Jahr",hint:"Als Musical.ly fusioniert und rebrandeded.",emoji:"📱"},
  {id:"film_048",q:"Wie viele Millionen Exemplare hat der Da Vinci Code verkauft?",a:80,unit:"Millionen",hint:"Dan Browns Bestseller über Geheimgesellschaften.",emoji:"📖"},
  {id:"film_049",q:"Wie viele Episoden hat The Sopranos?",a:86,unit:"Episoden",hint:"6 Staffeln über Tony Soprano.",emoji:"🍕"},
  {id:"film_050",q:"In welchem Jahr erschien Eminem's Slim Shady LP?",a:1999,unit:"Jahr",hint:"Sein Mainstream-Durchbruch.",emoji:"🎤"},
  {id:"film_051",q:"Wie viele Millionen Dollar hat Harry Potter und der Stein der Weisen eingespielt?",a:975,unit:"Millionen Dollar",hint:"Fast eine Milliarde für Teil 1.",emoji:"⚡"},
  {id:"film_052",q:"Wie viele Staffeln hat die Serie House of Cards?",a:6,unit:"Staffeln",hint:"Frank Underwoods Aufstieg zur Macht.",emoji:"🃏"},
  {id:"film_053",q:"In welchem Jahr erschien Beyoncés Lemonade?",a:2016,unit:"Jahr",hint:"Eines der meistdiskutierten Alben des Jahrzehnts.",emoji:"🎵"},
  {id:"film_054",q:"Wie viele Milliarden Dollar hat The Dark Knight eingespielt?",a:1,unit:"Milliarden Dollar",hint:"Heath Ledgers Joker bleibt unvergessen.",emoji:"🦇"},
  {id:"film_055",q:"Wie viele Episoden hat die Serie The Crown?",a:60,unit:"Episoden",hint:"6 Staffeln über die britische Königsfamilie.",emoji:"👑"},
  {id:"film_056",q:"In welchem Jahr wurde Spotify gegründet?",a:2006,unit:"Jahr",hint:"Daniel Ek startete die Musikrevolution.",emoji:"🎵"},
  {id:"film_057",q:"Wie viele Milliarden Dollar hat Titanic (1997) eingespielt?",a:2.2,unit:"Milliarden Dollar",hint:"Hielt 12 Jahre den Weltrekord.",emoji:"🚢"},
  {id:"film_058",q:"Wie viele Staffeln hat die Serie Prison Break?",a:5,unit:"Staffeln",hint:"Michael Scofield und sein Ausbruchplan.",emoji:"🔒"},
  {id:"film_059",q:"In welchem Jahr startete Facebook?",a:2004,unit:"Jahr",hint:"Zunächst nur für Harvard-Studenten.",emoji:"📱"},
  {id:"film_060",q:"Wie viele Millionen Abonnenten hat Pewdiepie auf YouTube?",a:111,unit:"Millionen",hint:"Längste Zeit der meistabonnierte Kanal.",emoji:"🎮"},
  {id:"film_061",q:"Wie viele Staffeln hat die Serie 24?",a:9,unit:"Staffeln",hint:"Jack Bauer rettet die Welt in 24 Stunden.",emoji:"💣"},
  {id:"film_062",q:"In welchem Jahr erschien Radioheads OK Computer?",a:1997,unit:"Jahr",hint:"Oft als bestes Album aller Zeiten gelistet.",emoji:"🎸"},
  {id:"film_063",q:"Wie viele Millionen Dollar hat The Lion King (1994) eingespielt?",a:987,unit:"Millionen Dollar",hint:"Disneys erfolgreichster Zeichentrickfilm.",emoji:"🦁"},
  {id:"film_064",q:"Wie viele Episoden hat die Serie Homeland?",a:96,unit:"Episoden",hint:"8 Staffeln über CIA-Agentin Carrie Mathison.",emoji:"🕵️"},
  {id:"film_065",q:"In welchem Jahr erschien Daft Punks Random Access Memories?",a:2013,unit:"Jahr",hint:"Get Lucky dominierte die Charts.",emoji:"🎵"},
  {id:"film_066",q:"Wie viele Millionen Dollar verdient Kim Kardashian pro Instagram-Post?",a:1,unit:"Millionen Dollar",hint:"Für bezahlte Kooperationen.",emoji:"📸"},
  {id:"film_067",q:"Wie viele Staffeln hat die Serie Suits?",a:9,unit:"Staffeln",hint:"Meghan Markle spielte Rachel Zane.",emoji:"⚖️"},
  {id:"film_068",q:"In welchem Jahr erschien der erste Transformers-Kinofilm?",a:2007,unit:"Jahr",hint:"Michael Bay und tonnenschwere CGI.",emoji:"🤖"},
  {id:"film_069",q:"Wie viele Millionen Dollar hat Shrek 2 eingespielt?",a:920,unit:"Millionen Dollar",hint:"Der erfolgreichste Animationsfilm seiner Zeit.",emoji:"🟢"},
  {id:"film_070",q:"In welchem Jahr erschien Adeles Album 21?",a:2011,unit:"Jahr",hint:"Rolling in the Deep war ein globaler Hit.",emoji:"🎵"},
  {id:"film_071",q:"Wie viele Millionen Dollar hat Inception eingespielt?",a:836,unit:"Millionen Dollar",hint:"Christopher Nolans Träum-im-Traum-Film.",emoji:"🌀"},
  {id:"film_072",q:"Wie viele Staffeln hat die Serie Billions?",a:7,unit:"Staffeln",hint:"Über Hedgefonds und Staatsanwälte.",emoji:"💰"},
  {id:"film_073",q:"In welchem Jahr erschien Kanye Wests The College Dropout?",a:2004,unit:"Jahr",hint:"Sein gefeierstes Debütalbum.",emoji:"🎵"},
  {id:"film_074",q:"Wie viele Milliarden Dollar hat The Avengers (2012) eingespielt?",a:1.52,unit:"Milliarden Dollar",hint:"Erster Milliarden-Superhelden-Film.",emoji:"🦸"},
  {id:"film_075",q:"Wie viele Episoden hat die Serie Sons of Anarchy?",a:92,unit:"Episoden",hint:"7 Staffeln über einen Motorradclub.",emoji:"🏍️"},
  {id:"film_076",q:"In welchem Jahr erschien Cardi Bs Invasion of Privacy?",a:2018,unit:"Jahr",hint:"Bodak Yellow machte sie zur ersten Frau mit #1-Rap-Hit.",emoji:"🎤"},
  {id:"film_077",q:"Wie viele Milliarden Dollar hat Aquaman (2018) eingespielt?",a:1.15,unit:"Milliarden Dollar",hint:"Erfolgreichster DC-Film.",emoji:"🌊"},
  {id:"film_078",q:"Wie viele Staffeln hat die Serie Westworld?",a:4,unit:"Staffeln",hint:"Über KI und Bewusstsein im Vergnügungspark.",emoji:"🤖"},
  {id:"film_079",q:"In welchem Jahr erschien Drakes Take Care?",a:2011,unit:"Jahr",hint:"Sein zweites Studioalbum – eines der einflussreichsten.",emoji:"🎵"},
  {id:"film_080",q:"Wie viele Millionen Dollar hat Iron Man (2008) eingespielt?",a:585,unit:"Millionen Dollar",hint:"Das MCU begann hier.",emoji:"🤖"},
  {id:"film_081",q:"Wie viele Staffeln hat die Serie Narcos: Mexico?",a:3,unit:"Staffeln",hint:"Über das Guadalajara-Kartell.",emoji:"🌵"},
  {id:"film_082",q:"In welchem Jahr erschien Ed Sheerans Multiply (+)?",a:2014,unit:"Jahr",hint:"Thinking Out Loud wurde ein Klassiker.",emoji:"🎸"},
  {id:"film_083",q:"Wie viele Milliarden Dollar hat Black Panther eingespielt?",a:1.35,unit:"Milliarden Dollar",hint:"Wegweisender Film für Repräsentation.",emoji:"🦅"},
  {id:"film_084",q:"Wie viele Episoden hat die Serie Peaky Blinders?",a:36,unit:"Episoden",hint:"6 Staffeln über die Shelby-Familie.",emoji:"🎩"},
  {id:"film_085",q:"In welchem Jahr erschien Lana Del Reys Born to Die?",a:2012,unit:"Jahr",hint:"Ihr Durchbruchsalbum.",emoji:"🌹"},
  {id:"film_086",q:"Wie viele Milliarden Dollar hat Jurassic World eingespielt?",a:1.67,unit:"Milliarden Dollar",hint:"3. Platz damals – heute überholt.",emoji:"🦕"},
  {id:"film_087",q:"Wie viele Staffeln hat die Serie Yellowstone?",a:5,unit:"Staffeln",hint:"Kevin Costners Rancher-Drama.",emoji:"🤠"},
  {id:"film_088",q:"In welchem Jahr startete der Podcast Serial?",a:2014,unit:"Jahr",hint:"Der erste große True-Crime-Podcast.",emoji:"🎙️"},
  {id:"film_089",q:"Wie viele Millionen Dollar hat The Hunger Games (2012) eingespielt?",a:694,unit:"Millionen Dollar",hint:"Jennifer Lawrence wurde zum Star.",emoji:"🏹"},
  {id:"film_090",q:"Wie viele Episoden hat die Serie Arrested Development?",a:84,unit:"Episoden",hint:"Oft als intelligenteste Sitcom bezeichnet.",emoji:"🍌"},
  {id:"film_091",q:"In welchem Jahr erschien Olivia Rodrigos SOUR?",a:2021,unit:"Jahr",hint:"drivers license dominierte die Charts.",emoji:"🎵"},
  {id:"film_092",q:"Wie viele Millionen Dollar hat Doctor Strange in the Multiverse of Madness eingespielt?",a:955,unit:"Millionen Dollar",hint:"Sam Raimis Horror-Marvel-Mash-up.",emoji:"🌀"},
  {id:"film_093",q:"Wie viele Staffeln hat die Serie Money Heist (La Casa de Papel)?",a:5,unit:"Staffeln",hint:"Spaniens erfolgreichste Netflix-Serie.",emoji:"💰"},
  {id:"film_094",q:"In welchem Jahr erschien Billie Eilishs When We All Fall Asleep?",a:2019,unit:"Jahr",hint:"Mit 17 Jahren zum Weltstar.",emoji:"🖤"},
  {id:"film_095",q:"Wie viele Milliarden Dollar hat Spider-Man: No Way Home eingespielt?",a:1.9,unit:"Milliarden Dollar",hint:"Dritter Platz aller Zeiten.",emoji:"🕷️"},
  {id:"film_096",q:"Wie viele Episoden hat die Serie Fleabag?",a:12,unit:"Episoden",hint:"Phoebe Waller-Bridges Meisterwerk.",emoji:"🦊"},
  {id:"film_097",q:"In welchem Jahr erschien The Weeknds Starboy?",a:2016,unit:"Jahr",hint:"Kollabo mit Daft Punk.",emoji:"⭐"},
  {id:"film_098",q:"Wie viele Millionen Dollar hat The Batman (2022) eingespielt?",a:770,unit:"Millionen Dollar",hint:"Robert Pattinson als dunkler Ritter.",emoji:"🦇"},
  {id:"film_099",q:"Wie viele Staffeln hat die Serie Better Call Saul?",a:6,unit:"Staffeln",hint:"Breaking Bad Prequel über Saul Goodman.",emoji:"⚖️"},
  {id:"film_100",q:"In welchem Jahr erschien Harry Styles' As It Was als Single?",a:2022,unit:"Jahr",hint:"Meistgestreamter Song 2022 weltweit.",emoji:"🎵"},
  {id:"film_101",q:"Wie viele Milliarden Dollar hat Minions (2015) eingespielt?",a:1.16,unit:"Milliarden Dollar",hint:"Die kleinen Gelben wurden zum Kulturphänomen.",emoji:"💛"},
  {id:"film_102",q:"Wie viele Staffeln hat die Serie True Detective?",a:4,unit:"Staffeln",hint:"Anthologieserie – jede Staffel eine neue Geschichte.",emoji:"🔍"},
  {id:"film_103",q:"In welchem Jahr erschien Dua Lipas Future Nostalgia?",a:2020,unit:"Jahr",hint:"Levitating wurde ein globaler Hit.",emoji:"💃"},
  {id:"film_104",q:"Wie viele Milliarden Dollar hat Fast and Furious 7 eingespielt?",a:1.52,unit:"Milliarden Dollar",hint:"Paul Walkers letzter Film.",emoji:"🚗"},
  {id:"film_105",q:"Wie viele Episoden hat die Serie The Mandalorian?",a:24,unit:"Episoden",hint:"3 Staffeln – Baby Yoda wurde zum Internet-Phänomen.",emoji:"⭐"},
  {id:"film_106",q:"In welchem Jahr erschien Kendrick Lamars DAMN.?",a:2017,unit:"Jahr",hint:"Erster Rap-Album mit dem Pulitzer-Preis.",emoji:"🎵"},
  {id:"film_107",q:"Wie viele Milliarden Dollar hat Captain America: Civil War eingespielt?",a:1.15,unit:"Milliarden Dollar",hint:"Marvel gegen sich selbst.",emoji:"🛡️"},
  {id:"film_108",q:"Wie viele Staffeln hat die Serie Succession?",a:4,unit:"Staffeln",hint:"Die Roy-Familie und der Medienmogul.",emoji:"💼"},
  {id:"film_109",q:"In welchem Jahr erschien Lorde's Pure Heroine?",a:2013,unit:"Jahr",hint:"Royals wurde mit 16 Jahren ein Welthit.",emoji:"🎵"},
  {id:"film_110",q:"Wie viele Milliarden Dollar hat Toy Story 3 eingespielt?",a:1.07,unit:"Milliarden Dollar",hint:"Pixars erstes Milliarden-Film.",emoji:"🤖"},
  {id:"film_111",q:"Wie viele Episoden hat die Serie The Boys?",a:32,unit:"Episoden",hint:"4 Staffeln – Superhelden mal böse.",emoji:"⚡"},
  {id:"film_112",q:"In welchem Jahr erschien Stormzy's Gang Signs & Prayer?",a:2017,unit:"Jahr",hint:"Erstes Grime-Album auf Platz 1 in UK.",emoji:"🎤"},
  {id:"film_113",q:"Wie viele Millionen Dollar hat Guardians of the Galaxy Vol. 3 eingespielt?",a:845,unit:"Millionen Dollar",hint:"James Gunns emotionaler Abschluss.",emoji:"🌌"},
  {id:"film_114",q:"Wie viele Staffeln hat die Serie Ozark?",a:4,unit:"Staffeln",hint:"Breaking Bad der Seen.",emoji:"💸"},
  {id:"film_115",q:"In welchem Jahr erschien Frank Oceans Blonde?",a:2016,unit:"Jahr",hint:"Eines der wichtigsten Alben der 2010er.",emoji:"🎵"},
  {id:"film_116",q:"Wie viele Millionen Dollar hat Interstellar eingespielt?",a:701,unit:"Millionen Dollar",hint:"Christopher Nolans Weltraumepos.",emoji:"🌌"},
  {id:"film_117",q:"Wie viele Episoden hat die Serie Squid Game?",a:9,unit:"Episoden",hint:"Netflix' meistgesehene Serie aller Zeiten.",emoji:"🦑"},
  {id:"film_118",q:"In welchem Jahr erschien Ariana Grandes Thank U, Next?",a:2019,unit:"Jahr",hint:"In einer Woche nach ihrem Breakup veröffentlicht.",emoji:"💅"},
  {id:"film_119",q:"Wie viele Millionen Dollar hat The Greatest Showman eingespielt?",a:435,unit:"Millionen Dollar",hint:"Hugh Jackman als P.T. Barnum.",emoji:"🎪"},
  {id:"film_120",q:"Wie viele Staffeln hat die Serie The Witcher?",a:3,unit:"Staffeln",hint:"Henry Cavill als Geralt – bis Staffel 3.",emoji:"⚔️"},
  {id:"film_121",q:"In welchem Jahr erschien Childish Gambinos This Is America?",a:2018,unit:"Jahr",hint:"Das Musikvideo wurde viral wegen seiner Symbolik.",emoji:"🎵"},
  {id:"film_122",q:"Wie viele Millionen Dollar hat Wonder Woman (2017) eingespielt?",a:822,unit:"Millionen Dollar",hint:"Erster weiblicher Superhelden-Blockbuster.",emoji:"⚡"},
  {id:"film_123",q:"Wie viele Episoden hat die Serie Dark (Netflix Deutschland)?",a:26,unit:"Episoden",hint:"3 Staffeln – eine der besten deutschen Serien.",emoji:"🌀"},
  {id:"film_124",q:"In welchem Jahr erschien Post Malones Beerbongs & Bentleys?",a:2018,unit:"Jahr",hint:"Sein zweites Studioalbum mit Rekord-Streams.",emoji:"🎵"},
  {id:"film_125",q:"Wie viele Milliarden Dollar hat Deadpool & Wolverine eingespielt?",a:1.34,unit:"Milliarden Dollar",hint:"Erster R-rated Marvel-Film mit Milliarde.",emoji:"🔴"},
  {id:"film_126",q:"Wie viele Staffeln hat die Serie Emily in Paris?",a:4,unit:"Staffeln",hint:"Amerikanerin in Paris – guilty pleasure.",emoji:"🗼"},
  {id:"film_127",q:"In welchem Jahr erschien SZA's SOS?",a:2022,unit:"Jahr",hint:"Meistgestreamtes Debütalbum eines weiblichen Künstlers.",emoji:"🎵"},
  {id:"film_128",q:"Wie viele Milliarden Dollar hat Joker (2019) eingespielt?",a:1.08,unit:"Milliarden Dollar",hint:"Joaquin Phoenix gewann den Oscar.",emoji:"🃏"},
  {id:"film_129",q:"Wie viele Episoden hat die Serie Ted Lasso?",a:34,unit:"Episoden",hint:"3 Staffeln – Apples Feel-Good-Serie.",emoji:"⚽"},
  {id:"film_130",q:"In welchem Jahr erschien Weeknds Dawn FM?",a:2022,unit:"Jahr",hint:"Ein komplettes 80er-Synth-Konzept-Album.",emoji:"📻"},
  {id:"film_131",q:"Wie viele Millionen Dollar hat Forrest Gump eingespielt?",a:678,unit:"Millionen Dollar",hint:"Tom Hanks gewann seinen zweiten Oscar.",emoji:"🏃"},
  {id:"film_132",q:"Wie viele Staffeln hat die Serie Big Little Lies?",a:2,unit:"Staffeln",hint:"Nicole Kidman und Reese Witherspoon.",emoji:"🌊"},
  {id:"film_133",q:"In welchem Jahr erschien Twenty One Pilots Blurryface?",a:2015,unit:"Jahr",hint:"Stressed Out wurde zum Hymnus einer Generation.",emoji:"🎵"},
  {id:"film_134",q:"Wie viele Millionen Dollar hat The Revenant eingespielt?",a:533,unit:"Millionen Dollar",hint:"DiCaprio gewann endlich seinen Oscar.",emoji:"🐻"},
  {id:"film_135",q:"Wie viele Episoden hat die Serie Euphoria?",a:16,unit:"Episoden",hint:"2 Staffeln – Zendayas Durchbruch als Erwachsene.",emoji:"💊"},
  {id:"film_136",q:"In welchem Jahr erschien Tyler the Creators Igor?",a:2019,unit:"Jahr",hint:"Gewann den Grammy für bestes Rap-Album.",emoji:"🎵"},
  {id:"film_137",q:"Wie viele Millionen Dollar hat Black Widow eingespielt?",a:379,unit:"Millionen Dollar",hint:"Enttäuschend wegen gleichzeitigem Disney+-Release.",emoji:"🕷️"},
  {id:"film_138",q:"Wie viele Staffeln hat die Serie Yellowjackets?",a:3,unit:"Staffeln",hint:"Über überlebende Mädchen nach einem Flugzeugabsturz.",emoji:"✈️"},
  {id:"film_139",q:"In welchem Jahr erschien Mitskis Puberty 2?",a:2016,unit:"Jahr",hint:"Indie-Darling und eine der besten Songwriterinnen.",emoji:"🎵"},
  {id:"film_140",q:"Wie viele Millionen Dollar hat Gladiator (2000) eingespielt?",a:460,unit:"Millionen Dollar",hint:"Russell Crowe gewann den Oscar.",emoji:"⚔️"},
  {id:"film_141",q:"Wie viele Episoden hat die Serie White Lotus?",a:14,unit:"Episoden",hint:"2 Staffeln – Satire über reiche Touristen.",emoji:"🌺"},
  {id:"film_142",q:"In welchem Jahr erschien Childish Gambino's Awaken, My Love!?",a:2016,unit:"Jahr",hint:"Redbone wurde zu einem 70er-Funk-Klassiker.",emoji:"🎵"},
  {id:"film_143",q:"Wie viele Millionen Dollar hat No Time to Die eingespielt?",a:774,unit:"Millionen Dollar",hint:"Daniel Craigs letzter Bond.",emoji:"🔫"},
  {id:"film_144",q:"Wie viele Staffeln hat die Serie The Last of Us?",a:2,unit:"Staffeln",hint:"HBO-Adaption des preisgekrönten Videospiels.",emoji:"🍄"},
  {id:"film_145",q:"In welchem Jahr erschien Normani's Motivation (Single)?",a:2019,unit:"Jahr",hint:"Ihr Solo-Durchbruch nach Fifth Harmony.",emoji:"💃"},
  {id:"film_146",q:"Wie viele Millionen Dollar hat Encanto eingespielt?",a:256,unit:"Millionen Dollar",hint:"We Don't Talk About Bruno wurde viral.",emoji:"🌈"},
  {id:"film_147",q:"Wie viele Episoden hat die Serie Station Eleven?",a:10,unit:"Episoden",hint:"Pandemie-Drama – kurz nach Covid relevant.",emoji:"☄️"},
  {id:"film_148",q:"In welchem Jahr erschien Weyes Bloods And in the Darkness, Hearts Aglow?",a:2022,unit:"Jahr",hint:"Eine der Kritikerlieblings-LPs des Jahres.",emoji:"🎵"},
  {id:"film_149",q:"Wie viele Milliarden Dollar hat Avatar: The Way of Water eingespielt?",a:2.32,unit:"Milliarden Dollar",hint:"Cameron bricht wieder Rekorde.",emoji:"🌊"},
  {id:"film_150",q:"Wie viele Staffeln hat die Serie The Bear?",a:3,unit:"Staffeln",hint:"Das Restaurant-Drama gewann viele Emmys.",emoji:"🍳"},
  {id:"film_151",q:"In welchem Jahr erschien Bad Bunnys Un Verano Sin Ti?",a:2022,unit:"Jahr",hint:"Meistgestreamtes Album auf Spotify 2022.",emoji:"🐇"},
  {id:"film_152",q:"Wie viele Milliarden Dollar hat The Super Mario Bros. Movie eingespielt?",a:1.36,unit:"Milliarden Dollar",hint:"Erfolgreichster Videospiel-Film aller Zeiten.",emoji:"🍄"},
  {id:"film_153",q:"Wie viele Episoden hat die Serie Only Murders in the Building?",a:30,unit:"Episoden",hint:"3 Staffeln – Hulu True-Crime-Comedy.",emoji:"🔍"},
  {id:"film_154",q:"In welchem Jahr erschien Ice Spice's debut mixtape?",a:2023,unit:"Jahr",hint:"Ihr Aufstieg von Bronx bis Weltberühmtheit.",emoji:"🧡"},
  {id:"film_155",q:"Wie viele Millionen Dollar hat The Notebook (2004) eingespielt?",a:115,unit:"Millionen Dollar",hint:"Ryan Gosling und Rachel McAdams.",emoji:"💕"},
  {id:"film_156",q:"Wie viele Staffeln hat die Serie Abbott Elementary?",a:3,unit:"Staffeln",hint:"Mockumentary über amerikanische Grundschulen.",emoji:"🏫"},
  {id:"film_157",q:"In welchem Jahr erschien Nicki Minajs Pink Friday?",a:2010,unit:"Jahr",hint:"Ihr Debütalbum – machte sie zur Queen of Rap.",emoji:"💕"},
  {id:"film_158",q:"Wie viele Millionen Dollar hat Wolf of Wall Street eingespielt?",a:392,unit:"Millionen Dollar",hint:"DiCaprio und Scorsese – 3 Stunden Exzess.",emoji:"💰"},
  {id:"film_159",q:"Wie viele Staffeln hat die Serie Severance?",a:2,unit:"Staffeln",hint:"Apple TV+ – Arbeit und Privatleben getrennt.",emoji:"🔪"},
  {id:"film_160",q:"In welchem Jahr erschien Paramore's After Laughter?",a:2017,unit:"Jahr",hint:"Ihr Pop-orientiertes Comeback-Album.",emoji:"🎵"},
  {id:"film_161",q:"Wie viele Millionen Dollar hat Glass Onion (Netflix) gekostet?",a:40,unit:"Millionen Dollar",hint:"Knives-Out-Sequel – exklusiv auf Netflix.",emoji:"🧅"},
  {id:"film_162",q:"Wie viele Episoden hat die Serie Mindhunter?",a:19,unit:"Episoden",hint:"2 Staffeln – Netflix-Serie über FBI-Profiler.",emoji:"🔍"},
  {id:"film_163",q:"In welchem Jahr erschien Coldplays Music of the Spheres?",a:2021,unit:"Jahr",hint:"Ihre umstrittenste – und gleichzeitig kommerziell erfolgreichste LP.",emoji:"🌌"},
  {id:"film_164",q:"Wie viele Millionen Dollar hat The Truman Show eingespielt?",a:264,unit:"Millionen Dollar",hint:"Jim Carrey in einem Klassikunterricht.",emoji:"📺"},
  {id:"film_165",q:"Wie viele Staffeln hat die Serie House M.D.?",a:8,unit:"Staffeln",hint:"Dr. House – der schnodderige Diagnosegenie.",emoji:"🏥"},
  {id:"film_166",q:"In welchem Jahr erschien SAABs Sorry 4 Waiting?",a:2021,unit:"Jahr",hint:"Aufstrebendes Rap-Talent aus Baltimore.",emoji:"🎵"},
  {id:"film_167",q:"Wie viele Staffeln hat die Serie Mad Men?",a:7,unit:"Staffeln",hint:"Über die Werbewelt der 1960er.",emoji:"🥃"},
  {id:"film_168",q:"In welchem Jahr erschien Tame Impalas Currents?",a:2015,unit:"Jahr",hint:"Psychedelischer Pop – Cornerstone.",emoji:"🌀"},
  {id:"film_169",q:"Wie viele Millionen Dollar hat Oppenheimer (2023) eingespielt?",a:952,unit:"Millionen Dollar",hint:"Christopher Nolans Atombombe.",emoji:"💥"},
  {id:"film_170",q:"Wie viele Episoden hat die Serie Killing Eve?",a:32,unit:"Episoden",hint:"4 Staffeln – Jodie Comer als Villanelle.",emoji:"🔪"},
  {id:"film_171",q:"In welchem Jahr erschien FKA Twigs LP1?",a:2014,unit:"Jahr",hint:"Eines der einflussreichsten Alben der 2010er.",emoji:"🎵"},
  {id:"film_172",q:"Wie viele Millionen Dollar hat La La Land eingespielt?",a:446,unit:"Millionen Dollar",hint:"Emma Stone und Ryan Gosling tanzen in LA.",emoji:"🌆"},
  {id:"film_173",q:"Wie viele Staffeln hat die Serie Chernobyl?",a:1,unit:"Staffel",hint:"5 Episoden – HBO Miniserie über die Katastrophe.",emoji:"☢️"},
  {id:"film_174",q:"In welchem Jahr erschien Lizzo's Cuz I Love You?",a:2019,unit:"Jahr",hint:"Truth Hurts wurde nachträglich ihr größter Hit.",emoji:"🎵"},
  {id:"film_175",q:"Wie viele Millionen Dollar hat Schindler's List eingespielt?",a:322,unit:"Millionen Dollar",hint:"Spielbergs Holocaust-Drama gewann 7 Oscars.",emoji:"🕯️"},
  {id:"film_176",q:"Wie viele Episoden hat die Serie Sharp Objects?",a:8,unit:"Episoden",hint:"Amy Adams in der HBO-Miniserie.",emoji:"🔪"},
  {id:"film_177",q:"In welchem Jahr erschien Clairos Sling?",a:2021,unit:"Jahr",hint:"Indie-Pop-Phänomen.",emoji:"🎵"},
  {id:"film_178",q:"Wie viele Millionen Dollar hat Everything Everywhere All at Once eingespielt?",a:70,unit:"Millionen Dollar",hint:"Gewann 7 Oscars mit kleinem Budget.",emoji:"🥯"},
  {id:"film_179",q:"Wie viele Staffeln hat die Serie Invincible (Amazon)?",a:2,unit:"Staffeln",hint:"Animationsserie über einen jugendlichen Superhelden.",emoji:"💪"},
  {id:"film_180",q:"In welchem Jahr erschien Dojas Cats Planet Her?",a:2021,unit:"Jahr",hint:"Need to Know wurde ihr größter Chart-Hit.",emoji:"🐱"},
  {id:"film_181",q:"Wie viele Millionen Dollar hat Rocketman eingespielt?",a:195,unit:"Millionen Dollar",hint:"Elton Johns Biopic mit Taron Egerton.",emoji:"🎹"},
  {id:"film_182",q:"Wie viele Episoden hat die Serie Yellowstone?",a:55,unit:"Episoden",hint:"5 Staffeln – Paramount's Mega-Hit.",emoji:"🤠"},
  {id:"film_183",q:"In welchem Jahr erschien Solange's A Seat at the Table?",a:2016,unit:"Jahr",hint:"Eines der bedeutendsten Soul-Alben der 2010er.",emoji:"🎵"},
  {id:"film_184",q:"Wie viele Millionen Dollar hat Knives Out eingespielt?",a:311,unit:"Millionen Dollar",hint:"Rian Johnsons Whodunit-Revival.",emoji:"🔪"},
  {id:"film_185",q:"Wie viele Staffeln hat die Serie Atlanta?",a:4,unit:"Staffeln",hint:"Donald Glovers Meisterwerk.",emoji:"🌙"},
  {id:"film_186",q:"In welchem Jahr erschien Phoebe Bridgers Punisher?",a:2020,unit:"Jahr",hint:"Eines der besten Indie-Folk-Alben des Jahrzehnts.",emoji:"🎵"},
  {id:"film_187",q:"Wie viele Millionen Dollar hat The Martian eingespielt?",a:631,unit:"Millionen Dollar",hint:"Matt Damon wächst Kartoffeln auf dem Mars.",emoji:"🥔"},
  {id:"film_188",q:"Wie viele Staffeln hat die Serie Bridgerton?",a:3,unit:"Staffeln",hint:"Netflix Regency-Romance.",emoji:"🌸"},
  {id:"film_189",q:"In welchem Jahr erschien Stromae's Multitude?",a:2022,unit:"Jahr",hint:"Sein langersehntes drittes Album.",emoji:"🎵"},
  {id:"film_190",q:"Wie viele Millionen Dollar hat Bohemian Rhapsody eingespielt?",a:910,unit:"Millionen Dollar",hint:"Rami Malek als Freddie Mercury.",emoji:"🎸"},
  {id:"film_191",q:"Wie viele Episoden hat die Serie Succession?",a:39,unit:"Episoden",hint:"4 Staffeln – eine der besten Serien aller Zeiten.",emoji:"💼"},
  {id:"film_192",q:"In welchem Jahr erschien Weyes Bloods Titanic Rising?",a:2019,unit:"Jahr",hint:"Ein Album über den Klimawandel.",emoji:"🌊"},
  {id:"film_193",q:"Wie viele Millionen Dollar hat Top Gun (1986) ursprünglich eingespielt?",a:356,unit:"Millionen Dollar",hint:"Der Film der Tom Cruise zum Star machte.",emoji:"✈️"},
  {id:"film_194",q:"Wie viele Staffeln hat die Serie Banshee?",a:4,unit:"Staffeln",hint:"Brutale Crime-Serie auf Cinemax.",emoji:"🔫"},
  {id:"film_195",q:"In welchem Jahr erschien Burna Boys Love, Damini?",a:2022,unit:"Jahr",hint:"Afrobeats-Superstar.",emoji:"🎵"},
  {id:"film_196",q:"Wie viele Millionen Dollar hat Morbius (2022) eingespielt?",a:167,unit:"Millionen Dollar",hint:"Ein Meme wurde daraus: It's Morbin Time.",emoji:"🦇"},
  {id:"film_197",q:"Wie viele Staffeln hat die Serie Twin Peaks?",a:3,unit:"Staffeln",hint:"David Lynchs Meisterwerk.",emoji:"🌲"},
  {id:"film_198",q:"In welchem Jahr erschien Gorillaz Demon Days?",a:2005,unit:"Jahr",hint:"Feel Good Inc. war überall.",emoji:"🎵"},
  {id:"film_199",q:"Wie viele Millionen Dollar hat Se7en eingespielt?",a:327,unit:"Millionen Dollar",hint:"What's in the box?!",emoji:"📦"},
  {id:"film_200",q:"Wie viele Staffeln hat die Serie The Expanse?",a:6,unit:"Staffeln",hint:"Harte Science-Fiction im Weltraum.",emoji:"🚀"},
  {id:"film_201",q:"In welchem Jahr erschien Jack Johnsons In Between Dreams?",a:2005,unit:"Jahr",hint:"Banana Pancakes wurde ein Sommerhit.",emoji:"🎵"},
  {id:"film_202",q:"Wie viele Millionen Dollar hat Sonic the Hedgehog (2020) eingespielt?",a:319,unit:"Millionen Dollar",hint:"Redesign nach Fan-Protest rettete den Film.",emoji:"💙"},
  {id:"film_203",q:"Wie viele Staffeln hat die Serie Black Sails?",a:4,unit:"Staffeln",hint:"Piraten-Prequel zu Schatzinsel.",emoji:"🏴‍☠️"},
  {id:"film_204",q:"In welchem Jahr erschien Caribous Suddenly?",a:2020,unit:"Jahr",hint:"Elektronik und Emotion.",emoji:"🎵"},
  {id:"film_205",q:"Wie viele Millionen Dollar hat Parasite (2019) eingespielt?",a:258,unit:"Millionen Dollar",hint:"Erster nicht-englischer Film mit dem Oscar für besten Film.",emoji:"🏠"},
  {id:"film_206",q:"Wie viele Staffeln hat die Serie Devs?",a:1,unit:"Staffel",hint:"FX Miniserie über Quantencomputer.",emoji:"💻"},
  {id:"film_207",q:"In welchem Jahr erschien Sufjan Stevens' Carrie & Lowell?",a:2015,unit:"Jahr",hint:"Eines der traurigsten und schönsten Alben.",emoji:"🎵"},
  {id:"film_208",q:"Wie viele Episoden hat die Serie Sopranos?",a:86,unit:"Episoden",hint:"6 Staffeln – eines der besten TV-Dramen.",emoji:"🍕"},
  {id:"film_209",q:"In welchem Jahr erschien Nirvanas In Utero?",a:1993,unit:"Jahr",hint:"Ihr letztes Studioalbum vor Cobains Tod.",emoji:"🎸"},
  {id:"film_210",q:"Wie viele Millionen Dollar hat Mission Impossible – Dead Reckoning eingespielt?",a:568,unit:"Millionen Dollar",hint:"Tom Cruise setzt immer noch auf Stunts.",emoji:"🎬"},
  {id:"film_211",q:"Wie viele Staffeln hat die Serie The Handmaid's Tale?",a:5,unit:"Staffeln",hint:"Basiert auf Margaret Atwoods Roman.",emoji:"🔴"},
  {id:"film_212",q:"In welchem Jahr erschien Kendrick Lamars To Pimp a Butterfly?",a:2015,unit:"Jahr",hint:"Kritisch als eines der wichtigsten Alben gelobt.",emoji:"🎵"},
  {id:"film_213",q:"Wie viele Millionen Dollar hat The Notebook eingespielt?",a:115,unit:"Millionen Dollar",hint:"Ryan Gosling und Rachel McAdams.",emoji:"💕"},
  {id:"film_214",q:"Wie viele Staffeln hat die Serie Breaking Bad?",a:5,unit:"Staffeln",hint:"62 Episoden über Walter Whites Fall.",emoji:"🧪"},
  {id:"film_215",q:"In welchem Jahr erschien Lady Gagas The Fame?",a:2008,unit:"Jahr",hint:"Poker Face wurde ihr erster globaler Hit.",emoji:"🎤"},
  {id:"film_216",q:"Wie viele Millionen Dollar hat Crazy Rich Asians eingespielt?",a:238,unit:"Millionen Dollar",hint:"Erster Hollywood-Film mit asiatischem Hauptcast seit 1993.",emoji:"💰"},
  {id:"film_217",q:"Wie viele Staffeln hat die Serie Westworld auf HBO?",a:4,unit:"Staffeln",hint:"Über KI und Bewusstsein.",emoji:"🤖"},
  {id:"film_218",q:"In welchem Jahr erschien Jay-Zs The Blueprint?",a:2001,unit:"Jahr",hint:"Veröffentlicht am 11. September 2001.",emoji:"🎵"},
  {id:"film_219",q:"Wie viele Millionen Dollar hat John Wick 4 eingespielt?",a:440,unit:"Millionen Dollar",hint:"Keanu Reeves als unsterblicher Auftragskiller.",emoji:"🔫"},
  {id:"film_220",q:"Wie viele Staffeln hat die Serie Killing Eve?",a:4,unit:"Staffeln",hint:"Sandra Oh und Jodie Comer.",emoji:"🔪"},
  {id:"film_221",q:"In welchem Jahr erschien Rihanna's ANTI?",a:2016,unit:"Jahr",hint:"Work war überall zu hören.",emoji:"🎵"},
  {id:"film_222",q:"Wie viele Millionen Dollar hat Glass Onion eingespielt?",a:311,unit:"Millionen Dollar",hint:"Knives-Out-Sequel exklusiv auf Netflix.",emoji:"🧅"},
  {id:"film_223",q:"In welchem Jahr erschien Pharrell Williams Happy?",a:2013,unit:"Jahr",hint:"Aus dem Despicable Me 2 Soundtrack.",emoji:"😊"},
  {id:"film_224",q:"Wie viele Millionen Dollar hat Scream (2022) eingespielt?",a:140,unit:"Millionen Dollar",hint:"Legacy-Sequel – 25 Jahre nach dem Original.",emoji:"🔪"},
  {id:"film_225",q:"Wie viele Staffeln hat die Serie Ted Lasso auf Apple TV+?",a:3,unit:"Staffeln",hint:"Feel-Good-Soccer-Drama.",emoji:"⚽"},
  {id:"film_226",q:"In welchem Jahr erschien Billie Eilishs Happier Than Ever?",a:2021,unit:"Jahr",hint:"Ihr zweites Studioalbum.",emoji:"🎵"},
  {id:"film_227",q:"Wie viele Staffeln hat die Serie Skins (UK)?",a:7,unit:"Staffeln",hint:"Britische Jugendserie mit wechselndem Cast.",emoji:"🎭"},
  {id:"film_228",q:"In welchem Jahr erschien The Weeknds Beauty Behind the Madness?",a:2015,unit:"Jahr",hint:"Cant Feel My Face – globaler Hit.",emoji:"🎵"},
  {id:"film_229",q:"Wie viele Millionen Dollar hat The Nun eingespielt?",a:365,unit:"Millionen Dollar",hint:"Teil des Conjuring-Universums.",emoji:"👻"},
  {id:"film_230",q:"Wie viele Staffeln hat die Serie Pose (FX)?",a:3,unit:"Staffeln",hint:"LGBTQ+-Drama über die Ballroom-Kultur der 80er.",emoji:"🌈"},
  {id:"film_231",q:"In welchem Jahr erschien Macklemores The Heist?",a:2012,unit:"Jahr",hint:"Thrift Shop wurde ein viraler Hit.",emoji:"🛍️"},
  {id:"film_232",q:"Wie viele Millionen Dollar hat Mamma Mia! eingespielt?",a:608,unit:"Millionen Dollar",hint:"ABBA-Musical verfilmt.",emoji:"🎵"},
  {id:"film_233",q:"Wie viele Staffeln hat die Serie True Blood?",a:7,unit:"Staffeln",hint:"Vampir-Drama auf HBO.",emoji:"🧛"},
  {id:"film_234",q:"In welchem Jahr erschien Katy Perrys Teenage Dream?",a:2010,unit:"Jahr",hint:"5 Songs von einem Album schafften Nummer 1.",emoji:"🎤"},
  {id:"film_235",q:"Wie viele Millionen Dollar hat Nope (2022) eingespielt?",a:171,unit:"Millionen Dollar",hint:"Jordan Peeles UFO-Horror.",emoji:"👽"},
  {id:"film_236",q:"Wie viele Staffeln hat die Serie Alias?",a:5,unit:"Staffeln",hint:"Jennifer Garner als CIA-Agentin.",emoji:"🕵️"},
  {id:"film_237",q:"In welchem Jahr erschien Lorde's Melodrama?",a:2017,unit:"Jahr",hint:"Perfect Places – eines ihrer besten Alben.",emoji:"🎵"},
  {id:"film_238",q:"Wie viele Milliarden Dollar hat Der König der Löwen (2019) eingespielt?",a:1.66,unit:"Milliarden Dollar",hint:"Fotorealistisches Remake des Klassikers.",emoji:"🦁"},
  {id:"film_239",q:"Wie viele Staffeln hat die Serie Justified?",a:6,unit:"Staffeln",hint:"Timothy Olyphant als US-Marshal in Kentucky.",emoji:"🤠"},
  {id:"film_240",q:"In welchem Jahr erschien Frank Oceans Channel Orange?",a:2012,unit:"Jahr",hint:"Sein Durchbruchsalbum.",emoji:"🍊"},
  {id:"film_241",q:"Wie viele Millionen Dollar hat Minions: The Rise of Gru eingespielt?",a:940,unit:"Millionen Dollar",hint:"Die kleinen Gelben sind unschlagbar.",emoji:"💛"},
  {id:"film_242",q:"Wie viele Staffeln hat die Serie Younger?",a:7,unit:"Staffeln",hint:"Hilary Duff und Sutton Foster.",emoji:"👩"},
  {id:"film_243",q:"In welchem Jahr erschien Queens of the Stone Ages Songs for the Deaf?",a:2002,unit:"Jahr",hint:"No One Knows wurde ihr bekanntester Song.",emoji:"🎸"},
  {id:"film_244",q:"Wie viele Millionen Dollar hat The Lost City eingespielt?",a:190,unit:"Millionen Dollar",hint:"Sandra Bullock und Channing Tatum.",emoji:"🌿"},
  {id:"film_245",q:"Wie viele Staffeln hat die Serie Reign (CW)?",a:4,unit:"Staffeln",hint:"Über Maria Königin von Schottland.",emoji:"👑"}
];
