// 🍆 SEX & TABUS – Erwachsene – 250 Fragen
export default [
  {q:"Wie viele Millionen Pornos gibt es schätzungsweise im Internet?",a:4,unit:"Millionen Videos",hint:"Über 4 Millionen Videos – und täglich kommen neue dazu.",emoji:"🔞"},
  {q:"Wie viele Millionen Besucher hat Pornhub pro Tag?",a:130,unit:"Millionen",hint:"Einer der meistbesuchten Websites weltweit.",emoji:"💻"},
  {q:"Wie viele Gramm wiegt ein durchschnittlicher Dildo?",a:200,unit:"Gramm",hint:"Variiert stark je nach Material und Größe.",emoji:"🍆"},
  {q:"In welchem Jahr wurde das erste Kondom aus Latex hergestellt?",a:1920,unit:"Jahr",hint:"Davor waren Kondome aus Schafsdarm.",emoji:"💊"},
  {q:"Wie viele Kalorien verbrennt man beim Oralsex pro Stunde?",a:100,unit:"kcal",hint:"Mehr als man denkt – Muskeln sind im Einsatz.",emoji:"🔥"},
  {q:"Wie viele cm ist der durchschnittliche erigierte Penis weltweit?",a:13.1,unit:"cm",hint:"Meta-Analyse 2015 mit 15.000+ Männern weltweit.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen weltweit sind an HIV infiziert?",a:39,unit:"Millionen",hint:"Stand 2022 – antiretrovirale Therapie hilft.",emoji:"🎗️"},
  {q:"Wie lange dauert der durchschnittliche Geschlechtsakt laut Studie in Minuten?",a:5.4,unit:"Minuten",hint:"Von Penetration bis Ejakulation gemessen.",emoji:"⏱️"},
  {q:"Wie viele Millionen Spermien enthält ein durchschnittlicher Ejakulationsschuss?",a:250,unit:"Millionen",hint:"Nur eines davon befruchtet die Eizelle.",emoji:"🔬"},
  {q:"In welchem Jahr wurde Viagra zugelassen?",a:1998,unit:"Jahr",hint:"FDA-Zulassung am 27. März 1998.",emoji:"💊"},
  {q:"Wie viele Nervenendigungen hat die Klitoris?",a:8000,unit:"Nervenenden",hint:"Doppelt so viele wie der Penis.",emoji:"⚡"},
  {q:"Wie viele cm ist die durchschnittliche Vaginaltiefe in Ruhe?",a:9,unit:"cm",hint:"Erregt dehnt sie sich auf 12-15 cm aus.",emoji:"📏"},
  {q:"Wie viele Milliarden Dollar wert ist die globale Sexspielzeug-Industrie?",a:33,unit:"Milliarden Dollar",hint:"33 Milliarden Dollar jährlich – wächst stark.",emoji:"💰"},
  {q:"Wie viele Mal pro Jahr hat ein Deutscher durchschnittlich Sex?",a:98,unit:"Mal",hint:"Fast zweimal pro Woche laut Umfragen.",emoji:"❤️"},
  {q:"Wie viele Stunden im Leben verbringt ein Mensch mit Sex?",a:520,unit:"Stunden",hint:"Etwa 21 Tage – über ein Leben gerechnet.",emoji:"⏰"},
  {q:"Wie viele cm beträgt die durchschnittliche Penislänge schlaff?",a:9,unit:"cm",hint:"Im Durchschnitt 7-10 cm schlaff.",emoji:"📏"},
  {q:"In welchem Jahr wurde der erste Vibrator erfunden?",a:1880,unit:"Jahr",hint:"Ursprünglich als medizinisches Gerät für 'Hysterie'.",emoji:"⚡"},
  {q:"Wie viele Sekunden dauert die durchschnittliche weibliche Orgasmus-Kontraktion?",a:22,unit:"Sekunden",hint:"Weibliche Orgasmen dauern länger als männliche.",emoji:"🌊"},
  {q:"Wie viele Millionen Mal wird der Begriff 'sex' täglich gegoogelt?",a:8,unit:"Millionen",hint:"Einer der meistgesuchten Begriffe weltweit.",emoji:"🔍"},
  {q:"Wie viele cm Durchmesser hat eine durchschnittliche Brustwarze?",a:1.5,unit:"cm",hint:"Variiert stark – von 0,5cm bis über 2,5cm.",emoji:"📏"},
  {q:"In welchem Jahr wurde die Pille erfunden?",a:1960,unit:"Jahr",hint:"FDA-Zulassung 1960 – revolutionierte Frauenrechte.",emoji:"💊"},
  {q:"Wie viele Millionen Kondome werden weltweit täglich verwendet?",a:6,unit:"Millionen",hint:"6 Mio. täglich = ~2 Milliarden pro Jahr.",emoji:"💊"},
  {q:"Wie viele Grad Celsius erhöht sich die Körpertemperatur beim Orgasmus?",a:0.3,unit:"°C",hint:"Eine leichte aber messbare Erwärmung.",emoji:"🌡️"},
  {q:"Wie viele Millionen Menschen weltweit haben Syphilis?",a:7,unit:"Millionen",hint:"Immer noch verbreitet – trotz Antibiotika.",emoji:"🔬"},
  {q:"Wie viele Minuten dauert ein Geschlechtsakt durchschnittlich von Beginn bis Ende?",a:30,unit:"Minuten",hint:"Inklusive Vorspiel ca. 30 Min., nur Penetration 5-6 Min.",emoji:"⏰"},
  {q:"Wie viele Milligramm Protein enthält Sperma pro Ejakulation?",a:300,unit:"Milligramm",hint:"Weniger als eine Tasse Milch.",emoji:"⚗️"},
  {q:"In welchem Jahr wurde das erste Sexspielzeug für Männer (Fleshlight) erfunden?",a:1995,unit:"Jahr",hint:"Patentiert von Steve Shubin.",emoji:"📅"},
  {q:"Wie viele cm ist der Abstand zwischen Klitoris und Vaginalöffnung durchschnittlich?",a:2.5,unit:"cm",hint:"Beeinflusst die Orgasmusfähigkeit.",emoji:"📏"},
  {q:"Wie viele Millionen Dollar verdient der meistbezahlte Pornodarsteller pro Jahr?",a:1,unit:"Millionen Dollar/Jahr",hint:"Frauen verdienen in der Branche oft mehr.",emoji:"💰"},
  {q:"Wie viele Minuten schneller schläft man nach dem Orgasmus ein?",a:10,unit:"Minuten",hint:"Oxytocin und Prolaktin nach dem Orgasmus fördern den Schlaf.",emoji:"😴"},
  {q:"Wie viele Millionen Menschen sind weltweit in der Sexarbeit tätig?",a:40,unit:"Millionen",hint:"Schätzung – schwer messbar durch Illegalität.",emoji:"🌍"},
  {q:"Wie viele cm lang ist die G-Punkt-Zone von der Vaginalöffnung?",a:5,unit:"cm",hint:"An der vorderen Vaginalwand.",emoji:"📏"},
  {q:"In welchem Jahr wurde Sexarbeit in Deutschland legalisiert?",a:2002,unit:"Jahr",hint:"Das Prostitutionsgesetz trat am 1. Januar 2002 in Kraft.",emoji:"📜"},
  {q:"Wie viele Millionen Besucher hat OnlyFans?",a:220,unit:"Millionen",hint:"Registrierte Nutzer – mit 2,5 Mio. Creators.",emoji:"📱"},
  {q:"Wie viele Gramm wiegt ein Durchschnitts-Hoden?",a:20,unit:"Gramm",hint:"Beide Hoden zusammen wiegen 40 Gramm.",emoji:"⚖️"},
  {q:"In welchem Jahr wurde der erste Erotik-Film gedreht?",a:1896,unit:"Jahr",hint:"Le Coucher de la Mariée – 7 Minuten lang.",emoji:"🎬"},
  {q:"Wie viele Mal pro Nacht hat ein gesunder Mann eine Erektion im Schlaf?",a:4,unit:"Mal",hint:"NPT – nächtliche penile Tumeszenz.",emoji:"😴"},
  {q:"Wie viele cm ist die durchschnittliche Brust in Deutschland (Körbchen)?",a:75,unit:"cm Unterbrustweite",hint:"Körbchen B/C ist am häufigsten in Deutschland.",emoji:"👙"},
  {q:"Wie viele Milliarden Dollar wert ist der globale Erotik-Literatur-Markt?",a:1.5,unit:"Milliarden Dollar",hint:"Fifty Shades of Grey allein brachte Milliarden.",emoji:"📚"},
  {q:"Wie lange dauert der Samenerguss durchschnittlich in Sekunden?",a:8,unit:"Sekunden",hint:"Die Muskelkontraktionen dauern 3-15 Sekunden.",emoji:"⏱️"},
  {q:"Wie viele Millionen Deutschen geben an, regelmäßig Pornos zu schauen?",a:25,unit:"Millionen",hint:"Jeder dritte Deutsche.",emoji:"📺"},
  {q:"Wie viele cm beträgt der durchschnittliche Brust-Umfang einer Frau in Deutschland?",a:97,unit:"cm",hint:"Brustumfang variiert stark.",emoji:"📏"},
  {q:"In welchem Jahr erschien Fifty Shades of Grey?",a:2011,unit:"Jahr",hint:"E.L. James' BDSM-Roman wurde zum Weltbestseller.",emoji:"📖"},
  {q:"Wie viele Millionen Exemplare verkaufte Fifty Shades of Grey?",a:150,unit:"Millionen",hint:"Eines der meistverkauften Bücher aller Zeiten.",emoji:"📚"},
  {q:"Wie viele cm ist die durchschnittliche weibliche Brustwarze lang?",a:1,unit:"cm",hint:"Im Ruhezustand etwa 1 cm.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen in Deutschland haben schon Analverkehr praktiziert?",a:20,unit:"Millionen",hint:"Etwa 35-40% der Bevölkerung.",emoji:"📊"},
  {q:"Wie viele Grad Celsius wird die Klitoris beim Orgasmus wärmer?",a:2,unit:"°C",hint:"Messbar durch Infrarotthermografie.",emoji:"🌡️"},
  {q:"Wie viele Stunden schaut ein Durchschnittsdeutscher Pornos pro Monat?",a:4,unit:"Stunden",hint:"Laut anonymen Nutzungsdaten.",emoji:"📺"},
  {q:"In welchem Jahr wurde Sex in der Raumstation ISS zum ersten Mal theoretisch diskutiert?",a:2006,unit:"Jahr",hint:"NASA-Studie über Sex im All.",emoji:"🚀"},
  {q:"Wie viele Millionen Menschen haben eine Sexsucht?",a:16,unit:"Millionen",hint:"3-6% der Bevölkerung – hauptsächlich Männer.",emoji:"🔬"},
  {q:"Wie viele cm lang ist die durchschnittliche erigierte Klitoris?",a:10,unit:"cm",hint:"Die innere Struktur – nicht nur die sichtbare Eichel.",emoji:"📏"},
  {q:"In welchem Jahr wurde das erste Bordell der Geschichte dokumentiert?",a:600,unit:"v.Chr.",hint:"Im antiken Griechenland unter Solon.",emoji:"🏛️"},
  {q:"Wie viele Millionen Dollar kostete die Produktion von Fifty Shades of Grey (Film)?",a:40,unit:"Millionen Dollar",hint:"Und spielte 569 Mio. Dollar ein.",emoji:"🎬"},
  {q:"Wie viele Gramm wiegt eine Prostata?",a:25,unit:"Gramm",hint:"Im Alter kann sie auf 100g wachsen.",emoji:"⚖️"},
  {q:"In welchem Jahr wurde das erste legal produzierte Porno-Video verkauft?",a:1972,unit:"Jahr",hint:"Deep Throat – der erste Mainstream-Pornofilm.",emoji:"🎬"},
  {q:"Wie viele cm ist der Menstrual-Cup durchschnittlich groß?",a:7,unit:"cm",hint:"Umweltfreundliche Alternative zu Tampons.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen schauen täglich Pornos auf mobilen Geräten?",a:90,unit:"Millionen",hint:"Über 70% des Traffics kommt von Smartphones.",emoji:"📱"},
  {q:"Wie viele Stunden Porno werden täglich auf Pornhub hochgeladen?",a:115,unit:"Stunden",hint:"Täglich neue Inhalte.",emoji:"📹"},
  {q:"In welchem Jahr wurde das erste Kondom aus Kunststoff (Polyurethan) eingeführt?",a:1994,unit:"Jahr",hint:"Alternative für Latex-Allergiker.",emoji:"💊"},
  {q:"Wie viele ml Vaginalflüssigkeit produziert eine Frau beim Sex?",a:4,unit:"ml",hint:"Natürliche Befeuchtungsreaktion.",emoji:"💧"},
  {q:"Wie viele Millionen Dollar verdiente Pornodarstellerin Lisa Ann auf ihrem Höhepunkt pro Jahr?",a:1.5,unit:"Millionen Dollar",hint:"Einem der bekanntesten Stars der Branche.",emoji:"💰"},
  {q:"Wie viele cm tief ist die Vagina bei sexueller Erregung durchschnittlich?",a:11,unit:"cm",hint:"In Ruhe 7–8cm, bei Erregung 11–12cm (Masters & Johnson 1966).",emoji:"📏"},
  {q:"In welchem Jahr wurde die erste Penisvergrößerungsoperation dokumentiert?",a:1971,unit:"Jahr",hint:"Chirurgische Eingriffe seit den 1970ern.",emoji:"🏥"},
  {q:"Wie viele Millionen Dollar wert ist der globale Markt für Erotik-Videospiele?",a:100,unit:"Millionen Dollar",hint:"Nische aber wachsend.",emoji:"🎮"},
  {q:"Wie viele Milligramm Fruchtzucker enthält Sperma?",a:2.5,unit:"mg",hint:"Frukose gibt Spermien Energie.",emoji:"⚗️"},
  {q:"In welchem Jahr wurde die erste Sexklinik in Deutschland eröffnet?",a:1918,unit:"Jahr",hint:"Magnus Hirschfeld eröffnete das Institut für Sexualwissenschaft.",emoji:"🏥"},
  {q:"Wie viele cm beträgt die maximale Vaginaltiefe bei starker Erregung?",a:15,unit:"cm",hint:"Beim Tenting-Effekt: Gebärmutter hebt sich, Vagina verlängert sich auf bis zu 15cm.",emoji:"📏"},
  {q:"Wie viele Millionen Pornhub-Suchanfragen kommen täglich aus Deutschland?",a:10,unit:"Millionen",hint:"Deutschland gehört zu den Top-Konsumenten.",emoji:"🔍"},
  {q:"Wie viele Sekunden dauert der längste bekannte Orgasmus in Sekunden?",a:43,unit:"Sekunden",hint:"Gemessen im Labor (Stand ~2024).",emoji:"⏱️"},
  {q:"In welchem Jahr wurde das erste Sexdolls-Unternehmen gegründet?",a:1997,unit:"Jahr",hint:"RealDoll aus San Diego war der Pionier.",emoji:"🤖"},
  {q:"Wie viele cm Länge hat ein durchschnittlicher Vibrator?",a:18,unit:"cm",hint:"Der Klassiker.",emoji:"📏"},
  {q:"Wie viele Millionen Dollar Umsatz macht die BDSM-Industrie weltweit?",a:500,unit:"Millionen Dollar",hint:"Bondage, Dominanz, Sadismus, Masochismus.",emoji:"🔗"},
  {q:"Wie viele Milligramm Zink enthält eine Ejakulation?",a:5,unit:"mg",hint:"Milligramm – essenziell für Spermienqualität.",emoji:"⚗️"},
  {q:"In welchem Jahr gründete Hugh Hefner das Playboy-Magazin?",a:1953,unit:"Jahr",hint:"Marilyn Monroe war auf dem ersten Cover.",emoji:"🐰"},
  {q:"Wie viele Millionen Pornhub-Suchanfragen gehen täglich ein?",a:100,unit:"Millionen",hint:"Millionen täglich – eine gigantische Zahl.",emoji:"🔍"},
  {q:"Wie viele cm lang ist ein durchschnittlicher Anal-Plug?",a:10,unit:"cm",hint:"Viele Variationen – von klein bis groß.",emoji:"📏"},
  {q:"Wie viele Stunden im Leben verbringt ein Mensch mit Masturbation (Männer)?",a:7000,hint:"Fast 300 Tage über ein Leben.",unit:"Stunden",emoji:"📊"},
  {q:"In welchem Jahr wurde der Begriff 'Bisexualität' erstmals wissenschaftlich verwendet?",a:1892,unit:"Jahr",hint:"Von Charles Gilbert Chaddock.",emoji:"🔬"},
  {q:"Wie viele Millionen Dollar wert ist der globale Markt für Gleitmittel?",a:800,unit:"Millionen Dollar",hint:"Gleitmittel sind ein riesiger Markt.",emoji:"💰"},
  {q:"Wie viele cm lang ist die durchschnittliche menschliche Zunge?",a:9,unit:"cm",hint:"Ca. 9cm – beim Küssen wird etwa die Hälfte eingesetzt.",emoji:"💋"},
  {q:"In welchem Jahr wurde das erste Nackt-Fotoshooting in einer Zeitschrift veröffentlicht?",a:1896,unit:"Jahr",hint:"In frühen Kunstzeitschriften.",emoji:"📸"},
  {q:"Wie viele Gramm wiegt die Gebärmutter?",a:70,unit:"Gramm",hint:"Im Nicht-Schwanger-Zustand.",emoji:"⚖️"},
  {q:"Wie viele Millionen Menschen haben Gonorrhoe weltweit?",a:82,unit:"Millionen",hint:"Eine der häufigsten STIs.",emoji:"🔬"},
  {q:"Wie viele cm lang ist die durchschnittliche Penisvorhaut?",a:5,unit:"cm",hint:"Variiert stark.",emoji:"📏"},
  {q:"In welchem Jahr wurde der erste Homosexuellen-Club in Deutschland eröffnet?",a:1897,unit:"Jahr",hint:"Hirschfelds Wissenschaftlich-humanitäres Komitee.",emoji:"🌈"},
  {q:"Wie viele Millionen Menschen schauen täglich Pornos auf Arbeit?",a:30,unit:"Millionen",hint:"Überraschend viele Nutzer weltweit.",emoji:"💼"},
  {q:"Wie viele Gramm wiegen beide Brüste einer C-Körbchen-Frau zusammen?",a:500,unit:"Gramm",hint:"Etwa 500g – je nach Größe.",emoji:"⚖️"},
  {q:"Wie viele Stunden dauert eine durchschnittliche Hochzeitsnacht?",a:3,unit:"Stunden",hint:"Mehr Schlafen als gedacht.",emoji:"🌙"},
  {q:"In welchem Jahr wurde der erste Swingerclub in Deutschland eröffnet?",a:1971,unit:"Jahr",hint:"In den liberalen 70ern.",emoji:"🕺"},
  {q:"Wie viele cm ist die durchschnittliche Länge eines Liebeskugel-Sets?",a:20,unit:"cm",hint:"Liebeskugeln für Beckenboden-Training.",emoji:"📏"},
  {q:"In welchem Jahr wurde der erste Striptease-Club in den USA eröffnet?",a:1969,unit:"Jahr",hint:"In San Francisco während der Sexual Revolution.",emoji:"💃"},
  {q:"Wie viele Gramm wiegt ein Strap-on-Dildo durchschnittlich?",a:300,unit:"Gramm",hint:"Je nach Material zwischen 200-500g.",emoji:"⚖️"},
  {q:"Wie viele cm ist die durchschnittliche Penisbreite erigiert?",a:12,unit:"cm Umfang",hint:"Der Umfang variiert stärker als die Länge.",emoji:"📏"},
  {q:"Wie viele Milliarden Euro generiert die deutsche Sexarbeit pro Jahr?",a:15,unit:"Milliarden Euro",hint:"15 Milliarden Euro jährlich in Deutschland.",emoji:"💶"},
  {q:"In welchem Jahr wurde das erste weibliche Kondom zugelassen?",a:1993,unit:"Jahr",hint:"FDA-Zulassung 1993.",emoji:"💊"},
  {q:"Wie viele cm ist die durchschnittliche Klitoris-Vorhaut lang?",a:0.5,unit:"cm",hint:"Das Präputium Clitoridis.",emoji:"📏"},
  {q:"Wie viele Millionen Escorts sind weltweit tätig?",a:1,unit:"Million",hint:"Schätzungen – exakte Zahlen nicht messbar.",emoji:"💼"},
  {q:"Wie viele Stunden dauerte der längste belegte Geschlechtsakt (Rekord)?",a:134,unit:"Stunden",hint:"134 Stunden – Guinness-Rekord eines amerikanischen Paares 2004.",emoji:"⏰"},
  {q:"In welchem Jahr wurde das Phänomen 'Female Ejaculation' wissenschaftlich anerkannt?",a:1982,unit:"Jahr",hint:"Erstmals 1982 wissenschaftlich beschrieben.",emoji:"🔬"},
  {q:"Wie viele cm gilt als Grenzwert für die Mikropenis-Diagnose?",a:7,unit:"cm",hint:"Unter 7cm erigiert gilt medizinisch als Mikropenis (ca. 0,6% der Männer).",emoji:"📏"},
  {q:"Wie viele Millionen Menschen haben Chlamydien weltweit?",a:127,unit:"Millionen",hint:"Die häufigste bakterielle STI.",emoji:"🔬"},
  {q:"In welchem Jahr gründete Alfred Kinsey sein Sexualforschungsinstitut?",a:1947,unit:"Jahr",hint:"Das Kinsey Institute in Indiana.",emoji:"🔬"},
  {q:"Wie viele cm lang soll laut Selbstauskunft der längste Penis der Welt sein?",a:34,unit:"cm",hint:"Jonah Falcon behauptet 34cm – medizinisch nicht offiziell verifiziert.",emoji:"📏"},
  {q:"Wie viele Milliarden Dollar wert ist der globale Markt für Potenzpillen?",a:6,unit:"Milliarden Dollar",hint:"Viagra, Cialis und Generika.",emoji:"💊"},
  {q:"Wie viele Minuten dauert Vorspiel durchschnittlich laut Studien?",a:18,unit:"Minuten",hint:"Zu wenig laut den meisten Frauen.",emoji:"⏱️"},
  {q:"In welchem Jahr wurde das erste Sex-Museum in Amsterdam eröffnet?",a:1985,unit:"Jahr",hint:"Das Sexmuseum Amsterdam.",emoji:"🏛️"},
  {q:"Wie viele cm lang ist die durchschnittliche Analöffnung beim Entspanntsein?",a:3,unit:"cm",hint:"Kann durch Training und Entspannung größer werden.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen sind in der Welt als Transfrau oder Transmann identifiziert?",a:25,unit:"Millionen",hint:"Schätzungen variieren – weltweit ~0,3% der Bevölkerung.",emoji:"🏳️‍⚧️"},
  {q:"Wie viele Milligramm wiegt eine typische Antibabypille?",a:150,unit:"Milligramm",hint:"Die Tablette selbst wiegt ca. 100-200mg – der Wirkstoff nur 0,03mg.",emoji:"⚖️"},
  {q:"In welchem Jahr wurde das erste FKK-Gelände in Deutschland eröffnet?",a:1920,unit:"Jahr",hint:"Die Freikörperkultur begann in den 20ern.",emoji:"🌞"},
  {q:"Wie viele ml fasst ein Analplug durchschnittlich?",a:100,unit:"ml",hint:"Variiert je nach Größe.",emoji:"💧"},
  {q:"Wie viele Millionen Euro Umsatz macht der deutsche Sexspielzeug-Markt?",a:400,unit:"Millionen Euro",hint:"Wächst jährlich um 10%.",emoji:"💶"},
  {q:"In welchem Jahr wurde der Kegel-Beckenboden-Trainer erfunden?",a:1948,unit:"Jahr",hint:"Dr. Arnold Kegel entwickelte die Übungen.",emoji:"💪"},
  {q:"Wie viele cm ist die durchschnittliche Länge eines Butt-Plugs?",a:10,unit:"cm",hint:"Je nach Größe und Erfahrung.",emoji:"📏"},
  {q:"Wie viele Millionen Kondome werden in Deutschland pro Jahr verkauft?",a:200,unit:"Millionen",hint:"Sinkende Tendenz durch Pille und IUDs.",emoji:"💊"},
  {q:"In welchem Jahr erschien das Kamasutra in Europa erstmals?",a:1883,unit:"Jahr",hint:"Richard Burton übersetzte es ins Englische.",emoji:"📖"},
  {q:"Wie viele Positionen beschreibt das Kamasutra?",a:64,unit:"Positionen",hint:"Viele davon sind für den Alltag kaum praktisch.",emoji:"📖"},
  {q:"Wie viele cm beträgt die maximale bekannte Vaginaltiefe?",a:15,unit:"cm",hint:"Gut dokumentiert sind bis zu 15cm bei starker Erregung – Extremwerte sind selten belegt.",emoji:"📏"},
  {q:"Wie viele Milliarden Dollar wert ist der globale Markt für Aphrodisiaka?",a:2,unit:"Milliarden Dollar",hint:"Rhino-Produkte, Oyster-Extrakte und mehr.",emoji:"💊"},
  {q:"Wie viele Stunden braucht der Körper um sich nach dem Sex zu erholen?",a:2,unit:"Stunden",hint:"Bis Herzschlag und Hormone normalisiert sind.",emoji:"💓"},
  {q:"In welchem Jahr wurde die erste Sextherapie-Praxis in Deutschland eröffnet?",a:1975,unit:"Jahr",hint:"Nach Masters & Johnson's Forschungen.",emoji:"🏥"},
  {q:"Wie viele mm hoch ist ein durchschnittlicher Brustnippel in Ruhe?",a:5,unit:"mm",hint:"Ca. 5mm Höhe, 15mm Durchmesser – variiert stark.",emoji:"📏"},
  {q:"Wie viele Tausend Dollar hat die Pornodarstellerin Mia Khalifa insgesamt verdient?",a:12,unit:"Tausend Dollar",hint:"Nur 12.000 Dollar in ihrer kurzen Karriere – trotz enormer Bekanntheit.",emoji:"💰"},
  {q:"Wie viele Gramm Glukose werden beim Sex verbrannt?",a:8,unit:"Gramm",hint:"Entspricht einem kleinen Stück Schokolade.",emoji:"🍫"},
  {q:"In welchem Jahr wurde das erste Porno-Magazin (Playboy) gegründet?",a:1953,unit:"Jahr",hint:"Hugh Hefner startete eine Revolution.",emoji:"🐰"},
  {q:"Wie viele Millionen Menschen identifizieren sich weltweit als homosexuell?",a:390,unit:"Millionen",hint:"Ca. 5% der Weltbevölkerung.",emoji:"🌈"},
  {q:"Wie viele Minuten Vorspiel brauchen Frauen durchschnittlich für einen Orgasmus?",a:20,unit:"Minuten",hint:"Studien zeigen ca. 20 Minuten Stimulation – mehr als die meisten Männer annehmen.",emoji:"⏱️"},
  {q:"In welchem Jahr wurde der Analverkehr in Deutschland legalisiert?",a:1969,unit:"Jahr",hint:"Paragraf 175 wurde reformiert.",emoji:"📜"},
  {q:"Wie viele cm ist ein durchschnittlicher Liebeskugelstrang lang?",a:25,unit:"cm",hint:"Verbundene Kugeln für Beckenboden.",emoji:"📏"},
  {q:"Wie viele Millionen Euro wert ist der deutsche Erotik-Film-Markt?",a:200,unit:"Millionen Euro",hint:"Produktionen aus Deutschland.",emoji:"🎬"},
  {q:"In welchem Jahr erschien das erste weiblich geschriebene Erotik-Buch (Lady Chatterley)?",a:1928,unit:"Jahr",hint:"D.H. Lawrence schrieb es – war jahrzehntelang verboten.",emoji:"📚"},
  {q:"Wie viele cm ist die Basis eines durchschnittlichen Vibrators?",a:4,unit:"cm",hint:"Breiter unten für sicheres Halten.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen in Deutschland haben sexuelle Dysfunktionen?",a:10,unit:"Millionen",hint:"Breites Spektrum – viele suchen keine Hilfe.",emoji:"🔬"},
  {q:"Wie viele cm ist der Abstand zwischen Anus und Vaginalöffnung (Perineum)?",a:3,unit:"cm",hint:"Das Perineum variiert individuell.",emoji:"📏"},
  {q:"Wie viele Millionen Dollar verdiente Hustler Magazine pro Jahr auf seinem Höhepunkt?",a:50,unit:"Millionen Dollar/Jahr",hint:"Larry Flynts Sexmagazin in den 80ern.",emoji:"💰"},
  {q:"Wie viele Stunden im Monat schauen Singles mehr Pornos als Paare?",a:4,unit:"Stunden",hint:"Singles konsumieren deutlich mehr.",emoji:"📊"},
  {q:"Wie viele cm ist die durchschnittliche Brust in Österreich (Körbchengröße)?",a:80,unit:"cm Unterbrustweite",hint:"Ähnlich wie in Deutschland.",emoji:"👙"},
  {q:"Wie viele Millionen Nutzer hat Grindr weltweit?",a:13,unit:"Millionen",hint:"Die bekannteste Gay-Dating-App.",emoji:"📱"},
  {q:"Wie viele cm lang ist der durchschnittliche Klitoris-Stiel?",a:3,unit:"cm",hint:"Der innere Teil des Klitoriskörpers.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen nutzen Swingerclub-Apps weltweit?",a:2,unit:"Millionen",hint:"Spezialisierte Apps für Lifestyler.",emoji:"📱"},
  {q:"Wie viele Gramm wiegt ein Durchschnitts-Ovarium (Eierstock)?",a:14,unit:"Gramm",hint:"Beide zusammen etwa 28 Gramm.",emoji:"⚖️"},
  {q:"Wie viele ml Flüssigkeit wird beim Squirting durchschnittlich ausgestoßen?",a:50,unit:"ml",hint:"Spanne: 0,3ml bis über 150ml – hauptsächlich Urin aus der Blase (Salama et al. 2015).",emoji:"💧"},
  {q:"Wie viele Stunden im Monat verbringen Singles mit Dating-Apps?",a:10,unit:"Stunden",hint:"Viel Zeit fürs digitale Dating.",emoji:"📱"},
  {q:"Wie viele cm ist das durchschnittliche Hymen von der Vaginalöffnung entfernt?",a:2,unit:"cm",hint:"Das Hymen ist ein dünnes Schleimhautgewebe.",emoji:"📏"},
  {q:"Wie viele Tausend Menschen haben eine Sexallergie (Seminalplasma)?",a:40,unit:"Tausend",hint:"Ca. 40.000 Menschen – seltene Allergie gegen Sperma-Proteine.",emoji:"🔬"},
  {q:"Wie viele Grad Celsius wärmer ist der Vaginalkanal während des Orgasmus?",a:0.5,unit:"°C",hint:"Messbar durch präzise Thermometer.",emoji:"🌡️"},
  {q:"Wie viele Millionen Menschen haben vaginismus (Scheidenverkrampfen)?",a:15,unit:"Millionen",hint:"Eine häufige aber wenig diskutierte Erkrankung.",emoji:"🔬"},
  {q:"Wie viele Gramm wiegt das Clitoris-Schwellkörpernetz?",a:20,unit:"Gramm",hint:"Das gesamte Klitorissystem.",emoji:"⚖️"},
  {q:"Wie viele Minuten braucht der Mann durchschnittlich nach dem Orgasmus bis zur nächsten Erektion?",a:30,unit:"Minuten",hint:"Etwa 30 Min. bei jungen Männern – im Alter bis zu Stunden oder Tagen.",emoji:"⏰"},
  {q:"Wie viele Millionen Menschen praktizieren Bondage weltweit?",a:100,unit:"Millionen",hint:"Laut Studien haben 15-20% der Menschen BDSM-Erfahrungen gemacht.",emoji:"🔗"},
  {q:"Wie viele cm ist die Länge eines erigierten Klitoriskörpers?",a:10,unit:"cm",hint:"Viel größer als sichtbar.",emoji:"📏"},
  {q:"Wie viele Pikogramm Oxytocin pro ml werden beim Orgasmus ausgeschüttet?",a:100,unit:"pg/ml",hint:"Ca. 100 Pikogramm/ml – winzige Menge mit großer Wirkung.",emoji:"⚗️"},
  {q:"Wie viele Stunden Schlaf pro Nacht sind für gute Sexualfunktion empfohlen?",a:8,unit:"Stunden",hint:"Unter 5h Schlaf reduziert Testosteron – 8h ist der Richtwert.",emoji:"😴"},
  {q:"Wie viele Millionen Menschen nutzen Fetlife weltweit?",a:10,unit:"Millionen",hint:"Das größte BDSM-soziale Netzwerk.",emoji:"🔗"},
  {q:"Wie viele Gramm Elastin hat das Vaginalgewebe?",a:1,unit:"Gramm",hint:"Elastin ermöglicht die Dehnung bei der Geburt.",emoji:"⚗️"},
  {q:"Wie viele ml Schmierung produziert die Bartholin-Drüse beim Sex?",a:2,unit:"ml",hint:"Natürliche Gleitfähigkeit.",emoji:"💧"},
  {q:"Wie viele Spermien erreichen von 250 Millionen die Eizelle maximal?",a:200,unit:"Spermien",hint:"Von 250 Mio. schaffen es nur ~200 bis zur Eizelle – eines befruchtet sie.",emoji:"🔬"},
  {q:"Wie viele Stunden im Jahr verbringt ein Mensch mit romantischen Aktivitäten?",a:730,unit:"Stunden",hint:"2 Stunden täglich an Romantik und Intimität.",emoji:"❤️"},
  {q:"Wie viele cm ist die Vorhaut im erigierten Zustand lang?",a:12,unit:"cm",hint:"Die Vorhaut kann bis zur Hälfte des Penis bedecken.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen haben Erektionsprobleme weltweit?",a:320,unit:"Millionen",hint:"Fast ein Drittel aller Männer irgendwann.",emoji:"🔬"},
  {q:"Wie viele Mikrometer ist ein durchschnittliches Spermium lang?",a:50,unit:"Mikrometer",hint:"0,05mm – das entspricht etwa 1/20 eines menschlichen Haares.",emoji:"🔬"},
  {q:"Wie viele Stunden länger schläft man nach einem Orgasmus laut Studien?",a:1,unit:"Stunde mehr",hint:"Orgasmus fördert Schlaf durch Oxytocin.",emoji:"😴"},
  {q:"Wie viele ml Vaginalflüssigkeit produziert eine Frau täglich?",a:2,unit:"ml",hint:"Normal ist 1-4 ml täglich.",emoji:"💧"},
  {q:"Wie viele cm ist der maximale Umfang eines erigierten Penis im Rekord?",a:25,unit:"cm",hint:"Extremfälle sind dokumentiert (Stand ~2024).",emoji:"📏"},
  {q:"Wie viele Millionen Menschen leiden weltweit an sexuellen Angststörungen?",a:30,unit:"Millionen",hint:"Sexangst – nicht selten.",emoji:"🔬"},
  {q:"Wie viele Minuten pro Woche masturbieren Frauen durchschnittlich laut Studien?",a:30,unit:"Minuten/Woche",hint:"Studien zeigen ca. 30 Min./Woche bei Frauen – Männer etwa doppelt so viel.",emoji:"📊"},
  {q:"Wie viele Mikrogramm Östradiol enthält eine normale Verhütungspille täglich?",a:30,unit:"Mikrogramm",hint:"30µg – sehr niedrige Dosis, frühere Pillen hatten 50–150µg.",emoji:"💊"},
  {q:"Wie viele Millionen Menschen sind Teil der Polyamorie-Bewegung?",a:21,unit:"Millionen",hint:"Schätzung in den USA allein.",emoji:"💕"}
  {q:"Wie viele Mal pro Woche hat ein durchschnittliches Paar Sex?",a:2,unit:"Mal",hint:"Ca. 2 Mal pro Woche – sinkt mit zunehmendem Alter.",emoji:"❤️"},
  {q:"Wie viele Kalorien verbrennt man beim Sex (30 Minuten)?",a:144,unit:"kcal",hint:"Ca. 144 kcal – wie ein 25-minütiger Spaziergang.",emoji:"🔥"},
  {q:"Wie viele Prozent der Erwachsenen haben schon einmal einen One-Night-Stand?",a:55,unit:"%",hint:"Ca. 55% – mehr Männer als Frauen laut Studien.",emoji:"🌙"},
  {q:"Wie viele Minuten dauert der Geschlechtsakt weltweit durchschnittlich?",a:5.4,unit:"Minuten",hint:"Laut Studie: 5,4 Minuten im Median – Türkei führt mit 3,7.",emoji:"⏱️"},
  {q:"Wie viele Prozent der Frauen erreichen beim Sex regelmäßig einen Orgasmus?",a:25,unit:"%",hint:"Nur ~25% durch Penetration allein – der Rest braucht andere Stimulation.",emoji:"💫"},
  {q:"Wie viele Milligramm Testosteron produziert ein Mann täglich?",a:7,unit:"Milligramm",hint:"Ca. 7mg täglich – bei Frauen 10× weniger.",emoji:"💪"},
  {q:"Wie viele cm ist die durchschnittliche erigierte Penislänge weltweit?",a:13.1,unit:"cm",hint:"Meta-Analyse 2015 mit 15.000+ Männern – Median 13,1 cm.",emoji:"📏"},
  {q:"Wie viele Prozent aller Internetseiten sind pornografisch?",a:12,unit:"%",hint:"Ca. 12% aller Webseiten – generieren 25% des Traffics.",emoji:"🖥️"},
  {q:"Wie viele Millionen Menschen haben eine sexuell übertragbare Krankheit weltweit?",a:1000,unit:"Millionen",hint:"Ca. 1 Milliarde – WHO-Schätzung für alle STIs zusammen.",emoji:"🩺"},
  {q:"Wie viele Stunden pro Woche masturbieren Männer laut Studien?",a:1,unit:"Stunde",hint:"Ca. 1 Stunde pro Woche – bei Frauen etwa die Hälfte.",emoji:"🔬"},
  {q:"Wie viele Millionen Menschen identifizieren sich als LGBTQ+?",a:500,unit:"Millionen",hint:"Ca. 5% der Weltbevölkerung = ~500 Millionen Menschen.",emoji:"🏳️‍🌈"},
  {q:"Wie viele Prozent der Deutschen haben schon Sex im Auto gehabt?",a:33,unit:"%",hint:"Ca. 33% – Autos sind der dritthäufigste Ort nach Zuhause.",emoji:"🚗"},
  {q:"Wie viele Sekunden dauert der männliche Orgasmus im Schnitt?",a:17,unit:"Sekunden",hint:"3-25 Sekunden – im Median etwa 17 Sekunden.",emoji:"⏱️"},
  {q:"Wie viele Prozent aller Schwangerschaften sind ungeplant?",a:40,unit:"%",hint:"Ca. 40% weltweit – in manchen Ländern über 60%.",emoji:"🤰"},
  {q:"Wie viele Millionen Paare in Deutschland nutzen die Pille?",a:9,unit:"Millionen",hint:"Ca. 9 Millionen Frauen in Deutschland nehmen die Pille.",emoji:"💊"},
  {q:"Wie viele Prozent der Deutschen sind mit ihrem Sexleben zufrieden?",a:65,unit:"%",hint:"Ca. 65% – Singles sind unzufriedener als Paare.",emoji:"💑"},
  {q:"Wie viele Gramm wiegen beide Hoden zusammen?",a:40,unit:"Gramm",hint:"Ca. 40g zusammen – so schwer wie ein kleines Ei.",emoji:"🔬"},
  {q:"Wie viele Monate dauert die weibliche Menopause im Schnitt?",a:48,unit:"Monate",hint:"4-5 Jahre Übergangsphase – manchmal früher oder länger.",emoji:"🌸"},
  {q:"Wie viele Prozent der Menschen haben schon einmal Sex am Arbeitsplatz gehabt?",a:15,unit:"%",hint:"Ca. 15% laut Studien – meistens nach Arbeitsschluss.",emoji:"💼"},
  {q:"Wie viele Minuten braucht ein Mann im Durchschnitt zum Orgasmus?",a:5,unit:"Minuten",hint:"Ca. 5-6 Minuten – Frauen brauchen ca. 20 Minuten.",emoji:"⏱️"},
  {q:"Wie viele Prozent der Deutschen haben Sex mindestens einmal pro Woche?",a:45,unit:"%",hint:"Ca. 45% – mehr jüngere als ältere Paare.",emoji:"❤️"},
  {q:"Wie viele Nervenenden hat die Klitoris?",a:8000,unit:"Nervenendigungen",hint:"Ca. 8.000 Nervenendigungen – doppelt so viele wie der Penis.",emoji:"🔬"},
  {q:"Wie viele ml Ejakulat enthält eine normale Ejakulation?",a:3.5,unit:"ml",hint:"2-5ml – WHO-Mindestwert für Fruchtbarkeit: 1,5ml.",emoji:"🔬"},
  {q:"Wie viele Prozent der Männer hatten schon einen Erektionsproblem?",a:50,unit:"%",hint:"Über 50% aller Männer ab 40 – häufigste Ursache: psychisch.",emoji:"🩺"},
  {q:"Wie viele Sekunden braucht ein Mann nach dem Orgasmus bis zur nächsten Erektion (jung)?",a:1800,unit:"Sekunden",hint:"Ca. 30 Minuten (1.800s) – im Alter können es Stunden sein.",emoji:"⏰"},
  {q:"Wie viele Prozent aller Paare geben Sexprobleme als Trennungsgrund an?",a:20,unit:"%",hint:"Ca. 20% – nach Kommunikation und Vertrauen häufigster Grund.",emoji:"💔"},
  {q:"Wie viele Millionen Kondome werden weltweit täglich verwendet?",a:6,unit:"Millionen",hint:"Ca. 6 Millionen täglich – 2 Milliarden pro Jahr.",emoji:"🎈"},
  {q:"Wie viele Prozent der Deutschen haben Sex in der Öffentlichkeit gehabt?",a:25,unit:"%",hint:"Ca. 25% – Parks und öffentliche Orte sind beliebt.",emoji:"🌿"},
  {q:"Wie viele Hormone werden beim Orgasmus ausgeschüttet?",a:5,unit:"Hormone",hint:"Oxytocin, Dopamin, Serotonin, Endorphine, Prolaktin.",emoji:"🧪"},
  {q:"Wie viele Mal pro Sekunde wird Pornhub aufgerufen?",a:250,unit:"Mal",hint:"Ca. 250 Zugriffe pro Sekunde – 81.000 Videos täglich abgerufen.",emoji:"🖥️"},
  {q:"Wie viele Millionen Dollar wert ist die globale Sexspielzeug-Industrie?",a:33000,unit:"Millionen Dollar",hint:"33 Milliarden Dollar jährlich – wächst stark.",emoji:"💰"},
  {q:"Wie viele Prozent der Frauen täuschen den Orgasmus vor?",a:50,unit:"%",hint:"Ca. 50-80% geben an, den Orgasmus schon mal vorgetäuscht zu haben.",emoji:"🎭"},
  {q:"Wie viele Meter lang kann eine Erektion im Schnitt sein (Vorhaut)?",a:0,unit:"Meter",hint:"Keine Länge – die Vorhaut ist ein ringförmiges Gewebe.",emoji:"🔬"},
  {q:"Wie viele Prozent der Deutschen verlieren ihre Jungfräulichkeit unter 16?",a:15,unit:"%",hint:"Ca. 15% – Durchschnittsalter beim ersten Mal: 17,2 Jahre.",emoji:"💑"},
  {q:"Wie viele Stunden pro Monat sehen Männer Pornos an?",a:6,unit:"Stunden",hint:"Ca. 6 Stunden monatlich laut Pornhub-Statistiken.",emoji:"🖥️"},
  {q:"Wie viele Prozent aller Frauen haben eine Bimax-Empfindlichkeit?",a:70,unit:"%",hint:"Ca. 70% der Frauen empfinden Brustwarzen als erogene Zone.",emoji:"🔬"},
  {q:"Wie viele cm ist die Vagina in Ruhe tief?",a:7.5,unit:"cm",hint:"Ca. 7-8cm in Ruhe – bei Erregung bis 11cm.",emoji:"📏"},
  {q:"Wie viele Stunden Schlaf verbessern die sexuelle Funktion?",a:8,unit:"Stunden",hint:"8h Schlaf steigert Testosteron – unter 5h sinkt es stark.",emoji:"😴"},
  {q:"Wie viele Prozent der Deutschen haben Erfahrung mit BDSM?",a:25,unit:"%",hint:"Ca. 25% haben BDSM-Erfahrungen – leichte Formen sehr verbreitet.",emoji:"⛓️"},
  {q:"Wie viele Millionen Menschen weltweit sind Sex-Süchtig?",a:40,unit:"Millionen",hint:"Ca. 40 Millionen – 6% aller Männer, 1,5% aller Frauen.",emoji:"🩺"},
  {q:"Wie viele Prozent der Paare haben Sex mindestens einmal pro Monat?",a:80,unit:"%",hint:"Ca. 80% aller Paare haben mindestens 1× pro Monat Sex.",emoji:"💑"},
  {q:"Wie viele Minuten dauert Vorspiel bei Deutschen durchschnittlich?",a:15,unit:"Minuten",hint:"Ca. 15 Minuten – empfohlen werden für Frauen 20+.",emoji:"💑"},
  {q:"Wie viele Prozent aller Menschen haben eine sexuelle Fetisch?",a:50,unit:"%",hint:"Ca. 50% haben eine sexuelle Vorliebe die als Fetisch gilt.",emoji:"🔍"},
  {q:"Wie viele Millionen Pornhub-Besuche gibt es täglich?",a:130,unit:"Millionen",hint:"Ca. 130 Millionen Besuche täglich – 47 Milliarden jährlich.",emoji:"🖥️"},
  {q:"Wie viele Monate dauert eine Schwangerschaft?",a:9,unit:"Monate",hint:"9 Monate – genauer 40 Wochen = 280 Tage.",emoji:"🤰"},
  {q:"Wie viele Prozent der Paare haben eine offene Beziehung?",a:5,unit:"%",hint:"Ca. 4-5% – in jüngeren Generationen häufiger.",emoji:"💑"},
  {q:"Wie viele Nanogramm Oxytocin werden beim Orgasmus ausgeschüttet?",a:100,unit:"pg/ml",hint:"Ca. 100 Pikogramm/ml – winzige Menge mit großer Wirkung.",emoji:"💉"},
  {q:"Wie viele Sekunden dauert ein durchschnittlicher Kuss?",a:12,unit:"Sekunden",hint:"Ca. 12 Sekunden – der längste Kuss dauerte 58 Stunden.",emoji:"💋"},
  {q:"Wie viele Millionen Menschen haben weltweit HIV?",a:39,unit:"Millionen",hint:"Ca. 39 Millionen Menschen leben mit HIV (Stand 2023).",emoji:"🩺"},
  {q:"Wie viele Prozent der Deutschen reden über Sex mit ihrem Partner?",a:55,unit:"%",hint:"Ca. 55% kommunizieren aktiv über ihre Wünsche.",emoji:"💬"},
  {q:"Wie viele Mal im Leben küsst ein Mensch durchschnittlich?",a:100000,unit:"Mal",hint:"Ca. 100.000 Küsse – 15 Minuten täglich × 70 Jahre.",emoji:"💋"},
  {q:"Wie viele Milliliter Vaginalsekret produziert eine Frau täglich?",a:5,unit:"Milliliter",hint:"Ca. 5ml täglich – erhöht sich bei Erregung stark.",emoji:"🔬"},
  {q:"Wie viele Prozent der Deutschen sind monogam eingestellt?",a:85,unit:"%",hint:"Ca. 85% – aber 30-40% haben trotzdem schon betrogen.",emoji:"💑"},
  {q:"Wie viele Millionen Menschen haben Gonorrhoe weltweit?",a:82,unit:"Millionen",hint:"Ca. 82 Millionen neue Fälle pro Jahr – WHO-Schätzung.",emoji:"🩺"},
  {q:"Wie viele Monate dauert die Wechseljahre bei Männern (Andropause)?",a:120,unit:"Monate",hint:"Ca. 10 Jahre schleichend – Testosteron sinkt ab 40.",emoji:"🔬"},
  {q:"Wie viele Prozent der Frauen haben mehr als 10 Sexualpartner?",a:20,unit:"%",hint:"Ca. 20% der Frauen und 35% der Männer.",emoji:"💑"},
  {q:"Wie viele Sekunden live streamen täglich auf Pornhub?",a:169,unit:"Jahre",hint:"Laut Pornhub: hochgeladenes Videomaterial entspricht ~169 Jahren.",emoji:"🖥️"},
  {q:"Wie viele Prozent der Deutschen haben eine Sexualstörung?",a:30,unit:"%",hint:"Ca. 30% – häufigste Störung: mangelndes Verlangen.",emoji:"🩺"},
  {q:"Wie viele mg Testosteron hat eine 25-jährige Frau?",a:0.3,unit:"mg/dl",hint:"Ca. 0,3mg/dl – ein Zehntel des männlichen Werts.",emoji:"🔬"},
  {q:"Wie viele Tage ist eine Frau pro Monat fruchtbar?",a:6,unit:"Tage",hint:"Ca. 6 Tage – 5 Tage vor und am Tag des Eisprungs.",emoji:"📅"},
  {q:"Wie viele Millionen Spermatozoen überleben von 250 Millionen bis zur Eizelle?",a:200,unit:"Spermien",hint:"Von 250 Mio. schaffen es nur ~200 bis zur Eizelle – eines befruchtet sie.",emoji:"🔬"},
  {q:"Wie viele Minuten Stimulation brauchen Frauen durchschnittlich für einen Orgasmus?",a:20,unit:"Minuten",hint:"Studien zeigen ca. 20 Minuten – mehr als die meisten Männer annehmen.",emoji:"⏱️"},
  {q:"Wie viele Tage überlebt ein Spermium in der Gebärmutter?",a:5,unit:"Tage",hint:"Bis zu 5 Tage – deshalb kann man schon vor dem Eisprung schwanger werden.",emoji:"🔬"},
  {q:"Wie viele Prozent aller Deutschen hatten schon Sex im Freien?",a:40,unit:"%",hint:"Ca. 40% – im Sommer steigen die Zahlen.",emoji:"🌲"},
  {q:"Wie viele Euro Umsatz macht die Sex-Industrie in Deutschland jährlich?",a:15000,unit:"Millionen Euro",hint:"Ca. 15 Milliarden Euro – einer der größten Märkte Europas.",emoji:"💰"},
  {q:"Wie viele Prozent der Männer haben Penisangst?",a:68,unit:"%",hint:"Ca. 68% aller Männer sind unzufrieden mit ihrer Penisgröße.",emoji:"🔬"},
  {q:"Wie viele Millimeter vergrößern sich die Pupillen bei sexueller Erregung?",a:3,unit:"Millimeter",hint:"Bis zu 3mm Erweiterung – deshalb wirken verliebte Menschen attraktiver.",emoji:"👁️"},
  {q:"Wie viele Prozent der Deutschen gucken Pornos?",a:50,unit:"%",hint:"Ca. 50% der Deutschen – 70% der Männer, 30% der Frauen.",emoji:"🖥️"},
  {q:"Wie viele Monate after Sex entwickelt sich HIV zu AIDS unbehandelt?",a:120,unit:"Monate",hint:"Unbehandelt ca. 10 Jahre bis zum AIDS-Stadium.",emoji:"🩺"},
  {q:"Wie viele Kalorien hat eine Portion Sperma?",a:5,unit:"kcal",hint:"Ca. 5 kcal pro 5ml – Wasser, Proteine, Fruktose.",emoji:"🔬"},
  {q:"Wie viele Prozent aller Geburten weltweit sind Kaiserschnitte?",a:21,unit:"%",hint:"Ca. 21% – in manchen Ländern über 50%.",emoji:"🏥"},
  {q:"Wie viele Stunden nach Sex kann man mit der Pille danach verhüten?",a:72,unit:"Stunden",hint:"Bis 72 Stunden – Ella wirkt bis 120 Stunden.",emoji:"💊"},
  {q:"Wie viele Millionen Dating-App-Nutzer gibt es weltweit?",a:366,unit:"Millionen",hint:"Ca. 366 Millionen Dating-App-Nutzer (Stand 2022).",emoji:"📱"},
  {q:"Wie viele Prozent der Paare haben Sex mindestens einmal pro Woche?",a:45,unit:"%",hint:"Ca. 45% der Paare – je jünger desto häufiger.",emoji:"💑"},
  {q:"Wie viele Millionen Dollar verdient der meistbezahlte Pornodarsteller pro Jahr?",a:1,unit:"Millionen Dollar",hint:"Die Topverdiener kommen auf ca. 1 Million Dollar jährlich.",emoji:"💰"},
  {q:"Wie viele Prozent der sexuellen Übergriffe werden angezeigt?",a:15,unit:"%",hint:"Nur ca. 10-20% der Übergriffe werden bei der Polizei angezeigt.",emoji:"⚖️"},
  {q:"Wie viele Millionen Paare in Deutschland leben in einer Fernbeziehung?",a:1,unit:"Million",hint:"Ca. 1 Million Paare in Deutschland in einer Fernbeziehung.",emoji:"💑"},
];
