// 💰 GELD & ABSURDE PREISE – Erwachsene – 250 Fragen
export default [
  {id:"geld_001",q:"Wie viel kostete das teuerste je verkaufte Gemälde (Salvator Mundi) in Millionen Dollar?",a:450,unit:"Millionen Dollar",hint:"2017 bei Christie's versteigert.",emoji:"🖼️"},
  {id:"geld_002",q:"Wie viele Milliarden Dollar ist Jeff Bezos reich?",a:170,unit:"Milliarden Dollar",hint:"Schwankt – Stand 2024 ca. 170 Mrd.",emoji:"💰"},
  {id:"geld_003",q:"Wie viel kostet eine Flasche Krug Grande Cuvée Champagner?",a:200,unit:"Euro",hint:"Hochwertigster Champagner im Standard-Sortiment.",emoji:"🥂"},
  {id:"geld_004",q:"Wie viel kostete das teuerste Haus der Welt (Villa Les Cèdres) in Millionen Euro?",a:350,unit:"Millionen Euro",hint:"Villa in Cap-Ferrat, Südfrankreich (Stand ~2024).",emoji:"🏰"},
  {id:"geld_005",q:"Wie viele Milliarden Dollar kostet ein modernes Flugzeugträger?",a:13,unit:"Milliarden Dollar",hint:"Der Ford-Class Träger der US Navy.",emoji:"🚢"},
  {id:"geld_006",q:"Wie viele Billionen Dollar würde 1 Gramm Antimaterie kosten?",a:62.5,unit:"Billionen Dollar",hint:"62,5 Billionen Dollar pro Gramm.",emoji:"⚛️"},
  {id:"geld_007",q:"Wie viel kostete das teuerste Parfüm (Clive Christian No. 1) pro Flasche?",a:2150,unit:"Dollar",hint:"In einem goldenen Flacon (Stand ~2024).",emoji:"🌸"},
  {id:"geld_008",q:"Wie viele Milliarden Dollar Umsatz macht Apple pro Quartal?",a:90,unit:"Milliarden Dollar",hint:"Apple ist das wertvollste Unternehmen der Welt.",emoji:"🍎"},
  {id:"geld_009",q:"Wie viel kostet ein Mondstein-Gramm der NASA in Dollar?",a:50800,unit:"Dollar/Gramm",hint:"Der teuerste Stoff auf der Erde nach Antimaterie.",emoji:"🌙"},
  {id:"geld_010",q:"Wie viele Milliarden Dollar kostet die Internationale Raumstation?",a:150,unit:"Milliarden Dollar",hint:"Das teuerste von Menschen gebaute Objekt.",emoji:"🚀"},
  {id:"geld_011",q:"Wie viel kostet ein Schweizer Luxusquartier (Gnägi Villa) pro Nacht?",a:50000,unit:"Dollar/Nacht",hint:"Exklusivste Hotels kosten ein Vermögen.",emoji:"🏨"},
  {id:"geld_012",q:"Wie viele Milliarden Dollar gab die US-Regierung 2023 für Militär aus?",a:858,unit:"Milliarden Dollar",hint:"Mehr als die nächsten 10 Länder zusammen.",emoji:"⚔️"},
  {id:"geld_013",q:"Wie viel kostete die teuerste Uhr (Patek Philippe Grandmaster Chime)?",a:31,unit:"Millionen Dollar",hint:"2019 für 31 Mio. Dollar versteigert.",emoji:"⌚"},
  {id:"geld_014",q:"Wie viel kostet 1 Kilogramm weißer Trüffel?",a:10000,unit:"Euro/kg",hint:"Kann bis zu 300.000€ pro kg kosten.",emoji:"🍄"},
  {id:"geld_015",q:"Wie viele Milliarden Dollar kostet ein Space Shuttle Flug?",a:1.5,unit:"Milliarden Dollar",hint:"Jeder Shuttle-Flug kostete ~1,5 Mrd. Dollar.",emoji:"🚀"},
  {id:"geld_016",q:"Wie viel kostete das teuerste Buch (Codex Leicester von Leonardo da Vinci)?",a:30.8,unit:"Millionen Dollar",hint:"Gekauft von Bill Gates 1994.",emoji:"📖"},
  {id:"geld_017",q:"Wie viele Billionen Dollar schuldet die USA?",a:34,unit:"Billionen Dollar",hint:"Stand 2024 – wächst täglich.",emoji:"💸"},
  {id:"geld_018",q:"Wie viel kostete das teuerste Foto (Rhein II von Andreas Gursky)?",a:4.34,unit:"Millionen Dollar",hint:"2011 versteigert.",emoji:"📷"},
  {id:"geld_019",q:"Wie viele Milliarden Dollar Jahresumsatz macht McDonald's?",a:23,unit:"Milliarden Dollar",hint:"Hamburger sind ein Milliardengeschäft.",emoji:"🍔"},
  {id:"geld_020",q:"Wie viel kostet ein Kilogramm Saffron (Safran) auf dem Markt?",a:10000,unit:"Euro/kg",hint:"Das teuerste Gewürz der Welt.",emoji:"🌺"},
  {id:"geld_021",q:"Wie viele Millionen Dollar kostet ein Top-Formel-1-Fahrer pro Jahr?",a:50,unit:"Millionen Dollar",hint:"Hamilton verdient ~50 Mio. – plus Sponsoren.",emoji:"🏎️"},
  {id:"geld_022",q:"Wie viel kostete die teuerste Handtasche (Hermès Birkin) je?",a:300,unit:"Tausend Dollar",hint:"Aus Krokodilleder mit Diamanten (Stand ~2024).",emoji:"👜"},
  {id:"geld_023",q:"Wie viele Milliarden Dollar ist der globale Markt für Pornografie wert?",a:97,unit:"Milliarden Dollar",hint:"Einer der größten Märkte im Internet.",emoji:"🔞"},
  {id:"geld_024",q:"Wie viel kostet eine Übernachtung im teuersten Hotel (Empathy Suite, Las Vegas)?",a:100000,unit:"Dollar/Nacht",hint:"Im Palms Casino Resort (Stand ~2024).",emoji:"🏨"},
  {id:"geld_025",q:"Wie viele Milliarden Dollar wert ist Elon Musks SpaceX?",a:180,unit:"Milliarden Dollar",hint:"Stand 2024 – private Raumfahrt boomt.",emoji:"🚀"},
  {id:"geld_026",q:"Wie viel kostet 1 mg Californium-252 in Dollar?",a:27,unit:"Millionen Dollar/mg",hint:"27 Mio. Dollar pro Milligramm.",emoji:"☢️"},
  {id:"geld_027",q:"Wie viele Milliarden Dollar Jahresgewinn macht Saudi Aramco?",a:161,unit:"Milliarden Dollar",hint:"Das profitabelste Unternehmen der Welt 2022.",emoji:"🛢️"},
  {id:"geld_028",q:"Wie viele Millionen Euro kostete das teuerste je verkaufte Auto (Mercedes 300 SLR)?",a:142,unit:"Millionen Euro",hint:"2022 für 142 Millionen Euro versteigert.",emoji:"🚗"},
  {id:"geld_029",q:"Wie viele Milliarden Dollar ist der Bitcoin-Markt wert?",a:1000,unit:"Milliarden Dollar",hint:"Schwankt stark – zeitweise über 1 Billion.",emoji:"₿"},
  {id:"geld_030",q:"Wie viel kostet ein Kobe-Rind pro kg?",a:500,unit:"Euro/kg",hint:"Das teuerste Fleisch der Welt.",emoji:"🥩"},
  {id:"geld_031",q:"Wie viele Milliarden Dollar Jahresbudget hat die NASA?",a:25,unit:"Milliarden Dollar",hint:"Nur 0,3% des US-Budgets.",emoji:"🚀"},
  {id:"geld_032",q:"Wie viel kostet ein Glas Whisky aus der Macallan Fine & Rare Collection?",a:10000,unit:"Dollar",hint:"Pro Glas in Luxus-Bars.",emoji:"🥃"},
  {id:"geld_033",q:"Wie viele Billionen Dollar ist der globale Immobilienmarkt wert?",a:326,unit:"Billionen Dollar",hint:"Der größte Anlagemarkt der Welt.",emoji:"🏠"},
  {id:"geld_034",q:"Wie viel kostet der teuerste Champagner (Goût de Diamants)?",a:1.2,unit:"Millionen Euro",hint:"Mit Diamanten verziert (Stand ~2024).",emoji:"🥂"},
  {id:"geld_035",q:"Wie viele Milliarden Dollar verdient Taylor Swift pro Tour?",a:1,unit:"Milliarden Dollar",hint:"Die Eras Tour 2023-2024 – erste Milliarden-Tour.",emoji:"🎤"},
  {id:"geld_036",q:"Wie viel kostet 1 Gramm Meissen-Porzellan (als Kunstwerk)?",a:1000,unit:"Euro",hint:"Echtes Meissen ist extrem wertvoll.",emoji:"🏺"},
  {id:"geld_037",q:"Wie viel kostete das teuerste Diamant-Ehering (Pink Star)?",a:71.2,unit:"Millionen Dollar",hint:"2017 für 71,2 Mio. Dollar versteigert.",emoji:"💍"},
  {id:"geld_038",q:"Wie viele Milliarden Dollar Steuern hinterziehen Deutsche pro Jahr?",a:30,unit:"Milliarden Euro",hint:"Schätzungen liegen bei 30 Milliarden Euro.",emoji:"💸"},
  {id:"geld_039",q:"Wie viel kostet ein Flug ins All mit Virgin Galactic?",a:450,unit:"Tausend Dollar",hint:"Für einen Suborbitalflug.",emoji:"🚀"},
  {id:"geld_040",q:"Wie viele Milliarden Dollar ist der globale Kaffeehandel wert?",a:100,unit:"Milliarden Dollar",hint:"Kaffee ist eines der größten Handelsgüter.",emoji:"☕"},
  {id:"geld_041",q:"Wie viel kostet 1 Bitcoin auf seinem Allzeithoch in Dollar?",a:73000,unit:"Dollar",hint:"Im März 2024 erreichte Bitcoin ~73.000 Dollar.",emoji:"₿"},
  {id:"geld_042",q:"Wie viele Milliarden Dollar hat Warren Buffett gespendet?",a:50,unit:"Milliarden Dollar",hint:"Der meistgebende Milliardär der Geschichte.",emoji:"💝"},
  {id:"geld_043",q:"Wie viel kostet ein Kilogramm Kaviar (Almas)?",a:34500,unit:"Euro/kg",hint:"Weißer Kaviar von Albino-Stören.",emoji:"🐟"},
  {id:"geld_044",q:"Wie viele Milliarden Dollar Jahresumsatz macht LVMH (Luxuskonzern)?",a:86,unit:"Milliarden Euro",hint:"Louis Vuitton, Moët, Hennessy und viele mehr.",emoji:"👜"},
  {id:"geld_045",q:"Wie viel kostet ein Top-Anwalt in New York pro Stunde?",a:2000,unit:"Dollar/Stunde",hint:"Hochkarätige Anwälte verlangen enorme Honorare.",emoji:"⚖️"},
  {id:"geld_046",q:"Wie viele Milliarden Dollar ist der globale Glücksspielmarkt wert?",a:500,unit:"Milliarden Dollar",hint:"Casinos, Sportwetten und Online-Gambling.",emoji:"🎰"},
  {id:"geld_047",q:"Wie viel kostet ein Luxus-Penthouse in Monaco pro m²?",a:100000,unit:"Euro/m²",hint:"Teuerster Immobilienmarkt der Welt.",emoji:"🏠"},
  {id:"geld_048",q:"Wie viele Milliarden Dollar geben Amerikaner pro Jahr für Haustiere aus?",a:150,unit:"Milliarden Dollar",hint:"Milliarden für Hunde, Katzen und Co.",emoji:"🐕"},
  {id:"geld_049",q:"Wie viel kostet ein Jahr Harvard-Studium (alles inbegriffen)?",a:80000,unit:"Dollar/Jahr",hint:"Wohnen, Essen, Studiengebühren.",emoji:"🎓"},
  {id:"geld_050",q:"Wie viele Milliarden Dollar kostet ein Kernkraftwerk?",a:12,unit:"Milliarden Dollar",hint:"Die neuesten Reaktoren kosten bis zu 30 Mrd.",emoji:"⚡"},
  {id:"geld_051",q:"Wie viel kostet ein Kilo Gold aktuell in Euro?",a:60000,unit:"Euro/kg",hint:"Gold kostet ca. 60.000€/kg – Stand 2024.",emoji:"🪙"},
  {id:"geld_052",q:"Wie viele Milliarden Dollar Jahresumsatz hat Google?",a:280,unit:"Milliarden Dollar",hint:"Haupteinnahme: Werbung.",emoji:"🔍"},
  {id:"geld_053",q:"Wie viel kostet der teuerste Cognac (Hennessy Richard)?",a:12000,unit:"Dollar",hint:"Pro Flasche – handgefertigt (Stand ~2024).",emoji:"🥃"},
  {id:"geld_054",q:"Wie viele Milliarden Dollar kostet es ein Olympisches Spiel auszurichten?",a:15,unit:"Milliarden Dollar",hint:"London 2012 kostete 15 Mrd. Pfund.",emoji:"🏅"},
  {id:"geld_055",q:"Wie viel kostet ein Kilogramm Diamanten (Rohdiamant)?",a:55000,unit:"Dollar/Karat",hint:"Qualitätsdiamanten können viel mehr kosten.",emoji:"💎"},
  {id:"geld_056",q:"Wie viele Milliarden Dollar wert ist der Tabakmarkt global?",a:900,unit:"Milliarden Dollar",hint:"Trotz Rückgang – immer noch riesig.",emoji:"🚬"},
  {id:"geld_057",q:"Wie viel kostet ein privater Hubschrauber (Airbus H145)?",a:7,unit:"Millionen Dollar",hint:"Ein Standard-Luxushubschrauber.",emoji:"🚁"},
  {id:"geld_058",q:"Wie viele Milliarden Dollar verdient FIFA pro WM?",a:5,unit:"Milliarden Dollar",hint:"Die WM 2022 in Katar generierte ~7,5 Mrd.",emoji:"⚽"},
  {id:"geld_059",q:"Wie viel kostet das teuerste Hotelzimmer pro Nacht in Dubai?",a:85000,unit:"Dollar",hint:"Royal Penthouse im Burj Al Arab (Stand ~2024).",emoji:"🏨"},
  {id:"geld_060",q:"Wie viele Milliarden Dollar wert ist der globale Pharmasektor?",a:1600,unit:"Milliarden Dollar",hint:"Ein billionenschwerer Markt.",emoji:"💊"},
  {id:"geld_061",q:"Wie viel kostet 1 kg Heroin auf dem Schwarzmarkt?",a:50000,unit:"Dollar/kg",hint:"Straßenpreise variieren stark.",emoji:"💊"},
  {id:"geld_062",q:"Wie viele Milliarden Dollar geben Amis pro Jahr für Fast Food aus?",a:280,unit:"Milliarden Dollar",hint:"Fast Food ist Amerikas Lieblingsessen.",emoji:"🍔"},
  {id:"geld_063",q:"Wie viel kostet eine private Insel in der Karibik (Einstieg)?",a:5,unit:"Millionen Dollar",hint:"Kleine Inseln ab 5 Mio. Dollar.",emoji:"🏝️"},
  {id:"geld_064",q:"Wie viele Milliarden Dollar wert ist der globale Waffenmarkt?",a:600,unit:"Milliarden Dollar",hint:"Legaler Waffenhandel weltweit.",emoji:"⚔️"},
  {id:"geld_065",q:"Wie viel kostet ein Luxusjet (Bombardier Global 7500)?",a:75,unit:"Millionen Dollar",hint:"Der größte Privatjet der Welt.",emoji:"✈️"},
  {id:"geld_066",q:"Wie viele Milliarden Euro hat Deutschland 2023 in Rüstung investiert?",a:52,unit:"Milliarden Euro",hint:"Auf dem Weg zum 2%-Ziel der NATO.",emoji:"⚔️"},
  {id:"geld_067",q:"Wie viel kostet 1 Sekunde Werbung beim Super Bowl?",a:200,unit:"Tausend Dollar",hint:"30 Sekunden = 6 Mio. Dollar.",emoji:"📺"},
  {id:"geld_068",q:"Wie viele Milliarden Dollar ist TikTok (ByteDance) wert?",a:250,unit:"Milliarden Dollar",hint:"Stand 2024.",emoji:"📱"},
  {id:"geld_069",q:"Wie viel kostet ein Kilogramm Seltener Erde (Scandium)?",a:15000,unit:"Dollar/kg",hint:"Seltene Erden sind der Stoff der modernen Welt.",emoji:"⚗️"},
  {id:"geld_070",q:"Wie viele Milliarden Dollar Jahresgewinne macht Apple?",a:100,unit:"Milliarden Dollar",hint:"Apple ist unfassbar profitabel.",emoji:"🍎"},
  {id:"geld_071",q:"Wie viel kostet eine Hermes Birkin Tasche (Sonderanfertigung)?",a:500,unit:"Tausend Dollar",hint:"Mit exotischen Materialien.",emoji:"👜"},
  {id:"geld_072",q:"Wie viele Milliarden Dollar hat Elon Musk für Twitter/X bezahlt?",a:44,unit:"Milliarden Dollar",hint:"Im Oktober 2022.",emoji:"𝕏"},
  {id:"geld_073",q:"Wie viel kostet ein Kilogramm Plutonium?",a:6.6,unit:"Millionen Dollar",hint:"Das teuerste legale Material auf Erden.",emoji:"☢️"},
  {id:"geld_074",q:"Wie viele Milliarden Dollar wert ist Cristiano Ronaldos Marke?",a:1,unit:"Milliarden Dollar",hint:"CR7 ist Milliardär durch Marke und Investments.",emoji:"⚽"},
  {id:"geld_075",q:"Wie viel kostet ein Kunstwerk von Banksy im Durchschnitt?",a:5,unit:"Millionen Dollar",hint:"Game Changer wurde für 16,8 Mio. verkauft.",emoji:"🎨"},
  {id:"geld_076",q:"Wie viele Milliarden Dollar kostet der Mars-Kolonisierungsplan von SpaceX?",a:100,unit:"Milliarden Dollar",hint:"Musk schätzte ursprünglich 100 Mrd.",emoji:"🔴"},
  {id:"geld_077",q:"Wie viel kostet ein Megajacht (100m+) pro Jahr an Unterhalt?",a:10,unit:"Millionen Dollar/Jahr",hint:"10% des Kaufpreises jährlich für Unterhalt.",emoji:"⛵"},
  {id:"geld_078",q:"Wie viele Milliarden Dollar Jahresumsatz hat die Pornoindustrie?",a:97,unit:"Milliarden Dollar",hint:"Ein gigantischer globaler Markt.",emoji:"🔞"},
  {id:"geld_079",q:"Wie viel kostet eine Tasse Kopi Luwak (teuerster Kaffee)?",a:100,unit:"Dollar/Tasse",hint:"Kaffee aus dem Kot der Zibetkatze (Stand ~2024).",emoji:"☕"},
  {id:"geld_080",q:"Wie viele Milliarden Dollar wert ist der globale E-Sport-Markt?",a:2,unit:"Milliarden Dollar",hint:"Professionelles Spielen wächst rasant.",emoji:"🎮"},
  {id:"geld_081",q:"Wie viel kostet ein Kilogramm Quecksilber auf dem freien Markt?",a:50,unit:"Dollar",hint:"Relativ günstig – trotz Giftigkeit.",emoji:"🌡️"},
  {id:"geld_082",q:"Wie viele Milliarden Euro hat Deutschland in die Flüchtlingskrise investiert?",a:20,unit:"Milliarden Euro/Jahr",hint:"2015-2022 insgesamt über 100 Mrd.",emoji:"🏠"},
  {id:"geld_083",q:"Wie viel kostet ein Top-Fußballspieler-Transfer (Neymar)?",a:222,unit:"Millionen Euro",hint:"Teuerster Transfer aller Zeiten 2017.",emoji:"⚽"},
  {id:"geld_084",q:"Wie viele Milliarden Dollar wert ist der globale Kosmetikmarkt?",a:500,unit:"Milliarden Dollar",hint:"Schönheit ist ein riesiges Geschäft.",emoji:"💄"},
  {id:"geld_085",q:"Wie viel kostet 1 Watt Solarenergie zur Installation?",a:0.3,unit:"Dollar/Watt",hint:"Drastisch gesunken – von 80$/W in 1970.",emoji:"☀️"},
  {id:"geld_086",q:"Wie viele Milliarden Dollar kostet ein Atomkraftwerk (Hinkley Point C)?",a:33,unit:"Milliarden Pfund",hint:"Das teuerste Bauwerk in UK.",emoji:"⚡"},
  {id:"geld_087",q:"Wie viel kostet eine Luxusuhr von Richard Mille?",a:1,unit:"Millionen Dollar",hint:"Die teuersten Uhren der Welt.",emoji:"⌚"},
  {id:"geld_088",q:"Wie viele Milliarden Dollar Jahresumsatz hat Nestlé?",a:95,unit:"Milliarden Dollar",hint:"Größter Lebensmittelkonzern der Welt.",emoji:"🍫"},
  {id:"geld_089",q:"Wie viel kostet ein Kilogramm Kokain in Europa?",a:35000,unit:"Euro/kg",hint:"Straßenpreise – stark variierend.",emoji:"💊"},
  {id:"geld_090",q:"Wie viele Milliarden Dollar wert ist der globale Alkohol-Markt?",a:1600,unit:"Milliarden Dollar",hint:"Bier, Wein und Spirituosen zusammen.",emoji:"🍷"},
  {id:"geld_091",q:"Wie viel kostet ein privater Raketenstarter bei SpaceX (Falcon 9)?",a:67,unit:"Millionen Dollar",hint:"67 Mio. pro Falcon-9-Start.",emoji:"🚀"},
  {id:"geld_092",q:"Wie viele Milliarden Dollar verdiente Fortnite in seinem ersten Jahr?",a:2.4,unit:"Milliarden Dollar",hint:"Epic Games Blockbuster-Spiel.",emoji:"🎮"},
  {id:"geld_093",q:"Wie viel kostet der teuerste Sneaker je versteigert?",a:1.8,unit:"Millionen Dollar",hint:"Nike Moon Shoe von 1972.",emoji:"👟"},
  {id:"geld_094",q:"Wie viele Milliarden Dollar wert ist die gesamte Krypto-Marktkapitalisierung?",a:2000,unit:"Milliarden Dollar",hint:"Stand Anfang 2024.",emoji:"₿"},
  {id:"geld_095",q:"Wie viel kostet ein Liter Blut im Krankenhaus in den USA?",a:1000,unit:"Dollar",hint:"Gespendetes Blut wird teuer verkauft.",emoji:"🩸"},
  {id:"geld_096",q:"Wie viele Milliarden Dollar Jahresumsatz hat Amazon?",a:514,unit:"Milliarden Dollar",hint:"Größter Onlinehändler der Welt.",emoji:"📦"},
  {id:"geld_097",q:"Wie viel kostet ein Quadratmeter in Hongkong (teuerste Gegend)?",a:100000,unit:"Dollar/m²",hint:"Hongkong ist eine der teuersten Städte (Stand ~2024).",emoji:"🏙️"},
  {id:"geld_098",q:"Wie viele Millionen Dollar kostet ein neues Flugzeug (Airbus A380)?",a:445,unit:"Millionen Dollar",hint:"Das größte Passagierflugzeug.",emoji:"✈️"},
  {id:"geld_099",q:"Wie viel kostet eine Flasche Petrus (Bordeaux, 1947)?",a:75000,unit:"Euro",hint:"Einige Flaschen wurden für über 100.000€ verkauft.",emoji:"🍷"},
  {id:"geld_100",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Schusswaffen?",a:28,unit:"Milliarden Dollar",hint:"Legaler Waffenmarkt.",emoji:"🔫"},
  {id:"geld_101",q:"Wie viel kostet 1 km Autobahn zu bauen in Deutschland?",a:25,unit:"Millionen Euro/km",hint:"25 Mio. Euro pro Kilometer.",emoji:"🛣️"},
  {id:"geld_102",q:"Wie viele Millionen Euro kostet der Wiederaufbau der Notre-Dame?",a:700,unit:"Millionen Euro",hint:"Über 700 Mio. Euro für die Renovierung.",emoji:"⛪"},
  {id:"geld_103",q:"Wie viel kostet ein Quadratmeter in Paris (Innenstadt)?",a:12000,unit:"Euro/m²",hint:"Paris ist eine der teuersten Städte Europas.",emoji:"🗼"},
  {id:"geld_104",q:"Wie viele Milliarden Dollar ist Tesla wert?",a:600,unit:"Milliarden Dollar",hint:"Schwankt stark – war mal über 1 Billion.",emoji:"🚗"},
  {id:"geld_105",q:"Wie viel kostet ein Jahr in der teuersten Privatschule der Welt?",a:120,unit:"Tausend Schweizer Franken",hint:"Institut Le Rosey in der Schweiz (Stand ~2024).",emoji:"🎓"},
  {id:"geld_106",q:"Wie viele Milliarden Dollar wert ist der globale Musikmarkt?",a:26,unit:"Milliarden Dollar",hint:"Streaming dominiert.",emoji:"🎵"},
  {id:"geld_107",q:"Wie viel kostet ein Kilogramm Vanille?",a:600,unit:"Dollar/kg",hint:"Einer der teuersten Gewürze nach Safran.",emoji:"🌿"},
  {id:"geld_108",q:"Wie viele Milliarden Dollar wert ist Goldman Sachs?",a:120,unit:"Milliarden Dollar",hint:"Eine der mächtigsten Investmentbanken.",emoji:"🏦"},
  {id:"geld_109",q:"Wie viel kostet ein Penthouse in New York City (durchschnittlich)?",a:20,unit:"Millionen Dollar",hint:"Luxuspenthouses in Manhattan.",emoji:"🏙️"},
  {id:"geld_110",q:"Wie viele Milliarden Dollar gibt die Welt pro Jahr für Rüstung aus?",a:2200,unit:"Milliarden Dollar",hint:"2,2 Billionen Dollar jährlich.",emoji:"⚔️"},
  {id:"geld_111",q:"Wie viel kostet 1 km neues U-Bahn-Netz in London?",a:1,unit:"Milliarden Dollar/km",hint:"London hat die teuersten U-Bahnbauprojekte.",emoji:"🚇"},
  {id:"geld_112",q:"Wie viele Milliarden Dollar ist der globale Markt für Videospiele wert?",a:200,unit:"Milliarden Dollar",hint:"Größer als Film und Musik zusammen.",emoji:"🎮"},
  {id:"geld_113",q:"Wie viel kostet ein Jahresgehalt eines Hedge-Fonds-Managers?",a:1,unit:"Milliarden Dollar",hint:"Spitzenmanager verdienen Milliarden.",emoji:"💰"},
  {id:"geld_114",q:"Wie viele Milliarden Dollar ist der globale Tourismus-Markt wert?",a:9500,unit:"Milliarden Dollar",hint:"9,5 Billionen Dollar – einer der größten Sektoren.",emoji:"✈️"},
  {id:"geld_115",q:"Wie viel kostet das Anlegen eines Sterns nach dir?",a:50,unit:"Dollar",hint:"Internationales Sternregister – eigentlich rechtlich nicht bindend.",emoji:"⭐"},
  {id:"geld_116",q:"Wie viele Milliarden Dollar kostet ein Wolkenkratzer (Burj Khalifa)?",a:1.5,unit:"Milliarden Dollar",hint:"Der höchste Turm der Welt.",emoji:"🏙️"},
  {id:"geld_117",q:"Wie viel kostet 1 Kilo Seltener Erden-Neodym?",a:175,unit:"Dollar/kg",hint:"Essenziell für Elektromotoren.",emoji:"⚗️"},
  {id:"geld_118",q:"Wie viele Milliarden Dollar wert ist der FC Barcelona?",a:5,unit:"Milliarden Dollar",hint:"Einer der wertvollsten Sportklubs.",emoji:"⚽"},
  {id:"geld_119",q:"Wie viel kostet ein privater DNA-Test bei 23andMe?",a:200,unit:"Dollar",hint:"Plus optionale Abonnements.",emoji:"🧬"},
  {id:"geld_120",q:"Wie viele Milliarden Dollar Jahresumsatz hat die Filmindustrie (Hollywood)?",a:50,unit:"Milliarden Dollar",hint:"Box Office plus Streaming.",emoji:"🎬"},
  {id:"geld_121",q:"Wie viel kostet ein Meter Eintrittskarte für ein Taylor-Swift-Konzert (VIP)?",a:3000,unit:"Dollar",hint:"VIP-Pakete für die Eras Tour.",emoji:"🎤"},
  {id:"geld_122",q:"Wie viele Milliarden Dollar wert ist die Marke Nike?",a:50,unit:"Milliarden Dollar",hint:"Just Do It – einer der stärksten Markennamen.",emoji:"👟"},
  {id:"geld_123",q:"Wie viel kostet ein Kilogramm weißer Trüffel auf Auktionen?",a:300,unit:"Tausend Euro/kg",hint:"Rekord-Trüffel werden für Hunderttausende verkauft.",emoji:"🍄"},
  {id:"geld_124",q:"Wie viele Milliarden Dollar wert ist der globale Schönheitsmarkt?",a:800,unit:"Milliarden Dollar",hint:"Wächst stark durch Influencer-Kultur.",emoji:"💄"},
  {id:"geld_125",q:"Wie viel kostet ein Concorde-Ticket (als sie noch flog)?",a:8000,unit:"Dollar",hint:"Ein Transatlantikflug für 8000 Dollar.",emoji:"✈️"},
  {id:"geld_126",q:"Wie viele Milliarden Dollar hat Elon Musk in einem Jahr verloren (2022)?",a:200,unit:"Milliarden Dollar",hint:"Größter Vermögensverlust in der Geschichte.",emoji:"📉"},
  {id:"geld_127",q:"Wie viel kostet ein Quadratmeter auf der teuersten Straße der Welt (Hong Kong)?",a:236,unit:"Tausend Dollar/m²",hint:"Causeway Bay, Hong Kong (Stand ~2024).",emoji:"🏙️"},
  {id:"geld_128",q:"Wie viele Milliarden Dollar wert ist der globale Sportmarkt?",a:500,unit:"Milliarden Dollar",hint:"Alle Sportveranstaltungen, Rechte und Merchandise.",emoji:"⚽"},
  {id:"geld_129",q:"Wie viel kostet 1 Minute Werbung auf dem Super Bowl?",a:10,unit:"Millionen Dollar",hint:"Über 10 Mio. Dollar für 30 Sekunden.",emoji:"📺"},
  {id:"geld_130",q:"Wie viele Milliarden Dollar kostet das amerikanische Bildungssystem pro Jahr?",a:700,unit:"Milliarden Dollar",hint:"Von Kindergarten bis Uni.",emoji:"🎓"},
  {id:"geld_131",q:"Wie viel kostet ein Liter Parfüm Chanel No. 5?",a:3000,unit:"Euro",hint:"Eines der ikonischsten Parfüms.",emoji:"🌸"},
  {id:"geld_132",q:"Wie viele Milliarden Dollar hat Saudi-Arabien in Soccer-Stars investiert?",a:6,unit:"Milliarden Dollar",hint:"Die Saudi Pro League wirbt Weltstars ab.",emoji:"⚽"},
  {id:"geld_133",q:"Wie viel kostet ein Kilogramm Madame Jeanette-Chili in Europa?",a:50,unit:"Euro/kg",hint:"Seltene scharfe Chili aus Surinam.",emoji:"🌶️"},
  {id:"geld_134",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Streaming?",a:100,unit:"Milliarden Dollar",hint:"Netflix, Spotify, Amazon und alle anderen.",emoji:"📺"},
  {id:"geld_135",q:"Wie viel kostet eine Mitgliedschaft im Augusta National Golf Club?",a:300,unit:"Tausend Dollar",hint:"Der exklusivste Golfklub der Welt.",emoji:"⛳"},
  {id:"geld_136",q:"Wie viele Milliarden Dollar verliert die Weltwirtschaft durch Korruption?",a:2600,unit:"Milliarden Dollar",hint:"2,6 Billionen Dollar pro Jahr laut UN.",emoji:"💸"},
  {id:"geld_137",q:"Wie viel kostet ein kg Ambergris (Walrat) auf dem Schwarzmarkt?",a:50000,unit:"Dollar",hint:"Verwendet in Luxusparfüms.",emoji:"🐋"},
  {id:"geld_138",q:"Wie viele Milliarden Dollar ist der globale Fast-Fashion-Markt wert?",a:100,unit:"Milliarden Dollar",hint:"Zara, H&M und Shein dominieren.",emoji:"👗"},
  {id:"geld_139",q:"Wie viel kostet ein Privatflug London-New York?",a:150,unit:"Tausend Dollar",hint:"Im Luxus-Jet.",emoji:"✈️"},
  {id:"geld_140",q:"Wie viele Milliarden Dollar wert ist der globale Lebensmittelmarkt?",a:8000,unit:"Milliarden Dollar",hint:"8 Billionen Dollar – täglicher Bedarf.",emoji:"🍎"},
  {id:"geld_141",q:"Wie viel kostet ein Meter Silizium-Chip-Produktion (TSMC 2nm)?",a:20000,unit:"Dollar/Wafer",hint:"Die teuersten Chips der Welt.",emoji:"💻"},
  {id:"geld_142",q:"Wie viele Milliarden Dollar wert ist der globale Online-Shopping-Markt?",a:5000,unit:"Milliarden Dollar",hint:"5 Billionen Dollar – wächst weiter.",emoji:"📦"},
  {id:"geld_143",q:"Wie viel kostet 1 Liter menschliches Blutplasma?",a:500,unit:"Dollar",hint:"Blutplasma ist ein wertvolles Medizinprodukt.",emoji:"🩸"},
  {id:"geld_144",q:"Wie viele Milliarden Dollar wert ist Spotify?",a:40,unit:"Milliarden Dollar",hint:"Stand 2024.",emoji:"🎵"},
  {id:"geld_145",q:"Wie viel kostet ein Kilogramm Carbon-Fiber?",a:100,unit:"Dollar/kg",hint:"Für Formel-1 und Luft-/Raumfahrt essenziell.",emoji:"🏎️"},
  {id:"geld_146",q:"Wie viele Milliarden Dollar hat Kylie Jenner verdient als jüngste Selfmade-Milliardärin?",a:1,unit:"Milliarden Dollar",hint:"Durch ihre Kosmetikmarke.",emoji:"💄"},
  {id:"geld_147",q:"Wie viel kostet ein Quadratmeter in München (Maxvorstadt)?",a:15000,unit:"Euro/m²",hint:"Einer der teuersten Immobilienmärkte Deutschlands.",emoji:"🏠"},
  {id:"geld_148",q:"Wie viele Milliarden Dollar kostet es die Klimakrise zu lösen (jährlich)?",a:4000,unit:"Milliarden Dollar",hint:"Schätzungen des IPCC.",emoji:"🌍"},
  {id:"geld_149",q:"Wie viel kostet der teuerste Tee (Da Hong Pao)?",a:1,unit:"Millionen Dollar/kg",hint:"1 Mio. Dollar pro kg – kaum noch erhältlich (Stand ~2024).",emoji:"🍵"},
  {id:"geld_150",q:"Wie viele Milliarden Dollar wert ist der globale Cannabismarkt?",a:50,unit:"Milliarden Dollar",hint:"Legal und illegal zusammen.",emoji:"🌿"},
  {id:"geld_151",q:"Wie viel kostet ein Kilogramm roher Saphir?",a:30000,unit:"Dollar/Karat",hint:"Hochwertige Saphire kosten 30.000+/Karat.",emoji:"💎"},
  {id:"geld_152",q:"Wie viele Milliarden Dollar jährlich macht die CIA mit verdeckten Operationen?",a:90,unit:"Milliarden Dollar",hint:"Das geheime US-Geheimdienstbudget.",emoji:"🕵️"},
  {id:"geld_153",q:"Wie viel kostet ein Kilo Seltenes Element Rhenium?",a:5000,unit:"Dollar/kg",hint:"Eines der seltensten stabilen Elemente.",emoji:"⚗️"},
  {id:"geld_154",q:"Wie viele Milliarden Dollar wert ist der globale Markt für KI?",a:200,unit:"Milliarden Dollar",hint:"Wächst exponentiell.",emoji:"🤖"},
  {id:"geld_155",q:"Wie viel kostet ein Ferrari F40 heute?",a:1.5,unit:"Millionen Euro",hint:"Legendärer Supersportwagen von 1987.",emoji:"🚗"},
  {id:"geld_156",q:"Wie viele Milliarden Dollar wert ist der globale Cloud-Computing-Markt?",a:600,unit:"Milliarden Dollar",hint:"AWS, Azure und Google dominieren.",emoji:"☁️"},
  {id:"geld_157",q:"Wie viel kostet 1 Meter Unterwasserkabel (Internet)?",a:35000,unit:"Dollar/km",hint:"Unterseekabel verbinden die Kontinente.",emoji:"🌊"},
  {id:"geld_158",q:"Wie viele Milliarden Dollar geben Reiche Menschen für Kunst aus?",a:68,unit:"Milliarden Dollar",hint:"Der globale Kunstmarkt 2022.",emoji:"🎨"},
  {id:"geld_159",q:"Wie viel kostet der teuerste Wein je (Romanée-Conti 1945)?",a:558,unit:"Tausend Dollar",hint:"Pro Flasche – 2018 versteigert.",emoji:"🍷"},
  {id:"geld_160",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Cybersecurity?",a:200,unit:"Milliarden Dollar",hint:"Wächst mit jedem Angriff.",emoji:"🔒"},
  {id:"geld_161",q:"Wie viel kostet ein Penthouse in Dubai (Palm Jumeirah)?",a:30,unit:"Millionen Dollar",hint:"Luxuriöse Residenzen auf der Palmeninsel.",emoji:"🌴"},
  {id:"geld_162",q:"Wie viele Milliarden Dollar wert ist die Sportartikelmesse (Adidas+Nike)?",a:100,unit:"Milliarden Dollar",hint:"Beide zusammen.",emoji:"👟"},
  {id:"geld_163",q:"Wie viel kostet ein Stunde mit einem Top-Management-Consultant (McKinsey)?",a:1200,unit:"Dollar",hint:"Für Senior Partner.",emoji:"💼"},
  {id:"geld_164",q:"Wie viele Milliarden Dollar wert ist der globale Pharmamarkt?",a:1600,unit:"Milliarden Dollar",hint:"Medikamente sind ein riesiger Markt.",emoji:"💊"},
  {id:"geld_165",q:"Wie viel kostet ein Jahresmitgliedschaft bei Amazon Prime?",a:139,unit:"Dollar",hint:"In den USA – unterschiedlich je Land.",emoji:"📦"},
  {id:"geld_166",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Elektroautos?",a:400,unit:"Milliarden Dollar",hint:"Wächst schnell – Tesla führt.",emoji:"🚗"},
  {id:"geld_167",q:"Wie viele Milliarden Dollar Jahresumsatz hat Volkswagen?",a:293,unit:"Milliarden Euro",hint:"Größter Automobilkonzern Europas.",emoji:"🚗"},
  {id:"geld_168",q:"Wie viel kostet ein normales Herz-Transplantation in den USA?",a:1,unit:"Millionen Dollar",hint:"Inklusive Nachsorge.",emoji:"❤️"},
  {id:"geld_169",q:"Wie viele Milliarden Dollar wert ist TikTok-Eigentümer ByteDance?",a:250,unit:"Milliarden Dollar",hint:"Wertvollstes nicht-börsennotiertes Unternehmen.",emoji:"📱"},
  {id:"geld_170",q:"Wie viel kostet ein Kilogramm Lithium auf dem Weltmarkt?",a:30,unit:"Dollar/kg",hint:"Essenziell für Batterien.",emoji:"⚡"},
  {id:"geld_171",q:"Wie viele Milliarden Dollar wert ist der globale Suchmaschinenmarkt?",a:300,unit:"Milliarden Dollar",hint:"Google dominiert mit über 90%.",emoji:"🔍"},
  {id:"geld_172",q:"Wie viel kostet ein Abonnement von Netflix pro Monat (Standard)?",a:15,unit:"Dollar/Monat",hint:"In den USA – unterschiedlich je Land.",emoji:"📺"},
  {id:"geld_173",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Elektronikmüll?",a:60,unit:"Milliarden Dollar",hint:"Wertvolle Metalle landen im Müll.",emoji:"♻️"},
  {id:"geld_174",q:"Wie viel kostet 1 Gramm Helium-3 (Mondressource)?",a:14000,unit:"Dollar/Gramm",hint:"Potenzielle Fusionsenergiequelle.",emoji:"🌙"},
  {id:"geld_175",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Düngemittel?",a:200,unit:"Milliarden Dollar",hint:"Essenziell für die Nahrungsmittelproduktion.",emoji:"🌾"},
  {id:"geld_176",q:"Wie viel kostet ein Stunde mit einem Top-Strafrechtler in Deutschland?",a:600,unit:"Euro/Stunde",hint:"Top-Anwälte verlangen enorme Stundensätze.",emoji:"⚖️"},
  {id:"geld_177",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Halbleiter?",a:600,unit:"Milliarden Dollar",hint:"Chips regieren die Welt.",emoji:"💻"},
  {id:"geld_178",q:"Wie viel kostet ein Kilo Hafnium (seltenes Metall)?",a:900,unit:"Dollar/kg",hint:"Verwendet in Atomreaktoren.",emoji:"⚗️"},
  {id:"geld_179",q:"Wie viele Millionen Dollar hat der erste NFT (Beeple) eingebracht?",a:69,unit:"Millionen Dollar",hint:"'Everydays: The First 5000 Days' – 69 Mio. 2021.",emoji:"🖼️"},
  {id:"geld_180",q:"Wie viel kostet ein Kilo weißes Trüffelöl?",a:5000,unit:"Euro/Liter",hint:"Das beste Trüffelöl ist extrem teuer.",emoji:"🍄"},
  {id:"geld_181",q:"Wie viele Milliarden Dollar ist Airbnb wert?",a:90,unit:"Milliarden Dollar",hint:"Stand 2024.",emoji:"🏠"},
  {id:"geld_182",q:"Wie viel kostet eine Lungenatmung in einem US-Krankenhaus (Beatmung, Tag)?",a:10000,unit:"Dollar/Tag",hint:"Intensivstation in den USA.",emoji:"🏥"},
  {id:"geld_183",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Robotik?",a:100,unit:"Milliarden Dollar",hint:"Industrieroboter und Service-Roboter.",emoji:"🤖"},
  {id:"geld_184",q:"Wie viel kostet ein Kilogramm Gallium?",a:250,unit:"Dollar/kg",hint:"Essenziell für Halbleiter.",emoji:"⚗️"},
  {id:"geld_185",q:"Wie viele Milliarden Dollar wert ist Ferrari als Unternehmen?",a:60,unit:"Milliarden Dollar",hint:"Ferrari ist mehr Luxusmarke als Autohersteller.",emoji:"🚗"},
  {id:"geld_186",q:"Wie viel kostet 1 Liter Kerosin für Privatjets?",a:2,unit:"Dollar/Liter",hint:"Steuerbegünstigt – weniger als Benzin.",emoji:"✈️"},
  {id:"geld_187",q:"Wie viele Milliarden Dollar wert ist der globale Diamantmarkt?",a:80,unit:"Milliarden Dollar",hint:"Lab-Diamanten bedrohen den Markt.",emoji:"💎"},
  {id:"geld_188",q:"Wie viel kostet ein Durchschnittskauf im Hermès Paris pro Einkauf?",a:5000,unit:"Euro",hint:"Hermès-Kunden geben viel aus.",emoji:"👜"},
  {id:"geld_189",q:"Wie viele Milliarden Dollar wert ist Airbus?",a:100,unit:"Milliarden Euro",hint:"Der größte Flugzeugbauer Europas.",emoji:"✈️"},
  {id:"geld_190",q:"Wie viel kostet ein Tesla Model S?",a:100000,unit:"Dollar",hint:"Das Flaggschiff-Modell von Tesla.",emoji:"🚗"},
  {id:"geld_191",q:"Wie viele Milliarden Dollar wert ist der globale Markt für nachhaltige Investments?",a:35000,unit:"Milliarden Dollar",hint:"ESG-Investments boomen.",emoji:"🌿"},
  {id:"geld_192",q:"Wie viel kostet ein km² Agrarland in Bayern?",a:80000,unit:"Euro/Hektar",hint:"Bayern hat die teuersten Agrarpreise Deutschlands.",emoji:"🌾"},
  {id:"geld_193",q:"Wie viele Milliarden Dollar wert ist der globale Online-Gaming-Markt?",a:250,unit:"Milliarden Dollar",hint:"Mobile Gaming ist der größte Teil.",emoji:"🎮"},
  {id:"geld_194",q:"Wie viele Milliarden Dollar wert ist IKEA?",a:58,unit:"Milliarden Dollar",hint:"Privat geführt – durch eine Stiftung.",emoji:"🛋️"},
  {id:"geld_195",q:"Wie viele Milliarden Dollar Jahresumsatz macht H&M?",a:22,unit:"Milliarden Dollar",hint:"Zweitgrößte Modekette der Welt.",emoji:"👗"},
  {id:"geld_196",q:"Wie viele Milliarden Dollar wert ist WhatsApp (beim Verkauf an Facebook)?",a:19,unit:"Milliarden Dollar",hint:"Gekauft 2014 für damals schwindelerregende Summe.",emoji:"💬"},
  {id:"geld_197",q:"Wie viele Milliarden Euro wert ist BMW?",a:70,unit:"Milliarden Euro",hint:"Eines der wertvollsten deutschen Unternehmen.",emoji:"🚗"},
  {id:"geld_198",q:"Wie viele Millionen Dollar kostet eine Satellitenmine?",a:300,unit:"Millionen Dollar",hint:"Millionen für einen militärischen Satelliten.",emoji:"🛰️"},
  {id:"geld_199",q:"Wie viele Milliarden Dollar wert ist Red Bull?",a:20,unit:"Milliarden Dollar",hint:"Aus Österreich zum Weltkonzern.",emoji:"🐂"},
  {id:"geld_200",q:"Wie viele Milliarden Dollar hat die Corona-Impfkampagne die Welt gekostet?",a:15,unit:"Milliarden Dollar",hint:"Für die Entwicklung der mRNA-Impfstoffe.",emoji:"💉"},
  {id:"geld_201",q:"Wie viele Milliarden Euro wert ist Adidas?",a:35,unit:"Milliarden Euro",hint:"Der Streifen ist eine der wertvollsten Marken.",emoji:"👟"},
  {id:"geld_202",q:"Wie viele Milliarden Dollar hat Bill Gates gespendet?",a:59,unit:"Milliarden Dollar",hint:"Die Gates Foundation ist größte private Stiftung.",emoji:"💝"},
  {id:"geld_203",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Elektrizität?",a:3000,unit:"Milliarden Dollar",hint:"3 Billionen Dollar – essenziell für alles.",emoji:"⚡"},
  {id:"geld_204",q:"Wie viele Milliarden Dollar Marktkapitalisierung hat Microsoft?",a:3200,unit:"Milliarden Dollar",hint:"Stand 2024 – zeitweise das wertvollste Unternehmen.",emoji:"💻"},
  {id:"geld_205",q:"Wie viele Milliarden Euro kostet Oktoberfest die Münchner Wirtschaft?",a:1.3,unit:"Milliarden Euro",hint:"Über eine Milliarde Euro Wirtschaftsleistung.",emoji:"🍺"},
  {id:"geld_206",q:"Wie viele Milliarden Dollar wert ist der globale Haushaltsgeräte-Markt?",a:700,unit:"Milliarden Dollar",hint:"Waschmaschinen, Kühlschränke und Co.",emoji:"🏠"},
  {id:"geld_207",q:"Wie viele Milliarden Euro Schaden entsteht durch Cyberkriminalität in Deutschland?",a:200,unit:"Milliarden Euro",hint:"Jährlich laut Bitkom.",emoji:"🔒"},
  {id:"geld_208",q:"Wie viele Millionen Dollar kostet 1 km Autobahn in den USA?",a:10,unit:"Millionen Dollar/km",hint:"In dicht bebauten Gebieten deutlich mehr.",emoji:"🛣️"},
  {id:"geld_209",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Haustierprodukte?",a:260,unit:"Milliarden Dollar",hint:"Wächst stark – Menschen lieben ihre Haustiere.",emoji:"🐕"},
  {id:"geld_210",q:"Wie viele Milliarden Euro wert ist SAP?",a:200,unit:"Milliarden Euro",hint:"Deutschlands wertvollstes Tech-Unternehmen.",emoji:"💻"},
  {id:"geld_211",q:"Wie viele Millionen Dollar kostet die Herstellung eines Smartphones?",a:350,unit:"Millionen Dollar",hint:"Dollar Materialkosten für ein iPhone.",emoji:"📱"},
  {id:"geld_212",q:"Wie viele Milliarden Dollar hat Amazon für Whole Foods bezahlt?",a:13.7,unit:"Milliarden Dollar",hint:"2017 – Amazons Einstieg in den Lebensmittelhandel.",emoji:"🛒"},
  {id:"geld_213",q:"Wie viele Milliarden Dollar Jahresumsatz hat Coca-Cola?",a:46,unit:"Milliarden Dollar",hint:"Eines der bekanntesten Marken weltweit.",emoji:"🥤"},
  {id:"geld_214",q:"Wie viele Milliarden Dollar wert ist der globale Sportkleidungsmarkt?",a:200,unit:"Milliarden Dollar",hint:"Athleisure-Trend treibt das Wachstum.",emoji:"👕"},
  {id:"geld_215",q:"Wie viele Milliarden Euro kostet die Energiewende Deutschland bis 2035?",a:500,unit:"Milliarden Euro",hint:"Schätzungen variieren erheblich.",emoji:"⚡"},
  {id:"geld_216",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Bücher?",a:138,unit:"Milliarden Dollar",hint:"Print und E-Books zusammen.",emoji:"📚"},
  {id:"geld_217",q:"Wie viele Milliarden Dollar hat Google für YouTube bezahlt?",a:1.65,unit:"Milliarden Dollar",hint:"2006 – im Rückblick das Schnäppchen des Jahrhunderts.",emoji:"▶️"},
  {id:"geld_218",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Süßigkeiten?",a:200,unit:"Milliarden Dollar",hint:"Schokolade, Kaugummi und Co.",emoji:"🍫"},
  {id:"geld_219",q:"Wie viele Milliarden Euro hat die Covid-19-Krise Deutschland gekostet?",a:300,unit:"Milliarden Euro",hint:"Hilfspaket plus wirtschaftliche Einbußen.",emoji:"😷"},
  {id:"geld_220",q:"Wie viele Milliarden Dollar wert ist Instacart?",a:10,unit:"Milliarden Dollar",hint:"Lebensmittellieferservice aus San Francisco.",emoji:"🛒"},
  {id:"geld_221",q:"Wie viele Milliarden Euro wert ist Bosch?",a:93,unit:"Milliarden Euro",hint:"Größter Automobilzulieferer der Welt.",emoji:"🔧"},
  {id:"geld_222",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Brillen?",a:150,unit:"Milliarden Dollar",hint:"Luxottica dominiert den Markt.",emoji:"👓"},
  {id:"geld_223",q:"Wie viele Milliarden Dollar hat Facebook (Meta) für Instagram bezahlt?",a:1,unit:"Milliarden Dollar",hint:"2012 – heute ist Instagram Milliarden wert.",emoji:"📸"},
  {id:"geld_224",q:"Wie viele Milliarden Euro Schulden hat die Deutsche Bahn?",a:30,unit:"Milliarden Euro",hint:"Eines der am stärksten verschuldeten Staatsunternehmen.",emoji:"🚂"},
  {id:"geld_225",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Kreuzfahrten?",a:150,unit:"Milliarden Dollar",hint:"Wächst trotz Pandemie-Einbruch wieder.",emoji:"🚢"},
  {id:"geld_226",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Hautpflege?",a:180,unit:"Milliarden Dollar",hint:"Teil des riesigen Kosmetik-Markts.",emoji:"💆"},
  {id:"geld_227",q:"Wie viele Millionen Dollar hat Apple für Shazam bezahlt?",a:400,unit:"Millionen Dollar",hint:"Millionen Dollar für die Musik-App.",emoji:"🎵"},
  {id:"geld_228",q:"Wie viele Milliarden Euro Jahresumsatz hat Deutsche Telekom?",a:114,unit:"Milliarden Euro",hint:"Größter Telekomkonzern Europas.",emoji:"📱"},
  {id:"geld_229",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Dating-Apps?",a:9,unit:"Milliarden Dollar",hint:"Tinder, Bumble und Co.",emoji:"❤️"},
  {id:"geld_230",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Fitness?",a:100,unit:"Milliarden Dollar",hint:"Fitnessstudios, Apps und Equipment.",emoji:"💪"},
  {id:"geld_231",q:"Wie viele Milliarden Dollar hat Microsoft für LinkedIn bezahlt?",a:26.2,unit:"Milliarden Dollar",hint:"2016 – das teuerste Social-Media-Acquisition.",emoji:"💼"},
  {id:"geld_232",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Schmerzmittel?",a:35,unit:"Milliarden Dollar",hint:"Ibuprofen, Aspirin und Co.",emoji:"💊"},
  {id:"geld_233",q:"Wie viele Milliarden Dollar kostet ein Flugzeugträger der USA?",a:13,unit:"Milliarden Dollar",hint:"Der Gerald R. Ford kostet 13,3 Milliarden.",emoji:"🚢"},
  {id:"geld_234",q:"Wie viele Milliarden Euro wert ist BASF?",a:40,unit:"Milliarden Euro",hint:"Größter Chemiekonzern der Welt.",emoji:"⚗️"},
  {id:"geld_235",q:"Wie viele Milliarden Dollar wert ist der globale Markt für Legal Cannabis?",a:50,unit:"Milliarden Dollar",hint:"Wächst durch Legalisierungswellen.",emoji:"🌿"},
  {id:"geld_236",q:"Wie viele Milliarden Dollar Jahresumsatz macht Walt Disney?",a:88,unit:"Milliarden Dollar",hint:"Film, Parks, Streaming und Merchandise.",emoji:"🏰"},
  {id:"geld_237",q:"Wie viele Milliarden Dollar hat Microsoft für Activision Blizzard bezahlt?",a:68.7,unit:"Milliarden Dollar",hint:"2023 – das teuerste Gaming-Acquisition.",emoji:"🎮"},
  {id:"geld_238",q:"Wie viele Milliarden Euro wert ist der deutsche Immobilienmarkt?",a:14000,unit:"Milliarden Euro",hint:"14 Billionen Euro – größtes nationales Vermögen.",emoji:"🏠"},
  {id:"geld_239",q:"Wie viele Milliarden Dollar kostet das James Webb Telescope?",a:10,unit:"Milliarden Dollar",hint:"Das teuerste Teleskop der Geschichte.",emoji:"🔭"},
  {id:"geld_240",q:"Wie viele Milliarden Euro Jahresumsatz hat Siemens?",a:77,unit:"Milliarden Euro",hint:"Eines der größten Industrieunternehmen Europas.",emoji:"⚙️"},
  {id:"geld_241",q:"Wie viele Milliarden Dollar wert ist Zoom?",a:20,unit:"Milliarden Dollar",hint:"Covid hat Zoom zum Must-Have gemacht.",emoji:"📹"},
  {id:"geld_242",q:"Wie viele Milliarden Dollar hat TikTok laut Schätzungen Umsatz?",a:16,unit:"Milliarden Dollar",hint:"Stand 2023 – schnell wachsend.",emoji:"📱"},
  {id:"geld_243",q:"Wie viele Milliarden Dollar wert ist der globale Sneaker-Markt?",a:70,unit:"Milliarden Dollar",hint:"Nike, Adidas und Resale-Markt zusammen.",emoji:"👟"},
  {id:"geld_244",q:"Wie viele Milliarden Euro schulden Deutsche Privathaushalte insgesamt?",a:1900,unit:"Milliarden Euro",hint:"1,9 Billionen Euro Privatschulden.",emoji:"💸"},
  {id:"geld_245",q:"Wie viele Milliarden Dollar wert ist der globale Markt für KI-Chips?",a:100,unit:"Milliarden Dollar",hint:"Nvidia dominiert mit seinen GPUs.",emoji:"💻"}
];
