// 🌍 GESCHICHTE & KURIOSITÄTEN – Erwachsene – 250 Fragen
export default [
  {id:"hist_001",q:"In welchem Jahr wurde das erste Brustimplantat einoperiert?",a:1962,unit:"Jahr",hint:"Timmie Jean Lindsey war die erste Frau weltweit.",emoji:"👙"},
  {id:"hist_002",q:"Wie viele Frauen hatte König Salomo laut Bibel?",a:700,unit:"Frauen",hint:"Dazu kamen noch 300 Konkubinen.",emoji:"👑"},
  {id:"hist_003",q:"In welchem Jahr wurde Viagra erfunden?",a:1998,unit:"Jahr",hint:"Ursprünglich als Herzmedikament entwickelt.",emoji:"💊"},
  {id:"hist_004",q:"Wie viele Millionen Menschen starben beim Schwarzen Tod?",a:50,unit:"Millionen",hint:"Ein Drittel der europäischen Bevölkerung im 14. Jh.",emoji:"💀"},
  {id:"hist_005",q:"In welchem Jahr wurde die Guillotine in Frankreich abgeschafft?",a:1981,unit:"Jahr",hint:"Letzte Hinrichtung war 1977.",emoji:"⚔️"},
  {id:"hist_006",q:"Wie viele Jahre war die Berliner Mauer in Betrieb?",a:28,unit:"Jahre",hint:"Von 1961 bis zum Fall am 9. November 1989.",emoji:"🧱"},
  {id:"hist_007",q:"In welchem Jahr wurde das erste Telefon von Bell patentiert?",a:1876,unit:"Jahr",hint:"Bell erhielt das Patent am 7. März 1876.",emoji:"📞"},
  {id:"hist_008",q:"Wie viele Arbeiter bauten schätzungsweise die Cheops-Pyramide?",a:20000,unit:"Arbeiter",hint:"Neuere Forschung: bezahlte Arbeiter, keine Sklaven.",emoji:"🏛️"},
  {id:"hist_009",q:"Wie viele Millionen Tonnen Gold sind schätzungsweise im Meer gelöst?",a:20,unit:"Millionen Tonnen",hint:"Genug für 9 Pfund Gold pro Person auf der Erde.",emoji:"⚱️"},
  {id:"hist_010",q:"In welchem Jahr wurde die erste Kondom-Fabrik eröffnet?",a:1844,unit:"Jahr",hint:"Nach Goodyears Vulkanisierung von Gummi.",emoji:"💊"},
  {id:"hist_011",q:"Wie viele Konkubinen hatte Kaiser Qianlong von China?",a:3000,unit:"Konkubinen",hint:"Er regierte von 1735 bis 1796.",emoji:"👑"},
  {id:"hist_012",q:"Wie viele Jahre dauerte der Hundertjährige Krieg tatsächlich?",a:116,unit:"Jahre",hint:"Von 1337 bis 1453 – also 116 Jahre, nicht 100.",emoji:"⚔️"},
  {id:"hist_013",q:"Wie viele Personen wurden beim Hexenprozess von Salem hingerichtet?",a:19,unit:"Personen",hint:"1692 in Massachusetts.",emoji:"🔥"},
  {id:"hist_014",q:"In welchem Jahr erfand Nicolas Appert die Konservierung in Dosen?",a:1810,unit:"Jahr",hint:"Napoleon schrieb den Preis aus – Appert gewann ihn 1810.",emoji:"🥫"},
  {id:"hist_015",q:"Wie viele Minuten dauerte der kürzeste Krieg der Geschichte?",a:38,unit:"Minuten",hint:"Der Anglo-Sansibar-Krieg von 1896.",emoji:"⚔️"},
  {id:"hist_016",q:"Wie viele Jahre saß Nelson Mandela im Gefängnis?",a:27,unit:"Jahre",hint:"Von 1964 bis 1990 auf Robben Island.",emoji:"✊"},
  {id:"hist_017",q:"In welchem Jahr fand die erste Mondlandung statt?",a:1969,unit:"Jahr",hint:"Apollo 11, 20. Juli 1969.",emoji:"🌙"},
  {id:"hist_018",q:"In welchem Jahr wurde die Titanic gebaut (Baubeginn)?",a:1909,unit:"Jahr",hint:"Sie sank bei ihrer Jungfernfahrt 1912.",emoji:"🚢"},
  {id:"hist_019",q:"Wie viele Millionen Menschen starben im Ersten Weltkrieg?",a:20,unit:"Millionen",hint:"Militär und Zivilbevölkerung zusammen.",emoji:"🕊️"},
  {id:"hist_020",q:"Wie viele Jahre regierte Queen Elizabeth II.?",a:70,unit:"Jahre",hint:"Von 1952 bis zu ihrem Tod 2022.",emoji:"👑"},
  {id:"hist_021",q:"In welchem Jahr erfand Karl Benz das erste Automobil?",a:1885,unit:"Jahr",hint:"Der Benz Patent-Motorwagen – drei Räder, 0,75 PS.",emoji:"🚗"},
  {id:"hist_022",q:"Wie viele Stockwerke hatte das World Trade Center?",a:110,unit:"Stockwerke",hint:"Die Zwillingstürme wurden am 11. September 2001 zerstört.",emoji:"🏙️"},
  {id:"hist_023",q:"Wie viele Jahre dauerte der Zweite Weltkrieg?",a:6,unit:"Jahre",hint:"Von 1939 bis 1945.",emoji:"🌍"},
  {id:"hist_024",q:"In welchem Jahr wurde die erste Atombombe gezündet?",a:1945,unit:"Jahr",hint:"Trinity-Test in New Mexico, 16. Juli 1945.",emoji:"💥"},
  {id:"hist_025",q:"Wie viele Milliarden Menschen lebten auf der Erde im Jahr 1800?",a:1,unit:"Milliarden Menschen",hint:"Eine Milliarde – heute sind es 8 Milliarden.",emoji:"🌍"},
  {id:"hist_026",q:"Wie viele Mal wurde Napoleon verbannt?",a:2,unit:"Mal",hint:"Erst nach Elba, dann nach St. Helena.",emoji:"🏝️"},
  {id:"hist_027",q:"In welchem Jahr fiel die Mauer in Berlin?",a:1989,unit:"Jahr",hint:"9. November 1989 – einer der wichtigsten Tage der Geschichte.",emoji:"🧱"},
  {id:"hist_028",q:"Wie viele Millionen Juden wurden im Holocaust ermordet?",a:6,unit:"Millionen",hint:"Einer der dunkelsten Momente der Menschheitsgeschichte.",emoji:"✡️"},
  {id:"hist_029",q:"In welchem Jahr wurde das Internet erfunden (ARPANET)?",a:1969,unit:"Jahr",hint:"Das erste Netzwerk übertrug 1969 Daten.",emoji:"🌐"},
  {id:"hist_030",q:"Wie viele Millionen Afrikaner wurden im transatlantischen Sklavenhandel verschleppt?",a:12,unit:"Millionen Menschen",hint:"12 Millionen Afrikaner wurden zwischen 1500 und 1900 verschleppt.",emoji:"⛓️"},
  {id:"hist_031",q:"In welchem Jahr landete Kolumbus in Amerika?",a:1492,unit:"Jahr",hint:"Am 12. Oktober 1492 betrat er San Salvador.",emoji:"⛵"},
  {id:"hist_032",q:"Wie viele Bücher der Bibel gibt es?",a:66,unit:"Bücher",hint:"39 im Alten, 27 im Neuen Testament.",emoji:"📖"},
  {id:"hist_033",q:"Wie viele Millionen Menschen starben in der Spanischen Grippe?",a:50,unit:"Millionen",hint:"1918-1920 – schlimmer als der Erste Weltkrieg.",emoji:"😷"},
  {id:"hist_034",q:"In welchem Jahr wurde die Magna Carta unterzeichnet?",a:1215,unit:"Jahr",hint:"König Johann ohne Land unterschrieb die erste Verfassung.",emoji:"📜"},
  {id:"hist_035",q:"Wie viele Götter hatte das alte Ägypten?",a:2000,unit:"Götter",hint:"Das ägyptische Pantheon war riesig.",emoji:"🏛️"},
  {id:"hist_036",q:"In welchem Jahr erfand Gutenberg den Buchdruck?",a:1450,unit:"Jahr",hint:"Die Druckpresse veränderte die Welt.",emoji:"📚"},
  {id:"hist_037",q:"Wie viele Jahre regierte das Römische Reich insgesamt?",a:503,unit:"Jahre",hint:"Vom Stadtgründungsdatum 27 v.Chr. bis 476 n.Chr.",emoji:"🏛️"},
  {id:"hist_038",q:"Wie viele Kilogramm Gold enthielt der Schatz von Tutanchamun?",a:110,unit:"kg Gold",hint:"Kg pures Gold im Sarkophag.",emoji:"🪙"},
  {id:"hist_039",q:"In welchem Jahr gab es die erste Zeitung?",a:1605,unit:"Jahr",hint:"'Relation' wurde 1605 in Straßburg gedruckt.",emoji:"📰"},
  {id:"hist_040",q:"Wie viele Millionen Menschen lebten zur Zeit Jesu auf der Erde?",a:300,unit:"Millionen Menschen",hint:"300 Millionen um das Jahr 0.",emoji:"🌍"},
  {id:"hist_041",q:"Wie viele Seiten umfasst die längste erhaltene Rechtskodex (Hammurabi)?",a:282,unit:"Paragraphen",hint:"Hammurabi regierte Babylon 1792-1750 v.Chr (Stand ~2024).",emoji:"📜"},
  {id:"hist_042",q:"In welchem Jahr wurde Stonehenge gebaut?",a:3100,unit:"v.Chr.",hint:"Die ältesten Steine wurden um 3100 v.Chr. aufgestellt.",emoji:"🗿"},
  {id:"hist_043",q:"Wie viele Sklaven besaß George Washington?",a:317,unit:"Sklaven",hint:"Bei seinem Tod besaß er 317 Sklaven.",emoji:"⛓️"},
  {id:"hist_044",q:"Wie viele Tausend Menschen wurden beim Massaker von Nanjing getötet?",a:300,unit:"Tausend",hint:"1937 töteten japanische Truppen bis zu 300.000 Chinesen.",emoji:"☮️"},
  {id:"hist_045",q:"In welchem Jahr fand das letzte öffentliche Hinrichtung in Frankreich statt?",a:1939,unit:"Jahr",hint:"Eugen Weidmann war der letzte öffentlich Hingerichtete.",emoji:"⚔️"},
  {id:"hist_046",q:"Wie viele Jahre dauerte die Inquisition der Katholischen Kirche?",a:600,unit:"Jahre",hint:"Von 1184 bis 1820.",emoji:"🔥"},
  {id:"hist_047",q:"Wie viele Nationen nahmen am Zweiten Weltkrieg teil?",a:30,unit:"Nationen",hint:"Auf beiden Seiten zusammen über 30 Länder.",emoji:"🌍"},
  {id:"hist_048",q:"In welchem Jahr begann die Französische Revolution?",a:1789,unit:"Jahr",hint:"Mit dem Sturm auf die Bastille am 14. Juli.",emoji:"🗽"},
  {id:"hist_049",q:"Wie viele Tausend Personen wurden während der Französischen Revolution guillotiniert?",a:16.5,unit:"Tausend",hint:"Etwa 16.500 – davon 2.600 allein in Paris.",emoji:"⚔️"},
  {id:"hist_050",q:"Wie viele Millionen Menschen lebten im Römischen Reich?",a:65,unit:"Millionen",hint:"Im 2. Jahrhundert n.Chr. auf dem Höhepunkt.",emoji:"🏛️"},
  {id:"hist_051",q:"In welchem Jahr erfand Edison die Glühbirne?",a:1879,unit:"Jahr",hint:"Am 22. Oktober 1879 leuchtete sie 13,5 Stunden.",emoji:"💡"},
  {id:"hist_052",q:"Wie viele Frauen haben je eine vollständige Legislaturperiode als Staatschef abgeschlossen?",a:60,unit:"Frauen",hint:"Über 60 Frauen haben ein Land regiert.",emoji:"👩"},
  {id:"hist_053",q:"Wie viele Jahre dauerte die Sklaverei in den USA legal?",a:246,unit:"Jahre",hint:"Von 1619 bis zur Abschaffung 1865.",emoji:"⛓️"},
  {id:"hist_054",q:"In welchem Jahr begann der Erste Kreuzzug?",a:1096,unit:"Jahr",hint:"Papst Urban II. rief dazu auf.",emoji:"⚔️"},
  {id:"hist_055",q:"Wie viele Personen überlebten den Untergang der Titanic?",a:710,unit:"Personen",hint:"Von 2224 Bordpersonen.",emoji:"🚢"},
  {id:"hist_056",q:"Wie viele Jahre dauerte die Berliner Luftbrücke?",a:1,unit:"Jahr",hint:"Juni 1948 bis Mai 1949.",emoji:"✈️"},
  {id:"hist_057",q:"Wie viele Millionen Menschen starben in der Hungersnot in Irland?",a:1,unit:"Million",hint:"1845-1852 starben über 1 Million Iren.",emoji:"🥔"},
  {id:"hist_058",q:"In welchem Jahr erfand Fleming Penicillin?",a:1928,unit:"Jahr",hint:"Alexander Fleming entdeckte es zufällig.",emoji:"💊"},
  {id:"hist_059",q:"Wie viele Generäle hatte Napoleon in seinem Heer?",a:300,unit:"Generäle",hint:"Napoleon hatte das modernste Offizierskorps seiner Zeit.",emoji:"⚔️"},
  {id:"hist_060",q:"In welchem Jahr wurde die erste Dampfmaschine gebaut?",a:1712,unit:"Jahr",hint:"Thomas Newcomen baute die erste praktische Dampfmaschine.",emoji:"🔧"},
  {id:"hist_061",q:"Wie viele Männer haben auf dem Mond gestanden?",a:12,unit:"Männer",hint:"Alle 12 waren Amerikaner – alle Apollo-Missionen.",emoji:"🌙"},
  {id:"hist_062",q:"Wie viele Jahre regierte Cleopatra Ägypten?",a:21,unit:"Jahre",hint:"Von 51 v.Chr. bis zu ihrem Tod 30 v.Chr.",emoji:"👑"},
  {id:"hist_063",q:"In welchem Jahr wurde das erste Foto aufgenommen?",a:1826,unit:"Jahr",hint:"Joseph Nicéphore Niépce machte die älteste erhaltene Aufnahme.",emoji:"📷"},
  {id:"hist_064",q:"Wie viele Millionen Menschen tötete Stalin?",a:20,unit:"Millionen",hint:"Schätzungen variieren zwischen 6 und 20 Millionen.",emoji:"☭"},
  {id:"hist_065",q:"In welchem Jahr erfand Wright Brothers das Flugzeug?",a:1903,unit:"Jahr",hint:"Am 17. Dezember 1903 flog Orville 12 Sekunden.",emoji:"✈️"},
  {id:"hist_066",q:"Wie viele Tausend Personen starben beim Bau des Panamakanals?",a:27.5,unit:"Tausend",hint:"Malaria, Gelbfieber und Unfälle.",emoji:"⚒️"},
  {id:"hist_067",q:"Wie viele Jahre baute man am Kölner Dom?",a:632,unit:"Jahre",hint:"Von 1248 bis zur Vollendung 1880.",emoji:"⛪"},
  {id:"hist_068",q:"Wie viele Tausend Menschen starben bei der Atombombe in Hiroshima?",a:140,unit:"Tausend",hint:"Bis Ende 1945 starben etwa 140.000 Menschen an den Folgen.",emoji:"💥"},
  {id:"hist_069",q:"In welchem Jahr fand die Oktoberrevolution statt?",a:1917,unit:"Jahr",hint:"Am 7. November 1917 stürmten Bolschewiken den Winterpalast.",emoji:"☭"},
  {id:"hist_070",q:"Wie viele Nationen unterzeichneten die UN-Charta?",a:51,unit:"Nationen",hint:"Bei Gründung 1945 – heute 193.",emoji:"🌍"},
  {id:"hist_071",q:"In welchem Jahr verlor Deutschland den Ersten Weltkrieg?",a:1918,unit:"Jahr",hint:"Waffenstillstand am 11. November 1918.",emoji:"🕊️"},
  {id:"hist_072",q:"Wie viele Stockwerke hat der Eiffelturm?",a:3,unit:"Etagen",hint:"Mit drei Aussichtsplattformen.",emoji:"🗼"},
  {id:"hist_073",q:"In welchem Jahr wurde die Unabhängigkeitserklärung der USA unterzeichnet?",a:1776,unit:"Jahr",hint:"Am 4. Juli 1776.",emoji:"🗽"},
  {id:"hist_074",q:"Wie viele Jahre lebte Leonardo da Vinci?",a:67,unit:"Jahre",hint:"1452-1519 – Universalgenie der Renaissance.",emoji:"🎨"},
  {id:"hist_075",q:"In welchem Jahr erfand Tesla die Wechselstrom-Übertragung?",a:1888,unit:"Jahr",hint:"Der Kampf gegen Edison begann.",emoji:"⚡"},
  {id:"hist_076",q:"Wie viele Nationen nahmen an der Unterzeichnung des Versailler Vertrags teil?",a:27,unit:"Nationen",hint:"1919 nach dem Ersten Weltkrieg.",emoji:"📜"},
  {id:"hist_077",q:"In welchem Jahr erfand Marconi das Radio?",a:1896,unit:"Jahr",hint:"Guglielmo Marconi meldete 1896 sein Patent an.",emoji:"📻"},
  {id:"hist_078",q:"Wie viele Personen wurden in der Bartholomäusnacht getötet?",a:30000,unit:"Personen",hint:"1572 – Massaker an Hugenotten in Frankreich.",emoji:"🔥"},
  {id:"hist_079",q:"In welchem Jahr erschoss ein Serbe den österreichischen Kronprinzen?",a:1914,unit:"Jahr",hint:"Gavrilo Princip erschoss Franz Ferdinand.",emoji:"💣"},
  {id:"hist_080",q:"Wie viele km lang ist der Suezkanal?",a:193,unit:"km",hint:"Verbindet das Mittelmeer mit dem Roten Meer.",emoji:"⛵"},
  {id:"hist_081",q:"In welchem Jahr wurde die Berliner Mauer gebaut?",a:1961,unit:"Jahr",hint:"Am 13. August 1961 begann der Bau.",emoji:"🧱"},
  {id:"hist_082",q:"Wie viele Jahre existierte das Dritte Reich?",a:12,unit:"Jahre",hint:"Von 1933 bis 1945.",emoji:"☮️"},
  {id:"hist_083",q:"In welchem Jahr wurde die NATO gegründet?",a:1949,unit:"Jahr",hint:"Am 4. April 1949 in Washington.",emoji:"🌍"},
  {id:"hist_084",q:"Wie viele Millionen Soldaten starben im Zweiten Weltkrieg?",a:25,unit:"Millionen",hint:"Zivile Opfer waren mit ~50 Mio. noch mehr.",emoji:"🕊️"},
  {id:"hist_085",q:"In welchem Jahr wurde das erste Konzentrationslager eröffnet?",a:1933,unit:"Jahr",hint:"Dachau wurde am 22. März 1933 eröffnet.",emoji:"☮️"},
  {id:"hist_086",q:"Wie viele Tage dauerte die Belagerung von Stalingrad?",a:160,unit:"Tage",hint:"Von August 1942 bis Februar 1943.",emoji:"⚔️"},
  {id:"hist_087",q:"In welchem Jahr wurde die EU gegründet?",a:1993,unit:"Jahr",hint:"Der Maastricht-Vertrag trat am 1. November 1993 in Kraft.",emoji:"🇪🇺"},
  {id:"hist_088",q:"Wie viele Länder gehörten zur Sowjetunion?",a:15,unit:"Länder",hint:"Die UdSSR löste sich 1991 auf.",emoji:"☭"},
  {id:"hist_089",q:"In welchem Jahr entdeckte Newton die Schwerkraft?",a:1666,unit:"Jahr",hint:"Der Apfel fiel – die Legende begann.",emoji:"🍎"},
  {id:"hist_090",q:"Wie viele Personen wurden in der Nacht der langen Messer ermordet?",a:85,unit:"Personen",hint:"1934 – Hitler ließ SA-Führer und politische Gegner töten.",emoji:"🔪"},
  {id:"hist_091",q:"In welchem Jahr erfand Pasteur die Pasteurisierung?",a:1864,unit:"Jahr",hint:"Louis Pasteur entwickelte sie für Wein.",emoji:"🧪"},
  {id:"hist_092",q:"Wie viele km lang war der Westwall im Zweiten Weltkrieg?",a:630,unit:"km",hint:"Deutschlands Befestigungslinie an der Westgrenze.",emoji:"⚔️"},
  {id:"hist_093",q:"In welchem Jahr wurde der Euro eingeführt?",a:1999,unit:"Jahr",hint:"Als Buchgeld – als Bargeld ab 2002.",emoji:"💶"},
  {id:"hist_094",q:"Wie viele Tausend Personen starben beim Erdbeben von Lissabon 1755?",a:60,unit:"Tausend",hint:"1755 – eines der schlimmsten Erdbeben Europas.",emoji:"🌋"},
  {id:"hist_095",q:"In welchem Jahr gründete Hitler die NSDAP?",a:1919,unit:"Jahr",hint:"Als DAP – in NSDAP umbenannt 1920.",emoji:"☮️"},
  {id:"hist_096",q:"Wie viele Jahre dauerte die Reformation?",a:50,unit:"Jahre",hint:"Von Luthers Thesenanschlag 1517 bis etwa 1570.",emoji:"⛪"},
  {id:"hist_097",q:"In welchem Jahr wurde der Eiffelturm fertiggestellt?",a:1889,unit:"Jahr",hint:"Für die Weltausstellung in Paris.",emoji:"🗼"},
  {id:"hist_098",q:"Wie viele Millionen Menschen starben in der Ukrainischen Hungersnot (Holodomor)?",a:4,unit:"Millionen",hint:"1932-1933 – vom Sowjet-Regime verursacht.",emoji:"🌾"},
  {id:"hist_099",q:"In welchem Jahr begann der Koreakrieg?",a:1950,unit:"Jahr",hint:"Am 25. Juni 1950.",emoji:"⚔️"},
  {id:"hist_100",q:"Wie viele km lang war die Ostfront im Zweiten Weltkrieg?",a:4000,unit:"km",hint:"Die längste Front der Kriegsgeschichte.",emoji:"⚔️"},
  {id:"hist_101",q:"In welchem Jahr erfand Tesla die Neonröhre?",a:1891,unit:"Jahr",hint:"Tesla demonstrierte seine drahtlosen Lampen.",emoji:"💡"},
  {id:"hist_102",q:"Wie viele Seiten umfasst Hitlers Mein Kampf?",a:782,unit:"Seiten",hint:"Geschrieben während seiner Haftzeit 1924-1925.",emoji:"📖"},
  {id:"hist_103",q:"In welchem Jahr wurde Deutschland geteilt?",a:1949,unit:"Jahr",hint:"BRD und DDR entstanden 1949.",emoji:"🧱"},
  {id:"hist_104",q:"Wie viele Länder invadierte das Britische Empire?",a:171,unit:"Länder",hint:"Fast die ganze Welt – nur 22 Länder nie.",emoji:"🗺️"},
  {id:"hist_105",q:"In welchem Jahr erfand Nobel das Dynamit?",a:1867,unit:"Jahr",hint:"Alfred Nobel patentierte es 1867.",emoji:"💣"},
  {id:"hist_106",q:"In welchem Jahr wurde die UNO gegründet?",a:1945,unit:"Jahr",hint:"Am 24. Oktober 1945 – der UN-Tag.",emoji:"🌍"},
  {id:"hist_107",q:"Wie viele km lang war die Chinesische Mauer als sie vollständig war?",a:21196,unit:"km",hint:"Inklusive aller Seiten und Verzweigungen.",emoji:"🧱"},
  {id:"hist_108",q:"In welchem Jahr verbrannte Joan of Arc?",a:1431,unit:"Jahr",hint:"Am 30. Mai 1431 in Rouen.",emoji:"🔥"},
  {id:"hist_109",q:"Wie viele Millionen Menschen starben weltweit an der Pest im 14. Jahrhundert?",a:75,unit:"Millionen",hint:"Ein Drittel der Weltbevölkerung – in Europa ~50 Mio.",emoji:"💀"},
  {id:"hist_110",q:"In welchem Jahr erfand Daimler den Verbrennungsmotor?",a:1885,unit:"Jahr",hint:"Benz und Daimler erfanden unabhängig voneinander.",emoji:"🚗"},
  {id:"hist_111",q:"In welchem Jahr begann der Vietnamkrieg (US-Beteiligung)?",a:1965,unit:"Jahr",hint:"Die USA griffen direkt 1965 ein.",emoji:"✈️"},
  {id:"hist_112",q:"Wie viele Millionen Menschen starben im Mongolenreich?",a:40,unit:"Millionen",hint:"Dschingis Khans Feldzüge töteten Millionen.",emoji:"⚔️"},
  {id:"hist_113",q:"In welchem Jahr wurde das erste Konzentrationslager in Ausschwitz gebaut?",a:1940,unit:"Jahr",hint:"Auschwitz I wurde 1940 eröffnet.",emoji:"☮️"},
  {id:"hist_114",q:"Wie viele Personen starben auf der Titanic?",a:1514,unit:"Personen",hint:"Von 2224 Personen an Bord.",emoji:"🚢"},
  {id:"hist_115",q:"In welchem Jahr wurde die Atombombe auf Hiroshima abgeworfen?",a:1945,unit:"Jahr",hint:"Am 6. August 1945.",emoji:"💥"},
  {id:"hist_116",q:"Wie viele Stockwerke hatte der Turm von Babel laut Bibel?",a:7,unit:"Etagen",hint:"Eine Zikkurat mit 7 Stufen.",emoji:"🏛️"},
  {id:"hist_117",q:"In welchem Jahr begann die Reformation durch Martin Luther?",a:1517,unit:"Jahr",hint:"Mit dem Thesenanschlag am 31. Oktober.",emoji:"⛪"},
  {id:"hist_118",q:"Wie viele Millionen Menschen starben im Dreißigjährigen Krieg?",a:8,unit:"Millionen",hint:"Ein Drittel der deutschen Bevölkerung.",emoji:"⚔️"},
  {id:"hist_119",q:"In welchem Jahr wurde der Panamakanal eröffnet?",a:1914,unit:"Jahr",hint:"Am 15. August 1914.",emoji:"⛵"},
  {id:"hist_120",q:"Wie viele km lang ist die Transsibirische Eisenbahn?",a:9289,unit:"km",hint:"Die längste Eisenbahnstrecke der Welt.",emoji:"🚂"},
  {id:"hist_121",q:"In welchem Jahr begann der Kalte Krieg?",a:1947,unit:"Jahr",hint:"Mit der Truman-Doktrin im März 1947.",emoji:"☭"},
  {id:"hist_122",q:"Wie viele Tausend Sklaven wurden in die USA importiert?",a:400,unit:"Tausend",hint:"400.000 direkte Importe – heute über 40 Mio. Nachkommen.",emoji:"⛓️"},
  {id:"hist_123",q:"In welchem Jahr fiel der Eiserne Vorhang?",a:1989,unit:"Jahr",hint:"Öffneten sich die Grenzen.",emoji:"🧱"},
  {id:"hist_124",q:"Wie viele Jahre dauerte der Dreißigjährige Krieg?",a:30,unit:"Jahre",hint:"Von 1618 bis 1648.",emoji:"⚔️"},
  {id:"hist_125",q:"In welchem Jahr wurde das erste Automobile öffentlich vorgestellt?",a:1886,unit:"Jahr",hint:"Bertha Benz fuhr die erste Langstrecke.",emoji:"🚗"},
  {id:"hist_126",q:"In welchem Jahr erfand Morse den Morsecode?",a:1838,unit:"Jahr",hint:"Samuel Morse demonstrierte ihn 1838.",emoji:"📡"},
  {id:"hist_127",q:"Wie viele Sprachen spricht die UNO offiziell?",a:6,unit:"Sprachen",hint:"Arabisch, Chinesisch, Englisch, Französisch, Russisch, Spanisch.",emoji:"🌍"},
  {id:"hist_128",q:"In welchem Jahr begann die Entdeckung Amerikas durch Vikinger?",a:1000,unit:"Jahr",hint:"Leif Eriksson erreichte Nordamerika um 1000 n.Chr.",emoji:"⛵"},
  {id:"hist_129",q:"Wie viele km lang ist der Amazonas in Südamerika?",a:6400,unit:"km",hint:"Einer der längsten Flüsse der Welt.",emoji:"🌿"},
  {id:"hist_130",q:"In welchem Jahr wurde das erste Parlament gegründet (Island)?",a:930,unit:"Jahr",hint:"Das Althing in Island – ältestes Parlament der Welt.",emoji:"📜"},
  {id:"hist_131",q:"In welchem Jahr wurde die Berliner Mauer offiziell abgerissen?",a:1990,unit:"Jahr",hint:"Der offizielle Abriss begann 1990.",emoji:"🧱"},
  {id:"hist_132",q:"Wie viele Kapitel hat das Alte Testament?",a:929,unit:"Kapitel",hint:"Kapitel im Alten Testament.",emoji:"📖"},
  {id:"hist_133",q:"In welchem Jahr erfand Semmelweis das Händewaschen?",a:1847,unit:"Jahr",hint:"Er rettete Menschenleben – wurde dafür aber verlacht.",emoji:"🧼"},
  {id:"hist_134",q:"Wie viele Millionen Menschen starben in Chinas Großem Sprung nach vorn?",a:45,unit:"Millionen",hint:"Maos Hungersnot 1959-1961.",emoji:"🌾"},
  {id:"hist_135",q:"In welchem Jahr wurde das erste Frauenwahlrecht eingeführt (Neuseeland)?",a:1893,unit:"Jahr",hint:"Neuseeland war das erste Land weltweit.",emoji:"🗳️"},
  {id:"hist_136",q:"Wie viele Jahre dauerte der Peloponnesische Krieg?",a:27,unit:"Jahre",hint:"Athen gegen Sparta, 431-404 v.Chr.",emoji:"⚔️"},
  {id:"hist_137",q:"In welchem Jahr wurde Saddam Hussein hingerichtet?",a:2006,unit:"Jahr",hint:"Am 30. Dezember 2006.",emoji:"☮️"},
  {id:"hist_138",q:"Wie viele Millionen Menschen tötete Pol Pot in Kambodscha?",a:2,unit:"Millionen",hint:"Ein Viertel der Bevölkerung Kambodschas.",emoji:"☮️"},
  {id:"hist_139",q:"In welchem Jahr begann der Irakkrieg?",a:2003,unit:"Jahr",hint:"Am 20. März 2003 begann die US-Invasion.",emoji:"⚔️"},
  {id:"hist_140",q:"Wie viele Millionen Menschen waren bei D-Day beteiligt?",a:3,unit:"Millionen",hint:"Millionen Alliierte planten die Invasion.",emoji:"⚔️"},
  {id:"hist_141",q:"In welchem Jahr wurde der Erste Computer (ENIAC) gebaut?",a:1945,unit:"Jahr",hint:"ENIAC füllte einen ganzen Raum.",emoji:"💻"},
  {id:"hist_142",q:"Wie viele Nationen unterzeichneten den Kyoto-Protokoll?",a:192,unit:"Nationen",hint:"Fast alle Länder der Welt.",emoji:"🌍"},
  {id:"hist_143",q:"In welchem Jahr erfand Levi Strauss die Jeans?",a:1873,unit:"Jahr",hint:"Für Goldgräber in Kalifornien.",emoji:"👖"},
  {id:"hist_144",q:"Wie viele Personen starben beim Attentat auf Abraham Lincoln?",a:1,unit:"Person",hint:"Lincoln selbst – der Attentäter floh zunächst.",emoji:"🎩"},
  {id:"hist_145",q:"In welchem Jahr endete der Koreakrieg?",a:1953,unit:"Jahr",hint:"Mit einem Waffenstillstand – kein Friedensvertrag.",emoji:"🕊️"},
  {id:"hist_146",q:"Wie viele Millionen Flüchtlinge gab es nach dem Zweiten Weltkrieg?",a:50,unit:"Millionen",hint:"Die größte Flüchtlingsbewegung der Geschichte.",emoji:"🚶"},
  {id:"hist_147",q:"In welchem Jahr wurde das Frauenwahlrecht in Deutschland eingeführt?",a:1918,unit:"Jahr",hint:"Nach dem Ersten Weltkrieg.",emoji:"🗳️"},
  {id:"hist_148",q:"Wie viele Jahre saß Mandela im Gefängnis auf Robben Island?",a:18,unit:"Jahre",hint:"Von 27 Jahren Gesamtstrafe.",emoji:"✊"},
  {id:"hist_149",q:"In welchem Jahr landete der erste Mensch auf dem Mars?",a:9999,unit:"(noch nicht)",hint:"Stand 2025 ist es noch kein Mensch auf dem Mars gelandet.",emoji:"🔴"},
  {id:"hist_150",q:"Wie viele Personen haben die ISS besucht?",a:250,unit:"Personen",hint:"Über 250 Menschen aus 20 Ländern.",emoji:"🚀"},
  {id:"hist_151",q:"In welchem Jahr wurde das erste iPhone vorgestellt?",a:2007,unit:"Jahr",hint:"Steve Jobs präsentierte es am 9. Januar 2007.",emoji:"📱"},
  {id:"hist_152",q:"Wie viele Milliarden Menschen nutzen das Internet?",a:5,unit:"Milliarden",hint:"Über 60% der Weltbevölkerung.",emoji:"🌐"},
  {id:"hist_153",q:"In welchem Jahr wurde Facebook gegründet?",a:2004,unit:"Jahr",hint:"Mark Zuckerberg gründete es als Harvard-Student.",emoji:"📱"},
  {id:"hist_154",q:"Wie viele Millionen Jahre hat der Mensch das Feuer genutzt?",a:1,unit:"Millionen Jahre",hint:"Erste Belege für Feuer vor 1 Million Jahren.",emoji:"🔥"},
  {id:"hist_155",q:"In welchem Jahr erfand Archimedes sein Prinzip?",a:250,unit:"v.Chr.",hint:"Archimedes rief 'Heureka!' in seiner Badewanne.",emoji:"🛁"},
  {id:"hist_156",q:"Wie viele Tausend Tonnen Gold wurden in der Geschichte abgebaut?",a:190,unit:"Tausend Tonnen",hint:"190.000 Tonnen – alles je abgebaute Gold würde in 3 Olympia-Schwimmbecken passen.",emoji:"🪙"},
  {id:"hist_157",q:"In welchem Jahr erfand Pasteur den Impfstoff gegen Tollwut?",a:1885,unit:"Jahr",hint:"Die erste erfolgreiche Tollwutimpfung.",emoji:"💉"},
  {id:"hist_158",q:"Wie viele Personen haben je den Nobelpreis erhalten?",a:950,unit:"Personen",hint:"Manche Preisträger haben ihn zweimal bekommen.",emoji:"🏆"},
  {id:"hist_159",q:"In welchem Jahr erfand Röntgen die Röntgenstrahlen?",a:1895,unit:"Jahr",hint:"Am 8. November 1895 entdeckte er sie zufällig.",emoji:"🩻"},
  {id:"hist_160",q:"Wie viele Länder beteiligten sich am Ersten Weltkrieg?",a:30,unit:"Länder",hint:"Auf beiden Seiten zusammen.",emoji:"⚔️"},
  {id:"hist_161",q:"In welchem Jahr gründete Hitler die SS?",a:1925,unit:"Jahr",hint:"Als persönliche Leibwache, später Terrorapparat.",emoji:"☮️"},
  {id:"hist_162",q:"Wie viele Millionen Tonnen Sprengstoff wurden im Zweiten Weltkrieg verwendet?",a:5,unit:"Millionen Tonnen",hint:"Der Zweite Weltkrieg übertraf den Ersten bei weitem.",emoji:"💣"},
  {id:"hist_163",q:"In welchem Jahr erfand Curie das Radium?",a:1898,unit:"Jahr",hint:"Marie und Pierre Curie entdeckten Polonium und Radium.",emoji:"☢️"},
  {id:"hist_164",q:"Wie viele Jahre alt ist das älteste bekannte Schriftsystem?",a:5500,unit:"Jahre",hint:"Sumerische Keilschrift aus Mesopotamien (Stand ~2024).",emoji:"📜"},
  {id:"hist_165",q:"In welchem Jahr begann der Amerikanische Bürgerkrieg?",a:1861,unit:"Jahr",hint:"Am 12. April 1861 mit der Beschießung Fort Sumters.",emoji:"⚔️"},
  {id:"hist_166",q:"Wie viele Tausend Menschen starben im Amerikanischen Bürgerkrieg?",a:750,unit:"Tausend",hint:"750.000 – der verlustreichste Krieg in der Geschichte der USA.",emoji:"⚔️"},
  {id:"hist_167",q:"In welchem Jahr wurde das erste Kernkraftwerk gebaut?",a:1954,unit:"Jahr",hint:"Obninsk in der Sowjetunion, 1954.",emoji:"⚡"},
  {id:"hist_168",q:"Wie viele Atommächte gibt es offiziell?",a:9,unit:"Länder",hint:"USA, Russland, UK, Frankreich, China, Indien, Pakistan, Israel, Nordkorea.",emoji:"☢️"},
  {id:"hist_169",q:"In welchem Jahr wurde das Konzentrationslager Auschwitz befreit?",a:1945,unit:"Jahr",hint:"Am 27. Januar 1945 durch sowjetische Truppen.",emoji:"☮️"},
  {id:"hist_170",q:"Wie viele Jahre war die UdSSR ein Staat?",a:69,unit:"Jahre",hint:"Von 1922 bis zur Auflösung 1991.",emoji:"☭"},
  {id:"hist_171",q:"In welchem Jahr gründete Truman die CIA?",a:1947,unit:"Jahr",hint:"Harry Truman unterzeichnete den National Security Act am 26. Juli 1947.",emoji:"🕵️"},
  {id:"hist_172",q:"Wie viele Tausend Tonnen werden jährlich in Atomkraftwerken verarbeitet?",a:70,unit:"Tausend Tonnen Uran",hint:"70.000 Tonnen Uran jährlich weltweit.",emoji:"⚡"},
  {id:"hist_173",q:"Wie viele Sprachen sprach Kleopatra?",a:9,unit:"Sprachen",hint:"Sie war die erste Ptolemäerin die Ägyptisch sprach.",emoji:"👑"},
  {id:"hist_174",q:"In welchem Jahr fand der erste Olympische Wettkampf statt?",a:776,unit:"v.Chr.",hint:"In Olympia, Griechenland.",emoji:"🏅"},
  {id:"hist_175",q:"Wie viele Meter hoch war das Kolosseum in Rom?",a:48,unit:"Meter",hint:"Das größte Amphitheater der Antike.",emoji:"🏛️"},
  {id:"hist_176",q:"In welchem Jahr wurde das erste U-Boot eingesetzt?",a:1776,unit:"Jahr",hint:"Die Turtle wurde im Amerikanischen Unabhängigkeitskrieg eingesetzt.",emoji:"🌊"},
  {id:"hist_177",q:"Wie viele km entfernt ist Karthago von Rom?",a:1500,unit:"km",hint:"Trotzdem kämpften sie drei Kriege lang.",emoji:"⚔️"},
  {id:"hist_178",q:"In welchem Jahr erfand Lister die Antisepsis?",a:1867,unit:"Jahr",hint:"Joseph Lister revolutionierte die Chirurgie.",emoji:"🏥"},
  {id:"hist_179",q:"Wie viele Personen wurden im Tower of London hingerichtet?",a:3000,unit:"Personen",hint:"Über 3000 Jahre Exekutionen.",emoji:"🏰"},
  {id:"hist_180",q:"In welchem Jahr baute Henry Ford das erste Fließband?",a:1913,unit:"Jahr",hint:"Die Massenproduktion begann in Detroit.",emoji:"🚗"},
  {id:"hist_181",q:"Wie viele Jahre regierte das Osmanische Reich?",a:623,unit:"Jahre",hint:"Von 1299 bis 1922.",emoji:"🌙"},
  {id:"hist_182",q:"In welchem Jahr erfand Morse den ersten Telegrafen?",a:1837,unit:"Jahr",hint:"Das erste elektrische Nachrichtensystem.",emoji:"📡"},
  {id:"hist_183",q:"Wie viele Tausend Personen starben bei der Bombardierung von Dresdens?",a:25,unit:"Tausend",hint:"Im Februar 1945.",emoji:"💥"},
  {id:"hist_184",q:"In welchem Jahr begann der Spanische Bürgerkrieg?",a:1936,unit:"Jahr",hint:"Franco gegen die Republik.",emoji:"⚔️"},
  {id:"hist_185",q:"Wie viele Jahre lang herrschte die Apartheid in Südafrika?",a:46,unit:"Jahre",hint:"Von 1948 bis zur Aufhebung 1994.",emoji:"✊"},
  {id:"hist_186",q:"In welchem Jahr erfand Freud die Psychoanalyse?",a:1899,unit:"Jahr",hint:"Mit der Veröffentlichung der Traumdeutung.",emoji:"🧠"},
  {id:"hist_187",q:"Wie viele Milliarden Dollar kostete das Manhattan-Projekt?",a:2,unit:"Milliarden Dollar",hint:"In heutiger Kaufkraft über 25 Milliarden.",emoji:"💣"},
  {id:"hist_188",q:"In welchem Jahr fand die Befreiung der KZs statt?",a:1945,unit:"Jahr",hint:"Mit dem Vormarsch der Alliierten.",emoji:"🕊️"},
  {id:"hist_189",q:"Wie viele km weit schoss die Pariser Kanone im Ersten Weltkrieg?",a:130,unit:"km",hint:"Konnte Paris vom deutschen Hinterland aus bombardieren.",emoji:"💣"},
  {id:"hist_190",q:"In welchem Jahr wurde die erste Weltkarte gezeichnet?",a:600,unit:"v.Chr.",hint:"Von Anaximander aus Milet.",emoji:"🗺️"},
  {id:"hist_191",q:"Wie viele Sprachen hat das Alte Testament ursprünglich?",a:3,unit:"Sprachen",hint:"Hebräisch, Aramäisch und Griechisch.",emoji:"📖"},
  {id:"hist_192",q:"In welchem Jahr erfand Pascal den Taschenrechner?",a:1642,unit:"Jahr",hint:"Die Pascaline konnte addieren und subtrahieren.",emoji:"🔢"},
  {id:"hist_193",q:"Wie viele Tausend Menschen lebten in Pompeji beim Ausbruch des Vesuvs?",a:10,unit:"Tausend",hint:"Ca. 10.000 Einwohner – viele entkamen rechtzeitig.",emoji:"🌋"},
  {id:"hist_194",q:"In welchem Jahr erfand Watt die Dampfmaschine (verbesserte Version)?",a:1769,unit:"Jahr",hint:"James Watt verbesserte Newcomens Version erheblich.",emoji:"⚙️"},
  {id:"hist_195",q:"Wie viele Tonnen wog das schwerste Schlachtschiff aller Zeiten (Yamato)?",a:72000,unit:"Tonnen",hint:"Das japanische Schlachtschiff Yamato (Stand ~2024).",emoji:"⛵"},
  {id:"hist_196",q:"In welchem Jahr wurde der erste Weltrat des Sports gegründet?",a:1896,unit:"Jahr",hint:"Die ersten modernen Olympischen Spiele 1896.",emoji:"🏅"},
  {id:"hist_197",q:"Wie viele Völker lebten im Römischen Reich?",a:50,unit:"Völker",hint:"Das Reich vereinte Dutzende Kulturen.",emoji:"🏛️"},
  {id:"hist_198",q:"In welchem Jahr erfand Galilei das Teleskop?",a:1609,unit:"Jahr",hint:"Er verbesserte ein niederländisches Modell.",emoji:"🔭"},
  {id:"hist_199",q:"Wie viele km lang war die Frontlinie bei Verdun?",a:30,unit:"km",hint:"Über 300 Tage dauerte die Schlacht.",emoji:"⚔️"},
  {id:"hist_200",q:"In welchem Jahr erfand Darwin die Evolutionstheorie?",a:1859,unit:"Jahr",hint:"Mit der Veröffentlichung von 'On the Origin of Species'.",emoji:"🔬"},
  {id:"hist_201",q:"Wie viele Millionen Sklaven starben auf der Überfahrt (Middle Passage)?",a:2,unit:"Millionen",hint:"15-20% aller Verschleppten starben auf See.",emoji:"⛓️"},
  {id:"hist_202",q:"In welchem Jahr begann der Peloponnesische Krieg?",a:431,unit:"v.Chr.",hint:"Athen gegen Sparta.",emoji:"⚔️"},
  {id:"hist_203",q:"Wie viele Jahre regierte Alexander der Große?",a:13,unit:"Jahre",hint:"Von 336 bis zu seinem Tod 323 v.Chr.",emoji:"⚔️"},
  {id:"hist_204",q:"In welchem Jahr erfand Einstein die Relativitätstheorie?",a:1905,unit:"Jahr",hint:"Das 'Annus Mirabilis' – Einstein veröffentlichte 4 Revolutionen.",emoji:"⚛️"},
  {id:"hist_205",q:"In welchem Jahr wurde der erste Satellit (Sputnik) gestartet?",a:1957,unit:"Jahr",hint:"Am 4. Oktober 1957.",emoji:"🛰️"},
  {id:"hist_206",q:"Wie viele Millionen Menschen besuchten die Weltausstellung 1889 in Paris?",a:32,unit:"Millionen",hint:"Mit dem Eiffelturm als Hauptattraktion.",emoji:"🗼"},
  {id:"hist_207",q:"Wie viele Personen saßen beim letzten Abendmahl?",a:13,unit:"Personen",hint:"Jesus und 12 Jünger.",emoji:"✝️"},
  {id:"hist_208",q:"In welchem Jahr wurde Deutschland (BRD) Mitglied der NATO?",a:1955,unit:"Jahr",hint:"Am 9. Mai 1955.",emoji:"🇩🇪"},
  {id:"hist_209",q:"Wie viele Millionen Tonnen CO₂ stieß die Welt 1900 aus?",a:2000,unit:"Millionen Tonnen",hint:"Heute sind es 37 Milliarden Tonnen.",emoji:"🌿"},
  {id:"hist_210",q:"In welchem Jahr wurde Karthago zerstört?",a:146,unit:"v.Chr.",hint:"Das dritte Punische Krieg endete mit der Vernichtung.",emoji:"🏛️"},
  {id:"hist_211",q:"Wie viele Millionen Menschen lebten zur Zeit Alexanders des Großen auf der Erde?",a:150,unit:"Millionen",hint:"Um 300 v.Chr. – Weltbevölkerung sehr viel kleiner.",emoji:"🌍"},
  {id:"hist_212",q:"In welchem Jahr wurde der Turm von London gebaut?",a:1078,unit:"Jahr",hint:"Wilhelm der Eroberer ließ ihn bauen.",emoji:"🏰"},
  {id:"hist_213",q:"Wie viele Jahre dauerte die mongolische Herrschaft über Russland?",a:240,unit:"Jahre",hint:"Das Mongolische Joch von 1240 bis 1480.",emoji:"⚔️"},
  {id:"hist_214",q:"In welchem Jahr fand die Uraufführung von Beethovens 9. Symphonie statt?",a:1824,unit:"Jahr",hint:"In Wien – Beethoven war damals taub.",emoji:"🎵"},
  {id:"hist_215",q:"Wie viele Tausend km lang war das Netz der Römerstraßen?",a:400,unit:"Tausend km",hint:"400.000 km Straßen verbanden das Imperium.",emoji:"🏛️"},
  {id:"hist_216",q:"In welchem Jahr erfand Franklin Blitzableiter?",a:1752,unit:"Jahr",hint:"Benjamin Franklin und sein berühmter Drachen.",emoji:"⚡"},
  {id:"hist_217",q:"Wie viele Gladiatorenkämpfe fanden im Kolosseum jährlich statt?",a:100,unit:"Tage",hint:"Bis zu 100 Spieltage im Jahr.",emoji:"⚔️"},
  {id:"hist_218",q:"In welchem Jahr wurde Österreich-Ungarn aufgelöst?",a:1918,unit:"Jahr",hint:"Ende des Ersten Weltkriegs.",emoji:"🗺️"},
  {id:"hist_219",q:"Wie viele Millionen Menschen waren in der Sklaverei in den USA 1860?",a:4,unit:"Millionen",hint:"Kurz vor dem Bürgerkrieg.",emoji:"⛓️"},
  {id:"hist_220",q:"In welchem Jahr begann der Vietnamkrieg für Vietnam?",a:1955,unit:"Jahr",hint:"US-Beteiligung ab 1965.",emoji:"🌿"},
  {id:"hist_221",q:"Wie viele Personen unterzeichneten die US-Unabhängigkeitserklärung?",a:56,unit:"Personen",hint:"Delegierte am 4. Juli 1776.",emoji:"📜"},
  {id:"hist_222",q:"In welchem Jahr wurde der Suezkanal eröffnet?",a:1869,unit:"Jahr",hint:"Am 17. November 1869.",emoji:"⛵"},
  {id:"hist_223",q:"Wie viele Millionen Menschen starben in Maos Kulturrevolution?",a:2,unit:"Millionen",hint:"Von 1966 bis 1976.",emoji:"☭"},
  {id:"hist_224",q:"In welchem Jahr entdeckte Marco Polo China?",a:1271,unit:"Jahr",hint:"Er reiste 17 Jahre durch Asien.",emoji:"🗺️"},
  {id:"hist_225",q:"Wie viele Jahre dauerte die Belagerung von Troja laut Homer?",a:10,unit:"Jahre",hint:"Der Trojanische Krieg.",emoji:"⚔️"},
  {id:"hist_226",q:"Wie viele Jahre regierte Kaiser Augustus?",a:44,unit:"Jahre",hint:"Von 27 v.Chr. bis 14 n.Chr.",emoji:"🏛️"},
  {id:"hist_227",q:"In welchem Jahr wurde Konstantinopel von den Osmanen eingenommen?",a:1453,unit:"Jahr",hint:"Ende des Byzantinischen Reiches.",emoji:"🌙"},
  {id:"hist_228",q:"Wie viele Tage dauerte das Massaker von My Lai im Vietnamkrieg?",a:1,unit:"Tag",hint:"Am 16. März 1968 – 504 Zivilisten getötet.",emoji:"☮️"},
  {id:"hist_229",q:"In welchem Jahr wurde der erste Motor-Flug versucht (Langley)?",a:1903,unit:"Jahr",hint:"Langley scheiterte kurz vor den Wrights.",emoji:"✈️"},
  {id:"hist_230",q:"Wie viele Millionen Iren emigrierten nach der Hungersnot?",a:1,unit:"Million",hint:"1845-1852 – neben 1 Mio. Toten.",emoji:"🌿"},
  {id:"hist_231",q:"In welchem Jahr wurde Argentinien unabhängig?",a:1816,unit:"Jahr",hint:"9. Juli 1816 – Unabhängigkeitstag.",emoji:"🇦🇷"},
  {id:"hist_232",q:"Wie viele Jahre regierte Dschingis Khan?",a:21,unit:"Jahre",hint:"Von 1206 bis zu seinem Tod 1227.",emoji:"⚔️"},
  {id:"hist_233",q:"Wie viele Tonnen Gold förderte das Römische Reich pro Jahr?",a:9,unit:"Tonnen/Jahr",hint:"Ca. 9 Tonnen jährlich – vor allem aus Spanien.",emoji:"🪙"},
  {id:"hist_234",q:"In welchem Jahr wurde Japan demokratisch?",a:1945,unit:"Jahr",hint:"Nach der Kapitulation im Zweiten Weltkrieg.",emoji:"🗳️"},
  {id:"hist_235",q:"Wie viele Schlachten verlor Napoleon insgesamt?",a:10,unit:"Schlachten",hint:"Er gewann 60 von 70 Schlachten.",emoji:"⚔️"},
  {id:"hist_236",q:"In welchem Jahr gründete William Penn Pennsylvania?",a:1681,unit:"Jahr",hint:"Als Zuflucht für Quäker.",emoji:"📜"}
];
