// 🍺 ESSEN & TRINKEN – Erwachsene – 250 Fragen
export default [
  {q:"Wie viele Kalorien hat ein Big Mac?",a:563,unit:"kcal",hint:"Davon kommen 257 kcal aus dem Fett.",emoji:"🍔"},
  {q:"Wie viele Liter Bier wurden beim Oktoberfest 2023 getrunken?",a:7300000,unit:"Liter",hint:"Das Oktoberfest ist das größte Volksfest der Welt.",emoji:"🍺"},
  {q:"Wie viele Gramm Zucker in einer Dose Cola (330ml)?",a:35,unit:"Gramm",hint:"Das sind etwa 7 Teelöffel Zucker.",emoji:"🥤"},
  {q:"Wie viele Tonnen Schokolade isst Deutschland pro Jahr?",a:900000,unit:"Tonnen",hint:"Weltmeister im Schokoladenkonsum pro Kopf.",emoji:"🍫"},
  {q:"Wie viele Liter Milch braucht man für 1 kg Käse?",a:10,unit:"Liter",hint:"Je nach Sorte 8–12 Liter Milch.",emoji:"🧀"},
  {q:"Wie viele Monate reift ein echter Parmesan mindestens?",a:24,unit:"Monate",hint:"Premium-Parmesan reift bis zu 5 Jahre.",emoji:"🧀"},
  {q:"Wie viele Körner Kaffee braucht man für einen Espresso?",a:50,unit:"Körner",hint:"Ein Kaffeebaum produziert pro Jahr ~500g Kaffee.",emoji:"☕"},
  {q:"Wie viele Liter Wein trinkt ein Franzose pro Jahr?",a:45,unit:"Liter",hint:"Frankreich führt weltweit den Pro-Kopf-Weinkonsum.",emoji:"🍷"},
  {q:"Wie viele kg Pasta isst ein Italiener durchschnittlich pro Jahr?",a:23,unit:"kg",hint:"Italien führt weltweit den Pastakonsum.",emoji:"🍝"},
  {q:"Wie hoch ist der Wasseranteil in einer Gurke in Prozent?",a:97,unit:"%",hint:"Gurken bestehen fast nur aus Wasser.",emoji:"🥒"},
  {q:"Wie viele Liter Kaffee trinken Finnen pro Kopf pro Jahr?",a:12,unit:"kg",hint:"Finnland ist Weltmeister im Kaffeeverbrauch.",emoji:"☕"},
  {q:"Wie viele Gramm Butter enthält ein original Croissant?",a:50,unit:"Gramm",hint:"Der hohe Butteranteil macht die blättrige Textur möglich.",emoji:"🥐"},
  {q:"Wie viele Prozent Fettgehalt hat Gänsestopfleber (Foie Gras)?",a:50,unit:"%",hint:"Eines der kalorienreichsten Lebensmittel.",emoji:"🍴"},
  {q:"Wie viele Liter Wasser braucht man für 1 kg Rindfleisch?",a:15000,unit:"Liter",hint:"Rindfleisch hat den größten Wasserverbrauch aller Nahrungsmittel.",emoji:"🥩"},
  {q:"Wie viele Jahre ist der älteste bekannte Wein alt (Speyer-Wein)?",a:1650,unit:"Jahre",hint:"Die Flasche wurde 1867 in einem römischen Grab gefunden (Stand ~2024).",emoji:"🍷"},
  {q:"Wie viele Milligramm wiegt eine Kaviar-Perle?",a:50,unit:"Milligramm",hint:"Beluga-Kaviar kostet bis zu 25.000€ pro kg.",emoji:"🐟"},
  {q:"Wie viele Kalorien hat ein Teelöffel Olivenöl?",a:40,unit:"kcal",hint:"Gesund – aber kalorienreich wie alle Fette.",emoji:"🫒"},
  {q:"Wie viele Gramm Salz isst ein Deutscher täglich?",a:10,unit:"Gramm",hint:"Empfohlen werden maximal 6 Gramm.",emoji:"🧂"},
  {q:"Wie scharf ist der Carolina Reaper in Millionen Scoville?",a:2.2,unit:"Mio. Scoville",hint:"Das schärfste Chili der Welt.",emoji:"🌶️"},
  {q:"Wie viele Stunden muss Jamon Iberico mindestens reifen?",a:8760,unit:"Stunden",hint:"Das sind mindestens 3 Jahre.",emoji:"🥩"},
  {q:"Wie viele Würste werden beim Nürnberger Christkindlesmarkt gegessen?",a:2000000,unit:"Würste",hint:"Nürnberger Bratwürste sind die kleinsten deutschen Würste.",emoji:"🌭"},
  {q:"Wie alt kann ein Wein maximal werden und noch trinkbar sein in Jahren?",a:200,unit:"Jahre",hint:"Ein 1811er Château d'Yquem wurde als exzellent bewertet.",emoji:"🍷"},
  {q:"Wie viel kostet Safran pro kg in Euro?",a:10000,unit:"€/kg",hint:"Safran ist das teuerste Gewürz der Welt.",emoji:"🌺"},
  {q:"Wie viele Pizzen werden täglich weltweit gegessen in Millionen?",a:5,unit:"Millionen",hint:"Die USA essen allein 3 Milliarden Pizzen pro Jahr.",emoji:"🍕"},
  {q:"Wie viele Kalorien hat ein Glas Rotwein (200ml)?",a:170,unit:"kcal",hint:"Wein hat mehr Kalorien als die meisten denken.",emoji:"🍷"},
  {q:"Wie viele Stunden dauert die Herstellung von echtem Champagner mindestens?",a:12960,unit:"Stunden",hint:"Das sind mindestens 18 Monate Reifung.",emoji:"🥂"},
  {q:"Wie viele Gramm Zucker hat ein Glas Orangensaft (200ml)?",a:20,unit:"Gramm",hint:"Fast so viel wie Cola – oft unterschätzt.",emoji:"🍊"},
  {q:"Wie viele Minuten pro Tag massiert man Kobe-Rind?",a:60,unit:"Minuten",hint:"Sie werden tatsächlich massiert und mit Bier gefüttert.",emoji:"🥩"},
  {q:"Wie viel Prozent des Wasabis im Restaurant ist echt?",a:1,unit:"%",hint:"99% ist gefälschter Wasabi aus Meerrettich und Farbe.",emoji:"🍣"},
  {q:"Wie viele Milliarden Liter Bier braut Deutschland pro Jahr?",a:8,unit:"Milliarden Liter",hint:"Milliarden Liter – Platz 5 weltweit.",emoji:"🍺"},
  {q:"Wie viele kcal hat eine durchschnittliche Currywurst?",a:350,unit:"kcal",hint:"Mit Pommes kommen nochmal 400 kcal dazu.",emoji:"🌭"},
  {q:"Wie viele Milliliter Espresso enthält eine Standard-Tasse?",a:25,unit:"ml",hint:"Ein Doppio hat 50 ml.",emoji:"☕"},
  {q:"Wie viele kg Mehl verbraucht Deutschland pro Kopf im Jahr?",a:86,unit:"kg",hint:"Wir sind eine Brotnation.",emoji:"🍞"},
  {q:"Wie viele Liter Wasser braucht man für 1 Liter Bier?",a:300,unit:"Liter",hint:"Inklusive Anbau, Verarbeitung und Kühlung.",emoji:"🍺"},
  {q:"Wie viele Kalorien hat ein Döner Kebab?",a:850,unit:"kcal",hint:"Der Döner ist Deutschlands beliebtestes Fast Food.",emoji:"🌯"},
  {q:"Wie viele Milliarden Liter Wein produziert Frankreich pro Jahr?",a:4,unit:"Milliarden Liter",hint:"Milliarden Liter – Platz 2 weltweit nach Italien.",emoji:"🍷"},
  {q:"Wie viele Gramm Eiweiß hat ein Ei?",a:6,unit:"Gramm",hint:"Ein Hühnerei hat ~6g Protein.",emoji:"🥚"},
  {q:"Wie viele Stunden fermentiert Kimchi traditionell?",a:24,unit:"Stunden",hint:"Manchmal auch Monate – je nach Rezept.",emoji:"🥬"},
  {q:"Wie viele Kalorien hat 100g dunkle Schokolade?",a:550,unit:"kcal",hint:"Viel Fett und Zucker – aber auch Antioxidantien.",emoji:"🍫"},
  {q:"Wie viele Tassen Tee trinken Briten pro Tag (pro Person)?",a:3,unit:"Tassen",hint:"Briten trinken jährlich 60 Milliarden Tassen Tee.",emoji:"🫖"},
  {q:"Wie viele Gramm Zucker hat Ketchup pro 100g?",a:22,unit:"Gramm",hint:"Ketchup enthält überraschend viel Zucker.",emoji:"🍅"},
  {q:"Wie viele Liter Wasser braucht man für 1 kg Mandeln?",a:15000,unit:"Liter",hint:"Mandeln sind extrem wasserintensiv.",emoji:"🌰"},
  {q:"Wie viele Milliarden Eier werden in Deutschland pro Jahr gegessen?",a:15,unit:"Milliarden",hint:"Etwa 180 Eier pro Person und Jahr.",emoji:"🥚"},
  {q:"Wie viele kcal hat eine Packung Chips (200g)?",a:1080,unit:"kcal",hint:"Über die Hälfte des Tagesbedarfs in einem Snack.",emoji:"🍟"},
  {q:"Wie viele Monate fermentiert echter Roquefort-Käse?",a:3,unit:"Monate",hint:"In speziellen Höhlen bei konstanter Temperatur.",emoji:"🧀"},
  {q:"Wie viele Gramm Salz enthält ein normales Brot (700g)?",a:10,unit:"Gramm",hint:"Brot ist eine der größten Salzquellen.",emoji:"🍞"},
  {q:"Wie viele Liter Bier hat der durchschnittliche Bayer pro Jahr?",a:150,unit:"Liter",hint:"Bayern führt den deutschen Bierkonsum an.",emoji:"🍺"},
  {q:"Wie viele Kalorien hat ein Schnitzel Wiener Art (ohne Beilagen)?",a:650,unit:"kcal",hint:"Mit Kartoffelsalat kommen nochmal 300 kcal dazu.",emoji:"🥩"},
  {q:"Wie viele Tonnen Obst isst Deutschland pro Jahr?",a:5000000,unit:"Tonnen",hint:"Äpfel sind das beliebteste Obst.",emoji:"🍎"},
  {q:"Wie viele Prozent Alkohol hat Standard-Bier?",a:5,unit:"%",hint:"Starkbiere haben bis zu 14% Alkohol.",emoji:"🍺"},
  {q:"Wie viele Gramm Kohlenhydrate hat 100g Weißbrot?",a:50,unit:"Gramm",hint:"Weißbrot hat fast so viele Kohlenhydrate wie Zucker.",emoji:"🍞"},
  {q:"Wie viele Stunden dauert die Fermentation von echtem Sourdough?",a:48,unit:"Stunden",hint:"Echter Sauerteig braucht Zeit für Geschmack.",emoji:"🍞"},
  {q:"Wie viele Liter Wasser braucht man für 1 kg Avocado?",a:1000,unit:"Liter",hint:"Avocados sind sehr wasserintensiv.",emoji:"🥑"},
  {q:"Wie viele kcal hat eine Tafel Vollmilchschokolade (100g)?",a:535,unit:"kcal",hint:"Milchschokolade hat etwas weniger als dunkle.",emoji:"🍫"},
  {q:"Wie viele Tonnen Bananen importiert Deutschland pro Jahr?",a:1000000,unit:"Tonnen",hint:"Banane ist die meistgekaufte Frucht Deutschlands.",emoji:"🍌"},
  {q:"Wie viele Gramm Fett hat 100g Butter?",a:83,unit:"Gramm",hint:"Butter ist fast pures Fett.",emoji:"🧈"},
  {q:"Wie viele Milliarden Würste werden in Deutschland pro Jahr produziert?",a:1500,unit:"Millionen",hint:"Deutschland ist Weltmeister in Wurstvielfalt.",emoji:"🌭"},
  {q:"Wie viele kcal hat ein Döner in einem normalen Fladenbrot?",a:1000,unit:"kcal",hint:"Ein Döner kann über die Hälfte des Tagesbedarfs decken.",emoji:"🌯"},
  {q:"Wie viele Liter Wasser braucht man für 1 kg Schokolade?",a:17196,unit:"Liter",hint:"Die wasserintensivste Süßigkeit.",emoji:"🍫"},
  {q:"Wie viele Stunden reift ein Gouda-Käse mindestens?",a:720,unit:"Stunden",hint:"30 Tage für jungen Gouda – alter Gouda reift Monate.",emoji:"🧀"},
  {q:"Wie viele Kalorien hat eine Maß Bier (1 Liter)?",a:430,unit:"kcal",hint:"Bier hat pro 100ml etwa 43 kcal.",emoji:"🍺"},
  {q:"Wie viele Gramm Protein hat 100g Hühnchen (Brust)?",a:31,unit:"Gramm",hint:"Hühnchenbrust ist eine der eiweißreichsten Quellen.",emoji:"🍗"},
  {q:"Wie viele Tonnen Kaffee trinkt Deutschland pro Jahr?",a:500000,unit:"Tonnen",hint:"Kaffee ist das Lieblingsgetränk der Deutschen.",emoji:"☕"},
  {q:"Wie viele kcal hat eine normale Portion Pommes Frites (150g)?",a:450,unit:"kcal",hint:"Mit Ketchup und Mayonnaise deutlich mehr.",emoji:"🍟"},
  {q:"Wie viele Liter Wein trinken Deutsche pro Kopf pro Jahr?",a:20,unit:"Liter",hint:"Weniger als Franzosen oder Portugiesen.",emoji:"🍷"},
  {q:"Wie viele Gramm Zucker hat ein Glas Eistee (250ml)?",a:25,unit:"Gramm",hint:"Eistee ist eine versteckte Zuckerfalle.",emoji:"🍵"},
  {q:"Wie viele kcal hat ein normales Croissant?",a:250,unit:"kcal",hint:"Kleines Gebäck mit vielen Kalorien.",emoji:"🥐"},
  {q:"Wie viele Monate fermentiert echter Miso?",a:12,unit:"Monate",hint:"Traditioneller Miso reift 1-3 Jahre.",emoji:"🫙"},
  {q:"Wie viele Gramm Mehl braucht man für eine Pizza (30cm)?",a:250,unit:"Gramm",hint:"Plus Tomatensauce, Käse und Belag.",emoji:"🍕"},
  {q:"Wie viele Liter Wasser braucht man für 1 kg Schweinefleisch?",a:5988,unit:"Liter",hint:"Deutlich weniger als Rind, aber immer noch viel.",emoji:"🥩"},
  {q:"Wie viele kcal hat ein Stück Schwarzwälder Kirschtorte?",a:450,unit:"kcal",hint:"Sahne, Schokolade und Kirschwasser.",emoji:"🎂"},
  {q:"Wie viele Milligramm Capsaicin enthält ein Jalapeño?",a:100,unit:"Milligramm",hint:"Capsaicin ist der Wirkstoff der Schärfe.",emoji:"🌶️"},
  {q:"Wie viele Tonnen Erdbeeren produziert Deutschland pro Jahr?",a:100000,unit:"Tonnen",hint:"Bayern ist größter Produzent.",emoji:"🍓"},
  {q:"Wie viele Stunden braucht ein Käse um zu schimmeln (Camembert)?",a:168,unit:"Stunden",hint:"7 Tage für die charakteristische weiße Rinde.",emoji:"🧀"},
  {q:"Wie viele Liter Wasser braucht man für 1 Tasse Kaffee?",a:140,unit:"Liter",hint:"Inklusive Anbau und Verarbeitung.",emoji:"☕"},
  {q:"Wie viele Kalorien hat ein Hamburger (ohne Pommes)?",a:500,unit:"kcal",hint:"Je nach Belag mehr oder weniger.",emoji:"🍔"},
  {q:"Wie viele Gramm Omega-3 hat 100g Lachs?",a:2.5,unit:"Gramm",hint:"Lachs ist eine der besten Omega-3-Quellen.",emoji:"🐟"},
  {q:"Wie viele Millionen Hektoliter Bier trinkt die Welt pro Jahr?",a:1900,unit:"Mio. Hektoliter",hint:"China ist der größte Biermarkt weltweit.",emoji:"🍺"},
  {q:"Wie viele kcal hat 1 Gramm Alkohol?",a:7,unit:"kcal",hint:"Mehr als Zucker (4 kcal) – aber weniger als Fett (9 kcal).",emoji:"🍺"},
  {q:"Wie viele Tonnen Süßigkeiten isst Deutschland pro Jahr?",a:800000,unit:"Tonnen",hint:"Haribo ist das bekannteste deutsche Süßwareunternehmen.",emoji:"🍬"},
  {q:"Wie viele Stunden dauert das Räuchern eines Schinkens?",a:48,unit:"Stunden",hint:"Echtes Kalträuchern dauert Tage.",emoji:"🥩"},
  {q:"Wie viele Gramm Zucker hat ein Päckchen Gummibärchen (200g)?",a:140,unit:"Gramm",hint:"70% Zucker – Gummibärchen sind fast purer Zucker.",emoji:"🐻"},
  {q:"Wie viele kcal hat ein Bier (0,5l, Pils)?",a:215,unit:"kcal",hint:"Ein Bier hat mehr Kalorien als ein Apfel.",emoji:"🍺"},
  {q:"Wie viele Liter Wasser braucht man für 1 kg Käse?",a:5000,unit:"Liter",hint:"Inklusive der Milch die man braucht.",emoji:"🧀"},
  {q:"Wie viele Gramm hat ein Standard-Würfel Zucker?",a:4,unit:"Gramm",hint:"16 kcal pro Würfel.",emoji:"🍬"},
  {q:"Wie viele Tonnen Tomaten produziert Italien pro Jahr?",a:5000000,unit:"Tonnen",hint:"Größter Tomatenproduzent Europas.",emoji:"🍅"},
  {q:"Wie viele Milliliter hat ein Standard-Shot Schnaps?",a:40,unit:"ml",hint:"In Deutschland sind 2 cl der Standard.",emoji:"🥃"},
  {q:"Wie viele kcal hat 100g Erdnussbutter?",a:589,unit:"kcal",hint:"Sehr kalorienreich – aber voller Proteine.",emoji:"🥜"},
  {q:"Wie viele Gramm Eiweiß hat 100g Quark (Magerquark)?",a:12,unit:"Gramm",hint:"Magerquark ist eine günstige Proteinquelle.",emoji:"🥛"},
  {q:"Wie viele Liter Wasser braucht man für 1 kg Tomaten?",a:183,unit:"Liter",hint:"Deutlich weniger als Fleisch.",emoji:"🍅"},
  {q:"Wie viele Kalorien hat 100g Brokkoli?",a:34,unit:"kcal",hint:"Eines der nährstoffreichsten Gemüse.",emoji:"🥦"},
  {q:"Wie viele Tonnen Wurst produziert Deutschland pro Jahr?",a:1500000,unit:"Tonnen",hint:"1,5 Millionen Tonnen – über 1500 Sorten.",emoji:"🌭"},
  {q:"Wie viele Stunden reift echter Roquefort in Höhlen?",a:2160,unit:"Stunden",hint:"90 Tage in Combalou-Höhlen.",emoji:"🧀"},
  {q:"Wie viele kcal hat ein Brezn (80g)?",a:270,unit:"kcal",hint:"Mit Butter nochmal 100 kcal mehr.",emoji:"🥨"},
  {q:"Wie viele Gramm Zucker hat 100ml Fruchtsaft?",a:10,unit:"Gramm",hint:"Naturtrüber Saft enthält genauso viel Zucker wie Cola.",emoji:"🍹"},
  {q:"Wie viele Milliarden Eier produziert Deutschland pro Jahr?",a:15,unit:"Milliarden",hint:"Trotzdem importieren wir noch Eier.",emoji:"🥚"},
  {q:"Wie viele kcal hat ein Weißwurst-Frühstück (2 Würste + Brezel + Bier)?",a:900,unit:"kcal",hint:"Ein bayerisches Frühstück ist keine leichte Mahlzeit.",emoji:"🍺"},
  {q:"Wie viele Liter Wasser braucht man für 1 Liter Orangensaft?",a:1000,unit:"Liter",hint:"Anbau, Transport und Verarbeitung addieren sich.",emoji:"🍊"},
  {q:"Wie viele Gramm Fett hat ein Döner?",a:30,unit:"Gramm",hint:"Je nach Zubereitung 20-50g Fett.",emoji:"🌯"},
  {q:"Wie viele Tonnen Honig produziert Deutschland pro Jahr?",a:25000,unit:"Tonnen",hint:"Trotzdem importieren wir deutlich mehr.",emoji:"🍯"},
  {q:"Wie viele kcal hat ein Stück Käsekuchen (100g)?",a:320,unit:"kcal",hint:"Eines der kalorienreichsten deutschen Desserts.",emoji:"🎂"},
  {q:"Wie viele Gramm Calcium hat 100ml Milch?",a:120,unit:"Gramm",hint:"Milch ist die beste Calciumquelle.",emoji:"🥛"},
  {q:"Wie viele Stunden fermentiert echter Balsamico aus Modena?",a:87600,unit:"Stunden",hint:"10 Jahre – manchmal sogar 25 Jahre.",emoji:"🫙"},
  {q:"Wie viele Millionen Liter Champagner werden weltweit pro Jahr produziert?",a:300,unit:"Millionen Liter",hint:"Millionen Liter aus nur einer Region Frankreichs.",emoji:"🥂"},
  {q:"Wie viele kcal hat 100g Avocado?",a:160,unit:"kcal",hint:"Reich an gesunden Fetten.",emoji:"🥑"},
  {q:"Wie viele Tonnen Kartoffeln isst Deutschland pro Jahr?",a:4000000,unit:"Tonnen",hint:"Über 50 kg pro Person pro Jahr.",emoji:"🥔"},
  {q:"Wie viele Gramm Zucker hat 100g Ketchup?",a:22,unit:"Gramm",hint:"Ketchup ist fast ein Viertel Zucker.",emoji:"🍅"},
  {q:"Wie viele kcal hat ein Sauerbraten mit Knödel?",a:1200,unit:"kcal",hint:"Ein echtes deutsches Festmahl.",emoji:"🥩"},
  {q:"Wie viele Milliliter fasst ein Standard-Weinglas?",a:200,unit:"ml",hint:"Ein normales Weinglas – nicht bis zum Rand.",emoji:"🍷"},
  {q:"Wie viele Tonnen Fleisch isst Deutschland pro Jahr?",a:7500000,unit:"Tonnen",hint:"Etwa 90 kg Fleisch pro Person pro Jahr.",emoji:"🥩"},
  {q:"Wie viele kcal hat ein Lebkuchen (35g)?",a:130,unit:"kcal",hint:"Weihnachtsgebäck mit versteckten Kalorien.",emoji:"🍪"},
  {q:"Wie viele Gramm Protein hat 100g Linsen (gekocht)?",a:9,unit:"Gramm",hint:"Linsen sind eine gute pflanzliche Proteinquelle.",emoji:"🫘"},
  {q:"Wie viele Liter Wasser braucht man für 1 kg Reis?",a:2500,unit:"Liter",hint:"Nassreis-Anbau verbraucht enorm viel Wasser.",emoji:"🍚"},
  {q:"Wie viele kcal hat 100g Walnüsse?",a:654,unit:"kcal",hint:"Sehr kalorienreich aber voller gesunder Fette.",emoji:"🌰"},
  {q:"Wie viele Gramm Zucker hat eine Flasche Energydrink (250ml)?",a:27,unit:"Gramm",hint:"Ähnlich wie Cola – plus Koffein.",emoji:"⚡"},
  {q:"Wie viele Tonnen Zucker konsumiert Deutschland pro Jahr?",a:3000000,unit:"Tonnen",hint:"3 Millionen Tonnen – über 35 kg pro Person.",emoji:"🍬"},
  {q:"Wie viele kcal hat ein Apfelstrudel (100g)?",a:250,unit:"kcal",hint:"Wiener Spezialität mit Butter und Zucker.",emoji:"🥐"},
  {q:"Wie viele Milliliter hat ein Standard-Espresso?",a:25,unit:"ml",hint:"Klein aber stark – 7g Kaffeemehl.",emoji:"☕"},
  {q:"Wie viele Gramm Kohlenhydrate hat 100g Kartoffeln?",a:17,unit:"Gramm",hint:"Weniger als gedacht – Fett in Pommes ist das Problem.",emoji:"🥔"},
  {q:"Wie viele Liter Wein trinkt die Welt pro Jahr (Milliarden)?",a:26,unit:"Milliarden Liter",hint:"Milliarden Liter – steigende Tendenz.",emoji:"🍷"},
  {q:"Wie viele kcal hat 100g Vollmilch (3,5%)?",a:64,unit:"kcal",hint:"Milch ist kalorienärmer als die meisten denken.",emoji:"🥛"},
  {q:"Wie viele Gramm Zucker hat 100g Joghurt (Fruchtjoghurt)?",a:13,unit:"Gramm",hint:"Fruchtjoghurt hat überraschend viel Zucker.",emoji:"🫙"},
  {q:"Wie viele Millionen Tonnen Weizen produziert Deutschland pro Jahr?",a:22,unit:"Millionen Tonnen",hint:"Deutschland ist einer der größten Weizenproduzenten Europas.",emoji:"🌾"},
  {q:"Wie viele kcal hat eine Brezel mit Butter?",a:400,unit:"kcal",hint:"Eine beliebte bayrische Snack-Kombination.",emoji:"🥨"},
  {q:"Wie viele Gramm Protein hat 100g Thunfisch (aus der Dose)?",a:26,unit:"Gramm",hint:"Einer der günstigsten Proteinsupplier.",emoji:"🐟"},
  {q:"Wie viele Liter Wasser braucht man für 1 Tasse Tee?",a:30,unit:"Liter",hint:"Deutlich weniger als Kaffee.",emoji:"🫖"},
  {q:"Wie viele kcal hat 100g Hüttenkäse?",a:98,unit:"kcal",hint:"Sehr eiweißreich und kalorienarm.",emoji:"🧀"},
  {q:"Wie viele Gramm Zucker hat ein Gummibärchen?",a:2,unit:"Gramm",hint:"Pro Stück – eine Packung hat 140g Zucker.",emoji:"🐻"},
  {q:"Wie viele Millionen Tonnen Lebensmittel verschwendet Deutschland pro Jahr?",a:12,unit:"Millionen Tonnen",hint:"Ein Drittel aller produzierten Lebensmittel landet im Müll.",emoji:"🗑️"},
  {q:"Wie viele kcal hat ein Brot (Scheibe, 50g)?",a:120,unit:"kcal",hint:"Abhängig von der Brotsorte.",emoji:"🍞"},
  {q:"Wie viele Gramm Eiweiß hat ein Hühnerei?",a:6,unit:"Gramm",hint:"Eier haben das hochwertigste Protein aller Lebensmittel.",emoji:"🥚"},
  {q:"Wie viele Millionen Liter Cognac und Armagnac destilliert Frankreich pro Jahr?",a:200,unit:"Millionen Liter",hint:"Millionen Liter Cognac und Armagnac.",emoji:"🥃"},
  {q:"Wie viele kcal hat 100g Olivenöl?",a:884,unit:"kcal",hint:"Das kalorienreichste gängige Lebensmittel.",emoji:"🫒"},
  {q:"Wie viele Gramm Zucker hat 100ml Orangensaft (frisch gepresst)?",a:8,unit:"Gramm",hint:"Frisch gepresst hat etwas weniger Zucker als Fertigsaft.",emoji:"🍊"},
  {q:"Wie viele Tonnen Schinken produziert Spanien pro Jahr?",a:350000,unit:"Tonnen",hint:"Spanien ist Weltmeister im Schinkenkonsum.",emoji:"🥩"},
  {q:"Wie viele kcal hat ein Stück Tiramisu (100g)?",a:400,unit:"kcal",hint:"Mascarpone, Eier und Zucker machen es kalorienreich.",emoji:"🎂"},
  {q:"Wie viele Gramm Fett hat 100g Cheddar-Käse?",a:34,unit:"Gramm",hint:"Hartkäse sind generell sehr fettreich.",emoji:"🧀"},
  {q:"Wie viele Liter Schnaps trinkt ein Österreicher pro Jahr?",a:5,unit:"Liter",hint:"Österreich führt Europa im Schnapskonsum an.",emoji:"🥃"},
  {q:"Wie viele kcal hat 100g Lachs (geräuchert)?",a:180,unit:"kcal",hint:"Lachs hat mehr Kalorien als mageres Fleisch.",emoji:"🐟"},
  {q:"Wie viele Gramm Protein hat 100g Tempeh?",a:19,unit:"Gramm",hint:"Tempeh hat mehr Protein als Tofu.",emoji:"🫘"},
  {q:"Wie viele Millionen Tonnen Zucker isst die Welt pro Jahr?",a:200,unit:"Millionen Tonnen",hint:"Millionen Tonnen – steigend.",emoji:"🍬"},
  {q:"Wie viele kcal hat ein Gulasch mit Reis?",a:800,unit:"kcal",hint:"Ein sättigendes Mittagessen.",emoji:"🍲"},
  {q:"Wie viele Gramm Kohlenhydrate hat 100g Weißbrot?",a:50,unit:"Gramm",hint:"Weißbrot hat einen hohen glykämischen Index.",emoji:"🍞"},
  {q:"Wie viele Millionen Tonnen Fisch werden weltweit pro Jahr gegessen?",a:90,unit:"Millionen Tonnen",hint:"Millionen Tonnen – die Ozeane werden überfischt.",emoji:"🐟"},
  {q:"Wie viele kcal hat 100g Leberwurst?",a:330,unit:"kcal",hint:"Sehr fett- und kalorienreich.",emoji:"🌭"},
  {q:"Wie viele Gramm Ballaststoffe hat 100g Vollkornbrot?",a:7,unit:"Gramm",hint:"Deutlich mehr als Weißbrot (2g).",emoji:"🍞"},
  {q:"Wie viele Liter Trinkwasser verbraucht ein Deutscher täglich?",a:124,unit:"Liter",hint:"Davon trinkt man nur 1-2 Liter direkt.",emoji:"💧"},
  {q:"Wie viele kcal hat ein Stück Schwarzbrot (50g)?",a:108,unit:"kcal",hint:"Kalorienärmer als Weißbrot.",emoji:"🍞"},
  {q:"Wie viele Gramm Zucker hat 100ml Cola?",a:10.6,unit:"Gramm",hint:"Über 10% Zucker in jedem Schluck.",emoji:"🥤"},
  {q:"Wie viele Tonnen Käse produziert Deutschland pro Jahr?",a:2000000,unit:"Tonnen",hint:"Deutschland ist weltführend in der Käseproduktion.",emoji:"🧀"},
  {q:"Wie viele kcal hat 100g Baklava?",a:430,unit:"kcal",hint:"Süßes türkisches Gebäck aus Blätterteig und Honig.",emoji:"🍯"},
  {q:"Wie viele Gramm Eiweiß hat 100g Rinderfilet?",a:22,unit:"Gramm",hint:"Mageres Rindfleisch ist eine hervorragende Proteinquelle.",emoji:"🥩"},
  {q:"Wie viele Millionen Liter Wodka trinkt Russland pro Jahr?",a:1600,unit:"Millionen Liter",hint:"Russland führt weltweit den Wodkakonsum.",emoji:"🥃"},
  {q:"Wie viele kcal hat ein Stück Apfelkuchen (100g)?",a:290,unit:"kcal",hint:"Mit Sahne nochmal 100 kcal mehr.",emoji:"🥧"},
  {q:"Wie viele Gramm Fett hat 100g Camembert?",a:24,unit:"Gramm",hint:"Der Fettgehalt variiert je nach Reifegrad.",emoji:"🧀"},
  {q:"Wie viele Liter Wasser braucht man für 1 kg Soja?",a:1000,unit:"Liter",hint:"Weniger als tierische Produkte.",emoji:"🫘"},
  {q:"Wie viele kcal hat ein Franzbrötchen (80g)?",a:320,unit:"kcal",hint:"Hamburger Spezialität mit Butter und Zimt.",emoji:"🥐"},
  {q:"Wie viele Gramm Kohlenhydrate hat 100g Nudeln (ungekocht)?",a:70,unit:"Gramm",hint:"Nudeln sind eine Kohlenhydrat-Bombe.",emoji:"🍝"},
  {q:"Wie viele Tonnen Schokolade exportiert Deutschland pro Jahr?",a:400000,unit:"Tonnen",hint:"Deutschland ist Europas größter Schokoladenexporteur.",emoji:"🍫"},
  {q:"Wie viele kcal hat ein Weißwein-Schorle (200ml)?",a:80,unit:"kcal",hint:"Weniger als Rotwein durch die Verdünnung.",emoji:"🍷"},
  {q:"Wie viele Gramm Zucker hat ein Bounty (57g)?",a:31,unit:"Gramm",hint:"Über die Hälfte ist Zucker.",emoji:"🍫"},
  {q:"Wie viele Millionen Liter Sekt trinkt Deutschland pro Jahr?",a:300,unit:"Millionen Liter",hint:"Deutschland ist Weltmeister im Sektkonsum.",emoji:"🥂"},
  {q:"Wie viele kcal hat 100g Nüsse (gemischt)?",a:600,unit:"kcal",hint:"Nüsse sind sehr kalorienreich aber gesund.",emoji:"🥜"},
  {q:"Wie viele Gramm Eiweiß hat 100g Shrimps?",a:24,unit:"Gramm",hint:"Sehr proteinreich und kalorienarm.",emoji:"🍤"},
  {q:"Wie viele Liter Milch trinkt ein Deutscher pro Jahr?",a:52,unit:"Liter",hint:"Rückgang seit Jahren – Alternativen boomen.",emoji:"🥛"},
  {q:"Wie viele kcal hat 100g Hummus?",a:177,unit:"kcal",hint:"Gesunder Aufschnitt aus Kichererbsen.",emoji:"🫘"},
  {q:"Wie viele Gramm Fett hat 100g Chips?",a:35,unit:"Gramm",hint:"Ein Drittel der Chips besteht aus Fett.",emoji:"🍟"},
  {q:"Wie viele Tonnen Tomatenmark produziert die Welt pro Jahr?",a:9000000,unit:"Tonnen",hint:"Die Basis fast aller Saucen.",emoji:"🍅"},
  {q:"Wie viele kcal hat ein Stück Königsberger Klopse (2 Stück)?",a:400,unit:"kcal",hint:"Deutsche Fleischbällchen in Kapernsauce.",emoji:"🍲"},
  {q:"Wie viele Gramm Kohlenhydrate hat 100g Honig?",a:80,unit:"Gramm",hint:"Honig besteht fast nur aus Zucker.",emoji:"🍯"},
  {q:"Wie viele Millionen Tonnen Getreide produziert die EU pro Jahr?",a:300,unit:"Millionen Tonnen",hint:"Getreide ist die wichtigste Nahrungsgrundlage.",emoji:"🌾"},
  {q:"Wie viele kcal hat ein Glas Smoothie (300ml)?",a:180,unit:"kcal",hint:"Smoothies können viele versteckte Kalorien haben.",emoji:"🍹"},
  {q:"Wie viele Gramm Protein hat 100g Kürbiskerne?",a:30,unit:"Gramm",hint:"Eine der proteinreichsten pflanzlichen Quellen.",emoji:"🎃"},
  {q:"Wie viele Milliarden Liter Bier braut die USA pro Jahr?",a:20,unit:"Milliarden Liter",hint:"Größter Biermarkt der Welt nach China.",emoji:"🍺"},
  {q:"Wie viele kcal hat eine Tasse Cappuccino?",a:120,unit:"kcal",hint:"Milch und Schaum haben Kalorien.",emoji:"☕"},
  {q:"Wie viele Gramm Zucker hat 100g Marmelade?",a:65,unit:"Gramm",hint:"Marmelade ist fast zwei Drittel Zucker.",emoji:"🍓"},
  {q:"Wie viele Tonnen Butter produziert Deutschland pro Jahr?",a:500000,unit:"Tonnen",hint:"Deutschland ist Europas größter Butterproduzent.",emoji:"🧈"},
  {q:"Wie viele kcal hat 100g Mandeln?",a:576,unit:"kcal",hint:"Sehr kalorienreich – auch wenn sie gesund sind.",emoji:"🌰"},
  {q:"Wie viele Gramm Eiweiß hat 100g Mozzarella?",a:18,unit:"Gramm",hint:"Mehr Protein als die meisten Weichkäse.",emoji:"🧀"},
  {q:"Wie viele Stunden fermentiert traditionelles Sauerkraut?",a:336,unit:"Stunden",hint:"14 Tage oder mehr.",emoji:"🥬"},
  {q:"Wie viele kcal hat 100g Frühstücksflocken (Cornflakes)?",a:370,unit:"kcal",hint:"Weniger als Müsli mit Nüssen.",emoji:"🥣"},
  {q:"Wie viele Gramm Kohlenhydrate hat 100g Weintrauben?",a:17,unit:"Gramm",hint:"Trauben sind sehr zuckerreich.",emoji:"🍇"},
  {q:"Wie viele Millionen Tonnen Fleisch produziert die Welt pro Jahr?",a:340,unit:"Millionen Tonnen",hint:"Davon ist die Hälfte Schweinefleisch.",emoji:"🥩"},
  {q:"Wie viele kcal hat ein Knäckebrot (10g)?",a:34,unit:"kcal",hint:"Sehr kalorienarm – gut als Diätknacker.",emoji:"🍞"},
  {q:"Wie viele Gramm Fett hat 100g Sahne (Schlagsahne)?",a:35,unit:"Gramm",hint:"Schlagsahne ist fast reines Fett.",emoji:"🍦"},
  {q:"Wie viele Liter Wasser braucht man für 1 kg Äpfel?",a:822,unit:"Liter",hint:"Äpfel brauchen deutlich weniger Wasser als exotische Früchte.",emoji:"🍎"},
  {q:"Wie viele kcal hat ein Berliner Pfannkuchen (60g)?",a:250,unit:"kcal",hint:"Frittiert und mit Marmelade gefüllt.",emoji:"🍩"},
  {q:"Wie viele Gramm Protein hat 100g Kichererbsen (gekocht)?",a:9,unit:"Gramm",hint:"Eine wichtige vegane Proteinquelle.",emoji:"🫘"},
  {q:"Wie viele Tonnen Olivenöl produziert Spanien pro Jahr?",a:1800000,unit:"Tonnen",hint:"Größter Olivenölproduzent weltweit.",emoji:"🫒"},
  {q:"Wie viele kcal hat 100g Speck?",a:541,unit:"kcal",hint:"Einer der kalorienreichsten Fleischprodukte.",emoji:"🥓"},
  {q:"Wie viele Gramm Kohlenhydrate hat 100g Süßkartoffeln?",a:20,unit:"Gramm",hint:"Etwas mehr als normale Kartoffeln.",emoji:"🍠"},
  {q:"Wie viele Millionen Hektoliter Wein produziert Italien pro Jahr?",a:50,unit:"Mio. Hektoliter",hint:"Italiens größter Weinexport-Posten.",emoji:"🍷"},
  {q:"Wie viele kcal hat 100g Räucherlachs?",a:180,unit:"kcal",hint:"Weniger kalorienreich als geräuchertes Fleisch.",emoji:"🐟"},
  {q:"Wie viele Gramm Fett hat 100g Bratwurst?",a:25,unit:"Gramm",hint:"Bratwurst ist ein fettreiches Produkt.",emoji:"🌭"},
  {q:"Wie viele Stunden dauert die Herstellung von Sojasoße traditionell?",a:4380,unit:"Stunden",hint:"6 Monate Fermentation.",emoji:"🫙"},
  {q:"Wie viele kcal hat eine Pizza Margherita (30cm)?",a:900,unit:"kcal",hint:"Die klassische Pizza – noch ohne Extras.",emoji:"🍕"},
  {q:"Wie viele Gramm Zucker hat 100g Honigmelone?",a:8,unit:"Gramm",hint:"Melone ist im Sommer perfekt.",emoji:"🍈"},
  {q:"Wie viele Millionen Tonnen Zucker stecken in der weltweiten Coca-Cola-Produktion pro Jahr?",a:10,unit:"Millionen Tonnen",hint:"Millionen Tonnen Zucker in Coca-Cola jährlich.",emoji:"🥤"},
  {q:"Wie viele kcal hat 100g Edamer Käse?",a:357,unit:"kcal",hint:"Ein milder Schnitt-Käse mit mittlerem Fettgehalt.",emoji:"🧀"},
  {q:"Wie viele Gramm Eiweiß hat 100g griechischer Joghurt?",a:10,unit:"Gramm",hint:"Doppelt so viel wie normaler Joghurt.",emoji:"🫙"},
  {q:"Wie viele Milliarden Liter Scotch Whisky exportiert Schottland pro Jahr?",a:1300,unit:"Millionen Liter",hint:"1,3 Milliarden Liter – Scotch Whisky ist ein Riesenmarkt.",emoji:"🥃"},
  {q:"Wie viele kcal hat 100g Mayonnaise?",a:680,unit:"kcal",hint:"Fast reines Fett aus Öl und Ei.",emoji:"🫙"},
  {q:"Wie viele Gramm Fett hat 100g Avocado?",a:15,unit:"Gramm",hint:"Ungesättigte Fettsäuren – die guten Fette.",emoji:"🥑"},
  {q:"Wie viele Millionen kg Kaffee verbraucht Deutschland täglich?",a:2,unit:"Millionen kg",hint:"Millionen Kilogramm Kaffee täglich.",emoji:"☕"},
  {q:"Wie viele kcal hat 100g Camembert (45% Fett)?",a:290,unit:"kcal",hint:"Weichkäse sind kalorienreich.",emoji:"🧀"},
  {q:"Wie viele Gramm Kohlenhydrate hat 100g Banane?",a:23,unit:"Gramm",hint:"Bananen liefern schnelle Energie.",emoji:"🍌"},
  {q:"Wie viele Gramm Eiweiß hat 100g Tofu?",a:8,unit:"Gramm",hint:"Tofu ist eine wichtige vegane Proteinquelle.",emoji:"🫘"},
  {q:"Wie viele kcal hat 100g Schinken?",a:130,unit:"kcal",hint:"Weniger fett als Salami.",emoji:"🥩"},
  {q:"Wie viele Gramm Zucker hat ein Schokoriegel (Mars, 51g)?",a:36,unit:"Gramm",hint:"Fast drei Viertel des Schokoriegels ist Zucker.",emoji:"🍫"},
  {q:"Wie viele Liter Bier trinkt ein Tscheche pro Jahr?",a:189,unit:"Liter",hint:"Weltmeister im Pro-Kopf-Bierverbrauch.",emoji:"🍺"},
  {q:"Wie viele Gramm Fett hat 100g Nutella?",a:31,unit:"Gramm",hint:"Und 57g Zucker dazu.",emoji:"🍫"},
  {q:"Wie viele kcal hat 100g Lachs (frisch)?",a:208,unit:"kcal",hint:"Reich an Omega-3-Fettsäuren.",emoji:"🐟"},
  {q:"Wie viele kg Fleisch isst ein Amerikaner pro Jahr?",a:120,unit:"kg",hint:"Fast doppelt so viel wie ein Europäer.",emoji:"🥩"},
  {q:"Wie viele Gramm Zucker hat ein Glas Milchkaffee (Latte, 300ml)?",a:14,unit:"Gramm",hint:"Durch die Milch.",emoji:"☕"},
  {q:"Wie viele kcal hat ein Stück Tiramisu (150g)?",a:600,unit:"kcal",hint:"Mascarpone macht es sehr kalorienreich.",emoji:"🎂"},
  {q:"Wie viele Gramm Protein hat 100g Seitan?",a:25,unit:"Gramm",hint:"Weizenglutenprodukt – sehr proteinreich.",emoji:"💪"},
  {q:"Wie viele Liter Wasser braucht man für 1 kg Hühnchen?",a:4325,unit:"Liter",hint:"Deutlich weniger als Rind.",emoji:"🐔"},
  {q:"Wie viele kcal hat ein Donut (Glazed, 57g)?",a:269,unit:"kcal",hint:"Klein aber mächtig kalorienreich.",emoji:"🍩"},
  {q:"Wie viele Gramm Fett hat 100g Chorizo?",a:40,unit:"Gramm",hint:"Eine der fettreichsten Wurstarten.",emoji:"🌭"},
  {q:"Wie viele Prozent Fett enthält griechischer Joghurt (normal)?",a:10,unit:"%",hint:"Deutlich fettreicher als normaler Joghurt.",emoji:"🫙"},
  {q:"Wie viele kcal hat 100g Roquefort-Käse?",a:369,unit:"kcal",hint:"Schimmelkäse sind kalorienreicher.",emoji:"🧀"},
  {q:"Wie viele Gramm Zucker hat 100g Müsli?",a:15,unit:"Gramm",hint:"Ungesüßtes Müsli hat weniger – Fertigprodukte viel mehr.",emoji:"🥣"},
  {q:"Wie viele Liter produziert ein Weinberg (Hektar) pro Jahr?",a:5000,unit:"Liter",hint:"Wein braucht erstaunlich viel Wasser.",emoji:"🍷"},
  {q:"Wie viele kcal hat ein Glas Apfelsaft (200ml)?",a:94,unit:"kcal",hint:"Fast wie Cola – trotz 'gesund'.",emoji:"🍎"},
  {q:"Wie viele Gramm Protein hat 100g Haferflocken?",a:13,unit:"Gramm",hint:"Eine der proteinreichsten Getreidearten.",emoji:"🌾"},
  {q:"Wie viele kcal hat ein Stück Focaccia (100g)?",a:270,unit:"kcal",hint:"Italienisches Fladenbrot mit Olivenöl.",emoji:"🍞"},
  {q:"Wie viele Gramm Kohlenhydrate hat 100g Paprika?",a:6,unit:"Gramm",hint:"Paprika ist sehr kohlenhydratarm.",emoji:"🌶️"},
  {q:"Wie viele Liter Milch trinkt ein Finne pro Jahr?",a:180,unit:"Liter",hint:"Finnland ist Weltmeister im Milchkonsum.",emoji:"🥛"},
  {q:"Wie viele kcal hat ein Vollkornbrot (Scheibe, 50g)?",a:105,unit:"kcal",hint:"Etwas weniger als Weißbrot.",emoji:"🍞"},
  {q:"Wie viele Gramm Zucker hat 100g Balsamico-Essig?",a:17,unit:"Gramm",hint:"Viel Zucker für ein Sauerprodukt.",emoji:"🫙"},
  {q:"Wie viele Tonnen Sushi wird täglich in Japan gegessen?",a:2000,unit:"Tonnen",hint:"Japan bleibt der Weltmarktführer.",emoji:"🍣"},
  {q:"Wie viele kcal hat ein Hotdog (normal)?",a:290,unit:"kcal",hint:"Mit Senf und Ketchup etwas mehr.",emoji:"🌭"},
  {q:"Wie viele Kilogramm Calcium hat 100g Parmesan?",a:1.184,unit:"Kilogramm",hint:"Parmesan hat mehr Calcium als fast jedes andere Lebensmittel.",emoji:"🧀"},
  {q:"Wie viele Millionen Tonnen Schokolade produziert die Welt pro Jahr?",a:8,unit:"Millionen Tonnen",hint:"Millionen Tonnen weltweit.",emoji:"🍫"},
  {q:"Wie viele kcal hat 100g Macarons?",a:450,unit:"kcal",hint:"Sehr zuckerreich und kalorienreich.",emoji:"🍬"},
  {q:"Wie viele Gramm Zucker hat ein Red Bull (250ml)?",a:27,unit:"Gramm",hint:"Fast so viel wie Cola.",emoji:"⚡"},
  {q:"Wie viele Liter Wasser braucht man für 1 Tasse heißen Tee?",a:30,unit:"Liter",hint:"Inklusive Anbau und Verarbeitung.",emoji:"🍵"},
  {q:"Wie viele kcal hat ein Stück Baklava (50g)?",a:215,unit:"kcal",hint:"Süß und kalorienreich.",emoji:"🍯"},
  {q:"Wie viele Gramm Protein hat 100g Kürbissamen?",a:30,unit:"Gramm",hint:"Eine der proteinreichsten pflanzlichen Quellen.",emoji:"🎃"},
  {q:"Wie viele Kilogramm Zucker isst ein Europäer pro Jahr?",a:38,unit:"kg",hint:"Kg – über 100g täglich.",emoji:"🍬"},
  {q:"Wie viele kcal hat ein Stück Käsekuchen (100g)?",a:321,unit:"kcal",hint:"Quark und Eier machen ihn kalorienreich.",emoji:"🎂"},
  {q:"Wie viele Gramm Eiweiß hat 100g schwarze Bohnen (gekocht)?",a:9,unit:"Gramm",hint:"Gute pflanzliche Proteinquelle.",emoji:"🫘"},
  {q:"Wie viele Liter Kaffee trinkt ein Norweger pro Jahr?",a:9.9,unit:"kg",hint:"Skandinavien führt den Kaffeekonsum weltweit.",emoji:"☕"},
  {q:"Wie viele kcal hat 100g Acai-Beeren?",a:534,unit:"kcal",hint:"Überraschend kalorienreich trotz 'Superfood'.",emoji:"🫐"},
  {q:"Wie viele Gramm Fett hat 100g Hüttenkäse?",a:4,unit:"Gramm",hint:"Sehr fettarm und proteinreich.",emoji:"🧀"},
  {q:"Wie viele kcal hat ein Glas Buttermilch (200ml)?",a:66,unit:"kcal",hint:"Kalorienarm und proteinreich.",emoji:"🥛"},
  {q:"Wie viele Gramm Zucker hat eine Flasche Gatorade (500ml)?",a:34,unit:"Gramm",hint:"Ähnlich wie eine Dose Limo.",emoji:"🏃"},
  {q:"Wie viele Tonnen Avocado importiert Europa pro Jahr?",a:1000000,unit:"Tonnen",hint:"1 Million Tonnen – der Boom hält an.",emoji:"🥑"},
  {q:"Wie viele kcal hat 100g Joghurt mit Früchten?",a:100,unit:"kcal",hint:"Fruchtjoghurt hat mehr als Naturjoghurt.",emoji:"🫙"},
  {q:"Wie viele Gramm Protein hat 100g Edamame?",a:11,unit:"Gramm",hint:"Unreife Sojabohnen – ideal als Snack.",emoji:"🫘"}
];
