// 🍆 SEX & TABUS – Erwachsene – 250 Fragen
export default [
  {q:"Wie viele Millionen Pornos gibt es schätzungsweise im Internet?",a:4000000,unit:"Videos",hint:"Über 4 Millionen Videos – und täglich kommen neue dazu.",emoji:"🔞"},
  {q:"Wie viele Millionen Besucher hat Pornhub pro Tag?",a:130,unit:"Millionen",hint:"Einer der meistbesuchten Websites weltweit.",emoji:"💻"},
  {q:"Wie viele Gramm wiegt ein durchschnittlicher Dildo?",a:200,unit:"Gramm",hint:"Variiert stark je nach Material und Größe.",emoji:"🍆"},
  {q:"In welchem Jahr wurde das erste Kondom aus Latex hergestellt?",a:1920,unit:"Jahr",hint:"Davor waren Kondome aus Schafsdarm.",emoji:"💊"},
  {q:"Wie viele Kalorien verbrennt man beim Oralsex pro Stunde?",a:100,unit:"kcal",hint:"Mehr als man denkt – Muskeln sind im Einsatz.",emoji:"🔥"},
  {q:"Wie viele cm ist der durchschnittliche erigierte Penis in Deutschland?",a:14.5,unit:"cm",hint:"Deutsche Männer liegen leicht über dem globalen Schnitt.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen weltweit sind an HIV infiziert?",a:39,unit:"Millionen",hint:"Stand 2022 – antiretrovirale Therapie hilft.",emoji:"🎗️"},
  {q:"Wie lange dauert der durchschnittliche Geschlechtsakt laut Studie in Minuten?",a:5.4,unit:"Minuten",hint:"Von Penetration bis Ejakulation gemessen.",emoji:"⏱️"},
  {q:"Wie viele Millionen Spermien enthält ein durchschnittlicher Ejakulationsschuss?",a:250,unit:"Millionen",hint:"Nur eines davon befruchtet die Eizelle.",emoji:"🔬"},
  {q:"In welchem Jahr wurde Viagra zugelassen?",a:1998,unit:"Jahr",hint:"FDA-Zulassung am 27. März 1998.",emoji:"💊"},
  {q:"Wie viele Nervenendigungen hat die Klitoris?",a:8000,unit:"Nervenenden",hint:"Doppelt so viele wie der Penis.",emoji:"⚡"},
  {q:"Wie viele cm ist die durchschnittliche Vaginaltiefe in Ruhe?",a:9,unit:"cm",hint:"Erregt dehnt sie sich auf 12-15 cm aus.",emoji:"📏"},
  {q:"Wie viele Millionen Dollar wert ist die globale Sexspielzeug-Industrie?",a:33000,unit:"Mio. Dollar",hint:"33 Milliarden Dollar – wächst jährlich.",emoji:"💰"},
  {q:"Wie viele Mal pro Jahr hat ein Deutscher durchschnittlich Sex?",a:98,unit:"Mal",hint:"Fast zweimal pro Woche laut Umfragen.",emoji:"❤️"},
  {q:"Wie viele Stunden im Leben verbringt ein Mensch mit Sex?",a:520,unit:"Stunden",hint:"Etwa 21 Tage – über ein Leben gerechnet.",emoji:"⏰"},
  {q:"Wie viele cm beträgt die durchschnittliche Penislänge schlaff?",a:9,unit:"cm",hint:"Im Durchschnitt 7-10 cm schlaff.",emoji:"📏"},
  {q:"In welchem Jahr wurde der erste Vibrator erfunden?",a:1880,unit:"Jahr",hint:"Ursprünglich als medizinisches Gerät für 'Hysterie'.",emoji:"⚡"},
  {q:"Wie viele Sekunden dauert die durchschnittliche weibliche Orgasmus-Kontraktion?",a:22,unit:"Sekunden",hint:"Weibliche Orgasmen dauern länger als männliche.",emoji:"🌊"},
  {q:"Wie viele Millionen Mal wird der Begriff 'sex' täglich gegoogelt?",a:8,unit:"Millionen",hint:"Einer der meistgesuchten Begriffe weltweit.",emoji:"🔍"},
  {q:"Wie viele cm lang ist die durchschnittliche Brust-Brustwarze im Durchmesser?",a:1.5,unit:"cm",hint:"Brustwarzen variieren stark in Größe und Form.",emoji:"📏"},
  {q:"In welchem Jahr wurde die Pille erfunden?",a:1960,unit:"Jahr",hint:"FDA-Zulassung 1960 – revolutionierte Frauenrechte.",emoji:"💊"},
  {q:"Wie viele Millionen Kondome werden weltweit täglich verwendet?",a:6,unit:"Millionen",hint:"Milliarden pro Jahr.",emoji:"💊"},
  {q:"Wie viele Grad Celsius erhöht sich die Körpertemperatur beim Orgasmus?",a:0.3,unit:"°C",hint:"Eine leichte aber messbare Erwärmung.",emoji:"🌡️"},
  {q:"Wie viele Millionen Menschen weltweit haben Syphilis?",a:7,unit:"Millionen",hint:"Immer noch verbreitet – trotz Antibiotika.",emoji:"🔬"},
  {q:"Wie lange dauert eine Erektion im Schnitt an?",a:30,unit:"Minuten",hint:"Inklusive aller sexuellen Aktivitäten.",emoji:"⏰"},
  {q:"Wie viele Milligramm Protein enthält Sperma pro Ejakulation?",a:300,unit:"Milligramm",hint:"Weniger als eine Tasse Milch.",emoji:"⚗️"},
  {q:"In welchem Jahr wurde das erste Sexspielzeug für Männer (Fleshlight) erfunden?",a:1995,unit:"Jahr",hint:"Patentiert von Steve Shubin.",emoji:"📅"},
  {q:"Wie viele cm ist der Abstand zwischen Klitoris und Vaginalöffnung durchschnittlich?",a:2.5,unit:"cm",hint:"Beeinflusst die Orgasmusfähigkeit.",emoji:"📏"},
  {q:"Wie viele Millionen Dollar verdient der meistbezahlte Pornodarsteller?",a:1,unit:"Mio. Dollar/Jahr",hint:"Frauen verdienen in der Branche oft mehr.",emoji:"💰"},
  {q:"Wie viele Stunden schlafen Menschen die viel Sex haben länger?",a:1,unit:"Stunde mehr",hint:"Orgasmus setzt schlaffördernde Hormone frei.",emoji:"😴"},
  {q:"Wie viele Millionen Menschen sind weltweit in der Sexarbeit tätig?",a:40,unit:"Millionen",hint:"Schätzung – schwer messbar durch Illegalität.",emoji:"🌍"},
  {q:"Wie viele cm lang ist die G-Punkt-Zone von der Vaginalöffnung?",a:5,unit:"cm",hint:"An der vorderen Vaginalwand.",emoji:"📏"},
  {q:"In welchem Jahr wurde Sexarbeit in Deutschland legalisiert?",a:2002,unit:"Jahr",hint:"Das Prostitutionsgesetz trat am 1. Januar 2002 in Kraft.",emoji:"📜"},
  {q:"Wie viele Millionen Besucher hat OnlyFans?",a:220,unit:"Millionen",hint:"Registrierte Nutzer – mit 2,5 Mio. Creators.",emoji:"📱"},
  {q:"Wie viele Gramm wiegt ein Durchschnitts-Hoden?",a:20,unit:"Gramm",hint:"Beide Hoden zusammen wiegen 40 Gramm.",emoji:"⚖️"},
  {q:"In welchem Jahr wurde der erste Erotik-Film gedreht?",a:1896,unit:"Jahr",hint:"Le Coucher de la Mariée – 7 Minuten lang.",emoji:"🎬"},
  {q:"Wie viele Mal pro Nacht hat ein gesunder Mann eine Erektion im Schlaf?",a:4,unit:"Mal",hint:"NPT – nächtliche penile Tumeszenz.",emoji:"😴"},
  {q:"Wie viele cm ist die durchschnittliche Brust in Deutschland (Körbchen)?",a:75,unit:"cm Unterbrustweite",hint:"Körbchen B/C ist am häufigsten in Deutschland.",emoji:"👙"},
  {q:"Wie viele Millionen Dollar wert ist der globale Erotik-Literatur-Markt?",a:1500,unit:"Mio. Dollar",hint:"Fifty Shades of Grey allein brachte Milliarden.",emoji:"📚"},
  {q:"Wie lange dauert der Samenerguss durchschnittlich in Sekunden?",a:8,unit:"Sekunden",hint:"Die Muskelkontraktionen dauern 3-15 Sekunden.",emoji:"⏱️"},
  {q:"Wie viele Millionen Deutschen geben an, regelmäßig Pornos zu schauen?",a:25,unit:"Millionen",hint:"Jeder dritte Deutsche.",emoji:"📺"},
  {q:"Wie viele cm beträgt der durchschnittliche Brust-Umfang einer Frau in Deutschland?",a:97,unit:"cm",hint:"Brustumfang variiert stark.",emoji:"📏"},
  {q:"In welchem Jahr erschien Fifty Shades of Grey?",a:2011,unit:"Jahr",hint:"E.L. James' BDSM-Roman wurde zum Weltbestseller.",emoji:"📖"},
  {q:"Wie viele Millionen Exemplare verkaufte Fifty Shades of Grey?",a:150,unit:"Millionen",hint:"Eines der meistverkauften Bücher aller Zeiten.",emoji:"📚"},
  {q:"Wie viele cm ist die durchschnittliche weibliche Brustwarze lang?",a:1,unit:"cm",hint:"Im Ruhezustand etwa 1 cm.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen in Deutschland haben schon Analverkehr praktiziert?",a:20,unit:"Millionen",hint:"Etwa 35-40% der Bevölkerung.",emoji:"📊"},
  {q:"Wie viele Grad Celsius wird die Klitoris beim Orgasmus wärmer?",a:2,unit:"°C",hint:"Messbar durch Infrarotthermografie.",emoji:"🌡️"},
  {q:"Wie viele Stunden schaut ein Durchschnittsdeutscher Pornos pro Monat?",a:4,unit:"Stunden",hint:"Laut anonymen Nutzungsdaten.",emoji:"📺"},
  {q:"In welchem Jahr wurde Sex in der Raumstation ISS zum ersten Mal theoretisch diskutiert?",a:2006,unit:"Jahr",hint:"NASA-Studie über Sex im All.",emoji:"🚀"},
  {q:"Wie viele Millionen Menschen haben eine Sexsucht?",a:16,unit:"Millionen",hint:"3-6% der Bevölkerung – hauptsächlich Männer.",emoji:"🔬"},
  {q:"Wie viele cm lang ist die durchschnittliche erigierte Klitoris?",a:10,unit:"cm",hint:"Die innere Struktur – nicht nur die sichtbare Eichel.",emoji:"📏"},
  {q:"In welchem Jahr wurde das erste Bordell der Geschichte dokumentiert?",a:600,unit:"v.Chr.",hint:"Im antiken Griechenland unter Solon.",emoji:"🏛️"},
  {q:"Wie viele Millionen Dollar kostete die Produktion von Fifty Shades of Grey (Film)?",a:40,unit:"Mio. Dollar",hint:"Und spielte 569 Mio. Dollar ein.",emoji:"🎬"},
  {q:"Wie viele Gramm wiegt eine Prostata?",a:25,unit:"Gramm",hint:"Im Alter kann sie auf 100g wachsen.",emoji:"⚖️"},
  {q:"In welchem Jahr wurde das erste legal produzierte Porno-Video verkauft?",a:1972,unit:"Jahr",hint:"Deep Throat – der erste Mainstream-Pornofilm.",emoji:"🎬"},
  {q:"Wie viele cm ist der Menstrual-Cup durchschnittlich groß?",a:7,unit:"cm",hint:"Umweltfreundliche Alternative zu Tampons.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen schauen täglich Pornos auf mobilen Geräten?",a:90,unit:"Millionen",hint:"Über 70% des Traffics kommt von Smartphones.",emoji:"📱"},
  {q:"Wie viele Stunden Porno werden täglich auf Pornhub hochgeladen?",a:115,unit:"Stunden",hint:"Täglich neue Inhalte.",emoji:"📹"},
  {q:"In welchem Jahr wurde das erste Kondom aus Kunststoff (Polyurethan) eingeführt?",a:1994,unit:"Jahr",hint:"Alternative für Latex-Allergiker.",emoji:"💊"},
  {q:"Wie viele ml Vaginalflüssigkeit produziert eine Frau beim Sex?",a:4,unit:"ml",hint:"Natürliche Befeuchtungsreaktion.",emoji:"💧"},
  {q:"Wie viele Millionen Dollar verdiente die Pornodarstellerin Lisa Ann auf ihrem Höhepunkt?",a:1.5,unit:"Mio. Dollar/Jahr",hint:"Einem der bekanntesten Stars der Branche.",emoji:"💰"},
  {q:"Wie viele cm ist die Vagina beim Squirting gedehnt?",a:15,unit:"cm",hint:"Dehnung durch Erregung.",emoji:"📏"},
  {q:"In welchem Jahr wurde die erste Penisvergrößerungsoperation dokumentiert?",a:1971,unit:"Jahr",hint:"Chirurgische Eingriffe seit den 1970ern.",emoji:"🏥"},
  {q:"Wie viele Millionen Dollar wert ist der globale Markt für Erotik-Videospiele?",a:100,unit:"Mio. Dollar",hint:"Nische aber wachsend.",emoji:"🎮"},
  {q:"Wie viele Milligramm Fruchtzucker enthält Sperma?",a:2.5,unit:"mg",hint:"Frukose gibt Spermien Energie.",emoji:"⚗️"},
  {q:"In welchem Jahr wurde die erste Sexklinik in Deutschland eröffnet?",a:1918,unit:"Jahr",hint:"Magnus Hirschfeld eröffnete das Institut für Sexualwissenschaft.",emoji:"🏥"},
  {q:"Wie viele cm beträgt die durchschnittliche Vaginaltiefe beim Sex (erregt)?",a:13,unit:"cm",hint:"Von 9cm in Ruhe auf 12-15cm erregt.",emoji:"📏"},
  {q:"Wie viele Millionen Pornhub-Suchanfragen kommen täglich aus Deutschland?",a:10,unit:"Millionen",hint:"Deutschland gehört zu den Top-Konsumenten.",emoji:"🔍"},
  {q:"Wie viele Sekunden dauert der längste bekannte Orgasmus in Sekunden?",a:43,unit:"Sekunden",hint:"Gemessen im Labor (Stand ~2024).",emoji:"⏱️"},
  {q:"In welchem Jahr wurde das erste Sexdolls-Unternehmen gegründet?",a:1997,unit:"Jahr",hint:"RealDoll aus San Diego war der Pionier.",emoji:"🤖"},
  {q:"Wie viele cm Länge hat ein durchschnittlicher Vibrator?",a:18,unit:"cm",hint:"Der Klassiker.",emoji:"📏"},
  {q:"Wie viele Millionen Dollar Umsatz macht die BDSM-Industrie?",a:500,unit:"Mio. Dollar",hint:"Bondage, Dominanz, Sadismus, Masochismus.",emoji:"🔗"},
  {q:"Wie viele Milligramm Zink enthält eine Ejakulation?",a:5,unit:"mg",hint:"Milligramm – essenziell für Spermienqualität.",emoji:"⚗️"},
  {q:"In welchem Jahr gründete Hugh Hefner das Playboy-Magazin?",a:1953,unit:"Jahr",hint:"Marilyn Monroe war auf dem ersten Cover.",emoji:"🐰"},
  {q:"Wie viele Millionen Pornhub-Suchanfragen gehen täglich ein?",a:100,unit:"Millionen",hint:"Millionen täglich – eine gigantische Zahl.",emoji:"🔍"},
  {q:"Wie viele cm lang ist ein durchschnittlicher Anal-Plug?",a:10,unit:"cm",hint:"Viele Variationen – von klein bis groß.",emoji:"📏"},
  {q:"Wie viele Stunden im Leben verbringt ein Mensch mit Masturbation (Männer)?",a:7000,hint:"Fast 300 Tage über ein Leben.",unit:"Stunden",emoji:"📊"},
  {q:"In welchem Jahr wurde der Begriff 'Bisexualität' erstmals wissenschaftlich verwendet?",a:1892,unit:"Jahr",hint:"Von Charles Gilbert Chaddock.",emoji:"🔬"},
  {q:"Wie viele Millionen Dollar wert ist der globale Markt für Lubricants?",a:800,unit:"Mio. Dollar",hint:"Gleitmittel sind ein riesiger Markt.",emoji:"💰"},
  {q:"Wie viele cm ist die durchschnittliche Zungenlänge beim Küssen relevant?",a:10,unit:"cm",hint:"Franzosenkuss beinhaltet die halbe Zunge.",emoji:"💋"},
  {q:"In welchem Jahr wurde das erste Nackt-Fotoshooting in einer Zeitschrift veröffentlicht?",a:1896,unit:"Jahr",hint:"In frühen Kunstzeitschriften.",emoji:"📸"},
  {q:"Wie viele Gramm wiegt die Gebärmutter?",a:70,unit:"Gramm",hint:"Im Nicht-Schwanger-Zustand.",emoji:"⚖️"},
  {q:"Wie viele Millionen Menschen haben Gonorrhoe weltweit?",a:82,unit:"Millionen",hint:"Eine der häufigsten STIs.",emoji:"🔬"},
  {q:"Wie viele cm lang ist die durchschnittliche Penisvorhaut?",a:5,unit:"cm",hint:"Variiert stark.",emoji:"📏"},
  {q:"In welchem Jahr wurde der erste Homosexuellen-Club in Deutschland eröffnet?",a:1897,unit:"Jahr",hint:"Hirschfelds Wissenschaftlich-humanitäres Komitee.",emoji:"🌈"},
  {q:"Wie viele Millionen Menschen schauen täglich Pornos auf Arbeit?",a:30,unit:"Millionen",hint:"Überraschend viele Nutzer weltweit.",emoji:"💼"},
  {q:"Wie viele Gramm wiegen beide Brüste einer C-Körbchen-Frau zusammen?",a:500,unit:"Gramm",hint:"Etwa 500g – je nach Größe.",emoji:"⚖️"},
  {q:"Wie viele Stunden dauert die durchschnittliche Honeymoon-Nacht in Stunden?",a:3,unit:"Stunden",hint:"Mehr Schlafen als gedacht.",emoji:"🌙"},
  {q:"In welchem Jahr wurde der erste Swingerclub in Deutschland eröffnet?",a:1971,unit:"Jahr",hint:"In den liberalen 70ern.",emoji:"🕺"},
  {q:"Wie viele cm ist die durchschnittliche Länge eines Liebeskugel-Sets?",a:20,unit:"cm",hint:"Liebeskugeln für Beckenboden-Training.",emoji:"📏"},
  {q:"Wie viele Millionen Accounts gibt es auf OnlyFans?",a:220,unit:"Millionen",hint:"Nutzer plus Creator-Accounts.",emoji:"📱"},
  {q:"In welchem Jahr wurde der erste Striptease-Club in den USA eröffnet?",a:1969,unit:"Jahr",hint:"In San Francisco während der Sexual Revolution.",emoji:"💃"},
  {q:"Wie viele Gramm wiegt ein Strap-on-Dildo durchschnittlich?",a:300,unit:"Gramm",hint:"Je nach Material zwischen 200-500g.",emoji:"⚖️"},
  {q:"Wie viele cm ist die durchschnittliche Penisbreite erigiert?",a:12,unit:"cm Umfang",hint:"Der Umfang variiert stärker als die Länge.",emoji:"📏"},
  {q:"Wie viele Millionen Euro generiert die deutsche Sexarbeit pro Jahr?",a:15000,unit:"Mio. Euro",hint:"15 Milliarden Euro jährlich in Deutschland.",emoji:"💶"},
  {q:"In welchem Jahr wurde das erste weibliche Kondom zugelassen?",a:1993,unit:"Jahr",hint:"FDA-Zulassung 1993.",emoji:"💊"},
  {q:"Wie viele cm ist die durchschnittliche Klitoris-Vorhaut lang?",a:0.5,unit:"cm",hint:"Das Präputium Clitoridis.",emoji:"📏"},
  {q:"Wie viele Millionen Escorts sind weltweit tätig?",a:1,unit:"Million",hint:"Schätzungen – exakte Zahlen nicht messbar.",emoji:"💼"},
  {q:"Wie viele Stunden hat der weltlängste gemessene Geschlechtsakt gedauert?",a:15,unit:"Stunden",hint:"Dokumentiert in einer Studie (Stand ~2024).",emoji:"⏰"},
  {q:"In welchem Jahr wurde das Phänomen 'Female Ejaculation' wissenschaftlich anerkannt?",a:1982,unit:"Jahr",hint:"Erstmals 1982 wissenschaftlich beschrieben.",emoji:"🔬"},
  {q:"Wie viele cm ist der kürzeste klinisch dokumentierte erigierte Penis?",a:1,unit:"cm",hint:"Mikropenis wird unter 7cm erigiert definiert.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen haben Chlamydien weltweit?",a:127,unit:"Millionen",hint:"Die häufigste bakterielle STI.",emoji:"🔬"},
  {q:"In welchem Jahr gründete Alfred Kinsey sein Sexualforschungsinstitut?",a:1947,unit:"Jahr",hint:"Das Kinsey Institute in Indiana.",emoji:"🔬"},
  {q:"Wie viele cm ist die längste dokumentierte erigierte Penislänge?",a:34,unit:"cm",hint:"Jonah Falcon aus New York (Stand ~2024).",emoji:"📏"},
  {q:"Wie viele Millionen Dollar wert ist der globale Markt für Potenzpillen?",a:6000,unit:"Mio. Dollar",hint:"Viagra, Cialis und Generika.",emoji:"💊"},
  {q:"Wie viele Minuten dauert Vorspiel durchschnittlich laut Studien?",a:18,unit:"Minuten",hint:"Zu wenig laut den meisten Frauen.",emoji:"⏱️"},
  {q:"In welchem Jahr wurde das erste Sex-Museum in Amsterdam eröffnet?",a:1985,unit:"Jahr",hint:"Das Sexmuseum Amsterdam.",emoji:"🏛️"},
  {q:"Wie viele cm lang ist die durchschnittliche Analöffnung beim Entspanntsein?",a:3,unit:"cm",hint:"Kann durch Training und Entspannung größer werden.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen sind in der Welt als Transfrau oder Transmann identifiziert?",a:25,unit:"Millionen",hint:"Schätzungen variieren – weltweit ~0,3% der Bevölkerung.",emoji:"🏳️‍⚧️"},
  {q:"Wie viele Milligramm wiegt eine Geburtskontrollpille?",a:30,unit:"Milligramm",hint:"Milligramm täglich – winzig aber wirkungsvoll.",emoji:"⚖️"},
  {q:"In welchem Jahr wurde das erste FKK-Gelände in Deutschland eröffnet?",a:1920,unit:"Jahr",hint:"Die Freikörperkultur begann in den 20ern.",emoji:"🌞"},
  {q:"Wie viele ml fasst ein Analplug durchschnittlich?",a:100,unit:"ml",hint:"Variiert je nach Größe.",emoji:"💧"},
  {q:"Wie viele Millionen Euro Umsatz macht der deutsche Sexspielzeug-Markt?",a:400,unit:"Mio. Euro",hint:"Wächst jährlich um 10%.",emoji:"💶"},
  {q:"In welchem Jahr wurde der Kegel-Beckenboden-Trainer erfunden?",a:1948,unit:"Jahr",hint:"Dr. Arnold Kegel entwickelte die Übungen.",emoji:"💪"},
  {q:"Wie viele cm ist die durchschnittliche Länge eines Butt-Plugs?",a:10,unit:"cm",hint:"Je nach Größe und Erfahrung.",emoji:"📏"},
  {q:"Wie viele Millionen Kondome werden in Deutschland pro Jahr verkauft?",a:200,unit:"Millionen",hint:"Sinkende Tendenz durch Pille und IUDs.",emoji:"💊"},
  {q:"In welchem Jahr erschien das Kamasutra in Europa erstmals?",a:1883,unit:"Jahr",hint:"Richard Burton übersetzte es ins Englische.",emoji:"📖"},
  {q:"Wie viele Positionen beschreibt das Kamasutra?",a:64,unit:"Positionen",hint:"Viele davon sind für den Alltag kaum praktisch.",emoji:"📖"},
  {q:"Wie viele cm ist die längste dokumentierte Vaginaltiefe?",a:20,unit:"cm",hint:"Starke individuelle Variation (Stand ~2024).",emoji:"📏"},
  {q:"Wie viele Millionen Dollar wert ist der globale Markt für Sex-Drogen (Aphrodisiaka)?",a:2000,unit:"Mio. Dollar",hint:"Rhino-Produkte, Oyster-Extrakte und mehr.",emoji:"💊"},
  {q:"Wie viele Stunden braucht der Körper um sich nach dem Sex zu erholen?",a:2,unit:"Stunden",hint:"Bis Herzschlag und Hormone normalisiert sind.",emoji:"💓"},
  {q:"In welchem Jahr wurde die erste Sextherapie-Praxis in Deutschland eröffnet?",a:1975,unit:"Jahr",hint:"Nach Masters & Johnson's Forschungen.",emoji:"🏥"},
  {q:"Wie viele cm groß ist ein durchschnittlicher Brustnippel?",a:0.5,unit:"cm Höhe",hint:"Variiert stark von Person zu Person.",emoji:"📏"},
  {q:"Wie viele Millionen Dollar hat die Pornodarstellerin Mia Khalifa insgesamt verdient?",a:12,unit:"Tausend Dollar",hint:"Nur 12.000 Dollar in ihrer kurzen Karriere.",emoji:"💰"},
  {q:"Wie viele Gramm Glukose werden beim Sex verbrannt?",a:8,unit:"Gramm",hint:"Entspricht einem kleinen Stück Schokolade.",emoji:"🍫"},
  {q:"In welchem Jahr wurde das erste Porno-Magazin (Playboy) gegründet?",a:1953,unit:"Jahr",hint:"Hugh Hefner startete eine Revolution.",emoji:"🐰"},
  {q:"Wie viele Millionen Menschen identifizieren sich weltweit als homosexuell?",a:390,unit:"Millionen",hint:"Ca. 5% der Weltbevölkerung.",emoji:"🌈"},
  {q:"Wie viele Minuten Vorspiel brauchen Frauen durchschnittlich für einen Orgasmus?",a:20,unit:"Minuten",hint:"Minuten Stimulation im Schnitt.",emoji:"⏱️"},
  {q:"In welchem Jahr wurde der Analverkehr in Deutschland legalisiert?",a:1969,unit:"Jahr",hint:"Paragraf 175 wurde reformiert.",emoji:"📜"},
  {q:"Wie viele cm ist ein durchschnittlicher Liebeskugelstrang lang?",a:25,unit:"cm",hint:"Verbundene Kugeln für Beckenboden.",emoji:"📏"},
  {q:"Wie viele Millionen Euro wert ist der deutsche Erotik-Film-Markt?",a:200,unit:"Mio. Euro",hint:"Produktionen aus Deutschland.",emoji:"🎬"},
  {q:"In welchem Jahr erschien das erste weiblich geschriebene Erotik-Buch (Lady Chatterley)?",a:1928,unit:"Jahr",hint:"D.H. Lawrence schrieb es – war jahrzehntelang verboten.",emoji:"📚"},
  {q:"Wie viele cm ist die Basis eines durchschnittlichen Vibrators?",a:4,unit:"cm",hint:"Breiter unten für sicheres Halten.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen in Deutschland haben sexuelle Dysfunktionen?",a:10,unit:"Millionen",hint:"Breites Spektrum – viele suchen keine Hilfe.",emoji:"🔬"},
  {q:"Wie viele cm ist der Abstand zwischen Anus und Vaginalöffnung (Perineum)?",a:3,unit:"cm",hint:"Das Perineum variiert individuell.",emoji:"📏"},
  {q:"Wie viele Millionen Dollar hat Hustler Magazine auf seinem Höhepunkt verdient?",a:50,unit:"Mio. Dollar/Jahr",hint:"Larry Flynts Sexmagazin in den 80ern.",emoji:"💰"},
  {q:"Wie viele Stunden im Monat schauen Singles mehr Pornos als Paare?",a:4,unit:"Stunden",hint:"Singles konsumieren deutlich mehr.",emoji:"📊"},
  {q:"Wie viele cm ist die durchschnittliche Brust in Österreich (Körbchengröße)?",a:80,unit:"cm Unterbrustweite",hint:"Ähnlich wie in Deutschland.",emoji:"👙"},
  {q:"Wie viele Millionen Nutzer hat Grindr weltweit?",a:13,unit:"Millionen",hint:"Die bekannteste Gay-Dating-App.",emoji:"📱"},
  {q:"Wie viele cm lang ist der durchschnittliche Klitoris-Stiel?",a:3,unit:"cm",hint:"Der innere Teil des Klitoriskörpers.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen nutzen Swingerclub-Apps weltweit?",a:2,unit:"Millionen",hint:"Spezialisierte Apps für Lifestyler.",emoji:"📱"},
  {q:"Wie viele Gramm wiegt ein Durchschnitts-Ovarium (Eierstock)?",a:14,unit:"Gramm",hint:"Beide zusammen etwa 28 Gramm.",emoji:"⚖️"},
  {q:"Wie viele ml Vaginalflüssigkeit produziert eine Frau beim Squirting?",a:200,unit:"ml",hint:"Variiert stark – von wenig bis sehr viel.",emoji:"💧"},
  {q:"Wie viele Stunden im Monat verbringen Singles mit Dating-Apps?",a:10,unit:"Stunden",hint:"Viel Zeit fürs digitale Dating.",emoji:"📱"},
  {q:"Wie viele cm ist das durchschnittliche Hymen von der Vaginalöffnung entfernt?",a:2,unit:"cm",hint:"Das Hymen ist ein dünnes Schleimhautgewebe.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen haben eine Sexallergie (Seminalplasma)?",a:40,unit:"Tausend",hint:"000 Menschen – Allergie gegen Sperma-Proteine.",emoji:"🔬"},
  {q:"Wie viele Grad Celsius wärmer ist der Vaginalkanal während des Orgasmus?",a:0.5,unit:"°C",hint:"Messbar durch präzise Thermometer.",emoji:"🌡️"},
  {q:"Wie viele Millionen Menschen haben vaginismus (Scheidenverkrampfen)?",a:15,unit:"Millionen",hint:"Eine häufige aber wenig diskutierte Erkrankung.",emoji:"🔬"},
  {q:"Wie viele Gramm wiegt das Clitoris-Schwellkörpernetz?",a:20,unit:"Gramm",hint:"Das gesamte Klitorissystem.",emoji:"⚖️"},
  {q:"Wie viele Minuten braucht der Mann durchschnittlich nach dem Orgasmus bis zur nächsten Erektion?",a:30,unit:"Minuten",hint:"Minuten Refraktärzeit bei jungen Männern.",emoji:"⏰"},
  {q:"Wie viele Millionen Menschen praktzieren Bondage weltweit?",a:100,unit:"Millionen",hint:"BDSM in verschiedenen Formen.",emoji:"🔗"},
  {q:"Wie viele cm ist die Länge eines erigierten Klitoriskörpers?",a:10,unit:"cm",hint:"Viel größer als sichtbar.",emoji:"📏"},
  {q:"Wie viele mg Oxytocin werden beim Orgasmus ausgeschüttet?",a:0.001,unit:"mg",hint:"Winzige Menge – aber starke Bindungswirkung.",emoji:"⚗️"},
  {q:"Wie viele Stunden Schlaf verbessern die Sexualfunktion?",a:8,unit:"Stunden",hint:"Ausreichend Schlaf ist entscheidend.",emoji:"😴"},
  {q:"Wie viele Millionen Menschen nutzen Fetlife weltweit?",a:10,unit:"Millionen",hint:"Das größte BDSM-soziale Netzwerk.",emoji:"🔗"},
  {q:"Wie viele Gramm Elastin hat das Vaginalgewebe?",a:1,unit:"Gramm",hint:"Elastin ermöglicht die Dehnung bei der Geburt.",emoji:"⚗️"},
  {q:"Wie viele ml Schmierung produziert die Bartholin-Drüse beim Sex?",a:2,unit:"ml",hint:"Natürliche Gleitfähigkeit.",emoji:"💧"},
  {q:"Wie viele Millionen Spermatozoen überleben nach der Ejakulation maximal?",a:1,unit:"Millionen",hint:"Von 250 Millionen überleben nur die Stärksten.",emoji:"🔬"},
  {q:"Wie viele Stunden im Jahr verbringt ein Mensch mit romantischen Aktivitäten?",a:730,unit:"Stunden",hint:"2 Stunden täglich an Romantik und Intimität.",emoji:"❤️"},
  {q:"Wie viele cm ist die Vorhaut im erigierten Zustand lang?",a:12,unit:"cm",hint:"Die Vorhaut kann bis zur Hälfte des Penis bedecken.",emoji:"📏"},
  {q:"Wie viele Millionen Menschen haben Erektionsprobleme weltweit?",a:320,unit:"Millionen",hint:"Fast ein Drittel aller Männer irgendwann.",emoji:"🔬"},
  {q:"Wie viele Millimeter ist ein durchschnittliches Spermium lang?",a:0.05,unit:"mm",hint:"50 Mikrometer – mit Schwanzanteil.",emoji:"🔬"},
  {q:"Wie viele Stunden schlafen Menschen nach gutem Sex besser?",a:1,unit:"Stunde mehr",hint:"Orgasmus fördert Schlaf durch Oxytocin.",emoji:"😴"},
  {q:"Wie viele ml Vaginalflüssigkeit produziert eine Frau täglich?",a:2,unit:"ml",hint:"Normal ist 1-4 ml täglich.",emoji:"💧"},
  {q:"Wie viele cm ist der maximale Umfang eines erigierten Penis im Rekord?",a:25,unit:"cm",hint:"Extremfälle sind dokumentiert (Stand ~2024).",emoji:"📏"},
  {q:"Wie viele Millionen Menschen leiden weltweit an sexuellen Angststörungen?",a:30,unit:"Millionen",hint:"Sexangst – nicht selten.",emoji:"🔬"},
  {q:"Wie viele Stunden im Leben verbringt ein Mensch mit Masturbation (Frauen)?",a:2000,unit:"Stunden",hint:"Weniger als Männer – aber erheblich.",emoji:"📊"},
  {q:"Wie viele mg Östradiol enthält eine normale Verhütungspille täglich?",a:0.03,unit:"mg",hint:"30 Mikrogramm – sehr niedrige Dosis.",emoji:"💊"},
  {q:"Wie viele Millionen Menschen sind Teil der Polyamorie-Bewegung?",a:21,unit:"Millionen",hint:"Schätzung in den USA allein.",emoji:"💕"}
];
