// 🚀 WELTRAUM – Kinder
export default [
  {id:"kwelt_001",q:"Wie viele Planeten gibt es in unserem Sonnensystem?",a:8,unit:"Planeten",hint:"Pluto ist seit 2006 kein Planet mehr.",emoji:"🪐"},
  {id:"kwelt_002",q:"Wie viele Minuten braucht Sonnenlicht bis zur Erde?",a:8,unit:"Minuten",hint:"Licht reist mit 300.000 km pro Sekunde.",emoji:"☀️"},
  {id:"kwelt_003",q:"Wie viele Monde hat der Saturn?",a:146,unit:"Monde",hint:"Saturn hat die meisten Monde aller Planeten.",emoji:"🪐"},
  {id:"kwelt_004",q:"Wie weit ist die Erde von der Sonne entfernt in Millionen km?",a:150,unit:"Millionen km",hint:"Diese Entfernung nennt man 1 Astronomische Einheit.",emoji:"☀️"},
  {id:"kwelt_005",q:"Wie viele Grad Celsius ist es auf dem Mond nachts?",a:-170,unit:"°C",hint:"Tagsüber sind es +130°C.",emoji:"🌙"},
  {id:"kwelt_006",q:"Wie viele Milliarden Sterne hat unsere Milchstraße?",a:200,unit:"Milliarden",hint:"Milliarden Sterne in der Milchstraße allein.",emoji:"⭐"},
  {id:"kwelt_007",q:"Wie alt ist das Universum in Milliarden Jahren?",a:13.8,unit:"Milliarden Jahre",hint:"Seit dem Urknall.",emoji:"🌌"},
  {id:"kwelt_008",q:"Wie viele km ist der Mond von der Erde entfernt?",a:384.4,unit:"Tausend km",hint:"Apollo-Astronauten brauchten 3 Tage.",emoji:"🌙"},
  {id:"kwelt_009",q:"Wie hoch fliegt die ISS über der Erde in km?",a:400,unit:"km",hint:"Sie umkreist die Erde alle 90 Minuten.",emoji:"🚀"},
  {id:"kwelt_010",q:"Wie viele Erdmassen hat Jupiter?",a:318,unit:"Erdmassen",hint:"Jupiter ist diese Zahl Mal so schwer wie die Erde.",emoji:"🪐"},
  {id:"kwelt_011",q:"Wie viele Monate dauert ein Jahr auf dem Mars?",a:24,unit:"Erdmonate",hint:"Ein Marsjahr = 687 Erdtage.",emoji:"🔴"},
  {id:"kwelt_012",q:"Wie viele km/h bewegt sich die Erde um die Sonne?",a:107000,unit:"km/h",hint:"Das sind 30 km pro Sekunde.",emoji:"🌍"},
  {id:"kwelt_013",q:"Wie viele km beträgt der Durchmesser der Erde?",a:12742,unit:"km",hint:"Am Äquator ist sie etwas dicker als an den Polen.",emoji:"🌍"},
  {id:"kwelt_014",q:"Wie heiß ist die Oberfläche der Sonne in °C?",a:5500,unit:"°C",hint:"Im Kern sind es 15 Millionen Grad.",emoji:"☀️"},
  {id:"kwelt_015",q:"Wie lange dauerte die erste Mondlandung in Stunden auf dem Mond?",a:21,unit:"Stunden",hint:"Neil Armstrong und Buzz Aldrin am 20. Juli 1969.",emoji:"🌙"},
  {id:"kwelt_016",q:"Wie viele km beträgt der Umfang der Erde am Äquator?",a:40075,unit:"km",hint:"Die Erde ist nicht perfekt rund.",emoji:"🌍"},
  {id:"kwelt_017",q:"Wie viele Astronauten waren bisher auf dem Mond?",a:12,unit:"Astronauten",hint:"Alle 12 waren Amerikaner bei den Apollo-Missionen.",emoji:"👨‍🚀"},
  {id:"kwelt_018",q:"Wie viele Ringe hat Saturn?",a:7,unit:"Hauptringe",hint:"Die Ringe bestehen aus Eis und Gestein.",emoji:"🪐"},
  {id:"kwelt_019",q:"Wie viele Monde hat der Mars?",a:2,unit:"Monde",hint:"Phobos und Deimos – beide sehr klein.",emoji:"🔴"},
  {id:"kwelt_020",q:"Wie viele km/h muss eine Rakete fliegen um die Erde zu verlassen?",a:40000,unit:"km/h",hint:"Das ist die Fluchtgeschwindigkeit der Erde.",emoji:"🚀"},
  {id:"kwelt_021",q:"Wie groß ist der Große Rote Fleck auf Jupiter in km?",a:16000,unit:"km",hint:"Ein Sturm, der seit 350 Jahren tobt.",emoji:"🪐"},
  {id:"kwelt_022",q:"Wie viele km beträgt der Durchmesser der Sonne?",a:1.39,unit:"Millionen km",hint:"Die Sonne ist 109 Mal so breit wie die Erde.",emoji:"☀️"},
  {id:"kwelt_023",q:"Wie schnell dreht sich die Erde am Äquator in km/h?",a:1670,unit:"km/h",hint:"Wir spüren die Rotation nicht, weil alles mitbewegt wird.",emoji:"🌍"},
  {id:"kwelt_024",q:"Wie viele Grad Celsius beträgt die Temperatur im Weltall?",a:-270,unit:"°C",hint:"Fast der absolute Nullpunkt von -273°C.",emoji:"❄️"},
  {id:"kwelt_025",q:"Wie weit ist Alpha Centauri von der Erde in Lichtjahren?",a:4,unit:"Lichtjahre",hint:"Das nächste Sternensystem nach unserem.",emoji:"⭐"},
  {id:"kwelt_026",q:"Wie viele Stunden dauert ein Tag auf der Venus?",a:5832,unit:"Stunden",hint:"Ein Venusjahr ist kürzer als ein Venustag!",emoji:"🪐"},
  {id:"kwelt_027",q:"Wie lange dauert ein Tag auf dem Merkur in Erdtagen?",a:59,unit:"Erdtage",hint:"Merkur dreht sich sehr langsam um seine Achse.",emoji:"☿"},
  {id:"kwelt_028",q:"Wie viele Millionen Mal größer ist die Sonne als die Erde (Volumen)?",a:1.3,unit:"Millionen Mal",hint:"1,3 Millionen Erden würden in die Sonne passen.",emoji:"☀️"},
  {id:"kwelt_029",q:"Wie heiß ist der Kern der Erde in °C?",a:6000,unit:"°C",hint:"Ähnlich heiß wie die Oberfläche der Sonne.",emoji:"🌍"},
  {id:"kwelt_030",q:"Wie viele km/h fährt der Sonnenwind?",a:500000,unit:"km/h",hint:"Elektrisch geladene Teilchen von der Sonne.",emoji:"💨"},
{id:"kwelt_031",q:"Wie viele Monde hat Jupiter?",a:95,unit:"Monde",hint:"Stand 2023 – die meisten aller Planeten.",emoji:"🪐"},
  {id:"kwelt_032",q:"Wie schwer ist die Erde in kg (Zehnerpotenz)?",a:24,unit:"× 10^? kg",hint:"5,97 × 10^24 kg.",emoji:"🌍"},
  {id:"kwelt_033",q:"Wie viele Jahre braucht ein Licht von der Galaxis-Mitte bis zur Erde?",a:26000,unit:"Lichtjahre",hint:"Wir leben am Rand der Milchstraße.",emoji:"🌌"},
  {id:"kwelt_034",q:"Wie hoch fliegt ein Flugzeug in km?",a:10,unit:"km",hint:"Reiseflughöhe 9-12 km.",emoji:"✈️"},
  {id:"kwelt_035",q:"Wie viele Planeten hat unser Sonnensystem?",a:8,unit:"Planeten",hint:"Pluto ist seit 2006 kein Planet mehr.",emoji:"🪐"},
  {id:"kwelt_036",q:"Wie tief ist der Ozean auf Europa (Jupitermond) in km?",a:100,unit:"km",hint:"Unter dem Eis – mögliches Leben.",emoji:"❄️"},
  {id:"kwelt_037",q:"Wie viele Sterne sieht man mit bloßem Auge nachts?",a:5000,unit:"Sterne",hint:"Bei klarem Himmel ohne Lichtverschmutzung.",emoji:"⭐"},
  {id:"kwelt_038",q:"Wie lang braucht eine Rakete von der Erde zum Mond?",a:3,unit:"Tage",hint:"Apollo-Astronauten brauchten 3 Tage.",emoji:"🚀"},
  {id:"kwelt_039",q:"Wie groß ist ein Asteroid der die Erde auslöschen könnte in km?",a:10,unit:"km",hint:"Der Chicxulub-Asteroid war ~10 km groß.",emoji:"☄️"},
  {id:"kwelt_040",q:"Wie viele Stunden dauert ein Tag auf dem Mond?",a:709,unit:"Stunden",hint:"Der Mond dreht sich sehr langsam.",emoji:"🌙"},
  {id:"kwelt_041",q:"Wie kalt ist der Weltraum in °C?",a:-270,unit:"°C",hint:"Fast der absolute Nullpunkt.",emoji:"❄️"},
  {id:"kwelt_042",q:"Wie viele Satelliten umkreisen die Erde?",a:9000,unit:"Satelliten",hint:"Aktive und inaktive zusammen.",emoji:"🛰️"},
  {id:"kwelt_043",q:"Wie lange hat die erste Mondlandung gedauert auf dem Mond?",a:21,unit:"Stunden",hint:"Neil Armstrong und Buzz Aldrin.",emoji:"🌙"},
  {id:"kwelt_044",q:"Wie viele km/h braucht eine Rakete um den Mond zu erreichen?",a:40000,unit:"km/h",hint:"Die Fluchtgeschwindigkeit der Erde.",emoji:"🚀"},
  {id:"kwelt_045",q:"Wie weit ist Neptun von der Sonne entfernt in Milliarden km?",a:4.5,unit:"Milliarden km",hint:"Der fernste Planet des Sonnensystems.",emoji:"🔵"},
  {id:"kwelt_046",q:"Wie viele Monde hat Neptun?",a:16,unit:"Monde",hint:"Der größte heißt Triton.",emoji:"🔵"},
  {id:"kwelt_047",q:"Wie viele km beträgt der Durchmesser von Pluto?",a:2377,unit:"km",hint:"Kleiner als der Mond.",emoji:"🌑"},
  {id:"kwelt_048",q:"Wie lange hat das James Webb Teleskop gebaut?",a:25,unit:"Jahre",hint:"Jahre von der Idee bis zur Fertigstellung.",emoji:"🔭"},
  {id:"kwelt_049",q:"Wie hoch ist die ISS über der Erde in km?",a:400,unit:"km",hint:"Kreist alle 90 Minuten um die Erde.",emoji:"🚀"},
  {id:"kwelt_050",q:"Wie groß ist die Kármán-Linie (Grenze zum Weltraum) in km?",a:100,unit:"km",hint:"Ab 100 km beginnt offiziell der Weltraum.",emoji:"🚀"},
  {id:"kwelt_051",q:"Wie kalt ist es auf dem Triton (Neptunmond) in °C?",a:-235,unit:"°C",hint:"Einer der kältesten Körper im Sonnensystem.",emoji:"❄️"},
  {id:"kwelt_052",q:"Wie lang dauert ein Marsatmung-Monat in Tagen?",a:59,unit:"Tage",hint:"2 Marsmonate auf ein Mal.",emoji:"🔴"},
  {id:"kwelt_053",q:"Wie viele Jahre hat das Voyager 1-Raumschiff gebraucht um das Sonnensystem zu verlassen?",a:35,unit:"Jahre",hint:"Gestartet 1977 – Heliopause 2012.",emoji:"🚀"},
  {id:"kwelt_054",q:"Wie hoch ist die Schallgeschwindigkeit auf dem Mars?",a:240,unit:"m/s",hint:"Etwas langsamer als auf der Erde.",emoji:"🔴"},
  {id:"kwelt_055",q:"Wie viele km/s bewegt sich die Erde um die Sonne?",a:30,unit:"km/s",hint:"Das sind 107.000 km/h.",emoji:"🌍"},
  {id:"kwelt_056",q:"Wie groß ist ein typischer Komet-Kern in km?",a:5,unit:"km",hint:"Meistens 1-10 km groß.",emoji:"☄️"},
  {id:"kwelt_057",q:"Wie weit ist Alpha Centauri entfernt in Lichtjahren?",a:4,unit:"Lichtjahre",hint:"Das nächste Sternensystem.",emoji:"⭐"},
  {id:"kwelt_058",q:"Wie viele Stunden braucht Licht von Neptun zur Erde?",a:4,unit:"Stunden",hint:"Stunden Lichtreise.",emoji:"🔵"},
  {id:"kwelt_059",q:"Wie viele km/h dreht sich die Erde am Äquator?",a:1670,unit:"km/h",hint:"Wir spüren es nicht – alles bewegt sich mit.",emoji:"🌍"},
  {id:"kwelt_060",q:"Wie groß ist Titan (Saturnmond) im Durchmesser in km?",a:5150,unit:"km",hint:"Größer als Merkur.",emoji:"🪐"},
  {id:"kwelt_061",q:"Wie viele Ringe hat Uranus?",a:13,unit:"Ringe",hint:"Dunkler als Saturns Ringe.",emoji:"🟦"},
  {id:"kwelt_062",q:"Wie schwer ist ein m³ Sonnenkern-Material in kg?",a:150,unit:"Tausend kg",hint:"150x dichter als Wasser.",emoji:"☀️"},
  {id:"kwelt_063",q:"Wie lange haben die Apollo-Missionen insgesamt Mondgestein mitgebracht in kg?",a:382,unit:"kg",hint:"Von 6 erfolgreichen Landungen.",emoji:"🌙"},
  {id:"kwelt_064",q:"Wie viele km ist der Olympus Mons auf dem Mars hoch?",a:21,unit:"km",hint:"Der höchste Vulkan im Sonnensystem.",emoji:"🌋"},
  {id:"kwelt_065",q:"Wie groß ist die Andromeda-Galaxie im Durchmesser in Lichtjahren?",a:220000,unit:"Lichtjahre",hint:"Größer als die Milchstraße.",emoji:"🌌"},
  {id:"kwelt_066",q:"Wie viele Stunden dauert ein Jahr auf Merkur?",a:1408,unit:"Stunden",hint:"88 Tage – das kürzeste Planetenjahr.",emoji:"☿"},
  {id:"kwelt_067",q:"Wie viele km beträgt der Durchmesser von Titan?",a:5150,unit:"km",hint:"Der größte Saturnmond.",emoji:"🪐"},
  {id:"kwelt_068",q:"Wie kalt ist es auf dem Mars nachts am Pol in °C?",a:-125,unit:"°C",hint:"Kohlenstoffdioxid-Eis bildet sich dort.",emoji:"🔴"},
  {id:"kwelt_069",q:"Wie lange braucht das Licht von der Sonne bis zum Mars in Minuten?",a:13,unit:"Minuten",hint:"Je nach Abstand 3-22 Minuten.",emoji:"🔴"},
  {id:"kwelt_070",q:"Wie viele km lang ist der Valles Marineris auf dem Mars?",a:4000,unit:"km",hint:"10x länger als der Grand Canyon.",emoji:"🔴"},
  {id:"kwelt_071",q:"Wie groß ist Europa (Jupitermond) in km?",a:3122,unit:"km",hint:"Möglicherweise hat er Leben unter dem Eis.",emoji:"❄️"},
  {id:"kwelt_072",q:"Wie viele Stunden dauert ein Tag auf dem Merkur?",a:1408,unit:"Stunden",hint:"Ein Merkur-Tag ist länger als ein Merkur-Jahr!",emoji:"☿"},
  {id:"kwelt_073",q:"Wie viele Billionen Tonnen wiegt die Marsatmosphäre?",a:25,unit:"Billionen Tonnen",hint:"2,5 × 10^16 kg – sehr dünn.",emoji:"🔴"},
  {id:"kwelt_074",q:"Wie weit ist die Voyager-Sonde von der Erde entfernt in Milliarden km?",a:23,unit:"Milliarden km",hint:"Stand 2023 – immer weiter.",emoji:"🚀"},
  {id:"kwelt_075",q:"Wie viele km/h fährt die ISS um die Erde?",a:28000,unit:"km/h",hint:"Alle 90 Minuten eine Runde.",emoji:"🚀"},
  {q:"Wie groß ist der Durchmesser des Schwarzen Lochs M87* in km?",a:40000000000,hint:"Das erste fotografierte Schwarze Loch.",unit:"km",emoji:"🌑"},
  {id:"kwelt_076",q:"Wie kalt ist es in den dauerhaft beschatteten Mondkratern in °C?",a:-248,unit:"°C",hint:"Fast der absolute Nullpunkt.",emoji:"🌑"},
  {id:"kwelt_077",q:"Wie viele Jahre braucht Pluto für einen Umlauf um die Sonne?",a:248,unit:"Erdenjahre",hint:"Sehr elliptische Bahn.",emoji:"🌑"},
  {id:"kwelt_078",q:"Wie viele km/h beträgt der Sonnenwind?",a:500000,unit:"km/h",hint:"Elektrisch geladene Teilchen.",emoji:"☀️"},
  {id:"kwelt_079",q:"Wie groß ist Enceladus (Saturnmond) in km?",a:500,unit:"km",hint:"Hat Geysire aus flüssigem Wasser.",emoji:"🪐"},
  {id:"kwelt_080",q:"Wie viele Milliarden Lichtjahre groß ist das beobachtbare Universum?",a:93,unit:"Milliarden Lichtjahre",hint:"Der sichtbare Teil.",emoji:"🌌"},
  {id:"kwelt_081",q:"Wie tief ist der Ozean auf Enceladus in km?",a:10,unit:"km",hint:"Unter 40km dickem Eis.",emoji:"❄️"},
  {id:"kwelt_082",q:"Wie viele Stunden braucht Licht von Pluto zur Erde?",a:5.5,unit:"Stunden",hint:"5,5 Stunden Lichtreise.",emoji:"🌑"},
  {id:"kwelt_083",q:"Wie hoch ist der Temperaturunterschied zwischen Tag und Nacht auf dem Mond in °C?",a:300,unit:"°C",hint:"+130°C tagsüber, -170°C nachts.",emoji:"🌙"},
  {id:"kwelt_084",q:"Wie groß ist das Hubble-Teleskop in Metern?",a:13,unit:"Meter",hint:"So groß wie ein Schulbus.",emoji:"🔭"},
  {id:"kwelt_085",q:"Wie viele Astronauten waren gleichzeitig auf der ISS maximal?",a:13,unit:"Astronauten",hint:"Bei STS-127 Mission 2009.",emoji:"👨‍🚀"},
  {id:"kwelt_086",q:"Wie lang dauert ein Raumflug von der Erde zur ISS in Stunden?",a:6,unit:"Stunden",hint:"Moderne Sojus-Kapseln schaffen es in 6h.",emoji:"🚀"},
  {id:"kwelt_087",q:"Wie viele Sternschnuppen sind pro Stunde bei einem normalen Meteorschauer sichtbar?",a:10,unit:"pro Stunde",hint:"Bei stärkerem Schauer bis zu 100.",emoji:"💫"},
  {id:"kwelt_088",q:"Wie viele km beträgt der Durchmesser von Io (Jupitermond)?",a:3642,unit:"km",hint:"Der vulkanischste Körper im Sonnensystem.",emoji:"🌋"},
  {id:"kwelt_089",q:"Wie groß war der Chicxulub-Asteroid der die Dinos auslöschte in km?",a:10,unit:"km",hint:"Traf vor 66 Millionen Jahren Mexiko.",emoji:"☄️"},
  {id:"kwelt_090",q:"Wie viele Grad Celsius ist die Temperatur in einem Weißen Zwerg?",a:100000,unit:"°C",hint:"Abgestorbener Stern – kühlt über Milliarden Jahre.",emoji:"⭐"},
  {id:"kwelt_091",q:"Wie lang dauert ein Raumflug zum Mars in Monaten?",a:9,unit:"Monate",hint:"Beim günstigsten Startfenster.",emoji:"🔴"},
  {id:"kwelt_092",q:"Wie groß ist die Sonne verglichen mit dem Mond (Durchmesser)?",a:400,unit:"x größer",hint:"Aber der Mond ist um ein Vielfaches näher – daher gleich groß am Himmel.",emoji:"☀️"},
  {id:"kwelt_093",q:"Wie viele Planeten wurden außerhalb unseres Sonnensystems entdeckt?",a:5500,unit:"Exoplaneten",hint:"Stand 2023 – täglich werden neue gefunden.",emoji:"🌍"},
  {id:"kwelt_094",q:"Wie schwer ist der Mond verglichen mit der Erde in %?",a:1.2,unit:"% der Erdmasse",hint:"Der Mond ist 1,2% so schwer wie die Erde.",emoji:"🌙"},
  {id:"kwelt_095",q:"Wie viele Millionen km lang kann ein Kometenschweif sein?",a:150,unit:"Millionen km",hint:"Kometen-Schweife können so lang wie der Erde-Sonne-Abstand sein.",emoji:"☄️"},
  {id:"kwelt_096",q:"Wie viele km/h dreht sich Jupiter am Äquator?",a:45000,unit:"km/h",hint:"Die schnellste Planetenrotation.",emoji:"🪐"},
  {id:"kwelt_097",q:"Wie lang dauert ein Tag auf Neptun in Stunden?",a:16,unit:"Stunden",hint:"Kürzerer Tag als die Erde.",emoji:"🔵"},
  {id:"kwelt_098",q:"Wie weit ist das Zentrum der Milchstraße von uns in Lichtjahren?",a:26000,unit:"Lichtjahre",hint:"Sagittarius A* – ein Schwarzes Loch.",emoji:"🌌"},
  {id:"kwelt_099",q:"Wie groß ist Ganymede (Jupitermond) verglichen mit Merkur?",a:108,unit:"% größer",hint:"Ganymede ist größer als Merkur!",emoji:"🪐"},
  {id:"kwelt_100",q:"Wie viele km/s beträgt die Fluchtgeschwindigkeit der Sonne?",a:617,unit:"km/s",hint:"Km/s – fast 0,2% der Lichtgeschwindigkeit.",emoji:"☀️"},
  {id:"kwelt_101",q:"Wie kalt ist es auf dem Neptun in °C?",a:-214,unit:"°C",hint:"Der kälteste Planet des Sonnensystems.",emoji:"🔵"},
  {id:"kwelt_102",q:"Wie viele Monde entdeckte Galileo Galilei beim Jupiter?",a:4,unit:"Monde",hint:"Io, Europa, Ganymede, Callisto.",emoji:"🔭"},
  {id:"kwelt_103",q:"Wie groß ist der Ring-Radius von Saturns Hauptring in km?",a:280,unit:"Tausend km",hint:"Die Ringe reichen bis 280.000 km vom Zentrum.",emoji:"🪐"},
  {id:"kwelt_104",q:"Wie viele Grad Celsius ist Merkur tagsüber?",a:430,unit:"°C",hint:"Nachts -180°C – extremster Temperaturwechsel.",emoji:"☿"},
  {id:"kwelt_105",q:"Wie viele Stunden dauert ein Jahr auf der Venus?",a:5392,unit:"Stunden",hint:"225 Erdtage – und ein Tag ist länger!",emoji:"🌋"},
  {id:"kwelt_106",q:"Wie viele Trillionen Tonnen wiegt der Asteroid Ceres?",a:9390,unit:"Milliarden Tonnen",hint:"9,4 × 10^20 kg – der größte Asteroid.",emoji:"☄️"},
  {id:"kwelt_107",q:"Wie viele km/h dreht sich Saturn an seinem Äquator?",a:35500,unit:"km/h",hint:"Zweitschnellste Rotation nach Jupiter.",emoji:"🪐"},
  {id:"kwelt_108",q:"Wie lang dauert ein Sonnensturm bis zur Erde in Stunden?",a:48,unit:"Stunden",hint:"Koronale Masseauswürfe: 1-3 Tage.",emoji:"☀️"},
  {id:"kwelt_109",q:"Wie groß ist der Olympus Mons verglichen mit dem Everest?",a:2.5,unit:"x höher",hint:"21km vs 8,8km – 2,5x so hoch.",emoji:"🌋"},
  {id:"kwelt_110",q:"Wie viele Milliarden Jahre alt ist die Sonne?",a:4.6,unit:"Milliarden Jahre",hint:"Und hat noch 5 Mrd. Jahre vor sich.",emoji:"☀️"},
  {id:"kwelt_111",q:"Wie viele km von der Erde entfernt endet der Erdmagnetismus?",a:65000,unit:"km",hint:"Die Magnetosphäre schützt uns bis 65.000 km.",emoji:"🌍"},
  {id:"kwelt_112",q:"Wie kalt ist die Atmosphäre auf dem Uranus in °C?",a:-224,unit:"°C",hint:"Kälteste Atmosphärentemperatur aller Planeten.",emoji:"🟦"},
  {id:"kwelt_113",q:"Wie viele Sekunden braucht Licht von der Erde zum Mond?",a:1.3,unit:"Sekunden",hint:"Nur 1,3 Sekunden – der Mond ist sehr nah.",emoji:"🌙"},
  {id:"kwelt_114",q:"Wie groß ist ein Neutronenstern im Durchmesser in km?",a:20,unit:"km",hint:"So klein wie eine Stadt – aber unvorstellbar schwer.",emoji:"⭐"},
  {id:"kwelt_115",q:"Wie viele km/s dreht sich die Sonne an ihrem Äquator?",a:2,unit:"km/s",hint:"7200 km/h – differenzielle Rotation.",emoji:"☀️"},
  {id:"kwelt_116",q:"Wie lange dauerte die längste Weltraummission?",a:437,unit:"Tage",hint:"Waleri Poljakow auf der Mir-Station (Stand ~2024).",emoji:"🚀"},
  {id:"kwelt_117",q:"Wie viele Stunden dauert ein Jahr auf Jupiter?",a:87672,unit:"Stunden",hint:"12 Erdenjahre.",emoji:"🪐"},
  {id:"kwelt_118",q:"Wie groß ist Plutos größter Mond Charon verglichen mit Pluto?",a:52,unit:"% von Plutos Größe",hint:"Charon ist riesig verglichen mit Pluto (Stand ~2024).",emoji:"🌑"},
  {id:"kwelt_119",q:"Wie viele km/h schnell fliegen interstellare Objekte wie Oumuamua?",a:85000,unit:"km/h",hint:"Das erste interstellare Objekt in unserem System.",emoji:"☄️"},
  {id:"kwelt_120",q:"Wie viele Planeten hat TRAPPIST-1?",a:7,unit:"Planeten",hint:"Erdähnliche – 3 in der habitablen Zone.",emoji:"🌍"},
  {id:"kwelt_121",q:"Wie lang dauert ein Tag auf Titan (Saturnmond)?",a:382,unit:"Stunden",hint:"15,9 Erdtage.",emoji:"🪐"},
  {id:"kwelt_122",q:"Wie groß ist die Magnetosphäre der Erde in Erdradien?",a:10,unit:"Erdradien",hint:"Auf der Tagseite um ein Vielfaches – Nachtseite viel größer.",emoji:"🌍"},
  {id:"kwelt_123",q:"Wie viele Milliarden km ist die Voyager 1 von der Erde entfernt (2023)?",a:23,unit:"Milliarden km",hint:"Das am weitesten entfernte von Menschen gebaute Objekt.",emoji:"🚀"},
  {id:"kwelt_124",q:"Wie kalt ist der dunkelste bekannte Ort im Universum (Boomerang Nebel)?",a:-272,unit:"°C",hint:"Kälter als der kosmische Mikrowellenhintergrund.",emoji:"❄️"},
  {id:"kwelt_125",q:"Wie viele Stunden verbrachten Apollo-Astronauten insgesamt auf dem Mond?",a:80,unit:"Stunden",hint:"Über alle 6 Missionen.",emoji:"🌙"},
  {id:"kwelt_126",q:"Wie groß ist Callisto (Jupitermond) in km?",a:4820,unit:"km",hint:"Fast so groß wie Merkur.",emoji:"🪐"},
  {id:"kwelt_127",q:"Wie viele Stunden dauert ein Umlauf der ISS um die Erde?",a:1.5,unit:"Stunden",hint:"90 Minuten – 16 Sonnenaufgänge täglich.",emoji:"🚀"},
  {id:"kwelt_128",q:"Wie lang ist ein Sonnenzyklus in Jahren?",a:11,unit:"Jahre",hint:"Von Sonnenminimum zu Sonnenminimum.",emoji:"☀️"},
  {id:"kwelt_129",q:"Wie groß ist der Kuipergürtel Durchmesser in AU?",a:50,unit:"Astronomische Einheiten",hint:"30-50 AU von der Sonne entfernt.",emoji:"☄️"},
  {id:"kwelt_130",q:"Wie viele Grad Celsius ist die Venus-Oberfläche?",a:465,unit:"°C",hint:"Heißer als Merkur trotz größerer Entfernung.",emoji:"🌋"},
  {id:"kwelt_131",q:"Wie viele Tausend Jahre nach dem Urknall bildeten sich die ersten Atome?",a:380,unit:"Tausend Jahre",hint:"380.000 Jahre nach dem Urknall.",emoji:"⚛️"},
  {id:"kwelt_132",q:"Wie groß ist das Sonnensystem bis zur Oort-Wolke in Lichtjahren?",a:2,unit:"Lichtjahre",hint:"Lichtjahre Durchmesser.",emoji:"☄️"},
  {id:"kwelt_133",q:"Wie viele Astronauten haben die Erde aus dem Weltraum gesehen?",a:600,unit:"Astronauten",hint:"Stand 2023 – aus über 40 Ländern.",emoji:"👨‍🚀"},
  {id:"kwelt_134",q:"Wie lang dauert eine Sonnenfinsternis maximal in Minuten?",a:7.5,unit:"Minuten",hint:"Totale Sonnenfinsternis maximal 7,5 Minuten.",emoji:"🌑"},
  {id:"kwelt_135",q:"Wie groß ist der Jupitermond Ganymede in km?",a:5268,unit:"km",hint:"Der größte Mond im Sonnensystem.",emoji:"🪐"},
  {id:"kwelt_136",q:"Wie viele km/h beträgt die maximale Windgeschwindigkeit auf Neptun?",a:2100,unit:"km/h",hint:"Stärkste bekannte Winde im Sonnensystem.",emoji:"🌀"},
  {id:"kwelt_137",q:"Wie lang dauert es bis die Sonne zum roten Riesen wird in Milliarden Jahren?",a:5,unit:"Milliarden Jahre",hint:"Dann wird sie die Erde verschlucken.",emoji:"☀️"},
  {id:"kwelt_138",q:"Wie groß ist die Entfernung zwischen den Sternen in der Milchstraße in Lichtjahren?",a:5,unit:"Lichtjahre",hint:"Durchschnittlich 5 Lichtjahre zwischen Sternen.",emoji:"⭐"},
  {id:"kwelt_139",q:"Wie viele Monde hat Saturn (Stand 2023)?",a:146,unit:"Monde",hint:"Mehr als jeder andere Planet.",emoji:"🪐"},
  {id:"kwelt_140",q:"Wie groß ist die Sonne verglichen mit einem roten Riesenstern?",a:100,unit:"x kleiner",hint:"Rote Riesen können um ein Vielfaches größer sein.",emoji:"⭐"},
  {id:"kwelt_141",q:"Wie viele Stunden dauert ein Tag auf Pluto?",a:153,unit:"Stunden",hint:"6 Erdtage.",emoji:"🌑"},
  {id:"kwelt_142",q:"Wie lang ist ein Sonnenjahr genau in Tagen?",a:365.25,unit:"Tage",hint:"Deshalb gibt es alle 4 Jahre einen Schalttag.",emoji:"📅"},
  {id:"kwelt_143",q:"Wie groß ist die Milchstraße in Lichtjahren?",a:100000,unit:"Lichtjahre",hint:"100.000 Lichtjahre Durchmesser.",emoji:"🌌"},
  {id:"kwelt_144",q:"Wie kalt ist der Weltraum zwischen Galaxien?",a:-270,unit:"°C",hint:"Fast absoluter Nullpunkt.",emoji:"❄️"},
  {id:"kwelt_145",q:"Wie viele Ringe hat Neptun?",a:5,unit:"Ringe",hint:"Dunkler und dünner als Saturns.",emoji:"🔵"},
  {id:"kwelt_146",q:"Wie viele km ist der Mond dick an seinem Äquator?",a:3474,unit:"km",hint:"Der Monddurchmesser am Äquator.",emoji:"🌙"},
  {id:"kwelt_147",q:"Wie groß ist der rote Überriese Beteigeuze in Sonnenradien?",a:700,unit:"Sonnenradien",hint:"Um ein Vielfaches größer als unsere Sonne.",emoji:"⭐"},
  {id:"kwelt_148",q:"Wie viele Stunden dauert ein Vollmond-Zyklus?",a:709,unit:"Stunden",hint:"29,5 Tage von Vollmond zu Vollmond.",emoji:"🌕"},
  {id:"kwelt_149",q:"Wie lang ist die Heliosphäre im Durchmesser in AU?",a:200,unit:"AU",hint:"Astronomische Einheiten.",emoji:"☀️"}
,
  {id:"kwelt_150",q:"Wie viele Monate dauert ein Jahr auf Jupiter?",a:144,unit:"Monate",hint:"12 Erdenjahre – 144 Erdenmonate.",emoji:"🪐"},
  {id:"kwelt_151",q:"Wie viele Grad Celsius ist die Oberfläche von Neptun?",a:-214,unit:"°C",hint:"Der kälteste Planet im Sonnensystem.",emoji:"🔵"},
  {id:"kwelt_152",q:"Wie weit ist der nächste Stern Alpha Centauri entfernt?",a:4,unit:"Lichtjahre",hint:"Das nächste Sternensystem.",emoji:"⭐"},
  {id:"kwelt_153",q:"Wie viele km hoch liegt die Raumstation ISS?",a:400,unit:"km",hint:"In der Erdumlaufbahn.",emoji:"🚀"},
  {id:"kwelt_154",q:"Wie groß ist der Rote Fleck auf Jupiter in km?",a:16000,unit:"km",hint:"Ein Sturm seit 350 Jahren.",emoji:"🪐"},
  {id:"kwelt_155",q:"Wie viele Monde hat der Jupiter?",a:95,unit:"Monde",hint:"Jupiter hat die meisten Monde – Stand 2023.",emoji:"🪐"},
  {id:"kwelt_156",q:"Wie lang dauert ein Tag auf Merkur in Erdtagen?",a:59,unit:"Erdtage",hint:"Sehr langsame Eigenrotation.",emoji:"☿"},
  {id:"kwelt_157",q:"Wie weit ist Uranus von der Sonne entfernt in Milliarden km?",a:2.9,unit:"Milliarden km",hint:"7x weiter als die Erde.",emoji:"🟦"},
  {id:"kwelt_158",q:"Wie viele Grad Celsius kalt ist es auf Pluto?",a:-230,unit:"°C",hint:"Einer der kältesten Orte im Sonnensystem.",emoji:"🌑"},
  {id:"kwelt_159",q:"Wie viele km/h bewegt sich ein Komet?",a:100000,unit:"km/h",hint:"Kometen rasen durchs All.",emoji:"☄️"},
  {id:"kwelt_160",q:"Wie viele Sterne kann man mit bloßem Auge sehen?",a:5000,unit:"Sterne",hint:"An einem klaren Nacht.",emoji:"⭐"},
  {id:"kwelt_161",q:"Wie viele Jahre braucht Uranus für einen Umlauf?",a:84,unit:"Jahre",hint:"Erdenjahre pro Uranus-Jahr.",emoji:"🟦"},
  {id:"kwelt_162",q:"Wie groß ist der Mond verglichen mit der Erde in %?",a:27,unit:"% Erddurchmesser",hint:"Etwa ein Viertel so groß.",emoji:"🌙"},
  {id:"kwelt_163",q:"Wie viele Vulkane hat der Mars?",a:43000,unit:"Vulkane",hint:"Darunter der größte Vulkan im Sonnensystem.",emoji:"🔴"},
  {id:"kwelt_164",q:"Wie viele Grad Celsius ist Venus nachts?",a:465,unit:"°C",hint:"Tag und Nacht fast gleich heiß.",emoji:"🌋"},
  {id:"kwelt_165",q:"Wie lang ist der Valles Marineris auf dem Mars in km?",a:4000,unit:"km",hint:"10x länger als der Grand Canyon.",emoji:"🔴"},
  {id:"kwelt_166",q:"Wie viele Monate dauert ein Jahr auf Saturn?",a:354,unit:"Monate",hint:"29,5 Erdenjahre.",emoji:"🪐"},
  {id:"kwelt_167",q:"Wie viele Stunden dauert ein Tag auf Neptun?",a:16,unit:"Stunden",hint:"Schnelle Rotation.",emoji:"🔵"},
  {id:"kwelt_168",q:"Wie weit ist Neptun von der Sonne in Milliarden km?",a:4.5,unit:"Milliarden km",hint:"Licht braucht 4 Stunden.",emoji:"🔵"},
  {id:"kwelt_169",q:"Wie viele Minuten braucht Licht von Saturn zur Erde?",a:75,unit:"Minuten",hint:"Variiert je nach Position.",emoji:"🪐"},
  {id:"kwelt_170",q:"Wie schwer ist ein Astronaut auf dem Mond im Vergleich zur Erde?",a:17,unit:"% des Erdgewichts",hint:"Bei 60kg auf der Erde nur 10kg auf dem Mond.",emoji:"🌙"},
  {id:"kwelt_171",q:"Wie hoch ist der Olympus Mons auf dem Mars?",a:22,unit:"km",hint:"3x höher als der Everest.",emoji:"🔴"},
  {id:"kwelt_172",q:"Wie lang dauert eine Mondumrundung der Erde?",a:27,unit:"Tage",hint:"3 Tage genau.",emoji:"🌙"},
  {id:"kwelt_173",q:"Wie viele Grad dreht sich die Erde täglich?",a:15,unit:"Grad pro Stunde",hint:"360° in 24 Stunden = 15°/h.",emoji:"🌍"},
  {id:"kwelt_174",q:"Wie viele km groß ist der Mond im Durchmesser?",a:3474,unit:"km",hint:"Etwa so breit wie Australien.",emoji:"🌙"},
  {id:"kwelt_175",q:"Wie viele Stunden dauert ein Flug zur ISS?",a:6,unit:"Stunden",hint:"Mit der Sojuz-Kapsel.",emoji:"🚀"},
  {id:"kwelt_176",q:"Wie viele kg wiegt die ISS?",a:420,unit:"Tausend kg",hint:"420 Tonnen – so schwer wie 320 Autos.",emoji:"🚀"},
  {id:"kwelt_177",q:"Wie lang dauert die Sonneneruption bis zur Erde in Stunden?",a:8,unit:"Minuten Licht",hint:"Licht braucht 8 Minuten – Teilchen 1-3 Tage.",emoji:"☀️"},
  {id:"kwelt_178",q:"Wie viele Monde hat Uranus?",a:27,unit:"Monde",hint:"Alle nach Shakespeare-Figuren benannt.",emoji:"🟦"},
  {id:"kwelt_179",q:"Wie viele Kilogramm Mondgestein brachten Apollo-Missionen mit?",a:382,unit:"kg",hint:"Kg über alle Missionen.",emoji:"🌙"},
  {id:"kwelt_180",q:"Wie lang ist ein Sonnentag (Rotation) auf der Venus?",a:243,unit:"Erdtage",hint:"Ein Venustag dauert länger als ein Venusjahr.",emoji:"🌋"},
  {id:"kwelt_181",q:"Wie viele km/h beträgt der Solarwind?",a:500000,unit:"km/h",hint:"Elektrisch geladene Teilchen von der Sonne.",emoji:"☀️"},
  {id:"kwelt_182",q:"Wie viele Sternbilder gibt es am Himmel?",a:88,unit:"Sternbilder",hint:"Offiziell von der IAU anerkannt.",emoji:"⭐"},
  {id:"kwelt_183",q:"Wie weit ist die Milchstraße breit?",a:100000,unit:"Lichtjahre",hint:"100.000 Lichtjahre Durchmesser.",emoji:"🌌"},
  {id:"kwelt_184",q:"Wie viele Kilometer misst der Durchmesser der Sonne?",a:1.39,unit:"Millionen km",hint:"109x größer als die Erde.",emoji:"☀️"},
  {id:"kwelt_185",q:"Wie viele Stunden Sonnenlicht bekommt der Nordpol im Sommer täglich?",a:24,unit:"Stunden",hint:"Mitternachtssonne – die Sonne geht nicht unter.",emoji:"☀️"},
  {id:"kwelt_186",q:"Wie viele Minuten braucht Licht von Neptun zur Erde?",a:240,unit:"Minuten",hint:"4 Stunden Lichtweg.",emoji:"🔵"},
  {id:"kwelt_187",q:"Wie viele Monate dauert eine Mission zur ISS?",a:6,unit:"Monate",hint:"Astronauten bleiben typisch 6 Monate.",emoji:"🚀"},
  {id:"kwelt_188",q:"Wie schwer ist ein Raumanzug in kg?",a:130,unit:"kg",hint:"Ein EMU-Raumanzug auf der ISS.",emoji:"👨‍🚀"},
  {id:"kwelt_189",q:"Wie viele km² hat die Oberfläche des Mondes?",a:37.9,unit:"Millionen km²",hint:"Fast so groß wie Russland.",emoji:"🌙"},
  {id:"kwelt_190",q:"Wie viele Grad Celsius ist der Kern des Jupiters?",a:36000,unit:"°C",hint:"Extrem heißer Kern unter dem Gas.",emoji:"🪐"},
  {id:"kwelt_191",q:"Wie lang braucht ein Lichtsignal von der Erde zum Mars in Minuten?",a:12,unit:"Minuten",hint:"Je nach Abstand 3-22 Minuten.",emoji:"🔴"},
  {id:"kwelt_192",q:"Wie viele Planeten sind kleiner als die Erde?",a:2,unit:"Planeten",hint:"Merkur und Mars sind kleiner.",emoji:"🪐"},
  {id:"kwelt_193",q:"Wie viele km/h beträgt die Umlaufgeschwindigkeit der ISS?",a:28000,unit:"km/h",hint:"Alle 90 Minuten einmal um die Erde.",emoji:"🚀"},
  {id:"kwelt_194",q:"Wie viele Milliarden Sterne hat die Milchstraße ungefähr?",a:200,unit:"Milliarden Sterne",hint:"200 Milliarden.",emoji:"⭐"},
  {id:"kwelt_195",q:"Wie viele Milliarden Jahre ist das Universum alt?",a:13.8,unit:"Milliarden Jahre",hint:"13,8 Milliarden Jahre seit dem Urknall.",emoji:"🌌"},
  {id:"kwelt_196",q:"Wie hoch ist die Kármán-Linie – Grenze zum Weltraum – in km?",a:100,unit:"km",hint:"Ab hier beginnt offiziell der Weltraum.",emoji:"🚀"},
  {id:"kwelt_197",q:"Wie viele Planeten in unserem Sonnensystem sind größer als die Erde?",a:4,unit:"Planeten",hint:"Jupiter, Saturn, Uranus, Neptun.",emoji:"🪐"},
  {id:"kwelt_198",q:"Wie viele km/h fliegt die New Horizons Sonde?",a:58536,unit:"km/h",hint:"Die schnellste von Menschen gebaute Sonde.",emoji:"🚀"},
  {id:"kwelt_199",q:"Wie viele Tage dauert ein Jahr auf Merkur in Erdtagen?",a:88,unit:"Tage",hint:"Nur 88 Erdtage.",emoji:"☿"},
  {id:"kwelt_200",q:"Wie viele Milliarden km entfernt ist die Voyager 1 von der Erde?",a:23,unit:"Milliarden km",hint:"Die weiteste von Menschen gebaute Sonde.",emoji:"🚀"},
  {id:"kwelt_201",q:"Wie viele Kometen wurden im Sonnensystem entdeckt?",a:4000,unit:"Kometen",hint:"Und es gibt noch Millionen unbekannte.",emoji:"☄️"},
  {id:"kwelt_202",q:"Wie viele Asteroiden haben einen Durchmesser über 100km?",a:200,unit:"Asteroiden",hint:"Im Asteroidengürtel.",emoji:"☄️"},
  {id:"kwelt_203",q:"Wie viele Weltraumspaziergänge hat ein Astronaut auf der ISS pro Mission?",a:3,unit:"Spacewalks",hint:"Durchschnittlich 2-5 pro Mission.",emoji:"👨‍🚀"},
  {id:"kwelt_204",q:"Wie viele Millionen km entfernt liegt die Sonne von uns?",a:150,unit:"Millionen km",hint:"150 Millionen km = 1 AU.",emoji:"☀️"},
  {id:"kwelt_205",q:"Wie groß ist Titan (Saturnmond) im Vergleich zur Erde in %?",a:40,unit:"% Erddurchmesser",hint:"Größer als Merkur.",emoji:"🪐"},
  {id:"kwelt_206",q:"Wie viele Stunden dauert der Mondaufgang bis Monduntergang?",a:12,unit:"Stunden",hint:"Ähnlich wie die Sonne – aber variiert.",emoji:"🌙"},
  {id:"kwelt_207",q:"Wie viele Meteoriten fallen täglich auf die Erde?",a:50,unit:"Tonnen",hint:"Tonnen Meteoritenstaub täglich.",emoji:"☄️"},
  {id:"kwelt_208",q:"Wie viele km/h dreht sich die Erde um sich selbst am Äquator?",a:1670,unit:"km/h",hint:"Wir merken es nicht.",emoji:"🌍"},
  {id:"kwelt_209",q:"Wie viele Sterne kann man mit einem Fernrohr sehen?",a:50000,unit:"Sterne",hint:"Deutlich mehr als mit bloßem Auge.",emoji:"🔭"},
  {id:"kwelt_210",q:"Wie lang ist die Tagundnachtgleiche auf dem Planeten Uranus in Jahren?",a:21,unit:"Erdenjahre",hint:"Jede Jahreszeit dauert diese Zeit Jahre.",emoji:"🟦"},
  {id:"kwelt_211",q:"Wie viele Minuten braucht Licht von Jupiter zur Erde?",a:43,unit:"Minuten",hint:"Variiert mit der Entfernung.",emoji:"🪐"},
  {id:"kwelt_212",q:"Wie viele g Kräfte wirken beim Raketenstart auf Astronauten?",a:3,unit:"g",hint:"Das dreifache Körpergewicht.",emoji:"🚀"},
  {id:"kwelt_213",q:"Wie viele Planeten kreisen um andere Sterne (Exoplaneten)?",a:5500,unit:"Exoplaneten",hint:"Stand 2024 – werden ständig mehr.",emoji:"🌌"},
  {id:"kwelt_214",q:"Wie viele Millionen Sonnenmassen hat das schwarze Loch im Zentrum der Milchstraße?",a:4,unit:"Millionen Sonnenmassen",hint:"Sagittarius A* – 4 Millionen Sonnenmassen.",emoji:"🌑"},
  {id:"kwelt_215",q:"Wie viele Stunden dauert ein Jahr auf Venus?",a:5392,unit:"Stunden",hint:"225 Erdtage – kürzer als ein Venustag.",emoji:"🌋"},
  {id:"kwelt_216",q:"Wie lang hat es gedauert bis Voyager 1 die Grenze des Sonnensystems erreichte?",a:35,unit:"Jahre",hint:"Gestartet 1977, Heliopause 2012.",emoji:"🚀"},
  {id:"kwelt_217",q:"Wie viele km ist der Äquator der Erde lang?",a:40075,unit:"km",hint:"Umfang der Erde am Äquator.",emoji:"🌍"},
  {id:"kwelt_218",q:"Wie viele Sternschnuppen sieht man durchschnittlich pro Stunde?",a:10,unit:"Sternschnuppen",hint:"In einer normalen Nacht.",emoji:"🌠"},
  {id:"kwelt_219",q:"Wie weit ist Neptun von der Erde im Durchschnitt in Milliarden km?",a:4.4,unit:"Milliarden km",hint:"Der äußerste Planet.",emoji:"🔵"},
  {id:"kwelt_220",q:"Wie viele Grad Celsius ist die Temperatur auf dem Mars tagsüber maximal?",a:20,unit:"°C",hint:"Nur am Äquator im Sommer.",emoji:"🔴"},
  {id:"kwelt_221",q:"Wie viele Millionen Kilometer weit ist der Asteroid-Gürtel von der Sonne entfernt?",a:400,unit:"Millionen km",hint:"Zwischen Mars und Jupiter.",emoji:"☄️"},
  {id:"kwelt_222",q:"Wie viele Stunden dauert ein Sonnentag auf dem Mond?",a:708,unit:"Stunden",hint:"29,5 Erdtage – der Mondtag ist lang.",emoji:"🌙"},
  {id:"kwelt_223",q:"Wie viele Meter breit ist das Sonnensegel der ISS?",a:109,unit:"Meter",hint:"So breit wie ein Fußballfeld.",emoji:"🚀"},
  {id:"kwelt_224",q:"Wie viele km hoch ist die Atmosphäre der Erde?",a:10000,unit:"km",hint:"Die dichte Troposphäre reicht nur 12km.",emoji:"🌍"},
  {id:"kwelt_225",q:"Wie viele Male umkreist die ISS die Erde pro Tag?",a:16,unit:"Mal",hint:"Alle 90 Minuten eine Runde.",emoji:"🚀"},
  {id:"kwelt_226",q:"Wie viele Minuten braucht Licht von Merkur zur Erde?",a:4,unit:"Minuten",hint:"Merkur ist näher als die meisten Planeten.",emoji:"☿"},
  {id:"kwelt_227",q:"Wie viele Jahre braucht Neptun für einen Umlauf?",a:165,unit:"Jahre",hint:"Erdenjahre.",emoji:"🔵"},
  {id:"kwelt_228",q:"Wie viele Milliarden km ist Saturn von der Sonne entfernt?",a:1.4,unit:"Milliarden km",hint:"Fast 10x weiter als die Erde.",emoji:"🪐"},
  {id:"kwelt_229",q:"Wie viele km beträgt der Durchmesser des Großen Roten Flecks auf Jupiter?",a:16000,unit:"km",hint:"Größer als die Erde.",emoji:"🪐"},
  {id:"kwelt_230",q:"Wie lang dauert die Reise mit einer Rakete zum Mars in Monaten?",a:7,unit:"Monate",hint:"Mit heutiger Technologie ca. 7 Monate.",emoji:"🔴"},
  {id:"kwelt_231",q:"Wie viele km/h dreht sich Jupiter an seinem Äquator?",a:45000,unit:"km/h",hint:"Die schnellste Rotation aller Planeten.",emoji:"🪐"},
  {id:"kwelt_232",q:"Wie viele g wiegt ein Astronaut auf dem Mond?",a:16.7,unit:"% Erdgewicht",hint:"Ein 60kg Mensch wiegt auf dem Mond 10kg.",emoji:"🌙"},
  {id:"kwelt_233",q:"Wie viele Weltraumtouristen haben die Erde schon von oben gesehen?",a:600,unit:"Menschen",hint:"Inklusive Astronauten – ca. 600 Stand 2024.",emoji:"🚀"},
  {id:"kwelt_234",q:"Wie viele km groß ist der Krater auf dem Mond (Clavius)?",a:231,unit:"km",hint:"Einer der größten Mondkrater.",emoji:"🌙"},
  {id:"kwelt_235",q:"Wie viele Sternschnuppen regnen bei einem Meteor-Schauer pro Stunde?",a:100,unit:"Sternschnuppen",hint:"Bei Höhepunkten sogar mehr.",emoji:"🌠"},
  {id:"kwelt_236",q:"Wie viele Jahre existiert die ISS schon?",a:25,unit:"Jahre",hint:"Seit 1998 im Bau – erste Besatzung 2000.",emoji:"🚀"},
  {id:"kwelt_237",q:"Wie viele Milliarden Sonnensysteme könnte die Milchstraße haben?",a:100,unit:"Milliarden",hint:"Potenziell Hunderte Milliarden.",emoji:"🌌"},
  {id:"kwelt_238",q:"Wie viele Meter beträgt die Größe der kleinsten bekannten Asteroiden?",a:1,unit:"Meter",hint:"Mikroasteoriden – kaum nachweisbar.",emoji:"☄️"},
  {id:"kwelt_239",q:"Wie viele Stunden Sonnentaglicht gibt es auf Merkur?",a:4224,unit:"Stunden",hint:"176 Erdtage Tageslicht.",emoji:"☿"}
];
