// 🦕 DINOSAURIER – Kinder
export default [
  {id:"kdino_001",q:"Vor wie vielen Millionen Jahren starben die Dinosaurier aus?",a:66,unit:"Millionen Jahren",hint:"Ein Asteroideneinschlag löste das Massenaussterben aus.",emoji:"☄️"},
  {id:"kdino_002",q:"Wie lang war der größte Dinosaurier (Argentinosaurus) in Metern?",a:40,unit:"Meter",hint:"Länger als 4 Busse hintereinander (Stand ~2024).",emoji:"🦕"},
  {id:"kdino_003",q:"Wie groß war ein T-Rex-Zahn in cm?",a:30,unit:"cm",hint:"So lang wie ein menschlicher Unterarm.",emoji:"🦷"},
  {id:"kdino_004",q:"Wie viele kg wog ein ausgewachsener T-Rex?",a:8000,unit:"kg",hint:"Trotz der Größe war er ein Zweibeiniger.",emoji:"🦖"},
  {id:"kdino_005",q:"Wie lange lebten Dinosaurier auf der Erde in Millionen Jahren?",a:165,unit:"Millionen Jahre",hint:"Viel länger als bisher die Menschen – wir sind erst 0,3 Mio. Jahre alt.",emoji:"🌍"},
  {id:"kdino_006",q:"Wie viele Hörner hatte ein Triceratops?",a:3,unit:"Hörner",hint:"Zwei lange und ein kurzes Nasenhorn.",emoji:"🦏"},
  {id:"kdino_007",q:"Wie lang war ein Velociraptor wirklich in Metern?",a:1.8,unit:"Meter",hint:"Viel kleiner als im Film – so groß wie ein Truthahn.",emoji:"🦖"},
  {id:"kdino_008",q:"Vor wie vielen Millionen Jahren erschienen die ersten Dinosaurier?",a:231,unit:"Millionen Jahren",hint:"In der Trias-Periode.",emoji:"🌿"},
  {id:"kdino_009",q:"Wie lang war ein Brachiosaurus-Hals in Metern?",a:9,unit:"Meter",hint:"Damit konnte er Blätter aus sehr hohen Bäumen fressen.",emoji:"🦕"},
  {id:"kdino_010",q:"Wie viele Platten hatte ein Stegosaurus auf dem Rücken?",a:17,unit:"Platten",hint:"Die Platten halfen bei der Temperaturregulierung.",emoji:"🦖"},
  {id:"kdino_011",q:"Wie hoch konnte ein Brachiosaurus seinen Kopf heben in Metern?",a:12,unit:"Meter",hint:"So hoch wie ein vierstöckiges Haus.",emoji:"🦕"},
  {id:"kdino_012",q:"Wie viele Zähne hatte ein T-Rex?",a:60,unit:"Zähne",hint:"Und sie wurden ständig erneuert wie bei Haien.",emoji:"🦷"},
  {id:"kdino_013",q:"Wie schnell konnte ein T-Rex laufen in km/h?",a:20,unit:"km/h",hint:"Langsamer als ein Mensch auf dem Fahrrad.",emoji:"🦖"},
  {id:"kdino_014",q:"Wie lang war ein Diplodocus in Metern?",a:27,unit:"Meter",hint:"Der Schwanz allein war halb so lang wie der ganze Körper.",emoji:"🦕"},
  {id:"kdino_015",q:"Vor wie vielen Millionen Jahren entstand der erste Vogel (Archaeopteryx)?",a:150,unit:"Millionen Jahren",hint:"Vögel sind die lebenden Nachfahren der Dinosaurier.",emoji:"🐦"},
  {id:"kdino_016",q:"Wie lange dauerte die Kreidezeit in Millionen Jahren?",a:79,unit:"Millionen Jahre",hint:"Von vor 145 bis vor 66 Millionen Jahren.",emoji:"🌿"},
  {id:"kdino_017",q:"Wie groß war ein Compsognathus in cm?",a:60,unit:"cm",hint:"Einer der kleinsten Dinosaurier – so groß wie eine Henne.",emoji:"🐓"},
  {id:"kdino_018",q:"Wie viele Dinosaurier-Arten wurden bisher entdeckt?",a:700,unit:"Arten",hint:"Und jedes Jahr werden neue Arten gefunden.",emoji:"🔍"},
  {id:"kdino_019",q:"Wie groß war ein Pteranodon mit Flügelspannweite in Metern?",a:7,unit:"Meter",hint:"Kein Dinosaurier, aber zeitgleich – ein fliegender Reptil.",emoji:"🦅"},
  {id:"kdino_020",q:"Wie viele Kilogramm fraß ein Brachiosaurus täglich?",a:400,unit:"kg",hint:"Kg Pflanzen täglich – das ist enorm.",emoji:"🌿"},
  {id:"kdino_021",q:"Wie dick war die Schädeldecke eines Pachycephalosaurus in cm?",a:25,unit:"cm",hint:"Für Kopfstöße gegen andere Artgenossen.",emoji:"💀"},
  {id:"kdino_022",q:"Wie groß waren die Eier des größten Dinosauriers in cm Durchmesser?",a:45,unit:"cm",hint:"Fast so groß wie ein Fußball (Stand ~2024).",emoji:"🥚"},
  {id:"kdino_023",q:"Wie lang war der Dornfortsatz eines Spinosaurus in cm?",a:180,unit:"cm",hint:"Der Spinosaurus hatte einen großen Segel auf dem Rücken.",emoji:"🦖"},
  {id:"kdino_024",q:"Wie lang war ein Mikroraptor in cm?",a:50,unit:"cm",hint:"Einer der kleinsten bekannten Dinosaurier.",emoji:"🐦"},
  {id:"kdino_025",q:"Wie viele Jahre hat es gedauert, das erste vollständige T-Rex-Skelett zu finden?",a:100,unit:"Jahre",hint:"Sue ist das vollständigste je gefundene T-Rex-Skelett.",emoji:"🦴"},
  {id:"kdino_026",q:"Wie schwer war ein Ankylosaurus in Tonnen?",a:8,unit:"Tonnen",hint:"Schwer gepanzert – sein Körper war eine wandelnde Festung.",emoji:"🛡️"},
  {id:"kdino_027",q:"Wie lang war ein ausgewachsener Allosaurus in Metern?",a:12,unit:"Meter",hint:"Der T-Rex des Jura – lebte 150 Mio. Jahre vor uns.",emoji:"🦖"},
  {id:"kdino_028",q:"Wie viele Eier legte ein durchschnittlicher Dinosaurier pro Gelege?",a:15,unit:"Eier",hint:"Ähnlich wie heutige Reptilien.",emoji:"🥚"},
  {id:"kdino_029",q:"Wie groß war ein Parasaurolophus-Kamm in cm?",a:100,unit:"cm",hint:"Der Kamm wurde wie ein Instrument zum Rufen benutzt.",emoji:"🦕"},
  {id:"kdino_030",q:"Wie weit konnte ein Pterodactylus fliegen in km pro Tag?",a:100,unit:"km",hint:"Flugsaurier waren ausdauernde Flieger.",emoji:"🦅"},
{id:"kdino_031",q:"Wie schwer war ein ausgewachsener Stegosaurus in Tonnen?",a:5,unit:"Tonnen",hint:"Trotz Größe hatte er ein winziges Gehirn.",emoji:"🦖"},
  {id:"kdino_032",q:"Wie lange dauerte die Triaszeit in Millionen Jahren?",a:52,unit:"Millionen Jahre",hint:"Von 252 bis 201 Millionen Jahre.",emoji:"🌿"},
  {id:"kdino_033",q:"Wie lang war ein Triceratops in Metern?",a:9,unit:"Meter",hint:"Mit drei Hörnern und Knochenkragen.",emoji:"🦏"},
  {id:"kdino_034",q:"Wie schwer war ein Triceratops in Tonnen?",a:8,unit:"Tonnen",hint:"Ähnlich schwer wie ein T-Rex.",emoji:"🦏"},
  {id:"kdino_035",q:"Wie viele Zähne hatte ein Hadrosaur?",a:1000,unit:"Zähne",hint:"Enten-Schnabel-Dinosaurier mit Zahnbatterien.",emoji:"🦷"},
  {id:"kdino_036",q:"Wie lang war ein Spinosaurus in Metern?",a:18,unit:"Meter",hint:"Wahrscheinlich länger als ein T-Rex.",emoji:"🦖"},
  {id:"kdino_037",q:"Wie hoch war ein Brachiosaurus in Metern?",a:13,unit:"Meter",hint:"So hoch wie ein vierstöckiges Haus.",emoji:"🦕"},
  {id:"kdino_038",q:"Wie viele Tage brüteten Dinosaurier ihre Eier aus?",a:90,unit:"Tage",hint:"Je nach Art 45 bis 180 Tage.",emoji:"🥚"},
  {id:"kdino_039",q:"Wie schwer war ein ausgewachsener Iguanodon in Tonnen?",a:3.5,unit:"Tonnen",hint:"Einer der ersten entdeckten Dinosaurier.",emoji:"🦖"},
  {id:"kdino_040",q:"Wie lang war ein Ankylosaurus in Metern?",a:10,unit:"Meter",hint:"Gepanzert wie ein Panzer.",emoji:"🛡️"},
  {id:"kdino_041",q:"Wie schnell konnte ein Gallimimus laufen in km/h?",a:70,unit:"km/h",hint:"Einer der schnellsten Dinosaurier.",emoji:"🦖"},
  {id:"kdino_042",q:"Wie lang war ein Brontosaurus in Metern?",a:22,unit:"Meter",hint:"Lange dachte man er sei gleich wie Apatosaurus.",emoji:"🦕"},
  {id:"kdino_043",q:"Wie schwer war ein Carnotaurus in Tonnen?",a:2,unit:"Tonnen",hint:"Hatte zwei kleine Hörner am Kopf.",emoji:"🦖"},
  {id:"kdino_044",q:"Wie viele Wirbel hatte ein Diplodocus im Hals?",a:15,unit:"Halswirbel",hint:"Der lange Hals bestand aus 15 Wirbeln.",emoji:"🦕"},
  {id:"kdino_045",q:"Wie lang war ein Archaeopteryx in cm?",a:50,unit:"cm",hint:"Der Übergang zwischen Dinosaurier und Vogel.",emoji:"🐦"},
  {id:"kdino_046",q:"Wie groß war ein Pachycephalosaurus-Schädel in cm?",a:60,unit:"cm",hint:"Dicker Schädel für Kopfstöße.",emoji:"💀"},
  {id:"kdino_047",q:"Wie schwer war ein Maiasaura in kg?",a:4000,unit:"kg",hint:"Brutpflegender Dinosaurier.",emoji:"🦖"},
  {id:"kdino_048",q:"Wie lang war ein Carnotaurus in Metern?",a:9,unit:"Meter",hint:"Südamerikanischer Raubsaurier.",emoji:"🦖"},
  {id:"kdino_049",q:"Wie viele Finger hatte ein Iguanodon?",a:4,unit:"Finger",hint:"Plus ein Daumen-Stachel als Waffe.",emoji:"🦖"},
  {id:"kdino_050",q:"Wie schwer war ein Stegosaurus in Tonnen?",a:5,unit:"Tonnen",hint:"Gehirn nur 80g – kleinstes im Tierreich.",emoji:"🦖"},
  {id:"kdino_051",q:"Wie lang war ein Coelophysis in cm?",a:300,unit:"cm",hint:"Früher schlanker Räuber.",emoji:"🦖"},
  {id:"kdino_052",q:"Wie groß war ein Protoceratops-Ei in cm?",a:20,unit:"cm",hint:"In der Mongolei wurden viele Nester gefunden.",emoji:"🥚"},
  {id:"kdino_053",q:"Wie schwer war ein Parasaurolophus in Tonnen?",a:2.5,unit:"Tonnen",hint:"Konnte röhren wie ein Instrument.",emoji:"🦕"},
  {id:"kdino_054",q:"Wie lang war ein Baryonyx in Metern?",a:10,unit:"Meter",hint:"Fischfressender Dinosaurier aus England.",emoji:"🦖"},
  {id:"kdino_055",q:"Wie viele Zähne hatte ein Diplodocus?",a:50,unit:"Zähne",hint:"Lange Stifte zum Abstreifen von Blättern.",emoji:"🦷"},
  {id:"kdino_056",q:"Wie schwer war ein Allosaurus in Tonnen?",a:3,unit:"Tonnen",hint:"Der T-Rex des Jura.",emoji:"🦖"},
  {id:"kdino_057",q:"Wie lang war ein Oviraptor in cm?",a:200,unit:"cm",hint:"Dachte man er stiehlt Eier – falsch!",emoji:"🦖"},
  {id:"kdino_058",q:"Wie hoch war ein Tyrannosaurus Rex stehend in Metern?",a:5,unit:"Meter",hint:"Meter hoch – wie ein Doppeldeckerbus.",emoji:"🦖"},
  {id:"kdino_059",q:"Wie lang war ein Herrerasaurus in Metern?",a:4,unit:"Meter",hint:"Einer der ältesten bekannten Dinosaurier.",emoji:"🦖"},
  {id:"kdino_060",q:"Wie schwer war ein Euoplocephalus in Tonnen?",a:2,unit:"Tonnen",hint:"Hatte eine knöcherne Keule am Schwanz.",emoji:"🛡️"},
  {id:"kdino_061",q:"Wie groß war ein Brachiosaurus-Ei in cm?",a:30,unit:"cm",hint:"Noch nicht vollständig bekannt.",emoji:"🥚"},
  {id:"kdino_062",q:"Wie viele Hörner hatte ein Styracosaurus?",a:6,unit:"Hörner",hint:"Plus ein großes Nasenhorn.",emoji:"🦏"},
  {id:"kdino_063",q:"Wie lang war ein Kentrosaurus in Metern?",a:5,unit:"Meter",hint:"Afrikanischer Verwandter des Stegosaurus.",emoji:"🦖"},
  {id:"kdino_064",q:"Wie schwer war ein Edmontosaurus in Tonnen?",a:4,unit:"Tonnen",hint:"Einer der häufigsten Hadrosauren.",emoji:"🦕"},
  {id:"kdino_065",q:"Wie lang war ein Ceratosaurus in Metern?",a:7,unit:"Meter",hint:"Hatte ein Horn auf der Nase.",emoji:"🦖"},
  {id:"kdino_066",q:"Wie hoch war eine Giraffen-Vorfahrin (Sauroposeidon) in Metern?",a:17,unit:"Meter",hint:"Größter bekannter Dinosaurier in der Höhe.",emoji:"🦕"},
  {id:"kdino_067",q:"Wie schwer war ein Pachycephalosaurus in Tonnen?",a:450,unit:"kg",hint:"Kg – relativ klein.",emoji:"💀"},
  {id:"kdino_068",q:"Wie lang war ein Apatosaurus in Metern?",a:23,unit:"Meter",hint:"Früher Brontosaurus genannt.",emoji:"🦕"},
  {id:"kdino_069",q:"Wie viele Fingergelenke hatte ein T-Rex pro kleinem Arm?",a:2,unit:"Gelenke",hint:"Winzige Arme mit 2 Fingern.",emoji:"🦖"},
  {id:"kdino_070",q:"Wie lange dauerte die Kreidezeit genau in Millionen Jahren?",a:79,unit:"Millionen Jahre",hint:"Von 145 bis 66 Millionen Jahre.",emoji:"🌿"},
  {id:"kdino_071",q:"Wie schwer war ein Carcharodontosaurus in Tonnen?",a:7,unit:"Tonnen",hint:"Rivale des T-Rex aus Nordafrika.",emoji:"🦖"},
  {id:"kdino_072",q:"Wie viele Eier legte ein Maisaura pro Nest?",a:25,unit:"Eier",hint:"Sie pflegten ihre Jungen.",emoji:"🥚"},
  {id:"kdino_073",q:"Wie lang war ein Therizinosaurus-Klaue in cm?",a:70,unit:"cm",hint:"Längste Klauen aller bekannten Tiere.",emoji:"🦖"},
  {id:"kdino_074",q:"Wie hoch war ein Brachiosaurus-Hals in Metern?",a:9,unit:"Meter",hint:"Fast so lang wie der ganze Körper.",emoji:"🦕"},
  {id:"kdino_075",q:"Wie schwer war ein Diplodocus in Tonnen?",a:16,unit:"Tonnen",hint:"Trotz der Länge relativ leicht.",emoji:"🦕"},
  {id:"kdino_076",q:"Wie lang war der Schwanz eines Diplodocus in Metern?",a:14,unit:"Meter",hint:"Über die Hälfte der Körperlänge.",emoji:"🦕"},
  {id:"kdino_077",q:"Wie viele Zähne hatte ein Allosaurus?",a:70,unit:"Zähne",hint:"Scharfe gezähnte Zähne zum Reißen.",emoji:"🦷"},
  {id:"kdino_078",q:"Wie schwer war ein Psittacosaurus in kg?",a:20,unit:"kg",hint:"Kleiner früher Ceratopsier.",emoji:"🦖"},
  {id:"kdino_079",q:"Wie lang war ein Spinosaurus-Segel in cm?",a:170,unit:"cm",hint:"Der Segel auf dem Rücken war 1,7m hoch.",emoji:"🦖"},
  {id:"kdino_080",q:"Wie viele Millionen Jahre gab es Dinosaurier insgesamt?",a:165,unit:"Millionen Jahre",hint:"Viel länger als Menschen existieren.",emoji:"🌍"},
  {id:"kdino_081",q:"Wie groß war ein Velociraptor im Verhältnis zu einem Menschen in %?",a:50,unit:"% der Körpergröße",hint:"Velociraptoren waren halb so groß wie Menschen.",emoji:"🦖"},
  {id:"kdino_082",q:"Wie schwer war ein Torvosaurus in Tonnen?",a:4,unit:"Tonnen",hint:"Einer der größten Jura-Räuber.",emoji:"🦖"},
  {id:"kdino_083",q:"Wie lang war ein Mamenchisaurus-Hals in Metern?",a:14,unit:"Meter",hint:"Der längste Hals aller Dinosaurier.",emoji:"🦕"},
  {id:"kdino_084",q:"Wie viele Stunden brüteten kleine Dinosaurier ihre Eier?",a:2880,unit:"Stunden",hint:"120 Tage – länger als Krokodile.",emoji:"🥚"},
  {id:"kdino_085",q:"Wie schwer war ein Giraffatitan in Tonnen?",a:30,unit:"Tonnen",hint:"Einer der schwersten Dinosaurier.",emoji:"🦕"},
  {id:"kdino_086",q:"Wie lang war ein Compsognathus in cm?",a:60,unit:"cm",hint:"So groß wie ein Huhn.",emoji:"🐓"},
  {id:"kdino_087",q:"Wie schwer war ein Huayangosaurus in Tonnen?",a:900,unit:"kg",hint:"Früher kleiner Stegosauride.",emoji:"🦖"},
  {id:"kdino_088",q:"Wie lang war ein Ouranosaurus in Metern?",a:8,unit:"Meter",hint:"Hatte einen Segel oder Buckel auf dem Rücken.",emoji:"🦕"},
  {id:"kdino_089",q:"Wie viele Finger hatte ein Brachiosaurus pro Fuß?",a:5,unit:"Zehen",hint:"Sauropoden hatten 5 Zehen.",emoji:"🦕"},
  {id:"kdino_090",q:"Wie schwer war ein Ceratosaurus in Tonnen?",a:1,unit:"Tonne",hint:"Mit Horn auf der Nase.",emoji:"🦖"},
  {id:"kdino_091",q:"Wie lang war ein Tenontosaurus in Metern?",a:8,unit:"Meter",hint:"Beute für Velociraptoren.",emoji:"🦕"},
  {id:"kdino_092",q:"Wie viele Krallen hatte ein Therizinosaurus?",a:3,unit:"Klauen pro Hand",hint:"Riesige Klauen – für Pflanzen.",emoji:"🦖"},
  {id:"kdino_093",q:"Wie schwer war ein Sarcosuchus (Superkrokodil) in Tonnen?",a:8,unit:"Tonnen",hint:"Das größte Krokodil das je lebte.",emoji:"🐊"},
  {id:"kdino_094",q:"Wie lang war ein Sarcosuchus in Metern?",a:12,unit:"Meter",hint:"Lebte zur Dinosaurierzeit.",emoji:"🐊"},
  {id:"kdino_095",q:"Wie viele Millionen Jahre starben die letzten Dinosaurier aus?",a:66,unit:"Millionen Jahren vor heute",hint:"Durch den Asteroiden-Einschlag.",emoji:"☄️"},
  {id:"kdino_096",q:"Wie groß war ein Argentinosaurus-Wirbel in Metern?",a:1.8,unit:"Meter Länge",hint:"Jeder Wirbel größer als ein Mensch.",emoji:"🦕"},
  {id:"kdino_097",q:"Wie schwer war ein Megalosaurus in Tonnen?",a:1,unit:"Tonne",hint:"Erster wissenschaftlich beschriebener Dinosaurier.",emoji:"🦖"},
  {id:"kdino_098",q:"Wie lang war ein Camptosaurus in Metern?",a:7,unit:"Meter",hint:"Zweibeiniger Pflanzenfresser.",emoji:"🦕"},
  {id:"kdino_099",q:"Wie viele Sätze Zähne bildete ein Hadrosaur?",a:1000,unit:"Zähne gleichzeitig",hint:"Ständig nachwachsend.",emoji:"🦷"},
  {id:"kdino_100",q:"Wie schwer war ein Yangchuanosaurus in Tonnen?",a:3,unit:"Tonnen",hint:"Chinesischer Jura-Räuber.",emoji:"🦖"},
  {id:"kdino_101",q:"Wie lang war ein Lessemsaurus in Metern?",a:9,unit:"Meter",hint:"Früher Sauropode aus Argentinien.",emoji:"🦕"},
  {id:"kdino_102",q:"Wie viele Federn hatte ein Microraptor?",a:500,unit:"Federn",hint:"Vierflügliger Miniatur-Dinosaurier.",emoji:"🪶"},
  {id:"kdino_103",q:"Wie schwer war ein Heterodontosaurus in kg?",a:2,unit:"kg",hint:"Winziger früher Dinosaurier.",emoji:"🦖"},
  {id:"kdino_104",q:"Wie lang war ein Plateosaurus in Metern?",a:9,unit:"Meter",hint:"Früher europäischer Prosauropode.",emoji:"🦕"},
  {id:"kdino_105",q:"Wie viele Millionen Jahre lebte der Stegosaurus?",a:8,unit:"Millionen Jahre",hint:"Nur 8 Millionen Jahre auf der Erde.",emoji:"🦖"},
  {id:"kdino_106",q:"Wie schwer war ein Daspletosaurus in Tonnen?",a:3,unit:"Tonnen",hint:"Vorfahre des T-Rex.",emoji:"🦖"},
  {id:"kdino_107",q:"Wie lang war ein Saltasaurus in Metern?",a:12,unit:"Meter",hint:"Gepanzerter Sauropode aus Argentinien.",emoji:"🦕"},
  {id:"kdino_108",q:"Wie viele Zähne hatte ein Parasaurolophus?",a:800,unit:"Zähne",hint:"Zahnbatterien wie alle Hadrosauren.",emoji:"🦷"},
  {id:"kdino_109",q:"Wie schwer war ein Megaraptor in Tonnen?",a:1.5,unit:"Tonnen",hint:"Großer Raubsaurier aus Argentinien.",emoji:"🦖"},
  {id:"kdino_110",q:"Wie viele Rippen hatte ein Diplodocus?",a:24,unit:"Rippenpaare",hint:"Lange Rippen für den riesigen Körper.",emoji:"🦕"},
  {id:"kdino_111",q:"Wie schwer war ein Styracosaurus in Tonnen?",a:3,unit:"Tonnen",hint:"Mit beeindruckendem Knochenkragen.",emoji:"🦏"},
  {id:"kdino_112",q:"Wie lang war ein Albertosaurus in Metern?",a:9,unit:"Meter",hint:"Kleiner Verwandter des T-Rex.",emoji:"🦖"},
  {id:"kdino_113",q:"Wie viele Meter lang war der Schwanz eines T-Rex?",a:6,unit:"Meter",hint:"Der Schwanz half beim Gleichgewicht.",emoji:"🦖"},
  {id:"kdino_114",q:"Wie schwer war ein Dilophosaurus in kg?",a:400,unit:"kg",hint:"Hatte zwei Kämme auf dem Kopf.",emoji:"🦖"},
  {id:"kdino_115",q:"Wie lang war ein Scelidosaurus in Metern?",a:4,unit:"Meter",hint:"Früher gepanzerter Dinosaurier.",emoji:"🦖"},
  {id:"kdino_116",q:"Wie schwer war ein Wannanosaurus in kg?",a:0.5,unit:"kg",hint:"Winziger Pachycephalosauride.",emoji:"🦖"},
  {id:"kdino_117",q:"Wie lang war ein Pisanosaurus in cm?",a:100,unit:"cm",hint:"Einer der ältesten Ornithischier.",emoji:"🦖"},
  {id:"kdino_118",q:"Wie viele Millionen Jahre dauerte der Jura?",a:56,unit:"Millionen Jahre",hint:"Von 201 bis 145 Millionen Jahre.",emoji:"🌿"},
  {id:"kdino_119",q:"Wie schwer war ein Concavenator in Tonnen?",a:1,unit:"Tonne",hint:"Hatte einen buckelartigen Auswuchs.",emoji:"🦖"},
  {id:"kdino_120",q:"Wie lang war ein Irritator in Metern?",a:8,unit:"Meter",hint:"Spinosauride aus Brasilien – schwer zu identifizieren.",emoji:"🦖"},
  {id:"kdino_121",q:"Wie viele Ausläufer hatte der Knochen-Kragen eines Triceratops?",a:5,unit:"Ausläufer",hint:"Gezackter Rand des Nackenschilds.",emoji:"🦏"},
  {id:"kdino_122",q:"Wie schwer war ein Rapetosaurus in Tonnen?",a:8,unit:"Tonnen",hint:"Titanosauride aus Madagaskar.",emoji:"🦕"},
  {id:"kdino_123",q:"Wie lang war ein Iguanodon-Daumen-Stachel in cm?",a:15,unit:"cm",hint:"Wurde als Verteidigungswaffe genutzt.",emoji:"🦖"},
  {id:"kdino_124",q:"Wie viele Arten von Dinosauriern gab es schätzungsweise?",a:1000,unit:"Arten",hint:"Nur ~700 sind bisher gefunden.",emoji:"🔍"},
  {id:"kdino_125",q:"Wie schwer war ein Pentaceratops in Tonnen?",a:5,unit:"Tonnen",hint:"Hatte fünf Horn-ähnliche Strukturen.",emoji:"🦏"},
  {id:"kdino_126",q:"Wie lang war ein Muttaburrasaurus in Metern?",a:8,unit:"Meter",hint:"Australischer Iguanodontide.",emoji:"🦕"},
  {id:"kdino_127",q:"Wie viele Finger hatte ein Tyrannosaurus Rex?",a:2,unit:"Finger",hint:"Zwei winzige Finger an den kleinen Armen.",emoji:"🦖"},
  {id:"kdino_128",q:"Wie schwer war ein Giganotosaurus in Tonnen?",a:7,unit:"Tonnen",hint:"Südamerikanischer Rivale des T-Rex.",emoji:"🦖"},
  {id:"kdino_129",q:"Wie lang war ein Shunosaurus in Metern?",a:11,unit:"Meter",hint:"Hatte eine knöcherne Keule am Schwanz.",emoji:"🦕"},
  {id:"kdino_130",q:"Wie viele Wirbel hatte ein Supersaurus im Hals?",a:15,unit:"Wirbel",hint:"Einer der längsten Dinosaurierhalse.",emoji:"🦕"},
  {id:"kdino_131",q:"Wie schwer war ein Lambeosaurus in Tonnen?",a:5,unit:"Tonnen",hint:"Hatte einen besonderen Kopfkamm.",emoji:"🦕"},
  {id:"kdino_132",q:"Wie lang war ein Euhelopus in Metern?",a:15,unit:"Meter",hint:"Sauropode aus China.",emoji:"🦕"},
  {id:"kdino_133",q:"Wie viele Milliarden Jahre nach Entstehung der Erde erschienen die ersten Dinosaurier?",a:4.2,unit:"Milliarden Jahre später",hint:"Erde 4,5 Mrd. Jahre alt – Dinos vor 230 Mio. Jahren.",emoji:"🌍"},
  {id:"kdino_134",q:"Wie schwer war ein Zuniceratops in kg?",a:100,unit:"kg",hint:"Früher kleiner Ceratopsier.",emoji:"🦏"},
  {id:"kdino_135",q:"Wie lang war ein Draconyx in Metern?",a:4,unit:"Meter",hint:"Iguanodontide aus Portugal.",emoji:"🦕"},
  {id:"kdino_136",q:"Wie viele Hornzähne hatte ein Psittacosaurus?",a:9,unit:"Zähne",hint:"Kleiner früher Ceratopsier.",emoji:"🦖"},
  {id:"kdino_137",q:"Wie schwer war ein Kritosaurus in Tonnen?",a:3,unit:"Tonnen",hint:"Hadrosaure aus Nordamerika.",emoji:"🦕"},
  {id:"kdino_138",q:"Wie lang war ein Isanosaurus in Metern?",a:15,unit:"Meter",hint:"Sauropode aus Thailand.",emoji:"🦕"}
,
  {id:"kdino_139",q:"Wie lang war die Zunge eines Brachiosaurus in cm?",a:60,unit:"cm",hint:"Perfekt um Blätter von Bäumen zu pflücken.",emoji:"🦕"},
  {id:"kdino_140",q:"Wie viele Eier konnte ein Oviraptor auf einmal legen?",a:22,unit:"Eier",hint:"Der Name bedeutet 'Eierdieb' – aber das stimmte nicht.",emoji:"🥚"},
  {id:"kdino_141",q:"Wie lang waren die Krallen eines Deinonychuss in cm?",a:12,unit:"cm",hint:"Diese Krallen machten ihn zu einem gefährlichen Jäger.",emoji:"🦖"},
  {id:"kdino_142",q:"Wie hoch konnte ein T-Rex aufrecht stehen in Metern?",a:6,unit:"Meter",hint:"So hoch wie ein zweistöckiges Haus.",emoji:"🦖"},
  {id:"kdino_143",q:"Wie viele Tonnen wog ein Brachiosaurus?",a:80,unit:"Tonnen",hint:"Eines der schwersten Tiere die je lebten.",emoji:"🦕"},
  {id:"kdino_144",q:"Wie viele Finger hatte ein T-Rex an jedem Arm?",a:2,unit:"Finger",hint:"Kleine Arme mit nur zwei Fingern.",emoji:"🦖"},
  {id:"kdino_145",q:"Wie schnell konnte ein Ornithomimus laufen in km/h?",a:60,unit:"km/h",hint:"Einer der schnellsten Dinosaurier.",emoji:"🏃"},
  {id:"kdino_146",q:"Wie lang wurde ein Parasaurolophus in Metern?",a:10,unit:"Meter",hint:"Bekannt für seinen langen Hohlkamm.",emoji:"🦕"},
  {id:"kdino_147",q:"Wie viele Kilogramm fraß ein T-Rex täglich?",a:230,unit:"kg",hint:"Viel Fleisch für ein so großes Tier.",emoji:"🦖"},
  {id:"kdino_148",q:"Wie viele Jahre lebten Dinosaurier durchschnittlich?",a:80,unit:"Jahre",hint:"Große Sauropoden wurden besonders alt.",emoji:"📅"},
  {id:"kdino_149",q:"Wie groß war das Gehirn eines T-Rex in cm³?",a:340,unit:"cm³",hint:"Kleiner als das menschliche Gehirn – aber er war trotzdem clever.",emoji:"🧠"},
  {id:"kdino_150",q:"Wie lang war ein Iguanodon in Metern?",a:10,unit:"Meter",hint:"Einer der ersten entdeckten Dinosaurier.",emoji:"🦖"},
  {id:"kdino_151",q:"Wie viele Federn hatte ein Archaeopteryx?",a:12,unit:"Schwanzfedern",hint:"Ein Übergangstier zwischen Dinosaurier und Vogel.",emoji:"🪶"},
  {id:"kdino_152",q:"Wie schwer war ein Triceratops-Schädel in kg?",a:400,unit:"kg",hint:"Einer der größten Tierköpfe aller Zeiten.",emoji:"💀"},
  {id:"kdino_153",q:"Wie weit konnte ein Pterodactylus gleiten in Metern?",a:100,unit:"Meter",hint:"Kein Dinosaurier aber ein fliegender Zeitgenosse.",emoji:"🦅"},
  {id:"kdino_154",q:"Wie viele Zehen hatte ein Velociraptor?",a:4,unit:"Zehen",hint:"Eine Zehe war die berühmte Sichelkralle.",emoji:"🦶"},
  {id:"kdino_155",q:"Wie lang war ein Diplodocus-Schwanz in Metern?",a:14,unit:"Meter",hint:"Wurde wie eine Peitsche eingesetzt.",emoji:"🦕"},
  {id:"kdino_156",q:"Wie schwer war ein Ceratosaurus in kg?",a:980,unit:"kg",hint:"Fast eine Tonne – ein mittelgroßer Fleischfresser.",emoji:"🦖"},
  {id:"kdino_157",q:"Wie lang war ein Allosaurus-Zahn in cm?",a:10,unit:"cm",hint:"Gezackt wie ein Sägeblatt.",emoji:"🦷"},
  {id:"kdino_158",q:"Wie hoch war der Rücken-Segel eines Spinosaurus in cm?",a:180,unit:"cm",hint:"Fast 2 Meter hoher Segel auf dem Rücken.",emoji:"🦖"},
  {id:"kdino_159",q:"Wie lang war ein Apatosaurus-Hals in Metern?",a:6,unit:"Meter",hint:"Früher auch Brontosaurus genannt.",emoji:"🦕"},
  {id:"kdino_160",q:"Wie viele Rippen hatte ein großer Sauropode?",a:24,unit:"Rippen",hint:"Sehr viele Rippen für den langen Körper.",emoji:"🦴"},
  {id:"kdino_161",q:"Wie schwer war ein Pachycephalosaurus in kg?",a:450,unit:"kg",hint:"Mittelschwerer Pflanzenfresser.",emoji:"🦖"},
  {id:"kdino_162",q:"Wie lang waren die Flügel eines Quetzalcoatlus?",a:11,unit:"Meter",hint:"Größter bekannter Flugsaurier.",emoji:"🦅"},
  {id:"kdino_163",q:"Wie weit konnte ein Dilophosaurus spucken laut Jurassic Park?",a:5,unit:"Meter",hint:"Im echten Leben spuckte er kein Gift – nur Hollywood.",emoji:"🎬"},
  {id:"kdino_164",q:"Wie lang war ein Mosasaurus in Metern?",a:17,unit:"Meter",hint:"Ein riesiger Meeresräuber – kein echter Dino.",emoji:"🌊"},
  {id:"kdino_165",q:"Wie alt wurden Schildkröten zur Dinosaurierzeit in Jahren?",a:100,unit:"Jahre",hint:"Schildkröten lebten schon mit Dinosauriern zusammen.",emoji:"🐢"},
  {id:"kdino_166",q:"Wie viele Stunden am Tag fraß ein Pflanzenfresser-Dino?",a:16,unit:"Stunden",hint:"Fast nonstop fressen um genug Energie zu bekommen.",emoji:"🌿"},
  {id:"kdino_167",q:"Wie lang war ein Corythosaurus-Kamm in cm?",a:50,unit:"cm",hint:"Helmartige Kopfform für Kommunikation.",emoji:"🦕"},
  {id:"kdino_168",q:"Wie schwer war ein Tyrannosaurus-Beinknochen in kg?",a:20,unit:"kg",hint:"Massive Knochen für das Gewicht.",emoji:"🦴"},
  {id:"kdino_169",q:"Wie viele Meter tief gruben Dinosaurier ihre Nester?",a:1,unit:"Meter",hint:"Manche Dinosaurier bauten tiefe Erdnester.",emoji:"🥚"},
  {id:"kdino_170",q:"Wie lang war ein Gallimimus in Metern?",a:6,unit:"Meter",hint:"Schneller Laufvogel-Dinosaurier.",emoji:"🏃"},
  {id:"kdino_171",q:"Wie viele km/h rannte ein Gallimimus?",a:50,unit:"km/h",hint:"Einer der schnellsten Dinosaurier.",emoji:"⚡"},
  {id:"kdino_172",q:"Wie hoch war ein ausgewachsener Brachiosaurus in Metern?",a:13,unit:"Meter",hint:"Konnte in ein vierstöckiges Fenster schauen.",emoji:"🦕"},
  {id:"kdino_173",q:"Wie lang war der Stachel eines Stegosaurus in cm?",a:90,unit:"cm",hint:"Die Schwanzstacheln wurden Thagomizer genannt.",emoji:"💪"},
  {id:"kdino_174",q:"Wie viele Millionen Jahre vor heute lebte der erste Vogel?",a:150,unit:"Millionen Jahre",hint:"Archaeopteryx – Übergang Dino zu Vogel.",emoji:"🐦"},
  {id:"kdino_175",q:"Wie schwer war ein Pachycephalosaurus-Schädelknochen in cm Dicke?",a:25,unit:"cm",hint:"Für Kopfstöße evolutionär entwickelt.",emoji:"💀"},
  {id:"kdino_176",q:"Wie lang war ein Compsognathus-Körper in cm?",a:60,unit:"cm",hint:"Einer der kleinsten bekannten Dinos.",emoji:"🐓"},
  {id:"kdino_177",q:"Wie viele Millionen Jahre lebte die Kreidezeit?",a:79,unit:"Millionen Jahre",hint:"Von 145 bis 66 Millionen Jahre vor heute.",emoji:"📅"},
  {id:"kdino_178",q:"Wie hoch wuchs ein Baumfarn zur Dinosaurierzeit in Metern?",a:15,unit:"Meter",hint:"Riesenpflanzen für riesige Pflanzenfresser.",emoji:"🌿"},
  {id:"kdino_179",q:"Wie viele Knochenstücke hatte ein Ankylosaurus-Panzer?",a:2000,unit:"Knochenstücke",hint:"Ein natürlicher Rüstungsanzug.",emoji:"🛡️"},
  {id:"kdino_180",q:"Wie lang war die Trächtigkeit eines großen Dinosauriers in Monaten?",a:6,unit:"Monate",hint:"Ähnlich wie bei großen heutigen Reptilien.",emoji:"🥚"},
  {id:"kdino_181",q:"Wie weit konnte ein Pteranodon pro Tag fliegen?",a:500,unit:"km",hint:"Ausdauernder Flieger über Ozeane.",emoji:"🦅"},
  {id:"kdino_182",q:"Wie lang war ein Amargasaurus-Hals-Stachel in cm?",a:60,unit:"cm",hint:"Doppelter Stachelkamm auf Hals und Rücken.",emoji:"🦕"},
  {id:"kdino_183",q:"Wie viele Sekunden dauerte ein Dinosaurier-Herzschlag?",a:0.3,unit:"Sekunden",hint:"Großes Herz – langsamer Puls.",emoji:"❤️"},
  {id:"kdino_184",q:"Wie schwer war ein Maiasaura-Baby bei der Geburt in kg?",a:0.5,unit:"kg",hint:"Pflegte seine Jungen im Nest.",emoji:"👶"},
  {id:"kdino_185",q:"Wie viele Kilogramm wog das größte bekannte Dinosaurier-Ei?",a:3,unit:"kg",hint:"Kg – groß aber nicht riesig (Stand ~2024).",emoji:"🥚"},
  {id:"kdino_186",q:"Wie lang war ein Dromaeosaurus in cm?",a:180,unit:"cm",hint:"Kleiner aber gefährlicher Raubdino.",emoji:"🦖"},
  {id:"kdino_187",q:"Wie hoch ragte der Segel eines Ouranosaurus in cm?",a:60,unit:"cm",hint:"Halber Meter – für Temperaturregulierung.",emoji:"🌡️"},
  {id:"kdino_188",q:"Wie viele Eier legte ein Maiasaura pro Nest?",a:30,unit:"Eier",hint:"Herdentiere die ihre Jungen pflegten.",emoji:"🥚"},
  {id:"kdino_189",q:"Wie lang war ein Hypsilophodon in cm?",a:150,unit:"cm",hint:"Kleiner schneller Pflanzenfresser.",emoji:"🦖"},
  {id:"kdino_190",q:"Wie weit konnte ein Dimorphodon fliegen in km?",a:50,unit:"km",hint:"Früher Flugsaurier aus dem Jura.",emoji:"🦅"},
  {id:"kdino_191",q:"Wie viele Tonnen fraß ein Brontosaurus wöchentlich?",a:3,unit:"Tonnen",hint:"3000 kg Pflanzen pro Woche.",emoji:"🌿"},
  {id:"kdino_192",q:"Wie viele Sauriarten lebten gleichzeitig in der Kreidezeit?",a:1000,unit:"Arten",hint:"Riesige Artenvielfalt.",emoji:"🦕"},
  {id:"kdino_193",q:"Wie lang war ein Microceratus in cm?",a:60,unit:"cm",hint:"Winziger Vorfahre der Ceratopsier.",emoji:"🦖"},
  {id:"kdino_194",q:"Wie viele Stunden schlief ein Dinosaurier täglich?",a:8,unit:"Stunden",hint:"Ähnlich wie heutige Krokodile.",emoji:"😴"},
  {id:"kdino_195",q:"Wie lang war ein Stegosaurus-Stachel in cm?",a:90,unit:"cm",hint:"Vier Schwanzstacheln als Verteidigung.",emoji:"⚔️"},
  {id:"kdino_196",q:"Wie schwer war ein neugeborener T-Rex in kg?",a:10,unit:"kg",hint:"Klein am Anfang – riesig als Erwachsener.",emoji:"👶"},
  {id:"kdino_197",q:"Wie viele Tage benötigte ein Dinosaurier-Ei zum Schlüpfen?",a:90,unit:"Tage",hint:"Drei Monate Brutzeit.",emoji:"🥚"},
  {id:"kdino_198",q:"Wie lang war ein Centrosaurus in Metern?",a:6,unit:"Meter",hint:"Herdentier mit einem Nasenhorn.",emoji:"🦏"},
  {id:"kdino_199",q:"Wie viele Sinne hatte ein Tyrannosaurus?",a:5,unit:"Sinne",hint:"Sehen, Hören, Riechen, Schmecken, Fühlen.",emoji:"👁️"},
  {id:"kdino_200",q:"Wie lang war ein Protoceratops in cm?",a:180,unit:"cm",hint:"Kleiner Vorfahre des Triceratops.",emoji:"🦖"},
  {id:"kdino_201",q:"Wie schwer war ein Iguanodon in Tonnen?",a:5,unit:"Tonnen",hint:"Einer der ersten beschriebenen Dinosaurier.",emoji:"🦴"},
  {id:"kdino_202",q:"Wie viele Rückenplatten hatte ein Stegosaurus?",a:17,unit:"Platten",hint:"In versetzten Reihen angeordnet.",emoji:"🦖"},
  {id:"kdino_203",q:"Wie lang war ein Suchomimus in Metern?",a:11,unit:"Meter",hint:"Fischfresser ähnlich dem Spinosaurus.",emoji:"🦖"},
  {id:"kdino_204",q:"Wie viele Millionen Jahre vor heute erschienen die ersten Säugetiere?",a:225,unit:"Millionen Jahre",hint:"Gleichzeitig mit den ersten Dinosauriern.",emoji:"🐭"},
  {id:"kdino_205",q:"Wie hoch wuchs ein Schachtelhalm zur Triaszeit in Metern?",a:15,unit:"Meter",hint:"Riesenpflanzen die heute nur klein sind.",emoji:"🌿"},
  {id:"kdino_206",q:"Wie viele Tonnen wog ein Laplatasaurus?",a:90,unit:"Tonnen",hint:"Einer der schwersten Sauropoden.",emoji:"🦕"},
  {id:"kdino_207",q:"Wie lang war ein Edmontosaurus in Metern?",a:13,unit:"Meter",hint:"Großer Entenschnabel-Dinosaurier.",emoji:"🦕"},
  {id:"kdino_208",q:"Wie viele Stunden am Tag bewegten sich Sauropoden?",a:18,unit:"Stunden",hint:"Fast nonstop wandern und fressen.",emoji:"🚶"},
  {id:"kdino_209",q:"Wie weit sprangen Dromaeasauriden in Metern?",a:4,unit:"Meter",hint:"Springend auf ihre Beute.",emoji:"🦘"},
  {id:"kdino_210",q:"Wie viele Millionen Arten lebten in der Jurazeit?",a:500,unit:"Tausend ",hint:"Enorme Vielfalt im Erdzeitalter.",emoji:"🌍"},
  {id:"kdino_211",q:"Wie lang war ein Camarasaurus in Metern?",a:23,unit:"Meter",hint:"Häufigster Sauropode Nordamerikas.",emoji:"🦕"},
  {id:"kdino_212",q:"Wie viele Wirbelknochen hatte ein Diplodocus?",a:90,unit:"Wirbel",hint:"Langer Hals und Schwanz ergeben viele Wirbel.",emoji:"🦴"},
  {id:"kdino_213",q:"Wie schwer war ein Torosaurus-Schädel in kg?",a:700,unit:"kg",hint:"Größter Tierschädel aller Zeiten.",emoji:"💀"},
  {id:"kdino_214",q:"Wie lang war ein Maiasaura in Metern?",a:9,unit:"Meter",hint:"Bedeutet 'gute Mutter-Echse'.",emoji:"🦕"},
  {id:"kdino_215",q:"Wie viele km/h konnte ein Ceratosaurus rennen?",a:30,unit:"km/h",hint:"Mittelschneller Fleischfresser.",emoji:"🏃"},
  {id:"kdino_216",q:"Wie tief waren Dinosaurierspuren im Schlamm in cm?",a:30,unit:"cm",hint:"Tiefe Abdrücke großer Sauropoden.",emoji:"👣"},
  {id:"kdino_217",q:"Wie viele Millionen Jahre vor heute erschienen die ersten Krokodile?",a:230,unit:"Millionen Jahre",hint:"Lebten gleichzeitig mit Dinosauriern.",emoji:"🐊"},
  {id:"kdino_218",q:"Wie lang war ein Zuniceratops in cm?",a:300,unit:"cm",hint:"Früher Vorläufer der Ceratopsier.",emoji:"🦏"},
  {id:"kdino_219",q:"Wie schwer war ein Pachyrhinosaurus in Tonnen?",a:4,unit:"Tonnen",hint:"Lebte in Herden in Nordamerika.",emoji:"🦕"},
  {id:"kdino_220",q:"Wie lang war ein Lesothosaurus in cm?",a:100,unit:"cm",hint:"Kleiner früher Ornithischier.",emoji:"🦖"},
  {id:"kdino_221",q:"Wie viele Eier legte ein Titanosaur pro Saison?",a:25,unit:"Eier",hint:"Kleine Eier für ein riesiges Tier.",emoji:"🥚"},
  {id:"kdino_222",q:"Wie weit wanderten Dinosaurier-Herden pro Jahr in km?",a:500,unit:"km",hint:"Saisonale Wanderungen auf der Suche nach Nahrung.",emoji:"🚶"},
  {id:"kdino_223",q:"Wie viele Tonnen wog ein Giraffatitan?",a:60,unit:"Tonnen",hint:"Afrikanischer Verwandter des Brachiosaurus.",emoji:"🦕"},
  {id:"kdino_224",q:"Wie lang war ein Gorgosaurus in Metern?",a:9,unit:"Meter",hint:"Kleinerer Verwandter des T-Rex.",emoji:"🦖"},
  {id:"kdino_225",q:"Wie lang war ein Stygimoloch-Horn in cm?",a:15,unit:"cm",hint:"Kopfhörner für Kämpfe.",emoji:"🦖"},
  {id:"kdino_226",q:"Wie schwer war das größte Dinosaurier-Ei in Kilogramm?",a:5,unit:"Kilogramm",hint:"5kg – das schwerste bekannte Ei (Stand ~2024).",emoji:"🥚"},
  {id:"kdino_227",q:"Wie viele Kilometer wanderte ein Jobaria täglich?",a:20,unit:"km",hint:"Afrikanischer Langhals-Sauropode.",emoji:"🦕"},
  {id:"kdino_228",q:"Wie tief war ein Sauropoden-Fußabdruck in cm?",a:40,unit:"cm",hint:"Massive Abdrücke im weichen Boden.",emoji:"👣"},
  {id:"kdino_229",q:"Wie lang war ein Sauropodomorpha in Metern?",a:10,unit:"Meter",hint:"Frühe Vorfahren der großen Sauropoden.",emoji:"🦕"},
  {id:"kdino_230",q:"Wie viele Millionen Jahre existierten Dinosaurier insgesamt?",a:165,unit:"Millionen Jahre",hint:"Viel länger als Menschen bisher.",emoji:"📅"},
  {id:"kdino_231",q:"Wie schwer war ein junger T-Rex mit 10 Jahren in kg?",a:2000,unit:"kg",hint:"Er wuchs schnell – bis zu 2kg pro Tag.",emoji:"🦖"},
  {id:"kdino_232",q:"Wie lang war ein Dimorphodon-Flügelspanne in cm?",a:140,unit:"cm",hint:"Früher Flugsaurier aus dem Jura.",emoji:"🦅"},
  {id:"kdino_233",q:"Wie viele Kilogramm fraß ein Supersaurus täglich?",a:500,unit:"kg",hint:"Pflanzen pro Tag.",emoji:"🌿"},
  {id:"kdino_234",q:"Wie lang war ein Tsintaosaurus in Metern?",a:10,unit:"Meter",hint:"Chinesischer Entenschnabel-Dinosaurier.",emoji:"🦕"},
  {id:"kdino_235",q:"Wie schwer war ein Therizinosaurus in Tonnen?",a:6,unit:"Tonnen",hint:"Riesige Klauen – aber Pflanzenfresser.",emoji:"🦖"}
];
