// 🏰 MÄRCHEN & FANTASIE – Kinder – 30 Fragen
export default [
  {q:"Wie viele Zwerge hat Schneewittchen?",a:7,unit:"Zwerge",hint:"Sie alle haben Namen: Schlafmütze, Brummbär, Hatschi...",emoji:"🏔️"},
  {q:"Wie viele Jahre schlief Dornröschen?",a:100,unit:"Jahre",hint:"Bis sie ein Prinz wachküsste.",emoji:"🌹"},
  {q:"Wie viele Wünsche erfüllt der Geist aus der Wunderlampe in Aladdin?",a:3,unit:"Wünsche",hint:"3 Wünsche – dann muss der Geist in die Lampe zurück.",emoji:"🪔"},
  {q:"Wie viele Geschwister hat Aschenputtel (Stiefschwestern)?",a:2,unit:"Stiefschwestern",hint:"Zwei böse Stiefschwestern.",emoji:"👠"},
  {q:"Wie viele Brüder hat die kleine Meerjungfrau Ariel?",a:6,unit:"Brüder",hint:"Nein – sie hat 6 Schwestern.",emoji:"🧜‍♀️"},
  {q:"Wie viele Etagen hat Rapunzels Turm?",a:1,unit:"Etagen",hint:"Ein einziger hoher Raum ganz oben.",emoji:"🏰"},
  {q:"Wie viele Zwerge helfen den Gnomen im Märchen Snow White?",a:7,unit:"Zwerge",hint:"Die Sieben Zwerge sind weltberühmt.",emoji:"⛏️"},
  {q:"Wie viele Jahre braucht der gestiefelten Kater um seinen Herrn reich zu machen?",a:1,unit:"Jahr",hint:"Im Märchen geht es sehr schnell.",emoji:"🐱"},
  {q:"Wie viele Schwestern hat Aschenputtel?",a:2,unit:"Schwestern",hint:"Beide wollen den Prinzen für sich.",emoji:"👗"},
  {q:"Wie viele Söhne hat der König im Märchen 'Der Froschkönig'?",a:0,unit:"Söhne",hint:"Er hat Töchter – die Prinzessin ist der Hauptcharakter.",emoji:"🐸"},
  {q:"Wie viele Goldmünzen versteckt Rumpelstilzchen?",a:0,unit:"Münzen",hint:"Er will kein Gold – er will das Baby.",emoji:"👶"},
  {q:"Wie viele Hänsel und Gretel Kinder gibt es im Märchen?",a:2,unit:"Kinder",hint:"Hänsel UND Gretel – ein Bruder-Schwester-Paar.",emoji:"🏠"},
  {q:"Wie viele Meter lang ist Rapunzels Haar laut Märchen?",a:20,unit:"Meter",hint:"Lang genug für den Prinzen zum Hochklettern.",emoji:"👱‍♀️"},
  {q:"Wie viele Söhne hat der Müller in Rumpelstilzchen?",a:0,unit:"Söhne",hint:"Er hat eine Tochter – die spinnt Stroh zu Gold.",emoji:"🌾"},
  {q:"Wie viele Wölfe gibt es im Märchen 'Die sieben Geißlein'?",a:1,unit:"Wolf",hint:"Ein böser Wolf – der große böse Wolf.",emoji:"🐺"},
  {q:"Wie viele Geißlein frisst der Wolf?",a:6,unit:"Geißlein",hint:"Das jüngste versteckte sich in der Wanduhr.",emoji:"🐐"},
  {q:"Wie viele Schuhe verliert Aschenputtel?",a:1,unit:"Schuh",hint:"Den gläsernen Schuh auf der Treppe.",emoji:"👠"},
  {q:"Wie viele Charaktere besuchen die Bremer Stadtmusikanten?",a:4,unit:"Tiere",hint:"Esel, Hund, Katze, Hahn.",emoji:"🎵"},
  {q:"Wie viele Becher trinkt Schneewittchen von der bösen Königin?",a:0,unit:"Becher",hint:"Sie isst einen vergifteten Apfel – keinen Becher.",emoji:"🍎"},
  {q:"Wie viele Prinzessinnen tanzen die Nacht durch im Märchen 'Die zertanzten Schuhe'?",a:12,unit:"Prinzessinnen",hint:"12 Schwestern tanzen heimlich.",emoji:"👠"},
  {q:"Wie viele Stockwerke hat das Schloss von Dornröschen?",a:0,unit:"Stockwerke",hint:"Im Märchen wird die Etage nicht erwähnt.",emoji:"🏰"},
  {q:"Wie viele Küsse braucht der Froschkönig um Mensch zu werden?",a:1,unit:"Kuss",hint:"Ein einziger Kuss der Prinzessin.",emoji:"🐸"},
  {q:"Wie viele Schwestern hat Cinderella in Disneys Version?",a:2,unit:"Stiefschwestern",hint:"Anastasia und Drizella.",emoji:"👑"},
  {q:"Wie viele Jahre schläft die Schöne im Dornröschen?",a:100,unit:"Jahre",hint:"Das gesamte Schloss schläft mit.",emoji:"😴"},
  {q:"Wie viele Goldmünzen bekommt der Bauer durch Hänsel und Gretel?",a:0,unit:"Münzen",hint:"Es geht nicht um Gold – sondern ums Überleben.",emoji:"🍬"},
  {q:"Wie viele Kinder hat die böse Hexe in Hänsel und Gretel?",a:0,unit:"Kinder",hint:"Sie hat keine eigenen Kinder.",emoji:"🏠"},
  {q:"Wie viele Stunden braucht Cinderella um nach Hause zu kommen?",a:0,unit:"Stunden",hint:"Der Zauber endet um Mitternacht.",emoji:"🕛"},
  {q:"Wie viele Tiere helfen Schneewittchen im Wald?",a:7,unit:"Waldtiere",hint:"Die Waldtiere helfen ihr das Haus der Zwerge zu finden.",emoji:"🦌"},
  {q:"Wie viele Male versucht die Hexe Schneewittchen zu töten?",a:3,unit:"Male",hint:"Haarband, Kamm und vergifteter Apfel.",emoji:"🍎"},
  {q:"Wie viele Söhne hat Rumpelstilzchen?",a:0,unit:"Söhne",hint:"Er hat keine – er will das Baby der Müllerstochter.",emoji:"👶"},
];
