// 🏆 SPORT & REKORDE – Kinder
export default [
  {id:"ksport_001",q:"Wie viele Kilometer ist ein Marathon lang?",a:42.195,unit:"km",hint:"Benannt nach dem Lauf eines Boten aus Marathon nach Athen.",emoji:"🏃"},
  {id:"ksport_002",q:"Wie schnell lief Usain Bolt seinen Weltrekord über 100m in Sekunden?",a:9.58,unit:"Sekunden",hint:"Aufgestellt 2009 in Berlin.",emoji:"⚡"},
  {id:"ksport_003",q:"Wie viele Goldmedaillen gewann Michael Phelps bei Olympia?",a:23,unit:"Goldmedaillen",hint:"Der erfolgreichste Olympiateilnehmer aller Zeiten.",emoji:"🏊"},
  {id:"ksport_004",q:"Wie hoch ist ein Basketballkorb in Metern?",a:3.05,unit:"Meter",hint:"Die offizielle Höhe in der NBA und bei Olympia.",emoji:"🏀"},
  {id:"ksport_005",q:"Wie viele Spieler stehen beim Fußball auf dem Platz (beide Teams)?",a:22,unit:"Spieler",hint:"11 pro Mannschaft.",emoji:"⚽"},
  {id:"ksport_006",q:"Wie lang ist ein olympisches Schwimmbecken in Metern?",a:50,unit:"Meter",hint:"Die offizielle Länge für Weltrekorde.",emoji:"🏊"},
  {id:"ksport_007",q:"Wie viele Punkte bekommt man bei einem Touchdown im American Football?",a:6,unit:"Punkte",hint:"Dazu kommt noch ein Extra-Punkt für den Kick.",emoji:"🏈"},
  {id:"ksport_008",q:"Wie hoch ist ein Volleyballnetz bei Männern in Metern?",a:2.43,unit:"Meter",hint:"Bei Frauen ist es 2,24 Meter hoch.",emoji:"🏐"},
  {id:"ksport_009",q:"Wie viele km fährt ein Tour-de-France-Fahrer insgesamt?",a:3500,unit:"km",hint:"Über 21 Etappen in 3 Wochen.",emoji:"🚴"},
  {id:"ksport_010",q:"Wie lange dauert ein Eishockeyspiel in Minuten (reine Spielzeit)?",a:60,unit:"Minuten",hint:"3 Drittel à 20 Minuten.",emoji:"🏒"},
  {id:"ksport_011",q:"Wie viele Runden hat ein Formel-1-Rennen durchschnittlich?",a:57,unit:"Runden",hint:"Je nach Streckenlänge variiert die Rundenzahl.",emoji:"🏎️"},
  {id:"ksport_012",q:"Wie viele Meter hoch ist der Hochsprung-Weltrekord?",a:2.45,unit:"Meter",hint:"Javier Sotomayor stellte 1993 diesen Rekord auf.",emoji:"🏃"},
  {id:"ksport_013",q:"Wie viele Punkte braucht man im Tischtennis zum Gewinnen eines Satzes?",a:11,unit:"Punkte",hint:"Mit 2 Punkten Vorsprung muss man gewinnen.",emoji:"🏓"},
  {id:"ksport_014",q:"Wie lang ist ein Fußballfeld maximal in Metern?",a:105,unit:"Meter",hint:"Die FIFA-Vorgabe ist 100–110 Meter.",emoji:"⚽"},
  {id:"ksport_015",q:"Wie viele Spieler hat eine Baseballmannschaft?",a:9,unit:"Spieler",hint:"Feldspieler und ein Schlagmann.",emoji:"⚾"},
  {id:"ksport_016",q:"Wie viele Meter weit springt man beim Weitsprung-Weltrekord?",a:8.95,unit:"Meter",hint:"Mike Powell sprang 1991 in Tokio diesen Rekord.",emoji:"🏃"},
  {id:"ksport_017",q:"Wie viele Stunden dauerte das längste Tennisspiel aller Zeiten?",a:11,unit:"Stunden",hint:"Isner vs. Mahut 2010 in Wimbledon.",emoji:"🎾"},
  {id:"ksport_018",q:"Wie viele Mal hat Bayern München die Bundesliga gewonnen?",a:32,unit:"Mal",hint:"Deutschlands erfolgreichster Fußballklub.",emoji:"⚽"},
  {id:"ksport_019",q:"Wie groß ist ein Basketballfeld in Metern Länge?",a:28,unit:"Meter",hint:"Das offizielle FIBA-Spielfeld ist diese Zahl x 15 Meter.",emoji:"🏀"},
  {id:"ksport_020",q:"Wie viele Spieler hat ein Rugbyteam?",a:15,unit:"Spieler",hint:"Im Rugby League sind es 13 Spieler.",emoji:"🏉"},
  {id:"ksport_021",q:"Wie viele Schritte darf man im Basketball ohne Dribbeln machen?",a:2,unit:"Schritte",hint:"Bei 3 Schritten gibt es Schrittfehler.",emoji:"🏀"},
  {id:"ksport_022",q:"Wie viele km/h erreichte der schnellste Tennisaufschlag?",a:263,unit:"km/h",hint:"Samuel Groth aus Australien, 2012.",emoji:"🎾"},
  {id:"ksport_023",q:"Wie viele km weit wirft man beim Speerwurf-Weltrekord?",a:98.48,unit:"Meter",hint:"Jan Železný aus Tschechien, 1996.",emoji:"🎯"},
  {id:"ksport_024",q:"Wie viele Tore schoss Ronaldo in seiner Karriere ungefähr?",a:900,unit:"Tore",hint:"Er ist einer der erfolgreichsten Torschützen aller Zeiten.",emoji:"⚽"},
  {id:"ksport_025",q:"Wie viele PS hat ein Formel-1-Motor?",a:1000,unit:"PS",hint:"Moderne F1-Motoren leisten über 1000 PS.",emoji:"🏎️"},
  {id:"ksport_026",q:"Wie hoch ist ein Tischtennis-Netz in cm?",a:15.25,unit:"cm",hint:"Nur 15,25 cm – das ist sehr niedrig!",emoji:"🏓"},
  {id:"ksport_027",q:"Wie viele Goldmedaillen hat Usain Bolt bei Olympia gewonnen?",a:8,unit:"Goldmedaillen",hint:"3x Olympia, immer Gold über 100m, 200m und 4x100m.",emoji:"🏅"},
  {id:"ksport_028",q:"Wie schwer ist ein Fußball in Gramm?",a:430,unit:"Gramm",hint:"Die FIFA schreibt 410–450 Gramm vor.",emoji:"⚽"},
  {id:"ksport_029",q:"Wie lang ist eine Olympia-Bahn beim Schwimmen in Metern?",a:50,unit:"Meter",hint:"Kurzbahn-Wettkämpfe finden auf 25 Meter statt.",emoji:"🏊"},
  {id:"ksport_030",q:"Wie viele Felder hat ein Schachbrett?",a:64,unit:"Felder",hint:"8 x 8 Felder, abwechselnd schwarz und weiß.",emoji:"♟️"},
{id:"ksport_031",q:"Wie viele Spieler hat eine Fußballmannschaft?",a:11,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"⚽"},
  {id:"ksport_032",q:"Wie groß ist ein offizielles Fußballfeld in Metern?",a:105,unit:"Meter Länge",hint:"× 68 Meter.",emoji:"⚽"},
  {id:"ksport_033",q:"Wie viele Goldmedaillen hat Michael Phelps?",a:23,unit:"Goldmedaillen",hint:"Erfolgreichster Olympionike aller Zeiten.",emoji:"🏊"},
  {id:"ksport_034",q:"Wie lang ist ein Olympisches Schwimmbecken?",a:50,unit:"Meter",hint:"Für Weltrekorde.",emoji:"🏊"},
  {id:"ksport_035",q:"Wie schnell lief Usain Bolt seine 100m in Sekunden?",a:9.58,unit:"Sekunden",hint:"Berlin 2009.",emoji:"⚡"},
  {id:"ksport_036",q:"Wie viele km ist ein Marathon lang?",a:42.195,unit:"km",hint:"Benannt nach dem Lauf eines Boten.",emoji:"🏃"},
  {id:"ksport_037",q:"Wie viele Punkte braucht man im Tischtennis?",a:11,unit:"Punkte",hint:"Mit 2 Punkten Vorsprung.",emoji:"🏓"},
  {id:"ksport_038",q:"Wie viele Spieler hat ein Rugby-Team?",a:15,unit:"Spieler",hint:"Im Rugby League 13.",emoji:"🏉"},
  {id:"ksport_039",q:"Wie hoch ist ein Volleyball-Netz bei Männern?",a:2.43,unit:"Meter",hint:"Bei Frauen 2,24 Meter.",emoji:"🏐"},
  {id:"ksport_040",q:"Wie viele Runden hat ein Formel-1-Rennen?",a:57,unit:"Runden",hint:"Je nach Streckenlänge.",emoji:"🏎️"},
  {id:"ksport_041",q:"Wie weit springt man beim Weitsprung-Weltrekord?",a:8.95,unit:"Meter",hint:"Mike Powell, Tokio 1991.",emoji:"🏃"},
  {id:"ksport_042",q:"Wie viele km fährt ein Tour-de-France-Fahrer?",a:3500,unit:"km",hint:"21 Etappen in 3 Wochen.",emoji:"🚴"},
  {id:"ksport_043",q:"Wie lang ist ein Eishockeyspiel in Minuten?",a:60,unit:"Minuten",hint:"3 Drittel à 20 Minuten.",emoji:"🏒"},
  {id:"ksport_044",q:"Wie viele Schritte darf man im Basketball?",a:2,unit:"Schritte",hint:"Bei 3 Schritten: Schrittfehler.",emoji:"🏀"},
  {id:"ksport_045",q:"Wie viele km/h schlägt Serena Williams einen Aufschlag?",a:207,unit:"km/h",hint:"Rekord für Frauen.",emoji:"🎾"},
  {id:"ksport_046",q:"Wie viele Spieler hat ein Baseballteam?",a:9,unit:"Spieler",hint:"Feldspieler.",emoji:"⚾"},
  {id:"ksport_047",q:"Wie viele Punkte ist ein Touchdown?",a:6,unit:"Punkte",hint:"Plus Extra-Punkt für den Kick.",emoji:"🏈"},
  {id:"ksport_048",q:"Wie viele Stunden dauerte das längste Tennisspiel?",a:11,unit:"Stunden",hint:"Isner vs. Mahut 2010 in Wimbledon.",emoji:"🎾"},
  {id:"ksport_049",q:"Wie hoch ist das Tischtennis-Netz in cm?",a:15.25,unit:"cm",hint:"Sehr niedrig.",emoji:"🏓"},
  {id:"ksport_050",q:"Wie viele Punkte gibt es beim Darts pro Pfeil maximal?",a:60,unit:"Punkte",hint:"Dreifach-20 = 60 Punkte.",emoji:"🎯"},
  {id:"ksport_051",q:"Wie viele km/h fliegt ein Badminton-Federball maximal?",a:493,unit:"km/h",hint:"Schnellstes Sportgerät der Welt.",emoji:"🏸"},
  {id:"ksport_052",q:"Wie groß ist ein Basketballfeld in Metern?",a:28,unit:"Meter Länge",hint:"× 15 Meter.",emoji:"🏀"},
  {id:"ksport_053",q:"Wie viele Goldmedaillen hat Usain Bolt bei Olympia?",a:8,unit:"Goldmedaillen",hint:"3x Olympia, immer Gold.",emoji:"🏅"},
  {id:"ksport_054",q:"Wie viele Spieler hat ein Handballteam auf dem Feld?",a:7,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"🤾"},
  {id:"ksport_055",q:"Wie hoch ist ein Turnreck in Metern?",a:2.8,unit:"Meter",hint:"Das Hochreck bei Männern.",emoji:"🤸"},
  {id:"ksport_056",q:"Wie lang ist eine Olympische Laufbahn in Metern?",a:400,unit:"Meter",hint:"Alle Stadien haben 400m Bahnen.",emoji:"🏃"},
  {id:"ksport_057",q:"Wie viele Spieler hat eine Eishockeymannschaft auf dem Eis?",a:6,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"🏒"},
  {id:"ksport_058",q:"Wie viele km/h fährt ein Formel-1-Auto maximal?",a:370,unit:"km/h",hint:"Auf langen Geraden.",emoji:"🏎️"},
  {id:"ksport_059",q:"Wie lang ist eine Schwimmbahn bei den Olympischen Spielen?",a:50,unit:"Meter",hint:"Long Course – für alle Weltrekorde.",emoji:"🏊"},
  {id:"ksport_060",q:"Wie viele Pins stehen beim Bowling?",a:10,unit:"Pins",hint:"Im Dreieck aufgestellt.",emoji:"🎳"},
  {id:"ksport_061",q:"Wie viele Spieler hat ein Wasserball-Team?",a:7,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"🤽"},
  {id:"ksport_062",q:"Wie hoch ist ein Sprungbrett bei Olympia in Metern?",a:10,unit:"Meter",hint:"Turm-Springen von 10m.",emoji:"🏊"},
  {id:"ksport_063",q:"Wie viele Pferde zieht ein Schlitten beim Hundeschlittenrennen Iditarod?",a:16,unit:"Hunde",hint:"Keine Pferde – Hunde!",emoji:"🐕"},
  {id:"ksport_064",q:"Wie viele km lang ist das Iditarod-Rennen?",a:1600,unit:"km",hint:"Von Anchorage nach Nome, Alaska.",emoji:"🛷"},
  {id:"ksport_065",q:"Wie viele Spieler hat ein Rugby-Sevens-Team?",a:7,unit:"Spieler",hint:"Kleiner als normales Rugby.",emoji:"🏉"},
  {id:"ksport_066",q:"Wie hoch ist ein Hochsprung-Weltrekord in Metern?",a:2.45,unit:"Meter",hint:"Javier Sotomayor, 1993.",emoji:"🏃"},
  {id:"ksport_067",q:"Wie viele Runden hat ein Boxkampf maximal?",a:12,unit:"Runden",hint:"Profi-Weltmeisterschaftskampf.",emoji:"🥊"},
  {id:"ksport_068",q:"Wie lang ist eine Curveball-Wurfbahn beim Baseball in Metern?",a:18.44,unit:"Meter",hint:"Der Pitching-Abstand.",emoji:"⚾"},
  {id:"ksport_069",q:"Wie viele Spieler hat ein Cricketteam?",a:11,unit:"Spieler",hint:"Gleich wie Fußball.",emoji:"🏏"},
  {id:"ksport_070",q:"Wie viele Hürden überquert ein Läufer beim 110m-Hürdenlauf?",a:10,unit:"Hürden",hint:"Hürden á 1,067m Höhe.",emoji:"🏃"},
  {id:"ksport_071",q:"Wie viele Kegel stehen beim Kegeln?",a:9,unit:"Kegel",hint:"Im deutschen Kegeln – anders als Bowling.",emoji:"🎳"},
  {id:"ksport_072",q:"Wie schwer ist ein Diskus bei Frauen in kg?",a:1,unit:"kg",hint:"Bei Männern 2 kg.",emoji:"🥏"},
  {id:"ksport_073",q:"Wie lang ist ein Olympisches Ruderrennen in km?",a:2,unit:"km",hint:"2000 Meter auf ruhigem Wasser.",emoji:"🚣"},
  {id:"ksport_074",q:"Wie hoch ist ein Turnbarren vom Boden in Metern?",a:2,unit:"Meter",hint:"Parallelbarren bei Männern.",emoji:"🤸"},
  {id:"ksport_075",q:"Wie viele km weit wirft der Speerwurf-Weltrekord?",a:98.48,unit:"Meter",hint:"Jan Železný, 1996.",emoji:"🎯"},
  {id:"ksport_076",q:"Wie viele Spieler hat ein Volleyball-Team auf dem Feld?",a:6,unit:"Spieler",hint:"Inklusive Libero.",emoji:"🏐"},
  {id:"ksport_077",q:"Wie lang ist ein Fußballtrikot-Kurzärmel-Ärmel maximal in cm?",a:30,unit:"cm",hint:"Geregelt in FIFA-Ausrüstungsregeln.",emoji:"👕"},
  {id:"ksport_078",q:"Wie hoch ist die Tischtennisplatte vom Boden in cm?",a:76,unit:"cm",hint:"Standardhöhe weltweit.",emoji:"🏓"},
  {id:"ksport_079",q:"Wie lang ist eine Badminton-Bahn in Metern?",a:13.4,unit:"Meter",hint:"13,4 × 6,1 Meter für Doppel.",emoji:"🏸"},
  {id:"ksport_080",q:"Wie viele Spieler hat ein American-Football-Team auf dem Feld?",a:11,unit:"Spieler",hint:"Offense AND Defense je 11.",emoji:"🏈"},
  {id:"ksport_081",q:"Wie groß ist ein Golfball im Durchmesser in mm?",a:42.67,unit:"mm",hint:"Mindestdurchmesser nach Regelwerk.",emoji:"⛳"},
  {id:"ksport_082",q:"Wie lang ist eine Olympisches Ruder-Skullyboot in Metern?",a:8,unit:"Meter",hint:"Einer sitzt – 2 Ruder.",emoji:"🚣"},
  {id:"ksport_083",q:"Wie viele Spieler hat ein Lacrosse-Team auf dem Feld?",a:10,unit:"Spieler",hint:"Bei Männern – bei Frauen 12.",emoji:"🥍"},
  {id:"ksport_084",q:"Wie hoch ist ein Fußballtor in Metern?",a:2.44,unit:"Meter",hint:"2,44m × 7,32m breit.",emoji:"⚽"},
  {id:"ksport_085",q:"Wie viele Stunden dauerte die längste Schachpartie?",a:20,unit:"Stunden",hint:"Klassisches Schach ohne Zeitkontrolle (Stand ~2024).",emoji:"♟️"},
  {id:"ksport_086",q:"Wie viele km/h schießt ein Tennisball beim schnellsten Aufschlag?",a:263,unit:"km/h",hint:"Samuel Groth, 2012.",emoji:"🎾"},
  {id:"ksport_087",q:"Wie lang ist eine Olympische Triathlon-Schwimmstrecke in km?",a:1.5,unit:"km",hint:"Dann 40km Radfahren und 10km Laufen.",emoji:"🏊"},
  {id:"ksport_088",q:"Wie viele Punkte braucht man im Squash pro Satz?",a:11,unit:"Punkte",hint:"Best of 5 Sätze.",emoji:"🎾"},
  {id:"ksport_089",q:"Wie lang ist ein Eishockeyfeld in Metern?",a:61,unit:"Meter",hint:"× 30 Meter – NHL-Standard.",emoji:"🏒"},
  {id:"ksport_090",q:"Wie hoch ist das Netz beim Beach-Volleyball bei Männern?",a:2.43,unit:"Meter",hint:"Gleich wie Hallen-Volleyball.",emoji:"🏐"},
  {id:"ksport_091",q:"Wie viele Spieler hat ein Fußball-Kader bei der WM?",a:26,unit:"Spieler",hint:"Seit der WM 2022.",emoji:"⚽"},
  {id:"ksport_092",q:"Wie schwer ist eine Kugel beim Kugelstoßen bei Männern in kg?",a:7.26,unit:"kg",hint:"Bei Frauen 4 kg.",emoji:"🏋️"},
  {id:"ksport_093",q:"Wie lang ist eine Bowlingbahn in Metern?",a:18.29,unit:"Meter",hint:"Von der Abwurflinie zu den Pins.",emoji:"🎳"},
  {id:"ksport_094",q:"Wie hoch ist ein Fußball-Tor bei Frauen in Metern?",a:2.44,unit:"Meter",hint:"Gleich wie bei Männern.",emoji:"⚽"},
  {id:"ksport_095",q:"Wie viele Schritte macht ein Marathonläufer?",a:40000,unit:"Schritte",hint:"Etwa 40.000 Schritte pro Marathon.",emoji:"🏃"},
  {id:"ksport_096",q:"Wie lang ist ein Biathlon-Lauf in km?",a:20,unit:"km",hint:"Plus 4 Schießeinlagen.",emoji:"🎯"},
  {id:"ksport_097",q:"Wie viele Runden dreht ein Radfahrer bei der Olympischen Bahn-Jagd?",a:16,unit:"Runden",hint:"4km auf einer 250m-Bahn.",emoji:"🚴"},
  {id:"ksport_098",q:"Wie viele Punkte hat ein Golfball Grübchen?",a:336,unit:"Grübchen",hint:"Standard sind 300-500 Dimples.",emoji:"⛳"},
  {id:"ksport_099",q:"Wie lang ist eine Olympische Kanu-Slalom-Strecke in Metern?",a:250,unit:"Meter",hint:"Mit mindestens 18 Toren.",emoji:"🚣"},
  {id:"ksport_100",q:"Wie hoch ist ein Turnpferd (Pauschenpferd) in Metern?",a:1.15,unit:"Meter",hint:"Standarthöhe laut FIG.",emoji:"🤸"},
  {id:"ksport_101",q:"Wie viele km/h fährt ein Ski-Abfahrtsfahrer maximal?",a:160,unit:"km/h",hint:"Die schnellste alpine Disziplin.",emoji:"⛷️"},
  {id:"ksport_102",q:"Wie viele Spieler hat ein Curling-Team?",a:4,unit:"Spieler",hint:"Ein Skip und drei Sweeper.",emoji:"🥌"},
  {id:"ksport_103",q:"Wie lang ist eine Olympische 400m-Hürdenstrecke?",a:400,unit:"Meter",hint:"10 Hürden à 91,4cm Höhe bei Männern.",emoji:"🏃"},
  {id:"ksport_104",q:"Wie schwer ist ein Hammerball beim Hammerwurf in kg?",a:7.26,unit:"kg",hint:"Bei Frauen 4 kg.",emoji:"🔨"},
  {id:"ksport_105",q:"Wie viele km/h schießt ein Eishockey-Puck maximal?",a:175,unit:"km/h",hint:"Bei professionellen Slap Shots.",emoji:"🏒"},
  {id:"ksport_106",q:"Wie viele Spieler hat ein Rugbyteam beim 7er-Rugby?",a:7,unit:"Spieler",hint:"Weniger Spieler, mehr Raum.",emoji:"🏉"},
  {id:"ksport_107",q:"Wie hoch ist ein Sprungbrett beim Wasserspringen (Kunstspringen)?",a:3,unit:"Meter",hint:"Auch 1m-Brett und 10m-Turm.",emoji:"🏊"},
  {id:"ksport_108",q:"Wie viele Spiele hat ein NBA-Grunddurchgang?",a:82,unit:"Spiele",hint:"Jede Mannschaft spielt 82 Spiele.",emoji:"🏀"},
  {id:"ksport_109",q:"Wie lang ist eine Rhythmische Sportgymnastik-Seiltour in Minuten?",a:1.5,unit:"Minuten",hint:"75-90 Sekunden Pflichtprogramm.",emoji:"🤸"},
  {id:"ksport_110",q:"Wie viele km legt ein Radfahrer bei der Tour de France täglich zurück?",a:175,unit:"km",hint:"Durchschnitt über alle Etappen.",emoji:"🚴"},
  {id:"ksport_111",q:"Wie hoch ist der Weltrekord im Stabhochsprung in Metern?",a:6.23,unit:"Meter",hint:"Armand Duplantis 2024.",emoji:"🏃"},
  {id:"ksport_112",q:"Wie viele km/h erreicht ein Profi-Tennisspieler beim Aufschlag?",a:230,unit:"km/h",hint:"Durchschnitt der Spitzenserveurs.",emoji:"🎾"},
  {id:"ksport_113",q:"Wie viele Spieler hat ein Cricketteam beim Twenty20?",a:11,unit:"Spieler",hint:"Gleich wie normales Cricket.",emoji:"🏏"},
  {id:"ksport_114",q:"Wie lang dauert eine Judo-Partie maximal in Minuten?",a:5,unit:"Minuten",hint:"Bei Gleichstand: Golden Score.",emoji:"🥋"},
  {id:"ksport_115",q:"Wie viele km/h fährt ein Eisschnellläufer auf 500m?",a:60,unit:"km/h",hint:"Sprintdisziplin auf Eis.",emoji:"⛸️"},
  {id:"ksport_116",q:"Wie viele Darts wirft man pro Aufnahme?",a:3,unit:"Darts",hint:"Drei Pfeile pro Zug.",emoji:"🎯"},
  {id:"ksport_117",q:"Wie lang ist eine Leichtathletik-Wurfbahn beim Speerwurf in Metern?",a:4,unit:"Meter Breite",hint:"Schmale Bahn für den Anlauf.",emoji:"🎯"},
  {id:"ksport_118",q:"Wie viele Minuten dauert eine Basketball-Halbzeit?",a:10,unit:"Minuten",hint:"4 Viertel à 10 Minuten (FIBA).",emoji:"🏀"},
  {id:"ksport_119",q:"Wie schwer ist ein Fußball (offiziell) in Gramm?",a:430,unit:"Gramm",hint:"410-450 Gramm laut FIFA.",emoji:"⚽"},
  {id:"ksport_120",q:"Wie lang ist die kürzeste olympische Laufdisziplin in Metern?",a:100,unit:"Meter",hint:"Der Sprint über 100m.",emoji:"🏃"},
  {id:"ksport_121",q:"Wie hoch ist das Netz beim Badminton in Metern?",a:1.55,unit:"Meter",hint:"In der Mitte 1,524m.",emoji:"🏸"},
  {id:"ksport_122",q:"Wie viele km/h schießt ein Fußball beim härtesten Schuss?",a:210,unit:"km/h",hint:"Von Profis bei Schussrekorden.",emoji:"⚽"},
  {id:"ksport_123",q:"Wie lang ist ein Handball-Spielfeld in Metern?",a:40,unit:"Meter",hint:"× 20 Meter.",emoji:"🤾"},
  {id:"ksport_124",q:"Wie viele Spieler hat ein Tug-of-War-Team?",a:8,unit:"Spieler",hint:"Tauziehen – olympische Disziplin bis 1920.",emoji:"🏋️"},
  {id:"ksport_125",q:"Wie lang ist ein Bobbahn in Metern?",a:1500,unit:"Meter",hint:"Mit vielen Kurven.",emoji:"🛷"},
  {id:"ksport_126",q:"Wie viele km/h erreicht ein Luger beim Rodeln?",a:140,unit:"km/h",hint:"Auf dem Rücken liegend.",emoji:"🛷"},
  {id:"ksport_127",q:"Wie viele Spieler hat ein Ringball-Team?",a:7,unit:"Spieler",hint:"Südafrikanische Sportart.",emoji:"🏀"},
  {id:"ksport_128",q:"Wie hoch ist ein Turnreck bei Frauen in Metern?",a:2.5,unit:"Meter",hint:"Hochreck für die Uneven Bars.",emoji:"🤸"},
  {id:"ksport_129",q:"Wie viele km lang ist eine Biathlon-Staffel?",a:4,unit:"km pro Läufer",hint:"Läufer × 7.5km = 30km gesamt.",emoji:"🎿"},
  {id:"ksport_130",q:"Wie viele Punkte hat ein Snowboard-Halfpipe-Run maximal?",a:100,unit:"Punkte",hint:"Jurybewertung von 0-100.",emoji:"🏂"},
  {id:"ksport_131",q:"Wie lang ist ein Schwimm-Wettkampf beim Freistil maximal in Metern?",a:1500,unit:"Meter",hint:"1500m Freistil ist die längste Beckendisziplin.",emoji:"🏊"},
  {id:"ksport_132",q:"Wie viele km/h schleudert ein Hammerwerfer den Hammer?",a:100,unit:"km/h",hint:"Der Hammer erreicht massive Geschwindigkeit.",emoji:"🔨"},
  {id:"ksport_133",q:"Wie lang ist die Wettkampfstrecke beim Eisschnelllauf (kürzeste) in Metern?",a:500,unit:"Meter",hint:"Die Sprintdisziplin.",emoji:"⛸️"},
  {id:"ksport_134",q:"Wie viele Minuten dauert ein normales Fußballspiel?",a:90,unit:"Minuten",hint:"2 Halbzeiten à 45 Minuten.",emoji:"⚽"},
  {id:"ksport_135",q:"Wie viele Spieler hat ein Ultimate Frisbee-Team?",a:7,unit:"Spieler",hint:"Vs 7 auf dem Feld.",emoji:"🥏"},
  {id:"ksport_136",q:"Wie hoch ist ein Wassersprung-Turm maximal in Metern?",a:10,unit:"Meter",hint:"Die höchste olympische Sprunghöhe.",emoji:"🏊"},
  {id:"ksport_137",q:"Wie viele Kämpfe hat ein MMA-Profi pro Jahr?",a:3,unit:"Kämpfe",hint:"Etwa 2-4 Kämpfe pro Jahr.",emoji:"🥊"},
  {id:"ksport_138",q:"Wie lang ist eine Skisprungrampe (Normalschanze) in Metern?",a:90,unit:"Meter Sprungweite",hint:"Normalschanze = K90.",emoji:"🎿"},
  {id:"ksport_139",q:"Wie viele Spieler hat ein Lacrosse Box-Team?",a:6,unit:"Spieler",hint:"Indoor-Lacrosse mit weniger Spielern.",emoji:"🥍"},
  {id:"ksport_140",q:"Wie lang ist ein 110m-Hürdenlauf-Hurde in cm Höhe?",a:106.7,unit:"cm",hint:"Für Männer.",emoji:"🏃"},
  {id:"ksport_141",q:"Wie viele km/h fährt ein Rennradsportler beim Zeitfahren?",a:55,unit:"km/h",hint:"Tour-de-France Zeitfahrspezialisten.",emoji:"🚴"},
  {id:"ksport_142",q:"Wie schwer ist ein Diskus bei Männern in kg?",a:2,unit:"kg",hint:"Bei Frauen 1 kg.",emoji:"🥏"},
  {id:"ksport_143",q:"Wie lang ist ein Basketballfeld in Metern?",a:28,unit:"Meter",hint:"× 15 Meter FIBA-Standard.",emoji:"🏀"},
  {id:"ksport_144",q:"Wie viele Punkte braucht man beim Squash für einen Satz?",a:11,unit:"Punkte",hint:"Neuere PAR-Regel.",emoji:"🎾"},
  {id:"ksport_145",q:"Wie hoch ist ein Netz beim Tischtennis in cm?",a:15.25,unit:"cm",hint:"Sehr niedrig.",emoji:"🏓"},
  {id:"ksport_146",q:"Wie lang ist ein Leichtathletik-Weitsprung-Anlauf in Metern?",a:40,unit:"Meter",hint:"Durchschnittlicher Anlauf der Elite.",emoji:"🏃"},
  {id:"ksport_147",q:"Wie viele Spieler hat ein Floorball-Team?",a:6,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"🏑"},
  {id:"ksport_148",q:"Wie lang ist eine Curling-Bahn in Metern?",a:45,unit:"Meter",hint:"Von Haus zu Haus.",emoji:"🥌"},
  {id:"ksport_149",q:"Wie viele km/h erreicht ein Bobteam im Eiskanal?",a:150,unit:"km/h",hint:"Viererbob auf schnellen Strecken.",emoji:"🛷"},
  {id:"ksport_150",q:"Wie viele Spieler hat ein Polo-Team?",a:4,unit:"Spieler",hint:"Reiter auf Pferden.",emoji:"🐎"},
  {id:"ksport_151",q:"Wie lang ist eine Rugby-Partie in Minuten?",a:80,unit:"Minuten",hint:"2 Halbzeiten à 40 Minuten.",emoji:"🏉"},
  {id:"ksport_152",q:"Wie viele Spieler hat ein Sepak Takraw-Team?",a:3,unit:"Spieler",hint:"Südostasiatischer Ballsport.",emoji:"🦵"},
  {id:"ksport_153",q:"Wie lang ist eine Biathlon-Strafschleife in Metern?",a:150,unit:"Meter",hint:"Für jeden verfehlten Schuss.",emoji:"🎿"},
  {id:"ksport_154",q:"Wie hoch ist der Weitsprung-Weltrekord bei Frauen in Metern?",a:7.52,unit:"Meter",hint:"Galina Chistyakova, 1988.",emoji:"🏃"},
  {id:"ksport_155",q:"Wie viele Spieler hat ein Hockeyteam auf dem Feld?",a:11,unit:"Spieler",hint:"Feldhockey-Standard.",emoji:"🏑"},
  {id:"ksport_156",q:"Wie lang ist eine Radrenn-Mannschaftsverfolgung?",a:4,unit:"km",hint:"Km auf der Bahn.",emoji:"🚴"},
  {id:"ksport_157",q:"Wie schwer ist ein Schläger beim Eishockey in kg?",a:0.85,unit:"kg",hint:"Leicht für maximale Kontrolle.",emoji:"🏒"},
  {id:"ksport_158",q:"Wie viele Spieler hat ein Gaelic-Football-Team?",a:15,unit:"Spieler",hint:"Irischer Sport ähnlich wie Rugby.",emoji:"🏈"},
  {id:"ksport_159",q:"Wie viele km lang ist ein Triathlon Ironman?",a:226,unit:"km",hint:"3,8km Schwimmen + 180km Rad + 42km Laufen.",emoji:"🏊"},
  {id:"ksport_160",q:"Wie hoch ist ein Schach-Turm auf dem Brett in cm?",a:6,unit:"cm",hint:"Größte Figur nach dem König.",emoji:"♟️"},
  {id:"ksport_161",q:"Wie viele Spieler hat ein Handball-Team?",a:7,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"🤾"},
  {id:"ksport_162",q:"Wie lang ist ein Olympisches Gewichtheben-Wettkampftag?",a:10,unit:"Stunden",hint:"Alle Gewichtsklassen zusammen.",emoji:"🏋️"},
  {id:"ksport_163",q:"Wie viele km/h fährt ein Downhill-Mountainbiker?",a:80,unit:"km/h",hint:"Auf extremen Strecken.",emoji:"🚵"}
,
  {id:"ksport_164",q:"Wie viele Spieler hat ein Handball-Team auf dem Feld?",a:7,unit:"Spieler",hint:"6 Feldspieler plus Torwart.",emoji:"🤾"},
  {id:"ksport_165",q:"Wie lang ist eine Olympia-Laufstrecke beim 400m-Lauf?",a:400,unit:"Meter",hint:"Eine Runde um die Bahn.",emoji:"🏃"},
  {id:"ksport_166",q:"Wie hoch ist das Netz beim Badminton?",a:1.55,unit:"Meter",hint:"Etwas höher als beim Tennis.",emoji:"🏸"},
  {id:"ksport_167",q:"Wie viele Punkte braucht man beim Dart um von 501 runterzuspielen?",a:501,unit:"Punkte",hint:"Genau auf Null – nicht drunter.",emoji:"🎯"},
  {id:"ksport_168",q:"Wie lang ist ein Curling-Feld in Metern?",a:42,unit:"Meter",hint:"Das Eis-Schach.",emoji:"🥌"},
  {id:"ksport_169",q:"Wie hoch ist ein Boxring in cm über dem Boden?",a:100,unit:"cm",hint:"Ungefähr 1 Meter über dem Hallenboden.",emoji:"🥊"},
  {id:"ksport_170",q:"Wie viele Meter wird beim Hochsprung-Weltrekord gesprungen?",a:2.45,unit:"Meter",hint:"Javier Sotomayor 1993.",emoji:"🏃"},
  {id:"ksport_171",q:"Wie viele km fährt ein Tour-de-France-Sieger im Durchschnitt?",a:3500,unit:"km",hint:"Über 21 Etappen.",emoji:"🚴"},
  {id:"ksport_172",q:"Wie lange dauert ein Eishockey-Spiel in Minuten?",a:60,unit:"Minuten",hint:"3 Drittel à 20 Minuten.",emoji:"🏒"},
  {id:"ksport_173",q:"Wie viele Punkte ist ein Dreier beim Basketball wert?",a:3,unit:"Punkte",hint:"Hinter der Dreierlinie geworfen.",emoji:"🏀"},
  {id:"ksport_174",q:"Wie lang ist eine Olympia-Schwimmstrecke?",a:50,unit:"Meter",hint:"Meter Langbahn.",emoji:"🏊"},
  {id:"ksport_175",q:"Wie viele Würfe hat man beim Bowling pro Frame?",a:2,unit:"Würfe",hint:"Beim Strike nur 1 – beim 10. Frame bis zu 3.",emoji:"🎳"},
  {id:"ksport_176",q:"Wie viele Meter tief ist ein Olympia-Schwimmbecken?",a:2,unit:"Meter",hint:"Mindesttiefe für internationale Wettkämpfe.",emoji:"🏊"},
  {id:"ksport_177",q:"Wie lange dauert ein Rugbyspiel in Minuten?",a:80,unit:"Minuten",hint:"2 Hälften à 40 Minuten.",emoji:"🏉"},
  {id:"ksport_178",q:"Wie viele Spieler stehen beim Volleyball auf dem Feld?",a:6,unit:"Spieler",hint:"Pro Seite.",emoji:"🏐"},
  {id:"ksport_179",q:"Wie schwer ist ein Diskus bei den Männern?",a:2,unit:"kg",hint:"Kg schwere Scheibe.",emoji:"🥏"},
  {id:"ksport_180",q:"Wie viele Runden hat ein Formel-1-Rennen in Monaco?",a:78,unit:"Runden",hint:"Kürzeste Strecke – daher mehr Runden.",emoji:"🏎️"},
  {id:"ksport_181",q:"Wie hoch ist ein Turnpferd?",a:1.15,unit:"Meter",hint:"Olympisches Turngerät.",emoji:"🤸"},
  {id:"ksport_182",q:"Wie viele Goldmedaillen gewann Usain Bolt insgesamt?",a:8,unit:"Goldmedaillen",hint:"3 Olympiaden – immer Gold über 100m und 200m.",emoji:"🥇"},
  {id:"ksport_183",q:"Wie viele Meter beträgt die Speerwurf-Weltrekorddistanz?",a:98.48,unit:"Meter",hint:"Jan Železný 1996 in Jena.",emoji:"🎯"},
  {id:"ksport_184",q:"Wie viele km/h erreicht ein Tennisball beim schärfsten Aufschlag?",a:263,unit:"km/h",hint:"Samuel Groth 2012.",emoji:"🎾"},
  {id:"ksport_185",q:"Wie lang ist ein Marathonlauf?",a:42.195,unit:"km",hint:"Benannt nach dem Lauf von Marathon nach Athen.",emoji:"🏃"},
  {id:"ksport_186",q:"Wie viele Spieler hat ein Eishockey-Team auf dem Eis?",a:6,unit:"Spieler",hint:"5 Feldspieler plus Torwart.",emoji:"🏒"},
  {id:"ksport_187",q:"Wie viele Punkte braucht man beim Tennis um ein Spiel zu gewinnen?",a:4,unit:"Punkte",hint:"15 – 30 – 40 – Spiel.",emoji:"🎾"},
  {id:"ksport_188",q:"Wie viele km/h fährt ein Downhill-Mountainbiker maximal?",a:130,unit:"km/h",hint:"Auf steilen Strecken.",emoji:"🚵"},
  {id:"ksport_189",q:"Wie viele Bahnen hat ein Olympia-Schwimmbecken?",a:8,unit:"Bahnen",hint:"Bahnen à 2,5 Meter Breite.",emoji:"🏊"},
  {id:"ksport_190",q:"Wie lang ist ein Fußballspiel in Minuten?",a:90,unit:"Minuten",hint:"2 Hälften à 45 Minuten.",emoji:"⚽"},
  {id:"ksport_191",q:"Wie hoch ist der Stabhochsprung-Weltrekord?",a:6.21,unit:"Meter",hint:"Armand Duplantis 2024.",emoji:"🏃"},
  {id:"ksport_192",q:"Wie viele Spieler hat ein Baseball-Team auf dem Feld?",a:9,unit:"Spieler",hint:"Positionen auf dem Feld.",emoji:"⚾"},
  {id:"ksport_193",q:"Wie weit wirft man beim Hammerwurf-Weltrekord?",a:86.74,unit:"Meter",hint:"Yuriy Sedykh 1986.",emoji:"🔨"},
  {id:"ksport_194",q:"Wie viele Runden besteht ein Boxkampf maximal (Profis)?",a:12,unit:"Runden",hint:"Jede Runde 3 Minuten.",emoji:"🥊"},
  {id:"ksport_195",q:"Wie lang ist ein Eisschnelllauf-Oval?",a:400,unit:"Meter",hint:"Standard-Eisschnelllaufbahn.",emoji:"⛸️"},
  {id:"ksport_196",q:"Wie viele km/h läuft ein Profifußballer maximal?",a:35,unit:"km/h",hint:"Beim Sprint.",emoji:"⚽"},
  {id:"ksport_197",q:"Wie hoch ist das Netz beim Tischtennis in cm?",a:15.25,unit:"cm",hint:"International standardisiert – überall gleich hoch.",emoji:"🏓"},
  {id:"ksport_198",q:"Wie viele Meter hat der 110m-Hürdenlauf?",a:110,unit:"Meter",hint:"10 Hürden à 1,067m Höhe.",emoji:"🏃"},
  {id:"ksport_199",q:"Wie viele Punkte ist ein Elfmeter-Tor im Fußball wert?",a:1,unit:"Tor",hint:"Wie jedes andere Tor auch.",emoji:"⚽"},
  {id:"ksport_200",q:"Wie lang ist ein Turniertennis-Platz?",a:23.77,unit:"Meter",hint:"23,77m × 8,23m (Einzel).",emoji:"🎾"},
  {id:"ksport_201",q:"Wie schwer ist eine Kugel beim Kugelstoßen (Männer)?",a:7.26,unit:"kg",hint:"7,26 kg – fast ein kleiner Bowlingball.",emoji:"🎱"},
  {id:"ksport_202",q:"Wie viele Torwürfe macht ein Handballer pro Spiel?",a:8,unit:"Würfe",hint:"Im Durchschnitt.",emoji:"🤾"},
  {id:"ksport_203",q:"Wie viele km/h kann ein Profischwimmer in 50m erreichen?",a:8,unit:"km/h",hint:"Beim Sprint.",emoji:"🏊"},
  {id:"ksport_204",q:"Wie lang ist der 4x100m Staffellauf insgesamt?",a:400,unit:"Meter",hint:"4 Läufer je 100m.",emoji:"🏃"},
  {id:"ksport_205",q:"Wie viele Spieler darf man beim Fußball einwechseln?",a:5,unit:"Spieler",hint:"Seit 2020 – vorher nur 3.",emoji:"⚽"},
  {id:"ksport_206",q:"Wie hoch ist ein Basketballkorb?",a:3.05,unit:"Meter",hint:"Weltweit einheitlich – egal ob Profi oder Amateur.",emoji:"🏀"},
  {id:"ksport_207",q:"Wie viele km fährt ein Triathlon beim langen Radabschnitt?",a:180,unit:"km",hint:"Beim Ironman: 3,8km Schwimmen – 180km Rad – 42km Laufen.",emoji:"🚴"},
  {id:"ksport_208",q:"Wie lang ist eine Eiskunstlauf-Kür bei den Damen?",a:4,unit:"Minuten",hint:"Minuten maximale Kürzeit.",emoji:"⛸️"},
  {id:"ksport_209",q:"Wie viele Punkte braucht man beim Badminton für einen Satz?",a:21,unit:"Punkte",hint:"Best of 3 Sätze.",emoji:"🏸"},
  {id:"ksport_210",q:"Wie viele km legt ein Tennisspieler pro Match zurück?",a:3,unit:"km",hint:"Je nach Spiellänge.",emoji:"🎾"},
  {id:"ksport_211",q:"Wie weit springt man beim Dreisprung-Weltrekord?",a:18.29,unit:"Meter",hint:"Jonathan Edwards 1995.",emoji:"🏃"},
  {id:"ksport_212",q:"Wie viele Tore schoss Lionel Messi bei seiner Rekord-WM?",a:7,unit:"Tore",hint:"WM 2022 in Katar.",emoji:"⚽"},
  {id:"ksport_213",q:"Wie lang ist eine Kanuslalom-Strecke?",a:300,unit:"Meter",hint:"Mit Toren die durchfahren werden müssen.",emoji:"🛶"},
  {id:"ksport_214",q:"Wie schwer ist ein Boxhandschuh beim Profiboxen in Unzen?",a:10,unit:"Unzen",hint:"Profis haben schwerere Handschuhe als im Training.",emoji:"🥊"},
  {id:"ksport_215",q:"Wie viele km schwimmt man beim Ironman-Triathlon?",a:3.8,unit:"km",hint:"Start des längsten Triathlons.",emoji:"🏊"},
  {id:"ksport_216",q:"Wie lang ist eine Eisschnelllauf-500m-Strecke?",a:500,unit:"Meter",hint:"Schnellste Disziplin.",emoji:"⛸️"},
  {id:"ksport_217",q:"Wie viele Punkte braucht man im Squash für ein Spiel?",a:11,unit:"Punkte",hint:"Best of 5 Spiele.",emoji:"🎾"},
  {id:"ksport_218",q:"Wie hoch ist ein Turnreck über dem Boden?",a:2.75,unit:"Meter",hint:"Olympisches Gerät.",emoji:"🤸"},
  {id:"ksport_219",q:"Wie viele km legt ein Radprofi bei der Tour de France täglich zurück?",a:167,unit:"km",hint:"Durchschnitt über alle Etappen.",emoji:"🚴"},
  {id:"ksport_220",q:"Wie viele Spieler hat ein Rugby-League-Team?",a:13,unit:"Spieler",hint:"Rugby Union hat 15.",emoji:"🏉"},
  {id:"ksport_221",q:"Wie schwer ist ein Diskus bei den Frauen?",a:1,unit:"kg",hint:"Halb so schwer wie bei den Männern.",emoji:"🥏"},
  {id:"ksport_222",q:"Wie lang ist ein Wettkampf-Ruderboot (Achter)?",a:20,unit:"Meter",hint:"8 Ruderer plus Steuermann.",emoji:"🚣"},
  {id:"ksport_223",q:"Wie viele Meter taucht ein Freitaucher beim Weltrekord?",a:214,unit:"Meter",hint:"Herbert Nitsch – tiefster Mann der Welt (Stand ~2024).",emoji:"🤿"},
  {id:"ksport_224",q:"Wie viele km/h fährt ein Profi-Radrennfahrer in der Spitze?",a:80,unit:"km/h",hint:"Im Sprint – bergab noch mehr.",emoji:"🚴"},
  {id:"ksport_225",q:"Wie lang ist ein Tischtennis-Tisch?",a:2.74,unit:"Meter",hint:"274cm × 152,5cm.",emoji:"🏓"},
  {id:"ksport_226",q:"Wie viele Runden besteht ein Amateur-Boxkampf?",a:3,unit:"Runden",hint:"Olympisches Boxen: 3 Runden à 3 Minuten.",emoji:"🥊"},
  {id:"ksport_227",q:"Wie weit schießt man beim Bogenschießen auf der Olympia-Distanz?",a:70,unit:"Meter",hint:"Meter bei Olympia.",emoji:"🏹"},
  {id:"ksport_228",q:"Wie hoch springt ein Ski-Springer beim Normalschanzenrekord?",a:100,unit:"Meter",hint:"Auf der Normalschanze (Stand ~2024).",emoji:"⛷️"},
  {id:"ksport_229",q:"Wie lang ist ein Biathlon-Lauf bei den Herren?",a:20,unit:"km",hint:"Kombiniert Skilanglauf und Schießen.",emoji:"🎿"},
  {id:"ksport_230",q:"Wie viele Punkte braucht man beim Volleyball für einen Satz?",a:25,unit:"Punkte",hint:"Mit 2 Punkten Vorsprung gewinnen.",emoji:"🏐"},
  {id:"ksport_231",q:"Wie viele km laufen Fußballer bei einem Bundesligaspiel?",a:11,unit:"km",hint:"Durchschnitt pro Spieler.",emoji:"⚽"},
  {id:"ksport_232",q:"Wie schwer ist ein Olympia-Gewichtheber-Barbell?",a:20,unit:"kg",hint:"Die Stange selbst wiegt 20kg.",emoji:"🏋️"},
  {id:"ksport_233",q:"Wie lang ist ein Handball-Spielfeld?",a:40,unit:"Meter",hint:"40m × 20m.",emoji:"🤾"},
  {id:"ksport_234",q:"Wie viele Runden hat ein Motorradrennen bei der MotoGP?",a:27,unit:"Runden",hint:"Je nach Strecke 20-30 Runden.",emoji:"🏍️"},
  {id:"ksport_235",q:"Wie lang ist eine Hürde beim 110m-Lauf in cm Höhe?",a:106,unit:"cm",hint:"Für Männer 106,7cm hoch.",emoji:"🏃"},
  {id:"ksport_236",q:"Wie viele Punkte ist ein Freiwurf beim Basketball wert?",a:1,unit:"Punkt",hint:"Vom Freiwurfstreifen.",emoji:"🏀"},
  {id:"ksport_237",q:"Wie viele Minuten dauert eine Halbzeit beim Fußball?",a:45,unit:"Minuten",hint:"Zwei Hälften à 45 Minuten.",emoji:"⚽"},
  {id:"ksport_238",q:"Wie viele Spieler hat ein Lacrosse-Team?",a:10,unit:"Spieler",hint:"Feldspieler.",emoji:"🥍"},
  {id:"ksport_239",q:"Wie hoch ist das Tor beim Fußball in Metern?",a:2.44,unit:"Meter",hint:"Höher als du denkst!",emoji:"⚽"}
];
