// 🎯 GRATIS-TEST – Kinder (immer kostenlos)
export default [
  {q:"Wie viele Beine hat eine Spinne?",a:8,unit:"Beine",hint:"Spinnen sind keine Insekten – Insekten haben nur 6 Beine!",emoji:"🕷️"},
  {q:"Wie hoch ist der Mount Everest in Metern?",a:8849,unit:"Meter",hint:"Er ist der höchste Berg der Erde.",emoji:"🏔️"},
  {q:"Wie viele Farben hat ein Regenbogen?",a:7,unit:"Farben",hint:"Rot, Orange, Gelb, Grün, Blau, Indigo, Violett.",emoji:"🌈"},
  {q:"Wie viele Planeten gibt es in unserem Sonnensystem?",a:8,unit:"Planeten",hint:"Pluto zählt seit 2006 nicht mehr dazu.",emoji:"🪐"},
  {q:"Wie viele Zähne hat ein Erwachsener?",a:32,unit:"Zähne",hint:"Inklusive der Weisheitszähne.",emoji:"🦷"},
  {q:"Wie viele Stunden hat ein Tag?",a:24,unit:"Stunden",hint:"Die Erde dreht sich einmal in 24 Stunden um ihre Achse.",emoji:"⏰"},
  {q:"Wie viele Herzen hat ein Tintenfisch?",a:3,unit:"Herzen",hint:"Zwei pumpen Blut zu den Kiemen, eines zum Körper.",emoji:"🐙"},
  {q:"Wie schnell kann ein Gepard laufen in km/h?",a:112,unit:"km/h",hint:"Er ist das schnellste Landtier der Welt.",emoji:"🐆"},
  {q:"Wie viele km ist es von der Erde zum Mond?",a:384400,unit:"km",hint:"Die Apollo-Astronauten brauchten 3 Tage dorthin.",emoji:"🌙"},
  {q:"Wie viele Knochen hat ein Erwachsener?",a:206,unit:"Knochen",hint:"Babys haben noch 270 – viele wachsen zusammen.",emoji:"🦴"},
  {q:"Wie alt kann eine Schildkröte werden in Jahren?",a:150,unit:"Jahre",hint:"Manche Schildkröten werden über 200 Jahre alt!",emoji:"🐢"},
  {q:"Wie viele Kontinente gibt es auf der Erde?",a:7,unit:"Kontinente",hint:"Afrika, Amerika (2), Antarktika, Asien, Australien, Europa.",emoji:"🌍"},
  {q:"Wie groß war der größte Dinosaurier in Metern?",a:40,unit:"Meter",hint:"Der Argentinosaurus war der längste bekannte Dinosaurier.",emoji:"🦕"},
  {q:"Wie viele Augen hat eine Biene?",a:5,unit:"Augen",hint:"2 große Facettenaugen und 3 kleine Punktaugen oben.",emoji:"🐝"},
  {q:"Wie viele Minuten braucht Sonnenlicht bis zur Erde?",a:8,unit:"Minuten",hint:"Licht reist mit 300.000 km pro Sekunde.",emoji:"☀️"},
{q:"Wie viele Beine hat ein Insekt?",a:6,unit:"Beine",hint:"Insekten haben immer 6 Beine – Spinnen 8.",emoji:"🐛"},
  {q:"Wie viele Zähne hat ein Kleinkind (Milchzähne)?",a:20,unit:"Zähne",hint:"Erwachsene haben 32.",emoji:"🦷"},
  {q:"Wie viele Farben hat die deutsche Flagge?",a:3,unit:"Farben",hint:"Schwarz, Rot, Gold.",emoji:"🇩🇪"},
  {q:"Wie viele Tage hat ein Schaltjahr?",a:366,unit:"Tage",hint:"Alle 4 Jahre kommt ein 29. Februar dazu.",emoji:"📅"},
  {q:"Wie viele Finger hat ein Mensch?",a:10,unit:"Finger",hint:"5 an jeder Hand.",emoji:"✋"},
  {q:"Wie viele Jahreszeiten gibt es?",a:4,unit:"Jahreszeiten",hint:"Frühling, Sommer, Herbst, Winter.",emoji:"🌸"},
  {q:"Wie viele Seiten hat ein Würfel?",a:6,unit:"Seiten",hint:"Alle zusammen ergeben immer 21.",emoji:"🎲"},
  {q:"Wie viele Minuten hat eine Stunde?",a:60,unit:"Minuten",hint:"Minuten × 24 Stunden = 1440 Minuten pro Tag.",emoji:"⏰"},
  {q:"Wie viele Buchstaben hat das Alphabet?",a:26,unit:"Buchstaben",hint:"Von A bis Z.",emoji:"🔤"},
  {q:"Wie viele Sinne hat ein Mensch?",a:5,unit:"Sinne",hint:"Sehen, Hören, Riechen, Schmecken, Tasten.",emoji:"👁️"},
  {q:"Wie viele Monate hat ein Jahr?",a:12,unit:"Monate",hint:"Von Januar bis Dezember.",emoji:"📅"},
  {q:"Wie viele Wochen hat ein Jahr?",a:52,unit:"Wochen",hint:"Wochen und 1 Tag.",emoji:"📅"},
  {q:"Wie viele cm hat ein Meter?",a:100,unit:"cm",hint:"10 cm = 1 dm, 10 dm = 1 m.",emoji:"📏"},
  {q:"Wie viele Seiten hat ein Dreieck?",a:3,unit:"Seiten",hint:"Tri = drei.",emoji:"🔺"},
  {q:"Wie viele Meter hat ein Kilometer?",a:1000,unit:"Meter",hint:"Kilo bedeutet tausend.",emoji:"📏"},
  {q:"Wie viele Grad hat ein Kreis?",a:360,unit:"Grad",hint:"Alte babylonische Konvention.",emoji:"⭕"},
  {q:"Wie viele Continente hat die Erde?",a:7,unit:"Kontinente",hint:"Afrika, Amerika (2), Antarktika, Asien, Australien, Europa.",emoji:"🌍"},
  {q:"Wie viele Tage hat der Februar in einem normalen Jahr?",a:28,unit:"Tage",hint:"Außer im Schaltjahr – dann 29.",emoji:"📅"},
  {q:"Wie viele Zähne hat ein Erwachsener ohne Weisheitszähne?",a:28,unit:"Zähne",hint:"Mit Weisheitszähnen 32.",emoji:"🦷"},
  {q:"Wie viele Sekunden hat eine Minute?",a:60,unit:"Sekunden",hint:"× 60 = 3600 Sekunden pro Stunde.",emoji:"⏱️"},
  {q:"Wie viele Seiten hat ein Quadrat?",a:4,unit:"Seiten",hint:"Alle gleich lang.",emoji:"🟦"},
  {q:"Wie viele kg hat eine Tonne?",a:1000,unit:"kg",hint:"Kg = 1 Tonne.",emoji:"⚖️"},
  {q:"Wie viele Spieler hat eine Fußballmannschaft?",a:11,unit:"Spieler",hint:"Inklusive Torwart.",emoji:"⚽"},
  {q:"Wie viele Beine hat ein Oktopus?",a:8,unit:"Arme",hint:"Oktopus = 8 Arme.",emoji:"🐙"},
  {q:"Wie viele Kontinente berührt der Äquator?",a:3,unit:"Kontinente",hint:"Afrika, Südamerika, Asien.",emoji:"🌍"},
  {q:"Wie viele Noten hat eine Oktave?",a:8,unit:"Noten",hint:"C, D, E, F, G, A, H, C.",emoji:"🎵"},
  {q:"Wie viele Stunden hat eine Woche?",a:168,unit:"Stunden",hint:"7 Tage × 24 Stunden.",emoji:"⏰"},
  {q:"Wie viele Gramm hat ein Kilogramm?",a:1000,unit:"Gramm",hint:"1 kg = 1000 g.",emoji:"⚖️"},
  {q:"Wie viele Millimeter hat ein Zentimeter?",a:10,unit:"mm",hint:"Mm = 1 cm.",emoji:"📏"},
  {q:"Wie viele Sekunden hat eine Stunde?",a:3600,unit:"Sekunden",hint:"60 × 60 = 3600.",emoji:"⏱️"},
  {q:"Wie viele Spieler spielen gegeneinander beim Tennis (Einzel)?",a:2,unit:"Spieler",hint:"1 gegen 1.",emoji:"🎾"},
  {q:"Wie viele Grundfarben gibt es beim Malen?",a:3,unit:"Farben",hint:"Rot, Gelb, Blau.",emoji:"🎨"},
  {q:"Wie viele Tage hat ein Jahr?",a:365,unit:"Tage",hint:"Außer im Schaltjahr – dann 366.",emoji:"📅"},
  {q:"Wie viele Planeten sind kleiner als die Erde im Sonnensystem?",a:2,unit:"Planeten",hint:"Merkur und Mars.",emoji:"🪐"},
  {q:"Wie viele Meter tief ist ein olympisches Schwimmbecken?",a:2,unit:"Meter",hint:"Mindesttiefe 2 Meter.",emoji:"🏊"},
  {q:"Wie viele Ohren hat ein Mensch?",a:2,unit:"Ohren",hint:"Links und rechts.",emoji:"👂"},
  {q:"Wie viele Farben hat ein Regenbogen?",a:7,unit:"Farben",hint:"ROYGBIV – Rot, Orange, Gelb, Grün, Blau, Indigo, Violett.",emoji:"🌈"},
  {q:"Wie viele Bundesländer hat Deutschland?",a:16,unit:"Bundesländer",hint:"3 Stadtstaaten und 13 Flächenländer.",emoji:"🇩🇪"},
  {q:"Wie viele Ecken hat ein Sechseck?",a:6,unit:"Ecken",hint:"Wie eine Bienenwabe.",emoji:"⬡"},
  {q:"Wie viele Zehen hat ein Mensch?",a:10,unit:"Zehen",hint:"5 an jedem Fuß.",emoji:"🦶"},
  {q:"Wie viele Seiten hat ein Pentagon?",a:5,unit:"Seiten",hint:"Penta = fünf.",emoji:"⭐"},
  {q:"Wie viele Stunden hat ein halber Tag?",a:12,unit:"Stunden",hint:"Die Hälfte von 24.",emoji:"⏰"},
  {q:"Wie viele Milimeter hat ein Meter?",a:1000,unit:"mm",hint:"10 × 10 × 10 = 1000.",emoji:"📏"},
  {q:"Wie viele Knochen hat ein Erwachsener?",a:206,unit:"Knochen",hint:"Babys haben noch 270.",emoji:"🦴"},
  {q:"Wie viele Buchstaben hat das Wort ELEFANT?",a:7,unit:"Buchstaben",hint:"E-L-E-F-A-N-T.",emoji:"🐘"},
  {q:"Wie viele Tage hat der Monat September?",a:30,unit:"Tage",hint:"April, Juni, September, November haben 30 Tage.",emoji:"📅"},
  {q:"Wie viele Seiten hat ein Oktagon?",a:8,unit:"Seiten",hint:"Octo = acht – wie ein Stop-Schild.",emoji:"🔴"},
  {q:"Wie viele Flügel hat ein Schmetterling?",a:4,unit:"Flügel",hint:"2 Vorder- und 2 Hinterflügel.",emoji:"🦋"},
  {q:"Wie viele Saiten hat eine Geige?",a:4,unit:"Saiten",hint:"G, D, A, E.",emoji:"🎻"},
  {q:"Wie viele Punkte hat ein Würfel auf allen Seiten zusammen?",a:21,unit:"Punkte",hint:"1+2+3+4+5+6 = 21.",emoji:"🎲"},
  {q:"Wie viele Knöchel hat ein Mensch pro Hand?",a:3,unit:"Knöchel",hint:"Jeder Finger hat 3 Gelenke.",emoji:"✋"},
  {q:"Wie viele Milliliter hat ein Liter?",a:1000,unit:"ml",hint:"1 Liter = 1000 ml.",emoji:"💧"},
  {q:"Wie viele Sekunden hat ein Tag?",a:86400,unit:"Sekunden",hint:"24 × 60 × 60 = 86.400.",emoji:"⏱️"},
  {q:"Wie viele Kegelseiten hat ein Kegel?",a:1,unit:"Seitenfläche",hint:"Eine gebogene Fläche plus Kreis-Boden.",emoji:"🍦"},
  {q:"Wie viele Tier-Beine haben Katze und Hund zusammen?",a:8,unit:"Beine",hint:"4 + 4 = 8.",emoji:"🐱"},
  {q:"Wie viele Stunden schläft ein Baby täglich?",a:16,unit:"Stunden",hint:"Neugeborene schlafen sehr viel.",emoji:"👶"},
  {q:"Wie viele Tage hat eine Woche?",a:7,unit:"Tage",hint:"Von Montag bis Sonntag.",emoji:"📅"},
  {q:"Wie viele km/h fährt ein Fahrrad durchschnittlich?",a:15,unit:"km/h",hint:"Freizeitradler fahren 12-20 km/h.",emoji:"🚴"},
  {q:"Wie viele Linsen hat eine Kamera?",a:1,unit:"Linse",hint:"Manche Kameras haben mehrere – die meisten eine.",emoji:"📷"},
  {q:"Wie viele Seiten hat ein Oktaeder?",a:8,unit:"Seiten",hint:"Dreiecke.",emoji:"🔷"},
  {q:"Wie viele Liter Wasser trinkt ein Mensch täglich?",a:2,unit:"Liter",hint:"Empfohlen werden 1,5-2 Liter.",emoji:"💧"},
  {q:"Wie viele Farben hat die österreichische Flagge?",a:2,unit:"Farben",hint:"Rot und Weiß.",emoji:"🇦🇹"},
  {q:"Wie viele Ecken hat ein Achteck?",a:8,unit:"Ecken",hint:"Octo = 8.",emoji:"🔴"},
  {q:"Wie viele Ohren hat ein Kaninchen?",a:2,unit:"Ohren",hint:"Sehr lange Ohren.",emoji:"🐇"},
  {q:"Wie viele Beine hat ein Stuhl meistens?",a:4,unit:"Beine",hint:"Manchmal auch 3 oder 5.",emoji:"🪑"},
  {q:"Wie viele Knöpfe hat ein normaler Taschenrechner?",a:36,unit:"Tasten",hint:"Je nach Modell.",emoji:"🔢"},
  {q:"Wie viele Farben hat die Schweizer Flagge?",a:2,unit:"Farben",hint:"Rot und Weiß.",emoji:"🇨🇭"},
  {q:"Wie viele Minuten hat ein halber Tag?",a:720,unit:"Minuten",hint:"12 × 60 = 720.",emoji:"⏰"},
  {q:"Wie viele Seiten hat ein Dodekaeder?",a:12,unit:"Seiten",hint:"Dodeka = 12.",emoji:"🔷"},
  {q:"Wie viele Tage hat der Oktober?",a:31,unit:"Tage",hint:"Januar, März, Mai, Juli, August, Oktober, Dezember: 31 Tage.",emoji:"📅"},
  {q:"Wie viele Kerzen hat ein Geburtstagskuchen für ein 10-jähriges Kind?",a:10,unit:"Kerzen",hint:"Eine Kerze pro Lebensjahr.",emoji:"🎂"},
  {q:"Wie viele Planeten sind größer als die Erde im Sonnensystem?",a:4,unit:"Planeten",hint:"Jupiter, Saturn, Uranus, Neptun.",emoji:"🪐"},
  {q:"Wie viele Noten gibt es in einem Dur-Dreiklang?",a:3,unit:"Noten",hint:"Grundton, Terz, Quinte.",emoji:"🎵"},
  {q:"Wie viele Räder hat ein Dreirad?",a:3,unit:"Räder",hint:"Drei = Tri.",emoji:"🚲"},
  {q:"Wie viele Flossen hat ein typischer Fisch?",a:7,unit:"Flossen",hint:"Rücken-, Bauch-, Brust-, After- und Schwanzflosse.",emoji:"🐟"},
  {q:"Wie viele Beine hat ein Hund?",a:4,unit:"Beine",hint:"Vierbeiner.",emoji:"🐕"},
  {q:"Wie viele Schüsse hat ein Elfmeter?",a:1,unit:"Schuss",hint:"Ein Versuch – bei Wiederholung wieder einer.",emoji:"⚽"},
  {q:"Wie viele Hörner hat ein Einhorn?",a:1,unit:"Horn",hint:"Ein Horn – daher Einhorn.",emoji:"🦄"},
  {q:"Wie viele Zacken hat eine Schneeflocke?",a:6,unit:"Zacken",hint:"Alle Schneeflocken haben 6-fache Symmetrie.",emoji:"❄️"},
  {q:"Wie viele Reifen hat ein Auto?",a:4,unit:"Reifen",hint:"Plus ein Ersatzreifen.",emoji:"🚗"},
  {q:"Wie viele Zähne verliert ein Kind?",a:20,unit:"Milchzähne",hint:"Alle 20 Milchzähne fallen aus.",emoji:"🦷"},
  {q:"Wie viele Beine hat eine Ente?",a:2,unit:"Beine",hint:"Alle Vögel haben 2 Beine.",emoji:"🦆"},
  {q:"Wie viele Sterne sind auf der EU-Flagge?",a:12,unit:"Sterne",hint:"Immer 12 – egal wie viele Mitglieder.",emoji:"🇪🇺"},
  {q:"Wie viele Würfel braucht man für Mensch Ärger dich nicht?",a:1,unit:"Würfel",hint:"Nur ein Würfel wird geworfen.",emoji:"🎲"},
  {q:"Wie viele Spielkarten hat ein normales Kartendeck?",a:52,unit:"Karten",hint:"4 Farben × 13 Karten.",emoji:"🃏"},
  {q:"Wie viele Pfoten hat eine Katze?",a:4,unit:"Pfoten",hint:"Vorderläufe und Hinterläufe.",emoji:"🐱"},
  {q:"Wie viele Augen hat ein Cyclop?",a:1,unit:"Auge",hint:"Cyclops aus der griechischen Mythologie.",emoji:"👁️"},
  {q:"Wie viele Stunden hat ein Wochentag?",a:24,unit:"Stunden",hint:"Jeder Tag hat 24 Stunden.",emoji:"⏰"},
  {q:"Wie viele Seiten hat eine Pyramide mit quadratischer Basis?",a:5,unit:"Seiten",hint:"4 Dreiecke + 1 Quadrat unten.",emoji:"🔺"},
  {q:"Wie viele Schritte macht ein Mensch täglich?",a:8000,unit:"Schritte",hint:"Durchschnitt ca. 7.000-10.000.",emoji:"🚶"},
  {q:"Wie viele Tage hat der Monat April?",a:30,unit:"Tage",hint:"April, Juni, September, November: 30 Tage.",emoji:"📅"},
  {q:"Wie viele Liter fasst ein normaler Eimer?",a:10,unit:"Liter",hint:"Standard-Eimer fasst 10 Liter.",emoji:"🪣"},
  {q:"Wie viele Buchstaben hat das deutsche Wort SCHMETTERLING?",a:13,unit:"Buchstaben",hint:"S-C-H-M-E-T-T-E-R-L-I-N-G.",emoji:"🦋"}
,
  {q:"Wie viele Beine hat eine Libelle?",a:6,unit:"Beine",hint:"Alle Insekten haben genau 6 Beine.",emoji:"🪲"},
  {q:"Wie viele Zähne hat ein erwachsener Mensch?",a:32,unit:"Zähne",hint:"Inklusive der Weisheitszähne.",emoji:"🦷"},
  {q:"Wie tief ist der tiefste See der Welt (Baikalsee)?",a:1642,unit:"Meter",hint:"In Russland – so tief wie 5 Eiffeltürme.",emoji:"💧"},
  {q:"Wie viele Planeten gibt es in unserem Sonnensystem?",a:8,unit:"Planeten",hint:"Pluto zählt seit 2006 nicht mehr dazu.",emoji:"🪐"},
  {q:"Wie schwer ist ein neugeborenes Baby durchschnittlich in kg?",a:3.4,unit:"kg",hint:"Zwischen 2,5 und 4,5 kg ist normal.",emoji:"👶"},
  {q:"Wie viele Stunden hat eine Woche?",a:168,unit:"Stunden",hint:"7 Tage × 24 Stunden.",emoji:"📅"},
  {q:"Wie viele Seiten hat ein Würfel?",a:6,unit:"Seiten",hint:"1, 2, 3, 4, 5, 6.",emoji:"🎲"},
  {q:"Wie lang ist ein Schuljahr in Deutschland in Wochen?",a:40,unit:"Wochen",hint:"Mit ca. 12 Wochen Ferien.",emoji:"🏫"},
  {q:"Wie viele Minuten hat ein halber Tag?",a:720,unit:"Minuten",hint:"12 Stunden × 60 Minuten.",emoji:"⏰"},
  {q:"Wie viele Knochen hat ein Neugeborenes?",a:270,unit:"Knochen",hint:"Mehr als Erwachsene – viele wachsen zusammen.",emoji:"🦴"},
  {q:"Wie viele Rippen hat ein Mensch?",a:24,unit:"Rippen",hint:"12 Paare – linke und rechte Seite.",emoji:"🦴"},
  {q:"Wie viele Liter Blut hat ein Kind mit 10 Jahren?",a:3,unit:"Liter",hint:"Erwachsene haben etwa 5-6 Liter.",emoji:"🩸"},
  {q:"Wie viele km/h läuft der schnellste Mensch?",a:45,unit:"km/h",hint:"Usain Bolt erreichte 44,7 km/h.",emoji:"⚡"},
  {q:"Wie viele Länder gibt es in Europa?",a:44,unit:"Länder",hint:"Je nach Zählung 44-50 Länder.",emoji:"🗺️"},
  {q:"Wie viele Monate hat ein Jahr?",a:12,unit:"Monate",hint:"Januar bis Dezember.",emoji:"📅"},
  {q:"Wie viele Buchstaben hat das Alphabet?",a:26,unit:"Buchstaben",hint:"Ohne Umlaute.",emoji:"🔤"},
  {q:"Wie viele Ecken hat ein Dreieck?",a:3,unit:"Ecken",hint:"Tri = drei.",emoji:"🔺"},
  {q:"Wie viele Sekunden hat eine Minute?",a:60,unit:"Sekunden",hint:"Teilt sich perfekt durch viele Zahlen.",emoji:"⏱️"},
  {q:"Wie viele Tage hat ein Schaltjahr?",a:366,unit:"Tage",hint:"Der Februar hat einen Extra-Tag.",emoji:"📅"},
  {q:"Wie hoch fliegt ein Flugzeug normalerweise in Metern?",a:10000,unit:"Meter",hint:"Reiseflughöhe bei 9000-12000 Metern.",emoji:"✈️"},
  {q:"Wie viele Finger hat ein Mensch an beiden Händen?",a:10,unit:"Finger",hint:"5 pro Hand.",emoji:"🖐️"},
  {q:"Wie viele Zehen hat ein Mensch an beiden Füßen?",a:10,unit:"Zehen",hint:"5 pro Fuß.",emoji:"🦶"},
  {q:"Wie viele Kalorien hat ein Apfel ungefähr?",a:80,unit:"kcal",hint:"Ein mittelgroßer Apfel.",emoji:"🍎"},
  {q:"Wie viele Minuten dauert ein normaler Film?",a:100,unit:"Minuten",hint:"Die meisten Kinofilme sind 90-120 Minuten lang.",emoji:"🎬"},
  {q:"Wie viele Punkte hat ein Stern normalerweise?",a:5,unit:"Punkte",hint:"Der klassische Stern hat 5 Zacken.",emoji:"⭐"},
  {q:"Wie viele Augen hat ein Mensch?",a:2,unit:"Augen",hint:"Vorderseitig – für räumliches Sehen.",emoji:"👁️"},
  {q:"Wie viele Seiten hat ein Rechteck?",a:4,unit:"Seiten",hint:"Vier Seiten – je zwei gleich lang.",emoji:"▭"},
  {q:"Wie viele Wochen hat ein Jahr?",a:52,unit:"Wochen",hint:"Genauer: 52 Wochen und 1-2 Tage.",emoji:"📅"},
  {q:"Wie viele Kilogramm hat eine Tonne?",a:1000,unit:"kg",hint:"Kg = 1 Tonne.",emoji:"⚖️"},
  {q:"Wie viele Minuten dauert eine Schulstunde?",a:45,unit:"Minuten",hint:"Die Standard-Schulstunde in Deutschland.",emoji:"🏫"},
  {q:"Wie viele Beine hat ein Oktopus?",a:8,unit:"Arme",hint:"Oktopus bedeutet 'acht Füße' auf Griechisch.",emoji:"🐙"},
  {q:"Wie viele Gramm hat ein Kilogramm?",a:1000,unit:"Gramm",hint:"Kilo kommt vom griechischen 'chilioi' = tausend.",emoji:"⚖️"},
  {q:"Wie viele Meter sind ein Kilometer?",a:1000,unit:"Meter",hint:"Kilo = tausend.",emoji:"📏"},
  {q:"Wie viele Seiten hat ein Pentagon?",a:5,unit:"Seiten",hint:"Penta = fünf.",emoji:"⬠"},
  {q:"Wie viele Tage hat der Februar in einem normalen Jahr?",a:28,unit:"Tage",hint:"Im Schaltjahr 29.",emoji:"📅"},
  {q:"Wie viele Beine hat eine Krabbe?",a:10,unit:"Beine",hint:"Zehn Beine – dazu zwei Scheren.",emoji:"🦀"},
  {q:"Wie viele Stunden hat ein halbes Jahr?",a:4380,unit:"Stunden",hint:"182,5 Tage × 24 Stunden.",emoji:"⏰"},
  {q:"Wie viele Seiten hat ein Hexagon?",a:6,unit:"Seiten",hint:"Hexa = sechs – wie Bienenwaben.",emoji:"⬡"},
  {q:"Wie viele Zähne hat ein Milchgebiss?",a:20,unit:"Zähne",hint:"Kinder haben 20 Milchzähne.",emoji:"🦷"},
  {q:"Wie viele Knochen hat ein Erwachsener?",a:206,unit:"Knochen",hint:"Als Baby hatte man noch 270.",emoji:"🦴"},
  {q:"Wie viele Gramm hat eine Tafel Schokolade normalerweise?",a:100,unit:"Gramm",hint:"Eine Standard-Schokoladentafel.",emoji:"🍫"},
  {q:"Wie viele Stunden dauert ein Langstreckenflug nach New York?",a:9,unit:"Stunden",hint:"Von Frankfurt ungefähr 8-10 Stunden.",emoji:"✈️"},
  {q:"Wie viele Kontinente gibt es auf der Erde?",a:7,unit:"Kontinente",hint:"Afrika, Antarktika, Asien, Australien, Europa, Nordamerika, Südamerika.",emoji:"🌍"},
  {q:"Wie viele Schritte hat eine Treppe normalerweise pro Etage?",a:16,unit:"Stufen",hint:"Durchschnittlich 15-18 Stufen.",emoji:"🏢"},
  {q:"Wie viele Farben hat ein Regenbogen?",a:7,unit:"Farben",hint:"Rot, Orange, Gelb, Grün, Blau, Indigo, Violett.",emoji:"🌈"},
  {q:"Wie viele Liter Wasser soll man täglich trinken?",a:1.5,unit:"Liter",hint:"Empfehlung für Kinder: 1-1,5 Liter.",emoji:"💧"},
  {q:"Wie viele Stunden schläft ein Grundschulkind pro Nacht?",a:10,unit:"Stunden",hint:"9-11 Stunden sind empfohlen.",emoji:"😴"},
  {q:"Wie viele Grad hat ein Vollkreis?",a:360,unit:"Grad",hint:"Eine volle Umdrehung.",emoji:"⭕"},
  {q:"Wie viele cm hat ein Meter?",a:100,unit:"cm",hint:"Zentimeter = 1 Meter.",emoji:"📏"},
  {q:"Wie viele Seiten hat ein Oktagon?",a:8,unit:"Seiten",hint:"Okto = acht – wie ein Stoppschild.",emoji:"🛑"},
  {q:"Wie viele Monate hat ein Schuljahr?",a:10,unit:"Monate",hint:"September bis Juni mit Sommerferien.",emoji:"🏫"},
  {q:"Wie viele Beine hat eine Ameise?",a:6,unit:"Beine",hint:"Alle Insekten haben 6 Beine.",emoji:"🐜"},
  {q:"Wie viele Liter hat ein Wassereimer?",a:10,unit:"Liter",hint:"Ein Standard-Haushaltseimer fasst 10 Liter.",emoji:"🪣"},
  {q:"Wie viele Stockwerke hat ein typisches Einfamilienhaus?",a:2,unit:"Stockwerke",hint:"Erdgeschoss und ein Obergeschoss.",emoji:"🏠"},
  {q:"Wie viele Minuten hat ein Viertelstunde?",a:15,unit:"Minuten",hint:"Ein Viertel von 60 Minuten.",emoji:"⏰"},
  {q:"Wie viele Beine hat eine Spinne?",a:8,unit:"Beine",hint:"Spinnen sind keine Insekten.",emoji:"🕷️"},
  {q:"Wie viele Punkte hat ein Würfel insgesamt auf allen Seiten?",a:21,unit:"Punkte",hint:"1+2+3+4+5+6 = 21.",emoji:"🎲"},
  {q:"Wie viele cm sind ein Dezimeter?",a:10,unit:"cm",hint:"Dezi = zehn.",emoji:"📏"},
  {q:"Wie viele Seiten hat ein Dreieck?",a:3,unit:"Seiten",hint:"Tri = drei.",emoji:"🔺"},
  {q:"Wie viele Monate hat ein Vierteljahr?",a:3,unit:"Monate",hint:"Ein Viertel von 12 Monaten.",emoji:"📅"},
  {q:"Wie viele Liter fasst ein Badewanne?",a:150,unit:"Liter",hint:"Eine typische Badewanne fasst 120-180 Liter.",emoji:"🛁"},
  {q:"Wie viele Zähne hat ein ausgewachsener Hund?",a:42,unit:"Zähne",hint:"Mehr als der Mensch.",emoji:"🐕"},
  {q:"Wie viele Farben hat der Regenbogen zusammen?",a:7,unit:"Farben",hint:"Alle Spektralfarben zusammen.",emoji:"🌈"},
  {q:"Wie viele Wochentage gibt es?",a:7,unit:"Tage",hint:"Mo, Di, Mi, Do, Fr, Sa, So.",emoji:"📅"},
  {q:"Wie viele Buchstaben hat das Wort SCHULE?",a:6,unit:"Buchstaben",hint:"S-C-H-U-L-E.",emoji:"🏫"},
  {q:"Wie viele Minuten hat eine halbe Stunde?",a:30,unit:"Minuten",hint:"Die Hälfte von 60 Minuten.",emoji:"⏰"},
  {q:"Wie viele Tage hat der März?",a:31,unit:"Tage",hint:"Tage – dritter Monat.",emoji:"📅"},
  {q:"Wie viele Bundesländer hat Deutschland?",a:16,unit:"Bundesländer",hint:"Länder – Bayern ist das größte.",emoji:"🇩🇪"},
  {q:"Wie viele Meter tief ist ein Hallenbad?",a:2,unit:"Meter",hint:"Meistens 1,80-2m Tiefe.",emoji:"🏊"},
  {q:"Wie viele Zähne hat ein Hase?",a:28,unit:"Zähne",hint:"Nagetiere mit ständig wachsenden Vorderzähnen.",emoji:"🐇"},
  {q:"Wie viele Seiten hat ein Quadrat?",a:4,unit:"Seiten",hint:"Alle Seiten gleich lang.",emoji:"⬛"},
  {q:"Wie viele Liter fasst ein Rucksack?",a:20,unit:"Liter",hint:"Schulrucksäcke fassen 15-25 Liter.",emoji:"🎒"},
  {q:"Wie viele Monate hat ein Halbjahr?",a:6,unit:"Monate",hint:"Die Hälfte von 12 Monaten.",emoji:"📅"},
  {q:"Wie viele km/h fährt eine S-Bahn durchschnittlich?",a:60,unit:"km/h",hint:"Mit Halten etwa 40-60 km/h Durchschnitt.",emoji:"🚊"},
  {q:"Wie viele Stunden braucht man für 100km zu Fuß?",a:25,unit:"Stunden",hint:"Bei 4 km/h Gehgeschwindigkeit.",emoji:"🚶"},
  {q:"Wie viele Stühle passen an einen normalen Esstisch?",a:6,unit:"Stühle",hint:"Runder oder ovaler 6-Personen-Tisch.",emoji:"🪑"},
  {q:"Wie viele Gramm hat ein Schokoriegel?",a:50,unit:"Gramm",hint:"Typische Größe eines Schokoriegels.",emoji:"🍫"},
  {q:"Wie viele Kilos hat ein Sack Kartoffeln?",a:10,unit:"kg",hint:"Standard-Kartoffelsack.",emoji:"🥔"},
  {q:"Wie viele Buchstaben hat das Alphabet inklusive Umlauten?",a:29,unit:"Buchstaben",hint:"26 + ä, ö, ü = 29.",emoji:"🔤"},
  {q:"Wie viele Beine hat eine Zecke?",a:8,unit:"Beine",hint:"Zecken sind Spinnentiere.",emoji:"🕷️"},
  {q:"Wie viele Tage hat ein Jahr im Durchschnitt?",a:365.25,unit:"Tage",hint:"365 Tage plus ein Viertel – daher alle 4 Jahre Schaltjahr.",emoji:"📅"},
  {q:"Wie viele Minuten schaut ein Kind täglich durchschnittlich TV?",a:90,unit:"Minuten",hint:"Laut Studien etwa 1,5 Stunden täglich.",emoji:"📺"},
  {q:"Wie viele Stunden schläft ein Baby pro Tag?",a:16,unit:"Stunden",hint:"Neugeborene schlafen fast den ganzen Tag.",emoji:"👶"},
  {q:"Wie viele Stufen hat die Leiter einer Feuerwehr?",a:14,unit:"Stufen",hint:"Eine typische Schiebleiter.",emoji:"🚒"},
  {q:"Wie viele Liter Milch braucht man für ein Kilo Butter?",a:21,unit:"Liter",hint:"Sehr viel Milch für wenig Butter.",emoji:"🧈"},
  {q:"Wie viele Gramm Salz braucht man zum Kochen von 500g Nudeln?",a:10,unit:"Gramm",hint:"Pro 100g Nudeln 1-2g Salz.",emoji:"🧂"},
  {q:"Wie viele km/h fährt eine Achterbahn maximal?",a:130,unit:"km/h",hint:"Die schnellsten Achterbahnen der Welt.",emoji:"🎢"},
  {q:"Wie viele Stunden dauert eine Schulwoche?",a:30,unit:"Stunden",hint:"Bei 6 Stunden täglich.",emoji:"🏫"},
  {q:"Wie viele Minuten dauert ein Kinofilm durchschnittlich?",a:100,unit:"Minuten",hint:"Die meisten Filme sind 90-120 Minuten.",emoji:"🎬"},
  {q:"Wie viele Tage hat der August?",a:31,unit:"Tage",hint:"Einer der Monate mit 31 Tagen.",emoji:"📅"},
  {q:"Wie viele Augen hat ein Fliege?",a:2,unit:"Augen",hint:"Aber jedes Auge hat tausende Einzellinsen.",emoji:"🪰"},
  {q:"Wie viele Beine hat ein Krebs?",a:10,unit:"Beine",hint:"Krebse sind Zehnfüßer.",emoji:"🦀"},
  {q:"Wie viele Ecken hat ein Würfel?",a:8,unit:"Ecken",hint:"Ein Würfel hat 8 Ecken, 12 Kanten und 6 Flächen.",emoji:"🎲"},
  {q:"Wie viele Monate haben 31 Tage?",a:7,unit:"Monate",hint:"Jan, März, Mai, Jul, Aug, Okt, Dez.",emoji:"📅"},
  {q:"Wie viele Gramm hat ein halbes Kilogramm?",a:500,unit:"Gramm",hint:"Die Hälfte von 1000g.",emoji:"⚖️"},
  {q:"Wie viele Minuten hat ein Tag?",a:1440,unit:"Minuten",hint:"24 Stunden × 60 Minuten.",emoji:"⏰"},
  {q:"Wie viele Kanten hat ein Würfel?",a:12,unit:"Kanten",hint:"Jede Fläche hat 4 Kanten – aber geteilt.",emoji:"🎲"},
  {q:"Wie viele Seiten hat ein Oktaeder?",a:8,unit:"Seiten",hint:"Okta = acht.",emoji:"🔷"},
  {q:"Wie viele cm ist ein halber Meter?",a:50,unit:"cm",hint:"Die Hälfte von 100cm.",emoji:"📏"},
  {q:"Wie viele Stunden hat eine halbe Woche?",a:84,unit:"Stunden",hint:"3,5 Tage × 24 Stunden.",emoji:"⏰"},
  {q:"Wie viele Achsen hat ein Auto?",a:2,unit:"Achsen",hint:"Vorder- und Hinterachse.",emoji:"🚗"},
  {q:"Wie viele Flügel hat ein Schmetterling?",a:4,unit:"Flügel",hint:"Zwei Vorder- und zwei Hinterflügel.",emoji:"🦋"},
  {q:"Wie viele Augen hat eine Fliege?",a:2,unit:"Augen",hint:"Zwei Facettenaugen mit je tausenden Linsen.",emoji:"🪰"},
  {q:"Wie viele Räder hat ein Dreirad?",a:3,unit:"Räder",hint:"Tri = drei.",emoji:"🚲"},
  {q:"Wie viele Beine hat ein Pferd?",a:4,unit:"Beine",hint:"Vier Hufe.",emoji:"🐴"},
  {q:"Wie viele Flossen hat ein Goldfisch?",a:7,unit:"Flossen",hint:"Rücken, Brust (2), Bauch (2), After, Schwanz.",emoji:"🐠"},
  {q:"Wie viele Knöpfe hat ein normales Hemd?",a:7,unit:"Knöpfe",hint:"Die meisten Hemden haben 6-8 Knöpfe.",emoji:"👔"},
  {q:"Wie viele Seiten hat ein Fünfeck?",a:5,unit:"Seiten",hint:"Penta = fünf.",emoji:"⬠"},
  {q:"Wie viele Jahreszeiten gibt es?",a:4,unit:"Jahreszeiten",hint:"Frühling, Sommer, Herbst, Winter.",emoji:"🌸"},
  {q:"Wie viele Minuten dauert eine Schulpause?",a:10,unit:"Minuten",hint:"Kurze Pause zwischen den Stunden.",emoji:"🏫"},
  {q:"Wie viele Flügel hat eine Biene?",a:4,unit:"Flügel",hint:"Zwei Vorder- und zwei Hinterflügel.",emoji:"🐝"},
  {q:"Wie viele Hände hat ein Mensch?",a:2,unit:"Hände",hint:"Links und rechts.",emoji:"🙌"},
  {q:"Wie viele Tassen passen in einen Liter?",a:4,unit:"Tassen",hint:"Eine Tasse hat 250ml.",emoji:"☕"},
  {q:"Wie viele Seiten hat ein Heptagon?",a:7,unit:"Seiten",hint:"Hepta = sieben.",emoji:"⬡"},
  {q:"Wie viele Monate hat ein Quartal?",a:3,unit:"Monate",hint:"Q1: Jan-März, Q2: Apr-Jun, usw.",emoji:"📅"},
  {q:"Wie viele Noten hat die Tonleiter?",a:7,unit:"Noten",hint:"Do, Re, Mi, Fa, Sol, La, Si.",emoji:"🎵"},
  {q:"Wie viele Stunden hat ein langer Schulnachmittag?",a:4,unit:"Stunden",hint:"Von 13-17 Uhr.",emoji:"🏫"},
  {q:"Wie viele Beine hat ein Hund?",a:4,unit:"Beine",hint:"Vier Pfoten.",emoji:"🐕"},
  {q:"Wie viele Flügel hat ein Vogel?",a:2,unit:"Flügel",hint:"Zwei – links und rechts.",emoji:"🐦"},
  {q:"Wie viele Augen hat ein Pferd?",a:2,unit:"Augen",hint:"Seitlich angeordnet für weites Sichtfeld.",emoji:"🐴"},
  {q:"Wie viele Stunden braucht man um 10km zu Fuß zu gehen?",a:2.5,unit:"Stunden",hint:"Bei 4 km/h.",emoji:"🚶"},
  {q:"Wie viele Liter hat eine große PET-Flasche?",a:1.5,unit:"Liter",hint:"Die gängige Größe im Supermarkt.",emoji:"🍶"},
  {q:"Wie viele Räder hat ein Fahrrad?",a:2,unit:"Räder",hint:"Bi = zwei – daher Fahrrad.",emoji:"🚲"},
  {q:"Wie viele Federn hat ein Pfauenschwanz?",a:200,unit:"Federn",hint:"Bis zu 200 Schmuckfedern.",emoji:"🦚"},
  {q:"Wie viele Punkte hat ein Stern mit 6 Zacken?",a:6,unit:"Zacken",hint:"Der Davidstern.",emoji:"✡️"},
  {q:"Wie viele Minuten dauert eine Schulwoche in Unterricht?",a:1350,unit:"Minuten",hint:"30 Schulstunden à 45 Minuten.",emoji:"🏫"},
  {q:"Wie viele Beine hat eine Katze?",a:4,unit:"Beine",hint:"Vier Pfoten.",emoji:"🐱"},
  {q:"Wie viele Seiten hat ein Nona-Eck?",a:9,unit:"Seiten",hint:"Nona = neun.",emoji:"🔷"},
  {q:"Wie viele Ohren hat ein Hase?",a:2,unit:"Ohren",hint:"Sehr lange Ohren!",emoji:"🐇"},
  {q:"Wie viele Taschen hat eine Jeans normalerweise?",a:5,unit:"Taschen",hint:"2 vorne, 2 hinten, 1 kleine.",emoji:"👖"},
  {q:"Wie viele Wirbelsäulen hat ein Mensch?",a:1,unit:"Wirbelsäule",hint:"Aus 33 einzelnen Wirbeln.",emoji:"🦴"},
  {q:"Wie viele Augen hat ein Einhorn?",a:2,unit:"Augen",hint:"Wie alle Säugetiere.",emoji:"🦄"},
  {q:"Wie viele Zähne verliert ein Kind insgesamt?",a:20,unit:"Zähne",hint:"Das gesamte Milchgebiss.",emoji:"🦷"},
  {q:"Wie viele Flügel hat ein Marienkäfer?",a:4,unit:"Flügel",hint:"2 Deckflügel und 2 Flugflügel.",emoji:"🐞"},
  {q:"Wie viele Liter hat eine Badewanne?",a:150,unit:"Liter",hint:"Typische Badewannen-Größe.",emoji:"🛁"},
  {q:"Wie viele Monate hat ein Trimester?",a:3,unit:"Monate",hint:"In der Schwangerschaft ein Drittel.",emoji:"📅"},
  {q:"Wie viele Noten hat eine Oktave?",a:8,unit:"Noten",hint:"Töne von C bis C.",emoji:"🎵"},
  {q:"Wie viele Stufen hat eine normale Leiter?",a:8,unit:"Stufen",hint:"Verschiedene Größen – ca. 8.",emoji:"🪜"},
  {q:"Wie viele Blätter hat ein vierblättriges Kleeblatt?",a:4,unit:"Blätter",hint:"Sehr selten – bringt Glück!",emoji:"🍀"},
  {q:"Wie viele Achsen hat ein LKW?",a:3,unit:"Achsen",hint:"Vorne 1, hinten 2 Achsen.",emoji:"🚛"}
];
