export default [
  {id:"kunst_001",q:"Wie viele Farben hat ein Regenbogen?",a:7,unit:"Farben",hint:"Rot, Orange, Gelb, Grün, Blau, Indigo, Violett.",emoji:"🌈"},
  {id:"kunst_002",q:"Wie viele Jahre malte Leonardo da Vinci an der Mona Lisa?",a:4,unit:"Jahre",hint:"Ca. 1503–1507 – manche sagen er hat nie aufgehört.",emoji:"🖼️"},
  {id:"kunst_003",q:"Wie viele Saiten hat eine klassische Gitarre?",a:6,unit:"Saiten",hint:"6 Saiten – Ukulele hat 4, Geige auch 4.",emoji:"🎸"},
  {id:"kunst_004",q:"Wie viele Tasten hat ein modernes Klavier?",a:88,unit:"Tasten",hint:"52 weiße und 36 schwarze Tasten.",emoji:"🎹"},
  {id:"kunst_005",q:"Wie viele Grundfarben gibt es beim Malen?",a:3,unit:"Grundfarben",hint:"Rot, Gelb, Blau – daraus entstehen alle anderen Farben.",emoji:"🎨"},
  {id:"kunst_006",q:"Wie viele Linien hat ein Notenblatt (ein System)?",a:5,unit:"Linien",hint:"5 Linien und 4 Zwischenräume.",emoji:"🎵"},
  {id:"kunst_007",q:"Wie viele Saiten hat eine Violine?",a:4,unit:"Saiten",hint:"G, D, A, E – von tief nach hoch.",emoji:"🎻"},
  {id:"kunst_008",q:"Wie viele Töne hat eine Oktave?",a:8,unit:"Töne",hint:"Do, Re, Mi, Fa, Sol, La, Si, Do.",emoji:"🎼"},
  {id:"kunst_009",q:"Wie viele Farben hat die deutsche Flagge?",a:3,unit:"Farben",hint:"Schwarz, Rot, Gold – seit 1919.",emoji:"🇩🇪"},
  {id:"kunst_010",q:"Wie viele Saiten hat eine Harfe (klassisch)?",a:47,unit:"Saiten",hint:"47 Saiten und 7 Pedale.",emoji:"🎵"},
  {id:"kunst_011",q:"Wie viele Ventile hat eine klassische Trompete?",a:3,unit:"Ventile",hint:"3 Ventile – damit werden verschiedene Töne gespielt.",emoji:"🎺"},
  {id:"kunst_012",q:"Wie viele Seiten hat ein Dreieck?",a:3,unit:"Seiten",hint:"3 Seiten, 3 Ecken, Winkelsumme 180°.",emoji:"📐"},
  {id:"kunst_013",q:"Wie viele Buchstaben hat das deutsche Alphabet?",a:26,unit:"Buchstaben",hint:"26 Buchstaben plus Umlaute ä, ö, ü und ß.",emoji:"📝"},
  {id:"kunst_014",q:"Wie viele Seiten hat ein Oktagon?",a:8,unit:"Seiten",hint:"Oktagon = 8 Seiten – wie ein Stoppschild.",emoji:"🛑"},
  {id:"kunst_015",q:"Wie viele Seiten hat ein Hexagon?",a:6,unit:"Seiten",hint:"Hexa = 6 – wie eine Bienenwabe.",emoji:"🐝"},
  {id:"kunst_016",q:"Wie viele Primärfarben gibt es beim Licht (RGB)?",a:3,unit:"Farben",hint:"Rot, Grün, Blau – zusammen ergeben sie Weiß.",emoji:"💡"},
  {id:"kunst_017",q:"Wie viele Töne hat die Pentatonik-Tonleiter?",a:5,unit:"Töne",hint:"5 Töne – Grundlage vieler Volkslieder und Bluesmusik.",emoji:"🎵"},
  {id:"kunst_018",q:"Wie viele Meter hoch ist der Eiffelturm?",a:330,unit:"Meter",hint:"Mit Antenne 330m – ohne 300m. Gebaut 1889.",emoji:"🗼"},
  {id:"kunst_019",q:"Wie viele Seiten hat ein Fünfeck?",a:5,unit:"Seiten",hint:"Fünf-Eck = Pentagon.",emoji:"⬠"},
  {id:"kunst_020",q:"Wie viele Farben hat ein typischer Buntstift-Kasten (klein)?",a:12,unit:"Farben",hint:"Kleine Kästen haben meist 12, große bis zu 120 Farben.",emoji:"🖍️"},
  {id:"kunst_021",q:"Wie viele Werke schuf Pablo Picasso?",a:20000,unit:"Werke",hint:"Über 20.000 Werke – Gemälde, Skulpturen, Zeichnungen.",emoji:"🎨"},
  {id:"kunst_022",q:"Wie viele Meter ist die Sixtinische Kapelle lang?",a:40,unit:"Meter",hint:"40 Meter lang, 13 Meter breit – Michelangelo malte die Decke.",emoji:"⛪"},
  {id:"kunst_023",q:"Wie viele Jahre arbeitete Michelangelo an der Decke der Sixtinischen Kapelle?",a:4,unit:"Jahre",hint:"1508–1512 – liegend auf einem Gerüst.",emoji:"🎨"},
  {id:"kunst_024",q:"Wie viele Stockwerke hat der Eiffelturm?",a:3,unit:"Stockwerke",hint:"3 Etagen – auf allen kann man die Aussicht genießen.",emoji:"🗼"},
  {id:"kunst_025",q:"Wie viele Primärfarben beim Drucken (CMYK)?",a:4,unit:"Farben",hint:"Cyan, Magenta, Yellow, Key (Schwarz) – für den Druck.",emoji:"🖨️"},
  {id:"kunst_026",q:"Wie viele Töne hat die chromatische Tonleiter?",a:12,unit:"Töne",hint:"12 Halbtöne innerhalb einer Oktave.",emoji:"🎹"},
  {id:"kunst_027",q:"Wie viele Farben enthält weißes Licht?",a:7,unit:"Farben",hint:"Weißes Licht enthält alle Regenbogenfarben.",emoji:"🌈"},
  {id:"kunst_028",q:"Wie viele Meter hoch ist die Mona Lisa?",a:0.77,unit:"Meter",hint:"77 cm × 53 cm – kleiner als die meisten denken.",emoji:"🖼️"},
  {id:"kunst_029",q:"Wie viele Gemälde hat van Gogh zu Lebzeiten verkauft?",a:1,unit:"Gemälde",hint:"Nur eines – 'Die rote Weinberg' – zu Lebzeiten.",emoji:"🌻"},
  {id:"kunst_030",q:"Wie viele Sterne sind auf van Goghs 'Sternennacht'?",a:11,unit:"Sterne",hint:"11 Sterne plus Mond in dem berühmten Gemälde.",emoji:"🌙"},
  {id:"kunst_031",q:"Wie viele Töne erklingen bei einem Dur-Dreiklang?",a:3,unit:"Töne",hint:"Grundton, Terz und Quinte – z.B. C-E-G.",emoji:"🎵"},
  {id:"kunst_032",q:"Wie viele Oktaven hat ein normales Klavier?",a:7,unit:"Oktaven",hint:"7 vollständige Oktaven plus ein paar Töne.",emoji:"🎹"},
  {id:"kunst_033",q:"Wie viele Farben hat die Regenbogenfahne (Pride)?",a:6,unit:"Farben",hint:"Rot, Orange, Gelb, Grün, Blau, Violett.",emoji:"🏳️‍🌈"},
  {id:"kunst_034",q:"Wie viele Farben hat das Olympische Logo?",a:5,unit:"Farben",hint:"Blau, Gelb, Schwarz, Grün, Rot – je eine pro Kontinent.",emoji:"🏅"},
  {id:"kunst_035",q:"Wie viele Seiten hat ein Rechteck?",a:4,unit:"Seiten",hint:"4 Seiten – zwei Paare gleich langer Seiten.",emoji:"▭"},
  {id:"kunst_036",q:"Wie viele Seiten hat ein Siebeneck?",a:7,unit:"Seiten",hint:"Sieben-Eck = Heptagon.",emoji:"⬡"},
  {id:"kunst_037",q:"Wie viele Seiten hat ein Achteck?",a:8,unit:"Seiten",hint:"Acht-Eck = Oktagon.",emoji:"🛑"},
  {id:"kunst_038",q:"Wie viele Jahre ist die Venus von Milo alt?",a:2200,unit:"Jahre",hint:"Ca. 130-100 v.Chr. erschaffen – also etwa 2.200 Jahre.",emoji:"🏛️"},
  {id:"kunst_039",q:"Wie viele cm lang ist ein DIN-A4-Blatt?",a:29.7,unit:"cm",hint:"DIN A4: 21 × 29,7 cm – der häufigste Papierstandard.",emoji:"📄"},
  {id:"kunst_040",q:"Wie viele Gramm wiegt ein normaler Bleistift?",a:6,unit:"Gramm",hint:"Ca. 5-7 Gramm – je nach Länge.",emoji:"✏️"},
  {id:"kunst_041",q:"Wie viele Millimeter breit ist ein normaler Bleistift?",a:7,unit:"Millimeter",hint:"Ca. 7mm – die Mine innen ist nur 2mm.",emoji:"✏️"},
  {id:"kunst_042",q:"Wie viele Gemälde malte Leonardo da Vinci im Leben?",a:20,unit:"Gemälde",hint:"Nur ca. 15-20 vollendete Gemälde – aber Tausende Zeichnungen.",emoji:"🖼️"},
  {id:"kunst_043",q:"Wie viele Stunden malte Picasso täglich auf dem Höhepunkt?",a:8,unit:"Stunden",hint:"Bis zu 8 Stunden – er war extrem produktiv.",emoji:"🖌️"},
  {id:"kunst_044",q:"Wie viele Farben mischt man um Orange zu bekommen?",a:2,unit:"Farben",hint:"Rot + Gelb = Orange.",emoji:"🎨"},
  {id:"kunst_045",q:"Wie viele Farben mischt man um Grün zu bekommen?",a:2,unit:"Farben",hint:"Blau + Gelb = Grün.",emoji:"🎨"},
  {id:"kunst_046",q:"Wie viele Farben mischt man um Lila zu bekommen?",a:2,unit:"Farben",hint:"Rot + Blau = Lila/Violett.",emoji:"🎨"},
  {id:"kunst_047",q:"Wie viele Seiten hat ein Drachen (Viereck)?",a:4,unit:"Seiten",hint:"Ein Drachen ist ein Viereck mit zwei Paaren gleich langer Seiten.",emoji:"🪁"},
  {id:"kunst_048",q:"Wie viele Noten hat ein Lied normalerweise mindestens?",a:8,unit:"Noten",hint:"Die meisten einfachen Lieder haben mindestens 8 Töne.",emoji:"🎵"},
  {id:"kunst_049",q:"Wie viele kg wiegt ein Steinway-Konzertflügel?",a:480,unit:"kg",hint:"Ca. 480 kg – ein sehr schweres Instrument.",emoji:"🎹"},
  {id:"kunst_050",q:"Wie viele Farben hat eine normale Wasserfarben-Palette (Schule)?",a:12,unit:"Farben",hint:"12 Farben – genug für Grundschüler.",emoji:"🎨"},
  {id:"kunst_051",q:"Wie viele Minuten dauert Beethovens 5. Sinfonie?",a:33,unit:"Minuten",hint:"Ca. 33 Minuten – mit dem berühmten 'ta-ta-ta-taaaa'-Motiv.",emoji:"🎼"},
  {id:"kunst_052",q:"Wie viele Seiten hat ein Quadrat?",a:4,unit:"Seiten",hint:"4 gleich lange Seiten – alle Winkel 90°.",emoji:"⬜"},
  {id:"kunst_053",q:"Wie viele Meter ist die größte Leinwand der Welt?",a:5000,unit:"Meter",hint:"In Dubai wurde eine 5.000m² große Leinwand bemalt.",emoji:"🖼️"},
  {id:"kunst_054",q:"Wie viele Zentimeter dick ist die Mauer der Sixtinischen Kapelle?",a:60,unit:"cm",hint:"Die Wände sind ca. 60cm dick – typisch für Renaissance-Bauten.",emoji:"🏛️"},
  {id:"kunst_055",q:"Wie viele Millionen Farben kann das menschliche Auge unterscheiden?",a:10,unit:"Millionen Farben",hint:"Ca. 10 Millionen Farbnuancen – das Gehirn verarbeitet sie.",emoji:"👁️"},
  {id:"kunst_056",q:"Wie viele Buchstaben hat das chinesische Alphabet?",a:50000,unit:"Zeichen",hint:"Ca. 50.000 Schriftzeichen – im Alltag braucht man 3.000.",emoji:"📝"},
  {id:"kunst_057",q:"Wie viele Werke schrieb Mozart?",a:626,unit:"Werke",hint:"606 Werke – das letzte (Requiem) blieb unvollendet.",emoji:"🎼"},
  {id:"kunst_058",q:"Wie viele Jahre alt war Mozart als er starb?",a:35,unit:"Jahre",hint:"Wolfgang Amadeus Mozart starb 1791 im Alter von 35 Jahren.",emoji:"🎹"},
  {id:"kunst_059",q:"Wie viele Symphonien schrieb Beethoven?",a:9,unit:"Symphonien",hint:"9 Symphonien – die 9. mit der Ode an die Freude.",emoji:"🎼"},
  {id:"kunst_060",q:"Wie viele Noten hat eine Viertelnote Wert (in Achtelnoten)?",a:2,unit:"Achtelnoten",hint:"Eine Viertelnote = 2 Achtelnoten = 4 Sechzehntelnoten.",emoji:"🎵"},
  {id:"kunst_061",q:"Wie viele Tonarten gibt es in der Musik?",a:24,unit:"Tonarten",hint:"12 Dur- und 12 Moll-Tonarten.",emoji:"🎹"},
  {id:"kunst_062",q:"Wie viele Stunden dauerte die Entstehung der Sixtinischen Kapellen-Decke?",a:20000,unit:"Stunden",hint:"Ca. 4 Jahre × 5.000 Stunden/Jahr – enorme Arbeit.",emoji:"⛪"},
  {id:"kunst_063",q:"Wie viele Stücke malte Rembrandt?",a:350,unit:"Gemälde",hint:"Ca. 350 Gemälde – dazu Hunderte Radierungen.",emoji:"🖼️"},
  {id:"kunst_064",q:"Wie viele Meter hoch ist das Brandenburger Tor?",a:26,unit:"Meter",hint:"26m hoch – das Wahrzeichen Berlins.",emoji:"🏛️"},
  {id:"kunst_065",q:"Wie viele Säulen hat das Brandenburger Tor?",a:12,unit:"Säulen",hint:"12 dorische Säulen – 6 vorne, 6 hinten.",emoji:"🏛️"},
];
