// 🌍 GEOGRAFIE – Kinder
export default [
  {q:"Wie hoch ist der Mount Everest in Metern?",a:8849,unit:"Meter",hint:"Der höchste Berg der Erde, im Himalaya.",emoji:"🏔️"},
  {q:"Wie lang ist der Nil in km?",a:6650,unit:"km",hint:"Er ist der längste Fluss der Welt.",emoji:"🌊"},
  {q:"Wie viele Länder gibt es auf der Erde?",a:195,unit:"Länder",hint:"Davon sind 193 Mitglieder der UNO.",emoji:"🌍"},
  {q:"Wie tief ist der Marianengraben in Metern?",a:11000,unit:"Meter",hint:"Der tiefste Punkt der Weltmeere.",emoji:"🌊"},
  {q:"Wie viele km lang ist der Amazonas?",a:6400,unit:"km",hint:"Der wasserreichste Fluss der Welt.",emoji:"🌿"},
  {q:"Wie hoch liegt die Hauptstadt Boliviens (La Paz) in Metern?",a:3600,unit:"Meter",hint:"Eine der höchstgelegenen Hauptstädte der Welt.",emoji:"🏙️"},
  {q:"Wie viele km² hat die Sahara?",a:9200000,unit:"km²",hint:"Die größte Wüste der Welt.",emoji:"🏜️"},
  {q:"Wie tief ist der Baikalsee in Metern?",a:1642,unit:"Meter",hint:"Der tiefste See der Welt, in Russland.",emoji:"💧"},
  {q:"Wie viele Einwohner hat China (Milliarden)?",a:1.4,unit:"Milliarden",hint:"Das bevölkerungsreichste Land der Erde.",emoji:"🇨🇳"},
  {q:"Wie hoch ist der Eiffelturm in Metern?",a:330,unit:"Meter",hint:"Inklusive Antenne steht er in Paris.",emoji:"🗼"},
  {q:"Wie viele Einwohner hat die Erde (Milliarden)?",a:8,unit:"Milliarden",hint:"2022 überschritt die Weltbevölkerung 8 Milliarden.",emoji:"🌍"},
  {q:"Wie lang ist der Rhein in km?",a:1230,unit:"km",hint:"Er fließt durch die Schweiz, Deutschland und die Niederlande.",emoji:"🌊"},
  {q:"Wie hoch fliegen Flugzeuge durchschnittlich in Metern?",a:10000,unit:"Meter",hint:"Die Reiseflughöhe liegt bei 9.000–12.000 Metern.",emoji:"✈️"},
  {q:"Wie lang ist die Elbe in km?",a:1091,unit:"km",hint:"Sie fließt von Tschechien durch Deutschland.",emoji:"🌊"},
  {q:"Wie viele Inseln hat Indonesien?",a:17000,unit:"Inseln",hint:"Der viertbevölkerungsreichste Staat der Welt.",emoji:"🏝️"},
  {q:"Wie hoch ist die Zugspitze in Metern?",a:2962,unit:"Meter",hint:"Der höchste Berg Deutschlands in Bayern.",emoji:"🏔️"},
  {q:"Wie viele km ist der Äquator lang?",a:40075,unit:"km",hint:"Der Umfang der Erde am Breitengrad 0°.",emoji:"🌍"},
  {q:"Wie viele km² ist der Schwarzwald groß?",a:6000,unit:"km²",hint:"Das größte zusammenhängende Waldgebirge Deutschlands.",emoji:"🌲"},
  {q:"Wie viele km² ist der Amazonas-Regenwald groß?",a:5500000,unit:"km²",hint:"Die größte tropische Regenwaldregion der Erde.",emoji:"🌴"},
  {q:"Wie lang ist die Küstenlinie Kanadas in km?",a:202080,unit:"km",hint:"Die längste Küstenlinie aller Länder.",emoji:"🍁"},
  {q:"Wie viele km² ist Grönland groß?",a:2166086,unit:"km²",hint:"Die größte Insel der Welt.",emoji:"🧊"},
  {q:"Wie lang ist der Mississippi in km?",a:3730,unit:"km",hint:"Der längste Fluss Nordamerikas zusammen mit dem Missouri.",emoji:"🌊"},
{q:"Wie lang ist der Amazonas in km?",a:6400,unit:"km",hint:"Der wasserreichste Fluss der Welt.",emoji:"🌿"},
  {q:"Wie hoch ist der Kilimandscharo in Metern?",a:5895,unit:"Meter",hint:"Der höchste Berg Afrikas.",emoji:"🏔️"},
  {q:"Wie lang ist die Chinesische Mauer in km?",a:21000,unit:"km",hint:"Das längste Bauwerk der Menschheitsgeschichte.",emoji:"🧱"},
  {q:"Wie viele km² hat Deutschland?",a:357000,unit:"km²",hint:"Das flächengrößte Land in Mitteleuropa.",emoji:"🇩🇪"},
  {q:"Wie viele Einwohner hat China in Milliarden?",a:1.4,unit:"Milliarden",hint:"Das bevölkerungsreichste Land.",emoji:"🇨🇳"},
  {q:"Wie groß ist Australien in km²?",a:7700000,unit:"km²",hint:"Der sechstgrößte Staat der Erde.",emoji:"🦘"},
  {q:"Wie viele Länder grenzen an Deutschland?",a:9,unit:"Länder",hint:"Dänemark, Polen, Tschechien, Österreich, Schweiz, Frankreich, Luxemburg, Belgien, Niederlande.",emoji:"🇩🇪"},
  {q:"Wie viele km² ist die Sahara groß?",a:9200000,unit:"km²",hint:"Die größte Wüste der Welt.",emoji:"🏜️"},
  {q:"Wie viele Einwohner hat die Erde in Milliarden?",a:8,unit:"Milliarden",hint:"2022 wurden 8 Milliarden überschritten.",emoji:"🌍"},
  {q:"Wie tief ist der Genfer See in Metern?",a:310,unit:"Meter",hint:"Der größte See Mitteleuropas.",emoji:"💧"},
  {q:"Wie hoch ist der Fuji in Japan in Metern?",a:3776,unit:"Meter",hint:"Der heilige Berg Japans ist ein Vulkan.",emoji:"🗻"},
  {q:"Wie groß ist Grönland in km²?",a:2166086,unit:"km²",hint:"Die größte Insel der Welt.",emoji:"🧊"},
  {q:"Wie hoch ist die Statue of Liberty in New York in Metern?",a:93,unit:"Meter",hint:"Inklusive Sockel und Fackel.",emoji:"🗽"},
  {q:"Wie viele km lang ist der Grand Canyon?",a:446,unit:"km",hint:"Das größte Canyon-System der USA.",emoji:"🏜️"},
  {q:"Wie viele Länder sind in der EU?",a:27,unit:"Länder",hint:"Nach dem Brexit.",emoji:"🇪🇺"},
  {q:"Wie tief ist der tiefste See der USA (Crater Lake) in Metern?",a:594,unit:"Meter",hint:"In Oregon – entstand durch einen Vulkan.",emoji:"💧"},
  {q:"Wie groß ist die Antarktis in km²?",a:14000000,unit:"km²",hint:"Das fünftgrößte Territorium der Erde.",emoji:"🧊"},
  {q:"Wie lang ist die Donau in km?",a:2860,unit:"km",hint:"Fließt durch 10 Länder.",emoji:"🌊"},
  {q:"Wie hoch liegt Mexiko-Stadt in Metern?",a:2240,unit:"Meter",hint:"Eine der höchstgelegenen Hauptstädte.",emoji:"🏙️"},
  {q:"Wie viele km lang ist die Küstenlinie Australiens?",a:25760,unit:"km",hint:"Sehr langer Küstenstreifen.",emoji:"🏖️"},
  {q:"Wie groß ist Russland in Millionen km²?",a:17,unit:"Mio. km²",hint:"Das größte Land der Welt.",emoji:"🗺️"},
  {q:"Wie hoch ist der Olymp in Griechenland in Metern?",a:2917,unit:"Meter",hint:"Der höchste Berg Griechenlands – Göttersitz.",emoji:"🏔️"},
  {q:"Wie viele Länder hat Südamerika?",a:12,unit:"Länder",hint:"Von Kolumbien bis Argentinien.",emoji:"🌎"},
  {q:"Wie lang ist der Niger in km?",a:4180,unit:"km",hint:"Der drittlängste Fluss Afrikas.",emoji:"🌊"},
  {q:"Wie tief ist der Marianengraben genau in Metern?",a:11034,unit:"Meter",hint:"Der Challenger Deep – tiefste Stelle der Ozeane.",emoji:"🌊"},
  {q:"Wie viele km² hat Bayern?",a:70550,unit:"km²",hint:"Das größte deutsche Bundesland.",emoji:"🍺"},
  {q:"Wie hoch ist der Mont Blanc in Metern?",a:4808,unit:"Meter",hint:"Der höchste Berg der Alpen.",emoji:"🏔️"},
  {q:"Wie viele Länder liegen auf dem Kontinent Ozeanien?",a:14,unit:"Länder",hint:"Australien, Neuseeland und die Pazifikinseln.",emoji:"🌊"},
  {q:"Wie lang ist der Nil mit dem Weißen Nil zusammen in km?",a:6650,unit:"km",hint:"Der längste Fluss der Welt.",emoji:"🌊"},
  {q:"Wie viele km² ist die Gobi-Wüste groß?",a:1295000,unit:"km²",hint:"Die kälteste Wüste der Welt.",emoji:"🏜️"},
  {q:"Wie hoch ist der Vesuvius in Metern?",a:1281,unit:"Meter",hint:"Der Vulkan der Pompeji zerstörte.",emoji:"🌋"},
  {q:"Wie viele km² hat Österreich?",a:83879,unit:"km²",hint:"Kleines aber bergiges Land.",emoji:"🇦🇹"},
  {q:"Wie lang ist der Kongo in km?",a:4700,unit:"km",hint:"Der tiefste Fluss der Welt.",emoji:"🌊"},
  {q:"Wie viele km² ist das Mittelmeer groß?",a:2500000,unit:"km²",hint:"Das größte Binnenmeer der Welt.",emoji:"🌊"},
  {q:"Wie hoch ist der Kilimandscharo-Gipfel Kibo in Metern?",a:5895,unit:"Meter",hint:"Der höchste Punkt Afrikas.",emoji:"🏔️"},
  {q:"Wie viele Länder hat Asien?",a:49,unit:"Länder",hint:"Der größte Kontinent mit den meisten Menschen.",emoji:"🌏"},
  {q:"Wie lang ist der Jenissei in km?",a:5539,unit:"km",hint:"Einer der längsten Flüsse der Welt in Russland.",emoji:"🌊"},
  {q:"Wie viele km² ist die Namib-Wüste groß?",a:81000,unit:"km²",hint:"Die älteste Wüste der Welt.",emoji:"🏜️"},
  {q:"Wie hoch ist der Aconcagua in Metern?",a:6961,unit:"Meter",hint:"Der höchste Berg Südamerikas.",emoji:"🏔️"},
  {q:"Wie viele km lang ist der Panamakanal?",a:82,unit:"km",hint:"Verbindet Atlantik und Pazifik.",emoji:"⛵"},
  {q:"Wie viele km² ist Brasilien groß?",a:8515767,unit:"km²",hint:"Das fünftgrößte Land der Welt.",emoji:"🇧🇷"},
  {q:"Wie lang ist der Rhein vom Ursprung bis zur Mündung in km?",a:1230,unit:"km",hint:"Entspringt in der Schweiz.",emoji:"🌊"},
  {q:"Wie viele km hoch ist der Himalaya-Gebirgszug insgesamt?",a:2400,unit:"km Länge",hint:"Das längste Hochgebirge der Erde.",emoji:"🏔️"},
  {q:"Wie tief ist der Titicacasee in Metern?",a:283,unit:"Meter",hint:"Der höchstgelegene schiffbare See.",emoji:"💧"},
  {q:"Wie viele km² hat die Schweiz?",a:41285,unit:"km²",hint:"Kleines Land mit großen Bergen.",emoji:"🇨🇭"},
  {q:"Wie lang ist der Ob in Russland in km?",a:3650,unit:"km",hint:"Einer der größten sibirischen Flüsse.",emoji:"🌊"},
  {q:"Wie viele km entfernt ist New York von London?",a:5570,unit:"km",hint:"Über den Atlantik.",emoji:"✈️"},
  {q:"Wie viele km² ist die Mongolei groß?",a:1564116,unit:"km²",hint:"Das Land mit der niedrigsten Bevölkerungsdichte.",emoji:"🐎"},
  {q:"Wie hoch ist der Elbrus in Russland in Metern?",a:5642,unit:"Meter",hint:"Der höchste Berg Europas.",emoji:"🏔️"},
  {q:"Wie viele Einwohner hat Tokio in Millionen?",a:37,unit:"Millionen",hint:"Die größte Stadtregion der Welt.",emoji:"🗼"},
  {q:"Wie lang ist der Suezkanal in km?",a:193,unit:"km",hint:"Verbindet Mittelmeer und Rotes Meer.",emoji:"⛵"},
  {q:"Wie viele km² ist die Arabische Halbinsel groß?",a:3237500,unit:"km²",hint:"Die größte Halbinsel der Welt.",emoji:"🏜️"},
  {q:"Wie hoch ist der Etna auf Sizilien in Metern?",a:3357,unit:"Meter",hint:"Der aktivste Vulkan Europas.",emoji:"🌋"},
  {q:"Wie viele km² ist Kanada groß?",a:9984670,unit:"km²",hint:"Das zweitgrößte Land der Welt.",emoji:"🍁"},
  {q:"Wie tief ist der Tiefste Punkt Deutschlands (Wilstedt)?",a:3,unit:"m unter Meeresspiegel",hint:"Im Wilstermarsch in Schleswig-Holstein.",emoji:"📏"},
  {q:"Wie viele Inseln hat Griechenland?",a:6000,unit:"Inseln",hint:"Davon sind etwa 200 bewohnt.",emoji:"🏝️"},
  {q:"Wie lang ist die Transsibirische Eisenbahn in km?",a:9289,unit:"km",hint:"Die längste Bahnstrecke der Welt.",emoji:"🚂"},
  {q:"Wie viele km² hat die Türkei?",a:783562,unit:"km²",hint:"Liegt in Europa und Asien.",emoji:"🇹🇷"},
  {q:"Wie hoch ist der Große Ararat in der Türkei in Metern?",a:5137,unit:"Meter",hint:"Der biblische Berg der Arche Noah.",emoji:"🏔️"},
  {q:"Wie viele km lang ist der Amazonas-Regenwald?",a:3000,unit:"km Breite",hint:"Größtes Regenwaldgebiet der Erde.",emoji:"🌿"},
  {q:"Wie viele Länder hat Europa?",a:44,unit:"Länder",hint:"Je nach Definition 44-50.",emoji:"🇪🇺"},
  {q:"Wie lang ist die Grenze zwischen USA und Kanada in km?",a:8891,unit:"km",hint:"Die längste Landesgrenze der Welt.",emoji:"🗺️"},
  {q:"Wie viele km² ist Indien groß?",a:3287263,unit:"km²",hint:"Das siebtgrößte Land der Welt.",emoji:"🇮🇳"},
  {q:"Wie hoch ist die Zugspitze über München in Metern (Unterschied)?",a:2932,unit:"Meter",hint:"München liegt auf 520m, Zugspitze auf 2962m.",emoji:"🏔️"},
  {q:"Wie lang ist die Weser in km?",a:452,unit:"km",hint:"Fließt durch Hessen, Niedersachsen in die Nordsee.",emoji:"🌊"},
  {q:"Wie hoch ist der Brocken im Harz in Metern?",a:1141,unit:"Meter",hint:"Der höchste Gipfel Norddeutschlands.",emoji:"🏔️"},
  {q:"Wie viele km² ist die Nordsee groß?",a:575000,unit:"km²",hint:"Ein Randmeer des Atlantiks.",emoji:"🌊"},
  {q:"Wie weit ist Berlin von München in km Luftlinie?",a:504,unit:"km",hint:"Beide Hauptstädte Deutschlands.",emoji:"🇩🇪"},
  {q:"Wie lang ist der Inn in km?",a:517,unit:"km",hint:"Entspringt in der Schweiz – mündet in die Donau.",emoji:"🌊"},
  {q:"Wie viele km entfernt liegt Hamburg von der Nordsee?",a:100,unit:"km",hint:"Die Elbe verbindet Hamburg mit der See.",emoji:"⛵"},
  {q:"Wie hoch ist der Feldberg im Schwarzwald in Metern?",a:1493,unit:"Meter",hint:"Der höchste Berg Baden-Württembergs.",emoji:"🏔️"},
  {q:"Wie viele Einwohner hat München?",a:1500000,unit:"Einwohner",hint:"Ca. 1,5 Millionen – größte Stadt Bayerns.",emoji:"🏙️"},
  {q:"Wie viele km² ist Berlin groß?",a:892,unit:"km²",hint:"Etwa 3,7 Millionen Einwohner.",emoji:"🇩🇪"},
  {q:"Wie viele Kilometer Autobahnnetz hat Deutschland?",a:13200,unit:"km",hint:"Das drittlängste der Welt.",emoji:"🛣️"},
  {q:"Wie hoch ist der Taunus-Höchste Punkt (Großer Feldberg) in Metern?",a:878,unit:"Meter",hint:"Nördlich von Frankfurt.",emoji:"🏔️"},
  {q:"Wie weit ist Hamburg von Frankfurt in km Luftlinie?",a:430,unit:"km",hint:"Beide sind Millionenstädte.",emoji:"🇩🇪"},
  {q:"Wie viele Bundesländer hat Deutschland?",a:16,unit:"Bundesländer",hint:"3 Stadtstaaten und 13 Flächenländer.",emoji:"🇩🇪"},
  {q:"Wie lang ist die Autobahn A9 (München-Berlin) in km?",a:524,unit:"km",hint:"Eine der wichtigsten deutschen Autobahnen.",emoji:"🛣️"},
  {q:"Wie viele km² ist der Bodensee groß?",a:536,unit:"km²",hint:"Drittgrößter See Mitteleuropas.",emoji:"💧"},
  {q:"Wie tief ist der Bodensee maximal in Metern?",a:254,unit:"Meter",hint:"Am tiefsten zwischen Bregenz und Friedrichshafen.",emoji:"💧"},
  {q:"Wie viele km² ist Hamburg groß?",a:755,unit:"km²",hint:"Einer der drei deutschen Stadtstaaten.",emoji:"⚓"},
  {q:"Wie hoch ist der Wendelstein in Bayern in Metern?",a:1838,unit:"Meter",hint:"Mit Zahnradbahn zugänglich.",emoji:"🏔️"},
  {q:"Wie weit ist Köln von Düsseldorf in km?",a:45,unit:"km",hint:"Beide liegen am Rhein in NRW.",emoji:"🌊"},
  {q:"Wie viele km² ist die Lüneburger Heide groß?",a:7400,unit:"km²",hint:"Größtes Naturschutzgebiet Norddeutschlands.",emoji:"🌿"},
  {q:"Wie hoch ist der Grossglockner in Österreich in Metern?",a:3798,unit:"Meter",hint:"Höchster Berg Österreichs.",emoji:"🏔️"},
  {q:"Wie viele Einwohner hat Wien?",a:2000000,unit:"Einwohner",hint:"Die Hauptstadt Österreichs.",emoji:"🎵"},
  {q:"Wie lang ist der Bodensee in km?",a:63,unit:"km",hint:"Von Bregenz bis Konstanz.",emoji:"💧"},
  {q:"Wie viele km² ist die Nordseeküste Deutschlands lang?",a:450,unit:"km",hint:"Von der dänischen Grenze bis zur Elbmündung.",emoji:"🌊"},
  {q:"Wie hoch ist der Schwarzwald-Gipfel Belchen in Metern?",a:1414,unit:"Meter",hint:"Einer der schönsten Aussichtsgipfel.",emoji:"🏔️"},
  {q:"Wie viele Einwohner hat Hamburg?",a:1800000,unit:"Einwohner",hint:"Die zweitgrößte Stadt Deutschlands.",emoji:"⚓"},
  {q:"Wie lang ist die Küstenlinie der Ostsee (Deutschland) in km?",a:354,unit:"km",hint:"Von Flensburg bis zur Oderbucht.",emoji:"🌊"},
  {q:"Wie weit ist München von Wien in km Luftlinie?",a:357,unit:"km",hint:"Zwei der schönsten deutschsprachigen Städte.",emoji:"🏙️"},
  {q:"Wie hoch ist der Piz Bernina in der Schweiz in Metern?",a:4049,unit:"Meter",hint:"Der östlichste Viertausender der Alpen.",emoji:"🏔️"},
  {q:"Wie viele Einwohner hat Zürich?",a:400000,unit:"Einwohner",hint:"Die größte Stadt der Schweiz.",emoji:"🇨🇭"},
  {q:"Wie lang ist die Grenze Deutschlands insgesamt in km?",a:3757,unit:"km",hint:"9 Nachbarländer.",emoji:"🇩🇪"},
  {q:"Wie hoch ist der Dachstein in Österreich in Metern?",a:2995,unit:"Meter",hint:"Mit Gletscher und Hängebrücke.",emoji:"🏔️"},
  {q:"Wie viele km² ist die Côte d'Azur lang?",a:180,unit:"km",hint:"Von Saint-Tropez bis Menton.",emoji:"🌊"},
  {q:"Wie viele Einwohner hat Berlin?",a:3700000,unit:"Einwohner",hint:"Die Hauptstadt und größte Stadt Deutschlands.",emoji:"🇩🇪"},
  {q:"Wie lang ist die Strecke Berlin-Paris in km?",a:1050,unit:"km",hint:"Mit dem Zug etwa 8 Stunden.",emoji:"🚂"},
  {q:"Wie hoch ist der Teide auf Teneriffa in Metern?",a:3718,unit:"Meter",hint:"Der höchste Berg Spaniens.",emoji:"🌋"},
  {q:"Wie viele km² ist die Toskana in Italien groß?",a:22987,unit:"km²",hint:"Berühmt für Wein und Kunst.",emoji:"🍷"},
  {q:"Wie weit ist Deutschland von Australien entfernt in km?",a:16000,unit:"km",hint:"Auf der anderen Seite der Erde.",emoji:"🌏"},
  {q:"Wie viele km² ist Frankreich groß?",a:551695,unit:"km²",hint:"Das größte Land Westeuropas.",emoji:"🇫🇷"},
  {q:"Wie lang ist die Loire in Frankreich in km?",a:1013,unit:"km",hint:"Der längste Fluss Frankreichs.",emoji:"🌊"},
  {q:"Wie hoch ist der Matterhorn in der Schweiz in Metern?",a:4478,unit:"Meter",hint:"Das Wahrzeichen der Alpen.",emoji:"🏔️"},
  {q:"Wie viele Einwohner hat Paris?",a:2200000,unit:"Einwohner",hint:"Die Stadt der Liebe.",emoji:"🗼"},
  {q:"Wie lang ist die Themse in Großbritannien in km?",a:346,unit:"km",hint:"Fließt durch London.",emoji:"🌊"},
  {q:"Wie viele km² ist Spanien groß?",a:505990,unit:"km²",hint:"Das zweitgrößte Land Westeuropas.",emoji:"🇪🇸"},
  {q:"Wie hoch ist der Nanga Parbat in Pakistan in Metern?",a:8126,unit:"Meter",hint:"Der neunte höchste Berg der Welt.",emoji:"🏔️"},
  {q:"Wie viele km² ist Italien groß?",a:301340,unit:"km²",hint:"Die Form des Stiefels.",emoji:"🇮🇹"},
  {q:"Wie lang ist der Po in Italien in km?",a:652,unit:"km",hint:"Der längste Fluss Italiens.",emoji:"🌊"},
  {q:"Wie hoch ist der Vesuv bei Neapel in Metern?",a:1281,unit:"Meter",hint:"Er zerstörte Pompeji im Jahr 79 n.Chr.",emoji:"🌋"},
  {q:"Wie viele Einwohner hat Rom?",a:2800000,unit:"Einwohner",hint:"Die ewige Stadt.",emoji:"🏛️"},
  {q:"Wie lang ist der Ebro in Spanien in km?",a:930,unit:"km",hint:"Der wasserreichste Fluss Spaniens.",emoji:"🌊"},
  {q:"Wie hoch ist der Pico de Orizaba in Mexiko in Metern?",a:5636,unit:"Meter",hint:"Der höchste Berg Mexikos.",emoji:"🏔️"},
  {q:"Wie viele km² ist Mexiko groß?",a:1964375,unit:"km²",hint:"Das drittgrößte Land Lateinamerikas.",emoji:"🌵"},
  {q:"Wie lang ist der Jangtse-Fluss in China in km?",a:6300,unit:"km",hint:"Der längste Fluss Asiens.",emoji:"🌊"},
  {q:"Wie hoch ist der K2 in Pakistan in Metern?",a:8611,unit:"Meter",hint:"Der zweithöchste Berg der Welt.",emoji:"🏔️"},
  {q:"Wie viele km² ist China groß?",a:9596960,unit:"km²",hint:"Das viertgrößte Land der Welt.",emoji:"🇨🇳"},
  {q:"Wie lang ist der Huang He (Gelber Fluss) in China in km?",a:5464,unit:"km",hint:"Die Wiege der chinesischen Zivilisation.",emoji:"🌊"},
  {q:"Wie hoch ist der Fuji-San in Japan genau in Metern?",a:3776,unit:"Meter",hint:"Symbol Japans.",emoji:"🗻"},
  {q:"Wie viele km² ist Japan groß?",a:377975,unit:"km²",hint:"Ein Inselstaat im Pazifik.",emoji:"🇯🇵"},
  {q:"Wie viele Einwohner hat Tokio genau in Millionen?",a:37,unit:"Millionen",hint:"Größte Stadtregion der Welt.",emoji:"🗼"},
  {q:"Wie lang ist der Mekong in km?",a:4350,unit:"km",hint:"Fließt durch 6 Länder Südostasiens.",emoji:"🌊"},
  {q:"Wie hoch ist der Kilimandscharos zweithöchster Gipfel Mawenzi in Metern?",a:5149,unit:"Meter",hint:"Der zweite Gipfel des Kilimandscharo.",emoji:"🏔️"},
  {q:"Wie viele km² ist die USA groß?",a:9833517,unit:"km²",hint:"Das drittgrößte Land der Welt.",emoji:"🇺🇸"},
  {q:"Wie lang ist der Missouri in km?",a:3767,unit:"km",hint:"Längster Fluss in den USA.",emoji:"🌊"},
  {q:"Wie hoch ist der Denali in Alaska in Metern?",a:6190,unit:"Meter",hint:"Der höchste Berg Nordamerikas.",emoji:"🏔️"},
  {q:"Wie viele Einwohner hat New York City in Millionen?",a:8.3,unit:"Millionen",hint:"Die größte Stadt der USA.",emoji:"🗽"},
  {q:"Wie lang ist der Colorado River in km?",a:2334,unit:"km",hint:"Er schuf den Grand Canyon.",emoji:"🌊"},
  {q:"Wie viele km² ist Argentinien groß?",a:2780400,unit:"km²",hint:"Das achtgrößte Land der Welt.",emoji:"🇦🇷"},
  {q:"Wie hoch sind die Iguazu-Wasserfälle in Metern?",a:82,unit:"Meter",hint:"Breiter als die Niagarafälle.",emoji:"🌊"},
  {q:"Wie viele km lang ist der Nil vom See Victoria bis zur Mündung?",a:5584,unit:"km",hint:"Je nach Messung der längste Fluss.",emoji:"🌊"},
  {q:"Wie hoch ist der Tafelberg in Südafrika in Metern?",a:1086,unit:"Meter",hint:"Wahrzeichen Kapstadts.",emoji:"🏔️"},
  {q:"Wie viele km² ist die Demokratische Republik Kongo groß?",a:2344858,unit:"km²",hint:"Das zweitgrößte Land Afrikas.",emoji:"🌿"},
  {q:"Wie lang ist der Sambesi in km?",a:2574,unit:"km",hint:"An ihm liegen die Victoriafälle.",emoji:"🌊"},
  {q:"Wie hoch sind die Victoriafälle in Simbabwe in Metern?",a:108,unit:"Meter",hint:"Größte Wasserfälle der Welt nach Breite.",emoji:"🌊"},
  {q:"Wie viele km² ist Ägypten groß?",a:1001449,unit:"km²",hint:"95% davon ist Wüste.",emoji:"🏜️"},
  {q:"Wie lang ist der Sambesi von der Quelle bis zur Mündung in km?",a:2574,unit:"km",hint:"Fließt von Sambia bis Mosambik.",emoji:"🌊"}
,
  {q:"Wie lang ist der Amazonas-Fluss in km?",a:6400,unit:"km",hint:"Einer der längsten Flüsse der Welt.",emoji:"🌿"},
  {q:"Wie viele Einwohner hat Tokio?",a:14000000,unit:"Einwohner",hint:"Eine der größten Städte der Welt.",emoji:"🏙️"},
  {q:"Wie viele km² hat Australien?",a:7700000,unit:"km²",hint:"Der sechstgrößte Staat der Erde.",emoji:"🦘"},
  {q:"Wie viele Länder hat Afrika?",a:54,unit:"Länder",hint:"Der Kontinent mit den meisten Ländern.",emoji:"🌍"},
  {q:"Wie hoch ist der Fujiyama in Japan?",a:3776,unit:"Meter",hint:"Japans heiliger Vulkan.",emoji:"🗻"},
  {q:"Wie groß ist die Sahara in km²?",a:9200000,unit:"km²",hint:"Die größte Wüste der Welt.",emoji:"🏜️"},
  {q:"Wie viele km² hat Brasilien?",a:8500000,unit:"km²",hint:"Größtes Land Südamerikas.",emoji:"🇧🇷"},
  {q:"Wie lang ist der Mississippif luss in km?",a:3730,unit:"km",hint:"Der große Strom Nordamerikas.",emoji:"🌊"},
  {q:"Wie viele Einwohner hat Mumbai?",a:20000000,unit:"Einwohner",hint:"Die größte Stadt Indiens.",emoji:"🏙️"},
  {q:"Wie hoch ist der Aconcagua in Argentinien?",a:6961,unit:"Meter",hint:"Höchster Berg Amerikas.",emoji:"🏔️"},
  {q:"Wie lang ist der Ganges in km?",a:2525,unit:"km",hint:"Heiliger Fluss Indiens.",emoji:"🌊"},
  {q:"Wie viele km² hat Saudi-Arabien?",a:2150000,unit:"km²",hint:"Das größte Land Westasiens.",emoji:"🇸🇦"},
  {q:"Wie tief ist der Vierwaldstättersee in Metern?",a:214,unit:"Meter",hint:"In der Schweiz – Herzstück der Eidgenossenschaft.",emoji:"💧"},
  {q:"Wie viele Länder grenzen an Frankreich?",a:8,unit:"Länder",hint:"Spanien, Andorra, Monaco, Italien, Schweiz, Deutschland, Luxemburg, Belgien.",emoji:"🇫🇷"},
  {q:"Wie hoch ist der Olymp in Griechenland?",a:2917,unit:"Meter",hint:"Berg der griechischen Götter.",emoji:"⛰️"},
  {q:"Wie lang ist der Rhein von der Quelle bis zur Mündung?",a:1230,unit:"km",hint:"Von den Alpen bis zur Nordsee.",emoji:"🌊"},
  {q:"Wie hoch liegt Machu Picchu in Metern?",a:2430,unit:"Meter",hint:"Die Stadt der Inka in Peru.",emoji:"🏛️"},
  {q:"Wie viele km² hat Indien?",a:3290000,unit:"km²",hint:"Das siebtgrößte Land der Welt.",emoji:"🇮🇳"},
  {q:"Wie viele Einwohner hat Mexiko-Stadt?",a:22000000,unit:"Einwohner",hint:"Eine der größten Städte Amerikas.",emoji:"🏙️"},
  {q:"Wie lang ist der Donaufluss in km?",a:2860,unit:"km",hint:"Fließt durch 10 Länder.",emoji:"🌊"},
  {q:"Wie tief ist das Tote Meer in Metern unter dem Meeresspiegel?",a:430,unit:"Meter",hint:"Der tiefste Punkt der Erdoberfläche.",emoji:"🌊"},
  {q:"Wie viele km² hat die Mongolei?",a:1564000,unit:"km²",hint:"Größtes Binnenland der Welt.",emoji:"🏕️"},
  {q:"Wie lang ist die Oder in km?",a:866,unit:"km",hint:"Grenzfluss zwischen Deutschland und Polen.",emoji:"🌊"},
  {q:"Wie hoch ist der Mont Blanc ohne Schneegipfel?",a:4810,unit:"Meter",hint:"Höchster Berg der Alpen.",emoji:"🏔️"},
  {q:"Wie viele km² hat Schweden?",a:450000,unit:"km²",hint:"Das größte skandinavische Land.",emoji:"🇸🇪"},
  {q:"Wie viele Einwohner hat Sao Paulo?",a:21000000,unit:"Einwohner",hint:"Die größte Stadt Südamerikas.",emoji:"🏙️"},
  {q:"Wie lang ist der Lena-Fluss in Russland?",a:4400,unit:"km",hint:"Einer der längsten Flüsse Sibiriens.",emoji:"🌊"},
  {q:"Wie tief ist der Bodensee in Metern?",a:251,unit:"Meter",hint:"Dreiländersee: Deutschland, Österreich, Schweiz.",emoji:"💧"},
  {q:"Wie viele km² hat die Ukraine?",a:603000,unit:"km²",hint:"Das flächengrößte europäische Land (ohne Russland).",emoji:"🇺🇦"},
  {q:"Wie viele Länder hat Ozeanien?",a:14,unit:"Länder",hint:"Australien, Neuseeland und zwölf Inselstaaten.",emoji:"🏝️"},
  {q:"Wie viele km² hat Spanien?",a:506000,unit:"km²",hint:"Zweitgrößtes Land der EU.",emoji:"🇪🇸"},
  {q:"Wie tief ist der Lago Maggiore in Metern?",a:372,unit:"Meter",hint:"Zwischen Italien und der Schweiz.",emoji:"💧"},
  {q:"Wie viele Einwohner hat Kairo?",a:20000000,unit:"Einwohner",hint:"Größte Stadt Afrikas.",emoji:"🏙️"},
  {q:"Wie lang ist der Tigris in km?",a:1900,unit:"km",hint:"Mesopotamien – Wiege der Zivilisation.",emoji:"🌊"},
  {q:"Wie viele km² hat Polen?",a:313000,unit:"km²",hint:"Das neuntgrößte Land Europas.",emoji:"🇵🇱"},
  {q:"Wie lang ist der Main in km?",a:525,unit:"km",hint:"Wichtigster rechter Nebenfluss des Rheins.",emoji:"🌊"},
  {q:"Wie tief ist der Lago di Garda in Metern?",a:346,unit:"Meter",hint:"Größter See Italiens.",emoji:"💧"},
  {q:"Wie viele Einwohner hat New York City?",a:8000000,unit:"Einwohner",hint:"Die größte Stadt der USA.",emoji:"🗽"},
  {q:"Wie hoch ist der Etna auf Sizilien?",a:3357,unit:"Meter",hint:"Aktivster Vulkan Europas.",emoji:"🌋"},
  {q:"Wie lang ist der Euphrat in km?",a:2800,unit:"km",hint:"Zusammen mit dem Tigris Wiege der Zivilisation.",emoji:"🌊"},
  {q:"Wie viele km² hat Norwegen?",a:385000,unit:"km²",hint:"Land der Fjorde.",emoji:"🇳🇴"},
  {q:"Wie tief ist der Traunsee in Österreich?",a:191,unit:"Meter",hint:"Tiefster See Österreichs.",emoji:"💧"},
  {q:"Wie viele Einwohner hat Los Angeles?",a:4000000,unit:"Einwohner",hint:"Stadt der Engel.",emoji:"🌴"},
  {q:"Wie hoch ist der Großglockner in Österreich?",a:3798,unit:"Meter",hint:"Höchster Berg Österreichs.",emoji:"🏔️"},
  {q:"Wie viele km² hat Finnland?",a:338000,unit:"km²",hint:"Das Land der tausend Seen.",emoji:"🇫🇮"},
  {q:"Wie viele Seen hat Finnland?",a:188000,unit:"Seen",hint:"Über 180.000 Seen – das meiste Wasser Europas.",emoji:"💧"},
  {q:"Wie lang ist der Kongof luss in km?",a:4700,unit:"km",hint:"Zweitlängster Fluss Afrikas.",emoji:"🌊"},
  {q:"Wie hoch ist der Kilimanjaro in Tansania?",a:5895,unit:"Meter",hint:"Höchster Berg Afrikas.",emoji:"🏔️"},
  {q:"Wie tief ist der Plattensee in Ungarn?",a:12,unit:"Meter",hint:"Größter Süßwassersee Mitteleuropas.",emoji:"💧"},
  {q:"Wie viele Inseln hat Schweden?",a:220000,unit:"Inseln",hint:"Über 200.000 Inseln in der Küste.",emoji:"🏝️"},
  {q:"Wie lang ist der Kongo-Fluss in km?",a:4700,unit:"km",hint:"Tiefster Fluss der Welt.",emoji:"🌊"},
  {q:"Wie hoch ist der Montserrat in Spanien?",a:1236,unit:"Meter",hint:"Heiliger Berg Kataloniens.",emoji:"⛰️"},
  {q:"Wie viele km² hat Portugal?",a:92000,unit:"km²",hint:"Das westlichste Land Europas.",emoji:"🇵🇹"},
  {q:"Wie viele km lang ist die Küstenlinie Deutschlands?",a:2389,unit:"km",hint:"Nord- und Ostseeküste zusammen.",emoji:"🌊"},
  {q:"Wie hoch liegt Wien über dem Meeresspiegel?",a:171,unit:"Meter",hint:"Hauptstadt Österreichs.",emoji:"🏙️"},
  {q:"Wie groß ist die Nordsee in km²?",a:570000,unit:"km²",hint:"Zwischen Großbritannien und dem Festland.",emoji:"🌊"},
];
