export default [
  {id:"maer_001",q:"Wie viele Zwerge hat Schneewittchen?",a:7,unit:"Zwerge",hint:"Hatschi, Schläfer, Brummbär, Happy, Bashful, Grumpy, Doc.",emoji:"⛏️"},
  {id:"maer_002",q:"Wie viele Jahre schlief Dornröschen?",a:100,unit:"Jahre",hint:"100 Jahre – bis ein Prinz sie weckte.",emoji:"💤"},
  {id:"maer_003",q:"Wie viele Wünsche gewährt der Flaschengeist in Aladdin?",a:3,unit:"Wünsche",hint:"3 Wünsche – Aladdin nutzt sie weise.",emoji:"🧞"},
  {id:"maer_004",q:"Wie viele Stiefschwestern hat Aschenputtel?",a:2,unit:"Stiefschwestern",hint:"Zwei böse Stiefschwestern und eine böse Stiefmutter.",emoji:"👠"},
  {id:"maer_005",q:"Wie viele Schwestern hat Ariel (die kleine Meerjungfrau)?",a:6,unit:"Schwestern",hint:"6 Schwestern – Ariel ist die siebte.",emoji:"🧜"},
  {id:"maer_006",q:"Wie viele Geißlein hat die Mutter der sieben Geißlein?",a:7,unit:"Geißlein",hint:"7 Geißlein – eines versteckt sich im Uhrkasten.",emoji:"🐐"},
  {id:"maer_007",q:"Wie viele Fliegen erschlägt das tapfere Schneiderlein auf einmal?",a:7,unit:"Fliegen",hint:"Sieben auf einen Streich – deshalb schreibt er es auf den Gürtel.",emoji:"🪰"},
  {id:"maer_008",q:"Wie viele Male versucht die böse Königin Schneewittchen zu töten?",a:3,unit:"Versuche",hint:"Korsett, Kamm und vergifteter Apfel.",emoji:"🍎"},
  {id:"maer_009",q:"Wie viele Pferde zieht die Kutsche von Aschenputtel?",a:6,unit:"Pferde",hint:"6 weiße Pferde – aus 6 Eidechsen.",emoji:"🐎"},
  {id:"maer_010",q:"Wie viele goldene Eier legt die Gans pro Tag?",a:1,unit:"Ei",hint:"Ein goldenes Ei täglich – bis der Bauer die Gans schlachtet.",emoji:"🥚"},
  {id:"maer_011",q:"Wie viele Erbsen spürt die echte Prinzessin?",a:1,unit:"Erbse",hint:"Eine einzige Erbse unter 20 Matratzen.",emoji:"👸"},
  {id:"maer_012",q:"Wie viele Matratzen liegen auf der Erbse?",a:20,unit:"Matratzen",hint:"20 Matratzen und 20 Federbetten – sie spürte es trotzdem.",emoji:"🛏️"},
  {id:"maer_013",q:"Wie viele Brüder werden in 'Die zwölf Brüder' in Raben verwandelt?",a:12,unit:"Brüder",hint:"12 Brüder – die Schwester muss 12 Jahre schweigen.",emoji:"🐦"},
  {id:"maer_014",q:"Wie viele Kinder lockt der Rattenfänger von Hameln weg?",a:130,unit:"Kinder",hint:"130 Kinder folgten dem Rattenfänger – nie wiedergefunden.",emoji:"🐀"},
  {id:"maer_015",q:"Wie viele Aufgaben löst das tapfere Schneiderlein?",a:3,unit:"Aufgaben",hint:"3 unmögliche Aufgaben – er besteht alle mit List.",emoji:"✂️"},
  {id:"maer_016",q:"Wie viele Sterne fallen in 'Sterntaler'?",a:7,unit:"Sterne",hint:"7 Sterne fielen als Geldstücke – das Kind wurde reich.",emoji:"⭐"},
  {id:"maer_017",q:"Wie viele Kleider bekommt Aschenputtel vom Baum?",a:3,unit:"Kleider",hint:"Silber, Gold und das schönste Kleid für den Ball.",emoji:"👗"},
  {id:"maer_018",q:"Wie viele Tage hat Rumpelstilzchen um seinen Namen zu erraten?",a:3,unit:"Tage",hint:"3 Tage hat die Müllerstochter um seinen Namen zu erraten.",emoji:"🧵"},
  {id:"maer_019",q:"Wie viele Nächte dreht Rumpelstilzchen Stroh zu Gold?",a:3,unit:"Nächte",hint:"3 Nächte – dafür verlangt er Ring, Halsband und das Kind.",emoji:"🌙"},
  {id:"maer_020",q:"Wie viele Schwäne rettet die Schwester in 'Die sechs Schwäne'?",a:6,unit:"Brüder",hint:"6 Brüder wurden in Schwäne verwandelt.",emoji:"🦢"},
  {id:"maer_021",q:"Wie viele Aufgaben bekommt Aschenputtel von der Stiefmutter?",a:3,unit:"Aufgaben",hint:"Linsen lesen, Herd kehren und mehr.",emoji:"⭐"},
  {id:"maer_022",q:"Wie viele Jahre reist Sindbad der Seefahrer?",a:7,unit:"Reisen",hint:"7 Seefahrten – jede bringt neue Abenteuer.",emoji:"⛵"},
  {id:"maer_023",q:"Wie viele Gebrüder Grimm sammelten Märchen?",a:2,unit:"Brüder",hint:"Jacob und Wilhelm Grimm – das berühmteste Brüderpaar.",emoji:"📖"},
  {id:"maer_024",q:"Wie viele Märchen sammelten die Gebrüder Grimm insgesamt?",a:211,unit:"Märchen",hint:"211 Märchen in der Gesamtausgabe.",emoji:"📚"},
  {id:"maer_025",q:"Wie viele Tiere helfen Aschenputtel beim Linsenlesen?",a:2,unit:"Taubenarten",hint:"Weiße und bunte Täubchen helfen ihr bei der unmöglichen Aufgabe.",emoji:"🕊️"},
  {id:"maer_026",q:"Wie viele Kinder hat Hänsel und Gretel (Familie)?",a:2,unit:"Kinder",hint:"Zwei Kinder – Hänsel und Gretel.",emoji:"🌲"},
  {id:"maer_027",q:"Wie viele Meter hoch ist Rapunzels Turm?",a:20,unit:"Meter",hint:"Hoch genug dass das Haar als Leiter dient.",emoji:"🏰"},
  {id:"maer_028",q:"Wie viele Aufgaben bekommt Marie in 'Frau Holle'?",a:2,unit:"Prüfungen",hint:"Fleiß oder Faulheit – die fleißige Marie besteht.",emoji:"❄️"},
  {id:"maer_029",q:"Wie viele Haare hat das Goldkind vom Teufel?",a:3,unit:"Haare",hint:"3 goldene Haare – jedes enthüllt ein Geheimnis.",emoji:"✨"},
  {id:"maer_030",q:"Wie viele goldene Haare hat das Goldkind?",a:3,unit:"Haare",hint:"3 goldene Haare vom Teufel.",emoji:"✨"},
  {id:"maer_031",q:"Wie viele Riesen bekämpft Jack (Jack und der Bohnenstängel)?",a:1,unit:"Riesen",hint:"Jack bekämpft einen Riesen – 'Fe-fi-fo-fum!'",emoji:"⚡"},
  {id:"maer_032",q:"Wie viele Bohnen pflanzt Jack in 'Jack und der Bohnenstängel'?",a:5,unit:"Bohnen",hint:"5 magische Bohnen – sie wachsen bis in den Himmel.",emoji:"🌱"},
  {id:"maer_033",q:"Wie viele Schwestern schickt die böse Stiefmutter zum Tanzen?",a:2,unit:"Schwestern",hint:"Die beiden bösen Stiefschwestern – mit gebundenen Füßen.",emoji:"💃"},
  {id:"maer_034",q:"Wie viele Stunden dauert der Ball bei Aschenputtel?",a:3,unit:"Stunden",hint:"Der Ball geht bis Mitternacht – Asche muss vorher weg.",emoji:"🕛"},
  {id:"maer_035",q:"Wie viele Zähne hat der böse Wolf in Rotkäppchen?",a:32,unit:"Zähne",hint:"Was für große Zähne – 'damit ich dich besser fressen kann!'",emoji:"🐺"},
  {id:"maer_036",q:"Wie viele Jahreszeiten gibt es in Hans Christian Andersens Märchen?",a:4,unit:"Jahreszeiten",hint:"Frühling, Sommer, Herbst, Winter – Grundlage vieler Märchen.",emoji:"🌸"},
  {id:"maer_037",q:"Wie viele Häuser bauen die drei kleinen Schweinchen?",a:3,unit:"Häuser",hint:"Stroh, Holz, Stein – nur das Steinhaus hält dem Wolf stand.",emoji:"🏠"},
  {id:"maer_038",q:"Wie viele Male pustet der Wolf in 'Die drei kleinen Schweinchen'?",a:3,unit:"Male",hint:"Er pustet 3 Häuser – nur das Steinhaus bleibt stehen.",emoji:"💨"},
  {id:"maer_039",q:"Wie viele Bären wohnen bei Goldlöckchen?",a:3,unit:"Bären",hint:"Vater, Mutter und kleiner Bär – Goldlöckchen probiert alles.",emoji:"🐻"},
  {id:"maer_040",q:"Wie viele Schüsseln Brei isst Goldlöckchen?",a:1,unit:"Schüssel",hint:"Nur die Schüssel vom kleinen Bären – gerade richtig.",emoji:"🥣"},
  {id:"maer_041",q:"Wie viele Nüsse enthält Aschenputtels goldene Nuss?",a:1,unit:"Kleid",hint:"In jeder goldenen Nuss steckt ein wunderschönes Kleid.",emoji:"🌰"},
  {id:"maer_042",q:"Wie viele km muss Hänsel und Gretel durch den Wald gehen?",a:3,unit:"Tage",hint:"3 Tage Wanderung – tief in den dunklen Wald.",emoji:"🌲"},
  {id:"maer_043",q:"Wie viele Tage wanderte der Prinz in Dornröschen um das Schloss?",a:1,unit:"Tag",hint:"Er fand das Schloss sofort – die Dornen wichen von selbst zurück.",emoji:"🌹"},
  {id:"maer_044",q:"Wie viele Märchen schrieb Hans Christian Andersen?",a:156,unit:"Märchen",hint:"156 Märchen – darunter 'Die kleine Meerjungfrau' und 'Der Däumling'.",emoji:"📖"},
  {id:"maer_045",q:"Wie viele Jahre lebte die Schneekönigin in ihrem Eispalast?",a:100,unit:"Jahre",hint:"Die Schneekönigin herrscht seit Ewigkeiten über ihr Eisreich.",emoji:"❄️"},
  {id:"maer_046",q:"Wie viele Paar Eisenschuhe tanzt das Mädchen in 'Die roten Schuhe'?",a:1,unit:"Paar",hint:"Ein verhextes Paar roter Schuhe – es hört nie auf zu tanzen.",emoji:"👠"},
  {id:"maer_047",q:"Wie viele Monate dauert der Schlaf in 'Dornröschen'?",a:1200,unit:"Monate",hint:"100 Jahre = 1.200 Monate Schlaf.",emoji:"💤"},
  {id:"maer_048",q:"Wie viele Kinder versucht die Hexe in Hänsel und Gretel aufzufressen?",a:2,unit:"Kinder",hint:"Hänsel und Gretel – sie werden clever gerettet.",emoji:"🏠"},
  {id:"maer_049",q:"Wie viele Stiefel braucht der gestiefelte Kater?",a:1,unit:"Paar",hint:"Nur ein Paar Stiefel – damit beginnt sein Aufstieg.",emoji:"😺"},
  {id:"maer_050",q:"Wie viele Male lügt Pinocchio (bevor seine Nase sehr lang wird)?",a:3,unit:"Male",hint:"Dreimal lügen bis die Nase richtig lang wird.",emoji:"🪵"},
];
